### ISSUE TITLE
[2.0.0] element getFilters() return null value in array

### ISSUE THREAD

**Issue by arius86** [phalcon/cphalcon#10009]
Let's assume that I have form like this:

````
namespace Vegas\Tests\Stub\Models;

use \Vegas\Forms\Form,
    \Phalcon\Forms\Element\Text,
    \Vegas\Validation\Validator\PresenceOf;

class FakeVegasForm extends Form
{
    public function initialize()
    {
        $field = new Text('fake_field');
        $field->addValidator(new PresenceOf());
        $this->add($field);
    }
}
````
Calling var_dump($fakeVegasForm->get('fake_field')->getFilters()) will return NULL what is correct.
But after adding filter: $fakeVegasForm->get('fake_field')->addFilter('foo'), calling var_dump($this->form->get('fake_field')->getFilters()) will return:

````
[
  0 => NULL,
  1 => "foo"
]
````
NULL value should not be there.

**Comment by andresgutierrez** [comment]
This is fixed in latest commit, thanks
