### ISSUE TITLE
[2.0.0] Why removed docblock from Zephir code?

### ISSUE THREAD

**Issue by KorsaR-ZN** [phalcon/cphalcon#10012]
@phalcon 
Why removed docblock from Zephir code?
This is convenient for the automatic generation of documentation...

See #10011, #9990, #9989, etc...

**Comment by ovr** [comment]
Run `zephir stubs`. It works without it

**Comment by KorsaR-ZN** [comment]
@ovr Thanks! 
I didn't know about this feature Zephir :)

**Comment by ovr** [comment]
@KorsaR-ZN 
Not a problem :smile_cat: 
Dont forget to close this issue ;)
