### ISSUE TITLE
Catchable fatal error: Object of class Multiple\Backend\Models\urunler could not be converted to string  in /var/www/apps/backend/controllers/UrunController.php on line

### ISSUE THREAD

**Issue by emrullahayin** [phalcon/cphalcon#10033]
UrunController.php

public function kontrolAction(){
			$kk = new urunler();
			$kk->kodkontrol($this->request->getPost());
			echo $kk;
		}

urunler.php

public function kodkontrol(){
		while(1){
			$UrunKodu = chr(rand(65,90)).chr(rand(65,90)).'-'.rand(1,9999);
			$UKKontrol = $this->findFirst("urunBarkod = '{$UrunKodu}'");
			if($UKKontrol > 0){
				continue;
			} else{
				break;
			}
		}
		
		echo $UrunKodu;
	}

**Comment by andresgutierrez** [comment]
You can't 'echo' an object: echo $kk; if you want to check the attributes you can use print_r($kk->dump());

**Comment by emrullahayin** [comment]
thank you
