### ISSUE TITLE
Warning using translate function

### ISSUE THREAD

**Issue by pablomoreno61** [phalcon/cphalcon#10055]
Hi,

There is a warning when using translate service:
In my Bootstrap:

        $this->di->set('translate', function () use ($config) {
            $translate = new Gettext(array(
                'locale' => 'es_ES',
                'defaultDomain' => 'messages',
                'directory' => PROJECT_PATH . $config->application->langDir));

            return $translate;
        });

In my View:
{{ translate.t('Últimas campañas') }}

And in my view I get the following message:
Warning: func_get_arg(): Argument 2 not passed to function in /var/www/consupermiso2-frontend/cache/volt_var_www_frontend_apps_modules_frontend_views_reward_summary.phtml.php on line 1

I'm already using Volt template engine in my views.

**Comment by andresgutierrez** [comment]
What version of Phalcon are you using?

**Comment by pablomoreno61** [comment]
Hi!

I'm using the master version from 14 of April, based on Phalcon 2.0.0

2015-04-20 0:09 GMT+02:00 Andres Gutierrez <notifications@github.com>:

**Comment by KorsaR-ZN** [comment]
@pablomoreno61 
It fixes #10088

**Comment by Green-Cat** [comment]
@andresgutierrez Fixed in #10088
