### ISSUE TITLE
Release 2.0.0 tag on GitHub and Packagist

### ISSUE THREAD

**Issue by ovr** [phalcon/cphalcon#10066]

**Comment by andresgutierrez** [comment]
Fixed

**Comment by ovr** [comment]
@andresgutierrez 
 phalcon-v2.0.0 -> 2.0.0

**Comment by ovr** [comment]
https://packagist.org/packages/phalcon/cphalcon
Via phalcon-v2.0.0 - version is not supported

**Comment by KorsaR-ZN** [comment]
:+1: 
see - http://semver.org/

**Comment by ovr** [comment]
v2.0.0

@andresgutierrez 
v is not needed
