### ISSUE TITLE
[2.0.0] Error implementing Phalcon Multi Module Application: ModuleDefinitionInterface

### ISSUE THREAD

**Issue by hiubers** [phalcon/cphalcon#10060]
When i try to migrate my phalcon application from v1.3.4 to v2.0.0 i got this error message

Fatal error: Declaration of Redist\Backend\Module::registerAutoloaders() must be compatible with Phalcon\Mvc\ModuleDefinitionInterface::registerAutoloaders(Phalcon\DiInterface $dependencyInjector = NULL) in C:\wamp\www\redist\app\modules\backend\Module.php on line 17

But when i check the phalcon v2.0.0 documentation the implementation of the ModuleDefinitionInterface is the same in previous versions.

below my interface implementation, this code works well in phalcon V1.3.4 on windows 7 with wamp server.

class Module implements ModuleDefinitionInterface
{
	/**
	* Registers the module auto-loader
	*/
	public function registerAutoloaders()
	{
		$loader = new Loader();
		$loader->registerNamespaces(
			array(
				'Redist\Backend\Controllers' => __DIR__ . '/controllers/',
				'Redist\Backend\Library' => __DIR__ . '/library/',
				'Redist\Models' => __DIR__ . '/../../models/'
			));
		$loader->register();
	}

	/**
	* Registers the module-only services
	*
	* @param Phalcon\DI $di
	*/
	public function registerServices($di)
	{
		/**
		 * Read configuration
		 */
		$config = include __DIR__ . "/config/config.php";

		$di['dispatcher'] = function() use($config)	{
			//$eventsManager = new EventsManager;
			//$eventsManager->attach('dispatch:beforeException', new ExceptionNotFound);
			$dispatcher = new Dispatcher();
			//$dispatcher->setEventsManager($eventsManager);
			$dispatcher->setDefaultNamespace($config->application->defaultNamespace);
			return $dispatcher;
		};
}

**Comment by andresgutierrez** [comment]
Phalcon 2 now validates parameters in the implemented interfaces, you have to change it to:

```php
public function registerServices(\Phalcon\DiInterface $di)
````
This is mentioned in the upgrading guide: http://blog.phalconphp.com/post/115773676765/guide-upgrading-to-phalcon-2

**Comment by hiubers** [comment]
Thanks, Andres i really appreciate your excelent work!
Best regards

2015-04-17 15:24 GMT-04:30 Andres Gutierrez <notifications@github.com>:

> Phalcon 2 now validates parameters in the implemented interfaces, you have
> to change it to:
>
> public function registerServices(\Phalcon\DiInterface $di)
>
> This is mentioned in the upgrading guide:
> http://blog.phalconphp.com/post/115773676765/guide-upgrading-to-phalcon-2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phalcon/cphalcon/issues/10060#issuecomment-94062183>.
>



-- 
Hiuber Sánchez

**Comment by sergeyklay** [comment]
@hiubers Issue can be closed?
