### ISSUE TITLE
[2.0.0] QueryBuilder (DISTINCT) not working.

### ISSUE THREAD

**Issue by ohmcoe** [phalcon/cphalcon#10064]
This work in 1.3.4 but not work in 2.0.0
```
$builder = $this->modelsManager->createBuilder();
$builder->from("robot");
$builder->distinct("id");
echo $builder->getPhql());
```

Result in 1.3.4
```
SELECT DISTINCT [robot].* FROM [robot]
```

Result in 2.0.0
```
SELECT [robot].* FROM [robot]
```

Testing env.
OS Debian 7.8 wheezy
PHP 5.4.39-0+deb7u2
GCC 4.7.2
Phalcon 2.0.0 build from source in github (master)

**Comment by dugwood** [comment]
distinct is a boolean:
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model/query/builder.zep#L263

The only bug with distinct in 2.0 is this one:
https://github.com/phalcon/cphalcon/issues/9985

**Comment by ohmcoe** [comment]
Thank for answer I have issue same #9985

**Comment by dugwood** [comment]
If so, please close this bug report (as «duplicate»). Thanks.

**Comment by ohmcoe** [comment]
duplicate of #9985
