### ISSUE TITLE
getEventsManager no longer be a magic method to obtain eventsManager service ?

### ISSUE THREAD

**Issue by xueron** [phalcon/cphalcon#10063]
eventsManager service is registered by default in FactoryDefault, but can not be obtained with magic method getEventsManager. It's ok with 1.3.x.

It seems that in 2.0.x, Di implements EventsAwareInterface and getEventsManager is a defined interface.

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.x branch, thanks

**Comment by xueron** [comment]
Got it, thanks!
