### ISSUE TITLE
Incorrect namespace when creating module application with a . in the name

### ISSUE THREAD

**Issue by oaass** [phalcon/cphalcon#10077]
When creating a project that has a . in the name, this dot is also used in the namespace causing a fatal error and requires some manual clean up. Let's say we make a project like this
```
phalcon project project.dev modules
```
The namespace now becomes `Project.dev\Controllers` causing a parse error
```
Parse error: syntax error, unexpected '.', expecting \\ (T_NS_SEPARATOR) or ';' or '{' in /****/apps/frontend/Module.php on line 3
```
Maybe it would be an idea for the namespaces to either strip the `.dev` or make it ucfirst() after each dot? Or add an option to set a project name and the actual folder separately.

I did try doing `phalcon project --name TheName --directory=/var/www/name.dev --type=modules` but that didn't work since it tried to create a folder `TheName` inside `/var/www/name.dev` which doesn't exist.

**Comment by andresgutierrez** [comment]
Can you please report this in the devtools repo? https://github.com/phalcon/phalcon-devtools
