### ISSUE TITLE
[2.0.0] Can't use column type: double

### ISSUE THREAD

**Issue by megaxman** [phalcon/cphalcon#10070]
I checked the source [column.zep], it seems that there is no support for column type [double]

**Comment by ChanoAndersen** [comment]
Have the same problem. Worked before upgrading.

**Comment by thepatron** [comment]
Same here.  I luckily have't gone to production yet so I changed my column types to decimals and they worked as expected.

**Comment by andresgutierrez** [comment]
This is fixed in branch 2.0.x
