### ISSUE TITLE
Getting error in upgrading version to 2 "compilation terminated"

### ISSUE THREAD

**Issue by vsikarwar** [phalcon/cphalcon#10094]
I am getting this error when upgrading my phalcon framework.
<pre>
In file included from /usr/include/php5/ext/spl/spl_iterators.h:27:0,
                 from /var/www/cphalcon/build/64bits/phalcon.zep.c:206:
/usr/include/php5/ext/pcre/php_pcre.h:29:18: fatal error: pcre.h: No such file or directory
 #include "pcre.h"
                  ^
compilation terminated.
make: *** [phalcon.lo] Error 1
</pre>

**Comment by Green-Cat** [comment]
It looks like you do not have the pcre library installed.

**Comment by vsikarwar** [comment]
Yes I checked, Installed and it is fixed now.
Thanks
