### ISSUE TITLE
[2.0.0] Session\Bag : Indirect modification of overloaded property

### ISSUE THREAD

**Issue by ogarbe** [phalcon/cphalcon#10095]
i've got a lot of notices : 
Indirect modification of overloaded property Phalcon\Session\Bag::$prestations has no effect

with a project updated from 1.3.4

**Comment by ogarbe** [comment]
it seems linked to https://github.com/phalcon/cphalcon/issues/1895 the pb occurs while setting values like this

```php
$sessionBag->prestations[$key] = $value;
```

method found for the moment : 

```php
$prestations = $sessionBag->prestations;
$prestations[$key] = $value;
$sessionBag->prestations = $prestations;
```

The previous code worked in 1.3.4

**Comment by ogarbe** [comment]
@andresgutierrez is it a normal feature ?

**Comment by andresgutierrez** [comment]
Zephir does not support references so the value cannot be modified that way.

**Comment by ogarbe** [comment]
ok thanks.
