### ISSUE TITLE
[2.0.0][paginator] Next paging function problems

### ISSUE THREAD

**Issue by nlmayday** [phalcon/cphalcon#10107]
See below
$paginator = new Phalcon\Paginator\Adapter\Model(array("data" => $data, "limit" => 1, "page" => 1));
$p = $paginator->getPaginate();
echo 'current:'.$p->current, ', before:'.$p->before, ', next:'.$p->next, ', total:'.$p->total_pages;
This will output “current:1, before:1, next:1, total:2”
I think the "next" should be "2"

**Comment by Green-Cat** [comment]
I'll look into and have a bug fix soon :).

**Comment by Green-Cat** [comment]
Fixed in #10114.
Could you try again after the pull request is merged?

**Comment by Green-Cat** [comment]
@phalcon fixed in #10114
