### ISSUE TITLE
Андрес, ты поехавший?

### ISSUE THREAD

**Issue by AveVlad** [phalcon/cphalcon#10102]
![](http://cs304311.vk.me/v304311251/6610/6EA-fuPL3yk.jpg)

**Comment by KorsaR-ZN** [comment]
В чем суть вопроса? От большого ума наверное...

**Comment by KorsaR-ZN** [comment]
Please close!

**Comment by AveVlad** [comment]
@KorsaR-ZN ну так  закрой

**Comment by KorsaR-ZN** [comment]
@AveVlad Смешной такой)
Если мог, то закрыл бы.

**Comment by AveVlad** [comment]
@KorsaR-ZN а я могу

**Comment by ovr** [comment]
@AveVlad Влад ты еблан <3
