### ISSUE TITLE
[2.0.0][Codeception] Click method not working after upgrade to Phalcon2

### ISSUE THREAD

**Issue by andreroggeri** [phalcon/cphalcon#10106]
```
private function login($I, $u = "admin@piv.com.br", $p = "admin"){
        $I->amOnPage('admin/login');
        $I->fillField('email', $u);
        $I->fillField('senha', $p);
        $I->click('Entrar');
        $I->see('Administrador');
    }
```

The code above work as expected on Phalcon1, but after upgrading to Phalcon2 it fails on **Click** step.

Stacktrace in here: http://pastebin.com/H2VpXN8c

I do understand that codeception is a third-party app, but upgrading phalcon shouldn't break things.

**Comment by andresgutierrez** [comment]
Can you check if the "session" service is registered as shared?

**Comment by andreroggeri** [comment]
Well, my project had wrong configuration.

The session was registered on each module(Multi module application) and also on the bootstrap.

Fixing this seems to be the solution.

I will double check tonight and close this issue.


Thank you very much for your support @andresgutierrez .

**Comment by andreroggeri** [comment]
So far so good ! :)

Phalcon1 module seems to be compatible with Phalcon2
