### ISSUE TITLE
[2.0.0][ORM][Query Builder] issue

### ISSUE THREAD

**Issue by eclipse88** [phalcon/cphalcon#10110]
```php
$result =$builder->from(['Table1' => 'Table1'])
    ->columns(['Table1.*', 'Table2.*', 'Table3.*'])
    ->join('Table2', 'Table1.id = Table2.tb2_id', 'Table2')
    ->join('Table3', 'Table1.id = Table3.tb3_id', 'Table3')
    ->getQuery()
    ->execute();
$result->toArray();
```
on my server(ubuntu 12.0.4) returning an empty array, but when i try from windows on same db and with same phalcon version(2.0.0) is returning an array with records(the expected result).

I notice if i let one parameter in columns: 
Ex: ->columns(['Table1.* ']) or ->columns(['Table2.* '])  is working.

In 1.3.4 was working properly

**Comment by andresgutierrez** [comment]
Check that your files match the same case sensitiveness as the models you're using in the Query.
