### ISSUE TITLE
[2.0.0][Assets]Js minify bug

### ISSUE THREAD

**Issue by eclipse88** [phalcon/cphalcon#10111]
```php
$js = $manager->collection('js')
->addJs('common-functions.js')
->addJs('page-functions.js')
->addFilter(new Phalcon\Assets\Filters\Jsmin())
->join(true)
->setTargetPath('public/production/final.js')
->setTargetUri('production/final.js');
```
Crushing my app and returning blank page

**Comment by KorsaR-ZN** [comment]
@eclipse88 
Now it should work.
Please try again using latest 2.0.x

**Comment by butamuh4o** [comment]
...i know its other topic, but... can u try this (see latest posts): https://github.com/phalcon/cphalcon/issues/10014 did you have same issue with assets includes external resources? (or i understand documentation wrong?)
Thanks
