### ISSUE TITLE
Request: Better Phalcon Naming

### ISSUE THREAD

**Issue by wetux** [phalcon/cphalcon#10121]
Please consider having this following examples as default naming of phalcon controllers/models file names and in-code.

#### Controllers

Right-Now:
```php
use Phalcon\Mvc\Controller;

class PostsController extends Controller {

  public function indexAction() {}

}
```

Request:
```php
use Phalcon\Mvc\Controller;

class Posts extends Controller {

  public function index() {}

}
```

Workarounds:
Setting this two empty suffixes in Dispatcher.
```php
$dispatcher->setControllerSuffix("");
$dispatcher->setActionSuffix("");
```

Thank you to "[Andres Gutierrez](http://forum.phalconphp.com/discussion/6476/better-phalcon-naming#C17485)" for pointing out this workarounds. But having this as default would be much better then having to set this suffixes to empty.

**Comment by KorsaR-ZN** [comment]
I am against such a decision. Everything should remain as it is.
:-1:

**Comment by andresgutierrez** [comment]
Changing this will break almost all existing applications

**Comment by wetux** [comment]
Reason been default should not force users to use "Controller" and "Action" by default. The proposal is for PhalconPHP 3.0 at least.

**Comment by andresgutierrez** [comment]
Also, If you aren't using namespaces there will be class name collisions:

```php
class Posts extends Controller
{
}
```

```php
class Posts extends Model
{
}
```

**Comment by KorsaR-ZN** [comment]
If do not use the namespace in the application, it will lead to a conflict of names controllers and models.
I against such innovation...

**Comment by wetux** [comment]
Why don't phalcon look for "extends Controller" or "extends Model" instead of looking at "class PostsController" in controllers and "class Posts" in models internally ?? Seems a bit weird.

**Comment by andresgutierrez** [comment]
@wetux That's how PHP works

**Comment by wetux** [comment]
LOL alright thanks Andres.

**Comment by wetux** [comment]
@ Stefan, in my opinion I don't think is a good idea to remove the suffix. This way you can see right away what is an action, what is a normal function and what is a simple class or a controller.

I don't see any confusion here. You would not store any other class in your /controllers/ folder, just controllers this is what /libraries/ folder is for. As for the "Action" prefix, you can simply use "private" for regular functions and "public" for actions. If you have anything other then actions you shouldn't store it in your class anyway, use /libraries/ folder and create separate class for your functions. Remember we are talking about namespace method. So I guess it really depends on how you organize your application.

I find it much more cleaner to not use this prefixes. Here is an example;

Base.php Controller
/app/controllers/Base.php
```php
<?php
/**
 * Base Controller
 */

namespace App\Controllers;

use Phalcon\Mvc\Controllers;

class Base extends Controller {

  function initialize() {}

  public function error() {}

} #class

#EOF: ./app/controllers/Base.php
```

Index.php Controller
/app/controllers/Index.php
```php
<?php
/**
 * Index Controller
 */

namespace App\Controllers;

use App\Libraries\Class;

class Index extends Base {

    public function index() {
      Class::action();
   } #index

} #class

#EOF: ./app/controllers/Index.php
```

**Comment by chiriac-stefan** [comment]
@wetux 
Not everyone use namespaces for all projects and is needed a solution that words with directories too.
Also if you look around on other frameworks you'll see that is common to make a difference in name for controllers and actions. Following standards is nice to do, intuitive and very helpful for developers. I'm sure no one wants a framework that when it comes to standards is "like iexplorer".

Putting aside the technical stuff, if you think a bit, when searching for a controller or action, by default, first you look at the name, not at what the controller extends or if the function is private or public. Some might argue this doesn't really make a difference, but when you're tired and caffeine level is sky high, believe me that is a difference.

What @andresgutierrez gave you are not workarounds, but more like options and are part of the flexibility that phalcon offers.
http://docs.phalconphp.com/en/master/api/Phalcon_Mvc_DispatcherInterface.html

These are my 2 cents and I'm against the decision :)

**Comment by cyberhck** [comment]
I'd beg to differ in this matter. I have some issues with naming convention here too. If you are inside a controller directory, you're not gonna keep models there. And if you don't use proper namespacing, you're out of luck anyways.

I also have problem with how naming are done for models. By definition models are supposed to be a row in table (singular data). So instead of having Users model, User model makes more sense. Users sounds like collection to me. By default (even in tutorial), model name and db table name are same, but it should use singular and table name should be plural.
