### ISSUE TITLE
Idea: Have Donations Page on KickStarter or Indiegogo

### ISSUE THREAD

**Issue by wetux** [phalcon/cphalcon#10123]
You should create donation page on https://www.kickstarter.com/ or https://www.indiegogo.com/ instead of using Pledgie. I think you will get much more support there.

**Comment by eva-thien** [comment]
Hey @wetux Phalcon Team members aren't location  at USA and they aren't allowed to use Kickstarter.

**Comment by wetux** [comment]
All team members ?

**Comment by eva-thien** [comment]
I dont know, you can ask author Phalcon

**Comment by wetux** [comment]
@ eva-thien, If you don't know why did you reply with "Team members aren't location at USA and they aren't allowed to use Kickstarter."

**Comment by andresgutierrez** [comment]
We are not in USA or UK
