### ISSUE TITLE
Phalcon 2.0 - Phalcon\Mvc\Model\Query Issue With Joins

### ISSUE THREAD

**Issue by rkeplin** [phalcon/cphalcon#10137]
I am in the process of upgrading from Phalcon 1.3.5 to Phalcon 2.0.0. Most of the process was fine, but I came across a blocker with Phalcon\Mvc\Model\Query.

https://gist.github.com/rkeplin/14d7c86a653f5ce3f7fe

In TestController.php, there are three queries. The second query always returns false while the first and third always returns true.

I am able to reproduce this issue against the 2.0.0 branch, and also the 2.0.0 tag. I cannot reproduce the issue against the 1.3.5 branch.

**Comment by virgofx** [comment]
Maybe related to #10041 ?

**Comment by andresgutierrez** [comment]
Could you please try again compiling from the 2.0.x branch?

**Comment by rkeplin** [comment]
Yes, after compiling from the 2.0.x branch this issue is resolved.  Thanks!
