### ISSUE TITLE
phalcon 2.0 oracle model->find() 

### ISSUE THREAD

**Issue by zsj1029** [phalcon/cphalcon#10135]
oracle 

exception e
#0 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(StudentBase)) #1 [internal function]: Phalcon\Mvc\Model->getReadConnection() #2 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, NULL, NULL) #3 [internal function]: Phalcon\Mvc\Model\Query->execute(NULL, NULL) #4 D:\webroot\choose\app\controllers\SessionController.php(58): Phalcon\Mvc\Model::find(Array) #5 [internal function]: SessionController->startAction() #6 [internal function]: Phalcon\Dispatcher->dispatch() #7 D:\webroot\choose\public\index.php(50): Phalcon\Mvc\Application->handle() #8 {main}

mycode
line：58 
$user = StudentBase::find(array(  
                    "student_code = '$code'",
                    "del_flag" => "0"
                ));

what‘s wrong？ what should i do
help me thx

**Comment by zsj1029** [comment]
if i use mysql 
code is normal

**Comment by zsj1029** [comment]
how to print sql statement when i use model-》find

**Comment by andresgutierrez** [comment]
Possible reference #10160

**Comment by andresgutierrez** [comment]
Could you please try again compiling from the 2.0.x branch?
