### ISSUE TITLE
initialize() not calling

### ISSUE THREAD

**Issue by mohammadhzp** [phalcon/cphalcon#10139]
in my bootstrap I created a custom dispatcher
```php
$di->set('dispatcher', function() use($di) {
    $event_manager = $di->getShared('eventsManager');
    $event_manager->attach('dispatch', new \My\Name\Space\Handler());
    
    $dispatcher = new \Phalcon\Mvc\Dispatcher();
    $dispatcher->setEventsManager($event_manager);
    
    return $dispatcher;
});
```

my Handler.php is almost like this : 
```php
namespace  \My\Name\Space;
class Handler extends \Phalcon\Mvc\User\Plugin {
function initialize() { echo 1; }
function beforeExecuteRoute($event, $dispatcher) {echo 2;}
}
```

Handler::beforeExecuteRoute() is calling but Handler::initialize() never gets called

I am using phalcon 2 on php 5.6.7

I don't think I'm doing it wrong so it's either a phalcon bug in general or it's not working with 5.6.7

**Comment by andresgutierrez** [comment]
Method initialize is called on controllers but not on plugins.

**Comment by mohammadhzp** [comment]
Sorry, I'm a newbie
