### ISSUE TITLE
ACL extends privileges problem.

### ISSUE THREAD

**Issue by Michal-St** [phalcon/cphalcon#10134]
$acl->addRole($guest);
$acl->addRole($basic_user, $guest);
$acl->addRole($user, $basic_user);
$acl->addRole($admin, $user);

When I migrate to Phalcon 2.0 I realise that roles can extend privileges only for first parent. I have resources avaible for guest, I'm logged using 'admin' role and ACL return false. Each privileges for user are avaible for admin.

**Comment by 7thcubic** [comment]
found it.
basically current it is set so that you can only check inherit for a single level.

**Comment by sersh88** [comment]
Same here. Please, solve this. I think it should work as expected - extend privileges in all levels.

**Comment by Green-Cat** [comment]
@7thcubic Pull requests are always welcome.
