### ISSUE TITLE
2.0 problems

### ISSUE THREAD

**Issue by HudsonNicoletti** [phalcon/cphalcon#10154]
so i have upgraded the windows dll to the correct 2.0 and this happens : 

Fatal error: Declaration of Frontend\Module::registerAutoloaders() must be compatible with Phalcon\Mvc\ModuleDefinitionInterface::registerAutoloaders(Phalcon\DiInterface $dependencyInjector = NULL) in C:\wamp\www\agronomia\apps\frontend\Module.php on line 12

**Comment by Green-Cat** [comment]
Phalcon 2.0 is stricter with data types.
That means that you need to specifically type hint the object type to comply with the interface.
So you need to edit you Frontend\Module::registerAutoloaders from
```php
public function registerAutoloaders($dependencyInjector = null)
```
to
```php
registerAutoloaders(Phalcon\DiInterface $dependencyInjector = null)
```
