### ISSUE TITLE
Error with oracle dialect and adapter in phalcon 2

### ISSUE THREAD

**Issue by dantevirgilio** [phalcon/cphalcon#10160]
Hi all, I'm quite new to phalcon. I set up my very first project some days ago, today I've upgraded to phalcon 2.0 and my db access (Oracle!), has stopped working. This is the exeption I've got

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Call to undefined method Phalcon\\Db\\Dialect\\Oracle::tableexists()' in /var/www/html/cupido/app/controllers/ApiController.php:49\nStack trace:\n#0 [internal function]: Phalcon\\Db\\Adapter->tableExists

How can I fix them? Thank you very much!

**Comment by zsj1029** [comment]
me too 
the same question

**Comment by KorsaR-ZN** [comment]
@zsj1029 Try branch 2.0.x, In this branch, this error fixed

**Comment by zsj1029** [comment]
@KorsaR-ZN  but i am in windows7 
what should i do

**Comment by KorsaR-ZN** [comment]
@andresgutierrez Please, help him build branch 2.0.x on windows

**Comment by andresgutierrez** [comment]
2.0.1 is now released
