### ISSUE TITLE
[2.0.0] Dispatcher Error

### ISSUE THREAD

**Issue by alphanyx** [phalcon/cphalcon#10179]
I've upgraded from Phalcon v1.3.4 to Version 2.0.0

I used this method in some part of my Application to get the full Controller Class with Namespace from the Dispatcher (**Phalcon\Mvc\Dispatcher**)

```php
$controllerClass = $dispatcher->getControllerClass();
```

In version **1.3.4** everything works fine.
In version **2.0.0** i get an error from this Method:

**Call to undefined method Phalcon\Mvc\Dispatcher::gethandlername()**

Reference:
- [Phalcon Forum](http://forum.phalconphp.com/discussion/6514/dispatcher-error-after-upgrade-to-200)

**Comment by sergeyklay** [comment]
Possible reference #10078

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2.0.3 or higher?

**Comment by alphanyx** [comment]
With Version 2.0.3 everything works fine.
Bug seems to be fixed
