### ISSUE TITLE
2.0.x can't view file

### ISSUE THREAD

**Issue by wolftail** [phalcon/cphalcon#10189]
if use namespace like admin, can't auto find view file

**Comment by sergeyklay** [comment]
@wolftail Can you provide your autoload map and directories structure please?

**Comment by ryomo** [comment]
I hope this may help you.
```php
$this->view->setViewsDir($this->view->getViewsDir() .'admin/');
```
[simple-subcontrollers - phalcon/mvc](https://github.com/phalcon/mvc/tree/master/simple-subcontrollers)

**Comment by wolftail** [comment]
i just add a namespace admin, and view file is  views/admin/test/hello.phtml, can' t find the file. i remove namespace, the view file is views/test/hello.phtml,  it is ok.

**Comment by wolftail** [comment]
router is :
$router = new \Phalcon\Mvc\Router();
$router->add("/(api|admin)/([a-zA-Z0-9_-]*)/?([a-zA-Z0-9_]*)(/.*)*", array(
    'namespace' => 1,
    'controller' => 2,
    'action' => 3,
    'params' => 4
));
return $router;

**Comment by andresgutierrez** [comment]
Can you please use the latest released Phalcon or supply a full script to reproduce the issue?
