### ISSUE TITLE
[2.0.0] Phalcon\Security setDefaultHash() Method missing?

### ISSUE THREAD

**Issue by alphanyx** [phalcon/cphalcon#10181]
I've upgraded from Phalcon 1.3.4 to Phalcon 2.0.0

I've used this method to set the Default Hash of the Security Class

```php
$security->setDefaultHash(\Phalcon\Security::CRYPT_BLOWFISH_Y);
```

But in Phalcon 2 this method seems missing. How do i set the Default Hash in Phalcon 2?

Reference:
- [Phalcon Forum](http://forum.phalconphp.com/discussion/6515/phalcon-2-phalconsecurity-setdefaulthash-method-missing)

**Comment by sergeyklay** [comment]
Fixed in 173d5bfa7d66d8912b0718cb9923326dacf9b45a
