### ISSUE TITLE
Translate NativeArray Adapter's offsetSet method

### ISSUE THREAD

**Issue by ilgityildirim** [phalcon/cphalcon#10197]
Let me start by saying I'm guessing this is a bug as far as what I understand from the documentation.

The documentation;
http://docs.phalconphp.com/en/latest/api/Phalcon_Translate_Adapter.html

Here it states that `offsetSet()` sets a translation value.

Let's imagine I set a service called "translator" in my DI and I try the following code from controller to add / change translation value on the fly!
````php 
    $translator = $this->getDI()->get("translator");
    $translator->offsetSet("my_key","my translation value for my_key");
````
This code above ends up with following error; `Phalcon\Translate\Exception: Translate is an immutable ArrayAccess object`

I ended up creating my own translate adapter and it works as expected.

However I should also mention the documentation here http://docs.phalconphp.com/en/latest/reference/translate.html is not complete. It doesn't mention that you also need to add methods in `Phalcon\Translate\Adapter` such as `offsetSet()`, `offsetExists()`, `offsetUnset()`, `offsetGet()` There are no mentions for these methods within the documentation for implementing your own adapter.

I'm using Phalcon 2.0.0

**Comment by andresgutierrez** [comment]
Those methods are required by the ArrayAccess interface not by Phalcon: http://php.net/manual/en/class.arrayaccess.php

**Comment by xerron** [comment]
So why they are public?

public offsetSet (string $offset, string $value) inherited from Phalcon\Translate\Adapter
public offsetExists (mixed $translateKey) inherited from Phalcon\Translate\Adapter
public offsetUnset (string $offset) inherited from Phalcon\Translate\Adapter
public string offsetGet (string $translateKey) inherited from Phalcon\Translate\Adapter

Gettext Adapter:

```php
$t->offsetSet('Name', 'Nombre');
```
show:

```text
Translate is an immutable ArrayAccess object

#0 /home/xerron/Repo/php/u-w-u.com/modules/system/system.routing.php(125): Phalcon\Translate\Adapter->offsetSet('Name', 'Nombre')
#1 [internal function]: {closure}()
#2 /home/xerron/Repo/php/u-w-u.com/web/index.php(68): Phalcon\Mvc\Micro->handle()
#3 {main}
```
