### ISSUE TITLE
2.0 Pagination bug in pnultimate page attribute "next"

### ISSUE THREAD

**Issue by rvnerd** [phalcon/cphalcon#10196]
![pagination](https://cloud.githubusercontent.com/assets/3394457/7384964/7e4c0af4-ee34-11e4-8389-adbce1de750d.png)

when you hover the next button, as you can see from the url at the bottom, on the penultimate item, which has the `$page->next` attribute implemented in the next button, it shows not the next one (which is the last [9]) but instead it shows the current one which is the `$page->current` ([8])

**Comment by Green-Cat** [comment]
This should be fixed in the 2.0.x branch (#10114). Could you try it?

**Comment by rzZzv** [comment]
thanks @Green-Cat , I will test it!
