### ISSUE TITLE
[2.0.0] Add new default paths for views to the docs and upgrade guide

### ISSUE THREAD

**Issue by vladimmi** [phalcon/cphalcon#10190]
I'm using annotations router with Volt templates. After upgrading to 2.0.0 view paths changed their controller part from `UpperCamelCase` to `snake_case`. For example, `TypeCategory/index.volt` became `type_category/index.volt`.

On other side, action part changed from `lowerCamelCase` to `lowercase`. For example, `corporation/vsKillboard.volt` became `corporation/vskillboard.volt`.

This change turns site into white pages without any errors in logs.

Think, this should be noted in upgrade guide and somewhere in the docs.

**Comment by sergeyklay** [comment]
:+1:

**Comment by sergeyklay** [comment]
I want to close this issue because the `1.3.x` and `2.0.x` branch is not longer supported and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
