### ISSUE TITLE
[NFR] Application Interface

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#10205]
Hello!

It seems it would be useful to have something like `ApplicationInterface` for

* `\Phalcon\Cli\Console`
* `\Phalcon\Mvc\Application`
* `\Phalcon\Mvc\Micro`

at least for testing purposes

**Comment by SidRoberts** [comment]
I think MVC HTTP apps are very different to CLI apps so they shouldn't share the same interface. However, if we created `Phalcon\Mvc\ApplicationBaseInterface` (taking [`ViewBaseInterface`](https://github.com/phalcon/cphalcon/commit/57731fce407c1f4f6ea0bbc11da8748e139a9f7a) as inspiration), there would only be two methods in the interface: `__construct()` and `handle()`. Whilst the parameters are the same, the return types for `handle()` are different.

I'm not against the idea but I'm not sure how useful it would be either. :smile:

**Comment by sergeyklay** [comment]
@SidRoberts  for example:

https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Connector/Phalcon1.php#L60
```php
if (!$application instanceof \Phalcon\MVC\Application && !$application instanceof \Phalcon\MVC\Micro) {
    throw new \Exception('Unsupported application class');
}
```

In general I don't encourage such rude approach to the problem. Thinking at the interface level we make cleaner code and often it turns more elegant.

**Comment by Green-Cat** [comment]
@sergeyklay I think that https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/application.zep is an implementation of this NFR?
