### ISSUE TITLE
[1.3.4] Phalcon Paginator NativeArray with empty data

### ISSUE THREAD

**Issue by hugofcampos** [phalcon/cphalcon#10206]
If I've created a \Phalcon\Paginator\Adapter\NativeArray with an empty array, the result pagination has the following information:

```php
object(stdClass)#239 (8) {
  ["items"]=>
  array(0) {
  }
  ["before"]=>
  int(1)
  ["first"]=>
  int(1)
  ["next"]=>
  int(0)
  ["last"]=>
  int(0)
  ["current"]=>
  int(1)
  ["total_pages"]=>
  int(0)
  ["total_items"]=>
  int(0)
}
```

Looking for the value of current and total_pages, they are inconsistent (1 and 0, respectively). I think it should be 1 for both of values.

**Comment by andresgutierrez** [comment]
Phalcon 1.3 is not supported anymore, could you try using 2.0.0?
