### ISSUE TITLE
[2.0.0] Massive amount of segfaults

### ISSUE THREAD

**Issue by rbrosboel** [phalcon/cphalcon#10213]
I have a project that causes 2.0.0 to segfault on ~50% of requests. The same project is rock solid on 1.3.4.

Attaching gdb to apache I get a variety of different stacks, but they all seem to crash a few frames into reading model meta data.

All attempts to create a minimal test case have resulted in only sporadic crashes. If a @phalcon developer is interested in my code base for fast reproduction of the bug, please let me know.

**Comment by gte451f** [comment]
I've just started playing around with 2.0 and am getting similar behavior but more like 1 in 15 request. 
I'm developing an API on the micro stack if that helps.

Sticking with 1.3.x series on Production for now.

**Comment by andresgutierrez** [comment]
Could you please try again compiling from the 2.0.x branch?

**Comment by gte451f** [comment]
I will rebuild and try it out.

**Comment by gte451f** [comment]
The segfaults seem much worse for me on latest 2.0.x, I can only make it a couple of requests until I have to restart Apache.
I'm on Debian 7, Apache, ModPHP.

Switching to 1.3.4 restores everything to normal.

I am happy to attempt to gather error logs but I confess I don't know how to go about getting them.  Can you point me to a resource to help me understand how to debug phalcon errors or just gather stack traces?

**Comment by sergeyklay** [comment]
@gte451f +1

@andresgutierrez me too :)

**Comment by andresgutierrez** [comment]
Without a script to reproduce the issue it would be hard to provide a solution

**Comment by andresgutierrez** [comment]
Can you check again using latest 2.0.x?
