### ISSUE TITLE
[2.0.x] \Phalcon\Debug\Dump::var

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#10214]
`\Phalcon\Debug\Dump::var`
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/debug/dump.zep#L252

`var` is reserved word in PHP 
http://php.net/manual/en/reserved.keywords.php

Suggest rename it to `dump`

**Comment by Green-Cat** [comment]
var is also reserved in zephir

**Comment by sergeyklay** [comment]
@KorsaR-ZN thanks
