### ISSUE TITLE
partials : can't set partial extension when calling a partial

### ISSUE THREAD

**Issue by yd021976** [phalcon/cphalcon#10215]
Hello, think it's a bug : when calling partial like {{ partial('menu.html') }}, view throws exception saying " ../app/views/partials/menu.volt was not found in the views directory".

I discovered this is because i set views template engines with "registerEngines" to "phtml" in first and "volt" in second. If i set "volt" in first and "phtml" in second, it works.

So i think it's a bug because 
1 - Falcon automatically add or look for a partial file with extension corresponding to the first declared template engine in view
2 - We could call a partial no matter the template engines are sets in view object.

Thanks for your help.

**Comment by andresgutierrez** [comment]
It checks if the file exist in every engine registered not just the first one
