### ISSUE TITLE
[BUG] Some wrong info in documentation

### ISSUE THREAD

**Issue by butamuh4o** [phalcon/cphalcon#10210]
If u open http://docs.phalconphp.com/en/latest/reference/cache.html - section Memcached Backend Example - u will see git stuff. 
Its good to fix this. Thanks

**Comment by sergeyklay** [comment]
@butamuh4o Can u create issue in [docs](https://github.com/phalcon/docs) repo please?

**Comment by butamuh4o** [comment]
Sure, sorry for wrong place... :/
