### ISSUE TITLE
[2.0.0] Phalcon\Config bug with array access with integer key: "Parameter 'index' must be a string"

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10225]
I'm receiving **Parameter 'index' must be a string** exception when attempting to do array access with an integer.  It works with property access though.

Data:

```php
array (
    'signin' => 
        array (
            0 => 'signin',
            1 => 'org::session::signin'
        )
)
```

This doesn't work:

```php
$config->['signin'][1];
```

But this does work:

```php
$config['signin']->{1}
```

**Comment by dschissler** [comment]
I'll reopen later if the new code doesn't work.

**Comment by olivierandriessen** [comment]
This doesn't work in Phalcon 2.0

**Comment by andresgutierrez** [comment]
@olivierandriessen It works for me in >= 2.0.2

**Comment by olivierandriessen** [comment]
@andresgutierrez  Never mind, i'm still on 2.0.0.
