### ISSUE TITLE
[2.0.x] Dispatcher function getControllerClass()

### ISSUE THREAD

**Issue by michanismus** [phalcon/cphalcon#10228]
Function returns class with namespace but first char of controller name is missing.

Example: Horus\AdminBundle\Controller\ashboardController
Should be: Horus\AdminBundle\Controller\DashboardController

**Comment by michanismus** [comment]
Same for getHandlerClass()

**Comment by konsultaner** [comment]
I experienced the same problem and had it posted to the [forum](http://forum.phalconphp.com/discussion/6793/moving-from-134-to-201-causes-ndexcontrollerclass-not-loaded)

**Comment by andresgutierrez** [comment]
Could you please post the relevant code that allow us to reproduce the issue?

**Comment by michanismus** [comment]
Can't reproduce it anymore. Seems to be fixed with one of the commits in the last 14 days.
