### ISSUE TITLE
unit testing a phalcon component

### ISSUE THREAD

**Issue by pablomoreno61** [phalcon/cphalcon#10221]
Hi!

I'm trying to test a component which needs Phalcon DI container in order to get a view template, but even I load my DI as de thefault DI, my component cannot found view dependency.

This is written in my index.php (which is written exactly as your documentation)

$di->set('view', function () use ($config) {
    $view = new View();

    $view->setViewsDir(PROJECT_PATH . '/Project/Application/Shared/View/');

    $view->setLayoutsDir('layouts/');

    $view->setLayout($config->application->defaultLayoutName);

    $view->registerEngines(array(
        '.volt' => '\Phalcon\Mvc\View\Engine\Volt',
        '.phtml' => function ($view, $di) use ($config) {
            $volt = new Volt($view, $di);

            $volt->setOptions(
                array(
                    'compiledPath' => PROJECT_PATH . $config->volt->cacheDir,
                    'compiledSeparator' => '_',
                    'compileAlways' => true
                )
            );

            return $volt;
        }
    ));

    return $view;
});

DI::setDefault($di);

Then I have my MailTest which extends UnitTestCase, written exactly as your documentation.

Then in my component (extending from \Phalcon\Mvc\User\Component) I have the following:

        // Get template
        $view = $this->getDI()->get('view');
        $currentViewsDir = $view->getViewsDir();

        $view->setViewsDir($this->templatesDir);
        $content = $view->getRender('', $name, $personalizationParams);

But this code doesn't works while unit testing execution, I get this error:

Phalcon\Di\Exception: Service 'view' wasn't found in the dependency injection container

I've tried to create a new FactoryDefault() int my Test, and inject it into my component using setDI(), in that case, view is found but directory path seems blank even I've configured it before.

Could you help me??

thanks!

**Comment by sergeyklay** [comment]
@pablomoreno61 I just created right now this example repo for you https://github.com/sergeyklay/phalcon-component-example

**Comment by sergeyklay** [comment]
Greeting component: https://github.com/sergeyklay/phalcon-component-example/blob/master/app/library/Greeting.php
Used here: https://github.com/sergeyklay/phalcon-component-example/blob/master/app/controllers/IndexController.php

**Comment by sergeyklay** [comment]
@pablomoreno61 And test :)
https://github.com/sergeyklay/phalcon-component-example/blob/master/tests/UnitTest.php#L22

**Comment by pablomoreno61** [comment]
Hi Serghei!

I made work my DI following your example, thanks! Anyway, I'm still having
problems with rendering my views. That's a piece of code:

        $view = $this->getDI()->get('view');
        $currentViewsDir = $view->getViewsDir();

        $view->setViewsDir($this->templatesDir);
        $content = $view->getRender('', $name, $personalizationParams);

And that's the templatesDir:

'templatesDir' => PROJECT_PATH .
'/apps/Consupermiso/Application/Mail/View/mail/'

I only want to render the html parsed with Volt, so this is why I don't use
the controller parameter: That gives me the following error:

user@group:/var/www/frontend (master)$ php vendor/bin/phpunit -c
tests/phpunit.xml
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from /var/www/frontend/tests/phpunit.xml

......Violación de segmento (`core' generado)

I've tried to remove "mail/" from my templatesDir and add "mail" to the
first parameter of getRender, but it still giving this error.

pablo.

2015-05-03 12:11 GMT+02:00 Serghei Iakovlev <notifications@github.com>:

**Comment by sergeyklay** [comment]
@pablomoreno61 Can you please share your code?  
I try to understand

**Comment by sergeyklay** [comment]
@pablomoreno61 Issue can be closed?

**Comment by sergeyklay** [comment]
@pablomoreno61 ?

**Comment by pablomoreno61** [comment]
Hi Serghei, I'm trying just know, i will let you know soon.

thanks!

2015-05-05 10:01 GMT+02:00 Serghei Iakovlev <notifications@github.com>:

**Comment by Metehan** [comment]
Hi, i have same problem but looks like the example repo you created is removed do you still have that example @sergeyklay

**Comment by sergeyklay** [comment]
@Metehan could you please open a new issue with code to reproduce and php/os versions
