### ISSUE TITLE
Session set 0 value return NULL, is a bug?

### ISSUE THREAD

**Issue by hardlick** [phalcon/cphalcon#10238]
Hi, i do:

	 $this->session->set(self::BTS_SESSION_USER_ID,$o_user->getIduser());

where $o_user->getIduser(), could be, 0,1,2,3,4.....1000

when i try to save in session: 0 value, and do:
	
	var_dump($this->session->get(self::BTS_SESSION_USER_ID));
	
the response is: NULL

Why does not save 0 value!... this is a bug??

**Comment by andresgutierrez** [comment]
Fixed in 2.0.x
