### ISSUE TITLE
The Asset setSourcePath didn't work with ver 2.0

### ISSUE THREAD

**Issue by vantienvnn** [phalcon/cphalcon#10233]
Hi All,

I had used the function \Phalcon\Assets\Collection::setSourcePath(). But it didn't work when i updated Phalcon from 1.3.4 to 2.0 ( work well in Phalcon 1.3.4 )
When i run the my project, i got the resource path is not valid message.

My source code: in view index.php

$this->assets->collection('css')
        ->addCss('/css/bootstrap.min.css')
        ->addCss('/css/main.css')
        ->addCss('/css/owl.carousel.css')
       ->setSourcePath('/var/www/public/html/');
->setTargetUri('/css/index.css')
        ->join(true);
$this->assets->outputCss();

I got the error:
Resource \'/css/bootstrap.min.css\' does not have a valid source path

Thanks,
Tien Van Vo

**Comment by andresgutierrez** [comment]
Could you please try again using latest Phalcon 2.0.6?

**Comment by vantienvnn** [comment]
Thank you, now it work already
