### ISSUE TITLE
[2.0.x][Volt] User controller & view directory auto wrapping element to view templates

### ISSUE THREAD

**Issue by caleuanhopkins** [phalcon/cphalcon#10235]
I have noticed that since running the 2.0 version, Phalcon seems to automatically place centering code into my views:

``` <div align="center"> ```

Here are a few shots of the html element appearing. It seems to be added when the ``` {{ content() }} ``` function is used in ``` .volt ``` templates:

![elements centered aligned](https://cldup.com/mV_NYb7XRq-3000x3000.png)
---
![elements in code](https://cldup.com/L1_-_SnPrQ-3000x3000.png)
---
![showing it aooears from content function](https://cldup.com/hkphq3NSaM-3000x3000.png)
---
![evidence in code](https://cldup.com/5SfC6Acobk-3000x3000.png)
---
Can someone tell me how to stop this from being placed in my templates?

**Comment by sergeyklay** [comment]
I'm not sure that it makes Phalcon. 
At least I could not find it:
```sh
 grep -nr 'center' phalcon/
```

**Comment by caleuanhopkins** [comment]
@sergeyklay It's definitely something to do with the ``` content() ``` function. If I move the html to the main ``` index.volt ``` file in the ``` views ``` directory, the element doesn't appear.

**Comment by caleuanhopkins** [comment]
@sergeyklay figured it out.

Turns out if you create a Controller (or scaffold using dev-tools which I did) titled ``` users ```, then all templates in the ``` users ``` view directory will have ``` <div align="center"> ... </div> ``` wrapped around the loaded template through the ``` {{ content() }} ``` function. Renaming the controller and the views directory to anything else will remove the ``` align="center" ``` element.

I have no idea how to debug Phalcon so I unfortunately cannot supply a patch fix for this.

**Comment by caleuanhopkins** [comment]
http://forum.phalconphp.com/discussion/6615/remove-auto-center-alignment#C17899

Problem solved here

**Comment by SidRoberts** [comment]
I'm on a train so there's not much I can do but it sounds like a layouts file. Here's the offending line: https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Builder/Scaffold.php#L606

If you edit views/layouts/users.volt, you should be able to remove the align="center".
