### ISSUE TITLE
NGINX + Phalcon 2 + FPM silently fails on larger requests

### ISSUE THREAD

**Issue by gte451f** [phalcon/cphalcon#10245]
I've been testing out Phalcon 2 on a couple of different stacks and recent install exhibited odd behavior.  A micro framework API would run correctly for "small" requests but silently fail for large requests.  In other words, the API would return a few records, but if I asked the API for a larger result set, the request would silently fail with no trace of a problem in any of the usual log files (NGINX, PHP-FPM).  

Reverting back to Phalcon 1.3.4 eliminated the problem.

I noticed that PHP would fire up a process and it would quick, but NGINX never responded and the web page would remain in a loading state forever.  There wasn't even a time out.

Machine Stack:
NGINX
Phalcon 2
PHP-FPM
PHP 5.6

**Comment by andresgutierrez** [comment]
Could you please try again using latest version in 2.0.x branch?
