### ISSUE TITLE
[2.0.x]  Namspace with duplicate Names

### ISSUE THREAD

**Issue by wojewsky** [phalcon/cphalcon#10268]
I've a problem with namespaces.
I've defines the Namespace 'test' => '/path1/path2/
If I have a class like this test/foo/bar/test/base i've got an error.
This had worked with phalcon 1.3.x

**Comment by dreamsxin** [comment]
Please sumbit test code, Can reproduce the problem?

**Comment by wojewsky** [comment]
$loader = new \Phalcon\Loader();
$loader->registerDirs(array(
  $config->application->controllersDir,
));
//Namespaces definieren
$loader->registerNamespaces(array(
  'Webdata'    => '/data/Webdata/
));
$this->_di['loader'] = $loader;
...
$result = Webdata\Db\Webdata\Basics::getData();
...
namespace Webdata\Db\Webdata;
class Basics
{
public static function getData() {
}
}

-> Fatal error: Class 'Webdata\Db\Webdata\Basics' not found in /data/Webdata/Db/Webdata.php

**Comment by andresgutierrez** [comment]
Fixed in 2.0.x branch
