### ISSUE TITLE
[2.0.x] Annotations Router with path "/" becomes empty pattern

### ISSUE THREAD

**Issue by michanismus** [phalcon/cphalcon#10261]
Seems to be a bug.

If I create a route with:

```php
$route = new \Phalcon\Mvc\Router\Route('/');
```
The route _pattern = "/" and the _compiledPattern = "/" as well.

For annotation like:
```php
    /**
     * Slug index action.
     *
     * @Route("/",  name="slug_index", locale=true)
     */
    public function indexAction()
    {
```
The route _pattern and _compiledPattern is empty "" and the route won't never match.

**Comment by baryshev** [comment]
Seems to duplicates #1608. Fixed in 2.0.x branch.

**Comment by michanismus** [comment]
I'm using latest 2.0.x branch.

**Comment by michanismus** [comment]
Works now with branch 2.0.x.
