### ISSUE TITLE
Flash\Session::getMessage('key') returns an array

### ISSUE THREAD

**Issue by osse76** [phalcon/cphalcon#10279]
I set a flash success messages in the backend. In the view, i also check with getMessage('error') if there error messages present. the method "getMessages('error')" return an array like this:
Array ( [success] => Array (  [0] => "success Message") ).
There was already a similar Bug #908
I would expect an empty array, null or false

**Comment by andresgutierrez** [comment]
Fixed in 2.0.x branch
