### ISSUE TITLE
Phalcon changed my mysql database host address and can't connect to db.

### ISSUE THREAD

**Issue by zikezhang** [phalcon/cphalcon#10272]
PDOException: SQLSTATE[28000] [1045] Access denied for user 'username'@'x.x.x.206' (using password: YES)

but I set host is x.x.x.117.

so why phalcon said the host is x.x.x.206?

and you can see the screen shot here: http://www.awesomescreenshot.com/image/189837/39318c098c8da4ffeca70615b4993a32

so, why I can't use $db = new \Phalcon\Db\Adapter\Pdo\Mysql() to connect my db?

**Comment by virgofx** [comment]
More than likely, you have another setting that is overriding your host. This happens a lot with dev/prod systems where developers create local overrides. If possible just check the values via XDebug/echo/var_dump just prior to your mysql call.
