### ISSUE TITLE
[2.0.x] [Bug] ResultSet Model Hydration does not work with Resultset::HYDRATE_RECORDS and Specific Columns

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#10275]
Does not work:
```php
        $results = Robots::find([
            'columns'    => 'name',
            'hydration'  => Resultset::HYDRATE_RECORDS
        ]);
        foreach ($results as $result) {
            // Outputs "Phalcon\Mvc\Model\Row"
            // Expected to have a "Model\Robot" with only partially filled properties
            echo get_class($result);
            exit;
        }
```

Works, with no columns selected:
```php
        $results = Robots::find([
            'hydration'  => Resultset::HYDRATE_RECORDS
        ]);
        foreach ($results as $result) {
            // Outputs "Models\Robot"
            echo get_class($result);
            exit;
        }
```

**Comment by patrick-zippenfenig** [comment]
was ist working on 2.0.0?

**Comment by virgofx** [comment]
@patrick-zippenfenig No, this bug should be present in all versions. This really is just an aspect of the Query class in how it determines the internal translation of simple or not. I had tagged 2.0.x just to note it's present in latest not that it's only affected by this version.

**Comment by virgofx** [comment]
It appears the default attempts to hydrate as records unless it detects specific columns and then it reverts to array/row, ignoring any specific value specified for the hydration. Perhaps the fix would be to set the default to null such that when a specific value for hydration is specified, it will use this instead of reverting to default.

**Comment by virgofx** [comment]
@andresgutierrez Can you shed some insight into how one could accomplish using Models for query results when only selecting limited data (e.g. You have a table with large column size and for performance you only need a couple of columns, yet you want to utilize getters/setters from a defined model).

Thanks.

**Comment by patrick-zippenfenig** [comment]
A select query defaults to ````Phalcon\Mvc\Model\Row```` as soon as ````columns```` is set. The hydrated model is stored in the private property ````_model```` in ````Phalcon\Mvc\Model\Resultset\Simple````:
````php
$robots = Robots::find(['columns' => 'name']);
echo get_class($robots); // Phalcon\Mvc\Model\Resultset\Simple

// set _model
$reflectionClass = new ReflectionClass('Phalcon\Mvc\Model\Resultset\Simple');
$prop = $reflectionClass->getProperty('_model');
$prop->setAccessible(true);
$prop->setValue($robots, new Robots());

foreach ($robots as $robot) {
  echo get_class($robot); // Robots
  echo $robot->name;
}
````

**Comment by virgofx** [comment]
@patrick-zippenfenig This doesn't seem very intuitive from an end-user perspective. I would think that there would be a nice option to force the resultset from find/firstFirst/etc. to be either an array or object without having to explicitly instantiate a new reflection class and set the data.
