### ISSUE TITLE
Fatal error when calling Request::hasPut()

### ISSUE THREAD

**Issue by mahelious** [phalcon/cphalcon#10283]
After upgrading our environment to Phalcon 2.0 was running some tests and ran into an error when calling Phalcon\Http\Request::hasPut().  Checking the [documentation](http://docs.phalconphp.com/en/latest/api/Phalcon_Http_Request.html) for Phalcon 2.0 I find references to has, hasGet, hasPost and hasServer, however hasPut is missing.  Why has this method not been included?  If oversight, is there a php fragment I can use until a patched stable is released?  If it has been done away with intentionally why was that not mentioned in the upgrade guide?

**Comment by andresgutierrez** [comment]
Fixed in 2.0.x branch
