### ISSUE TITLE
Cannot rename the Plugin directory

### ISSUE THREAD

**Issue by zjhzxhz** [phalcon/cphalcon#10291]
I tried to rename the name of `plugins` directory in `app` to `plugin`.
Also I change the `config.ini` to this:
```
[application]
controllerDir = app/controller/
modelDir      = app/model/
viewDir       = app/view/
pluginDir     = app/plugin/
formDir       = app/form/
libraryDir    = app/library/
baseUri       = /invo/
```
When I start the application, I got an exception:
```
Fatal error: Class 'SecurityPlugin' not found in /home/xiehaozhe/Development/PHP/invo/app/config/services.php on line 28
```

**Comment by sergeyklay** [comment]
Double check autoloader
https://github.com/phalcon/invo/blob/master/app/config/loader.php#L11

**Comment by zjhzxhz** [comment]
I'm new to Phalcon. And I'm using the demo names [invo](https://github.com/phalcon/invo).
Where's the autoloader?
Is it located in `app/config/loader.php`?
And here's the content of `loader`.php
```
$loader->registerDirs(
	array(
		APP_PATH . $config->application->controllerDir,
		APP_PATH . $config->application->modelDir,
		APP_PATH . $config->application->viewDir,
		APP_PATH . $config->application->pluginDir,
		APP_PATH . $config->application->formDir,
		APP_PATH . $config->application->libraryDir,
	)
)->register();
```

**Comment by sergeyklay** [comment]
Invo's `config.ini` contains plugin**s**Dir not pluginDir: 
https://github.com/phalcon/invo/blob/master/app/config/config.ini#L12

also `loader.php` contains plugin**s**Dir not pluginDir: 
https://github.com/phalcon/invo/blob/master/app/config/loader.php#L11

If you are changed this, double check all you changes.
At least right now I downloaded Invo and checked:

```sh
$ cd /tmp
$ git clone git@github.com:phalcon/invo.git
$ cd invo
$ sed -i.bak -e "s/invo\///g" app/config/config.ini
$ php -S localhost:8000 -t public/ .htrouter.php
```

then open in browser http://localhost:8000/ all work fine

**Comment by zjhzxhz** [comment]
Well, I'll test it later.
But now I'm trouble into another problem. I got an error message without any other information:
`A dependency injection container is required to access the 'request' service`. 
Can you help me to solve it?

**Comment by zjhzxhz** [comment]
Well, I'll test it later.
But now I'm trouble into another problem. I got an error message without any other information:
`A dependency injection container is required to access the 'request' service`. 
Can you help me to solve it?

**Comment by zjhzxhz** [comment]
Well it works.
Thanks a lot.
