### ISSUE TITLE
Phalcon\Mvc\Micro\Collection missing via() method

### ISSUE THREAD

**Issue by mahelious** [phalcon/cphalcon#10296]
[doucmentation](http://docs.phalconphp.com/en/latest/reference/micro.html#defining-routes) for Micro-controllers indicates the following to map multiple methods at once:

> //Matches if the HTTP method is GET or POST
> $app->map('/repos/store/refs',"action_product")->via(array('GET', 'POST'));

However via() is absent from [Phalcon\Mvc\Micro\Collection](http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Micro_Collection.html) and throws an error when attempting to invoke.

**Comment by sergeyklay** [comment]
Can you please create issue in [docs](https://github.com/phalcon/docs) repo?

**Comment by mahelious** [comment]
I don't believe the issue is with the docs, the Micro Collection ought to have a via() method.

**Comment by Green-Cat** [comment]
It is not, I will be able to fix this when I get home, if no one makes a PR by then.

**Comment by Green-Cat** [comment]
The via() method however, does not even exist in 1.3.5, so not too sure about that one.

**Comment by mahelious** [comment]
Skimming the code I am mystified at how via() was ever working.  The only clue I have is that in 1.3 map() seemed to return a Phalcon\Mvc\Micro\CollectionInterface while in 2.0 it returns a Phalcon\Mvc\Micro\Collection.  It's not much help as there is no via function in ext/mvc/micro/collectioninterface.c (nor in ext/mvc/micro/collection.c for that matter).  I can confirm the code worked in Phalcon 1.3.3.

In any case, map() adds an item to the collection _handlers with an empty method.  Is there a "correct" way to populate the method (or preferably multiple methods) once map() is finished?  My thought is immediately after calling map() to pop the last element, and then foreach over the list of methods to update _handlers with multiple "cloned" items, but I don't know if that matches the expected behavior.

**Comment by Green-Cat** [comment]
It implements the interface, so returning itself does return the interface.

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.x
