### ISSUE TITLE
Update PPA

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#10300]
@andresgutierrez

1. I think need update PPA ` ppa:phalcon/stable`. It is important
2. Need add to README.md instructions (or link) — how to install from PPA for Ubuntu/Debian without any compilations and building.

I think this way for Ubuntu/Debian will be very popular, hehe

**Comment by andresgutierrez** [comment]
@thecodeassassin

**Comment by sergeyklay** [comment]
@andresgutierrez Please update http://phalconphp.com/en/download

> There is a PKGBUILD for ArchLinux, available here

404 Link not found.
Correct link: https://aur.archlinux.org/packages/php-phalcon/
Also if it possible, make changes for all languages

**Comment by andresgutierrez** [comment]
Feel free to submit a PR to the website https://github.com/phalcon/website

**Comment by thecodeassassin** [comment]
@sergeyklay what needs to be updated about the phalcon/stable PPA?

phalcon/stable: 2.0.0
phalcon/legacy: 1.3.4

**Comment by sergeyklay** [comment]
But current stable is 2.0.1

**Comment by sergeyklay** [comment]
@thecodeassassin http://blog.phalconphp.com/post/118465365385/phalcon-2-0-1-released

**Comment by thecodeassassin** [comment]
@andresgutierrez i usually check the releases for changea when i build the new packages. Do you plan to create a release for these bugfix releases?

**Comment by m157y** [comment]
Please, create tag or branch for 2.0.1, because it's very uncomfortable to create homebrew package from master branch.

**Comment by andresgutierrez** [comment]
@thecodeassassin @m157y 2.0.1 is now tagged and released https://github.com/phalcon/cphalcon/releases/tag/phalcon-v2.0.1

Thanks

**Comment by thecodeassassin** [comment]
@andresgutierrez can you (for the next release) add a lastupdate.json file in the repo containing the changelog of the new release? I want to build a script that reads this JSON from every release and builds packages automatically? This will allow for a more automated way of creating the packages (which is now a pain in the butt). 

I discussed this with @niden earlier.

the format can be:

```json
{'2.0.5': ['change1', 'changetwo'] }
````

**Comment by thecodeassassin** [comment]
the package is updated

**Comment by sergeyklay** [comment]
:+1:

**Comment by sergeyklay** [comment]
@thecodeassassin 2.0.2 has been released. You manually create every time a new version of package or 2.0.2 version of package is already done by using any automated scripts?

**Comment by sergeyklay** [comment]
@thecodeassassin 2.0.3 has been released :)

**Comment by sergeyklay** [comment]
```sh
$ lsb_release -d
Description:	Ubuntu 14.04.3 LTS
```

```sh
$ php --version
PHP 5.6.13-1+deb.sury.org~trusty+3 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

```sh
$ sudo apt-get install php5-phalcon
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-phalcon : Depends: phpapi-20121212
E: Unable to correct problems, you have held broken packages.
```
