### ISSUE TITLE
[2.0.0][BUG] Form render non-existing element results in segfault

### ISSUE THREAD

**Issue by AmazingDreams** [phalcon/cphalcon#10317]
When you call `\Phalcon\Forms\Form#render($someNonExistingElementName)` it results in a segfault instead of the exception. I used Volt as the template engine.

Steps to reproduce:
1. Create a form
2. Call the default render method in a volt template.

**Comment by AmazingDreams** [comment]
If I use the render function with a non existing element directly in the controller. It does throw the exception. So it seems to be related to Volt.

**Comment by andresgutierrez** [comment]
Could you please try again using the latest version in the 2.0.x branch?

**Comment by AmazingDreams** [comment]
Seems to work now! Great!
