### ISSUE TITLE
Controller initialize() method called once on Ratchet server. Mindset change proposal.

### ISSUE THREAD

**Issue by vicaba** [phalcon/cphalcon#10323]
I am using Phalcon in a different way that HTTP servers like Apache work, I'm not reloading all the code every request as I have a PHP server built with Ratchet. The problem I'm facing now is that initialize() method is not called on every request as my code is not reloading on every request. The problem is that piece of code: 

``` php
/* dispatcher.zep */
/**
 * Call the 'initialize' method just once per request
 */
if wasFresh === true {
    if method_exists(handler, "initialize") {
        handler->initialize();
    }
```

If `wasFresh` is set to false (which is a variable coming from the DI and it's a flag so it cannot be changed externally) the `initialize` method is not called. This was done to prevent calling `initialize` more than once during the same request. As I said, my problem is that everything is "the same" request as the server never dies and I don't bootstrap the application every time I get a new HTTP request.

I solved this problem calling the `initialize` method in the `beforeExecuteRoute` event but I was wondering if there is a possibility to add this mindset while developing Phalcon that not all applications will bootstrap all the application code on every request. As you might know, PHP 7 solves several memory leaks and it is faster, there are also some PHP servers arising like Ratchet and ReactPHP (I know that one is built on top of the other). Phalcon could be a great partner for those PHP servers (I'm actually using Phalcon in that way)

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
