### ISSUE TITLE
[ORM] Phalcon\Mvc\Model - getSource() blocks generic use of prefix

### ISSUE THREAD

**Issue by marianacapelo** [phalcon/cphalcon#10328]
Looking for a workaround to table prefixes that didnt exactly use the name class, I thought that it would be really simple to control it if not for the getSource method. Maybe I'm not thinking straight, but still, here is my post in the forum

http://forum.phalconphp.com/discussion/6711/table-prefix-without-getsource-method

**Comment by sergeyklay** [comment]
Implemented in the `3.2.x` branch.
