### ISSUE TITLE
[2.0.0] createQuery return blank result

### ISSUE THREAD

**Issue by FlexIDK** [phalcon/cphalcon#10324]
If create query (*): 
```php
        $query = $this->modelsManager->createQuery("
            SELECT
              a.*,
              SQRT(POW((a.address_lat - :latitude:), 2) + POW((a.address_lng - :longitude:), 2)) AS delta
                FROM Model\Address AS a
        ");

        $address = $query->execute(array(
            'latitude' => $latitude,
            'longitude' => $longitude,
        ));
```

result blank

If create query with field's: 

```php
        $query = $this->modelsManager->createQuery("
            SELECT
              a.address_id, a.address_lat, a.address_lng, a.address_street, a.address_house,
              SQRT(POW((a.address_lat - :latitude:), 2) + POW((a.address_lng - :longitude:), 2)) AS delta
                FROM Model\Address AS a
        ");

        $address = $query->execute(array(
            'latitude' => $latitude,
            'longitude' => $longitude,
        ));
```

result correct.

**Comment by andresgutierrez** [comment]
What do you mean by "result blank", do you have error_reporting(E_ALL) activated?

**Comment by FlexIDK** [comment]
> var_dump($address);

object(Phalcon\Mvc\Model\Resultset\Complex)[265]
  protected '_type' => int 0
  protected '_result' => null
  protected '_cache' => null
  protected '_isFresh' => boolean true
  protected '_pointer' => int -1
  protected '_count' => null
  protected '_activeRow' => null
  protected '_rows' => null
  protected '_errorMessages' => null
  protected '_hydrateMode' => int 0
  protected '_columnTypes' => null

with fields:

object(Phalcon\Mvc\Model\Resultset\Simple)[252]
  protected '_type' => int 0
  protected '_result' => 
    object(Phalcon\Db\Result\Pdo)[250]
      protected '_connection' => 
        object(Phalcon\Db\Adapter\Pdo\Mysql)[193]
          protected '_eventsManager' => 
            object(Phalcon\Events\Manager)[196]
              ...
          protected '_descriptor' => 
            array (size=6)
              ...
          protected '_dialect' => 
            object(Phalcon\Db\Dialect\MySQL)[195]
              ...
          protected '_connectionId' => int 0
          protected '_sqlStatement' => string 'SELECT `a`.`address_id` AS `address_id`, `a`.`address_lat` AS `address_lat`, `a`.`address_lng` AS `address_lng`, `a`.`address_street` AS `address_street`, `a`.`address_house` AS `address_house`, SQRT(POW((`a`.`address_lat` - :latitude), 2) + POW((`a`.`address_lng` - :longitude), 2)) AS `delta` FROM `address` AS `a` ORDER BY `delta` ASC LIMIT 10' (length=346)
          protected '_sqlVariables' => 
            array (size=2)
              ...
          protected '_sqlBindTypes' => null
          protected '_transactionLevel' => int 0
          protected '_transactionsWithSavepoints' => boolean false
          protected '_pdo' => 
            object(PDO)[194]
              ...
          protected '_affectedRows' => null
          protected '_type' => string 'mysql' (length=5)
          protected '_dialectType' => string 'mysql' (length=5)
      protected '_result' => null
      protected '_fetchMode' => int 2
      protected '_pdoStatement' => 
        object(PDOStatement)[249]
          public 'queryString' => string 'SELECT `a`.`address_id` AS `address_id`, `a`.`address_lat` AS `address_lat`, `a`.`address_lng` AS `address_lng`, `a`.`address_street` AS `address_street`, `a`.`address_house` AS `address_house`, SQRT(POW((`a`.`address_lat` - :latitude), 2) + POW((`a`.`address_lng` - :longitude), 2)) AS `delta` FROM `address` AS `a` ORDER BY `delta` ASC LIMIT 10' (length=346)
      protected '_sqlStatement' => string 'SELECT `a`.`address_id` AS `address_id`, `a`.`address_lat` AS `address_lat`, `a`.`address_lng` AS `address_lng`, `a`.`address_street` AS `address_street`, `a`.`address_house` AS `address_house`, SQRT(POW((`a`.`address_lat` - :latitude), 2) + POW((`a`.`address_lng` - :longitude), 2)) AS `delta` FROM `address` AS `a` ORDER BY `delta` ASC LIMIT 10' (length=346)
      protected '_bindParams' => 
        array (size=2)
          'latitude' => float 55.700877
          'longitude' => float 37.622405
      protected '_bindTypes' => null
      protected '_rowCount' => int 10
  protected '_cache' => null
  protected '_isFresh' => boolean true
  protected '_pointer' => int -1
  protected '_count' => int 10
  protected '_activeRow' => null
  protected '_rows' => null
  protected '_errorMessages' => null
  protected '_hydrateMode' => int 0
  protected '_model' => 
    object(Phalcon\Mvc\Model\Row)[251]
  protected '_columnMap' => 
    array (size=6)
      'address_id' => string 'address_id' (length=10)
      'address_lat' => string 'address_lat' (length=11)
      'address_lng' => string 'address_lng' (length=11)
      'address_street' => string 'address_street' (length=14)
      'address_house' => string 'address_house' (length=13)
      'delta' => string 'delta' (length=5)
  protected '_keepSnapshots' => boolean false

**Comment by andresgutierrez** [comment]
Requiring the full object ``a.*`` makes the ORM return a Phalcon\Mvc\Model\Resultset\Complex instance
