### ISSUE TITLE
[2.0.1] Phalcon\Forms\Element\Select multiple doesn't selected after post and validation failed

### ISSUE THREAD

**Issue by thxer** [phalcon/cphalcon#10332]
My code is:

in the form: 

``` php
  $this->add((new Element\Select("user[]", User::find(), [
            "multiple" => "multiple",
            "using" => ["id", "name"]
        ]))->setLabel("Users"));
```

in the action:

``` php
 if ($this->request->isPost()){
            if ($form->isValid($this->request->getPost())){
                $entity = new $entityClass;
                $form->bind($this->request->getPost(),$entity);
            }
}
```

**Comment by Knallcharge** [comment]
I have the same problem, I can use $element->setDefault($this->request->getPost('element')); to set the default values, but as soon as I use a PresenceOf-validator, I'm unable to validate the form.

**Comment by alimo2** [comment]
Even in phalcon 3.0.0 & php7 the same problem exists! no way can fix it?

**Comment by etshy** [comment]
Same probleme with the latest 3.2.5.
If I don't add brackets on my Select name, I only have one value, If I add the brackets, the validation fails.

**Comment by cgaugel** [comment]
Same problem here...

**Comment by deoomen** [comment]
Yeap. Phalcon have a problem with multiple values in forms. I managed with this problem by defining my own validator. Sample code below. It's not perfect but works.

    class MultipleFields extends Validator
    {
        public function validate(Validation $validator, $attribute)
        {
            $attribute = substr($attribute,0,-2);  // substr to get rid od '[]'
            $values = $validator->getValue($attribute);
        
            $errors = FALSE;
            $message = $this->getOption("message");
            if (!$message){
                $message = "Field contain wrong value";
            }
            foreach ($values as $key => $value){
                // check value
                // ...
                // if value is not valid then
                $errors = TRUE;
                $validator->appendMessage(
                    new Message($message, $attribute."[{$key}]", "MultipleFields")
                );
            }
        
            return !$errors;
        }
    }

**Comment by santhoshkumarkrishana** [comment]
I got it working by simply adding multiple as yes on the view file, nothing on the form file.

{{ xform.render('user_id', ['id':'user_id','name':'user_id','multiple':true]) }}
