### ISSUE TITLE
[2.0.1] Validation Issue When Updating Models

### ISSUE THREAD

**Issue by fefas** [phalcon/cphalcon#10334]
Please,

I'm having a problem when I try to update a register in database using phalcon model. My model class is:
```php
class UsuarioAdmin extends ModelBase
{
   public $id;
   public $nomepri;
   public $nomeult;
   public $email;
   public $senha;

   public function validation()
   {
      $this->validate(new \Phalcon\Mvc\Model\Validator\PresenceOf([
         "field"   => "nomepri",
         "message" => "This fields has to be informed."
      ]));
      $this->validate(new \Phalcon\Mvc\Model\Validator\PresenceOf([
         "field"   => "nomeult",
         "message" => "This fields has to be informed."
      ]));
      $this->validate(new \Phalcon\Mvc\Model\Validator\PresenceOf([
         "field"   => "email",
         "message" => "This fields has to be informed."
      ]));
      $this->validate(new \Phalcon\Mvc\Model\Validator\PresenceOf([
         "field"   => "senha",
         "message" => "This fields has to be informed."
      ]));
      $this->validate(new \Phalcon\Mvc\Model\Validator\Uniqueness([
         "field"   => "email",
         "message" => "This email already exists."
      ]));
      $this->validate(new \Phalcon\Mvc\Model\Validator\Email([
         'field'   => 'email',
         "message" => "This email is not valid."
      ]));
      return $this->validationHasFailed() != true;
   }
}
```
And the follow action in controller:

```php
class UsuariosController extends BaseController
{
   // ...
   public function putAction()
   {
      // get model
      $usuario = Model\UsuarioAdmin::findFirst($this->dispatcher->getParam('id'));

      // set new values
      $usuario->nomepri = $this->request->getPut('nomepri');
      $usuario->nomeult = $this->request->getPut('nomeult');
      $usuario->email   = $this->request->getPut('email');

      // update model
      if ($usuario->save() == false) {
         $err = [
            'msg' => 'Missing fields!',
            'fields'   => []
         ];
         foreach ($usuarios->getMessages() as $e)
            $err['fields'][$e->getField()] = $e->getMessage();
         throw new MyException(400, $err); // send json content with http status code 400
      }
   }
   // ...
}
```
This action is executed when the follow request is sent:
```
method: PUT
resource: /usuarios/<id>
params: {"nomepri": "value1", "nomeult": "value2", "email": "value3"}
```
The result I receive is:
```
Status Code: 400
Body: {"msg": "Missing fields", "fields": {"nomepri": "...", "nomeult": "...", "email": "..."}
```
This error just occur when the `$usuario->save()` is `false`. In other words: something wrong happens when I try to save the new data.

This code works on my mac OS X 10.10.3:
- php `5.6.8`
- mysql `5.6.24`
- phalcon `2.0.0`
- zephir `0.6.2a`

But not on our production server Ubuntu 14.04.2 LTS:
- php `5.5.9`
- mysql `5.5.43`
- phalcon `2.0.1`
- zephir `0.6.2a`

*I think the difference between my computer and the server operational system and the versions of php, mysql and phalcon should not interfere*

**This error happens with all models (I cited here only the simplest one).**

I don't know what is going wrong and we are exciting to put this application to production soon.

Thank you very much for the attention

**Comment by cspeak** [comment]
Try changing

```php
foreach ($this->getMessages() as $e)
```

to 

```php
foreach ($usuario->getMessages() as $e)
```

**Comment by fefas** [comment]
Sorry, I wrote it wrong.

The problem is not the access to `getMessage()` method, the problem is: always when I try to save an existing model (`$modelInstanceVariable->save()`), I receive `false` with exception of all validation fields.

**Comment by fefas** [comment]
Hello Andres, which information do you need? :)

**Comment by sergeyklay** [comment]
@fefas Could you please try latest Phalcon?

**Comment by fefas** [comment]
@sergeyklay .. this issue is very old and I do not have this trouble anymore .. I believe you can close it if no one reported similar problems.
