### ISSUE TITLE
[2.0] Fatal error on form->getElements after removing and adding elements (PHP 5.6)

### ISSUE THREAD

**Issue by kevinhatry** [phalcon/cphalcon#10339]
The code below creates a fatal error with PHP 5.6 cli or fpm : 

``` php
<?php

$cpt = 1;
$form = new \Phalcon\Forms\Form();

$hiddenStep = new \Phalcon\Forms\Element\Hidden('cs', array('value' => 1));
$form->add($hiddenStep);

// remove all elements
foreach ($form->getElements() as $element) {
  $form->remove($element->getName());
}

$newHid = new \Phalcon\Forms\Element\Hidden('hid', array('value' => 2));
$form->add($newHid);

display_elements($form, $cpt++);


function display_elements ($form, $cpt) {
  echo 'display num '.$cpt."\n";
  foreach ($form->getElements() as $n => $element) {
    echo $n.' : '.$element->getName()."\n";
  }
  echo '-------------'."\n";
}
```

Output : 

```
display num 1
PHP Fatal error:  Call to undefined method Phalcon\Forms\Form::getName() in bug_form.php on line 23
```

Line 23 is the one with the "echo".
As if $form->getElements() returned an array containing a Form object instead of one element.

---

PHP 5.6.4-1+deb.sury.org~precise+1 (cli) (built: Dec 21 2014 19:26:25) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

Build from Phalcon source, commit df311308270b534f299ddd80b8af24bcb5f2e2a1
But also present in the 2.0 built from commit 874c47d34496af2ed0b745a2dc9aa7c73dd56b36

Not present using Phalcon 1.3 OR PHP 5.3.

**Comment by dreamsxin** [comment]
Updated zephir lasted it's ok.

**Comment by kevinhatry** [comment]
Hi,

dreamsxin : thank you for the patch
apparently the patch was not merged into phalcon 2. Is there something to do on my side ?
