### ISSUE TITLE
[NFR] provide a method to get the matched controller name in beforeExecuteRoute micro app events

### ISSUE THREAD

**Issue by jeffreycahyono** [phalcon/cphalcon#1034]
When the route was matched in the regular Mvc, getting the controller name is very straightforward by calling $router->getControllerName().

But when dealing with matched contoller in micro application (mounted by using Micro Collection), there is no way to get which controller name of the matched route.  So the  the possible hack is like this.

``` php
function getMatchedControllerName($app){
    $handlerArr = (array)$app->getActiveHandler();
    if(isset($x[0]['_definition']))
        return $handlerArr[0]['_definition'];
}
```
##

**Comment by Elvander** [comment]
Any news on this feature?
