### ISSUE TITLE
PPHP 5.6 on Windows 7 & 8.1: PHP Warning:  PHP Startup: phalcon: Unable to initialize module (Module compiled with module API=20121212)

### ISSUE THREAD

**Issue by caaguado** [phalcon/cphalcon#10342]
When starting up Phalcon 2.0.1 with PHP 5.6 VC11 _NTS_ on Windows 7 and 8.1 the
following warning appears in the Command Prompt window:

PHP Warning:  PHP Startup: phalcon: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0

This happens only with the PHP _5.6_ Phalcon DLL, irrespectively of HTTP server used
(tested on Apache 1.3.41, Apache 2.4.12 (both apachelounge.com binaries) and nginx 1.9.0 for Windows and it sometimes makes these HTTP servers to fail with a 500 Internal Server Error
(not always).

Phalcon 2.0.1 PHP 5.3 VC9 PHP 5.4 VC9 NTS, PHP 5.5 VC11 NTS versions work OK, so I presume
this fault is probably a compile-time API configuration issue. The fault is completely new to the
Phalcon 2.0 branch (that is, it didn't fail in any versions prior to Phalcon 2.0.x)

Note that I haven't tested the 2.0.x thread-safe DLLs.

If you need further info or want me to test anything for you, please contact me at:
releases [at] xcentra [dot] com

Thanks and best regards, Carlos.

**Comment by andresgutierrez** [comment]
We'll compile the extensions again tonight and will let you know

**Comment by niden** [comment]
@caaguado Sorry for the delay. I have been having trouble compiling the VC11 ones. Some weird JScript error comes up when I run `configure` which doesn't allow me to continue with the compilation.

I will have to rebuild the environment this weekend and compile the DLLs. While I am at it I will use the latest PHP versions available.

**Comment by caaguado** [comment]
**@niden:** Thank you, no worries, we aren't in a hurry after all ;-)
Please note that PHP 5.6.9 was released yesterday [http://windows.php.net/download/]
Best regards.

**Comment by caaguado** [comment]
Hi Andrés, niden, any rough idea when will this be implemented? We missed 2.0.2. Please contact me back if you want me to test the fix on PHP 5.6,as I have my test environment readily available :-)
Thanks a lot again!

**Comment by phalcon** [comment]
Dlls are now available in the download page

**Comment by caaguado** [comment]
Hi again, sorry, but I can't find the DLLs in the official Windows DLL download page (http://phalconphp.com/en/download/windows) nor nowhere in Github. May you please kindly send me the actual download URL, so I can test the new 5.6 DLL? Thank you.

**Comment by andresgutierrez** [comment]
![image](https://cloud.githubusercontent.com/assets/213590/7934934/d110b410-08f1-11e5-9cc4-b923faa09e22.png)

http://static.phalconphp.com/files/phalcon_x86_vc11_php5.6.0_2.0.2_nts.zip

**Comment by caaguado** [comment]
Hi Andrés, the changelog for master 2.0.2 (https://github.com/phalcon/cphalcon/blob/master/CHANGELOG) doesn't mention this  bug #10342 as included/fixed.

Accordingly, I still see the same error on 2.0.2 (only for PHP 5.6), leading to a 500 Internal Server Error. This is from right now:

PHP Warning:  PHP Startup: phalcon: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match

Best regards.

**Comment by steffengy** [comment]
I don't think that ``PHP 5.6 VC11 NTS`` is what you are using, it looks like since
``PHP compiled with module API=20131226`` is complaining about a version missmatch of 2012 vs 2013, you are using a VC12 PHP with a VC11 module, therefore it logically doesn't work.

**Comment by caaguado** [comment]
Actually, the official php.net's PHP 5.6 package is built on VC11. I'm using the x86 (Win32) version:
http://windows.php.net/download/

However, I found out that the actual root cause for this fault was that I was using the Phalcon DLL for PHP 5.5 along with PHP 5.6. Once I pointed out my PHP.ini file to the Phalcon DLL for PHP 5.6 the problem has disappeared.

I'm sorry for this mistake; hope this outcome is useful to others. You can close this ticket.

Thanks really a lot for your support.

**Comment by andresgutierrez** [comment]
Nice you found it

**Comment by rprasanth** [comment]
@caaguado could you please explain the step briefly?? for solving the PHP compilation issue. I am getting the same problem for other toolkit

PHP Warning:  PHP Startup: BittWare: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0


php -v
PHP Warning:  PHP Startup: BittWare: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0
PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:21:29) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

**Comment by caaguado** [comment]
Hi, ultimately, it was caused by my own mistake, as I was using a wrong DLL version not matching the actual PHP version.

Just make sure that your Phalcon DLL matches PHP

BR // Carlos.

**Comment by Jeeva-Rathinam** [comment]
@caaguado @rprasanth  could you pls help me, how you solved the issue.

The PHP exe file you specified did not run correctly:
C:\wamp\bin\php\php7.0.25\php.exe

```
The php.ini used by your command-line PHP is: C:\wamp\bin\php\php7.0.25\php.ini

Program Output:
Warning: PHP Startup: mysql: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20151012
These options need to match
 in Unknown on line 0
```

**Comment by caaguado** [comment]
In my case I was inadvertedly using a wrong combination of Phalcon DLL in terms of PHP version, thread support (NTS vs TS) and/or "bitness" (32 vs 64 bits)... I can't remember exactly what it was right now...

Just make sure you use the right combination  and it should work OK for you, the same way it was worked spotlessly for me ever since ;-)

Good luck // Carlos.

**Comment by caaguado** [comment]
By the way, have a look at xtack, in which Phalcon works just fine out of the box:

https://xtack.org

We're about to release some updates between today and tomorrow, including Phalcon 3.2.4 ;-)
