### ISSUE TITLE
2.0.1 execute sql error

### ISSUE THREAD

**Issue by wolftail** [phalcon/cphalcon#10340]
hi, i run pdo->execute(sqls), but report error:
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  cannot insert multiple commands into a prepared statement

how can i run multiple commands sql? It is a sql file.

**Comment by andresgutierrez** [comment]
Why is this a bug?

**Comment by wolftail** [comment]
cannot insert multiple commands into a prepared statement. we need import sql file to db

**Comment by andresgutierrez** [comment]
This is not Phalcon related, maybe these links could help you:

* http://stackoverflow.com/questions/1176352/pdo-prepared-inserts-multiple-rows-in-single-query
* http://stackoverflow.com/questions/19680494/insert-multiple-rows-with-pdo-prepared-statements
* http://stackoverflow.com/questions/10060721/pdo-mysql-insert-multiple-rows-in-one-query
