### ISSUE TITLE
[NFR] When using controller as micro app handler, Controller::initialize should be invoked

### ISSUE THREAD

**Issue by jeffreycahyono** [phalcon/cphalcon#1036]
In the regular Mvc controller, controller::initialize() method is always invoked before calling the matched action but

when using controller as micro app handler, Controller::initialize is ignored.
It would be very helpfull if the initialize method in controller is also invoked.
##

**Comment by antonienko** [comment]
+1

**Comment by Jurigag** [comment]
Controller in micro application is just some generic class for storing methods. Controller as itself is NEVER created when executing your action. 

This needs to rewrite whole micro and probably introduce dispatcher to micro. This will just slow down application.

Not sure also why you need it. Controller extends Injectable, so you can access any service without any problem.

**Comment by Jurigag** [comment]
As i remember you had some plans for micro in 4.0.0 to refactor/rewrite it? @sergeyklay so maybe 4.0.0 this?

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
