### ISSUE TITLE
Phalcon\Security getSaltBytes

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#10365]
I'm running Phalcon 1.3.4. When calling getSaltBytes() I get a string of only 16 characters. I'm expecting a string > 22.

**Comment by andresgutierrez** [comment]
Can you try again using 2.0.0?

**Comment by ruudboon** [comment]
Will do soon. Waiting for phalcon-2.0.1 to get updated in the FreeBSD ports.
Is 1.3.4 EoL?

**Comment by andresgutierrez** [comment]
Maybe this could work for you? https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199578

**Comment by ruudboon** [comment]
Think this one can be closed
