### ISSUE TITLE
[2.0.x] Zephir\CompilerException 

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#10361]
$ git fetch 
$ git rebase origin/2.0.x
$ zephir fullclean 
$ zephir build
Zephir\CompilerException: Type "static-constant-access" is not supported.

**Comment by andresgutierrez** [comment]
Do you have the latest Zephir in master?

**Comment by sergeyklay** [comment]
Need rebuild Zephir?

**Comment by andresgutierrez** [comment]
No:

```php
cd zephir
git pull -u
```

**Comment by sergeyklay** [comment]
I have local Zephir repo in another place. I just updated Zephir and reinstall with `./install -c`. Now Phalcon builds ok. Thanks
