### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by quantumpacket** [phalcon/cphalcon#10378]
PHP7 betas should be rolling out next month, so I think at least master should support it for testing purposes.

In PHP7 `etc/standard/php_smart_str.h` has been renamed to `etc/standard/php_smart_string.h`.

Compilation for master, 2.0.0, and 2.0.x both fail with the following error:

> /tmp/compile_php_phalcon/cphalcon-2.0.x/build/64bits/phalcon.zep.c:184:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include <ext/standard/php_smart_str.h>
                                        ^
> compilation terminated.
make: *** [phalcon.lo] Error 1

I don't know C, otherwise would submit a patch. :)

**Comment by andresgutierrez** [comment]
This is not an easy task, migration to PHP7 must have to be done in Zephir: https://github.com/phalcon/zephir/issues/952

**Comment by salarmehr** [comment]
@andresgutierrez PHP 7 will be far faster than php6, also ther is HHVM and Hacklang. Also you have said migrating Zephir to PHP 7 is really time and effort demanding if not impossible.  What is the point in migrating Zephir to PHP7. Why not you port the lovely Phalon to plain PHP instead? A huge number of PHP programmer can contribute, we will have 16 github issues instead of 612 issues. Those who started large project using Phalcon have not to migrate all of their code to another PHP framework and Phalcon will live forever.   Phalcon can be "The PHP Framework For Web Artisans".

**Comment by andresgutierrez** [comment]
@salarmehr PHP7 is not faster than Zephir

**Comment by ovr** [comment]
@salarmehr facepalm

**Comment by salarmehr** [comment]
I did not claimed that PHP7 is faster than Zephir. I said "PHP 7 will be far faster than **php6**". I can understand you. You spend a long time developing the Zephir and I and others in Phalcon community investigate on Phalcon, we learned it deeply and used it as a foundation for our projects.  

In Zephir home page you introduced it as a single-purpose language: "designed to ease the creation and maintainability of extensions for PHP ". Its a programming language designed for anther language. If you plan to make it more versatile and writing pure-zephir web application possible its a different story. 

Please also take a look at this page: https://github.com/laravel/framework/issues/3295

**Comment by hdogan** [comment]
What is PHP **6**?

**Comment by salarmehr** [comment]
@hdogan My bad, PHP5 ◕‿◕

**Comment by Green-Cat** [comment]
Major :-1: to switching away from zephir.

**Comment by JCMais** [comment]
Guys: http://php.net/archive/2015.php#id2015-12-03-1

**Comment by Izopi4a** [comment]
@andresgutierrez , maybe if you create a list of "things" that has to be changed, with files and a very tiny hints, in a separated issue, create a new branch ( maybe 2.2 or directly on 2.1.x ), and see if any of us can help you make phalcon works with php7. Unless you are already at the finishing point :D

**Comment by andrefauth** [comment]
I'd like to see Phalcon/Zephir ported to PHP 7. I'm using it for 18 months on a very big project (the project wasn't launched yet) with 10 other developers and would like to be able to continue using it. And now that PHP 7 has been released, a lot of people will start using it. Of course, there is a window of time where the most paranoid, like myself, will not update to the new version so soon. But definitely we would like that to happen in a good time-frame.

**Comment by hakimio** [comment]
Zephir works with PHP 7 (phalcon/zephir/issues/756), but there is still some C code in Phalcon which needs to be fixed.
Hope someone will take a look at it sometime soon. Would love to be able to use PHP 7 with Phalcon.

**Comment by Rewt0r** [comment]
+1

**Comment by zjhzxhz** [comment]
+1

**Comment by phecho** [comment]
:+1:

**Comment by JakeGlascock** [comment]
+1

**Comment by phpclub** [comment]
+1

**Comment by sergeyklay** [comment]
@quantumpacket, @phpclub, @JakeGlascock, @phecho, @zjhzxhz, @Rewt0r, @hakimio,@andrefauth, @Izopi4a, @JCMais, @Green-Cat, @salarmehr, @hdogan

Hey mans, now you can try Phalcon 2.1.x with PHP 7. Just use latest Zephir with `zephir build —backend=ZendEngine3` command

**Comment by Jurigag** [comment]
Well, is there anything need for test or it should work as it is ?

**Comment by Izopi4a** [comment]
i will report tomorrow busy playing diablo 3 atm :D

**Comment by sergeyklay** [comment]
@Izopi4a :smile: anyway, create a separated issue

**Comment by phpclub** [comment]
zephir build —backend=ZendEngine3
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /zephir/Library/CompilerFile.php on line 173

**Comment by phpclub** [comment]
Under centos 6.x
zephir build —backend=ZendEngine3
Warning: Variable "_SESSION" assigned but not used in Phalcon\Session\Adapter::remove in /root/Soft/cphalcon/phalcon/session/adapter.zep on 204 [unused-variable]

	 }
	-^


PHP Notice:  Use of undefined constant APC_ITER_ALL - assumed 'APC_ITER_ALL' in /root/Soft/zephir/Library/ClassDefinition.php on line 1743
PHP Notice:  Use of undefined constant APC_LIST_ACTIVE - assumed 'APC_LIST_ACTIVE' in /root/Soft/zephir/Library/ClassDefinition.php on line 1743
Warning: Variable "beforeLine" assigned but not used in Phalcon\Debug::showTraceItem in /root/Soft/cphalcon/phalcon/debug.zep on 339 [unused-variable]

	   beforeLine, firstLine, afterLine, lastLine, i, linePosition, currentLine;
	-------------^


Warning: Function "\\sodium\\randombytes_buf" does not exist at compile time in /root/Soft/cphalcon/phalcon/security/random.zep on 118 [nonexistent-function]

	   return \\Sodium\\randombytes_buf(len);
	----------------------------------------^


Warning: Function "\\sodium\\randombytes_uniform" does not exist at compile time in /root/Soft/cphalcon/phalcon/security/random.zep on 309 [nonexistent-function]

	   return \\Sodium\\randombytes_uniform(len);
	--------------------------------------------^

**Comment by phpclub** [comment]
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c: В функции ‘zim_Phalcon_Annotations_Reader_parse’:
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:91: ошибка: несовместимый тип аргумента 1 функции ‘phannot_parse_annotations’
./phalcon/annotations/annot.h:44: замечание: expected ‘struct zval *’ but argument is of type ‘zval’
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:115: ошибка: несовместимый тип аргумента 1 функции ‘phannot_parse_annotations’
./phalcon/annotations/annot.h:44: замечание: expected ‘struct zval *’ but argument is of type ‘zval’
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:147: ошибка: несовместимый тип аргумента 1 функции ‘phannot_parse_annotations’
./phalcon/annotations/annot.h:44: замечание: expected ‘struct zval *’ but argument is of type ‘zval’
make: *** [phalcon/annotations/reader.lo] Ошибка 1
make: *** Ожидание завершения заданий...
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c: В функции ‘zim_Phalcon_Annotations_Reader_parse’:
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:91: ошибка: несовместимый тип аргумента 1 функции ‘phannot_parse_annotations’
./phalcon/annotations/annot.h:44: замечание: expected ‘struct zval *’ but argument is of type ‘zval’
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:115: ошибка: несовместимый тип аргумента 1 функции ‘phannot_parse_annotations’
./phalcon/annotations/annot.h:44: замечание: expected ‘struct zval *’ but argument is of type ‘zval’
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:147: ошибка: несовместимый тип аргумента 1 функции ‘phannot_parse_annotations’
./phalcon/annotations/annot.h:44: замечание: expected ‘struct zval *’ but argument is of type ‘zval’
make: *** [phalcon/annotations/reader.lo] Ошибка 1

**Comment by phpclub** [comment]
PHP 7.0.3 (cli) (built: Feb  3 2016 11:40:05) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by Jurigag** [comment]
In Phalcon 2.1 support for APC should be dropped in favor of APCu.

**Comment by Izopi4a** [comment]
@phpclub build and isntall this: https://github.com/krakjoe/apcu

also make sure you do zephir fullclean before zephir build

and i am not 100% sure but i think i increased my memory limit ( while building it ) i am not sure if problem was fixed as soon as i instakked apcu

**Comment by andrefauth** [comment]
Oh, nice. Thanks for the heads up. I'll let you know what happens.
Em 19/02/2016 18:46, "Serghei Iakovlev" <notifications@github.com> escreveu:

**Comment by phpclub** [comment]
Thanx

zephir fullclean
[root@conf cphalcon]# zephir build —backend=ZendEngine3
Warning: Variable "_SESSION" assigned but not used in Phalcon\Session\Adapter::remove in /root/Soft/cphalcon/phalcon/session/adapter.zep on 204 [unused-variable]

	 }
	-^


PHP Notice:  Use of undefined constant APC_ITER_ALL - assumed 'APC_ITER_ALL' in /root/Soft/zephir/Library/ClassDefinition.php on line 1743
PHP Notice:  Use of undefined constant APC_LIST_ACTIVE - assumed 'APC_LIST_ACTIVE' in /root/Soft/zephir/Library/ClassDefinition.php on line 1743
Warning: Variable "beforeLine" assigned but not used in Phalcon\Debug::showTraceItem in /root/Soft/cphalcon/phalcon/debug.zep on 339 [unused-variable]

	   beforeLine, firstLine, afterLine, lastLine, i, linePosition, currentLine;
	-------------^


Warning: Variable "possibleSetter" declared but not used in Phalcon\Mvc\Model::assign in /root/Soft/cphalcon/phalcon/mvc/model.zep on 440 [unused-variable]

	  var key, keyMapped, value, attribute, attributeField, possibleSetter, metaData, columnMap, dataMapped;
	----------------------------------------------------------------------^


Warning: Function "\\sodium\\randombytes_buf" does not exist at compile time in /root/Soft/cphalcon/phalcon/security/random.zep on 119 [nonexistent-function]

	   return \\Sodium\\randombytes_buf(len);
	----------------------------------------^


Warning: Function "\\sodium\\randombytes_uniform" does not exist at compile time in /root/Soft/cphalcon/phalcon/security/random.zep on 310 [nonexistent-function]

	   return \\Sodium\\randombytes_uniform(len);
	--------------------------------------------^


Copying new kernel files...
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Extension installed!
Add extension=phalcon.so to your php.ini
Don't forget to restart your web server

**Comment by phpclub** [comment]
Done! Where to download the stress tests for phalcon?

PHP Version 7.0.3
Web framework delivered as a C-extension for PHP
phalcon	enabled
Author	Phalcon Team and contributors
Version	2.1.0b
Build Date	Feb 25 2016 10:56:47
Powered by Zephir	Version 0.9.2a-dev

**Comment by nsossonko** [comment]
If someone puts out some DLLs for Windows I can stress test them on my project.

**Comment by sergeyklay** [comment]
@phpclub  https://github.com/phalcon/cphalcon/pull/11432 I do it. Unfortunately I do not have time to do it quickly.

**Comment by zjhzxhz** [comment]
Failed to compile in Deepin (an OS based on Debian 8).

PHP Information:

```
PHP 7.0.3 (cli) (built: Feb 16 2016 17:50:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

Zephir Information:

```
 _____              __    _
/__  /  ___  ____  / /_  (_)____
  / /  / _ \/ __ \/ __ \/ / ___/
 / /__/  __/ /_/ / / / / / /
/____/\___/ .___/_/ /_/_/_/
         /_/

Zephir version 0.9.2a-dev
```

OS Information:

```
Distributor ID:	Deepin
Description:	Deepin 15.1
Release:	15.1
Codename:	jessie
```

Compile Command:

```
$ /tmp/zephir/bin/zephir build —backend=ZendEngine3
```

Error Log:

```
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c: In function ‘zim_Phalcon_Annotations_Reader_parse’:
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:91:55: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
   ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(classAnnotations, &comment, &_0$$3, &_1$$3 TSRMLS_CC);
                                                       ^
In file included from /tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:115:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(propertyAnnotations, &comment, &_3$$7, &_4$$7 TSRMLS_CC);
                                                         ^
In file included from /tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:147:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(methodAnnotations, &comment, &_7$$12, &_8$$12 TSRMLS_CC);
                                                         ^
In file included from /tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
make: *** [phalcon/annotations/reader.lo] Error 1
make: *** Waiting for unfinished jobs....
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c: In function ‘zim_Phalcon_Annotations_Reader_parse’:
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:91:55: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
   ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(classAnnotations, &comment, &_0$$3, &_1$$3 TSRMLS_CC);
                                                       ^
In file included from /tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:115:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(propertyAnnotations, &comment, &_3$$7, &_4$$7 TSRMLS_CC);
                                                         ^
In file included from /tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:147:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(methodAnnotations, &comment, &_7$$12, &_8$$12 TSRMLS_CC);
                                                         ^
In file included from /tmp/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
make: *** [phalcon/annotations/reader.lo] Error 1
```

**Comment by zjhzxhz** [comment]
Failed to compile it in OS X 10.11.

PHP Information:

```
PHP 7.0.3 (cli) (built: Feb 16 2016 09:03:13) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

Zephir Information:

```
 _____              __    _
/__  /  ___  ____  / /_  (_)____
  / /  / _ \/ __ \/ __ \/ / ___/
 / /__/  __/ /_/ / / / / / /
/____/\___/ .___/_/ /_/_/_/
         /_/

Zephir version 0.9.2a-dev
```

Error Log:

```
Build complete.
Don't forget to run 'make test'.


PHP Warning:  PHP Startup: Unable to load dynamic library '/private/tmp/zephir/Library/../parser/zephir_parser.so' - dlopen(/private/tmp/zephir/Library/../parser/zephir_parser.so, 9): Symbol not found: _zval_used_for_init
  Referenced from: /private/tmp/zephir/Library/../parser/zephir_parser.so
  Expected in: flat namespace
 in /private/tmp/zephir/Library/../parser/zephir_parser.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/private/tmp/zephir/Library/../parser/zephir_parser.so' - dlopen(/private/tmp/zephir/Library/../parser/zephir_parser.so, 9): Symbol not found: _zval_used_for_init
  Referenced from: /private/tmp/zephir/Library/../parser/zephir_parser.so
  Expected in: flat namespace
 in /private/tmp/zephir/Library/../parser/zephir_parser.so in Unknown on line 0
PHP Fatal error:  Uncaught Error: Call to undefined function Zephir\zephir_parse_file() in /private/tmp/zephir/Library/CompilerFile.php:173
Stack trace:
#0 /private/tmp/zephir/Library/CompilerFile.php(563): Zephir\CompilerFile->genIR(Object(Zephir\Compiler))
#1 /private/tmp/zephir/Library/Compiler.php(314): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
#2 /private/tmp/zephir/Library/Compiler.php(353): Zephir\Compiler->preCompile('phalcon/acl.zep')
#3 /private/tmp/zephir/Library/Compiler.php(900): Zephir\Compiler->recursivePreCompile('phalcon')
#4 /private/tmp/zephir/Library/Compiler.php(1105): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#5 /private/tmp/zephir/Library/Compiler.php(1224): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#6 /private/tmp/zephir/Library/Compiler.php(1305): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#7 /private/tmp/zephir/Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild in /private/tmp/zephir/Library/CompilerFile.php on line 173

Fatal error: Uncaught Error: Call to undefined function Zephir\zephir_parse_file() in /private/tmp/zephir/Library/CompilerFile.php:173
Stack trace:
#0 /private/tmp/zephir/Library/CompilerFile.php(563): Zephir\CompilerFile->genIR(Object(Zephir\Compiler))
#1 /private/tmp/zephir/Library/Compiler.php(314): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
#2 /private/tmp/zephir/Library/Compiler.php(353): Zephir\Compiler->preCompile('phalcon/acl.zep')
#3 /private/tmp/zephir/Library/Compiler.php(900): Zephir\Compiler->recursivePreCompile('phalcon')
#4 /private/tmp/zephir/Library/Compiler.php(1105): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#5 /private/tmp/zephir/Library/Compiler.php(1224): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#6 /private/tmp/zephir/Library/Compiler.php(1305): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#7 /private/tmp/zephir/Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild in /private/tmp/zephir/Library/CompilerFile.php on line 173
```

**Comment by Izopi4a** [comment]
@zjhzxhz 

```

cd _PATH_TO_ZEPHIR_/parser
make clean
phpize --clean

```

try to compile again

**Comment by lajosbencz** [comment]
Debian x64 Jessie
PHP Version 7.0.3
Zephir 0.9.2a-dev
Phalcon 2.1.x

Everything compiled just fine, the Phalcon extension is loaded without error and shows up in ```php -m```, but when calling ```Phalcon\Mvc\Application::handle()``` i get a segmentation fault.

Any hints on how to get a stacktrace / give you guys useful info?

**Comment by zjhzxhz** [comment]
@Izopi4a 

Here's the output of executing `clean` command:

```
➜  parser git:(master) make clean
make: *** No rule to make target `clean'.  Stop.
➜  parser git:(master) phpize --clean
Cleaning..
```

And it's still not working. I got the same error message as previous.

**Comment by Izopi4a** [comment]
@zjhzxhz do you have extension=/private/tmp/zephir/Library/../parser/zephir_parser.so in your php.ini by any chance ? if so remove it.

if you type `php -v` do you get 7.0.3 ..., also `which php-config` and `which phpize` should also show the path to your php 7.

do you have skype or something that we can chat and give it a try to fix it ?

**Comment by kaioken** [comment]
just wanted to say , it worked perfectly 

thanks

**Comment by phpclub** [comment]
Under ubuntu 14.04
cphalcon# zephir build —backend=ZendEngine3
Warning: Variable "_SESSION" assigned but not used in Phalcon\Session\Adapter::remove in /root/Soft/cphalcon/phalcon/session/adapter.zep on 204 [unused-variable]

	 }
	-^


PHP Notice:  Use of undefined constant APC_ITER_ALL - assumed 'APC_ITER_ALL' in /root/Soft/zephir/Library/ClassDefinition.php on line 1743
PHP Notice:  Use of undefined constant APC_LIST_ACTIVE - assumed 'APC_LIST_ACTIVE' in /root/Soft/zephir/Library/ClassDefinition.php on line 1743
Warning: Variable "beforeLine" assigned but not used in Phalcon\Debug::showTraceItem in /root/Soft/cphalcon/phalcon/debug.zep on 339 [unused-variable]

	   beforeLine, firstLine, afterLine, lastLine, i, linePosition, currentLine;
	-------------^


Warning: Function "\\sodium\\randombytes_buf" does not exist at compile time in /root/Soft/cphalcon/phalcon/security/random.zep on 118 [nonexistent-function]

	   return \\Sodium\\randombytes_buf(len);
	----------------------------------------^


Warning: Function "\\sodium\\randombytes_uniform" does not exist at compile time in /root/Soft/cphalcon/phalcon/security/random.zep on 309 [nonexistent-function]

	   return \\Sodium\\randombytes_uniform(len);
	--------------------------------------------^

Copying new kernel files...
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information

at Library/Compiler.php(1244)
#0 Library/Compiler.php(1305): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#1 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#2 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#3 compiler.php(21): Zephir\Bootstrap::boot()
#4 {main}


int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:147:31: error: incompatible type for argument 1 of 'phannot_parse_annotations'
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(methodAnnotations, &comment, &_7$$12, &_8$$12 TSRMLS_CC);
                               ^
In file included from /root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected 'struct zval *' but argument is of type 'zval'
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
make: *** [phalcon/annotations/reader.lo] Ошибка 1
root@smialex:~/Soft/cphalcon# cat compile-errors.log 
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c: In function 'zim_Phalcon_Annotations_Reader_parse':
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:91:29: error: incompatible type for argument 1 of 'phannot_parse_annotations'
   ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(classAnnotations, &comment, &_0$$3, &_1$$3 TSRMLS_CC);
                             ^
In file included from /root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected 'struct zval *' but argument is of type 'zval'
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:115:31: error: incompatible type for argument 1 of 'phannot_parse_annotations'
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(propertyAnnotations, &comment, &_3$$7, &_4$$7 TSRMLS_CC);
                               ^
In file included from /root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected 'struct zval *' but argument is of type 'zval'
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:147:31: error: incompatible type for argument 1 of 'phannot_parse_annotations'
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(methodAnnotations, &comment, &_7$$12, &_8$$12 TSRMLS_CC);
                               ^
In file included from /root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected 'struct zval *' but argument is of type 'zval'
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
make: *** [phalcon/annotations/reader.lo] Ошибка 1
make: *** Ожидание завершения заданий...
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c: In function 'zim_Phalcon_Annotations_Reader_parse':
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:91:29: error: incompatible type for argument 1 of 'phannot_parse_annotations'
   ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(classAnnotations, &comment, &_0$$3, &_1$$3 TSRMLS_CC);
                             ^
In file included from /root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected 'struct zval *' but argument is of type 'zval'
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:115:31: error: incompatible type for argument 1 of 'phannot_parse_annotations'
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(propertyAnnotations, &comment, &_3$$7, &_4$$7 TSRMLS_CC);
                               ^
In file included from /root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected 'struct zval *' but argument is of type 'zval'
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:147:31: error: incompatible type for argument 1 of 'phannot_parse_annotations'
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(methodAnnotations, &comment, &_7$$12, &_8$$12 TSRMLS_CC);
                               ^
In file included from /root/Soft/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected 'struct zval *' but argument is of type 'zval'
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^

**Comment by freshman20** [comment]
No installation problems with ubuntu 14.04 here but with defaults events like beforeExecuteRoute.
It seems as if they are not called, onConstruct in controller didn't work too.

**Comment by Izopi4a** [comment]
opened a bug here about contruct methods https://github.com/phalcon/zephir/issues/1203

i need those in order to test the rest

**Comment by Izopi4a** [comment]
@andresgutierrez could you please fix this https://github.com/phalcon/zephir/issues/1203 so we can test the rest ?

**Comment by tflori** [comment]
+1

**Comment by freshman20** [comment]
I believe I have found another bug.
Action
`$this->view->title = 'foo';`
in View should work this
`{{ title }}`
but it caused an error:
 '<b>Notice</b>:  Undefined variable: title'
Workaround:
`{{ view.title }}`

**Comment by Jurigag** [comment]
What happens if you use:
```
$view->setVar("title", "foo");
```

**Comment by freshman20** [comment]
same error

**Comment by Jurigag** [comment]
Well we need to deal currently with seg faults in tests, then if in test it will fail too i will add it to this list:

https://github.com/phalcon/cphalcon/issues/11550

**Comment by Jurigag** [comment]
For me view doesn't even work in php 7. Such a code:

```
use Phalcon\Mvc\View;

$di = new \Phalcon\Di\FactoryDefault();

$di->set('view',function(){
    $view=new \Phalcon\Mvc\View\Simple;
    $view->registerEngines([
        '.volt'=>'Phalcon\Mvc\View\Engine\Volt'
    ]);
    return $view;
});
/** @var \Phalcon\Mvc\View\Simple $view */
$view = $di->get('view');
echo $view->render('test.volt');
```

Displays nothing form test.volt even its adasdasdasdasd

**Comment by tobasar** [comment]
@freshman20 #11465

**Comment by googlle** [comment]
+1

**Comment by sergeyklay** [comment]
Introduced in v3.0.0
