### ISSUE TITLE
build cphalcon " error: âZEND_FE_ENDâ undeclared here (not in a function)  ZEND_FE_END"

### ISSUE THREAD

**Issue by iammote** [phalcon/cphalcon#10387]
I' try install in CentOS
by refer link ( http://phalconphp.com/en/download) but I'm get this error after run  "sudo ./install"

In file included from /usr/include/php/Zend/zend.h:303:0,
                 from /usr/include/php/main/php.h:35,
                 from /root/software/cphalcon/build/64bits/phalcon.zep.c:169:
/usr/include/php/Zend/zend_object_handlers.h:147:17: note: expected âchar *â but argument is of type âconst char *â
 ZEND_API zval **zend_std_get_static_property(zend_class_entry *ce, char *property_name, int property_name_len, zend_bool silent TSRMLS_DC);
                 ^
/root/software/cphalcon/build/64bits/phalcon.zep.c: In function âpp_syntax_errorâ:
/root/software/cphalcon/build/64bits/phalcon.zep.c:98723:0: warning: "TOKEN" redefined [enabled by default]
 #define TOKEN (ppminor.pp0)
 ^
/root/software/cphalcon/build/64bits/phalcon.zep.c:29228:0: note: this is the location of the previous definition
 #define TOKEN (aaminor.aa0)
 ^
/root/software/cphalcon/build/64bits/phalcon.zep.c: In function âvv_syntax_errorâ:
/root/software/cphalcon/build/64bits/phalcon.zep.c:116831:0: warning: "TOKEN" redefined [enabled by default]
 #define TOKEN (vvminor.vv0)
 ^
/root/software/cphalcon/build/64bits/phalcon.zep.c:98723:0: note: this is the location of the previous definition
 #define TOKEN (ppminor.pp0)
 ^
/root/software/cphalcon/build/64bits/phalcon.zep.c: At top level:
/root/software/cphalcon/build/64bits/phalcon.zep.c:130892:1: error: âZEND_FE_ENDâ undeclared here (not in a function)
 ZEND_FE_END
 ^
make: *** [phalcon.lo] Error 1

please help me resolve this problem.

**Comment by iammote** [comment]
I'm use php 5.3.3
and this my result of " php-config"

Usage: /usr/bin/php-config [OPTION]
Options:
  --prefix            [/usr]
  --includes          [-I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib]
  --ldflags           []
  --libs              [-lcrypt   -lcrypt -ledit -lncurses -lgmp -lbz2 -lz -lpcre -lm -ldl -lnsl  -lxml2 -lz -lm -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto -lssl -lcrypto -lxml2 -lz -lm -lcrypt -lxml2 -lz -lm -lcrypt ]
  --extension-dir     [/usr/lib64/php/modules]
  --include-dir       [/usr/include/php]
  --php-binary        [/usr/bin/php]
  --php-sapis         [cli cgi]
  --configure-options [--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --target=x86_64-redhat-linux-gnu --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --cache-file=../config.cache --with-libdir=lib64 --with-config-file-path=/etc --with-config-file-scan-dir=/etc/php.d --disable-debug --with-pic --disable-rpath --without-pear --with-bz2 --with-exec-dir=/usr/bin --with-freetype-dir=/usr --with-png-dir=/usr --with-xpm-dir=/usr --enable-gd-native-ttf --without-gdbm --with-gettext --with-gmp --with-iconv --with-jpeg-dir=/usr --with-openssl --with-pcre-regex=/usr --with-zlib --with-layout=GNU --enable-exif --enable-ftp --enable-magic-quotes --enable-sockets --enable-sysvsem --enable-sysvshm --enable-sysvmsg --with-kerberos --enable-ucd-snmp-hack --enable-shmop --enable-calendar --without-sqlite --with-libxml-dir=/usr --enable-xml --with-system-tzdata --enable-force-cgi-redirect --enable-pcntl --with-imap=shared --with-imap-ssl --enable-mbstring=shared --enable-mbregex --with-gd=shared --enable-bcmath=shared --enable-dba=shared --with-db4=/usr --with-xmlrpc=shared --with-ldap=shared --with-ldap-sasl --with-mysql=shared,/usr --with-mysqli=shared,/usr/lib64/mysql/mysql_config --enable-dom=shared --with-pgsql=shared --enable-wddx=shared --with-snmp=shared,/usr --enable-soap=shared --with-xsl=shared,/usr --enable-xmlreader=shared --enable-xmlwriter=shared --with-curl=shared,/usr --enable-fastcgi --enable-pdo=shared --with-pdo-odbc=shared,unixODBC,/usr --with-pdo-mysql=shared,/usr/lib64/mysql/mysql_config --with-pdo-pgsql=shared,/usr --with-pdo-sqlite=shared,/usr --with-sqlite3=shared,/usr --enable-json=shared --enable-zip=shared --without-readline --with-libedit --with-pspell=shared --enable-phar=shared --with-tidy=shared,/usr --enable-sysvmsg=shared --enable-sysvshm=shared --enable-sysvsem=shared --enable-posix=shared --with-unixODBC=shared,/usr --enable-fileinfo=shared --enable-intl=shared --with-icu-dir=/usr --with-enchant=shared,/usr --with-recode=shared,/usr]
  --version           [5.3.3]
  --vernum            [50303]

**Comment by andresgutierrez** [comment]
PHP 5.3.3 is not supported anymore, can you please update at least to 5.3.21?

**Comment by iammote** [comment]
Thank you. I'll try :)
