### ISSUE TITLE
PHQL Complex Delete Query Problem

### ISSUE THREAD

**Issue by bahadirbirsoz** [phalcon/cphalcon#10380]
I am not able to run complex delete queries with PHQL. 
```
$this->modelsManager->executeQuery("
            DELETE 
                Translation
            FROM 
                Project\Models\Data\Translation as Translation
            INNER JOIN 
                Project\Models\Data\TranslationParam as TranslationParam ON 
                    TranslationParam.translation_param_id = Translation.translation_param_id
            WHERE
                Translation.language_id = :lang_id:
                    AND
                TranslationParam.translation_param_type_id = :type_id:
            ",array(
                "lang_id" => $langId,
                "type_id" => $typeId
                ));
```

When I replace the model names with table names, query runs successfully. All the model classes are declared. Here is the error message I receive : 

> Syntax error, unexpected token IDENTIFIER(Translation), near to ' FROM Projectz\Models\Data\Translation as Translation INNER JOIN Projectz\Models\Data\TranslationParam as TranslationParam ON TranslationParam.translation_param_id = Translation.translation_param_id WHERE Translation.language_id = :lang_id: AND TranslationParam.translation_param_type_id = :type_id: ', when parsing: DELETE Translation FROM Projectz\Models\Data\Translation as Translation INNER JOIN Projectz\Models\Data\TranslationParam as TranslationParam ON TranslationParam.translation_param_id = Translation.translation_param_id WHERE Translation.language_id = :lang_id: AND TranslationParam.translation_param_type_id = :type_id: (523)

When I remove the first model alias Translation from query and it starts like `Delete From`, there error message is as follows:
> Syntax error, unexpected token INNER, near to ' JOIN Projectz\Models\Data\TranslationParam as TranslationParam ON TranslationParam.translation_param_id = Translation.translation_param_id WHERE Translation.language_id = :lang_id: AND TranslationParam.translation_param_type_id = :type_id: ', when parsing: DELETE FROM Projectz\Models\Data\Translation as Translation INNER JOIN Projectz\Models\Data\TranslationParam as TranslationParam ON TranslationParam.translation_param_id = Translation.translation_param_id WHERE Translation.language_id = :lang_id: AND TranslationParam.translation_param_type_id = :type_id: (492)

I've tried a lot of different ways. I don't want to run two queries (one select and one delete) for a job that can be done with only one query. 

Any suggestions?

**Comment by andresgutierrez** [comment]
That syntax is not supported in PHQL, but you can use:

```php
$this->db->execute("
            DELETE 
                translation
            FROM 
                translation
            INNER JOIN 
                translation_param ON 
                    translation_param.translation_param_id = translation.translation_param_id
            WHERE
                translation.language_id = :lang_id
                    AND
                translationParam.translation_param_type_id = :type_id
            ",array(
                "lang_id" => $langId,
                "type_id" => $typeId
                ));
```
