### ISSUE TITLE
Please refresh the Package Opensuse. 

### ISSUE THREAD

**Issue by dewid1985** [phalcon/cphalcon#10399]
There version 1.3.4 Please upgrade to 2.0. 
Thanks in advance!!!

**Comment by andresgutierrez** [comment]
@mruz

**Comment by mruz** [comment]
Done.

You can update to version 2.0.2 now:
```sh
zypper up php5-phalcon
```

There is also 1.3.4, so you can install with force:
```sh
zypper in -f <package-with-version>
```

**Comment by dewid1985** [comment]
Thanks!!!

**Comment by andresgutierrez** [comment]
@mruz Thanks
