### ISSUE TITLE
[2.0.1] - Phalcon\Mvc\Collection custom validator compatibility error

### ISSUE THREAD

**Issue by ginodeis** [phalcon/cphalcon#10390]
After update to Phalcon 2.0.1, I have noticed that using custom model validator classes to validate Phalcon\Mvc\Collection objects raise an error like this:

```
PHP Catchable fatal error:  Argument 1 passed to <class>::validate() 
must implement interface Phalcon\Mvc\ModelInterface
```

Until version 1.3.5, I had used some custom model validators from [Incubator](https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Mvc/Model/Validator) to validate Phalcon\Mvc\Collection objects with no problem.

#### Sample code:

**Collection class**
```php
class Throttles extends \Phalcon\Mvc\Collection
{
	...

	public function validation()
    {

        // username (native model validator)
        $this->validate(new \Phalcon\Mvc\Model\Validator\PresenceOf(array(
            'field'   => 'username',
            'message' => 'Username not specified'
        )));

        // server_ip (incubator custom model validator)
        $this->validate(new \Phalcon\Mvc\Model\Validator\IP(array(
            'field'             => 'server_ip',
            'version'           => IP::VERSION_4 | IP::VERSION_6, // v6 and v4. The same if not specified
            'allowReserved'     => false,   // False if not specified. Ignored for v6
            'allowPrivate'      => false,   // False if not specified
            'message'           => 'IP address has to be correct'
        )));

        return ($this->validationHasFailed() != true);
    }

	...

}
```

**Incubator custom model validator**
[Source code from Incubator](https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/Model/Validator/IP.php)

**Error Raised**
```
PHP Catchable fatal error:  Argument 1 passed to Phalcon\Mvc\Model\Validator\IP::validate()
must implement interface Phalcon\Mvc\ModelInterface, instance of Throttles.
```

Note that the IP custom model validator implements Phalcon\Mvc\Model\ValidatorInterface with the same signature that class [cphalcon/phalcon/mvc/model/validator/presenceof.zep](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/validator/presenceof.zep), but this validator not raise any error.

Thanks.

**Comment by AKeeman** [comment]
The point is that a validator for a collection needs an Phalcon\Mvc\Model\ValidatorInterface, as of SidRoberts' commit [ https://github.com/phalcon/cphalcon/commit/fc50e58b5768d15e50395c4f3b87364b19bf4840 ].
Collections shouldn't use Model stuff.

654    -	protected function validate(validator) -> void
648    +	protected function validate(<Model\ValidatorInterface> validator) -> void

**Comment by Nafania** [comment]
@AKeeman and how we need to use validation for collections?

```
$this->validate();
````

in validate method waits ValidationInterface, but Validator with this Interface waits Mvc\Model\ValidatorInterface

How i supposed to deal with it?

**Comment by KorsaR-ZN** [comment]
@Nafania 
Please replace in `\Phalcon\Mvc\Model\Validator\IP`

`public function validate(ModelInterface $record)` 
to 
`public function validate(\Phalcon\Mvc\EntityInterface $record)`

**Comment by KorsaR-ZN** [comment]
@Nafania 
Please replace in `\Phalcon\Mvc\Model\Validator\IP`

`public function validate(ModelInterface $record)`
to
`public function validate(\Phalcon\Mvc\EntityInterface $record)`

**Comment by Nafania** [comment]
@KorsaR-ZN i can't find ```\Phalcon\Mvc\EntityInterface``` and still receive ```must be compatible with Phalcon\Mvc\Model\ValidatorInterface::validate(Phalcon\Mvc\ModelInterface $record)``` error.

What version of phalcon do you using?

**Comment by KorsaR-ZN** [comment]
@Nafania Latest from `2.0.x` branch
Then remove the type checking `public function validate($record)`

I added the validator to the core see #10572

**Comment by Nafania** [comment]
@KorsaR-ZN I'm using own custom validator. If i remove type checking i still receive the same error.

**Comment by KorsaR-ZN** [comment]
@Nafania What version of phalcon?
Could show code your validator?

**Comment by Nafania** [comment]
@KorsaR-ZN 
>What version of phalcon?

```php --ri phalcon

phalcon

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 2.0.3
Build Date => Jun 26 2015 11:08:35
Powered by Zephir => Version 0.6.3a```

> Could show code your validator?

```php
class Collection extends \Phalcon\Mvc\Collection {
public function validation()
    {
        $this->validate(new Unique([
            'field' => ['id', 'type']
        ]));

        return !$this->validationHasFailed();
    }
}
```

```php
use Phalcon\Mvc\Model\Validator,
	Phalcon\Mvc\Model\Message;
use Phalcon\Mvc\Model\ValidatorInterface;

class Unique extends Validator implements ValidatorInterface
{
	/**
	 * Validates that the record is unique
	 *
	 * @param $record
	 * @return boolean
	 */
	public function validate($record)
	{
		$field = $this->getOption('field');
		$count = $record::count([[$field => $record->readAttribute($field)]]);
		if ($count > 1) {
			$message = $this->getOption('message');
			$this->appendMessage(new Message($message, $field));
			return false;
		}
		return true;
	}
}
```

**Comment by KorsaR-ZN** [comment]
## v2.0.3
`class Unique extends Validator implements ValidatorInterface`
replace to
`class Unique extends Validator`

## v2.0.4+
`class Unique extends Validator`
replace to
`class Unique extends Validator implements ValidatorInterface`

`public  function  validate ($record)`
replace to
`public  function  validate (\Phalcon\Mvc\EntityInterface $record)`

**Comment by KorsaR-ZN** [comment]
@Nafania Unfortunately in 2.0.3 is not supported collection validation (bug interfaces)
Please build from 2.0.x branch or wait for a stable release 2.0.4

**Comment by Nafania** [comment]
@KorsaR-ZN 
>Unfortunately in 2.0.3 is not supported collection validation (bug interfaces)

I've already find out that.

Thanks for your help! I will try 2.0.4.

**Comment by andresgutierrez** [comment]
Phalcon 2.0.4 released

**Comment by amitvbn** [comment]
Does any one able to resolve this issue?
I am too facing same issue.

**Comment by amitvbn** [comment]
I am using 2.0.7, but still facing same issue.

**Comment by Nafania** [comment]
@amitvbn in 2.0.7 that already fixed and now worked for me, here is my validator code

```/**
 * Class Unique
 * @package app\common\components\validators
 */
class Unique extends Validator implements ValidatorInterface
{
	/**
	 * Validates that the record is unique
	 *
	 * @param $record
	 * @return boolean
	 */
	public function validate(\Phalcon\Mvc\EntityInterface $record)
	{
        $condition = $this->getOption('condition');
        /**
         * @var \Phalcon\Mvc\Collection $record
         */
        $count = $record->getConnection()->selectCollection($record->getSource())->count($condition);

		if ($count) {
			$message = $this->getOption('message');
            $message = ($message ?: 'The ' . implode(', ', $condition) . ' must be unique');
			$this->appendMessage($message);
			return false;
		}
		return true;
	}
}
```
