### ISSUE TITLE
[2.0.2] Error building -- Unable to make [ phalcon.lo ]  Error 1

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#10401]
```bash
git clone https://github.com/phalcon/cphalcon.git --depth=1
cd cphalcon/build
sudo sh ./install
```

```sh
/bin/bash /tmp/cphalcon/build/64bits/libtool --mode=compile gcc  -I. -I/tmp/cphalcon/build/64bits -DPHP_ATOM_INC -I/tmp/cphalcon/build/64bits/include -I/tmp/cphalcon/build/64bits/main -I/tmp/cphalcon/build/64bits -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DPHALCON_RELEASE -DHAVE_CONFIG_H  -march=native -mtune=native -O2 -finline-functions -fomit-frame-pointer -fvisibility=hidden   -c /tmp/cphalcon/build/64bits/phalcon.zep.c -o phalcon.lo 
libtool: compile:  gcc -I. -I/tmp/cphalcon/build/64bits -DPHP_ATOM_INC -I/tmp/cphalcon/build/64bits/include -I/tmp/cphalcon/build/64bits/main -I/tmp/cphalcon/build/64bits -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -finline-functions -fomit-frame-pointer -fvisibility=hidden -c /tmp/cphalcon/build/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
/tmp/cphalcon/build/64bits/phalcon.zep.c: In function 'vv_syntax_error':
/tmp/cphalcon/build/64bits/phalcon.zep.c:117547:0: warning: "TOKEN" redefined [enabled by default]
 #define TOKEN (vvminor.vv0)
 ^
/tmp/cphalcon/build/64bits/phalcon.zep.c:99562:0: note: this is the location of the previous definition
 #define TOKEN (ppminor.pp0)
 ^
/tmp/cphalcon/build/64bits/phalcon.zep.c: At top level:
/tmp/cphalcon/build/64bits/phalcon.zep.c:3291:13: warning: 'zephir_pow_function_ex' used but never defined [enabled by default]
 static void zephir_pow_function_ex(zval *return_value, zval *zbase, zval *zexp TSRMLS_DC);
             ^
make: *** [phalcon.lo] Error 1
```

**Comment by virgofx** [comment]
Also -- would it be possible to test for these issues? I have various production systems that pull from master and latest stable release ... all of which fail to build when this happens.

**Comment by andresgutierrez** [comment]
This is now fixed in master, could you please try again?

**Comment by virgofx** [comment]
Confirm fixed.

**Comment by eeusta** [comment]
Hi,
What is the solution?

https://github.com/phalcon/cphalcon/issues/10401

**Comment by virgofx** [comment]
@eeusta Ensure you have the latest release >= 2.03

**Comment by tiagocaetano** [comment]
i have the same problem !! How i can resolve this situation ?

config.status: executing libtool commands
/bin/bash /etc/cphalcon/build/32bits/libtool --mode=compile gcc  -I. -I/etc/cphalcon/build/32bits -DPHP_ATOM_INC -I/etc/cphalcon/build/32bits/include -I/etc/cphalcon/build/32bits/main -I/etc/cphalcon/build/32bits -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -DPHALCON_RELEASE -DHAVE_CONFIG_H  -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden   -c /etc/cphalcon/build/32bits/phalcon.zep.c -o phalcon.lo 
libtool: compile:  gcc -I. -I/etc/cphalcon/build/32bits -DPHP_ATOM_INC -I/etc/cphalcon/build/32bits/include -I/etc/cphalcon/build/32bits/main -I/etc/cphalcon/build/32bits -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden -c /etc/cphalcon/build/32bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
^CMakefile:181: recipe for target 'phalcon.lo' failed
make: *** [phalcon.lo] Error 1

**Comment by eeusta** [comment]
Whats gcc builder version?

8 Ekim 2015 Perşembe tarihinde, Tiago Caetano <notifications@github.com>
yazdı:

**Comment by Doncode** [comment]
I have the same problem

**Comment by sergeyklay** [comment]
@Doncode Use [Zephir](http://github.com/phalcon/zephir/):
```sh
$ git clone https://github.com/phalcon/cphalcon.git
$ git checkout <REQUIRED_BRANCH>
$ zephir build
# Or for PHP 7
$ zephir build --backend=ZendEngine3
```
