### ISSUE TITLE
[2.x / master] ModelInterface and CollectionInterface differential

### ISSUE THREAD

**Issue by arius86** [phalcon/cphalcon#10406]
Compare find() and findFirst() methods in:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/collectioninterface.zep
and
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/modelinterface.zep

Differential in Interface definitions (`array $parameters` vs `undefined $parameters`) make repository pattern not possible to implement without proper proxy. Would be useful to unify this.

**Comment by sergeyklay** [comment]
:+1:

**Comment by archdevil666pl** [comment]
:+1:

**Comment by dschissler** [comment]
@sergeyklay Add to Phalcon 4 milestone.  There is another issue with CollectionInterface which I recommended being added.  I don't understand these issue exactly but it seems like Phalcon 4 should just break these things all at once so that it can be cleaned up.

**Comment by niden** [comment]
This will not be implemented. We will remove the `Mvc\Collection` from the framework since there is no real support for Mongo for now. The driver we have been using has not been maintained for the last 5 years.
