### ISSUE TITLE
[2.0.x] view getContent return empty on linux

### ISSUE THREAD

**Issue by partynetwork** [phalcon/cphalcon#10419]
This problem occurs on Linux(Centos 7) platform. I don't get any value for {{content}}. I've configured all the settings. Not sure if it is cause by 
<pre>$view->setViewsDir(APPLICATION_PATH . '/modules/auth/views/'); 
$view->setPartialsDir("../../../common/views/partials/");
$view->setLayoutsDir("../../../common/views/layouts/");
</pre>
or not. However, everything is working perfectly on Windows-based host.
but it work on windows hosting

PHP 5.6.9
Apache 2.4

**Comment by andresgutierrez** [comment]
What version of Phalcon are you using? All your paths are case sensitive?

**Comment by partynetwork** [comment]
Yes, my folder is lowercase , 
I used Phalcon 2.0.2

**Comment by andresgutierrez** [comment]
Could you please post a small repo with the problem that allow us to reproduce issue?

**Comment by dreamsxin** [comment]
I guess the reason of no content is a view file not found.

**Comment by partynetwork** [comment]
I have solved this problem, 
I have changed my dispatcher to 
<pre>$dispatcher->setActionName(\Phalcon\Text::uncamelize($dispatcher->getActionName()));</pre>

Thank you for your help
