### ISSUE TITLE
[1.3.4]Default filter doesn't convert float correctly in Http\Request

### ISSUE THREAD

**Issue by friparia** [phalcon/cphalcon#10422]
I want to get an integer in my controller like this:
```php
$num = $this->request->getPost('num', 'int');
```
but when i passed a float like 1.1111111 to this action,  what i want is the digit 1, but  this function actually returns 11111111, it just remove the decimal point in the parameter.

So i need to cast the float myself by using
```php
$num = (int)$this->request->getPost('num');
```

**Comment by andresgutierrez** [comment]
In Phalcon 2 you can use:

```php
$num = $this->request->getPost('num', 'int!');
```

To do the same thing

**Comment by friparia** [comment]
:+1: nice job in Phalcon 2. We will update to phalcon 2.
