### ISSUE TITLE
Windows DLL Downloads Broken

### ISSUE THREAD

**Issue by synergycns** [phalcon/cphalcon#10420]
None of the Windows DLL Downloads on phalconphp.com seem to be working, they're all returning 404 errors.

**Comment by andresgutierrez** [comment]
We're having some problems with our CDN, meanwhile you can download them from here: https://github.com/phalcon/website/tree/master/public/files

**Comment by synergycns** [comment]
Perfect. Thanks for the quick response.

**Comment by andresgutierrez** [comment]
It must be now fixed
