### ISSUE TITLE
Bug: phpize writes phplibdir wrong

### ISSUE THREAD

**Issue by KlavsKlavsen** [phalcon/cphalcon#10425]
when you generate configure.in from phpize - it writes phplibdir to be set from `pwd` /modules. This works when just running install - but I would like to write an rpm package spec file.. it works with just "using your install script" - except that phplibdir is wrong - so those are installed in the build dir - ignoring INSTALL_ROOT setting to makefile.

I can't seem to figure out (or find docu) on how phpize gets that phplibdir setting from config.m4 (or whereever).

If you could point me in the right direction - I would gladly submit pull request after testing on my end :)

**Comment by andresgutierrez** [comment]
The `php-config` binary in PATH must belong to the same version of `phpize`

**Comment by KlavsKlavsen** [comment]
It does. I have not build the phpize or any PHP package myself - it's centos 7 plain packages.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
