### ISSUE TITLE
[2.0.x][RFC] Phalcon2 REST

### ISSUE THREAD

**Issue by akaNightmare** [phalcon/cphalcon#10426]
Propose implement REST Controller with the next functionality:
- [ ] REST Auth
  - [ ] HTTP basic auth over HTTPS
  - [ ] Granted via Token (OAuth2) - BEARER
  - [ ] Query Authentication
- [ ] REST Controller
  - [ ] Content negotiation and Data formatting
  - [ ] Index (or List) Action - list of resources(GET) 
  - [ ] ViewAction - returns defails of resource (GET with ID) 
  - [ ] DeleteAction - delete resource(DELETE with ID) 
  - [ ] CreateAction - create resource (POST)
  - [ ] UpdateAction - update resource (PUT with ID)
  - [ ] built-in support for the OPTIONS and HEAD
  - [ ] HATEOAS
  - [ ] JSON/XML/HTML response format
  - [ ] Data, HTTP caching _TBD_
  - [ ] Rate limited _TBD_
- [ ] ERROR HANDLING (with the following HTTP codes response WIKI - http://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
  - [ ] 200 - OK
  - [ ] 201 - success created (POST only)
  - [ ] 204 - success deleted (DELETE only)
  - [ ] 304 - resource was not modified
  - [ ] 400 - bad request
  - [ ] 401 - auth failed
  - [ ] 403 - forbidden
  - [ ] 404 - not found
  - [ ] 405 - default - (method not allowed)
  - [ ] 422 - validation failed
  - [ ] 422 - validation failed
  - [ ] 415 - unsupported media type
  - [ ] 429 - too many requests 
  - [ ] 500 - internal server error
- [ ] Vrrsioning

REST API best pratices - http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

**Comment by Green-Cat** [comment]
I have a custom implementation, in php, but it would be great to have it backed straight into the framework.

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
