### ISSUE TITLE
[1.3.4] Incorrect path used for compiled templates if 'compilePath' does not have trailing slash

### ISSUE THREAD

**Issue by tselina** [phalcon/cphalcon#10430]
$volt = new \Phalcon\Mvc\View\Engine\Volt($view, $di);
$volt->setOptions(array(
    'compiledPath' => realpath('/path/to/cache/'),
));

Actually compiled templates will be found inside of directory '/path/to/' . I expect it still should go into '/path/to/cache/' as this directory is valid for the cached templates (exists and writable)

The only difference is that realpath('/path/to/cache/') removes trailing slash and returns '/path/to/cache' which is still correct path.

If I remove realpath() then cache stored into correct directory '/path/to/cache/'

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2?

**Comment by tselina** [comment]
I'm sorry, but I don't have version 2.0. And I expect that our website
won't be upgraded to that version in nearest future
31 трав. 2015 19:14, користувач "Andres Gutierrez" <notifications@github.com>
написав:

**Comment by andresgutierrez** [comment]
@tselina we can't help you then
