### ISSUE TITLE
First link on Google for "phalcon documentation offline" is broken

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10437]
https://media.readthedocs.org/pdf/phalcon-php-framework-documentation/latest/phalcon-php-framework-documentation.pdf

Is there a Phalcon 2.0 offline documentation yet?

**Comment by andresgutierrez** [comment]
It seems read the docs changed the link to that file, it must be: https://media.readthedocs.org/pdf/phalcon-php-framework-documentation/latest/phalcon-php-framework-documentation.pdf

**Comment by dschissler** [comment]
The link works.
