### ISSUE TITLE
Phalcon doesn't understand (My)SQL "INTERVAL" form

### ISSUE THREAD

**Issue by hakimio** [phalcon/cphalcon#10432]
The following valid MySQL condition doesn't work in Phalcon:

```php
ToDoModel::find(['date <= DATE_SUB( CURDATE(), INTERVAL 2 MONTH )']);
```
Above query results in `unexpected token INTEGER(2), near to ' MONTH` error.

**Comment by Green-Cat** [comment]
Interval is a mysql only feature. PHQL currently only supports statements which are sql standard.

**Comment by hakimio** [comment]
Ok, I guess then this issue can be closed as invalid.

**Comment by Green-Cat** [comment]
You might however be interested in this https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Db#dialectmysqlextended

**Comment by hakimio** [comment]
Thanks, I'll take a look at the library.
Anyway, as a workaround, the MySQL query mentioned above can be replaced with the following PHP code which works as expected:

```php
$before2Months = date('Y-m-d', strtotime('-2 months'));
ToDoModel::find([
    'date <= ?0',
    'bind' => [$before2Months]
]);
```

**Comment by Green-Cat** [comment]
According to the docs (http://dev.mysql.com/doc/refman/5.6/en/fulltext-search.html) "Full-text indexes can be used only with InnoDB or MyISAM tables". Innodb is pretty popular as a storage engine afaik.

**Comment by hakimio** [comment]
Yes, InnoDB is popular and my knowledge about MySQL full text search is a bit outdated (https://dev.mysql.com/doc/refman/5.5/en/fulltext-search.html). Apparently support for fulltext indexes was introduced in InnoDB with MySQL version 5.6.

**Comment by andresgutierrez** [comment]
Interval keyword will not be supported, however you can use custom functions to support this syntax: https://blog.phalconphp.com/post/phalcon-2-0-3-released

**Comment by dugwood** [comment]
I've just tested it in Phalcon\Db\RawValue, and it's working (in the model). I hit the same issue as above, but I manage to go around with ADDDATE(NOW(), 1) which adds days (but not month), however it's working in RawValue, so that's a great point.

**Comment by hakimio** [comment]
@dugwood Check andresgutierrez's link to see how to add custom functions to PHSQL.

**Comment by dugwood** [comment]
@hakimio sure, I knew that, but it was broken in 2.0.3 when I migrated from 1.3, so I ended up with the solution of days with ADDDATE/SUBDATE. But today I tried the INTERVAL in the RawValue, thought it would hang, and no. So I'm pleased :-)
