### ISSUE TITLE
Phalcon\Http\Client\Request->getBaseUri( )

### ISSUE THREAD

**Issue by Izabela-Roxana-Ilies** [phalcon/cphalcon#10431]
Fatal error: Call to undefined method Phalcon\Http\Uri::toString() in /library/Phalcon/Http/Client/Request.php on line 58

**Comment by Green-Cat** [comment]
There is no Phalcon\Http\Uri class. 
What is /library/Phalcon/Http/Client/Request.php seems like an external library, since the whole of phalcon is in zephir not php.

**Comment by Green-Cat** [comment]
Oh I see, this is an issue with the incubator library. Please report the issue there.
