### ISSUE TITLE
migrations types problems

### ISSUE THREAD

**Issue by stefanchiriac** [phalcon/cphalcon#10448]
Hello,

- when generating migrations is not finding the type 'TIMESTAMP', 'BIGINT', and other types
- there is no Column::TYPE_TIMESTAMP, but I got over it by just writing 'TIMESTAMP',
- default for TYPE_INTEGER does nothing if I set an int value
- when I add 'CURRENT_TIMESTAMP' as default value I get an mysql error. 

     `SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'`

Edit: Seems like if I don't set anything on default, is setting by itself CURRENT_TIMESTAMP and an attribute 'on update CURRENT_TIMESTAMP' which is not what I want at all.

It is a way to get over this, or to be implemented in 2.0.3?
Thanks

**Comment by andresgutierrez** [comment]
Can you please post this in the devtools repo? github.com/phalcon/phalcon-devtools

**Comment by stefanchiriac** [comment]
but this is part of cphalcon. Is not about phalcon-devtools, but that cphalcon doesn't have support integrated for these at all.

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.4 branch
