### ISSUE TITLE
PHQL placeholders are not consistant with PDO

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#10447]
Currently PHQL uses `:foo:` and `?INDEX` while PDO uses `:foo:`  and `?` as placeholders. This confuse programmers. Please make PDO formats valid in PHQL.

**Comment by dschissler** [comment]
PHQL is more than just a wrapper around PDO.  For example; the MongoDB adapter.

**Comment by salarmehr** [comment]
@dschissler I know that it can do more. But why not to follow its syntax for placeholder? This lead to chaos.
