### ISSUE TITLE
Phalcon framework as php 

### ISSUE THREAD

**Issue by liesislukas** [phalcon/cphalcon#10457]
Phalcon is blazing fast because it's pre-compiled and already in memory. That's great. I use it for every new project for last 2 years. Can't find any way to use it on shared hosting. 

Maybe there is some way to export zephir to plain php? 

I'm PHP guy, don't know details about C stuff, so just asking if there is any automated way to export Phalcon as simple php framework (symfony, zend). Call it "fall back" version of phalcon for situations when developer can't say if user will or won't have phalcon extension installed.

**Comment by andresgutierrez** [comment]
There's no framework in PHP you can use as a drop-in replacement for the extension. Many components in Phalcon cannot be translated easily to PHP.

**Comment by stefanchiriac** [comment]
there are quite a few ways to use it on shared hosts. Just google it a bit.
All you have to do is compile the extension for the shared host OS version + PHP version (do that in a virtual machine), get the .so and include it in your php.ini.
I'm doing that myself and is working.

**Comment by liesislukas** [comment]
stefanchiriac, how can .so file be added to shared hosting provider, when the only thing you have is ftp login/password? A lot of users can't edit php.ini either. 

andresgutierrez, but it would require a lot of time and manual working? any automatic way to "build" php files from zephir?

**Comment by stefanchiriac** [comment]
through ftp you upload the phalcon.so and then in php.ini add
`extension=/path/to/phalcon.so`
That's the solution you'll find all over internet
It surprises me there are shared hosts that doesn't let you modify php.ini. But there are tons of alternatives so anyone can switch to a shared host that let you do that. Also with $5 you can find an average vps.

The idea of having a fallback to php I had it too and many others before me. Someone even started to make a clone of phalcon on php, but is not easy and I would rather prefer that time to be spent on improving the actual framework or making php extensions dedicated to phalcon.

**Comment by andresgutierrez** [comment]
@liesislukas Phalcon is not just Zephir, there are components such as the parsers, escaper, kernel features, etc that are written in pure C, an automatic translation is just not feasible

**Comment by niden** [comment]
@liesislukas Along with what others have suggested, you could always get a virtual box, that will allow you to have root access and install whatever you want on it.

I understand that this is not what you want to read, I get it. However, please consider the following
- Virtual machines are abundant on the internet and extremely cheap. Check the hosting page on the phalcon website for some alternatives.
- Indeed there is no substitute or translator in the PHP world for Phalcon. There has been a discussion on where Zephir will go and we talked about having some sort of parser flag which could generate Zephir to PHP. This is just talk though, and has not materialized - I am sure it will in the future.
- If you really want to stay on shared hosting, cPanel has a guide on how to install phalcon on it.

HTH

**Comment by liesislukas** [comment]
I'm using virtual boxes for development and vps for production, not a problem for myself. But I was interested what would be if I would create app which would be downloadable. So requirements would be a little harder to understand when just "upload & go to your domain".

Thanks for all Your answers & great framework. I believe Phalcon will be popular enough to get to all shared hosting as default package with php :)
