### ISSUE TITLE
Cookies getValue() returns null without any error

### ISSUE THREAD

**Issue by softdream** [phalcon/cphalcon#10452]
Hello, i test this little peace of code: 

```php

if(!$this->cookies->has('t')){
       $this->cookies->set('t', 'test', (10*(365*(24*(60*60))))+time(), '/', null, '*');
}
$c = $this->cookies->get('t');
var_dump($c); //got object with protected _value with "test"
var_dump($c->getValue()); //got null

```

So as you can see in example, when i call getValue i got NULL but, i can see the cookie value in dump of object, can you help me how can i solve this ? I trying to access the protected variable by build custom Cookie class but it doesnt work still i got null.

My bootstrap cookies registration:

```php
$di->set('cookies', function() {
    $cookies = new \Phalcon\Http\Response\Cookies();
    $cookies->useEncryption(false);
    return $cookies;
});
```

**Comment by andresgutierrez** [comment]
The problem seems to be domain = "*", without that parameter it works

**Comment by softdream** [comment]
Yeah, sorry you're right so then this is desultory question,
