### ISSUE TITLE
Error in phalcon scaffold

### ISSUE THREAD

**Issue by mpparent** [phalcon/cphalcon#10458]
Phalcon Devtools (2.0.0) PHP 5.5 Mysql 5.5.34 Apache 2.2.27 I installed with compose I created a project I Created models with the phalcon models commands, it works. When I want to scaffold, the only answer I have is

Error: Parameter 'index' must be a string.

Like that: [~/public_html/xxxxxxxxxxxxxxx.com/etht]# phalcon scaffold Membre Phalcon DevTools (2.0.0)
Error: Parameter 'index' must be a string
```

If I create Controller first with the command phalcon controller, it goes a little bit further, it create 2 files: [~/public_html/xxxxxxxxxxxxxxx.com/etht]# ../phalcon-devtools/phalcon controller Membre ```

Phalcon DevTools (2.0.0)
Success: Controller "Membre" was successfully created. [~/public_html/xxxxxxxxxxxxxxx.com/etht]# ../phalcon-devtools/phalcon scaffold Membre Phalcon DevTools (2.0.0)

/home/wdiqcca/publichtml/xxxxxxxxxxxxxxx.com/etht/app/views/layouts/membre.phtml /home/wdiqcca/publichtml/xxxxxxxxxxxxxxx.com/etht/app/views/membre/index.phtml

Error: Parameter 'index' must be a string

So I look for index parameter, didn't find it. What am I missing?

**Comment by andresgutierrez** [comment]
could you please post this in the devtools repo? https://github.com/phalcon/phalcon-devtools

**Comment by mpparent** [comment]
Sorry. You have absolutly reason, i didn't see my mistake. 

Sorry again. 

WDI ce n'est pas que des sites web, des noms de domaine et de l'hébergement! C'est aussi un service informatique pour le dépannage, l'installation de réseaux, d'ordinateurs et autres équipements électroniques et de logiciels. Nousnous occupons aussi de l'acquisition de vos produits informatiques. N'hésitez pas à nous contacter!

Marc Philippe Parent ing. jr, M.Sc
WebDev Intégration Ltée
http://www.wdi.qc.ca
(418)655-5607
================================
Avis relatif à la confidentialité :
Ce message contient des renseignements qui peuvent être confidentiels ou protégés. Il s'adresse au destinataire prévu ou à une personne autorisée à le recevoir en son nom.  Si vous l'avez reçu par erreur, nous vous prions d'en informer l'auteur dans les meilleurs délais, de ne pas divulguer son contenu et de le supprimer de votre système.
========================= 
Notice of Confidentiality :
This message contains information that may be confidential or privileged.  It is intended for the exclusive use of the addressee or any person entitled to receive it.  If you received this message in error,  please inform the author as soon as possible, do not disclose its contents and delete it from your system.

**Comment by sergeyklay** [comment]
But nor Phalcon nor Devtools hasn't this message. Search with ` grep -nir 'must be a string' path/`

**Comment by mpparent** [comment]
it seams to be in composer.phar. I diagnose it, correct everything, still have the error. I will contact them

**Comment by mpparent** [comment]
but is it suppose to use composer when scaffolding?
