### ISSUE TITLE
CSRF Token mismatch on >= 2.0.1

### ISSUE THREAD

**Issue by fichtner** [phalcon/cphalcon#10455]
Version: 2.0.1 and up (as applied on OPNsense/FreeBSD)

Expected behaviour: POST succeed with CSRF Token

Actual behaviour: POST is not accepted due to missing CSRF Token

Reporter: @adschellevis

Details:

on page rendering put the following data into our page (using setVars and render in Volt template “default.volt”):

    $this->security->getTokenKey()
    $this->security->getToken()

and make JQuery send this data with every request:

    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}" );
    xhr.setRequestHeader("X-CSRFTokenKey", "{{ csrf_tokenKey }}" );

Then on post, I see the headers in my post message (example):

    X-CSRFToken	 BWoewuthOGp8IJ3N
    X-CSRFTokenKey	 80dSQ7HfcFfka1Vr

But when phalcon is asked about it using $this->security->checkToken from another controller it doesn’t know about it anymore.

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/43955298f03d753727fcac39dbdf4d2f36dd8c0b

@andresgutierrez Default behaviour changed without being in the patch notes; this seems to fix the issue?

**Comment by andresgutierrez** [comment]
Yes, the path is regenerated every time it's checked. Passing false in the third parameter avoids that.

**Comment by fichtner** [comment]
Alright, confirmed working, thanks for the heads-up. :)
