### ISSUE TITLE
Dispatcher call wrong namespace?

### ISSUE THREAD

**Issue by thxer92** [phalcon/cphalcon#10451]
``` php
try {
    $content = $app->handle()->getContent();
} catch (\Exception $e){
    print $e;
}
print $app->router->getNamespaceName(); // MyOtherNamespace\Frontend\Controllers
print $app->dispatcher->getNamespaceName(); // MyNamespace\Modules\Core\Controller
```
Exception:
 Uncaught exception 'Phalcon\Mvc\Dispatcher\Exception' with message 'MyNamespace\Modules\Core\Controller\ErrorController handler class cannot be loaded

in phalcon/mvc/application.zep:320:  
``` zep
dispatcher->setNamespaceName(router->getNamespaceName());
```

Where is the error? 

My system info:
PHP: 5.6.9
Phalcon: 2.0.2

**Comment by Surt** [comment]
Maybe you are overriding the dispatcher namespace somewhere?
I do it on the modules registerServices for example:

```php
$dependencyInjector['dispatcher']->setDefaultNamespace($namespace);
```

**Comment by thxer92** [comment]
I have, in Module::registerServices(): 

``` php
$dispatcher->setDefaultNamespace('MyOtherNamespace\Frontend\Controllers');
```

But it contains the correct namespace.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
