### ISSUE TITLE
Print fields on model when call save if allowEmptyStringValues sets to array()

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#10456]
I got other bug, it seems related with $this->allowEmptyStringValues(array()) (#10442) because when I have this line on initialize method, and then call for save it, I got a print_r with fields of my model.

**Comment by phalcon** [comment]
I suggest you compile from the development branchs using `zephir build`

**Comment by gtux** [comment]
This issue was fixed on 2.0.3, I do not have any more this problem, thanks very much

**Comment by andresgutierrez** [comment]
Nice
