### ISSUE TITLE
[2.0.3] Routes not working

### ISSUE THREAD

**Issue by stefanchiriac** [phalcon/cphalcon#10462]
I just upgraded to Phalcon 2.0.3 and routes no longer work; they all send me to homepage '/'. Using ubuntu 14.04 with apache.
also $this->router->getMatchedRoute() now return a string instead of an object
`host=localhost;dbname=xxx`

I tried both master and 2.0.x and both have same problem. Something changed on how things get handled?

Edit: I think something is messed up with latest version of Zephir. I compiled the extension again without Zephir and now it says that is Phalcon 2.0.2 and working
Also, I tried to compile 2.0.0 with zephir and same problem.

**Comment by dreamsxin** [comment]
Please submit the route define code?

**Comment by stefanchiriac** [comment]
I just did a pull to zephir and cphalcon, compiled again and is working fine. I guess it has been fixed.
