### ISSUE TITLE
The method 'skipAttributes' doesn't exist on model

### ISSUE THREAD

**Issue by vbojan** [phalcon/cphalcon#10467]
I just upgraded to Phalcon 2.0.2 and instantly started receiving the following error:
```
exception 'Phalcon\\Mvc\\Model\\Exception' with message 'The method 'skipAttributes' doesn't exist on model...
```

In 2.0.0 and 2.0.1 I had problems with skipAttributes and skipAttributesOnCreate not working as expected:
https://github.com/phalcon/cphalcon/issues/10249#issuecomment-104235738
However, now it throws an error.

**Comment by andresgutierrez** [comment]
The method is protected, you have to call it inside the class scope: https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model.zep#L3227-L3239

**Comment by vbojan** [comment]
Thank you Andres.

A minor refactoring fixed it.
I hope skipAttributes will get fixed in the next version.

**Comment by andresgutierrez** [comment]
What is requiring a fix?

**Comment by vbojan** [comment]
This one:
https://github.com/phalcon/cphalcon/issues/10249
