### ISSUE TITLE
How to change DB FetchMode in DbAdapter ?

### ISSUE THREAD

**Issue by chakravarthy28** [phalcon/cphalcon#10475]
Hi 
How can i set default fetch mode in DbAdapter is it Possible

```php
$di->set('db', function () use ($config) {
    return new DbAdapter(array(
        'host' => $config->database->host,
        'username' => $config->database->username,
        'password' => $config->database->password,
        'dbname' => $config->database->dbname
    ));
});
```

**Comment by pauliuspetronis** [comment]
```
$di->set('db', function () use ($config) {
    return new DbAdapter(array(
        'host' => $config->database->host,
        'username' => $config->database->username,
        'password' => $config->database->password,
        'dbname' => $config->database->dbname,
        'options' => array(
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ
        )
    ));
});
```

**Comment by chakravarthy28** [comment]
Thanks. please help me
If using object to find records. query like     
$settings = Settings::find(
            array(
        "conditions" => "status = 1"
    ));
when i print the result, it display 
Phalcon\Mvc\Model\Resultset\Simple Object
(
    [_type:protected] => 1
    [_result:protected] => Phalcon\Db\Result\Pdo Object
        (
            [_connection:protected] => Phalcon\Db\Adapter\Pdo\Mysql Object
                (
                    [_eventsManager:protected] => 
                    [_descriptor:protected] => Array
                        (
                            [host] => localhost
                            [username] => root
                            [password] => root
                            [dbname] => pezydir
                            [options] => Array
                                (
                                    [19] => 2
                                )

                        )

                    [_dialect:protected] => Phalcon\Db\Dialect\Mysql Object
                        (
                            [_escapeChar:protected] => `
                        )

                    [_connectionId:protected] => 1
                    [_sqlStatement:protected] => 
                    [_sqlVariables:protected] => 
                    [_sqlBindTypes:protected] => 
                    [_transactionsWithSavepoints:protected] => 0
                    [_pdo:protected] => PDO Object
                        (
                        )

                    [_affectedRows:protected] => 
                    [_transactionLevel:protected] => 0
                    [_type:protected] => mysql
                    [_dialectType:protected] => mysql
                )

            [_result:protected] => 
            [_fetchMode:protected] => 2
            [_pdoStatement:protected] => PDOStatement Object.........

why its not coming like this

stdClass Object
(
    [Id] => 1
    [Postcode] => AB101AA
    [Latitude] => 57.148235000000000
    [Longitude] => -2.096648000000000
    [GridRef] => NJ942063
    [County] => 
    [District] => Aberdeen City
    [Ward] => George St/Harbour
    [Country] => Scotland
    [Region] => Aberdeen North
)

why its getting lot of objects in it  [_dialect:protected] => Phalcon\Db\Dialect\Mysql Object

how to stop this ?

**Comment by pauliuspetronis** [comment]
[About Phalcon Models](https://docs.phalconphp.com/en/latest/reference/models.html)
>Models are intended to work on a database high layer of abstraction. If you need to work with databases at a lower level check out the [Phalcon\Db](https://docs.phalconphp.com/en/latest/api/Phalcon_Db.html) component documentation.

**Comment by pauliuspetronis** [comment]
Simple example:
```
$statement =  $db->prepare("SELECT * FROM settings WHERE status = ?")->execute(array(1));
$settings = $statement->fetchAll(); // $settings =  array(0 => stdClass Object ([Id] => 1, ....), 1 => stdClass Object ([Id] => 2, ....))
```
