### ISSUE TITLE
[2.0.x] Hash returning different results

### ISSUE THREAD

**Issue by caleuanhopkins** [phalcon/cphalcon#10470]
Can anyone explain why this is happening?

![](https://cldup.com/lhlfoJFgHB-3000x3000.png)
![](https://cldup.com/IFT3C2ylHX-3000x3000.png)

**Comment by andresgutierrez** [comment]
Phalcon\Security returns different hashes for the same input, this ensures that if someone has access to the database it cannot figure out other passwords generated using the same original input by just looking for a previous generated known one.

**Comment by caleuanhopkins** [comment]
@andresgutierrez so can we compare two string encoded with hash to see if the original strings are the same?

**Comment by caleuanhopkins** [comment]
@andresgutierrez urgh I've just found `$this->security->checkHash()`. Figured this out now, having a bit of a brain dump day, sorry!
