### ISSUE TITLE
bug on the request->hasFiles() in version 2.0.1 and 2.0.2

### ISSUE THREAD

**Issue by meyssamhf** [phalcon/cphalcon#10471]
hi, 
I install new version 2.0.2 on local xampp, but in upload file and request->hasFiles() line always return true(1), i test it again with version of 1.3.3 but it's Ok.
I think it's a bug in core class....

**Comment by dreamsxin** [comment]
Can you please sumbit html code to test?

**Comment by aleksandrzen** [comment]
@meyssamhf, try this:
```PHP
$this->request->hasFiles(true);
```

**Comment by meyssamhf** [comment]
yes. it's work...... thanks aleksandrzen
and Where did you find it?

**Comment by aleksandrzen** [comment]
@meyssamhf 
I was faced with the same problem, after migration 1.2.6 -> 2.0.2.
I found [this](https://github.com/phalcon/cphalcon/issues/511) issue and concluded, that developers change default argument  in `Phalcon\Http\Request::hasFiles($notErrored)`.

This is only suggestion, I've not looked into sources.

1.2.6
```PHP
/**
 * Checks whether request includes attached files
 *
 * @return boolean
 */
public function hasFiles($notErrored=null){ }
```
