### ISSUE TITLE
Object oriented query model can't use an alias

### ISSUE THREAD

**Issue by uuking** [phalcon/cphalcon#10479]
Query model can not use an alias, in the case of using namespace, use the connection query master table and the connection table if there is a field repeat and cause conflict when the condition

**Comment by uuking** [comment]
$robots = Robots::query()
    ->join('RobotsParts', 'r.id = Robots.robots_id', 'r');
    ->where("type = :type:")
    ->andWhere("year < 2000")
    ->bind(array("type" => "mechanical"))
    ->order("name")
    ->execute();
If you use a namespace in this query, the Robots table is unable to use the alias

**Comment by uuking** [comment]
Table Robots and table RobotsParts if the field has a duplicate and as a query condition, then an error occurs.

**Comment by bombless** [comment]
I'm Chinese, you can rephrase your question in Chinese, I'll see what I can do here.
你可以用中文描述一遍你的问题，我看能否帮到你。
https://github.com/phalcon/cphalcon/issues/10479 中的描述同样很混乱，那糟糕的机翻还是别用了:)

**Comment by uuking** [comment]
好吧，使用面向对象方式查询的时候，如果model使用了命名空间，那么robots是不能使用别名的，如果连接表robotsparts中与robots的字段有重复，并且作为查询条件，这样会导致错误

**Comment by bombless** [comment]
我这边的代码是
```php
<?php
$robots = Robots::createBuilder()
->from(array('r' => 'Robots'))
->join('RobotsParts', 'r.id = rp.robots_id', 'rp');
->where("r.type = :type:")
->andWhere("year < 2000")
->bind(array("type" => "mechanical"))
->order("r.name")
->execute();
```
这样的，不知道能否解决你的问题。

**Comment by uuking** [comment]
刚试了，model中是没有createBulilder方法的

**Comment by andresgutierrez** [comment]
@dreamsxin

**Comment by uuking** [comment]
haha，He is my friend of mine.

**Comment by bombless** [comment]
哦我从公司代码看到的，估计就是简单的
```php
<?php
$builder = new \Phalcon\Mvc\Model\Query\Builder();
```

**Comment by uuking** [comment]
使用构建器是可以的，主要是使用面向对象方式的时候，那是一个小bug

**Comment by uuking** [comment]
还有就是查询的时候使用leftjoin反而别join慢很多，所生成的sql直接运行是很快的

**Comment by dreamsxin** [comment]
我这边测试一切 OK

```php
class Robots extends \Phalcon\Mvc\Model
{
	public function initialize()
	{
		$this->hasMany('id', 'Test\RobotsParts', 'robots_id', array(
			'foreignKey' => true
		));
	}
}

class RobotsParts extends \Phalcon\Mvc\Model
{
	public function initialize()
	{
		$this->belongsTo('parts_id', 'Test\Parts', 'id', array(
			'foreignKey' => true
		));
		$this->belongsTo('robots_id', 'Test\Robots', 'id', array(
			'foreignKey' => array(
				'message' => 'The robot code does not exist'
			)
		));
	}
}

class Parts extends \Phalcon\Mvc\Model
{
	public function initialize()
	{
		$this->hasMany('id', 'Test\RobotsParts', 'parts_id', array(
			'foreignKey' => array(
				'message' => 'Parts cannot be deleted because is referenced by a Robot'
			)
		));
	}
}

$robots = Robots::query()
->join('Test\RobotsParts', 'r.id = Test\Robots.id', 'r')
->where("type = :type:")
->andWhere("year < 2000")
->bind(array("type" => "mechanical"))
->order("name")
->execute();
var_dump($robots->toArray());
```

**Comment by uuking** [comment]
d哥出马就是不一样，哈哈

**Comment by Jurigag** [comment]
So i have to use model with full namespaces in columns ? Its kind of bad, i think there should be parameter in query for setting alias of model.
