### ISSUE TITLE
The build query is slow

### ISSUE THREAD

**Issue by uuking** [phalcon/cphalcon#10477]
If there are leftjoin in the build query, the query will be slow, but join will not

**Comment by andresgutierrez** [comment]
Probably not a bug, the left join is executed by the database not by Phalcon

**Comment by uuking** [comment]
Thank you for your answer, I'm Chinese, are Baidu translate it, please forgive me.
There is in model, $this->modelsManager and $this->bulider, different versions of Phalcon, PHP whether, the situation is different, of course, registered in di.

**Comment by uuking** [comment]
In the 1.3 version of the $this->modelsManager is not used in model, the 2.x version is normal,

**Comment by bombless** [comment]
我想他是希望你提供一个脚本，类似这样的：https://github.com/phalcon/cphalcon/issues/2922

**Comment by sergeyklay** [comment]
The 1.3.x branch is not longer supported.
