### ISSUE TITLE
Oracle auto incremented ID column is empty after model->save()

### ISSUE THREAD

**Issue by skaosYan** [phalcon/cphalcon#10485]
I have Phalcon 2.0.2 and Oracle 12c. I have created sequence and set getSequnceName() function for my model. But model->save() still raises an error "ORA-01400: cannot insert NULL" for a primary key.

**Comment by skaosYan** [comment]
Does anybody have any clue, is it a bug?

**Comment by andresgutierrez** [comment]
Are you manually setting the meta-data of that model?

**Comment by skaosYan** [comment]
No, I do not use metadata classes. I only use columnMap (actually I am forced to use columnMap, because Phalcon by default generates column names in quotas , when Oracle treats quotes as case-sensitive names).

**Comment by skaosYan** [comment]
Do you need any logs or additional info?

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/incubator#796
