### ISSUE TITLE
[2.0.x] Model->save() outputs array (Maybe dev debug output?)

### ISSUE THREAD

**Issue by michanismus** [phalcon/cphalcon#10483]
Hey,
to reproduce this, just clone tutorial from https://github.com/phalcon/tutorial.git

In index.php disable view:

```php
...
 // Handle the request
$application = new Application($di);
$application->useImplicitView(false);
...
```

In IndexControler IndexAction do:
```php
$user = new Users;
$user->save(['name' => 'michi', 'email' => 'mail@server.com']);
```

Open in the web browser and you will see a blank page with output:

```
Array
(
)
```

**Comment by andresgutierrez** [comment]
Are you compiling from ext/ or build/?

**Comment by michanismus** [comment]
From /build

**Comment by andresgutierrez** [comment]
Can you compile please from ext/?

**Comment by michanismus** [comment]
Compiled from ext/ and there is no debug output anymore!
