### ISSUE TITLE
[Bug]metadata.zep

### ISSUE THREAD

**Issue by phannguyencuong** [phalcon/cphalcon#10497]
I'm using Phalcon version 2.0 , everything works fine . When I upgraded to 2.0.3 , each save data , the error appears :
Notice: Undefined index: 12 in phalcon / mvc / model / metadata.zep print on line 276
Please let me fix this guide . Configuration of my modelData as follows :

```php
$di->set(
    'modelsMetadata',
    function () use ($config) {
        return new MetaDataAdapter(array(
            'metaDataDir' => $config->application->cacheDir  . 'metaData/'
        ));
    },
    true
);
```

**Comment by andresgutierrez** [comment]
If you're using the files meta-data, manually delete all files in the meta-data directory and try again.

**Comment by phannguyencuong** [comment]
I deleted all the files in the metadata but this error .

**Comment by phannguyencuong** [comment]
Thank andresgutierrez lot . It has been in operation
