### ISSUE TITLE
Put parameters ?

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#10499]
When i create put parameters with payload like this : {firstName:123,lastName:123} when i do $this->request->getPut() phalcon return array like this:

array(1) {
  ["{firstName:123,lastName:123}"]=>
  string(0) ""
}

which is completely useless, i had to do this : json_decode(key($params),true) then i got right array.

**Comment by Jurigag** [comment]
Also phalcon return underscores for dots in email.

**Comment by andresgutierrez** [comment]
It doesn't parse the payload as JSON, it assumes the input comes from in the form of variable=value:

https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/http/request.zep#L118-L132

**Comment by andresgutierrez** [comment]
You can use getJsonRawBody https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/http/request.zep#L346-L356

**Comment by Jurigag** [comment]
Thanks ! Didnt know about getJsonRawBody, beacause i had outdated devtools, know updated and got  ide completition in phpstorm so to know about it :)
