### ISSUE TITLE
Can't install on CentOS

### ISSUE THREAD

**Issue by atayev** [phalcon/cphalcon#10501]
Hi, can't install in CentOS.  Tried install:

git clone --depth=1 git://github.com/phalcon/cphalcon.git
cd cphalcon/build
sudo ./install

Get error like:

/root/cphalcon/build/64bits/phalcon.zep.c: Assembler messages:
/root/cphalcon/build/64bits/phalcon.zep.c:16027: Error: Incorrect register `%esi' used with `q' suffix
/root/cphalcon/build/64bits/phalcon.zep.c:16031: Error: Incorrect register `%edi' used with `q' suffix

**Comment by andresgutierrez** [comment]
What version of PHP do you have? This seems to be caused by an old version of PHP

https://bugs.php.net/bug.php?id=64729

**Comment by atayev** [comment]
In server installed php 5.4.13

**Comment by andresgutierrez** [comment]
Maybe the problem is not fixed yet in 5.4.13

**Comment by atayev** [comment]
Hi, thanks for your answer. I solve this problem. Only upgrade php to 5.4.40

**Comment by andresgutierrez** [comment]
Nice

**Comment by warfu** [comment]
good  i just have the some problem

i use  
PHP 5.4.7 (cli) (built: Jul 23 2015 16:23:37) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies

**Comment by sergeyklay** [comment]
@warfu Try please latest Zephir and command `zephir build` instead `cd cphalcon/build` & `sudo ./install`
