### ISSUE TITLE
I want to support this method of model

### ISSUE THREAD

**Issue by zhouyl** [phalcon/cphalcon#10503]
like this,  can use the class `ArrayObject`:

```
$members = Members::find();

$members->uasort(function($a, $b) {
    ...
});
```

**Comment by Surt** [comment]
Yo can use the filter method of the resultset.

Filtering Resultsets¶
The most efficient way to filter data is setting some search criteria, databases will use indexes set on tables to return data faster. Phalcon additionally allows you to filter the data using PHP using any resource that is not available in the database:

<?php

$customers = Customers::find()->filter(function($customer) {

    //Return only customers with a valid e-mail
    if (filter_var($customer->email, FILTER_VALIDATE_EMAIL)) {
        return $customer;
    }

});
