### ISSUE TITLE
[NFR] Support mysql BLOB field types 

### ISSUE THREAD

**Issue by mattvb91** [phalcon/cphalcon#10502]
Hi everyone

I would like to see the BLOB data types supported for mysql. I have installed zephir and made the following changes (I have added tinyblob, blob, mediumblob, longblob too. For this example just using the blob field)

\Phalcon\Db\Column.zep Line 105
    
```zep
	/**
     * Blob abstract data type
     */
    const TYPE_BLOB = 11;
```

\Phalcon\Db\Adapter\Pdo\Mysql.zep Line 194

```php
    	/**
        * Blob
        */
		if(memstr(columnType, "blob")) {
		      let definition["type"] = Column::TYPE_BLOB;
		      break;
		}
```

\Phalcon\Db\Dialect\Mysql.zep Line 134

```php
    			case Column::TYPE_BLOB:
			       if empty columnSql {
			           let columnSql .= "BLOB";
			       }
```
			    break;

Where would be the best place to define mysql specific column types instead of \Phalcon\Db\Column.zep?

**Comment by andresgutierrez** [comment]
Phalcon needs to know what type is a column so the ORM can use the proper data type in PDO::bindValue (http://php.net/manual/en/pdostatement.bindvalue.php). Could you please submit a PR with these changes?

**Comment by mattvb91** [comment]
Thanks for the reply Andre, I will submit a PR this evening.

Am I assuming correctly then that \Phalcon\Db\Column.zep is the correct place to define these new types? As from looking at the code each sql dialect will default it to its own type if it doesn't support it anyway.

**Comment by andresgutierrez** [comment]
@mattpavelle Yes, it's the right place. I think it will be simply not available to other platforms
