### ISSUE TITLE
PHQL uses join ON 1 condition when joining directly against the hasMany linking table 

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10507]
I have 3 table:
- `table1`: `id`
- `link_table`: `id`, `table1Id`, `table2Id`, `type`
- `table2`: `id`

The SQL reads `INNER JOIN table1 ON 1` instead of inferring the relationship from the hasManyToMany relationship.  I must include an additional hasMany relationship from table1 the linking table but this information is already available from the hasManyToMany relationship.

This stems from needing to include a flag field in the link table.  Phalcon seems to assume that the link hasManyToMany link table will only have a primary id and two foreign keys and just falls apart and offers no facilities for dealing with it any other way.

If there are no edge cases that would become ambiguous then I propose that in effect that a hasManyToMany relationship will automatically add an extra hasMany relationship to the linking table or some other other equivalent method that allows the `ON` condition to be filled out.

I did enjoy the new `$query->getSql()` method though and it made it real easy to catch once I knew what I was looking for.

**Comment by dschissler** [comment]
@phalcon 

I created some scripts on [phalcon_bug_10507](https://github.com/dschissler/phalcon_bug_10507) that demonstrate the various errors.  Forgive the layout of the project because I needed to test different permutations of actual model classes and also how it interacts with settings on the ModelsManager.

One of the scripts works but it appears to be impossible to use the new ModelsManager aliases for the query that I want to use.  Using aliases appears to break the hasManyToMany searches when searching for values on the intermediate linking table.  I had to add an additional hasMany relationship to link them together.

So I think that maybe there are two hard bugs and another would-be-nice-to-have.

Its difficult to keep track of the bugs since sometimes there is a hard fail from it including the table JOIN condition twice when it is explicitly declared and other times the relationship table join `ON` condition is set to 1.  Its difficult to succinctly explain the variety of bugs and weird behaviour and so hopefully you can see that the queries shouldn't be anything too weird and that they just don't work unless setup in a very particular way.

**Comment by dschissler** [comment]
[65199a71660ddc00aae8ee1b670c8ec22350ebaa](https://github.com/phalcon/cphalcon/commit/65199a71660ddc00aae8ee1b670c8ec22350ebaa) does not seem to fix the `sad_1.php`, `sad_2.php` or `sad_3.php` script.  New bug #10526 should resolve some of the tests/errors but then there is still the matter that if you add a relationship alias in `Persons` that it will fail.

**Comment by andresgutierrez** [comment]
Are you compiling from ext/ in the 2.0.x branch?

**Comment by andresgutierrez** [comment]
I've made the following test, Robots joining directly to RobotsParts:

```php
<?php

namespace Some;

use Phalcon\DI,
    Phalcon\Db\Column,
    Phalcon\Db\RawValue,
    Phalcon\Mvc\Model,
    Phalcon\Events\Manager as EventsManager,
    Phalcon\Db\Dialect\MySQL as SqlDialect,
    Phalcon\Db\Adapter\Pdo\MySQL as Connection,
    Phalcon\Mvc\Model\Manager as ModelsManager,
    Phalcon\Mvc\Model\Metadata\Memory as ModelsMetaData;

$eventsManager = new EventsManager();

$di = new DI();

$connection = new Connection(array(
    "host"     => "localhost",
    "username" => "root",
    "password" => "",
    "dbname"   => "phalcon_test",
));

$connection->setEventsManager($eventsManager);

$eventsManager->attach('db',
    function ($event, $connection) {
        switch ($event->getType()) {
            case 'beforeQuery':
                echo $connection->getSqlStatement(), "\n";
                break;
        }
    }
);

$modelsManager = new ModelsManager();
$modelsManager->setDi($di);
$di['db'] = $connection;
$di['modelsManager'] = $modelsManager;
$di['modelsMetadata'] = new ModelsMetadata();

class Robots extends Model
{
    public function initialize()
    {
        $this->hasMany(
            "id",
            "Some\RobotsParts",
            "robots_id"
        );
    }
}

class RobotsParts extends Model
{

}

class Parts extends Model
{

}

$phql = "SELECT r.* FROM Some\\Robots r JOIN Some\\RobotsParts rp";

$robots = $modelsManager->executeQuery($phql);
echo(count($robots));
```

Outputs:

```sql
SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = 'robots' AND `TABLE_SCHEMA` = DATABASE()
DESCRIBE `robots`
SELECT `r`.`id`, `r`.`name`, `r`.`type`, `r`.`year`, `r`.`datetime`, `r`.`text` FROM `robots` AS `r`  INNER JOIN `robots_parts` AS `rp` ON `r`.`id` = `rp`.`robots_id`
```

The join condition is automatically added there

**Comment by dschissler** [comment]
I just compiled from `./ext/install` in the latest commit.  I wasn't aware there was a difference between building normally from `./build/64bits` in the development snapshots.

Your test doesn't do anything useful.  I urge you to run the scripts that I made.  It was difficult to track down the behaviour.  I think that if you join all of the way to `Parts` and add an extra property onto `RobotParts` that you use in a condition then you must also add an alias to the relation defined in `Robots` and it should fail.  I have it laid out in the scripts that I made.

Here are the [scripts](https://github.com/dschissler/phalcon_bug_10507) that I made to test it.

Perhaps I'm not explaining myself very well but I think that the bug is difficult to reproduce and at least one variety of it was reported a year ago.  I made the scripts to squash this once and for all but it doesn't appear that you ran them.  Maybe try inside of a VM?

**Comment by andresgutierrez** [comment]
I'm checking `sad1`:

* There is no direct relation between Persons and PersonsGroups so that's why it joins the model but using a dummy condition `1`. PersonsGroups is just an intermediate model to reach Groups. I think you can define this explicit relation and you will get the right condition there.

**Comment by dschissler** [comment]
So jump ahead to `sad3` (with a direct relationship defined for the models) and you will see that for test1 the failure changes to then being that there is a double INNER JOIN (one from explicit and one from implicit).  `quirky1` fixes this by removing the explicit JOIN to only use the implicit one but then there is no way to use `v2.0.3` ModelsManager aliases form as found in `sad1-3`.

Also, maybe an Exception should be thrown instead of a dummy condition.

**Comment by dschissler** [comment]
> PersonsGroups is just an intermediate model to reach Groups.

This is an assumption that doesn't hold true for my example because the whole point that brought me here is wanting to store a data flag in that intermediate table (`PersonsGroups`).  3rd normal and all of that.  Additionally using an alias to store the relationship was not appropriate for me in this case because Phalcon has no mechanism to assign a value to a linking intermediate table.  Its a good thing that I didn't go that route either because literally assigning an alias to the `hasManyToMany` relationship in `Persons` causes that relationship to not work properly.

**Comment by dschissler** [comment]
Perhaps the standard issue `RobotParts` table/model should have an integer flag field/attribute added to it to be able to test for this.

So:
```
id:              primary key integer
robotsKey: integer
partsKey:   integer
flag:           integer
```

**Comment by dschissler** [comment]
Since you have the script perhaps you could mark this as a bug so it doesn't get lost.

**Comment by ruudboon** [comment]
Any update's regarding this issue?

**Comment by dschissler** [comment]
You simply need to set an additional relation and the default condition is `JOIN ON 1`.  The `hasManyToMany` relation does not automatically create the intermediate relation.  I think that it should throw an exception instead when there is no defined relation but hey, at least this way everyone will get experience inspecting the SQL to see why they are receiving all results.

**Comment by ruudboon** [comment]
Thnx @dschissler I'l dive into it. All relation are there. Guess I must be missing something.

**Comment by dschissler** [comment]
Regarding my last comment: There are a number of pitfalls depending on exactly what you are trying to do.  Some months ago I added the capability to disable implicit joins on the global level and on the query level with `enable_implicit_joins`.  This can work well if you encounter any weird issues with more complicated joins.  Phalcon model relations do a whole hell of a lot for you but they don't work 100% for rare and complicated ones.  In this case just do it manually.

At some point someone will need to flush out I think two remaining bugs to make Phalcon perfect.  Its almost there.

**Comment by dschissler** [comment]
Table1 -> Table2 -> Table3

If you setup your many-to-many relation from Table1 to Table3 then Phalcon will not know how to join Table1 against Table2 by inferring from that relation and so you need to define another relation specifically for that.  Then what I mean by no knowing is that it fills in basically `TRUE`.

**Comment by ruudboon** [comment]
That's my case indeed. Table 1 -> (many to 1) Table 2 -> (many to 1) Table 3
