### ISSUE TITLE
Why I can't use   $this->tag->linkTo();

### ISSUE THREAD

**Issue by XMap** [phalcon/cphalcon#10519]
Such like the title  ，

I'm in PHP 5.6.10 and Phalcon 2.0.3 .

This page html source just have that 
h1{Hello}  
<hr/>
http://120.26.113.48/
http://120.26.113.48/info.php
<hr/>
Help me please ~~~~  and I'm copy that 
https://docs.phalconphp.com/en/latest/reference/tutorial.html
<hr/>

**Comment by andresgutierrez** [comment]
Are you getting an error or something?

**Comment by XMap** [comment]
Fatal error: Class 'UrlProvider' not found in /usr/share/nginx/html/devxmap/public/index.php on line 30

I have change the php.ini .  It's show that .

**Comment by andresgutierrez** [comment]
You can find the full code here: https://github.com/phalcon/tutorial

**Comment by XMap** [comment]
http://120.26.113.48/aaa.txt
you can check my this index.php file source ....
............

I don't think it's because this reason ...

**Comment by XMap** [comment]
: )   Thank you First !  I'm sorry ...

**Comment by andresgutierrez** [comment]
Instead of:

```
use Phalcon\Mvc\Url;
```

it must be:

```
use Phalcon\Mvc\Url as UrlProvider;
```

**Comment by XMap** [comment]
Cool!  thank you very much !
