### ISSUE TITLE
PHQL can not be used when there is more than one colliation in a databases

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#10517]
PHQL does not allow using `binary` or `collation` in where clauses. In such cases, nothing will work: 
`SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_bin,NONE) and (utf8_general_ci,COERCIBLE
) for operation 'like'`.

**Comment by anettan** [comment]
Thanks. I'll try,,  time, and having a routes() method just doesn't work. Whereas the following does..,

**Comment by andresgutierrez** [comment]
You can create a custom function that allow you to set the collation: https://blog.phalconphp.com/post/phalcon-2-0-3-released

**Comment by salarmehr** [comment]
I hope raw query build make using `collation` and `binary` possible.
