### ISSUE TITLE
[2.0.x] Did Phql Limit placeholder make its way into the 2.x branch from 1.3?

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10528]
I'm still having trouble disabling phpLiterals.  

Did this make it in [commit 1023](https://github.com/phalcon/cphalcon/pull/1023)?

I can't get any of these forms to work in a very recent `2.0.x`.

```php
        $phql = "SELECT stuff LIMIT 1";
        $this->getDI()->getModelsManager()
            ->createQuery($phql)
            ->execute([
            ]);
```

```php
        $phql = "SELECT stuff LIMIT :P_LIMIT";
        $this->getDI()->getModelsManager()
            ->createQuery($phql)
            ->execute([
                'P_LIMIT' => 1
            ]);
```

**Comment by andresgutierrez** [comment]
First one works fine, second has a wrong placeholder (missing colon) and it needs the bind type, it must be:

```php
$phql = "SELECT stuff LIMIT :P_LIMIT:";
        $this->getDI()->getModelsManager()
            ->createQuery($phql)
            ->execute([
                'P_LIMIT' => 1
            ], 
            ['P_LIMIT' => \Phalcon\Db\Column::BIND_PARAM_INT]
);
```

**Comment by dschissler** [comment]
I think that I was using the correct placeholder in my real code so it must be the bind type.  I didn't know that it was ever required.

**Comment by andresgutierrez** [comment]
Yes, it's required by PDO/MySQL: http://stackoverflow.com/questions/2269840/how-bindvalue-in-limit

**Comment by dschissler** [comment]
Thanks.  That would have been difficult to find.
