### ISSUE TITLE
( ! ) Fatal error: Declaration of Models\Paginate::__construct() must be compatible with Phalcon\Paginator\AdapterInterface::__construct(array $config) 

### ISSUE THREAD

**Issue by ilyaskorik** [phalcon/cphalcon#10521]
This is phalcon-dev-tools/ide problem. I'm using the latest version of phalcon-dev-tools from github.

**Comment by Green-Cat** [comment]
Are you using a compatible version of phalcon? For example phalcon 2.0.3 + dev-tools 2.0.3?
If you are still using phalcon 1.3.x you need to use dev-tools 1.x

**Comment by ilyaskorik** [comment]
Yes, I use version 2.0.3 for app and 2.0.0 for tools. This is typo in /phalcon-devtools/ide/2.0.0/Phalcon/paginator/AdapterInterface.php ?

**Comment by ilyaskorik** [comment]
https://github.com/phalcon/phalcon-devtools/blob/master/ide/2.0.0/Phalcon/paginator/AdapterInterface.php

**Comment by ilyaskorik** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/paginator/adapterinterface.zep

**Comment by andresgutierrez** [comment]
Could you please post this in the devtools repo? https://github.com/phalcon/phalcon-devtools
