### ISSUE TITLE
[2.0.3] Model::FindFirstBy* magic methods should work when phqlLiterals is false

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10523]
The `findFirstBy*` magic methods throw an exception with message `Literals are disabled in PHQL statements` when invoked.  Perhaps all of the underlying code should use the long hand explicit binding so that it is compatible with disabling this feature.

I dream of the day when I can turn this setting on to have a bit more assurance.  I thought that we might be there after the LIMIT clause was fixed.

**Comment by andresgutierrez** [comment]
This is implemented in the 2.0.x branch

**Comment by dschissler** [comment]
It works.
