### ISSUE TITLE
include in volt seems different

### ISSUE THREAD

**Issue by xicond** [phalcon/cphalcon#10524]
if I use variable in include, volt would generate cache using $this->partial, and it make different mechanism, so I should ignore (dot)volt extension

        {% set dirRoot = "../../../views/" %}
        {% else %}
        {% set dirRoot = "" %}
        {% endif %}
        {% include dirRoot ~ 'core/templates/content/head' %}

vs

        {% include '../../../views/core/templates/content/head.volt' %}

**Comment by andresgutierrez** [comment]
This is the expected behavior. When including the extension it performs ahead-of-time compilation but if the file cannot be resolved at compile time it falls back to the partial function.

**Comment by xicond** [comment]
I'm not pointing on fallback to $this->partial, but on method to include string, one should use extension, one shouldn't, it's misinterpreting for programmer usage
