### ISSUE TITLE
Phalcon\Mvc\Model\Validator::getOptions should be public in version 2.0.x

### ISSUE THREAD

**Issue by kevas** [phalcon/cphalcon#10520]
It was changed in version 1.x. Methods from protected to public:
 - getOptions
 - getOption
 - isSetOption

Can you please change the visibility in version 2.0.x?

Thank you.

**Comment by sergeyklay** [comment]
+1

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch
