### ISSUE TITLE
View / Simple View, Volt: inconsistent behaviour on rendering or a bug

### ISSUE THREAD

**Issue by roman-kulish** [phalcon/cphalcon#10535]
This happens when using View or View\Simple stand-alone with Volt engine and non-shared "view" service. Note: it's *not* documented whether "view" service should be shared and examples are controversial.

The use-case scenario (in my case) was mass-rendering of different content types, where each type had common and unique data and it was logical to get a fresh instance from DI, pre-set variables to it and keep to re-use it later.

I will demonstrate it on the View\Simple.

Let's have these volt templates:
- test1.volt with content "1"
- test2.volt with content "2"

Services setup:
```
$di->set('voltService', function ($view, $di) {
    return new Volt($view, $di);
});

$di->setShared('view', function () {
    $view = new View();
    $view->setViewsDir('/path/to/templates');
    $view->registerEngines([
        '.volt' => 'voltService'
    ]);

    return $view;
});

$di->setShared('viewSimple1', function ()  {
    $view = new Simple();
    $view->setViewsDir('/path/to/templates');
    $view->registerEngines([
        '.volt' => function($view, $di) {
            return new Volt($view, $di);
        }
    ]);

    return $view;
});

$di->setShared('viewSimple2', function ()  {
    $view = new Simple();
    $view->setViewsDir('/path/to/templates');
    $view->registerEngines([
        '.volt' => 'voltService'
    ]);

    return $view;
});
```

The code is:
```
$v1 = $di->get('viewSimple1');
$v2 = $di->get('viewSimple1');

echo $v1->render('test1');
echo $v2->render('test2');

$v1 = $di->get('viewSimple2');
$v2 = $di->get('viewSimple2');

echo $v1->render('test1');
echo $v2->render('test2');

$v1 = $di->get('view');
$v2 = $di->get('view');

// skipped View buffering etc...
echo $v1->render('test1');
echo $v2->render('test2');
// skipped View buffering etc...
```

First we test with "viewSimple1" service that creates Volt via \Closure. In https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/simple.zep # 154 engine initialization happens via ```let engineObject = call_user_func_array(engineService, arguments);``` and so each new instance of View\Simple has a new instance of Volt.

The output after rendering is "12".

Next, we test with "viewSimple2" service. It creates engine via ```let engineObject = dependencyInjector->getShared(engineService, arguments);``` and so each new instance of View\Simple has THE SAME instance of Volt, stored inside the DI as shared.

The output after rendering is "1".

When Volt instance is created it references to the $v1 view. When we run ```$v2->render('test2');``` the Volt will set content ... of the $v1. See https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt.zep # 121, ```this->_view->setContent(ob_get_contents());```

Next, we try to run the same using "view" service that uses "voltService" together with "viewSimple2". 

The output after rendering is "NULL" and no layout has rendered ... as Volt still sets content to $v1 of the "viewSimple2".

View and View\Simple cannot share the same Volt as a DI service?

This one looks like it too: https://github.com/phalcon/cphalcon/issues/2872

**Comment by andresgutierrez** [comment]
The volt service is obtained using getShared so the instance works as shared even if it's registered or not as shared. This is why it returns the same instance. You can fix this by registering the engine using a closure or create a different volt service for simple and hierarchical.

**Comment by roman-kulish** [comment]
Thanks @andresgutierrez I am cool, I use closure and it works. However, it is unexpected behaviour which should be wither fixed or properly documented. 

Another thing: as I now have Simple View as shared and I set vars to it, it becomes a memory hog, because there is no standard way to reset variables.

**Comment by andresgutierrez** [comment]
@roman-kulish Could you please submit a new NFR asking for a reset method and close this one?
