### ISSUE TITLE
warning: \U used with no following hex digits

### ISSUE THREAD

**Issue by pct** [phalcon/cphalcon#10531]
Hello, when compile phalcon 2.0.3 on FreeBSD 10.1-RELEASE, it shows following warning message: (\U)

        /usr/ports/www/phalcon/work/cphalcon-phalcon-v2.0.3/build/32bits/phalcon.zep.c:112026:40: warning: \U used with no following hex digits; treating as '\' followed by identifier [-Wunicode] ZEPHIR_REGISTER_CLASS_EX(Phalcon\\Mvc\\Url, Exception, phalcon, mvc_url_exception, phalcon_exception_ce, NULL, 0);

Could I ignore this warning? 

Thanks.

**Comment by andresgutierrez** [comment]
Hello, yes, you can ignore it

**Comment by pct** [comment]
Hi, thanks for your quickly reply.
