### ISSUE TITLE
Error "Phalcon\Mvc\Model\Exception: The method 'sethydratemode' doesn't exist on model" on Phalcon 2.0.3

### ISSUE THREAD

**Issue by williamokano** [phalcon/cphalcon#10547]
Hi, I'm getting the error "Phalcon\Mvc\Model\Exception: The method 'sethydratemode' doesn't exist on model 'Apps\Models\Entities\Users'"
C:\app\apps\models\repositories\Repository\User.php (18)

https://gist.github.com/williamokano/e093c36a84b056cefb46

Phalcon version: Windows precompiled dll 2.0.3 for PHP 5.3.9 x86
PHP Version PHP 5.3.27 (cli) (built: Jul 10 2013 20:56:24) Zend Engine 2.3.0 with xDebug 2.2.7

PS.: I opened the issue because the exact same code works fine on Phalcon 2.0.1.

**Comment by andresgutierrez** [comment]
In Phalcon 2.0.0 and Phalcon 2.0.1 methods that weren't declared in the model were called and the framework did not throw an exception. In Phalcon 2.0.2 you're getting that error because the method does not exist.

**Comment by williamokano** [comment]
Hi @andresgutierrez,

The error is being throw by FindFirst Phalcon model when I try to hydrate the collection:

EntityUsers::findFirst(array(
"conditions" => "UserId = :UserId:", 
"bind" => array("UserId" => $user_uid), 
'hydration' => Resultset::HYDRATE_ARRAYS)
)->toArray();

Should I declare on every model the sethydratemode? That makes no sense for me.

**Comment by andresgutierrez** [comment]
No, I was explaining you why this worked in Phalcon <= 2.0.2 but no in Phalcon 2.0.2

**Comment by williamokano** [comment]
Ok, sorry about that. :)

Should I discuss the solution for that on the forum or this can be considered a bug? If it is not a bug, I will close the issue.

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.x branch

**Comment by williamokano** [comment]
@Thanks @andresgutierrez :+1:
