### ISSUE TITLE
NFR: Phalcon\Mvc\Model\Criteria must have groupBy method

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#10546]
If i want to create a "complex" (not really complex) query for a model, it's simple enough use the query method from model, that it returns a Criteria object, but, this class don't have a group method, that some times is needed.

**Comment by andresgutierrez** [comment]
That method is already there in Phalcon 2.0.4: https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model/criteria.zep#L526

**Comment by gtux** [comment]
Ah ok, thanks!
