### ISSUE TITLE
Compile warnings on osx

### ISSUE THREAD

**Issue by miao606** [phalcon/cphalcon#10554]
gcc -I. -I/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits -DPHP_ATOM_INC -I/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits/include -I/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits/main -I/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -finline-functions -fomit-frame-pointer -fvisibility=hidden -c /Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits/phalcon.zep.c  -fno-common -DPIC -o .libs/phalcon.o
/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits/phalcon.zep.c:112026:40: warning: \U used with no following hex digits; treating as '\' followed by
      identifier [-Wunicode]
        ZEPHIR_REGISTER_CLASS_EX(Phalcon\\Mvc\\Url, Exception, phalcon, mvc_url_exception, phalcon_exception_ce, NULL, 0);
                                              ^
/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits/phalcon.zep.c:112329:40: warning: \U used with no following hex digits; treating as '\' followed by
      identifier [-Wunicode]
        ZEPHIR_REGISTER_CLASS_EX(Phalcon\\Mvc\\User, Component, phalcon, mvc_user_component, phalcon_di_injectable_ce, NULL, 0);
                                              ^
/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits/phalcon.zep.c:112351:40: warning: \U used with no following hex digits; treating as '\' followed by
      identifier [-Wunicode]
        ZEPHIR_REGISTER_CLASS_EX(Phalcon\\Mvc\\User, Module, phalcon, mvc_user_module, phalcon_di_injectable_ce, NULL, 0);
                                              ^
/Users/mxu/Downloads/cphalcon-phalcon-v2.0.3/build/64bits/phalcon.zep.c:112373:40: warning: \U used with no following hex digits; treating as '\' followed by
      identifier [-Wunicode]
        ZEPHIR_REGISTER_CLASS_EX(Phalcon\\Mvc\\User, Plugin, phalcon, mvc_user_plugin, phalcon_di_injectable_ce, NULL, 0);
                                              ^
4 warnings generated.

**Comment by andresgutierrez** [comment]
These are warnings caused by macros in PHP and they will not be fixed
