### ISSUE TITLE
Model Transforming empty strings into nulls

### ISSUE THREAD

**Issue by cchristensen-cxp** [phalcon/cphalcon#10583]
Model transforming empty strings into nulls.

Use find method to pull rows from database.
Foreach through records.
Save a record.

Error: 
object(Phalcon\Mvc\Model\Message)#138 (4) {
  ["_type":protected]=>
  string(10) "PresenceOf"
  ["_message":protected]=>
  string(21) "column is required"
  ["_field":protected]=>
  string(9) "column"
  ["_model":protected]=>
  NULL
}

**Comment by phalcon** [comment]
No script to reproduce has been posted yet
