### ISSUE TITLE
Resultset filter returns array

### ISSUE THREAD

**Issue by Surt** [phalcon/cphalcon#10580]
Is this intended? Why not return a Resultset with the filtered models instances?

**Comment by andresgutierrez** [comment]
Resultsets are returned from the database, filtered resultsets are manually built by the developer and not returned by the database.

https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model/resultset.zep#L537-L561

**Comment by Surt** [comment]
Hi @andresgutierrez ,

yes I know the behaviour but I was wondering if you don't think that this is a little bit inconsistent. 
When I work with the ORM or the ODM I expect "Entities/Models" or "Collections/Resultsets" and I would like to mantain that behaviour all the time, just for confort. And of course, the main target here is to abstract it from the database/persistence. While using the ORM and its results would be great to know the domain, not the ways used to retrieve or return it. 

Maybe, making the Resultset a little more complex (through more interfaces) we could work always with them. Not taking care of extrange transformations from Resultset to array, etc... 
It seems easy to do, just adding a flag to the resultset, telling if the results are in memory (_rows) or waiting to be fetched from database. 

This is the way of Doctrine, or laravel eloquent and many others. Resultsets/Collections as an abstraction for a group of Entities/Models. And you can play with those objects in a better way than with arrays.

**Comment by galki** [comment]
+1

**Comment by tobispace** [comment]
+1
