### ISSUE TITLE
[2.0.4] Phalcon\Mvc\Model\Criteria::fromInput() not working with columnMap

### ISSUE THREAD

**Issue by drIceman** [phalcon/cphalcon#10587]
This error was encountered again in the latest version 2.0.4
https://github.com/phalcon/cphalcon/issues/2463

**Comment by drIceman** [comment]
This is my method overload, written in PHP

public static function fromInput(Phalcon\DiInterface $dependencyInjector, $modelName, $data) {
		$conditions = [];
		if (count($data)) {
			$modelsMetadata = $dependencyInjector->getShared('modelsMetadata');
			$model = new $modelName;
			$dataTypes = $modelsMetadata->getDataTypes($model);
			$modelColumnMap = array_flip($model->columnMap());

			/**
			 * We look for attributes in the array passed as data
			 */
			$bind = [];
			foreach ($data as $field => $value) {
				$type = $dataTypes[$modelColumnMap[$field]];
				if ($value !== null && $value !== '') {
					if ($type == Phalcon\Db\Column::TYPE_VARCHAR) {
						/**
						 * For varchar types we use LIKE operator
						 */
						$conditions[] = $field . ' LIKE :' . $field . ':';
						$bind[$field] = '%' . $value . '%';
					} else {
						/**
						 * For the rest of data types we use a plain = operator
						 */
						$conditions[] = $field . '=:' . $field . ':';
						$bind[$field] = $value;
					}
				}
			}
		}
		
		/**
		 * Create an object instance and pass the paramaters to it
		 */
		$criteria = new Phalcon\Mvc\Model\Criteria();
		if (count($conditions)) {
			$criteria->where(join(' AND ', $conditions));
			$criteria->bind($bind);
		}

		$criteria->setDI($dependencyInjector);
		$criteria->setModelName($modelName);

		return $criteria;
		
	}

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch
