### ISSUE TITLE
FindFirst creates 2 instances of my model

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#10596]
I got a model that extends the Phalcon\Mvc\Model;
When I load a model with MyModel::findFirst(ID) it returns the loaded model.
Unfortunately it looks like the initialize method is not called.
When logging the object hash in the initialize() with spl_object_hash($this) and the logging the object hash of the returned model I found out that they don't match. 
It looks like the initialize is called but the returned object is different then the initialised object. Running on Phalcon 2.0.3

**Comment by andresgutierrez** [comment]
'initialize' is just called once per model, not per instance of the model, you might want to use 'onConstruct'

**Comment by ruudboon** [comment]
Ok. Thnx that for clearing why theres is only 1 call to the initialise. 
Brings me back to my original problem. 
I'm setting some private member variables on the model in the init. 
Those vars are all cleared in the returned model. This is causing an issue for me. It was working in 1.3.4.

I can easily change it to onConstruct but I assume that setting a member var in the initialise should effect the new instances.

**Comment by andresgutierrez** [comment]
In Phalcon 2.0.x, if you modify the instance in initialize() it only modifies the first instance created.

**Comment by ruudboon** [comment]
Thnx for the fast response. I will change my implementation.
Still not sure why there are instances in first places when doing findFirst but not sure if that's a bug.

**Comment by ruudboon** [comment]
We an close this one.
