### ISSUE TITLE
Is there any way to use dynamic columns?

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#10592]
I need to use MariaDB [dynamic columns](https://mariadb.com/kb/en/mariadb/dynamic-columns) feature. PHQL does not support it a the moment. Should I wait for raw sql builder or there is a workaround?

**Comment by sszdh** [comment]
+1

**Comment by williamokano** [comment]
+1

**Comment by andresgutierrez** [comment]
What makes that you can't use this in PHQL?

**Comment by andresgutierrez** [comment]
Closed as no feedback provided from OP
