### ISSUE TITLE
Normal tag naming

### ISSUE THREAD

**Issue by ovr** [phalcon/cphalcon#10601]
Hey! I can't explain why this prefix (`phalcon-v`) is needed, but it's not useful
phalcon-v2.0.3
This tag seems to be a piece of shit

Use
`2.0.3` instead of  phalcon-v2.0.3

It's rly easy and will be useful
Please do it

**Comment by andresgutierrez** [comment]
I don't see any difference, many projects also use the name of project + version

**Comment by ovr** [comment]
http://semver.org/
using v + version

https://github.com/symfony/symfony/releases
using v + version

https://github.com/laravel/framework
using v + version

https://github.com/twbs/bootstrap/releases
using v + version

https://github.com/angular/angular/releases
only version in tag

https://github.com/angular/angular.js/releases
using v + version

Why `phalcon` prefix is needed? It is not useful

**Comment by ovr** [comment]
https://www.versioneye.com/php/phalcon:cphalcon/phalcon-v2.0.4?utm_medium=email&utm_source=new_versoin
> This version number (phalcon-v2.0.4) doesn't fit semantic versioning 2.0.0!
