### ISSUE TITLE
Routes with group capturing

### ISSUE THREAD

**Issue by davidsteinsland** [phalcon/cphalcon#10605]
``` php
$app = new Micro();

$app->get('/([a-z]+)/([0-9]+)', function() use ($app) {
    /* arguments are not passed on to handler. must use $app->getRouter()->getMatches() instead */ 
});

/*
should match: /model/1/model2/5/model3/500 ...
*/
$app->get('(/{name: [a-z]+}/{id:[0-9]+})+', function() use ($app) {
    /* pattern does not compile into a regex */
});
```

Phalcon should pass captured group to the callable, and not rely on the `params` in the route.

**Comment by williamokano** [comment]
+1

**Comment by sergeyklay** [comment]
+1

**Comment by andresgutierrez** [comment]
Not sure why you need this, set variables by name works fine and by default routes are processed as static strings, this speed up pattern matching as it does not need to use the regex engine to check if the pattern was matched.

If you use variables it will compile to a regex as expected:

```php
<?php

$app = new \Phalcon\Mvc\Micro();

$app->map('/{name:[a-z]+}/{id:[0-9]+}', function($a, $b) use ($app) {
    var_dump($a);
    var_dump($b);
});

$app->handle('/hello/123');
```

**Comment by davidsteinsland** [comment]
@andresgutierrez You are missing the repeating outer group. The pattern should repeat itself at least once, and match URIs as per the comment.
