### ISSUE TITLE
Phalcon\Cache\Backend\memcache的flush方法都存在删除不掉的情况

### ISSUE THREAD

**Issue by gufei** [phalcon/cphalcon#10613]
原因是在statsKey的在存储中用的是key来存的，但在flush方法中
for key in keys这样的写法key其实取的是value，所以下边的delete动作执行是不成功的

修改方法是改为for key, value in keys

建议官方修复

另外，官方保存key列表的思路在memcache下会受到单条记录最大1M的限制，用flush在所有的key总长度超过1M的时候，也无法清除所有的了，是否官方考虑flush方法直接使用memcache->flush()

**Comment by yongsheng-xia** [comment]
或许你需要翻译一下，或者给出代码说明

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch
