### ISSUE TITLE
query builder:select for update Syntax error

### ISSUE THREAD

**Issue by yongsheng-xia** [phalcon/cphalcon#10611]
phalcon 2.0.4

···
$rs = Member::instance()->getModelsManager()->createBuilder(['for_update'=>true])
                ->columns('member_name')
                ->from(Member::class)
                ->where('member_id=2')
                ->getQuery()
                ->execute();
···

···
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE' at line 1
···

···
SELECT `member`.`member_name` AS `member_name` FROM `member` WHERE `member`.`member_id` = 2FOR UPDATE
···

**Comment by andresgutierrez** [comment]
Added a fix in the 2.0.x branch
