### ISSUE TITLE
$model->save() does not catch all errors

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#10627]
I'm not sure, but I guess in Phalcon 1.3 Model::getMessages() had been catching invalid data format errors. However in 2.0.3 it only generates `PresenceOf` errors. Invalid data types throw an exception. (I mean without writing `validation` method for the model )

~~~~
$user=new User;
$user->age='foo';
if(!$user->save()){  // Uncaught exception 'PDOException' with message 'SQLSTATE[22007]: Incorrect integer value: 'foo' for column 'age' 
var_dump($user->getMessages());  
}

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
