### ISSUE TITLE
why uncamelize taskName

### ISSUE THREAD

**Issue by yongsheng-xia** [phalcon/cphalcon#10622]
`php cli.php AppUse run;`

`AppuseTask can no be load`

why uncamelize taskName

```
# phalcon/cli/router/route.zep:360
// Always pass the task to lowercase
let routePaths["task"] = uncamelize(realClassName);
```

**Comment by andresgutierrez** [comment]
You have to name your task App_UseTask then

**Comment by yongsheng-xia** [comment]
but we use Camel-Case code style

**Comment by yongsheng-xia** [comment]
@andresgutierrez i see phalcon in http://www.php-fig.org/ Member Projects list, psr-1 say Class names MUST be declared in StudlyCaps.

**Comment by SidRoberts** [comment]
If you want to call the `AppUseTask` class, use:

```bash
php cli.php app-use run
```

I also use this code snippet in the CLI's dispatcher to use hyphenated actions:

```php
$eventsManager->attach(
	"dispatch:beforeDispatchLoop",
	function ($event, $dispatcher, $data) {
		if ($dispatcher->getActionName()) {
			$actionName = $dispatcher->getActionName();
			$actionName = \Phalcon\Text::camelize($actionName);
			$actionName = lcfirst($actionName);
			
			$dispatcher->setActionName($actionName);
		}
	}
);
```

Without it, to call `AppUseTask::aRandomNameAction`, you have to do `php cli.php app-use aRandomName`. With the snippet, you can do `php cli.php app-use a-random-name`.
