### ISSUE TITLE
API Documentation - Menu Links Broken

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#10626]
All links in the left sidebar menu broken, it contains "backslash" \ on the links.

Examples: https://api.phalconphp.com/class/Phalcon/Events\Manager.html
https://api.phalconphp.com/class/Phalcon/Forms\ElementInterface.html

**Comment by andresgutierrez** [comment]
Now fixed

**Comment by tuxy** [comment]
@andresgutierrez, Thank You. It works now!
