### ISSUE TITLE
Phalcon\Logger\Formatter\Line: no more newline at end of message like in 1.3.x

### ISSUE THREAD

**Issue by olivier-monaco** [phalcon/cphalcon#10631]
In 1.3.x, Phalcon\Logger\Formatter\Line::format added a newline a the end. In 2.0.x, no more. Instead, Phalcon\Logger\Adapter\File add a newline before calling logInternal. But we use Phalcon\Logger\Adapter\Stream that don't add a newline.

Use case:
<pre>
use Phalcon\Logger\Adapter\Stream;
use Phalcon\Logger;

$logger = new Stream('php://output');
$logger->setLogLevel(Logger::INFO);

$logger->log(Logger::ERROR, 'Error');
$logger->log(Logger::INFO, 'Info');
</pre>

Is this a feature or a bug?

**Comment by andresgutierrez** [comment]
It looks like something that can be fixed

**Comment by olivier-monaco** [comment]
Ok. I will in some hours. Thanks.

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch
