### ISSUE TITLE
Volt template engine parse problem on Linux

### ISSUE THREAD

**Issue by SkyZH** [phalcon/cphalcon#10639]
When I use Volt on Linux,     
`{{ stylesheet_link('//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css') }}`    
 will be parsed as     
` <link rel="stylesheet" type="text/css" href="/oj///cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" />`
But on Windows it works correctly.      
 `<link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
`      
 is the result on Windows.      
I can solve this problem by manully typing      
 `<link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">`       
into the volt file. I think there might be something wrong with Volt.

**Comment by carvajaldiazeduar** [comment]
Do you have 2.0.4 on both machines?

**Comment by SkyZH** [comment]
I install phalcon with apt-get and ppa repositoy on Ubuntu. This version is 2.0.1...
and install the latest version 2.0.4 of phalcon on Windows.

**Comment by SkyZH** [comment]
Thank you! After I download and install the latest version of Phalcon, this issue has been solved.
