### ISSUE TITLE
Mapping URI with capitals to controller class name broken in 2.0.4

### ISSUE THREAD

**Issue by ioncube** [phalcon/cphalcon#10640]
This is a possibly related in some way to #10638
Having updated to 2.0.4, a URI /API/foo/ that formerly mapped to a controller class ApiController now maps to ApIController (capital A, lower case p, capital I). Is this a bug or a new naming strategy that breaks BC?

**Comment by olivier-monaco** [comment]
I can reproduce... In fact only the last character is kept uppercase. Looking for "http://.../CONTROLLER" result in: "PhalconException: ControlleRController handler class cannot be loaded"

**Comment by andresgutierrez** [comment]
@olivier-monaco could you please post the php code you used?

**Comment by olivier-monaco** [comment]
index.php
```php
<?php

use Phalcon\Mvc\View;
use Phalcon\Mvc\Application;
use Phalcon\DI\FactoryDefault;

try {
    $di = new FactoryDefault();

    $di->set('view', function(){
        $view = new View();
        $view->setViewsDir('../app/views/');
        return $view;
    });

    $router = new Phalcon\Mvc\Router(true);
    $di->set('router', $router, true);

    $application = new Application($di);
    echo $application->handle()->getContent();

}
catch (\Exception $e) {
     echo "PhalconException: ", $e->getMessage();
}
```

.htaccess
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]
</IfModule>
```

**Comment by olivier-monaco** [comment]
Problem comes from zephir_camelize.

From https://github.com/phalcon/cphalcon/blob/master/phalcon/dispatcher.zep#L632
```php
let camelizedClass = camelize(handlerName);
```

handlerName = CONTROLLER
camelizedClass = ControlleR

camelize function is replaced be C function named zephir_camelize. Problem comes from https://github.com/phalcon/zephir/blob/master/kernels/ZendEngine2/string.c#L288:
```php
	if (likely(i == len - 1)) {
		smart_str_appendc(&camelize_str, *marker);
	}
```

Last character is copied as-is. It must be "lowercased".

**Comment by andresgutierrez** [comment]
Fixed in latest Zephir

**Comment by ioncube** [comment]
Thanks Andres, and to Olivier for reproducing.
