### ISSUE TITLE
Improve Phalcon\Translate\Adapter::replacePlaceholders

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#10646]
Just gonna leave this here to refer on this issue.

Need extend `Adapter::replacePlaceholders` for using more simple translate `key => value` pars:

For example:
```
[
    'Hello %s' => 'Oi %s'
]
```

In the specific case, this can be solved as follows:

```php
class Translate extends \Phalcon\Translate\Adapter\NativeArray
{
    protected function replacePlaceholders($translation, $placeholders = null)
    {
        if (is_array($placeholders) && !empty($placeholders)) {
            array_unshift($placeholders, $translation);

            $translation = call_user_func_array('sprintf', $placeholders);
        }

        return $translation;
    }
}
```

I think by default `replacePlaceholders` shouldn't change (so as not to BC break), but if in ctor passed additional parameter/option - `replacePlaceholders` should use new algo.

**Comment by sergeyklay** [comment]
This can be used as follow:

```php
<?php echo $t->_("Hello %s", ['Andres']); ?>
```

**Comment by pauliuspetronis** [comment]
I can try implement this improvement

**Comment by pauliuspetronis** [comment]
@sergeyklay, You make this improvement? If not, then I can implement.

**Comment by sergeyklay** [comment]
@pauliuspetronis Try please. I have a lot of work now

**Comment by pauliuspetronis** [comment]
@sergeyklay I have improvement [here](https://github.com/pauliuspetronis/cphalcon/commit/2ce6b4db1e7c1f379001064f4189e3ac367d95a9). Maybe have comments? I'm not sure about my used terminology ["replacer"](https://github.com/pauliuspetronis/cphalcon/commit/2ce6b4db1e7c1f379001064f4189e3ac367d95a9#diff-4dfb116d0e7e31eae5eaa91ea5142a09R27) :)

**Comment by sergeyklay** [comment]
:+1: I thought about "Method" class name, but your variant is more human-readable

@andresgutierrez ?

**Comment by sergeyklay** [comment]
with tests :+1: :+1:

**Comment by andresgutierrez** [comment]
Now in 2.0.x branch
