### ISSUE TITLE
tel_field not wrapping values in array()

### ISSUE THREAD

**Issue by SoccerField24x7** [phalcon/cphalcon#10658]
Using 2.0.4 and trying to create a volt tel_field:
tel_field("phone", "class":"box")

In the error log:
[Tue Jul 14 18:40:04.681176 2015] [:error] [pid 5457] [client 45.50.41.42:64292] PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /usr/local/Sites/qbdn.com/app/cache/_usr_local_sites_qbdn.com_app_views_contact_index.volt.php on line 156

Line 156 in cache file:
<?php echo $this->tag->telField('phone', 'class' => 'box'); ?>

tel_field("name":"phone","class":"box")  produces the same error.

When I look at other lines in the cache file, the other field types all have the parameters wrapped in an array():
<?php echo $this->tag->textField(array('lname', 'class' => 'box', 'required' => 'required')); ?>
<?php echo $this->tag->emailField(array('email', 'class' => 'box', 'required' => 'required')); ?>

So, it would seem that the tel_field is missing some function call that wraps the passed in params, that the others have.

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch
