### ISSUE TITLE
JS Minifier not handling umlaut characters (åäö)

### ISSUE THREAD

**Issue by rahmen86** [phalcon/cphalcon#10657]
The problem here is that characters like å, ä and ö was removed and appeared as a space in the html (around 3 spaces in the js file). My workaround was to replace with \&auml; etc. The desired fix is to take those characters into account when minifying.

My testing:
https://gist.github.com/rahmen86/5226ef6c7609c7838de1

Thanks to @rianorie, who found the JS Minifier line that seems to be wrong:
https://github.com/phalcon/cphalcon/blob/master/ext/phalcon/assets/filters/jsminifier.c#L67

**Comment by andresgutierrez** [comment]
In Phalcon 2.0.5:

```php
$jsmin = new Phalcon\Assets\Filters\Jsmin();
echo $jsmin->filter("å, ä and ö");
````

Outputs:

```
å,ä and ö
```

**Comment by rahmen86** [comment]
@andresgutierrez: 
Maybe you have to put multiple files together as well.

I hope this gives any more hints to you. I'm not sure how these things work so I feel a bit lost...
https://gist.github.com/rahmen86/cabbd5b7cae0ec3db9f8

**Comment by andresgutierrez** [comment]
@rahmen86 I think you must see if this happens using the latest released version. Bugs are only fixed if they are raised in the latest version
