### ISSUE TITLE
[Issue] User limit and offset in query

### ISSUE THREAD

**Issue by KhanhKid** [phalcon/cphalcon#10666]
Dear Phalcon Team

This is my code

```php
$results = $ObjReviDeta::query()->columns('\Modules\User\Models\ReviewDetail.id,\Modules\User\Models\ReviewDetail.userid,c.name,\Modules\User\Models\ReviewDetail.compid,type,c.indusid,content,v.average,\Modules\User\Models\ReviewDetail.timestamp')
            ->join('\Modules\User\Models\Company', 'c.id = \Modules\User\Models\ReviewDetail.compid','c')
            ->join('\Modules\User\Models\CompanyAverage', 'v.compid = \Modules\User\Models\ReviewDetail.compid','v')
            ->where($condition)
            ->limit(8,0)
            ->orderby($sort)
            ->execute();
```

I use Phalcon 2.0.5
I need to limit 8 items and offset is 0 but the function is not working.
When I remove offset 0, ( -> limit(8) ). It's working.

Before I user Phalcon 2.0.2. The issue didn't appear :(
How can I fix it?

**Comment by williamokano** [comment]
Paste the generated query please.

**Comment by KhanhKid** [comment]
I'm doing to paste to generated query.... :(
$results = ReviewDetail::find(array(
                    $condition,
                    "order" => $sort,
                    "limit" => array("number" => 8, "offset" => $offset)
                ));
The same errors with model of Phalcon.... When I user offset. It's not working...
Only select all row (ignored limit ) ....
Is the Bug, right?

**Comment by alanbarber111** [comment]
Confirming this is a bug in phalcon/mvc/model/query/builder.zep:

```

			if is_numeric(limit) {

				let hiddenParam = this->_hiddenParamNumber,
					phql .= " LIMIT :AP" . hiddenParam . ":",
					this->_bindParams["AP" . hiddenParam] = intval(number, 10),
					this->_bindTypes["AP" . hiddenParam] = Column::BIND_PARAM_INT;

				if is_numeric(offset) {
					let hiddenParam++,
						phql .= " OFFSET :AP" . hiddenParam . ":",
						this->_bindParams["AP" . hiddenParam] = intval(offset, 10),
						this->_bindTypes["AP" . hiddenParam] = Column::BIND_PARAM_INT;
				}

				let this->_hiddenParamNumber = hiddenParam + 1;
			}
```
You can see hidenParam is incremented *every* time getPhql is called, meaning when the query is executed you get a too many bindings error

**Comment by alanbarber111** [comment]
See my PR:
https://github.com/phalcon/cphalcon/pull/10672

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.x branch

**Comment by KhanhKid** [comment]
Thank you @alanbarber111  and @andresgutierrez 
I will try to modify the builder.zep file.

**Comment by andresgutierrez** [comment]
@KhanhKid Maybe you should compile from ext/ in the 2.0.x branch instead of modify the file by yourself?

**Comment by KhanhKid** [comment]
@andresgutierrez  I will try it :).
Thank you so much for support quickly :). :+1:
