### ISSUE TITLE
Beanstalk: Invalid arguments supplied for explode()

### ISSUE THREAD

**Issue by iotch** [phalcon/cphalcon#10662]
Hello.
When listening for a new job and the server goes away, the following errors occurs:

> Warning: Invalid arguments supplied for explode() in \*myscript.php\* on line N
> Notice: Cannot use a scalar value as an array in phalcon/queue/beanstalk.zep on line 153

`explode()` error seems to be happening here - https://github.com/phalcon/cphalcon/blob/master/phalcon/queue/beanstalk.zep#L273

Steps to reproduce:

A.Start listening for a new job

    $bs = new \Phalcon\Queue\Beanstalk;
    $bs->reserve();

B. Stop or restart beanstalkd
```
    service beanstalkd stop
```

I think Beanstalk class should handle this case with exception telling that connection lost or something like that.

Thanks!

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch
