### ISSUE TITLE
Dump does not honor the name for basic variable types

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#10665]
According https://github.com/phalcon/cphalcon/blob/master/phalcon/debug/dump.zep#L226 if a variable is an integer, float, string and so on, the output does not contain the name, so this code dont show the name:

```php
echo (new \Phalcon\Debug\Dump())->variable(4, 'variable');
```

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch
