### ISSUE TITLE
toArray used to save in Phalcon\Mvc\Collection 2.0.5

### ISSUE THREAD

**Issue by Surt** [phalcon/cphalcon#10677]
After updating from 2.0.3 to 2.0.5 my Phalcon\Mvc\Collection's have a strange behaviour when using a setter. I'm using one to transform a string with datetime to a MongoDate, and it works well, the Collection object have this property assigned, but after saving the property is a string, not a mongoDate.

**Comment by Surt** [comment]
Don't know if it's refered to this change 
https://github.com/phalcon/cphalcon/commit/5f4fdf7003b0dcfb5adc20e1ce34c8fd97b7d471

**Comment by Surt** [comment]
I found the error. I'm overriding the ```toArray()``` method in the collection. This method is used now to save and I override it to use my getters for properties (the getters transforms de data back to my expected types, not the mongo ones, so during the save all is transformed)

I think that the use of a public method (toArray) to save is not recomended since it can drive to unexpected problems when overrided. What do you think?


P.D. By the way, I will really love to see https://github.com/phalcon/cphalcon/pull/10391 that one + a getters override. I'm doing to much transformations on models (try to separate the "entity" from the database, but I have to overwrite my toArrays, take care of using the getters instead accesing the property, and the same with the setters...

**Comment by Surt** [comment]
Here, a script to test the ```toArray``` problem

```php

<?php

error_reporting(E_ALL);

// mongo config
$config = [
    'username' => 'dev1',
    'password' => 'd9cYobr7iLowImP635bSm',
    'host'     => 'localhost',
    'port'     => '27017',
    'dbname'   => 'dev1'
];

class Robot extends \Phalcon\Mvc\Collection
{
    public $date_made;

    public function setDateMade($date_string)
    {
        $this->date_made = new MongoDate(strtotime($date_string));
    }

    public function getDateMade()
    {
        return date('Y-m-d h:i:s', $this->date_made->sec);
    }

    public function toArray()
    {
        $result = parent::toArray();
        $result['date_made'] = $this->getDateMade();
        return $result;
    } 
}

$di = new Phalcon\Di\FactoryDefault();
// Simple database connection to localhost
$di->set('mongo', function () use ($di, $config) {
    $connect_data = ($config)?"mongodb://" . $config['username'] . ':' . $config['password'] . '@' . $config['host'] . ':' . $config['port'] . '/' . $config['dbname']:null;
    $mongo = new \MongoClient($connect_data);
    return $mongo->selectDB($config['dbname']);
}, true);

$di->set('collectionManager', function () {
    return new Phalcon\Mvc\Collection\Manager();
}, true);


$robot = new Robot();
$robot->setDateMade('2015-04-05 12:00:00');

// check setter
echo "setter working";
var_dump($robot->date_made);
// check getter
echo "getter working";
var_dump($robot->getDateMade());
// save
$robot->save();

// check raw
var_dump($robot->date_made);
// check getter
var_dump($robot->getDateMade());

```

**Comment by andresgutierrez** [comment]
@SidRoberts can you take a look?

**Comment by SidRoberts** [comment]
How about using `beforeSave()` and `afterFetch()`?:

```php
class Robot extends \Phalcon\Mvc\Collection
{
    public $date_made;



    public function beforeSave()
    {
        $this->date_made = new MongoDate(strtotime($this->date_made));
    }

    public function afterFetch()
    {
        $this->date_made = date('Y-m-d h:i:s', $this->date_made->sec);
    }
}
```

This way, whenever you interact with `$robot->date_made`, it'll be a string but it'll get converted to a MongoDate when you save or update the model.

**Comment by Surt** [comment]
I would like to encapsulate the logic in each getter and setter, for better readability, but of course, actually thats the way to do it right now. Thanks @SidRoberts 

P.D. anyway the toArray used to save could be problematic, it exposes possible problems since you can override a common method wich is used internally to save without any advise in the documentation.
