### ISSUE TITLE
Scanning error before '' when parsing... 

### ISSUE THREAD

**Issue by Dm3Ch** [phalcon/cphalcon#10691]
Hello!
I'm writing RESTful API on PHP using `PhalconPHP` 2.0.5.
When I added to SQL querry `FROM_UNIXTIME()` I got error: `[Sun Jul 19 18:33:13.853158 2015] [:error] [pid 24575] [client 46.39.49.135:18026] PHP Fatal error:  Uncaught exception 'Phalcon\\Mvc\\Model\\Exception' with message 'Scanning error before '' when parsing: INSERT INTO readings (sensor_id, value, error, timestamp) VALUES (:sensor_id:, :value:, :error:, FROM_UNIXTIME( :timestamp: )); (127)' in /var/www/rest.technical-craft.ru/public/index.php:45\nStack trace:\n#0 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#1 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#2 /var/www/rest.technical-craft.ru/public/index.php(45): Phalcon\\Mvc\\Model\\Manager->executeQuery('INSERT INTO rea...', Array)\n#3 [internal function]: {closure}()\n#4 /var/www/rest.technical-craft.ru/public/index.php(70): Phalcon\\Mvc\\Micro->handle()\n#5 {main}\n  thrown in /var/www/rest.technical-craft.ru/public/index.php on line 45
`

The part of code with SQL

        $querry = "INSERT INTO readings (sensor_id, value, error, timestamp) VALUES (:sensor_id:, :value:, :error:, FROM_UNIXTIME( :timestamp: ));";

        $status = $app->modelsManager->executeQuery($querry, array(
            'sensor_id' =>$reading->sensor_id,
            'value' => $reading->value,
            'error' => $reading->error,
            'timestamp' => $reading->timestamp
        ));

P.S. I'm not sure it's bug, but i can't fix this error. On IRC and StackOverflow no one help me, so i write it here. Sorry for the wasted time if it's not an error.

**Comment by phalcon** [comment]
PHQL does not require the ; (dot-comma)

**Comment by Dm3Ch** [comment]
Ok, thank you! It doesn't require, but why it is error?
But I got new problem. I had got this problem earlier, but I didn't solve it.

[Mon Jul 20 00:08:31.207051 2015] [:error] [pid 24060] [client 46.39.49.135:17164] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters' in /var/www/rest.technical-craft.ru/public/index.php:42\nStack trace:\n#0 [internal function]: PDOStatement->execute()\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->execute('INSERT INTO `re...', Array, Array)\n#3 [internal function]: Phalcon\\Db\\Adapter->insert('readings', Array, Array, Array)\n#4 [internal function]: Phalcon\\Mvc\\Model->_doLowInsert(Object(Phalcon\\Mvc\\Model\\MetaData\\Memory), Object(Phalcon\\Db\\Adapter\\Pdo\\Mysql), 'readings', 'id')\n#5 [internal function]: Phalcon\\Mvc\\Model->save(Array, NULL)\n#6 [internal function]: Phalcon\\Mvc\\Model->create(Array)\n#7 [internal function]: Phalcon\\Mvc\\Model\\Query->_executeInsert(Array, Array, NULL)\n#8 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#9 /var/www/rest.technical-craft.ru/public/index.php(42): Phalcon\\Mvc\\Model\\Manager-> in /var/www/rest.technical-craft.ru/public/index.php on line 42

**Comment by SidRoberts** [comment]
When using the Models Manager you're actually using [PHQL](https://docs.phalconphp.com/en/latest/reference/phql.html), not SQL.

If you want to use PHQL, the "table name" (SELECT * FROM *table*) has to match the class name (presumably `SELECT * FROM Readings` or `SELECT * FROM Models\Readings`).

If you want to use SQL, [`$this->db->executePrepared()`](https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/db/adapter/pdo.zep#L174) or [`$this->db->execute()`](https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/db/adapter/pdo.zep#L330) may be what you're looking for. Note that regular SQL takes prepared statements in the form of `:name` (not `:name:`).

Hopefully these might solve the problem or at least give you a better error message. :smile:

**Comment by Dm3Ch** [comment]
Ok. But how can I insert timestamp into mysql using phql? If i remove `FROM_UNIXTIME()` I get in DB row with 00-00-0000 00:00:00.

**Comment by SidRoberts** [comment]
Personally, I would convert the timestamp in PHP:

```php
    $dateTime = \DateTime::createFromFormat('U', $timestamp);
    $sqlFriendlyDateTime = $dateTime->format('Y-m-d H:i:s');
```

[More information about DateTime::createFromFormat is available the PHP manual](http://php.net/manual/en/datetime.createfromformat.php).

**Comment by Dm3Ch** [comment]
Thank you for help!
