### ISSUE TITLE
$this->session->destroy(); does not work!

### ISSUE THREAD

**Issue by hardlick** [phalcon/cphalcon#10696]
i have:

    $di->setShared('session', function() {
     $session = new Phalcon\Session\Adapter\Files();
     $session->start();
     return $session;
    });

On controller:

     $this->session->set(self::BTS_SESSION_USER_ID, $o_user->getIduser());
and after:

    $this->session->destroy();
     var_dump($this->session->get(self::BTS_SESSION_USER_NAME));

And response with data!.

**Comment by andresgutierrez** [comment]
destroy() calls session_destroy() which is a PHP built-in function:

https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/session/adapter.zep#L220

**Comment by hardlick** [comment]
@andresgutierrez  i changed redis session to native session:

    $di->setShared('session', function() {
    $session = new Phalcon\Session\Adapter\Files();
    $session->start();
    return $session;
   });

On controller:

    $this->session->set(self::BTS_SESSION_USER_ID, $o_user->getIduser());
and after:

    $this->session->destroy();
    var_dump($this->session->get(self::BTS_SESSION_USER_NAME));

And response with data!.
The same problem!...

**Comment by andresgutierrez** [comment]
In the description of session_destroy:

```
session_destroy() destroys all of the data associated with the current session. It does not unset any of the global variables associated with the session, or unset the session cookie. To use the session variables again, session_start() has to be called.

In order to kill the session altogether, like to log the user out, the session id must also be unset. If a cookie is used to propagate the session id (default behavior), then the session cookie must be deleted. setcookie() may be used for that.
```

**Comment by hardlick** [comment]
I added:

     setcookie(session_name(), '', time()-42000, '/'); 
     session_destroy();
     var_dump($this->session->get(self::BTS_SESSION_USER_NAME));

But The same problem!,can you help me please,  how do you remove all session data?

**Comment by andresgutierrez** [comment]
session_destroy() does not remove any data from the superglobal $_SESSION, you have to remove it:

```php
$this->session->remove(self::BTS_SESSION_USER_NAME);
```

**Comment by hardlick** [comment]
Ok thanks! @andresgutierrez ,

i used:

    session_unset();
    session_regenerate_id(true);
    var_dump($this->session->get(self::BTS_SESSION_USER_NAME));

And response NULL!,

works!, the reason that i want to destroy all session data, not only one key, for example for logout 

there is any way to do that? with : $this->session-> ?

**Comment by andresgutierrez** [comment]
I added an option to Phalcon 2.0.7 to remove data in _SESSION:

```php
$this->session->destroy(true);
```
