### ISSUE TITLE
Feature Request: Allow implicit joins to be turned off because they block more complicated queries from being possible

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10704]
Simply:

```php
  'no_implicit_joins_just_right_now_please' => YES
```

would be nice.  It would help to alleviate the immediate pains of bug #10526.

**Comment by dschissler** [comment]
Due to the nature of the other bug this won't immediately help me but it might someday help some adapter pioneers out a lot.

**Comment by dschissler** [comment]
This is my solution so far:

```
		if this->_explicit_joins_only == true {
			for joinItem in selectJoins {
				let joinAlias = joinItem["alias"]["name"];

				let joinType = joinTypes[joinAlias];
				let joinSource = joinSources[joinAlias];
				let sqlJoins[] = [
					"type": joinType,
					"source": joinSource,
					"conditions": [joinPreCondition[joinAlias]]
				];
			}
			return sqlJoins;
		}
```

**Comment by andresgutierrez** [comment]
@dschissler where is that fragment of code located?

**Comment by dschissler** [comment]
[Line 430](https://github.com/phalcon/cphalcon/blob/4651c14873fb903d495431835d3a2af196e35035/phalcon/mvc/model/query.zep#L1430).  I just short circuited the loop to avoid so much bracing and tab madness.

**Comment by dschissler** [comment]
@andresgutierrez Here is my modified constructor:

```
	/**
	 * Phalcon\Mvc\Model\Query constructor
	 *
	 * @param string phql
	 * @param \Phalcon\DiInterface dependencyInjector
	 */
	public function __construct(phql = null, <DiInterface> dependencyInjector = null, options = null)
	{
		var explicit_joins_only;

		if typeof phql != "null" {
			let this->_phql = phql;
		}

		if typeof dependencyInjector == "object" {
			this->setDI(dependencyInjector);
		}

		let this->_explicit_joins_only = false;
		if typeof options == "array" {
			if fetch explicit_joins_only, options["explicit_joins_only"] {
				// let this->_explicit_joins_only = (explicit_joins_only == true);
				let this->_explicit_joins_only = true;
			}
		}
	}
```

**Comment by andresgutierrez** [comment]
You can better take the global configuration variables approach:

* https://github.com/phalcon/cphalcon/blob/master/config.json#L84-L87
* https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/resultset/simple.zep#L111

**Comment by dschissler** [comment]
Oh, but I do really like the implicit joins for all of the mundane stuff and I'd hate to lose it.  It could always be added later with a simple `||`.  I mostly just see this as a way to get Phalcon out of the way until it can catch up to a use case because otherwise you are 100% shit out of luck.  Then the developer can move forward making their program while submitting a bug report to later tidy up their code by having Phalcon do more automatic stuff for them.

**Comment by dschissler** [comment]
@andresgutierrez I'm trying to use class constants but I can't figure out the syntax to :

```
		let this->_explicitJoinsOnly = false;
		if typeof options == "array" {
			if fetch joinStrategy, options[self::OPTION_JOIN_STRATEGY] {
				let this->_explicitJoinsOnly = (joinStrategy == self::EXPLICIT_JOINS);
			}
		}
```

**Comment by dschissler** [comment]
I'll offer global and local options for forcing explicit joins.

Also, I was dreaming last night about special SQL syntax like this:

```
SELECT ...
EXPLICIT LEFT JOIN ...
```

So that it could be turned off for only a single join.  Of course though this would require enormous efforts.

**Comment by dschissler** [comment]
Implemented
