### ISSUE TITLE
[2.0.4] PHQL DISTINCT does not work for my case due to inappropriate implicit join

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10705]
Between bugs #10526 and #10507 I'm tempted to remove all of the assigned relationships to severals core models that make up all of the interesting parts of my user data and to only use the assigned relationships for the mundane admin related models.

There is no way to get the phql below to work with the joining as it is now.  I need to be able to specify that Placement is joining against `SuperRecord` and not `Record`.

```php
        $phql = <<<PHQL
SELECT DISTINCT Record.*
FROM $Record Record
LEFT JOIN $Type Type ON Type.recordsId = Record.id
LEFT JOIN $Attribute Attribute ON Attribute.recordsId = Record.id
... conditions
AND
EXISTS (
  SELECT SuperRecord.*
  FROM $Record SuperRecord
  LEFT JOIN $Placement Placement ON Placement.setId = SuperRecord.id
... conditions
)
PHQL;
```

In my case I actually have two assigned relationships between `Placement` and `Record` (so another edge case) and I get this error message: `There is more than one relation between models 'Webird\Data\Record' and 'placement', the join must be done using an alias, when preparing: SELECT DISTINCT Record.*`.  Ok, but aliases are very broken when things start getting complicated (mostly I guess due to #10526) and the forced implicit joins.

I think a more comprehensive rework of the joining and aliases is necessary but for now I've created a more simple bug #10704 to let Phalcon get out of the way as people push the ORM into strange database specific use cases.

**Comment by dschissler** [comment]
When I explicitly declared the join conditions inside the EXISTS it ended up listing it out **3** times.  Wow!  Something needs to get cleared out.

```php
...
EXISTS (
  SELECT `SuperRecord`.* FROM `record` AS `SuperRecord`
  LEFT JOIN `placement` AS `Placement` ON `Placement`.`setId` = `SuperRecord`.`id`
  LEFT JOIN `type` AS `Type` ON `Type`.`recordsId` = `SuperRecord`.`id`
  LEFT JOIN `attribute` AS `Attribute` ON `Attribute`.`recordsId` = `SuperRecord`.`id`
  LEFT JOIN `placement` AS `Placement` ON `Placement`.`setId` = `SuperRecord`.`id`
  LEFT JOIN `type` AS `Type` ON `Type`.`recordsId` = `SuperRecord`.`id`
  LEFT JOIN `attribute` AS `Attribute` ON `Attribute`.`recordsId` = `SuperRecord`.`id`
  LEFT JOIN `placement` AS `Placement` ON `Placement`.`setId` = `SuperRecord`.`id`
  LEFT JOIN `type` AS `Type` ON `Type`.`recordsId` = `SuperRecord`.`id`
  LEFT JOIN `attribute` AS `Attribute` ON `Attribute`.`recordsId` = `SuperRecord`.`id`
  WHERE `Placement`.`elementId` = `Record`.`id` AND `SuperRecord`.`id` = :2
)
```

**Comment by dschissler** [comment]
I ran an experiment where I commented out all of the relation definitions in the initialize() of the models so that only the explicit conditions in the phql would be used. 

```php
        $phql = <<<PHQL
SELECT DISTINCT Record.*
FROM $Record Record
LEFT JOIN $Type Type ON Type.recordsId = Record.id
LEFT JOIN $Attribute Attribute ON Attribute.recordsId = Record.id
AND
EXISTS (
  SELECT SuperRecord.*
  FROM $Record SuperRecord
  LEFT JOIN $Placement Placement ON Placement.setId = SuperRecord.id
  WHERE Placement.elementId = Record.id AND SuperRecord.id = ?1
)
PHQL;
```

It did something really weird in the EXISTS group.

```sql
SELECT DISTINCT `Record`.`id`, `Record`.`active`, `Record`.`type`
FROM `record` AS `Record`
LEFT JOIN `type` AS `Type` ON `Type`.`recordsId` = `Record`.`id`
LEFT JOIN `attribute` AS `Attribute` ON `Attribute`.`recordsId` = `Record`.`id`
AND
EXISTS (
  SELECT `SuperRecord`.* FROM `record` AS `SuperRecord`
  LEFT JOIN `placement` AS `Placement` ON `Placement`.`setId` = `SuperRecord`.`id`
  LEFT JOIN `placement` AS `Placement` ON `Placement`.`setId` = `SuperRecord`.`id`
  LEFT JOIN `placement` AS `Placement` ON `Placement`.`setId` = `SuperRecord`.`id`
  WHERE `Placement`.`elementId` = `Record`.`id` AND `SuperRecord`.`id` = :1
)
```

@phalcon What the heck is going on in there?  Is nobody else doing interesting things with the ORM?  I'm getting bit in the ass with this duplicating condition thing every time I try to join.

**Comment by dschissler** [comment]
@phalcon I'm at a point now where I seem to be pushing new ground and routinely hitting Phalcon bugs I'm at a point where I can really benefit from Phalcon features such as the ability to easily switch literals on and off and also being able to used named parameters more than once.  I'm almost all in now so its better that I try to fix the Zephir code instead of working around it in PHP and its time one way or the other.  Between ES5, ES2015-2016, PHP, SQL and learning Russian I'm a bit full on languages and syntax but I'll try to fit Zephir in.  At the very least I can easily run through the code and point out bad lines.

**Comment by dschissler** [comment]
I'm looking through `mvc/model/query.zep` and I'm thinking that the variables could have some better names:

```
			sqlAliases = this->_sqlAliases,
			sqlAliasesModels = this->_sqlAliasesModels,
			sqlModelsAliases = this->_sqlModelsAliases,
			sqlAliasesModelsInstances = this->_sqlAliasesModelsInstances,
```

**Comment by dschissler** [comment]
I made an important discovery that every JOIN in the main SELECT is causing the JOIN clause to duplicate within the EXISTS.  So if I remove both `LEFT JOIN` clauses in the top part then there is no duplication.  If I add one LEFT JOIN then there is a single duplication.

**Comment by dschissler** [comment]
@phalcon

I've been able to work around this by adding the following into `Query::_getJoins`:

```
		if this->_explicit_joins_only == true {
			for joinItem in selectJoins {
				let joinAlias = joinItem["alias"]["name"];

				let joinType = joinTypes[joinAlias];
				let joinSource = joinSources[joinAlias];
				let sqlJoins[] = [
					"type": joinType,
					"source": joinSource,
					"conditions": [joinPreCondition[joinAlias]]
				];
			}
			return sqlJoins;
		}
```

I added a third options parameter to the Query class.  I'm still early in this and I'd like to make some progress understanding the loop below better.  I think that the problem might be [here](https://github.com/phalcon/cphalcon/blob/4651c14873fb903d495431835d3a2af196e35035/phalcon/mvc/model/query.zep#L1504).

**Comment by dschissler** [comment]
@andresgutierrez I'll push out a repo for you to evaluate in a day or two because I think that I fixed it this issue.  It was using the global list of models instead of only the ones for that select statement.  It took me a while to figure out which data structures to use.  We'll see if it passes the tests.

```
// New code in top level of method
		let tables = select["tables"];
		if !isset tables[0] {
			let selectTables = [tables];
		} else {
			let selectTables = tables;
		}

// New code in top level of method
		let fromModelsFixed = [];

		for tableItem in selectTables {
			let table = tableItem["qualifiedName"]["name"];
			let fromModelsFixed[table]	= true;
		}

		/**
		 * Create join relationships dynamically
		 */
		let manager = this->_manager;

		// for fromModelName, _ in fromModels {
		for fromModelName, _ in fromModelsFixed {

```

**Comment by dschissler** [comment]
My Phalcon pull request fixes this issue and now I'm able to run the following off of my Phalcon build.  I'm sort of hand pasting the phql in a routine and using literals since there are small issues with the way that I'm building the query strings.

I'm using implicit joins on the first part and then explicit joins later 

```
SELECT Record.*
FROM Webird\Data\Record Record
LEFT JOIN Webird\Data\Type Type
LEFT JOIN Webird\Data\Attribute Attribute
WHERE Type.isa = 'file'
AND EXISTS (
  SELECT SuperRecord.*
  FROM Webird\Data\Record SuperRecord
  LEFT JOIN Webird\Data\Placement Placement ON Placement.setId = SuperRecord.id
  LEFT JOIN Webird\Data\Type Type ON Type.recordsId = SuperRecord.id
  LEFT JOIN Webird\Data\Attribute Attribute ON Attribute.recordsId = SuperRecord.id
  WHERE
    Placement.elementId = Record.id AND SuperRecord.id = 1
    AND
    Type.isa = 'dir' AND Attribute.mode = 'sys' AND Attribute.property = 'root'
)
```

In fact the following works as well and I only have to leave the explicit join on placement because there are two relations between those models.

```
$phql = <<<PHQL
SELECT Record.*
FROM $Record Record
LEFT JOIN $Type Type
LEFT JOIN $Attribute Attribute
WHERE Type.isa = 'file'
AND EXISTS (
  SELECT SuperRecord.*
  FROM $Record SuperRecord
  LEFT JOIN $Placement Placement ON Placement.setId = SuperRecord.id
  LEFT JOIN $Type Type
  LEFT JOIN $Attribute Attribute
  WHERE
    Placement.elementId = Record.id AND SuperRecord.id = 1
    AND
    Type.isa = 'dir' AND Attribute.mode = 'sys' AND Attribute.property = 'root'
)
PHQL;
```

So I'd say that PHQL is pretty damn smart now, and it works!!!

**Comment by andresgutierrez** [comment]
@dschissler Can you please close this issue?

**Comment by dschissler** [comment]
I'll try running all of the scripts tomorrow to see if it is fixed.  I saw that you did something a few days ago that looked related to this issue.

**Comment by dschissler** [comment]
Actually I will close this.  I was confused with the other bugs.
