### ISSUE TITLE
Cookie crypt/Decrypt with short key value and \0 symbols

### ISSUE THREAD

**Issue by Horrower** [phalcon/cphalcon#10718]
https://forum.phalconphp.com/discussion/364/d-encryption-cookies-problem 
We spent many time for fixing this issue.
Please make 
$Crypt->setMode(MCRYPT_MODE_CFB);
as Default mode

**Comment by andresgutierrez** [comment]
We can do this in Phalcon 2.1

**Comment by andresgutierrez** [comment]
Changed mode in 2.1.0
