### ISSUE TITLE
Is Phalcon\Session\Adapter\Redis duplicated?

### ISSUE THREAD

**Issue by PyYoshi** [phalcon/cphalcon#10714]
- https://github.com/phalcon/cphalcon/blob/master/phalcon/session/adapter/redis.zep
- https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Session/Adapter/Redis.php

**Comment by Green-Cat** [comment]
https://github.com/phalcon/incubator/pull/392 Made a pull request for it.

**Comment by Green-Cat** [comment]
https://github.com/phalcon/incubator/pull/392#event-364329845 has now been merged. This can be closed.

**Comment by PyYoshi** [comment]
Thanks!
