### ISSUE TITLE
Latest build failed with Zephir

### ISSUE THREAD

**Issue by nask0** [phalcon/cphalcon#10724]
home cphalcon # git remote -v
origin	https://github.com/phalcon/cphalcon (fetch)
origin	https://github.com/phalcon/cphalcon (push)
home cphalcon # zephir version
0.7.1b
home cphalcon # zephir build
Warning: Class "APCIterator" does not exist at compile time in /home/nask0/src/git/cphalcon/phalcon/cache/backend/apc.zep on 221 [nonexistent-class]

	   apc = new \APCIterator("user", prefixPattern);
	------------------------------------------------^

Warning: Class "APCIterator" does not exist at compile time in /home/nask0/src/git/cphalcon/phalcon/cache/backend/apc.zep on 263 [nonexistent-class]

	  for item in iterator(new \APCIterator("user")) {
	-----------------------------------------------^

Warning: Function "yaml_parse" does not exist at compile time in /home/nask0/src/git/cphalcon/phalcon/queue/beanstalk.zep on 297 [nonexistent-function]

	   let data = yaml_parse(response);
	----------------------------------^

Copying new kernel files...
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information

home cphalcon # cat compile-errors.log 
/home/nask0/src/git/cphalcon/ext/phalcon/assets/filters/cssmin.zep.c:15:48: fatal error: phalcon/assets/filters/cssminifier.h: No such file or directory
compilation terminated.
make: *** [phalcon/assets/filters/cssmin.lo] Error 1
make: *** Waiting for unfinished jobs....
/home/nask0/src/git/cphalcon/ext/phalcon/assets/filters/jsmin.zep.c:15:47: fatal error: phalcon/assets/filters/jsminifier.h: No such file or directory
compilation terminated.
make: *** [phalcon/assets/filters/jsmin.lo] Error 1
/home/nask0/src/git/cphalcon/ext/phalcon/assets/filters/cssmin.zep.c:15:48: fatal error: phalcon/assets/filters/cssminifier.h: No such file or directory
compilation terminated.
make: *** [phalcon/assets/filters/cssmin.lo] Error 1
home cphalcon #

**Comment by andresgutierrez** [comment]
Do you have the latest Zephir?

It seems there are missing files in your local cloned repository, but the files are there:

* https://github.com/phalcon/cphalcon/blob/master/ext/phalcon/assets/filters/cssminifier.h
* https://github.com/phalcon/cphalcon/blob/master/ext/phalcon/assets/filters/jsminifier.h

**Comment by nask0** [comment]
You're right, mistake is on my side, sorry for false positive.
However, there are a few warnings, but nothing fatal : 
```
Warning: Class "APCIterator" does not exist at compile time in /mnt/301d7a40-8c00-4bbf-bae9-c11cc9320e48/src/git/cphalcon/phalcon/cache/backend/apc.zep on 221 [nonexistent-class]
	   apc = new \APCIterator("user", prefixPattern);
	------------------------------------------------^

Warning: Class "APCIterator" does not exist at compile time in /mnt/301d7a40-8c00-4bbf-bae9-c11cc9320e48/src/git/cphalcon/phalcon/cache/backend/apc.zep on 263 [nonexistent-class]
	  for item in iterator(new \APCIterator("user")) {
	-----------------------------------------------^

Warning: Function "yaml_parse" does not exist at compile time in /mnt/301d7a40-8c00-4bbf-bae9-c11cc9320e48/src/git/cphalcon/phalcon/queue/beanstalk.zep on 297 [nonexistent-function]
	   let data = yaml_parse(response);
	----------------------------------^
```

Thanks and keep up the good work. Let me know if you need more info or help.

**Comment by andresgutierrez** [comment]
These warnings are caused due to missing extensions in your system apc and yaml.

**Comment by nask0** [comment]
Exactly, thanks,
