### ISSUE TITLE
[2.0.6] paginator/querybuilder total_items bug

### ISSUE THREAD

**Issue by DestinyMKas** [phalcon/cphalcon#10725]
Hello,

if builder has set groupby, then $paginator->total_items shows wrong result.

I think, groupBy and having should be removed when counting total lines.

**Comment by DestinyMKas** [comment]
This way is not good too. We need to keep groupby and having.

I solved this puzzle in this way:

SELECT sum(t.row_count) as total FROM (SELECT count(*) as row_count ............... ) as t;

**Comment by DestinyMKas** [comment]
Another way:

$data = clone $this->getData();
$data->columns(sprintf('COUNT(*) as [total]', $this->getName()));
if ($data->getGroupBy() != '') {
	$this->total = $data->getQuery()->execute()->count();
} else {
	$this->total = $data->getQuery()->execute()->getFirst()->total;
}

**Comment by andresgutierrez** [comment]
Duplicate of #2411
