### ISSUE TITLE
Uncommon behaviour rendering Volt

### ISSUE THREAD

**Issue by uLow** [phalcon/cphalcon#10728]
Just started to explain to my junior volt's includes and partials with showing a little bit of "under the hood". I was surprised when my explanation did not fit with reality.

Lets asume we have `index.volt`
```twig
<div>{% include "index/test" with ['world': 'sandbox'] %}</div>
<div>{{ partial("index/test", ['world': 'sandbox']) }}</div>
```
In fact it's just the same according to the documentation examples. Lets look into cached variation:
```php
<div><?php $this->partial('index/test', array('world' => 'sandbox')); ?></div>
<div><?php echo $this->partial('index/test', array('world' => 'sandbox')); ?></div>
```

Where was ***echo*** came from?

**Comment by andresgutierrez** [comment]
{{ }} are used to print the results of the evaluated expression. {% do ... %} is used to evaluate the expression without print the result.

**Comment by uLow** [comment]
https://docs.phalconphp.com/en/latest/reference/volt.html#view-integration

Do you confirm that mistake comes from documentation and we all have to use
```twig
<div>{% include "index/test" with ['world': 'sandbox'] %}</div>
<div>{% partial("index/test", ['world': 'sandbox']) %}</div>
```
?

**Comment by uLow** [comment]
Also, there is told that `Templates aren’t inlined if the ‘include’ have variables passed with ‘with’`. That's not true, because if we provide 'with', we get `View not found` exception there.
```twig
<div>{% include "index/test.volt" %}</div>
{#<div>{% include "index/test.volt" with ['world': 'sandbox'] %}</div> Exception here#}
```

**Comment by andresgutierrez** [comment]
@uLow It's true, if you pass variables the template can't be inlined. It has to use the `partial` helper. Also, if you don't specify the extension it won't be inlined.

Regarding the first example, the documentation uses {{ }} for partial because it's short, knowing in advance that an implicit `echo null` is done, if this is uncomfortable you can use {% do ... %}
