### ISSUE TITLE
多级缓存Phalcon\Cache\Multiple没有清除缓存flush方法

### ISSUE THREAD

**Issue by gufei** [phalcon/cphalcon#10737]
建议在多级缓存Phalcon\Cache\Multiple增加清除缓存的flush方法

public function flush() -> boolean
{
	var backend;
	for backend in this->_backends {
		backend->flush();
	}
	return true;
}

**Comment by andresgutierrez** [comment]
Implemented in 2.0.x branch

**Comment by gufei** [comment]
2.0.x 仍然没有这个方法
