### ISSUE TITLE
not work on WinServer 2008 R2 x64 16 gb ram

### ISSUE THREAD

**Issue by mindochin** [phalcon/cphalcon#10733]
with openserver (http://open-server.ru/) - apache 2.2 and php 5.4
unknown error "PHP startup:"

**Comment by mindochin** [comment]
v1.3 work

**Comment by andresgutierrez** [comment]
VC11 builds are only available for PHP 5.5 and 5.6

**Comment by mindochin** [comment]
well,where to download? see older versions only

**Comment by andresgutierrez** [comment]
@mindochin we're recompiling VC11, will let you know

**Comment by mindochin** [comment]
thanks!

**Comment by andresgutierrez** [comment]
Now available: https://phalconphp.com/en/download/windows
