### ISSUE TITLE
2.0.x form bind entity

### ISSUE THREAD

**Issue by DestinyMKas** [phalcon/cphalcon#10738]
Hello,

I have contact form, which I want to send by email. Actually I have no model and no entity. When I want to validate it, I'm trying to 

```php
$form->bind($this->request->getPost());
```

But this is wrong, because second param (entity) is required.

I can workaround with

```php
$form->bind($this->request->getPost(), \stdClass());
```

But I think, entity should not be a required param, because:
__construct() and isValid() methods has entity and it is not required.

**Comment by andresgutierrez** [comment]
But bind() means "bind" this data to this "entity", you can't bind without an entity

**Comment by DestinyMKas** [comment]
Hmm.. I think $form->bind() means bind data to form, not to entity.

Ex:

```php
$form = new Form();

$form->add($element);
$form->add($element1);
$form->add($element2);

$form->bind($someData);

if ($form->isValid()) {
  doSomething();
}
```

Is this code is not logic?

**Comment by andresgutierrez** [comment]
You can pass $someData to isValid, "bind" is used to bind data to the entity

**Comment by DestinyMKas** [comment]
$entity->assign($someData) is used to bind data to the entity.
$form->bind() should be used to bind data to form.
