### ISSUE TITLE
LIMIT array not passing actual value?

### ISSUE THREAD

**Issue by SoccerField24x7** [phalcon/cphalcon#10746]
I am using a custom adapter/dialect for MSSQL.  The parameters being passed to the SQL `select` method does not contain the limit value.

Calling code:
```php
$customers = Customers::find(array(
			"limit"		=>	2,
			"order"		=>  "id DESC"
		));
```

In dialect file:
```php
public function select(array $definition) {
    print_r($definition);
...
}
```
Produces array value:
```php
Array ( [models] => Array ( [0] => Customers ) [tables] => Array ( [0] => customers ) [columns] => Array ( [0] => Array ( [0] => id [1] => customers ) [1] => Array ( [0] => name [1] => customers ) [2] => Array ( [0] => contacts [1] => customers ) [3] => Array ( [0] => addresses [1] => customers ) [4] => Array ( [0] => credit_limit [1] => customers ) ) [order] => Array ( [0] => Array ( [0] => Array ( [type] => qualified [domain] => customers [name] => id [balias] => id ) [1] => DESC ) ) [limit] => Array ( [number] => Array ( [type] => placeholder [value] => :AP0 ) ) )
```
This does work in the Mysql adapter, so perhaps there is something I am just doing incorrectly, or a step I am missing.

The value was accessible in Phalcon 2.0.2, but I see in the 2.0.4 release notes you changed the method of passing the value.  I've tested 2.0.5 and 2.0.6 and both do not contain the limit value.

Thank you!

**Comment by SoccerField24x7** [comment]
I can give you direct access to my testing environment if you want to contact me directly.  Don't want to post it here for obvious reasons. :)

**Comment by andresgutierrez** [comment]
As we don't support SQL server, I'm not sure how I can accept this as a bug.

**Comment by SoccerField24x7** [comment]
I understand.  I think it may still be relevant as what *seems* to be happening is that the limit values aren't being passed, but perhaps I am just not knowledgeable enough.  You can tell me.  Basically, we have this:
```php
class Mssql extends \Phalcon\Db\Dialect {
     public function select(array $definition) {
         print_r($definition);
    }
}
```
Should $definition have the limit values contained in the array if I specified them in ::find()?  If yes, I think there's a bug.  If no, close the ticket and it will just be me not understanding.

**Comment by andresgutierrez** [comment]
Limit values are passed as bound parameters, can you post the output of $definition?

**Comment by SoccerField24x7** [comment]
It's there in the original post.  LIMIT shows as:
```php
[limit] => Array ( [number] => Array ( [type] => placeholder [value] => :AP0 ) )
```

**Comment by andresgutierrez** [comment]
It passes the limit using bound parameters, so you have to generate something like:

```sql
LIMIT :AP0
```

Then when the query is executed there is a variable call bindParams that has the value for AP0. Probably PDO with emulate prepares enabled will replace this parameter client-side if SQL server does not support it.

**Comment by SoccerField24x7** [comment]
Got it!  No bug then, just me not fully understanding.
