### ISSUE TITLE
Phalcon\Mvc\Model\Validator\Uniqueness didn't support mongodb

### ISSUE THREAD

**Issue by noel-ykt** [phalcon/cphalcon#10744]
PHP Version 5.6.4-4ubuntu6.2
Mongo 1.6.10
Phalcon 2.0.5, Build Date Jul 14 2015 08:19:05

...Uncaught exception 'RuntimeException' with message 'Call to undefined method Tops::getschema()'...

```
use Phalcon\Mvc\Collection,
    Phalcon\Mvc\Model\Message,
    Phalcon\Mvc\Model\Validator\Uniqueness;
class Tops extends Collection {

    public function validation() {
        $this->validate(new Uniqueness(
            array(
                "field"   => "href",
                "message" => "The top href must be unique"
            )
        ));
        return $this->validationHasFailed() != true;
    }
}
```

i find issue #2585 :(

**Comment by Jurigag** [comment]
`Phalcon\Validation\Validator\Uniqueness` now supprt mongodb php 5.x in phalcon 3.1.x. There still need to be change done incubator for php 7.x but i guess when phalcon 3.1.0 will be relased it will be there.
