### ISSUE TITLE
[NFR] getAttributeScopes() method for Phalcon\Mvc\Model\MetaData

### ISSUE THREAD

**Issue by galki** [phalcon/cphalcon#10743]
Consider the following model.

``` php
class User extends \Phalcon\Mvc\Model
{
    public $id;
    public $username;
    public $email;

    protected $password;
    protected $status_id;
    protected $created_time;

    private $is_deleted;
}
```

In order to for example connect a complex ACL based security plugin to this model, a developer would need to know which ACL role can view/edit which attributes. So _getAttributeScopes_ would return:

``` php
Array
(
    [id]           => 'public'
    [username]     => 'public'
    [email]        => 'public'
    [password]     => 'protected'
    [status_id]    => 'protected'
    [created_time] => 'protected'
    [is_deleted]   => 'private'
)
```

**Comment by sergeyklay** [comment]
:+1:

**Comment by andresgutierrez** [comment]
You can do this using reflection

**Comment by galki** [comment]
Reflection did the job. Thank you!

By the way, what's the criteria for accepting a NFR such as this (a convenience method)? I want to know so I can post better in the future.
