### ISSUE TITLE
compile error on Centos-6.6

### ISSUE THREAD

**Issue by zaibkiani** [phalcon/cphalcon#10750]
php version is 5.3.3

 -O2 -fomit-frame-pointer -fvisibility=hidden -c /usr/src/cphalcon/build/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
/usr/src/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_fetch_static_property_ce':
/usr/src/cphalcon/build/64bits/phalcon.zep.c:6961: warning: passing argument 2 of 'zend_read_static_property' discards qualifiers from pointer target type
/usr/include/php/Zend/zend_API.h:321: note: expected 'char *' but argument is of type 'const char *'
/usr/src/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_update_static_property_ex':
/usr/src/cphalcon/build/64bits/phalcon.zep.c:7071: warning: passing argument 2 of 'zend_std_get_static_property' discards qualifiers from pointer target type
/usr/include/php/Zend/zend_object_handlers.h:147: note: expected 'char *' but argument is of type 'const char *'
/usr/src/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_require_ret':
/usr/src/cphalcon/build/64bits/phalcon.zep.c:12632: warning: assignment discards qualifiers from pointer target type
/usr/src/cphalcon/build/64bits/phalcon.zep.c: At top level:
/usr/src/cphalcon/build/64bits/phalcon.zep.c:138267: error: 'ZEND_FE_END' undeclared here (not in a function)
make: *** [phalcon.lo] Error 1

**Comment by phalcon** [comment]
Php 5.3.3 is not supported, you have to use 5.3.21 at least
