### ISSUE TITLE
LIMIT param not avail offset?

### ISSUE THREAD

**Issue by AndrewUshchenko** [phalcon/cphalcon#10753]
I used before ```ModelName::find([
'limit'=>[
      'number'=>5,
      'offset'=>10,
    ]
]);```
Resulting in a request to the following form ``SELECT * FROM model_name LIMIT 0,5``
Who is setting the ``limit`` stops working with an array, only the number, and I have to write parameter ``offset``, for example:
``ModelName::find([
    'limit'=>5,
    'offset'=>10
]);``
I use PDO for MySQL.
This is a bug?

**Comment by andresgutierrez** [comment]
This is already fixed in 2.0.6
