### ISSUE TITLE
PhalconEye Error message

### ISSUE THREAD

**Issue by idlleF** [phalcon/cphalcon#10756]
Hi there.
I was installed phalcon 2.0.6 and phalconeye 0.4.1 after configuration i tried to start CMS but get those errors 
'Fatal error: Uncaught exception 'Exception' with message 'The argument is not initialized or iterable()' in phalcon/config.zep on line 62'

'Exception: The argument is not initialized or iterable() in phalcon/config.zep on line 62'

**Comment by andresgutierrez** [comment]
It looks like the Phalcon\Config constructor is not receiving an array as it expects.

**Comment by andresgutierrez** [comment]
@lantian

**Comment by lantian** [comment]
@idlleF 0.4.1 doesn't support phalcon after 1.3.4 version. So errors are possible, this issue can be closed.
