### ISSUE TITLE
2.0.6 - Bug on getActiveMethod in dispatcher

### ISSUE THREAD

**Issue by FirePro** [phalcon/cphalcon#10755]
Hello!

I having actions in controllers like "helloMyWorldAction", and using annotations to route. If i try to  $dispatcher->getActiveMethod() i get string like "hellomyworldAction"

Lost the original formatting of the text, it converted to lowercase.

This bug was corrected in Phalcon 1.3 *, but again returned to the Phalcon 2.0

**Comment by FirePro** [comment]
A bug in version 1.3 are discussed here https://github.com/phalcon/cphalcon/issues/2313

**Comment by andresgutierrez** [comment]
Views are looked up in lowercase, returning helloMyWorldAction makes it look for a view called helloMyWorld.phtml instead of hellomyworld.phtml

**Comment by FirePro** [comment]
What decision should be to get existing Annotations on active method without extra code?

Before update to 2.0, this 

<code>
$annotations = $this->annotations->getMethod(
            $this->dispatcher->getControllerClass(),
           $this->dispatcher->getActiveMethod()
 );
</code>

After update to 2.0.6, It took me to write a function:

<code>
$activeMethod = $this->dispatcher->getActionName()."action";
$methods = $this->annotations->getMethods($this->dispatcher->getControllerClass());

foreach ($methods as $key => $value) {
       if (strtolower($key)==$activeMethod) {
                $activeMethod = $key;
       }
}
$annotations = $this->annotations->getMethod(
            $this->dispatcher->getControllerClass(),
            $activeMethod
);
</code>

**Comment by andresgutierrez** [comment]
I think the annotations component must work with case insensitive method names and it does not matter in php

**Comment by FirePro** [comment]
If you send to getMethod lowercase, you don't get any annotations. If you send formatted string, you get all annotations.

**Comment by andresgutierrez** [comment]
Yeah, that's what I'm saying, the annotations component must return the annotations for the method without having into account the case sensitiveness.

**Comment by FirePro** [comment]
It would be great, if it will work as you said :) But now getMethod is case-sensitive and required the original name of active method.

**Comment by andresgutierrez** [comment]
I've added case insensitiveness to getMethod in the 2.0.x branch
