### ISSUE TITLE
IndexController::IndexAction() run twice

### ISSUE THREAD

**Issue by SergeyBran** [phalcon/cphalcon#10761]
When I calling method IndexController::IndexAction() this method run twice. Also discovered when call some other method in other controller, IndexController::IndexAction() is run as additional.
You can check it pretty easy by tried to write something to a file or send an email in this method. The result will be a double. 
Probably #2279 issue is related with this. I also found this problem when trying to generate CSRF token in the controller.
I tested on versions 2.0.5 and 2.0.6

**Comment by andresgutierrez** [comment]
Could you please post a script that allow us to reproduce the issue?

**Comment by SergeyBran** [comment]
https://github.com/phalcon/tutorial
class IndexController extends Controller
{
	public function indexAction()
	{
		file_put_contents("../public/files/test.txt", '$', FILE_APPEND);
	}
}

"$" will be written twice

**Comment by andresgutierrez** [comment]
I executed it and only one $ is written to the file

**Comment by andresgutierrez** [comment]
I think your browser is prefetching a static resource that is missing causing index/index being executed twice. Also it could be that you don't have a favicon.ico causing the same.

**Comment by SergeyBran** [comment]
Exactly. Chrom is trying to get favicon.ico. Thank you so much!
