### ISSUE TITLE
Unable to create condition with a related model

### ISSUE THREAD

**Issue by thxer92** [phalcon/cphalcon#10767]
Hi,

I have two models: Page and PageLocalized

PageLocalized has a belongsTo relation:
``` php
$this->belongsTo("page_id",'TestProject\Models\Page', "id",[
    'alias' => 'page',
    'foreignKey' => [
        'action' => Relation::ACTION_RESTRICT
    ]
]);
```

when i try this:
``` php
$pageLocalized = PageLocalized::findFirst([
    "slug = :slug: AND Page.site_id = :site_id:",
    "bind" => [
        "slug" => $slug,
        "site_id" => $this->site->getId()
    ]
]);
```
i gave an exception:
 'Unknown model or alias 'Page'
when i try with full namespace i gave the same exception, but with namespace

I created a query:
``` php
$pageLocalized = PageLocalized::query()
    ->columns("*")
    ->leftJoin("TestProject\Models\Page")
    ->conditions("TestProject\Models\Page.site_id = :site_id: AND slug = :slug: AND TestProject\Models\Page.soft_deleted = 0")
    ->bind([
        "slug" => $slug,
        "site_id" => $this->site->getId()
    ])
    ->execute();
```
I gave multiple notice:
Undefined index: balias in ...
Warning: Phalcon\Mvc\Model\Resultset\Complex::current(): Property should be string in ...
and i gave an empty resultset

PHP 5.6
Phalcon 2.0.6

**Comment by andresgutierrez** [comment]
This is already fixed in the 2.0.x branch
