### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by CKKing** [phalcon/cphalcon#10769]
When I type sudo ./install,the error happen,so this:
/bin/sh /home/cike/cphalcon/build/64bits/libtool --mode=compile gcc  -I. -I/home/cike/cphalcon/build/64bits -DPHP_ATOM_INC -I/home/cike/cphalcon/build/64bits/include -I/home/cike/cphalcon/build/64bits/main -I/home/cike/cphalcon/build/64bits -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DPHALCON_RELEASE -DHAVE_CONFIG_H  -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden   -c /home/cike/cphalcon/build/64bits/phalcon.zep.c -o phalcon.lo
libtool: compile:  gcc -I. -I/home/cike/cphalcon/build/64bits -DPHP_ATOM_INC -I/home/cike/cphalcon/build/64bits/include -I/home/cike/cphalcon/build/64bits/main -I/home/cike/cphalcon/build/64bits -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden -c /home/cike/cphalcon/build/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
/home/cike/cphalcon/build/64bits/phalcon.zep.c: 在函数‘zephir_fetch_static_property_ce’中:
/home/cike/cphalcon/build/64bits/phalcon.zep.c:6961: 警告：传递‘zend_read_static_property’的第 2 个实参时丢弃了指针目标类型的限定
/usr/include/php/Zend/zend_API.h:321: 附注：需要类型‘char *’，但实参的类型为‘const char *’
/home/cike/cphalcon/build/64bits/phalcon.zep.c: 在函数‘zephir_update_static_property_ex’中:
/home/cike/cphalcon/build/64bits/phalcon.zep.c:7071: 警告：传递‘zend_std_get_static_property’的第 2 个实参时丢弃了指针目标类型的限定
/usr/include/php/Zend/zend_object_handlers.h:147: 附注：需要类型‘char *’，但实参的类型为‘const char *’
/home/cike/cphalcon/build/64bits/phalcon.zep.c: 在函数‘zephir_require_ret’中:
/home/cike/cphalcon/build/64bits/phalcon.zep.c:12632: 警告：赋值丢弃了指针目标类型的限定
/home/cike/cphalcon/build/64bits/phalcon.zep.c: 在文件层：
/home/cike/cphalcon/build/64bits/p

**Comment by andresgutierrez** [comment]
PHP 5.3.3 is not supported anymore, you have to use 5.3.21 at least.
