### ISSUE TITLE
[2.0.4+] Binding arrays in PHQL seems impossible to do?

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#10764]
https://forum.phalconphp.com/discussion/7971/binding-arrays-204+-in-phql

Ok so its a new feature thats not yet documented and that is fine but I just can't figure out how to use it or if its in fact working correctly at this moment.  So as of this moment this issue is somewhere between a forum comment and a github issue.

**Comment by dschissler** [comment]
@andresgutierrez Can you confirm that something like `:PARAM0:` or `{PARAM0:array}` is the correct path to take?

So I'm already binding the hell out of scalars and everything is great and lovely.  For arrays my idea is that I pass an array as `'PARAM0' => [1,2,3]` and then use those values like `field IN :PARAM:` or `field IN {PARAM0:array}`.

Am I correct in this basic approach or is my syntax simply wrong?  Please a quick yes/no on if the syntax is in fact correct.

Maybe having the number character in the parameter name is causing an issue?

**Comment by andresgutierrez** [comment]
Example:

```php
<?php

namespace Some;

use Phalcon\DI;
use Phalcon\Mvc\Model;
use Phalcon\Events\Manager as EventsManager;
use Phalcon\Db\Adapter\Pdo\MySQL as Connection;
use Phalcon\Mvc\Model\Manager as ModelsManager;
use Phalcon\Mvc\Model\Metadata\Memory as ModelsMetaData;

$eventsManager = new EventsManager();

$di = new DI();

$connection = new Connection(array(
    "host"          => "localhost",
    "username"      => "root",
    "password"      => "secret",
    "dbname"        => "phalcon_test",
));

$connection->setEventsManager($eventsManager);

$eventsManager->attach(
    'db',
    function ($event, $connection) {
        switch ($event->getType()) {
            case 'afterQuery':
                break;
            case 'beforeQuery':
                echo $connection->getSqlStatement(), "\n";
                print_r($connection->getSqlVariables());
                break;
            default:
                echo $event->getType(), PHP_EOL;
        }
    }
);

$modelsManager = new ModelsManager();
$modelsManager->setDi($di);
$di['db'] = $connection;
$di['modelsManager'] = $modelsManager;
$di['modelsMetadata'] = new ModelsMetadata();

class Robots extends Model
{
}

$phql = "SELECT * FROM Some\\Robots WHERE id IN ({PARAM0:array})";
$robots = $modelsManager->executeQuery($phql, [
    'PARAM0' => [1, 2, 3]
]);

foreach ($robots as $robot) {
    echo $robot->id, PHP_EOL;
}
```

Outputs:

```sql
SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = 'robots' AND `TABLE_SCHEMA` = DATABASE()
DESCRIBE `robots`
SELECT `robots`.`id`, `robots`.`name`, `robots`.`type`, `robots`.`year` FROM `robots` WHERE `robots`.`id` IN (:PARAM00, :PARAM01, :PARAM02)
Array
(
    [PARAM0] => Array
        (
            [0] => 1
            [1] => 2
            [2] => 3
        )

)
1
2
3
```

**Comment by dschissler** [comment]
Great Andres.  Thanks.  I was simply not wrapping it in a parenthesis.  I thought that I had but it must have been with another combination.  Such is the issue with brute forcing it.

Now just an initial thought I'm thinking that in an ideal world the Adapter/Query parser stuff would know to supply the wrapping parenthesis in a similar manner to how one should bind wildcard searches as `%val%` instead of using the `%` in the SQL itself.  Now PDO doesn't allow bound arrays so perhaps there are issues there making it be the way that it is now as I'm not aware of the full implications of both approaches.

Again thanks for the quick reply so that I don't have to throw away my experiment.  Between PHQL binding arrays and being able to used a named parameter multiple times (really the big win feature for me) I'm finding that the layer that I've created on top of PHQL is becoming very thin indeed.

Closed!

**Comment by jeftom** [comment]
{PARAM0:array}, forget the ()

**Comment by Ecksters** [comment]
Not sure if the syntax was updated in newer versions, but this doesn't appear to be working in Phalcon 3.2 with MySQL, getting the error: `Bind value is required for array type placeholder: regions`, however, I _am_ already binding it.

It works if I just use `implode` and insert the string of the array directly into the query, but obviously I'd like to use bound parameters
