### ISSUE TITLE
Cookies has/get

### ISSUE THREAD

**Issue by Dmitry-Kucher** [phalcon/cphalcon#10772]
Unpredictable behaviour in cookies module. Reason - implicit set in get function
https://github.com/phalcon/cphalcon/blob/c705e115264fbe42d44bb3f1fbf7aebd3e2498bb/phalcon/http/response/cookies.zep#L155

Example:
```php
    public function testAction() {
        var_dump($this->cookies->has('testcookie'));
        $this->cookies->get('testcookie');
        var_dump($this->cookies->has('testcookie'));
        exit;
    }
```
Output:
```php
boolean false
boolean true
```
Possible solutions:
If I understand algorithm the reason for this issue is attempting to incapsulate superglobal $_COOKIE with local _cookies.
Use something like constructor to move superglobal array to loca _cookies and check at has() function only local variable.
https://github.com/phalcon/cphalcon/blob/c705e115264fbe42d44bb3f1fbf7aebd3e2498bb/phalcon/http/response/cookies.zep#L193

Thank you for your attention

**Comment by andresgutierrez** [comment]
I think both has/get must initialize the cookie so the cookies get initialized in both cases

**Comment by Dmitry-Kucher** [comment]
not actual. https://github.com/phalcon/cphalcon/blob/master/phalcon/http/response/cookies.zep#L149
