### ISSUE TITLE
[2.0.6] Bug: can't save hasMany relation with lowercase alias

### ISSUE THREAD

**Issue by galki** [phalcon/cphalcon#10779]
```php
// this doesn't save (documentation teaches this way)
$album->songs = $songs;
$album->save();

// this does save
$album->Songs = $songs;
$album->save();

// this does save if the relation is hasOne
$album->songs = $song;
$album->save();
```

The strange thing is I COULD save with lowercase aliases up to and including this version, but not this particular time. No errors were returned and debugging came up with nothing, but [Nate's comment](https://forum.phalconphp.com/discussion/793/model-not-saving-related-records) suggested capitalizing the alias names and it worked.

**Comment by tobasar** [comment]
@galki 
I confirmed this bug. Using capitalizing the alias name make it worked.

It must be a bug in **belongsTo** function.

**Comment by tobasar** [comment]
Something weird also happens:

If I start the alias with "m" letter, it won't work. But if I change alias to start with "g" letter it works!

```php
// this doesn't save
$album->market = $market;
$album->save();

// this does save
$album->garket = $market;
$album->save();
```

**Comment by tobasar** [comment]
Maybe some new bugs are introduced after commit c1f80f573a2512b5aebe4278007d6e5057b95943 **Allowing to use an alias to eager load data** is pushed at 6 Aug?

**Comment by malletjo** [comment]
fyi: have the same issue in 2.0.10 too ( at least for the belongsto ) and the uppercase worked

**Comment by sergeyklay** [comment]
@tobasar @malletjo @galki Could someone provide script to reproduce?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
