### ISSUE TITLE
[NFR] Phalcon\Secure\Random with cryptographically secure algorithms

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#10776]
Hello.

I suggest to move the functionality of `Phalcon\Text::random` in a separate class (e.g. `SecureRandom`).

I believe that the method `Phalcon\Text::random` is not well implemented. The method may use other ways to randomize. For example:
- [x] Use `openssl`
- [x] Use `libsodium`
- [ ] <s>Way with uppercase characters and numbers that cannot be confused</s> _(Need implement into Text class.)_
- [x] Way with `base64`
- [x] Way with URL-safe `base64`
- [x] UUID-based way
* etc.

But if we amend this method it will become overloaded, it is difficult to be tested and badly readable.  Furthermore, I believe that the purpose of the `random` method is weakly associated in meaning with the `Phalcon\Text` class name.

We could look toward [Ruby][1]. There is nothing bad. Symfony2 is largely borrows ideas from R&R.

We could even have `Phalcon\Secure\Random` class name. In order to reserve the `Phalcon\Secure` namespace (for example `Phalcon\Secure\Crypt`, `Phalcon\Secure\Acl`, etc)

For example we can implement:

- [x]  `Phalcon\Secure\Random::bytes`
- [x]  `Phalcon\Secure\Random::hex`
- [x]  `Phalcon\Secure\Random::base64`
- [x]  `Phalcon\Secure\Random::base64Safe`
- [ ] <s>`Phalcon\Secure\Random::alpha`</s> _(Leave into Text class.)_
- [ ] <s>`Phalcon\Secure\Random::alnum`</s> _(Leave into Text class.)_ 
- [x] `Phalcon\Secure\Random::number`
- [x] `Phalcon\Secure\Random::uuid`
* etc.

[1]: http://ruby-doc.org/stdlib-2.2.2/libdoc/securerandom/rdoc/SecureRandom.html

**Comment by sergeyklay** [comment]
I'll do this. @andresgutierrez assign please to me

**Comment by andresgutierrez** [comment]
it can be Phalcon\Security\Random, as we're already using this namespace. Also, I think you can use libsodium for that.

**Comment by virgofx** [comment]
2 Thoughts

* If you could include the UUID functionality as provided by [ramsey/uuid](https://github.com/ramsey/uuid) natively --- That would be great.

* In regards to UUIDs and other commonly generated values - If you do include this; could you incorporate it into the Models and Metadata.  (This is something I've done for my applications extending the current Phalcon application). Specifically, add another native value in the MetaData to hold **GeneratedValue** columns.  This data would be set directly and via annotations. We are using the similar Doctrine mapping for this as follows below. In general, you could release with only supporting the uuid strategy and add more as necessary later. 

```php
    /**
     * @Primary
     * @GeneratedValue(strategy='uuid')
     * @Column(name='id', type='string', nullable=false)
     */
    protected $id;
```

**Comment by sergeyklay** [comment]
@virgofx 
* I suggest include the UUID functionality into `UuidTools` or something like that. Because `Phalcon\Secure\Random` should provide methods with cryptographically secure algorithms. In my humble opinion `Phalcon\Secure\Random` shouldn't generating UUID.
* 2 proposal need separate to new issue

**Comment by sergeyklay** [comment]
@andresgutierrez ?

**Comment by sergeyklay** [comment]
@virgofx

Ruby's SecureRandom v2.2.2 [contains][1] `SecureRandom.uuid` which generates a v4 random UUID. The version 4 UUID is purely random (except the version). It doesn’t contain meaningful information such as MAC address, time, etc.

However if you propose to implement full functionality as provided by [ramsey/uuid][2] IMHO we need separated class.

[1]: http://ruby-doc.org/stdlib-2.2.2/libdoc/securerandom/rdoc/SecureRandom.html#method-c-uuid
[2]: https://github.com/ramsey/uuid

**Comment by virgofx** [comment]
Fair enough. The namespace should be outside of SecureRandom as you've noted. Makes more sense. My only thought would be to consider the importance of having this linked as a generated value (along with other potential common database generated values).

**Comment by sergeyklay** [comment]
@virgofx I've implemented `Phalcon\Secure\Random::uuid` for v4 random UUID.

See https://github.com/phalcon/cphalcon/pull/10804
