### ISSUE TITLE
Model limit with offset doesn't work

### ISSUE THREAD

**Issue by ilgityildirim** [phalcon/cphalcon#10783]
It seems there is a problem with 2.0.5 when you want to use limit with offset on a model.

Consider this;
    ````Posts::find([
        "limit" => [
             "number" => 10,
             "limit"       => 0
         ]
    ]);````

You'd expect to get 10 records but it grabs all the records from the related table. However if I do this ````Posts::find(["limit" => 10]);```` I get expected 10 results.

I'm using **Ubuntu 14.04 LTS**

**Comment by andresgutierrez** [comment]
This is already fixed in the 2.0.x branch

**Comment by ilgityildirim** [comment]
@andresgutierrez I'm using 2.0.5 and I just noticed this problem. May I ask when the fixed version will be available as this effects the application.

**Comment by andresgutierrez** [comment]
You can install from the 2.0.x branch or it will be released in one week or so.

**Comment by ilgityildirim** [comment]
@andresgutierrez thanks
