### ISSUE TITLE
filter in Assets addJs not working

### ISSUE THREAD

**Issue by xicond** [phalcon/cphalcon#10781]
I imagine that this filter would gave me an exceptional filtered action, but all js that added still filtered using JsMin

    $collection = $this->assets->collection($key)->setTargetPath('js/final.js')->setTargetUri('js/min/final.js')
                ->setSourcePath('/assets/js/')->setTargetPath('/js/min/')
                ->setPrefix('js/min/')
                ->addFilter(new \Phalcon\Assets\Filters\Jsmin);

    //function addJs(string! path, var local = null, boolean filter = false, attributes = null)
    $collection->addJs($js,true,false);

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
