### ISSUE TITLE
ERROR: Model name Group

### ISSUE THREAD

**Issue by xerron** [phalcon/cphalcon#10785]
Not work model called Group.

class Group extends \Phalcon\Mvc\Model
{
...
}

$phql = "SELECT * FROM Group";
$groups = $app->modelsManager->executeQuery($phql);

Syntax error, unexpected token GROUP, near to '   ', when parsing: SELECT id, type, name, description, price, created_at, updates_at FROM Group    (79)

How I can make it work ?

**Comment by andresgutierrez** [comment]
```php
$phql = "SELECT * FROM [Group]";
```

https://docs.phalconphp.com/en/latest/reference/phql.html#escaping-reserved-words

**Comment by xerron** [comment]
work fine!!
thank you!!! @andresgutierrez. +1
