### ISSUE TITLE
多模块(Multi Module Applications)中，是否可以一个模块是命令行（cli）应用？

### ISSUE THREAD

**Issue by gufei** [phalcon/cphalcon#10787]
如题，如何做才能在多模块Multi Module Applications上有一个命令行应用（cli）?

**Comment by sergeyklay** [comment]
https://forum.phalconphp.com/discussion/7283/multiple-module-cli

You can ask questions like this in the forum. Github is only intended to report bugs or discuss new features. https://forum.phalconphp.com/
