### ISSUE TITLE
Controller放在命名空间时，Dispatcher::forward在linux下报Controller handler class cannot be loaded错误

### ISSUE THREAD

**Issue by sprufu** [phalcon/cphalcon#10780]
遇错代码如下：
```php
    namespace gw\mvc\controllers;

   // ....

    public function someAction() {
        // ....
        $this->dispatcher->forward([
            'controller' => 'documentList',
            'action' => 'registered'
        ]);
    }
```
在window下运行正常，放到linux下就报`PhalconException: gw\mvc\controllers\DocumentlistController handler class cannot be loaded`  

php环境：Apache/2.4.10 (Unix) OpenSSL/1.0.1j PHP/5.6.3 mod_perl/2.0.8-dev Perl/v5.16.3
phalcon版本：2.0.6
linux版本是：Red Hat Enterprise Linux Server release 6.3

**Comment by andresgutierrez** [comment]
You can ask questions like this in the forum. Github is only intended to report bugs or discuss new features. https://forum.phalconphp.com/
