### ISSUE TITLE
Model assign function in MongoDB collection

### ISSUE THREAD

**Issue by iwalkalone69** [phalcon/cphalcon#10793]
The support to assign to collection class by array like in models. I've made a collection base with that and works:

    public function assign(array $data)
    {
        foreach ($data as $property => $value) {
            if (property_exists(get_class($this), $property)) {
                $this->$property = $value;
            }
        }
    }

But probably you can adapt and improve it.

Thanks.

**Comment by andresgutierrez** [comment]
What if the property is not defined?

**Comment by iwalkalone69** [comment]
I see two options: ignore it or throw an Excpetion. I think the best would be ignore it.

**Comment by andresgutierrez** [comment]
if you have a model defined as follows?

```php
class Robots extends \Phalcon\Mvc\Collection
{

}
```

Assign wouldn't do anything

**Comment by iwalkalone69** [comment]
Yes, that's true. But I think that best practice is to declare the properties. At least I always define them.

**Comment by andresgutierrez** [comment]
Sure, but as that being an optional practice, the implementation would depend on "optional" practices that seems to be a bad idea

**Comment by iwalkalone69** [comment]
And why it is optional? There is a reason for that?

**Comment by andresgutierrez** [comment]
Because PHP does not force you to declare the properties of each class.

**Comment by iwalkalone69** [comment]
I know that, unless you use the strict mode. What I meant is that using a framework like Phalcon, that tries to help following best practices and have the code ordered and easy to understand, why to keep it optional?

**Comment by andresgutierrez** [comment]
This strict mode?

```php
<?php

error_reporting(E_ALL | E_STRICT);

use Phalcon\Mvc\Collection;

class Robots
{
}

$robot = new Robots;
$robot->hello = "hello"; // no exception or error or warning or notice

print_r($robot);
```

**Comment by iwalkalone69** [comment]
Sorry. You're right.

**Comment by challet** [comment]
Could I add that even for optional properties, an _assign_ function would nice to have : 

`public function assign(array $data)
{
    foreach ($data as $property => $value) {
            $this->$property = $value;
        }
    }
}`
