### ISSUE TITLE
NFR: self property for loop context

### ISSUE THREAD

**Issue by lajosbencz** [phalcon/cphalcon#10798]
Passing the loop context to a macro or partial as an argument is impossible, because the compiler needs a property accessor to evaluate it to the temporary class.

Please add a property `self` to the generated temporary class which returns the instance itself, so passing the loop context as an argument is possible.

Syntax, Example:

``` php
// view.volt
{% for i in 1..10 %}
   {{ partial('some_tpl',{'loop':loop.self}) }}
{% endfor %}
```

``` php
// partials/some_tpl.volt
{% if loop.first %}
<p>First!</p>
{% else if loop.last %}
<p>Last!</p>
{% else %}
<p>{{ loop.index }}</p>
{% endif %}
```

**Comment by sergeyklay** [comment]
@lajosbencz Can you please provide a small test?

**Comment by lajosbencz** [comment]
Sure, in what context? :) Like, add a unit test? Could you point me to an example that someone has already done with an NFR?

**Comment by lajosbencz** [comment]
Sorry about the ```eval```, couldn't think of a simpler way to check the real output... and the input for it is controlled.

**Comment by lajosbencz** [comment]
Let me know if something's off the requirements! :]

**Comment by sergeyklay** [comment]
@andresgutierrez
