### ISSUE TITLE
Phalcon\Mvc\Collection::_getResultset - returns ...\Document when fields are specified

### ISSUE THREAD

**Issue by AxeeL** [phalcon/cphalcon#10791]
Hi!

I have just worked on my project and after a change I got some errors, after debugging I found out it's caused by this line:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/collection.zep#L401

When I'm specifying  'fields' key in parameters a Phalcon\Mvc\Collection\Document is returned instead of the model I'm using, and by this I can't use my getters and this leads to a problem, if I'm specifying the 'fields' in a working and completed code after a while, I have to change my code (by removing my getters) and implement my getters logic if it's needed.

So, my point, is it needed to work like that? Returning a  Phalcon\Mvc\Collection\Document?

Thanks!

**Comment by andresgutierrez** [comment]
It returns an incomplete object, due to the specification of 'fields' not every field is returned in the model, so saving by mistake an incomplete object may result in data loss. This is way it returns a Phalcon\Mvc\Collection\Document to avoid save the object and lose data.
