### ISSUE TITLE
Phalcon Model Relation Alias Not Caching with CamelCase

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#10800]
When using an alias for a related model (defined either via annotations or directly on the model via `initialize()`)  that is camel cased ... the corresponding `getRelated()` works; however, it does not cache the query on subsequent requests. 

When using a non-camel cased alias, the query is properly cached.

I have tested and confirmed this in my application explicitly on the `hasMany()`.  It probably exists as an issue on the other relations as well.

Pseudo example:

``` php
// Initialize database to log queries for reference  (replace {{VARIABLES}} as necessary)
$this->di->setShared('db', function() {

    $databaseConnection = new \Phalcon\Db\Adapter\Pdo\Mysql([
        'host'     => '{{HOST}}',
        'username' => '{{USERNAME}}',
        'password' => '{{PASSWORD}}',
        'dbname'   => '{{DBNAME}}'
    ]);
    $eventsManager = $this->di->getShared('eventsManager');
    $logger = new \Phalcon\Logger\Adapter\File('{{LOGFILE}}');
    $profiler = new \Phalcon\Db\Profiler();

    $eventsManager->attach('db:beforeQuery', function($event, $connection) use ($logger, $profiler) {
        $profiler->startProfile($connection->getSQLStatement());
    });

    $eventsManager->attach('db:afterQuery', function($event, $connection) use ($logger, $profiler) {
        $profiler->stopProfile();
        $logger->log(\Phalcon\Logger::INFO, $connection->getSQLStatement());
    });
    $databaseConnection->setEventsManager($eventsManager);
}
```

``` php
class Robot extends \Phalcon\Mvc\Model {

    public function initialize() {
        $this->hasMany("id", "RobotsParts", "parts_id", [
            'alias' => 'robotParts'
        ]);
        $this->hasMany("id", "RobotsParts", "parts_id", [
            'alias' => 'robotpartsnocamel'
        ]);
    }

    public function testGetRelated() {
        return $this->robotParts;
    }

    public function testGetRelatedNoCamel() {
        return $this->robotpartsnocamel;
    }
}
```

``` php
for ($i = 0; $i < 10; $i++) {
    /// ...
    $robotModel->testGetRelated();
}
// Database Queries ~ 10  (Not Expected, Expected = 1)

for ($i = 0; $i < 10; $i++) {
    /// ...
    $robotModel->testGetRelatedNoCamel();
}
// Database Queries ~ 1 (As expected)
```

**Comment by virgofx** [comment]
@andresgutierrez Any chance you were able to reproduce this?

**Comment by virgofx** [comment]
@andresgutierrez Any way the camel aliases could get fixed for 2.1 LTS / 2.0.8 ?

**Comment by andresgutierrez** [comment]
Checking it

**Comment by virgofx** [comment]
@andresgutierrez Culprits are setting of the alias to lower in set()/get() of \Phalcon\Mvc\Model.

Why is this being done?

https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model.zep#L4104
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model.zep#L4117
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model.zep#L4117

etc.

**Comment by rudiservo** [comment]
I think I can fix this issue real simple, how should I proceed?
Create a new branch just for the issue?
Pull request on 2.1.x or 2.0.x ?

**Comment by nsossonko** [comment]
fork the repo and create a pull request on 2.1.x
