### ISSUE TITLE
[BuiltWith] PhVer - Phalcon Version Release History

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#10803]
I've submitted tiny app called [PhVer](http://zvoid.net/phver/) (no source code) to BuiltWith @ https://github.com/phalcon/builtwith/pull/83 No screenshot, but you guys can add it if you like. I've also used "background", "favicon" and "logo" from main PhalconPHP website I hope you don't mind =)

Short Explanation:
* DL -- Download ``.tar.gz`` release when available.
* Version -- Phalcon release version (also linked to changelog tag).
* Released -- Phalcon version released (YYYY-MM-DD)
* Difference -- Between previous phalcon version and current.
* Days Past -- Days past from Phalcon release version date.

It's not automaticly updated (yet), and not all versions are listed only stable versions.

**Comment by sergeyklay** [comment]
:+1:

**Comment by ovr** [comment]
:+1:

**Comment by sergeyklay** [comment]
@tuxy Can you please add PhVer to http://phalcontip.com/ ?

**Comment by tuxy** [comment]
@sergeyklay Some one already did :-)

**Comment by sergeyklay** [comment]
@tuxy We only accept bug reports, new feature requests and pull requests in this repo. PR related to Phalcon. :)
