### ISSUE TITLE
Query Options LIMIT not Working

### ISSUE THREAD

**Issue by zjhzxhz** [phalcon/cphalcon#10817]
As the [documentation](https://docs.phalconphp.com/en/latest/reference/models.html) said:

The available query option `limit` is used for limiting the results of the query to results to certain range. 
For advanced usage: `“limit” => 10 / “limit” => array(“number” => 10, “offset” => 5)`.
However, I found this not working.

Instead, I found this worked:

```
$resultSet  = Product::find(array(
    'limit'     => 10,
    'offset'    => 5,
));
```

Maybe you should update the documentation. :)

**Comment by phalcon** [comment]
Are you using Phalcon 2.0.7?

**Comment by zjhzxhz** [comment]
No. 2.0.6.
Is this the new feature in 2.0.7?

On Fri, Aug 21, 2015 at 9:05 PM, Phalcon <notifications@github.com> wrote:

> Are you using Phalcon 2.0.7?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phalcon/cphalcon/issues/10817#issuecomment-133421019>.
>



-- 

谢浩哲

**Comment by andresgutierrez** [comment]
In 2.0.7:

```php
$robots = Robots::find(array(
    'limit' => array(
        'number'     => 10,
        'offset'    => 5,
    )
));
```

SQL Log:

```sql
SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = 'robots' AND `TABLE_SCHEMA` = DATABASE()
DESCRIBE `robots`
SELECT `robots`.`id`, `robots`.`name`, `robots`.`type`, `robots`.`year`, `robots`.`datetime`, `robots`.`text` FROM `robots` LIMIT :APL0 OFFSET :APL1
Array
(
    [APL0] => 10
    [APL1] => 5
)
Array
(
    [APL0] => 1
    [APL1] => 1
)
```
