### ISSUE TITLE
1.3.4 - 2.0.7 migration problem

### ISSUE THREAD

**Issue by siciarek** [phalcon/cphalcon#10816]
I am trying to migrate the project form phalcon v 1.3.4 to 2.0.7
The error:

Fatal error: Cannot override final method Phalcon\Mvc\Controller::__construct() in /my/path/to/project/app/modules/frontend/controllers/DefaultController.php on line 0

occurs when I try to display a page with invalid route on 2.0.7, while on 1.3.4 version just 404 occurs.

I would appreciate any help.

**Comment by andresgutierrez** [comment]
Phalcon\Mvc\Controller::__construct is a final method that cannot be overriden. You have to use 'onConstruct'  https://docs.phalconphp.com/en/latest/reference/controllers.html#initializing-controllers

**Comment by siciarek** [comment]
You're absolutely right.

But the problem is that I do not overwrite any __construct method especially in mentioned controller, it looks like the following:

<?php

namespace Application\Frontend\Controller;

class DefaultController extends \Phalcon\Mvc\Controller {
    
    /**
     * @Route("/", name="home")
     */
    public function homeAction() {
        $baseUri = sprintf('%s://%s/', $this->request->getScheme(), $this->request->getHttpHost());

        /**
         * @var \Phalcon\Mvc\Url $router
         */
        $router = $this->getDI()->getUrl();
        $router->setBaseUri($baseUri);
        $url = $router->get(['for' => 'user.sign_in']);

        return $this->response->redirect($url);
    }
}

**Comment by yergo** [comment]
It happens because of using `$router->setDefaultController()` before actually setting it with `$router->add()` or `$router->addModuleResource()`. Class was loaded twice. Once we moved everything to the bottom of router declaration with:

     $router->setDefaults(array(
        'module' => 'frontend',
        'controller' => 'Application\Frontend\Controller\Default',
        'action' => 'home'
     ));
    
    $router->notFound(array(
        'module' => 'common',
        'namespace' => 'Application\Common\Controller',
        'controller' => 'error',
        'action' => 'notFound'
    ));

it starts firing `notFoundAction` (404 header set) but does not produce view, rather blankpage..
