### ISSUE TITLE
[BUG][NFR] Phalcon2: Phalcon\Validation\Message is missing $code parameter

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#10819]
Hi,

Before:
https://docs.phalconphp.com/en/master/api/Phalcon_Validation_Message.html

Now:
https://docs.phalconphp.com/en/latest/api/Phalcon_Validation_Message.html

Phalcon 1.3 `Phalcon\Validation\Message` constructor had the fourth argument: `[int $code]`.

Can we have it back in Phalcon 2 along with getter and setter?

Thanks!

P.S. The same goes for `Phalcon\Mvc\Model\Message`.

**Comment by temuri416** [comment]
Hi @andresgutierrez 

Was that omission a bug or a feature?

Cheers!

**Comment by andresgutierrez** [comment]
It looks that no one is using it so it's probably just noticed

**Comment by temuri416** [comment]
Can we have it back, please? I think it's incredibly useful to be able to assign codes to validation error messages.

**Comment by Green-Cat** [comment]
@temuri416 I will implement it later today.
Also 'Phalcon\Mvc\Model\Validation' is deprecated in 2.1 so not much point fixing that one.

**Comment by temuri416** [comment]
Glad to hear about the demise of `Phalcon\Mvc\Model\Validation` :+1: 

Thanks!

**Comment by Green-Cat** [comment]
Done, #10827.

**Comment by temuri416** [comment]
Much appreciated!

**Comment by andresgutierrez** [comment]
Implemented in the 2.0.x branch
