### ISSUE TITLE
Scanner: Unknown opcode 58

### ISSUE THREAD

**Issue by tarikogut** [phalcon/cphalcon#10821]
what is this ?

**Comment by andresgutierrez** [comment]
https://github.com/phalcon/cphalcon/blob/2.0.x/CONTRIBUTING.md#bug-report-checklist

**Comment by andresgutierrez** [comment]
@tarikogut ping

**Comment by MaxCodeX** [comment]
# I also encountered this error. #

### This is code in a action ###
```php
$phql = 'SELECT total_credits - (SELECT SUM(remaining_credits) FROM Frontend\Models\Sites WHERE users_id = :id) FROM Frontend\Models\Users WHERE id = :id';
$available_credits = $this->modelManager->executeQuery($phql, array(
	'id' => $this->user->id
));
```

### And, this is trace ###

Scanner: Unknown opcode 58

#0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 [internal function]: Phalcon\Mvc\Model\Query->execute()
#2 /srv/shareview.libtools.org/apps/frontend/controllers/SitesController.php(128): Phalcon\Mvc\Model\Manager->executeQuery('SELECT total_cr...', Array)
#3 [internal function]: Frontend\Controllers\SitesController->distributionAction()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /srv/shareview.libtools.org/public/index.php(186): Phalcon\Mvc\Application->handle()
#6 {main}

**Comment by tarikogut** [comment]
old code

$phql = 'SELECT total_credits - (SELECT SUM(remaining_credits) FROM
Frontend\Models\Sites WHERE users_id = :id) FROM Frontend\Models\Users
WHERE id = :id';
$available_credits = $this->modelManager->executeQuery($phql, array(
    'id' => $this->user->id
));


new code

$phql = 'SELECT total_credits - (SELECT SUM(remaining_credits) FROM
Frontend\Models\Sites WHERE users_id = :id:) FROM
Frontend\Models\Users WHERE id = :id:';
$available_credits = $this->modelManager->executeQuery($phql, array(
    'id' => $this->user->id
));


change :id to :id:



2015-09-18 11:23 GMT+03:00 Nguyen Tien Manh <notifications@github.com>:

**Comment by diwuwudi123** [comment]
:id

**Comment by strayobject** [comment]
In case someone comes here with the same error, when you are naming your params you need TWO colons not one.
Good: `WHERE id = :id:`
Bad: `WHERE id = :id`
