### ISSUE TITLE
memory run out bug

### ISSUE THREAD

**Issue by playgamelxh** [phalcon/cphalcon#10822]
Bug code:
$id = 1
while(true){
    $obj = $user::findFirst("id={$id}");
    $id++;
}
Very quickly,you will see:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2992 bytes) 

But,I change another method
$id = 1
while(true){
    $obj = $user::findFirst(array(
        'conditions' => "id = :id:",
        'bind' => array('id' => $id);
   ));
    $id++;
}
It do well

**Comment by andresgutierrez** [comment]
This is not a bug, without using bound parameters it creates a new PHQL plan cached in memory.

* https://docs.phalconphp.com/en/latest/reference/phql.html#phql-lifecycle
* https://docs.phalconphp.com/en/latest/reference/models-cache.html#caching-of-phql-planning
