### ISSUE TITLE
criteria class has a bindparam bug

### ISSUE THREAD

**Issue by jword** [phalcon/cphalcon#10833]
$criteria = Robots::query();
$criteria->inWhere('id', array('1', '2', '3'));
$criteria->limit(10, 0);
$data = Robots::find($criteria->getparams());

When using like this, the result is not what we want.
It appears to be the binding parameters have been covered.

**Comment by phalcon** [comment]
Are you using Phalcon 2.0.7?

**Comment by jword** [comment]
No,I'm using Phalcon 2.0.6

**Comment by andresgutierrez** [comment]
In order to report a bug you have to use the latest version released. Could you please use 2.0.7?
