### ISSUE TITLE
[2.0] Routing with parameters: difference between Router and Router\Group (not as in 1.3)

### ISSUE THREAD

**Issue by RickyGit** [phalcon/cphalcon#10842]
Hello,

With Phalcon 1.3.x, Router and Router\Group work same with parameters.
But in 2.0.x, parameter name with Router\Group doesn't work.

Exemple : 

``` php
$router = new \Phalcon\Router;

$router ->add('/modif/{id:[0-9a-z]+}', 'index::index');

class IndexController extends \Phalcon\Mvc\Controller
{
    public function indexAction($id)
    {
        echo $id: // => it works
    }
}
```

same as

``` php
$routerGroup = new \Phalcon\Mvc\Router\Group;

$routerGroup->add('/modif/{id:[0-9a-z]+}', 'index::index');

class IndexController extends \Phalcon\Mvc\Controller
{
    public function indexAction($id)
    {
        echo $id: // => it works
    }
}
```

But, in 2.0.x, Router\Group doesn't have the same behaviour : 

``` php
$router = new \Phalcon\Router;

$router ->add('/modif/{id:[0-9a-z]+}', 'index::index');

class IndexController extends \Phalcon\Mvc\Controller
{
    public function indexAction($id)
    {
        echo $id: // => it works
    }
}
```

not same as

``` php
$routerGroup = new \Phalcon\Mvc\Router\Group;

$routerGroup->add('/modif/{id:[0-9a-z]+}', 'index::index');

class IndexController extends \Phalcon\Mvc\Controller
{
    public function indexAction($id)
    {
        echo $id: // => $id equal to null
    }
}
```

**Comment by RickyGit** [comment]
Hello,

Sorry but I can't find where the problem is.
Someone can help me? A lead?

This issue is blocking my migration from 1.3 to 2. *

Thanks

**Comment by SparoHawk** [comment]
Did you mount the RouteGroup to the Router? Asking because I do not see it in the sample code.

`$router->mount($routerGroup);`

**Comment by RickyGit** [comment]
Hello,

Yes, I have ``$router->mount($routerGroup);``

I have migrated to Phalcon 2.0 using
``$id = $this->request->getQuery('id');``
at the top of my action function

It works but if I can use parameters in action function definition it's better.

**Comment by SparoHawk** [comment]
I'll test it out with the current project I am working on, but I haven't encountered the same issue as you.

Meanwhile, can you provide an example `$id` that is making the route fail?

**Comment by Jurigag** [comment]
It's working for me with router groups. I don't know why id don't work for you. Maybe it's about query params ? Try to set $router->setUriSource(Router::URI_SOURCE_SERVER_REQUEST_URI); ?

**Comment by Jurigag** [comment]
Well no answer so i think this can be closed?
