### ISSUE TITLE
[NFR] \Phalcon\Mvc\Model\Criteria [where].

### ISSUE THREAD

**Issue by fenixphp** [phalcon/cphalcon#10853]
For ease of use, I propose to change the method "where":

```php
/**
 * Add a basic where clause to the query.
 *
 * @param  string|array  $column
 * @param  string  $operator
 * @param  mixed   $value
 * 
 * @return Criteria
 */
public function where($column, $operator = null, $value = null) {}

/**
 * Sets the conditions parameter in the criteria
 *
 * @param string $conditions 
 * @param mixed $bindParams 
 * @param mixed $bindTypes 
 * @return Criteria 
 */
public function whereRaw($conditions, $bindParams = null, $bindTypes = null) {}
```

That allows both static filling:
```php
$query = \App\Models\Menu\Item::query();
$query->where("menu_id", "=", "1");
$query->where("parent_id", "=", "1");
```

And a simple cyclic processing:
```php
$alias = [
  'eq' => '=',
  'er' => '!=',
  'et' => '<=',
  'qt' => '>='
];

$getData = [
  'where' => [
    [
      'field' => 'menu_id',
      'operator' => 'eq',
      'value' => '1'
    ],
    [
      'field' => 'parent_id',
      'operator' => 'eq',
      'value' => '1'
    ]
  ]
];

$query = \App\Models\Menu\Item::query();

foreach ($getData['where'] as $condition) {
  $query->where($condition['field'], $alias[$condition['operator']], $condition['value']);
}
```

P.S. Need look in the direction of "Query Builders" in such frameworks as the "Laravel", "CI" I think they have the best approach to the "Query Builders".

**Comment by andresgutierrez** [comment]
I don't think this is going to be implemented. It looks very limited.

**Comment by fenixphp** [comment]
What is it limited?

**Comment by andresgutierrez** [comment]
You need many "where" to compose compound conditions, how to use parentheses other logical operators such as "or"?, between? in? not in?

**Comment by fenixphp** [comment]
Is using:
[Laravel](http://laravel.com/docs/5.1/queries)
[Codeigniter](http://www.codeigniter.com/user_guide/database/query_builder.html)
Can not be generate such requests?

This offer is probably to simplify and readability of the final code.

**Comment by andresgutierrez** [comment]
> This offer is probably to simplify and readability of the final code.

By introducing limitations and BC breaks

**Comment by fenixphp** [comment]
No, it's more complete approach to DBAL.
Now I understand why almost all of my friends advised developers not to use Phalcon.

Then how can I override "\ Phalcon \ Mvc \ Model \ Criteria" instance?

**Comment by andresgutierrez** [comment]
```php
use Phalcon\Mvc\Model\Criteria;

class MyCriteria extends Criteria
{
}
```

**Comment by fenixphp** [comment]
This approach will override this class in all models?

**Comment by andresgutierrez** [comment]
No, you have to register it in the DI:

```php
$di->set('Phalcon\Mvc\Model\Criteria', function() {
   return new MyCriteria;
});
```

**Comment by fenixphp** [comment]
Ok thanks.
