### ISSUE TITLE
[NFR] Phalcon\Db\DialectInterface: Create trigger

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#10875]
I created this issue to be referenced later.
- [Postgresql](http://www.postgresql.org/docs/9.1/static/sql-createtrigger.html)
- [SQLite](https://sqlite.org/lang_createtrigger.html)
- [MySQL](https://dev.mysql.com/doc/refman/5.1/en/create-trigger.html)

**Comment by Green-Cat** [comment]
:+1:
