### ISSUE TITLE
Annotations Router for multi Module is not working

### ISSUE THREAD

**Issue by kenjilabs** [phalcon/cphalcon#10873]
annotations  are not working for multi module. when i  use "addModuleResource" it's not using checking class accordingly namespace

on the frontend its giving this error "Class UsersController does not exist"

```php
$di->set('router', function () {
	$router = new \Phalcon\Mvc\Router\Annotations(false);

	$router->setDefaultModule('frontend');
	$router->setDefaultNamespace('Frontrow\Frontend\Controllers');

	// Read the annotations from Backend\Controllers\ProductsController if the URI starts with /api/products
	$router->addModuleResource('frontend', 'Users', '/api/users');

	return $router;
});
```

**Comment by dzubchik** [comment]
@kenjilabs , is it still broken?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
