### ISSUE TITLE
[DOC] Views - template adapter typo

### ISSUE THREAD

**Issue by f3l1x** [phalcon/cphalcon#10879]
Here:
- https://docs.phalconphp.com/en/latest/reference/views.html#creating-your-own-template-engine-adapter

There is:

``` php
public function render($path, $params)
{
    // Access view
    $view    = $this->_view;

    // Access options
    $options = $this->_options;

    // Render the view
    // ...
}
```

But if you use `$this->_options` it triggers **E_USER_NOTICE: Access to undefined property _options**.

Am I doing anything bad? Or is it really mistake.

**Comment by f3l1x** [comment]
@ping

**Comment by sergeyklay** [comment]
This is docs mistake

**Comment by Jurigag** [comment]
So can be closed?
