### ISSUE TITLE
[BUG] Cookie delete, subdomain

### ISSUE THREAD

**Issue by tmihalik** [phalcon/cphalcon#10871]
If I have `test.example.com` and writing cookies to `.example.com`. 

``` php
/**
 * Set the cookie from test.example.com to .example.com
 */
$this->cookies->set('remember-me', 'some value', 0, '/', null, '.example.com');
```

Later I can't delete the cookie:

``` php
/**
 * Get the cookie
 */
$this->cookies->get('remember-me'); // it's ok

/**
 * Delete the cookie
 */
$this->cookies->get('remember-me')->delete(); // does nothing
// or
$this->cookies->delete('remember-me'); // does nothing

```

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch

**Comment by tmihalik** [comment]
I'm still having this issue on Phalcon 2.0.8

**Comment by tmihalik** [comment]
ping @andresgutierrez

**Comment by tmihalik** [comment]
ping @phalcon

**Comment by tmihalik** [comment]
ping @sergeyklay

**Comment by sergeyklay** [comment]
@tmihalik Could you please try to test `2.0.x` branch?

**Comment by tmihalik** [comment]
Both 2.0.x and 2.1.x has this bug.
If create and delete is in the same request it's ok.
To reproduce the bug create a cookie and then try to delete it in another request.

**Comment by tmihalik** [comment]
I don't think this has been fixed.
I'm still having this issue on Phalcon 3.3.2
