### ISSUE TITLE
Can't save relation in model if alias is camelCase

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#10886]
Model Foo has a bidirectional belongsTo/hasMany relationship with model BarBaz. In the relationship on Foo we aliased BarBaz as barBaz. If we try to save the model as follows:

```php
$foo = new Foo();
$barBaz = new BarBaz();
$foo->barBaz = $barBaz;
$foo->create();
```

It screws up $foo (getMessages returns null [not even empty array, null] and the create call returns null). The creation also does not work. However, if the following is done:

```php
$foo = new Foo();
$barBaz = new BarBaz();
$foo->barbaz = $barBaz;
$foo->create();
```

It will work properly. $foo->barBaz will be empty but $foo->barbaz will contain the nested relation and both will have been created.

**Comment by andresgutierrez** [comment]
Are you printing if any message is being created after save the record? 

```php
print_r($foo->getMessages());
```

**Comment by nsossonko** [comment]
As I mentioned initially, getMessages returns null (not even empty array) on $foo.

**Comment by tobasar** [comment]
@andresgutierrez 
Is this case somehow related to #10800 and #10779?

Both of them are issues related to lowercase and camelCase alias.

**Comment by andresgutierrez** [comment]
@tobasar Thanks for pointing it out, taking a look

**Comment by tobasar** [comment]
@andresgutierrez Any progress about this bug? Would love to help testing this bug again if you need.

**Comment by tobasar** [comment]
@andresgutierrez 
I checked to cphalcon/phalcon/db/adapter.zep line 357:

```
let escapedFields[] = this->{"escapeIdentifier"}(field);
```

Maybe this line has a bug camelizing alias?

**Comment by tobasar** [comment]
@andresgutierrez 
I saw in manager.zep line 1100

```
/**
	 * Returns a relation by its alias
	 */
	public function getRelationByAlias(string! modelName, string! alias) -> <Relation> | boolean
	{
		var aliases, relation;
		let aliases = this->_aliases;
		if typeof aliases == "array" {
			if fetch relation, aliases[strtolower(modelName . "$" . alias)] {
				return relation;
			}
		}
		return false;
	}
```
What is the point lowering case the alias? Could it be the hiccup?

**Comment by tobasar** [comment]
Broken strtolower perhaps? I saw no strtolower unit test yet

**Comment by tobasar** [comment]
@nsossonko any update about this bug?

**Comment by nsossonko** [comment]
@tobasar I don't see this issue anymore in my application. Not sure why...
