### ISSUE TITLE
[2.0.7] $model->save() does not save anything, even if it returns true

### ISSUE THREAD

**Issue by ryomo** [phalcon/cphalcon#10888]
When I use PDO options to avoid cast as string like [this](https://forum.phalconphp.com/discussion/872/invalid-data-types-returned-by-phalcon-db#C3370), $model->save() which returns true saves nothing.

### test.php
```php
<?php

use Phalcon\Db\Adapter\Pdo\Mysql as DbAdapter;
use Phalcon\DI\FactoryDefault;
use Phalcon\Mvc\Model;

/**
 * Prepare tests
 */

$dbUser = 'root';
$dbPass = 'pass';
$dbName = 'phalcon_test';

$sql = "CREATE DATABASE IF NOT EXISTS {$dbName} DEFAULT CHARACTER SET utf8;"
."USE {$dbName};"
.'DROP TABLE IF EXISTS user;'
.'CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `isConfirmed` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;';

echo shell_exec("mysql -u{$dbUser} -p{$dbPass} -e '{$sql}'");

$di = new FactoryDefault();
$dbConf = [
    'host'          => 'localhost',
    'username'      => $dbUser,
    'password'      => $dbPass,
    'dbname'        => $dbName,
    'charset'       => 'utf8',
    'options'       => [
        PDO::ATTR_EMULATE_PREPARES => false,
        PDO::ATTR_STRINGIFY_FETCHES => false,
    ]
];
$di->set('db', function () use ($dbConf) {
    $connection = new DbAdapter($dbConf);
    return $connection;
}, true);

/**
 * Start tests
 */

class User extends Model
{
    public $id;
    public $name;
    public $isConfirmed;
}

$user = new User();
$user->assign([
    'name' => 'Octocat',
    'isConfirmed' => 0,
]);
$result = $user->create();
var_dump($result);  // says bool(true)

$user = User::findFirstByName('Octocat');
if ($user) {
    echo 'Found Octocat'.PHP_EOL;
} else {
    echo 'Octocat not found !'.PHP_EOL;
}
```

### run
```sh
$ php test.php
```

#### Phalcon 2.0.0
```
bool(true)
Found Octocat
```
Ok

#### Phalcon 2.0.7
```
bool(true)
Octocat not found !
```
Fail

## Others
These may have some relavance to this issue.
* [#10627](https://github.com/phalcon/cphalcon/issues/10627)
* [Why save()/update() doesn't save and returns no error - Phalcon Forum](https://forum.phalconphp.com/discussion/8023/why-saveupdate-doesnt-save-and-returns-no-error)

**Comment by ryomo** [comment]
Phalcon 2.1.0 BETA 1
```
bool(true)
Octocat not found !
```
Phalcon 2.1.0 fails, too :cry:

**Comment by ryomo** [comment]
Found a workaround.
Use `int(1)` in database, instead of `bit(1)`. :smile: 
*!!`Phalcon\Db\Column::TYPE_BOOLEAN` outputs `bit(1)`!!*

**Comment by Lucups** [comment]
I think you should need  set the default DI:

```
Phalcon\Di::setDefault($di);
```

because of  `find` and `findFirst` use the default DI, of course, if you init the application instance, phalcon will auto set it.

**Comment by andresgutierrez** [comment]
Phalcon\Db\Column::TYPE_BOOLEAN is intended for tinyint(1) columns, bit(1) columns aren't supported.

**Comment by ryomo** [comment]
Thanks Andres !
That was my fault. `TYPE_BOOLEAN` outputs `tinyint(1)` properly.
It was my tool which rewrote the column type from `tinyint(1)` to `bit(1)`.

**Comment by oh-ren** [comment]
> bit(1) columns aren't supported.

?
Phalcon shoulnd't prevent in using bit(1), which is the best type to use for yes/no / on/off type of data AFAIA (in/for MySQL at least).
Anyway bit(1) seems to work, but only in emulated prepares mode...
