### ISSUE TITLE
[Feature] Micro: after handlers

### ISSUE THREAD

**Issue by f3l1x** [phalcon/cphalcon#10890]
Allow change returnedValue in after\* handlers / events.

Same as here:
- https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/micro.zep#L841

Or just add setter **setReturnedValue()**.

Thanks.

**Comment by dreamsxin** [comment]
@f3l1x Can you to add the feature?

**Comment by f3l1x** [comment]
Hi. It's outdated for me, so, I'm closing it. Thank you anyway. :-)
