### ISSUE TITLE
Let people set default validation error messages

### ISSUE THREAD

**Issue by Jojatekok** [phalcon/cphalcon#10892]
https://github.com/phalcon/cphalcon/blob/e0c2afd362583f18b13c547b0128dcabb63fb631/phalcon/mvc/model/validator/stringlength.zep

I would like to set `messageMinimum` and `messageMaximum` to default values which can be localized. I wouldn't like to store the localized string in a variable, nor do I want to create a custom method for validating string length.

**Comment by andresgutierrez** [comment]
Mvc\Model|\Validator is deprecated in Phalcon 2.1. You can set default messages in Phalcon\Validation: 

https://github.com/phalcon/cphalcon/blob/master/phalcon/validation.zep#L234-L266
