### ISSUE TITLE
[NFR] Phalcon\Form\Element\Select::render() should escapeHtml its options content

### ISSUE THREAD

**Issue by TrogloGeek** [phalcon/cphalcon#10897]
As `<option></option>` does not accept markup as content, their content should be HTML escaped IMHO.

**Comment by andresgutierrez** [comment]
Could you please post the code that explains the situation?

**Comment by TrogloGeek** [comment]
Quick exemple from a view:
```
<?php
/* @var $this \Phalcon\Mvc\View\Engine\Php */
$this->tag->setDocType(Phalcon\Tag::XHTML5);

$select = new \Phalcon\Forms\Element\Select('age', ['0-20', '20-40', '> 40']);
echo $select->render();

```
this piece of code ends up being rendered as follow:
```
<select id="age" name="age">
	<option value="0">0-20</option>
	<option value="1">20-40</option>
	<option value="2">> 40</option>
</select>
```
please notice the `>` character not escaped in the last option.

We obviously can html encode options text before passing them to the select constructor, but as HTML only allow simple text as content of `<option>` tag I feel that it really should be encoded/escaped by the `render()` method.
