### ISSUE TITLE
Router Annotations Multi Module support - Module register functions not called

### ISSUE THREAD

**Issue by honerlaw** [phalcon/cphalcon#10891]
The cause of this is that the annotations are trying to be parsed before the class is loaded. Specifically `\Phalcon\Annotations\Reader` is calling `new \ReflectionClass(className);`. However, the autoloader (in the `Module.php` file) containing the location of `className` has not been registered so it can not be loaded.

The issue can be replicated when using router annotations on a multi module project. The module register functions (registerServers and registerAutoloaders) are not called. So if you register the controllers for that module in the registerAutoloaders function then an exception is thrown (`Class Test\Frontend\Controllers\IndexController does not exist`).

So given a controller like so.

```
namespace Test\Frontend\Controllers;

/**
 * @RoutePrefix("/")
 */ 
class IndexController extends \Phalcon\Mvc\Controller
{

    /**
     * @Get("/")
     */
    public function indexAction()
    {

    }

}
```

 and a module definition file like so

```
class Module implements ModuleDefinitionInterface
{
    /**
     * Registers an autoloader related to the module
     *
     * @param DiInterface $di
     */
    public function registerAutoloaders(DiInterface $di = null)
    {

        $loader = new Loader();
        $loader->registerNamespaces(array(
            'Test\Frontend\Controllers' => __DIR__ . '/controllers/',
            'Test\Frontend\Models' => __DIR__ . '/models/',
        ));
        $loader->register();
    }

    /**
     * Registers services related to the module
     *
     * @param DiInterface $di
     */
    public function registerServices(DiInterface $di)
    {
        /**
         * Read configuration
         */
        $config = include APP_PATH . "/apps/frontend/config/config.php";

        /**
         * Setting up the view component
         */
        $di['view'] = function () {
            $view = new View();
            $view->setViewsDir(__DIR__ . '/views/');

            return $view;
        };

        /**
         * Database connection is created based in the parameters defined in the configuration file
         */
        $di['db'] = function () use ($config) {
            return new DbAdapter($config->toArray());
        };
    }
}
```

the following router would work fine and automatically call the register functions in the module definition class based on the url that is requested.

```
/**
 * Registering a router
 */
$di->set('router', function () {
    $router = new \Phalcon\Mvc\Router();
    $router->setDefaultModule('frontend');
    $router->setDefaultNamespace('Test\Frontend\Controllers');
    return $router;
});
```

However, if you define an annotations router instead like so

```
/**
 * Registering a router
 */
$di->set('router', function () {
    $router = new Annotations(false);
    $router->addModuleResource('frontend', 'Test\Frontend\Controllers\Index', '/');
    return $router;
});
```

A Class not found exception will be thrown because the module `frontend` is never loaded (more specifically the registerAutoloaders / registerServices functions are not called).

**Comment by andresgutierrez** [comment]
`new \ReflectionClass(className);` loads the class if it wasn't loaded

**Comment by honerlaw** [comment]
How does it know where to load it from though? Considering the `className` is literally just the class's name and not the location of the class.

I didn't know a better way to describe not loading the class.

**Comment by andresgutierrez** [comment]
Using an autoloader? 

* http://php.net/manual/en/language.oop5.autoload.php
* https://docs.phalconphp.com/en/latest/reference/loader.html

**Comment by honerlaw** [comment]
`include "Test\Frontend\Controllers\IndexController.php"` will not work if the controller is at say `apps/modules/test/frontend/controllers/IndexController.php`. Unless the include is being called from a file that happens to be in `apps/modules` (which it is not).

The autoloaders that are suppose to be loading the class are not called from the module (`registerAutoloaders()`) because the annotations are trying to load the class (before it has been loaded by the autoloaders).

**Comment by andresgutierrez** [comment]
Then you have to register the auto-loaders globally, so they can be available when the class is needed.

* https://github.com/phalcon/biko/blob/master/config/loader.php#L7-L17
* https://github.com/phalcon/biko/blob/master/public/index.php#L22

**Comment by honerlaw** [comment]
I know I can do that and have been doing that. However, doesn't that remove the half of the entire point of having modules? You have to register all of your namespaces globally instead of per module...

**Comment by andresgutierrez** [comment]
Yes, but how the annotations router will be able to read annotations if it cannot access the classes where the annotations are placed?

**Comment by honerlaw** [comment]
The annotations class would need to load and call the module before it tries to parse the annotations?

My idea would be to simply load the module before the annotations are parsed... Then when it comes back to the `handle` function in the application class check to see if the module has been loaded. If not try to load it. If it has then skip it.

But otherwise, I guess the best way for now to handle it would be to simply load the controllers globally and then everything else in the modules themselves.
