### ISSUE TITLE
PUT requests are not being parsed.

### ISSUE THREAD

**Issue by fabiocarneiro** [phalcon/cphalcon#10902]
when I use $request->getPut() it returns me a array with only one value, which is the string content of php://input, and then when I try to retrieve a specific variable it returns null (it will not be able to match the index since there is no index).

Its also not being covered by unit tests.

**Comment by zyxep** [comment]
+1 on this, compared to the old getPut() method in C, is this worse.
you can't even parse a json to it.

**Comment by KorsaR-ZN** [comment]
@fabiocarneiro Which Phalcon version are you using?

**Comment by fabiocarneiro** [comment]
@KorsaR-ZN 2.0.5

The 2.0.7 code seems to be the same. Also the same for master.

**Comment by andresgutierrez** [comment]
Code:

```php
$request = new Phalcon\Http\Request;
print_r($request->getPut());
```

Test:
```php
curl -i -X PUT -d "dadada=1&foofoo=2" http://localhost/a.php
HTTP/1.1 200 OK
Date: Mon, 07 Sep 2015 13:33:33 GMT
Server: Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/1.0.2d DAV/2 PHP/5.6.0
X-Powered-By: PHP/5.6.0
Content-Length: 46
Content-Type: text/html; charset=UTF-8

Array
(
    [dadada] => 1
    [foofoo] => 2
)
```

**Comment by fabiocarneiro** [comment]
@andresgutierrez Yes, that works for me too.

Now try to use form-data or json

**Comment by andresgutierrez** [comment]
Code:

```php
$request = new Phalcon\Http\Request;
print_r($request->getPut("foofoo"));
```

Test:

```bash
$ curl -i -X PUT -d "dadada=1&foofoo=2" http://localhost/a.php
HTTP/1.1 200 OK
Date: Mon, 07 Sep 2015 13:35:10 GMT
Server: Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/1.0.2d DAV/2 PHP/5.6.0
X-Powered-By: PHP/5.6.0
Content-Length: 1
Content-Type: text/html; charset=UTF-8

2
```

**Comment by fabiocarneiro** [comment]
read above

**Comment by andresgutierrez** [comment]
I think you're confused on what this method does. This implements the same behavior as if you send data with POST. If you want to use JSON you have to use:

```php
$request = new Phalcon\Http\Request;
print_r($request->getgetJsonRawBody());
```

**Comment by fabiocarneiro** [comment]
@andresgutierrez I'm not confused. When using the POST method it works because php already parses the request and have the superglobal that you can retrieve data from. However, php does not parse the PUT request to a variable, so its phalcon responsability to provide this.

I'm not using json. I'm giving maintenance to a old project that was written in 1.3.4 and it was working in that version and it itsnt anymore because the getPut code is very different (and its acceptable to be, since this is a major)

I'm using "Content-Type: multipart/form-data" and I was expecting it to return the same parsed string as the get (for POST) do.

**Comment by andresgutierrez** [comment]
But It's doing the same as POST, passing the header in the curl example returns the same data:

```php
$ curl -i -X PUT -d "dadada=1&foofoo=2" -H "Content-Type:multipart/form-data" http://localhost/a.php
HTTP/1.1 200 OK
Date: Mon, 07 Sep 2015 14:00:56 GMT
Server: Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/1.0.2d DAV/2 PHP/5.6.0
X-Powered-By: PHP/5.6.0
Content-Length: 46
Content-Type: text/html; charset=UTF-8

Array
(
    [dadada] => 1
    [foofoo] => 2
)
```

**Comment by fabiocarneiro** [comment]
@andresgutierrez Using the content type header doesnt make it a content type encoded data.

You're setting some header and using the same input format. How can you expect it not to work?

**Comment by fabiocarneiro** [comment]
@andresgutierrez The script is already provided.

```
curl -X PUT -H "Cache-Control: no-cache" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -F "data[_id]=55ed59721020d115008b4571" -F "data[BodyStyle]=Saloon" -F "data[Category]=Something" -F "type=Category" 'http://localhost:8080/mappings/edit'
```

**Comment by andresgutierrez** [comment]
> The script is already provided.

WHERE DID YOU PROVIDED IT? I JUST CHECKED A SECOND AGO AND THERE WAS NOT ANY SCRIPT

**Comment by fabiocarneiro** [comment]
https://github.com/phalcon/cphalcon/issues/10902#issuecomment-138305226

**Comment by andresgutierrez** [comment]
Editing an existing comment

**Comment by fabiocarneiro** [comment]
I didn't

**Comment by andresgutierrez** [comment]
I don't have time for this, maybe any other can help you

**Comment by fabiocarneiro** [comment]
I don't need help. I'm reporting an issue. Feel free to fix or ignore it, its up to you.

**Comment by ricardofiorani** [comment]
It's easy fixable by just removing line from 124 to 129

https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep#L124

**Comment by zyxep** [comment]
dude, he is trying to help you.

he is one of the core devs so behave.
Show him your code so he can help you.

He has proven above that a simple https://github.com/phalcon/cphalcon/issues/10902#issuecomment-138301215 works with printing stuff out.

**Comment by fabiocarneiro** [comment]
@zyxep No. I'm trying to help him. I'm the one creating the issue here. You helped me in irc, and I can see the difference. 

I'm reporting a bug and explained how he should be able to reproduce it by using multipart/form-data, but instead of using the code I provided https://github.com/phalcon/cphalcon/issues/10902#issuecomment-138305226, and that was even before he added the "need script to reproduce" label. He kept sending the same request, and added the content type header, which does not change anything if he doesn't send the params using -F instead of -d, and then he was ignorant here https://github.com/phalcon/cphalcon/issues/10902#issuecomment-138335388, and that doesn't seems to be IMHO how ppl trying to contribute should be answered.

**Comment by lajosbencz** [comment]
@fabiocarneiro this is an open source project, maintained by these guys for free. The contributors are them, and also the helpers. Sure, you may have stumbled upon a valid issue, but there's always the fork button on github and you can fix it and create a pull request... THAT would be contribution :P

**Comment by fabiocarneiro** [comment]
@lajosbencz Issues are also contributions.

**Comment by lajosbencz** [comment]
@fabiocarneiro nah, you're reporting it because you need it for you project, but won't take the effort to try and fix it. Take a look at the number of issues coming in, of which most are irrelevant or false. I'm not saying this one is, but don't surprised if the contributors are mainly skimming the issues. The source is even written in zephir now, not C++. Instead of demanding, you might try to ask. Or make yourself useful and file a pull request with a fix ;]

**Comment by fabiocarneiro** [comment]
@lajosbencz I don't need it. I'm not demanding anything. As I already said before, I'm only reporting it. I was polite, I provided all information requested and this guy wrote in camelcase, kept sending the same thing over and over again without trying to understand what I was saying, and in the end gave the nice "I dont have time for this" excuse.

If they want to ignore it, I don't give a fuck. The issue can be closed and we'll be happy. No need to go any further in this pointless discussion.

**Comment by niden** [comment]
Can we please tone down the drama. Everyone is trying to help everyone else and the project itself. We all work in our own free time for this so be mindful of that. It is not only your time but the audience.

@lajosbencz perhaps all this could have been avoided if you posted something in the lines "see my top post". In long conversations like this it is easy to not find things.

Can you create a failing test and show us exactly what you expect to see? This way we have a test in the suite for future development so that this doesn't come back and it is easier for us to figure out what is going on.

Thanks.

**Comment by fabiocarneiro** [comment]
@niden I already sent it two times. You can scroll up and get it. You basically need to send a curl request using -F instead of -d, but the code is above. I'll not post it again. 

Btw, I got what is going on. It's not a phalcon issue, but PHP. It doesn't parse PUT requests of any enconding (multipart/form-data, x-www-form-urlenconded), so its up to you to decide if phalcon should take care of that or if you will leave that for the developer (`parse_str(file_get_contents("php://input"), $data);`).

Maybe specifying that on the docs is a good idea.

**Comment by niden** [comment]
@fabiocarneiro Happy to see a resolution for this.

As for the docs, you can easily send a PR with your findings in the docs repository :)
