### ISSUE TITLE
why the backend cache redis add the special key(statsKey) _PHCR

### ISSUE THREAD

**Issue by lixiphp** [phalcon/cphalcon#10905]
when the cache is expired, the key still exists in statsKey _PHCR, why design this sepcial key store all the index keys?

**Comment by Green-Cat** [comment]
It exists to be able to flush the Redis cache from phalcon. It is disabled by default in the 2.0.x branch now though.

**Comment by lixiphp** [comment]
@Green-Cat it is a good idea. So flushing cache can realize via PHP code not impacted by KV Redis.
