### ISSUE TITLE
Volt nesteds blocks

### ISSUE THREAD

**Issue by kniaz-tolya** [phalcon/cphalcon#10914]
if the opportunity to implement in volt, it does not support nested blocks?
Forced to use temporary twig

{% extends "layout.volt" %}

{% block content %}
   {% block body %}
            Content Body Text
   {% endblock %}
 Content Text
{% endblock %}

**Comment by lajosbencz** [comment]
Duplicate of #329 

According to the roadmap, it will be implemented in the 2.1 version: https://github.com/phalcon/cphalcon/wiki/Roadmap

**Comment by kniaz-tolya** [comment]
Thanks
