### ISSUE TITLE
Reusable Micro Middleware (before) does not stop operation?

### ISSUE THREAD

**Issue by sszdh** [phalcon/cphalcon#10912]
Hi there,

I have an Access class as a Middleware for my Micro App:

``` php
namespace Api\Middleware;

use Phalcon\Mvc\Micro as PhMicro,
    Phalcon\Mvc\Micro\MiddlewareInterface;

/**
 * Class Access
 * @package Api\Middleware
 */
class Access implements MiddlewareInterface
{
    public function call(PhMicro $application)
    {
        $session  = $application['session'];

        if(!$application->session->has('identity')) {
            $application->response->unAuthorized(); // Response json error blah blah
            return false;
        }
        return true;
    }
}
```

but when it attached to application as follow:

``` php
$application = new \Phalcon\Mvc\Micro();
$application->before(new Api\Middleware\Access());
$application->handle();
```

The operation does not stop and route execute after middleware returns FALSE!

I confused cause using middleware as a closure already works:

``` php
$application = new \Phalcon\Mvc\Micro();
$application->before(function () use($application) {
    if(!$application->session->has('identity')) {
        $application->response->unAuthorized();
        return false;
    }
    return true;
});
$application->handle();
```

Is this a bug or something else?

Thanks.

**Comment by pauliuspetronis** [comment]
I think it's a bug.

By [documentation](https://docs.phalconphp.com/en/latest/reference/micro.html#middleware-events): 

Event Name | Triggered | Can stop operation?
------------ | ------------- | -------------
before | Before executing the handler. It can be used to control the access to the application | *Yes*
after | Executed after the handler is executed. It can be used to prepare the response | *No*
finish | Executed after sending the response. It can be used to perform clean-up | *No*

By [source code](https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/micro.zep#L640-L687), last *if statement* will never be executed.

I created Pull request with fix(in 2.0.x)

**Comment by pauliuspetronis** [comment]
@sszdh, you must call `$application->stop()` before `return false` (in your Middleware class)

**Comment by sszdh** [comment]
@pauliuspetronis, thanks
Yes I think it's a bug!

The '$status' tied with '$_stopped' property and I do not understand that...

**Comment by steambao** [comment]
Yep, can confirm bug. Been waiting for this to be fixed for a while actually :)

**Comment by hinablue** [comment]
Every `handle` called will reset the `this->_stopped` to `false`, so middleware will never stop. If use the `this->_stopped` to check.

https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/micro.zep#L642

**Comment by jasonraimondi** [comment]
It seems like this bug is still around, I am finding it in my Phalcon 3.2 Micro App.

**Comment by Jurigag** [comment]
You need to use `$application->stop()` i think. Even in phalcon 2 there was never check for false/true, only for _stopped.
