### ISSUE TITLE
volt extends bug in Phalcon 2.1.0 beta 1

### ISSUE THREAD

**Issue by kniaz-tolya** [phalcon/cphalcon#10919]
> Project /
>  /app/views/

file **layout.volt**
``` HTML
{% block content %}{% endblock %}
```

file: **index.volt**
``` HTML
{% extends "layout.volt" %}
{%  block content %}
Hello World
{% endblock %}
```
**IndexController.php**
``` PHP
IndexAction(){
  $this->view->pick('index');
}
```

The problem is as follows, after the current version added the ability to:
Phalcon\Mvc\View supports many views directories
there was a problem when you try to inherit an exception, instead of the transmission path to search for the directory array
```
Phalcon\Mvc\View\Engine\Volt\Exception
Template file Arraylayout.volt does not exist
```

**Comment by KorsaR-ZN** [comment]
This fixed in 2.1.x branch

**Comment by kniaz-tolya** [comment]
I build few hours ago it from the 2.1.x branch

**Comment by KorsaR-ZN** [comment]
Please give the script to reproduce the problem.
And also please show how you configure service `view`

**Comment by kniaz-tolya** [comment]
1. 

> \mvc-master\simple-volt\app\config\services.php

```PHP
use Phalcon\Mvc\View as PhView;
use Phalcon\Mvc\View\Engine\Volt as PhVolt;
      .....
        $this->di['volt'] = function ($view, $di) use ($config) {
            $volt  = new PhVolt($view, $di);
            $volt->setOptions(
                [
                    'compiledPath'      => $config->application->cacheDir
                    'compiledExtension' => '.php',
                    'compiledSeparator' => '_',
                    'compileAlways'     => true,
                ]
            );
            $compiler = $volt->getCompiler();
            return $volt;
        };

        $this->di['view'] = function () use ($config, $di) {
            $view = new PhView();
            $view->setViewsDir($config->application->viewsDir);
            $view->registerEngines([
                '.volt' => 'volt'
            ]);
            return $view;
        };
```

2. 

> \mvc-master\simple-volt\app\controllers\IndexController.php
```PHP
     ....
    public function indexAction()
    {
           $this->view->pick('index');
    }
```
3. \mvc-master\simple-volt\app\views\

file: **layout.volt**

```HTML
<body>
       {% block content %}{% endblock %}
</body>
```

file: **index.volt**
```HTML
{% extends "layout.volt" %}
    {% block content %}
        Hello World!
     {% endblock %}
```

**Comment by KorsaR-ZN** [comment]
This bug not reproduced on the latest build `2.1.x` branch.
You reboot php-fmp? :)

[test-app.zip](https://drive.google.com/file/d/0BxDkwGMJ98ueUWdjSlp2Q0dweUk/view?usp=sharing)
Ext. info:
```
Version: 2.1.0b
Build Date: Sep 10 2015 18:41:31
Powered by: Zephir	Version 0.7.1b
```

**Comment by kniaz-tolya** [comment]
php-fpm restarted

version Phalcon 2.1.0 BETA 1

I your example, uploaded. Error

![phalcon](https://cloud.githubusercontent.com/assets/4132867/9795058/27805034-5821-11e5-9339-314813958056.png)

``` bash
git clone https://github.com/phalcon/cphalcon
git checkout 2.1.x
cd build
./install
```

It may be necessary to rebuild?

**Comment by andresgutierrez** [comment]
Compile from ext/:

```bash
git clone https://github.com/phalcon/cphalcon
cd cphalcon/ext
git checkout 2.1.x
./install
```

**Comment by kniaz-tolya** [comment]
Everything works, thank you! issues can be closed.
