### ISSUE TITLE
Phalcon\Image\Adapter\GD resize optional parameters bug

### ISSUE THREAD

**Issue by Surt** [phalcon/cphalcon#10920]
Triying to resize an image with the Phalcon\Image\Adapter\GD and without one of the 2 first parameters fails. https://docs.phalconphp.com/en/master/api/Phalcon_Image_Adapter_GD.html

The docs says

> Resize the image to the given size. Either the width or the height can be omitted and the image will be resized proportionally.

But if I try the code below on 2.0.7 an exception is throw

> width and height must be specified   

```php
 public function testsAction()
    {
        try {
            $image = new Phalcon\Image\Adapter\Gd('absolute_path_on_server');
            $image->resize(null, 800);
            $image->save();
        } catch (\Exception $e) {
            $this->flash->error($e->getMessage());
        }
    }
```

**Comment by pauliuspetronis** [comment]
Try [https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/image/adapter.zep#L112](https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/image/adapter.zep#L112)
```php
 public function testsAction()
    {
        try {
            $image = new Phalcon\Image\Adapter\Gd('absolute_path_on_server');
            $image->resize(null, 800, Phalcon\Image::HEIGHT);
            $image->save();
        } catch (\Exception $e) {
            $this->flash->error($e->getMessage());
        }
    }
```
[Default is Image::AUTO](https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/image/adapter.zep#L85)
