### ISSUE TITLE
Return 404

### ISSUE THREAD

**Issue by yuriygr** [phalcon/cphalcon#10930]
Greetings Community.
I would like to know how to return a 404 error if nothing is found in the controller?
At the moment, I have the following code:
~~~php
class PostController extends ControllerBase
{
***
public function showAction()
{
	// Select data
	$post = Post::findFirst($parameter);
	// Checking availability.
	if (!$post) {
		return $this->dispatcher->forward(array(
			'controller' => 'pages',
			'action' => 'show404'
		));
	}
}
***
}
~~~
Works well, returns 404 page.
But duplicated initialize() in ControllerBase, In which I connect assets. And it turns out that he is connected twice.

How to make so that initialize() twice has not been called?

**Comment by dreamsxin** [comment]
You can overwrite method initialize in PagesController.

**Comment by SidRoberts** [comment]
Could you post your `initialize()` method? It's possible we could move that code to the DI.

**Comment by yuriygr** [comment]
@SidRoberts 
~~~php
public function initialize()
{
	$this->tag->setAutoescape(false);
	$this->tag->setDocType(Phalcon\Tag::HTML5);
	$this->tag->setTitleSeparator(' - ');
	$this->tag->setTitle($this->config->site->title);
	$this->assets
		 ->addCss('css/reset.css')
		 ->addCss('css/style.css');
}
~~~

@dreamsxin
Then other pages will be called without him.

I seem to have found a solution for themselves:
~~~php
$this->response->setStatusCode(404, "Not Found");
$this->tag->prependTitle("Ошибка 404");
return $this->view->pick('pages/show404');
~~~

**Comment by SidRoberts** [comment]
I'd personally put all that stuff in the `initialize()` method into the DI services:

```php
$di->set(
    "tag",
    function () {
        $tag = new \Phalcon\Tag();

        $tag->setAutoescape(false);
        $tag->setDocType(\Phalcon\Tag::HTML5);
        $tag->setTitleSeparator(' - ');
        $tag->setTitle($this->config->site->title);

        return $tag;
    },
    true
);

$di->set(
    "assets",
    function () {
        $assets = new \Phalcon\Assets\Manager();

        $assets
             ->addCss('css/reset.css')
             ->addCss('css/style.css');

        return $assets;
    },
    true
);
```

With this, you'll be able to use `$this->dispatcher->forward()` properly. :)

**Comment by yuriygr** [comment]
@SidRoberts Very good decision.

I think, can be closed issues.
