### ISSUE TITLE
[Feature] Asset management, make resource collection be a Set

### ISSUE THREAD

**Issue by Dimous** [phalcon/cphalcon#10938]
I made widgets, that autoregister their own css/js. When I use multiple instances of a widget, its link/script entries get duplicated.

**Comment by Dimous** [comment]
This snippet reproduces resource registering behaviour of 10 instances of a widget:
for ($nIndex = 0; $nIndex < 10; ++ $nIndex) $this->assets->addCss("style.css")->addJs("script.js");

**Comment by Dimous** [comment]
Oy vey! Feature #10938 is still not merged!

**Comment by sergeyklay** [comment]
It may be part of 3.1.0

**Comment by sergeyklay** [comment]
Implemented in 3.2.x branch.
