### ISSUE TITLE
skipAttributes/skipAttributesOnCreate does not work for Primary keys

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#10932]
Hi,

I am using Mysql and cannot get my primary keys to be skipped during create. In Mysql my primary keys are set to AUTO_INCREMENT. I call model->skipAttributes('id') in initialize, to no avail. If a primary key is set on the model, it will be passed to Mysql and set to that value.

```php
class Samples extends \Phalcon\Mvc\Model {
    /**
     * @Primary
     * @Identity
     * @Column(type="integer", nullable=false, length=16)
     */
    public $id;

    public function initialize() {
        // set model to use dynamic updates
        $this->useDynamicUpdate(true);

        // id columns will always be auto-generated and immutable
        $this->skipAttributes(array('id'));
    }
}

$sample = new Samples();
$sample->id = 5;
$sample->create();
$record = Samples::findFirst(5);
var_dump($record->toArray());
```

```sql
CREATE TABLE `samples` (
    `id` bigint(16) unsigned NOT NULL AUTO_INCREMENT
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by andresgutierrez** [comment]
What version of Phalcon are you using?

**Comment by nsossonko** [comment]
2.0.7

**Comment by andresgutierrez** [comment]
Fields marked with the @Identity are automatically assigned by Phalcon, remove this annotation will do the work for you

**Comment by nsossonko** [comment]
I removed it and still same story. The id is whatever is assigned to it, it is not skipped.

**Comment by sszdh** [comment]
Clear your metadata cache and try again.
May helps...

**Comment by Fuhunter** [comment]
Use `$this->skipAttributesOnCreate(array('id'));` for skipping them, when you want to create a new record. Works fine for me.

**Comment by nsossonko** [comment]
I switched to using getters/setters for what I was doing as it made more sense anyhow. If this is tested and works, you can close this issue.
