### ISSUE TITLE
Column 'YEAR' doesn't belong to any of the selected models (1)

### ISSUE THREAD

**Issue by sverdier** [phalcon/cphalcon#10934]
I have the same bug : https://forum.phalconphp.com/discussion/1829/how-to-fetch-computed-columns-using-the-query-builder-

$user->columns(array('id', 'email', 'firstname', 'lastname', 'TIMESTAMPDIFF( YEAR ,birthday,CURDATE()) AS age'));

Result: Column 'YEAR' doesn't belong to any of the selected models (1)

Standard Mysql date calculation isn't possible with Phalcon => https://dev.mysql.com/doc/refman/5.0/en/date-calculations.html

**Comment by andresgutierrez** [comment]
This is not a bug, custom SQL extensions aren't supported by PHQL, you can use custom dialect functions: https://blog.phalconphp.com/post/phalcon-2-0-3-released
