### ISSUE TITLE
Disable meta-data dumping

### ISSUE THREAD

**Issue by ITCPhantom** [phalcon/cphalcon#10947]
Is it possible to disable meta-data dumping for all models? for one specific model? 
I use Phalcon 2.0.7

**Comment by andresgutierrez** [comment]
Meta-data strategy is only one for all models.

**Comment by ITCPhantom** [comment]
Thanks for quick answer. How can I enable something like Empty/Null strategy to avoid dumping?

**Comment by andresgutierrez** [comment]
By changing the meta-data strategy in the models meta-data manager:

```php
$di->set('modelsMetadata', function() {
      $metaData = new \Phalcon\Mvc\Model\MetaData\Memory();
      $metaData->setStrategy(new MyStrategy());
      return $metaData;
 });
```
