### ISSUE TITLE
Serialization in Phalcon\Mvc\Model\Resultset\Simple for cache

### ISSUE THREAD

**Issue by ramizka** [phalcon/cphalcon#10948]
Phalcon\Mvc\Model\Resultset\Simple uses its own serialize() and unserilalize() for storing data in cache. It's good, but if I prefer using Igbinary as FrontendCache, I would like to use it for serialization. 

So it's would be nice to check Frontend Cache Adapter, to use igbinary for serialization, for example.

**Comment by andresgutierrez** [comment]
Phalcon\Mvc\Model\Resultset\Simple doesn't use their own serialize in the full sense of the word. It just prepares the data for serialization by serialize/igbinary/json_encode, etc.

**Comment by ramizka** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/resultset/simple.zep

return serialize([
			"model"	   : this->_model,
			"cache"	   : this->_cache,
			"rows"		: this->toArray(false),
			"columnMap"   : this->_columnMap,
			"hydrateMode" : this->_hydrateMode
		]);

So it does not prepare. It does its own serialization
