### ISSUE TITLE
A little advice on softdelete behaivor

### ISSUE THREAD

**Issue by jword** [phalcon/cphalcon#10959]
when delete a records  using softdelete behaivor  it also will be validation the data.
but when delete a record i don't want to validate it.
 can we add an validate scheme to solve different validation demand ？

i using in the model like this now:

```
private $valid = 1;
public function initialize()
{
    $this->addBehavior(new SoftDelete(
        array(
            'field' => 'state',
            'value' => parent::DELETED,
        )
    ));
}

public function validation()
{
    if ($this->valid == 1) {
        $this->validate(new Uniqueness(
            array(
                'field'   => array('name', 'uid', 'state'),
                'message' => 'the name has exists',
            )
        ));
    }

    if ($this->validationHasFailed() == true) {
        return false;
    }
}
```

**Comment by dschissler** [comment]
I ported the Phalcon 2 SoftDelete Zephir code into PHP and I extended it and added a Trait (PHP 5.4+) to go along with it.

* [Behavior](https://github.com/perchlayer/webird/blob/master/app/phalcon/common/library/Mvc/Model/Behavior/SoftDelete.php)
* [Trait](https://github.com/perchlayer/webird/blob/master/app/phalcon/common/library/Mvc/Model/Traits/SoftDeleteModelTrait.php)

**Comment by dschissler** [comment]
At some point when Zephir supports Trait then I think that this issue should be addressed.  I tried to take a stab at this but I ended up not using soft deletion in my project and so its unlikely to be refined or 100% functional.
