### ISSUE TITLE
Phalcon doesn't generate routes with Micro 

### ISSUE THREAD

**Issue by karlozz157** [phalcon/cphalcon#10950]
The application is very easy but I don't know where is my error or I don't know if Phalcon has a  bug about this.

I'm using apache, php version 5.5.9-1ubuntu4.11, phalcon version 2.0.7.

The index.php file only has two responses

```
use Phalcon\Mvc\Micro;

$app = new Micro();

$app->get('/', function () {
    echo 'root';
});

$app->get('/welcome', function () {
    echo 'welcome';
});

$app->handle();
```

So when I enter to my app I see "root" like response and that's correct.

```
└ ~$ curl -X GET http://localhost:8080/index.php/
root
```

but I must see "welcome" like response in this route "index.php/welcome" but not and I don't know why.

```
└ ~$ curl -X GET http://localhost:8080/index.php/welcome
root
```

Thanks for your comments!

**Comment by nsossonko** [comment]
The url is expected to be passed via a query parameter, see here for how to write the rewrite rules for this: https://docs.phalconphp.com/en/latest/reference/apache.html#directory-under-the-main-document-root
