### ISSUE TITLE
[NFR] Aliases in Paginator

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#10957]
When building pagination, "Page.before" is absolutely not the term I would use for the page number previous to the current page.  Could we get some aliases for that?  Since it's a stdClass, I figure the overhead is pretty minimal.

Aliases I would use/could see others using:
previous
prev
back

**Comment by williamokano** [comment]
@andresgutierrez It's a bad idea to change the function
```php
public function getPaginate() -> <\stdclass>
```

To something like that?
´´´php
public function getPaginate(var aliases = []) -> <\stdclass>

// ...... lots of code
let page = new \stdClass(),
// ...... more code

for alias, alias_to in aliases {
    let page->{alias} = page->{alias_to};
}

return page;
```

I'm very new to the zephir lang and this looks like a very easy contribution I could make to phalcon.
