### ISSUE TITLE
[BUG] Phalcon 2.0.* - model properties are not retained after findFirst()

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#10958]
Hi,

The code:

``` php
$di = new Phalcon\DI\FactoryDefault;
$di->set('db', function() {
    return new Phalcon\Db\Adapter\Pdo\Mysql(array(
        'host' => '127.0.0.1',
        'username' => 'root',
        'password' => 'password',
        'dbname' => 'mydb',
        'port' => '3306'
    ));
});

class Book extends Phalcon\Mvc\Model
{
    public $prop = 'A';

    public function getSource()
    {
        return 'book';
    }
}
$book = new Book;
$book->prop = 'B' . PHP_EOL;
$book = $book->findFirst(1);
echo $book->prop . PHP_EOL;
```

In Phalcon 1.3.5 code above prints `B`, while in 2.0 it prints `A`.

I am not sure which of the two versions are wrong, but I would certainly prefer 1.3.5 behaviour.

In 1.3.5 I could do this:

``` php
$di = new Phalcon\DI\FactoryDefault;
$di->set('db', function() {
    return new Phalcon\Db\Adapter\Pdo\Mysql(array(
        'host' => '127.0.0.1',
        'username' => 'root',
        'password' => 'password',
        'dbname' => 'mydb',
        'port' => '3306'
    ));
});

class Book extends Phalcon\Mvc\Model
{
    public $doSomething = false;

    public function getSource()
    {
        return 'book';
    }

    public function afterFetch()
    {
        if ($this->doSomething) {
            // Do something here: send email, produce PDF or ping google.
        }
    }
}
$book = new Book;
$book->doSomething = true;
$book = $book->findFirst(1);
```

@phalcon What's your opinion on this? I see it as a major breaking change.

Thanks!

**Comment by temuri416** [comment]
@phalcon 

Could you please comment on this?

If this is a new behaviour and it is now different from v.1.3.5 - I'll have to refactor my models. Kind of important to know the status.

Thanks!

**Comment by dschissler** [comment]
First off when you write `echo $u->prop . PHP_EOL;` I think that it should be `echo $book->prop . PHP_EOL;` because I don't see any `$u` variable.

Next, what is the point of preloading the author model there for a single model?  You could simply define the named relationship and then access it with `$book->getAuthor()` or maybe `$book->getAuthors()[0]`.  If you are doing that for a lot of models then it would probably be more efficient to obtain all of the authors with a single query on the resultset (to prevent the N+1 query common pitfall).

It seems to me that from a purely logically perspective that the 2.0 behavior is correct.  In your first example the first `$book` pointer is overwritten and there is no longer a pointer to that object and you are creating a new object there from `findFirst` so I'm not sure how it would still be around.

To consider, there is a feature in the Resultset that allows the same model to exist only a single time across the entire execution but I'm not sure exactly how that is triggered (by primary key, I guess) and if that would be coming into play in your example.  If there are more complicated things going on then demonstrated in your example then it might be the case.

**Comment by temuri416** [comment]
1. yes, that was a typo.
2. I've updated example, to illustrate that I may want to do *whatever*. Not necessarily to load an author, so there is no "N+1 query common pitfall".

Now look at the problem again.

What I am trying to say is this:

**Having loaded a Model I would OPTIONALLY like to do something else.**

Do you see a problem with that approach?

On another note, the reason this ticket is opened is that there is a discrepancy between 1.3.5 and 2.0 behaviours. And it wasn't mentioned anywhere as breaking change. Thus the ticket.

Unfortunately I could not get any word from developers on the nature of the change.

**Comment by dschissler** [comment]
Here is an idea:

class Book extends Phalcon\Mvc\Model
{
    public $prop = 'A';

    public static function find(array $options = null)
    {
        $doStuff = (isset($options['doStuff']));
        unset($options['doStuff']));

        $Model = __CLASS__;

        $phql = "SELECT * FROM $Model ...";

        $query = new PhQuery($phql, Di::getDefault());
        $query->setBindParams($bindValues);
        $query->setBindTypes($bindTypes);

        $results = $query->execute();
        
        if ($doStuff)) {
            // Do stuff here inline or static method or even call a public method on each model
        }

        return $results;
    }

    public static function findFirst(array $options = null)
    {
        if (!isset($options)) {
            $options = [];
        }
        $options['limit'] = 1;

        $results = self::find($options);
        if ($results->length == 0) {
            return false;
        } else {
            return $results[0];
        }
    }
}

I've had a lot of good times extending the static model methods.  You can do anything with it.

**Comment by dschissler** [comment]
Also as a much easier hack you could change `public $doSomething = false;` to `public static $doSomething = false;`.  Then just toggle off that static variable after you have done something from your `afterFetch` event.

**Comment by temuri416** [comment]
Well, the problem with static is that they persist across instantiations.

What's good for ```$book1 = new Book```; may not be the same for ```$book2```. And then, you're in the ugly mess of setting and unsetting.

**Comment by dschissler** [comment]
You're code is a bit unusual:

```php
$book = new Book;
$book->prop = 'B' . PHP_EOL;
$book = $book->findFirst(1);
```

I would typically do it like this:

```php
$book = Book::findFirstByKey(1);
```

**Comment by ogarbe** [comment]
Problem is : you're using a static method as a non static one (call $book->findfirst instead of Book::findfirst), which should be refused by PHP engine. If i'm not wrong php 5.6 throws a notice in this case.

**Comment by temuri416** [comment]
@ogarbe 

It does not matter what I use - result is the same.

And, Phalcon's model intercept both ```::``` and ```->``` and route calls to static method.

**Comment by dschissler** [comment]
I'd say that you were relying on some undocumented Phalcon 1.3 functionality.  There just isn't a convention for calling static methods off of a object instance like that and so I'd put it in the same category as using undocumented internal functions.  Also, its just ... weird.
