### ISSUE TITLE
Phalcon\Validation\Validator\File not found

### ISSUE THREAD

**Issue by longfeiRen** [phalcon/cphalcon#10951]
A strange question，Phalcon Version 2.0.6 In the same two server environment； ```

php -r "echo Phalcon\Version::get();"

2.0.6

php -v

PHP 5.4.40 (cli) (built: Apr 23 2015 21:23:18) Copyright (c) 1997-2014 The PHP Group Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies 
```
 One of the servers Exception information 
``` Class 'Phalcon\Validation\Validator\File' not found in <b>/app/controllers/AccountController.php</b> on line <b>158</b><br />

**Comment by sergeyklay** [comment]
Provide please `/app/controllers/AccountController.php`

**Comment by Green-Cat** [comment]
It is hard to guess what the actual issue is without seeing your code, but let's get one of the easy oversights. Is your controller in a namespace? If it is then you need to use "\Phalcon\Validation\Validator\File".
