### ISSUE TITLE
[NFR] Parametrized Modules

### ISSUE THREAD

**Issue by stoiev** [phalcon/cphalcon#10967]
It could be great if Phalcon implements at its core a way to pass parameters to [Modules](https://docs.phalconphp.com/en/latest/reference/applications.html#multi-module).

I felt that necessity coding some _pluggable_ modules that pretends to be used on different phalcon environment configuration more independently.

I could not find a proper way to implement it besides registering a _config_ service in DI with specific module entries, but this solution seems to be too _coupled_.

A better alternative could be an optional entry on [registerModules](https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Application.html). For example, changing this:

``` php
$application->registerModules(
        array(
            'frontend' => array(
                'className' => 'Multiple\Frontend\Module',
                'path'      => '../apps/frontend/Module.php'
            )
        )
    );
```

To this:

``` php
$application->registerModules(
        array(
            'frontend' => array(
                'className' => 'Multiple\Frontend\Module',
                'path'      => '../apps/frontend/Module.php',
                'parameters' => new \Phalcon\Config(array(
                     'number_of_entries_per_page' => 10
                ))
            )
        )
    );
```

_parameters_ here could be a simple associative array, a \Phalcon\Config or a ordinary object... all of this are arguable, since there is a way to pass parameters to modules.

The drawback is that _ModuleDefinitionInterface_ needs to be change somehow for _parameters_ passing. 

Another solution could be letting module be registered with an instantiated object. Example:

``` php
$myModule = new MyModule(
    new \Phalcon\Config(array(
        'number_of_entries_per_page' => 10
    ))
);

$application->registerModules(
        array(
            'frontend' => array(
                'module' => $myModule
            )
        )
    );
```

It is not full _lazying load_ stuff, but it gives full flexibility for modules developers on a back compatible way.

Is it posible? Desirable?

**Comment by f3l1x** [comment]
:+1:
