### ISSUE TITLE
number_field documentation mismatch

### ISSUE THREAD

**Issue by pwoszczyk** [phalcon/cphalcon#10969]
When i use volt helper (follow documentation https://docs.phalconphp.com/en/latest/reference/volt.html#using-tag-helpers):
{{ number_field('product_id') }}

I receive error:
Phalcon\Mvc\View\Exception: Macro 'number_field' does not exist

Problem has been described and closed in #2149, but it is not fixed.

**Comment by SidRoberts** [comment]
Turns out it's actually `numeric_field`. I've committed it to the documentation repo so it should be fixed the next time the documentation is regenerated.

**Comment by pwoszczyk** [comment]
Current documentation is correct!
