### ISSUE TITLE
How to get extra columns of inter-media table in Many to Many relationship?

### ISSUE THREAD

**Issue by Wayne-Wen** [phalcon/cphalcon#10965]
Our project have two Models ---- "Booking" and "Passenger". Each Booking have many passengers, and each passenger have many booking. In this case, we using "booking_passenger" as their inter-media table. However, each passenger might have different "request" for different booking. So we have a "request" field in "booking_passenger" table. We are using "hasManyToMany" method to define relationships in "Booking" and "Passenger" model. Therefore, if we have fetched a booking ("$booking"), we can access passengers via "$booking->passengers". When we are using for loop to iterate "$booking->passengers":

```
 foreach($booking->passengers as $passenger){...}
```

Is there any way we can access "request" via $passenger? Like Laravel, you can access using "pivot". 

```
$passenger->pivot->request;
```

I think it is a good way, could Phalcon add this feature?

**Comment by Jurigag** [comment]
Why just not use modelsManager and select joined columns ? you can select easly all booking_passenger which has booking = your booking and leftJoin passenger and you good to go.
