### ISSUE TITLE
Column name containing parentheses causes errors

### ISSUE THREAD

**Issue by SoccerField24x7** [phalcon/cphalcon#10974]
I have a column named:  billtime(rounded) which is legal in MySQL.  How can this be represented in the Phalcon model?

```
/**
 *
 * @var string
 */
public $billtime(rounded);
```

Leaving it as is, causes errors to be thrown.

**Comment by Green-Cat** [comment]
php does not support brackets in variable names.
http://php.net/manual/en/language.variables.basics.php

**Comment by VCJeroen** [comment]
You could try independent column mapping: https://docs.phalconphp.com/en/latest/reference/models.html#independent-column-mapping

    public $billtime_rounded;
    public $etc;

    public function columnMap()
    {
        return array(
            'billtime(rounded)' => 'billtime_rounded',
            'etc' => 'etc',
        );
    }

**Comment by SoccerField24x7** [comment]
Right @Green-Cat, PHP does not support it, which is why it is a bug that the dev tools create it that way, and the reason for my inquiry as to how the Phalcon team expects people to handle it.  Thank you for your work around @VCJeroen! Presumably you have to define every column in the model though.  In this particular case, this table has 30+ columns.  Not impossible to do, but a pain to specify each of them individually.

**Comment by andresgutierrez** [comment]
@SoccerField24x7 please follow the advice of @VCJeroen
