### ISSUE TITLE
[DOC][API] Link to class on Github 

### ISSUE THREAD

**Issue by f3l1x** [phalcon/cphalcon#10971]
I would be nice to have a direct link to the source class from documentation. 

https://docs.phalconphp.com/en/latest/api/Phalcon_Queue_Beanstalk.html
->
https://github.com/phalcon/cphalcon/blob/master/phalcon/queue/beanstalk.zep

**Comment by f3l1x** [comment]
@SidRoberts It's great. We can close it or do you plan more?

**Comment by SidRoberts** [comment]
@f3l1x, close this please. :smile:
