### ISSUE TITLE
beforeValidation not called before internal validation on update

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#10977]
When a model is updated the beforeValidation method is not called **prior** to internal validation. Therefore, if a required field is not filled (or is filled with the wrong type), beforeValidation will never get called and the update fails immediately with the single internal message.

When a model is created, however, beforeValidation is called first.

**Comment by nsossonko** [comment]
Just to clarify, this happens in a very specific scenario:

```php

class Test extends \Phalcon\Mvc\Model {
  /**
   * @Column(type="integer", nullable=false, length=1)
   */
  $allow;

  public function beforeValidation() {
    echo "In beforeValidation";
  }
}

$test = new Test();
$test->allow = 0; // This is the key, the value must be empty (i.e. 0, false, etc).
$test->create();

$test->assign(array('allow' => 'a'));
$test->update(); // beforeValidation not called
```

**Comment by FaimMedia** [comment]
You could refresh the state of the model, by using `$test->refresh();`.
It should trigger again when trying to update.
