### ISSUE TITLE
Log Transactions assign the same timestamp for all Log Items

### ISSUE THREAD

**Issue by vbojan** [phalcon/cphalcon#10989]
If Logger doesn't use transactions everything works fine - each log entry has a timestamp assigned at the moment when Log Item was created.

I would expect the same to happen when transactions are used.
The only difference would be that log would contain entries that would appear to be out of order as with log transactions all log entries belonging to that transactions are grouped together and appended to the log at once. This means log entries would not be in a chronological order which is fine.

However, when Logger uses transactions, all log entries belonging to the transaction have the exact same timestamp which gets assigned to them at the moment when transaction is being committed. This doesn't feel right.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
