### ISSUE TITLE
[NFR] Phalcon\Mvc\Model\Manager->getRelationByAlias()

### ISSUE THREAD

**Issue by NicePebkac** [phalcon/cphalcon#10984]
At present the method `getRelationByAlias($modelName, $alias)` against Phalcon\Mvc\Model\Manager will only return results provided the `$modelName` class has already been initialized (ie. Relationships loaded).

It would be good if there was either
A. getRelationByAlias(...) initialized the model to load the relationships, and then check.
or
B. getRelationByAlias(...) returned something different than False, so there's some distinction between if the Model relationships have _not_ been loaded, vs relationship does not exist.

Code example for the lols:

``` php
$modelsManager = function(){ return \Phalcon\Di::getDefault()->getShared('modelsManager'); };

$modelsManager()->getRelationByAlias('Foo', 'bar');         //Returns False
if(!$modelsManager()->isInitialized('Foo')){
    $modelsManager()->initialize(new Foo());
}
$modelsManager()->getRelationByAlias('Foo', 'bar');         //Returns object as expected
```

AFAIK a fix could potentially be as easy as adding:

``` zep
        if !this->isInitialized(modelName) {
            if !this->initialize(modelName) {
                return null;
            }
        }
```

into getRelationByAlias @ 
https://github.com/phalcon/cphalcon/blob/8dffb2f77ed460398c681ebe24624532798fd178/phalcon/mvc/model/manager.zep#L1101

**Comment by vigilant-hylian** [comment]
+1

**Comment by brendont** [comment]
+1
