### ISSUE TITLE
Possible bug in Phalcon\Mvc\Model\Criteria::notBetweenWhere()

### ISSUE THREAD

**Issue by calinrada** [phalcon/cphalcon#10988]
Please have a look at https://forum.phalconphp.com/discussion/8759/can-not-use-not-between-in-find-and-query-function . I have tested thin on 2.0.7 and I have the same issue.

**Comment by Izopi4a** [comment]
I dont know C, but it seems like parser has to be updated with this case.

Maybe @phalcon can help it

https://github.com/phalcon/cphalcon/blob/master/ext/phalcon/mvc/model/query/base.c#L43
