### ISSUE TITLE
Feature Request - Partial vs Include based on environment

### ISSUE THREAD

**Issue by thepatron** [phalcon/cphalcon#10990]
Hi,

Per this [documentation](https://docs.phalconphp.com/en/latest/reference/volt.html#partial-vs-include), there is better performance for include vs. partial.  It'd be nice to be able to use partial in debug / test environments and include in production without doing something like the following everywhere in the code...

``` volt
{% if devEnv == 'prod' %}
  {% include "partials/footer.volt" %}
{% else %}
  {{ partial("partials/footer") }}
{% endif %}
```

To something like the following which would do the above in one line.  I messed around with trying to add a function to volt to do this, but I couldn't figure out how to reproduce include properly.  

``` volt
{{ envPartial("partials/footer") }} 
```

Thoughts?

Thanks

**Comment by Feloot** [comment]
Interesting ! I would very much like to see such a feature as well. Do we know how much impact using partial has on performances ?
