### ISSUE TITLE
Model not updating if column name contains whitespace

### ISSUE THREAD

**Issue by suhrab** [phalcon/cphalcon#10995]
Phalcon 2.0.7
Php 5.5.9

``` php
$dbPayment = \App\DomainModels\Payment::findFirst($paymentId);
$updateValues = [
    'TransactionToken' => $orderDetail->getCyberSourceTransactionNumber(),
    'ResponseStatus' => $orderDetail->getOrderStatusCode(),
    'BankCardNumber ' => $orderDetail->getBankCardNumber()
];
$saveResult = $dbPayment->save($updateValues);
$errors = $dbPayment->getMessages();
```

BankCardNumber has a trailing white-space. Save does not save this column, $errors is empty
I made some test. Same happens if there is space in the beginning
I think getMessages() should return an error, or use trim() and therefore save() should update the column

**Comment by rianorie** [comment]
@andresgutierrez what is the desired behavior? I think a message is the better solution myself

**Comment by andresgutierrez** [comment]
It doesn't throw an exception here, as the data might come from an external source Phalcon simply ignores fields that does not belong to the model.

**Comment by rianorie** [comment]
Right, fair point. And a message is somewhat of a soft-error.. and we've just established the behavior is not actually an error so a message doesn't make sense either. Which leaves us with trimming the columns, I believe.

Agreed?
