### ISSUE TITLE
Implement allowEmpty for Ip validator

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#10992]
Currently, specifying 'allowEmpty' => true in the options array for the Ip validator does nothing. It still fails.

**Comment by KorsaR-ZN** [comment]
What Phalcon version are you using?

**Comment by KorsaR-ZN** [comment]
This feature is implemented only for `Phalcon\Validation`

`Ip` is not included in this component, tomorrow I'll be able to get it to port

**Comment by nsossonko** [comment]
Version 2.0.8. Many of the Mvc\Model\Validator classes also implement allowEmpty (as can be seen here: https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/validator/email.zep#L67 for example). Ip was just missed...

**Comment by KorsaR-ZN** [comment]
This component is deprecated since version 2.1. 
For the 2.0.x branch, I also made a patch today

**Comment by andresgutierrez** [comment]
Fixed in 2.0.x branch
