### ISSUE TITLE
Transaction in ORM cause timeout

### ISSUE THREAD

**Issue by wlisesrivas** [phalcon/cphalcon#10999]
When I try to create a records with transactions I get a timeout exception from database.

If I load the record explicitly, for example "$candidato->findFirstByid(1)"  the transaction save successfully, for example "$candidato->findFirstByid(1)"  the transaction save successfully because the ID of the record is present. But, when is a new record, cant do it. When debug step by step the "$candidato->id" is null, so I think thats the problem.

NOTE: If I don't use the transactions, everything work well.

![phalcon_error](https://cloud.githubusercontent.com/assets/1482092/10268968/58504a4e-6a9f-11e5-98b3-81526dcd6266.jpg)

The Database is simply, has several tables with foreign-key one to many, the models was created through the phalcon-tools ver 2.0.6

:: Environment ::
Phalcon  ver 2.0
PHP ver: 5.5.12
MySQL ver: 5.6.17

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
