### ISSUE TITLE
CSRF doesnt work in 2.1.x

### ISSUE THREAD

**Issue by Izopi4a** [phalcon/cphalcon#11009]
Pretty much everything is described here:

https://forum.phalconphp.com/discussion/8889/csrf-doesnt-work

however I tested it with master branch ( from today )(2.0.8) and it Works.

if it makes any difference in my registerServices for this module I have

```
$di->set('view', function() {

            $view = new View();
            $view->setViewsDir([
                MODULES_DIR . 'home/views/',
                COMMON_DIR . 'views/'
            ])
            ->setLayoutsDir(LAYOUT_DIR)
            ->setPartialsDir(PARTICIALS_DIR)
            ->setTemplateAfter('main')
            ->registerEngines(['.phtml' => 'Phalcon\Mvc\View\Engine\Php']);

            return $view;
        });

```

**Comment by Izopi4a** [comment]
```
$this->security->getTokenKey();
$this->security->getToken();

        echo "<pre>";
        print_r(var_dump($this->security->checkToken()));
        echo "</pre>";
        exit;
```

this prints false

**Comment by rudiservo** [comment]
@Izopi4a Two things we gotta be aware on security class.

The checkToken() function will DESTROY it's session reference to key and token if it checks out ok.
Like you mentioned most browsers have issues on double request, when they dont find favicon, etc, meaning if it checks out on the first request, second request that you see will destroy the session "$PHALCON/CSRF/KEY$" and "$PHALCON/CSRF$" variables and it will no longer check out.

3 ways you can solve this:
1st
$this->security->checkToken(null, null, false);

The last parameter wont destroy the session variables needed for the checkToken function

2nd 
check Vokuru implementation of csrf check.

3rd
Change Security Class on another version of Phalcon (2.1.x) to have a configuration not to destroy session variables, thus resolving the other optional issue of using the same token for the hole session.
i.e. $security->tokenValidDestroy(false);

@andresgutierrez , I dont mind making the change to 2.1.x, new issue and feature?


Reference:
https://forum.phalconphp.com/discussion/922/csrf-protection-not-working
bug #2279, #2596
