### ISSUE TITLE
ODM: incomplete object when $slice is used

### ISSUE THREAD

**Issue by ashpumpkin** [phalcon/cphalcon#11005]
Look at the code below

``` PHP
Robots::find([
            'fields' => [
                'robotParts' => false
            ]
])
```

It returns instances of \Phalcon\Mvc\Collection\Document instead of \Robots. This behaviour is described in the documentation and sounds reasonable:

> Returns specific columns instead of the full fields in the collection. When using this option an incomplete object is returned

BUT, why does phalcon return incomplete objects when I use $slice option?

``` PHP
Robots::find([
            'fields' => [
                'robotParts' => ['$slice' => 1]
            ]
])
```

I think this behaviour is incorrect, because resulting objects are complete. They still have 'robotParts' field even if $slice === 0

**Comment by andresgutierrez** [comment]
Incomplete objects are returned when key 'fields' is used in the parameters, it doesn't analyze the 'fields' directive in order to know whether it must return incomplete objects or not.

**Comment by ashpumpkin** [comment]
@andresgutierrez yes, I already understood that. Maybe someone can implement this analyzer?

**Comment by saiger** [comment]
@andresgutierrez Good day! 
I think @ashpumpkin is right because $slice operator controls the number of items of an array that a query returns. (http://docs.mongodb.org/manual/reference/operator/projection/slice/).
May be you can try to implement it?
Thanks!

**Comment by ashpumpkin** [comment]
@andresgutierrez mongo documents have no structure. And when using projection like this:
```[
    'field1' => true,
    'field2' => true,
    'field3' => true,
]
``` 
we will never know if documents are complete or not. Maybe we should add some kind of a flag for this feature?
For example:
```
Robots::find([
            'fields' => [
                'field1' => true,
                'field2' => true,
                'field3' => true,
                'robotParts' => ['$slice' => 1]
            ],
            'incomplete' => true
])
```
in this case it will return Document[], otherwise - always Robots. This feature can be done in ORM too

**Comment by ashpumpkin** [comment]
@andresgutierrez maybe we should replace this "fields" check, with hydration like in ORM? https://github.com/ashpumpkin/cphalcon/commit/ab2e6903d99247b06219825bcac31a3cd744efff
I can make a pull request if this implementation is good
