### ISSUE TITLE
Typo in security\random.zep?

### ISSUE THREAD

**Issue by pjacferreira** [phalcon/cphalcon#11002]
Hi, I found the following code in security/random.zep (starting line 106):
if function_exists("\\Sodium\\randombytes_buf") {
(*) return \\Sodium\\randombytes_buf(len);
}

I noticed the double '\\' on the line marked with (*). Is this correct?

**Comment by williamokano** [comment]
You say the \ before Sodium?

If yes, it's correct.

**Comment by sergeyklay** [comment]
> Is this correct?
Yes. Correct :)

```php
<?php

namespace A {
    function foo() { echo 'Foo', PHP_EOL; }
}

namespace B {

    function foo() { echo 'Bar', PHP_EOL; }

    foo();
    \A\foo();
}
```

**Comment by SidRoberts** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/security/random.zep#L107

It's this line. It's technically not correct but it still works.

**Comment by williamokano** [comment]
Right, I see.

Github omitted the double slash on the issue page.

I think it's really a typo from some ctrl+c, ctrl+v from the string, that
need to be scaped.

I haven't looked inside the file before the answer, my bad.

**Comment by sergeyklay** [comment]
@SidRoberts this is Zephir workaround

**Comment by pjacferreira** [comment]
Okay, 

return \\\\Sodium\\\\randombytes_buf(len);
is equivalent to the PHP
return \Sodium\randombytes_buf(len);

Correct?

If I read what @sergeyklay correctly, this means that there is a bug in the zephir compiler?

There is actually 2 instances of a double '\' in the file (a function number(): 298).

**Comment by sergeyklay** [comment]
Zephir fails for `\Namespace\function()` but work fine with `\\Namespace\\function()`

**Comment by pjacferreira** [comment]
Kind of funny, considering that the intermediate Parse File of the ZEP is correct with only a single '\'... So it means the problem must be within the ZEP compiler itself, and the code it produces...

**Comment by sergeyklay** [comment]
I'm not sure but you can try in Zephir something like `{"\Namespace\function"}()` <- with 1 slash

**Comment by sergeyklay** [comment]
@steffengy

**Comment by pjacferreira** [comment]
Okay thank you.

Your comment also brought to mind another piece of code in phalcon:
let {"_POST"} = [];
Which I find kind of strange, since in theory you could have just done
let _POST = []; // Also legal ZEP I think.

Must have been also a workaround.
