### ISSUE TITLE
Router.zep duplicate use

### ISSUE THREAD

**Issue by pjacferreira** [phalcon/cphalcon#11003]
Hi,

In the file router.zep, we have to 'includes' of Phalcon\Events\ManagerInterface. 
Once on line 26 the other on line 30.

**Comment by Green-Cat** [comment]
Nice catch, I submitted a PR to fix it.

**Comment by pjacferreira** [comment]
Actually, I didn't catch it, the PHP compiler did :)
I'm working on ZEP to PHP converter (https://github.com/test-to-com/zephir) and when I was debugging the Phalcon PHP Version, it threw up an exception.
