### ISSUE TITLE
Setting prefix in Assets\Collection applies also for non-local resources.

### ISSUE THREAD

**Issue by plescheff** [phalcon/cphalcon#11016]
Environment:
- Phalcon 2.0.8 (built from source)
- PHP 5.6.14

Consider use case where I want to add local and remote CSS files and want all locals to be prefixed with some path:

``` php
$assets = $di->get('assets');
$assets->collection('header')
    ->addCss('//fonts.googleapis.com/css?family=Antic+Slab', false)
    ->addCss('styles/main.css')
    ->setPrefix('foo/');
```

This will produce an unexpected output where remote CSS is also prefixed with _foo_:

``` html
<link rel="stylesheet" type="text/css" href="foo///fonts.googleapis.com/css?family=Antic+Slab">
<link rel="stylesheet" type="text/css" href="/foo/styles/main.css">
```

Expected result:

``` html
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Antic+Slab">
<link rel="stylesheet" type="text/css" href="/foo/styles/main.css">
```

**Comment by dancebear** [comment]
you can extends \Phalcon\Assets\Manager to fixed this.
`<?php
namespace xxx;

class Assets extends \Phalcon\Assets\Manager
{

    /**
     * Adds a resource by its type
     *
     * <code>
     * $assets->addResourceByType('css', new \Phalcon\Assets\Resource\Css('css/style.css'));
     * </code>
     */
    public function addResourceByType($type, $resource)
    {
        if (! isset($this->_collections[$type])) {
            $collection = new \Phalcon\Assets\Collection();
            $this->_collections[$type] = $collection;
        } else {
            $collection = $this->_collections[$type];
        }
        
        if ($collection->getJoin() !== true && $resource->getLocal() === true)
            $resource->setPath($collection->getPrefix() . $resource->getPath());
        
        /**
         * Add the resource to the collection
         */
        $collection->add($resource);
        
        return $this;
    }

    /**
     * Traverses a collection calling the callback to generate its HTML
     *
     * @param
     *            \Phalcon\Assets\Collection collection
     * @param
     *            callback callback
     * @param
     *            string type
     */
    public function output(\Phalcon\Assets\Collection $collection, $callback, $type)
    {
        if ($collection->getJoin() !== true)
            $collection->setPrefix(null);
        return parent::output($collection, $callback, $type);
    }
}`
use

`$di->setShared('assets', function () {            
            return new Assets();
        });
$assets = $di->get('assets');
$assets->collection('header')
    ->addCss('//fonts.googleapis.com/css?family=Antic+Slab', false)
    ->addCss('styles/main.css')
    ->setPrefix('foo/')->join(false);
`
