### ISSUE TITLE
[2.1.x] PHP 5.5.9-1ubuntu4.13 Trouble binding to closure when the source of the function was a static class method

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#11029]
* Phalcon - `7fdc8831d7bb80e84b17b9be6eefec809dc70e28` - latest
* Zephir - `3386a95bedd1e27e0cef0683e1e91224089aebac` - latest
* PHP - PHP 5.5.9-1ubuntu4.13

`PHP Warning:  Cannot bind an instance to a static closure in ...`

This is in my private project but I based it off of publicly accessible code in my Webird project, so it should be the same issue.

I'm using a static method in the base Module class to create the `view` service function.  Then each module calls this static method that is then set with module specific view paths (in addition to the common view paths).  This was working great in Phalcon 1.3 and 2.0 and it allows me to pre-compile all Volt templates for the build process.  The method needs to be public static because I make the typical assumption that only a single module will be called during execution cycle [and the CLI script to create the production build needs to be able to access all of the module view functions] .

* The [view function](https://github.com/perchlayer/webird/blob/master/app/phalcon/common/library/Module.php#L27) in the base Module class
* The web module [setting the service](https://github.com/perchlayer/webird/blob/master/app/phalcon/modules/web/Module.php#L49)

So you can see that function returned is not static and it should appear just as a normal function.  This seems like some kind of regression in all of the cool closure stuff that appeared in PHP 5.4 and 5.5.

I have no idea why it works like this.  I suspect that PHP 5.5 closure stuff is still just internal hacks to make it seem like their is pure support.  Zephir or Phalcon are perhaps interpreting something too strictly.

Would this work in PHP 5.6 or 7.0?

**Comment by dschissler** [comment]
I inlined the static function into the called module class and it stopped complaining about it at that location but it still fails at `echo $application->handle()->getContent();`

So again, is this a new convention that I need to adhere to or is this a bug?

**Comment by dschissler** [comment]
I recompiled Phalcon `2.0.8` with Zephir `0.9a-dev` and my code works again.  So, its a Phalcon issue.

**Comment by dschissler** [comment]
Also I'll add that the service closure wasn't able to bind the DI as `$this` in the closure.  I suspect that code is an issue.  The function comes from a static function but is itself just a anonymous function assigned to a variable and then passed in.  This is interfering with the DI being able to bind to it.

What version of PHP are the devs using?  PHP 5.4+ is supposed to be supported in this version of Phalcon.

**Comment by andresgutierrez** [comment]
PHP doesn't allow to bind an object to a closure created from a static context. I think this is something that must be changed by developers in order to use Phalcon 2.1

**Comment by dschissler** [comment]
@andresgutierrez Can you explain to me why this works with PHP 5.5 and Phalcon 2.0 but not 2.1?  Is Phalcon 2.0 doing something behind the scenes in C land that is cheating on what PHP is normally capable of?  I urge you to briefly look at the two source links above to explain why this is an illegal action.

I'd like to upgrade Webird and my private project to Phalcon 2.1 next week and to be able to report juicy new issues.  Its a bit cumbersome to switch back and forth between Phalcon 2.1 and 2.0 because of the change to validation.

**Comment by Jurigag** [comment]
Old validation is only deprecated its should still work in 2.1

**Comment by dschissler** [comment]
Ok, its been a while since I tried it.  Maybe there were interface differences.  Something was different but I can't remember what exactly.

**Comment by andresgutierrez** [comment]
@dschissler This is ilegal in Phalcon 2.1 because Phalcon 2.0 does not bind $this to closures. However, as I said before that constraint is introduced by PHP and not by Phalcon

**Comment by dschissler** [comment]
@andresgutierrez the 2.1 upgrade is going well so far and I'm trying to remove `use ($di)` from my services.  I've noticed a percularity in the `voltService`.  It seems that the voltService isn't having its context set to the DI.

**Old way:**

```php
$voltService = function($view, $di) {
    $config = $di->getConfig();
```

**Why not this?:**

```php
// $voltService = function($view, $di) {
$voltService = function($view) {
    $config = $this->getConfig();
```

Is there a reason why this doesn't work.  Perhaps the signature could even be changed to remove the `$di` and to have it bound like normal.

**Comment by huyencodon** [comment]
So, don't have any solution for this bug? i have a same problem.

![error](https://cloud.githubusercontent.com/assets/16998531/13944272/a0e1caae-f036-11e5-8bb0-00f0e6ae55d2.jpg)

**Comment by dschissler** [comment]
It looks like the tools need to be updated.  File an issue in that repo.

**Comment by andresgutierrez** [comment]
Can you please file an issue here https://github.com/phalcon/phalcon-devtools ?

**Comment by dschissler** [comment]
@andresgutierrez Does the following count as a static closure in PHP?

```php
$className = 'Phalcon\Db\Adapter\Pdo\\' . $adapter;
unset($configArray['adapter']);
return new $className($configArray);
```

I wouldn't think so but perhaps they hacked it into the internals this way.  It does seem pretty arbitrary and irrelevant of a designation from a purely programmer perspective.

**Comment by huyencodon** [comment]
Thanks all, but i fixed it. Because i use PHP ver 5.5 + Phalcon ver 2.1.0 => It's error.
But i replace phalcon ver 2.1.0 by ver 2.0.10 => it's OK.
I think ver 2.1.0 isn't compatible with PHP ver 5.5.

**Comment by andresgutierrez** [comment]
@huyencodon It's compatible, but a closure created in a static context cannot be bound to an object, this is a php behavior, it's not something that we introduced arbitrarily.

**Comment by andresgutierrez** [comment]
This is what is happening under the hood:

```php
<?php

class A
{
    public static function b()
    {
      return function() { };
    }
}

$closure = A::b();
\Closure::bind($closure, new \stdClass);
```

```bash
$ php a.php 
PHP Warning:  Cannot bind an instance to a static closure in /Users/andres/a.php on line 13

Warning: Cannot bind an instance to a static closure in /Users/andres/a.php on line 13
```

**Comment by dschissler** [comment]
I think that we need more information from @huyencodon because I looked at the dev tools code there and I can't see how its a static closure.

**Comment by kakuilan** [comment]
@dschissler 
Maybe when you get a service, use getService instead of get, for example:
$cache = $this->di->get('cache'); //Phalcon 2.0X
Replace as:
$cache = $this->di->getService('cache'); //Phalcon 2.1

**Comment by dschissler** [comment]
@sergeyklay Why is this on the 3.0.2 milestone?  I thought that it was just a limitation of PHP.

**Comment by GBraL** [comment]
Using Phalcon 3 and PHP 5.6 I can't remove this message?

**Comment by Jurigag** [comment]
As far as i understand no - https://github.com/phalcon/cphalcon/issues/11029#issuecomment-200612702

This is limitation of php, not phalcon bug.

**Comment by GBraL** [comment]
So, what I need to do to work with phalcon 3 and php 5.6? 

Because the warning messages can cause problems when rendering the page.

**Comment by dschissler** [comment]
@GBraL we would need to see your service definition.  This is fixable because I also encountered this issue when I migrated to Phalcon 3 because now it binds the service definition function to the DI object, whereas it didn't used to do that.

**Comment by GBraL** [comment]
Thank you.

**Comment by dugwood** [comment]
Hit the same bug/behaviour with Debian stable:
```php
var_dump(\Phalcon\Version::get(), PHP_VERSION);
$di['cache'] = function () {
    return []; // empty array
};
```
Then, when calling the service:

**Comment by Jurigag** [comment]
Also i don't understand this. I have 5.6.19 and your code fore me is returning:

```
string(5) "3.0.1" string(6) "5.6.19" array(0) { }
```

**Comment by dugwood** [comment]
You're right, if I only run:
```php
$di = new \Phalcon\DI\FactoryDefault();
$di['cache'] = function ()
{
	return [];
};
var_dump(\Phalcon\Version::get(), PHP_VERSION, $di->getCache());
exit;
```
It works well... so that must be the class I'm using to get the DI that goes wrong... I'll let you know (as many people still seem to have the issue!).

**Comment by dugwood** [comment]
OK, my issue is that I've done something like:
```php
class Kernel {
    public static function getDI($module) {
        $di = new FactoryDefault();
        $di['cache'] = ....
        return $di;
    }
}
$di = Kernel::getDI('frontend');
```
If I use a non-static «getDI» function, it works like a charm. I'll change it soon :-)

**Comment by Jurigag** [comment]
The problem is in currently in php there is no way to check if closure is static.

**Comment by dugwood** [comment]
I understand, but the fact that the DI is created in a static function returns the same error, which I found weird... But as long as there's a solution without suppressing the error, that's fine by me.
Hum, after reading @andresgutierrez answer again, I understand it correctly: «in a static context», that's exactly what I've done (wrong).

**Comment by Jurigag** [comment]
Just there is not a bug at all in phalcon. We can't check if it's static context in php. Only one way i guess to do this is add something to zephir to check it, not sure if it's possible or as i wrote add `@` in zephir.

**Comment by dugwood** [comment]
I think you shouldn't hide the PHP error. It's not a bug in Zephir, but I didn't see any global explanation or answer about what was causing it.
You said: https://github.com/phalcon/cphalcon/issues/11029#issuecomment-245774054 so to me there wasn't any solution to avoid this PHP error with PHP 5.6. But there is! Your comment may be understood the wrong way.
So it's a PHP error, not a Zephir bug, and the solution is to avoid declaring the DI within a static method. Which is quite easy to achieve (I've done it in less than 10 minutes on my whole application, once I've understood the issue).
