### ISSUE TITLE
Model::findFirst() with conditions and always getting 0 result on Oracle

### ISSUE THREAD

**Issue by MLukman** [phalcon/cphalcon#11033]
I'm using PhalconPHP 2.0.7's \Phalcon\Mvc\Model::findFirst() with conditions on Oracle database and always getting 0 result. When I attached event manager to log SQL to a file, it seems that PhalconPHP adds "ROWNUM <= 0" to the SQL, which is of course means 0 result. Adding limit parameter doesn't help.

Sample code:

    Resource::findFirst(array(
        'STAFF_NO = :staff:',
        'bind' => array(
            'staff' => $staffNo
        )
    ));

Generated SQL:

    SELECT * FROM (SELECT Z1.*, ROWNUM PHALCON_RN FROM (/***** effective SQL *****/) Z1 WHERE ROWNUM <= 0)

**Comment by rlaffers** [comment]
I can confirm this bug. It is buggy even without any conditions. The point is, ROWNUM starts counting at 1 in Oracle, not at 0, so the WHERE ROWNUM <= 0 effectively filters out all results.

**Comment by jeiel** [comment]
In the current version already they got this problem solving


git clone  git://github.com/phalcon/cphalcon.git
cd cphalcon/ext
git checkout 2.0.x
sudo ./install(edited)

**Comment by rlaffers** [comment]
1fe6089a2773fe0926af34c6202470ee32c199be does not properly resolve the issue. findFirst works, but find with limit=1 not. The result contains all rows from the table. The limit method needs an overhaul. https://github.com/phalcon/cphalcon/issues/11217

**Comment by rlaffers** [comment]
I fixed the Oracle dialect in my private branch at rlaffers@91985cf

Unfortunately I had to branch off from the last known working commit from just before https://github.com/phalcon/cphalcon/commit/1fe6089a2773fe0926af34c6202470ee32c199be . After that, it seems Phalcon does not step into the limit method in the Oracle dialect when using findFirst() or find with limit specified. Can anybody confirm this behavior? I would like to bring my fix into the 2.0.x branch but first we have to figure out what went wrong later on.

**Comment by jeiel** [comment]
I am working with version 2.0x I have not had problems making the edit and delete records common simple crud. How else could test the operation?

**Comment by rlaffers** [comment]
@jeiel Did you test my changes or are you reporting not having any issue with the standard build?

**Comment by jeiel** [comment]
I am confirming that I have no problem to edit and delete the code you already got and want to test your code if you help me also that
how could download it to compile correct me if it is not so 
git clone --depth=1 git://github.com/rlaffers/cphalcon.git
cd cphalcon/build
sudo ./install

'll try to select multiple , and views I confirm if I get error or confirm if that moment gave problem, after your corrections and you compilale notice

**Comment by rlaffers** [comment]
After cloning you have to 
```
git checkout -b 2.0.x origin/2.0.x
```
then cd build and the rest as you wrote.

**Comment by sergeyklay** [comment]
Phalcon does not support Oracle. Refer to #12008
