### ISSUE TITLE
Fix ODM logic

### ISSUE THREAD

**Issue by dzubchik** [phalcon/cphalcon#11031]
Currently ODM working in some interesting way. When do query with set of fields - it returns document,  without - returns collection. My proposition is to correct this - always return document or set of documents, and give ability to change document class to be returned. How about that?

**Comment by sergeyklay** [comment]
:+1:

**Comment by ashpumpkin** [comment]
@sergeyklay 
Maybe my hydration in ODM pr (https://github.com/phalcon/cphalcon/pull/11013) will be alright for that issue?

**Comment by sergeyklay** [comment]
@dzubchik ?

**Comment by sergeyklay** [comment]
@ashpumpkin This PR doesn't solves the problem completely.

**Comment by ashpumpkin** [comment]
@sergeyklay why not?
```PHP
Robots::find(); //returns Robots
Robots::find(['hydration' => Collection::HYDRATE_DOCUMENTS]); // you get Documents
Robots::find(['hydration' => Collection::HYDRATE_COLLECTIONS]); // you get Robots
Robots::find(['hydration' => Collection::HYDRATE_ARRAYS]); // you get raw arrays (the fastest one)
```
and the same works with findFirst(). I think the problem is completely solved :smiley:

**Comment by aleksandrzen** [comment]
:+1:

**Comment by dzubchik** [comment]
@ashpumpkin , it does not solve the issue because you can not declare the document class for collection

**Comment by ashpumpkin** [comment]
@dzubchik @sergeyklay 
How about that:
```PHP
Robots::find(); //returns Robots
Robots::find(['class' => 'Books']); // you get Books
Robots::find(['class' => 'Phalcon\Mvc\Collection\Document']); // you get Documents
Robots::find(['class' => 'UnknowClass']); // you get php error Class 'UnknownClass' not found
Robots::find(['class' => 'KnownClassNotImplementingInterface']); // you get phalcon exception "Class must be an implementation of Phalcon\Mvc\CollectionInterface or an instance of Phalcon\Mvc\Collection\Document"
```
I almost implemented it on my local machine and can make a pr if this realization is good and solving the problem completely.

**Comment by dzubchik** [comment]
@ashpumpkin , I thought it would be something like this:
```php
<?php

use Phalcon\Mvc\Collection;

class Robots extends Collection
{
    public static $documentClass = 'My\Namespace\Robot\Document';
}
```

And by default it would search document class in same namespace as collection. And if there are no document class - uses default.

**Comment by ashpumpkin** [comment]
@dzubchik I think in case when you need to dynamically change documents class in one script this code looks better:
```PHP
$dinosaurs = Zombies::find([/*some query options*/ 'class' => 'Dinosaurs']);
$vampires = Zombies::find([/*some other query options*/ 'class' => 'Vampires']);
```
than
```PHP
// (Zombies collection has $documentClass = 'Dinosaurs')
$dinosaurs = Zombies::find([/*some query options*/']);
Zombies::$documentClass = 'Vampires';
$vampires = Zombies::find([/*some other query options*/']);
```

**Comment by ashpumpkin** [comment]
@dzubchik here is my commit for this feature https://github.com/ashpumpkin/cphalcon/commit/eab40a7f49083f15b98aa766949a64cdff5a42e9
If you agree with it I can make a pr, @sergeyklay said that you may have your own ready solution for that, maybe you show it and we'll compare?

**Comment by dzubchik** [comment]
@ashpumpkin, sorry I can not show my solution now because I'm on vacation. You pull request is almost what I wanted, but I can not understand use cases when you need to change document class in runtime.

**Comment by dzubchik** [comment]
@ashpumpkin, you solution is 90% of this issue. We had discussion about this issue in our company and decided to extend current phalcon ODM. Moreover, our solution is completely remove backward compatibility and has other "philosophy". I would like to close issue.
