### ISSUE TITLE
Optimize generated queries

### ISSUE THREAD

**Issue by ITCPhantom** [phalcon/cphalcon#11046]
I found that Phalcon methods (find(), findFirst() etc.) generate sql like `SELECT table.column1, table.column2 ...`. Is there a way to force Phalcon to generate sql like `SELECT * ...` or `SELECT table.* ...`. There are a lot of queries and big models in my project and current approach is really a waste of network bandwidth.

**Comment by sszdh** [comment]
+1

**Comment by andresgutierrez** [comment]
Actually passing all the columns from the client makes the database server not having to expand the `*` which improves performance. Also, if the model partially maps some columns of the model it will make the database server return unnecessary data.

**Comment by sergeyklay** [comment]
Agree with @andresgutierrez

**Comment by ITCPhantom** [comment]
Ok, but is there a way to choose strategy? (List names or use *)
