### ISSUE TITLE
Loader doesn't fully follow PSR-4 specification

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#11041]
How to reproduce:

**/tmp/loader_issue.php**
```php
<?php

use Phalcon\Loader;

$loader = new Loader();

$loader->registerNamespaces('ABC');

print_r($loader);
```

```
$ php loader_issue.php 
PHP Catchable fatal error:  Argument 1 passed to Phalcon\Loader::registerNamespaces() must be of the type array, string given in /tmp/loader_issue.php on line 7
PHP Stack trace:
PHP   1. {main}() /tmp/loader_issue.php:0
```

From http://www.php-fig.org/psr/psr-4/
> Autoloader implementations MUST NOT throw exceptions, MUST NOT raise errors of any level, and SHOULD NOT return a value.

**Comment by andresgutierrez** [comment]
That note is for the auto-loading process and do not for every functionality that an auto-loader provides

**Comment by sergeyklay** [comment]
Let's take a look at
```zephir
public function registerNamespaces(array !namespaces, boolean merge = false) -> <Loader>
{
    ...
}
```
We can just do nothing if `namespaces` is not an array

**Comment by andresgutierrez** [comment]
Yes, that's how it's expected to work

**Comment by sergeyklay** [comment]
How about 
```zephir
public function registerNamespaces(namespaces, boolean merge = false) -> <Loader>
{
    if typeof namespaces != "array" || !namespaces instanceof \Traversable {
        return this;
    }
    ...
}
```

**Comment by andresgutierrez** [comment]
But that silents the error and the developer will never know that a wrong value is being passed causing the autoloader to not work properly.

**Comment by sergeyklay** [comment]
But that is exactly what is expected of PSR-4 compliant autoloader.

**Comment by sergeyklay** [comment]
In any case we can fire event here

**Comment by andresgutierrez** [comment]
No, the only method that must not throw exceptions is autoload: https://github.com/phalcon/cphalcon/blob/master/phalcon/loader.zep#L256

**Comment by sergeyklay** [comment]
Looks logical. Thank you :)
