### ISSUE TITLE
Dispatcher has detected a cyclic routing causing stability problems

### ISSUE THREAD

**Issue by jigneshnavsoft** [phalcon/cphalcon#11053]
Below is my code but nor forwarding ???

 if ($this->session->client['authTestVersion'] == 'test') {
            return $dispatcher->forward(array(
                'namespace' => 'Modules\Modules\TestService\Controllers',
                'controller' => 'test',
                'action' => 'index'
            ));
            return false;
        }

**Comment by sergeyklay** [comment]
Can you please provide `Modules\Modules\TestService\Controllers\TestController` and dispatcher config ?

**Comment by jigneshnavsoft** [comment]
$application->registerModules(array(
    
    'testservice' => array(
        'className' => 'Modules\Modules\Testservice\Module',
        'path' => __DIR__ . '/../modules/testservice/Module.php'
    )
    
));

**Comment by jigneshnavsoft** [comment]
Module.php
$application->registerModules(array(
    
    'testservice' => array(
        'className' => 'Modules\Modules\Testservice\Module',
        'path' => __DIR__ . '/../modules/testservice/Module.php'
    )
    
));

**Comment by jigneshnavsoft** [comment]
ControllerBase.php
public function beforeExecuteRoute($dispatcher) {
return $dispatcher->forward(array(
            'controller' => 'test',
            'action' => 'index'
            ));

}

**Comment by sergeyklay** [comment]
It isn't bug.
For questions like this you can use the forum: https://forum.phalconphp.com/
