### ISSUE TITLE
Phalcon\Validation\Validator\Regex

### ISSUE THREAD

**Issue by feanorelf** [phalcon/cphalcon#11057]
Referring to Version 2.1 Beta 2

The validator seems to prepend a '^' to the given pattern: for instance, the pattern: /[1-9]+/, which should validate for any string containing at least one digit, only validates when the string "starts" with a digit. 
This makes, above all, validation with lookahead zero-length patterns - the most common for passwords - impossible.

**Comment by dzubchik** [comment]
@feanorelf , please watch this issue #11414
