### ISSUE TITLE
Phalcon\Mvc\Model\Query[2.0.x] produces incorrect SQL WHERE clause when Models have columns with same name

### ISSUE THREAD

**Issue by ghost** [phalcon/cphalcon#11068]
Hi,

The query componen of the framework produces invalid WHERE clause when for a query with simple join when bot models have a column with the same name and it is used as filtering condition. To reproduce the issue:
- Given the standart Models from the official documentation, add the 'created_at' column of type DATETIME to Robots, RobotsParts and Parts Models, and the 'active' column of type TINYINT(1) to Robots and Parts Models.
- Create the following query through the Query Builder:

``` php
$rp = new RobotsParts();
$builder = $rp->getModelsManager()->createBuilder()
    ->from(array('rp' => 'RobotsParts'))
    ->columns(array(
        'id' => 'r.id',
        'name' => 'r.name',
        'created_at' => 'r.created_at',
        'assigned_at' => 'rp.created_at',
    ))
    ->join('Robots', 'rp.robot_id = r.id', 'r')
    ->where('(rp.created_at = :rp_created_at:) AND (rp.part_id = :id: AND r.active = 1)');
```
- Print out the SQL invoking:

``` php
$builder->getQuery()->getSql();
```
- The componen generates the following SQL query which fails because of an ambiguous column name in WHERE clause:

``` sql
SELECT
  `r`.`id` AS `id`,
  `r`.`name` AS `name`,
  `r`.`created_at` AS `created_at`,
  `r`.`updated_at` AS `updated_at`,
  `rp`.`created_at` AS `assigned_at`
FROM `robots_parts` AS `rp`
INNER JOIN `robots` AS `r` ON `rp`.`robots_id` = `r`.`id`
WHERE (`created_at` = :rp_created_at)
  AND (`rp`.`part_id` = :id AND `r`.`active` = 1)
```

It is interesting that the PHQL is strill correct. The error is introduced during the parsing of the PHQL to SQL.

**Comment by phalcon** [comment]
What error or exception are you getting?

**Comment by karen-nalbandian-adb** [comment]
I dont get any exception on Phalcon, just the incorrectly genetated SQL expression. As you can see the 'rp' domain is just stripped out in the leftmost side of the resulting WHERE clause.

**Comment by hinablue** [comment]
This is the `columns` issue?( I'm not sure. ) if use the `columns` like that,

``` php
->columns(array(
    'id' => 'r.id',
    'name' => 'r.name',
    'created_at' => 'r.created_at',
    'assigned_at' => 'rp.created_at',
))
```

The builder will output the SQL query without the `rp` domain. I think 

Chang the `columns` to,

``` php
->columns(array(
    'r.id',
    'r.name',
    'r.created_at',
    'rp.created_at AS assigned_at',
))
```

The builder output SQL query will be fine.

**Comment by karen-nalbandian-adb** [comment]
Hello,
It is not related to the getSql() exactly. I think it is more about the _getExpression() protected method where the query parts are parsed. Take a look at the WHERE part of the generated query "`WHERE (created_at = :rp_created_at)...`". This is where the prefix is removed. At some point the expression parser considers the field as "qualified" (maybe because it exists in the model in the FROM part), and strips out the domain.

P.S.: Changing the `columns` format to the proposed one didn't fixed the issue.

**Comment by hinablue** [comment]
Hello,

I tested the `columns`, Yeap, if the expression like `created_at` in the columnMap list, the where case parse function domain will missing.

And I found the source code in `query.zep`, the `parse()` function in your case, the `domain` does not exists. So, it's a bug I think :-(

For example, if `columns` like this,

``` php
->columns(array(
    'r.id',
    'r.name',
    'r.created_at AS created',
    'rp.created_at AS assigned',
))
```

And `WHERE` case like this,

``` php
... AND (rp.created_at = \'2015-10-29\')');
```

The parse from the query will be,

``` php
    ["right"]=>
    array(2) {
      ["type"]=>
      string(11) "parentheses"
      ["left"]=>
      array(4) {
        ["type"]=>
        string(9) "binary-op"
        ["op"]=>
        string(1) "="
        ["left"]=>
        array(4) {
          ["type"]=>
          string(9) "qualified"
          ["domain"]=>
          string(1) "rp"
          ["name"]=>
          string(6) "created_at"
          ["balias"]=>
          string(6) "created_at"
        }
        ["right"]=>
        array(2) {
          ["type"]=>
          string(7) "literal"
          ["value"]=>
          string(11) "'2015-10-29'"
        }
      }
    }
```

But if the `columns` like this,

``` php
->columns(array(
    'id' => 'r.id',
    'name' => 'r.name',
    'created_at' => 'r.created_at',
    'assigned_at' => 'rp.created_at',
))
```

With the same `WHERE` case.

The parse is incorrect like this,

``` php
["right"]=>
    array(2) {
      ["type"]=>
      string(11) "parentheses"
      ["left"]=>
      array(4) {
        ["type"]=>
        string(9) "binary-op"
        ["op"]=>
        string(1) "="
        ["left"]=>
        array(2) {
          ["type"]=>
          string(9) "qualified"
          ["name"]=>
          string(6) "created_at"
        }
        ["right"]=>
        array(2) {
          ["type"]=>
          string(7) "literal"
          ["value"]=>
          string(11) "'2015-10-29'"
        }
      }
```

The left domain is missing and the balias also gone . :-(

**Comment by karen-nalbandian-adb** [comment]
Hi @phalcon!

Is there any plan to review this issue and if it is a bug correct it?

Thank you in advance!

**Comment by andresgutierrez** [comment]
@karen-nalbandian-adb Checking it now

**Comment by satakecode** [comment]
A long time has passed since this problem was reported and yet I still find it in version 3.2.1. No plans to correct this issue?

**Comment by sergeyklay** [comment]
@satakecode I'll take a look

**Comment by satakecode** [comment]
I found where this issue lies. 

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query.zep

```
protected final function _getQualified(array! expr) -> array
{
    var columnName, sqlColumnAliases, metaData, sqlAliases,
        source, sqlAliasesModelsInstances, realColumnName, columnDomain,
        model, models, columnMap, hasModel, className;
    int number;

    let columnName = expr["name"];

    /**
     * Check if the qualified name is a column alias
     */
    let sqlColumnAliases = this->_sqlColumnAliases;
    if isset sqlColumnAliases[columnName] {
        return [
            "type": "qualified",
            "name": columnName
        ];
    }

...

}
```

In my case:

> expr = Array
>(
>    [type] => PHQL_T_QUALIFIED
>    [domain] => Assets
>    [name] => AssStatus
>)

So my columnName="AssStatus", and at the same time I have an alias with the same name "AssStatus", in this case the alias gets detected @ `if isset sqlColumnAliases[columnName]` and returns ignoring the fact that a domain was specified for the operation.

Maybe changing the logic from `if isset sqlColumnAliases[columnName]` to if isset sqlColumnAliases[columnName] && !isset expr["domain"]` might circumvent the problem.

Regards.
