### ISSUE TITLE
Notice: Array to string conversion in C:\xampp\htdocs\....

### ISSUE THREAD

**Issue by emrullahayin** [phalcon/cphalcon#11061]
Notice: Array to string conversion in C:\xampp\htdocs\.. ???????

Model

$urun = urunler::findFirst(
				array(
						'conditions' => array('urunNo' => "{$id}")
				));
		$urun->delete($id);

Controller

$this->view->disable();
			$urun =  new urunler();
			$urun->sil($this->request->getPost());

**Comment by SidRoberts** [comment]
The `conditions` parameter needs to be a string. You can use the `bind` parameter to avoid SQL injections. [More information here](https://docs.phalconphp.com/en/latest/reference/models.html#binding-parameters).

This should work:

```php
$urun = urunler::findFirst(
    array(
        'conditions' => 'urunNo = :urunNo:',
        'bind'       => array(
            'urunNo' => "{$id}"
        )
    )
);

$urun->delete($id);
```
