### ISSUE TITLE
Still do not compile using PHP 7 RC5 

### ISSUE THREAD

**Issue by masums** [phalcon/cphalcon#11065]
I have tried to compile using PHP 7 but shows following error.
ZVAL_STRING takes parameter 2 but 3 passed. 

php info

PHP 7.0.0RC5 (cli) (built: Oct 25 2015 17:36:08) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

**Comment by andresgutierrez** [comment]
Complete support will be announced when ready
