### ISSUE TITLE
Fatal error: Call to a member function delete() on boolean in

### ISSUE THREAD

**Issue by emrullahayin** [phalcon/cphalcon#11074]
public function delete($id){
              $product = $this->findFirst(
				array(
						"conditions" =>"productId= :id:",
						"bind" => array("id"=> $id)
				));
		
		$product->delete($id);
	
	}

**Comment by tdely** [comment]
When findFirst doesn't find a matching record it return false, that is why you are seeing this error message. It's easily fixed by something like this:

```php
public function delete($id){
    $product = $this->findFirst(
            array(
                "conditions" =>"productId= :id:",
                "bind" => array("id"=> $id)
            ));
    if ($product) {
        return $product->delete($id);
    }
    return false;

}
```
