### ISSUE TITLE
http request setStatusCode is  too slow

### ISSUE THREAD

**Issue by vodcms** [phalcon/cphalcon#11073]
i use phalcon make restfull services.

but i use apache ab  test api .

when use $this->response->setStatusCode(404) or other statucCode is too slow?

i try use php navtie  header("Content-type:application/json", false, 404);

it work very fast.

maybe is bug.

OS          OS X Yosemite 10.10.5
PHP       PHP 5.5.27 (cli) (built: Jul 23 2015 00:21:59) 
Phalcon  2.0.8 Version 0.8.0a
AB            This is ApacheBench, Version 2.3

**Comment by Jurigag** [comment]
I checked it on nginx + php-fpm, there is no diffrence.

**Comment by rabihsyw** [comment]
I built a Micro application, everything works fine. But performance tests shows a frustrating results. The application is very slow :

    ab -n 1000 -c 50 http://myproject.net/
Normal results:

    Concurrency Level:      100
    Time taken for tests:   58.083 seconds
    Complete requests:      1000
    Failed requests:        0
    Non-2xx responses:      1000
    Total transferred:      578000 bytes
    HTML transferred:       189000 bytes
    Requests per second:    17.22 [#/sec] (mean)
    Time per request:       5808.272 [ms] (mean)
    Time per request:       58.083 [ms] (mean, across all concurrent requests)
    Transfer rate:          9.72 [Kbytes/sec] received


After I comment **$response->send();** test results becomes better :

    Concurrency Level:      100
    Time taken for tests:   7.960 seconds
    Complete requests:      1000
    Failed requests:        0
    Total transferred:      166000 bytes
    HTML transferred:       0 bytes
    Requests per second:    125.62 [#/sec] (mean)
    Time per request:       796.048 [ms] (mean)
    Time per request:       7.960 [ms] (mean, across all concurrent requests)
    Transfer rate:          20.36 [Kbytes/sec] received

In the index file I defined the response object as a shared service :

    $di->setShared(System::RESPONSE, new App\Http\Response());

**App\Http\Response** is a class extends \Phalcon\Http\Response to allow me add some headers required in my application

    namespace App\Http;

    class Response extends \Phalcon\Http\Response
    {
        public function getDefaultErrorMessages()
        {
            return $this->defaultErrorMessages;
        }

        public function setDefaultErrorMessages($messages)
        {
            $this->defaultErrorMessages = $messages;
        }

        public function setErrors(array $messages)
        {
           $this->validationErrors = $messages;
        }

        public function setErrorContent(\Exception $e, $developerInfo = false)
        {
            $errorCode = $e->getCode();
            $statusCode = 500;
            $message = 'Unspecified error';
            
            $error = [];
            if ($this->validationErrors) {
                $error['errors'] = $this->validationErrors;
            }

        
            $this->setJsonContent(['error' => $error]);
            $this->setStatusCode($statusCode);
        }


        public function setJsonContent($content, $jsonOptions = 0, $depth = 512)
        {
            parent::setJsonContent($content, $jsonOptions, $depth);
            $this->setHeader('Access-Control-Allow-Origin', '*');
            $this->setHeader('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
            $this->setHeader(
                'Access-Control-Allow-Headers',
                'Content-Type, X-Requested-With, X-Authorization'
            );

            $this->setContentType('application/json');
        }
    }




All my code is wrapped in a try-catch statement in the index file. 
I tried to make an error in order to throw an exception, if the the exception is thrown by Zephir test results shows a fast results, while if it is thrown by our code test results shows same slow results.

When I use -k modifier of 'ab' results becomes much better :

    ab -k -n 1000 -c 50 http://myproject.net/

**Comment by Jurigag** [comment]
What problem you have ? 58ms is really so bad response time ?

**Comment by rabihsyw** [comment]
The application on my local machine which runs Ubuntu OS. I think it is slow comparing to other tests of another applications, all of them were done on my local machine.

Also when I comment "$response->send();" statement the results becomes obviously  much faster.

**Comment by Jurigag** [comment]
Yes it takes 58s to complete test for 1000 requests, so 58/1000 = 58ms per request.

**Comment by andresgutierrez** [comment]
Can you please execute `curl --head url` on both scenarios?

**Comment by rabihsyw** [comment]
**First Scenario**

> HTTP/1.1 200 OK
Date: Fri, 29 Jan 2016 09:43:01 GMT
Server: Apache/2.4.12 (Ubuntu)
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,PUT,POST,DELETE
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Authorization
E-Tag: 5642ebf7f7e8e3c7999855d1f28cbb65
Content-Length: 48
Content-Type: application/json


**Second scenario "without response":**

> HTTP/1.1 200 OK
Date: Fri, 29 Jan 2016 09:48:31 GMT
Server: Apache/2.4.12 (Ubuntu)
Content-Length: 0
Content-Type: text/html; charset=UTF-8



I noticed that the responses becomes slower whenever an exception is thrown
In addition in 'ab' testing  I missed the quotes that surrounds my targeted URL, so just the first sent parameter was readable where the others were ignored thats why there were always a thrown exception which make test results slower.

The latest test results :

> ab -n 1000 -c 100 "http://myproject.net/?vid=something&cid=somthingelse"

> Concurrency Level:      100
Time taken for tests:   40.011 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      166000 bytes
HTML transferred:       0 bytes
Requests per second:    24.99 [#/sec] (mean)
Time per request:       4001.090 [ms] (mean)
Time per request:       40.011 [ms] (mean, across all concurrent requests)
Transfer rate:          4.05 [Kbytes/sec] received

I will try to test it in the server again, then I will post my feedbacks

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
