### ISSUE TITLE
Error in migration when adding a foreign key with reference option = RESTRICT

### ISSUE THREAD

**Issue by phasmaweb** [phalcon/cphalcon#11083]
hello I am using the 2.0.8 version and I have this problem. The following code

```php
self::$_connection->addForeignKey('table_name', self::getDbName(), new Reference('fk_table_name_01', array(
            'referencedTable' => 'ref_table',
            'columns' => array('col_name'),
            'referencedColumns' => array('id'),
            'onUpdate' => 'RESTRICT',
            'onDelete' => 'RESTRICT')
        ));
```
throught the phalcon migration run command will produce a foreign key with reference option = NO ACTION for both update and delete.

**Comment by sergeyklay** [comment]
All Devtools (migrations including) related issues should be [published here](https://github.com/phalcon/phalcon-devtools/issues)

**Comment by phasmaweb** [comment]
Can I move the post somehow?

**Comment by sergeyklay** [comment]
Close this issue and reopen at Devtools repo
