### ISSUE TITLE
Prepared parameters: positional (?) PDO-like placeholders syntax

### ISSUE THREAD

**Issue by stamster** [phalcon/cphalcon#11089]
Hello,
Is there a way to use PDO-like syntax for placeholders with prepared statements and execute PDO queries?

```php
$preparedstmt = 'INSERT INTO TABLE (ID, Field0, Field1, Field2, Field3, Field4, Field5, Field6, Field7, Field8) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';

$bindData = [$className, $array['someaction'], $array['something'], $array['requestGUID'], $somevariable, $_SESSION['www'], $_SESSION['qqq'], $_SESSION['aaa'], $_SESSION['zzz'], $_SESSION['xxx']]; 

$query = $pdo->prepare($preparedstmt);

$query->execute($bindData); 

```
For now, I'm forced to use PHQL placeholders syntax like this example from official documentation

```php
// Inserting using placeholders
$phql = "INSERT INTO Cars (name, brand_id, year, style) "
      . "VALUES (?0, ?1, ?2, ?3)";
$manager->executeQuery(
    $phql,
    array(
     'Lamborghini Espada',
     7,
      1969,
      'Grand Tourer',
    )
);
```

Why do I have to type hints like ?0 and ?1 instead of question marks in natural ordering of the field names and supplied numeric array keys which bind to the data itself?

**Comment by andresgutierrez** [comment]
You can use the database component: https://docs.phalconphp.com/en/latest/reference/db.html

**Comment by stamster** [comment]
Thanks for a quick answer and classification (not a bug really).

**Comment by jimmycdinata** [comment]
As @andresgutierrez said, you able to use raw sql if you want:

```
$db = DI::getDefault()->get('db');
$db->execute("INSERT INTO cars (name, brand_id, year, style) VALUES (?, ?, ?, ?)", array('Lamborghini Espada', 7, 1969, 'Grand Tourer'));
```

**Comment by stamster** [comment]
Thanks.
RAW will do all the complex queries :+1:

**Comment by dzubchik** [comment]
@sergeyklay
