### ISSUE TITLE
[NFR] How to remove validator from element?

### ISSUE THREAD

**Issue by valVk** [phalcon/cphalcon#11082]
Elements allow add validators through method Element->[addValidator()](https://github.com/phalcon/cphalcon/blob/master/phalcon/forms/elementinterface.zep#L100)

We can even add a batch of validators. But there is no any possibility to remove validator on demand.

for example

I add some stack of validators for field 'Email'

``` php

/**
 * Class Users
 * @package PM
 * @Source("users")
 */
class Users extends \Phalcon\Mvc\Model
{
    /**
     * @Column(type="string", nullable=false, column="email")
     * @FormOptions(type=email)
     * @FormValidator(
     *  "Phalcon\Validation\Validator\PresenceOf":{'message': 'The e-mail field is required'},
     *  "Phalcon\Validation\Validator\Email":{'message': 'E-mail is not valid'},
     *  "Phalcon\Validation\Validator\Uniqueness":{'message': 'The E-mail is already taken', "model":"PM\Users"}
     * )
     * @var string
     */
    protected $email;
}

```

Later for example when I'll create an user everything goes fine.

Another story when I'll try to edit this user.
Validator `Phalcon\Validation\Validator\Uniqueness` failed every time I hit submit button, because user's email was not changed during edition process and it exists in DB.

So what I would like to use it in the some kind of way

``` php
$form = new EntityForm(Users::findFirst($id));
if ($this->request->isPost()) {
    if ($oldEmail == $newEmail) {
        $form->removeValidator($form->get('email'), ['Phalcon\\Validation\\Validator\\Db\\Uniqueness']);
    }
    if ($form->isValid($this->request->getPost()) != false) {
        //some code here
        return $this->response->redirect(["for" => "viewUser", "id" => $id]);
    }
}
```

Now I ended up with this

``` php
$form = new EntityForm(Users::findFirst($id));
if ($this->request->isPost()) {
    if ($oldEmail != $newEmail) {
        $form->get('email')->addValidator(new Uniqueness(
        ['message' => 'The E-mail is already taken', "table" => "users", "column" => "email"]
        ));
    }
    if ($form->isValid($this->request->getPost()) != false) {
        //some code here
        return $this->response->redirect(["for" => "viewUser", "id" => $id]);
    }
}
```

But I think It will be great to have possibility to remove validators on demand. And more convenient to remove that validation than add it every time it need

Or maybe someone will pointed me to the hidden parts of Phalcon which help me to do what I want.

Thanks

**Comment by auricurvy** [comment]
It's there any update regarding this request? 

I think it's ass important as removing an element from the form. 

Thanks.

**Comment by cbichis** [comment]
Same question here... I can't believe there is no way to remove a validator...

**Comment by Jurigag** [comment]
But Uniquqness validator is already ignoring current entity like is if it's found model and we are doing update, then it's adding `id != :id:`

**Comment by valVk** [comment]
This NFR may be outdated, because it is 1 year old. Probably current implementation of Uniqueness takes this into account. But main goal for this NFR is have possibility to remove validator from a stack in case if it does not need.

**Comment by temuri416** [comment]
Any chance this gets looked at?

Thanks!

**Comment by temuri416** [comment]
@sergeyklay This is still an issue, can we have this addressed?

Thanks!

**Comment by temuri416** [comment]
Never mind, this does the job:

```
$element->addValidators([], false);
```
