### ISSUE TITLE
Volt: Nested for-loop in if statement throws error

### ISSUE THREAD

**Issue by MLukman** [phalcon/cphalcon#11094]
In any volt template, putting nested for-loop in an if statement throws error "Unexpected ENDIF"

Sample:

	{% set data = 0 %}
    {% set arr = [[0, 1], [1, 2], [2, 3]] %}
    {% if data == 1 %}
    
        {% for a in arr %}
        {% for b in a %}
        
        {% endfor %}
        {% endfor %}
    
    {% endif %}

**Comment by jimmycdinata** [comment]
Yes, it's a bug. Related issue #10970

**Comment by m4k5imG** [comment]
If I use elseif statement with nested loop, I have same error
