### ISSUE TITLE
PHALCON Relation Problem

### ISSUE THREAD

**Issue by pjacferreira** [phalcon/cphalcon#11090]
Hi, 

This is probably a known bug/feature?

But I wanted to document it, in the case it was not known.

The problem is the following. I have a model with a dependency (recursive)

```
class User extends Model {
   public $id;
   ...
   protected $creator
   ...
}
```

The basic idea being that I want to know who created the user.

Somewhere in my code, I do something like

```
$new_user = new User();
$new_user->creator = $creator; // An instance of \User
$new_user->save();
```

This unfortunately exists with an exception like:

```
There are no defined relations for the model 'models\User' using alias 'creator'
```

I tracked the problem down to the file model.zep (around line 4089)

```
/**
 * Magic method to assign values to the the model
 *
 * @param string property
 * @param mixed value
 */
public function __set(string property, value)
{
    var lowerProperty, related, modelName, manager, lowerKey,
        relation, referencedModel, key, item;

    /**
     * Values are probably relationships if they are objects
     */
    if typeof value == "object" {
        if value instanceof ModelInterface {
            let lowerProperty = strtolower(property),
                this->{lowerProperty} = value,
                this->_related[lowerProperty] = value,
                this->_dirtyState = self::DIRTY_STATE_TRANSIENT;
            return value;
        }
    }

    ...
}
```

Which basically says: **_If you assign an object to a property than there has to be a relation to handle it**_

Well I didn't have a relation defined in my model. So I added it

```
$this->belongsTo("creator", "User", "id");
```

Unfortunately you still have the same exception.

Why? Because as part of the save() call, close to the end (around line 2906 of model.zep), there is this:

```
...

if typeof related == "array" {
    /**
     * Rollbacks the implicit transaction if the master save has failed
     */
    if success === false {
        writeConnection->rollback(false);
    } else {
        /**
         * Save the post-related records
         */
        let success = this->_postSaveRelatedRecords(writeConnection, related);
    }
}

...
```

and we saw from the previous code, that the variable **related** is initialize by the function **___set**_.
Even this is not the real problem. 

The real problem is that **__postSaveRelatedRecords**_ ignores the **belongTo** relation, but sees a need to save something because **related** is set, therefore the exception.

What are the possible work arounds available?
1. set **creator** using something like $new_user->creator = $creator->id; (the actual id, not an object)
2. Override **__postSaveRelatedRecords**_ to not call the basic class method, in this case and return true.

As a side note, there is actually another option/hack.  Modify User as following:

```
class User extends Model {
   ...
   public $creator
   ...

   public function __toString() {
      return $this->id;
   }
}
```

Why does this work?

Because;
1. **___set**_ function is not called for **public** properties (therefore related is not set)
2. Somewhere in the code that creates the insert, there is a piece of code that says something like let value = (string) value; (which calls __toString() to return the user id).

What do I think should happen?

**__postSaveRelatedRecords**_ should take into account **belongsTo** relations and ignore associated records in **related**.

**Comment by alkana** [comment]
Can you try with this 2 relationships in the initialize function (User model):
```php
$this->hasMany('id', 'User', 'creator', ['alias' => 'users']);
$this->hasOne('creator', 'User', 'id', ['alias' => 'creator']);
```

**Comment by pjacferreira** [comment]
@alkana I'm going to try your idea, and give you some feed back. But unfortunately, I'm in the middle of something, so It will take a little bit before I can get back to you on the results.

**Comment by adam-rocska** [comment]
@pjacferreira That's quite a bit...

**Comment by Jurigag** [comment]
Did i see that your user is in namespace models or what ? then we you defined relation without namespace ?
