### ISSUE TITLE
Create/Save Model with unique index issue

### ISSUE THREAD

**Issue by NicePebkac** [phalcon/cphalcon#11098]
I've been encountering an issues when using unique constraints with MySQL tables (InnoDB).
My environment is Windows x64, VC11 TS. Phalcon 2.0.8.
I've tried using 2 models metadata adapters: 

```
Phalcon\Mvc\Model\Metadata\Memory
Phalcon\Mvc\Model\Metadata\Redis
```

Take this model for example.

``` php
class EmailAddress extends \Phalcon\Mvc\Model{
    public $id;
    public $address;

    public getSource()
    {
        return 'emailAddress';
    }
}
```

and this MySQL table

``` sql
CREATE TABLE `emailAddress` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `address` varchar(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `address_UNIQUE` (`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Executing the following code:

``` php
for($i=1;$i<=2;$i++){
    $email = new EmailAddress();
    $email->address = 'example@email.com';
    $create = $email->create();
    echo sprintf(
        "Attempt #%d\n  EmailAddress created: %s\n  PK: %d\n  Messages: %d\n\n", 
        $i,  
        ($create == true) ? 'True' : 'False', 
        $email->id, 
        count($email->getMessages())
    );
}
```

Outputs:

```
Attempt #1                  
  EmailAddress created: True
  PK: 1
  Messages: 0               

Attempt #2                  
  EmailAddress created: True
  PK: 1
  Messages: 0
```

The same PK. Yet if you review the MySQL queries executed, and execute it yourself, you'll find:
`#1062 - Duplicate entry 'email@address.com' for key 'address_UNIQUE'` occurred for the second query execution.

**Comment by Jurigag** [comment]
But using redis/memory it should be set, i don't know what's it's your issue. For sure there is something more beacause i have similar codes working without problem.

**Comment by dugwood** [comment]
Not missing an `@Unique` on his column? Else I don't know how Phalcon can be aware of the uniqueness of the column in MySQL. Or perhaps it's a new feature in Phalcon 3.x :-)

**Comment by Jurigag** [comment]
No, he is not ussing annotations i think. He is using database strategy są no annotations needed.

**Comment by dugwood** [comment]
As the address field is unique, the PK is obviously the same! I use such strategy to update some records, Model::findFirst() by PK, then Model::save() and it updates an already existing row.

Didn't know about database strategy... Too bad!

**Comment by Jurigag** [comment]
It's the same but it shouldn't be, you can clearly see he is creating two new EmailAddresses

**Comment by dugwood** [comment]
After reading this:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L3182

You can see it's the same behaviour as `save`, except:
`If the instance already exists in the persistence it will throw an exception`

So to me it's because the $email is created again, hence unset() the old one, hence no «old» entry. Maybe try with such a code:
```php
for($i=1;$i<=2;$i++){
    $email[$i] = new EmailAddress();
    // and so on for every $email
```
to see if it's working too.

**Comment by Jurigag** [comment]
No, he doesn't to unset anything, he is creating new object, this code should work properly for sure.

**Comment by dugwood** [comment]
What I pointing out is that by using the same variable `$email` the previous `new EmailAddress()` is unset. So this may not be a bug!
So you have to try it... Or add this to your object, to validate that it's not unset:
```php
function __destruct() {
echo 'I\'ve been destroyed!';
}
```

**Comment by Jurigag** [comment]
There is some problem for sure, when you do two times $email = new EmailAddress() you assign new value. So PK should be other, not the same.

**Comment by dugwood** [comment]
No, you're wrong, if there's no assignation in another global variable, the variable is unset. See for instance:
```php
echo memory_get_usage(), '<br/>';
$a = str_repeat('abc', 1000000);
echo memory_get_usage(), '<br/>';
$a = str_repeat('def', 1000000);
echo memory_get_usage(), '<br/>';
```
returns:
```
2531832
5534224
5534224
```
So first variable `$a` was destroyed, else memory would have doubled, as if you change the second `$a` with a `$b`:
```
2530280
5532672
8535064
```

So please, it doesn't cost much, change the script! Then I'll be okay it's a bug.

**Comment by Jurigag** [comment]
Memory usage is other thing than assigning again value to variable. Memory usage will be the same obviously. Yes it's unset, so it should have **OTHER PK**, not the same.

**Comment by dugwood** [comment]
No, again it's because Phalcon knows that the `address` field is unique, then it finds the same entry! Give it a try :-)

Assigning the variable again destroys it, hence the create() doesn't find the previous record, hence there's no exception, and create() returns `true` because it returns `save()`!

Please DO try another code than the same assignment..

**Comment by Jurigag** [comment]
But address field IS NOT PK HERE. What you are talking about ?!

**Comment by dugwood** [comment]
Please read the database schema:
```sql
UNIQUE KEY `address_UNIQUE` (`address`)
```

Phalcon knows that the address IS unique. Hence it doesn't create another entry because it will run a SELECT on the unique colum.

**Comment by Jurigag** [comment]
**No, it won't RUN select statement on unique column since it's not PK**. You are wrong. End of story, he just posted wrong code or something because i have similar code and it's working fine, i will check it tomorrow to be sure..

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/3.2.x/phalcon/mvc/model.zep#L1026 here - exists is build on PRIMARY KEYS, NOT UNIQUE KEYS.

**Comment by dugwood** [comment]
Last comment is true, I admit :-) So the issue is here:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L3124
=> it changes the `false` into `true` in his code.

So it's not a bug :-)

**Comment by Jurigag** [comment]
Idk, there is for sure problem with his code or phalcon hat PK is 1 in both creates.

**Comment by NicePebkac** [comment]
Yeah, I should have included the "expected behaviour" originally, which would have been:
On the second iteration in the loop, `$email->create()` should be returning false.

There is already a row in the database with that value, which is in a column with a unique constraint.
Phalcon should not be falsely reporting that the object was created, because it is simply not true. You can see it from the PK.

**Comment by dugwood** [comment]
I agree that returning the PK is strange. It should stay with `null` or something like that.

But you're saying that you already have the row in the database (with the same email and PK=1?), hence both `->create()` fail.

`_postSave` does nothing on failure. But the issue is very old, hence we're not looking at the right code :-) In 2015, there wasn't Phalcon 3.x.

So I'm guessing there's no bug anymore...

**Comment by Jurigag** [comment]
No it shouldn't stay null, it should be actual PK from table since it's using last inserted id.

@NicePebkac no, not returning false, in this case expected result is PDOException since you didn't added validator.
