### ISSUE TITLE
Model's find() and findFirst() methods don't return Model instance if columns parameter is set inside these methods.

### ISSUE THREAD

**Issue by SevaJmurov** [phalcon/cphalcon#11096]
Hello,
```php
$myModel = MyModel::findFirst(['conditions' => 'update_id=?1',
                         'bind' => [1 => 12],
                         'hydration' => Resultset::HYDRATE_RECORDS
                         ]);
```
returns MyModel instance with all of it's public props relations and so on, however if I columns parameter is added:
```php
$myModel = MyModel::findFirst(['columns' => 'id,part_number,part_description,price',
                         'conditions' => 'update_id=?1',
                         'bind' => [1 => 12],
                         'hydration' => Resultset::HYDRATE_RECORDS
                         ]);
```
It will never return MyModel instance and will give object(Phalcon\Mvc\Model\Row) or stdClass or Array  depending on hydration settings. Same thing for rows received with find() method.

I think it's not predictable result, especially given that if I'm getting the same resultset(or single row) with raw sql it has MyModel instance.

**Comment by andresgutierrez** [comment]
This is not a bug and this behavior is mentioned in the documentation:

> Return specific columns instead of the full columns in the model. When using this option an incomplete object is returned

https://docs.phalconphp.com/en/latest/reference/models.html#finding-records

**Comment by SevaJmurov** [comment]
Yes, I can see it now.
I'm a way out in the left field with my expectations about resultset row object, however I must mention, I've started with MyModel public properties declared inside a class, which are don't appear in incomplete object with any hydration. e.g.

```php
class MyModel extends BaseModel {
    
   public $customProp1='customValue';
   public $customProp2='customValue';
```

none of this properties appear in anyway in result set if I use find() findFirst() methods with columns param.

Is it also correct behaviour?

**Comment by Jurigag** [comment]
Yes it is if you are not selecting them.
