### ISSUE TITLE
[2.0.8] Wrong property type after save

### ISSUE THREAD

**Issue by ashpumpkin** [phalcon/cphalcon#11091]
``` PHP
<?php
use Phalcon\DI,
    Phalcon\Mvc\Model,
    Phalcon\Db\Adapter\Pdo\MySQL as Connection,
    Phalcon\Mvc\Model\Manager as ModelsManager;


$di = new DI();

$connection = new Connection(array(
    "host"     => "localhost",
    "username" => "root",
    "password" => "12345",
    "dbname"   => "phalcon",
));

$modelsManager = new ModelsManager();
$modelsManager->setDi($di);
$di['db'] = $connection;
$di['modelsManager'] = $modelsManager;
$di['modelsMetadata'] = new Model\MetaData\Memory();

class Robots extends Model
{
    public $id;
}

$di->get('db')->execute('DROP TABLE IF EXISTS robots;');
$di->get('db')->execute('CREATE TABLE `robots` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;');

$robot = new Robots();
$robot->id = 1;
$robot->save();

var_dump($robot->id); // string '1' (length=1)
```

I expected that type of the ID should be int, but it was changed to string by phalcon for some reason. Is it a bug or not?

**Comment by pjacferreira** [comment]
Unfortunately, PHALCON does not work like Symfony (i.e. automatic type casts based on the database column type). 

PHALCON  will treat all database columns values as string, unless you specifically cast them to some other types.

I'm haven't run through this code but what is happening is that, after the INSERT/UPDATE to the database, PHALCON is re-fetching the record, to see if anything else has changed. When it does that, it will get and assign the 'id' as string, since it does not do any typecasting on retrieving values from the database (i.e. everything is a string when fetched).

There is an afterFetch to actual do any conversions, after retrieving the records from the database.
But even that has problems, since it is not called always (i.e. If I remember correctly on initial insert, it does not call afterFetch).

I haven't used this but I think it's also possible to use getter/setters to manage the types of the Model properties (i.e. do a cast on the getter or during a set).

Hope this helps.

**Comment by andresgutierrez** [comment]
PHALCON does cast values if you ask it to do it: https://blog.phalconphp.com/post/phalcon-2-0-4-released

**Comment by ashpumpkin** [comment]
@andresgutierrez I just added \Phalcon\Db::setup(['forceCasting' => true]); to the code above and there is no effect for me. the output is still: string '1' (length=1).

**Comment by andresgutierrez** [comment]
That's not how it works, the value isn't changed by the ORM unless you retrieve it from the database, you also need: \Phalcon\Mvc\Model::setup(['castOnHydrate' => true]);

**Comment by ashpumpkin** [comment]
```PHP
<?php
use Phalcon\DI,
	Phalcon\Mvc\Model,
	Phalcon\Db\Adapter\Pdo\MySQL as Connection,
	Phalcon\Mvc\Model\Manager as ModelsManager;

$di = new DI();

$connection = new Connection(array(
	"host"     => "localhost",
	"username" => "root",
	"password" => "12345",
	"dbname"   => "phalcon",
));

\Phalcon\Db::setup(['forceCasting' => true, 'castOnHydrate' => true]);

$modelsManager = new ModelsManager();
$modelsManager->setDi($di);
$di['db'] = $connection;

$di['modelsManager'] = $modelsManager;
$di['modelsMetadata'] = new Model\MetaData\Memory();

class Robots extends Model
{
	public $id;
}

$di->get('db')->execute('DROP TABLE IF EXISTS robots;');
$di->get('db')->execute('CREATE TABLE `robots` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;');

$robot = new Robots();
$robot->id = 1;
$robot->save();

var_dump($robot->id); // string '1' (length=1)

$robot1 = Robots::findFirst();
var_dump($robot1->id); //  this outputs "int 1" now but every 4th time it shows string '1' (length=1) !!!
```

Maybe I'm doing something wrong?

**Comment by pjacferreira** [comment]
Casting was always a gotcha when I moved over from Symfony. But now I'm just used to it.

I Debugged the problem down to this statement in model.zep (line 2277)

```
let this->{attributeField} = connection->lastInsertId(sequenceName);
```

Like I said, after performing the insert, it reload the 'id' attribute with the string value of '1'.

**Comment by pjacferreira** [comment]
On the other hand hand @ashpumpkin you misread @andresgutierrez post.
The
```
'castOnHydrate' => true
```
Is done on the **Model::setup** and not **Db::setup**

actually looking through the code in db.zep you see that Db::setup only sets globals for **escapeIdentifiers** and **forceCasting** and not **castOnHydrate**

**Comment by ashpumpkin** [comment]
@pjacferreira oh, yes, u are right, I edited my comment above

**Comment by pjacferreira** [comment]
@ashpumpkin I'm not the person to be answering your question about a fix, but in my opinion, you shouldn't count on a fix any time soon, as to me, it seems like a major code rewrite (something global, much like Symfony does it, to guarantee that all column values are cast, always...)

The only easy solution I see to this problem, would be not to do a lastInsertId, if the record already has an ID set.

**Comment by pjacferreira** [comment]
As a side note, 'castOnHydrate' seems to be sufficient to return the result as an int. I also didn't have the problem of "every 4th time it shows string"?

**Comment by ashpumpkin** [comment]
@pjacferreira I got it when set \Phalcon\Db::setup(['forceCasting' => true, 'castOnHydrate' => true]); by a mistake but I can't reproduce that problem anymore
