### ISSUE TITLE
[2.0.7] Redis cache queryKeys bug

### ISSUE THREAD

**Issue by AlexDRiVER** [phalcon/cphalcon#11100]
2.0.7

Function `queryKeys` in Redis cache adapter not find branch keys if not set prefix 

Sorry for my English :/

**Comment by AlexDRiVER** [comment]
bootstrap.php (cache init)
```php
$cache = new \Phalcon\Cache\Backend\Redis(
            new \Phalcon\Cache\Frontend\Data([
                'lifetime' => 3600
            ]), [
                'prefix' => 'prefixName:'
            ]
        );
```

IndexContoller.php (save / get keys cache)
```php
$this->cache->save('data:user:1', [1,2,3], 3600);
$this->cache->save('data:user:2', [1,2,3], 3600);
$this->cache->save('data:user:3', [1,2,3], 3600);
...
$keys = $this->cache->queryKeys('data:user')
```
**$keys** return empty array

if try
```php
$keys = $this->cache->queryKeys('prefixName:data:user')
```
**$keys** return valid array keys, but the keys are prefixed, what is wrong.

**Comment by pantaovay** [comment]
The redis cache backend adds `_PHCR` prefix to every cached key and uses `_PHCR` set to store all the cached keys.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by AlexDRiVER** [comment]
`queryKeys` method return empty array if force is not written prefix.

RU
Метод `queryKeys` возвращает пустой массив если принудительно не указан префикс. Получается странная работа адаптера, где-то как например в `save` и `get` указывать префикс не надо, а в `queryKeys` надо, при этом `queryKeys` возвращает массив содержаший значения с префиксом и например для удаления значения через `delete` приходится вычишать префикс из значений возвращённых `queryKeys`.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/backend/redis.zep#L332
