### ISSUE TITLE
\Phalcon\Mvc\Model - upsert problems

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#11101]
**Table Schema:**

``` sql
CREATE TABLE `profiles` (
  `id` int(11) unsigned NOT NULL DEFAULT '0',
  `name` varchar(255) DEFAULT NULL,
  `status` tinyint(3) unsigned DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Model:**

``` php
namespace App\Models;

class Profile extends \Phalcon\Mvc\Model
{
    public $id;
    public $name;
    public $status;
    public $createDate;
    public $updateDate;

    public function getSource()
    {
        return 'profiles';
    }

    public function columnMap()
    {
        return [
            'id' => 'id',
            'name' => 'name',
            'status' => 'status',
            'create_date' => 'createDate',
            'update_date' => 'updateDate'
        ];
    }

    public function beforeCreate()
    {
        $this->createDate = $this->updateDate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->updateDate = date('Y-m-d H:i:s'); 
    }
}
```

**First Action (CREATE):**

``` php
public function testAction()
{
    $profile = new \App\Models\Profile();
    $profile->id = 1;
    $profile->name = 'Test';
    $profile->status = 1;
    $profile->save();
}
```

![create](https://cloud.githubusercontent.com/assets/163442/11015820/0d4aab74-8576-11e5-91f1-9eb2576013bf.png)

**Second Action (UPDATE)**

``` php
public function testAction()
{
    $profile = new \App\Models\Profile();
    $profile->id = 1;
    $profile->status = 2;
    $profile->save();
}
```

![update](https://cloud.githubusercontent.com/assets/163442/11015838/65ef7b38-8576-11e5-87e9-5ccad5ca7571.png)

`$profile->useDynamicUpdate(true)` not helps to keep unchanged fields. 

`$profile->skipAttributesOnUpdate(['name', 'createDate'])` not respects to column mapping only expected like `$profile->skipAttributesOnUpdate(['name', 'create_date'])`

**Comment by alkana** [comment]
Hello,

can you try to retrieve object like that on the updating part:
`$profile = \App\Models\Profile::findFirst(1); // to retrieve an existing object`

I think phalcon do not load data (only check if the object exists) if you do a "new" and set manually the id.

**Comment by tugrul** [comment]
@alkana thanks for suggestion but this is ugly way because going to be like following everywhere for this logic:

```php
// anti pattern to upsert
$fbUser = \App\Models\Profile::findFirst($fbId);

if (empty($fbUser)) {
    $fbUser = new \App\Models\Profile();
    $fbUser->id = $fbId;
}
// ~ anti pattern to upsert

$fbUser->status = 2;
```

**Comment by xerron** [comment]
https://forum.phalconphp.com/discussion/13695/how-to-upsert-update-or-insert-for-mysql-postgresql-and-sqlite-m

**Comment by Jurigag** [comment]
Phalcon doesn't allow to change primary keys.

**Comment by tugrul** [comment]
I think this problem belongs to framework design. Models should not have functionality like `select` (`Model::find`, `Model::findFirst`), `insert` (`Model::save`), `update` (`Model::save`), `delete` (`Model::delete`) operation.

Models just be contract about exchanging data and structure in business logic. Every SQL operation should be on models manager by model map like `$modelManager->model->find()`, `$modelManager->model->findFirst()`, `$modelManager->model->insert()`, `$modelManager->model->update()`, `$modelManager->model->delete()`, `$modelManager->model->save()`

Models manager should not parse sql and should not integrate structure of table and model. Models manager should generate sql string by model map to models like format string for each operation `insert`, `update`, `delete`, `save`.

Related issue: https://github.com/phalcon/cphalcon/issues/12117

**Comment by Jurigag** [comment]
What you mean not parse sql ? Model managaer is just generating sql. Phalcon just has Active Record pattern, that's why models have this functionnality what you read. If you don't want it then you can use doctrine or something like this.

**Comment by xerron** [comment]
``` php
case 'mysql':
                $sql = 'INSERT INTO config ( collection, name, data ) '
                    . ' VALUES (:collection, :name, :data) '
                    . ' ON DUPLICATE KEY UPDATE '
                    . ' data = VALUES(data);';
                break;
            case 'pgsql':
                $sql = 'INSERT INTO config (collection, name, data) '
                    . 'VALUES (:collection, :name, :data) '
                    . 'ON CONFLICT (collection, name) '
                    . 'DO UPDATE SET data = EXCLUDED.data;';
                break;
            case 'sqlite':
                $sql = 'INSERT OR REPLACE INTO config (collection, name, data) '
                    . 'VALUES (:collection, :name, :data);';
                break;
```

**Comment by tugrul** [comment]
@Jurigag 

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/manager.zep#L1720
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query.zep

**Comment by tugrul** [comment]
I don't like doctrine because too verbose and useless. Phalcon is simple and efficient but can be better than now.

**Comment by Jurigag** [comment]
@tugrul and what's a problem with those links ? I don't quite understand. Manager is generating query object(which is an actual query) which you are executing, exactly what you wrote :).

**Comment by tugrul** [comment]
@Jurigag modelsmanager should not deal seperate ways (active record and phql) and should not resolve models on data binding.

modelsmanager should generate format string by models map and pass format string to formatter state machine. state machine should handle creating instance of model or filling model instance by own state.

this going to be same way and same line in phql and active record. active record going to be part of phql in this approach.

this is different design and different approach by actual implementation and looks like too hard.

I implemented this design in my private framework using PHP and im planning to share when i completed implementation usign hacklang.

**Comment by Jurigag** [comment]
But what you are talking about is just DataMapper. Phalcon is just using Active Record approach, you understand it or not ? We can't like change it because you want to....

**Comment by sergeyklay** [comment]
Phalcon uses [Active Record](https://en.wikipedia.org/wiki/Active_record_pattern), but your question related to a completely different system.  I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
