### ISSUE TITLE
Model has unnecessary select queries in specific case.

### ISSUE THREAD

**Issue by ifsnow** [phalcon/cphalcon#11106]
I'm always grateful for phalcon :)

I wish it would be improved at some future day. Thanks you.

---

For example, robot table has multiple primary keys and auto_increment column.

``` sql
CREATE TABLE `robot` (
    `seq` INT(11) NOT NULL AUTO_INCREMENT,
    `sub_key` INT(11) NOT NULL,
    `name` VARCHAR(100) NULL DEFAULT NULL,
    PRIMARY KEY (`seq`, `sub_key`)
);
```

create() function generates 3 quries. I think 2 select quires are unnecessary in this case.

``` php
$robot = new Robot();
$robot->sub_key = 1;
$robot->name = "Robot 1";
$robot->create();
```

``` sql
call _exists() function of create() function.
SELECT COUNT(*) "rowcount" FROM `robot` WHERE `seq` = NULL AND `sub_key` = 1;

call _exists() function of save() function.
SELECT COUNT(*) "rowcount" FROM `robot` WHERE `seq` = NULL AND `sub_key` = 1;

INSERT INTO...
```

Parameters are checked about null already. but, It needs more consideration.

If type of filed is AUTO_INCREMENT(or NOT NULL) and value is null, I think _exists() function should return false.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
