### ISSUE TITLE
date_field Not Working on Firefox

### ISSUE THREAD

**Issue by SoccerField24x7** [phalcon/cphalcon#11119]
Using Phalcon 2.0.8, when creating a date_field() in volt, the datepicker does not show for Firefox.  All other browsers show the arrows, which launch the picker.

    <label>Date of Climb: </label> {{ date_field("climbdate", "class":"form-control", "placeholder":"Click for Calendar") }}

**Comment by andresgutierrez** [comment]
What HTML is being generated? Does firefox support that HTML?

**Comment by SoccerField24x7** [comment]
<label>Date of Climb: </label> <input type="date" id="climbdate" name="climbdate" class="form-control" placeholder="Click for Calendar" />

Given that the picker doesn't work, I'm guessing Firefox doesn't support it.  I am just reporting that it doesn't work for me, you can decide if you want it to.  :)

**Comment by phalcon** [comment]
Not sure how we can make it work, maybe we have to wait for Mozilla to work into it
