### ISSUE TITLE
Multiple Field Validator

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11126]
How about add option for PresenceOf(and others valdidators) to accepting arrays like this way:

```php
$validator = new Validation();
$validator->add(['field1','field2','field3','field4'],new PresenceOf([
    'message'=>[
        'field1'=>'message for field1',
        'field2'=>'message for field2',
        'field3'=>'message for field3',
        'field4'=>'message for field4',
]]);
```

I already have this as a custom validator(but in old validation using $this->validate method). But i would love to use built-in option.

**Comment by sergeyklay** [comment]
Fixed in the `2.1.x` branch.
