### ISSUE TITLE
Phalcon PHP 2.0.8 uses PHP5.4 methods

### ISSUE THREAD

**Issue by devaddiction** [phalcon/cphalcon#11129]
Phalcon PHP 2.0.8 session Adapter now uses methods that were introduced in PHP5.4, like session_status().

This update makes Phalcon PHP 2.0.8 unsupported for PHP 5.3.

Zephir source code seems that checks the PHP version but actually it doesn't work.

```php
	/**
	 * Returns the status of the current session. For PHP 5.3 this function will always return SESSION_NONE
	 *
	 *<code>
	 *	var_dump($session->status());
	 *
	 *  // PHP 5.4 and above will give meaningful messages, 5.3 gets SESSION_NONE always
	 *  if ($session->status() !== $session::SESSION_ACTIVE) {
	 *      $session->start();
	 *  }
	 *</code>
	 */
	public function status() -> int
	{
		var status;

		if !is_php_version("5.3") {
			let status = session_status();

			switch status {
				case PHP_SESSION_DISABLED:
					return self::SESSION_DISABLED;

				case PHP_SESSION_ACTIVE:
					return self::SESSION_ACTIVE;
			}
		}

		return self::SESSION_NONE;
	}

```

**Comment by andresgutierrez** [comment]
Can you try again compiling from the 2.0.x branch?

**Comment by devaddiction** [comment]
Hello @andresgutierrez. I installed the package from the ppa, precise distribution

**Comment by rianorie** [comment]
@devaddiction those tend to lag behind a bit, you'd be better off compiling from the repository in this case

**Comment by devaddiction** [comment]
@rianorie thanks for your advise. I already patch it but I thought it was great if the community fix it for the rest of the world

**Comment by devaddiction** [comment]
Hello @andresgutierrez so this has been already fixed in the next version? Thanks!

**Comment by sergeyklay** [comment]
I'll try to deal today

**Comment by sergeyklay** [comment]
@devaddiction I tried to download PHP 5.3 from museum http://museum.php.net/php5/php-5.3.29.tar.bz2 and compile it locally but unfortunately I am not able to satisfy all dependencies of that version (even considering phpenv, phpbrew, etc.) 

So you have to run [this test](https://github.com/phalcon/cphalcon/pull/11238/files) manually, after I merge it with the 2.0.x branch:

```sh
$ php unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml --testsuite=stable \
  unit-tests/SessionTest.php
```

**Comment by sergeyklay** [comment]
@devaddiction

**Comment by devaddiction** [comment]
Hello @sergeyklay 

I've run the test but no luck. It fails trying to assert the sessionStart here:

```php
1) SessionTest::testSessionFiles
Failed asserting that true is false.
```

Thanks for your help. Regards,

**Comment by sergeyklay** [comment]
Hm...

Can you please create separated test class with [setUp](https://github.com/sergeyklay/cphalcon/blob/e2065f3ad4454087afa4d872065957f858e45ae5/unit-tests/SessionTest.php#L26-L35), [tearDown](https://github.com/sergeyklay/cphalcon/blob/e2065f3ad4454087afa4d872065957f858e45ae5/unit-tests/SessionTest.php#L37-L45) and [testSessionFilesWrite](https://github.com/sergeyklay/cphalcon/blob/e2065f3ad4454087afa4d872065957f858e45ae5/unit-tests/SessionTest.php#L72-L130) and run test?

**Comment by devaddiction** [comment]
Hello @sergeyklay 

Thanks for your response. I've tried to isolate the method that you mentioned and now works:

```php
vagrant@local:/var/www/supu/cphalcon$ php unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml --testsuite=stable   unit-tests/SessionSupuTest.php
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /var/www/supu/cphalcon/unit-tests/phpunit.xml


Starting test 'SessionSupuTest::testSessionFilesWrite'.
.
Starting test 'SessionSupuTest::testSessionFilesWriteMagicMethods'.
.

Time: 821 ms, Memory: 6.00Mb

OK (2 tests, 19 assertions)
```

Thanks!

**Comment by sergeyklay** [comment]
So, all ok? :)

**Comment by devaddiction** [comment]
Yes! Seems that works. Thanks :)
