### ISSUE TITLE
[2.0.8] Logger Interface

### ISSUE THREAD

**Issue by Infolegale** [phalcon/cphalcon#11130]
Hi,

Phalcon is a good framework, really good but, in order to extend and use properly the framework, but I think a logger interface is missing...

It comes to be really difficult to work with Logger\Multiple because it has no relation to Logger\Adapter even if the implements the same behavior regarding logging.

```php
<?php
class Foo {
  protected $logger;
  public function setLogger($logger)
  {
    if($logger instanceof \Phalcon\Logger\Adapter|| $logger instanceof \Phalcon\Logger\Multiple) {
      $this->logger = $logger;
    }
  }
}
```
AdapterInterface (implemented in Adapter only) should be splitted in 2 interfaces : AdapterInterface and LoggerInterface, as Adapter and Multiple shares common methodes (log, debug, info, etc)

Then above code would be :

```php
<?php
class Foo {
  protected $logger;
  public function setLogger(\Phalcon\Logger\LoggerInterface $logger)
  {
    $this->logger = $logger;
  }
}
```

**Comment by sergeyklay** [comment]
This BC breaks and should be implemented in major version e.g `2.1.x`.

**Comment by sergeyklay** [comment]
Related to https://github.com/phalcon/cphalcon/issues/11168
