### ISSUE TITLE
Phalcon support php7?

### ISSUE THREAD

**Issue by phecho** [phalcon/cphalcon#11137]
PHP 7.0.0 RC 6 Released, This is the eleventh pre-release of the new PHP 7 major series.

**Comment by williamokano** [comment]
There's an open thread about this.

Initially Phalcon will not support PHP 7 since Zaephir still don't support PHP 7 too.

It's just a matter of time.

**Comment by tobasar** [comment]
@phecho please search before asking this question. It has been asked many times. You can also use https://forum.phalconphp.com/ for a question.
