### ISSUE TITLE
ResultSet\Simple delete method returns true when a constraint violation occurs if the model has a virtual FK defined

### ISSUE THREAD

**Issue by GavinMcL** [phalcon/cphalcon#11133]
Using Robots demo as the example;

If I have a Robots model, which is related to a Parts model via RobotsParts, and Robots has this relationship map;

``` php
$this->hasMany('id', 'RobotsParts', 'robots_id', ['alias' => 'RobotsParts']);
```

if I do 

``` php
$robots = Robots::find();
$robots->delete();
```

I correctly get a PDOException

``` sql
PDOException: SQLSTATE[23000]: Integrity constraint violation: 
1451 Cannot delete or update a parent row: a foreign key constraint fails (`robots`.`robots_parts`, CONSTRAINT `robots_parts_ibfk_1` FOREIGN KEY (`robots_id`) REFERENCES `robots` (`id`))
```

**however**
if I alter the Robots relationship map to define a virtual foreign key with a friendlier message, eg

``` php
$this->hasMany('id', 'RobotsParts', 'robots_id', [
    'alias' => 'RobotsParts', 
    'foreignKey' => ['message' => 'robot is associated to a part']
]);
```

then re-run

``` php
$robots = Robots::find();
$robots->delete();
```

$robots->delete() returns true, even though $robots->getMessages() has the FK message I defined.  The actual database records are still correctly in place.

I would expect $robots->delete() to return false if any of the contained records fail to delete, in the same way as calling

``` php
$robot = Robots::findFirst();
$robot->delete();
```

will return false with the same FK violation.

**Comment by GavinMcL** [comment]
I've created 2 files in gist which demonstrate the behaviour I'm getting.

https://gist.github.com/GavinMcL/4d58e9ee2182ede3a7da

**Comment by Jurigag** [comment]
What happens if you add , 'foreignKey' => true also in RobotsParts relations ? Also try maybe to add it like this:

'foreignKey' => ['message'=>'test message','action'=>Relation::NO_ACTION(it should be already be default)]

**Comment by GavinMcL** [comment]
Hi sorry for the delay in responding, got diverted onto different project.

I've added foreignKey into RobotsParts, makes no difference

Adding foreignKey with a message makes no difference, but at least shows it is the fk in the Robots class that is being triggered

Adding 'action'=>Relation::NO_ACTION seems to have the same effect as NOT declaring the relations with foreignKey - the original behaviour happens where the underlying PDO Exception is thrown, which is what I was trying avoid in the first place.
