### ISSUE TITLE
ADR implementation (Feature Request)

### ISSUE THREAD

**Issue by jamesdobb** [phalcon/cphalcon#11140]
I'm implementing ADR using Phalcon in favor of MVC.  It's working well and is entirely possible with Phalcon, however, I have noticed a couple of implementations in the framework which could be considered for alteration to better support a technique that does not follow MVC.  
To Explain this I would like use 2 concepts: Routing and Dispatching.  

In Phalcon, we have access to a Base Dispatcher (\Phalcon\Dispatcher) and an MVC Disptcher (\Phalcon\Mvc\Dispatcher).  However, the Base Dispatcher uses a couple of method names that appear to follow the MVC structure, even though this class supposedly isn't designed with MVC in particular in mind.  The term 'Action' is used to refer to the method being executed.  In the world of ADR this can open us up to some confusion as the 'Action' is the class, not the method as it is referred to in MVC!

Routing has been isolated completely within the \Phalcon\Mvc namespace without a router available at \Phalcon\Router.  I have of course been able to use the MVC version with some adaptions but an abstract version might be a nice idea.

Essentially, without too many issues I have ADR working well, however I hope this describes useful food for thought.

Well done everyone, I'm loving both Zephir and the Phalcon framework!

**Comment by Jurigag** [comment]
Well if you will finish it(don't know if you are doing it in plain php or zephir). Then create proper PR with it.
