### ISSUE TITLE
PHQL - post order

### ISSUE THREAD

**Issue by urgotto** [phalcon/cphalcon#11149]
Hi, I have situation when i need execute query like:
```MYSQL
SELECT * FROM (SELECT SomeField, OtherField FROM SomePhalconModel WHERE OtherField LIKE('%some bla bla bla%') ORDER BY SomeOtherField111 Limit 0, 100500) as SubQuery ORDER BY SomeField
```
I read a lot of documentation and forums, and can`t find anything.
Can i do it by using PHQL? What do you do in this situation usually?

**Comment by andresgutierrez** [comment]
This syntax is currently not supported by PHQL, you can use raw queries: https://docs.phalconphp.com/en/latest/reference/phql.html#using-raw-sql

**Comment by urgotto** [comment]
Thx for answer.
