### ISSUE TITLE
Any plan about support PHP MongoDB Driver?

### ISSUE THREAD

**Issue by gai00** [phalcon/cphalcon#11156]
PHP PECL "mongo" is deprecated.
Ref: http://php.net/manual/en/book.mongo.php

The newer extension is PECL "mongodb"
Ref: http://php.net/manual/en/set.mongodb.php

Interfaces has huge differences.

**Comment by sergeyklay** [comment]
In general it is necessary to conduct laborious of refactoring. You'd be able to do it? :)

**Comment by virgofx** [comment]
+1

**Comment by gai00** [comment]
I don't think I can do that...Orz

hope it can be made by someone.

**Comment by fizzka** [comment]
+1
interface has _minor_ differences

**Comment by sergeyklay** [comment]
@fizzka Can you please do PR?

**Comment by fizzka** [comment]
sorry, but I don't think I can do smtng good in zep =)

2015-12-13 2:07 GMT+03:00 Serghei Iakovlev <notifications@github.com>:

**Comment by Ajibola** [comment]
+1

**Comment by memmaker** [comment]
+1

**Comment by Evgeny-** [comment]
+1

**Comment by ddonng** [comment]
Hope +1

**Comment by ulfims** [comment]
If i'm intersted to implement new driver, how can I do?

**Comment by ulfims** [comment]
Or someone already did this?

**Comment by sergeyklay** [comment]
I offer to do it first for Incubator. We will be able to evaluate his work and usefulness. Will be able to test and see thin places. Then we can port it to the Phalcon Core

**Comment by tigerstrikemedia** [comment]
Im happy to look at putting in some time to this. Has anyone made a start anywhere?

**Comment by sergeyklay** [comment]
@tigerstrikemedia It seems to me nobody

**Comment by tigerstrikemedia** [comment]
@sergeyklay looks like it's from scratch then ;)

**Comment by tigerstrikemedia** [comment]
@sergeyklay 

This is deeper than I thought. 

What sort of performance gains are we talking to essentially build a trimmed down version of the [mongo PHP library](https://github.com/mongodb/mongo-php-library/) eventually ported into zephir? 

Short of requiring that library which seems quite out of line with the phalcon system, that is what would be required to support the new MongoDB extension in the ODM system of phalcon.

perhaps It would even be better at that stage to start on a full DB Adapter for MongoDB, it would seem that the majority of that sort of functionality is what mongo decided to strip out of the PHP extension.

**Comment by sergeyklay** [comment]
> This is deeper than I thought.

Yeah, indeed.
But as @fizzka said
> interface has _minor_ differences

;)

It seems to me, we have to use current stable Mongodb API. This is really important. Of course, it's actually more complicated than it seems at first glance. But due to the fact that Phalcon is PHP extension it make sense. And yes, implementation of this feature implies compliance current Phalcon API and BC

**Comment by tigerstrikemedia** [comment]
@sergeyklay 

Interface has minor differences, but pulling that interface into phalcon requires recreating the wheel as that is what mongo split out to a PHP library rather than keeping it in the extension. Seems a bit like fighting the tide to me, but I think that Phalcon has been a bit like that the whole way along.

Ill pull what will essentially be a copy of the Mongo PHP library into a MongoDB Adapter in the incubator tonight / tomorrow and try to get a model adapter running from that.

Does that make sense?

**Comment by tigerstrikemedia** [comment]
Just added a pull request to the incubator.

https://github.com/phalcon/incubator/pull/625

**Comment by tigerstrikemedia** [comment]
@sergeyklay

The travis builds are failing from code styling issues do you know of anywhere I can get a PHPStorm code style config for this?

**Comment by duythien** [comment]
@tigerstrikemedia Because Phalcon incubator use PSR2 styles, so you can use this library to fix your styles code

```
curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
php phpcbf.phar --standard=PSR2  Library/Phalcon/Db/Adapter/MongoDB
```
```

**Comment by tigerstrikemedia** [comment]
or a PHPCS configuration

**Comment by tigerstrikemedia** [comment]
@duythien Cheers mate, running tests on that now ;)

**Comment by tigerstrikemedia** [comment]
Now failing due to function names not in camel case, Im not sure if I should change them or not.

The functions in the Functions class I migrated from being global functions in the \mongoDB namespace. they are used through-ought the adapter, but the stream wrapper functions aren't.

**Comment by tigerstrikemedia** [comment]
Now failing due to function names not in camel case, Im not sure if I should change them or not.

The functions in the Functions class I migrated from being global functions in the \mongoDB namespace. they are used through-ought the adapter, but the stream wrapper functions aren't.

**Comment by tigerstrikemedia** [comment]
We now have a very early version of the adapter (Phalcon\DB\Adapter\MongoDB) and collection (Phalcon\Mvc\MongoCollection) in the [2.1 branch of the incubator](https://github.com/phalcon/incubator/tree/2.1.x) anyone who wants to test and let me know what breaks i'd be happy to work through any issues.

**Comment by ohmcoe** [comment]
+1

Hope for PHP7.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Db/Adapter

**Comment by belgrid** [comment]
+1

**Comment by Jurigag** [comment]
It's already implemnted in incubator.

**Comment by belgrid** [comment]
+1

**Comment by Jurigag** [comment]
@belgrid it's already implemented in incubator.

**Comment by afbora** [comment]
+1

**Comment by cmeheut** [comment]
for Mongo <= 3.5 we can use an adapter (I use https://github.com/alcaeus/mongo-php-adapter)
But it's not working anymore for 3.6: The 'cursor' option is required, except for aggregate with the explain argument
It seems that using the new PHP lib would be the best way

**Comment by Jurigag** [comment]
@cmeheut there is adapter in incubator already, not sure which exactly mongo versions it support.

**Comment by simpleadm** [comment]
+1

**Comment by DmytroDiachuk** [comment]
+1 
I believe in it ;)

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by fizzka** [comment]
hi guys
what about https://github.com/alcaeus/mongo-php-adapter ?
it looks easy to say "install this, while we reinventing new solution for new driver"?
any thoughts?

**Comment by niden** [comment]
@fizzka There is already work underway by one of the members of the community to port the latest Mongo driver to the `Collection` class. That is one of the last issues we have in our v4 project

https://github.com/phalcon/cphalcon/projects/3

**Comment by Jeckerson** [comment]
Implemented as separate package - https://github.com/phalcon/incubator-mongodb
