### ISSUE TITLE
\Phalcon\Mvc\Model\MetaData does not implement Phalcon\Mvc\Model\MetaDataInterface

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#11152]
The abstract class doesn't extend the interface but instead the actual adapters do. Is this by design? Since the abstract `MetaData` adapter handles the core implemented methods shouldn't this implement the interface such that all adapters only need to extend MetaData?

**Comment by virgofx** [comment]
Thanks @sergeyklay

**Comment by virgofx** [comment]
Reopenening, until merged.

**Comment by sergeyklay** [comment]
Fixed in `2.0.x`
