### ISSUE TITLE
Query Builder Issues (dots in columns name, resultset problems)

### ISSUE THREAD

**Issue by bluetec** [phalcon/cphalcon#11153]
Hi, I have some issues with Phalcon query builder, issues are critical and I've tried many times to find a logical solution for them, but nothing.
### First Issue

_I think this is a bug! however..._

I want get a column name like `title` as `foo.title`,  look at sample code:

``` php
$options = ['...'];
$builder = $this->modelsManager->createBuilder();
$builder->from(['aircrafts' => 'App\Models\Aircrafts']);
$modelAlias = 'aircrafts';
$columns = [];
if($options['columns']) {
    foreach( $options['columns'] as $column ){
        columns[] = $column . ' as `' . $modelAlias . '.' . $column . '`';
    }
}

# sample query
# SELECT id as `aircrafts.id`, title as `aircrafts.title` FROM ...
```

Ok, as you know in mysql this query is valid, but seems phalcon does not offer any way to do this.

**Backticks (`) in phalcon query builder cause query scan error, how could use dot (.) in phalcon columns name?**
### Second Issue

_Query builder resultset issue_

Sample code:

``` php
$builder = $this->modelsManager->createBuilder();
$builder->from(['seatmap' => 'App\Models\SeatMaps']);
$builder->join('App\Models\Aircrafts', null, 'aircrafts');
$builder->join('App\Models\Airlines', 'aircraft.airline = airline.id', 'airline');
// Set columns
$builder->columns('seatmap.*, aircrafts.*, airline.title');
// ...Execute Query...
```

query result will be something like:

```
    // Complex Resultset   
    [
        'seatmaps' => {
            'id': '...',
            'title' : '...',
            // ..
        },
        'aircrafts' => {
            'id': '...',
            'title' : '...',
            // ...
        },
        'title' => '...' // this is airline title
    ]
```

as you see, in this case I need `title` column from airlines table and all columns from seatmaps `(seatmaps.*)` and aircrafts `(aircrafts.*)` models. how its possible to get data in following format:

```
    // Complex Resultset   
    [
        'seatmap' => {
            'id': '...',
            'title' : '...',
            //...
        },
        'aircrafts' => {
            'id': '...',
            'title' : '...',
            //...
        },
        // title belongs to airlines, so i want it be a child of airlines object
        'airlines' => {
            'title' => '...'
        }
    ]
```

how can I do this, fetch all columns in their related object in query builder resultset?

**Comment by Jurigag** [comment]
But this:

'airlines' => {
            'title' => '...'
        }

Is not true ! Cuz airlines dont contain only title, thats why when you select only airline.title only title appears in result. Its not a bug, it is how its supposed to be and work. Its just better and more consistent.

**Comment by bluetec** [comment]
@jurigag no, please read entire article, I wrote two different issues.

for second issue:
>'airlines' => {
>'title' => '...'
>}

I described and I know this is default behavior and it's OK, but how it's possible to force query builder to return all results in object style?

**Comment by Jurigag** [comment]
There is no way to force it cuz it will be wrong.

**Comment by andresgutierrez** [comment]
` backticks are supported but you can use [ ] https://docs.phalconphp.com/en/latest/reference/phql.html#escaping-reserved-words

**Comment by bluetec** [comment]
@andresgutierrez 
Please Let me know, how to execute this SQL statement with query builder?
```sql
SELECT posts.title as `post.title`, posts.createdAt as `post.date`, user.name as `author.name` FROM posts LEFT JOIN `users` user ON posts.user = user.id
```


I try with this query builder, but i got errors on columns aliases  that including ".";
```php
$builder = $this->modelsManager->createBuilder();
$builder->from(['post' => 'Posts'])
            ->leftJoin('Users', 'post.user = user.id, 'user')
            ->columns('posts.title as `post.title`, posts.createdAt as `post.date`, user.name as `author.name`')
           ->getQuery()->execute();


// or using []; produce errors
// ->columns('posts.title as [post.title], posts.createdAt as [post.date], user.name as [author.name]');

```

**Comment by sergeyklay** [comment]
```php
$this
    ->modelsManager
    ->createBuilder()
    ->from(['post' => 'Posts'])
    ->leftJoin('Users', 'post.user = user.id', 'user')
     ->columns([
        'posts.title as post_title',
        'posts.createdAt as post_date',
        'user.name as author_name'
    ])
    ->getQuery()
    ->execute();
```

**Comment by bluetec** [comment]
@sergeyklay 
underscores is a alternate but in this case I should use an extra loop to rename post_title to post.title.
MySQL allow to use "." in columns name  but PHQL produce scan error.
