### ISSUE TITLE
Micro app and 404 response code

### ISSUE THREAD

**Issue by mruz** [phalcon/cphalcon#11158]
Tools like https://varvy.com/tools and http://www.seoptimer.com for the micro app (eg. https://store.phalconphp.com) returns:

> This URL has HTTP 404! This is very bad for SEO. Analysis can not be performed.
```
HTTP/1.1 404 Not Found
```

**Comment by thiagolcks** [comment]
Maybe they are using curl to get the data, at least I had that problem. I've fixed it adding:

```php
$app->getRouter()->setUriSource(\Phalcon\Mvc\Router::URI_SOURCE_SERVER_REQUEST_URI);
```

Source:
https://forum.phalconphp.com/discussion/4527/phalcon-rest-api-problem

**Comment by dzubchik** [comment]
@mruz , I have checked it by curl and wget tools - got 200 and response. @sergeyklay?
