### ISSUE TITLE
Is $app bound to function closure in micro framework ?

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11154]
In 2.1.0 in beta $di is bound to function closures when adding service to it, so we can just use $this in function closure to access di. Can you add the same behaviour for micro framework or is it already added in master branch ?

Well as i see in some code example in 2.1 beta:

```php
use Phalcon\Mvc\Micro;

$app = new Micro();

// ...

$app->get(
    '/hello/{name}',
    function () {
        return $this->view->render(
            'hello',
            [
                'name' => $name,
            ]
        );
    }
);
```

So i guess its already working like this ? That you can access $app as $this ?

**Comment by andresgutierrez** [comment]
It already does that: https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/micro.zep#L695-L697
