### ISSUE TITLE
$config->foo->toArray() error when key foo does't exist

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#11157]
```
// current behaviour
$config->foo; // null, since config key 'foo' doesn't exist
$config->foo->toArray(); // error
```

The correct behaviour would be to return an empty object so that `toArray()` still works or discourage use of `toArray` in favour of boxing via `(array)$config->foo`.

**Comment by ashpumpkin** [comment]
I think this behaviour is correct. How do we solve the situation when we really need foo be equal to null? And more than that: if someone will do that fix, it will break BC because there are projects for sure that use checks like this:
```PHP
if ($config->foo->bar === null) {/* some actions */}

**Comment by aleemb** [comment]
```
if ($config->foo->bar === null) {/* some actions */}
```

This example actually highlights a second problem which is the API is ambiguous. It returns null if the key doesn't exist. It also returns null if the key exists and it's value is set to null. Not sure if that's desirable.

Even so, the problem remains that `$config->foo->toArray()` will randomly litter your log/screen with errors.

Better still, could you provide an example of would write out `$config->foo->bar->toArray()` without potentially error'ing out if `foo` or `bar` don't exist? That might illustrate the problem better.

**Comment by rianorie** [comment]
You are trying to access properties that don't exist.. that is never going to work. Saying you should be able to call `toArray()` would effectively make this possible: `$config->my->endless->chain->of->config->values->toArray()` .. and that's just nuts.

You can't call methods on a non-object, that's entirely correct, native PHP, behavior.

**Comment by sergeyklay** [comment]
Safely call methods in ruby
```ruby
a = one.try(:two).try(:three).try(:four)

# another example
report = params[:query_type]
.try { |qt| build_query(qt) }
.try { |sql| run_query(sql) }
.try { |res| format_result(res) }
```

:)

**Comment by aleemb** [comment]
@rianorie I am not so sure if that applies here. Just like writing `$arr['foo']` is brittle so is writing `$config->foo->bar->toArray()`. It's fairly easy to fix the former using `array_key_exists`. For the latter, it's a lot more cumbersome if you are accessing nested properties.

You are better of writing `(array)$config->foo->bar` then writing `$config->foo->bar->toArray()` as the former is much more reliable while the latter is brittle. Just like you would for arrays, which is ultimately how the config is defined as--a nested array.

**Comment by rianorie** [comment]
@aleemb isn't this what `isset` is for?  `isset($config->foo)`, `isset($config->foo->bar)`.. I'm still not getting it. Executing methods on a non-object makes no sense to me, `null` should be `null` and not an instance of a config object to be able to be turned into an array.

To add, you might try using `$config->get('foo')` though that will also return `null` if foo doesn't exist. However I think `$config->get('foo', new \Phalcon\Config([]))` will return an empty config object that you can then chain into toArray(). That array will then be empty though.

**Comment by aleemb** [comment]
@rianorie that's right `isset` or `(array)` will both remedy this.  However, I am of the opinion that a more considerate API design for `toArray()` could consider returning `[]` instead of `null` so the user doesn't have to do an `isset` check. Incidentally, a lot of the discussion on the topic uses the same reasoning:

> DO NOT return null values from collection properties or from methods returning collections. Return an empty collection or an empty array instead. https://msdn.microsoft.com/en-us/library/dn169389(v=vs.110).aspx

However, [Eric Lippert](http://blogs.msdn.com/b/ericlippert/archive/2009/05/14/null-is-not-empty.aspx) does suggest returning `null` when the semantics are `unknown` or `missing` and supports your argument.

Thanks for listening, didn't mean to bike-shed on the issue.

**Comment by rianorie** [comment]
@aleemb it's quite alright, I said I don't get it and I still don't entirely ;) But perhaps it's a perception issue, I've never seen the Config as a collection as described on MSDN, more like a value object (which it obviously isn't.). For me it's existing behavior is correct because I'd never iterate over the config values it might return, I'd only load them singularly and in pre-defined settings. I know what config values will be available.
