### ISSUE TITLE
Nginx url rewriting

### ISSUE THREAD

**Issue by Levano** [phalcon/cphalcon#11160]
Hi,

I tried to configure nginx to use Phalcon. When I try to acces i got an "Access denied" or a 404.
Here is my nginx vhost configuration:

server {
	listen 80 default_server;
	listen [::]:80 default_server;

    	root /var/www/esaf/public;

    	try_files $uri $uri/ @rewrite;

    	location @rewrite {
        	rewrite ^(.*)$ /index.php?_url=$1;
    	}

	# Add index.php to the list if you are using PHP
	index index.php index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
	#
	location ~ \.php$ {
	#	include snippets/fastcgi-php.conf;
	#
	#	# With php5-cgi alone:
	#	fastcgi_pass 127.0.0.1:9000;
	#	# With php5-fpm:
		fastcgi_pass unix:/var/run/php5-fpm.sock;
       		fastcgi_index /index.php;

        	include /etc/nginx/fastcgi_params;

        	fastcgi_split_path_info       ^(.+\.php)(/.+)$;
        	fastcgi_param PATH_INFO       $fastcgi_path_info;
        	fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  
	}

    	location ~* ^/(css|img|js|flv|swf|download)/(.+)$ {
        	root /var/www/esaf/public;
    	}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	location ~ /\.ht {
		deny all;
	}
}

 Thanks for helping

**Comment by rianorie** [comment]
here's he one I use, that works:

```
server {
    listen 80;
    server_name "rianorie.localhost";

    error_log /var/log/nginx/error.log;
    rewrite_log on;

    root /home/rian/Sites/rianorie/public;

    index index.php index.html;
    try_files $uri $uri/ @rewrite;

    location @rewrite {
        rewrite ^/(.*)$ /index.php?_url=/$1;
    }

    location ~ .php$ {

        expires off;
        fastcgi_pass unix:///var/run/php5-fpm.sock;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_split_path_info       ^(.+\.php)(/.+)$;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
                                                                                                                                                                                                                             
    location ~ /\.ht {                                                                                                                                                                                                       
        deny all;                                                                                                                                                                                                            
    } 
}
```
Obviously you will need to adjust this accordingly.

**Comment by dzubchik** [comment]
@Levano , please refer to documentation https://docs.phalconphp.com/en/latest/reference/nginx.html. @sergeyklay , maybe this should be closed?

**Comment by olekus2** [comment]
> @Levano , please refer to documentation https://docs.phalconphp.com/en/latest/reference/nginx.html. @sergeyklay , maybe this should be closed?

i tried nginx conf from phalcon docs. it doesnt work.
