### ISSUE TITLE
Memory leak in findFirst ORM function

### ISSUE THREAD

**Issue by KrisvanWaterschoot** [phalcon/cphalcon#11163]
When running a process (or an infinite while loop) and using the function 'findFirst' in this loop, the memory of the script is increasing dramatically until it runs out of memory. This prevents Phalcon to be used in PHP processes!

This issue may also occur when using other ORM Phalcon functions, but I have not tested that yet.

Can this be fixed in future version? Or can you provided a temporary workaround until this is fixed?

**Comment by KrisvanWaterschoot** [comment]
Hi, here's the script:

while(true) {
        ModelName::findFirst();
}

**Comment by sergeyklay** [comment]
Duplicated #2705, #3175
