### ISSUE TITLE
columnMap does not work

### ISSUE THREAD

**Issue by Dansf** [phalcon/cphalcon#11166]
in phalcon 2.0.8 column does not work.
me code is:
//Use diffrent column names
    public function columnMap()
    {
        return array (
            'mem_firstname' => 'firstname',
            'mem_lastname' => 'lastname',
            'mem_mobno' => 'mobileno',
            'mem_telno3' => 'telephone',
            'mem_email' => 'email'
        );
    }

**Comment by Jurigag** [comment]
Its working for me, show us your properties and database schema.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
