### ISSUE TITLE
Config variable Bug - i cant merge or use several config files with same variable names e.g $config both config.php   and in main index.php file

### ISSUE THREAD

**Issue by vymc** [phalcon/cphalcon#11175]
Phalcon version 2.1.0b
Hello, i cant merge several config files with same variable name e.g $config in main  index.php file

```
#A.config.php
$config = [];
$config['x'] = 'x';
return $config;
```

```
#B.config.php
$config = [];
$config['x'] = 'y';
return $config;
```

//same variables ->>>>  $config
$config = new Phalcon\Config(require  'A.config.php');
$config2 = new Phalcon\Config(require  'B.config.php');

print_r($config,$config2);

```
<pre>Array 
(
    [x] => y
)
</pre><pre>Phalcon\Config Object
(
    [x] => y
)
</pre>
```

NOW merging and getting FATAL ERROR
$config = new Phalcon\Config(require  'A.config.php');
$config2 = new Phalcon\Config(require  'B.config.php');
$config->merge($config2);// Fatal error: Call to a member function merge() on array in

```
//AND LAST NOW OK
```

$configXXXXX = new Phalcon\Config(require  'A.config.php');
$configYYYYYY = new Phalcon\Config(require  'B.config.php');
$configXXXXX ->merge($configYYYYYY );//NOW OK

```
sry, my english.... :)
```

**Comment by vymc** [comment]
Appending bug ;(

config file .php 
```
$config['x']  = 'x';
return $config;
```
Fatal error: Uncaught exception 'Exception' with message 'The argument is not initialized or iterable()' in phalcon/config.zep on line 62

and NOW  OK
```
$config = []; /// defining a type
$config['x']  = 'x';
return $config;
```

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. And it seems to me it maybe fixed 
in later versions.  I'll open it again if the need arises.
