### ISSUE TITLE
[2.1.x] Inconsistency with Model::assign() when Creating new Model Instances with Array Data

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#11171]
> The following issue is specific to 2.1.x which introduced the ability to create a new `Model()` instance with an array of instance field/value data.

Creating new Model instances with array data can result in data being transformed twice because `Model::assign()` will use internal setters.

This is a common issue when using snapshots or dynamic updates.

For example:

``` php
<?php

class Robot extends \Phalcon\Mvc\Model {

    public $specialField;

    public function initialize() {
        $this->useDynamicUpdate(true);
    }

    public setSpecialField($rawValue) {
       $this->specialField = $rawValue . '-transformed';
    }
}
```

``` php
$robot = new Robot();
$robot->setSpecialField('raw');

// Snapshot data contains the resulting transformed data. 
// $snapshot['specialField'] = 'raw-transformed';
$snapshot = $robot->getSnapshotData();

// Assume, the application needs to recreate this model.
$newRobot = new Robot($snapshotData);

// After construction, the instance data is not accurate since it's been transformed twice.
// $newRobot->specialField = 'raw-transformed-transformed';

// Expected:
// $newRobot->specialField = 'raw-transformed';

```

**Recommendations:**
1. Maintain backwards compatibility and add a `$useModelSetters = true` parameter to `Model::assign()` as the fourth parameter. The model construct should call this with `false`.
   
   https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/model.zep#L170
2. Since 2.1.x already  breaks backwards compatibility with Model instantiation, simply remove the setters in `Model::assign()`. 
   
   Not sure why this was ever introduced? For 2.1 this would break backwards compatibility but it should be the correct design. There exists ambiguity when the model arbitrarily looks for extending methods as the various export functions do not check for ambiguous functions (nor should they) (e.g. `toArray()`, `getSnapshotData()`, etc).
   
   https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/model.zep,  Lines 493-496, 498

**Comment by sergeyklay** [comment]
@virgofx Could you please check now 2.1.x branch

**Comment by virgofx** [comment]
Will recheck this soon as I get some time ... hopefully within a couple days.

**Comment by virgofx** [comment]
Small note: Model.zep @line 492/493 needs corrected notes

**Comment by sergeyklay** [comment]
@virgofx ping

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
