### ISSUE TITLE
[BUG] 2.0.9: \Phalcon\Mvc\View\Engine\Volt\Compiler uses absolute path for compileFile(), invalid relative path for extends

### ISSUE THREAD

**Issue by SlvrEagle23** [phalcon/cphalcon#11170]
I have tracked down an issue that is causing me quite a lot of difficulty in rendering templates that extend other templates in Phalcon 2.0.9.

When calling `{% extends "file.volt" %}` in a Volt template, to determine the path of the parent file, the Volt compiler passes a relative path to the `compileFile()` function, which only accepts an absolute path under normal circumstances. This triggers an inevitable exception about the file not found.

I believe the problem is caused by the path calculation on this line:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt/compiler.zep#L2097

(My apologies for not offering a direct patch for this issue, as I don't know enough Zephyr or enough about the process to do so easily)

I created a class that extends the Volt engine and its compiler for the purpose of investigating the issue, and dumping the paths from successive calls to `compileFile()`:

Arguments to `compileFile()`, Original file compile:

```
array(3) {
  [0]=>
  string(67) "/var/www/vagrant/app/modules/account/views/scripts/index/index.volt"
  [1]=>
  string(71) "/var/www/vagrant/app/modules/account/views/scripts/index/index.volt.php"
  [2]=>
  bool(false)
}
```

Arguments to `compileFile()` when the compiler calls compileFile for the extends:

```
array(3) {
  [0]=>
  string(41) "modules/account/views/scripts/cpanel.volt"
  [1]=>
  string(50) "modules/account/views/scripts/cpanel.volt%%e%%.php"
  [2]=>
  bool(true)
}
```

Here are the defaults being sent to the corresponding View class:

``` php
$view->setBasePath(APP_BASE_DIR.'/');
$view->setViewsDir('modules/frontend/views/scripts/');
$view->setLayoutsDir('../../../../templates/');
$view->setPartialsDir('');
```

**Comment by andresgutierrez** [comment]
Did you have this issue using a previous version of Phalcon?

**Comment by SlvrEagle23** [comment]
I'm not sure; I only started using Volt templates on this instance of Phalcon, which was just started a few days ago. It appears the Ubuntu PPA doesn't have older versions of Phalcon for me to test against (or if it does, I'm doing it wrong).

**Comment by SlvrEagle23** [comment]
Update: Supplying the full absolute path in `$view->setViewsDir()` and leaving `$view->setBaseDir()` empty seems to resolve the issue.

It appears, then, that the issue is that extended templates don't properly make use of the View's "base_dir" property, whereas the path calculation for the original views themselves does.

**Comment by andresgutierrez** [comment]
Can you try using 2.1? Absolute paths aren't supported in 2.0.x

**Comment by sergeyklay** [comment]
Absolute paths are now supported
