### ISSUE TITLE
Search on http://docs.phalconphp.ru/ does not work

### ISSUE THREAD

**Issue by akudryav** [phalcon/cphalcon#11188]
Search on http://docs.phalconphp.ru/ does not work
It always return 404 error (for example https://readthedocs.org/search/project/?q=getClass&selected_facets=project%3Aphalcon-docs-ru)

**Comment by andresgutierrez** [comment]
Official documentation is https://docs.phalconphp.com/ru/latest/index.html

**Comment by akudryav** [comment]
The same issue on that page also, search box is not working

**Comment by sergeyklay** [comment]
For doc related issues use please https://github.com/phalcon/docs repo
