### ISSUE TITLE
Query Builder Removes Table Alias in Parentheses

### ISSUE THREAD

**Issue by ilgityildirim** [phalcon/cphalcon#11189]
I might be mistaken but it seems like a bug.
I created a query using [QueryBuilder](https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model_Query_Builder.html), it all works expected unless I use parentheses in a join query.

When I use `getPhql()`  I get following result;

``` sql
SELECT m.id as id, m.name as name, l.name as country, l.id as locations_id
FROM [App\Models\Members] AS [m]
INNER JOIN [App\Models\Locations] AS [l] ON l.id = m.locations_id
WHERE m.deleted = :deleted:
AND (m.name LIKE :search: OR l.name LIKE :search:)
ORDER BY country desc LIMIT :APL0:
OFFSET :APL1:
```

Unfortunately this was giving me `404 Not Found` error so I logged the SQL query and I was surprised when I saw this log;

``` sql
SELECT `m`.`id` AS `id`, `m`.`name` AS `name`, `l`.`name` AS `country`, `l`.`id` AS `locations_id` 
FROM `members` AS `m`
INNER JOIN `locations` AS `l` ON `l`.`id` = `m`.`locations_id`
WHERE `m`.`deleted` = :deleted
AND (`name` LIKE :search OR `name` LIKE :search)
ORDER BY `country`
DESC LIMIT :APL0
OFFSET :APL1
```

I also tried to write model name instead of alias without any success. I can see the model name in query but in the log they are just being removed.

**Comment by sergeyklay** [comment]
Can you please provide small script to reproduce?

**Comment by nsossonko** [comment]
You can't bind twice to the same variable...unless I'm misreading your PHQL...

**Comment by ilgityildirim** [comment]
@sergeyklay I'll do it as soon as possible.
@nsossonko I'm not binding the same variable twice, I just use the same variable and bind it once as I'm looking for the same variable in different columns.

**Comment by nsossonko** [comment]
Yes but you're basically doing something like this:
```php
$query->andWhere(
  'm.name LIKE :search: OR l.name LIKE :search:',
  array('search' => 'foo')
);
```
Which in my experience does not work. You need to do:
```php
$query->andWhere(
  'm.name LIKE :search1: OR l.name LIKE :search2:',
  array('search1' => 'foo', 'search2' => 'foo')
);
```

**Comment by ilgityildirim** [comment]
@nsossonko no, it works. It would be redundant not to mention ridiculous to not have it work first way.

**Comment by nsossonko** [comment]
One would think so, but this is the fact. I just tested AGAIN just to be 100% certain and this is the error I get in the first scenario:

Exception: SQLSTATE[HY093]: Invalid parameter number

As soon as I switch to the second way, it is perfectly fine. Testing on Phalcon 2.0.9/Windows.

**Comment by ilgityildirim** [comment]
@nsossonko I'll check it out on my local computer as well if this is the case this should be fixed. PDO allows it without a problem.

**Comment by Jurigag** [comment]
@nsossonko well thats true, but for PDO, phql could possibly allow the same name of value, and put two values when generating final sql. For example you can use same name in dql and it's doing job by itself.

**Comment by nsossonko** [comment]
I don't think this has been fixed

**Comment by sergeyklay** [comment]
Open a new issue then
