### ISSUE TITLE
Phalcon Beanstalk Queue errors with Reserve when job data > 16KB

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#11190]
When using job data that serializes to amounts greater than 16KB (currently testing around 64KB), the Beanstalk queue will error when performing a reserve() command as it attempts to read the data, and parse it into a job.

`$queue->reserve()`

This will result in unserialization errors as such:
```php
Notice: unserialize(): Error at offset 16365 of 16365 bytes in [file] on line [fileLine]
```

The problem is that the `Beanstalk::read()` does not work correctly when using `fread` when coming through `reserve()`. Although the exact bytes returned in the response are correct (actually +2 makes it correct as noted in the source).  The `fread()` will return data that is truncated around 16KB. 

Switching this to simply do a standard while loop or using `fgets()` works.

https://github.com/phalcon/cphalcon/blob/master/phalcon/queue/beanstalk.zep#L353

**Comment by andresgutierrez** [comment]
Could you please submit a PR with the fix?

**Comment by virgofx** [comment]
I'm not sure how to approach this as I'm studying all the locations the read() is currently used and I have limited experience with sockets and performance.

To help confirm the issue:

**Beanstalk::read() Test**
```php
var_dump ('Attempting to read: ' . ($length + 2));
$data = fread($connection, $length + 2);
var_dump ('Actual returned: ' . strlen($data));
```
**Result**
```php
string(25) "Attempting to read: 67663"
string(22) "Actual returned: 16365"
```

Let's test using fgets():
```php
$data = fgets($connection);
var_dump ('Actual returned: ' . strlen($data));
```

```php
string(22) "Actual returned: 67663"
```


Before fixing ... would like to implement the best option ...

Perhaps, modify the `read($length = 0)` to behave as follows:
1) If length is not specified, use fgets()
2) If length is specified, use fgets() with length+2
3) Have the reserve() command call read() without the length parameter specified.

Thoughts?

**Comment by andresgutierrez** [comment]
Fixed by @virgofx

**Comment by shoother** [comment]
Very good.
