### ISSUE TITLE
belongsTo's foreignKey rule reaches on any save() operation

### ISSUE THREAD

**Issue by sszdh** [phalcon/cphalcon#11201]
Hi all,

Consider these models:

```php
class Robots extends Model
{
    public $id;

    public $name;

    public function initialize()
    {
        $this->useDynamicUpdate(true);
        
        $this->hasMany("id", "Parts", "robots_id", 
          [
            'alias' => 'parts'
          ]
        );
    }
}

class Parts extends Model
{

    public $id;

    public $name;
	
	public $robots_id;

    public function initialize()
    {
        $this->useDynamicUpdate(true);

        $this->belongsTo("robots_id", "Robots", "id", 
          [
            'alias' => 'robot',
            "foreignKey" => true
          ]
        );
    }
}
```

When I want to fetch>change>save on `Part`, the `foreignKey` rule causes extra query.

```php
$part = Parts::findFirst("id = 1");
$part->name = $part->name . ' new 1';
$result = $part->save();
```

SQL Log:

```sql
[Mon, 07 Dec 15 00:00:24 +0330][INFO] SELECT `parts`.`id`, `parts`.`name`, `parts`.`robots_id` FROM `parts` WHERE `parts`.`id` = 1 LIMIT :APL0 [1]
[Mon, 07 Dec 15 00:00:24 +0330][INFO] SELECT COUNT(*) AS `rowcount` FROM `robots` WHERE `robots`.`id` = :0 [1]
[Mon, 07 Dec 15 00:00:24 +0330][INFO] UPDATE `parts` SET `name` = ? WHERE `id` = ? [Sample Robot Part 1 new 1, 1]
```

Why we should have `foreignKey` check on `Parts` table (and extra query) when I just trying to change `name` field?!

Thanks.

**Comment by andresgutierrez** [comment]
As the relationship is marked as foreign key it checks data integrity before any save. You can remove the foreignKey => true to remove Phalcon the responsibility of checking foreign keys.

**Comment by sszdh** [comment]
I understand. But is not it better that this happen only on specific relation change not before any save?

Thanks.

**Comment by nsossonko** [comment]
This is actually a major bug, the foreign key check should ONLY be done if the relation is changed in some way. All the details about the relationship are available to Phalcon, so Phalcon can easily determine if there was a relationship change attempted...the way this is now is a huge perf concern for models with multiple relationships...

**Comment by sergeyklay** [comment]
@nsossonko Send PR with fixes
