### ISSUE TITLE
Phalcon\Mvc\Model\Row Object array[x] set is not support,but object-x set is support

### ISSUE THREAD

**Issue by guangju** [phalcon/cphalcon#11209]
HI all,

why not support array[x] set use Row Object?
why can be used in version 1.x?
why notes of method offsetSet in source code file cphalcon/phalcon/mvc/model/row.zep ntoes say:"Rows cannot be changed." but array-x set is support?

``` php
$id = 590;
$conditions = "id = :id: AND is_delete = 0";
$bind = array(
    "id"  => $id
);
$course = Course::findFirst([
    $conditions,
    "bind"      => $bind,
    'columns'   => 'id,title,main_cat,is_free'
]);

//course is Phalcon\Mvc\Model\Row Object
$course->description = 'x';     //support
$course['description'] = 'x';   //not support

print_r($course);exit;

```

**Comment by phalcon** [comment]
You can use `$course->description` because $course is an object and we can't make object inmutable in PHP. However if you access them using ArrayAccess we can control immutability.

**Comment by guangju** [comment]
This use is not convenient, please consider,but can be in 1.x version
