### ISSUE TITLE
Phalcon\Mvc\Model::find() with limit returns no results in Oracle

### ISSUE THREAD

**Issue by rlaffers** [phalcon/cphalcon#11217]
Phalcon 2.0.8
Oracle 10g.

There seems to be a problem with the Oracle dialect. When running
```php
        $result = Languages::find(array('limit' => 2));
        echo '<pre>' . var_export($result->toArray(), 1) . '</pre>';
```
the result is empty. I logged the SQL query produced by this code:
```sql
SELECT * FROM (SELECT Z1.*, ROWNUM PHALCON_RN FROM (SELECT LANGUAGE.ID_LANGUAGE, LANGUAGE.TITLE, LANGUAGE.CODE_2, LANGUAGE.CODE_3, LANGUAGE.VALID, LANGUAGE.USER_ACTOR, LANGUAGE.LOCALE FROM COMMON.LANGUAGE) Z1 WHERE ROWNUM <= 0)
[params: Array
(
    [APL0] => 2
)
] 
```
The param APL0 seems to be ignored - it is not used anywhere in the query.
Also, please note the ROWNUM in Oracle starts at 1, not 0 as reported [here](https://github.com/phalcon/cphalcon/issues/11033).

Language is my model extending \Phalcon\Mvc\Model. It uses columnMap() with the columns listed in the SQL query.

**Comment by MLukman** [comment]
Dear sir, any info on when will this fix be tagged with an actual version (e.g. 2.0.13) and can be downloaded from official site?

**Comment by sergeyklay** [comment]
PR here https://github.com/phalcon/cphalcon/pull/11216

**Comment by sergeyklay** [comment]
Phalcon does not support Oracle. Refer to #12008
