### ISSUE TITLE
Error in \Phalcon\Text::dynamic()

### ISSUE THREAD

**Issue by mzf** [phalcon/cphalcon#11215]
Please replace on https://github.com/phalcon/cphalcon/blame/master/phalcon/text.zep#L272
`let words = explode("|", matches[1]);`
to 
`let words = explode(separator, matches[1]);`

**Comment by mzf** [comment]
Thanks!

**Comment by mzf** [comment]
Not fixed yet?

**Comment by mzf** [comment]
Please fix it

**Comment by sergeyklay** [comment]
Fixed in the `2.1.x` branch.

**Comment by mzf** [comment]
Cool! Thanks a lot!
