### ISSUE TITLE
How to use user defined namespace

### ISSUE THREAD

**Issue by SakuraZhang** [phalcon/cphalcon#11226]
In our own project, we need a diffetent namespace with phalcon like that
namespace Pms;
but it seems not work well.Anyone could meet this?

Fatal error: Class .. not found in

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework or support requests please visit the [official forums](https://forum.phalconphp.com/).
