### ISSUE TITLE
Can't save collection with _id = 0 

### ISSUE THREAD

**Issue by notsu** [phalcon/cphalcon#11228]
I have been struggling with this problem for a while with Phalcon 2.0.8, And this is my model.

```
<?php

namespace App\Models;

use Phalcon\Mvc\Collection;

class Highlight extends Collection
{

    public $highlights;

    public $createAt;

    public $modifiedAt;

    public function initialize()
    {
        $this->useImplicitObjectIds(false);
    }

    public function getSource()
    {
        return 'highlight';
    }

    public function beforeCreate()
    {
        $this->createAt = new \MongoDate();
    }

    public function beforeUpdate()
    {
        $this->modifiedAt = new \MongoDate();
    }

    public function afterFetch()
    {
        $this->createAt = date('m/d/Y H:i:s', $this->createAt->sec);
    }

}
```

And I tried to save model with _id = 0 as default highlight model in our collection.

```
$highlight = new Highlight;
$highlight->_id = 0;
$highlight->settings = [];

$highlight->save();
```

After save this model and check it in our database I found that document save with _id: MongoId() instead of _id: 0

I don't know how to save it as _id: 0, and everthing work fine with _id: -1 or _id: 1

Hope to see any solution and sorry for my bad English.

**Comment by naNuke** [comment]
Try ```$highlight->_I'd = "0";```

**Comment by notsu** [comment]
@naNuke MongoDB is case-sensitive, so "0" != 0 and this will cause a problem in the collection as below example.

```
Highlight::findById("0"); // found
Highlight::findById(0); // not found
```

**Comment by naNuke** [comment]
@notsu right, I had similiar issue where phalcon ignored int 0 values, probably thinking its a bool false and saving them as a string solved it, but that was MySQL...

Maybe the root of the issue is same in this case and might need a workaround until fixed...
