### ISSUE TITLE
Boss, when to support php7?

### ISSUE THREAD

**Issue by chenshuhao** [phalcon/cphalcon#11234]
Boss, when to support php7?
thanks!

**Comment by sergeyklay** [comment]
Duplicated:
+ phalcon/cphalcon#10378
+ phalcon/zephir#756
+ phalcon/zephir#952
+ phalcon/cphalcon#11203

We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com/).
