### ISSUE TITLE
how can i use setSource in my model ?

### ISSUE THREAD

**Issue by hello2t** [phalcon/cphalcon#11230]
i want to change the table before find
just like this:
![qq 20151215171955](https://cloud.githubusercontent.com/assets/11027199/11806736/14b5f088-a350-11e5-85e8-542a5266895b.png)

but it can not work...

can anybody help me ?

**Comment by daison12006013** [comment]
First you're using github's issues, go to forum and ask the question there, issues should be related to the features/bugs to cphalcon itself.

You should not overriding the find function as it is not reliable, it's like you're breaking the Phalcon Model itself, instead create your own function something like findByDate($date == null) {}
