### ISSUE TITLE
Incorrect @property value in phalcon/di/injectable.zep

### ISSUE THREAD

**Issue by karen-nalbandian-adb** [phalcon/cphalcon#11231]
Hello,
First of all, thank you for developing so great and performant framework. It is really awesome!

While using it, I discover that there is a trailing semicolon in the class PHPDoc of the __phalcon/di/injectable.zep__ in the @property corresponding to the dispacher. This causes the IDE to not properly resolve the autocompletion.

**Comment by sergeyklay** [comment]
Thanks. Fixed in `2.0.x` branch
