### ISSUE TITLE
Volt convert array to object when adding var

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11242]
Well, in twig you can access to array elements just by dot, its pretty nice and clean. Volt dont have such an option. But how about adding option to volt that when it's set to true it will do on our vars passed as array such a staff:

```php
json_decode(json_encode($array, FALSE));
```

In that way we can access in volt all elements of array by dot, beacause its actually an object.

**Comment by Kachit** [comment]
maybe simple: (object) $array;
