### ISSUE TITLE
Please add native translation and volt filters |trans |transchoice 

### ISSUE THREAD

**Issue by lubberscorrado** [phalcon/cphalcon#11241]
The only thing i am currently missing in phalcon is a native implemented translation class and support on volt for filters like

|trans
|transchoice 

Just like in symfony:
http://api.symfony.com/3.0/Symfony/Component/Translation/Translator.html#method_transChoice

**Comment by Jurigag** [comment]
https://docs.phalconphp.com/en/latest/reference/translate.html
