### ISSUE TITLE
Implement CreditCard validator for model validators too

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#11245]
For now, CreditCard validator is only available in Phalcon\Validation\Validator, this would be really useful for Phalcon\Mvc\Model\Validator too.

**Comment by sergeyklay** [comment]
Since Phalcon v2.1.0 `Phalcon\Mvc\Model\Validation` is deprecated in favor of `Phalcon\Validation`

**Comment by nsossonko** [comment]
Yes but 2.1 is not out yet...

**Comment by virgofx** [comment]
@sergeyklay I notice in 2.1 the validators are still in `Phalcon\Mvc\Model`. Shouldn't these be removed?

**Comment by sergeyklay** [comment]
@nsossonko We aren't going to create something what soon will need to remove
@virgofx Currently in 2.1 version `Phalcon\Mvc\Model\Validation` is deprecated. But existing and working fine. In the future it will be removed
