### ISSUE TITLE
Oracle Model::insert does not work

### ISSUE THREAD

**Issue by rlaffers** [phalcon/cphalcon#11251]
Phalcon 2.0.x, Oracle 10g, PHP 5.4.45

Inserting a model in Oracle does not work. It did work in Phalcon 1.3.x.

```php
        $robot = new Robots();
        $robot->title = 'Marvin';
        $robot->year = '2001';
        $robot->current_state = 'on';    
        echo 'creating robot...<br/>';
        try {
            $result = $robot->create();
        } catch (\Exception $e) {
            echo $e->getMessage();
            die('failed to create robot');
        }
        echo 'created robot'; // never gets here
```
The problem: The record is not created and PHP never gets to the last line. No exceptions were thrown. Looking at the DB for last run queries, it doesn't seem as if Phalcon even attempted to run any INSERT query on the table.
Strangely, the output to screen reads:
```
creating robot...
array (
  'ID' => '2605',
  0 => '2605',
)
```
The number 2605 corresponds to a new value gotten from the table sequencer. This seems like a forgotten piece of debug code somewhere in Phalcon. Can anybody give pointers where to search for it? I may try to fix it.

**Comment by Jurigag** [comment]
Well you would need to check what was doing Oracle adapter in 1.3.x and whats the diffrence with 2.0.x. But you need to know C language.

**Comment by rlaffers** [comment]
Well that's obvious. I was rather hoping for a quick pointer from someone who recently has delved into Model inserting or saving in Phalcon 2.0.x to cut down on hunting the bug time.

**Comment by sergeyklay** [comment]
Phalcon does not support Oracle. Refer to #12008
