### ISSUE TITLE
Model boolean saving

### ISSUE THREAD

**Issue by daison12006013** [phalcon/cphalcon#11258]
I don't know if this kind of approach already brought up, or I might end up for nothing when posting this.

So I have a tinyint(1) column (is_deleted) in my table for boolean and to support a much more faster query compared of using deleted_at(just for reference to know the date).

so I have a function deleted()

```
    public function setDeleted($bool)
    {
        $this->is_deleted = (int) $bool;

        return $this;
    }
```

see above code, I am always typecasting the returned boolean into an int, for 1 and 0 values.

are not we supposed to support a boolean detector inside the cphalcon create/update process to change it to 1 or 0 instead of typecasting everything?

Fyi, close this if it is already brought up and please link reference as well.

**Comment by spuy767** [comment]
One, using the SoftDelete behavior on your model will make your life easier than calling setDeleted() and then calling update().  Two, checking whether or not deleted_at is null vs checking whether a value tinyint column is 1 or 0 should be nigh on the same execution time depending on indexes.

**Comment by daison12006013** [comment]
@spuy767, my concern is all about the boolean saving, it should be handled in the cphalcon.

I provided a tinyint(1) field and if I'll be passing a value of $model->field = true; the value should be understood as 1, and false for 0.

while my example, I need to typecast it into (int) to convert boolean into 1 or 0

**Comment by daison12006013** [comment]
@sergeyklay @andresgutierrez, putting you in guys, it's been month and no reply from you guys, any comment would really help specially people from us devs who hates typecasting variables.

or this thing is not doable for now?

**Comment by andresgutierrez** [comment]
this is a matter to which we have gone round many versions, some developers want to use tinyint(1) as boolean other wants to use it as integer. You can better use a "bit" column instead. https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/db/adapter/pdo/mysql.zep#L232

**Comment by daison12006013** [comment]
That's cool to hear that we're using "bit" instead of tinyint, however is there any possible way to provide the boolean fields inside the model?

I think this will help others to use a single database structure from different frameworks, likewise, I've been using symfony1 before and migrated all the code to laravel4.2, but still using the same database structure without any change.

I have an API that handles the same database structure, and still using a tinyint(1) fields.

While I want to start migrating my projects into Phalcon now, but I think I really need to typecast everything, unless there is a variable inside a model to provide all boolean fields or the link mysql.zep is flexible to determine if it is "tinyint(1)" or "bit".
