### ISSUE TITLE
[NFR] Bind model in router

### ISSUE THREAD

**Issue by mattvb91** [phalcon/cphalcon#11267]
Couldn't find any discussions on this maybe someone can link me.

Would there be any interest in having the ability to bind models in the router like we can in laravel 5:
https://laravel.com/docs/5.2/routing#route-model-binding

That way we can then in the controller actions inject the correct model for you already without having to manually do a find() or similar.

```
public function edit(Product $product)
{
      //bla
}
```

I guess the syntax could be similar too so instead of this:

```
$router->addGet("/products/edit/{id}", "Products::edit");
```

it would be:
```
$router->addGet("/products/edit/{product}", "Products::edit");

```

Which then looks up do we have a model of type "product", if we do lookup the identifier on the model and load it so that we can inject into the action in the controller.

**Comment by Green-Cat** [comment]
Symfony has this too http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html

**Comment by andresgutierrez** [comment]
https://docs.phalconphp.com/en/latest/reference/routing.html#using-conversors

**Comment by mattvb91** [comment]
@andresgutierrez thanks for the link I will have a play around with this. If this works the way I think it does I will open a pull request to update the docs with an example with a model.

**Comment by mattvb91** [comment]
wow that is awesome. Thats a hidden gem right there.

So this works perfectly:

```
            $router->add('/user/{user}', [
                'controller' => 'index',
                'action'     => 'test',
            ])->convert('user', function ($id) {
                return User::find($id)->getFirst();
            });
```

and in the controller:

```
 public function testAction(User $user)
 {
    //bla
 }
```

Now I guess the next question is, what would be involved in getting that to register/check for matching models automatically instead of having to manually do that for every route?

**Comment by Jurigag** [comment]
I guess in dispatcher it has to get type of parameters from action. If its class which extends model, then it could do this behaviour you want maybe ? But idk.

**Comment by spuy767** [comment]
@mattvb91 Perhaps you were just shorthanding it in your demo code, but if you use User::findFirst($id) you get to skip a step.

**Comment by mattvb91** [comment]
@spuy767 thanks yea I have updated documentation with findFirst().

@Jurigag thanks for the suggestions I will look into that.

**Comment by mattvb91** [comment]
@Jurigag I have managed to make it work in the dispatcher by using the following:

This is just thrown together to make it work haven't refined anything yet.

```php
$reflectionMethod = new \ReflectionMethod($handlerClass, $actionMethod);
$methodParams = $reflectionMethod->getParameters();

foreach($methodParams as $key => $methodParam){
    $class = $methodParam->getClass()->getName();

    if($class == Model::class || is_subclass_of($class, Model::class))
     {
          if(is_numeric($params[$key]))
          {
               //Get the model assigned to the controller
               if($class == Model::class)
                {
                      $class = call_user_func_array([$handlerClass, 'getModelName'], []);
                }

                $params[$key] = $class::findFirst([$params[$key]]);
          }
     }
 }

// We update the latest value produced by the latest handler
$this->_returnedValue = call_user_func_array([$handler, $actionMethod], $params);
$this->_lastHandler = $handler;

```

The above relies on the controller having a method to return the associated class name:

```php

function getModelName()
    {
        return Article::class;
    }
```

Then if the parameter getting passed in is an integer and the method accepts an object that extends Model it will load it and pass it in.

So then you end up in your controller being able to do:

```php 
public function viewAction(Article $article)
{
     //$article var loaded already
}
```

This is without using the $router->convert method. 

Does anyone have any feedback/want me to implement this in the zephir dispatcher?

**Comment by Jurigag** [comment]
Do pr with it :)

**Comment by Green-Cat** [comment]
@mattvb91 Good work!
Since we can get the type hint class with $param->getClass()->name, why can't we just inject the resolved object if the type hint class inherits Phalcon\Mvc\Model?

**Comment by mattvb91** [comment]
@Green-Cat I was actually thinking too that I would prefer to not rely on having a method in the controller to give the modelname and instead get anything thats needed from the parameters. 

ill have a play around with your suggestion and update! Love the suggestion for using parameters to pick which fields to do the retrieval on.

**Comment by mattvb91** [comment]
@Green-Cat just to clarify, the reason I am trying to do a "getModelName()" in the controller is for example if I have the BaseController doing:

```php
public function viewAction(Model $model)
{
     $this->view->setVar('model', $model)
}
```

which my ArticleController then extends, but unless I need custom functionality I wont be overriding "viewAction" to this:

```php
public function viewAction(Article $article)
{
    //Custom functionalitu
    return parent::viewAction($article);
}
```

So I need another way to get the "real" model, which currently is through the getModelName method but I would prefer to move that off to router to check for /article/{article} and then it knows it needs to do something.

**Comment by Jurigag** [comment]
Wait a min, you already have model name here - $class ?

**Comment by mattvb91** [comment]
Thats only if I decide to override the viewAction method in the parent class and give it the associated model.

If I just go through the BaseController then it will only see the Phalcon\Mvc\Model and has no way of knowing what the actual model is associated with the extended controller.

Or am I being too picky?

**Comment by Jurigag** [comment]
Well if you you are using something like ArticleController and Article model, then maybe get name from controller name and then if there is no model existing get it from getModelName ?

Also it would be nice that you will implement some interface for controller with getModelName. And then check if our controller is instanceof it to check if we actually have getModelName method.

So:

1. Check if class is not null
2. If its model extending Model, so we have Article for example, return just 
```
$class = $methodParam->getClass()->getName();
$params[$key] = $class::findFirst([$params[$key]]);
```
3. If its actually Model, get controller name, remover Controller from it and check if such a class exist, if yes then:
```
$params[$key] = $class::findFirst([$params[$key]]);
```
4. Then check if controller is instanceof some interface, if yes, then 
```
$class = call_user_func_array([$handlerClass, 'getModelName'], []);
$params[$key] = $class::findFirst([$params[$key]]);
```

**Comment by mattvb91** [comment]
:+1: thanks thats an even better way of doing it.

**Comment by huoybb** [comment]
Use code below, which will do the model binding. 
dispatch.php
···
$eventsManager = new \Phalcon\Events\Manager();
$eventsManager->attach("dispatch:beforeDispatchLoop", function($event, \Phalcon\Mvc\Dispatcher $dispatcher){
    //模型注入的功能，这里可以很方便的进行 model binding,这里基本上实现了Laravel中的模型绑定的功能了
    $controllerName = $dispatcher->getControllerClass();
    $actionName = $dispatcher->getActiveMethod();

    try{
        $reflection = new ReflectionMethod($controllerName,$actionName);
        $actionParams = [];
        foreach($reflection->getParameters() as $parameter){
//                var_dump($parameter->getClass());die();
            if($parameter->getClass()){
                $className = $parameter->getClass()->name;
                $objectId = $dispatcher->getParam($parameter->name);

                if($objectId){
                    if(is_subclass_of($className,\Phalcon\Mvc\Model::class)){
                        $actionParams[$parameter->name] = $className::findFirst($objectId);

                    }else{
                        $actionParams[$parameter->name] = new $className($objectId);
                    }
                }else{
                    $actionParams[$parameter->name] = new $className;
                }
                //如果没有找到相关的资源，应该抛出一个错误才对！
                if(!$actionParams[$parameter->name]) dd('没有找到相关资源');

            }else{
                //如果参数是普通参数的话如何处置？
                //如果存在路由参数，则赋值，否则给一个null结果
                $value = $dispatcher->getParam($parameter->name);
                if(null == $value and $parameter->isDefaultValueAvailable()) $value = $parameter->getDefaultValue();
                $actionParams[$parameter->name] = $value;
            }
        }

        if(count($actionParams)){
            $dispatcher->setParams($actionParams);
        }

    } catch(\Phalcon\Exception $e) {
        var_dump($e);
        die();
    }

});

$dispatcher = new \Phalcon\Mvc\Dispatcher();
$dispatcher->setEventsManager($eventsManager);
return $dispatcher;
···

**Comment by mattvb91** [comment]
Just to keep everyone up to date there has been alot of discussion on the pull request here:
https://github.com/phalcon/cphalcon/pull/11288

**Comment by sergeyklay** [comment]
@mattvb91 This issue might be closed?
