### ISSUE TITLE
XHP-JS (Server-side & Client-side efficiency) and the future of Phalcon

### ISSUE THREAD

**Issue by reactima** [phalcon/cphalcon#11264]
Phalcon became really great tool for turning my ZF1 legacy code into something usable last year.

Everything was great ... till I started getting more more into isomorphic React/Redux/Node/ES6 movement... and finally got into "hot-reload" staff which don't loose data state.

For example Redux https://github.com/gaearon/redux

Redux became huge productivity boost in very short period of time for me ... and I want the same thing in Phalcon community!

So please consider the potential port of XHP-JS into Phalcon. https://code.facebook.com/posts/858739974205250/announcing-xhp-js-building-efficient-user-interface-components-with-hack-react-and-xhp/

XHP-JS allows to generate React components on server.

Please recognize it as beginning of new huge trend in the web developement!

As Facebook has grown, there have been three major classes of issues for our UI code:

Server-side efficiency: HTTP responses should be quick and easy to compute. Client-side efficiency: Anything computed inside the web browser still needs to be fast so we don't harm perceived load time or battery life. Developer efficiency: Code should be easy to understand, easy to reuse, and easy to refactor. We solve these issues with several open-source projects: XHP provides a safe, easy-to-use abstraction for server-side UI components; Hack adds convenient support for asynchronous operations; and React provides an efficient client-side UI library.

The open-source XHP library has recently gained support for Hack's async functionality — but purely server-side UIs aren't sufficient for the modern web. Today's release of XHP-JS provides the ability to add client-side logic to XHP components and even to create instances of React components from Hack code.

MeteorJS community noticed React trend ... Phalcon should be the next one. http://info.meteor.com/blog/meteor-the-missing-infrastructure-for-building-great-react-apps

Any thoughts?

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
