### ISSUE TITLE
Weird behavior of numeric parameter binding in Models (has to start with zero)

### ISSUE THREAD

**Issue by noobiwan** [phalcon/cphalcon#11263]
In the Working with Models, [Binding Parameters section](https://docs.phalconphp.com/en/latest/reference/models.html#binding-parameters) of the manual its written:

```php
// Query robots binding parameters with integer placeholders
$conditions = "name = ?1 AND type = ?2";
$parameters = array(1 => "Robotina", 2 => "maid");
$robots     = Robots::find(
    array(
        $conditions,
        "bind" => $parameters
    )
);
```
The integer placeholders binding doesn't seem to work like that (at least not when filtering related records based on relationships). To make it work I had to start the binding with ?0:

```php
$conditions = "name = ?0 AND type = ?1";
$parameters = array(0 => "Robotina", 1 => "maid");
```

or

```php
$conditions = "name = ?0 AND type = ?1";
$parameters = array("Robotina", "maid");
```

But starting with 1 instead of 0 would result in the following exception to be raised when calling the find() method:

```
PDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
```

It seems very odd. Is it a bug or a documentation issue?

**Comment by spuy767** [comment]
Because you can't do that.  If your array is going to be [1 => 'fred', 2 => 'bill'], then your bound parameters are going to need to be ?1 and ?2 not ?0 and ?1.  This is a constraint of PDO and not Phalcon, I believe.

**Comment by noobiwan** [comment]
That's what I am saying. Even if your array index starts at 1 and you use ?1 it doesn't work. The example doesn't work. That's my point. Could you please check?

**Comment by noobiwan** [comment]
I will try to provide a script that reproduces it

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
