### ISSUE TITLE
[NFR] Ability to set a default namespace for models

### ISSUE THREAD

**Issue by Green-Cat** [phalcon/cphalcon#11268]
When using a namespace for a project, it needs to be specified for every single model in PHQL, even if there is only one namespace for all models. The router has a way to set the namespace of all controllers, a similar feature for PHQL would be very convenient.

**Comment by Jurigag** [comment]
There already is https://docs.phalconphp.com/pl/latest/api/Phalcon_Mvc_Model_Manager.html

public registerNamespaceAlias (unknown $alias, unknown $namespaceName)

**Comment by andresgutierrez** [comment]
From Phalcon 2.0.3 you can register namespace aliases: https://blog.phalconphp.com/post/phalcon-2-0-3-released

**Comment by Green-Cat** [comment]
I am well aware of that method, it is great for projects with several namespaces, but it not for ones with a single one. Ideally one should be able to do something like

```php
use Phalcon\Mvc\Model\Manager as ModelsManager;

$di->set(
    'modelsManager',
    function () {
        $modelsManager = new ModelsManager();
        $modelsManager->registerDefaultNamespace('MyNamespace\Controllers');
        return $modelsManager;
    }
);

$data = $this->modelsManager->executeQuery("
    SELECT r.*, rp.*
    FROM Robots AS r
    JOIN RobotsParts AS rp
");
```

**Comment by spuy767** [comment]
Ideally, I think that doing it at the dependency injection level is ok, but I think we'd be better served if we could do it on a QueryBuilder and Criteria as well.
