### ISSUE TITLE
[Q]Redis(and other cache backends)

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11287]
Can i know why for example redis backend have only a few methods from here https://github.com/phpredis/phpredis ? I guess beacause its BackendInterface. Is there any problem with adding more functions for redis backend ? Maybe i miss something ?

**Comment by Jurigag** [comment]
Also isnt lifetime in all methods in cache backends suppose to set new lifetime(for example when we do get in redis backend) ?

**Comment by sergeyklay** [comment]
What other methods need for cache backend interface?
