### ISSUE TITLE
[RFE] Improve querying so that manual sanitizing isn't necessary

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#11282]
A lot of ORMs allow simpler querying in the form of

``` php
Model::find(array('name' => 'sample'));
```

They bind the array keys to the array values in a where clause and check that the key is a valid attribute of the model. In Phalcon, all of this falls on the developer to do (even though in create and update this same format is valid and the developer doesn't have to worry about sanitization).

This will relieve the requirement on the developer to:

1) create a where string
2) ensure each column is a valid column for the desired model
3) create bind parameters matching the where clause

Requesting as an enhancement.

**Comment by andresgutierrez** [comment]
This way of specify queries is too limited and I don't think it would be implemented.

**Comment by nsossonko** [comment]
Well as-is a non-existent column results in a PDO exception which kind of sucks...can that be improved at all?

**Comment by andresgutierrez** [comment]
A non-existent column is an error, isn't it?

**Comment by nsossonko** [comment]
I'm not sure what you mean by that, it results in a PDO exception. What's the expectation on the developer, to validate each column against the metaData->getAttributes array?

**Comment by andresgutierrez** [comment]
PHQL validates every column against the metaData->getAttributes() because there something called column independent map which allow you to rename the SQL columns by better names in the application.

https://docs.phalconphp.com/en/latest/reference/models.html#independent-column-mapping

**Comment by nsossonko** [comment]
I am using the query builder and this is not happening, is there something I'm supposed to be doing to doing to enable that?

**Comment by andresgutierrez** [comment]
Can you provide a small use test case?

**Comment by nsossonko** [comment]
```php
namespace Sample {
  class Parents {
    $id;
    $name;
    function initialize() {
      $this->hasMany('id', 'Sample\Childs', 'parent' array('alias' => 'children'));
    }
  }

  class Childs {
    $id;
    $parent;
    $name;
    function initialize() {
      $this->belongsTo('parent', 'Sample\Parents', 'id' array('alias' => 'owner'));
    }
  }
}

$builder = new \Phalcon\Mvc\Model\Query\Builder();
$builder->addFrom('Sample\Childs', 'a')
        ->innerJoin('Sample\Parents', 'a.parent = owner.id', 'owner')
        ->where('a.notacolumn = :notacolumn:', array('notacolumn' => 'exception'));

$result = $builder->getQuery()->execute();
```

That's the gist of what we're doing, in short. The execute call results in a SQLSTATE exception (which I believe comes from the PDO driver).

**Comment by stefanchiriac** [comment]
- a thing I could agree from all of this is auto sanitization when using find(), but is not such  a deal breaker.

- notacolumn should throw SQLSTATE exception since after all doesn't exist and there is no point for the ORM to try to make a valid query. In the end this will make more problems than solve, since you won't know why your query is not returning the expected result.

**Comment by nsossonko** [comment]
So from the query.zep and parser.c code it seems this kind of sanitizing (eg, column existence and column renaming) is only done on the selected columns. It seems like modifying the rule for where (or expr) here: https://github.com/phalcon/cphalcon/blob/c8d4916bbfd0cb18395fe25d8c5a663fc5077d8f/ext/phalcon/mvc/model/query/parser.c#L963 might fix this, but I'm not 100% clear on how this is done and all the repercussions. An additional issue seems to be that if there is a column map defined for a where clause column that is not in the select, it won't be renamed, but I have not tested that specifically yet.

**Comment by nsossonko** [comment]
@andresgutierrez is this a bug that should be fixed or will this remain as-is?

**Comment by nsossonko** [comment]
I don't think this was ever fixed
