### ISSUE TITLE
Which Version of Phalcon Will Support PHP7 ?

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11285]
In this closed [issue](https://github.com/phalcon/zephir/issues/756) @ovr has mentioned "Yeap, we plan to support PHP 7, and next versions but not now." Which version will that be? Is it minor version like *2.0.10* or major version like *3.0.0* Please let us know so we can plan accordingly. Thank You!

**Comment by Green-Cat** [comment]
There are already some commits with initial work to support php 7.0 in the 2.1.x branch, so presumably 2.1 will ship with php 7 support.

**Comment by tuxy** [comment]
@Green-Cat, very nice! Thanks for pointing that out.
