### ISSUE TITLE
phalcon ODM Can not use $unset  MongoDB

### ISSUE THREAD

**Issue by overlords** [phalcon/cphalcon#11293]
protogenesis
```
db.example.update({}, {$rename:{"name.additional":"name.last"}}, false, true);
```

Ask how to use in Phalcon

**Comment by dot5enko** [comment]
why did you close this issue, i'm also wonder how to do achieve this. The same with $set

**Comment by sergeyklay** [comment]
@dot5enko Create separated issue

**Comment by bkvaiude** [comment]
Any updates on how to use  $unset operator?
