### ISSUE TITLE
Why the Model::findFirst( 1 ) function doesn't work?

### ISSUE THREAD

**Issue by yesworld** [phalcon/cphalcon#11307]
Hi everyone!

Why the ```Model::findFirst( 1 )``` function does not find anything? But if you make the request a bit different, using the same id, it works fine.
 ```php
            Model::find([
                'conditions' => 'id = 1'
            ]);
```
May it affect APC somehow?
Thank you!

**Comment by tmihalik** [comment]
I can confirm. It's a Phalcon bug!

Here's the problem: 
https://github.com/phalcon/cphalcon/blob/c8d4916bbfd0cb18395fe25d8c5a663fc5077d8f/phalcon/mvc/model/query/builder.zep#L267

try: `Model::findFirst('1');`

**Comment by Green-Cat** [comment]
That's weird, I have many uses of Model::findFirst(int) in my project and it seems to work just fine?

**Comment by yesworld** [comment]
Hey, tmihalik,
Thank you for your reply, but unfortunately this ```Model::findFirst('1');``` doesn't work for me either.

I don't think, that the issue has something to do with the type of data, because out of 100k records, I get just a half of them, and randomly

**Comment by ifsnow** [comment]
@tmihalik I think It's not a bug. In this case, Builder creates a condition using the related primary key.
https://github.com/phalcon/cphalcon/blob/c8d4916bbfd0cb18395fe25d8c5a663fc5077d8f/phalcon/mvc/model/query/builder.zep#L1010

@yesworld Can I see your table schema or model define. and output of `php --ri phalcon` command.

**Comment by yesworld** [comment]
@ifsnow, 
``` 
#php --ri phalcon
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 2.0.9
Build Date => Nov 30 2015 10:03:21
Powered by Zephir => Version 0.8.0a

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```

I'm sorry guy for wasting your time. I found the reason.
Somehow I didn't notice that the model's function findFirst was redefined!
