### ISSUE TITLE
`empty()` on `Phalcon\Config` item doesn't work correctly

### ISSUE THREAD

**Issue by bombless** [phalcon/cphalcon#11309]
```php
<?php
use Phalcon\Config;
$config = new Config(array('setting' => false));
var_dump(empty($config->setting)); // false
$another_config = (object)array('setting' => false);
var_dump(empty($another_config->setting)); // true
```
Is this actually a 'feature'?

**Comment by Jurigag** [comment]
I checked your code and it returns true for var_dump(empty($config->setting));

What phalcon version you are using ?

**Comment by ifsnow** [comment]
phalcon 1.3.4 : return `false`
phalcon 2.0.x : return `true`

**Comment by bombless** [comment]
So I guess it's fixed in 2.x.
Too bad my company still use 1.3.x. :cry:

**Comment by Jurigag** [comment]
@bombless 
So maybe tell them about update ?
