### ISSUE TITLE
[NFR]Relationship annotations, Validator annotations ?

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11304]
There is some old class AnnotationsInitializer - https://github.com/phalcon/tutorial-models-init/blob/master/library/AnnotationsInitializer.php

Any reason for dropping it ?

How about adding it to phalcon as zephir ? I can do PR request with it. But i think that `@HasMany` etc could be in properties level, not in class level. Also when is `afterIntialize` method fired ? Any idea what would be nice ?

```
@Source, @Schema, @HasOne, @HasMany, @BelongsTo, @HasManyToMany - I guess they are needed
@SkipAttributes, @SkipAttributesOnCreate, @SkipAttributesOnUpdate, @AllowEmptyStringValues - maybe they too
Maybe also @Whitelist - if added all save/create/update will use this whitelist, if we dont provide any.
```

Pretty much all functions which we are using in initialize method.

Also i think with new validation it would be nice to add property `validator` to model, which we can access and this way add new validators using annotations on properties ?

**Comment by virgofx** [comment]
@Jurigag Having these out of the box would be helpful; however, you could easily extend the annotations initializer to provide needed behavior (That's what I do on various projects)

**Comment by Jurigag** [comment]
@sergeyklay 

Well i think i can add handling all of those annotation and parsing them in https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/metadata/strategy/annotations.zep
But firstly i want to add more database types for ```@Column``` than those already built-in.

That's all for devtools to generate(that's why i want add more types, like most of them) whole database using annotations from models.

But im not sure https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/metadata/strategy/annotations.zep - is it good place to do it there ? Or maybe totally diffrent option in modelsManager ? But it will do just the same i guess ?

**Comment by sergeyklay** [comment]
In my opinion concentrating all this in one place - MetaData/Strategy/Annotations - is best choice. But this should be discussed.
