### ISSUE TITLE
regex in router not work

### ISSUE THREAD

**Issue by Myrai** [phalcon/cphalcon#11315]
regex in pcre also [alias|also] not work.
What this a bug?

**Comment by Myrai** [comment]
$router->add("/status/{statusname:[fail|next]}", array('controller' => 'index', 'action' => 'status'));
or more neeed? What i can also give up?

**Comment by Jurigag** [comment]
What this regex even mean ?

**Comment by Myrai** [comment]
you haven't search?
http://php.net/manual/en/regexp.reference.alternation.php

**Comment by Jurigag** [comment]
Well i tested it and got compilepattern. If you type it like this:

'/status/{statusname:fail|next}' then preg_match from '/status/fail' returns true - but phalcon still cannot handle this for some reason. Here code to test on micro app:

```
$app = new \Phalcon\Mvc\Micro();
$app->getRouter()->setUriSource(Router::URI_SOURCE_GET_URL);
$app->get('/status/{statusname:fail|next}',function($statusname){
    var_dump('test'); // not dumped, so not handled
});
/** @var Route[] $routes */
$routes=$app->getRouter()->getRoutes();
$uri=$app->getRouter()->getRewriteUri();
$pattern="";
foreach($routes as $route){
    $pattern=$route->getCompiledPattern();
}
var_dump($pattern); // returns '#^/status/(fail|next)$#u'
var_dump($uri); // returns '/status/fail'
var_dump(preg_match($pattern,$uri)); // returns 1
```

Pretty weird

**Comment by SidRoberts** [comment]
Try round brackets:

    {order:(hot|new|top|rising|controversial)}

**Comment by Jurigag** [comment]
Phalcon add round brackets himself in compiled pattern.

**Comment by Jurigag** [comment]
Oh i forgot handle xD

**Comment by Myrai** [comment]
Oh, really.. Last example work.
few offtop, how used part of additional match whose not always? e.g. paginator, within /status/fail/page/1..

**Comment by Jurigag** [comment]
Just add new routes BEFORE this:

$router->add("/status/{statusname:fail|next}/page/{page:[0-9]+$}", array(
    'controller' => 'index',
    'action'     => 'status'
));

**Comment by Myrai** [comment]
And have ~20 address route with pagination and 25-30 address without?
Don't fine for me.

**Comment by Myrai** [comment]
may close topic.
