### ISSUE TITLE
Cannot store number 0 by file cache

### ISSUE THREAD

**Issue by zxz054321** [phalcon/cphalcon#11322]
like these codes:

    $cache = new BackFile(
                new FrontOutput(["lifetime" => 6 * 3600]),
                ['cacheDir' => $dir]
    );
    
    $cache->save('counter', 0);	

Phalcon will only create an **empty** file named **counter**
A **0** should be placed in the file!

Environment
 - Windows 10
 - XAMPP
 - Phalcon 2.0.9

**Comment by sergeyklay** [comment]
Fixed in `2.0.x`
