### ISSUE TITLE
Fatal error: Class 'redis' not found

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#11327]
I use modelsCache such way:

```
	$di->setShared('modelsCache', function () {
	  $frontCache = new DataFrontend([
		  'lifetime' => 3600 * 24 * 7
	  ]);
  
	  $redis = new \Phalcon\Cache\Backend\Redis($frontCache, [
		  'host' => $this->get('config')->redis->host,
		  'port' => $this->get('config')->redis->port,
		  'auth' => $this->get('config')->redis->password
	  ]);
  
	  return $redis;
	});

```
and I got error:

```
	Fatal error: Class 'redis' not found in /home/www/apps/models/entities/Company/Company.php on line 421
```
This line is:

```
	$company = Company::findFirst([
            'cache' => 'company_cache_key'
	]);
```

This code return true:
```
	class_exists('\Phalcon\Cache\Backend\Redis');
```

I suspect there is problem with some Phalcon Framework class which handle Redis. But I have no idea how to fix it. Other libraries which use Redis work fines, generally Redis server works good. Any idea?

**Comment by Jurigag** [comment]
For me its working. What version of phalcon you are using ? I wrote you in forum how you can find reason for this error, use gdb, put this code in cli, and then you will have whole stack in php enviroment.

**Comment by SidRoberts** [comment]
What distribution/OS are you using? If you're on Debian/Ubuntu, you'll need to install the php5-redis package. Other distributions might have a different package name.

**Comment by Zaszczyk** [comment]
It works, thank You very much!
