### ISSUE TITLE
Database connection is not closed on the end of a request

### ISSUE THREAD

**Issue by wiesl** [phalcon/cphalcon#11337]
See: https://forum.phalconphp.com/discussion/10005/database-connection-is-on-closed-on-the-end-of-a-request

Hello,

First of all Phalcon is a great framework.

I'm having the problem that database connections are not closed when the request ends. DB Backend is PostgreSQL and PGPool II beforehand. I'm using php-fpm too, so there is a resource leak with open DB connections. Also when e.g. PGPool is restarted dangling and not useable useable connections are kept. Therefore all request before the reconnect fail (e.g. when pgpool oder postgrs is restarted).

I verified it with a new super class that close is not called (see below).
- `MyPostgresql::__construct()`
- `MyPostgresql::connect()`

According to the docs it should be closed on the end of the request: https://docs.phalconphp.com/en/latest/api/Phalcon_Db_Adapter_Pdo_Postgresql.html

`public close()` inherited from `Phalcon\Db\Adapter\Pdo` Closes the active connection returning success. Phalcon automatically closes and destroys active connections when the request ends

```
 'persistent' => 'false',
```

Version is latest stable from git repo.

Any help would be fine, if it is a bug would be great if you could fix it.

Thnx.

Ciao,

Gerhard

``` php
class MyPostgresql extends Postgresql {

/**
 * Creates the Adapter
 */
public function __construct(array $descriptor)
{
    error_log("MyPostgresql::__construct()");
    parent::__construct($descriptor);
}

/**
 * Connect
 */
public function connect($descriptor=null)
{
    error_log("MyPostgresql::connect()");
    return parent::connect($descriptor);
}

/**
 * Close
 */
public function close()
{
    error_log("MyPostgresql::close()");
    return parent::close();
}

}
```

**Comment by PolDeveloper** [comment]
Hello there!
I have similar problem with not closing MySQL connections.
I have wrote a test class like above:
`<?php

class MySQL extends \Phalcon\Db\Adapter\Pdo\Mysql {

/**
 * Creates the Adapter
 */
public function __construct(array $descriptor)
{
    error_log("MySQL::__construct()", 3, "xxxx/public/logs/error-log.log");
    parent::__construct($descriptor);
}

/**
 * Connect
 */
public function connect($descriptor=null)
{
    error_log("MySQL::connect()", 3, "xxxxx/public/logs/error-log.log");
    return parent::connect($descriptor);
}

/**
 * Close
 */
public function close()
{
    error_log("MySQL::close()", 3, "xxxx/public/logs/error-log.log");
    return parent::close();
}

}`
My credits are:

>

>  Oprogramowanie: MySQL
> Wersja oprogramowania: 5.6.30-76.3-log - Source distribution
> 
> PHP Version 5.6.19
> 
> Author   Phalcon Team and contributors
> Version   2.0.9
> Build Date   Nov 30 2015 09:47:49
> Powered by Zephir   Version 0.8.0a
> 
> mysql.allow_local_infile   On   On
> mysql.allow_persistent   On   On
> mysql.connect_timeout   60   60
> mysql.default_host   no value   no value
> mysql.default_password   no value   no value
> mysql.default_port   no value   no value
> mysql.default_socket   no value   no value
> mysql.default_user   no value   no value
> mysql.max_links   Unlimited   Unlimited
> mysql.max_persistent   Unlimited   Unlimited
> mysql.trace_mode   Off   Off

My connect's credits are:
`use xx\Backend\Models\MySQL;

  public function mysqltestAction()
      {
$dane = array(
                   "host" => "fal",
                   "dbname" => "con",
                   "username" => "fal",
                 "password" => "con",
               
              

      );
          $mysql = new MySQL($dane);
          //I run connect() and following Phalons's comment it should be closed by close()
      }`
When I run this class in my Controller my logs are:

> MySQL::__construct()MySQL::connect()

By the way, when I run:`$mysql = new MySQL($dane);
$mysql->close();`

I get what it should be:

> MySQL::__construct()MySQL::connect()MySQL::close()

First question how you suggest to deal with this sleeping MySQL processes, my host provider says that my project have too many of this and my efficiency of project is getting lower nad lower?

The second please test this close() method in this very cool framework.

Kind regards

Mike

**Comment by Ange7** [comment]
I have similar problem with not closing MySQL connections. and the script to reproduce is the same that @PolDeveloper
