### ISSUE TITLE
Versions of Phalcon Until 2.1

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11333]
How many version of Phalcon from 2.0.9 until 2.1 stable released ?

**Comment by andresgutierrez** [comment]
For questions like these please use the forum: http://forum.phalconphp.com/, Github is only intended to report bugs and discuss new features. Phalcon 2.1 is currently almost stable except for the support of PHP7.

**Comment by tuxy** [comment]
I actually think this should be posted in issues. At least tell us if this will happen this year ^_^
