### ISSUE TITLE
[BUG] New record, PostgreSQL and the Primary key

### ISSUE THREAD

**Issue by tema87** [phalcon/cphalcon#1134]
Test table in postgres:

``` sql
CREATE TABLE robots
(
  id serial NOT NULL,
  name character varying,
  CONSTRAINT robots_pkey PRIMARY KEY (id)
);
```

Model:

``` php
class Robot extends \Phalcon\Mvc\Model
{
    public function getSource()
    {
        return 'robots';
    }
}
```

Scenario №1:

``` php
$robot = new Robot();

$robot->name = uniqid();

$robot->save();
```

result: OK

Scenario №2

``` php
$robot = new Robot();

$robot->id = 666; // predefined primary key
$robot->name = uniqid();

$robot->save();
```

result: "PDOException: SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR: currval of sequence "robots_id_seq" is not yet defined in this session"

Scenario №3

``` php
$robot = new Robot();

$robot->id = $robot->getReadConnection()->fetchOne("SELECT NEXTVAL('robots_id_seq') as id")['id']; // predefined primary key from sequence
$robot->name = uniqid();

$robot->save(); //OK
//but:
$robot->refresh();
```

result: "Phalcon\Mvc\Model\Exception: The record cannot be refreshed because it does not exist or is deleted"
##

**Comment by mk-evergreens** [comment]
+1

**Comment by andresgutierrez** [comment]
Can you try again using Phalcon 2?

**Comment by temuri416** [comment]
+1

@andresgutierrez 

As much as I would love to switch to Phalcon 2, it's not really an option at the moment.

Any chance you could look at it?

Thanks!

**Comment by andresgutierrez** [comment]
@temuri416 if this is happening in Phalcon 2 then yes

**Comment by temuri416** [comment]
I see... No more bugfixes in 1.3.x then?

**Comment by andresgutierrez** [comment]
No, Phalcon 1.3.x is no longer maintained

**Comment by MikkelPaulson** [comment]
@andresgutierrez This is confirmed still happening as of 2.0.6. I was able to work around it by adding this to a trigger function that was already defined for that table:

    PERFORM NEXTVAL('tablename_id_seq');

From my research, this is a known quirk of Postgres, and the general consensus is "just ignore it". Simply removing this exception should suffice.

**Comment by MikkelPaulson** [comment]
MUCH better workaround: put this in your model.

    public static function getSequenceName() {
        return null;
    }

Bam!

**Comment by Chameleon-m** [comment]
+1 
test - 2.0.6 and 2.0.9 (7cd81ef3c04f660f2d901aa285c051ec8f44c0a1)

**Comment by dreamsxin** [comment]
@temuri416 You can try use this branch https://github.com/dreamsxin/cphalcon，My project use phalcon 1.3, so will continue to maintain.

**Comment by phackwer** [comment]
People, this is a PHP Bug since it does not use postgres' LASTVAL() to retrieve function on the lastInsertId() method of PDO_PGSQL.

(https://github.com/php/php-src/blob/master/ext/pdo_pgsql/pgsql_driver.c#L375)

I will send them the bugfix but it will be avaliable only for PHP 5.6 and 7.x.

I just made a workaround for Doctrine and I'm waiting for the pull request approval.

https://github.com/doctrine/dbal/pull/2328
https://github.com/doctrine/dbal/pull/2329

**Comment by kimonniez** [comment]
Regards to first post.
PDOException: SQLSTATE[55000] connected with primary key. If you dont have PK you will catch this exception
