### ISSUE TITLE
Phalcon PHP 2.0.9 uses PHP5.4 methods

### ISSUE THREAD

**Issue by collinsmao** [phalcon/cphalcon#11350]
#11129
I'm using wamp on windows,php version 5.3.29,Phalcon 2.0.9 - Windows x86 for PHP 5.3.9 (VC9) 

when running $this->session->set("user-name", "Michael") in a action,it's throw a exception:
Call to undefined function session_status()
#0 [internal function]: Phalcon\Session\Adapter->status()

uh,  phalcon2.0.7.dll  works well,, but zephir source code seems that they look exactly the same

**Comment by mattvb91** [comment]
As far as im aware 5.3 is no longer supported?
https://github.com/phalcon/cphalcon#requirements

**Comment by sergeyklay** [comment]
Have you tested this? https://github.com/phalcon/cphalcon/issues/11129#issuecomment-165700792

**Comment by sergeyklay** [comment]
The 2.0.x branch is not longer supported.
