### ISSUE TITLE
Service 'Module' wasn't found in the dependency injection container - windows 7 - 64bit

### ISSUE THREAD

**Issue by joeltejdeep** [phalcon/cphalcon#11364]
In my Windows 7, I'm facing the issue, after adding a new module from devtool.
Phalcon version 2.0.9 (latest). please help.

Steps I done:
-- I created project name as "test_project", type=module using devtool
-- Then I created a new module called "Admin", using devtool
-- I created IndexController and view in the Admin module 
-- When I tried to run admin module, I'm getting the error

```
Service 'Test_project\Admin\Module' wasn't found in the dependency injection container
#0 [internal function]: Phalcon\Di->get('Test_project\\Admin\\...')
#1 D:\wamp\www\test_project\public\index.php(36): Phalcon\Mvc\Application->handle()
#2 {main}
```

**Comment by sergeyklay** [comment]
This is [Devtools](https://github.com/phalcon/phalcon-devtools) issue, not Phalcon. Create please issue at Devtools repo

**Comment by joeltejdeep** [comment]
Ohhh.. Okay. Thank you.
