### ISSUE TITLE
Model generated from dev tools puts wrong setSource

### ISSUE THREAD

**Issue by davidgrenier** [phalcon/cphalcon#11367]
Hello,

When generating a model from the phalcon dev tools 2.0.9, it defines both getSource():

```php
    public function getSource()
    {
        return 'Accounts';
    }
```

And setSource in initialize:

```php
    public function initialize()
    {
        $this->setSource("'Accounts'");
    }
```

Notice how Accounts in setSource is surrounded by single quote.

It eventually generates the following query:

```sql
SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = ''accounts'' AND `TABLE_SCHEMA` = DATABASE()
```

Where you can see that the table name is surrounded by single quotes as well. Now I tested this after removing what I believe was a redundant getSource and not with it so I don't know if it would behave correctly with getSource.

David

**Comment by sergeyklay** [comment]
Hi. This is [Devtools](https://github.com/phalcon/phalcon-devtools) issue not Phalcon. Can you please create issue at Devtools repo?

**Comment by davidgrenier** [comment]
Will do, thanks!
