### ISSUE TITLE
View property

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11365]
Hello.
I use Phalcon 2.1.0.beta2 - Windows x86 for PHP 5.6.0 (vc11) 
```php
public function indexAction()
{
	return  $this->view->render('welcome', 'index', [
		'name' => 'hello world',
	]);
}
```
I can't get access the property name in view
Notice: Undefined variable: name in C:\xampp\htdocs\phalcon\app\module\view\welcome\index.phtml on line 4
Can anybody help me?

**Comment by googlle** [comment]
@sergeyklay Can you help me?

**Comment by sergeyklay** [comment]
```php
$this->view->setVars(['name' => 'hello world']);
$this->view->render('welcome', 'index');
```

**Comment by googlle** [comment]
@sergeyklay I made a mistake.
If I want the above code worked, I have to use Phalcon\Mvc\View\Simple instead of Phalcon\Mvc\View
