### ISSUE TITLE
Acl inherit

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11361]
Hello. When I use Acl with inherit get warning message.

```
Warning: Illegal offset type in C:\xampp\htdocs\phalcon\app\module\Acl\Acl.php on line 69

Notice: Array to string conversion in C:\xampp\htdocs\phalcon\app\module\Acl\Acl.php on line 69
Role 'Array' (to inherit) does not exist in the role listArray
```

This my code

``` php
$acl = new AclList();

$roles = array(
    'guest' => null,
    'member' => 'guest',
    'user1' => 'member',
    'user2' => 'member',
    'editor' => array('user1', 'user2'),
    'admin' => 'editor',
);

foreach ($roles as $name => $parent) {
    $acl->addRole(new Role($name), $parent);
}
```

Can I use array for inherit?

**Comment by Jurigag** [comment]
I guess you could if you would add something like this:

foreach ($roles as $name => $parent) {
    if(!is_array($parent)){
        $acl->addRole(new Role($name), $parent);
    }
    else{
        foreach ($parent as $role){
            $acl->addrole(new Role($name), $role);
        }
    }
}

But im not sure if you can have role which intherit more than 1 role.

**Comment by googlle** [comment]
@Jurigag, In the method "addRole" on line 158 https://github.com/phalcon/cphalcon/blob/master/phalcon/acl/adapter/memory.zep#L158, 
param "accessInherits" maybe array (@param  array|string accessInherits)
So, maybe it's a bug

**Comment by Jurigag** [comment]
Yes, but it doint chck if its array in addInherit and doesnt doing foreach.
