### ISSUE TITLE
Relation::NO_ACTION does not have any affect saving/updating in relationship

### ISSUE THREAD

**Issue by josefguenther** [phalcon/cphalcon#11379]
Consider a relationship for a `Robot`:

```
$this->hasMany('id', 'Parts', 'robot_id', array(
    'foreignKey' => array(
        'action' => Relation::NO_ACTION
    )
));
```

There is a reciprocal relation in the `Parts` model:

```
$this->belongsTo('robot_id, 'Robot', 'id', array(
    'alias' => 'robot'
));
```

If I create a part on Robot 1, something like this:

```
$part = new Parts();
$part->robot = $robot;
$part->save();
```

It will still generate the following database queries:
`UPDATE robot....`
`INSERT INTO parts....`

How can I get rid of the first `UPDATE` database query? I was of the impression that `Relation::NO_ACTION` would prevent this.

Note that I also tried adding the `Relation::NO_ACTION` to the belongsTo relationship with no change.

**Comment by jkns** [comment]
Any update on this? I've tried the same and noticed it's not working. Is there any other way around this?
