### ISSUE TITLE
Gettext translations not working

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11375]
In module/Module.php
```php
$di->setShared('translate', function() {
	$translate = new \Phalcon\Translate\Adapter\Gettext(array(
		'locale' => 'ru_RU',
		'file' => 'messages',
		'directory' => __DIR__ . '/locale'
	));
	return $translate;
});
```
In controller 
```php
$translate = $this->di->get('translate');
$this->view->setVar('translate', $translate);
```
My file is located in this directory module/locale/ru_RU/LC_MESSAGES/messages.mo
Poedit found and translated strings
But in view (index.phtml) translation does not work
```php
<?php echo $translate->_('Hello') ?>
```
I recently started to learn Phalcon. Can you help me?

**Comment by sergeyklay** [comment]
https://forum.phalconphp.com/discussion/10159/problem-with-gettext

**Comment by googlle** [comment]
@sergeyklay Thanks
