### ISSUE TITLE
Router overrides custom defined parameters with path information

### ISSUE THREAD

**Issue by josefguenther** [phalcon/cphalcon#11378]
I have the following route:

```
$router->addGet('/test/{id:[0-9]+}', array(
    'controller' => 'test',
    'auth' => true,
    'action' => 'get'
));
```

I am expecting the following parsed parameters:

```
$this->dispatcher->getParams();

array (size=2)
  'auth' => boolean true
  'id' => string '2' (length=1)
```

However, here is the actual result (auth set to TRUE):

```
array (size=2)
  'auth' => string '2' (length=1)
  'id' => string '2' (length=1)
```

If 'auth' is set to FALSE, then I get the following:

```
array (size=2)
  'auth' => string '/test/2' (length=7)
  'id' => string '2' (length=1)
```

**Comment by josefguenther** [comment]
I should clarify I am using default settings for `Phalcon\Mvc\Router` and `Phalcon\Mvc\Dispatcher`.

**Comment by daison12006013** [comment]
@josefguenther, this thing only occurs when using wildcard param, but if you have a static it seems it is fully working fine.

you could try '/test/{id}' I think for now..

**Comment by josefguenther** [comment]
Do you mean a regex pattern? I am not using a wildcard in my path.

**Comment by dzubchik** [comment]
@josefguenther , this is already fixed in 2.1.x branch (see phalcon/mvc/router at 519 line):
```zephir

    if typeof position != "string" && typeof position != "integer" {
                continue;
    }
```

**Comment by josefguenther** [comment]
I looked at the file... I cannot say I'm convinced that fixes anything. Also what if `auth` in my example was set to a string or an integer? Perhaps we need to make a unit test to determine if this was resolved.

**Comment by dzubchik** [comment]
@josefguenther , the behavior of router in 2.1.x is to check custom parameters (except module, controller ,action) values and map them on matched regex pattern only if position (value)  is integer or string. I agree, that this should be covered by unit test.
