### ISSUE TITLE
Different behavior of similar methods in validation

### ISSUE THREAD

**Issue by Studentsov** [phalcon/cphalcon#11405]
The getMessages methods of Models and Forms return different data types. Models return an array, and forms return object like Phalcon\Validation\Message\Group which any more not to transfer in Flash. Whether these methods to return identical data type owe?

**Comment by sergeyklay** [comment]
Since Phalcon 2.1.x `Phalcon\Mvc\Model\Validation` is deprecated  in favor of [Phalcon\Validation](https://docs.phalconphp.com/en/latest/reference/validation.html). 

The functionality of both components is merged into one, allowing us to reduce the codebase while offering the same functionality as before.

Previously validations were implemented as follows:
```php
namespace Invo\Models;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Validator\Email as EmailValidator;
use Phalcon\Mvc\Model\Validator\Uniqueness as UniquenessValidator;

class Users extends Model
{
    public function validation()
    {
        $this->validate(
            new EmailValidator(
                [
                    'field' => 'email',
                ]
            )
        );

        $this->validate(
            new UniquenessValidator(
                [
                    'field'   => 'username',
                    'message' => 'Sorry, That username is already taken',
                ]
            )
        );

        if ($this->validationHasFailed() == true) {
            return false;
        }
    }
}
```

Introducing Phalcon\Validation, you will need to change the above to:
```php
namespace Invo\Models;

use Phalcon\Mvc\Model;
use Phalcon\Validation;
use Phalcon\Validation\Validator\Email as EmailValidator;
use Phalcon\Validation\Validator\Uniqueness as UniquenessValidator;

class Users extends Model
{
    public function validation()
    {
        $validator = new Validation();

        $validator->add(
            'email',
            new EmailValidator()
        );

        $validator->add(
            'username',
            new UniquenessValidator(
                [
                    'message' => 'Sorry, That username is already taken',
                ]
            )
        );

        return $this->validate();
    }
}
```

You will agree that this change makes the code much smaller and easier to read.

**Comment by Studentsov** [comment]
Your code does not work =)
But `return $this->validate($validator);` is work.
Unfortunately, you did not understand my question, I think.
Phalcon\Mvc\Model:
`public function getMessages(var filter = null) -> <MessageInterface[]> { //... }`
Phalcon\Forms\Form:
`public function getMessages(boolean byItemName = false) -> <Group> { //... }`
Same as intended methods return different types of data. I just think it's wrong.

**Comment by sergeyklay** [comment]
> But return $this->validate($validator); is work.

Where? Phalcon 2.1.x?


> Unfortunately, you did not understand my question, I think.

Ah, yes. I inattentively read

**Comment by Studentsov** [comment]
Yes, Phalcon 2.1.0.RC1.
https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/model.zep
line 1373-1412

**Comment by sergeyklay** [comment]
Well, I copypasted the example from the blog. The Blog's example contains a misspelling. I fixed my answer. In general I think your observation is logical. We should have a common interface for both cases.
