### ISSUE TITLE
Routing doesn't use modificator.

### ISSUE THREAD

**Issue by Myrai** [phalcon/cphalcon#11400]
http://php.net/manual/en/reference.pcre.pattern.modifiers.php
doesn't work.
`/test/{name:[a-z\040]/x}` `/test/{name:a-z\040/x}` `/test/{name:(a-z\040)/x}` `/test/{name:(a-z\040/x)}`
P.S. how use pattern \p{Greek} with flag?

**Comment by dzubchik** [comment]
@Myrai, don't you forget to add '+' sign https://regex101.com/r/eI6iE6/1? Also, your regex for url has no sense, because all text after \# is only visible for browser. And, please, write what you write, what you get and what you expected.

**Comment by dzubchik** [comment]
@Myrai , do you still have problems with this issue?
