### ISSUE TITLE
please support returning id

### ISSUE THREAD

**Issue by wolftail** [phalcon/cphalcon#11407]
when i use pgbouncer with transaction mode,  it will report lastInsertId method error. from postgres 8.4 , it support use "returning id" append to insert sql to get create record id. thank you!

**Comment by sergeyklay** [comment]
@wolftail Could you please explain a bit more?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
