### ISSUE TITLE
Some questions about the JSON PostgreSQL field query

### ISSUE THREAD

**Issue by dengsgo** [phalcon/cphalcon#11413]
In the latest version of PostgreSQL, adding some new JSON operations, such as modification, deletion, etc.. But these operations can not be used in Phalcon, such as:

```
$a = Member::find([
        'job@>?',
        'bind' => [ '{"jobcode":0}' ]
]);
```

Phalcon throws an exception: Scanner: Unknown opcode 405. This should be how to solve? thanks.

**Comment by hihuazi** [comment]
the same issue

**Comment by hihuazi** [comment]
Using Raw SQL https://docs.phalconphp.com/zh/latest/reference/phql.html

**Comment by baurzhan** [comment]
Same issue with range include operator @>

**Comment by Jurigag** [comment]
You need to use raw sql or add dialect extension.

**Comment by mvc089** [comment]
This issue is with "@>". Tried RAW sql as well but got the same error.
