### ISSUE TITLE
Cannot set session variable in micro application

### ISSUE THREAD

**Issue by luqmanrom** [phalcon/cphalcon#11411]
I am creating api that will be using Phalcon Micro. But, I have some issues when trying to set the session variable. 

```php

$app->before(function() use ($app) {

	$app['session']->set("message","Hello World");
	
	if ($app['session']->has('message')) {
		echo 'Session message exist';
	} else {
		echo 'Session not exist';
	}	
	return true;
});

```

It seems the session variable of message is not set.

**Comment by sergeyklay** [comment]
Provide please session bootstrap

**Comment by luqmanrom** [comment]
There is minor error on my side. Everything supposed to works fine. Thanks!
