### ISSUE TITLE
Phalcon\Validation\Validator\Regex not work properly

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#11414]
I have form with such code:

```
$this->addValidators([
            new Regex([
                'pattern' => '/\d+/',
                'message' => 'At least one digit.'
            ]),
        ]);
```

Form validator return message for strings like: phalcon1, 1phalcon, 1phalcon1 and a lot other which contain digits. 
Regex tester: https://regex101.com/r/aP0zH4/1

PHP 5.6
Phalcon 2.1.x

**Comment by dzubchik** [comment]
@Zaszczyk , you have expected that validator will work as default preg_match behavior, but it does not. You can dive a little bit deeper into phalcon and find out this code:

```zephir
let matches = null;
		let value = validation->getValue(field);

		if preg_match(this->getOption("pattern"), value, matches) {
			let failed = matches[0] != value;
		} else {
			let failed = true;
		}

		if failed === true {
                        //...
			return false;
		}

		return true;
```

It seems that validator is correct only when your regex full match value. Here are examples:

```php
<?php


function regex($pattern, $value)
{
    $matches = null;
    if (preg_match($pattern, $value, $matches)) {
        $failed = $matches[0] != $value;
    } else {
        $failed = true;
    }

    return !$failed;
}

var_dump(regex('/\d+/', 'phalcon1'))."\n"; // false
var_dump(regex('/\d+/', '1phalcon1'))."\n"; // false
var_dump(regex('/(phalcon)(\d+)/', 'phalcon1'))."\n"; // true
var_dump(regex('/([a-z]+)(\d+)/', 'phalcon1'))."\n"; // true
```
In your case, you can simply replace regex with this pattern - ``` /(.*)\d(.*)/```. More examples: https://regex101.com/r/aP0zH4/2.

**Comment by Zaszczyk** [comment]
Thank You for an explanation.

**Comment by jellisii** [comment]
Perhaps some more information in the Regex validation documentation would be appropriate concerning the exact nature of how it operates?  I just lost 2 hours to a similar problem.

**Comment by sergeyklay** [comment]
@jellisii Could you send a PR with docs improvements?
