### ISSUE TITLE
Constructors in interfaces

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11410]
Any logical reason for some interfaces have ```__construct``` methods ? We cant create objects from interfaces, it's just a contract.

I think we should split constructors from interfaces and create maybe abstract classes with __onconstruct definition which implement those interfaces.

For example - thats why i needed to create so simple interfaces ```RoleAware``` and ```ResourceAware``` beacause ```RoleInterface``` and ```ResourceInterface``` have ```__construct``` methods, and then you cant have for example class extending ```Model``` and ```RoleInterface```.

I know its php, but i think there shouldn't be constructors in interfaces, well i think even magic methods should go away.

Well i know its not thing for change for any minor version. But it's thing to consider in next major version(3.x).

**Comment by valVk** [comment]
Just for reference.

[https://github.com/phalcon/cphalcon/blob/master/phalcon/acl/roleinterface.zep#L33](roleinterface.zep)

[https://github.com/phalcon/cphalcon/blob/master/phalcon/acl/resourceinterface.zep#L34](resourceinterface.zep)

Interfaces do not must have constructors.

**Comment by sergeyklay** [comment]
Fixed in `2.1.x` branch
