### ISSUE TITLE
[DOC] Model events are documented inconsistently/incompletely

### ISSUE THREAD

**Issue by ioncube** [phalcon/cphalcon#11434]
While many events are documented in easy to locate and digest tables, a few events are documented only in passing so as to be easily missed or not understood when their use is seen.

`validation()` is introduced with text:

> The special “validation” event

but omitted from the useful table of related events. 

`afterFetch()` is inconsistently introduced with text:

> You can implement the method ‘afterFetch’ in a model

and again does not appear in any table of events.

A section in the guide with a summary of all events categorised by related class/section and perhaps then by subcategory would be very useful to aid newcomers in getting an overview of the flexibility of phalcon, and also as an ongoing reference guide. If events are also documented in one or more tables within a particular section such as they are with Model, then all events must be documented and the tables directly accessible from the page contents.

**Comment by sergeyklay** [comment]
@ioncube For doc related issues use please https://github.com/phalcon/docs repo
