### ISSUE TITLE
[bug] install failed on debian testing

### ISSUE THREAD

**Issue by codesaler** [phalcon/cphalcon#11435]
os: debian testing (latest)
Linux 4.4.0-1-amd64 #1 SMP Debian 4.4.2-2 (2016-02-19) x86_64 GNU/Linux
libtool (GNU libtool) 2.4.6

commit cf3c1fe62184d36d24c543c0b4f9993ea8f2445b
git clone --depth=1 git://github.com/phalcon/cphalcon.git
cd cphalcon/build
sudo ./install

output:

[output.txt](https://github.com/phalcon/cphalcon/files/139450/output.txt)

**Comment by Green-Cat** [comment]
You are missing libtool

**Comment by codesaler** [comment]
@Green-Cat 
already installed libtool using:
apt-get install libtool

output as the same.

**Comment by valVk** [comment]
maybe there have to be libltdl-dev

`apt-get install libltdl-dev`

**Comment by codesaler** [comment]
@valVk already installed.
finally, problem solved.
reason: libtool version mismatch.
solution: 
`autoreconf --force --install`
`./configure `
`make`

according to http://stackoverflow.com/questions/3096989/libtool-version-mismatch-error
