### ISSUE TITLE
Phalcon 2.0.10 Documentation

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11439]
https://docs.phalconphp.com/en/latest/index.html

Is this documentation same for version 2.0.10 or you guys just haven't updated it yet ?

**Comment by sergeyklay** [comment]
Still not updated.

@andresgutierrez

**Comment by Green-Cat** [comment]
@sergeyklay fixed.

**Comment by Jurigag** [comment]
Actually it's 2.1.0 @Green-Cat

**Comment by sergeyklay** [comment]
```sh
$ wget -qO- https://docs.phalconphp.com/en/latest/index.html | grep '<title>'
```
