### ISSUE TITLE
[2.1.x] Bug: Phalcon\Forms\Form validation failed

### ISSUE THREAD

**Issue by xuqinjie** [phalcon/cphalcon#11443]
2.08 does not have this bug.

```
class MyForm extends \Phalcon\Forms\Form
{
	public function initialize() {
		$this->setEntity($this);
		$slug = new Text('slug');
		$slug->setFilters(array('striptags', 'trim'));

		$slug->addValidator( new UniquenessValidator(array(
	        'model' => '\MyModel\Post',
	        'message' => 'slug exist!'
    	)));
    	
		$this->add($slug);
	}
}
```

When make validation, it throws the below error:

```
Trying to call method getdi on a non-object
#0 [internal function]: Phalcon\Validation\Validator\Uniqueness->getColumnNameReal('\\MyModel\\P...', 'slug')
#1 [internal function]: Phalcon\Validation\Validator\Uniqueness->isUniqueness(Object(Phalcon\Validation), 'slug')
#2 [internal function]: Phalcon\Validation\Validator\Uniqueness->validate(Object(Phalcon\Validation), 'slug')
#3 [internal function]: Phalcon\Validation->validate(Array, NULL)
#4 ...MyController.php(62): Phalcon\Forms\Form->isValid(Array)
#5 [internal function]: ...
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 ...Phalcon\Mvc\Application->handle()
#8 {main}
```

**Comment by DestinyMKas** [comment]
In 2.0.x there is no getColumnNameReal method. I think this is 2.1.x issue

**Comment by xuqinjie** [comment]
Thanks, title should be 2.1.x

**Comment by sergeyklay** [comment]
@xuqinjie The model always must be initialized. 

This is invalid:
```php
'model' => '\MyModel\Post',
```

This must be an object, model instance, not string.

**Comment by xuqinjie** [comment]
Very strange, This is the documentation.
https://docs.phalconphp.com/zh/latest/api/Phalcon_Validation_Validator_Uniqueness.html

In 2.08 it works very well.

**Comment by xuqinjie** [comment]
@sergeyklay 

Very strange, This is the documentation.
https://docs.phalconphp.com/zh/latest/api/Phalcon_Validation_Validator_Uniqueness.html

In 2.08 it works very well.

**Comment by xuqinjie** [comment]
@sergeyklay 
I tested it again.
```
'model' => new \MyModel\Post //this works in 2.1.x
```

The above code works in 2.1.x but in 2.08, it will throw exception:

Warning: Phalcon\Validation\Validator\Uniqueness::validate(): class name must be a string

**Comment by sergeyklay** [comment]
This is why we'll release major version 2.1

**Comment by sergeyklay** [comment]
@xuqinjie Very strange this
```php
$this->setEntity($this);
```
and then

```php
'model' => new \MyModel\Post
```

**Comment by xuqinjie** [comment]
@sergeyklay 

Thank you very much!
