### ISSUE TITLE
[2.1.x] cache/backend/redis.ze::flush() doesn't clear everything

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#11444]
There is in documentation:

> public flush ()
> Immediately invalidates all existing items.

So I wrote code:
```
$cache = $this->di->get('modelsCache');
$cache->flush();
```
And I was sure this command clear all keys with prefix: '_PHCR*'. But redis monitor logs only:

> 1456319961.645539 [0 127.0.0.1:49139] "AUTH" "6bd49ef85982f53cac98f17a306aad4ef4b5a4beeb24e4d833570a08eebc6af5"
> 1456319961.645804 [0 127.0.0.1:49139] "SELECT" "0"
> 1456319961.646037 [0 127.0.0.1:49139] "SMEMBERS" "_PHCR"

So is it bug in code or in documentation or in my mind? :smile:

**Comment by sergeyklay** [comment]
Fixed in the `2.1.x` branch
