### ISSUE TITLE
[2.0.x] Volt String Manipulation Request

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11440]
Can we please get various string manipulations in volt ?

Things like; ``explode``, ``implode``, ``substr``, ``strstr``.

Something else useful is date/time format.

Thank You.

**Comment by valVk** [comment]
you can extends Volt with any custom function you need

[https://docs.phalconphp.com/en/latest/reference/volt.html#extending-volt](Extending Volt)

**Comment by tuxy** [comment]
What would be the best practice to extend volt ? Do we use separate class for it ? Some examples appreciated. Thank you.

**Comment by sergeyklay** [comment]
For questions like these please use the forum: http://forum.phalconphp.com/, GitHub is only intended to report bugs and discuss new features.
