### ISSUE TITLE
[2.1.x] Relation manyToMany saved double because of afterCreate event

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#11457]
I have model Activity, which has a lot relations, including hasMany and manyToMany:

```
$this->hasMany('id', 'XXX\Models\Entities\Activity\ActivityParameter', 'activity_id', [
            'alias' => 'parameters',
            'reusable' => true,
            'foreignKey' => [
                'action' => Relation::ACTION_CASCADE
            ]
        ]);

$this->hasManyToMany(
            'id',
            'XXX\Models\Entities\Activity\ActivityCollaborator',
            'activity_id', 'collaborator_id',
            'XXX\Models\Entities\User\User',
            'id',
            ['alias' => 'collaborators', 'reusable' => true]
        );
```

User's relation:

```

$this->hasManyToMany(
            'id',
            'XXX\Models\Entities\Activity\ActivityCollaborator',
            'user_id', 'activity_id',
            'FitCompany\Models\Entities\Activity\Activity',
            'id', ['alias' => 'collaboratedActivities', 'reusable' => true]
        );
```

ActivityParameter's relation:

```
$this->belongsTo('activity_id', 'XXX\Models\Entities\Activity\Activity', 'id', [
            'alias' => 'activity',
            'reusable' => true,
            'foreignKey' => [
                'allowNulls' => false,
                'message' => 'The activity doest not exist'
            ]
        ]);

```

and it was working right, I've created new objects and relations were OK. But I added afterCreate event to model Activity with code:

```
public function afterCreate(Event $event, Activity $activity)
{
$aService = new ActivityService();
$activity->parameters = [$aService->getSpecialParameter() $adService->getAnotherSpecialParameter()];

            if (!$activity->save()) {
                $messages = $activity->getMessages();
                throw new CreateEntityException($messages[0]);
            }
}
```

This code adds extra parameters to Activity object and save again new object. After this saving there are duplicated records in databse for collaborators related. For example, when I create new Activity and relate 1 User via collaborators relation, it is stored right, but afterCreate event duplicate relation collaborators for this new Activity object. If I comment afterCreate event, it will work right again.

Is it problem with Phalcon or with my implementation of relations?

PHP 5.6
Phalcon 2.1.x
MariaDB

**Comment by Jurigag** [comment]
How are you passing $event and $activity do afterCreate method ? Well i guess it looks like that $activity in passed parameter dont have stored ID. For now try update() method instead of save().

**Comment by Zaszczyk** [comment]
In Activity::initialize() I have such code:

```
$eventsManager = new Manager();
$eventsManager->attach('model', new ActivityListener());
$this->setEventsManager($eventsManager);
```
and method afterCreate() is in class ActivityListener.
I tried with update() and got:

> Wrong number of parameters
> /vagrant/www/apps/models/listeners/Activity/ActivityListener.php:67
> 0
> #0 /vagrant/www/apps/models/listeners/Activity/ActivityListener.php(67): Phalcon\Mvc\Model\Resultset->update()

I've also checked $activity with xDebug just before $activity->save() and there is id set.

**Comment by sergeyklay** [comment]
var_dump/die detected :smile:

**Comment by Zaszczyk** [comment]
@sergeyklay what do You mean? :smiley:

**Comment by sergeyklay** [comment]
The type of people which always use Xdebug (var_dump/die) for debugging purposes.  :stuck_out_tongue_winking_eye:

**Comment by Zaszczyk** [comment]
@sergeyklay do You have any idea how to debug or fix it?

**Comment by sergeyklay** [comment]
just enable the mind ;)

**Comment by Zaszczyk** [comment]
I enabled far far parts od my mind and added one line:
```
public function afterCreate(Event $event, Activity $activity)
{
$aService = new ActivityService();
$activity = Activity::findFirstById($activity->getId());
$activity->parameters = [$aService->getSpecialParameter() $adService->getAnotherSpecialParameter()];

            if (!$activity->save()) {
                $messages = $activity->getMessages();
                throw new CreateEntityException($messages[0]);
            }
}
```
It sucks but it works, could You present Your idea? ;)
