### ISSUE TITLE
How to use php-devel in php7 

### ISSUE THREAD

**Issue by vinaysikarwar** [phalcon/cphalcon#11461]
I have installed php7 php-devel version php70-php-devel.x86_64. But when running command ./install it is giving error.

Can't find PHP headers in /usr/include/php
The php-devel package is required for use of this command.

**Comment by dzubchik** [comment]
@vinaysikarwar , what OS/distributive do you use? Can you provide more information about you php-devel package installation?

**Comment by vinaysikarwar** [comment]
I do use Amazon Linux with Apache .

**Comment by dzubchik** [comment]
Can not have possibility to check this on Amazon Linux. What repository do you use for php7? Also some useful links for CentOS and **php5** headers problem:
* https://forum.phalconphp.com/discussion/10075/cant-find-php-headers-in-usrincludephpxxxxphp
* http://stackoverflow.com/questions/20827704/phpize-cant-find-php-headers-in-usr-include-php

Do you really have PHP headers in /usr/include/php?

**Comment by dzubchik** [comment]
Also, have you installed all packages listed in phalcon requirements?

``` # yum install php-devel pcre-devel gcc make```

**Comment by vinaysikarwar** [comment]
Php-devel is not installing in php7 .

**Comment by sergeyklay** [comment]
https://webtatic.com/packages/php70/
http://www.servermom.org/install-php-7-centos-ubuntu-debian/3030/
https://hasin.me/2015/12/06/upgrading-php-to-php7-0-in-a-centos-server-with-vesta-cp/
