### ISSUE TITLE
 Cannot use a scalar value as an array 

### ISSUE THREAD

**Issue by kowach** [phalcon/cphalcon#11466]
Problem:
Cannot use a scalar value as an array in [phalcon/mvc/model.zep on line 1070](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L1070)
which produces another error "You cannot serialize or unserialize PDO instances"

```
let num = connection->fetchOne(...)
if num["rowcount"]
```

if `num` is scalar then fetchOne returns an object. If database returns object then my default fetch mode is FETCH_OBJ.

```
$conn = new Phalcon\Db\Adapter\Pdo\Mysql(
...
 'options'  => array(
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ
    )
)
```

If I comment this option, I get no error.

**Comment by rlaffers** [comment]
I have a similar issue. The same error is manifested when calling \Phalcon\Db\Adapter\Pdo::connect() with a connection configuration containing:
```
        'options' => array(
            \PDO::ATTR_CASE => \PDO::CASE_UPPER
        ),
```
In fact, as long as options key is present in the config, the error does not go away.

**Comment by sergeyklay** [comment]
@rlaffers Could you please provide script to reproduce?

**Comment by lightindigo** [comment]
@sergeyklay got exactly the same issue after trying to update **from 2.0.13 to 3.2.2** (tried also 3.2.3, 3.1.x etc) both **building** and getting debian package from **Packagecloud** . The old way of setting default fetch mode (via passing options to Postgresql adapter constructructor as an example) is not working for some reason :( 

Just the same error 

```
Cannot use a scalar value as an array  in phalcon/mvc/model.zep on line 1139
```

The strange thing is that it was thrown while i was doing model->save();

It also seems that the behavior "test if there's a record and create if there none or update existing" not working as it did before :( We were just saving models previously on 2.0.13 without checking existence and it was OK, but now it just throws an error

**Comment by sergeyklay** [comment]
@lightindigo Which database do you use?

**Comment by Druid33** [comment]
Hi, this bug is still active on phalcon 4.2.1

I found that:
1.  if database config has **options** key as last key, i got **ErrorException: Cannot use a scalar value as an array**
2. if **options** config is not last key, i got **RuntimeException: Trying to call method upper on a non-object**. This is probably bug on line here: https://github.com/phalcon/cphalcon/blob/caeac66e7db02fd54c44a27cf22a6381654af2ee/phalcon/db/adapter/pdo.zep#L135

**Comment by sergeyklay** [comment]
@Druid33 Could you please open a new issue

**Comment by cottton** [comment]
I did: https://github.com/phalcon/cphalcon/issues/14330
