### ISSUE TITLE
How I Get The Origin Redis Instance from Phalcon\Cache\Backend\Redis

### ISSUE THREAD

**Issue by smallmenu** [phalcon/cphalcon#11472]
now the Phalcon\Cache\Backend\Redis has the protected _redis,  
i want get the redis origin instance in order to use some other redis commands such as SADD ...
but i don't know how

**Comment by smallmenu** [comment]
may be i should inherit that class and add a new method ?
thanks

**Comment by SidRoberts** [comment]
That's certainly the easiest method. But be aware that if `_connect()` isn't executed first, `$this->_redis` will be null.
