### ISSUE TITLE
[2.1.x] Transaction isManaged returns wrong result

### ISSUE THREAD

**Issue by TheCheat** [phalcon/cphalcon#11488]
Looking at sources Phalcon\Mvc\Model\Transaction:
```c
/**
 * Checks whether transaction is managed by a transaction manager
 */
public function isManaged() -> boolean
{
	return !this->_manager;
}
```

Now it returns if transaction is not managed. Shouldn't it be the other way around? 

P.S. Dat issue ID

**Comment by sergeyklay** [comment]
Fixed in `2.1.x` and `2.0.x`
