### ISSUE TITLE
$request->getQuery() Router Filter

### ISSUE THREAD

**Issue by ghost** [phalcon/cphalcon#11481]
Router filter for getQuery is not working. I wanted to limit (int) to just {1,2} example;

In Router File:

```
$router->add('/books{page:[0-9]{1,2}}', [
    'controller' => 'books',
    'action' => 'index'
]);
```

In Controller File:

```
$current = $this->request->getQuery('page', 'int');
```

Perhaps add this ability to getQuery, as $request->getQuery('page', 'int:1,2')

Workaround for now is to use;

```
$current = substr($current, 0, 2);
```

**Comment by dzubchik** [comment]
@tuxy, do you want to say that regex pattern to which your route converts is not working properly? The regex works, as expected. But, as I understand you want to force attribute length limit. Just try to wrap your route into brackets [] or () and phlacon automatically will wrap it: 
```zephir
        if memstr(pattern, "(") {
			return "#^" . pattern . "$#u";
		}

		// Square brackets are also checked
		if memstr(pattern, "[") {
			return "#^" . pattern . "$#u";
		}

```
I think, you will get what you want.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
