### ISSUE TITLE
\Phalcon\Validation\Validator\Digit returns wrong type of message

### ISSUE THREAD

**Issue by SevaJmurov** [phalcon/cphalcon#11497]
Phalcon digit validator returns Phalcon\Mvc\Model\Message with 'PresenceOf' type and ':field is required' message instead of appropriate fields for numeric validation failure message.
Tested on Phalcon 2.0.10. With code

```
// model validation
 public function validation() {        
        $validator = new Validation();       
        $validator ->add('qty',
        new DigitValidator([
            'message' => ':field must be numeric'
        ]));                             
        return $this->validate();        
    }    
```
which returns 
```
array (size=1)
  0 => 
    object(Phalcon\Mvc\Model\Message)[106]
      protected '_type' => string 'PresenceOf' (length=10)
      protected '_message' => string 'qty is required' (length=15)
      protected '_field' => string 'qty' (length=3)
      protected '_model' => null
```
for non-numeric qty.

**Comment by SidRoberts** [comment]
It would appear that the 'qty' field is marked as NOT NULL in the database.

This is where the 'PresenceOf' validation message is being created: https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model.zep#L1999

You can disable "not null" validations using:

```php
\Phalcon\Mvc\Model::setup(
    array(
        'notNullValidations' => false
    )
);
```

(see https://forum.phalconphp.com/discussion/283/created-at-and-validation#C1144)

**Comment by SevaJmurov** [comment]
Yes, I have this field marked not null in database, however in this case value of qty is not null.
For instance, I will get this message if I type 'hello' in qty field.

**Comment by SevaJmurov** [comment]
It appears that I had 'force casting' db setting enabled and together with NOT NULL in Db column, as you, Sid, correctly said, led to 'required' message. 
So it is my oversight after all.
