### ISSUE TITLE
[NFR] Add setLastModified to Phalcon\Http\Response

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#11491]
You can set the expire time using the public method setExpires (DateTime $datetime).
Can we add a setLastModified also?

**Comment by sergeyklay** [comment]
Implemented in `2.1.x` branch

**Comment by ruudboon** [comment]
👍

**Comment by akashkumardce** [comment]
@jaskaransingh156 - Very Helpful, looking for it since long time. :)
