### ISSUE TITLE
Model hasOne / belongsTo aliases with 2 fields not having 2nd param passed into the query 2.0.*

### ISSUE THREAD

**Issue by michael-langford** [phalcon/cphalcon#11504]
When calling a models alias in phalcon 2.0.\* that has 2 fields in the relationship the 2nd param is not passed into the generated SQL statement:

For example in the following hasOne relationship:

`$this->hasOne(array('email', 'id'), "UserEmail", array('email', 'user_id'), array('alias' => 'verification', 'resuable' => true));`

The SQL generated will be:

`SELECT`email_verify`.`user_id`,`email_verify`.`email`,`email_verify`.`hash`,,`email_verify`.`date_verified`,`email_verify`.`date_created`,`email_verify`.`sent`,`email_verify`.`registered_on`FROM`email_verify`WHERE`email_verify`.`email`= :APR0 AND`email_verify`.`user_id`= :APR1 LIMIT :APL0`

The SQL Variables are:

`{"APR0":"email@domain.com","APR1":null,"APL0":1}`

APR1 should be the ID from the original model but NULL is passed in.

This relationship works in 1.3.4 but does not in 2.0.*.

**Comment by dnapierata** [comment]
I'm having this same issue, only both APR0 and APR1 are both being passed NULL.

**Comment by sergeyklay** [comment]
The `2.x` branch is not longer supported.

**Comment by Jurigag** [comment]
This is actually on 3.0.x too i think https://forum.phalconphp.com/discussion/16399/problem-with-hasmany-composite-key

**Comment by zsilbi** [comment]
I wasn't able to reproduce this issue as this was fixed in https://github.com/phalcon/cphalcon/pull/12076

To make sure, I created a test for `Phalcon\Mvc\Model\Manager::getRelationRecords()` with multiple fields in https://github.com/phalcon/cphalcon/pull/14115

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14115
