### ISSUE TITLE
Paginator - Numbered page links

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11502]
It would be good to add "Numbered page links" in the paginator.
And sets limits "pagesInRange" (Array of pages returned by the scrolling style)

Example paginator.phtml (from zend framework 2)

``` php
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>
```

![img](http://i67.tinypic.com/3brx0.jpg)

**Comment by sergeyklay** [comment]
Could you please elaborate?
