### ISSUE TITLE
[Request] SQL Connection error shows all connection data

### ISSUE THREAD

**Issue by upabove** [phalcon/cphalcon#11508]
Hi.

I think it's mayor issue as some unexperienced programmers (but also experienced) may by mistake upload bugged config file while updating website. On error Phalcon is showing array with full connection data.

On more popular website someone lucky can just copy data and have access (if admin/developer will not change passwords).

More security is always better, so I think that Phalcon should by default hide connection attempt details. I know that there are probably many ways to hide such info, but I still think Phalcon should hide it by default, so no one will make this type of mistake ever.

Hope you can do something about it.

Regards.

**Comment by andresgutierrez** [comment]
Could you please post where the password is being shown?

**Comment by amateurme** [comment]
Page is generated through Developer Tools (multi module):

Output after going to page (for example http://localhost/)
```
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it. 
#0 [internal function]: PDO->__construct('mysql:host=airc...', '(user name appears here', 'user password is here', Array)

#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)

#2 D:\wamp\www\phalc\aircode\apps\frontend\Module.php(88): Phalcon\Db\Adapter\Pdo->__construct(Array)
(...)
```

File is Config.php (apps\frontend\config\config.php)
```
return new \Phalcon\Config(array(
    'database' => array(
        'adapter'  => 'Mysql',
        'host'     => 'localhost',
        'username' => 'user name appears here', 
        'password' => 'user password is here', 
        'dbname'   => 'dbname, 
        'charset'  => 'utf8',
    ),
    'application' => array(
        'controllersDir' => __DIR__ . '/../controllers/',
        'modelsDir'      => __DIR__ . '/../models/',
        'migrationsDir'  => __DIR__ . '/../migrations/',
        'viewsDir'       => __DIR__ . '/../views/',
        'baseUri'        => '/' // /
    )
));
```

And Module.php (apps\frontend\Module.php)
```
/**
         * Database connection is created based in the parameters defined in the configuration file
         */
        $di['db'] = function () use ($config) {
            $config = $config->database->toArray();

            $dbAdapter = '\Phalcon\Db\Adapter\Pdo\\' . $config['adapter'];
            unset($config['adapter']);

            return new $dbAdapter($config);
        };
```

Thanks for fast reaction.

**Comment by andresgutierrez** [comment]
But, that's the PHP's exception backtrace, it isn't generated by Phalcon itself. I think you can add a global try/catch and handle exceptions as here: https://github.com/phalcon/forum/blob/2.0.0/public/index.php#L58-L60

You can catch the exception and log it properly
