### ISSUE TITLE
Paginator problems 2.0.10 - Bad SQL count query generated sometimes 

### ISSUE THREAD

**Issue by michael-langford** [phalcon/cphalcon#11503]
We are getting fatal errors on some calls to the paginator. It is generating SQL count queries that throw errors in MySQL.

Generated:
SELECT COUNT() FROM table
Should be:
SELECT COUNT(*) FROM table

It is only happening on one complex SQL query we are generating that has joins and groups. The same query has no problem in 1.3.4 or 2.0.9

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
