### ISSUE TITLE
Phalcon\Session\Adapter\Redis need index

### ISSUE THREAD

**Issue by Surt** [phalcon/cphalcon#11501]
Scenario: multiple redis adapters (cache, modelsMetadata, session, ModelsCache) all of them with its own index and persistent.

Problem:
Actually, if I use the Redis adapter for session, the session key dance between Redis databases (unless I define persistent = false, wich connects each time :()

Solution: 
Will be great to check for the redis conection and always take and save etc on the defined "index" as in Cache adapter

**Comment by sergeyklay** [comment]
Try latest Phalcon with database index
