### ISSUE TITLE
PHP5-FPM crash, compileAlways = true.

### ISSUE THREAD

**Issue by jcastilloa** [phalcon/cphalcon#11507]
Hi, I am experiencing a similar issue that:

https://github.com/phalcon/cphalcon/issues/1949

Sometimes, PHP5-FPM dies when compiling template. Using phalcon 2.0.10. The problem goes away when I set compileAlways = false.

gdb bt full:

http://pastebin.com/4RsUEWfs

sportsearch.volt:

http://pastebin.com/TQ2yHGaZ

Regards,

**Comment by andresgutierrez** [comment]
Can you try again disabling opcache?

Does this file exist?

```
/CODE/mysite.com/releases/release-199/app/storage/compiled/%%code%%mysite.com%%releases%%release-199%%app%%skins%%default%%club%%widgets%%sportsearch.volt.compiled
```

**Comment by jcastilloa** [comment]
Hi, yes file exist and opcache was disabled (not using opcache).

**Comment by jcastilloa** [comment]
I'm checking other dumps, sportsearch was not the only file with problems.

**Comment by bkirova** [comment]
I have a similar problem: 
PHP: Version 7.0.4 - Zend Engine v3.0.0
Phalcon: Version 2.1.0b
Zephir: Version 0.9.2a-dev
Nginx: Version 1.9.12

Config Volt:

	[
		'stat' => true,
		'compileAlways' => true
	]

compiler.zep Code:

	var compileAlways_typeof;
	...
	let compileAlways_typeof = null;
	...
	if isset options["compileAlways"] {
	       let compileAlways = options["compileAlways"];
	       let compileAlways_typeof = typeof compileAlways;

	       echo "Type Of compileAlways: ";
	       var_dump(compileAlways);
	       echo "Type Of compileAlways_typeof: ";
	       var_dump(compileAlways_typeof);

               if compileAlways_typeof == "boolean"{
                    echo "compileAlways_typeof is boolean\n";
               }

	       if typeof compileAlways != "boolean" {
	               echo "compileAlways is not boolean: ";
	               var_dump(typeof compileAlways);
	               throw new Exception("'compileAlways' must be a bool value");
	       }
	}

Output:
```
Type Of compileAlways: bool(true)
Type Of compileAlways_typeof: string(7) "boolean"
compileAlways_typeof is boolean
compileAlways is not boolean: string(7) "boolean"
```
Error Log:

`"PHP message: 'compileAlways' must be a bool value"`

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/zephir/issues/1217

**Comment by sergeyklay** [comment]
@jcastilloa Could you please check now by using latest Zephir (`master` branch)

**Comment by Jurigag** [comment]
I think @bkirova and @jcastilloa are other issues. @bkirova problem should be fixed now.

**Comment by sergeyklay** [comment]
Yeah, I made a typo. @bkirova Your issue should be solved now

**Comment by bkirova** [comment]
Thanks all!

**Comment by sergeyklay** [comment]
@jcastilloa Could you please provide a script to reproduce?

**Comment by tobispace** [comment]
We experienced the same issue, see:
https://forum.phalconphp.com/discussion/14869/php5fpm-on-nginx-crash-zendzendlanguagescannerc-no-such-file-or-
