### ISSUE TITLE
'afterFetch' for find()

### ISSUE THREAD

**Issue by alitalaghat** [phalcon/cphalcon#11519]
Currently 'afterFetch' only works for findFirst(). It is very usefull if it can use for find() and records fetch by createBuilder.

**Comment by Jurigag** [comment]
For find it works too. You just have to return full objects.

**Comment by alitalaghat** [comment]
My test code is this:
```
use Phalcon\Mvc\Model;

class Test extends Model
{
    public $id;
    public $status;
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'status' => 'status',
        );
    }
    public function afterFetch()
    {
        $this->status = 'test'.$this->id;
    }
}

$objects = Test::find();
foreach($objects as $object){
	echo $object->status;
}
```

But it dosen't work and just echo 'status' column value.

**Comment by Jurigag** [comment]
Are you sure find returns full objects ? Isnt phalcon by default returning those objects as Phalcon\Mvc\Model\Resultset\Simple ? Try to set hydration mode to Resultset::HYDRATE_RECORDS

**Comment by alitalaghat** [comment]
Thanks.
'setHydrateMode(Resultset::HYDRATE_RECORDS)' solved the issue for find() but for createBuilder still it dosen't work.
```
 $test = $this->modelsManager->createBuilder()
            ->from('Test')
            ->getQuery()
            ->execute()
            ->setHydrateMode(Resultset::HYDRATE_RECORDS);
```

**Comment by Jurigag** [comment]
For createBuilder its gonna never works i guess.

**Comment by cottton** [comment]
Having this problem only on calling `ResultSet\Simple::toArray` **directly** after `::find`.

If im getting a simple result set by `::find` and directly call `::toArray`
then `::afterFetch` never gets triggerd.

But if im using an empty `foreach($collection as $item)` then `::afterFetch` gets triggered for all items.

`::find($params)->setHydrateMode(Simple::HYDRATE_RECORDS)` also works.
But i cannot find a description what it actually does (except the obvious) 
and the `::find` returns `ResultsetInterface` which does not provide `::setHydrateMode`. So i would need to place the result into a var to check if is instance of `ResultsetInterface`.

Question:
What is the recommended way to get the `::afterFetch` triggered always on `::find`?

Thanks,
cottton

**Comment by Jurigag** [comment]
It's correct behavior. afterFetch just don't get fired on find.

**Comment by cottton** [comment]
Ok. But shouldnt `::toArray` trigger it - i mean it actually has to get|fetch the entity to be able to return an array.

I tried a bit and atm i see only this solution:

    use Phalcon\Mvc\Model;
    
    # CREATE TABLE test (id int UNSIGNED AUTO_INCREMENT PRIMARY KEY);
    class Test extends Model
    {
        public $id;
    
        public function afterFetch()
        {
            var_dump(__FUNCTION__ . ' ' . $this->id);
            return $this;
        }
    
        public function customFind($parameters = null)
        {
            // return self::find($parameters); does not trigger ::afterFetch
            $collection = self::find($parameters);
            foreach ($collection as $item) {
                // does trigger ::afterFetch
            }
            return $collection;
        }
    }
    
    $model = new Test();
    $collection = $model->customFind();
    $collection->toArray();

But this is a "not so nice" solution. :)
I read about that phalcon does not execute the query until needed.
In such a case it would be executed always.

An suggestions to solve this?

**Comment by Jurigag** [comment]
No it shouldn't beacause you are using toArray on resultset - this is done like this to avoid overhead exactly with hydration, calling afterFetch on all records.

**Comment by vasilp** [comment]
Well, why the discussion goes in direction firing afterFetch when the model is accessed in a loop, after find or something...
As per documentation:

> May be the case that after obtaining a record from the database is necessary to initialise the data before being used by the rest of the application. You can implement the afterFetch() method in a model, this event will be executed just after create the instance and assign the data to it:

Source:
https://docs.phalconphp.com/en/3.0.0/reference/models.html#initializing-preparing-fetched-records

So in short - afterFetch should be called when the model object is materialized and filled in with the columns data. I dont think this will be slow - it is just a callback/event method.
I have the same problem - it is not called after $model::query()->execute()->getFirst();

Why it is not called - I'm considering this as a bug.
OR ... the documentation is wrong.

**Comment by vasilp** [comment]
I would add that I also work with .Net. I find Phalcon very modern and feature rich framework that also have perfect speed, compared with Laravel for example. And that is why I like Phalcon a lot.
But anyway - in Entity Framework there is a callback when the model is materialized (every time, in any case, it is called). And it is used widely. This is its analog and also could be used a lot.

Just a few more suggestions - there also other goodies that could be used, like out of the box validation (decorate with class names for example). The migrations can be made more flexible by having only the changes in each (not having all DB again)...

So Phalcon team, not having such goodies will force the developers to find "tweaks" / hacks / etc. that will make the code that uses Phalcon ugly and out of standard (depending on the skills of the devs). If you give guides to the devs with enough features, they will follow you and the code will be more standard and easy to read as it will be familiar with the rest. And the devs will not need to develop the wheel again and again. Well, that's the idea of a framework, right?

**Comment by Jurigag** [comment]
But this is exactly how it is. Just model object is materialized when accessing it in loop.

**Comment by cottton** [comment]
So if im getting this right then the trigger gets fired if the model gets filled with data(?).

So by calling `::find` the records are caught as array  - simply loaded from server, right?

And on `resultSet::toArray` no models gets created - the data just gets returned as array, right?

I then see the next problem: does `model::toArray` ever gets called on `model::find(...)->toArray` ?

_i could not test it yet_

**Comment by Jurigag** [comment]
The afterFetch is fired when model instance is created, nothing more, nothing less. Model::find doesn't create any model instances, toArray don't too.
