### ISSUE TITLE
Another type of \Phalcon\Db\Profiler

### ISSUE THREAD

**Issue by plamen-paskov** [phalcon/cphalcon#11521]
I'm using the db profiler like this:
- on before db query : start profiler
- on after query : stop the profiler and get last profiler

if thousands queries are run it will cause "allowed memory size limit exceeded". If i reset() the profiler on after query then i will most probably loose the starting times of all queries that the profiler was started for between starting and reseting the current query.

The workaround would be to "array_pop()" the last profile so the memory will become free

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and discussions like this please visit the [official forums](https://forum.phalconphp.com).
