### ISSUE TITLE
Some keywords for models don't support getters/setters

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#11548]
In relation to #11253 some of the keywords don't support getters and setters because Phalcon has conflicting function names. The ones I've found: source and transaction (probably schema too, but I haven't tried that).

**Comment by valVk** [comment]
I've read #11253 issue.

And I disagree that functional words which are used in relational DB have to be used as columns names. it can cause many problems, so I do not see any reasons why they are can be used here. This is really, really, really strange decision.

**Comment by nsossonko** [comment]
So don't use them. Why should your opinion prohibit others from using perfectly ok functionality?

**Comment by Jurigag** [comment]
Its obvious that they dont support them beacause Phalcon\Mvc\Model already have methos like get/setSource, get/setTransaction etc

There is no way to fix it. This problem can occur always. Its not a bug.

**Comment by nsossonko** [comment]
There are ways to fix this (you, in fact, mention some options) and, while it's not necessarily a bug, it's certainly a valid feature request.

**Comment by Jurigag** [comment]
I think it's too much effort for now. Better to focus on finally supporting php 7. I guess in something like version 3 maybe they will think about changing model related things to working without extending classes.

**Comment by nsossonko** [comment]
I could not agree more with the last statement (php 7). Thanks.
