### ISSUE TITLE
[2.0.x] Model.afterCreate event is not fired

### ISSUE THREAD

**Issue by hakimio** [phalcon/cphalcon#11546]
If I add "afterCreate" event listener to my Model definition, it's never called when I save a new model instance using the following steps:

```php
$model = new MyModel();
$model->assign(["field" => "data"]);
$model->save();
```

[This](https://forum.phalconphp.com/discussion/6954/related-models-rollbacks-and-aftercreate-events) forum thread might be related.

**Comment by hakimio** [comment]
Sorry, it seems there was a problem on my end. Please mark this one as invalid/delete it.

**Comment by Jurigag** [comment]
Just close it :)
