### ISSUE TITLE
[NFR] Missing interfaces

### ISSUE THREAD

**Issue by rianorie** [phalcon/cphalcon#11547]
Right now I'm reworking an application and decoupling a lot of code preparing it writing the ever missing unit tests as well. One thing I'm noticing is that a fair number of Phalcon classes don't have interfaces right now, making the tests of my libraries dependent on Phalcon classes rather than mocked objects.

Per @sergeyklay I'm creating an issue here for discussion so we can assess which classes to provide an interface for.

Thoughts? @sergeyklay @andresgutierrez ?

**Comment by SidRoberts** [comment]
What classes do you think should have interfaces?

**Comment by rianorie** [comment]
Honestly, from the point of view that a framework provides a service,
especially a framework what intents to be used as decoupled as phalcon I
think every class should have an interface. Even the ones you normally
don't expect one for.

**Comment by Jurigag** [comment]
http://www.w3schools.com/sql/func_datediff_mysql.asp

**Comment by sergeyklay** [comment]
* [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle)
* [Design by contract](https://en.wikipedia.org/wiki/Design_by_contract)

**Comment by Jurigag** [comment]
https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

So i think all classes which have similar functionallity should have interfaces - so for example we are missing inetfaces for Phalcon\Config. If we have only one class which have soem functionnality - no point implementing interface for it. At least no point if it's not injected anywhere in the phalcon to other methods.

**Comment by rianorie** [comment]
I would in the long run want to move towards a full dependency injection
based framework rather than the heavy usage of the di container.

Is we start implementing the design by contract principles that would be a
huge start towards decoupling the different parts of phalcon from each
other.

https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

So i think all classes which have similar functionallity should have
interfaces - so for example we are missing inetfaces for Phalcon\Config. If
we have only one class which have soem functionnality - no point
implementing interface for it. At least no point if it's not injected
anywhere in the phalcon to other methods.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/phalcon/cphalcon/issues/11547#issuecomment-198752434>

**Comment by Jurigag** [comment]
Yea but some classes arent used internally by phalcon and there is only one class which have some functionality - so we dont need interface for it. DI Container is dependency injection container - and it's much better then full dependency injection beacause i dont wanna have method with for example 5 or 10 or 20 parameters to be passed.

**Comment by rianorie** [comment]
But I do :p

I prefer it over the singleton we renamed to di container.

**Comment by Jurigag** [comment]
But most of people dont, if you want to remove di container then create other framework.

**Comment by rianorie** [comment]
That's kind of a crazy argument.. We're all here to work and discuss
phalcon. There's an easy way for both of us to get what we want, create the
base framework like how I suggest it and simply create some wrappers that
do what you want. Note how I'm not saying to go find a different framework.
I'm here to participate and contribute to phalcon, discussing ideas like
this is a part of that.

**Comment by Jurigag** [comment]
But it's bad idea ;p No point doing something if only 1% gonna use it, i cant believe that you would prefer something like this:

```
$someObject->someMethod($someParameter, $service1, $service2, $service3, $service4, $service5, $service6, $service7, $service8, $service9, $service10);
```
over:
```
$someObject->someMethod($someParameter);

public function someMethod($someParameter){
$service1 = $di->get('service1)' // etc
}

**Comment by rianorie** [comment]
Constructor injection rather than method injection, really. Also note how
you're not listing 10 services in your example ;)

I hadn't really given it much thought until recently but I'm refactoring a
phalcon app right now and noticing how tightly coupled everything is.

I don't believe it's a bad idea at all and would love some more insights,
Sergey? Andres?

**Comment by Jurigag** [comment]
Well we could at least use service locator in the way it should be - so passed as constructor parameter, all services which we need to use in our class are resolved from it and then in methods use those resolved properties - instead of calling di in static way.

**Comment by rianorie** [comment]
If I knew the shortcode for a happy dance you'd be seeing it now but I'm
using email ;)
That's exactly what I'm aiming for and the reason I suggest adding more
interfaces.
