### ISSUE TITLE
Build error Phalcon 2.1.x in Windows

### ISSUE THREAD

**Issue by Studentsov** [phalcon/cphalcon#11549]
I tried to build Phalcon 2.1.x from source codes, but received this error:

> Zephir\ParseException: Syntax error in D:\PHP\cphalcon-2.1.x\phalcon\paginator\adapter\querybuilder.zep on line 168
> 
>           var groups = totalBuilder->getGroupBy();
>         ----------------------------^

Windows 10, VS 2012, PHP 5.6.19 (NTS), Zephir 0.7.1 and 0.8 (I checked in both versions)
I used this manual: https://github.com/phalcon/zephir/blob/master/WINDOWS.md

**Comment by Jurigag** [comment]
As i remember you have to compile phalcon 2.1.x from zephir 0.9, as i know you have to compile zephir yourself - its in current repo.

**Comment by Studentsov** [comment]
Well, I tried to use the master branch of Zephir. Now I got the output library.
php_phalcon.dll 81,6 МB (85 656 064 bytes)
It is sad

**Comment by sergeyklay** [comment]
For dev purposes on Windows PC you can try to use [Vagrant Phalcon](https://github.com/phalcon/vagrant) or [Phalcon ready to go Docker Compose project](https://github.com/sergeyklay/phalcon-compose)

**Comment by Jurigag** [comment]
@Studentsov this size is fine, it is normal on PHP NTS. 250 MB on linux PHP 5.6.19 NTS
