### ISSUE TITLE
\Phalcon\Cache\Backend\Redis -> queryKeys returning nothing v2.0.*

### ISSUE THREAD

**Issue by michael-langford** [phalcon/cphalcon#11545]
We have found that `\Phalcon\Cache\Backend\Redis -> queryKeys` is returning nothing. We have verified the query does return something when using the PHP Redis class.

```
\Phalcon\Cache\Backend\Redis -> queryKeys('*key*'); // Does not returns values
\Redis -> getKeys('*key*'); // Returns values
```

**Comment by Jurigag** [comment]
As you can see:

https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/backend/redis.zep#L334

Phalcon using sMembers from redis, where wildcards are not working.

It needs to be change just to getKeys or it's just not a bug.
