### ISSUE TITLE
[2.1.x]cache frontend lifetime not working when querying with cache

### ISSUE THREAD

**Issue by linchao0828** [phalcon/cphalcon#11551]
```
$frontCache = new \Phalcon\Cache\Frontend\Data([
    'lifetime' => 300
]);

//backend
$cache = new \Phalcon\Cache\Backend\Libmemcached($frontCache, [
    'servers' => [[
        'host' => '127.0.0.1',
        'port' => '11211'
    ]],
    'statsKey' => null
]);

$di->set('modelsCache', $cache, true);

//use cache when query
$ret = Model::find([
    'cache' => [
        'key' => 'foo',
        'service' => 'modelsCache'
    ]
]);
```

Normally, the it will cache 300 sec. But actually, it's 3600 sec.

I just want to set a public lifetime by this way. And I think the problem is caused by https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query.zep#L3268
And compare with this 
https://github.com/phalcon/cphalcon/blob/1.3.4/ext/mvc/model/query.c#L4775

Could you please bring it back?

**Comment by linchao0828** [comment]
Anybody help?

**Comment by stamster** [comment]
I have similar issue. The thing is, my models' meta data just won't expire. 
If you dive into Zep code here: https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/frontend/data.zep#L63
It's is clear that this class is half implemented.

**Comment by dschissler** [comment]
Possible dup of #11757
