### ISSUE TITLE
Issue with transaction manager, doesn't manage transactions correctly

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#11554]
There's an issue with the transaction manager that makes it work very poorly. I will upload a pr that fixes it, but, as of now, I don't have time to run tests really on it. I have extended the manager and overriden this function so that it works properly for me, so that much testing I have done.

**Comment by nask0** [comment]
I guess this will fix the big i encountered and no need to open a separate issue ? Bug is :
```php
// Users Data Service class
public function save( array $data )
{
	try {
		// requested data is filtered and validated at this point, start db transaction
		$tx = $this->_getTransaction(); // returns TransactionMager->get() getted from DI

		$newUser = new UsersModel();
		$newUser->setTransaction( $tx );
		$newUser->setName( $data['name'] );
		// more setters for Users model

		if( false === $newUser->save() ) {
			$tx->rollback( 'Unable to save new user' );
		}

		$newDevice = new Devices();
		$newDevice->setTransaction( $tx );
		// more setters for Devices model

		if( false === $newDevice->save() ) {
			$tx->rollback( 'Unable to save new device' );
		}
		$tx->commit();
		return true;
		
	} catch( \Exception $e ) {
		$this->_setValidationError( 'unexpected', 'Unable to register user : ' . $e->getMessage() );
		return false;
	}
}

// SMS Data Service class
public function saveVerificationSMS( $verificationCode, $smsData )
{
	try {
		$tx = $this->_getTransaction();

		$message = new SmsMessagesSentModel();
		
		$message->setTransaction( $tx );
		// more setters for SmsMessagesModel()

		if( false === $message->save() ) {
			$tx->rollback( 'Unable to save SMS message.' );
		}

		$verification = new VerificationModel();
		$verification->setTransaction( $tx );
		// more setters for VerificationModel

		$verification->setCreatedAt( Date::getUTCTimestamp() );
		$verification->setUpdatedAt( Date::getUTCTimestamp() );

		if( false === $verification->save() ) {
			$tx->rollback( 'Unable to save new verification.' );
		}

		$tx->commit();
		return true;

	} catch( \Exception $e ) {
		$this->_setValidationError( 'unexpected', 'Unable to save verification SMS (' . $e->getMessage() . ')' );
		return false;
	}
}

// In controller :
$userDataService->save( $data ); // everything works fine

// throws PDO exception : "There is no active transaction", BUT all records are saved properly
$smsDataService->saveVerificationSMS( 'blah', [] ); 
```

Is there are known workaround for this or i must figure it out myself ? :)
Thanks in advance.

**Comment by nsossonko** [comment]
I think it's just because you never started the transaction. You have to call begin if you don't pass true for autoStart...

**Comment by sergeyklay** [comment]
@nsossonko @nask0 Could you please check now `2.1.x` branch?

**Comment by nask0** [comment]
@nsossonko [The documentation](https://docs.phalconphp.com/en/latest/reference/model-transactions.html#isolated-transactions) never told me to do begin(), moreover transaction is saved successfully, just always raise a exception.

@sergeyklay Ok, I will try 2.1 branch, thanks.

**Comment by nask0** [comment]
@sergeyklay i still get the same exception ( [branch 2.1.x install log](http://pastebin.com/wUi2WuUy) / [exception dump](http://pastebin.com/CEkHBpxm) ). 
However, @nsossonko was right and adding $tx->begin() after getting transaction fixes the issue, but i wonder what is _autoBegin_ parameter for then?

**Comment by sergeyklay** [comment]
Try `zephir build` from project root

**Comment by nask0** [comment]
@sergeyklay sorry, i got [zephir error](http://pastebin.com/XiEhZQFM), maybe it's something on my side, but currently do not have time to investigate further. 
If you have any tips, I will be glad to help :)

**Comment by sergeyklay** [comment]
@nask0 Could you please use latest Zephir? (master branch)

**Comment by nask0** [comment]
I am already with it: 
```
[nask0@h0m3 zephir]$ git branch
* master
[nask0@h0m3 zephir]$ git pull
Already up-to-date.
[nask0@h0m3 zephir]$
```

**Comment by sergeyklay** [comment]
@steffengy  Can you please figure out what's going on with Zephir on Fedora?

**Comment by nask0** [comment]
I found interesting that if i put $tx->begin() on the very first transaction that is get executed (from TxManager), none of transactions is saved, but if i remove just this first begin, everything "works" :)

**Comment by daison12006013** [comment]
@sergeyklay Just to confirm, I'm also getting the same bug right now when I rebuild my cphalcon on my local, remember this [11611](https://github.com/phalcon/cphalcon/issues/11611), when I rebuild it I got that error 

It throws the same error but it successfully saved a record in the database.

I will definitely try this on my other pc

**Comment by nsossonko** [comment]
The way transactions work is if you don't call begin on the transaction (or pass true for autoStart to get()) it will just create the model without a transaction. So what you are saying is not surprising. What you should test to verify this is: if you don't call begin and a second model fails after the first was created, then call rollback, see what happens. You should see the first model is created and the second is not.

Also, in your recent code you posted, it doesn't show that you are attaching the transaction to each model, which is necessary. You must call setTransaction on each model with the transaction.

**Comment by daison12006013** [comment]
@nsossonko I don't know if this solution works on your side too, try to transform your 'db' service as shared/singleton.

You might initialized the **db** first before **dispatcher**, which causes the error on my side.

**Comment by nask0** [comment]
@nsossonko thanks for comment. I intetionally menation "pseudo" code in my comment.
However, lets leave behind for a moment the fact that  the [default value of autoBegin in transaction manager is (boolean) true](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/transaction/manager.zep#L168) and strart from very beginning :

1. Here is how i [load application ](https://gist.github.com/nask0/f4d9d01b0b897f31fffd76df56e50ebd)
2. This is [DataService class](https://gist.github.com/nask0/e1f2dd6bde4c7b6efae30b019417899e) that just load data services
3. This is [DataServiceAbstract](https://gist.github.com/nask0/a9dd64551d8c7f91282bc10df07dda2d)  (note _getTransaction() method)
4. Here is actual Data Services that perform transactions : [User](https://gist.github.com/nask0/bd402cbfbc789f702ccb84f52db03e99), [ApiClients](https://gist.github.com/nask0/8a6b60094d11cf183f70f35e983b76a2), [Verifications](https://gist.github.com/nask0/7e517e01f01ac327c1e7ab6ff2f67538)
5. Finally in controller, transactions functions get called in the following order:
```php
$dataServiceUsers->save();
$dataServiceApiClients->register();
$dataServiceVefications->save()
```

Now, if i don't miss anything, according to [Phalcon documentation for isolated transactions ](https://docs.phalconphp.com/en/latest/reference/model-transactions.html#isolated-transactions) - the code should works, but it only works if i make some weird things like setting $tx->begin() in some of transactions as i already said.

**Comment by nsossonko** [comment]
Actually @daison12006013 might be correct, you're not setting the db and transactionManager via setShared so it may be creating more than one. About autoBegin, you seem to be right about that, so it shouldn't be required. I use the transaction manager extensively in my application and it works quite well for me.

**Comment by nask0** [comment]
@nsossonko ok, thanks. I will check all my code again and play with DI once i am done my current project  (deadline is soo soon :/). I will let you know guys, if i find anything else. 
Thanks all again and keep up the good work, Phalcon is awesome project (for ten long years in PHP this is the only framework i still use today)

**Comment by sergeyklay** [comment]
I'll open this issue again if the problem is actual
