### ISSUE TITLE
PHP 7 Tests related issues

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11550]
WORK IN PROGRESS - not all yet

**UP TO DATE FOR NOW(26.07.2016 8:48 GMT+1)**

I will update this list if something is fixed or new problem occurs:

- ```Phalcon\Assets\Resource``` needs to be changed cuz Resource is PHP 7 reserved word - http://php.net/manual/en/reserved.other-reserved-words.php - **NOT AN ISSUE**, but still it would be nice to change cuz it some day can be reserved word in php
- [x] - First usage of ```Phalcon\Test\Proxy\Assets\Collection``` cause error but then runs fine, if we return true in ```Phalcon\Test\Unit\Assets\CollectionTest::testAssetsResourceCollection``` then it runs fine, there is problem just when we construct this proxy class, if we change it to internal phalcon class then there is no problem - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - ```Phalcon\Config\Ini::toArray()``` returns ```Phalcon\Config``` object as a key - i think it's possible that it's related to https://github.com/phalcon/zephir/issues/1203 beacause its using ```method_exists``` too - _Fixed by https://github.com/phalcon/zephir/commit/68a1a2291b25d71112a557186d3dd507f309c420_
- [x] - First usage of ```Phalcon\Test\Proxy\Config``` cause error but then runs fine, if we change ```Config``` to ```PhConfig``` in ```Phalcon\Test\Unit\ConfigTest::testConfigToArray``` then it runs fine and again error now in ```Phalcon\Test\Unit\ConfigTest::testConfigCount```
- ```Phalcon\Config::merge()``` is just changing value of keys instead of merging, beacause type of key is not integer, it's related to https://github.com/phalcon/zephir/issues/1214 - _not an issue, https://github.com/phalcon/zephir/issues/1214#issuecomment-217577420_
- [x] - ```Phalcon\Test\Unit\Filter\FilterFloatTest::testSanitizeFloatHex()``` and ```Phalcon\Test\Unit\Filter\FilterIntegerTest::testSanitizeIntegerHex()``` - PHP 7 no longer cast hex value provided as string to hex - http://sandbox.onlinephpfunctions.com/code/87fc89e06fecac6b76dce332b1e1579524f505f3 and http://sandbox.onlinephpfunctions.com/code/d8033d7ed2ab04f99a603f1d81f466fbbdf0660b - _fixed by https://github.com/phalcon/cphalcon/commit/afbe355a2e76cf0bbef629d604ec947d40f45874_
- [x] - First usage of ```Phalcon\Test\Proxy\Flash\Direct``` cause error but then runs fine - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - First usage of ```Phalcon\Test\Proxy\Flash\Session``` cause error but then runs fine, if we return true in ```Phalcon\Test\Unit\Flash\SessionTest::testGetMessagesTypeRemoveMessages``` then it runs fine and again error now in ```Phalcon\Test\Unit\Flash\SessionTest::testClearMessagesFormSession``` - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - First usage of ```Phalcon\Test\Proxy\Http\Request``` cause error but then runs fine, if we return true in ```Phalcon\Test\Unit\Http\RequestTest::testHttpRequestGetDI``` then it runs fine and again error now in ```Phalcon\Test\Unit\Http\RequestTest::testHttpRequestInstanceOf``` - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - First usage of ```Phalcon\Test\Proxy\Http\Response``` cause error but then runs fine, if we return true in ```Phalcon\Test\Unit\Http\ResponseTest::testHttpResponseInstanceOf``` then it runs fine and again error now in ```Phalcon\Test\Unit\Http\ResponseTest::testHttpResponseSetHeader``` - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - First usage of ```Phalcon\Test\Proxy\Loader``` cause error but then runs fine, if we return true in ```Phalcon\Test\Unit\LoaderTest::testNamespaces``` then it runs fine and again error now in ```Phalcon\Test\Unit\LoaderTest::testNamespacesExtensions``` - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - First usage of ```Phalcon\Test\Proxy\Loader``` cause error but then runs fine, if we return true in ```Phalcon\Test\Unit\LoaderTest::testNamespaces``` then it runs fine and again error now in ```Phalcon\Test\Unit\LoaderTest::testNamespacesExtensions``` - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - First usage of ```Phalcon\Test\Proxy\Logger\Adapter\File``` cause error but then runs fine, if we return true in ```Phalcon\Test\Unit\Logger\Adapter\FileTest::testLoggerAdapterFileCreationDefault``` then it runs fine and again error now in `Phalcon\Test\Unit\Logger\Adapter\FileTest::testLoggerAdapterFileCreationWrite` - _fixed by https://github.com/phalcon/cphalcon/commit/99e197735199b46854b0ff6142a5ba043a2e88da_
- [x] - **SEG FAULT when running `Phalcon\Test\Unit\Logger\Adapter\FileTest::testLoggerAdapterFileCreationWrite`, more about here - https://github.com/phalcon/cphalcon/pull/11279#issuecomment-197026308 - that means the list finish now here if someone will fix it i will continue doing it, for now like 17.03.2016 it's all problems from tests for phalcon 2.1.x and php 7** - _fixed by don't know what, i guess some newest commits on zephir must fixed this_
- [x] - **SEG FAULT when running `CacheResultsetTest::testCacheResultsetNormal()` - common problem with `zephir_create_instance_params` - zephir can't build Query service from class name** - _fixed by https://github.com/phalcon/zephir/commit/bb572f1141df0c2e78741042a0ee445a2fbc3a86_
- [x] - **SEG FAULT when running `Phalcon\Test\Unit\Mvc\Model\Metadata\ApcCest:apc` - caused by phql parser not fully supported with PHP 7, other related DB tests are failing because of the same reason so no sense to write here them all, stacktrace here - http://pastebin.com/vt0Z6ETX** - _fixed on php7-parsers branch and newest zephir (30.04.2016)_ 
- [x] - **SEG FAULT when running `FormsTest::testFormValidatorEntity` - there is stacktrace http://pastebin.com/uzZ2cS8P ~~it's possible that is happening only on debug version~~ actually it happens on non-debug as well** - _fixed in php7-parsers branch_
- [x] - **SEG FAULT when running `Phalcon\Test\Unit\Session\BagTest::testBagSetEmptyArray`, it looks like some garbage collector problems but im not sure, there is stack - http://pastebin.com/x0Fjv9c4**
- [x] - `Phalcon\Test\Unit\Annotations\Adapter\XcacheTest::testXcacheAdapter`, this test is currently disabled for travis `Phalcon\Test\Unit\Mvc\Model\MetaData\XcacheTest::xcache` fails beacause xcache extension for php7 doesn't exist and checking for it is done in wrong way - _fixed by https://github.com/phalcon/cphalcon/commit/86c855969edb4c36c43859c61273d6ac5a2fb15e_
- [x] - `Phalcon\Test\Unit\Logger\Adapter\Firephp::testLoggerAdapterFirephpCreationDefault` fails beacause this line https://github.com/phalcon/cphalcon/blob/0f7098ba67ef68534d03507988bfc2b637d2a3ec/tests/unit/Logger/Adapter/FirephpTest.php#L63 have actually `"X-Wf-1-1-1-: 55|[{"Type":"INFO","Label":"Some firephp simple test"},""]|"` returned from `xdebug_get_headers()` - _fixed by https://github.com/phalcon/cphalcon/pull/12028_
- [x] - `Phalcon\Test\Unit\Mvc\UrlTest`, tests are failing due to https://github.com/phalcon/cphalcon/issues/11728 - _fixed by https://github.com/phalcon/cphalcon/commit/c3f34872c49bc0ad40167c08b833f76682de9dfb_
- [x] - `ControllersTest::testModelBinding` fails here https://github.com/phalcon/cphalcon/blob/2.1.x/unit-tests/ControllersTest.php#L125 beacause in PHP 7 wrong parameter type is now TypeError which extends Error, Exception is different type of throwable class, http://php.net/manual/en/language.errors.php7.php
- [x] - `ViewSimpleTest::testRenderWithCache` fails, i will add more info when i will check it myself -  _removed in 2.1.x_

**Comment by Jurigag** [comment]
@sergeyklay @Green-Cat 
Well im no sure about ```Phalcon\Assets\Resource```, cuz i created my own class named Resource and it works fine, but it's only not working in test where it's created. I will look later into it, maybe there is some other reason why there is error. Can i check somehow what error is it in codeception ? Some exception or what ?

**Comment by Izopi4a** [comment]
seems like phalcon did get quite a bit of popularity lately .. lets hope Andres will fix the php 7 in order to keep this popularity ...

**Comment by Jurigag** [comment]
@sergeyklay 
It looks like in almost every test on php7 there is weird problem with proxy class. If it's used for first time - then error occurs, then it's running fine.

**Comment by sergeyklay** [comment]
Temporary you can switch tests to the internal classes (but don't delete internal classes please) if it really solve testing issue

**Comment by Jurigag** [comment]
It's solving but there is still SEG FAULT so it doesn't matter. I will dont flag it as done until we dont figure out why this proxy classes works so weird.

**Comment by Jurigag** [comment]
@sergeyklay well i dont know why i didn't think about it later, just copied some proxy class into apache and tested it myself:

```

Warning: Declaration of Phalcon\Test\Proxy\Config::merge(Phalcon\Test\Proxy\Config $config) should be compatible with Phalcon\Config::merge(Phalcon\Config $config) in /vagrant/www/test/Config.php on line 0

Warning: Declaration of Phalcon\Test\Proxy\Config::__set_state($data) should be compatible with Phalcon\Config::__set_state(array $data) in /vagrant/www/test/Config.php on line 0

Fatal error: Uncaught Exception: The argument is not initialized or iterable() in phalcon/config.zep:62 Stack trace: #0 /vagrant/www/test/Config.php(27): Phalcon\Config->__construct(NULL) #1 /vagrant/www/test/index.php(10): Phalcon\Test\Proxy\Config->__construct() #2 {main} thrown in phalcon/config.zep on line 62
```

**Comment by Jurigag** [comment]
@sergeyklay 

Well there is a problem That both proxy classes on php 5.6 and php7 has wrong delcaration of methods(other types).

But on php 5.6 we have Strict Declarations errors. On php 7 we have Warnings - what my guess is if codeception detect warning in test - it's just automatically marking them as Error ?

**Comment by sergeyklay** [comment]
@Jurigag No proplem. Just do PR with proxies fixes :)

**Comment by Jurigag** [comment]
Well yea, im right, fast fix:

```error_level: E_ALL ^ E_WARNING``` in codeception settings

Proper fix:
```Fix all proxy classes to have good declaration```

**Comment by googlle** [comment]
Cool. It seems to be ready soon

**Comment by Jurigag** [comment]
If phalcon/zephir team will fix seg faults then maybe. Right now we can't test it further and find bugs if there any.

Well i will check when i have time others tests, currently it's only tests from tests folder, but there is also unit-tests.

Could someone fix this hex tests ?

**Comment by googlle** [comment]
I will try, but not sure

**Comment by googlle** [comment]
I do not know how to fix. https://wiki.php.net/rfc/remove_hex_support_in_numeric_strings

**Comment by Jurigag** [comment]
Just remove strings in test to be it just hex value.

**Comment by googlle** [comment]
What's next?

**Comment by Jurigag** [comment]
And do pr. In this line https://github.com/phalcon/cphalcon/blob/master/tests/unit/Phalcon/Filter/FilterFloatTest.php#L54 second parameter must be without single quotes. Just hex value.

**Comment by googlle** [comment]
@Jurigag pr https://github.com/phalcon/cphalcon/pull/11631

**Comment by Jurigag** [comment]
You forgot ```Phalcon\Test\Unit\Filter\FilterIntegerTest::testSanitizeIntegerHex()```

**Comment by googlle** [comment]
pr https://github.com/phalcon/cphalcon/pull/11632

**Comment by Jurigag** [comment]
Yea, that looks fine. Once it's merged i will mark is as done.

**Comment by Izopi4a** [comment]
now if someone fix create_instance_params would be awesome ...

**Comment by Jurigag** [comment]
I don't know c xd

**Comment by Jurigag** [comment]
Updated it with another "common" issue, when `vendor/bin/phpunit --bootstrap tests/_ci/phpunit.php unit-tests/ --testdox` there is seg fault on creating query service from class name on `zephir_create_instance_params`. We have to wait for fixing it cuz i don't have time for testing each test separately to see which test works which don't. I will update list when `zephir_create_instance_params` will be fixed.

**Comment by Jurigag** [comment]
@sergeyklay 

Any idea why there is seg fault when running `FormsTest::testFormValidatorEntity` https://github.com/phalcon/cphalcon/blob/2.1.x/unit-tests/FormsTest.php#L368 - there is stacktrace http://pastebin.com/uzZ2cS8P ? 

I copied code from this test to my seperated file and tested it myself and it works. But in test on validating it it fails. Weird

**Comment by Jurigag** [comment]
Well all tests are almost working(need to figure out one some not passing). But i have seg fault on 
```
✔ BagTest: Bag set empty array (0.0s)
```

What is this test is passing and after that i have seg fault, it's possible that there are some problems with php GC. Don't know how to make it working. I tried disable_gc() and gc_collect_cycles(), none seems to work.

It looks like this - http://pastebin.com/w0LPM7KH

Can someone test it too on newest zephir and php7-parsers branch of phalcon and can confirm an issue ?

@andresgutierrez @sergeyklay

**Comment by Jurigag** [comment]
@sergeyklay 

Updated with some tests related things.

**Comment by Jurigag** [comment]
@sergeyklay 

Well there is still some problem with xdebug - this testing is failing - https://travis-ci.org/phalcon/cphalcon/jobs/127384575#L1789 - i wrote in the list why. But well on php 5.x it's passing so don't know if it's not a bug in debug ?
