### ISSUE TITLE
Volt template names and camelized controller actions

### ISSUE THREAD

**Issue by makerlabs** [phalcon/cphalcon#11568]
Hi, 
Im having a strange issue In work we use a compiled version of phalcon from homebrew and it works fine I mean when we create a controller action named "addProductAction" the phalcon is calling the "addProduct.volt" template. But Now I switched to linux and compiled phalcon from sources and ran our application phalcon don't see the template "addProduct.volt" it tries to search for "addproduct.volt" why?

**Comment by sergeyklay** [comment]
Possible refs: https://github.com/phalcon/cphalcon/issues/284

**Comment by makerlabs** [comment]
This is actually a bug in the Annotation Router I created a fix for that
