### ISSUE TITLE
Phalcon\Db\Adapter\Pdo\Oracle can not handle Oracle\Package

### ISSUE THREAD

**Issue by blutrash** [phalcon/cphalcon#11563]
Exception: Syntax error, unexpected token (, near to 'icms_selection.crq_exists('%')) WHERE rownum < 26', when parsing: SELECT * FROM TABLE (icms_selection.crq_exists('%')) WHERE rownum < 26 (70)

Could this be fixed in near future?

**Comment by sergeyklay** [comment]
Phalcon does not support Oracle. Refer to #12008
