### ISSUE TITLE
[NFR] Support of nested forms and adding collections of elements to the form

### ISSUE THREAD

**Issue by MelnykDmitro** [phalcon/cphalcon#11579]
_Просьба перевести на english_

> Работа с HTML-форм является одним из наиболее распространенных - и сложных - задач для веб-разработчиков.

Phalcon\Forms\Form очень простой и лаконичный компонент, но к сожалению его функционала не хватает для решения основных повседневных задач. В связи с этим предлагаю:
Добавить возможность в **Phalcon\Forms\Form** добавлять под-формы(объекты Phalcon\Forms\Form) в качестве элементов и добавить новый элемент типу Collection который может содержать несколько элементов включая под-форму.

Эта возможность так-же должна включать:
1. Метод **Phalcon\Forms\Form->bind()** должен биндить данные в подформы и коллекции.
2. Метод **Phalcon\Forms\Form->render()** должен рассчитывать имя элемента включая иерархию.

Пример использования:
Создание формы **Robot** которая содержит коллекцию подформ **RobotPart**

``` php
<?php

use Phalcon\Mvc\Model;
use Phalcon\Forms\Form;
use Phalcon\Forms\Element;

class Robot extends Model
{
    protected $id;
    protected $name;

    protected function initialize()
    {
        $this->hasOne(
            'id',
            'RobotPart',
            'robot_id'
        );
    }
}


class RobotPart extends Model
{
    protected $id;
    protected $robot_id;
    protected $name;

    protected function initialize()
    {
        $this->belongsTo(
            'robot_id',
            'Robot',
            'id'
        );
    }
}

$robot = new Robot();

$robotPartForm = new Form();
$robotPartForm->add(new Element\Text('name'));

$robotForm = new Form($robot);
$robotForm->add(new Element\Text('name'));
$robotForm->add(new Element\Collection('robotPart', $robotPartForm));

$robotForm->bind($robot, $_POST);

echo $robotForm->render('name');

// Выводит несколько формы сущностями которых есть результат $robot->getRobotPart(), а если нету сущностей, выводит пустой единственный прототип
foreach ($robotForm->get('robotPart') as $robotPartForm) {
    // Должен вывести <input type="text" name="robotPart[*индекс*][name]" value="*value*/">
    echo $robotPartForm->render('name');
}
```

**Comment by Jurigag** [comment]
@sergeyklay 
Can you translate it ?

**Comment by sergeyklay** [comment]
Yes, in the evening guys. I'm little busy

**Comment by SidRoberts** [comment]
Here's a rough translation...

> Working with HTML forms is one of the most common - and challenging - tasks for web developers.

`Phalcon\Forms\Form` is very simple and concise component, but unfortunately it is not functional enough to solve the major everyday problems. To alleviate this problem:

Add the ability to `Phalcon\Forms\Form` to add a `Phalcon\Forms\Form` object as elements and add a new item type Collection that can contain several elements including a sub-form.

1. The `Phalcon\Forms\Form->bind()` method must bind data to collection and subforms.
2. The `Phalcon\Forms\Form->render()` method should expect the item name including the hierarchy.

Example:

Create a form that contains a collection of **Robot** subforms **RobotPart**

**Comment by valVk** [comment]
It's called Form Embedding and there are already exists NFR for this

https://github.com/phalcon/cphalcon/issues/705

**Comment by googlle** [comment]
+1

**Comment by GrigoriyIvanov** [comment]
+1

**Comment by fenixphp** [comment]
+1

**Comment by googlle** [comment]
Hello. 
@sergeyklay, will this feature be added in 2.1.0?

**Comment by Jurigag** [comment]
If someone will do it then it will be added.

**Comment by stanleer** [comment]
+1

**Comment by andrew-demb** [comment]
+1

**Comment by DepX** [comment]
+1

**Comment by StudioMaX** [comment]
Any progress here? This feature is working very nicely in Symfony framework, and it's not so cool that this feature still doesn't exist in Phalcon.

**Comment by DTukans** [comment]
+1

**Comment by StudioMaX** [comment]
This is still relevant.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
