### ISSUE TITLE
Incorrectly receiving "Redisd server selected database failed"

### ISSUE THREAD

**Issue by radean0909** [phalcon/cphalcon#11587]
In: https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/backend/redis.zep

This occurs when connecting to our new redis server (our last server didn't require authentication).

The relevant redis config info:

``` php
'redis' => array (
        'host' => '<REMOTE URL HERE>',
        'port' => '13659',
        'auth' => '<PW HERE>',
        'persistent' => false,
        'none' => 0,
        'short' => 60 * 5,
        'medium' => 60 * 10,
        'long' => 60 * 30, // 1 day
        'extraLong' =>60 * 60 * 24 * 7, 
    ),
```

Since experiencing this issue we have tried connecting to several different redis sources. Pure PHP implementation using the Redis adapter does work. I'm, beginning to write an Adapter for Predis as opposed to the Redis used by Phalcon, but as our current site is non-functional due to this presently, was hoping to get some insight.

**Comment by moazzamk** [comment]
You can also just use PHP redis . It is what Phalcon uses to make calls to redis .

**Comment by moazzamk** [comment]
radean0909: Do you have multiple databases on the Redis server? I just tried to connect to a Redis server that requires a password and I was able to do it without any issues (using phalcon). And, it throws an exception if the authentication is wrong.
