### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Hoet** [phalcon/cphalcon#11589]
Hello,

I'am trying to save related records. The code below generates the error specified in the title. Everything is ok when I comment the last two lines out. However when I leave them in, I get the message mentioned in the subject. Below the code is part of the model that we use.

Anyone have an idea how I could solve this, by using saving related records. 

``` php
$user =new Users();
$user->type =UserTypes::findFirst( "id='1'" );
$user->setEmail( $this->request->getPost( 'email' ));
$user->setGender( $this->request->getPost( 'title' ));
$user->setMobile( $this->request->getPost( 'mobile' ));
$user->setLastName( $this->request->getPost( 'lastname' ));
$user->setFirstName( $this->request->getPost( 'firstname' ));

$comment =new QuotationComments( );
$comment->user =$user;
$comment->setComment( $this->request->getPost( 'comment' ));

$quotation =new Quotations();
$quotation->user     =$user;
$quotation->comments =[ $comment ];
$quotation->setDuration( $this->request->getPost( 'duration' ));
$quotation->setDeparture( $this->request->getPost( 'departure' ));

$comment->quotation =$quotation;
$comment->update();
```

Models used:
![max reached](https://cloud.githubusercontent.com/assets/10795277/14027853/fc30634c-f1f9-11e5-985b-ed2ae2fa2875.png)

**Comment by Jurigag** [comment]
And how your relations looks like in phalcon ?

**Comment by Hoet** [comment]
Hi,

See below for the relations for every model used in the screenshot above.

**quotation_comments**
$this->setSource( 'quotation_comments' );
$this->belongsTo( 'user_id', __NAMESPACE__ . '\Users', 'id', [ 'alias' => 'User' ]);
$this->belongsTo( 'quotation_id', __NAMESPACE__ . '\Quotations', 'id', [ 'alias' => 'Quotation' ]);

**quotations**
$this->setSource( 'quotations' );
$this->hasMany( 'id', __NAMESPACE__ . '\QuotationsLog', 'quotation_id', [ 'alias' => 'Logs' ]);
$this->hasMany( 'id', __NAMESPACE__ . '\QuotationComments', 'quotation_id', [ 'alias' => 'Comments' ]);
$this->belongsTo( 'user_id', __NAMESPACE__ . '\Users', 'id', [ 'alias' => 'User' ]);

**quotation_logs**
$this->belongsTo( 'user_id', __NAMESPACE__ . '\Users', 'id', [ 'alias' => 'User' ]);
$this->belongsTo( 'quotation_id', __NAMESPACE__ . '\Quotations', 'id', [ 'alias' => 'Quotation' ]);

**parents_children**
$this->belongsTo( 'child_id', __NAMESPACE__ . '\Users', 'id' );
$this->belongsTo( 'parent_id', __NAMESPACE__ . '\Users', 'id' );

**users**
$this->hasMany( 'id', __NAMESPACE__ . '\Addresses', 'user_id' );
$this->hasMany( 'id', __NAMESPACE__ . '\Quotations', 'user_id' );
$this->hasMany( 'id', __NAMESPACE__ . '\QuotationLogs', 'user_id' );
$this->hasMany( 'id', __NAMESPACE__ . '\QuotationComments', 'user_id' );
$this->belongsTo( 'type_id', 'UserTypes', 'id', [ 'alias' => 'Type' ]);
$this->hasManyToMany( 'id', __NAMESPACE__ . '\ParrentsChildren', 'child_id', 'parent_id', __NAMESPACE__ . '\Users', 'id', [ 'alias' => 'Parents' ]);
$this->hasManyToMany( 'id', __NAMESPACE__ . '\ParrentsChildren', 'parent_id', 'child_id', __NAMESPACE__ . '\Users', 'id', [ 'alias' => 'Children' ]);

**user_types**
$this->hasMany( 'id', __NAMESPACE__ . '\Users', 'type_id', [ 'alias' => 'User' ]);

**addresses**
$this->belongsTo( 'user_id', __NAMESPACE__ . '\Users', 'id', [ 'alias' => 'User' ]);
$this->belongsTo( 'country_id', __NAMESPACE__ . '\Countries', 'id', [ 'alias' => 'Country' ]);

**Comment by Jurigag** [comment]
And what database you are using ? Not sure is there any difference but you have aliases with first letter uppercase, but in code your are using it lowercase.

**Comment by Hoet** [comment]
The DB I use is MySQL (default).

**lower/upper case**
I found out by trail and error that lowercase seems to work fine when working with aliases. The application consists of 74 tables and I used the uppercase/lowercase combo on all of them. I haven't gotten an error on that yet. But I'll change them for this part of the code just to see if it would make a difference.

**findfirst ....**
ok, will change that.

**validation**
No.
I use 'protected' for all values. All the models above just have an initialize to set the table to be used and the relations for that table. And model parameters are explicitly set via 'set/get' functions. And for now only the parameters that are used in the code in the first post are implemented. The rest will be implemented on a 'use' basis.

I do however have things like 'NOT NULL' and 'unsigned' set for various columns in the database. I design the DB via Navicats model builder. When I was setting this up for the first time did get validation errors because a couple of fields where 'NULL' instead of a proper value. But after I fixed all those messages I stated receiving the error messages.

**Comment by Hoet** [comment]
Hmm I have changed the code to the following and that seems to be working properly. Apparently by adding the update on quotations (see first post) the recursion is triggered. And apparently the update is not needed because the relations will take care of setting a quotation ID for the comment.

$address =new Addresses();
$address->setCity( $this->request->getPost( 'city' ));
$address->setPhone( $this->request->getPost( 'phone' ));
$address->setPostcode( $this->request->getPost( 'postcode' ));

$user =new Users();
$user->type =UserTypes::findFirst( 1 );
$user->addresses =[ $address ];
$user->setEmail( $this->request->getPost( 'email' ));
$user->setGender( $this->request->getPost( 'title' ));
$user->setMobile( $this->request->getPost( 'mobile' ));
$user->setLastName( $this->request->getPost( 'lastname' ));
$user->setFirstName( $this->request->getPost( 'firstname' ));

$comment =new QuotationComments( );
$comment->user =$user;
$comment->setComment( $this->request->getPost( 'comment' ));

$quotation =new Quotations();
$quotation->user =$user;
$quotation->comments =[ $comment ];
$quotation->setDuration( $this->request->getPost( 'duration' ));
$quotation->setDeparture( $this->request->getPost( 'departure' ));

$quotation->save( );
