### ISSUE TITLE
Phalcon\Cache\Backend\Redis not working with latest Phalcon 2.1.x build and PHP7

### ISSUE THREAD

**Issue by AniaSoft** [phalcon/cphalcon#11582]
Hi,

When I try to use Redis cache with latest Phalcon 2.1.x branch and PHP7 I got segmentation fault. When I use master branch and php 5.6 it works perfectly. Can anyone please help me with this?

> php index.php
> Segmentation fault

If I run under debugger:

> gdb php
> run index.php

I got this:

> Program received signal SIGSEGV, Segmentation fault.
> 0x00007fffe6ce0fd7 in zephir_call_user_function.3436 () from /usr/lib64/php/modules/phalcon.so

**Comment by Jurigag** [comment]
You have to compile phalcon 2.1.x with newest zephir, then it should work.

**Comment by AniaSoft** [comment]
Yes, I have compiled with the latest zephir (0.9.2a-dev).
zephir build -backend=ZendEngine3
Then I have to wait for a stable release. Thank you.

**Comment by Jurigag** [comment]
Create issue on zephir beacause it's zephir realated with whole backtrace from bt and close this issue.

**Comment by AniaSoft** [comment]
Yes, I will do so.
