### ISSUE TITLE
Namespace controller

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11585]
Hello. Now we can not use a namespace for the controller with the module. Why not make this possible?

``` php
$router->add("/", array(
    'module' => 'App',
    'controller' => 'App\Controller\Index',
    'action' => 'index',
))->setName('index');
```

Now it automatically adds to the controller - "{module}\Controller{MyControllerName}Controller"
Router creates the name of the controller that is "App\Controller\App\Controller\IndexController"

Why not first check the controller does not contain "module", if it contains - not to add module, otherwise use the default?

**Comment by Jurigag** [comment]
You can already use namepsace by:

```php
$router->add("/", array(
    'module' => 'App',
    'controller' => 'index',
    'namespace' => 'App\Controller',
    'action' => 'index',
))->setName('index');

**Comment by googlle** [comment]
Why I do not use full
1. I think phalcon should automatically add "Controller" to the name 
2. I use acl ("Index" controllers I have many - each with its own namespace)

Now I use this
```php
$router->add("/", array(
    'module' => 'App',
    'name' => 'App\Controller\Index',
    'controller' => 'Index',
    'action' => 'index',
))->setName('index');

$router->add("/home", array(
    'module' => 'App',
    'name' => 'App\Controller\Home\Index',
    'controller' => 'Home\Index',
    'action' => 'index',
))->setName('home');

class SecurityPlugin extends Plugin
{
    public function beforeDispatch(Event $event, Dispatcher $dispatcher)
    {
        $controller = $dispatcher->getControllerName();
        $action = $dispatcher->getActionName();
        $resource = $dispatcher->getParam('name', array('striptags'), null);
        
        if(!$acl->isAllowed($role, $resource, $action)) {
            ...
        }
    }
}
```

**Comment by Jurigag** [comment]
Why it should add automatically Controller when you are providing almost full namespace ? I don't get it. If you want to use just namespace - then type full namespace, if don't - then don't. For me typing full namespace without Controller will be inconsistence.

**Comment by googlle** [comment]
I guess this is correct. In many frameworks it is so used.

**Comment by fenixphp** [comment]
```php 
//Frontend\Controllers\Content\Index
//Backend\Controllers\Content\Index
$dispatcher->getControllerName()
```
There will always be ``` Index ```
But this approach will cripple the whole namespace for the controllers.

Not very elegant but saves in such a situation.
```php
get_class($dispatcher->getActiveController())
// Frontend\Controllers\Content\Index
```

PS: All the jump from the bridge, you bend down, too?
