### ISSUE TITLE
Validators still run, even if there is no PresenceOf

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11597]
I noticed that when I don't add PresenceOf validator to the element, during validation the form - validators will still run for this item.
```php
$element = new Text('test');
$element->setFilters(array('striptags', 'int'));
$element->addValidators(array(
    /* new PresenceOf(array(
        'message' => 'please fill in'
    )), */
    new Between(array(
        'minimum' => 0,
        'maximum' => 100,
        'message' => 'The value must be between 0 and 100'
    )),
));
$this->add($element);
```
Show error "The value must be between 0 and 100"

**Comment by Jurigag** [comment]
I guess it's a bug beacause this validator should run only if it's not empty.

**Comment by googlle** [comment]
I guess also
@Jurigag can you look? https://github.com/phalcon/cphalcon/issues/11584

**Comment by googlle** [comment]
@sergeyklay can you look? I guess it's a bug

**Comment by sergeyklay** [comment]
Which version of Phalcon did you use

**Comment by googlle** [comment]
I use Phalcon 2.1.0.RC1

**Comment by sergeyklay** [comment]
@googlle What about this feature https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/validation.zep#L475

**Comment by mraspor** [comment]
You could add ''allowEmpty' => true' to the validator, allowing empty submition.

```php
$element = new Text('test');
$element->setFilters(array('striptags', 'int'));
$element->addValidators(array(
    new Between(array(  // this validator will not run if element test is empy
        'minimum' => 0,
        'maximum' => 100,
        'message' => 'The value must be between 0 and 100',
        'allowEmpty' => true
    )),
));
$this->add($element)
```
https://docs.phalconphp.com/en/latest/reference/validation.html#avoid-validate-empty-values

**Comment by googlle** [comment]
Thanks to everybody
