### ISSUE TITLE
Request: Router "OR" in Param RegEx

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11595]
Not sure how hard this would be to implement in Phalcon, but can we please have "OR" for routers ? For example, I want to use "year" as my string and allow ether 2-digits or 4-digits only. I know I can use ``/([0-9]{2,4})/`` but what I'm asking is can we have "OR". Example would be something like, ``/([0-9]{2|4})/``. This would allow ONLY 2-digits OR 4-digits. This way 1-digit or 3-digits wont be allowed. I know this is very minor and may not be used often but could be very useful. Workaround right now would be to do something like ``/([0-9]{2}|([0-9]{4})/`` which is cumbersome.

**Comment by makerlabs** [comment]
This isn't a Phalcon issue this is how regular expressions are working there is no {m|m} quantifier so yes u must use /([0-9]{2}|([0-9]{4})/
