### ISSUE TITLE
Call to undefined function apc_fetch in tests

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11591]
On php 5.4 tests pass, on 5.5 and 5.6 don't. Are you guys using apcu on 5.5 and 5.6 ? Can you add apcu_bc on php 5.5 and 5.6 ?

https://pecl.php.net/package/apcu_bc

Or maybe should i just use ```Phalcon\Annotations\Adapter\Memory``` ?

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/blob/2.1.x/tests/shim.php

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/blob/2.1.x/tests/_ci/install_prereqs.sh#L55

**Comment by Jurigag** [comment]
I have apcu, but ```Phalcon\Annotations\Adapter\Apc``` is using apc_fetch and it fails on tests beacause there is no such a function. On my VM it's working fine beacause i have apcu_bc.
