### ISSUE TITLE
Request: Deprecate Long Paths

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11593]
I read the news about 2.1 RC1 good job guys. Can't wait for the stable version to use Phalcon in production environment with PHP 7. I've noticed this; ``Phalcon\Mvc\Model\Validation is now deprecated in favor of Phalcon\Validation`` Can we please have more of this similar deprecation for other long paths?

Some Examples:

 * Deprecate ``Phalcon\Mvc\Model`` in favor of ``Phalcon\Model``.
 * Deprecate ``Phalcon\Mvc\Controller`` in favor of ``Phalcon\Controller``

and more by removing at least "Mvc" word from many of this.

Another example is Paginator:

 * Deprecate ``Phalcon\Paginator\Adapter\Model`` in favor of ``Phalcon\Paginator\Model``
 * Deprecate ``Phalcon\Paginator\Adapter\NativeArray`` in favor of ``Phalcon\Paginator\Array``
 * Deprecate ``Phalcon\Paginator\Adapter\QueryBuilder`` in favor of ``Phalcon\Paginator\Query``

Thank you!

**Comment by Jurigag** [comment]
```Phalcon\Mvc\Model\Validation is now deprecated in favor of Phalcon\Validation```

This is not deprecated beacause long path. This is deprecated to make Forms and Model use the same validation component.

We can't do this beacause phalcon is allowing you to create not-mvc application(micro for example or cli). You don't have for example controllers in micro app. Putiing Phalcon\Mvc\Controller into Phalcon\Controller will mean now you can like use them in micro app too or anywhere you want.

Some with adapter. There is already existing Phalcon\Paginator\Adapter, class extending it should be in other namespace. Not the same. Learn more about namespaces :).
