### ISSUE TITLE
phalcon\mvc\model toArray doesnot work

### ISSUE THREAD

**Issue by laodalaoda520** [phalcon/cphalcon#11609]
when i  use 'columns' option  in the find method,
like
      
`$data  = (new model())-> find(array('','columns'=>array('*,count(1) as 'total')));`
and then, 
  `  print_r($data->array());`

**Comment by Jurigag** [comment]
there is no method ```->array()```

Also instead of:

```
$data = (new model())-> find(array('','columns'=>array('*,count(1) as 'total')));
```
do:

```
$data = Model::find(['columns'=>array('*,count(1) as 'total')]);
```

**Comment by laodalaoda520** [comment]
@sergeyklay 
sorry,  It's a mistake;
but ,you can try this 
```
$data = Model::find(['columns'=>array('*,count(1) as 'total')]);
var_dump($data->toArray());
```
it's no an array

**Comment by Jurigag** [comment]
```
$data = Model::find(['columns'=>array('*,count(1) as 'total')]);
var_dump($data->toArray());
```

This is mistake too, you need it like this:

```
$data = Model::find(['columns'=>array('*','count(1) as total')]);
var_dump($data->toArray());
```

**Comment by sergeyklay** [comment]
For questions like these please use the forum: http://forum.phalconphp.com/, GitHub is only intended to report bugs and discuss new features.

**Comment by laodalaoda520** [comment]
tks 4 help
