### ISSUE TITLE
"$this"  in Di setter refers to Phalcon\Di\FactoryDefault

### ISSUE THREAD

**Issue by skmail** [phalcon/cphalcon#11604]
Hello, 

**This issue on version 2.1.x**

**OS: Ubuntu 14.04
PHP Version: PHP Version 5.6.19-1+deb.sury.org~trusty+1**

I'm using multi module application using phalcon, the issue is when  registering some services  through registerServices(DiInterface $di) method and use  variable $this within lambada function in service setter, "$this" variable refers to "Phalcon\Di\FactoryDefault" and not the module definition class , this issue applies on all cases, i reproduced this is while registering a service fro a normal class, 

the following code will replicate it .

```
use Phalcon\DI\FactoryDefault;
$di = new FactoryDefault();

class Foo{

    protected $_dependencyInjector;

    public function __construct($di)
    {
        $this->_dependencyInjector = $di;
        $this->_dependencyInjector->set('test',function(){
            var_dump($this);
        });
    }

    public function render()
    {
        return $this->_dependencyInjector['test'];
    }
}


$foo = new Foo($di);

$foo->render();
``` 

Regards

**Comment by Jurigag** [comment]
Its a new thing in 2.1.0. Services are now bound to DI, that's why calling $this in function is actually di itself.

**Comment by sergeyklay** [comment]
This featured introduced in blog post 2015-09-25: https://blog.phalconphp.com/post/phalcon-2-0-8-and-2-1-0-beta2-released

**Comment by skmail** [comment]
Thank you.
