### ISSUE TITLE
Linking Tables do not allow combined primary keys

### ISSUE THREAD

**Issue by konsultaner** [phalcon/cphalcon#1160]
If you link a 2 tables with a hasManyToMany relationship using a linking table, the linking Table is not allowed to have both id's as **primary key**:

In my case
table: User | **user_id**,name, password, ...
link: User_Has_User | **parent_id**, **child_id**

they are linked like:
$this->hasManyToMany("user_id","User_Has_User","parent_id","child_Id","User","user_id");

The model will notice only one unique param, which was parent_id in this particular case.
##

**Comment by ZStelmo** [comment]
Any news  ? the problem persist  .

**Comment by konsultaner** [comment]
This is probably outdated
