### ISSUE TITLE
mcrypt deprecation 

### ISSUE THREAD

**Issue by HanXHX** [phalcon/cphalcon#11619]
PHP core team will deprecate mcrypt solution as PHP 7.1 version. => https://wiki.php.net/rfc/mcrypt-viking-funeral

We should start a migration to another solution.

**Comment by Jurigag** [comment]
It's already done in 2.1.x branch and replaced to openssl.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/pull/11530
