### ISSUE TITLE
Phalcon 2.0.10 MetaData Bug Default Values

### ISSUE THREAD

**Issue by tidytrax** [phalcon/cphalcon#11613]
If a table doenst have a auto-increment column metadata cannot read the defaults value, so when save get error column is required instead of read default values

So with auto-increment works fine but without all fields with default value ask to be filled 

Example

> column date_created = default_value = CURRENT_TIMESTAMP.
> column status = default_value = 'active'   

so to work i created a ID column INT auto increment and set as Primary key.

Phalcon 2.0.10 + Nginx 1.9.3 + PHP 5.6 FPM + MariaDB 10.1

**Comment by tidytrax** [comment]
**Steps **

```
CREATE TABLE `test` (
`test`  varchar(255) NOT NULL ,
`data_created`  timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
PRIMARY KEY (`test`)
)
```

```
$model = new Test();
$test->save(['test' => 'hello']);

```

**Comment by hisorange** [comment]
Happens on 2.1.0RC too, but in my case it goes a bit worse.
When I save a relation like
```php
$order->entries = [$entries];
$order->update();
```
It nulls the created_at on the order too.

**Comment by tidytrax** [comment]
here if is the primary key does not have a auto-increment, default values dont load
