### ISSUE TITLE
[Bug] In 'response' DI in which passing 404 status code can't rely on passed content

### ISSUE THREAD

**Issue by daison12006013** [phalcon/cphalcon#11611]
I'm using 2.0.10,

So I have this code:

```php
        // ... some codes.

        $response = di('response');
        $response->setContent($content);
        $response->setStatusCode(404);
        // $response->setStatusCode(500);

        return $response->send();
```

The ``$content`` is just a simple html with some 404 messages, however the passed html is not relying on it, here's the image: http://i.imgur.com/MptSdtP.png

If you will be changing the 404 into 500 or any status code except 404, the set content will work.

This is weird though that in the documentation has this: https://docs.phalconphp.com/en/latest/reference/response.html#returning-responses

@sergeyklay, mate can you confirm? or this is known issue or is this normal?

**Comment by sergeyklay** [comment]
I'll look into this as soon as I can. Ping me please in Slack

**Comment by daison12006013** [comment]
Sure :+1:

**Comment by sergeyklay** [comment]
```php
class IndexController extends ControllerBase
{

    public function indexAction()
    {
        header("HTTP/1.0 404 Not Found");
        echo "PHP continues.\n";
        die();
    }
}
```

![selection_138](https://cloud.githubusercontent.com/assets/1256298/14152408/da39c924-f6bb-11e5-9523-449ec7f72870.png)

```php
<?php

class IndexController extends ControllerBase
{

    public function indexAction()
    {
        header("HTTP/1.0 404 Not Found");
        echo "PHP continues.\n";
        die();
    }
}
```
![selection_139](https://cloud.githubusercontent.com/assets/1256298/14152419/eb2b3db2-f6bb-11e5-9c6e-1d879a96e8c5.png)

**Comment by daison12006013** [comment]
Yeah, this seems to be my 2.0.10 build when using --depth option when cloning this repository before.

So what I did was to pull the master branch again which I got a lot of updates, (dunno why). So building it again, and refreshed my page, and the content works well.

Thanks a lot @sergeyklay
