### ISSUE TITLE
Don't look through non-header server variables when calling getHeader

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#11626]
https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep#L257 this seems to be a mistake as it returns server variables in cases where server variables have the same name as the http header. The correct way should be to check for the HTTP_ variant (at least check it first) and maybe if it doesn't exist return the other.

**Comment by dschissler** [comment]
@Jurigag Is this correct behavior?  Are there edge cases where this is helpful or harmful?

**Comment by Jurigag** [comment]
I thinnk yea it should check first `HTTP_` variant, because indeed we can have rare cases as OP mention but you really should imho change it in your application to avoid such cases.

**Comment by nsossonko** [comment]
Using a custom USERNAME header hits this case. It's not something that I can change at this point (although I've fixed it myself locally already).

**Comment by nsossonko** [comment]
Still an issue
