### ISSUE TITLE
View setVars,setVar,disable not working in php7. 

### ISSUE THREAD

**Issue by JokeZhang** [phalcon/cphalcon#11628]
the view's setVar(),setVars(),disable() not work;

my controller code:
`$this->view->setVar('test','hellWord');
$this->view->disable();
`

my view code:
`<?php echo $test?>`

then output:
`Notice: Undefined variable: test in /data/wwwroot/shop/themes/views/backend/login/index.phtml on line 1`

System is Ubuntu.
PHP version is 7.0.5;
Palcon version is 2.1.0r;
compiling from Phalcon  branch using Zephir  0.9.2a-dev.

**Comment by Jurigag** [comment]
It's already reported.
