### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by Fenikkusu** [phalcon/cphalcon#11620]
Minor issue on Composer when trying with PHP 7

  Problem 1
    - Installation request for phalcon/cphalcon 2.1.x-dev -> satisfiable by phalcon/cphalcon[2.1.x-dev].
    - phalcon/cphalcon 2.1.x-dev requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.

**Comment by Green-Cat** [comment]
I already have a pull request to solve that issue.

**Comment by sergeyklay** [comment]
composer require --ignore-platform-reqs
