### ISSUE TITLE
Phalcon default services

### ISSUE THREAD

**Issue by makerlabs** [phalcon/cphalcon#11630]
I was actually wondering why all the service in phalcon implement the InjectionAware Interface rather than extend something like Phalcon\Di\Injectable which would reduce the need of unnecessary checks every time a service make a call to the service container.  It would make the code much cleaner in all default phalcon services and additional enforced the DRY concept.

**Comment by googlle** [comment]
If you can implement this feature, send a pull request

**Comment by makerlabs** [comment]
Im asking because it would require to update all the default phalcon services to do so it's a bit of a work and wanted to check first if the core team agrees to this change for 2.1.x or better to schelude it for 2.2.x?

**Comment by Jurigag** [comment]
2.1.x is still not realased, it's only RC, once all tests will be passing for php 7 then i guess it will be closed for release it(at least if there are still plan for full php 7 support in 2.1.x). So you still have time.

**Comment by sergeyklay** [comment]
Usually `RC` means no API additions (at least serious) only bug fixes. Of course we can make an exception to the rule, but this is not the case when it should be done

**Comment by Jurigag** [comment]
Well this is pretty serious API addition.

**Comment by tuxy** [comment]
If this delays the 2.1 stable release please wait for 2.1.x instead. Many of us are stuck with using PHP 5.6 and Phalcon 2.0 do to no good support of PHP 7 yet. Please concentrate on improving PHP 7 support in version 2.1 first before making more changes.

**Comment by makerlabs** [comment]
Additional the Phalcon\DI could be a bit optimized to only register services without the need of creating a new instance of class Phalcon\Di\Service in the process.

**Comment by Jurigag** [comment]
This class is kind of handy. And just used in DI in many places.

**Comment by makerlabs** [comment]
Yeah but you could seperate the definion building from the dependency container itself. I mean the using of a closure is a definion itself if I register a service:
`
$di->set('name', function() {
    // here goes my rest of dependencies usually passed either by the constructor, optional by additional methods or injected into the service if it extends Injectable for example
    return new ExampleService();
});
`

So at above definiton I do not need to build my service definition because it's already done by me.
But when I want I can register a service rather then set it then I want to define it set all the dependencies etc. Of course I can understand that the usage of Service is some what of simplifying the whole process with a small trade off but still the way I described it it could be optimized.

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
