### ISSUE TITLE
v2.1 RC1 QueryBuilder Error

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11634]
I've tried compiling v2.1 RC1 today to try it with PHP 7.0.5. I've installed Zephir 0.8 and run this following commands.

```
git clone http://github.com/phalcon/cphalcon
cd cphalcon
git checkout 2.1.x
zephir build
```

I get this error:

```
Zephir\ParseException: Syntax error in /cphalcon/phalcon/paginator/adapter/querybuilder.zep on line 168

	  var groups = totalBuilder->getGroupBy();
	----------------------------^
```

Also same error when using "zephir build --backend=ZendEngine3"

Any ideas? Thanks.

**Comment by Jurigag** [comment]
You need to compile phalcon with master zephir branch.

**Comment by tuxy** [comment]
@Jurigag I thought RC1 works with PHP 7.

**Comment by Jurigag** [comment]
No it doesn't. There are still many bugs to be fixed.

**Comment by andresgutierrez** [comment]
You have to use Zephir 0.9.3
