### ISSUE TITLE
[2.1RC] Namespace problem in annotation router

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#11638]
I use annotation router:

```
$router = new RouterAnnotations(false);

    $router->setDefaultModule('company');
    $router->setDefaultNamespace('Modules\Company\Controllers');

    $router->addModuleResource('company', 'Auth');
    $router->addModuleResource('company', 'Index');
    $router->addModuleResource('company', 'Error');
```

and this code work properly, however there is a problem, when I have another directory in controllers/ directory. I defined next controller (controllers/User/AccountController):
`$router->addModuleResource('company', 'User\Account');`
And I got ReflectionException:
`ReflectionException: Class User\User\AccountController does not exist`

This problem occured after update to 2.1RC

**Comment by Zaszczyk** [comment]
If I don't use setDefaultNamespace():

```
   $router->setDefaultModule('company');
    $router->setDefaultNamespace('');

    $router->addModuleResource('company', 'Modules\Company\Controllers\Auth');
```
there is such reuslt:
> ReflectionException: Class Modules\Company\Controllers\Modules\Company\Controllers\AuthController does not exist

The namespace from string is duplicated

**Comment by sergeyklay** [comment]
@Green-Cat Could you please deal with this

**Comment by Green-Cat** [comment]
@sergeyklay I'll look into it when I am home!

**Comment by fenixphp** [comment]
```php
$router = new \Phalcon\Mvc\Router\Annotations(false);

$router->setActionSuffix('');
$router->setControllerSuffix('');
$router->setDefaultNamespace('');
$router->removeExtraSlashes(true);
$router->setDefaultModule('Frontend');

$router->addModuleResource('Frontend', \Frontend\Controllers\Content\Index::class);
```
This configuration works with namespaces with annotation router.

**Comment by fenixphp** [comment]
php_phalcon.dll create 05-02-2016 This problem does not exist.
A php_phalcon.dll for the March 22, 2016 22:25:39 problem at all settings.

**Comment by JCMais** [comment]
I cannot find a way to make this work, any workarounds?

**Comment by JCMais** [comment]
From what I can gather the issue is originating here: https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/router/annotations.zep#L162

Stack trace:
> \# 0	ReflectionClass->__construct(Acme\Frontend\Controller\Acme\Frontend\Controller\IndexController)
\# 1	Phalcon\Annotations\Reader->parse(Acme\Frontend\Controller\Acme\Frontend\Controller\IndexController)
\# 2	Phalcon\Annotations\Adapter->get(Acme\Frontend\Controller\Acme\Frontend\Controller\IndexController)
\# 3	Phalcon\Mvc\Router\Annotations->handle()

**Comment by sergeyklay** [comment]
@Green-Cat
