### ISSUE TITLE
Assigning vars from controller to volt template don't work properly

### ISSUE THREAD

**Issue by benjamineukles** [phalcon/cphalcon#11636]
Hi,

I encounter a trouble with assigning vars from my controllers to my volt templates.
I'm using PHP 7 so I've compiled Phalcon from the 2.1.0r version.

Here is the code I use to create my view and my volt engine:

```
         $di->set(
            'volt', function ($view, $di) use ($config) {
            $volt = new \Phalcon\Mvc\View\Engine\Volt($view, $di);
            $volt->setOptions($config->get('volt')->toArray());

            return $volt;
        }
        );

        $di->set(
            'view', function () {
            $view = new \Phalcon\Mvc\View();
            $view->setViewsDir('../app/views/');
            $view->registerEngines(
                array(
                    ".volt" => 'volt'
                )
            );
            return $view;
        }
        );
```

Then in my controller if I try this in my action:
```
	public function indexAction() {

		$this->view->setVar('test', 'Hello World!');
	}
```

and in the corresponding volt template I put this:

`{{ dump(test) }}`

I get an error "Undefined variable: test in..."

To access my test variable in my tempalte it works with 
`{{ dump(view.test)}}`
or
`{{ dump(params['test'])}}`

So to have it working properly with "test" directly in my Template, I made an overload of the class Phalcon\Mvc\View\Engine\Volt and overload the render function like this:

```
namespace My;

use Phalcon\Mvc\View\Engine\Volt;

class MyVolt extends Volt {

    /**
     * Overload the Volt render function to have access to the variables assigned in controllers into the templates
     * (assigned with $this->view->setVar() in the controllers)
     *
     * @param string $templatePath
     * @param mixed  $params
     * @param bool   $mustClean
     */
    public function render($templatePath, $params, $mustClean = false) {
        if (gettype($params) === "array") {
            foreach ($params as $key => $value) {
                $$key = $value;
            }
        }

        parent::render($templatePath, $params, $mustClean);
    }
}
```

I guess it's an issue no? Any fix for this?

Regards,

Ben.

**Comment by Jurigag** [comment]
Just read other issues. Phalcon don't work with php 7 yet.

**Comment by benjamineukles** [comment]
Yes I know, but I've read that 

> Phalcon 2.1.x has beta PHP7 support, we expect to fix any blocking bug in the next two weeks before the final release

So I just wanted to contribute for this and report this bug, I didn't find any other issue reporting this bug.

**Comment by Jurigag** [comment]
But it was already reported many times. https://github.com/phalcon/cphalcon/issues/11465 https://github.com/phalcon/cphalcon/issues/11628 https://github.com/phalcon/cphalcon/issues/11616

**Comment by benjamineukles** [comment]
Ok sorry, I didn't find it. I hope my "fix" will be helpful for somebody :)
