### ISSUE TITLE
Test Proxy classes

### ISSUE THREAD

**Issue by makerlabs** [phalcon/cphalcon#11639]
Why do we use this classes in tests anyway? Because of them I wasted today one and a half hour because one of my test was returning wrong result and after many WTF statements I realize that the problem was not my changes, not zephir the problem was wrong written proxy class which passed in one method 2 arguments instead of 3... If we can remove them please do so because they only complicate the testing phase...

**Comment by sergeyklay** [comment]
Did you seen https://github.com/phalcon/cphalcon/blob/2.1.x/tests/README.md

**Comment by Jurigag** [comment]
Are you using newest repo ? I fixed all proxy classes already.

**Comment by makerlabs** [comment]
@sergeyklay Ok admited I was to laisy to read to the end. Why not generate them on the fly or by using a script?

**Comment by Jurigag** [comment]
If we would generate them on the fly or using script it will slow down the travis build which is already slow i guess.

**Comment by makerlabs** [comment]
Yeah I already saw that thanks.
