### ISSUE TITLE
[2.1 RC1] When using multiple directories in setViewsDir, views with same name are rendered for each dir

### ISSUE THREAD

**Issue by maurits150** [phalcon/cphalcon#11633]
It seems that when using multiple view directories ($view->setViewsDir(['dir1', 'dir2']), and a view with same name exists in both directories, both files get rendered.

I'm not sure if this is intended behavior, but it seem unintuitive to me in the case of a hierarchical view system where only the first found view should be rendered.

Solution seems to be to change the following line to the Zephir equivalent of "break 2;" instead of just a plain break.

https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/view.zep#L714

This makes that not just the [engines loop](https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/view.zep#L690) is terminated, but the [view directories loop](https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/view.zep#L623) also.

**Comment by dschissler** [comment]
Is this a bug or should this be the behavior?

**Comment by Jurigag** [comment]
Didn't even knew that you can set array there actually, never used it like this, not sure, it might be a bug. If this change which OP proposed will fix it then great.

**Comment by dschissler** [comment]
I think that was added with Phalcon 2.0 or 2.1 but I never used it since I designed my platform before that was an option.

Probably it should just stop the loop since it is also more work for the typical case where the same view doesn't exist in other directories.
