### ISSUE TITLE
Phalcon\Test\Module\UnitTest extends non exisiting class

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11650]
I don't even know how it's currently working but right know `Phalcon\Test\Module\UnitTest` extends non exisiting class in CodeCeption 2.2. I think it needs to be changed to `Codeception\Test\Unit`

@sergeyklay also what IDE are you using ? I added Codeception\Codeception Codeception\Verify and Codeception\Specify to libraries in phalcon project in PHPStorm and it doesn't see any methods in `except($something)` for some weird reason. Is autocomplete working for you ?

**Comment by sergeyklay** [comment]
Yes, we need to this. Did you seen https://github.com/Codeception/Codeception/blob/master/shim.php

**Comment by Jurigag** [comment]
Oh okay, but when i am changing `Codeception\TestCase\Test` to `Codeception\Test\Unit` then there must be method implemented `getName()` so not sure what it should return.

**Comment by sergeyklay** [comment]
Fixed in `2.1.x` branch
