### ISSUE TITLE
[php7 2.1.x]$view->registerEngines(array('.html' =>'\Phalcon\Mvc\View\Engine\Php')); error

### ISSUE THREAD

**Issue by cq-z** [phalcon/cphalcon#11666]
set $view->registerEngines(array('.html' =>'\Phalcon\Mvc\View\Engine\Php'));
the .html file is run。but $view->getContent()；is empty

**Comment by cq-z** [comment]
the code in [php56  2.1.x] is OK

**Comment by sergeyklay** [comment]
Refs #11583

**Comment by Jurigag** [comment]
@sergeyklay "Duplicate"

**Comment by sergeyklay** [comment]
Thanks

**Comment by cq-z** [comment]
Thanks ALL

**Comment by Jurigag** [comment]
@cq-z it should work fine now when phalcon is compiled with newest zephir

**Comment by cq-z** [comment]
```
Author	Phalcon Team and contributors
Version	2.1.0r
Build Date	Apr 27 2016 10:28:25
Powered by Zephir	Version 0.9.3a-dev
```
now is OK .
Thanks
