### ISSUE TITLE
Duplicate insert records in Chrome, help me!

### ISSUE THREAD

**Issue by tnt2306** [phalcon/cphalcon#11662]
Reload page, there are two records insert to database, if using phsql will not generate error duplicate records
Testing on firefox is OK,  Chrome is ERROR ?

Help ... thanks all friends

- Phalcon 2.1.0.RC1 - Windows x86 for PHP 5.6.0 (vc11) 
- Using: https://github.com/phalcon/mvc/tree/master/simple-volt

- Code in Controller
```
public function indexAction() {
		$user = new User();
		$user->username = 'abc_' . rand();
		$user->email = 'abc' . rand() . '@gmail.com';
		$user->password = rand();
		$user->save();
	}
```

- Models User.php
```
use Phalcon\Mvc\Model;
class User extends Model {
	public $user_id;
	public $username;
	public $email;
	public $password;
	public function initialize() {
		$this->setSource('user');
	}
}
```
- Database: Postgres
```
CREATE TABLE "user"
(
  user_id serial NOT NULL,
  username text NOT NULL,
  email text NOT NULL,
  password text NOT NULL,
  CONSTRAINT primary_key_user_id PRIMARY KEY (user_id),
  CONSTRAINT unique_email UNIQUE (email),
  CONSTRAINT unique_username UNIQUE (username)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "user"
  OWNER TO postgres;
```

**Comment by sergeyklay** [comment]
Did you check this:
https://github.com/phalcon/cphalcon/issues/10761
https://github.com/phalcon/cphalcon/issues/1598
