### ISSUE TITLE
phalcon apc_fetch not support array(multiple key)?

### ISSUE THREAD

**Issue by nagaho** [phalcon/cphalcon#11689]
http://php.net/manual/en/function.apc-fetch.php
https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/backend/apc.zep#L59

**Comment by sergeyklay** [comment]
Do you mean Phalcon Cache interface?
https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/backendinterface.zep#L91

**Comment by nagaho** [comment]
yes.

**Comment by sergeyklay** [comment]
You propose to refacor all cache adapters which implemets cache interface? can't understand

**Comment by nagaho** [comment]
Phalcon Apc class get method parameter keyName is only string. However apc_fetch's parameter supports not only String but also Array. Need not support multiple key?

**Comment by sergeyklay** [comment]
In order to do this we have modify cache interface and all adapters

**Comment by nagaho** [comment]
OK. I'll use general APC lib from now, and develop multiple get and set when I'm available. Thanks.
