### ISSUE TITLE
Error on create new model with only 1 column auto-increment

### ISSUE THREAD

**Issue by alkana** [phalcon/cphalcon#11687]
Hello,

I'm trying to insert (MySQL) new row in this table :

``` sql
CREATE TABLE IF NOT EXISTS `group` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT ''
) ENGINE = InnoDB;
```

My table have only 1 column (and it's an auto-increment)

The model corresponding :

``` php
<?php

class Group extends \Phalcon\Mvc\Model
{
    /**
     *
     * @var integer
     */
    protected $id;

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    public function afterFetch()
    {
        $this->id = (int) $this->id;
    }
}
```

So, when I try to create new group like that :

``` php
<?php

$group = new Group();
$group->create();
```

Phalcon throw an exception `Phalcon\Db\Exception: Unable to insert into group without data`

This exception come from:
https://github.com/phalcon/cphalcon/blob/phalcon-v2.0.10/phalcon/db/adapter.zep
line 311

I don't found any solution to get round this validation (all values are clean up by the model).

Phalcon version: 2.0.10
Mysql: 5.7.11 - MySQL Community Server (GPL)

**Comment by SidRoberts** [comment]
FWIW, you can get around this problem by adding a timestamp field (see https://docs.phalconphp.com/en/latest/reference/models.html#timestampable).

**Comment by alkana** [comment]
Hi,

Thank you for your answer.

I did something like that, I added a field who maybe one day I will use.
