### ISSUE TITLE
Bad gateway 502 when  use  Xhprof with php5.6 +  nginx + phalcon2.0.x

### ISSUE THREAD

**Issue by xkos** [phalcon/cphalcon#11693]
this is my environment
`debian 8
nginx 1.8
php 5.6
phalcon 2.0.x
xhprof 0.9.2`
when i running i get error 502:
`2016/04/21 19:48:08 [error] 21873#21873: *189 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: xxx, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/to/path/php-fpm.sock:", host: "xxx"`
this is gdb trace:
`Program received signal SIGSEGV, Segmentation fault.
hp_execute_internal (execute_data=0x7fffffffa540, fci=0x7fffffffa4a0, ret=1, 
    tsrm_ls=0x1204030)
    at /usr/local/src/php-ext/xhprof-0.9.4/extension/xhprof.c:1708
1708        temp_variable *retvar = &EX_T(opline->result.var);  
`
i checked this code make the 502 error:
`$di = new DiFactory();`
if i disable the xhprof, it can use.
how to deal this bug?

**Comment by Jurigag** [comment]
Maybe its just a bug with xhprof ?

**Comment by stamster** [comment]
So, xhprof binary causes this SegFault. Did you try running it w/o Phalcon binary? Just remove/rename phalcon.ini from mods-available dir of PHP.

**Comment by slilin** [comment]
@stamster  i run xhprof without phalcon, and it works

**Comment by Jurigag** [comment]
You know that last update to xhprof was lik 2-3 years ago ?

**Comment by slilin** [comment]
I know. And I'm wondering why it stop updating. it is a good tools for me.
Then, what tool should I use to analyze  performance with phalcon? Can you give me some suggest?
@Jurigag

**Comment by Jurigag** [comment]
xdebug ?

**Comment by slilin** [comment]
thinks , i will try it
