### ISSUE TITLE
UrlManager get 

### ISSUE THREAD

**Issue by Newbas** [phalcon/cphalcon#11715]
In Url manager there is regular expression to check is it local URL or not, and we got problem with colon in url, if colon exists in URL, then manager use it as not local. But it is not true. 

Here: 
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/url.zep#L188
`preg_match("#^(//)|([a-z0-9]+://)|([a-z0-9]+:)#i", uri)`
Line begin here used only for //, not for all components of regexp. 

http://refiddle.com/8re2 here is example how this regexp process such data.

So it looks like it should be 
`preg_match("#^((//)|([a-z0-9]+://)|([a-z0-9]+:))#i", uri)`
To validate different schemas from begin of the line. 
And here is example http://refiddle.com/8ren

**Comment by sergeyklay** [comment]
Looks good to me. Could you please create a PR with small test case?

**Comment by Newbas** [comment]
Ok, will do it.

**Comment by Newbas** [comment]
@sergeyklay sorry, could not find any info about it. I am trying to push my branch with changes, but i don't have access for this repository.

**Comment by sergeyklay** [comment]
You have to create [Pull Request](https://help.github.com/articles/using-pull-requests/)

**Comment by Newbas** [comment]
@sergeyklay Thanks, worked only with private repos.
