### ISSUE TITLE
Proposal: support usort function in resultset

### ISSUE THREAD

**Issue by friparia** [phalcon/cphalcon#11714]
Sometimes it is useful to sort the resultset by the customized sort function, but i find it not implemented this function.
The code maybe like this:
```php
usort($result, function($a, $b){
    if($a->someFunction() == $b->someFunction()){
        return 0;
    }
    return ($a->someFunction() > $b->someFunction()) ? -1 :1;
});
//or
$result->usort(function($a, $b){
    if($a->someFunction() == $b->someFunction()){
        return 0;
    }
    return ($a->someFunction() > $b->someFunction()) ? -1 :1;
});
```

**Comment by Jurigag** [comment]
Whats a problem with sorting in mysql ?

**Comment by friparia** [comment]
@Jurigag a part of data is not stored in mysql database

**Comment by Jurigag** [comment]
So what database you are using ? It's not providing order functionallity ?

**Comment by friparia** [comment]
well, i get a set of data from mysql, and then i need to fetch data in redis for each row and calculate a value, after that, i need to sort all the resultset. And i think usort is a more convenient way to finish my work.

**Comment by Jurigag** [comment]
Then it's bad behaviour beacause it will be slower.

**Comment by friparia** [comment]
That's a better way, anyway, thanks.

**Comment by Jurigag** [comment]
In mysql you have indexes etc. If you do some testing you will figure it out that ordering in mysql is almost always faster than by php functions. Well maybe this functionality would be nice if we order it on some small resultset, then performance difference would not be huge but still.

**Comment by friparia** [comment]
Yes, it is a convenient function for coding but not a fast function for the application.
