### ISSUE TITLE
 implement interface Phalcon\ValidationInterface, instance of Phalcon\Mvc\Model\Validator\Uniqueness given

### ISSUE THREAD

**Issue by surjit** [phalcon/cphalcon#11713]
I used this example https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model_Validator_Uniqueness.html

**Comment by andresgutierrez** [comment]
What version of Phalcon are you using?

**Comment by surjit** [comment]
phalcon_x86_vc11_php5.6.0_2.1.0.RC1.zip

**Comment by fenixphp** [comment]
#11464

**Comment by ugurozturk** [comment]
Same as here full xdebug error : 

 Catchable fatal error: Argument 2 passed to Phalcon\Validation::add() must implement interface Phalcon\Validation\ValidatorInterface, instance of Phalcon\Mvc\Model\Validator\Uniqueness given in C:\laragon\www\notpaylasim\app\models\Users.php on line 34

2.1.0 RC 1

**Comment by sergeyklay** [comment]
Documentation isn't fully updated yet. So you guys are using the documentation related to the Phalcon 2.0.x for Phalcon 2.1.x. As @fenixphp mentioned see #11464

**Comment by ugurozturk** [comment]
@sergeyklay I tried to use it too. Then the Uniqueness had throw up like something gone wrong. Installed Phalcon 2.0.9 and everyting works fine for now
