### ISSUE TITLE
is the view path case insensitive in phalcon 2.1.x?

### ISSUE THREAD

**Issue by slilin** [phalcon/cphalcon#11711]
i found the view dir case insensitive when i use phalcon 2.1.x
i use debian os
this is my folder:
>home/
     

> >controllers/

        

> > >IndexController.php

    

> >views

        

> > >index/

               

> > > >index.volt

when i run it, it show nothing
when i change the folder name index to Index, it works.
is the view path case insensitive in phalcon 2.1.x?
can i setting it to gnore case?

**Comment by andresgutierrez** [comment]
It always uses lowercase, also for questions like this you can use forum: https://forum.phalconphp.com/
