### ISSUE TITLE
Issue with Redis adaptor in 2.0.10

### ISSUE THREAD

**Issue by al35mm** [phalcon/cphalcon#11722]
Deleting a Redis cache key does not work - `$this->cache->delete($key);`. I am sure it was working in previous version of Phalcon, however, Redis sessions were not working in last version. I haven't tried in current version. Can anyone give me a status of Redis adaptor please? Is this a bug?

**Comment by Yurist-85** [comment]
The same issue [#12326]

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
