### ISSUE TITLE
webtools has wrong APP_PATH by default

### ISSUE THREAD

**Issue by stratoss** [phalcon/cphalcon#11738]
Hi, I'm playing around with Phalcon, and found an issue:

1) Created a project with `phalcon project test`
2) Enabled the web-tools with `phalcon webtools enable`
3) The main site saying that i'm flying with you, which is OK but
4) Trying to create a controller through `/webtools.php?_url=/controllers` I've got a message stating 
```
Sorry, WebTools doesn't know where the controllers directory is.
Please add the valid path for controllersDir in the application section.
```

Debugging around and I found that `/app/config/config.php` is defining it using `realpath('.')` which is okay for the main app, but not for the webtools script, as there APP_PATH is including the /public directory and all relevant paths, including the `controllersDir` are wrong. 

I've fixed it by adding `str_replace('/public', '', realpath('.'))` for now.

I'm using the default nginx setup with php5-fpm on debian stretch.sid if that matters.

Thank you for the great framework otherwise! I'm really impressed by the speed and the documentation.

edit: probably should open another issue for this, but forgot to mention that `phalcon project test` created default baseUri to be `/test/` which is wrong (it should be `/` )

**Comment by sergeyklay** [comment]
This is not Phalcon issue. Could you please open issue at [Devtools repo](https://github.com/phalcon/phalcon-devtools)?

**Comment by stamster** [comment]
I wrote long time ago about this issue. As I know, Webtools are planned to be re-developed from scratch.

**Comment by stratoss** [comment]
You're right... thanks
