### ISSUE TITLE
After  use $model->toArray(), $model can not be each anymore.

### ISSUE THREAD

**Issue by 4-1-1** [phalcon/cphalcon#11739]
![image](https://cloud.githubusercontent.com/assets/4401981/15012088/673285a0-1228-11e6-9225-8eade17fb717.png)
when the rows nums more than eighty.
After  use $model->toArray(), $model can not be each anymore.

is it a bug?

**Comment by Jurigag** [comment]
Wtf is `$dataresult->toArray()` you can just do `if(!empty($dataresult)` ? I guess you have too little memory to do toarray.

Also first create thread on forum, if you sure if it's issue then create issue. Also use binding.

**Comment by SidRoberts** [comment]
Actually, you use just use:

```php
// ...

$i = 0;

if ($dataresult) {
    $a = 222;

    // ...
```

Binding parameters: https://docs.phalconphp.com/zh/latest/reference/models.html#binding-parameters

**Comment by Jurigag** [comment]
Well i wasn't sure.

**Comment by laodalaoda520** [comment]
@Jurigag @SidRoberts  I know how to avoid this problem, I just do't undeerstand it, want to figure it out ,why it happen

**Comment by Jurigag** [comment]
```
I guess you have too little memory to do toArray and code after toArray is not even executed.
```

**Comment by laodalaoda520** [comment]
no  ,no error , I mean, the last i got [$a, $i] ，［222，0］

**Comment by laodalaoda520** [comment]
may be , the method toArray ,put the pointer of data to end?

**Comment by Jurigag** [comment]
Yes, beacause it's iterating the object using its own iterator. I guess toArray method needs to put pointer at the beginning resultset.

**Comment by laodalaoda520** [comment]
thanks very much

**Comment by Jurigag** [comment]
It's still a minor bug - toArray method at the end of it should set pointer of resultset to beginning of it. But maybe it's intentional to avoid developers write bad code :)

**Comment by laodalaoda520** [comment]
haha, I saw the source of this method on github, but I did't knew C language much

**Comment by Jurigag** [comment]
You don't need to know c language, it's wrote in zephir.
