### ISSUE TITLE
2.0.11: Macro was called without parameter condition

### ISSUE THREAD

**Issue by wiesl** [phalcon/cphalcon#11745]
After upgrading to 2.0.11 I'm getting the following error: Macro was called without parameter condition

Reverting to 2.0.10 works well.
```volt
{%- macro conditionaldate(condition, tdate, ttime, tz) %}
    {% if condition %} from <br/>{{ tdate }}, {{ ttime }} {{ tz }}{% endif %}
{%- endmacro %}

{{ conditionaldate(count_data > 0, tdate, ttime, tz) }}
```
Looks like it comes from the following change:
> Fixed `Phalcon\Mvc\View\Engine\Volt::callMacro` bug. Now it's correctly calling `call_user_func_array` instead of `call_user_func`

Any ideas?
https://forum.phalconphp.com/discussion/11419/2011-macro-was-called-without-parameter-condition

Well actually it was done to fix custom user functions, filters etc beacause they weren't working(they weren't passing parameters because `call_user_func` was executed, they are calling `callMacro` too, and working right now). I don't know why it broked macros.

Im not sure what has to be done here to make both of them working. You should create an issue on github. You can copy my above explanation why this change was made.

Im not sure you can use it like this. Can you first try to set `count_data > 0` to same variable and then call macro with variable ? Also it's weird that it was working on 2.0.10, it shouldn't too, beacause nothing was changed there, I only changed one function which shouldn't have any effect on this.

**Comment by Jurigag** [comment]
I think it's not a problem with `calluser_func_array`. I think the condition can be just passed as `count_data > 0` here. It expects variable i think, not expression.

**Comment by wiesl** [comment]
{% set countdataflag = count_data > 0 %}

{{ conditionaldate(countdataflag, tdate, ttime, tz) }}

But still the same.

**Comment by Jurigag** [comment]
Well, then i don't know what's going on. Try to pass value of `count_data > 0` as view variable, just to test it it's not a some problem in this case.

**Comment by wiesl** [comment]
I guess it comes from the following change:
Fixed `Phalcon\Mvc\View\Engine\Volt::callMacro` bug. Now it's correctly calling `call_user_func_array` instead of `call_user_func`

**Comment by Jurigag** [comment]
Not it doesn't. callMacro is not executed here.

**Comment by Jurigag** [comment]
Did yo uchecked maybe what will happen if you will set in php in controller `count_data > 0` and pass value of it as variable to view and use this variable ? Is it still happening ?

**Comment by sergeyklay** [comment]
It gets fixed if we mark that parameter as optional. 
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt.zep#L288
```zephir
array arguments = []
```

**Comment by wiesl** [comment]
Can you push the fix?

**Comment by Jurigag** [comment]
@sergeyklay 

But this exception which he has is thrown here:

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt/compiler.zep#L1911

Is it first called and then compiled then ?

**Comment by sergeyklay** [comment]
I'll try to deal

**Comment by rvanderfeer** [comment]
Not sure if this is related; I am calling a macro with 3 arguments, the first of which is an object.

I now get the error; `Cannot use object of type [TheObjectType] as array` when running the compiled macro where it was working fine before the update to 2.0.11.

It appears that the compiled macro expects to be called with a single array argument `function(array $arg){}` , where it is actually (still) called with consecutive arguments `function($arg1, $arg2, ... $arg_n){}`

This obviously breaks existing macros so is quite a serious bug for us.

**Comment by jellisii** [comment]
When can we expect this on the PPA?  We just updated this morning and are having the same problem.

**Comment by sergeyklay** [comment]
@jellisii We'll try to fix it in `v2.0.12` and release this version in the coming days

**Comment by jellisii** [comment]
Thank you sir.  I've reverted to a custom build using commit a5f615d as its source for the time being.

**Comment by Jurigag** [comment]
@rvanderfeer 

Yea, it must be a bug in compiler, it must call function with arguments as array, for me from 2.0.5 i think were callMacro was introduced it broke functions, filters etc, so that's why i had to do this commit which was mention here. Well it's pretty obvious that was needed to changed, just forgot that there are macros as well and it might broke it.

**Comment by sergeyklay** [comment]
@wiesl Can you please check the 2.0.x branch?

**Comment by sergeyklay** [comment]
@jellisii

**Comment by sergeyklay** [comment]
Thanks for your report. This issue has been fixed in 2.0.x branch. We will release v2.0.12 in coming days with this bug fix.

**Comment by wiesl** [comment]
Thnx, verified on master.

**Comment by jellisii** [comment]
Testing looks good.  Thanks.
