### ISSUE TITLE
Phalcon - update dynamically/update not working

### ISSUE THREAD

**Issue by arthurgermano** [phalcon/cphalcon#11748]
Hi.. I have the following scenario:

1) I have a record created on the database several fields - some of those the user never interacts with.
2) I will update a single row using $model->update().
3) The fields that I don't want to update I am not sending, but since I create the object like
- $model = new Model($post);
  It brings all the fields in the model anyway

4) Yes, I have tried (new Model())->update($post) it returns false I don't know why.
5) I am using columnMap
6) I am using beforeSave or beforeCreate/beforeUpdate - tried both ways still nothing

And no matter what I do, phalcon still update the fields that I am not sending to the database.

I am thinking it is because columnMap but I need that method.

Does anyone please can help me ? 
Follows the initialize method

public function initialize() {
        $this->di = $this->getDI();

```
    $this->setConnectionService('oracle');
    $this->setSource(strtoupper(APP_TABLE_PREFIX . $this->tableName));
    $this->useDynamicUpdate(true);
    $this->skipAttributesOnUpdate(array('cpfResponsavel', 'dtCarga', 'dtCadastro'));

    $this->belongsTo('idTipoLote', '\App\Models\Tipo', 'idTipoLote', array('alias' => 'Tipo'));
    $this->belongsTo('idSituacaoLote', '\App\Models\SituacaoLote', 'idSituacaoLote', array('alias' => 'SituacaoLote'));

}
```

Many thanks!

**Comment by arthurgermano** [comment]
Hi.. so I just find out that really is because columnMap() method.

But I have to use it. So this is kind of a bug right ?

Please someone ? 

Many thanks.

**Comment by andresgutierrez** [comment]
Could you please post a script that help us to reproduce the issue? 

https://github.com/phalcon/cphalcon/wiki/Submit-Reproducible-Test

**Comment by arthurgermano** [comment]
Hi... I tried to do a script. Please if I did something wrong tell me so I can do it right.

`
<?php

use Phalcon\DI;
use Phalcon\Events\Manager as EventsManager;
use Phalcon\Db\Adapter\Pdo\Mysql as Connection;
use Phalcon\Mvc\Model\Manager as ModelsManager;
use Phalcon\Mvc\Model\Metadata\Memory as ModelsMetaData;

$eventsManager = new EventsManager();

$di = new DI();

$connection = new Connection(array(
    "host" => "localhost",
    "username" => "root",
    "password" => "",
    "dbname" => "test"
));

$connection->setEventsManager($eventsManager);

$eventsManager->attach('db',
    function ($event, $connection) {
        switch ($event->getType()) {
            case 'beforeQuery':
                echo $connection->getSqlStatement(), "<br>\n";
                break;
        }
    }
);

$di['db'] = $connection;
$di['modelsManager'] = new ModelsManager();
$di['modelsMetadata'] = new ModelsMetadata();

if (!$connection->tableExists('user')) {
    $connection->execute('CREATE TABLE user
  (
    "IDUSER"         NUMBER(6,0) NOT NULL ENABLE,
    "DTCARGA" DATE,
    "QTDREGISTROS" NUMBER(6,0),
    "VLRTOTAL"     NUMBER(13,2),
  
    CONSTRAINT "TB_USER_PK" PRIMARY KEY ("IDUSER")
  )');
}

class User extends \Phalcon\Mvc\Model
{
    protected $idUser;
    protected $dtCarga;
    protected $qtdRegistros;
    protected $vlrTotal;

    
    public static function myCustomUserCreator()
    {
        $newUser = new User();
        $newUser->setIdUser(1);
        $newUser->setDtCarga('2016-May-05');
        $newUser->setQtdRegistros(300);
        $newUser->setVlrTotal(50000);
        if ($newUser->save() == false) {
            return false;
        }
        
        return $newUser->id;        
    }
    
    //THIS IS WHERE THE PROBLEM HAPPENS!!!
    public static function myCustomUserUpdator($post)
    {
        $update = new User($post);
        if ($update->update() == false) {
            return false;
        }
        
        //NOW I DIDN'T SET NEITHER DATE OR VLRTOTAL, BUT IT WILL UPDATE ANYWAY TO NULL OR 0 =(
        return $update->id;        
    }
    
    public function columnMap() {
        //mapping var name correponding to table field name
        //Case sensitive!
        //The fields in the database are UPPER_CASE
        return array(
            'IDUSER' => 'idUser',
            'DTCARGA' => 'dtCarga',
            'QTDREGISTROS' => 'qtdRegistros',
            'VLRTOTAL' => 'vlrTotal',
            'PHALCON_RN' => 'phalcon_rn'
        );
    }
    
    function getIdUser() {
        return $this->idUser;
    }

    function getDtCarga() {
        return $this->dtCarga;
    }

    function getQtdRegistros() {
        return $this->qtdRegistros;
    }

    function getVlrTotal() {
        return $this->vlrTotal;
    }

    function setIdUser($idUser) {
        $this->idUser = $idUser;
    }

    function setDtCarga($dtCarga) {
        $this->dtCarga = $dtCarga;
    }

    function setQtdRegistros($qtdRegistros) {
        $this->qtdRegistros = $qtdRegistros;
    }

    function setVlrTotal($vlrTotal) {
        $this->vlrTotal = $vlrTotal;
    }

    public function beforeSave(){
        //this is just a sample I'll do loads of things here, but I will 
        //go throught each field setting into a specific format unless the field is null
        //then I will not touch it
    }
}

echo User::myCustomUserCreator();

$post['idUser'] = 1;
$post['qtdRegistros'] = 10;
echo User::myCustomUserUpdator($post);

`

Thanks Andres..

**Comment by arthurgermano** [comment]
Hi.. I am using this function either inside User class script example

`
    public function initialize() {
        $this->useDynamicUpdate(true);
        $this->skipAttributesOnUpdate(array('cpfResponsavel', 'dtCarga', 'dtCadastro'));
    }
`

**Comment by arthurgermano** [comment]
Hi.. Good morning.. So .. I am still having this problem, but since I am in a project and it have delivery date. To surround this issue I have edited my row, sent it back to update... but before I do that I have to load the object again from the database and then use merge php array function =S - I don't need to say that performance went down the hole =S. A lousy solution but a way out for now..

I am still at your disposal to help solve this.

Many Thanks.. Cheers!

**Comment by Jurigag** [comment]
What you mean you didn't send them ? You send them by creating `new User` object. You need to find exisiting one in database and then update it. If you aleady have an user in database why you creating it again in your code instead of updating it(first find it and then update ?) ?

Also if you have iduser primiary key then set it ot AI and get rid of setting id for user.

This should look like this:

```php
    public static function myCustomUserUpdator($post)
    {
        $update = User::find($post['idUser']);
        unset($post['idUser']);
        if ($update->update($post) == false) {
            return false;
        }

        //NOW I DIDN'T SET NEITHER DATE OR VLRTOTAL, BUT IT WILL UPDATE ANYWAY TO NULL OR 0 =(
        return $update->id;        
    }
```

**Comment by arthurgermano** [comment]
Yes.. this is a nice way.. but since I am editing an row... that means I already have all the information about the row that I need.. I was kinda not wanting to find the row again you know... 

Kinda of like this..
1) Open edit page.. 
2) I change some values..
3) update my values.. only the ones I have changed.

But If I apply your solution.. what I am doing to solve it for now.. is like
1) Open edit page..
2) I change some values..
3) Find the row again.. merge some values with what I just found..
4) update my values.. all of them.

That means I have to go to the database once more. And with loads of access there is going to be some loss in respond it..

**Comment by Jurigag** [comment]
Then use existing USER OBJECT ?

```php
 public static function myCustomUserCreator()
    {
        $newUser = new User();
        $newUser->setIdUser(1);
        $newUser->setDtCarga('2016-May-05');
        $newUser->setQtdRegistros(300);
        $newUser->setVlrTotal(50000);
        if ($newUser->save() == false) {
            return false;
        }

        return $newUser;        
    }
```

```php
$user = User::myCustomUserCreator();
$post['idUser'] = 1;
$post['qtdRegistros'] = 10;
echo User::myCustomUserUpdator($post, $user);
```

```php
    public static function myCustomUserUpdator($post, User $user = null)
    {
        if(empty($user)) {
            $update = User::find($post['idUser']);
            unset($post['idUser']);
        }
        else {
            $update = $user;
        }
        if ($update->update($post) == false) {
            return false;
        }
        if ($update->update() == false) {
            return false;
        }

        //NOW I DIDN'T SET NEITHER DATE OR VLRTOTAL, BUT IT WILL UPDATE ANYWAY TO NULL OR 0 =(
        return $update->id;        
    }
```

**Comment by arthurgermano** [comment]
No men.. please don't be judgemental.. we are all here to learn.. I don't know everything.. ok.. and I think that you do not read all the problem, so I will explain it again:

So.. the facts are these:
1) First:  I want to update a row which information I already have loaded; It is an existing row in the database;
2) Second: I don't want to execute another find that means execute this line again User::find($post['idUser']); 
because I just want to update one or two fields of my row, and since I have the information in hand seems logical to me just update what i want like 

hey phalcon.. update user set vlrLote = xxxx where idLote = 1... thanks!

3) Third: I would like to do a parcial update that means I will be using 
$this->useDynamicUpdate(true);
$this->skipAttributesOnUpdate(array of fields);

4) Problem -> Phalcon will update all the fields not the ones I just sent.
So if I send just idUser and vlrTotal like
$post['idUser'] = 1;
$post['vlrTotal'] = 10;
User::update($post); it will return false; I don't dig deeper to find out why

so.. I have tried another aproach.. 
$user = new User();
$user->update($post);
This works but it will update all the fields not just the fields that I sending to. Meaning that qtdRegistros will be update to Null or 0 and the other fields as well

I am just trying to solve this.. Sometimes we make mistakes... maybe I am not seeing it cleary but that why I am seeking help.

Even the most advanced programmers forgot ; or make common mistakes =)

Thanks!

**Comment by Jurigag** [comment]
It's not phalcon, every ORM will update it like this you need the object with values from current row in database, by creating new object from just:

```php
$post['idUser'] = 1;
$post['qtdRegistros'] = 10;
```

You are telling phalcon that other fields are null/0. So they will save null/0 into database, as it should be.

If you want this behaviour you are writeing here you need to use PHQL as i stated above. Just read my full post.

Read documentation. Dynamic update is not for saving the columns which you are passing. Dynami update is for saving only that columns which **WERE CHANGED IN OBJECT**

**Comment by arthurgermano** [comment]
Ok.. But I used to work with CakePHP.. I am migrating to phalcon now..
WIth cake.. I just can say that.. set the ID and the values that I want to change and then pass the object just like I did like..

hey save these fields in this row ID..

I understand that Dinamyc Update is just to save the values and columns which I am passing.
But I am also saying
skipAttributesOnUpdate - That means if I execute and update no matter what skip these values please. I don't want to update these ones.

and I think that if I say skip this .. it should skip.. even if I pass values or not.. It would have just to ignore the values.. don't you agree ?

**Comment by Jurigag** [comment]
Well yes, skipAttirbutesOnUpdate hould do this, but i don't see `initialize` method in your code right now.

**Comment by arthurgermano** [comment]
Sorry.. I put it inside a comment right below the script...
Follows the initialize function

`
public function initialize() {
    $this->useDynamicUpdate(true);
    $this->skipAttributesOnUpdate(array('dtCarga', 'vlrTotal'));
}

**Comment by arthurgermano** [comment]
These fields will be update from outside of my application.
And there are some fields for example CreatedAt that should never be updated.

In my real case I have a number to identify the responsable user of that row. I don't want to update that. That row kinda belongs to him.. But an Administrator can update this row too but not meaning change of ownership. It will always belong to that user.

**Comment by Jurigag** [comment]
What will happen if you will values in array which you are passing to skip attributes to uppercase ? Im guessing skip attributes totallty ignores columnmap right now ?

**Comment by arthurgermano** [comment]
I will give it a shot.. 

but I don't know because I am using belongsTo() not in the script but in my real case.. and it works just fine.

let me set to upper case and test it here.. 
just a minute.. 

thanks men.

**Comment by Jurigag** [comment]
It doesn't have anything to do with belongsTo. just change this here:

```$this->skipAttributesOnUpdate(array('cpfResponsavel', 'dtCarga', 'dtCadastro'));```

to uppercase.

**Comment by arthurgermano** [comment]
Yes men.. because my belongsTo uses like this
$this->belongsTo('idTipoLote', '\App\Models\Tipo', 'idTipoLote', array('alias' => 'Tipo'));

Look the case I am using. And phalcon understand just fine.. 

but it worked just fine now..  
If we set it to UPPERCASE it works!!! Now it is ignoring the fields in the list!
I now don't have to use FIND again.. =) very nice solution my friend! 

Many thanks =)

**Comment by Jurigag** [comment]
@arthurgermano 

It's not a solution, it's a workaround to a bug right now because skipAttributes should check if there is any columnMap and get real field values from columnmap.

Also i would recommend to create some abstract code and put there some code for generating array for columnMap, beacause it can become pretty nasty with big tables(but this will need to you to change your names in database). I don't even know why you have uppercase in database, i prefer underscore.

**Comment by Jurigag** [comment]
Also i would really recommend to change your code bro. In most of database systems you have built-in query result cache. So if you select it once then other results will be fetched from cache. If you are using database without such a thing then i would recommend to use redis or memcache cache, and use objects. Static calls shouldn't be used for things like this.

**Comment by arthurgermano** [comment]
Yes.. it's true.. and UPPERCASE was not my first choice.. =( but we have to work with what is given to us.
and yes it is a bug..  I will correct the script and post it here with initialize function. And then describe whats is going on..

but thanks men.. you were very helpful! Good work =)

**Comment by arthurgermano** [comment]
@andresgutierrez we find out what is happening.. and it's small bug. I will post the script below but just to summarize what is happening.

1) I am setting and using columnMap function
2) I am also using dynamicUpdate and setting skipAttributesOnUpdate
like this -> $this->skipAttributesOnUpdate(array('qtdRegistros', 'dtCarga'));

So since the database is UPPERCASE and because I am using columnMap function it does not translate for me to skip my attributes this way;

To work I have to do this
$this->skipAttributesOnUpdate(array('QTDREGISTROS', 'DTCARGA'));

If I do that. Phalcon recognize it and then ignore the array list field.

If you have any doubts or questions I am here =) thanks men..

`
<?php

use Phalcon\DI;
use Phalcon\Events\Manager as EventsManager;
use Phalcon\Db\Adapter\Pdo\Mysql as Connection;
use Phalcon\Mvc\Model\Manager as ModelsManager;
use Phalcon\Mvc\Model\Metadata\Memory as ModelsMetaData;

$eventsManager = new EventsManager();

$di = new DI();

$connection = new Connection(array(
    "host" => "localhost",
    "username" => "root",
    "password" => "",
    "dbname" => "test"
));

$connection->setEventsManager($eventsManager);

$eventsManager->attach('db',
    function ($event, $connection) {
        switch ($event->getType()) {
            case 'beforeQuery':
                echo $connection->getSqlStatement(), "<br>\n";
                break;
        }
    }
);

$di['db'] = $connection;
$di['modelsManager'] = new ModelsManager();
$di['modelsMetadata'] = new ModelsMetadata();

if (!$connection->tableExists('user')) {
    $connection->execute('CREATE TABLE user
  (
    "IDUSER"         NUMBER(6,0) NOT NULL ENABLE,
    "DTCARGA" DATE,
    "QTDREGISTROS" NUMBER(6,0),
    "VLRTOTAL"     NUMBER(13,2),
  
    CONSTRAINT "TB_USER_PK" PRIMARY KEY ("IDUSER")
  )');
}

class User extends \Phalcon\Mvc\Model
{
    protected $idUser;
    protected $dtCarga;
    protected $qtdRegistros;
    protected $vlrTotal;

    public function initialize() {
        $this->useDynamicUpdate(true);
        $this->skipAttributesOnUpdate(array('qtdRegistros', 'dtCarga'));
    }
    
    public static function myCustomUserCreator()
    {
        $newUser = new User();
        $newUser->setIdUser(1);
        $newUser->setDtCarga('2016-May-05');
        $newUser->setQtdRegistros(300);
        $newUser->setVlrTotal(50000);
        if ($newUser->save() == false) {
            return false;
        }
        
        return $newUser->id;        
    }
    
    //THIS IS WHERE THE PROBLEM HAPPENS!!!
    public static function myCustomUserUpdator($post)
    {
        $update = new User($post);
        if ($update->update() == false) {
            return false;
        }
        
        //NOW I DIDN'T SET NEITHER DATE OR VLRTOTAL, BUT IT WILL UPDATE ANYWAY TO NULL OR 0 =(
        return $update->id;        
    }
    
    public function columnMap() {
        //mapping var name correponding to table field name
        //Case sensitive!
        //The fields in the database are UPPER_CASE
        return array(
            'IDUSER' => 'idUser',
            'DTCARGA' => 'dtCarga',
            'QTDREGISTROS' => 'qtdRegistros',
            'VLRTOTAL' => 'vlrTotal',
            'PHALCON_RN' => 'phalcon_rn'
        );
    }
    
    function getIdUser() {
        return $this->idUser;
    }

    function getDtCarga() {
        return $this->dtCarga;
    }

    function getQtdRegistros() {
        return $this->qtdRegistros;
    }

    function getVlrTotal() {
        return $this->vlrTotal;
    }

    function setIdUser($idUser) {
        $this->idUser = $idUser;
    }

    function setDtCarga($dtCarga) {
        $this->dtCarga = $dtCarga;
    }

    function setQtdRegistros($qtdRegistros) {
        $this->qtdRegistros = $qtdRegistros;
    }

    function setVlrTotal($vlrTotal) {
        $this->vlrTotal = $vlrTotal;
    }

    public function beforeSave(){
        $this->setDtCarga('2016-May-05');
        //this is just a sample I'll do loads of things here, but I will 
        //go throught each field setting into a specific format unless the field is null
        //then I will not touch it
    }
}

echo User::myCustomUserCreator();

$post['idUser'] = 1;
$post['qtdRegistros'] = 10;
echo User::myCustomUserUpdator($post);
`

**Comment by kideny** [comment]
php7.1 + phalcon3.2.2 + phalconbox2.0.3
it's not working too...

**Comment by arthurgermano** [comment]
Did you check the letter case ? It has worked for me.

Like this example..

```
class GuiaGRPR extends Model {    
    
   //declaring attributes
    protected $idGuiaGRPR;
    protected $....

//this one goes into initialize method
//this line must respect columnMap Declaration
$this->skipAttributesOnCreate(array('IDGUIAGRPR'));

public function columnMap() {
        //mapping var name correponding to table field name
        //Case sensitive!
        return array(
            'IDGUIAGRPR' => 'idGuiaGRPR'
            ....
            'PHALCON_RN' => 'phalcon_rn',
        );
    }

```

**Comment by kideny** [comment]
@arthurgermano you mean the issue come form the columnMap() function ?

**Comment by kideny** [comment]
but my columnMap() come from phalcon-devtools create.

**Comment by arthurgermano** [comment]
Hiii.. @kideny

No no.. I think that skipAttributesOnCreate or skipAttributesOnUpdate.. is case sensitive and must be equal column map declaration..

So when I mapped in column map for example $testVariable to TESTVARIABLE....  I must declare skipAttributesOnUpdate ("TESTVARIABLE");
