### ISSUE TITLE
Model default value incorrect behavior 

### ISSUE THREAD

**Issue by fantua** [phalcon/cphalcon#11744]
``` php
// Model:
public function validation() {
        if (!$this->search_tags) $this->search_tags = new RawValue('default');

        return true;
}

// Controller:
if ($model->save()) {
        var_dump($model->search_tags);
}
//output:
string 'default' (length=7) // must be null

// So after render I got:
<input type="text" value="default">
// I need 
<input type="text" value="">
```

Is that ok?

**Comment by sergeyklay** [comment]
You have to use `beforeValidationOnCreate`, `beforeValidationOnUpdate`, etc. For example: https://github.com/phalcon/forum/blob/master/app/models/Posts.php#L190

**Comment by Jurigag** [comment]
Yes, that it's okay. Checking for nulls happens before validation.

**Comment by fantua** [comment]
```php
public function beforeValidationOnUpdate () {
        if (!$this->search_tags) $this->search_tags = new RawValue('default');
    }

if ($model->save()) {
                var_dump($model->getSearchTags());
}

//output:
string 'default' (length=7)
```

I think that isn't ok

**Comment by Jurigag** [comment]
What database you are using ? you sure you have setted it okay ?

**Comment by fantua** [comment]
Mysql. Yes. [http://prntscr.com/b0hrjg](url)

After page refresh $model->getSearchTags() return null.

**Comment by Jurigag** [comment]
Well actually it doesn't gonna work in the way you want. Phalcon is not getting value for `default`.

I think there should be some other way to do it. Perhaps using metadata ?

**Comment by fantua** [comment]
>Phalcon is not getting value for default value when saving it.

So, which sense to use RawValue? 

>Perhaps you could maybe use onConstruct method or beforeValidation, getting metadata from DI, and use getDefaultValues method.

You mean like this?
```php
if (!$this->search_tags) $this->search_tags = $this->getDI()->getModelsMetadata()->getDefaultValues($this)['search_tags'];
```
I don't like this solution.
>Also next time use forum first, not reason for creating issue if you not sure it's an issue.

I think it's an issue, because [you recommend](http://stackoverflow.com/a/15952952/1542870) to use RawValue, but it's can't be usable after save.

**Comment by sergeyklay** [comment]
Could you please provide table schema and model?

**Comment by fantua** [comment]
```sql
`id` int(11) NOT NULL,
`name` varchar(255) DEFAULT NULL
```

```php
class Test extends \Phalcon\Mvc\Model {

    public $id;
    public $name;
    
    public function beforeValidationOnUpdate () {
        if (!$this->name) $this->name = new \Phalcon\Db\RawValue('default');
    }
    
    public function getSource()
    {
        return 'test';
    }

    public function columnMap()
    {
        return array(
            'id' => 'id',
            'name' => 'name'
        );
    }

}
```

When I try to create new record it's works fine:

```php
$test = new Test();
if ($test->save()) {
    var_dump($test->toArray());
}

//output:
array (size=2)
  'id' => string '2' (length=1)
  'name' => null
```

When I try to update:

```php
$test = Test::findFirst(1);
if ($test->save()) {
    var_dump($test->toArray());
}

//output:
array (size=2)
  'id' => string '1' (length=1)
  'name' => 
    object(Phalcon\Db\RawValue)[124]
      protected '_value' => string 'default' (length=7)
```

**Comment by makerlabs** [comment]
OK the problem is in the model itself not in your example because u are using it totally wrong. First the phalcon-devtools should generate a model with default values because they don't do it which is wrong in my opinion, second if you want default values you must define them in your model because the tools don't do it. U don't need to use the RawValue to do it unless u want to pass some SQL function like now() etc.
