### ISSUE TITLE
FileCache not expiring

### ISSUE THREAD

**Issue by stratoss** [phalcon/cphalcon#11759]
Here is the sample code:

``` php
$di->setShared('cache', function() {
    //Cache data for one hour by default
    $frontCache = new \Phalcon\Cache\Frontend\Data(array(
        'lifetime' => 3600
    ));

    //File cache settings
    $cache = new \Phalcon\Cache\Backend\File($frontCache, array(
        'cacheDir' => __DIR__ . '/cache/'
    ));

    return $cache;
});
```

then 

``` php
$resetAfter = $rate['saved'] + $seconds - time();
$cache->save($cacheName, $rate, (float)$resetAfter);
```

After a while `$resetAfter` becomes negative, and `$cache->exists($cacheName)` still returns the value...

edit: not touched the file for > 3600 seconds, and the file is still there. Looks like a bug for me.

**Comment by stratoss** [comment]
Hmm I've checked out the `cache/backend/file.zep` and realized that `filemtime()` returns the modified time on unix platforms, also I believed that passing `lifetime` while setting the cache is working as it does using memcached or redis for example, but the `File` implementation is totally different.

Do you think that instead of saving the raw content passed to `save()` saving an array like `['created' => time(), 'lifetime' => $lifetime, 'content' => $content]` is a good idea? It will solve the problem described above and the `File` cache will start behaving just like it does using memcached or redis? I could do a PR with the changes if you agree.

**Comment by sergeyklay** [comment]
@stratoss Could you please create PR for 2.0.x branch? Note, test coverage of this changes is mandatory.
