### ISSUE TITLE
how to change lifetime when i use redis session adapter

### ISSUE THREAD

**Issue by xkos** [phalcon/cphalcon#11757]
when i use redis as session i found  the lifetime i modify with `setOptions()` method in use did not enter into force. 
after modify lifetime , i set session , but it isn't clear overrun the new lifetime

is this a bug? or i used a wrong method to modify lifetime?
does phalcon have a method to set lifetime when assign a session var

**Comment by sergeyklay** [comment]
Close in favor of #11551
