### ISSUE TITLE
[NFR] Phalcon\Paginator Array Output

### ISSUE THREAD

**Issue by ghost** [phalcon/cphalcon#11751]
Can we have default array output instead of object when using  `Phalcon\Paginator\Adapter\NativeArray` or at least an option. It can be some thing like; 

``` php
$paginator = new NativeArray([
  'data' => $array, // data array
  'page' => $cpage, // current page
  'limit' => $limit // pages limit
],true); // Note: "true" for array output instead of object.
```

Thank you.

**Comment by duythien** [comment]
I think it is bad idea because we have some method get and set at https://docs.phalconphp.com/en/latest/api/Phalcon_Paginator_Adapter_NativeArray.html

**Comment by Jurigag** [comment]
You mean when doing getPaginate return array? Cuz im not sure what you mean. Can constructor even return array?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
