### ISSUE TITLE
IniConfig path must be a string

### ISSUE THREAD

**Issue by stratoss** [phalcon/cphalcon#11758]
I've got this error, trying to parse this sample ini file:
```
[access_token_limits]
5 = 600
```

The funny thing is, the problem turns out to be that the key is numeric, so the error message is completely misleading. Setting it as `s5 = 600` works good.

**Comment by sergeyklay** [comment]
> Variable names follow the same rules as other labels in PHP. A valid variable name **starts with a letter or underscore**, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: '[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*' |

So you suggest to allow to create Config object (from INI file) like this:

```php
class Phalcon\Config\Adapter\Ini {
    public $access_token_limits = class Phalcon\Config {
        public $0 = "600";
    }
}
```
