### ISSUE TITLE
Don't work in Ubunt 16.04

### ISSUE THREAD

**Issue by stingr31** [phalcon/cphalcon#11768]
W: The repository 'http://ppa.launchpad.net/phalcon/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/phalcon/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/phalcon/stable/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by sergeyklay** [comment]
1. This is [phalcon/ppa](https://github.com/phalcon/phalcon-ppa)'s repo issue and it is not related to this repo
2. The Ubuntu 16.04 [uses PHP 7](http://packages.ubuntu.com/xenial/php7.0) by default, but we haven't released Phalcon with full support of PHP 7 so far
3. As you can see https://github.com/phalcon/phalcon-ppa:
    ```
   The repository contains several branches:
    
   * precise: Ubuntu 12.04 LTS
   * trusty: Ubuntu 14.04 LTS
   * vivid: Ubuntu 15.04
   * wily: Ubuntu 15.10
    ```
