### ISSUE TITLE
incomplete Phalcon\Session\AdapterInterface

### ISSUE THREAD

**Issue by djfd** [phalcon/cphalcon#11762]
Hi,

as I can see https://github.com/phalcon/cphalcon/blob/master/phalcon/session/adapterinterface.zep#L27
there is not a method called `setId()` i.e. session user will be tied to `PHPSESSID` (in case of using cookies) or need to call native php function to set new ID.

Or is it intentionally? if so why?

Thanks

UPD. yet another possible improvement can include a few extra methods:

``` php
public function bind($key, &$value);
```

and

``` php
// removes session variable right after retrieval
public function getOnce($key, $default = NULL);
```

**Comment by Studentsov** [comment]
The interface describes public methods. You are sure that there is a situation when you need to set an id outside?

**Comment by djfd** [comment]
@Studentsov

well, what is wrong if I want to use cookie name `iam` instead of PHPSESSID? (for now I am considering only cookie based sessions bootstraps).

How do I achieve that if I did receive an instance of Phalcon\Session\AdapterInterface from DI container, like this
```
$di->setShared('session', function() {
    return new \Phalcon\Session\AdapterInterface {
    // ...
    };
});
```
There is not such method as setID, thus I need to use some other means. Is it safely to rely that we use standard sessions of PHP and use ```session_id('iam')```? Of course nope, eg. see an example of PHP independent session here https://github.com/kohana/core/blob/3.3/master/classes/Kohana/Session.php

so what I expected to do then?

**Comment by Studentsov** [comment]
I at first misunderstood your question.
However, the method is defined in an abstract class: https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/session/adapter.zep#L225

**Comment by djfd** [comment]
@Studentsov
You got a point. It is exactly what I do mean. 
```
abstract class Adapter implements AdapterInterface {
    // ...
    public function setId(...)
    {
        // ...
    }
}
```

We need to make software in terms of interfaces, to decouple as much as possible from an implementations

IMHO. abstract class need not to use $_SESSION at all. Look at Views rendering engines approach... There is PHP engine which simply uses standard PHP, and there is Volt. We can use that we want... The same approach is well suited to abstract session adapter, just use some internal container for data, then concrete PHP session adapter can just bind $_SESSION to that container and voila! 

And we still can have non PHP based concrete session adapters by going this way
