### ISSUE TITLE
Phalcon\Image\Adapter\GD resize (imagescale) color loss

### ISSUE THREAD

**Issue by acmenna** [phalcon/cphalcon#11773]
After using the gd adapter's resize method, the result image loses color.

PHP version: PHP 5.5.9-1ubuntu4.16 (cli)
Phalcon version: 2.0.11

Please Find below a possible fix, regarless the php version. I can create a pull request with this fix if needed.

```
public function resize($width = null, $height = null, $master = Image::AUTO)
{
    $new = imagecreatetruecolor($width, $height);
    imagecopyresampled($new, $this->getImage(), 0, 0, 0, 0, $width, $height,
        $this->getWidth(),$this->getHeight()
    );

    $this->_image = $new;
    $this->_width = $width;
    $this->_height = $height;
}
```

**Comment by Jurigag** [comment]
I think it's due to GD, beacause gd default compression level of jpeg files is 75.
