### ISSUE TITLE
Cookie is coupled with the Session

### ISSUE THREAD

**Issue by djfd** [phalcon/cphalcon#11770]
Hi,

synopsis: Cookie class is coupled with session class, it is wrong approach

in full:
let consider next micro-app

``` php
<?php

use Phalcon\Mvc\Router;
use Phalcon\Mvc\Micro;
use Phalcon\DiInterface;
use Phalcon\Di\FactoryDefault;
use Phalcon\Session\Adapter\Files;

class MyApp extends Micro
{
    public function __construct(DiInterface $di = null)
    {
        $di = $di ?: new FactoryDefault();

        // bot detector service mockup
        $di->setShared('iambot', function() {
            return null;
        });

        // only need session if not a bot
        $di->setShared('session', function() {
            $bot = $this->getShared('iambot');
            return $bot ? null : new Files();
        });

        parent::__construct($di);

        $this->router->setUriSource(Router::URI_SOURCE_SERVER_REQUEST_URI);

        $this->get('/{anything}', function($uri) use ($di) {
            $c = $di->getShared('cookies')->get('test');
            echo "got cookie<br>";

            $v = $c->getValue();
            echo "got cookie value `$v`<br>";
            echo "URI is `$uri`";
        });
    }
}

(new MyApp())->handle();
```

The idea is to do not create session for a bots, actually, why to do it.

This app wont work producing error:

```
Uncaught exception 'RuntimeException' with message
'Trying to call method isstarted on a non-object'
Stack trace:
  #0 [internal function]: Phalcon\\Http\\Cookie->restore()
```

see
https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L139
https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L300

Also we get infinite loop of session service creation if we have something like this:

``` php
$di->setShared('session', function() {
    // we do use custom cookie for a session bootstrap
    $bootstrap_cookie = $this->getShared('cookies')->get('session-bootstrap-cookie'); // this works
    $session_id = $bootstrap_cookie->getValue(); // this wont work, it is calling Cookie::restore() which tries to take session, and so on
    return new CustomSession($session_id);
});
```

thanks

**Comment by djfd** [comment]
it looks that storing cookie copy in session makes no sense at all. Could you please explain what is rationale behind of doing that?

**Comment by niden** [comment]
@djfd Thank you for reporting this. With @ekmst 's PR the session is no longer bound if the service is not set in the DI container. Although this is not the perfect solution, it will help until we redesign the HTTP layer to work with middleware

Resolved in https://github.com/phalcon/cphalcon/pull/14649

**Comment by ruudboon** [comment]
@niden let’s add a reminder for ourselves to update the docs upon release.
