### ISSUE TITLE
signal Segmentation fault  with php5.6.21 and zend guard loader extension

### ISSUE THREAD

**Issue by w3yyb** [phalcon/cphalcon#11772]
signal Segmentation fault  with php5.6.21 and "zend guard loader" extension

if remove the " zend guard loader "extension ,then work well.

**Comment by Jurigag** [comment]
Try maybe to load before phalcon or after phalcon, depends on which order load you have now ?

**Comment by w3yyb** [comment]
this is the problem code
 
$loader->registerDirs(array(
  __DIR__.'/models/'
))->register();

**Comment by w3yyb** [comment]
before phalcon

**Comment by Jurigag** [comment]
I mean about extension. Then try to load it after. Why you even this extension ?

**Comment by w3yyb** [comment]
Whether after or  before, both make signal Segmentation fault

**Comment by Jurigag** [comment]
Paste dump from gdb here.

**Comment by stamster** [comment]
Both Zend Guard and ionCube loaders interfere with a code at low level, so I guess there's some sort of incompatibility between Phalcon (Zephyr - C code) and those loaders.
Just for practise, try with ionCube loader.
