### ISSUE TITLE
Phalcon 2.0.11: extends Phalcon\Http\Response problem with method redirect

### ISSUE THREAD

**Issue by r0123456789** [phalcon/cphalcon#11784]
Hello,

When extends Phalcon\Http\Response and call the method redirect:

```
class Sample extends \Phalcon\Http\Response
{
    public function callMethodRedirect($uri)
    {
        $this->redirect($uri);
    }
}
```

occurs RuntimeException

`Trying to call method toarray on a non-object`

Only in version 2.0.11.

Please help!

Ty.

**Comment by sergeyklay** [comment]
Provide please full stack trace

**Comment by stamster** [comment]
Simple thing, instead of:
`        $this->redirect($uri); `
have you tried with:
`       return parent::redirect($uri); `

**Comment by stamster** [comment]
I hit this issue on one instance too.
My full stack trace tells only about runtime PHP exception, and it is regarding Phalcon Response object.
MVC application, so the issue is triggered on handle() method.

**Comment by stamster** [comment]
`RuntimeException Object
(
    [message:protected] => Trying to call method send on a non-object
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /fullpath/site/public/index.php
    [line:protected] => 59
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [function] => sendHeaders
                    [class] => Phalcon\Http\Response
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [file] => /fullpath/site/public/index.php
                    [line] => 59
                    [function] => handle
                    [class] => Phalcon\Mvc\Application
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

        )

    [previous:Exception:private] => 
)
`

**Comment by stamster** [comment]
I found the root cause of this issue.
Prior to 2.0.11 (i.e. 2.0.10) extending Phalcon\Http\Response worked without instantiating parent constructor. 
I just compiled Phalcon v 2.0.13 and this issue is still present. Thus, I had to call ``` parent::__construct();``` in order to instantiate Phalcon\Http\Response object. 

So, it worked on v 2.0.10 w/o calling parent constructor.
