### ISSUE TITLE
Does Phalcon extension support  PHP7.0  or not？

### ISSUE THREAD

**Issue by maxadjsky** [phalcon/cphalcon#11787]
My PHP version is 7.0.6，and I want to  kwon where can I find the phalcon extension supports php7.0.

**Comment by Green-Cat** [comment]
PHP 7.0 support is currently in development in the 2.1.x branch. You can compile the extension from that branch if you want to try it on 7.0. There are some known issues though.

**Comment by Jurigag** [comment]
In 2.1.x we cant tell there is something like beta support. I will soon update the rest of tests with what there is problem.

Next time check other issues.

**Comment by maxadjsky** [comment]
OK,thanks very much .I'll try the beta one for develop
