### ISSUE TITLE
PSR-7 support request & discussion

### ISSUE THREAD

**Issue by rahuldroy** [phalcon/cphalcon#11789]
PSR-7 has been an official standard for a while now. It would be awesome to support it!

I raised this very briefly in Slack. One of the ideas I raised was having a having a complete separate namespace just for this (similar to how Guzzle implemented it). Would like to hear your thoughts about this!

---

Refs:
- https://github.com/phalcon/cphalcon/pull/13437

**Comment by Jurigag** [comment]
If you have any idea you can create PR.

**Comment by sergeyklay** [comment]
First of all we have to refactor HTTP stack. For example HTTP Middlewares - at the moment it easy to use only for Micro application but they however, they do not implement PSR-7 stuff

**Comment by rahuldroy** [comment]
@sergeyklay Can you please elaborate on that

**Comment by Jurigag** [comment]
How about 4.0.0 this ?

**Comment by xerron** [comment]
+1

**Comment by stoiev** [comment]
+1

**Comment by grigoriygithub** [comment]
+1

**Comment by xueron** [comment]
+1

**Comment by MoneyCoder** [comment]
+1

**Comment by hoyo** [comment]
+1

**Comment by dibmartins** [comment]
+1

**Comment by C0DE8** [comment]
+1

**Comment by jasonraimondi** [comment]
+1

**Comment by lucasantarella** [comment]
+1

**Comment by CheckMater** [comment]
+1 we definitely need this, I'm bored to use the Wandu library

**Comment by olegatro** [comment]
+1

**Comment by Ark4ne** [comment]
+1

**Comment by niden** [comment]
This has been implemented
