### ISSUE TITLE
Csrf bind form

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11793]
When I use this, csrf works fine when I double submit form by click

``` php
$form = new PersonalForm();
```

When I use bind form, csrf is not valid when resending form

``` php
$form = new PersonalForm($account, array(
    'edit' => true
));
```

I guess it's bug?!

**Comment by googlle** [comment]
Now I use this and it works
```php
$form->bind([
    'firstname' => $account->getFirstname(),
    'lastname' => $account->getLastname(),
    'gender' => $account->getGender(),
    'birthday' => $account->getBirthday(),
], $account);
```

**Comment by makerlabs** [comment]
You are using it wrong. If you pass the entity when creating the form you don't need to use bind just use isValid and pass the request to it.
