### ISSUE TITLE
Acl inheritance issue

### ISSUE THREAD

**Issue by tempcke** [phalcon/cphalcon#11794]
## PHP to reproduce issue:
```php
    $reverseInherit = false; // set to true and we get expected results

    $acl = new Phalcon\Acl\Adapter\Memory();
    $acl->setDefaultAction(Acl::DENY);
    $acl->addResource('R',['Y','Z']);
    
    $acl->addRole('A');
    $acl->addRole('B');
    $acl->addRole('C');
    
    if ($reverseInherit) { // get expected results
      $acl->addInherit('A','C');
      $acl->addInherit('A','B');
    } else { // expose bug
      $acl->addInherit('A','B');
      $acl->addInherit('A','C');
    }
    
    $acl->allow('B','R','Y');
    $acl->allow('C','R','*');
    
    $li = "<li>isAllowed(%s, R, %s) = %d, expected %d</li>";
    echo sprintf($li,'A', 'Y', (int) $acl->isAllowed('A','R','Y'), 1); // 1 1
    echo sprintf($li,'A', 'Z', (int) $acl->isAllowed('A','R','Z'), 1); // 0 1
    
    echo sprintf($li,'B', 'Y', (int) $acl->isAllowed('B','R','Y'), 1); // 1 1
    echo sprintf($li,'B', 'Z', (int) $acl->isAllowed('B','R','Z'), 0); // 0 0
    
    echo sprintf($li,'C', 'Y', (int) $acl->isAllowed('C','R','Y'), 1); // 1 1
    echo sprintf($li,'C', 'Z', (int) $acl->isAllowed('C','R','Z'), 1); // 1 1
```

To help track it down I extended Phalcon\Acl\Adapter\Memory to intercept isAllowed()
The reason it fails is because of [this break:](https://github.com/phalcon/cphalcon/blob/master/phalcon/acl/adapter/memory.zep#L606)

I did a var_dump of `$this->access` and `$this->_roleInherits`:
```
$this->_access = array (size=6)
  'A!*!*' => int 0
  'B!*!*' => int 0
  'C!*!*' => int 0
  'B!R!Y' => int 1
  'B!R!*' => int 0
  'C!R!*' => int 1

$this->_roleInherits = array (size=1)
  'A' => array (size=2)
      0 => string 'B' (length=1)
      1 => string 'C' (length=1)
```
The reason the break causes the issue (though removing it is not the solution) is because it sees B!R!* and sets `haveAccess = 0; break;` and it never even looks at C!R!*

## Possible Solution
remove `break;` and use bitwise OR on haveAccess, in PHP this would look like this:
```php
    $haveAccess = (int) $haveAccess | $accessList[$accessKey];
//    break;
```
(int) cast is because the value of haveAccess is NULL before it is set.

More testing is required to know if other scenarios are also broken.  such as if B!R!Z => 0 I suspect it will also fail as it will never even check for x!x!* .. in which case the if null check around that loop would have to go also...

**Comment by tempcke** [comment]
on a side note the current unit tests (perhaps out of date) do not even pass for the Memory adapter..
There were 2 errors:
```
1) Phalcon\Test\Acl\Adapter\Memory\UnitTest::testAddResourceExists
BadMethodCallException: Wrong number of parameters

cphalcon/php-tests/tests/Phalcon/Acl/Adapter/Memory/UnitTest.php:154

2) Phalcon\Test\Acl\Adapter\Memory\UnitTest::testResourceName
BadMethodCallException: Wrong number of parameters

cphalcon/php-tests/tests/Phalcon/Acl/Adapter/Memory/UnitTest.php:170

FAILURES!
Tests: 12, Assertions: 16, Errors: 2.
```

**Comment by Jurigag** [comment]
@tempcke can you check 3.0.x ?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by tempcke** [comment]
Sorry, by the time @Jurigag asked me to check 3.x I had already made a work around and was still on v2.x .. Then I had forgot about this ticket.

I am running 3.x now though and re ran the simplified test above and it seems to have fixed the issue.

Thanks
