### ISSUE TITLE
PhalconPHP.com Website Not Loading

### ISSUE THREAD

**Issue by tuxy** [phalcon/cphalcon#11790]
I think do to ``https://static.phalconphp.com/`` whole site is not loading.

**Comment by niden** [comment]
Can you try loading this resource?

https://static.phalconphp.com/www/css/phalcon.min.css

It seems to be working fine for my location.

**Comment by tuxy** [comment]
@niden Okay, it works now. Not sure what that was =((

**Comment by niden** [comment]
It might have been that the DNS has not propagated yet for your ISP.

Thanks for the heads up.
