### ISSUE TITLE
Adding "/" to base route causes Phalcon to ignore the specified namespace

### ISSUE THREAD

**Issue by SparoHawk** [phalcon/cphalcon#11797]
I have this code:

``` php
$admin = new RouterGroup([
    'namespace' => 'Manager\Controllers\Admin'
]);

$admin->setPrefix('/admin');

$admin->add('', 'Index::index');
$admin->add('/users', 'Users::index');

$router->mount($admin);
```

If I switch the line `$admin->add('', 'Index::index');` for `$admin->add('/', 'Index::index');` I get an error and it shows that Phalcon is trying to get an AdminController with the namespace `Manager\Controllers` instead of looking in `Manager\Controllers\Admin`.

Any ideas?

**Comment by stamster** [comment]
Namespace delimiter is different, i.e. it should not interfere with URI like that (escaping).
Try to put leading backslash in your namespace definition.

**Comment by SparoHawk** [comment]
Nope. Still blows up:
```php
$admin = new RouterGroup([
    'namespace' => '\Manager\Controllers\Admin'
]);

$admin->setPrefix('/admin');

$admin->add('/', 'Index::index');
```

**Comment by stamster** [comment]
Which Phalcon version do you use to run your app?
