### ISSUE TITLE
Ubuntu package for 2.0.12 version

### ISSUE THREAD

**Issue by rmrbest** [phalcon/cphalcon#11803]
Hi,

When will be available new package for ubuntu?

Reminder for Sergey ;)

Thanks!

Regards,
Raul.

**Comment by sergeyklay** [comment]
@rmrbest The 2.0.12 is availavle for Ubuntu https://launchpad.net/~phalcon/+archive/ubuntu/stable

Going to release 2.0.13 with camelize/uncamelize fix
