### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11814]
There were lately discussion here: https://forum.phalconphp.com/discussion/11571/whats-going-on-with-phalcon

I think after realasing version 2.1.0(which supposed to be LTS) we should really switch to Semantic Versioning. So:

2.1.1 and next 2.1.x versions should be only bug fixes or adding methods which returns something that's already done in exisiting code for example this commit - https://github.com/phalcon/cphalcon/commit/7716f3bc3de2974f338cbabf7b4aac0181208ab7.
2.2.0 and next 2.x.0 versions should be only new things(so no changes to api like validation change in 2.0.x and 2.1.x) **or** at least if we want to reimplement something, change api, core etc - then we need to keep old behaviour **as well** and tag them as **deprecated**(but they **should work and be available** without any changes)
3.0.0 - api changes, removing deprecated things etc

That will be at least one point to make phalcon more reliable and trustable.

**Comment by stamster** [comment]
@Jurigag , I think this should be posted on official forum as well.

LTS means stability and backward compatibility. That is mandatory for enterprise acceptance, even though enterprises are not that agile to keep up to date their stacks once they got into production.

**Comment by mbadal** [comment]
Is this issue still live? I have searched the forum, but was not able to find any threads with this topic. 

IMHO semantic versioning could be really helpful for phalcon.

**Comment by sergeyklay** [comment]
https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e

**Comment by Jurigag** [comment]
Well yea, but changes for example to old model validation wasn't a "small change". It can possibly break a LOT of applications. That's why we should remain old behaviour as well.

**Comment by dschissler** [comment]
So you got your semver.  Issue closed.
