### ISSUE TITLE
ActiveController feature

### ISSUE THREAD

**Issue by progsmile** [phalcon/cphalcon#11817]
Hi there
Wish Phalcon has ActiveController for faster REST Api implementation. You can find this feature example in [Yii2](http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html#creating-controller).

Main idea: providing default resource management only with inheritance of ActiveController and setting right model 

``` php
class UserController extends ActiveController
{
    public $modelClass = 'app\models\User';
}
```

**Comment by Jurigag** [comment]
Well you can create abstractclass with such a controller yourself, it's not very much coding.

**Comment by progsmile** [comment]
It would be great if such functionality come from the box)
I can try implement it on php and push to `incubator`

**Comment by Jurigag** [comment]
If you can then great. Then someone can port it to zephir.
