### ISSUE TITLE
CSRF validation issue when multiple browsing

### ISSUE THREAD

**Issue by Timberland-7** [phalcon/cphalcon#11829]
As the Phalcon' CSRF protection function ( $this->security->checkToken() ) uses PHP session id, if you add session adapter to your Dependency Injector which you should in order to get it work properly, the session renews itself with every request to the server, So when you have forms in multiple views: 

`public function searchAction()`
`{`
`           // There's a form with $this->security->getTokenKey() & $this->security->getToken() in hidden fileds  In the view `
`// Pointed to localhost/search`
`}`

AND

`public function contactAction()`
`{`
`           // There's a form with $this->security->getTokenKey() & $this->security->getToken() in hidden fileds  In the view `
`// Pointed to localhost/contact`
`}`

If you open these Urls in your browser: localhost/search in one tab and then localhost/contact in another, only the last which is contact page will pass the CSRF validation

My workaround to this would be to store the tokens in browser cookie with Javascript:

`<script>`
`document.cookie = 'tokenkey=<?=$this->security->getTokenKey()?>; path=/'`
`document.cookie = 'token=<?=$this->security->getToken()?>; path=/'`
`</script>`

And pass the cookie values to checkToken() function:

`$tokenKey = $this->cookies->get('tokenkey')->getValue()`
`$token = $this->cookies->get('token')->getValue()`
`$this->security->checkToken( $tokenKey , $token )`

You can also use Phalcon' $this->cookies->set() method but the best is to use Javascript to set the cookies which forces the client to have the page rendered in their browser (or at least the http header be sent) in order to get the tokens for validation, which will give you the exact same effect as putting tokens in hidden inputs on forms And if you're using a base view template and put it there once, then you are good to go for the rest of the application and don't need to add it in each views that contain forms

Be aware that the JS way needs the browser to have Javascript enabled, if your site or application explicitly needs JS to be enabled then there's no worries and you are good to go Else have a backup code for JS's disabled

**Comment by Jurigag** [comment]
Well example of this problem you can find on phalcon forum.
