### ISSUE TITLE
[2.1.x] Phalcon Config parsing problem

### ISSUE THREAD

**Issue by betspin** [phalcon/cphalcon#11820]
config:
```php
return new \Phalcon\Config([
    'security' => [
        'jwt_key' => 'LwT>NbE9HL<kfJehXg9H)up9&t2uejMN',
        'jwt_algorithm' => 'HS256'
    ],
]);
```

output: 
```
Phalcon\Config Object
(
    [jwt_key] => LwT>NbE9HL HS256
)
```

after removing '<' from jwt_key the output looks ok:
```
Phalcon\Config Object
(
    [jwt_key] => LwT>NbE9HLkfJehXg9H)up9&t2uejMN
    [jwt_algorithm] => HS256
)
```

**Comment by chrizzz0101** [comment]
If i Try on 2.0.9 in a *.ini i get also an error. We have to check for previous Versions too.

`Warning: syntax error, unexpected ')' in /var/www/invo/app/config/development/chris.ini on line 26 in /var/www/invo/app/config/configloader.php on line 20
Configuration file chris.ini can't be loaded
`

`[test]
jwt_key = LwT>NbE9HL<kfJehXg9H)up9&t2uejMN`

**Comment by sergeyklay** [comment]
@chrizzz0101 try 
```ini
[test]
jwt_key = "LwT>NbE9HL<kfJehXg9H)up9&t2uejMN"
```

**Comment by sergeyklay** [comment]
Or do not use secret credentials like thi in config. For example you can try something like: http://phalcontip.com/discussion/54/using-true-secure-token

**Comment by chrizzz0101** [comment]
thanks @sergeyklay 
@betspin output config and check page source. at me its also:

`
[test] => Phalcon\Config Object
        (
            [jwt_key] => LwT>NbE9HL
`

but in page source its 

`
    [test] => Phalcon\Config Object
        (
            [jwt_key] => LwT>NbE9HL<kfJehXg9H)up9&t2uejMN
        )
`
