### ISSUE TITLE
getRender method does not seem to respect the render level set by setRenderLevel

### ISSUE THREAD

**Issue by jellisii** [phalcon/cphalcon#11848]
``` php
$this->view->setRenderLevel(\Phalcon\Mvc\View::LEVEL_BEFORE_TEMPLATE);
$html = $this->view->getRender('controller', 'action', array(
    'questions' => $assessment->getQuestion(),
    'size' => $this->request->getPost('size')
));
error_log($html);
```

Expected functionality would be for the string returned to match what would be on the output.  This does not appear to be true.  

--update: Formatting

**Comment by jellisii** [comment]
The current workaround that I've found is to disable all the unused renderLevels.

**Comment by Jurigag** [comment]
This is happening because getRender is using reset which resets renderLevel.
