### ISSUE TITLE
Issue with {some:array} in PHQL/Models

### ISSUE THREAD

**Issue by butamuh4o** [phalcon/cphalcon#11842]
Hi there,

It seems i use that type type of variables much more... so i found issue. Let give u example:

```
$s = [1 => 2, 2 => 12]; // Where 2 and 12 is some ids
$objs = \Models\ArticleAuthors::find([
 'conditions' => 'article_id={article:int} AND author_id IN ({authors:array})',
 'bind' => ['article' => (int)$id, 'authors' => $s]
]);
```
- so this will return error ***"PDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined"***. After some time of attempts i realize the problem is the keys of the array ```$s```- they did not start from 0! If you make ```$s = array_values($s);``` to reset keys all will works fine.

I think this is good to be fixed.

(i hope you did not forget that related issue too: https://github.com/phalcon/cphalcon/issues/11605)

My Phalcon version : 2.1.0r / Mar 23 2016 00:33:33 / on PHP 5.6.3 Windows

Thank You! 
May the force be with you. Always

**Comment by stamster** [comment]
This might be PDO issue more than Phalcon's, since you're getting plain PDOException. Bound parameters should be numerical array (starting at index 0 by default).

**Comment by butamuh4o** [comment]
Hmm, will accept that... but... is it possible PHQL prepare that or this is on purpose?

**Comment by Jurigag** [comment]
Im guessing this is on purpose. This could be fixed, but it would doing some stuff like array_values. And there is no really convenient way in php to check if assoc array is numerated from 1 or 0 etc.

**Comment by stamster** [comment]
Well, 
something like
```
if (isset($array[0])) //do something
else //don't do
```

But like I said PDO expects numerically indexed array here, which by default starts at index 0.

**Comment by Jurigag** [comment]
Well, but isn't this stuff only in phalcon ? As far as i know PDO don't allow binding array like we have.

**Comment by hisorange** [comment]
You can bind in PDO like
```sql
SELECT * FROM table WHERE id = :id
```

```php
$bind = ['id' => 1];
```

As far as I know phalcon doing the same just a bit smarter and required the param to be :id: instead of :id

**Comment by Jurigag** [comment]
I know you can bind in PDO like this. I mean we can't bind array in PDO..... read first, then answer.

**Comment by dschissler** [comment]
This might be a dupe of #11605

**Comment by butamuh4o** [comment]
Okay then, i will close it.
