### ISSUE TITLE
why "phalcon.zep.c:140681: error: ‘ZEND_FE_END’ undeclared" this error?

### ISSUE THREAD

**Issue by chenlongke** [phalcon/cphalcon#11843]
sudo ./install

Configuring for:
PHP Api Version:         20090626
Zend Module Api No:      20090626
Zend Extension Api No:   220090626
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for icc... no
checking for suncc... no
checking whether gcc and cc understand -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable phalcon... yes, shared
checking whether HAVE_BUNDLED_PCRE is declared... no
checking whether HAVE_JSON is declared... yes
checking for ext/json/php_json.h... yes
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
/bin/sh /data/cphalcon/build/64bits/libtool --mode=compile gcc  -I. -I/data/cphalcon/build/64bits -DPHP_ATOM_INC -I/data/cphalcon/build/64bits/include -I/data/cphalcon/build/64bits/main -I/data/cphalcon/build/64bits -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DPHALCON_RELEASE -DHAVE_CONFIG_H  -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden   -c /data/cphalcon/build/64bits/phalcon.zep.c -o phalcon.lo 
libtool: compile:  gcc -I. -I/data/cphalcon/build/64bits -DPHP_ATOM_INC -I/data/cphalcon/build/64bits/include -I/data/cphalcon/build/64bits/main -I/data/cphalcon/build/64bits -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden -c /data/cphalcon/build/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_cleanup_fcache’:
/data/cphalcon/build/64bits/phalcon.zep.c:4402: error: ‘zend_class_entry’ has no member named ‘info’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_class_exists’:
/data/cphalcon/build/64bits/phalcon.zep.c:5789: error: ‘ZEND_ACC_TRAIT’ undeclared (first use in this function)
/data/cphalcon/build/64bits/phalcon.zep.c:5789: error: (Each undeclared identifier is reported only once
/data/cphalcon/build/64bits/phalcon.zep.c:5789: error: for each function it appears in.)
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_read_property’:
/data/cphalcon/build/64bits/phalcon.zep.c:5932: warning: passing argument 2 of ‘zend_get_object_classname’ from incompatible pointer type
/usr/include/php/Zend/zend_API.h:324: note: expected ‘char **’ but argument is of type ‘const char **’
/data/cphalcon/build/64bits/phalcon.zep.c:5939: error: too many arguments to function ‘object->value.obj.handlers->read_property’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_fetch_property_this_quick’:
/data/cphalcon/build/64bits/phalcon.zep.c:5976: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c:5978: error: ‘zend_object’ has no member named ‘properties_table’
/data/cphalcon/build/64bits/phalcon.zep.c:5978: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c:5981: error: ‘zend_object’ has no member named ‘properties_table’
/data/cphalcon/build/64bits/phalcon.zep.c:5981: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_return_property_quick’:
/data/cphalcon/build/64bits/phalcon.zep.c:6039: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c:6041: error: ‘zend_object’ has no member named ‘properties_table’
/data/cphalcon/build/64bits/phalcon.zep.c:6041: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c:6044: error: ‘zend_object’ has no member named ‘properties_table’
/data/cphalcon/build/64bits/phalcon.zep.c:6044: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_update_property_zval’:
/data/cphalcon/build/64bits/phalcon.zep.c:6171: warning: passing argument 2 of ‘zend_get_object_classname’ from incompatible pointer type
/usr/include/php/Zend/zend_API.h:324: note: expected ‘char **’ but argument is of type ‘const char **’
/data/cphalcon/build/64bits/phalcon.zep.c:6178: error: too many arguments to function ‘object->value.obj.handlers->write_property’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_update_property_this_quick’:
/data/cphalcon/build/64bits/phalcon.zep.c:6220: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c:6220: error: ‘zend_object’ has no member named ‘properties_table’
/data/cphalcon/build/64bits/phalcon.zep.c:6220: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c:6220: error: ‘zend_object’ has no member named ‘properties_table’
/data/cphalcon/build/64bits/phalcon.zep.c:6220: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_unset_property’:
/data/cphalcon/build/64bits/phalcon.zep.c:6526: error: too many arguments to function ‘object->value.obj.handlers->unset_property’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_fetch_static_property_ce’:
/data/cphalcon/build/64bits/phalcon.zep.c:6609: warning: passing argument 2 of ‘zend_read_static_property’ discards qualifiers from pointer target type
/usr/include/php/Zend/zend_API.h:321: note: expected ‘char *’ but argument is of type ‘const char *’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_std_get_static_property’:
/data/cphalcon/build/64bits/phalcon.zep.c:6673: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c:6680: error: ‘zend_property_info’ has no member named ‘offset’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_create_closure_ex’:
/data/cphalcon/build/64bits/phalcon.zep.c:7059: error: too many arguments to function ‘zend_create_closure’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_http_build_query’:
/data/cphalcon/build/64bits/phalcon.zep.c:10789: error: ‘PHP_QUERY_RFC1738’ undeclared (first use in this function)
/data/cphalcon/build/64bits/phalcon.zep.c:10789: error: too many arguments to function ‘php_url_encode_hash_ex’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_htmlspecialchars’:
/data/cphalcon/build/64bits/phalcon.zep.c:10829: warning: passing argument 3 of ‘php_escape_html_entities_ex’ from incompatible pointer type
/usr/include/php/ext/standard/html.h:43: note: expected ‘int *’ but argument is of type ‘size_t *’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_htmlentities’:
/data/cphalcon/build/64bits/phalcon.zep.c:10854: warning: passing argument 3 of ‘php_escape_html_entities_ex’ from incompatible pointer type
/usr/include/php/ext/standard/html.h:43: note: expected ‘int *’ but argument is of type ‘size_t *’
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_require_ret’:
/data/cphalcon/build/64bits/phalcon.zep.c:11967: warning: assignment discards qualifiers from pointer target type
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_get_intval_ex’:
/data/cphalcon/build/64bits/phalcon.zep.c:12891: error: ‘IS_CALLABLE’ undeclared (first use in this function)
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_get_doubleval_ex’:
/data/cphalcon/build/64bits/phalcon.zep.c:12936: error: ‘IS_CALLABLE’ undeclared (first use in this function)
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_get_boolval_ex’:
/data/cphalcon/build/64bits/phalcon.zep.c:12974: error: ‘IS_CALLABLE’ undeclared (first use in this function)
/data/cphalcon/build/64bits/phalcon.zep.c: In function ‘zephir_escape_html’:
/data/cphalcon/build/64bits/phalcon.zep.c:16166: warning: passing argument 3 of ‘php_escape_html_entities’ from incompatible pointer type
/usr/include/php/ext/standard/html.h:42: note: expected ‘int *’ but argument is of type ‘size_t *’
/data/cphalcon/build/64bits/phalcon.zep.c: At top level:
/data/cphalcon/build/64bits/phalcon.zep.c:140681: error: ‘ZEND_FE_END’ undeclared here (not in a function)
make: *** [phalcon.lo] Error 1

**Comment by Jurigag** [comment]
You sure that your php version is 5.6.0 ? PHP Api Version: 20090626, 2009 year is like php 5.3.0 which is not more supported. What php -v return ?

**Comment by sergeyklay** [comment]
PHP 5.3.x is not supported anymore
