### ISSUE TITLE
[NFR] beforeEverything event on model save

### ISSUE THREAD

**Issue by charnad** [phalcon/cphalcon#1185]
The first event ever fired during save process is beforeValidation. At this point the query plan is already prepared, making impossible to update related values. At the same time, if one wants to create a complex behavior, that transparently updates related entities on save, one finds out that it is not possible.

My suggestion is: additional event, let's say "beforeEverything", that is fired before _preSaveRelatedRecords, but after values assignment, somewhere here:
https://github.com/phalcon/cphalcon/blob/master/ext/mvc/model.c#L4027 (right after getwriteconnection).

I think this is not hard, and I could do it myself, I only need your approval of the idea.

Another option might be - moving beforeValidation event to that place.

**Comment by Green-Cat** [comment]
@charnad Implemented in 2.0.x.
See #10414.
