### ISSUE TITLE
why build so large so file 243MB ? how to make it smaller ?

### ISSUE THREAD

**Issue by joostshao** [phalcon/cphalcon#11854]
243M -rwxr-xr-x 1 root root 243M  6月  5 07:42 phalcon.so*

**Comment by andresgutierrez** [comment]
How did you compile it?

**Comment by Jurigag** [comment]
You probably have php with debug. Just compile php without debug and it will be like 4.8-5 mb.

**Comment by joostshao** [comment]
yes, i compile with debug

**Comment by joostshao** [comment]
@Jurigag  why the debug version will add so much binary size ? any reference or docs ?

**Comment by Jurigag** [comment]
Beacause it's adding debugging symbols.

**Comment by joostshao** [comment]
at now:

142MB  23308 16316

it is normal now, thank you.

but , i am instereting in debug PHP using gdb, so in my own computer , i always build with debug.

**Comment by Jurigag** [comment]
Well then if you need debugging than just use it. In dev env there will be no problem. Just don't use it on production as debug.
