### ISSUE TITLE
Installing phalcon with mamp on osx mavericks   

### ISSUE THREAD

**Issue by AstmDesign** [phalcon/cphalcon#11850]
Guys, I'm trying to install phalcon on osx system with mamp  
First I runed the command 
**export PATH=/Applications/MAMP/bin/php/php5.6.7/bin:$PATH**
to load the version 5.6.7 after then 
runed the command 
**cd /Applications/MAMP/bin/php/php5.6.7/include/php**
then 
**brew install pcre**
then
**git clone --depth=1 git://github.com/phalcon/cphalcon.git** 
then
**cd cphalcon/build**
then
**sudo ./install**
then I got
Build complete.
Don't forget to run 'make test'.

**Installing shared extensions:     /Applications/MAMP/bin/php/php5.6.7/lib/php/extensions/no-debug-non-zts-20131226/
Installing header files:          /Applications/MAMP/bin/php/php5.6.7/include/php/

Thanks for compiling Phalcon!
Build succeed: Please restart your web server to complete the installation**

but I don't know how I can run the test and now if i typed 
**phalcon -v**
I got " -sh: phalcon: command not found "

How I can solve it? and what I miss?

**Comment by Jurigag** [comment]
```
phalcon -v
```

What is this ? Phalcon is php extension.

**Comment by ulfims** [comment]
Try: 
php -m

It whill show you : Phalcon on the list

**Comment by AstmDesign** [comment]
**phalcon -v**
-sh: phalcon: command not found

**Comment by AstmDesign** [comment]
**php -m**
phalcon not in the last

**Comment by ulfims** [comment]
> php -m
phalcon not in the last

@AstmDesign its ok. It means phalcon was installed

**Comment by AstmDesign** [comment]
not in the list 
this is my list now 
---------------------
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
mysql
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
yaz
zip
zlib

**Comment by Jurigag** [comment]
But did you added phalcon to php.ini cli ? By default it's not added to cli.

**Comment by AstmDesign** [comment]
no I didn't added phalcon to php.ini cli  and really I don't know how to add it , BTW i'm using mamp

**Comment by Jurigag** [comment]
So you need to add it to php.ini for cli if you need phalcon in cli.

**Comment by AstmDesign** [comment]
thank you, it's working now well after adding the extension=phalcon.so to my php.ini
