### ISSUE TITLE
[Bug] Macros strip & use only the first element of passed arrays

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#11868]
Hi,

With Phalcon 2.0.11, if an array (or an object that can be iterated) is passed as a parameter to a macro, then inside the macro, that parameter is no longer an array, but is the first element in the array.

Consider this action:
```php
public function testAction(){
    $this->view->testVar = [1,2,3];
}
```

And this view:
```
{%- macro arrayTest(param) %}
<?php print_r($param); ?>
{% endmacro %}

<?php print_r($testVar); ?>
{{ arrayTest(testVar) }}
```

The output will be:
```
Array ( [0] => 1 [1] => 2 [2] => 3 ) 1 
```

**Comment by Jurigag** [comment]
Check on phalcon 2.0.12 or later.

**Comment by quasipickle** [comment]
Ah, yep - 2.0.12 fixes it.
