### ISSUE TITLE
Problem with nested for loops

### ISSUE THREAD

**Issue by Hoet** [phalcon/cphalcon#11879]
'properties' is the result from a properties model like 'Properties::find([ "order" => "name" ])'. The result contains 12 results. When dumping the 'properties' I do see the 12 items as expected.

So far so good. Also looping through this while using the for loop as below without the nested loop produces 12 items as expected.

But when I use the 'properties' in a nested loop like below only one result is displayed instead all 12. The internal loop is the problem. if I remove it I get all 12 items displayed if added only the first items is displayed.

{% for item in properties %}

  {# Is the current option selected ? #}
  {% set selected = false %}
  {% for wish in properties %}
    {% if wish == item.getId() %}
      {% set selected = true %}
    {% endif %}
  {% endfor %}

  {{ dump( item.toArray() ) }}

{% endfor %}

The resulting php code looks ok. Removing the if within the nested for doesn't make a differance. I still get one result instead all 12.

`
    <?php foreach ($properties as $item) { ?>

```
    <?php $selected = false; ?>
    <?php foreach ($properties as $wish) { ?>
      <?php if ($wish == $item->getId()) { ?>
        <?php $selected = true; ?>
      <?php } ?>
    <?php } ?>

    <?php echo var_dump($item->toArray()); ?>

<?php } ?>
```

`

Anyone have an idea why this is the case ?
I do have a work around. I can supply the properties twice to the view like:

$viewVars['properties']  =Properties::find([ "order" => "name" ]);

$viewVars['properties2'] =Properties::find([ "order" => "name" ]);

But that should not be the solution.

using phalcin 2.0.9, debian 7.8,

**Comment by tembem** [comment]
Yes there's problem with nested loops https://github.com/phalcon/cphalcon/issues/10970

**Comment by Hoet** [comment]
But that is when you use an if statement. If I pull that from the code and just have a nested loop I experience the issue. Might be related of course,

adding '{{ loop.revindex }}' before and after the internal loop I get the same result of 12. So he knows that he still needs to iterate a number of records. and '{{ dump( loop.last ) }}' after the internal loop indicates a false.

**Comment by stamster** [comment]
Have you tried to upgrade to latest stable 2.0.13 version of Phalcon?

**Comment by Hoet** [comment]
Not yet, but I'll and post my comments here.

**Comment by sergeyklay** [comment]
@Hoet

**Comment by sverdier** [comment]
@sergeyklay I have this bug on Phalcon 3.4.4
