### ISSUE TITLE
[2.1.x] Phalcon/Mvc/Model/Validator namespace

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11887]
Why we keep this namespace ? Is there any way to use old validation in models ? I don't see it, `validate` method accepts only Phalcon\ValidationInterface.

At least we should trigger deprecated and inform that this is deprecated and Phalcon\Validation can be used only on creating of any validator.

**Comment by sergeyklay** [comment]
We just deprecated valdators from `Phalcon/Mvc/Model/Validator` namespace, but validators is there

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/validator.zep construct method looks the same. I know if we will try to use code from 2.0.x `validate` method will throw some exception or error but still if someone will create just some validator object then i think he should be informed about deprecation of it.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/12098

**Comment by SidRoberts** [comment]
By the way, [Phalcon\Mvc\Collection still uses the old model validators](https://github.com/phalcon/cphalcon/blob/v3.0.1/phalcon/mvc/collection.zep#L647).

**Comment by Jurigag** [comment]
Yea, we need to mark it as deprecated, possibly add option to use both validation ways and remove old validation in 4.0.0.

**Comment by niden** [comment]
This has already been addressed
