### ISSUE TITLE
 Call to undefined function Phanbook\Tools\mb_substr()

### ISSUE THREAD

**Issue by rmrio** [phalcon/cphalcon#11894]
Hi. Im trying to install phalcon to ubuntu 16.04 & php7, got the following error:    

    <p class="question-desc">
                            <br />
     <b>Fatal error</b>:  Uncaught Error: Call to undefined function Phanbook\Tools\mb_substr() in      /usr/share/nginx/html/phanbook/core/common/tools/ZFunction.php:98
    Stack trace:
     #0 /     usr/share/nginx/html/phanbook/content/cache/volt/_usr_share_nginx_html_phanbook_content_themes_default_partials_question.volt.php(20): Phanbook\Tools\ZFunction::truncate('Hey Community,\r...', 300, '...')
    #1 [internal function]: unknown()
    #2 [internal function]: Phalcon\Mvc\View\Engine\Volt-&gt;render('/usr/share/ngin...', Array, false)
    #3 [internal function]: Phalcon\Mvc\View-&gt;_engineRender(Array, 'partials/questi...', false, false)
    #4 [internal function]: Phalcon\Mvc\View-&gt;partial('partials/questi...', Array)
    #5  /usr/share/nginx/html/phanbook/content/cache/volt/_usr_share_nginx_html_phanbook_content_themes_def ault_partials_list-posts.volt.php(2): Phalcon\Mvc\View\Engine-&gt;partial('partials/questi...', Array)
    #6 [internal function]: unknown()
    #7 [internal function]: Phalcon\Mvc\View\Engine\Volt-&gt;render('/usr/share/ngin...', Array, false)
    #8 [internal function in <b>/usr/share/nginx/html/phanbook/core/common/tools/ZFunction.php</b> on line    <b>98</b><br />

**Comment by rmrio** [comment]
There is the fix:

     sudo apt-get install php7.0-mbstring

**Comment by duythien** [comment]
@rmrio Wrong page issue it should be at https://github.com/phanbook/phanbook/issues :)

**Comment by rmrio** [comment]
@duythien You are right ;)
