### ISSUE TITLE
[PHP7]Volt engine tries to access protected property in macros

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11902]
On php7 and phalcon 2.1.x and volt there is some problem that this view:

https://github.com/phalcon/cphalcon/blob/2.1.x/unit-tests/views/macro/hello.volt

which generated result is:

```php
<?php
$this->_macros['hello'] =
function ($__p = null)
{
	if (isset($__p[0])) {
		$name = $__p[0];
	}
	else {
		if (isset($__p["name"])) {
			$name = $__p["name"];
		}
		else {
			throw new \Phalcon\Mvc\View\Exception("Macro 'hello' was called without parameter: name");
		}
	} ?><?php
	return 'Hello ' . $name; ?><?php
};
$this->_macros['hello'] = \Closure::bind($this->_macros['hello'], $this); ?><?php echo $this->callMacro('hello', ['World']) ?>
```

tries to acces protected `_macros` property here https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/view/engine/volt.zep#L40 which results in triggering this error - https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/di/injectable.zep#L157

How to solve this:
- change protected to public or
- override `__get` method, so if we have `_macros` property accessed it just returns it first and then call parent override

**This might be as well some problem with volt parser, because there is no problem on php 5.x(at least not in tests). You can check it yourself this in tests by executing `ViewEnginesVoltTest::testVoltMacros()`.**

**Comment by xerron** [comment]
fix in branch 3.0.x
