### ISSUE TITLE
afterConnect event

### ISSUE THREAD

**Issue by dellert** [phalcon/cphalcon#11904]
Is there a way to set afterConnect event for database connection?

**Comment by Jurigag** [comment]
After this:

https://github.com/phalcon/cphalcon/blob/master/phalcon/db/adapter/pdo.zep#L155

add:

```
let eventsManager = <ManagerInterface> this->_eventsManager;

if typeof eventsManager == "object" {
    eventsManager->fire("db:afterConnect", this);
}
```

**Comment by Jurigag** [comment]
https://docs.phalconphp.com/pl/latest/reference/db.html#database-events

**Comment by dellert** [comment]
Thanks
