### ISSUE TITLE
Form validate modify object property

### ISSUE THREAD

**Issue by vantienvnn** [phalcon/cphalcon#11900]
Hello,

I have example for this error as bellow:
```php
$product = Product::findById(ID);
$form = new UpdateProductForm($product);
$product->parent_id = new MongoId($this->request->getPost('parent_id'));
if($form->isValid($this->request->isPost() == false){
     // exit if error
}
var_dump($product->parent_id);
```

The parent id after validate is string not Mongo Object Id
P/S: The UpdateProductForm code dont have change model property. This issues is same for Phalcon window and linux version 2.1.0

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/12128
