### ISSUE TITLE
cphalcon.zip corrupt on EasyApache/cpanel update/rebuild

### ISSUE THREAD

**Issue by zzplab** [phalcon/cphalcon#11903]
I've installed Phalcon through EasyApache on a cpanel server (CENTOS 6.8) for quite some time now. Worked fine till yesterday. Phalcon v2.0.13, PHP v5.6.22.
I get this error in the log when updating/rebuilding through EasyApache:
```
    -- Begin step 'Extract source' --
Archive:  cphalcon.zip
...
warning [cphalcon.zip]:  37 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [cphalcon.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
!! 'unzip cphalcon.zip' failed with exit code '768' !!
!! Restoring original working apache !!
```
Is that an error or bug in cphalcon.zip?

**Comment by sergeyklay** [comment]
I'm not sure https://github.com/phalcon/cphalcon/archive/phalcon-v2.0.13.zip

**Comment by zzplab** [comment]
EasyApache updated fine just now. What caused the error and solution is still a mystery to me.
Thanks for the response.
