### ISSUE TITLE
ignoreUnknownColumns=>true fails on Model::save()

### ISSUE THREAD

**Issue by igorsantos07** [phalcon/cphalcon#11907]
While enabling ignoreUnknownColumns do allow us to not specify repeated column names on columnMaps (as per a [comment in another issue](https://github.com/phalcon/cphalcon/issues/1780#issuecomment-115065496), as this is nowhere to be found in the docs), it still triggers `Column 'blah' isn't part of the column map`. In the stacktrace, it was triggered inside `Phalcon\Mvc\Model->_preSave()`.

This was found under 2.0.11 and then tested under 2.0.13 and 2.1.0 RC1 (7992678), both still displaying this issue.

Sample steps to reproduce:
1. have a table with a couple of fields, for instance `id, name, age`
2. set the model's columnMap to return `['name' => 'fullName']`
3. If you try to run a `find()` on it or something similar, it will trigger a columnMap error (as the `age` field is missing in the columnMap definition)
4. setting `\Phalcon\Mvc\Model::setup(['ignoreUnknownColumns' => true])` will clear up the `find()` error
5. however, that error will still appear if you try to run `save()` on the said model

**Comment by igorsantos07** [comment]
I was wondering if I could get someone's attention to this issue? There's 9 months it was opened, and got no reply :thinking: 

To help figure out what's going on, I tried to reproduce it in a simple project: I forked the sample project Invo, placed it into a dockerized environment with the new Phalcon 3, and created a [branch](https://github.com/igorsantos07/invo/tree/columnmap-issue) with the problem.

Actually, I couldn't even get `ignoreUnknownColumns` to work in `find()` scenarios as state in the initial bug report. To reproduce:
1. clone the repo (https://github.com/igorsantos07/invo) and checkout the `columnmap-issue` branch
2. run `docker-compose up -d`
3. run `docker-compose logs -f` to follow logs and see when the DB will be ready
4. access http://localhost:8000
5. an error message will popup and the logs in your terminal will state the `id` column isn't part of the columnMap, even with `ignoreUnknownColumns` enabled at `Services::initDb()`. Adding that line just above the `find()` command on `IndexController::indexAction` yields the same error.

**Comment by sergeyklay** [comment]
I'll take a look as soon as I can.

Thank you for contributing

**Comment by Druid33** [comment]
I have the same problem on phalcon 3.2.1.
Database i used is oracle 10g

**Comment by Jurigag** [comment]
@Druid33 @igorsantos07 could you try add to php.ini on proper sapi:

phalcon.orm.ignore_unkown_columns = 1

And restart your webserver/php-fpm and check again? This is just a guess.

**Comment by igorsantos07** [comment]
Sorry! I'm not on the project anymore 😔
Redirecting this to @gte451f

**Comment by Druid33** [comment]
@Jurigag 

adding `phalcon.orm.ignore_unkown_columns = 1` has no effect.

**Comment by Jurigag** [comment]
Your added it to correct sapi and restarted your webserver?

**Comment by sergeyklay** [comment]
> Database i used is oracle 10g

@Druid33 There is any chance to test `phalcon.orm.ignore_unkown_columns` with MySQL/PostgreSql/SQLite?

**Comment by pmanup** [comment]
the problem it's that orm generate metada from database and not from custom model.

if you put one method in yur parent class for all models like this:

use Phalcon\Mvc\Model\MetaData\Strategy\Annotations;

        public function metaData()
        {
            $anotations = new Annotations();
            return $anotations->getMetaData( $this, \Phalcon\DI::getDefault() );
        }

now, metada is generated from your model and you can add columns in your database without touch your model.

**Comment by Chealer** [comment]
I am getting this error with Phalcon\\Mvc\\Model\\Resultset\\Simple::toArray() with Phalcon 3.4.5. Is this supposed to be solved?
