### ISSUE TITLE
[NFR] Add "where" condition to Validator Uniqueness

### ISSUE THREAD

**Issue by yewjs** [phalcon/cphalcon#1191]
Can we specify more conditions that will be added as "where" clauses to the query:

```php
$this->validate(new Uniqueness(array(
     'field' => 'email',
     'condition'=>'status != "DELETE"'
)));
```

In the rule above, only rows with status not deleted would be included in the unique check.
##

**Comment by Jurigag** [comment]
There is except option which is solving this i think.
