### ISSUE TITLE
keepSnapshots is not working

### ISSUE THREAD

**Issue by KevinJay** [phalcon/cphalcon#11918]
```
class Test extends \Phalcon\Mvc\Model{
      public funtion initialize(){
          var_dump($this -> keepSnapshots(true));
      }
}
```
it's  output "NULL".

I tried to "setSnapshotData($data)" also is not working.

why?

Is I use the wrong way?

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/model.zep#L3584

It returns null because well - it returns null.

**Comment by KevinJay** [comment]
Can you give me a demo for  call "setSnapshotData" and "getSnapshotData" ? 
thanks.

**Comment by sergeyklay** [comment]
Have you seen https://docs.phalconphp.com/en/latest/reference/models.html#record-snapshots
