### ISSUE TITLE
Cannot update loaded relationships.

### ISSUE THREAD

**Issue by hisorange** [phalcon/cphalcon#11917]
Aye, not sure if it's a bug or did on purpose but when you load a relationship defined by a local property for e.g.: $parentID, and than trying to update that property the assign, and update fns will run and ignore the changes in the background, in code it looks like this:

``` php
class Robot extends Phalcon\Mvc\Model {
    public $parentID;

    public function initialize()
    {
        $this->belongsTo('parentID', 'Manufacturer', 'id', [
            'alias' => 'parent'
        ]);
    }
}

$robot  = Robot::findFirst();

if ($robot->parent->isAnything()) {
    $robot->update(['parentID' => 2]);
}
```

This runs silently and ignore the update, without throwing exception or returning false depending on the Model::setup(), but if I load the relationship like

``` php
$robot->getParent();
```

and update the parentID afterward it all works well.

I understand if the parentID changing the parent relationship has to be wiped but right now it locks the model, and the most problematic part is, it is not even reporting a failed update.

Phalcon version is 2.1.x, PHP 5.6

**Comment by sergeyklay** [comment]
Refs:
* https://github.com/phalcon/cphalcon/issues/11427
* https://github.com/phalcon/cphalcon/issues/10556
* https://github.com/phalcon/cphalcon/issues/11622
