### ISSUE TITLE
I could set non existing property in models

### ISSUE THREAD

**Issue by ddesplats** [phalcon/cphalcon#11912]
Hi all,

Here I have a big issue. When I try to set a non existing property on a model, i works !!!

After few "dive in the code" I found that Phalcon\Mvc\Model::isVisible() return true instead of false : https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L4191

Side effect is that it does not call magic setters on private nor crashes when trying to set a non existing property...

**Comment by tembem** [comment]
Let me help you create PR then. See https://github.com/phalcon/cphalcon/pull/11913

**Comment by gguridi** [comment]
The PR was rejected, I think this issue can be resolved as "won't fix" :)
