### ISSUE TITLE
[3.0.x] Remove $di being passed in as second parameter into Volt service

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#11926]
Phalcon 2.1 is binding the service functions to the dependency injector and so the second parameter being passed into the Volt definition is unnecessary.

This would turn the following:

``` php
$di->set('voltService', function($view, $di) {
    ...
    $volt = new Volt($view, $di);
```

into this:

``` php
$di->set('voltService', function($view) {
    ...
    $volt = new Volt($view, $this);
```

This would add consistency to the services but would have the downside of breaking existing service definitions.

**Comment by sergeyklay** [comment]
It seems to me this is mainly [phalcon/docs](https://github.com/phalcon/docs) issue

**Comment by Jurigag** [comment]
We just need to implemt both behaviours and that's it.

**Comment by dschissler** [comment]
Both behaviours are already implemented.  This issue is about removing one of them.  I don't want to close this issue because I think that it should be this way but since its just a matter of opinion then somebody else can close it.

**Comment by sergeyklay** [comment]
Could you please explain guys what kind of **problem** you are discussing

**Comment by dschissler** [comment]
I am not having a problem in the sense that I can't get it to do something or that there is regression.  Since I've been using the unreleased 2.1.x branch I have been taking advance of new features and capabilities.  One of those advancements is not needing to setup services in ways like `function() use ($di)` since with Phalcon 2.1 the service function is bound to the DI that it is being attached to.  I see it that the current voltService (maybe all engines, not sure?) signature is accepting a DI second parameter but this is now unnecessary sine the service is itself bound to the DI.  It has been suggested elsewhere that this allows for the use of two DIs but this was never a particular use case for the views and template engine throughout Phalcon's history so I think that it should be considered an artefact of old limitations (needing to support PHP 5.3 without `Closure::` tech).  So this is just something like an API cleanup.

**Comment by Jurigag** [comment]
For me old syntax shouldn't be removed on version 2.x. We could do it on 3.x for me.

**Comment by dschissler** [comment]
I don't think that there is a way to deprecate it in this case because it is an extra argument being sent in.

Ok so version 3 is super far away.  Should this just be closed?

Also since Phalcon is not semver now we could just remove this in version 2.2 or 3.0.  It would be very easy to document in a blog whats new post and quickly people would use the new way which is compatible with 2.1.

**Comment by Jurigag** [comment]
Where there is - we just need to use reflection, but should we ? Just if function accept two arguments - trigger deprecated and inform in which version it will be removed. We could in 2.2 maybe beacause we don't follow semver. But i think we always should inform about something before remove it, not everyone will check changelog, github or blog. Some of people will just install and that's it. At least in logs they could see something.

**Comment by dschissler** [comment]
Ok then

**Comment by dschissler** [comment]
Just for reference sake Vokuro has been using the new 3.0 capable style for a few months now without issue: https://github.com/phalcon/vokuro/blob/9573515fee52aceb7873762ecc12a5dd2c9ef554/app/config/services.php#L52

**Comment by dschissler** [comment]
Phalcon switched to semver when it jumped to version 3.0.  I propose that in late 2017 or so that a minor release should start throwing a deprecation warning if the second parameter is used.

**Comment by sergeyklay** [comment]
```php
$di->setShared(
    'volt',
    function (\Phalcon\Mvc\ViewBaseInterface $view, \Phalcon\DiInterface $di = null) {
        /** @var \Phalcon\DiInterface $this */
        $config = $this->getShared('config');

        $volt = new Volt($view, $di ?: $this);

        $volt->setOptions(
            [
                'compiledPath'      => $config->application->view->compiledPath,
                'compiledSeparator' => $config->application->view->compiledSeparator,
                'compiledExtension' => $config->application->view->compiledExtension,
                'compileAlways'     => (bool) $config->application->debug,
            ]
        );

        return $volt;
    }
);


di->setShared(
    'view',
    function () use ($registeredEngines) {
        /** @var \Phalcon\DiInterface $this */
        $config = $this->getShared('config');

        $view = new \Phalcon\Mvc\View();

        $engines = [
          '.volt' => $this->getShared('volt', [$view, $this]),
        ];

        $view->registerEngines($engines);
        $view->setViewsDir($config->application->view->viewsDir);

        return $view;
    }
);
```

**Comment by dschissler** [comment]
My point wasn't that this should be closed or that it is impossible to make a DI service now, but that removing the DI being sent in for the second parameter would break existing stuff.  So its pretty harmless for now and it needs to be there for the entire 3.* series but eventually it (DI being passed in as 2nd argument) should be removed for the 4 series.

**Comment by Jurigag** [comment]
It can be done in 3.* with keeping BC using reflection but there is no point in this imho.

**Comment by dschissler** [comment]
@sergeyklay @niden I propose that you reopen this and remove the $di second argument being passed for the volt function.  This is simply an artifact a long ago time when the DI service functions weren't bound to the DI object.  This is just inconsistent API and is not thoughtful or useful, its just old stuff that was never cleaned up.  The second parameter in the function does not need to be there.  Just get the DI from $this.  Any special weird setup that is precompiling or other unusual cases can simply bind the volt service function to the DI.  I don't believe that there is a use case for passing in two different DIs, (one from $this and one from the second parameter).  That doesn't exist.  Clean this crap up please.

**Comment by dschissler** [comment]
I propose just removing the di and not doing reflection as jurigag proposed before to save time adding problematic fix code.  It will be slightly confusing at first but its super easy to figure out during an upgrade.  The error logs will already say (expected DI but got null).  They'll figure it out real quickly.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
