### ISSUE TITLE
APCu classes

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11934]
In php7 in apcu there is no `apc_*` methods emulation. Phalcon has classes using only `apc_*`, not apcu. On some point if php 7 support in 2.1.x or later versions like 2.2.x or something will be better/stable we should add classes using APCu, so people don't need to install apcu_bc(which adds polyfill for apc_\* methods on php7).

**Comment by galki** [comment]
+1

**Comment by Jurigag** [comment]
You sure it's loaded ? Check phpinfo.

**Comment by galki** [comment]
That solved it, thank you. I was loading it in the wrong order.

**Comment by stevendesu** [comment]
+1 for APCu support

I'll be honest: I haven't fully done my research on this one. I did a bit of Googling for "PHP in-memory caches" and saw that my options were memcached and APCu, and reading up on the two it sounds like memcached is better for distributed environments or setups where more than PHP needs to read the cache, but if it's just PHP one a single server APCu is supposedly more performant. Based only on that minutia of knowledge I Google'd "Phalcon APCu support" and found this thread

I'll try installing APCu + APCu_bc and if it works as described then that will solve all of my issues for now (I have root access and can install whatever I need), but I know some people may not have the ability to install arbitrary extensions. Not to mention more extensions = more bloat, more memory usage, and longer load times.

**Comment by sergeyklay** [comment]
See https://pear.php.net/bugs/bug.php?id=21007

**Comment by Jurigag** [comment]
@stevendesu 

Extensions are loaded only on startup, apcu_bc is like a few kb of memory usage, and it has almost none bloat beacause it's just calling apcu functions.

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x` branch.
