### ISSUE TITLE
redis cache backend don't support the redis replication and redis sentinel model

### ISSUE THREAD

**Issue by bain2018** [phalcon/cphalcon#11939]
redis cache backend don't support the redis replication and redis sentinel model
if i have one master and two slave redis server,how can i use them?create 3 redis service di?
but if the redis sentinel change the redis master server,how deal with it?

**Comment by evrenbal** [comment]
Do we have a solution after 4 years of the original question?

**Comment by evrenbal** [comment]
> redis cache backend don't support the redis replication and redis sentinel model
> if i have one master and two slave redis server,how can i use them?create 3 redis service di?
> but if the redis sentinel change the redis master server,how deal with it?

Did you find a solution for this issue?
