### ISSUE TITLE
[NFR] Check for empty array in \Phalcon\Mvc\Model\Criteria::inWhere()

### ISSUE THREAD

**Issue by andrew-demb** [phalcon/cphalcon#11947]
It would be nice if we check array `values` and modify the condition in `\Phalcon\Mvc\Model\Criteria::inWhere()` method like implementation in `\Phalcon\Mvc\Model\Query\Builder::inWhere()`.
It's for 2.0.x versions and other (1.3.x, 2.1.x, etc).

This problem was raised in issue #10676.

Next script now throw exception `Phalcon\Mvc\Model\Exception: Syntax error, unexpected EOF`:
```php
$users = \Models\Users::query()
    ->inWhere("id", array())
    ->execute();
```

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
