### ISSUE TITLE
Phalcon Debug interferes with offline development due to external resources

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#11943]
I develop in offline mode quite a lot and Phalcon debug hangs the browser because it is looking for resources that aren't accessible.  I'm looking for possible solutions to allow it to always work.  Perhaps there could be an option to always direct it to an arbitrary url base path.

**Comment by stamster** [comment]
Phalcon debug? What exactly do you use?
Class Phalcon\Debug?

**Comment by dschissler** [comment]
I'm using `Phalcon\Debug`.  It wants to link:

* `//static.phalconphp.com/www/debug/2.0.0/jquery/jquery-ui.css`
* `//static.phalconphp.com/www/debug/2.0.0/themes/default/style.css`

I'm thinking that this could be fixed by allowing the debug service options to be set and to initiate it as a service.  For example:

```php
$di->set('debugComponent', function() {
    $config = $this->getConfig();
    $debug = new \Phalcon\Debug([
        'jqueryUi' => $config->...,
        'otherSetting' => $config->...
    ]);
    $debug->listen();
})
```

On my platform the debug component is only started if the environment is `DEVELOPING`.  Then I use Webpack so I can make the resources not part of the production build by writing `if (DEVELOPING)` and then since Webpack can evaluation that to always be `FALSE` it will remove that bit of code before loading modules and so it wouldn't be included in the output.

I'm trying to setup my development platform to use HSTS, always be HTTPS and the works so that it is just more similar to my production environment.  I worked offline a lot whether it is on a train or with a bad  wifi signal in the cafe and this would improve my experience.

I think that I can do this work myself within the next couple of months.

@andresgutierrez @sergeyklay Do you guys know if those resources are available ready to go with either Bower or NPM?  If not then I think that they should be.  I can do the work to upgrade the resources if needed and to evaluate if we want to jump to jquery 3.

**Comment by dschissler** [comment]
At least we really should consider upgrading these hard coded library versions before releasing 2.1.

**Comment by sergeyklay** [comment]
@dschissler May be closed?

**Comment by dschissler** [comment]
It always was setup to be able to work with offline usage.  We just need to make it easier from them to grab the resources.
