### ISSUE TITLE
fix install script

### ISSUE THREAD

**Issue by serus22** [phalcon/cphalcon#11953]
please edit install script who is creating symlink to ...../mods-available/phalcon.ini > ......20-phalcon.ini
to 50-phalcon.ini (for example, i think it could be 30+)

there is problem with loading mysql_pdo module - phalcon must be loaded after it

(its not real problem but its really annoying)
thanks

**Comment by stamster** [comment]
I never had such issue with 10+ installations from scratch / production.

**Comment by Jurigag** [comment]
I don't know why this is happening, maybe it's somehow system related ? Be default 20-pdo_mysql should be loaded BEFORE 20-phalcon beacause d is earlier than h, but on some systems it looks otherwise.

**Comment by stamster** [comment]
Yeah, Alphabet will take care of it, UNLESS locale setting interferes with
it in one way or another. Generally numbers are always better than alphabet
for sorting.


2016-07-05 13:14 GMT+02:00 Wojciech Ślawski <notifications@github.com>:

> I don't know why this is happening, maybe it's somehow system related ? Be
> default 20-pdo_mysql should be loaded BEFORE 20-phalcon beacause d is
> earlier than h, but on some systems it looks otherwise.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/phalcon/cphalcon/issues/11953#issuecomment-230451271>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMNhf5F4ZlLolfsH-h18VF8bhSrV8dVHks5qSjyZgaJpZM4JEM-0>
> .
>



-- 
I told the angels they could sing their songs to someone new.

>>Carpe diem quam minimum credula postero.<<

**Comment by Jurigag** [comment]
Yea, just better to change it 30 or 50 or something.

**Comment by serus22** [comment]
i have the same issue on debian wheezy and ubuntu 14lts (64 and 32b) and Ub. 16lts

**Comment by stamster** [comment]
How is that possible? I'm also using Ubuntu 14.04 LTS as well on a production, and never had such issue with PDO.
It must be something with a way how you built your stack before Phalcon. Did you compile PHP manually i.e. not used default repository?

**Comment by sergeyklay** [comment]
@serus22 Could you please explain a bit more, what kind of script you mean?

There are 4 ways to install Phalcon:

* `zephir build`
* Install via `build/install`
* `apt-get`
* Install from `ext/`

**Comment by sergeyklay** [comment]
@serus22 

We created a separated [repo for packaging](https://github.com/phalcongelist/packagecloud). 

This issue can be considered fixed since Phalcon 3.0.1
https://github.com/phalcongelist/packagecloud/blob/master/debian/phalcon.ini#L17

**Comment by virgofx** [comment]
We should still make a note once everything is working to re-do the installation documentation to include the matrix for installing different php versions / operating systems / provisioners.

**Comment by sergeyklay** [comment]
@virgofx I think now it is https://github.com/phalcongelist/packagecloud issue :)
