### ISSUE TITLE
PHP 5.3 support

### ISSUE THREAD

**Issue by lucasantarella** [phalcon/cphalcon#11956]
Hi everyone. I saw that it was listed on the main Phalcon site for installing the extension that PHP 5.3 was supported for compiling and installing the extension for version 2.0.x but here it says that PHP 5.4 is required. If PHP 5.3 is indeed supported, I cannot build the extension on PHP 5.3. It throws some Zend functions not found when compiling.

**Comment by Jurigag** [comment]
Not sure, perhaps zephir is needed for regenrate c source for php 5.3 ?

**Comment by andresgutierrez** [comment]
php 5.3.20 or greater should work with Phalcon 2.0.x, any version lesser than 5.3.20 is not supported by 2.0.x

**Comment by lucasantarella** [comment]
I'm running PHP 5.3.29. Really, I'm trying to run PHPUnit tests in Travis CI and I can't get PHP 5.3 to build in Travis, but PHP 5.4, 5.5, and 5.6 all run fine. Any suggestions?

**Comment by stamster** [comment]
I would strongly advise you to avoid PHP 5.3. It is much slower then current versions (not even comparing PHP 7).
It does not have OPcache at first place, and personally just writing `array` syntax is pain in the ass when I'm used to `[]` in PHP 5.4+.

**Comment by lucasantarella** [comment]
@stamster That's not really an option in this case. I'm with you, I like the new `[]` syntax and PHP 5.4 is a much needed improvement. But this library that I am working on is said support all PHP versions and I need to demonstrate that it is compatible with PHP 5.3. The only way to do this is to get phalcon to build in Travis CI for PHP 5.3 and run all PHPUnit tests. Without that, I cannot demonstrate why my PR should be merged. 

[Here](https://github.com/lucasantarella/oauth2-server-php/tree/phalcon-travis-ci-config) is the library I'm working on. If you could see anything wrong with my `.travis.yml` config, please let me know.

**Comment by stamster** [comment]
I just tested on one of my still in production PHP 5.3.14. 
I couldn't compile latest Phalcon v2.0.13. 
But I did managed to use PPA. 

```
 Web framework delivered as a C-extension for PHP
        phalcon                 enabled
   Author            Phalcon Team and contributors
   Version           2.0.9
   Build Date        Nov 26 2015 08:06:22
   Powered by Zephir Version 0.8.0a

```

It did installed 2.0.9. though, since this instance is 32bit... xD

So in short - you can get Phalcon to work even on PHP 5.3.14.

```
namespace OUTDATED;

use \Phalcon\Mvc\Micro\Exception as Error;

try{

$app = new \Phalcon\Mvc\Micro();

throw new Error(phpversion(), 381);
} catch (\Exception $e) {
        echo $e->getMessage() . PHP_EOL . $e->getCode() . PHP_EOL;
}
```
