### ISSUE TITLE
2.1.x install in php7 error

### ISSUE THREAD

**Issue by cq-z** [phalcon/cphalcon#11960]
error info 
` Cannot find config.m4. Make sure that you run /usr/local/bin/phpize in the top level sourc`

**Comment by andresgutierrez** [comment]
You need Zephir to install Phalcon+php7:

```
git clone http://github.com/phalcon/cphalcon
cd cphalcon
git checkout 2.1.x
zephir build --backend=ZendEngine3
```

https://blog.phalconphp.com/post/phalcon-2-0-13-released

**Comment by cq-z** [comment]
OK,thank you!
