### ISSUE TITLE
[NFR] Form input array invalidate

### ISSUE THREAD

**Issue by Mont4** [phalcon/cphalcon#11968]
Hi. Form validation does not work successfully in the array input.

``` php
        $title = new Text("title['en']", array(
            'class'       => 'form-control',
            'placeholder' => $this->trans->_('form.title'),
        ));
        $title->setLabel($this->trans->_('form.title'));
        $title->addValidators(array(
            new PresenceOf(array(
                'message' => $this->trans->_('validation.required', ['attribute' => 'form.title.en']),
            )),
        ));
        $this->add($title);
```

**Comment by Jurigag** [comment]
Beacause there is no such an ability as far as i know. This is actuallly NFR.

**Comment by cirot87** [comment]
Hi, if you use an Hidden object of the form you can get the value after an is_valid or bind function
$hidden = new Hidden("title");

You need to render this in your view.

But you can't use a  validation or filter when you call a bind or is_valid becouse this function are valid only for a single associative array as $title = new Text("title")

**Comment by Mo121Montazeri** [comment]
Please add this feature as soon as possible
it's very important for me
Thanks a lot
