### ISSUE TITLE
Cannot fetch all the result as an object when using raw sql.

### ISSUE THREAD

**Issue by raghavgarg1257** [phalcon/cphalcon#11963]
There are three function available to us "fetch()->returns a single row as an object", "fetchArray()->return a single row as an array" and "fetchAll()->returns a whole result as an array", but there is no function available to fetch whole result as an object.

**Comment by Jurigag** [comment]
Well not sure, but isn't is beacause you should phalcon `Row/Resultset` classes ?

**Comment by raghavgarg1257** [comment]
I guess Phalcon\Mvc\Model\Resultset class only works with models whereas I want to use raw sql with Phalcon\Db\Adapter\Pdo::query() and get the result as an object.

**Comment by Jurigag** [comment]
You can create Resultset object yourself. What you mean fetch all result as an object ? As stdClass or what ? If you want to map it to your model you can use resultset i think.

**Comment by stamster** [comment]
You need to set your PDO parameters if you need `fetch` to return an object. This is PDO stuff, not Phalcon.

**Comment by Jurigag** [comment]
Also i don't know where you have this fetchArray method in which class. If you are using `Phalcon\Db\Adapter\Pdo\Mysql` then second parameter in `fetchAll/fetchOne` is fetch mode. Just put in as second parameters `Phalcon\Db::FETCH_OBJ` or something like this.

**Comment by raghavgarg1257** [comment]
I want a mapped Object to one of my model if not possible then stdClass object would also be fine, I am not really sure how to use Resultset can you please show some example.?

I have tried `setFetchMode(\Phalcon\Db::FETCH_OBJ)` with `Phalcon\Db\Result\PDO::fetchAll()` but it anyways gives me an array, also tried giving `Phalcon\Db::FETCH_OBJ` as a parameter but got array. Only `Phalcon\Db\Result\PDO::fetch()` gives me a stdClass object but single row at a time.
I think `setFetchMode()` only affects `fetch()`.
![screenshot from 2016-07-11 15-16-14](https://cloud.githubusercontent.com/assets/6361538/16727187/8c32d474-477d-11e6-9769-04626bcd5711.png)

**Comment by Jurigag** [comment]
How about using ? https://docs.phalconphp.com/pl/latest/api/Phalcon_Db_Adapter_Pdo_Mysql.html Don't know what's the real difference between those classes.

**Comment by stamster** [comment]
@raghavgarg1257 just use ` Phalcon\Db\Adapter\Pdo\Mysql`, i.e. native PDO.

**Comment by Jurigag** [comment]
Also you have it in `$di` so no need to create new object.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
