### ISSUE TITLE
Install on Ubuntu 16.04 with PHP 7

### ISSUE THREAD

**Issue by jepster** [phalcon/cphalcon#11994]
Hi,

I tried a few stackoverflow instructions and a provided vagrantbox, but me as a phalcon newbie could not install phalcon with PHP 7. Do you have any "official" and straight-forward installation instruction?

**Comment by Jurigag** [comment]
1. Clone zephir repository.
2. Type `./install -c` inside of it
3. Go to phalcon repository
4. Select branch 2.1.x
5. Type `zephir fullclean`
6. Type `zephir build`

**Comment by stamster** [comment]
As a Phalcon newbie I would advise to first check out stable and production-ready Phalcon v.2.0.13 on PHP 5.4/5.5/5.6.

**Comment by Jurigag** [comment]
I don't think it's a problem. Perhaps 7.1 can be problem, last time i checked it compiled on php 7.0.5, will check on 7.0.8 and 7.1 when i will be home. You just still need zephir to build phalcon for php 7 and that's it.

**Comment by jepster** [comment]
Jurigag, the hint with the 2.1.x branch was useful. By this one I was able to compile phalcon successfully. However, if I add 

extension=phalcon.so

to my php.ini file, I cannot restart the apache webserver. I get the following item in my apache error log:

PHP Fatal error:  Class 'jsonserializable' not found in Unknown on line 0

Could this issue be related to case sensitivity regarding PHP's own class name "JsonSerializable", which was called without the uppercase letters?

**Comment by Jurigag** [comment]
You need to install json for php 7.

**Comment by jepster** [comment]
I could solve my issue. The problem was, that the phalcon php extension was loaded before the JsonSerializable class. So I have followed the steps from the answer at http://askstop.sc0713.com/0518/php-fatal-error-class-jsonserializable-not-found-in-unknown-on-line-0/. For keeping easier track, here's the cite of the necessary part:

> The problem is that the phalcon extension is being loaded before the json extension, so I guess that you, as myself, added the extension=phalcon.so line in the main php.ini
> 
> What you have to do is add a file in /etc/php/7.0/mods-available called phalcon.ini with the line in it: extension=phalcon.so
> 
> Then you just go and make a softlink that points from /etc/php/7.0/cli/conf.d/50-phalcon.ini to that phalcon.ini file, (important to put a number higher than 20 so it gets loaded after the json extension) and that's it!
> 
> Repeat the process to any other configuration that you have for php (apache, nginx, etc).

For usage along with apache I needed to copy the files in /etc/php/7.0/cli/conf.d "and" /etc/php/7.0/apache2/conf.d.

**Comment by Jurigag** [comment]
Im just always adding extension=phalcon.so at end of php.ini and it's working.

**Comment by jepster** [comment]
We are currently evaluating Phalcon for an new project. PHP 7 is a must for us. How long will it take to have Phalcon production ready for PHP 7?

**Comment by Jurigag** [comment]
When all php 7 issues will disappear from here:

https://github.com/phalcon/cphalcon/labels/PHP%207

Right now there are 2 hard problems - this opcache mentioned with conditions and bind and postgresql is seg faulting with php 7 and phalcon.
