### ISSUE TITLE
Upgrade from 1.x to 2.x has broken code with models magic getters/setters

### ISSUE THREAD

**Issue by TrogWarZ** [phalcon/cphalcon#11995]
## Prerequisites

* Ubuntu 12.04.x/14.x
* PHP 5.5.x/5.6.x (from `ppa:ondrej/php` and from deprecated `ppa:ondrej/php5-5.6` too)
* Transformers from [thephpleague/fractal package](https://github.com/thephpleague/fractal)
* Each API response contains mostly 100 objects + 3 connected objects (total 400 minus duplicates)
* [XhProf](https://github.com/gajus/xhprof.io) as profiler

## Phalcon 1.3.x (tested mostly on 1.3.6)

API response less than 1 second, about 5-7 megabytes RAM. XhProf shows that slowest point is `\file_exists` in composer autoload. Cool, fast.

## Phalcon 2.x (tested mostly on 2.0.10)

Strange happens. API response 40-60 seconds, very huge RAM eating (1 gigabyte and more plus swap), 100% eats one CPU core.

XhProf shows that bottleneck is `\ReflectionClass::getProperty` and traces leading to `\Phalcon\Mvc\Model\Resultset\Simple::current`. After some digging into, i found that PR #11417 made my code totally broken. Callgraph attached at the end of this post.

## Workaround

As a workaround i can extend magic setter of model in my base model and copy-paste some code from sources like this:

```php
public function __set($property, $value)
{
    if (is_array($value) || is_object($value))
        return parent::__set($property, $value);

    if ($this->_possibleSetter($property, $value))
        return $value();

    $this->{$property} = $value;

    return $value();
}
```

But, i think, this is a crooked nail. In my company and projects, we use only setters/getters for models and repos and don't care about setting like `$model->someprop = 'foobar'` (thus, it's not affects `toArray` call behaviour).

## Questions

1. Why it uses **very slow** Reflection instead of `getModelsMetadata` (that **can be cached**!)?
2. Really need caching of metadata here that got from Reflection. Can it be done? I can make PR for this but i have no experience with Zephir and time for this will be very huge (only in first part of august, maybe).
3. Can i update Phalcon later to LTS version and be **sure** that it (workaround, i mean) won't broke anything?

Thanks for any suggestions.

## Callgraph

![callgraph](https://cloud.githubusercontent.com/assets/5672868/16968369/73cd6568-4e1f-11e6-986d-caf867cef55c.png)

**Comment by andresgutierrez** [comment]
Maybe we should create an optimizer called is_private in Zephir, so the ORM does not have to use Reflection

**Comment by Jurigag** [comment]
Wiat, 8 total calls and 21 seconds spend on this ? What a hell.

**Comment by TrogWarZ** [comment]
@Jurigag , `\ReflectionClass` is really slow for any high-speed solution but Phalcon has great metadata's that can be cached. XhProf result shows that.

Simple test: install Phalcon 1.3.6, send request to api – get response in <1s, upgrade Phalcon to 2.x, send same request – get response in >20s. No other changes, 100% repeatable (on multiple versions in my subject post). Request will look like (in my concrete project) `api.example.com/v1/drivers?with=(cars,docs,passengers)` and respond will have 100 users (with 10+ properties) plus 300- connected objects.

I can trim my project (at make it as small as possible to reproduce) to post sample project for debugging and testing that later patch really solves issue. But remember – i use Phalcon with `thephpleague/fractal` (that i don't reversed yet but i decide that Fractal uses syntax like `$model->property` a lot) and – it will take long time because i will not be available the next two weeks on the internet. So, i'll post sample project about 2-7 august, really sorry for that.

ps: xDebug was disabled in all tests (and don't even installed). XhProf doesn't make any overhead by-design.

**Comment by Jurigag** [comment]
But as i wrote you. I checked it on 400 records, setting:

`Resultset->property` was done in 1.2E-5 sec
Foreach each row in resultset and set property directly on model like this:
`$model->property` was done in 0.0007 sec

I don't have slow execeution. Just that's why we need some script te reproduce, beacause i can't maybe andres can't.

**Comment by TrogWarZ** [comment]
@Jurigag , it's not enough to just "get some models from repository". You need to:

1. Create many (at least four in my example) models and implement Fractal Transformer in project for them.
2. Set up "one-to-many" relation from one of created models to all others
3. Implement Fractal TransformerManager in project and use it for working with responses
4. Link these models in Transformer as "optional available includes"
5. Request about 100 objects with all configured optional includes

As i said, i don't know right now how _exactly_ it works inside, especially with combination of magic setters (and don't have enough time until 2-7 august). But simple test with upgrading Phalcon to version with mentioned PR – breaks this code. Workaround in my post – solves issue.

I think that `\ReflectionClass` in `_isVisible` method is bottleneck now – that's the point why i'm creating issue here, in Phalcon project. If anybody can explain that it's slows down because of Fractal or my code smells bad or by any other reason – cool, i'll create issue there or refactor my code with "best practices" (-:

**Comment by Jurigag** [comment]
Relations doesn't have anything here beacause you don't join them.

**Comment by sergeyklay** [comment]
@TrogWarZ Could you please check the `3.0.x` branch now?

**Comment by sergeyklay** [comment]
@TrogWarZ

**Comment by TrogWarZ** [comment]
@sergeyklay, just installed `3.0.0` version and see broken changes. Will fix and check this today.

**Comment by sergeyklay** [comment]
@TrogWarZ Waiting for you

**Comment by andresgutierrez** [comment]
As ReflectionClass was removed I think this is fixed, also declare properties on every model must speed up any application.

**Comment by TrogWarZ** [comment]
Results of testing (ubuntu 12.04, 14.04) with different versions of php-fpm and phalcon:
```json
[
    {
        "v-php-fpm" : "5.6.23-1+deprecated+dontuse+deb.sury.org~precise+1",
        "v-phalcon" : "1.3.6",
        "time-php"  : 0.0746169090271,
        "time-db"   : 0.026349306106567
    },
    {
        "v-php-fpm" : "5.6.23-1+deprecated+dontuse+deb.sury.org~precise+1",
        "v-phalcon" : "2.0.13",
        "time-php"  : 26.32877898216248,
        "time-db"   : 0.079745054244995
    },
    {
        "v-php-fpm" : "5.6.23-1+deprecated+dontuse+deb.sury.org~precise+1",
        "v-phalcon" : "2.1.0 RC 1",
        "time-php"  : 28.077505111694336,
        "time-db"   : 0.02750825881958
    },
    {
        "v-php-fpm" : "5.6.23-1+deprecated+dontuse+deb.sury.org~precise+1",
        "v-phalcon" : "3.0.0",
        "time-php"  : 26.12922596931458,
        "time-db"   : 0.032534837722778
    },
    {
        "v-php-fpm" : "5.6.24-1+deb.sury.org~precise+1",
        "v-phalcon" : "1.3.6",
        "time-php"  : 0.36090803146362,
        "time-db"   : 0.30925035476685
    },
    {
        "v-php-fpm" : "5.6.24-1+deb.sury.org~precise+1",
        "v-phalcon" : "2.0.13",
        "time-php"  : 26.84207701683,
        "time-db"   : 0.1939103603363
    },
    {
        "v-php-fpm" : "5.6.24-1+deb.sury.org~precise+1",
        "v-phalcon" : "2.1.0 RC 1",
        "time-php"  : 27.166598796844,
        "time-db"   : 0.10126161575317
    },
    {
        "v-php-fpm" : "5.6.24-1+deb.sury.org~precise+1",
        "v-phalcon" : "3.0.0",
        "time-php"  : 26.581640958786,
        "time-db"   : 0.023773193359375
    }
]
```

Preparing XhProf dumps, right now, and trimming my app to give you example of code. Just wait for a bit – i'm after fulltime work now.

**Comment by andresgutierrez** [comment]
@TrogWarZ Can you please using 3.0x branch, fix hasn't landed into master yet

**Comment by TrogWarZ** [comment]
@andresgutierrez, am i doing it right?

```bash
git clone git://github.com/phalcon/cphalcon.git /tmp/cphalcon
cd /tmp/cphalcon/build
git checkout 3.0.x
./install
service php5.6-fpm restart
php -r "echo Phalcon\Version::get();"
```

**Comment by sergeyklay** [comment]
@TrogWarZ No. For dev branches only this aprouch:
```
...
git checkout 3.0.x
zephir fullclean && zephir build
...
```

**Comment by TrogWarZ** [comment]
@sergeyklay , oops, didn't know. Tested with build like you said on ubuntu 12.04/14.04 and php5.6/php7.0 – cool! Now works fast, yay! Thank you!
