### ISSUE TITLE
Phalcon\Image\Adapter\GD loses transparency on image resize

### ISSUE THREAD

**Issue by Dublerq** [phalcon/cphalcon#11997]
Issue: Phalcon's GD loses transparency of png file when it comes to resizing. Transparent part of image become black.

Phalcon information: 

```
Version => 2.1.0r
Build Date => Jun  3 2016 14:01:39
Powered by Zephir => Version 0.9.2a-dev
```

Code to reproduce:

```
$image = new \Phalcon\Image\Adapter\GD($image_path);
$image->background('#fff', 0); // for test purposes, not necessary 
$image->resize(500, 500);
if ($image->save($images_dir . '/' . $model->id . '.png')) {
// ...
}
```

**Comment by Jurigag** [comment]
This is happening i think beacause `imagealphablending(image, false);` is not executed. Check here source - https://github.com/phalcon/cphalcon/blob/master/phalcon/image/adapter/gd.zep#L127 on php lower than 5.5.0 it's working correctly beacause there is _create method executed which set `imagealphablending` to false which preserver transparency.

**Comment by Dublerq** [comment]
That's right, feel free to PR. I don't feel too confident with Zephir

**Comment by Jurigag** [comment]
Well if you could check if it's true(like install php 5.4.x for instance) and check if it's working then someone could do it.

**Comment by Dublerq** [comment]
@Jurigag We can generate an empty image using the same adapter and then test on it. There is no need for including one in tests.

**Comment by Dublerq** [comment]
@Jurigag Just tested on PHP 5.4.45 nad it works fine. As I said you were right

**Comment by Jurigag** [comment]
Is it fixed ? bug exists on php 5.6.

**Comment by Dublerq** [comment]
And every higher than 5.6

**Comment by Dublerq** [comment]
@Jurigag @sergeyklay 
![image](https://user-images.githubusercontent.com/13312449/29961297-737aa770-8eff-11e7-8fd5-8a56b1a09a9e.png)

**Comment by lajosbencz** [comment]
I encountered the same issue:

```php
$gd = new \Phalcon\Image\Adapter\Gd($tempFilePath);
$gd->resize($newWidth, $newHeight);
$gd->save($localPath, 90);
```

The resulting image has black background where it was transparent before.

Versions:
- PHP 7.2.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:23:06) ( NTS )
- Phalcon 3.4.3 Feb 25 2019 18:53:06
- Zephir 0.10.14-975ad02db4
