### ISSUE TITLE
How production ready is Phalcon for PHP 7?

### ISSUE THREAD

**Issue by jepster** [phalcon/cphalcon#11998]
Hi!

We are currently evaluating Phalcon for an new project. PHP 7 is a must for us. How long will it take to have Phalcon production ready for PHP 7? How risky is it to start with PHP 7 on production right now?

**Comment by Jurigag** [comment]
When all php 7 issues will disappear from here:

https://github.com/phalcon/cphalcon/labels/PHP%207

Right now there are 2 hard problems - this opcache mentioned with conditions and bind and postgresql is seg faulting with php 7 and phalcon.

**Comment by Green-Cat** [comment]
There are two known issues with php 7:
- Several PostgreSQL seg faults (doesn't affect you if you don't use postgresql as the database)
- Opcache seg fault when using conditions and bind at the same time.

**Comment by Jurigag** [comment]
Most of performance boost you just have from your code working on php 7, internally phalcon code will be like 1-5% difference I guess between php 5 and php 7.

**Comment by nsossonko** [comment]
Item #2 (opcache seg fault) was fixed it seems in d6855cc. :+1:

**Comment by Jurigag** [comment]
First too

**Comment by Jurigag** [comment]
Also keep in mind there is memory leak, so it's not production ready yet - especially if you are working on big result sets.

**Comment by nsossonko** [comment]
If someone can compile a windows php 7 dll I have a large, automated test suite I can run it through that can find issues in my project.

**Comment by Jurigag** [comment]
@nsossonko i think there are already windows dlls. Can you check it ?

**Comment by nsossonko** [comment]
Yes! So far so good, I will post full results of my tests later today. Great stuff, thanks guys!

**Comment by Jurigag** [comment]
@nsossonko well people have some weird problem with constructing di on windows

**Comment by nsossonko** [comment]
Not in my project, I am using a custom DI in one project and default DI (with some additions) in another, both no problem. I use $this (not the old use ($di)) for referencing the di, not sure if that matters.

**Comment by Jurigag** [comment]
No, they just have problem on something like this:

`$di = new Phalcon\Di\FactoryDefault(); // error here`

**Comment by nsossonko** [comment]
There's a memory leak issue on PHP 7, not sure what it is at this point, but my task runner is leaking memory continuously (and eventually dies from memory exhaustion). Problem did not occur on PHP 5.6 + Phalcon 2.1.x.

**Comment by Jurigag** [comment]
Yes, it's known, probably some model realted stuff, it happens on big resultsets.

**Comment by nsossonko** [comment]
Is there an issue #? Is there a way to manually work around the issue?

**Comment by Jurigag** [comment]
I don't think there is an issue. If you want to make it though you surely need to report it with some log from mem software analyzing stuff(like valgrind on linux).
