### ISSUE TITLE
Debug bar for Phalcon?

### ISSUE THREAD

**Issue by jepster** [phalcon/cphalcon#12002]
Hi,

the php frameworks Symfony, Laraval or Yii have a debug bar. For inspecting the sql-queries, profiling etc. I haven't seen in the Phalcon documentation, that something like this is integrated into Phalcon. Is there any extension you can recommend or do you have any similar way?

**Comment by Jurigag** [comment]
https://phalconist.com/fabfuel/prophiler
https://phalconist.com/snowair/phalcon-debugbar
