### ISSUE TITLE
TAG:2.0.13  strange problem with session

### ISSUE THREAD

**Issue by leezhiyong** [phalcon/cphalcon#12001]
I packaged fpm & phalcon in an image with docker, and run it as container.
In codes, I used class "Phalcon\Session\Adapter\Files" to handler session, but the data in session were always missing, I printed the session id and found empty.

Also I use the same code, it can be run correctly without docker

PHP.ini:
session.save_path = /tmp

**Comment by stamster** [comment]
Well, then it's docker stuff. Sessions are stored as files where native PHP configuration points them out on a filesystem. I would guess that you have issue on that level.
