### ISSUE TITLE
Drop Oracle support

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#12008]
Support of Oracle should be dropped from Phalcon Core for the following reasons:

* The lack of Oracle maintainer
* The lack of relevant experience among the Phalcon Core Team 
* Weak support from the community
* Incomplete implementation that creates only the illusion of support for Oracle
* Some issues hampering for the support of PHP 7 in Phalcon
* Weak interest of community

Oracle components need to be ported to the Phalcon Incubator. After (or if) they receive the appropriate support in the Phalcon Incubator repository, they may be returned back to the Phalcon Core.

**Comment by andresgutierrez** [comment]
👍

**Comment by andresgutierrez** [comment]
@sergeyklay is porting the implementation to the incubator so the community can still use Oracle alongside Phalcon https://github.com/phalcon/incubator/pull/647

**Comment by sergeyklay** [comment]
Fixed in the `2.1.x` branch.

**Comment by Green-Cat** [comment]
Major 👍

**Comment by arthurgermano** [comment]
This is a sad day... I really enjoy phalcon and I am building a new project using it.. So far so good. I have started in april.. and now.. I have this devastating news.. =(
I will have to rewrite all of it or worse abandon phalcon and go back to cake or other framework that supports oracle =(

Despite oracle hasn't a large number of followers.. there is some will be affected in a very bad way.. =(

All of that said.. Congratulations for phalcon.. it is a great framework =)

**Comment by Jurigag** [comment]
There is still adapter in incubator.

**Comment by andresgutierrez** [comment]
You can still use Oracle from the Incubator: https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Db/Adapter/Pdo/Oracle.php

**Comment by rodrigoformel** [comment]
This news was terrible. I suggested using Phalcon here at Embratel / Claro and was creating a test project to demonstrate and early on I can't use our database.

Bad thing about not having Oracle support.

**Comment by niden** [comment]
@rodrigoformel This post is from 2016 so this is not something new. 

There is a database adapter in the incubator that you can use but not sure how updated it is. 

If you are interested in this by all means create pull requests and contribute to either the incubator or the main repo for ORacle.

Whether this is a bad thing or not - debatable on who you ask.

**Comment by rodrigoformel** [comment]
I find it bad not to have Oracle support. It is probably the most widely used database in the enterprise. Anyway thank you for the answer.

**Comment by sergeyklay** [comment]
Well, if so popular, then we will not have to search a maintainer too long ;)
