### ISSUE TITLE
Model snapshots doesn't work with cache

### ISSUE THREAD

**Issue by udarkness** [phalcon/cphalcon#12000]
```php
public function initialize()
{
    $this->keepSnapshots(true);
}
```
works fine but when using it with the caching technique from this page: https://docs.phalconphp.com/en/latest/reference/models-cache.html#caching-resultsets
it produces an error  when calling the method hasChanged.
I guess the cache is not taking the snapshot when it restores the data.
The user has to manually call `$model->setSnapshotData($model->toArray())`, but this is a workaround that should not be required.

**Comment by sergeyklay** [comment]
@udarkness Could you please provide script to reproduce?

**Comment by udarkness** [comment]
Sure, create a new project with the phalcon tools, 
add this to the index controller:

```
<?php

class IndexController extends ControllerBase
{

    public function indexAction()
    {
        $site = Site::findFirst(array(
                "cache" => array(
                    "key" => "somecache",
                    "lifetime" => 3002
                )
        ));
        $site->hasChanged();
        var_dump($site);
        die();
    }

}
```

Add the modelCache for redis:
```
$di->set('modelsCache', function () use ($config) {

    // Cache data for one day by default
    $frontCache = new \Phalcon\Cache\Frontend\Data([
        "lifetime" => 33000,
        ]
    );

    // Memcached connection settings
    $cache = new Phalcon\Cache\Backend\Redis($frontCache, array(
        'prefix' => 'orm:',
        'host' => '127.0.0.1',
    ));

    return $cache;
});
```
Create a dummy table/model `Site`, add a record in the DB and this in the model

```
public function initialize()
{
    $this->keepSnapshots(true);
}
```

Run once and it is flawless, even the hasChanged works fine if you modify or not. 
Run again, and kaput! you will get
```
The record doesn't have a valid data snapshot

#0 /var/www/html/demo/app/controllers/IndexController.php(14): Phalcon\Mvc\Model->hasChanged()
#1 [internal function]: IndexController->indexAction()
#2 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(IndexController), 'indexAction', Array)
#3 [internal function]: Phalcon\Dispatcher->_dispatch()
#4 [internal function]: Phalcon\Dispatcher->dispatch()
#5 /var/www/html/demo/public/index.php(29): Phalcon\Mvc\Application->handle()
#6 {main}
```

The solution sounds easy, I don't know if the implementation is :), it is just to take the snapshot when the object wakes up

**Comment by Jurigag** [comment]
Oh okay, i see it's created already - https://github.com/phalcon/cphalcon/issues/12170

**Comment by sergeyklay** [comment]
@udarkness
Could you please check 3.0.x branch?

```
giit clone git@github.com:phalcon/cphalcon.git
git checkout 3.0.x
zephir fullclean
zephir fullclean build
```

**Comment by dschissler** [comment]
Nice one jurigag.

**Comment by udarkness** [comment]
Works great @sergeyklay, thank you @Jurigag
