### ISSUE TITLE
Default value for an action parameter is ignored

### ISSUE THREAD

**Issue by dedalozzo** [phalcon/cphalcon#1202]
Let's suppose I have a controller like this:

```php
class IndexController extends ListController {

  public function indexAction($hero = 'superman') {
    echo $hero;
  }

}
```

When I get the http://mysite.com, without any parameters, Phalcon passes to the action an empty string instead of NULL. This implies the default parameter value is ignored.
To fix this behaviour you have to do this:

```php
class IndexController extends ListController {

  public function indexAction($hero) {
    if (empty($hero))
      echo 'superman';
  }

}
```

Sometimes you want that http://mysite.com provide the same result of http://mysite.com/superman. Imagine for example a default order or results in a list.

**Comment by dedalozzo** [comment]
Well you closed this, but this is a bug.

**Comment by sergeyklay** [comment]
+ No reaction since Aug 23, 2015, when issue was tagged as "not a bug"
+ We don support `1.3.x` a very long time

**Comment by dedalozzo** [comment]
You right. Just to be sure, doesn't this problem affect 2.x?

**Comment by sergeyklay** [comment]
I'm not sure. I'll open this issue again if the problem is present in 2.x

**Comment by dedalozzo** [comment]
I will check and I'll let you know.

**Comment by dedalozzo** [comment]
Phalcon 2 doesn't have this bug anymore, just checked.

**Comment by sergeyklay** [comment]
Thanks
