### ISSUE TITLE
[suggestion] Deprecate 5.4 and 5.5 for next version of phalcon

### ISSUE THREAD

**Issue by Izopi4a** [phalcon/cphalcon#12025]
May i suggest deprecating of php 5.4 and php 5.5 ?

reason here http://php.net/supported-versions.php

i am not sure how many systems are running on 5.5 anyways, I am pretty sure people are either on 5.3 or those who update their systems after 5.3, they are on 5.6 

@sergeyklay @andresgutierrez

**Comment by andresgutierrez** [comment]
5.4 is already deprecated in 2.1/3.0, maybe could we deprecate 5.5 in some months?

**Comment by Izopi4a** [comment]
i dont thing its such a "must do" thing. But i guess code should be easier to maintain and also travis builds will pass faster since they will be runned on 5.6 and 7.0 for now

**Comment by Studentsov** [comment]
I think that the community shall refuse outdated versions as soon as possible. It is very important issue of safety.

**Comment by Studentsov** [comment]
Due to the beginning of development of the new version of a framework (or not? I not up to the end understood the appropriate pull-request) it is possible to think also of complete transition to support only to PHP 7 because development goes not quickly.

**Comment by tembem** [comment]
We can deprecate 5.5 after 7.0 is really stable, unless there's urgent reason to do that.

**Comment by Jurigag** [comment]
@Studentsov it's basically renamed 2.1.x to 3.0.x, there will be just 3.0.0 instead of 2.1.0

**Comment by zyxep** [comment]
i agree on @Izopi4a 

Why support a version that is deprecated by them self ?
As @sergeyklay say some companies still run a old version, but that is their headache they don't take care of their product they have made and add a security problem to their own product.

Phalcon can't care about that at ALL, they **should** only care about the current and maybe have a beta on the newest version of PHP.

So since php 5.5 is completely deprecated by them self on active support and security fixes why bother ?

I vote for support for this:
Phalcon 2.0.13 supports php 5.6 & possible php 7
Phalcon 3 supports 5.6 & php7 completely.

**Comment by Jurigag** [comment]
2.0.x will never support php 7, only 3, also 2.0.x will be no longer maintained.

**Comment by dschissler** [comment]
I think that we should support PHP 5.5 for another six months or so because then Ubuntu 16.04.2 will have come out and that will have given of the 14.04 people enough time to move over.

**Comment by dschissler** [comment]
@zyxep PHP support tends to be done by individual distros instead of by the PHP team and so there is still quite a lot of security support for many people some years after.

**Comment by Izopi4a** [comment]
If rest of you agree I say, support of php 5.* to be removed in phalcon 3.1. If you look at the code there are tons of if phpversion < 70000 etc..  I think phalcon is a framework that requires some skill. It isnt exacly composer update in order to make it work. So by the time 3.1 starts coming out i say drop all the php 5 support and clean the code for pure 7+.

**Comment by Jurigag** [comment]
Well that's a great idea, but 3.0.x should be still supported with 3.1.x, at least for something like 2 years or more.

**Comment by Izopi4a** [comment]
as far as i know "supported" means that bugs and security issues to be resolved. I think those PR can be merged both in 3.1 and 3.0.  I think this is what all the repos are doing. If you want the latest features you have to update.  I guess when the time comes to start thinking about 3.1 it should be fine to drop the php5 support.  Its worse for Andy cuz he has to start cleaning the code in ~3.0.5 or so :D . But who knows  we might become experts of C soon :P

**Comment by Jurigag** [comment]
Actually i thought that beacause of seperated php5/php7 builds we wanted to remove all those phpversion < 70000 but nvm.

**Comment by JCMais** [comment]
My suggestion is to deprecate and remove support for php 5.5 now, and support php 5.6 until their active support ends, at the end of this year.  There are no motives to support a php version that has hit their EOL, if people are still using it, they are the ones to be blamed, and should upgrade.

**Comment by stamster** [comment]
**PHP 5: Active Support Ends. Now what?**

Sooner or later new versions of frameworks, components, and tools will no longer support PHP 5. Here is a list of popular projects for which I was able to find information on PHP 5 support:

    NEOS 3.0 will be released in January 2017 and will not support PHP 5

    PHPUnit 6.0 will be released in February 2017 and will not support PHP 5

    TYPO3 8 LTS will be released in April 2017 and will not support PHP 5

    PhpSpec 4.0 will be released in June 2017 and will not support PHP 5

    Laravel 5.5 will be released in July 2017 and will not support PHP 5

    Xdebug 2.6 will be released in July 2017 and will not support PHP 5

    Symfony 4.0 will be released in November 2017 and will not support PHP 5

    Zend Framework plans to support PHP 5 until PHP 5.6 reaches its End of Life

    Joomla! 5 is planned for 2019 and expected to not support PHP 5 anymore

    Drupal 9, which is still several years away, is expected to not support PHP 5 anymore

**Comment by dschissler** [comment]
@stamster The only problem with this argument is that PHP 7.0 has the same EOL as PHP 5.6 and few would suggest to drop PHP 7.0 support just because of that.  Additionally most distros are inheriting code from Redhat or Debian and these distros are continuing to support PHP for quite a long time after the official PHP teams have stopped fixing serious issues.  So I just think that PHP 5 should be dropped when the people who are doing the work feel like it isn't worth the work and that they can be "brave" like Apple.

**Comment by niden** [comment]
The team has not fully discussed this but I think Phalcon 4 should drop support for PHP5. We cannot do the same with Phalcon 3 because it is LTS.

**Comment by SidRoberts** [comment]
@sergeyklay I think this can be closed now due to https://github.com/phalcon/cphalcon/pull/13027.
