### ISSUE TITLE
Adding a form message in controller doesnt show in view

### ISSUE THREAD

**Issue by Izopi4a** [phalcon/cphalcon#12037]
if i do this in the `controller`

```
$messages = $form->getMessages('name');
$messages->appendMessage(new  \Phalcon\Validation\Message("yohooo") );
var_dump($messages); // shows 1 message
```

however in the `view`

```
$form = $this->view->getVar("form");

var_dump($form->getMessages()); //prints null in view
```

discussed here https://forum.phalconphp.com/discussion/12205/appending-message-to-form#C37245

**Comment by sergeyklay** [comment]
Could you please provide Phalcon version and PHP

**Comment by Qmegas** [comment]
Hello Sergey,

I'm the one who originally raised this problem.

I tested it on Phalcon 2.10 and PHP 5.6

**Comment by Izopi4a** [comment]
i tested it on 3.0 with php7. I really dont know how to fix this tho

**Comment by Jurigag** [comment]
```
$messages = $form->getMessages('name');
```

What exactly this means ? After changing it to more proper:
```php
$messages = $form->getMessagesFor('name');
```

It works fine. I guess we should set this group somewhere in model - https://github.com/phalcon/cphalcon/blob/master/phalcon/forms/form.zep#L390 and work on it after setting it.
