### ISSUE TITLE
[2.0.10] Bug - Route

### ISSUE THREAD

**Issue by Mo121Montazeri** [phalcon/cphalcon#12034]
I have this code in route file
```php
$router->add(
    "/{language}/Genre/{title}/t{id}",
    array(
        'module'     => 'frontend',
        'controller' => 'genre',
        'action'     => 'show',
    )
)->setName('genre.show');
```

Problem one:
```php
$outputURL = $this->url->get(array('for' => 'genre.show', 'language' => 'en', 'title' => 'R&B', 'id' =>100));
// $outputURL is "http://development/Phalcon/en/Genre/R&B/t104"
```

$outputURL is "http://development/Phalcon/en/Genre/R&B/t104"
but $outputURL must be "http://development/Phalcon/en/Genre/**R%26B**/t104"

Problem two:
when browser request for "http://development/Phalcon/en/Genre/R%26B/t104"
```
App\Frontend\Controllers\EnController handler class cannot be loaded
#0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('App\\Frontend\\Co...', 2)
#1 [internal function]: Phalcon\Dispatcher->dispatch()
#2 /Users/iMohammad/Development/Phalcon/public/index.php(44): Phalcon\Mvc\Application->handle()
#3 {main}
```
in other case there aren't any problem
ex: when browser request for "http://development/Phalcon/en/Genre/Pop/t100"

**Comment by Jurigag** [comment]
Second problem happens beacause you have default behaviour of router i guess. Try to add false in constructor.

**Comment by andresgutierrez** [comment]
You can escape the value:

```php
$outputURL = $this->url->get(array(
   'for' => 'genre.show', 
   'language' => 'en', 
   'title' => $this->escaper->escapeHtmlAttr('R&B'), 
   'id' =>100
));
```

https://docs.phalconphp.com/en/latest/api/Phalcon_Escaper.html

**Comment by Mo121Montazeri** [comment]
[http://www.dalikon.com/en/Genre/R&B/t104](url) <- Laravel 5
[http://31.3.253.214/en/Genre/R&B/t104](url) <- Phalcon

```php
    $router = new Router(false);

    $router->removeExtraSlashes(true);
    $router->setDefaultModule('frontend');
    $router->setDefaultNamespace('App\Frontend\Controllers');

    return $router;
```

**Comment by Jurigag** [comment]
And some sample where you adding this route and where you register controllers ?

**Comment by Mo121Montazeri** [comment]
if "&" or "?" exist in URL. route doesn't work correctly.
@Jurigag @sergeyklay

**Comment by sergeyklay** [comment]
@Mo121Montazeri Could you please open a new issue with minimal script to reproduce

**Comment by Mo121Montazeri** [comment]
ok @sergeyklay
