### ISSUE TITLE
[NFR] Model validation setter/getter

### ISSUE THREAD

**Issue by NX49** [phalcon/cphalcon#12045]
Hello,
This feature will make way to get/set validators of model fields. It might be usefull when building forms, as the model validators can be merged along with form fields validators (to allow the code to stay DRY) and then provided to ie.: jQuery Form plugins like FormValidation, which are doing validation on the client-side before sending the form.

Below is the example of how I see it:

```
class Book extends Model
{
    protected function initialize()
    {
        $validation = new Validation();
        // Add some validators

        $this->setValidation($validation); 
    }
}
```

The `validation()` method will still be present for sake of any other validation, which is impossible(?) to do with validators, but the validation we have set using `setValidation()` is being fired right before calling the `validation()` method. If it fails, the `validation()` method is not being called. Of course there will be `getValidation()` method to get the current model validation.

I think that this new feature will not change the current behavior if implemented.

**Comment by Jurigag** [comment]
Well actually i think about this too to add `_validation` property to model to handle validation by annotations in future.
