### ISSUE TITLE
Phalcon 3.0.x debug screen looks terribly 

### ISSUE THREAD

**Issue by Dublerq** [phalcon/cphalcon#12047]
Is it normal that debug screen looks this way:
![image](https://cloud.githubusercontent.com/assets/13312449/17242087/9363b3f2-5575-11e6-88c3-5d794d1ba4b2.png)

Is old, good, fancy, styled view gone forever?

**Comment by sergeyklay** [comment]
@dschissler

**Comment by dschissler** [comment]
The resources appear to be in the correct place in the repo but they aren't on the www server.  The custom resources stayed in the same place so its easy to check.

The is on the website:
https://static.phalconphp.com/www/debug/2.0.0/prettify/prettify.js

This is not on the website:
https://static.phalconphp.com/www/debug/3.0.x/prettify/prettify.js

So it needs to get put there somehow.  I figured that it was automated.  Maybe it needs to be cloned over manually.

**Comment by dschissler** [comment]
Also we might want to change the default theme.  Currently we're using UI Lightness but we have a little time to find the best one before releasing.

**Comment by Jurigag** [comment]
I'm just guessing that phalcon website wasn't updated yet to latest commit ?

**Comment by dschissler** [comment]
Probably it needs a manual clone done from the terminal.

**Comment by Jurigag** [comment]
Or just git pull.

**Comment by dschissler** [comment]
So @niden or @andresgutierrez needs to do this.

**Comment by andresgutierrez** [comment]
This must be fixed now
