### ISSUE TITLE
What's the reason of 3.x instead of 2.x?

### ISSUE THREAD

**Issue by Dublerq** [phalcon/cphalcon#12049]
I've been discussing latest changes to phalcon with a few perons and they don't look to us like they are milestones or something. Our 1X k PHP lines project in phalcon has been upgraded to 3.x without a single change in code. We can't really see the reason of this decision.

@sergeyklay

**Comment by sergeyklay** [comment]
2.1 will not be fully backwards compatible. As a result, we are changing the version number to 3.0.

**Comment by Jurigag** [comment]
1. Too many new features.
2. Too many breaking BC things compared to 2.0.x(like models validation, some interfaces).

**Comment by sergeyklay** [comment]
Since 2.1 has many API changes, we decided that it would be best to not release it as is and start using SemVer to better communicate with the community and keep track of our releases.

**Comment by Dublerq** [comment]
From our perspective 3.x should be kept for at least full, official PHP7 support. Bear in mind that 2.1.x was still a dev branch. Upgrading project from for instance 2.0.4 to 3.0 doesn't really take much time to accomplish

**Comment by Jurigag** [comment]
Those are plans to support php7 fully. Understand that we are swtiching to semver and there are changes that breaks BC(removing of some things, methods name changing etc).

**Comment by Dublerq** [comment]
And this is why, in my opinion, you should keep old classes with new ones and wait with compatibility dropping till full support of php7. Which of those changes are brake breakthrough? None

**Comment by sergeyklay** [comment]
https://github.com/phalcon/blog/blob/master/data/posts/2016/07/2016-07-29-phalcon-3-0-0-released.md

See
> BACKWARDS INCOMPATIBLE

**Comment by Jurigag** [comment]
```
Phalcon\Mvc\Model\Validation is now deprecated in favor of Phalcon\Validation
Changed default hash algorithm in Phalcon\Security to CRYPT_BLOWFISH_Y
Changed constructor of Phalcon\Mvc\Model to allow pass an array of initialization data
Removed support for prefixes strategy in Phalcon\Loader
Method isSetOption in Phalcon\Validation\ValidatorInterface marked as deprecated, please use hasOption
Phalcon\Events\Event::getCancelable renamed to Phalcon\Events\Event::isCancelable
Removed Phalcon\Events\Manager::dettachAll in favor of Phalcon\Events\Manager::detachAll
Phalcon\Mvc\Model\Criteria::getOrder renamed to Phalcon\Mvc\Model\Criteria::getOrderBy
Phalcon\Acl\AdapterInterface::allow and Phalcon\Acl\AdapterInterface::deny have 4th argument - function, which will be called when using Phalcon\Acl\AdapterInterface::isAllowed
Phalcon\Acl\AdapterInterface::isAllowed have 4th argument - parameters, you can pass arguments for function defined in Phalcon\Acl\AdapterInterface:allow or Phalcon\Acl\AdapterInterface::deny as associative array where key is argument name
Mcrypt is replaced with openssl in Phalcon\Crypt
Default encrypt algorithm in Phalcon\Crypt is now changed to AES-256-CFB
Removed methods setMode(), getMode(), getAvailableModes() in Phalcon\CryptInterface
Removed Phalcon\Session #11340
```

Those changes affect BC somehow.
