### ISSUE TITLE
[3.0.x] Leaking memory on queries in PHP 5.5 and 7.0

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#12044]
I will provide a script here shortly now that I have the issue number.

**Comment by Jurigag** [comment]
To be honest - size of query shouldn't matter - just if you have larger resultsets - you need more memory, there is nothing fancy about this. Memory leaks should still happen, even on small queries.

**Comment by dschissler** [comment]
https://github.com/dschissler/phalcon_issue_12044

It appears to leak on both PHP 5.5 and 7.0 but more quickly on 7.0.

You can comment out the echo statements in the `printFileRange` function and see just the `echo memory_get_usage()` calls.  Also you can comment out the `foreach ($files as $file)` loop just after the first call to see that the memory doesn't go down.

**Comment by Jurigag** [comment]
Doesn't look like memory leak for me:

```
valgrind -v --log-file=apache.log --leak-check=full --read-var-info=yes php /vagrant/www/test/script.php
```

```
==7853== LEAK SUMMARY:
==7853==    definitely lost: 120 bytes in 3 blocks
==7853==    indirectly lost: 176 bytes in 5 blocks
==7853==      possibly lost: 0 bytes in 0 blocks
==7853==    still reachable: 10,732 bytes in 20 blocks
==7853==         suppressed: 0 bytes in 0 blocks
==7853== Reachable blocks (those to which a pointer was found) are not shown.
==7853== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

**Comment by dschissler** [comment]
Why won't it free the memory after being called?

**Comment by Jurigag** [comment]
As you see it frees memory, there is no memory leaks. You are just using full objects which cost memory and this is how php/phalcon works. What i can suggest is:

1)Don't use full objects(like select columns which you need)
2)Use arrays where possible(especially on resultset(`toArray()` method)

**Comment by dschissler** [comment]
Why does it never go down with `memory_get_usage` in the script?

**Comment by Jurigag** [comment]
Beacause this is how php works.

**Comment by dschissler** [comment]
I'll play with it tomorrow to make it more efficient to be able to complete and then I'll close this issue.

**Comment by Jurigag** [comment]
Also important thing to remember - phalcon caches all phql etc queries. You are making A LOT of them. Try to:

```
    Phalcon\DI::getDefault()
        ->getModelsManager()
        ->__destruct();
```

After each find/findFirst, it should greatly reduce your memory usage. Be aware it's only from 2.1.x.

**Comment by Jurigag** [comment]
With changing your code do something like this:

```
$limitSize = 100;
$fileCount = Meta::count("cpt IN ('file', 'doc')");
$numQueries = ceil($fileCount / $limitSize);
$currentOffset = 0;

for ($i = 0; $i < $numQueries; $i++) {
    printFileRange($limitSize, $currentOffset);
    $currentOffset += $limitSize;

    echo memory_get_usage()."\n";
}

sleep(10);
gc_collect_cycles();
sleep(10);
echo memory_get_usage();

function printFileRange($limit, $offset)
{
    $files = Phalcon\DI::getDefault()
        ->getModelsManager()
        ->createQuery("SELECT id, val FROM Meta WHERE cpt IN ('file', 'doc') limit $limit offset $offset")
        ->execute()
        ->toArray();

    Phalcon\DI::getDefault()
        ->getModelsManager()
        ->__destruct();

    foreach ($files as $file) {
        $fileId = $file['id'];
        $fileVal = $file['val'];

        $fileComment = Meta::findFirst(
            [
                'columns' => 'val',
                'conditions' => "cpt = 'note' AND lid = {$fileId}",
            ]
        );
        Phalcon\DI::getDefault()
            ->getModelsManager()
            ->__destruct();
        $pages = Meta::find(
            [
                'columns' => 'lelem,id',
                "cpt = 'page' and lid = {$fileId} ORDER BY lelem",
            ]
        )->toArray();
        Phalcon\DI::getDefault()
            ->getModelsManager()
            ->__destruct();

        $pageComments = [];
        foreach ($pages as $page) {
            $pageComment = Meta::findFirst(
                [
                    'columns' => 'val',
                    'conditions' => "cpt = 'note' AND lid = {$page['id']}",
                ]
            );
            Phalcon\DI::getDefault()
                ->getModelsManager()
                ->__destruct();
            if ($pageComment) {
                $pageNum = $page['lelem'] + 1;
                $pageComments[] = str_pad("p.{$pageNum} |", 9, ' ', STR_PAD_LEFT)."{$pageComment->val}";
                unset($pageComment);
                gc_collect_cycles();
            }
            unset($page);
            gc_collect_cycles();
        }

        unset($pages);
        gc_collect_cycles();

        if ($fileComment || count($pageComments) > 0) {
            echo $fileVal."\n";

            // File Commment
            if ($fileComment) {
                echo str_pad("file |", 9, ' ', STR_PAD_LEFT)."{$fileComment->val}\n";
                unset($fileComment);
                gc_collect_cycles();
            }

            // Page Comments
            foreach ($pageComments as $pageComment) {
                echo "$pageComment\n";
                unset($pageComment);
            }

            unset($pageComments);
            gc_collect_cycles();

            echo "\n";
        }

    }

    unset($files);
    gc_collect_cycles();
}
```

I have `334744` memory usage returned from `memory_get_usage`

**Comment by Jurigag** [comment]
Also this is happening also beacause you are NOT USING BINDING. Each condition like this:

`cpt = 'note' AND lid = {$fileId}`

Is changing phql query, which is causing adding new cache entry for phql. If you would use `cpt = 'note' AND lid = :field:` and bind then __destruct is not even needed.

**Comment by dschissler** [comment]
Thanks for the tips and I'll try to work into it tomorrow to see what can be done.  I my real project I disable all use of literals so that is good to know that it also adds efficiency.

**Comment by sergeyklay** [comment]
Also the problem is not using bound parameters: http://docs.phalconphp.com/en/latest/reference/models-cache.html#caching-of-phql-planning

Data is not "lost", PHQL planning is saved in memory until the request ends, you can track real memory leaks compiling PHP manually with --enable-debug and -dreport_memleaks=1

**Comment by Jurigag** [comment]
I see issue closed @dschissler you can even remove those unsets and gc_collect_cycles after changing your code beacause they are not needed. Also on php 7 there can be still memory leak - but this is actually memory leaks and they are known i think.
