### ISSUE TITLE
cphalcon3.0 crashed Error: Class 'MongoClient' not found

### ISSUE THREAD

**Issue by zyfmix** [phalcon/cphalcon#12058]
after upgrade to cphalcon3.0 with php7.0.9, i got error below:.

```php
Error: Class 'MongoClient' not found
```
> my old cphalcon2.0.9 php5.6 code like below

```php
$di->set("MongoSyData", function () use ($config) {
    $mongo = new \MongoDB\Driver\Manager("mongodb://127.0.0.1:27017");
    return $mongo->selectDb("syData");
}, true);
```
### Details

I had compiled [mongo-php-driver](https://github.com/mongodb/mongo-php-driver) ext from source.who can help me to connect mongodb with cphalcon3.0

**Comment by Jurigag** [comment]
Phalcon just don't support new mongo driver yet.

**Comment by Green-Cat** [comment]
There is an adapter on the incubator repo, might be worth a try.

**Comment by zyfmix** [comment]
Thank you for your answer. but when i try this incubator like below:
`
$di->set("MongoSyData", function () use ($config) {
    //$mongo = new MongoClient("mongodb://127.0.0.1:27017");
    //return $mongo->selectDb("syData");
    $mongo = new Phalcon\Db\Adapter\MongoDB\Client("mongodb://127.0.0.1:27017");
    return $mongo->selectDatabase('syData');
}, true);
`
it crashed error : 
`
RuntimeException: Call to undefined method ::rewind()
`
from my Collection::findFirst code:
`
$this->casc = LogClientAccessSecurityControlCollection::findFirst(array(
      array("ip" => $this->ip)
));
`
it seems has great work to migration .Who have a good solution?

**Comment by denzyldick** [comment]
@zyfmix  Did you found the solution to your problem ?

**Comment by MaksSlesarenko** [comment]
Encountered problem
