### ISSUE TITLE
Phalcon 3.0.x re2c

### ISSUE THREAD

**Issue by cdekok** [phalcon/cphalcon#12051]
It on OS X it didn't compile it threw a warning about re2c i needed to install it with

```
brew install re2c
````

Perhaps add some docs for Mac.

**Comment by sergeyklay** [comment]
It is [Phalcon Docs](https://github.com/phalcon/docs) issue. Could you please open the issue in the corresponding repo

**Comment by sergeyklay** [comment]
@SidRoberts Could you please sort out with this?

**Comment by cdekok** [comment]
Hi @sergeyklay can't we just add it to the README.md in this repo? 
https://github.com/phalcon/cphalcon#linuxunixmac
That what was i was reading trying to install it.

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
