### ISSUE TITLE
Phalcon 3 Mongo support

### ISSUE THREAD

**Issue by Akhundzade** [phalcon/cphalcon#12067]
Any chance to having mongodb driver support in ODM/Cache/etc for Phalcon3/PHP7 soon?

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/11156
https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Db/Adapter

**Comment by Akhundzade** [comment]
@sergeyklay Hi Sergey. Was nice to meet you last year on phpframeworkday in Kyiv :) 
Unfortunately adapters above can not solve problem. We are using Cache/Backend/Mongo for our needs and getting error like this during any cache operation:

> Fatal error: Class 'mongoclient' not found in ***/traits/Translatable.php on line 116

Line 116 is like this:
`$this->getDI()->get('cache')->get($key)`

And in DI
> new Phalcon\Cache\Backend\Mongo

Couldn't find adapter for cache in incubator. 
Issue with ODM solved, big thanks.

**Comment by sergeyklay** [comment]
@Akhundzade Could you please open an issue with script to reproduce at Incubator? I'll try to sort out.
