### ISSUE TITLE
php7.0-phalcon package for ubuntu 14.04

### ISSUE THREAD

**Issue by ReDev1L** [phalcon/cphalcon#12060]
Hello, can you please make package for php7.0 in ubuntu 14.04 phalcon PPA, so it will be compatible with ondrej sury PPA for php 7.0

**Comment by sergeyklay** [comment]
Could you please open the issue at [PPA repo](https://github.com/phalcon/phalcon-ppa)?

**Comment by ReDev1L** [comment]
done
