### ISSUE TITLE
[NFR] Allow injection of database stubs into MVC\Models.

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#1207]
For the purposes of unit testing I would like to detach database connection from my MVC\Models.

I want to be able to swap in stubs generated by $this->getMockBuilder() to prevent models from accessing database.

More info here:

http://forum.phalconphp.com/discussion/864/mvc-models-replacing-phalcon-db-adapter-pdo-mysql-with-a-stub

Thanks,

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
