### ISSUE TITLE
Type of "validation" variable checked twice in Phalcon\Validation on line 171 and 175

### ISSUE THREAD

**Issue by iugostudio** [phalcon/cphalcon#12085]
In Phalcon\Validation class duplicated code on lines 171 - 177.
`if typeof validator != "object" {
    throw new Exception("One of the validators is not valid");
}`

https://github.com/phalcon/cphalcon/blob/3.0.x/phalcon/validation.zep#L171

**Comment by sergeyklay** [comment]
Good catch

**Comment by Jurigag** [comment]
About this - we could possibly do a method https://github.com/phalcon/cphalcon/blob/3.0.x/phalcon/validation.zep#L132 beacause in those loops is done the same thing.

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
