### ISSUE TITLE
Rename Phalcon\Assets\Resource

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#12082]
I suggest to rename `Resource`, beacause it's on soft reserved word of PHP.

---

To rename:
- [x] `Phalcon\Assets\Resource`  (`Phalcon\Assets\Asset`)
- [x] `Phalcon\Assets\Resource\Css` (`Phalcon\Assets\Asset\Css`)
- [x] `Phalcon\Assets\Resource\Js` (`Phalcon\Assets\Asset\Js`)

**Comment by Jurigag** [comment]
ResourceAware and ResourceInterface don't need renaming though.

**Comment by sergeyklay** [comment]
I think this is similar to what is nonsense
```php
class Phalcon\Acl\Something implements Phalcon\Acl\ResourceInterface {}
```

May better naming is
```php
class Phalcon\Acl\Something implements Phalcon\Acl\ SomethingInterface {}
```

About ResourceAware:
The `Phalcon\Acl\Resource` is soft implements `ResourceAware`

**Comment by Jurigag** [comment]
No it's not similar, read my comment. Right now you can using ResourceAware like this:

```php
class User extends Phalcon\Mvc\Models implements ResourceAware
{
protected $name;

public function getName() // we cant use beacause of this ResourceInterface
{
return $this->name;
}

public function getResourceName()
{
    return "User";
}
```

```php
$user = new User();
$acl->isAllowed('SOME_ROLE', $user, 'create');
```

Only one solution is to simplify ResourceInterface as hard is it can be and change method names.

**Comment by niden** [comment]
@sergeyklay Renaming the Assets is easy, should have that done reasonably soon.

As far as the ACL is concerned. I propose the following
- `Phalcon\Acl\Resource` -> `Phalcon\Acl\Subject`
- `Phalcon\Acl\ResourceInterface` -> `Phalcon\Acl\SubjectInterface`
- `Phalcon\Acl\ResourceAware` -> `Phalcon\Acl\SubjectAware`

Also if we move to `Subject` we will have to change the `Role` as follows

- `Phalcon\Acl\Role` -> `Phalcon\Acl\Operation`
- `Phalcon\Acl\RoleInterface` -> `Phalcon\Acl\OperationInterface`
- `Phalcon\Acl\RoleAware` -> `Phalcon\Acl\OperationAware`

This pretty much changes the verbiage to `Subject` and `Operation` two terms that are widely used in the industry when describing access control lists.

**Comment by niden** [comment]
cc @Jurigag @danhunsaker

**Comment by niden** [comment]
This has been addressed
