### ISSUE TITLE
Error: Phalcon\Mvc\Model\Validator\StringLength does not implement Phalcon\ValidationInterface

### ISSUE THREAD

**Issue by mate01988** [phalcon/cphalcon#12097]
Argument 1 passed to Phalcon\Mvc\Model::validate() must implement interface Phalcon\ValidationInterface, instance of Phalcon\Mvc\Model\Validator\StringLength

**Comment by Jurigag** [comment]
Check blog post about new validation.

**Comment by mate01988** [comment]
I have that same problem:

Catchable fatal error: Argument 2 passed to Phalcon\Validation::add() must implement interface Phalcon\Validation\ValidatorInterface, instance of Phalcon\Mvc\Model\Validator\PresenceOf

**Comment by Jurigag** [comment]
You need to use `Phalcon\Validation\Validator\PresenceOf`, not `Phalcon\Mvc\Model\Valiadtor\Presence of` etc

**Comment by stamster** [comment]
At least provide Phalcon version you're using.

**Comment by Jurigag** [comment]
3.0 obviously.

**Comment by ralrom** [comment]
I was having the same issue. In addition to using Phalcon\Validation\Validator classes, you must also rewrite your model's validation method.

Old validation (doesn't work on Phalcon 3):
```
public function validation()
{
    $this->validate(new StringLengthValidator(array(
      "field" => "password",
      "min" => 6,
      "messageMinimum" => "Please choose a longer password (6 characters min)"
    )));

    if ($this->validationHasFailed() == true) {
      return !$this->validationHasFailed();
    }
}
```

New validation:
```
public function validation()
{
    $validator = new Validation();

    $validator - > add(
        'password',
        new StringLengthValidator([
            'model' => $this,
            'min' => 6,
            'messageMinimum' => 'Sorry, That username is already taken',
        ])
    );
    return $this->validate($validator);
}
```
