### ISSUE TITLE
Acl setNoArgumentsDefaultAction inconsistency

### ISSUE THREAD

**Issue by galki** [phalcon/cphalcon#12094]
I tried to use the _setNoArgumentsDefaultAction_ method in the **"Objects as role name and resource name"** example of the [documentation ](https://docs.phalconphp.com/en/latest/reference/acl.html) but it didn't work. Is this a feature or a bug?

**Comment by Jurigag** [comment]
Post script to reproduce.

**Comment by galki** [comment]
I must have misread the error for
`$acl->allow('guest', 'index', 'get', 'a_function_that_does_not_exist');`
Really sorry for wasting your time.

**Comment by Jurigag** [comment]
Oh, no problem, i will add test anyway.
