### ISSUE TITLE
502 Bad Gateway in $app->mount()

### ISSUE THREAD

**Issue by hartjo** [phalcon/cphalcon#12092]
how to catch controller error and return exception i only got 502 bad gateway if i put intended error on my controller and no response. In php56 and phalcon 2.0.x is working find but in PHP7 and Phalcon 3.0 i got 502 bad gateway please help thanks

```php
<?php

    namespace Controllers;

    class UsersController extends BaseController
    {
        asdasdasd <------- some intended error
        public function index() 
        {

        }

    }



    $test = new Phalcon\Mvc\Micro\Collection();
    $test->setHandler('Api\Controllers\TestController', true);
    $test->get('/','index');
    $app->mount($test);   <------ i got 502 bad gateway here how to catch error
```

in php56 and phalcon2.0.x working find

![screen shot 2016-08-05 at 8 04 08 am](https://cloud.githubusercontent.com/assets/8595930/17422318/51a3edb0-5ae3-11e6-9864-5143682d8f79.png)

php70 and phalcon3.0 502 bad gateway
![screen shot 2016-08-05 at 8 04 51 am](https://cloud.githubusercontent.com/assets/8595930/17422330/6d44a6f4-5ae3-11e6-97ec-6222f658cc4b.png)

**Comment by Jurigag** [comment]
502 bad gateway means that your php handler ended unexpectedly. There is probably seg fault generated(check logs) if yes - provide gdb stack reading this - https://bugs.php.net/bugs-generating-backtrace.php
