### ISSUE TITLE
Column Mapping PHQL Result

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#12091]
Problem looks like here: 

https://github.com/phalcon/cphalcon/blob/5372ac7972218b10fd9f08027a7718ea10f191b5/phalcon/mvc/model/resultset/simple.zep#L111-L133
https://github.com/phalcon/cphalcon/blob/5372ac7972218b10fd9f08027a7718ea10f191b5/phalcon/mvc/model.zep#L534

```
Type: Phalcon\Mvc\Model\Exception
Message: Column 'country_code' doesn't make part of the column map
Line: 34
Trace: 

#0 [internal function]: Phalcon\Mvc\Model::cloneResultMap(Object(Registry), Array, Array, 0, false)
```

``` php
// OK:
$query = 'SELECT registry.* FROM '
                . 'Registry registry '
                . 'INNER JOIN Country country ON country.id = registry.country ';

// Exception:
$query = 'SELECT country.* FROM '
                . 'Registry registry '
                . 'INNER JOIN Country country ON country.id = registry.country ';

// OK:
$query = 'SELECT country.* FROM '
                . 'Country country '
                . 'INNER JOIN Registry registry ON country.id = registry.country ';

// Exception:
$query = 'SELECT registry.* FROM '
                . 'Country country '
                . 'INNER JOIN Registry registry ON country.id = registry.country ';

// OK:
$query = 'SELECT registry.*, 1 AS test FROM '
                . 'Country country '
                . 'INNER JOIN Registry registry ON country.id = registry.country ';
```

$di->modelsManager->executeQuery($query);
### Details
- Phalcon version: 2.0.9
- PHP Version: 5.6.23-0+deb8u1
- Operating System: Debian 8
- Installation type: Compiling from source
- Zephir version (if any): 0.8.0a
- Server: Nginx
- Other related info (Database, table schema):

**Comment by Jurigag** [comment]
Try to update phalcon to 2.0.13 or 3 ?

**Comment by sergeyklay** [comment]
The 2.0.x branch is not longer supported. Could you please try to test 3.0.0?

**Comment by tugrul** [comment]
@sergeyklay same issue on 3.0.0

**Comment by MaksSlesarenko** [comment]
Same bug in php7 + phalcon 3.0.0
