### ISSUE TITLE
Error with column map under PHP 7.0

### ISSUE THREAD

**Issue by davihu** [phalcon/cphalcon#12096]
Hi, found a bug under Phalcon 3.0.0 and PHP 7.0

When I enable dynamic updates in model

```php
public function initialize()
{
    $this->useDynamicUpdate(true);
}
```

An error with column map appears, work fine under PHP 5.6 or when I disable it under PHP 7.0. I am not using any columns mappings and model attributes = database columns including case.

```php
object(Phalcon\Mvc\Model\Exception)[154]
  protected 'message' => string 'Column 'id' doesn't make part of the column map' (length=47)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string '...' (length=134)
  protected 'line' => int 20
  private 'trace' (Exception) => 
    array (size=13)
      0 => 
        array (size=4)
          'function' => string 'setSnapshotData' (length=15)
          'class' => string 'Phalcon\Mvc\Model' (length=17)
          'type' => string '->' (length=2)
          'args' => 
            array (size=2)
              ...
      1 => 
        array (size=4)
          'function' => string 'cloneResultMap' (length=14)
          'class' => string 'Phalcon\Mvc\Model' (length=17)
          'type' => string '::' (length=2)
          'args' => 
            array (size=5)
              ...
      2 => 
        array (size=6)
          'file' => string '...' (length=134)
          'line' => int 20
          'function' => string 'current' (length=7)
          'class' => string 'Phalcon\Mvc\Model\Resultset\Simple' (length=34)
          'type' => string '->' (length=2)
          'args' => 
            array (size=0)
              ...
```

**Comment by galki** [comment]
I can reproduce this.

**Comment by Jurigag** [comment]
Okay, but how ?

**Comment by galki** [comment]
Any combination of these 2 methods
```
public function initialize()
{
    $this->useDynamicUpdate(true);
    $this->keepSnapshots(true);
}
```
then
```
public function modelAction()
{
    $project = \Project::find();
    $project[0]->toArray(); // error

    $project = \Project::findFirst(123); // error
}
```

**Comment by Jurigag** [comment]
Check latest 3.0.x, you need to use zephir to compile it.

**Comment by sergeyklay** [comment]
@davihu @galki 

Could you please check 3.0.x branch?

```sh
git clone git@github.com:phalcon/cphalcon.git
cd cphalcon
git checkout 3.0.x

# Use latest Zephir here (from master branch)
zephir fullclean
zephir build
```

**Comment by davihu** [comment]
Hello @Jurigag and @sergeyklay,

look like everything is working now, using last nightly build phalcon_3.0.2-148 and zephir 0.9.4a-dev-7e304ba18c

Thanks a lot.

**Comment by davihu** [comment]
So, I tested it a bit more and there is still one case, when it is not working.
When you globally enable

phalcon.orm.cast_on_hydrate = On

then it is not working and it is returning that error. Bwt. cast_on_hydrate is very good for JSON APIs when you anable it, you can directly return results and numbers are numbers, strings are strings and bools are bools, otherwise its all string.

**Comment by Jurigag** [comment]
Only if you are not using mysqlnd(and you have stringify enabled in db connection) all are strings. Im not using cast_on_hydrate and have numbers returned from database.

**Comment by sergeyklay** [comment]
Well, for `cast_on_hydrate` create please separated issue with script to reproduce
