### ISSUE TITLE
multiple field Uniqueness validation in 3.0.0

### ISSUE THREAD

**Issue by Brade** [phalcon/cphalcon#12090]
I've read thru issues #11807, #11173, and #11826 and I still don't think multi-field Uniqueness validation is working as expected. I am using the new version 3. Here is my code in the model file:

`

    public function validation() 
    {
        $validator = new Validation();
        $validator->add('provider_id', new PresenceOf(['model' => $this, 'message' => 'Provider is required.']));
        $validator->add('date_applied', new PresenceOf(['model' => $this, 'message' => 'Date Applied is required.']));
        $validator->add(['provider_id', 'date_applied'], new Uniqueness(['model' => $this, 'message' => 'This Provider already has an entry for this Date Applied.']));
        return $this->validate($validator);
    }
`

The first 2 validator rules for PresenceOf work as expected, but the Uniqueness rule is seemingly ignored. I don't want multiple records to have the same combination of provider_id and date_applied.

**Comment by Jurigag** [comment]
Post your table and content of it ? You don't need to add `model` => $this in validators if it's done on model.

**Comment by Jurigag** [comment]
On phalcon_test table:

```php
$di = new Phalcon\DI\FactoryDefault();

$di->setShared('db', function () {
    $connection = new Phalcon\Db\Adapter\Pdo\Mysql([
        'adapter'  => 'Mysql',
        'host'     => 'localhost',
        'port'     => 3306,
        'dbname'   => 'phalcon_test',
        'username' => 'root'
    ]);

    return $connection;
});
Model::setup([
   'notNullValidations'=>false
]);

class Robots extends Phalcon\Mvc\Model
{
    public $id;

    public function getSource()
    {
        return 'robots';
    }

    public function validation()
    {
        $validation = new Validation();
        $validation->add('text', new Validation\Validator\PresenceOf());
        $validation->add(['name','type'], new Validation\Validator\Uniqueness());
        return $this->validate($validation);
    }
}
$robot = new Robots([
   'type'=>'mechanical',
   'name'=>'Robotina',
   'year'=>'1955',
   'datetime'=>'1972-01-01 00:00:00',
]);
var_dump($robot->create());
var_dump($robot->getMessages());
```

```
bool(false) array(2) { [0]=> object(Phalcon\Mvc\Model\Message)#47 (5) { ["_type":protected]=> string(10) "PresenceOf" ["_message":protected]=> string(22) "Field text is required" ["_field":protected]=> string(4) "text" ["_model":protected]=> NULL ["_code":protected]=> int(0) } [1]=> object(Phalcon\Mvc\Model\Message)#46 (5) { ["_type":protected]=> string(10) "Uniqueness" ["_message":protected]=> string(31) "Field name, type must be unique" ["_field":protected]=> array(2) { [0]=> string(4) "name" [1]=> string(4) "type" } ["_model":protected]=> NULL ["_code":protected]=> int(0) } }
```

**Comment by Jurigag** [comment]
Also you are telling that presence of is working. So im guessing that you have messages from presnce of ? Then obviously uniqueness is checking on nulls - you sure you have null values in table for those columns ?

**Comment by Brade** [comment]
Okay, I tried several scenarios (creating vs updating) with your code example and they all worked. So then I realized that my code also has a beforeSave rule like so:

`
    public function beforeSave()
    {
        $this->date_applied = date('Y-m-d', strtotime($this->date_applied));
    }
`

I do this because my form field has a more typical date format of m/d/Y, so my theory is that Phalcon is not always applying the beforeSave rules BEFORE applying the validation rules.

**Comment by Jurigag** [comment]
Yes, beacause you actually need to use beforeValidationOnSave. beforeSave is fired afet validation.

**Comment by Brade** [comment]
Great, that fixed all my issues. Thanks!

**Comment by hardik-satasiya** [comment]
how about forms, how do you write multiple columns in forms.
