### ISSUE TITLE
[3.x] [NFR] - Add Base 62 to Phalcon\Security\Random

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#12105]
Base62 is nice because it is the largest value that can safely be used in URLs without needing to take extra characters into consideration because it is [A-Za-z0-9].

**Comment by dschissler** [comment]
Also base 62 can be made to handle negative numbers as well since the `-` symbol is unused.  I'm unsure if we would want to add negative number handling to the routines or just to leave it up to the developer if they need it.

Actually I'd like to see Phalcon be able to provide a nice API wrapper for creating numbers in various bases because the `gmp_strval(gmp_init(...))` (using `gmp` extension) approach really sucks.

Also, wow, it would be nice if Phalcon could generate some UUIDs as well because that whole situation in PHP is a huge joke and it takes up far too much time for such an ancient concept.

**Comment by sergeyklay** [comment]
Implemented in the `3.2.x` branch
