### ISSUE TITLE
Validator option to skip all validation if field is not present

### ISSUE THREAD

**Issue by codeaid** [phalcon/cphalcon#12106]
## Problem

Currently there is no way to completely skip validation if a field has not been passed as part of an array into the `validate()` method. There was a similar issue submitted for this type of problem (#11597), however, the suggestion to use `allowEmpty` given in it doesn't really solve the problem. 

In my current scenario data is coming from an API endpoint, meaning not all fields are being submitted to PATCH endpoints. Users can submit `{ a: 1 }`, `{ b: 2 }` or `{ a: 1, b: 2 }`, which would all be equally valid in REST world. 

The problem is - if `allowEmpty` is enabled then consumers can still post `false`, `0`, `[]`, `null`, `""` etc. - anything that is an empty value, because the `preCheck()` method [has](https://github.com/phalcon/cphalcon/blob/master/phalcon/validation.zep#L573-L578) the following logic:

``` zephir
if validator->getOption("allowEmpty", false) {
    return empty this->getValue(singleField);
}
```

That means that additional sanitation needs to be performed in the method that eventually receives the validated data to make sure that invalid empty values are not present, simply because the data that results from the validator could look something like this (if `a` and `b` were posted as `false`):

``` php
[
    "a": false,
    "b": false,
]
```

In other words, it doesn't matter what other validators are attached to those fields, they'll happily "validate" if they're empty in any shape or form.
## Suggested solution

[Apigility](https://apigility.org/) solves this issue by having three options for each field:
- Required
- Allow empty
- Continue if empty

The first one is essentially the same as Phalcon's `PresenceOf` validator, and Apigility actually internally creates a very similar `NotEmpty` validator if `required` is set to `true`.

Allow empty is, yet again, an option that we luckily already have in Phalcon - it allows empty values to be passed in without performing any validation.

What we're missing though is implementation of the latter "continue if empty" option, which in case of Apigility completely ignores any validation on the field if the option is disabled and the value being validated is empty. In their [own words](https://apigility.org/documentation/content-validation/validating):

> If you want validators to run even if the data is not present or is empty, toggle the "Continue if Empty" setting.

My suggestion is to implement a similar option in Phalcon too, which would allow users of validator classes to skip validation on fields completely if they are not present in the data, which currently isn't possible without using the `allowEmpty` option (which in its turn allows invalid (empty) values to be accepted).

Rather than doing the following as a workaround:

``` php
$validator->add('a', new Validator\Between([
    "minimum"    => 1,
    "maximum"    => 100,
    "allowEmpty" => true,
]));
```

(which actually allows users to pass in `0` as the value) I suggest use the following option instead:

``` php
$validator->add('a', new Validator\Between([
    "minimum"       => 1,
    "maximum"       => 100,
    "ignoreMissing" => true,
]));
```
## Potential implementation

The change would be relatively small to add support for this option (the code is probably incorrect, meant more as an example). We would need a new method in the `Phalcon\Validation` class to check if the data being validated contains the key:

``` zephir
// could potentially be public
protected function hasValue(string field)
{
    let values = this->_values;
    return values->hasKey(field);
}
```

The reason for using `hasKey()` is to only check if the actual key exists, it doesn't matter whether the value is empty or not.

Once that's done, modify the `preChecking()` method to take the new option into account:

``` diff
protected function preChecking(var field, <ValidatorInterface> validator) -> boolean
{
    var singleField;
    if typeof field == "array" {
        for singleField in field {
+           if validator->getOption("ignoreMissing", true) {
+               if !this->hasValue(singleField) {
+                   return true;
+               }
+           }

            if validator->getOption("allowEmpty", false) {
                if method_exists(validator, "isAllowEmpty") {
                    return validator->isAllowEmpty(this, singleField);
                }
                return empty this->getValue(singleField);
            }
        }
    }
    else {
+       if validator->getOption("ignoreMissing", true) {
+           if !this->hasValue(field) {
+               return true;
+           }
+       }

        if validator->getOption("allowEmpty", false) {
            if method_exists(validator, "isAllowEmpty") {
                return validator->isAllowEmpty(this, field);
            }
            return empty this->getValue(field);
        }
    }

    return false;
}
```

Hope this all makes sense!

**Comment by codeaid** [comment]
Just a quick idea - I'm personally not a fan of the name "ignoreMissing". It was the best I could come up at the time, but it probably doesn't semantically represent the state. Missing implies that the field is expected but for some reason is not present.

Maybe "ignoreAbsent" would be a better name (even though I've not really seen the word "absent" being used much in the programming world)? It could also be "skip" instead of "ignore", e.g. "skipMissing" or "skipAbsent".

**Comment by codeaid** [comment]
Any news on this, @sergeyklay?

**Comment by sergeyklay** [comment]
I'll try to sort out asap

**Comment by gguridi** [comment]
I think this would be better achievable if we update allowEmpty behaviour.

- allowEmtpy = true (this means that everything that evaluates to empty is ok)
- allowEmpty = ['', null] (this means that empty only means empty string and null, false and 0 won't evaluate as empty).

I've added a pull request with this change. The benefits are:
- Backwards compatible.
- Flexible, we can specify 'unknown', 'empty' or -1 as empty values in case we are using a shitty api.

An improvement also added in the pull request is that only if the allowEmpty validation is true the validation will stop there, in case of false it will continue with the next validators.

**Comment by Jurigag** [comment]
Very nice and good idea i think.

**Comment by codeaid** [comment]
Hi, Gorka! Thanks for the change! Much appreciated!

That's one half of the change though. What about the "ignore missing" flag that would allow us to skip validation altogether if the field is not present? I don't think "allowEmpty" on its own solves the problem.

E.g. in case of the PATCH request which doesn't require the client to send all fields, I can't see a way to ignore something that's not present at all. In current situation, I'd have to define "allowEmpty" as "[null]" for it to work, which would mean that clients would still be able to send "null" as the value of the field, which isn't good enough if I don't want to allow such values.

Hope that makes sense! See my original question for a more detailed explanation of the scenario though.

**Comment by wajdijurry** [comment]
+1
