### ISSUE TITLE
[bug] Model::query No Binding

### ISSUE THREAD

**Issue by escribiendocodigo** [phalcon/cphalcon#12104]
Hi,

When using query() method  bind in the parameters in PersonasModel no longer get a result.

### No Binding

> **It is returning SQL WHERE unchanged**

> sql generated

```php

SELECT `personas`.`id`, `personas`.`codigo`, `personas`.`nombreCompleto`
FROM `personas`
WHERE (`personas`.`codigo` LIKE '%:q:%') OR (`personas`.`nombreCompleto` LIKE '%:q:%') 
ORDER BY `personas`.`nombreCompleto`

```
> Script to reproduce the issue

```php
$q = 'p4m';

$personas = Personas::query()
                    ->where("codigo LIKE '%:q:%'")
                    ->orWhere("nombreCompleto LIKE '%:q:%'")
                    ->orderBy('nombreCompleto')
                    ->bind(array(
                        'q' => $q
                        ))
                    ->execute();
```
### Details

* Phalcon version: 3.0.0
* PHP Version: 5.5.9
* Operating System: Elementary OS 0.3.2 Freya (Ubuntu 14.04)
* Installation type: installing via package manager
* Zephir version: 0.9.3a-dev-e716dbe641
* Server: Apache
* Database: MySQL

**Comment by Jurigag** [comment]
Try to :

```php
$q = '%p4m%';

$personas = Personas::query()
                    ->where("codigo LIKE :q:")
                    ->orWhere("nombreCompleto LIKE :q:")
                    ->orderBy('nombreCompleto')
                    ->bind(array(
                        'q' => $q
                        ))
                    ->execute();
```

**Comment by andresgutierrez** [comment]
It does not work like that, you have to use:

"Like :q:" and pass ['bind' => '%' . $q . '%']

The parser wouldn't be able to detect the placeholder if it is placed within a string
