### ISSUE TITLE
Version '2.0.*' for 'php5-phalcon' was not found

### ISSUE THREAD

**Issue by sunil-jhamnani** [phalcon/cphalcon#12114]
> Questions should go to https://forum.phalconphp.com

### Describe what you are trying to achieve and what goes wrong.
I have the command **_apt-get install -y php5-phalcon=2.0.*_** in my dockerfile to install phalcon. Earlier it was running fine but now its giving me this error.
I tried to upgrade the phalcon version to the latest one but this indeed is giving me the validation errors in the model class.

Is there any way I can use this version of phalcon? 

* Phalcon version: 2.0.*
* PHP Version: 5.5.*
* Operating System: Ubuntu
* Installation type: Installing via package manager
* Server: Nginx

**Comment by sergeyklay** [comment]
https://launchpad.net/~phalcon/+archive/ubuntu/stable/+build/9780005/+files/php5-phalcon_2.0.13-ppa1~trusty_i386.deb

https://launchpad.net/~phalcon/+archive/ubuntu/stable/+build/9780004/+files/php5-phalcon_2.0.13-ppa1~trusty_amd64.deb

**Comment by sunil-jhamnani** [comment]
Hi @sergeyklay,

What would be the command if I have to install it via apt-get from terminal?

**Comment by sunil-jhamnani** [comment]
So I used the combination of wget and dpkg command and it worked.

Thanks @sergeyklay
