### ISSUE TITLE
PHQL Advanced Binding - Transparent SQL

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#12117]
Parsing SQL is a little bit problematic approach. 

Tokenization as format string is better and generic approach but this way needs to have new syntax to tokenize table and fields. Also needs to have a registry of schemas and tables.

I implemented this approach in my own private framework. I can share my design if going to be implemented in Phalcon.

```
SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters
```

``` php
$query = 'UPDATE My\Models\Status SET valid = IF(id IN ({statuses:array}), 1, 0)';
$this->modelsManager->executeQuery($query, ['statuses' => [1,2,5,6,9]]);
```

```
Syntax error, unexpected EOF
```

``` php
$query = 'SELECT CONCAT(:firstName:, :lastName:) AS fullName';
$this->modelsManager->executeQuery($query, ['firstName' => 'Tuğrul', 'lastName' => 'Topuz']);
```
### Details
- Phalcon version: 2.0.13
- PHP Version: 5.6.24-0+deb8u1
- Operating System: Debian 8
- Installation type: Compiling from source
- Zephir version (if any): 0.9.2a-dev
- Server: Nginx

**Comment by sergeyklay** [comment]
@tugrul Could you please share the experience

**Comment by tugrul** [comment]
First step just tokenize extended SQL string, query schemas and models to registry using these tokens and replace tokens to regular table names using table and column maps.

## Registry

### DI Service: DB Connection
```php
public function initSharedMysql()
{
    $pdo = new \PDO('mysql:host=localhost;charset=utf8', 'phi', 'n0'); 
    return $pdo;
}
```

### DI Service: Model Manager
```php
public function initSqlModelManager()
{
    $sqlModelManager = new \Phino\Db\Sql\Model\Manager();
    $sqlModelManager->setConnection($this->di->get('mysql'));

    $sqlModelManager->addModelMap('sakila', new \App\Main\Models\Sakila());
    $sqlModelManager->addModelMap('mulkiIdari', new \App\Main\Models\MulkiIdari());

    return $sqlModelManager; 
}
```

### Model Map
```php
namespace App\Main\Models;

class Sakila extends \Phino\Db\Sql\Model\Map\MySql
{   
    public function initialize()
    {
        $this->setDbName('sakila');

        $this->addModel('actor', 'Actor')->setCursorClass('Cursor\Actor');
        $this->addModel('actorInfo', 'ActorInfo');
        $this->addModel('address', 'Address');
        $this->addModel('category', 'Category');
        $this->addModel('city', 'City');
        $this->addModel('country', 'Country');
        $this->addModel('customer', 'Customer');
        $this->addModel('customerList', 'CustomerList');
        $this->addModel('film', 'Film');
        $this->addModel('filmActor', 'FilmActor');
        $this->addModel('filmCategory', 'FilmCategory');
        $this->addModel('filmList', 'FilmList');
        $this->addModel('filmText', 'FilmText');
        $this->addModel('inventory', 'Inventory');
        $this->addModel('language', 'Language');
        $this->addModel('nicerSlowerFilmList', 'NicerSlowerFilmList');
        $this->addModel('payment', 'Payment');
        $this->addModel('rental', 'Rental');
        $this->addModel('salesFilmCategory', 'SalesFilmCategory');
        $this->addModel('salesStore', 'SalesStore');
        $this->addModel('staff', 'Staff');
        $this->addModel('staffList', 'StaffList');
        $this->addModel('store', 'Store'); 
    }
}
```

### Model
```php
namespace App\Main\Models\Sakila;

class Actor extends  \Phino\Db\Sql\Model
{
    protected static $source = 'actor';
    protected static $primaryKey = 'id';
    protected static $columnMap = array(
        'actor_id' => 'id',
        'first_name' => 'firstName',
        'last_name' => 'lastName',
        'last_update' => 'lastUpdate'
    );
    protected static $relations = array(
        'filmActor' => array(
            'source' => 'id',
            'entity' => 'filmActor',
            'target' => 'actorId'
        )
    );

    public $id;
    public $firstName;
    public $lastName;
    public $lastUpdate;

    public function getFullName()
    {
        return $this->firstName . ' ' . $this->lastName;
    }
}
```

## Tokenizer

Should not alternative of the SQL. Just extend to SQL transparently. There are 3 common element to format and map to models in SQL.

1. Model Names to Table Names
2. Model Field Names to Table Field Names
3. Wildcard

Every token should wrap with curly braces because curly braces are not special characters for SQL strings.

### Model Names to Table Names

Model Names should start with @ character and able to have schema names and aliases.

**Formats:**

```{@model}```
```{@model:alias}```
```{@schema.model}```
```{@schema.model:alias}```

**Samples:**

```{@actor}```
```{@actor:A}```
```{@sakila.actor}```
```{@sakila.actor:U}```

### Model Field Names to Table Field Names

**Formats:**

```{field}```
```{model.field}```
```{alias.field}```
```{field:alias}```
```{model.field:alias}```
```{alias.field:alias}```

**Samples:**

```{firstName}```
```{actor.firstName}```
```{U.firstName}```
```{firstName:FN}```
```{actor.firstName:FN}```
```{U.firstName:FN}```

### Wildcard

**Formats:**

```{*}```
```{model.*}```
```{alias.*}```

**Samples:**

```{*}```
```{actor.*}```
```{U.*}```

## Queries

```php
$sql = 'SELECT {*} FROM {@actor:A}';
//formatted internally to: 'SELECT * FROM `sakila`.`actor`'
$iterator = $this->sqlModelManager->sakila->query($sql);

// OR:
$sql = 'SELECT {*} FROM {@sakila.actor:A}';
//formatted internally to: 'SELECT * FROM `sakila`.`actor`'
$iterator = $this->sqlModelManager->query($sql);


$sql = 'SELECT {*} FROM {@actor:A} INNER JOIN {@filmActor:F} ON {A.id} = {F.actorId}';
//formatted internally to: 'SELECT * FROM `sakila`.`actor` `A` INNER JOIN `sakila`.`film_actor` `F` ON `A`.`id` = `F`.`actor_id`
$iterator = $this->sqlModelManager->sakila->query($sql);

$sql = 'SELECT {A.*} FROM {@sakila.actor:A} INNER JOIN {@sakila.filmActor:F} ON {A.id} = {F.actorId}';
//formatted internally to: 'SELECT `A`.* FROM `sakila`.`actor` `A` INNER JOIN `sakila`.`film_actor` `F` ON `A`.`id` = `F`.`actor_id`
$iterator = $this->sqlModelManager->query($sql);

$sql = 'UPDATE {@sakila.actor:A} INNER JOIN {@sakila.filmActor:F} ON {A.id} = {F.actorId} SET {F.filmId} = 5 WHERE {A.firstName} LIKE "%john%"';
$this->sqlModelManager->execute($sql);
```

## Handling Resultset
SQL tokenizer already has the state which models mapped to which tables and fields. PDO already has feature to fetch values to class `\PDO::FETCH_CLASS` . 

SQL tokenizer finds the model class for single table queries to set `\PDO::FETCH_CLASS` otherwise return `Phino\Db\Sql\Model\Compound` is handler to reverse lookup to prepare models and fills models' properties by tokenizer state.

So `PDOStatement::getColumnMeta` is not exact for aliased queries and it should be patched. https://github.com/facebook/hhvm/pull/7242
