### ISSUE TITLE
Missing docs / API on some Validators

### ISSUE THREAD

**Issue by igorsantos07** [phalcon/cphalcon#12120]
It seems there's a bunch of Validator classes that are not mentioned in [2.0](https://docs.phalconphp.com/en/2.0.0/reference/validation.html#validators) nor [3.0](https://docs.phalconphp.com/en/latest/reference/validation.html#validators) docs or [API listings](https://docs.phalconphp.com/en/2.0.0/api/index.html)... I found them because I thought they must exist and tried to auto-complete on PHPStorm using `phalcon-devtools`...

Examples:
- Date
- Alpha
- Alnum
- CreditCard
- Digit
- Identical
- File
- a bunch others

![screenshot_051](https://cloud.githubusercontent.com/assets/532299/17568371/da0b8b4c-5f19-11e6-8c58-33e90da7a929.jpg)

**Comment by sergeyklay** [comment]
The `Phalcon\Mvc\Model\Validation` is now deprecated in favor of `Phalcon\Validation`
The functionality of both components is merged into one, allowing us to reduce the codebase while offering the same functionality as before.

**Old way:**
```php
namespace Invo\Models;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Validator\Email as EmailValidator;
use Phalcon\Mvc\Model\Validator\Uniqueness as UniquenessValidator;

class Users extends Model
{
    public function validation()
    {
        $this->validate(
            new EmailValidator(
                [
                    'field' => 'email',
                ]
            )
        );

        $this->validate(
            new UniquenessValidator(
                [
                    'field'   => 'username',
                    'message' => 'Sorry, That username is already taken',
                ]
            )
        );

        if ($this->validationHasFailed() == true) {
            return false;
        }
    }
}
```

**New way:**
```php
namespace Invo\Models;

use Phalcon\Mvc\Model;
use Phalcon\Validation;
use Phalcon\Validation\Validator\Email as EmailValidator;
use Phalcon\Validation\Validator\Uniqueness as UniquenessValidator;

class Users extends Model
{
    public function validation()
    {
        $validator = new Validation();

        $validator->add(
            'email', //your field name
            new EmailValidator([
                'model' => $this,
                'message' => 'Please enter a correct email address'
            ])
        );

        $validator->add(
            'username',
            new UniquenessValidator([
                'model' => $this,
                'message' => 'Sorry, That username is already taken',
            ])
        );

        return $this->validate($validator);
    }
}
```

**Comment by igorsantos07** [comment]
Sorry @sergeyklay but it seems you didn't even read what I wrote. Deprecated or not, the documentation on a lot of validators **is still missing**, be it for 2.0 or 3.0.

Nonetheless, if 2.0 is going to be supported for some time, it must have documentation up there as well.

This is from 2.0 API Indice:
![screenshot_065](https://cloud.githubusercontent.com/assets/532299/17627599/2759451e-6088-11e6-970d-496ca4a1baac.jpg)

From 3.0 API Indice only the `Date` validator is missing. Is it missing or was that validator removed?

**Comment by sergeyklay** [comment]
>  it must have documentation up there as well

This is [docs](http://github.com/phalcon/docs) issue. Could you please create docs related issues in the appropriate repository?

**Comment by igorsantos07** [comment]
Oh well, I didn't know there was a separate repository for that. That doesn't seem to be pointed out in the docs page, neither in the project's readme / issue template. Thanks for pointing out, anyway.
