### ISSUE TITLE
Model validate Error

### ISSUE THREAD

**Issue by merlinyang521** [phalcon/cphalcon#12125]
> Questions should go to https://forum.phalconphp.com

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
Uncaught TypeError: Argument 1 passed to Phalcon\Mvc\Model::validate() must implement
 interface Phalcon\ValidationInterface, instance of Phalcon\Mvc\Model\Validator\Uniqueness given
```
> Provide minimal script to reproduce the issue

```php
$this->validate(new UniquenessValidator(
            array(
                'field'  => 'username',
                'message' => 'username error'
            )
 ));
```
### Details

* Phalcon version:3.0.0 
* PHP Version:7.0.4
* Operating System: Mac
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema):

**Comment by duythien** [comment]
Hello 

In Phalcon version3 validate in Phalcon\Mvc\Model\Validation is now deprecated in favor of Phalcon\Validation

You can see https://blog.phalconphp.com/post/phalcon-3-0-0-released
