### ISSUE TITLE
Error in Doc:  https://docs.phalconphp.com/en/latest/reference/di.html

### ISSUE THREAD

**Issue by xerron** [phalcon/cphalcon#12137]
In the page:

 https://docs.phalconphp.com/en/latest/reference/di.html

error:

![seleccion_090](https://cloud.githubusercontent.com/assets/1724033/17646973/166f5ef6-61a4-11e6-9ad2-df69b8bd83a7.png)

**Comment by sergeyklay** [comment]
Fixed in https://github.com/phalcon/docs/pull/856
