### ISSUE TITLE
Calling settype on model properties breaks the model

### ISSUE THREAD

**Issue by Paradoxis** [phalcon/cphalcon#12142]
I recently upgraded my PHP server to 7.0 and added type enforcements in lots of my classes. Using the built in model event `afterFetch()` I forced my model to automatically change the type of certain fields after fetching a record using the built in PHP `settype` function.

This however, caused all of my models to break when calling any `save()` functions on existing methods. This is an example of my code:

Example of my model:

```
class Books extends \Phalcon\Mvc\Model
{
    public $id;
    public $read;
    public $title;

    public function initialize()
    {
        $this->setSource('Books');
    }

    public function getSource()
    {
        return 'Books';
    }

    public function afterFetch()
    {
        settype($this->id, "int");
        settype($this->read, "bool");
    }
}
```

Using my code:

```
$book = Books::findFirst(10);
$book->save();

if ($messages = $book->getMessages())
{
    foreach($messages as $message)
    {
        echo "$message<br />";
    }
}
```

This results in the following output:

```
id is required
read is required
```

Writing the code like so does not cause any errors:

```
$this->id = (int) $this->id;
$this->read (bool) $this->read;
```

I'm currently using version 3.0.0.

**Comment by sergeyklay** [comment]
@Paradoxis  The 2.x branch is not longer supported. Could you please try the `3.0.x` branch or `master`?

**Comment by Paradoxis** [comment]
@sergeyklay Just upgraded to Phalcon 3.0.0, sadly the problem still persists

**Comment by Paradoxis** [comment]
@sergeyklay Tested on Phalcon 3.0.0, issue still persists

**Comment by sergeyklay** [comment]
**`phalcon.ini`**
```ini
[phalcon]
extension=phalcon.so
; allows casting hydrated attributes to the original types
; in the mapped tables instead of using strings
db.force_casting=On ; Off

; forces casting bound parameters to specified bind types
orm.cast_on_hydrate=On ; Off
```

Using that feature introduced in [2.0.4](https://github.com/phalcon/blog/blob/master/data/posts/2015/07/2015-07-07-phalcon-2-0-4-released.md) you don’t have to change types manually.
