### ISSUE TITLE
can't run HMVC phalcon

### ISSUE THREAD

**Issue by phongvt3110** [phalcon/cphalcon#12143]
hi everyone,i downloaded HMVC phalcon from github and i ran it but i get this error after i ran composer install --no-dev command,i ran successfully phalcon framework with no HMVC but i want to try HMVC . The error i got below

```
Phalcon\Mvc\Dispatcher\Exception: IndexController handler class cannot be loaded File=/var/www/PhalconHMVC/public/index.php Line=28
#0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('IndexController...', 2)
#1 [internal function]: Phalcon\Dispatcher->_dispatch()
#2 [internal function]: Phalcon\Dispatcher->dispatch()
#3 /var/www/PhalconHMVC/public/index.php(28): Phalcon\Mvc\Application->handle()
#4 {main}
```

Can anyone tell me how to fix this error or how to run HMVC phalcon , i don't know how to run Hello world HMVC phalcon . Thanks advance

**Comment by dreamsxin** [comment]
What phalcon version? Can run test
```shell
strace php index.php
```

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
