### ISSUE TITLE
[NFR] Module Facade

### ISSUE THREAD

**Issue by Mont4** [phalcon/cphalcon#12151]
I want have access to model in another module **without registering namespace** in current module. because i use different config in that module. i need sth similar to zend module facade.

I think it's very important that exist some things which make connection with another module.

**Comment by Jurigag** [comment]
I just don't uderstand how you want to do this without registering namespace ? What's the difference if phalcon will register it or not ?

**Comment by Mo121Montazeri** [comment]
facde is not just limitted to register model or controller,
and some how, it has a API alike structure for every module
