### ISSUE TITLE
[3.0] Gettext adapter constructor error

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#12157]
I got similar error like #11760:

> #0	Phalcon\Translate\Adapter\Gettext->prepareOptions(Array([locale] => pl_PL.UTF-8, [directory] => /var/www/xxx/www/apps/config/locale, [defaultDomain] => message))
#1	Phalcon\Translate\Adapter\Gettext->__construct(Array([locale] => pl_PL.UTF-8, [directory] => /var/www/xxx/www/apps/config/locale, [defaultDomain] => message))
#2	XXX\Plugins\Translation->__construct(Array([locale] => pl_PL.UTF-8, [directory] => /var/www/xxx/www/apps/config/locale, [defaultDomain] => message))
#3	Closure->{closure}()
#4	Phalcon\Di\Service->resolve(null, Object(Phalcon\Di\FactoryDefault))
#5	Phalcon\Di->get(translation, null)
#6	Phalcon\Di->getShared(translation)
#7	Phalcon\Di\Injectable->__get(translation)
#8	Modules\Company\Controllers\ControllerBase->initialize()
#9	Phalcon\Dispatcher->_dispatch()
#10	Phalcon\Dispatcher->dispatch()
#11	Phalcon\Mvc\Application->handle()

My code:
```
class Translation extends \Phalcon\Translate\Adapter\Gettext
{
    public function __construct(array $options)
    {
        parent::__construct($options);
        ...

}
```

### Details

* Phalcon version: 3.0.0
* PHP Version: 7.0.9
* Operating System: Ubuntu 14.04
* Installation type: Compiling from source
* Zephir version (if any): -
* Server: Apache

**Comment by sergeyklay** [comment]
Could you please provide Exception message?

**Comment by Zaszczyk** [comment]
Sure, I'm sorry.
`Error: Call to private method Phalcon\Translate\Adapter\Gettext::getoptionsdefault() from context 'FitCompany\Plugins\Translation'` 
in line:
`parent::__construct($options);`

**Comment by sergeyklay** [comment]
@Zaszczyk Could you please try test 3.0.x version?

**Comment by Zaszczyk** [comment]
I have Phalcon 3.0.0, so I've switched to branch 3.0.x
> git checkout 3.0.x

made git status:
> On branch 3.0.x
Your branch is up-to-date with 'origin/3.0.x'.

and run:
> sudo ./install
> service apache2 restart

I have still Phalcon 3.0.0 in phpinfo() after compilation, is it right? Because this error is still occurred. Should I upgrade Phalcon another way?

**Comment by Jurigag** [comment]
no, you need to use zephir

**Comment by sergeyklay** [comment]
@Zaszczyk For dev branches you have to use
```sh
zephir fullclean
zephir build --backend=ZendEngine3
```

**Comment by Jurigag** [comment]
This `--backend` is not needed, as far as i know it's only for generating c source for different php version than actual ?

**Comment by sergeyklay** [comment]
@Zaszczyk

**Comment by Zaszczyk** [comment]
@sergeyklay it works right with 3.0.x.
Little offtopic: what IDE do You use to developing cphalcon? I've installed Zephir plugin to PHPStorm and it looks good, but is there something better maybe?

**Comment by Jurigag** [comment]
Im using phpstorm and it's fine enough.

**Comment by sergeyklay** [comment]
PHPStorm + Zephir plugin
