### ISSUE TITLE
File Validation compatibility with Phalcon\Http\Request\File

### ISSUE THREAD

**Issue by skmail** [phalcon/cphalcon#12167]
Hello,

I think the way that File Validation "Phalcon\Validation\Validator\File"  need to be changed to work with Phalcon\Http\Request\File instances since the framework already make an instances of $_FILES  in the , 

In my opinion,  the File Validator is not responsible to work with external service Like HTTP Requests , as the validator  only validate Values, the File Validator must not check if the _SERVER is POST request , _FILES empty or not , we  can just pass a value that implements an interface like "Phalcon\Http\Request\FileInterface",  this may be  useful for unit testing to mock file instances, and the _SERVER['REQUEST_METHOD']  is not available in the CLI .

```
$data = $this->request->getPost();
foreach ($this->request->getUploadedFiles() as $uploadedFile) {           
    $data[$uploadedFile->getKey()] =  $uploadedFile;
}

if(!$form->isValid($data)){
   //validation error ....
}
```

What do you think?

Regards

**Comment by stamster** [comment]
Exactly. Such behaviour is odd. This validation needs to be self injectable. 
instead of: 
`$validator->validate($_FILES);`

it should accept reference to a files from `$this->request->getUploadedFiles()` object.

**Comment by juan-pinzon** [comment]
This was never solved, it should be possible to validate with the validator the files obtained through the method `$this->request->getUploadedFiles()`

**Comment by stamster** [comment]
Yeah, this one seems to be still present in such a dirty way. :/ We have to refactor it for 4.0 release.

**Comment by Jeckerson** [comment]
@sergeyklay @niden
