### ISSUE TITLE
Crash phalcon 3.0.0 on windows with php7.0.0

### ISSUE THREAD

**Issue by onexing** [phalcon/cphalcon#12168]
I try run my project https://github.com/onexing/xing-cms on windows 10 with phalcon 3.0.0 and php7.0.0 but phalcon is stuck WAMP. On linux (LAMP with php7.0.9) project works well. On windows with php5.6.16 and phalcon project works well too. I think here floating bug with phalcon 3.0.0 on windows and php7.0.0 because sometimes project runs.

apache error log:
[apache_error.txt](https://github.com/phalcon/cphalcon/files/437252/apache_error.txt)

**Comment by stamster** [comment]
Your best shot is to avoid using Windows and PHP 7 with Phalcon. Set up VirtualBox inside Windows and run GNU/Linux with or w/o PHP 7, as you like.

**Comment by andresgutierrez** [comment]
DLLs are compiled in 7.0.5 maybe you'll have to use a version higher or equals than 7.0.5

**Comment by virtueless** [comment]
Hello,
I'm using **Windows 10** with **WAMP 3.0.4** (64-bit), **PHP 7.0.4** and **Apache 2.4.18** are installed and I can run **Phalcon 3.0.0 - Windows x64 for PHP 7.0.0 (vc14)** so far without any crash.

**Comment by IsaacHub** [comment]
@virtueless  You said, no problems with wamp and php7
Is your PHP 7.0.4 **thread-safe(ts)** or **non-thread-safe(nts)** version ??
Is your Apache is running on **CGI/FastCGI** or **Apache2.0 Handler(mod_php)**  ??

Could you please post the screenshot of your `phpinfo()` ?
