### ISSUE TITLE
Volt partial problem along block

### ISSUE THREAD

**Issue by daison12006013** [phalcon/cphalcon#12169]
OS: Ubuntu
Versions: (phalcon) 2.0.7 / 3.0.0 / 3.0.1  |  (php) 5.6 / 7
Web Server: NginX

---

"layouts/main.volt":

``` volt
<html>
    <head>
        {{ partial("partials/facebook.meta") }}
        <title>{% block title %}{% endblock %}</title
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>
```

"partials/facebook.meta.volt":

``` volt
<meta property="og:title" content="{% block title %}{% endblock %}" />
```

"landing.volt":

``` volt
{% extends 'layouts/main.volt' %}

{% block title %}Welcome to Solid Layer{% endblock %}

{% block header %}
<link rel="stylesheet" href="/css/font-awesome.css">
<link rel="stylesheet" href="/css/console.css">
<link rel="stylesheet" href="/css/main.css">
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
<script type="text/javascript" src="/js/typed.min.js"></script>
<script type="text/javascript" src="/js/console.js"></script>
<script type="text/javascript">
{% endblock %}
```

I can't seem to fetch the `title` block inside the partial, I also encounter that once I called the same block in 1 volt template, it only shows that the first block is showing.

**Comment by stamster** [comment]
Post your Phalcon version, alongside PHP version, Web server and OS.

**Comment by Jurigag** [comment]
I have this too:
Phalcon 3.0.1
problem both on php 5.6 and 7
OS Ubuntu 14.04 and web server apache2.

**Comment by xueron** [comment]
+1
I meet this too.

block defined in a partial not works.
