### ISSUE TITLE
Diffrent volt partial() in php 5.6/7.0

### ISSUE THREAD

**Issue by FlexIDK** [phalcon/cphalcon#12176]
### Expected and Actual Behavior

In PHP 5.6

Volt: 
`partial("email/tag_open", {'type': 'p'})`  - `$type` is local  var
`{{ type }}` - not set
`partial("email/tag_open", {})` - `$type` inside - not set

In PHP 7

Volt: 
`partial("email/tag_open", {'type': 'p'})`  - $type is global  var
`{{ type }}` - last state set
`partial("email/tag_open", {})` - $type inside - last state set

### Details
- Phalcon version: 3.0.1
- PHP Version: 5.6.24-0+deb8u1 / 7.0.10-1~dotdeb+8.1
- Operating System: Debian 8.5
- Installation type: Compiling from source

### Refs
- https://github.com/phalcon/zephir/issues/1621

**Comment by andresgutierrez** [comment]
PHP 5 allowed us to create intermediate symbol tables per render, in php7 that is not possible, we have to research more about it.

**Comment by janisbizkovskis** [comment]
I would like to suggest this fixing ASAP, as this is braking all the partial system in the views. (quite important thing)

**Comment by challet** [comment]
It's also driving the [loop context](https://docs.phalconphp.com/en/3.0.0/reference/volt.html#loop-context) crazy :

```volt
{% for d in data %}
    {{ dump(loop.first) }} // true 
    // there is a {% for t in tags %} inside it
    {% include "header" with ['active': loop.first, 'tags': d.tags] %} 
    {{ dump(active) }} // true 
    {{ dump(loop.first) }} // false 
{% endfor %}
```

**Comment by jl91** [comment]
some news about it? someone knows  when it will be fixed? what branch ? or date? i've identified this problem in phalcon 3.0.0, but now i'm migrating to phalcon 3.0.3!

**Comment by Jurigag** [comment]
Im guessing if someone would know then he would do PR with fix. We have to wait until @andresgutierrez will do something about this.

**Comment by jellisii** [comment]
Can confirm this is still a problem, particularly the loop context that @challet referenced.  I can put together a test case if needed, as this is causing me headaches.

**Comment by janisbizkovskis** [comment]
Can confirm as now. (23.11.2017). Due to this issue cannot upgrade two of my projects to php 7+ :( Same behavior is with .phtml, so @sergeyklay `Volt` label can be removed, as it's affecting all kind of views.

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by kgrammer** [comment]
Can we get a status update regarding this issue?  Is it being addressed and if so, when might we expect a fix?

**Comment by thnoack** [comment]
With Phalcon 4 dropping PHP5 support, I believe this issue is becoming even more important. Is there any way one could possibly help to move this along?

**Comment by kgrammer** [comment]
Since this issue has not been fixed, I don't think it should have been closed by Mr. Stale Bot...

**Comment by zacek** [comment]
As the bug fixing can take some time, here is my workaround in the hope it helps someone: extend `\Phalcon\Mvc\View\Engine\Volt` and use it instead of the original class when creating voltService:

```
namespace My\Fix;

/*
 * This class is a workaround for a bug in zephir
 * Remove it when the bug is fixed, see https://github.com/phalcon/zephir/issues/1621
 */
class Volt extends \Phalcon\Mvc\View\Engine\Volt
{
    public function render($templatePath, $_params__, $_mustClean__ = false)
    {
        if ($_mustClean__) {
            ob_clean();
        }
        $compiler = $this->getCompiler();
        $compiler->compile($templatePath);
        $_compiledTemplatePath_ = $compiler->getCompiledTemplatePath();
        unset($compiler);
        unset($templatePath);

        if (is_array($_params__)) {
            foreach ($_params__ as $_key_ => $_value_) {
                $$_key_ = $_value_;
            }
        }
        require $_compiledTemplatePath_;
        if ($_mustClean__) {
            $this->_view->setContent(ob_get_contents());
        }
    }
}
```
The idea behind the fix is simple - I've just "copy-pasted" code from the zephir sources of the `Volt` class to PHP - in PHP it works as expected.

When the bux gets fixed simply replace `\My\Fix\Volt` with `\Phalcon\Mvc\View\Engine\Volt` and delete this class.

**Comment by kgrammer** [comment]
As I commented when Mr. Stale Bit attempted to close this issue last time, since this issue has not been fixed, I don't think it should have been closed by Mr. Stale Bot...

And with that said, when might we expect this issue to be addressed?

**Comment by niden** [comment]
Thank you @kgrammer 

As for when, not sure. I have a few issues I need to check first for this week and I will check this out soon. I have to identify first where it comes from and whether we need to make changes to Zephir.

**Comment by yesworld** [comment]
Unfortunately, @niden I have the same problem. #13551

**Comment by yesworld** [comment]
@niden, any news?

**Comment by niden** [comment]
@yesworld Sorry I haven't had time to check this out. I will try but it won't be until the end of next week till I have some free time.

**Comment by harrywebster** [comment]
Thanks @zacek that's a great little work-around until this issue is resolved!

**Comment by Jurigag** [comment]
Thanks to latest fixes to zephir I guess this will be soon fixed.

**Comment by sergeyklay** [comment]
I hope we managed to sort out with this issue finally here https://github.com/phalcon/cphalcon/pull/13606. All necessary changes are already in the appropriate branch. We will try to release the next version in the coming days.  Thank you for your patience, the report, and for helping us make Phalcon better.
