### ISSUE TITLE
[3.x][NFR] Phalcon\Mvc\Model\Validator\Uniqueness condition and param options

### ISSUE THREAD

**Issue by michanismus** [phalcon/cphalcon#12177]
Model uniqueness validation needs extra options for conditions and params.

Example: My table does have a flag field "deleted" and records with "deleted = 1" should be excluded from query.

At the moment it is impossible and the validation always throws an error.

**Comment by Jurigag** [comment]
But `Phalcon\Mvc\Model\Validator\Uniqueness` was dropped anyway in 3.x Use `Phalcon\Validator\Uniqueness `.

What you mean should dropped ? There is option `except` already.

**Comment by michanismus** [comment]
Oh, my fault. I am still using the old class...
