### ISSUE TITLE
running on docker has bug

### ISSUE THREAD

**Issue by yingshancool** [phalcon/cphalcon#12172]
```php
root@668c6f828294:/home/wwwroot/duoduo/public# gdb php -c core.34
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.
[New LWP 34]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php index.php'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007ff097683fe0 in zim_Phalcon_Mvc_Router_Route___construct () from /usr/local/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
(gdb)
```

### Details
I run my phalcon project on docker of centos system, but nginx always print 500 bad gateway, than i use gdb debug  "gdb php -c index.php". console print 

#0  0x00007ff097683fe0 in zim_Phalcon_Mvc_Router_Route___construct () from /usr/local/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so

why?
but, i running my local vmware soft is no problam!

I am a chinese firends!  pelease help me! thank you.

I use cloud Host vps.  alibaba.
but , I directly compile phalcon on cloud vps, too. no problam. why?
I use command pull of docker has problam.

[docker image](registry.cn-hangzhou.aliyuncs.com/technofiend_docker/docker-php5.6.24-phalcon2.1.xl)

`docker pull registry.cn-hangzhou.aliyuncs.com/technofiend_docker/docker-php5.6.24-phalcon2.1.x`

this is my docker image, php-fpm image

* Phalcon version:2.1.x OR 3.0 (`php --ri phalcon`)
* PHP Version: 5.6.24 OR 7.0(`php -v`)
* Operating System: centos 7
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
Write bt and post result from whole stacktrace. Where is script to reproduce error ?

**Comment by andresgutierrez** [comment]
It looks like the binary has an invalid instruction because it's running on a different processor where it was originally compiled.

Try compiling from ext/:

```
git clone https://github.com/phalcon/cphalcon
cd cphalcon/ext
sudo ./install
```

**Comment by yingshancool** [comment]
@andresgutierrez There may be, because my docker image compile on docker cloud.  base the php-5.4-fpm.
[this is docker file](https://github.com/yingshancool/docker-php5.6-phalcon3/blob/master/Dockerfile)

But I according to the above docker file documents, inside the VPS compile time is no problem.
pull images from cloud has problem.   strange.

It is CPU instruction set is not the same?Or x64 and x86 architecture.But I checked is 64

@Jurigag error script on index.php router object when instantiation.  but i running my pc is no error.  


thank you, brother

**Comment by nmapx** [comment]
@andresgutierrez @sergeyklay I have similar issue with v3.3.0 where building from /ext doesn't work. What else can I do?
