### ISSUE TITLE
beforeSave not fired 

### ISSUE THREAD

**Issue by Izopi4a** [phalcon/cphalcon#12180]
```
zephir init Test;
```

cat test/test.zep

```
namespace Test;

class Test extends \Phalcon\Mvc\Model {

    protected id { get, set };
    protected name { get, set };


    public function initialize(){
        this->setSource("koko");
    }

    public function beforeSave(){

        this->setName("yeaa");
    }
}
```
cat test.php
```
<?php

$di = new Phalcon\DI\FactoryDefault();

$di->setShared('db', function () {
    $connection = new Phalcon\Db\Adapter\Pdo\Mysql([
        'adapter'  => 'Mysql',
        'host'     => 'localhost',
        'port'     => 3306,
        'dbname'   => 'dbtest',
        'username' => 'root',
        'password' => 'whatever',
        'charset'  => 'utf8',
        'options'  => [
            PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'
        ]
    ]);

    return $connection;
});

$rec = new \Test\Test();

if ( false === $rec->save() ){

    var_dump($rec->getMessages());
}
```

```
CREATE TABLE `koko` (
  `id` int(11) NOT NULL,
  `name` varchar(222) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```

the result is :

```
/home/izopi4a/test/test.php:26:
array(1) {
  [0] =>
  class Phalcon\Mvc\Model\Message#33 (5) {
    protected $_type =>
    string(10) "PresenceOf"
    protected $_message =>
    string(16) "name is required"
    protected $_field =>
    string(4) "name"
    protected $_model =>
    NULL
    protected $_code =>
    int(0)
  }
}
```

### Details

* Phalcon version:  Version => 3.0.2 Build Date => Aug 29 2016 21:16:33
* PHP Version: 7.0.4
* Operating System: Ubuntu 14.04
* Installation type: Compiling from source
* Zephir version (if any): latest master
* Server: Apache
* Other related info (Database, table schema):  mysql 5.7

**Comment by Jurigag** [comment]
`beforeSave` is fired AFTER valiadtion, since validation didn't pass it's nof fired. User `beforeValidationOnSave`

**Comment by Izopi4a** [comment]
still the same with 

```
namespace Test;

class Test extends \Phalcon\Mvc\Model {
....
    protected id { get, set };
    protected name { get, set };
....

    public function initialize(){
        this->setSource("koko");
    }

    public function beforeValidationOnSave(){

        this->setName("yeaa");
    }
}

```

**Comment by Izopi4a** [comment]
aha ok, its `beforeValidationOnCreate` :D

thanks !

**Comment by Jurigag** [comment]
But beforeValidationOnSave should work too....

**Comment by Izopi4a** [comment]
no such event here 

https://docs.phalconphp.com/en/latest/reference/models.html#events-and-events-manager

or i cant see it ?

**Comment by Jurigag** [comment]
Oh beforeValidation then xD

**Comment by Izopi4a** [comment]
yea the same :D, yea actually i had no idea idea of those. I tough those are user specified validations.

I learned a valuable lesson today

**Comment by Jurigag** [comment]
https://docs.phalconphp.com/pl/latest/reference/models.html#disabling-enabling-features

**Comment by Izopi4a** [comment]
nah i think apps should work with everything enabled.  Especially when its something super simple. I dont like disabling things just because i dont know how to use them.  But you are right in some specific cases those things can be annoying and disabling them is the "right" thing to do.

Disabling features reminds me of some friends of mine who code with error_reporting 0 .....

**Comment by Jurigag** [comment]
I have always notNull validations disabled. I prefer to validate data myself, not have some magic stuff which can be added to messages.
