### ISSUE TITLE
Added controller and action but it is showing 404 error

### ISSUE THREAD

**Issue by rajeshdas-rp** [phalcon/cphalcon#12185]
Hi,
I am new in Phalcon so please guide me, I have download demo project and it's controller is working fine but when I am trying to add a new controller. It is showing 404 error.

URL: http://localhost/phalcon/invo/
Controller: IndexController.php
Code:
class IndexController extends ControllerBase
{
    public function initialize()
    {
        $this->tag->setTitle('Welcome');
        parent::initialize();
    }

    public function indexAction()
    {
       print "Test";
    }
}
Above code is working fine.

URL: http://localhost/phalcon/invo/
Controller: IndexController.php
Code:
class IndexController extends ControllerBase
{
    public function initialize()
    {
        $this->tag->setTitle('Welcome');
        parent::initialize();
    }

    public function indexAction()
    {
       print "Test";
    }
}
Above code is working fine. But bellow code is not working showing error 404. I have exactly make save as of above controller but it is not working. Can please anyone help me? 

URL: http://localhost/phalcon/invo/play
Controller: PlayController.php
Code:
class PlayController extends ControllerBase
{
    public function initialize()
    {
        $this->tag->setTitle('test');
        parent::initialize();
    }

    public function indexAction()
    {
     print "test";
    }
}

**Comment by Izopi4a** [comment]
for questions : https://forum.phalconphp.com/

check your apache/nginx config

**Comment by virtueless** [comment]
Hello,

I see you are doing the INVO tutorial. This one has a Security Plugin (located in app/plugins/SecurityPlugin.php) which allow you to control what the user has access to.

Add your PlayController in the plugin's public resources:

//Public area resources
$publicResources = array(
         'index'      => array('index'),
         'about'      => array('index'),
         'register'   => array('index'),
         'errors'     => array('show401', 'show404', 'show500'),
         'session'    => array('index', 'register', 'start', 'end'),
         'contact'    => array('index', 'send'),
         'play'       => array('index')
);

Then delete your browser's cookie/cache for this page, because the security is saved in a session to avoid loading it again later.

It should now work.

**Comment by rajeshdas-rp** [comment]
Hi,
I had added but as you say it is saved in session so I thin it was not opening. So now it is working fine.

Thanks for share your knowledge.
