### ISSUE TITLE
Model Validation cause PHP Fatal Error (Interface issues) [php-7.0.10, cphalcon-3.0.1]

### ISSUE THREAD

**Issue by C0DE8** [phalcon/cphalcon#12194]
### Expected Behavior
Using the old (Phalcon\Mvc\Model\Validator\*) or the new (Phalcon\Validation\Validator\*) validation variant, one of them should work.

**Both** validation variants in the model cause a PHP fatal error:

**Old (use Phalcon\Mvc\Model\Validator\Uniqueness):**
`Fatal error: Uncaught TypeError: Argument 1 passed to Phalcon\Mvc\Model::validate() must implement interface Phalcon\ValidationInterface, instance of Phalcon\Mvc\Model\Validator\Uniqueness given in /www/app/models/Robot.php on line 41`

**New (Phalcon\Validation\Validator\Uniqueness):**
`Fatal error: Uncaught TypeError: Argument 1 passed to Phalcon\Mvc\Model::validate() must implement interface Phalcon\ValidationInterface, instance of Phalcon\Validation\Validator\Uniqueness given in /www/app/models/Robot.php on line 41`

Database Table:
```sql
CREATE TABLE `robot` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(64) NOT NULL,
  `price` int(10) UNSIGNED NOT NULL,
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Model
```php
<?php

use Phalcon\Mvc\Model,
    Phalcon\Mvc\Model\Validator\Uniqueness       // old variant
//    Phalcon\Validation\Validator\Uniqueness    // new variant
;

/**
 * Class Robot
 */
class Robot extends Model
{
    /**
     * @var int
     */
    public $id;

    /**
     * @var string
     */
    public $name;

    /**
     * @var int
     */
    public $price;

    /**
     * @var int
     */
    public $status;

    /**
     * @return bool
     */
    public function validation()
    {
        $this->validate(
            new Uniqueness(
                array(
                    "field"   => "name",
                    "message" => "The robot name must be unique"
                )
            )
        );

        return $this->validationHasFailed() != true;
    }
}
```

The Controller:
```php
<?php

/**
 * Class IndexController
 */
class IndexController extends ControllerBase
{

    /**
     * index action
     */
    public function indexAction()
    {
        $robots         = new Robot;
        $robots->name   = 'foo';
        $robots->price  = 150;
        $robots->status = 1;

        $result = $robots->save();

        var_dump($result);

        if (!$result) {
            var_dump($robots->getMessages());
        }
    }

}
```

I'm using the phalcon/skeleton-single (https://github.com/phalcon/skeleton-single) for this small test. I browse the phalcon stubs for IDE (https://github.com/phalcon/phalcon-devtools/tree/master/ide/stubs/Phalcon), I found out, that the requested interface: 

`Phalcon\ValidationInterface`

is **not** implemented by any of the \Phalcon\Validation\* classes, parent classes, abstract classes or other interfaces.
(maybe the stubs are not updated to phalcon 3.0.1)

The `\Phalcon\Validator` implements the `\Phalcon\Validation\ValidatorInterface` **not** the requested `Phalcon\ValidationInterface`.

### Details

* Phalcon version: 3.0.1
* PHP Version: 7.0.10-1~bpo8+1 (Pi 1 B; Armv6)
* Operating System: Raspbian (8.0)
* Installation type: Compiling from source 
* Zephir version (if any): ---
* Server: Nginx 1.9.10
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
Don't use `Phalcon\Mvc\Model\Validator` at all. Check blog post how to use new validation - https://blog.phalconphp.com/post/phalcon-3-0-0-released Basically your code needs to be:

```php
public function validation()
    {
        $validation = new \Phalcon\Validation();
        $validation->add('name', new Uniquqness([
            'message' => "The robot name must be unique"
        ]);
        return $this->validate($validation);
    }
```

**Comment by C0DE8** [comment]
@Jurigag Thanks for fast response.
I just use the phalcon doc (https://docs.phalconphp.com/en/latest/reference/models.html#Validating Data Integrity), but your code works! THX
