### ISSUE TITLE
getRealSQLStatement and getSQLStatement has no differences

### ISSUE THREAD

**Issue by zhangkx666** [phalcon/cphalcon#12196]
the source is below.
[cphalcon/phalcon/db/adapter.zep](https://github.com/phalcon/cphalcon/blob/5372ac7972218b10fd9f08027a7718ea10f191b5/phalcon/db/adapter.zep)

```zep
/**
 * Active SQL statement in the object
 */
public function getSQLStatement() -> string
{
    return this->_sqlStatement;
}

/**
 * Active SQL statement in the object without replace bound paramters
 */
public function getRealSQLStatement() -> string
{
    return this->_sqlStatement;
}
```

**Comment by Jurigag** [comment]
There is no way to return sql statement with replaced bound parameters in PDO. Other than replace them "by hand".

**Comment by Jurigag** [comment]
I think this could be possibly new feature, it can be done on for 3.2.0. I mean both methods return at this moment the same thing. I thing reql sql statement should return sql statement with bound parameters.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14720
