### ISSUE TITLE
Volt's command "is defined" doesn't work properly with nested structure

### ISSUE THREAD

**Issue by dmytrechko** [phalcon/cphalcon#12204]
### Expected and Actual Behavior

Model **_User**_ has property 'data' which is JSON. I wrote getter for 'data' and it work good, when I call it directly, but when I tried to check if such property exists, volt return `false`
**_Example:**_

``` php
{{ $user->data->address->street }} // display 'Harley street';

{{ $user->data->address->street is defined }} // false
{{ $user->data->address->street is empty }} // true
```

> Provide minimal script to reproduce the issue

``` php
class User extends Model
{
     //COLUMNS
    public $id;
    public $first_name;
    public $last_name;
    protected $data;
    //END COLUMNS

    protected $_db_table = 'users';

    /**
     * Method that initialized before all others
     */
    public function initialize()
    {
        parent::initialize();
    }

    public function getData()
    {
        return json_decode($this->data, true);
    }

    public function setData($data)
    {
        $this->data = $data ? json_encode($data) : $this->getRawValue('default');
    }

}
```
### Details
- Phalcon version: 3.0.0
- PHP Version: 7.0.9 (the same issue with 5.6.23 and Phalcon 3.0.0)
- Operating System: Linux
- Installation type: Compiling from source || installing via package manager (doesn't matter)
- Zephir version (if any):
- Server:  Apache
- Other related info (Database, table schema): DB: PostgreSQL 9.5+

**Comment by andresgutierrez** [comment]
Can you check the php generated? Perhaps there is a clue of why is not working there
