### ISSUE TITLE
Defining a SEPARATOR with PHQL for MySQL's GROUP_CONCAT()

### ISSUE THREAD

**Issue by dstuecken** [phalcon/cphalcon#12205]
### Expected and Actual Behavior

I am trying to create a subquery with PHQL. The Query looks like the following:

```sql
SELECT GROUP_CONCAT(title SEPARATOR ', ') FROM table) AS alias
```

Without specifying the SEPARATOR it works fine.

This is what i get:
```php
Syntax error, unexpected token IDENTIFIER(SEPARATOR), near to ' ', '
```

The query is generated like this:

```php
self::query()
   ->columns(
       [
           "(SELECT GROUP_CONCAT(title SEPARATOR ', ') FROM table) AS alias",
       ]
   )
   ->execute()
```
### Details

* Phalcon version: 3.0.0
* PHP Version: 5.6.2
* Operating System: Mac Os X 10.11
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Apache
* Other related info (Database, table schema): MySQL Database

**Comment by andresgutierrez** [comment]
It's a SQL extension that is not supported by PHQL, you can create a PHQL function to support it: https://blog.phalconphp.com/post/phalcon-2-0-3-released

**Comment by 3amprogrammer** [comment]
@andresgutierrez I wasn't able to find out how to make `SEPARATOR` working. I have came up with something like this:
```
$dialect->registerCustomFunction(
    'GROUP_CONCAT_NO_SEPARATOR',
    function($dialect, $expression) {
        $arguments = $expression['arguments'];
        return sprintf(
            " GROUP_CONCAT(%s SEPARATOR '')",
            $dialect->getSqlExpression($arguments[0])
        );
    }
);
```
That matches my needs but is not generic at all. Can you give me a hint how to make separator working?

**Comment by sergeyklay** [comment]
@3amprogrammer Create please a separated issue with code to reproduce.

**Comment by Jurigag** [comment]
SEPARATOR is not function, you would need to edit source i guess to make SEPARATOR thing recognized by parser.

**Comment by 3amprogrammer** [comment]
Goddammit, so I think I need to get along with my current solution. Thanks

**Comment by Jurigag** [comment]
Well actually i use something like:

```php
class GroupConcat implements DialectFunctionInterface
{
    /**
     * @return \Closure
     */
    public function getFunction()
    {
        return function (Dialect $dialect, $expression) {
            $arguments = $expression['arguments'];
            if(!empty($arguments[2])) {
                return sprintf(
                    " GROUP_CONCAT(DISTINCT %s SEPARATOR %s)",
                    $dialect->getSqlExpression($arguments[0]),
                    $dialect->getSqlExpression($arguments[1])
                );
            }

            if (!empty($arguments[1])) {
                return sprintf(
                    " GROUP_CONCAT(%s SEPARATOR %s)",
                    $dialect->getSqlExpression($arguments[0]),
                    $dialect->getSqlExpression($arguments[1])
                );
            }

            return sprintf(
                " GROUP_CONCAT(%s)",
                $dialect->getSqlExpression($arguments[0])
            );
        };
    }
}
```

GROUP_CONCAT(column, ';', 1) means to seperate distinct results by `;`, GROUP_CONCAT(column, ';') just seperate by `;`

**Comment by maddanio** [comment]
hey, so how can I actually use this? where do I put this code to be able to use group_concat?
