### ISSUE TITLE
php-fpm SIGSEGV for cphalcon 3.0.1

### ISSUE THREAD

**Issue by sharptry** [phalcon/cphalcon#12208]
cphalcon: v3.0.1
php: 7.0.10
os: Centos7

php-fpm.log:
child 4372 exited on signal 11 (SIGSEGV) after 484.350438 seconds from start

issue:
```php
class A {
    public static function A1() {
        return B::B1();
    }
}

class B {
    public static function B1() {
        return C::C1();
    }
}

class C {
    public static function C1() {
        return D::D1();
    }
}

class D {
    public static function D1() {
        return 1;
    }
}

A::A1(); // when run this line will show 502 page, and log file is SIGSEGV。
```

It can not call mutil functions?

**Comment by Jurigag** [comment]
This means that there is probably crash dump file generated. Try to post backtrace from gdb:

https://bugs.php.net/bugs-generating-backtrace.php

**Comment by stamster** [comment]
I just tested your code with exactly the same PHP/Phalcon versions. There was no crash. The line you pointed out returns 1.
I can `echo A::A1();`

**Comment by Jurigag** [comment]
For me this should be closed, there are no phalcon calls so this is not phalcon framework related.
