### ISSUE TITLE
NFR: Support 'context' in Gettext (msgctxt)

### ISSUE THREAD

**Issue by xerron** [phalcon/cphalcon#12201]
``` text
# messages.po file (Croatian translation)

msgctxt "optionInForms"
msgid "yes"
msgstr "da"

msgctxt "confirmation"
msgid "yes"
msgstr "OK"
```

NFR, not affect old code if:

``` text
public string t (string $translateKey, [array $placeholders]) 
```

add:

``` text
public string t (string $translateKey, [array $placeholders], [string $context])
```

https://docs.phalconphp.com/en/latest/api/Phalcon_Translate_Adapter_Gettext.html

**Comment by Zaszczyk** [comment]
I already use PHP implementation, probably it will help You:
```
public function tWithContext($translateKey, array $placeholders = [], $context = null)
    {
        $contextString = "{$context}\004{$translateKey}";
        $translation = dcgettext('message', $contextString, LC_MESSAGES);
        if ($translation == $contextString) {
            return $this->_($translateKey, $placeholders);
        } else {
            if (count($translation) > 0) {
                $translation = $this->replacePlaceholders($translation, $placeholders);
            }
            return $translation;
        }
    }
```

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/zephir/issues/938

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by scrnjakovic** [comment]
The thing is that contexts are missing in phalcon's native implementation of gettext functions.

I made this for myself and decided sharing it https://github.com/scrnjakovic/php-gettext-context

Include file via loader and don't forget to hook into volt.

TIP: You can use twig extractors for Volt, as you will rarely find a good Volt extractor.
