### ISSUE TITLE
MariaDB dynamic columns and Phalcon

### ISSUE THREAD

**Issue by nask0** [phalcon/cphalcon#12212]
Hi there, 
i just noticed that there is no obvious way to insert [MariaDB dynamic columns](https://mariadb.com/kb/en/mariadb/dynamic-columns/) with Phalcon.
The ways to do is to execute raw sql query, but i don't wanna take care of bindings and so on.
Obviously this will not work:

``` php
$query = 'INSERT INTO SomeModel ( name, subject, message, parameters, created_at, updated_at ) VALUES (:name:, :subject:, :message:, :parameters:, :created_at:, :updated_at: )';
$this->getDI()->get( 'modelsManager' )->executeQuery( $query, [
    'name' => 'Name',
    'subject' => 'Subject',
    'parameters' => 'COLUMN_CREATE(\'key\', \'value\')',
    'message' => 'Just some message',
    'created_at' => '...',
    'updated_at' => '...',
]);
```

**Comment by Jurigag** [comment]
Obviously as mariadb is drop-in replacement for mysql this is why it works out-of-box with phalcon. But OBVIOUSLY any new features which mariadb is adding itself won't work because there is no OFFICIAL phalcon support for mariadb.

**Comment by nask0** [comment]
@Jurigag OBVIOUSLY thanks for response. 
Just don' t get whats yelling for, but ok, thanks :)

**Comment by Jurigag** [comment]
Well i understood your issue as yelling that's why it's not working. You should just create it as [NFR] with mariadb support.

**Comment by nask0** [comment]
@Jurigag i understand,  sorry it's my bad then, idk for [NFR] requests.
I will gonna create MariaDB adapter as it is highly deployed nowadays as drop in replacement for mysql (as you said) from various Linux distro's and i simply love those "new features". 
I will contact you if i have any further questions regarding developing of this adapter, thanks.

**Comment by stamster** [comment]
Yeah, our new projects from 2014+ are all based on MariaDB. So it is quite popular.

Native Phalcon support would be much appreciated, and we all should work on it.

**Comment by dschissler** [comment]
Well this probably could be started as a dialect extension in the Incubator repo/package.
