### ISSUE TITLE
Hashtag/Anchor text of url not removed on response redirect

### ISSUE THREAD

**Issue by CreaoticX** [phalcon/cphalcon#12211]
### Expected and Actual Behavior

I'm trying do a redirect following a login from Facebook.  Facebook for whatever reason has taken to appending `#_=_` to the callback URL.  After I process the response from Facebook, I do a redirect to the account page to remove all the query parameters.  However the  `#_=_`  remains after the redirect.  i.e. the url looks like this:
     http://www.example.com/startlocation/?foo=bar#_=_
and after redirect becomes
     http://www.example.com/redirectlocation/#_=_
In doing a redirect, I would expect all parameters, anchor text, etc. to be removed i.e.
     http://www.example.com/startlocation/?foo=bar#_=_
after redirect becomes
     http://www.example.com/redirectlocation/

### Minimal script to reproduce the issue

```php
class IndexController extends Controller{
    function testAction(){
                $this->response->redirect();
    }
}
```
Add the above code and then go to the `test` url depending on how your routes are setup with `#whatever` added to the end.
    http://www.example.com/index/test/#whatever
and you should be redirected to
    http://www.example.com/#whatever
### Details

* Phalcon version: 3.0.1
* PHP Version: 7.0.8
* Operating System: Ubuntu 16.04
* Installation type: Compiling from source 
* Server:  Apache

**Comment by sergeyklay** [comment]
@CreaoticX 
The 2.1.x branch is not longer supported.  Could you please check 3.0.x branch?

**Comment by CreaoticX** [comment]
So funny thing.  When I went to install Phalcon not more than a couple weeks ago, the only directions I found that were supposed to work with php 7 were for that test build.  Then when you said check the 3.0.x branch I found the install directions for Phalcon 3.0.1 on PHP 7 on the Phalcon site in all of about three seconds.  So I have now updated.  I will edit the Phalcon version above and I did a `php --ri phalcon` just to positively confirm that it was upgraded.  However, the problem is still there.  I just tested it again with the code I supplied and it worked exactly as I described it.

I should also add that I tested it with `$this->response->redirect('http://www.example.com/',TRUE);` which I believe is supposed to tell Phalcon that it's an external site and same result.  And then just to really try it out I tested  `$this->response->redirect('http://google.com/',TRUE);` and was sent to `http://google.com#whatever`.

**Comment by stamster** [comment]
Part after the sharp sign `#` is actually non-standard HTTP thingie. Response will treat it as-is, as it was part of the name of the domain or your URL `site.com/some/pretty/url/page.html`. HTTP does not treat hashtags in any way, that's why you have it there after the redirect. If you really want to get rid of it, you'll need to use pregmatch or similar and to ditch it that way.
In any case, hashtags should not cause you any issues with redirects.

**Comment by CreaoticX** [comment]
@stamster yes I fully understand your point that for all intents and purposes unless you happen to be redirecting to a page with the same anchor text or some other code that directly pulls data from the url this will not break anything.  It's just kind of obnoxious, and I would have just cleaned it myself, but I couldn't find where to do this.

However, your comments led me to do some more testing which led to some more research which led me to this http://stackoverflow.com/a/2305927/2122187.  This is apparently not a bug in Phalcon after all, but a bug in the standards.  It led me to the imperfect fix of just adding an empty `#` to the end of my redirect so now it just has a `#` instead of `#_=_`.  Thanks for the help and I'll close this since there's nothing to be done here to fix it.  Hope this thread helps someone else that runs into the problem.
