### ISSUE TITLE
Model Bug

### ISSUE THREAD

**Issue by bestirani2** [phalcon/cphalcon#12224]
Hi

After find in a model, I call count but it returns null
For example
`
$items=Employee::find(['limit'=>20, 'offset'=>20]);
$count=Employee::count();
`
This problem is because of wrong binding. This query is for count. it used bind of previous query.
`
SELECT COUNT(*) AS `rowcount` FROM `employee` LIMIT :APL0 OFFSET :APL1
`

**Comment by andresgutierrez** [comment]
What version of Phalcon are you using?

**Comment by bestirani2** [comment]
3.0.1
