### ISSUE TITLE
Cssmin provide wrong output

### ISSUE THREAD

**Issue by R3bm3v0N** [phalcon/cphalcon#12222]
I found a bug in Phalcon version 3.0.1
This code:
`/*! comment */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}`

Was transformed to
`tml{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}`

Not only the comment but aslo the **h** character from code was removed .
Please check, thank you!

**Comment by tembem** [comment]
@R3bm3v0N Cssmin will remove the comment by design. Adding "space" will solve this bug i think:

```
/*! comment */ html{font-family:sans-serif;}
```

Looking to the code, i guessed this line  `parser->style_pointer += 2;`
https://github.com/phalcon/cphalcon/blob/master/ext/phalcon/assets/filters/cssminifier.c#L232

**Comment by R3bm3v0N** [comment]
@tembem I have add a space as you said and its work like a charm, thank you very much.
But i think it still be a temporary solution and need to be fixed in the future, thanks again ^_^
