### ISSUE TITLE
Set variable from a block content (twig-like set/endset syntax)

### ISSUE THREAD

**Issue by aleksanderd** [phalcon/cphalcon#12239]
Hello!

Base question: https://forum.phalconphp.com/discussion/13739/volt-setting-variable-from-a-block-like-twigs-setendset-syntax-e

Why not to implement something like:
```twig
{% set foo %}
    <div id="pagination">
        ...
    </div>
{% endset %}
```
// found at http://twig.sensiolabs.org/doc/tags/set.html

Thank you!

**Comment by sergeyklay** [comment]
How about macro?
```volt
{%- macro error_messages(message, field, type) %}
    <div>
        <span class="error-type">{{ type }}</span>
        <span class="error-field">{{ field }}</span>
        <span class="error-message">{{ message }}</span>
    </div>
{%- endmacro %}

{# Call the macro #}
{{ error_messages('type': 'Invalid', 'message': 'The name is invalid', 'field': 'name') }}
```

**Comment by aleksanderd** [comment]
thnx! but I need exactly a var with content of a block. this var will be passed as array to some function

**Comment by Jurigag** [comment]
To function in volt ? I don't quite understand....

**Comment by aleksanderd** [comment]
I extended Form to have a method to render field with unified app's markup. The method can accept optionally some addons to label, etc, as parameters. So such string is not too huge, like 1-3 simple tags, but it is enought to make using {%set var = '...' %} not too comfy

**Comment by Jurigag** [comment]
I would just define this var using `$this->view->setVar` in controller or whatever.

**Comment by aleksanderd** [comment]
it can be solved ofcos, not critical :) currently, I using sub template + getPartial

but It would be nice to have extended syntax for this, if not too hard to implemet ofcos ;) 

thank you!
