### ISSUE TITLE
Catchable fatal error: session_regenerate_id()

### ISSUE THREAD

**Issue by al35mm** [phalcon/cphalcon#12234]
Using Phalcon 3.0.1 (via packagecloud), PHP 7.0.8/apache2 and php-redis (installed via apt) running on Ubuntu Xenial on vagrant machine, when doing `$this->session->regenerateId()` I get the following "Catchable fatal error: session_regenerate_id(): Failed to create(read) session ID: user (path: /tmp)".

In my bootstrap

```
$session = new \Phalcon\Session\Adapter\Redis(array(
            'uniqueId'   => $config->options['uniqueId'],
            'host'       => $config->options['host'],
            'port'       => $config->options['port'],
            'index'      => $config->options['index'],
            'persistent' => $config->options['persistent'],
            'lifetime'   => $config->options['lifetime'],
            'prefix'     => $config->options['prefix'],
            'statsKey'   => $config->options['statsKey']
        ));
        $session->start();
        return $session;
```

Sessions seem to be working fine apart from 'regenerateId'.  The same app has no issues running on Phalcon 2.x and PHP 5.x.

I'm not sure if this issue is related to php-redis or Phalcon redis adapter, or something else!

**Comment by Jurigag** [comment]
Isn't thix fixed in 3.0.x ?

**Comment by al35mm** [comment]
@Jurigag was this previously a problem in Phalcon's redis adaptor? If so I guess it hasn't been fixed. I suppose I may have to drop back to Phalcon 2.x and php5.x to continue development for now as it's unusable in current state :(

**Comment by Jurigag** [comment]
Well, you can always use other session adapter like libmemcached for example.

**Comment by al35mm** [comment]
Yes I could do, but I want to use redis :) I have looked but can not find any other issues on this problem with Phalcon. So I'm not sure if it's a Phalcon issue or something else.
