### ISSUE TITLE
Better return types for find() calls and similar

### ISSUE THREAD

**Issue by igorsantos07** [phalcon/cphalcon#12247]
### Expected and Actual Behavior

Have IDEs and inspection tools correctly recognize the return values from `Model::find()` calls and similar.

Currently, what's returned from those methods is documented as an instance of `ResultsetInterface`, what asks just for basic methods. When we use things like `sizeof()`, `->count()`, try to loop through the query result or access it as an array, we get inspection errors. All those features are implemented on the child class, `Resultset`, and it seems to be the only object that implements said interface - and what's actually returned from the `find()` calls. 

I wonder if the interface could get more powerful, implementing a couple of the interfaces that are used by `Resultset` (like `Countable`, `ArrayAccess`, that provide those features I mentioned), or even if `find()` could be documented to return `Resultset` instead (or `Resultset|ResultsetInterface`).
### Details

![selecao_383](https://cloud.githubusercontent.com/assets/532299/18736168/e11b6f94-805a-11e6-8324-3fe36cf76b8c.png)
- Phalcon version: 2.0.11
- PHP Version: 5.6.21
- Other related info (Database, table schema): PHPStorm?

**Comment by sergeyklay** [comment]
```php
/** @var array|\Countable $previousEvent */
$previousEvent = PassiveEvents::find([...]);
```

**Comment by gguridi** [comment]
Phalcon is a compiled framework, written in zephir, there is no PHPDocs that IDEs can follow to determine the return types, etc.

The only way would be to create stubs for the IDEs, but that's a huge amount of work for this small community. If someone can start a stub for JetBrains (for example) then it's possible to port to another IDE easily:
https://github.com/JetBrains/phpstorm-stubs/tree/master/standard

The option given by @sergeyklay is more realistic right now :)

**Comment by Jurigag** [comment]
Other option is some phpstorm plugin which will figure out class.

29.12.2016 6:15 PM "Gorka Guridi" <notifications@github.com> napisał(a):

**Comment by igorsantos07** [comment]
What's suggested by @sergeyklay seems like quite a dirty workaround something that should be provided by the framework correctly. Even more, if you think that's quite a common operation, and having to fix the return type-hint is... odd. It should return the correct type in the first place, right?

About the stubs mentioned, there's actually a project that does that - and it extracts its data from the framework itself. As can be seen [here](https://github.com/phalcon/phalcon-devtools/blob/master/ide/stubs/Phalcon/mvc/Model.php#L433), the generated stub points out to the incomplete data I mentioned in the original report - and it, indeed, [points out to the same info on the .zep file](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L797).

That said, I repeat my other suggestion: make `ResultsetInterface` also implement `Countable`, `ArrayAccess` and the like, so we get proper code completion and type-hints.  
On a side note: what's exactly the idea of having an interface for something unique as Resultset? Can that be replaced by some other class by a developer or a plugin of some sort?

**Comment by Jurigag** [comment]
Why you voting down my solution ? The same is happening for symfony 2 plugin for example. And most of people thinks it's very good.

**Comment by igorsantos07** [comment]
@Jurigag I don't think a plugin should be created to provide something the framework itself could easily do with proper coding/documentation - actually, that's the exact purpose of [Phalcon IDE Stubs](https://github.com/phalcon/phalcon-devtools/blob/master/ide/stubs/) (I think you could guess by the name), and I mentioned them in my last comment.

**Comment by sergeyklay** [comment]
Well, I think this is IDE/Stubs issue. Not related to the Phalcon code base.

**Comment by igorsantos07** [comment]
Sorry @sergeyklay, I'll have to disagree. The stubs are made based on Phalcon code, and there are explicit warnings there to not edit the stubs by hand. Thus, this fix would have to come from the Phalcon source itself - that's where the inconsistency on object hierarchy is, in the end.
Please, re-open it :)

**Comment by sergeyklay** [comment]
@igorsantos07 This is and Zephir (the `stubs` command) and probable Devtools (IDE/Stubs) issue, but not Phalcon.

**Comment by igorsantos07** [comment]
Again, those can only make output based on the Phalcon source, they can't do more than that.

As I pointed out in my first comment, the [root is in Phalcon's code](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L797).

**Comment by sergeyklay** [comment]
We can't modify `-> <ResultInterface>` part because this is compiler (not developer) hint. We can add `@return Something` but this may replaced by stubs generator (Zephir)

**Comment by igorsantos07** [comment]
But do you think `ResultInterface` could then implement the traditional PHP interfaces such as `ArrayAccess` and `Countable`? This tells PHP we can use the results as an ordinary array, and not only as an object :)

**Comment by sergeyklay** [comment]
In fact, we have 660 opened issue. Including support of PHP 7.1, PSR-7, etc. I think that most likely it will be implemented after you will lose interest in this project (as often happens)

**Comment by igorsantos07** [comment]
hahaha I know how it works :(
But you never know when a new developer could jump around, eager to get to know the codebase, and gets this as an easy one. I'm the one requesting but I doubt I would be the only one to benefit :)
Thanks for understanding the issue anyway.
