### ISSUE TITLE
NFR: Add module name to module class name format in Application::registerModules

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#12252]
Currently Phalcon module setup is a bit hacky because there is some overlap of concerns between the Loader and Application and modules.  The Application class has been doing a [poor man's loading](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L227-L235) to get the module definitions loaded up when the normal Loader class is fully capable of being used with the `Loader::registerClasses` method.

Currently if one wants to use the more correct approach then the following format must be used:

``` php
$application = new Application($di);
$application->registerModules([
    'org'   => ['className' => 'Project\Modules\Org\Module'],
    'site'  => ['className' => 'Project\Modules\Site\Module'],
    'admin' => ['className' => 'Project\Modules\Admin\Module'],
    'api'   => ['className' => 'Project\Modules\Api\Module']
]);
```

I propose that this could be made to look like the following while maintaining BC with the semver 3 series.

``` php
$application = new Application($di);
$application->registerModules([
    'org'   => 'Project\Modules\Org\Module',
    'site'  => 'Project\Modules\Site\Module',
    'admin' => 'Project\Modules\Admin\Module',
    'api'   => 'Project\Modules\Api\Module'
]);
```

Then I propose that late into `3.*` series (1-2 years from now) that the `className => ...` format should throw a deprecation warning and then this format should be removed in the 4.0 series for a breaking change.

**Update** This is also possible:

``` php
$application = new Application($di);
$application->registerModules([
    'org'   => OrgModule::class,
    'site'  => SiteModule::class,
    'admin' => AdminModule::class,
    'api'   => Api::Module,
]);
```

**Comment by dschissler** [comment]
Maybe the issue title isn't so good?

**Comment by Jurigag** [comment]
Also what about adding option to load whole module on bootstraping ? Like execute `registerNamespaces` and `registerServices` always so certain module can be used across all modules ?

**Comment by dschissler** [comment]
I think that the router takes care of that.

**Comment by Jurigag** [comment]
Yea i know, but what if someone need such a feature ? Right now you need to do some nasty things like create module class on your own and call methods, or register namespaces from other module and set proper services in other module and such stuff.

**Comment by dschissler** [comment]
@Jurigag I'm not sure what you mean by this last comment.  You don't need to do those things if you setup your routes correctly and also assign the router a default module.

There are different interpretations of how modules should work and they are quite simple if you make the assumption and condition that only a single Module can be instantiated for each execution.  Someone a while ago made some sweet tech that didn't do this and some interesting things were possible by using multiple modules at once.  For the most part the only thing that I feel that I miss out on is being able to forward to another module-controller-action tuple and so I just redirect.  In practice that is only a small issue for me when it comes to making the sign in display without a redirect if it is in another module.

**Comment by dschissler** [comment]
I've taken up interest on this again.  I'm going to try to make it align with what I've learned working on my Perch framework.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
