### ISSUE TITLE
$validation->setFilters("name", "trim"); seems like not working

### ISSUE THREAD

**Issue by kunloon** [phalcon/cphalcon#12254]
here is my code:

```php
use Phalcon\Validation;
use Phalcon\Mvc\Model;
use Phalcon\Validation\Validator\PresenceOf;

class Category extends Model
{
    public function validation()
    {
        $validation = new Validation();
        $validation->add(['title', 'name'], new PresenceOf([
            'message' => [
                'title' => 'title is required',
                'name' => 'name is required'
            ]
        ]));

        $validation->setFilters("name", "trim");
        $validation->setFilters("title", "trim");

        return $this->validate($validation);
    }
```

my input is some blank sapce like title: '    ',  name: '  ',
then i set filters by using 
> $validation->setFilters("name", "trim");

but it sames not working. the validation still return true;
and if i use $this->title = trim($this->title);  before validation, the validation will return false.

**Comment by sergeyklay** [comment]
@Jurigag Could you please take a look?

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/validation.zep#L483 

Filters just totally ignored if entity is object i guess ?

**Comment by sergeyklay** [comment]
@kunloon 
Could you please check 3.0.x branch?

```sh
git clone git@github.com:phalcon/cphalcon.git
cd cphalcon
git checkout 3.0.x

zephir fullclean
zephir build
```

**Comment by sergeyklay** [comment]
@kunloon

**Comment by sergeyklay** [comment]
@kunloon Ping

**Comment by kunloon** [comment]
@sergeyklay sorry, i use it in windows, and i don't know how to build 3.0.x as dll.

**Comment by sergeyklay** [comment]
Well, I'm hope this issue is fixed. At least in 3.0.x branch. 
I'm closing this issue now but will open it again if the need arises

**Comment by Jurigag** [comment]
Well in tests it works, so.

**Comment by dellert** [comment]
it doesn't work

**Comment by Jurigag** [comment]
What phalcon version?

**Comment by dellert** [comment]
3.0.3

**Comment by Jurigag** [comment]
Then post code to reproduce.

**Comment by dellert** [comment]
`    public function validation()
    {
        $validator = new Validation();
        $validator->setFilters('field', 'trim');

        return $this->validate($validator);
    }`

This code doesn't work on data save. All data for property "field" save with whitespaces. Besides, I 
I tried creating self custom filter, it doesn't work too
