### ISSUE TITLE
Error: PostgresSQL create table default value for integer column 

### ISSUE THREAD

**Issue by Ridlsan** [phalcon/cphalcon#12267]
Phalcon 3.0.1

If setting default value 0 for integer column, phalcon escapes it as string and postgres complains as column "0" not exists. 

Change its behavior in https://github.com/phalcon/cphalcon/blob/master/phalcon/db/dialect/postgresql.zep#L382

Just add check - if INTEGER so not escape value. Phalcon already has check for BOOLEAN

```zephir
		if column->hasDefault() {
				let defaultValue = column->getDefault();
				if memstr(strtoupper(columnDefinition), "BOOLEAN") {
					let sql .= " DEFAULT " . (defaultValue ? "true" : "false");
				} elseif memstr(strtoupper(defaultValue), "CURRENT_TIMESTAMP") {
					let columnLine .= " DEFAULT CURRENT_TIMESTAMP";
				} else {
					let columnLine .= " DEFAULT \"" . addcslashes(defaultValue, "\"") . "\"";
				}
		}
```

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/phalcon-devtools/issues/859
I'll fix it ASAP.

**Comment by sergeyklay** [comment]
Fixed. You have to update Phalcon from the `3.0.x` branch:

```sh
git clone git@github.com:phalcon/cphalcon.git
cd cphalcon
git checkout 3.0.x

zephir fullclean
zephir build
```
