### ISSUE TITLE
Call Model::afterFetch() on Model::refresh()

### ISSUE THREAD

**Issue by alexbusu** [phalcon/cphalcon#12260]
When I query for a Model entry in DB, the `afterFetch()` is automatically called, ensuring model data initialisation (time string to DateTime, comma-separated list to array, etc). This behaviour don't automatically happen when the model is refreshed.

Consider the following code:

``` php
class User extends Phalcon\Mvc\Model
{
    public $permissions = null;

    public function afterFetch()
    {
        $this->permissions = explode(',', $this->permissions);
    }
}

$user = User::findFirst(1);
// [...] (maybe outside) user details update, so
$user->refresh(); // `afterFetch` is not called on User model
// my User update of details [...]
$user->save(); // at this step, the `beforeSave` method will be called, but I'll have the `permissions` model property as string, and not as an expected array
```

I think the `Model::afterFetch()` _should be_ called on `Model::refresh()` as well.
### Other details
- Phalcon version: 3.0.1
- https://docs.phalconphp.com/uk/latest/reference/models.html#initializing-preparing-fetched-records

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/issues/12220 duplicated
