### ISSUE TITLE
isAllowed produces different return type than Acl:ALLOWED

### ISSUE THREAD

**Issue by cbichis** [phalcon/cphalcon#12268]
Hi,

INVO is comparing type strict isAllowed with Acl::ALLOW.

Unfortunately one uses boolean and the other one uses int...

I think this is not an INVO issue but rather a problem on Phalcon\Acl.

**Comment by Jurigag** [comment]
Well, im guessing we could just change here:

https://github.com/phalcon/cphalcon/blob/master/phalcon/acl.zep#L71
https://github.com/phalcon/cphalcon/blob/master/phalcon/acl.zep#L73

to true/false, it shouldn't cause a problem. But what if someone currently is comparing in his app like:
`=== Acl::ALLOW`

Then his app will break, so this is pretty much 4.0.0 change.

**Comment by cbichis** [comment]
At least the INVOI documentation should be updated meantime. I spent close to 1 hour trying to figure out whats wrong with my ACL... Was nothing wrong with the ACL, just with that condition...

**Comment by SidRoberts** [comment]
isAllowed() should return a Boolean because were effectively asking a question: is this allowed - yes or no? (I was the one who made this change in #3311. Before, the method returned integers and booleans - it was crazy). I'll update the documentation in the morning.
