### ISSUE TITLE
Assets Manager hard reference to \Phalcon\Tag, should use DI

### ISSUE THREAD

**Issue by kristofferingemansson** [phalcon/cphalcon#12261]
Assets Manager has hard reference to \Phalcon\Tag when generating HTML.
Assets Manager should fetch tag instance from dependency injector instead to allow custom behavior.

``` php
class MyTag extends \Phalcon\Tag
{
    public static function stylesheetLink($parameters = null, $local = true)
    {
        die('bar');
    }
}

$di = new \Phalcon\Di\FactoryDefault();
$di->setShared('tag', MyTag::class);

/** @var \Phalcon\Assets\Manager $manager */
$manager = $di->get('assets');
$manager->addCss('test.css');
$manager->outputCss();
```

Actual

``` php
<link rel="stylesheet" type="text/css" href="/test.css" />
```

Expected

``` php
bar
```

https://github.com/phalcon/cphalcon/blob/v3.0.1/phalcon/assets/manager.zep#L775
https://github.com/phalcon/cphalcon/blob/v3.0.1/phalcon/assets/manager.zep#L811 (same for JavaScript)
### Details
- Phalcon version: 3.0.1
- PHP Version: 5.5.24
- Operating System: Windows 7
- Installation type: xampp

**Comment by Jurigag** [comment]
If it's 3.1.0 then if service called tag doesn't exist it should still use Tag class in static way.

**Comment by niden** [comment]
Implemented
