### ISSUE TITLE
One/global layout for all modules

### ISSUE THREAD

**Issue by cbichis** [phalcon/cphalcon#12270]
I see there is no way to set "global" layouts for multi-module setup. One single layout for all modules... I was needing to hack things with some includes.

I guess it would be interesting to have one more level of layouts, global app layouts (not just module/controller/action).

**Comment by cbichis** [comment]
This applies to main layout also (the one set with setMainView() ). I dont even see a way to change the path for this "layout". I can only set the file.

**Comment by Izopi4a** [comment]
for multi module app - no.
Its doable by your own but i am not sure its worth the while

**Comment by sergeyklay** [comment]
Of course it is possible in Phalcon. You just did not read carefully the documentation.

We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
