### ISSUE TITLE
Add ability to move a table to a different schema

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#12272]

**Comment by Ultimater** [comment]
If I understand this feature request correctly, I know in MySQL you can copy a table to another database using:
```
CREATE TABLE db2.table LIKE db1.table;
INSERT INTO db2.table SELECT * FROM db1.table;
```
Not sure about an all-encompassing PDO solution though.

**Comment by sergeyklay** [comment]
To move a table to a different schema in PostgreSql:
```sql
ALTER TABLE myschema.distributors SET SCHEMA yourschema;
```
