### ISSUE TITLE
[BUG] \Phalcon\Mvc\View - setLayout and pick

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#12273]
`\Phalcon\Mvc\View::setLayout()` has no effect when use with `\Phalcon\Mvc\View::pick()`

``` php
$view->setLayout('content/scope');
$view->pick('content/list');
```
### Details
- Phalcon version: 2.0.13
- PHP Version: 5.6.24-0+deb8u1
- Operating System: Debian 8.5 (linux)
- Zephir version:: 0.9.2a-dev
- Server: Nginx + PHP-FPM

**Comment by Jurigag** [comment]
2.0.13 version is no longer maintained and supported. Can you check 3.0.x branch ?

**Comment by tugrul** [comment]
3.0.x has too buggy with PHP 5.6. so many seg faults. I can't waste my time with 3.0.x

**Comment by Jurigag** [comment]
You can use php 7.

**Comment by tugrul** [comment]
@Jurigag it is not easy in corporate business. PHP 7 is too young and we can't deal other problems like other php module incompatibility or old codebase incompatibility

http://php.net/manual/en/migration70.incompatible.php

**Comment by Jurigag** [comment]
Too young ? It's almost 10 months men.

**Comment by sergeyklay** [comment]
@tugrul Could you please provide an example what exactly does not work for you with Phalcon 3.0.0 and PHP5?

**Comment by tugrul** [comment]
@sergeyklay published a branch on my invo fork `addText` and `addVideo` actions don't have layout output due to view pick. `addEvent` doesn't have problem without view pick.

**Comment by stamster** [comment]
I always use `pick()` method for such needs.

Looking at the behavior of both `setLayout()` and `pick()`, how they're suppose to work together in harmony, in other words what do you want to achieve?

```
Change the layout to be used instead of using the name of the latest controller name
    $this->view->setLayout('main');

Choose a different view to render instead of last-controller/last-action
         $this->view->pick("products/list");
```

**Comment by tugrul** [comment]
@stamster there is a shared layout on reporting pages like setting date range or kind of product. I needed to print report by different criteria on same table structure. Also table structure can be different by report. Table structure not same each report and i cant put in same view filtering header and table structure in same view file.

You were right if i made simple blog application xD

I can achieve this with duplicate of table structure to action's view file but it's dirty.
