### ISSUE TITLE
Flash\Direct to render on layout

### ISSUE THREAD

**Issue by cbichis** [phalcon/cphalcon#12274]
It seems to be no way to render the Flash\Direct messages directly to layout.

Is quite an obvious approach to have on layout (let's say below the h1 page title) an area to display these messages.

Using Flash\Session is possible to render on layout, but not with \Flash\Direct which can be done only on view, using $this->getContent();

**Comment by cbichis** [comment]
I tried using also the 2.0 method output() but this doesnt seems to do anything on layout.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

**Comment by cbichis** [comment]
That's a feature request, as it seems is no way to do this.
