### ISSUE TITLE
Add generated files /ext to .gitignore

### ISSUE THREAD

**Issue by OMSmolina** [phalcon/cphalcon#12284]
Actually every contributor need to ignore all generated files, this is for every one before send a PR. For this in PR Template has this 2 points:
- Phalcon is written in Zephir, please do not submit commits that modify C generated
    files directly or those whose functionality/fixes are implemented in the C
    programming language
- Remove any change to ext/kernel / *.zep.c / *.zep.h files before submitting the PR

It's a pain in the ass in my prespective. I think it's better add this to .gitignore and make life easier for contributors. I know that *.zep.c / *.zep.h / etc are needed for people that not have zephir installed (./install) and for this reason only Core Team can generate this files to merge in to the branches.

Workflow:
1. People work on cphalcon ignoring generated files in .gitignore
2. People send a PR every time without /ext (generated files)
3. Core Team evaluate PR (download changes, tested, etc).
4. Core Team include *.zep.c / *.zep.h / etc manually to git,
5. Core Team merge PR with generated files to branch (ex, 3.0.x)

Thanks.

**Comment by dschissler** [comment]
@sergeyklay Can you add this to Phalcon 4 milestone?

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
