### ISSUE TITLE
REST API documentation does not use new validation class

### ISSUE THREAD

**Issue by PJosepherum** [phalcon/cphalcon#12291]
While trying to implement validation in a model for a REST API, I didn't realise that validation had changed in 3.0.x, as the documentation is still using the old classes `Phalcon\Mvc\Model\Validator` rather than `Phalcon\Validation\Validator`.

>[tutorial-rest.html#creating-a-model](https://docs.phalconphp.com/en/latest/reference/tutorial-rest.html#creating-a-model)

**Comment by Jurigag** [comment]
This is docs issue https://github.com/phalcon/docs
