### ISSUE TITLE
Issues 5,000+ GitHub bug?

### ISSUE THREAD

**Issue by stamster** [phalcon/cphalcon#12290]
This is odd, repository showing 5000+ issues (opened I guess) which does not reflect real state if you sum opened and closed issues there's no 5000 in total.

**Comment by mzf** [comment]
It is Schrödinger issues

**Comment by alec-w** [comment]
If you go to the issues tab and remove the filter then it shows there as being 737 open issues and 5013 closed. Seems to be including all the closed pull requests. [https://github.com/phalcon/cphalcon/issues?utf8=%E2%9C%93&q=](https://github.com/phalcon/cphalcon/issues?utf8=%E2%9C%93&q=)

**Comment by stamster** [comment]
New features @GitHub sux.

**Comment by Jurigag** [comment]
Well in my opinion it shouldn't it should only say opened issues imho. I reported it to github.

**Comment by sergeyklay** [comment]
I hope this will be fixed soon

**Comment by sergeyklay** [comment]
Fixed
