### ISSUE TITLE
404 with ':'

### ISSUE THREAD

**Issue by DeathKR** [phalcon/cphalcon#12305]
### Expected and Actual Behavior

There is a mistake in phalcon/http/response/headers.zep in send() function.
It's always add ':' at the end of main HTTP header:

```php
HTTP/1.1 404 Not Found:
```
> Provide minimal script to reproduce the issue

```php
$response->setStatusCode(404);
$response->setRawHeader("HTTP/1.1 404 Not Found");
```
### Details

* Phalcon version: 3.0.1
* PHP Version: PHP 7.0.11-1~dotdeb+8.1
* Operating System: Debian 8.6
* Installation type: from source
* Zephir version (if any): Version 0.9.4a-dev-7e304ba18c
* Server: Nginx

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.

Refs: https://github.com/phalcon/cphalcon/issues/12179
