### ISSUE TITLE
setJsonContent return strings only

### ISSUE THREAD

**Issue by JSONValidator** [phalcon/cphalcon#12306]
```php
$settings = Settings::findFirst(1);

$response = new \Phalcon\Http\Response();
$response->setJsonContent(array(
	"updated_time" => $settings->updated_time
));
return $response;
```

Result:
```
{"updated_time":"1476127517"}
```

Why updated_time is string? In mysql updated_time is bigint(20)

**Comment by Jurigag** [comment]
1. Do you have mysqlnd driver installed ?
2. Do you have stringify disabled in db connection options like:
```php
new Mysql([
// rest config stuff
'options => [
     PDO::ATTR_STRINGIFY_FETCHES => false,
]
```

3. Another way is to use cast on hydrate i guess.

4. Also instead of `"updated_time" => $settings->updated_time` do:

```php
$settings=Settings::findFirst([
    'columns' => 'updated_time'
    'conditions' => 'id = 1'
])->toArray();
$response = new \Phalcon\Http\Response();
$response->setJsonContent($settings);
return $response;
```

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
