### ISSUE TITLE
Tag: Checkbox cannot have value 0 and be checked

### ISSUE THREAD

**Issue by udarkness** [phalcon/cphalcon#12316]
Expected:

```
<input id="demo-0" name="demo-0" value="0" type="checkbox" checked>
```

Actual:

```
<input id="demo-0" name="demo-0" value="0" type="checkbox">
```

Checkbox and probably other _inputFieldChecked cannot have the value "0" (that is a valid value in the HTTP, HTML and PHP).

``` php
$this->tag->setDefault("demo-0", true);
echo $this->tag->checkField(["demo-0", "value" => "0"]);
```
- Phalcon version: Version => 3.0.1

Check this line:
https://github.com/phalcon/cphalcon/blob/master/phalcon/tag.zep#L538
And the reference https://docs.zephir-lang.com/en/latest/operators.html#comparison-operators
Zephir keeps the design problem of PHP operators. So it should be !==

0 is not null, 0 is a known magnitude in the real numbers. In the other hand, Null represents a value that is unknown. Totally different concepts.

Any comparison to null, should be null (like in sql)

**Comment by gguridi** [comment]
I totally agree. The comparison value != null doesn't contemplate that 0 is going to evaluate as null. I've created a pull request to fix this.

**Comment by sergeyklay** [comment]
@udarkness First of all I would like to draw your attention to the fact that setting to **true** as default value for checkbox and then **0** as current value is totally wrong.

```php
$this->tag->setDefault("demo-0", true); // In fact value is 1
$this->tag->checkField(["demo-0", "value" => "0"]); // But here value is 0
```
You should understand this very well: `0` !== `true`.

Secondly, [I created a small test to prove][1] that the `Tag::checkField` works as expected. In the future please try to provide a reproducible and correct script for determining the bug.

[1]: https://github.com/phalcon/cphalcon/pull/12487
