### ISSUE TITLE
Fatal error between two pages

### ISSUE THREAD

**Issue by rchockxm** [phalcon/cphalcon#12329]
I have read this article from [https://github.com/phalcon/cphalcon/issues/12056](url)

### Expected and Actual Behavior

> I want to test the API from A to B, the user will log in from A and see the data from B.

A: test.php

```php
use Phalcon\Mvc\Micro;

$app = new Micro();

$app->post(
    "/",
    function () use ($app) 
    {
        echo "User Post";
    }
);

$app->get(
    "/",
    function () use ($app) 
    {
        echo "User Get";
        echo file_get_contents("http://127.0.0.1/test_phalcon.php");
    }
);

$app->handle();
```

B: test_phalcon.php

```php
use Phalcon\Mvc\Micro;

$app = new Micro();

$app->post(
    "/",
    function () use ($app) 
    {
        echo "From test.php Post";
    }
);

$app->get(
    "/",
    function () use ($app) 
    {
        echo "From test.php Get";
    }
);

$app->handle();
```

And response show the error.

```php
User Get
Fatal error: Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default in C:\wamp\www\test_phalcon.php:11
```

If I just simply use the `file_get_contents` function in `test.php`

```php
echo file_get_contents("http://127.0.0.1/test_phalcon.php");
```

Everything will be fine.

```php
From test.php Get
```

There is no problem with PHP 5.6.19.

What should I do?

### Details

* Phalcon version: 3.0.1
* PHP Version: 7.0.4
* Operating System: Windows 8.1 x64
* Installation type: WAMP
* Zephir version (if any):
* Server: Apache 2.4.18

**Comment by Jurigag** [comment]
This is known bug with windows. To fix this you need to use one of this:

- vagrant/docer + linux
- nginx + php-cgi
- apache + php-cgi

The problem is only with apache and his php handler. If using php-cgi problems disappear.

**Comment by rchockxm** [comment]
Hi, Jurigag,

I've changed my test environment to CentOS 7.

Thank you

**Comment by Jurigag** [comment]
No problem, just tbh we not sure what really is causing it, be cause it works on php-cgi, it must be some bug with apache php handler itself. Sine by default wamp and xampp are coming with php-cgi is waste of resources and time to trying to fix this.

**Comment by rchockxm** [comment]
Yes, our production environment is use CentOS 7+ Nginx + PHP-FPM. I just want to confirm there is a new bug or my code question.

Thanks you for your kindly support.

**Comment by Jurigag** [comment]
This is a not new bug, it was already reported many times.

**Comment by sergeyklay** [comment]
@Jurigag Could you provide link to the opened issue

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/issues/12056

**Comment by sergeyklay** [comment]
Thanks

**Comment by nikolay-mihaylov** [comment]
I can confirm that when using Windows and switching from default Apache PHP Handler to CGI solves the problem as Jurigag suggested! Here is a nice guide how to make the upgrades: https://commaster.net/content/installing-php-fastcgi-and-zend-opcache-xampp-windows

**Note:** you don't have to do all the steps, I've just added the mod_fcgid.so module in apache/modules and updated my httpd-xampp.conf file. Thats it.
