### ISSUE TITLE
Events for dependent row are not called at create

### ISSUE THREAD

**Issue by cbichis** [phalcon/cphalcon#12339]
I noticed at least for a One-to-One relation the events for "dependent" row are not called at create. Still seems to be called at update.

I am not entirely sure if this is a bug or is a design decision.

**Comment by Izopi4a** [comment]
https://forum.phalconphp.com/

show us the code and maybe someone will be able to assist you

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
