### ISSUE TITLE
How i can create Model, that was sql string without alias?

### ISSUE THREAD

**Issue by free6k** [phalcon/cphalcon#12334]
Example:
```
$model::query()->columns('id')->execute();
```
give
```
select model.id from model.table
```
i need that was like
```
select id from table
```

For what? i send request for sphinxQl :)

**Comment by Jurigag** [comment]
You can't.

**Comment by SidRoberts** [comment]
Models use [PHQL](https://docs.phalconphp.com/en/latest/reference/phql.html) which is then translated into SQL. You can get the SQL statements using the 'db:beforeQuery' event:

```php
$di->set(
    "db",
    function () {
        $db = // ...

        $eventsManager = new \Phalcon\Events\Manager();

        $eventsManager->attach(
            "db:beforeQuery",
            function (\Phalcon\Events\Event $event, $db) {
                $sql = $db->getSQLStatement();

                // ...
            }
        );

        // Assign the eventsManager to the db adapter instance
        $db->setEventsManager($eventsManager);

        return $db;
    }
);
```

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
