### ISSUE TITLE
[BUG] Phalcon\Mvc\Model - serialize

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#12342]
### Expected Behavior

`group` property of `LdapUser` should serializable from `LdapUser` and unserializable to `LdapUser`.
### Actual Behavior

`group` property of `LdapUser` ignoring on serialize and unserialize.
### Why I Needed This?

Users and Groups are entity in my project design. But I don't want to keep user group relationship as entity because this will not consistent by ldap changes. I want to keep group ids on own entity when user login. So I store user entity in session and session use serialization and group property of model orphan by serialization.

```
C:8:"LdapUser":74:{a:4:{s:2:"id";i:1;s:8:"username";s:6:"tugrul";s:4:"name";N;s:5:"email";N;}}
```

``` php
// CREATE TABLE `ldap_users` (
    // `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    // `username` VARCHAR(50) NOT NULL,
    // `name` VARCHAR(255) NOT NULL,
    // `email` VARCHAR(255) NOT NULL,
    // PRIMARY KEY (`id`),
    // UNIQUE INDEX `username` (`username`)
// )
// COLLATE='utf8_general_ci'
// ENGINE=InnoDB
// AUTO_INCREMENT=1

class LdapUser extends \Phalcon\Mvc\Model
{
    public $id;
    public $username;
    public $name;
    public $email;

    public $groups = [];

    public function getSource()
    {
        return 'ldap_users';
    }

    public function columnMap()
    {
        return [
            'id' => 'id',
            'name' => 'name',
            'username' => 'username',
            'email' => 'email'
        ];
    }

    public function initialize()
    {
        $this->skipAttributes(['groups']);
    }
}

$di = new \Phalcon\DI\FactoryDefault();
$di->set('db', function(){
    $connection = new \Phalcon\Db\Adapter\Pdo\Mysql([
        'host' => 'localhost',
        'username' => 'user',
        'password' => 'pass',
        'dbname' => 'project_db',
        'charset' => 'utf8'
    ]);
    return $connection;
});

$ldapUser = new LdapUser();
$ldapUser->setDi($di);
$ldapUser->id = 1;
$ldapUser->username = 'tugrul';
$ldapUser->groups[] = 2;
$ldapUser->groups[] = 8;
$ldapUser->groups[] = 10;

echo serialize($ldapUser);
```
### Details
- Phalcon version: 2.0.13
- PHP Version: 5.6.26-0+deb8u1
- Operating System: Debian 8.5
- Installation type: Compiling from source 
- Zephir version (if any): 0.9.2a-dev
- Server: Nginx + PHP-FPM

**Comment by Jurigag** [comment]
It's not a bug, it's expected feature. It's ignored because doesn't exist on columnmap.

**Comment by tugrul** [comment]
This is design error. What is the purpose of model instead of array resultset if there is no benefit in application logic like this?

**Comment by tugrul** [comment]
Workaround. 

It's dirty but useful to save time.

```php
public function setGroups($groups)
{
	$session = $this->getDi()->get('session');
	$session->set('userGroups', $groups);
}

public function getGroups()
{
	$session = $this->getDi()->get('session');
	$session->get('userGroups');
}
```

**Comment by makerlabs** [comment]
This is not a design error. It's important when u serialize a database object to only serialize the database data and not some object junk... If you want to serialize your custom properties just overload serialize and unserialize methods because this is the right way to do it.

**Comment by Jurigag** [comment]
Purpose of model is to store database data obviously. Not some garbage stuff. If you want to store garbage stuff create seperateed class for this.

**Comment by tugrul** [comment]
@makerlabs why is there a `Phalcon\Mvc\Model::skipAttributes()` attributes?

Common principal: Give back how did you take it. 

Assert: `assertTrue(serialize($model) === serialize(unserialize(serialize($model))))`

There is an inconsistency

**Comment by Jurigag** [comment]
Why - because you want to use mysql default value and don't allow any changes of attributes perhaps ?
