### ISSUE TITLE
[NFR] Merging and compressing css and js files

### ISSUE THREAD

**Issue by elburgl69** [phalcon/cphalcon#12347]
A major performance bottleneck I encounter is having to download many *.css and *.js files. Re-using all kind of client frameworks, having plugins with their own files, explodes the amount of files to download to the client. This has a severe performance impact.

Real-live applications solve this problem by merging all *.css files and all *.js into a single file and removing all comments and unnecessary tokens and serving one (cached) file to the client.

I suggest to introduce a class CssJsManager.
```
use Phalcon\Mvc\User\Component;
class CssJsManager extends Component { }
```

This class has the following public methods:
```
public function setMergeFiles(bool $merge)
public function getMergeFiles()
```
Set the manager to merge the files or not. On development environments it can be useful not to merges css and js files.

```
public function setUseCache(bool $cache)
public function getUseCache()
```
When set to false the manager will always generate a new file. Again might be useful on development environments.

```
public function setPublicJsDir($directory)
public function setPublicCssDir($directory)
public function getPublicJsDir()
public function getPublicCssDir()
```
Set or get the directory (publicly accessible) where own css files are stored and where generated merged / compressed files are stored.

```
public function addCss(string $css)
public function addCss(array $css)
public function addJs(string $css)
public function addJs(array $css)
```
Adds a URI or array of URI's to the managers list of to be served css / js files.

```
public function jsAsArray()
public function cssAsArray()
```
Retrieves an array of added path's to css / js files.

```
public function cssAsHtml ($fileName = '')
public function jsAsHtml ($fileName = '')
```
Gets the full HTML necessary to put in your HTML to have the added css / js available. The output depends on the settings mergeFiles. If it is false it it will be all added individual URI's wrapped in a script or link tag. When true, it will return a URI of an on the fly generated css or js file wrapped in a script or link tag. In order to support caching the filename has the form of:
-  <md5 digest (32chars)>_$filename.ext   (in which ext is css or js.

The md5 digest is created by md5-ing a string with full qualified URI + last timestamp modified in order of addition of the uri to the manager. This assures generating a new file when:
- The order of files changes.
- One or more of the files has been changed.
- Files are added and / or deleted from the manager.
(An alternative would be md5-ing the content of the merged files, but that would require downloading all files also from external sources on every request, while the file info is enough).

It could be used in the phalcon framework like below.

Add the CssJSManger to the DI.
```
/**
 * Add the shared CSS and JS files manager to the services.
 */
$di->setShared('CssJSManager', function() {
    $config = $this->getConfig();
    $cssJsManger = new CssJsManager();
    $cssJsManger->setMergeFiles($config->CssJsManager->merge);
    $cssJsManger->setUseCache($config->CssJsManager->cache);
    $cssJsManger->addCss($config->CssJsManager->preloadCss);
    $cssJsManger->addJs($config->CssJsManager->preloadJs);
    return $cssJsManger;
});
```
In your Phalcon\Config you add a section CssJsManger which contains the setting for merging and caching. In addition you can add an array of css an js resources that are required on every request (and are added first to the object). In your controller (or normal processing) you add the required css and js resources with the methods addCss() and addJS().

In your base controller you can add an event listener on AfterExceuteRoute() like:

```
public function afterExecuteRoute(Dispatcher $dispatcher) {
        $view = $this->di->getShared('view');
        $cssJsManger = $this->di->getShared('CssJSManager');
        $config = $this->di->getConfig();
        if ($config->CssJsManager->controllerlevel) {
            $fn = $dispatcher->getControllerName();
        }
        else {
            $fn = $config->application->name;
        }
        $view->js = $cssJsManger->jsAsHtml ($fn);
        $view->css = $cssJsManger->cssAsHtml ($fn);
    }
```
 In the example above the value of $fileName in the methods jsAsHtml() and cssAsHtml() is set to either an application name (set in de application config) or the current controller name, depending on a setting in Config->CssJsManager->controllerlevel. One could use module name too. The idea is to give context to the generated files. If that is of no intrest of not desired, pass an empty string.

Will create an pull request on the Incubator project with a concrete implementation later today.

**Comment by elburgl69** [comment]
(Original got trucated, so the second part...)

<script> or <link> tag. In order to support caching the filename has the form of:
-  <md5 digest (32chars)>_$filename.ext   (in which ext is css or js.

The md5 digest is created by md5-ing a string with full qualified URI + last timestamp modified in order of addition of the uri to the manager. This assures generating a new file when:
- The order of files changes.
- One or more of the files has been changed.
- Files are added and / or deleted from the manager.
(An alternative would be md5-ing the content of the merged files, but that would require downloading all files also from external sources on every request, while the file info is enough).

It could be used in the phalcon framework like below.

Add the CssJSManger to the DI.
```
/**
 * Add the shared CSS and JS files manager to the services.
 */
$di->setShared('CssJSManager', function() {
    $config = $this->getConfig();
    $cssJsManger = new CssJsManager();
    $cssJsManger->setMergeFiles($config->CssJsManager->merge);
    $cssJsManger->setUseCache($config->CssJsManager->cache);
    $cssJsManger->addCss($config->CssJsManager->preloadCss);
    $cssJsManger->addJs($config->CssJsManager->preloadJs);
    return $cssJsManger;
});
```
In your Phalcon\Config you add a section CssJsManger which contains the setting for merging and caching. In addition you can add an array of css an js resources that are required on every request (and are added first to the object). In your controller (or normal processing) you add the required css and js resources with the methods addCss() and addJS().

In your base controller you can add an event listener on AfterExceuteRoute() like:

```
public function afterExecuteRoute(Dispatcher $dispatcher) {
        $view = $this->di->getShared('view');
        $cssJsManger = $this->di->getShared('CssJSManager');
        $config = $this->di->getConfig();
        if ($config->CssJsManager->controllerlevel) {
            $fn = $dispatcher->getControllerName();
        }
        else {
            $fn = $config->application->name;
        }
        $view->js = $cssJsManger->jsAsHtml ($fn);
        $view->css = $cssJsManger->cssAsHtml ($fn);
    }
```
 In the example above the value of $fileName in the methods jsAsHtml() and cssAsHtml() is set to either an application name (set in de application config) or the current controller name, depending on a setting in Config->CssJsManager->controllerlevel. One could use module name too. The idea is to give context to the generated files. If that is of no intrest of not desired, pass an empty string.

Will create an pull request on the Incubator project with a concrete implementation later today.

**Comment by Jurigag** [comment]
Imho its' stupid to merge css and js. There is already option to merge all css and js to one. What's a problem with it ? Caching of it you are setting in nginx/apache. What we can done is some built-in way to stop generating joined file all the time.

**Comment by elburgl69** [comment]
Imho it's stupid to serve 20+ or something css and/or js files to the client, if two is enough. Each request has a notable overhead! 20+ is not that much in plug-in systems.

I am not aware of a merging feature in Phalcon Framework. I am only aware of external solution but in that case it requires quite some maintenance of a system administrator to (re-)create te merged files. This can be a burden, especially for systems supporting plug-ins / modules.

If you solve it programmatically like I suggest one can write programming guides to follow, which contain the css / js registration method for plugin developers to have their plugin certified. The end-user can then decide to take administrative burden by using not-certified plug-ins or to use certified plug-ins.

Once implemented it only requires extra processing time:
- The first time the merged file is created.
- Once one of the contributing files changes.

**Comment by Jurigag** [comment]
But who are telling to serve 20+ css and js ? You can already join them. From what i udnerstand you want to serve css and js in single file(is it even possible ?).

There is assets manager in phalcon https://docs.phalconphp.com/pl/latest/reference/assets.html

It can join and minify assets. Only one feature is missing is caching file, but this is super easy to do yourself.

**Comment by Jurigag** [comment]
This is no NFR, this is already existing and framework, only one thing you mension here is caching, which NFR laready exists https://github.com/phalcon/cphalcon/issues/1756

**Comment by elburgl69** [comment]
Ok have read the provide links and documentation and agree this is not a NFR. Implementing #1756 with caching based upon the modified timestamp of the underlying resources would be nice.

For now the class I have posted to the Incubator project serves my purpose and I will migrate that solution to a child of Phalcon\Assets\Manager when I have some time to spare.
