### ISSUE TITLE
Special characters("&", "?") in url

### ISSUE THREAD

**Issue by Mo121Montazeri** [phalcon/cphalcon#12350]
When use special characters("&", "?") in url it's not working.

Examples:
1) http://localhost/en/R&B/t101 -> isn't working
1) http://localhost/en/R%26B/t101 -> isn't working
2) http://localhost/en/R?B/t101 -> isn't working
3) http://localhost/en/RB/t101 -> working
in this project [Phalcon-Project](https://github.com/Mo121Montazeri/Phalcon-Test)
- Phalcon version: 3.0.1
- PHP Version: 5.6
- Operating System: Centos 7 | Mac OS X
- Installation type: Compiling from source | installing via package manager
- Server: Nginx | Apache

**Comment by stamster** [comment]
`&` and `?` are both URL encode reserved chars and thus cannot be used literally as route patterns.  You are saying you actually want to use those jokers as a route name? May I ask why?

**Comment by Mo121Montazeri** [comment]
That's because the "?_url=" used in url.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the fact that given issue can be solved by correct setting up the web server.
