### ISSUE TITLE
Multi Checkbox

### ISSUE THREAD

**Issue by cbichis** [phalcon/cphalcon#12354]
Hi,

It seems to be needed to have easy to use multicheckboxes (with validate, get values, set default values, etc) on Phalcon.

Maybe like this ?
https://framework.zend.com/manual/2.2/en/modules/zend.form.element.multicheckbox.html

As far as I checked it seems to be a lot of manual work to fire some "emulated" multi checkboxes.

**Comment by challet** [comment]
I've done it, I just need to find the time to package it in a pull request

**Comment by sergeyklay** [comment]
@challet Could you please snd PR to the Incubator?

**Comment by challet** [comment]
I'm still aiming at doing it, need to make some cleaning and standardisation before. Sorry for the delay.

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
