### ISSUE TITLE
$model->save() is false when use setter/getter

### ISSUE THREAD

**Issue by kryptstorm** [phalcon/cphalcon#12353]
``` php
//Model
 /**
     *
     * @var string
     * @Column(type="string", length=240, nullable=false)
     */
    protected $email;

    /**
     *
     * @var string
     * @Column(type="string", length=60, nullable=false)
     */
    protected $password;

 /**
     * Method to set the value of field email
     *
     * @param string $email
     * @return $this
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Method to set the value of field password
     *
     * @param string $password
     * @return $this
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

// Controller
$model->setEmail($data['email']);
$model->setPassword($data['password']);

 if (!$model->create()) {
            // echo error
  }
```
## Result

array(2) { ["message"]=> string(20) "Username is required" ["errorCode"]=> int(1) }
### Details
- Phalcon version: (`php --ri phalcon`)
  phalcon

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.1
Build Date => Sep 15 2016 23:37:46
Powered by Zephir => Version 0.9.4a-dev-7e304ba18c

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
## phalcon.orm.ignore_unknown_columns => Off => Off
- PHP Version: (`php -v`)
  PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS )
  Copyright (c) 1997-2016 The PHP Group
  Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
  with Zend OPcache v7.0.10-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies
  --------------------------------------------------------------------------------------
- Operating System:
  Docker with ubuntu 14.04
  --------------------------------------------------------------------------------------
- Installation type: Compiling from source
- Server: Apache
- Other related info : mariadb

**Comment by Jurigag** [comment]
And what's a problem ? You didn't provide username which is required(not null in database).

**Comment by kryptstorm** [comment]
I'm sorry about my mistake! It's problem about mapcolumn,
```

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */

```
So, I try to change the value to make a friendly name for my error message, It's wrong! Thanks you.

**Comment by Jurigag** [comment]
So this can be closed ? @kryptstorm
