### ISSUE TITLE
Volt "include with" can be improved

### ISSUE THREAD

**Issue by ricksanchez** [phalcon/cphalcon#12364]
**This is not exactly a bug, because it is documented.  But I wonder if this can be improved and if you consider it worthy.**

If there is a compiler for volt and it is doing many practical things, why cannot it make a variable substitution?

partial/age.volt:

```
{{ age_min }} - {{ age_max }} years old
```

partial/parent.volt

```
{% include "partial/age.volt" with ["age_min": item.minAge, "age_max": item.maxAge] %}
```

Expected:

```
<?= $item->minAge ?> - <?= $item->maxAge ?> years old
```

Actual:

```
<?php $this->partial('partial/age', ['age_min' => $item->minAge, 'age_max' => $item->maxAge]); ?>
```

This would happen once in compile time, so it will be for free in runtime.
### Details
- Phalcon version: 3.0
- PHP Version: 7.0
- Operating System: Ubuntu 16.04
- Installation type: Compiling from source
- Server: Nginx

**Comment by challet** [comment]
it might be a nice workaround of #12176
