### ISSUE TITLE
Phalcon\Cache\Backend\File lifetime problem

### ISSUE THREAD

**Issue by spinmar** [phalcon/cphalcon#12365]
I'm experimenting a problem with lifetime in Phalcon\Cache\Backend\File cache.
Lifetime seems not be considered and exists method return always false.
This is my code with the problem:

``` php
// services.php
$di->set('modelsCache', function() {

    //Cache data for 5 minutes by default
    $frontCache = new \Phalcon\Cache\Frontend\Data(array(
            "lifetime" => 300
    ));

    //File backend settings
    $cache_file = new Phalcon\Cache\Backend\File($frontCache, array(
            "cacheDir" => __DIR__."/../cache/data/",
            "prefix" => "data-"
    ));

    return $cache_file;
});

//My controller
$cache = $this->getDI()->get("modelsCache");
$exists_cache = $cache->exists('hp-nazionali');
$lifetime_hp_nazionali=300;

if (!$exists_cache) {
            $logger->addInfo("Read HP");
            $xml = simplexml_load_file($file_hp);
            if ($xml !== false) {
                $json = json_encode($xml);
                $array_hp = json_decode($json,TRUE);
            }
            $logger->addInfo("Save HP to cache");
            $cache->save('hp-nazionale', $array_hp, $lifetime_hp_nazionali);
}
 else {
            $array_hp = $cache->get('hp-nazionali');
}

```

In my log I always see Read HP and Save HP to cache.
The methos exists always return false,
On my filesystem I see the file data-hp-nazionali which is always rewritten.
### Details
- Phalcon version: 3.0.1
- PHP Version: 
  PHP 5.6.26 (cli) (built: Oct  4 2016 18:07:57) 
  Copyright (c) 1997-2016 The PHP Group
  Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
- Operating System: 
  NAME="Ubuntu"
  VERSION="12.04.5 LTS, Precise Pangolin"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
  VERSION_ID="12.04"
- Installation type: Compiling from source 
- Zephir version (if any):
- Server: Apache
- Other related info (Database, table schema):

**Comment by Daredzik** [comment]
some error throws ??

try, 
`var_dump($cache->save('hp-nazionale', $array_hp, $lifetime_hp_nazionali));`
what's is a result ??

in other hand, from github: https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/backend/file.zep

method save(), should throw expection when can't save to file...

**Comment by spinmar** [comment]
The problem is not the methos save(): I see the file always written on fs.
The problem is the lifetime because the file should be cached for 5 minutes but the methos exists() return false (I suppose for some lifetime problem because the file has been written).

**Comment by Daredzik** [comment]
ahh i see, sorry i miss it in your first post...
check your dates in system, is correctly ?, coz method from source seems ok...

**Comment by spinmar** [comment]
I checked and the date is correct:

spinmar@localhost:~$ date
ven 28 ott 2016, 09.45.51, CEST

**Comment by stamster** [comment]
File cache is not the problem, I'm using it for other purpose:

```
use  \Phalcon\Cache\Backend\File as BackFile,
    \Phalcon\Cache\Frontend\Data as FrontData;

$di->setShared('cache', function (){

    $config = $this->getConfig();

    $frontCache = new FrontData(['lifetime' => 86400]); //keep data buffered for 1 day

    $cache = new BackFile($frontCache, ['cacheDir' => APP_PATH . $config->application->cacheDir]);

    return $cache;
});
```

I'm not even using `exists` method.

Simple use:

```
  $cache = $this->getCache();

  $cacheKey = 'my_footer.buffer';

    // Try to get buffered data
    $wpf = $cache->get($cacheKey);

    if (!$wpf) {
//read data again etc...
}
```

**Comment by spinmar** [comment]
Not in my system.
I replicated your code and I have the same problem.

**Comment by stamster** [comment]
The only difference being that you run PHP 5.6.x and I'm on PHP 7.0.x.
I'll test it on my other instance with manually compiled PHP 5.6.27.
