### ISSUE TITLE
Form element message not filled during form validation.

### ISSUE THREAD

**Issue by lisek2000** [phalcon/cphalcon#12395]
Hello,

as in the topic - messages in elements are not filled after form validation.

Short example:
```
class Element
{
    public function render()
    {
        return $this->hasMessages() ? "yes" : "no";
    }
}

$form = isValid($_POST); // assuming that error occurs
echo $form->get("elementName")->render() // echo "no";
echo $form->hasMessagesFor("elementName") ? "yes" : "no"; //echo"yes";
```

Expected behaviour: after isValid() called on $form, all messages related to elements in that form will be setted also in element.

### Details
* Phalcon version: 3.0.1
* PHP Version: 5.6.24
* Installation type: Compiling from source
* Server: Apache

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch. Thanks you
