### ISSUE TITLE
when i var_dump a value,it show all of the system infomation.

### ISSUE THREAD

**Issue by lujunjie521** [phalcon/cphalcon#12397]
php7.0.12  
Phalcon3.0.x

When i get an infomation from mysql, and use the var_dump function to show the result, but i get all of the system configure infomation ,such as website config, language defined,metaData cache and so on, all of them are shown in the browser

**Comment by Jurigag** [comment]
What exactly you var_dump ? Also this is not issue. Use forum for questions - https://forum.phalconphp.com

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

**Comment by stamster** [comment]
That's normal. DI will be present in your dump as well with other bound objects.
That's why `var_dump()` in OOP is a bad idea (okay maybe for development only).
