### ISSUE TITLE
Libmemcached  and Memcached 「get」 operation return the result is not consistent

### ISSUE THREAD

**Issue by amxsa** [phalcon/cphalcon#12398]
Libmemcached  and Memcached 「get」 operation return the result is not consistent
Libmemcached get() @return mixed|null
Memcached get() @return false

Encountered difficulties in the migration process, whether it can be consistent

### Details

* Phalcon version: (`3.0.1`)

**Comment by stamster** [comment]
How come this is a bug? Libmemcached and Memcached are different adapters (using same back-end). Functions available in libMemcached have different signatures than those present in plain Memcached (PHP implementation).

**Comment by sergeyklay** [comment]
We just have to make sure that both methods correspond to the interface (public API)
