### ISSUE TITLE
Phalcon\Mvc\Model Unintentionally updates related models

### ISSUE THREAD

**Issue by Bagarn** [phalcon/cphalcon#12393]
### Expected and Actual Behavior
> I have created two models with a **hasOne** relationship. I call the first one **Item** and the other one **Status**.
Looking like this in the DB:

***item***

| id [primary ai] | name | status_id |
| - | - | - |
| 1  | My Item  | 1 |

***status***

| id [primary ai] | name |
| - | - |
| 1  | Status 1  | 
| 2  | Status 2  | 

> I have setup my models like this
```php
use Phalcon\Mvc\Model;
class Item extends Model
{
    public $id;
    public $name;
    public $status_id;

    public function initialize()
    {
        $this->hasOne(
            'status_id',
            'Status',
            'id',
            ['alias' => 'status']
        );
    }
}
```

```php
use Phalcon\Mvc\Model;
class Status extends Model
{
    public $id;
    public $name;
}
```
> When i do this:
```php
$item = Item::findFirstById(1);
echo $item->status->id . ' - ' . $item->status->name; // 1 - Status 1
$item->status_id = 2;
$item->save();
echo $item->status->id . ' - ' . $item->status->name; // 2 - Status 1
```

> The model saves the name from status 1 to status 2.
So that the status table in the  DB looks like this.

| id | name |
| - | - |
| 1  | Status 1  | 
| 2  | Status 1  | 

> I would expect the Item to be updated with the second status and not the second status to be updated with the name from the first.

### The problem
> I think the problem here is that when I refer to the related status ( `$item->status->id` ), the model's **__get** method stores the status object in its **_related** attribute that then gets used in the **_postSaveRelatedRecords** method. 

> This results in the related status being saved even though I have not changed it in any way.
Moreover, for some reason **_postSaveRelatedRecords** does this:

```zephir
let columns = relation->getFields() // 'status_id' in this case
...
referencedFields = relation->getReferencedFields(); // 'id' in this case
...
if !fetch value, this->{columns} { ... } // resulting in value == '2'
...
recordAfter->writeAttribute(referencedFields, value); // why
```

> Since the only field in the related object being updated is the id (and not the name)
This will result is that, later when `if !recordAfter->save() {` is executed; the second record is updated with the information from the first.

### Possible solution
> I would suggest altering the **__get** method of **Phalcon\Mvc\Model** by removing this section:
```zephit
/**
 * For belongs-to relations we store the object in the related bag
 */
if result instanceof ModelInterface {
	let this->_related[lowerProperty] = result;
}
```
> I think the above section could cause other issues. Even without setting the status_id as I did in my example. The model would still unnecessarily save to the related model whenever it was previously fetched. Possibly causing data saved by another process during the time between fetch and save to be overwritten.

### Details

* Phalcon version:  3.0.1
* PHP Version: 7.0
* Operating System: Ubuntu 16.04 LTS

**Comment by ikas** [comment]
+1

**Comment by Jurigag** [comment]
```php
 $this->hasOne(
            'status_id',
            'Status',
            'id',
            ['alias' => 'status']
        );
```

This should be belongsTo relation.

**Comment by Bagarn** [comment]
Yes. That would solve the problem of the id being set, since the __preSaveRelatedRecords method does not have that line.
But then, what is the point of the hasOne relationship?
Imagine status being replaced by address or something. The same problem would still be present.

**Comment by Jurigag** [comment]
hasOne is for example accessing Item in status. Like for cases where you want access related record from table where current model is related somewhere. For example:

```php
class Status extends Model
{
    public $id;
    public $name;

    public function initialize()
    {
        $this->hasOne('id', 'Item', 'status_id', ['alias' => 'item']);
    }
}
```

**Comment by Bagarn** [comment]
Yes. you are very right.
But wouldn't the related record still be saved even if i used belongsTo?

**Comment by Bagarn** [comment]
This example results in the name update of status 1 to be reverted when the item is saved.
```php
$item = Item::findFirstById(1);
echo $item->status->id . ' - ' . $item->status->name; // 1 - Status 1

$status = status::findFirstById(1);
$status->name = 'Test';

$status->save();

$item->save();
echo $item->status->id . ' - ' . $item->status->name; // 1 - Status 1
```

**Comment by Bagarn** [comment]
Anyway. My main problem was solved by using belongsTo. And my other issue is probably not even an issue since you would use transactions in cases like that. Feel free to close this issue and thanks for the help.
