### ISSUE TITLE
QueryBuilder does not validate total number of records in the database before sending the query to retrieve data

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#12405]
### Expected and Actual Behavior

> QueryBuilder does not validate total number of records in the database before sending the query to retrieve data

> First, a request is sent to receive data, and then the total number

> For example I have 26 records in the database, 3 pages. When you call a page 4, the request is also sent to the database

```php
[15-Nov-2016 13:56:03] php: [DEBUG] SELECT `table`.* FROM `table` WHERE `table`.`user_id` = :user_id ORDER BY `table`.`created_time` DESC LIMIT :APL0 OFFSET :APL1 [1,10,30]

[15-Nov-2016 13:56:03] php: [DEBUG] SELECT COUNT(*) AS `rowcount` FROM `table` WHERE `table`.`user_id` = :user_id [1]

```
> Provide minimal script to reproduce the issue

```php
$paginator = new \Phalcon\Paginator\Adapter\QueryBuilder([
    'builder' => $builder,
    'page'    => $page,
    'limit'   => 10,
]);
```
### Details

* Phalcon version: 3.0.1
* PHP Version: 5.6
* Operating System: Windows
* Server: Apache

**Comment by Jurigag** [comment]
This is nto a bug, it's expected feature Why it should even check stuff like this ?

**Comment by googlle** [comment]
This is Paginator and it should do it. why not?

**Comment by Jurigag** [comment]
Because there is no any error or problem. Just 4th page doesn't have any data. What it should do if there is no data ?

**Comment by googlle** [comment]
return null for items. just at the beginning, the paginator should to know how many records in the database and then check whether need to access the database. if not then to show paginator->items = null;

**Comment by Jurigag** [comment]
Still - it needs to make some request to check if there is any items. Returning 0 rows from database or doing count and some check if needs to select rows will be no difference in performance. Even i think that returning 0 rows will be faster.

**Comment by googlle** [comment]
I'm not talking about the performance. Perhaps the performance will win in some places even, because there is no extra query. I say that the idea paginator should check in at the beginning of the number of records

**Comment by Jurigag** [comment]
But why ? I don't really see the difference, select 0 rows or check number of elements.

**Comment by virgofx** [comment]
I think more intuitively the count could be called first prior to the data ... and only query data if count > 0. That would be a quick 2 line fix

**Comment by googlle** [comment]
@virgofx yes, and should check this
```php
$offset = $limit * ($page - 1);
if ($offset < $count) {}
```

**Comment by stamster** [comment]
Count on very large tables (which by chance are also inserting lots of records at the same time) will have significant impact on performance.
So the idea is to really retrieve only set of results from the query, even if there are 0 of them.
