### ISSUE TITLE
Cannot override final method Phalcon\\Mvc\\Model::__construct()

### ISSUE THREAD

**Issue by kovacs-tamas** [phalcon/cphalcon#12404]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> I wanted to join two tables or just run a query on one model, but it always fails, because i get this error. The model class doesn't has not own constructor.

```php
PHP Fatal error:  Cannot override final method Phalcon\\Mvc\\Model::__construct() in /var/www/****/**.php on line 0
```
> Provide minimal script to reproduce the issue

```php
$result = $this->modelsManager->createBuilder()
     ->from('MainTable') 
    ->join('SecondTable') 
    ->limit(20) 
    ->getQuery() 
    ->execute();
```
### Details

* Phalcon version: 2.0.13
* PHP Version: 5.5.9
* Operating System: Ubuntu
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Apache
* Other related info (MySQL, InnoDB):

**Comment by sergeyklay** [comment]
It is concept by design.

**Comment by Jurigag** [comment]
You have afterConstruct method and initialize.

**Comment by sergeyklay** [comment]
Or models events

**Comment by kovacs-tamas** [comment]
In this care, aren't any ways to join two tables when i have event listeners in the model? Really?

**Comment by Jurigag** [comment]
What you mean join two tables ? You can just use query builder.

**Comment by kovacs-tamas** [comment]
Yes, i used the query builder also, and i got the same error

**Comment by Jurigag** [comment]
Because you override __construct method. Just dont override it.

**Comment by kovacs-tamas** [comment]
No , i don't have own __construct

**Comment by Jurigag** [comment]
Yes you have, otherwise you wouldn't have such an error.

**Comment by kovacs-tamas** [comment]
Okay, we can accept, i use the features of the ORM. So how can i get the data, should i write raw SQL question and parse the result? Is this the only one solution, right?

**Comment by Jurigag** [comment]
No. You can use query builder or whatever other solution.
