### ISSUE TITLE
[BUG] When SoftDelete behaviour is enabled, Model's 'afterDelete' event is not triggered

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#12403]
Current Phalcon version.

https://docs.phalconphp.com/en/latest/reference/model-behaviors.html#softdelete

**Current behaviour:**
Enabling SoftDelete behaviour suppresses calls to Model's 'afterDelete' listeners.

**Expected behaviour:**
While model row does not get deleted from the database, calls to `afterDelete` should still fire. I may have application logic that takes further actions on delete (regardless whether model row was deleted or marked as deleted).

Thanks!

**Comment by sprufu** [comment]
+1

**Comment by Izopi4a** [comment]
```
<?php
use Phalcon\Db\Adapter\Pdo\Mysql as DbAdapter;
use Phalcon\DI\FactoryDefault;
use Phalcon\Mvc\Application;
use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Behavior\SoftDelete;

$di = new FactoryDefault();

$di->set('db', function () {
    return new DbAdapter([
        'host' => "127.0.0.1",
        'username' => "root",
        'password' => "123456",
        'dbname' => "koko",
        "options" => [
            \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
            \PDO::ATTR_EMULATE_PREPARES => false,
            \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
            \PDO::ATTR_STRINGIFY_FETCHES => false
        ]
    ]);
});

class koko extends Model {

    public $id;

    const DELETED = "D";

    const NOT_DELETED = "N";

    public function initialize()
    {
        $this->setSource("Persons");

        $this->addBehavior(
            new SoftDelete(
                [
                    "field" => "address",
                    "value" => koko::DELETED,
                ]
            )
        );
    }

    public function beforeDelete(){

        echo "<pre>";
        var_dump("yes i am triggered!");
        echo "</pre>";
        exit;

        return false;
    }
}

$application = new Application($di);


$rec = koko::findFirstByPersonID(1);

echo "<pre>";
var_dump($rec->delete());
echo "</pre>";
exit;


```


outputs

```
<pre><pre>string(19) "yes i am triggered!"
```

php 7 0 13 
mysql 5.7.16

**Comment by temuri416** [comment]
@Izopi4a what are you trying to demonstrate exactly?

**Comment by Izopi4a** [comment]
come i checked beforedelete intead of afterdelete , just tell me i am stupid. 

i will check afterdelete tomorrow ...

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by sergeyklay** [comment]
> The default SoftDelete doesn't delete anything, it merely updates the field value to the deleted value and then it skips the delete operation.

Refs: 
* https://github.com/phalcon/cphalcon/issues/11069
* https://forum.phalconphp.com/discussion/10291/how-to-emulate-afterdelete-event-with-softdelete-behavior
* https://forum.phalconphp.com/discussion/4275/modelafterdelete-does-not-fire
* https://forum.phalconphp.com/discussion/4494/i-made-an-improved-softdelete

**Comment by sergeyklay** [comment]
> don't you think so

Right now no. Mb someday in the future. In any case, this not a bug and has a very low priority.

**Comment by temuri416** [comment]
I understand that you think this is a low-priority item and I agree,

But saying that this is not a bug is wrong. Because then the following statement would be incorrect, which makes perfect sense:

> I may have application logic that takes further actions on delete **regardless** whether model row was deleted or marked as deleted.

But, whatever. I can certainly stick another workaround in.

**Comment by wajdijurry** [comment]
That's because SoftDeleteBehavior do the following:
```
/**
 * Skip the current operation
 */
model->skipOperation(true);
```
