### ISSUE TITLE
Timing attack possible in \Phalcon\Security::checkToken

### ISSUE THREAD

**Issue by kristofferingemansson** [phalcon/cphalcon#12418]
In \Phalcon\Security::checkToken, comparison of supplied and expected tokens are done with simple "==" and is thus subject to a timing attack.
https://github.com/phalcon/cphalcon/blob/v3.0.1/phalcon/security.zep#L400

This is somewhat mitigated by the fact that tokens usually are regenerated.

Comparison should preferably be done using PHP's hash_equals if it exists (PHP >= 5.6.0) and then maybe use comparison algorithm from \Phalcon\Security::checkHash as fallback?
https://github.com/phalcon/cphalcon/blob/v3.0.1/phalcon/security.zep#L300

**Comment by sergeyklay** [comment]
I'll try to backport `hash_equals` from PHP 5.6

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
