### ISSUE TITLE
[Micro] url path filtering some character, '+'

### ISSUE THREAD

**Issue by jhaoheng** [phalcon/cphalcon#12421]
input : `curl -X POST http://localhost/xxxx+001@gmail.com/hellotest`
output : `xxxx 001@gmail.com`

**should output : xxxx+001@gmail.com**, but the charactor '+' is filtered

```php
use Phalcon\Mvc\Micro;
$app->GET('/{email}/hellotest', function ($email) use ($app) {
	echo $email;
});
```
### Details

* Phalcon version: 3.0.1
* PHP Version: 7.0
* Operating System: osx

**Comment by sergeyklay** [comment]
```php
$app = new Micro;
$app->get('/{email}/hellotest', function ($email) use ($app) {
    return $email;
});

if ($app->handle('/xxxx+001@gmail.com/hellotest') !== 'xxxx+001@gmail.com') {
    die('FAIL');
} else {
    echo ' Ok';
}
```

```
xxxx+001@gmail.com Ok
```


http://stackoverflow.com/questions/1005676/urls-and-plus-signs

**Comment by jhaoheng** [comment]
Hi @sergeyklay 

I still confusion it.
when i use your method
- `return $email`
- and `handle it`
it is work

if i don't `return $email` but echo this directly, the result still output `xxxx 001@gmail.com`
(i input `xxxx%2B001%40gmail.com` it still no `+`.)

i parse the url path, it is work
```
$app->GET('/{email}', function ($email) use ($app) {
    $path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
    $segments = explode('/', rtrim($path, '/'));
    $email = $segments[1];
});
```

I'm sure , if i parse url path directly , it is work. but if i get this parameter by MICRO , it is fail
what happened?

Thank you

**Comment by sergeyklay** [comment]
![micro-issue](https://cloud.githubusercontent.com/assets/1256298/20583476/de9684ce-b1f2-11e6-9e63-eb8256f908f7.png)

**Comment by jhaoheng** [comment]
![2016-11-24 9 26 29](https://cloud.githubusercontent.com/assets/1822475/20583838/5998edc6-b228-11e6-9e3d-7ff4350c6943.png)

**Comment by sergeyklay** [comment]
I don't see the problem on your screenshot. Could you please explain?

**Comment by jhaoheng** [comment]
Hi @sergeyklay 

The situation is 
1. `$app->handle('/anyString/hello')`
2. Type `{dns}/{email}/hello` on the browser.
3. should echo "email" : abcd@gmail.com on the browser
4. but the echo is `anyString`

should echo the email `abcd@gmail.com` on the browser.
Just only use `$app->handle();` can get the url parameter.

**Comment by Jurigag** [comment]
Browser encods + sign to %2B i guess

**Comment by jhaoheng** [comment]
Hi @Jurigag 

I tried use %2B to replace '+' .
When i use `parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);`, and it's work.
If i get parameter from MICRO, '+' will be replaced a blank character.

Confused.

Thank you.

**Comment by Jurigag** [comment]
I mean when browser is doing request it encods + sign to %2B.

**Comment by jhaoheng** [comment]
Hi @Jurigag 

It look like not browser behavior.
Because i type `dns/abc+001/` on the same browser, and i try two method to get `abc+001`.

1. Use `parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);` to get url path , and `$segments = explode('/', rtrim($path, '/'));`,  finial use `$var=$segments[1]` to get `abc+001`
==> it is work

2. Use MICRO 

```
use Phalcon\Mvc\Micro;
$app->GET('/{email}/hellotest', function ($email) use ($app) {
	echo $email;
});
```
will get `abc 001`

Do you have any suggestion?

**Comment by Mo121Montazeri** [comment]
Phalcon url structure must be change ....

This is laravel test:
<img width="440" alt="screen shot 2016-11-25 at 6 29 01 pm" src="https://cloud.githubusercontent.com/assets/7949908/20628763/2b6f9010-b33d-11e6-9485-57e40a860df3.png">

**Comment by sergeyklay** [comment]
I was able to reproduce it. I'll try to sort out

**Comment by Mo121Montazeri** [comment]
Please remove "?_url=" then many of bugs will be improved.

**Comment by sergeyklay** [comment]
For example?

**Comment by Mo121Montazeri** [comment]
[#12350](https://github.com/phalcon/cphalcon/issues/12350)

**Comment by sergeyklay** [comment]
But why 
> Because "?_url="

**Comment by stamster** [comment]
@Mo121Montazeri you don't have to use that default router strategy, but full REQUEST_URI instead. That way, `?_url` is not populated.

**Comment by mbrostami** [comment]
I think it's zephir issue with _GET global variable which has space instead of + in _url index.

**Comment by sergeyklay** [comment]
@mbrostami Could you please open an issue at Zephir repo with script to reproduce?

**Comment by mbrostami** [comment]
https://github.com/phalcon/zephir/issues/1371

**Comment by mbrostami** [comment]
I closed zephir issue. It was because of .htaccess file which in transforming _url parameter, replaces + character.
Changing this line: 
```RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]```
to this: 
```RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,B,L]```
will solve the problem.
