### ISSUE TITLE
Segmentation fault with 3.0.2 on PHP 7.1

### ISSUE THREAD

**Issue by dzuelke** [phalcon/cphalcon#12444]
You're already aware I guess, as the Travis builds are failing with the same problem, but I figured it wouldn't hurt to have an issue to track it.

Even just `php -v` segfaults :)

This is notably different from 3.0.1, which did not even compile successfully against 7.1.

**Comment by stamster** [comment]
7.1 ... I would check it only some time after official release.

In other words - I'm not even sure whenever PhalconPHP will support PHP 7.1 on this release series 3.0.x.
@sergeyklay should know more on this.

**Comment by Jurigag** [comment]
Definitely not going. 3.0.x is bugfix. PHP 7.1 support is new feature - so it will come most likely with 3.1.0 or 3.x.0 version.

**Comment by NextSeason** [comment]
Is there a new version has already fixed this issue? I really don't want to recompile the php code.

**Comment by Jurigag** [comment]
No there is not
