### ISSUE TITLE
Model setupping castOnHydrate and ignoreUnknownColumns problem 

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#12446]
I have query:

```
$qb = $this->modelsManager->createBuilder()
            ->addFrom(ItemLike::class, 'l')
            ->columns('u.*')
            ->join(User::class, 'l.user_id = u.id', 'u')
            ->andWhere('l.item_id = :item_id:', ['item_id' => $itemId])
            ->getQuery()->execute();
```
and it was working until I added to my code (I added it because I would like to have numbers as integer in objects from DB):

```
Phalcon\Mvc\Model::setup(['castOnHydrate' => true]);
Phalcon\Mvc\Model::setup(['ignoreUnknownColumns' => true]);
```
With these settings when I run query results (object Phalcon\Mvc\Model\Resultset\Simple) has invalid columnMap: there are fields from class ItemLike instead of User. So during iteraing results in foreach I got object User but with null fields.

Do You think is right behavior?

I found 2 fixes, but they are problematic to implement in whole application.
Fix 1: disable ignoreUnknownColumns and castOnHydrate - columnMap in Phalcon\Mvc\Model\Resultset\Simple is null. During iterating results in foreach object User has right fields.
Fix 2: switch class in join() with class in addFrom() - columnMap has fields from User class.

PHP 5.6, Phalcon 3.0.1

**Comment by Jurigag** [comment]
It's not right behaviour, this is well known bug for years/months. The best workaround and solution for now is just:

```
->columns('l.*,u.*')
```

**Comment by igorsantos07** [comment]
This sounds like yet another bug related to `ignoreUnknownColumns` that's taking dust, like #11907.

If someone wants to give it new life, I created a dockerized project based on Invo (the Phalcon sample project): https://github.com/igorsantos07/invo
You can fork it, add the code that triggers the issue to `IndexController::indexAction()`, and post it here. Would certainly help the maintainers to verify the issue and _maybe_, fix it.

**Comment by magroski** [comment]
Bump
