### ISSUE TITLE
Model::count() causes memory leak on 3.0.2 php7/php56

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#12456]
We have code that was doing the following:
```php
for ($i = 0; $i < 100; $i++) {
  $count= Model::count("attr = '123'");
  echo "{$count} records retrived";
}
````
On each invocation memory grows and is not released.

**Comment by sergeyklay** [comment]
Duplicated #2705, #3175

Also the problem is not using bound parameters: http://docs.phalconphp.com/en/latest/reference/models-cache.html#caching-of-phql-planning

**Comment by Jurigag** [comment]
Are you sure you are on 3.0.2 ? This was fixed in 3.0.2

**Comment by nsossonko** [comment]
I am sure. My code was using a variable that changed in each loop.

**Comment by sergeyklay** [comment]
And this is bad. Did you read https://docs.phalconphp.com/en/latest/reference/models-cache.html#caching-of-phql-planning

**Comment by nsossonko** [comment]
I read that, and fully understand that. It doesn't matter that the practice is bad, there are a lot of reason out there why not to always bind every last thing (some related to testing, etc.). There still should be a cap on caching...
