### ISSUE TITLE
can't start the php7.1 server when i update the php7 to php7.1 with the phalcon

### ISSUE THREAD

**Issue by lujunjie521** [phalcon/cphalcon#12457]
i have a problem to start php server;

before i update to the php7.1, i use the php7.0.13 and phalcon3.0.2, it works fine.

but when i update to the php7.1;
i can't restart the php server with this error
Starting php-fpm /etc/init.d/php-fpm: line 53: 18436 Segmentation fault      (core dumped) $php_fpm_BIN --daemonize $php_opts

**Comment by sergeyklay** [comment]
Duplicated https://github.com/phalcon/cphalcon/issues/12055
