### ISSUE TITLE
Phalcon\Mvc\View can't be extended correctly in Zephir

### ISSUE THREAD

**Issue by ucando** [phalcon/cphalcon#12460]
### Expected and Actual Behavior

I have an class extended Phalcon\Mvc\View write by Zephir, and it run well in Phalcon 3.0.1. when I upgrade to 3.0.2, it cause some "Undefined variable" notice, also the render system is broken. I review the code between 3.0.1 and 3.0.2 and found that many variables has defined as "[]", it seems the "[]" value can't be extend correctly. I write another php file to extend Phalcon\Mvc\View, and it can run well, so is it the bug of Zephir?

```php
Fatal error: Uncaught exception 'Exception' with message 'The argument is not initialized or iterable()' in phalcon/mvc/view.zep:904 Stack trace: #0 [internal function]: Phalcon\Mvc\View->render('index', 'index', Array) #1 g:\website\project\public\index.php(35): Phalcon\Mvc\Application->handle() #2 {main} thrown in phalcon/mvc/view.zep on line 904
```
> Provide minimal script to reproduce the issue

```php
//this code can run
$pass['b'] = "b";
$this->view->setVar('a', "a");
$this->view->setVars($pass);

//this code can't
$pass['a'] = "a";
$pass['b'] = "b";
$this->view->setVars($pass);
```
### Details

* Phalcon version: 3.0.2
* PHP Version: 5.6.1
* Operating System: windows 10
* Installation type: download dll
* Zephir version (if any):
* Server: Nginx

**Comment by gtux** [comment]
Hi, Could you please put the setup of view object? Because I think the error have some relation with the value of templateBefore variable. The error that you get is the same that I had informed before on zephir:

https://github.com/phalcon/zephir/issues/1328

**Comment by ucando** [comment]
very simple code, these code will cause error

```php
use Phalcon\Mvc\View as PhalconView;

class View extends PhalconView {
    protected _var_a = [];

    public function someFunction() {

    }
}
```

but if I change the properties definition, it can run correctly.

```php
use Phalcon\Mvc\View as PhalconView;

class View extends PhalconView {
    protected _var_a; //don't defined as array

    public function someFunction() {

    }
}
```

**Comment by sergeyklay** [comment]
@SidRoberts

**Comment by SidRoberts** [comment]
Can you post your extended class?

**Comment by SidRoberts** [comment]
It sounds like a Zephir bug to me.
