### ISSUE TITLE
PhalconMemorySession not found when running tests

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#12463]
I'm trying to run the PHP-Unit tests with the Vagrant Phalcon
I followed the unit-test setup in the Readme [https://github.com/phalcon/cphalcon/tree/master/tests](https://github.com/phalcon/cphalcon/tree/master/tests)
Unfortunately I'm getting the follow error

```
- SessionTest: Should auto escape html
PHP Fatal error:  Class 'Codeception\Lib\Connector\PhalconMemorySession' not found in /home/vagrant/cphalcon/tests/unit/Flash/SessionTest.php on line 48
PHP Stack trace:
```
Codeception is on v2.2.7, Phalcon 3.02, php5.6.28
Is this part of Codeception or Phalcon?

**Comment by Jurigag** [comment]
Codeception.

**Comment by ruudboon** [comment]
Ahh Awesome. Thnx
