### ISSUE TITLE
Install php7.0-phalcon on ubuntu 16.10

### ISSUE THREAD

**Issue by bvcmxy** [phalcon/cphalcon#12462]
There's no repository for Ubuntu 16.10 to install php7.0-phalcon, I had to set the repository from Ubuntu 16.04 to install it using apt.

Can this be fixed in the near future?

Thank you,

**Comment by stamster** [comment]
Why would it be for a distro not meant for a production use? Only LTS should be supported IMHO.
And on top of that, you can always compile from source on your own.

**Comment by sergeyklay** [comment]
https://forum.phalconphp.com/discussion/13265/phalcon-on-packagecloudio


We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
