### ISSUE TITLE
column name should be optional

### ISSUE THREAD

**Issue by elibyy** [phalcon/cphalcon#12508]
I've tried to map some columns within the model to a custom names, but if i don't map the entire module i get Phalcon\Mvc\Model\Exception

> Column 'name' isn't part of the column map

the expected result is that the column name will be resolved from the property name if it's not within the column annotations

the example code is in this [gist](https://gist.github.com/elibyy/acda5728125b4d004dff0999959002a8)

running on MacOS sierra with Phalcon 3.0.1 with CLI installed VIA brew

**Comment by Jurigag** [comment]
```
  $columns = $this->getModelsMetaData()->getAttributes($this);
        $map = [];
        foreach ($columns as $column) {
            $map[$column] = lcfirst(Text::camelize($column));
        }
        return $map;
```

If you want to have underscore in database and camelcase in models(most common situation).

**Comment by elibyy** [comment]
some columns are snake_cased in the database and in the code i want them to be in camelCase but i want to use annotations driver

**Comment by Jurigag** [comment]
So the code above is way to go.

**Comment by elibyy** [comment]
this is just adding extra code to the annotations that are already there

**Comment by Jurigag** [comment]
What ? Just put this code into some AbstractModel to columnMap method and extends all models with it. Doing what you need.

**Comment by elibyy** [comment]
it's not really helping me :( this is only an example, i have some usages where the db column is in different name, it would be much easier to specify only the custom mapping rather then the entire mapping

**Comment by Jurigag** [comment]
Then it's new feature request, if you want it to be optional feel free to create new PR.

**Comment by elibyy** [comment]
OK, i will submit a PR, thanks
