### ISSUE TITLE
Can't build phalcon v3.0.3 using zephir

### ISSUE THREAD

**Issue by tembem** [phalcon/cphalcon#12509]
Checkout to latest tag v3.0.3, but failed to compile it using zephir. It said:

```
Zephir\CompilerException: Cannot call non-static method 'getversion' in a static way
in /var/www/cphalcon/phalcon/image/adapter/imagick.zep on line 363

	   let version = \Imagick::getVersion();
```

How to reproduce:

```
git clone git://github.com/phalcon/cphalcon.git
cd cphalcon
git checkout v3.0.3
zephir fullclean
zephir build
```
### Details

* Phalcon version: 3.0.2
* PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
* Operating System: Ubuntu 16.04
* Installation type: Compiling from source
* Zephir version (if any): Version 0.9.4a-dev-22f6632128
* Server: Nginx

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch. Thank you!

**Comment by gabel** [comment]
@sergeyklay Having the same issue like @tembem again after this reverted fix.

**Comment by sergeyklay** [comment]
@gabel Just use latest Zephir from the `master` branch
