### ISSUE TITLE
Phalcon\Assets\Manager outputInlineJs() returns nothing for existing collection

### ISSUE THREAD

**Issue by SevaJmurov** [phalcon/cphalcon#12512]
I'm trying to get my js collection as inline javascript on html page. This is my assets manager.

```php

$di -> setShared('test_assets', function() {
  $test_assets = new \Phalcon\Assets\Manager();
  $test_assets -> collection('js') -> addJs('js/my_existing_javascript.js',true,true);
  //$test_assets -> collection('js') -> join(TRUE);
  return $test_assets;
});
```

Inside controller:

```php
  $this -> test_assets -> outputInlineJs('js');
   die;
```
returns this:

```html
<html>
  <head>   
  </head>
  <body>
  </body>
</html>
```

expected to return script from my_existing_javascript.js enclosed in <script> tags

```php
  $this -> test_assets -> outputJs('js');
   die;
```
returns 

```html
<html>
  <head>
    <script type="text/javascript" src="/js/my_existing_javascript.js"></script>
  </head>
  <body>
  </body>
</html>
```
my_existing_javascript.js is not empty and it's code is working in application in case I add it via outputJs('js);

### Details

* Phalcon version: (3.0.2)
* PHP Version: (7.0.13)
* Installation type: Compiling from source
* Server: Apache/2.4.6

**Comment by gguridi** [comment]
I don't think the system was though to work on this way.

The inline codes are stored in the property _codes and the resources into _resources.
Calling outputInlineJs calls outputInline method that uses what's in _codes to print the inline javascript.
Calling outputJs calls output, passing as callback for rendering the resource ["Phalcon\\Tag", "javascriptInclude"], so it's going to print always a <script type="text/javascript" src="/js/my_existing_javascript.js"></script> tag.

The only way is you manually doing it:

```php
$di -> setShared('test_assets', function() {
  $test_assets = new \Phalcon\Assets\Manager();
  $resource = new \Phalcon\Assets\Resource\Js('/js/my_existing_javascript.js', true);
  $test_assets->collection('js')->addInlineJs($resource->getContent(), true);
  return $test_assets;
});
```

Then you can print it:
```php
$this -> test_assets -> outputInlineJs('js');
```

Hope it helps.

**Comment by Jurigag** [comment]
As wrote above, to output inline js you obviously need to add it first.

**Comment by SevaJmurov** [comment]
@gguridi 
I see now. There is a lack of details about inlineJs in Assets Manager Class description, but I could have guessed that to output inline js you need to add it first as inline js. Thanks, you solution is actually what I really needed.
