### ISSUE TITLE
"with" parameter in Query Builder is not working

### ISSUE THREAD

**Issue by benjamineukles** [phalcon/cphalcon#12521]
I'm currently trying to find a way to not have 11 SQL queries played when I try to find 10 models and a related model for each model.

To be more explicit:
Playing the code below will execute 11 SQL queries! (please note that I'm working with namespace and that Company model has a "**hasOne**" relation to CompanySiret model, and CompanySiret model has a "**belongsTo**" relation to Company model).
```php
$builder = $this->getDI()
                ->getModelsManager()
                ->createBuilder()
                ->columns('Company.*, CompanySiret.*')
                ->addFrom(Company::class, 'Company')
                ->innerJoin(CompanySiret::class, 'CompanySiret.companyId = Company.id', 'CompanySiret')
                ->limit(10);
$res = $builder->getQuery()->execute();

foreach ($res as $r) {
    var_dump($r->Company->CompanySiret);
    var_dump($r->CompanySiret);
}
```
Actually, the first var_dump will **produce 10 SQL queries** for each company I've found. This is quite bad because with my initial query, I already got the CompanySiret... dumped with my second var_dump.
So you can imagine with a limit 1000.... 1001 queries whereas I got all the data with just the first one query.

Then I tried to find a solution for "eager load" the related models. I found a lot of discussions about it, I also found in the incubator the Trait "**Phalcon\Mvc\Model\EagerLoadingTrait**" but I really don't like how it has to be used, I prefer the Query Builder (more friendly with an IDE than using static method and string for me).

After that, I realized that there is a third parameter to the Query Builder method "**addFrom**". It's "**with**" which seems really great at first look. I then tried to use it but nothing happened, I thought I was not using it properly so I decided to go into the github phalcon respository to check how this parameter is used... and there I just faced the reality... this parameter is in the method signature but it is never used! 
If you look further, you can also notice that the parameter can be passed in the constructor with **$params['with']**.

Question/suggestion:

Can you tell me when this parameter will be handled? Secondly, can you remove it to avoid a waste of time for developer like me (I was searching a solution about an hour).

Let me know if I need to place this request into the forum instead of here, but as it produces a non desired code execution I've posted it here.

### Details

* Phalcon version: 3.0.1
* PHP Version: 7.0.10
* Operating System: Linux
* Installation type: Compiling from source
* Zephir version (if any): 0.9.4a-dev-7e304ba18c
* Server: Nginx

**Comment by Jurigag** [comment]
Yes you got but they are under `$r->CompanySiret`.

The addFrom and with is some old stuff which was just plan to add what you want but it was dropped beacause we decided that eager loading is just overall bad stuff. Just use `$r->CompanySiret`. See this issue - https://github.com/phalcon/cphalcon/issues/1117

**Comment by benjamineukles** [comment]
Thanks for your reply.
I know there are under `$r->CompanySiret`.
I'm doing an API in my project and for performance purpose I write my SQL queries just as described in my example. With 1 query I can get all data of a model and its related models... But to have better rendering I want the related models inside my main model (as requested here #10715 but  not yet done in current Phalcon version).

So the only way have to do this is to write something like (right after my first code example in the first post message):

```php
$return = [];
foreach($res as $myResult) {
    $company = $res->Company->toArray():
    $company['companySiret'] = $res->CompanySiret->toArray():

    $return[] = $company;
}

return $return;
```

And here, the line `$res->CompanySiret` is performing a new SQL query each time!

Why the support of eager load has been dropped? 
On a side we have Phalcon, compiled from Zephir, which is really good in terms of performance, but on the other side the ORM is quite bad in terms of performance... I don't understand the point here.

Also, as I've noticed, I already took a look at the incubator eager load, but I really don't like how it has to be used, I prefer the Query Builder (more friendly with an IDE than using static method and string for me).

**Comment by Jurigag** [comment]
Read the issue i mentioned - the answer is there.

What ? ORM in phalcon is fastest available ORM in php bro. Yes it's performing companysiret for each company. This is expected behaviour. Just use `$r->CompanySiret`. No other way.

**Comment by benjamineukles** [comment]
Thank for your explanation. For my project, yes I want the full related objects.
The main problem for me is that I can perform the perfect Query (as given in my first example), get all data (main model and related models) but there is nothing to get the result in a "**nested**" way (CompanySiret inside Company).

Maybe just a option, to set anywhere on the model or the query builder to tell him to nest result in query when we're selecting data from more than 1 model.

So it would be really cool if the parameter "**with**" is **removed from code** to avoid misunderstanding and hoping stuff from the framework that won't occur :)

**Comment by Jurigag** [comment]
What you exactly mention is called eager loading - as you can see in the issue i posted - it will be never implemented, at least not in nearest future.

Why exactly you need full data for API ? I am creating many apis, websites etc and i have like 1/50 situations where i need full objects returned from api.

**Comment by benjamineukles** [comment]
It's not really eager loading in my case since I already get all data I want. It's just a cleaner way to return data in that case. 

It's a waste of time and performance: to retrieve a data I already got, I will perform some SQL queries again and Phalcon will fetch my model with the data etc. whereas I already get all I want.

So I only have to format manually each result from my API, my code will be less readable and a little bit boring to write... And if I add a column on my database table, I have to think about I need to change my custom "return" style.

But I understand your point of you (you also described it in #1117) but I don't share it :)

So what about removing the code occurrences of "**with**" :)

**Comment by Jurigag** [comment]
Yea you get all data but you want to access it using eager loading anyway :)

**Comment by benjamineukles** [comment]
>  Then don't retrieve data you already got.

Yes that's what I will do:
>  So I only have to format manually each result from my API, my code will be less readable and a little bit boring to write... And if I add a column on my database table, I have to think about I need to change my custom "return" style.

I just think it's not a really efficient way to do it. Maybe it's because I (too much?) use to work with an ORM like Propel.

Anyway, thanks for your time, please just remove the parameter "**with**" in the Query Builder.

**Comment by Jurigag** [comment]
Yea propel is doing stuff which you want and that's why it's performing worse than phalcon orm. If we would add it would slow down phalcon.
