### ISSUE TITLE
Error in getMessages() Form

### ISSUE THREAD

**Issue by franzemil** [phalcon/cphalcon#12534]
> Provide minimal script to reproduce the issue

the variable byItemName is never used

```zephir
public function getMessages(boolean byItemName = false) -> <Group>{
		var messages;

		let messages = this->_messages;
		if typeof messages == "object" && messages instanceof Group {
                     return messages;
	         }

	return new Group();
}

```
### Details

* Phalcon version: (3.0.3)
* PHP Version: (7.1)
* Operating System: Ubuntu 16.04
* Installation type:  installing via package manager

**Comment by sergeyklay** [comment]
Cc: @mbrostami

**Comment by mbrostami** [comment]
Right, it should be removed in next major version. 
I kept that just for respecting backward compatibility.

**Comment by nadorator** [comment]
this is not usefull at all to remove this and the documentation is not concordant in 3.2.x. It says we can get attribute but in fact we can't. We can use this:

`$elements=$form->getElements();
foreach($elements as $element)
{
    if ($form->hasMessagesFor($element->getName()))
    {
        $errorFields[]=$element->getName();
    }
}`

problem: we can't get the element AND the message by doing only one loop. We have to do a second loop like that:

`$messages = $form->getMessages(false);
foreach ( $messages as $attribute => $message )
{
     $this->flashSession->error($message);
}`

or to loop using iterations inside the first loop of elements:

`$form->getMessagesFor($element->getName()`

both options are not optimized at all. 

can't you provide something clear and optimized to have both messages and field name at the same time?

**Comment by niden** [comment]
It appears that the original issue has been addressed.

For the double loop one can easily loop through the elements of the form and on each element call `getMessages()`. This way no double loops.

Closing
