### ISSUE TITLE
Database name with dot

### ISSUE THREAD

**Issue by robbygallo** [phalcon/cphalcon#12536]
Phalcon 3.0.3
If the db name contain dot, orm save return error

`'dbname' => 'xxxxxxx.dev',  ------>  'INSERT INTO 'xxxxxxx'.'dev'.'table_name'`

**Comment by Jurigag** [comment]
Try maybe `'[xxxxxxx.dev]'` ?

**Comment by stamster** [comment]
In config.ini, I have this situation:

; password is escaped with double quotes due to PHP INI parser requirements

password = "zzzzzz=aaaaa"

Try with double quotes.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises.
