### ISSUE TITLE
Flushing modelsCache (Redis) not work with a lot of keys

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/cphalcon#12531]
I have configured modelsCache:

```php
$di->setShared('redis', function () {
    $frontCache = new DataFrontend([
        'lifetime' => $this->get('config')->redis->lifetime
    ]);

    $redis = new \Phalcon\Cache\Backend\Redis($frontCache, [
        'host' => $this->get('config')->redis->host,
        'port' => $this->get('config')->redis->port,
        'statsKey' => '_PHCR',
        'index' => 0
    ]);

    return $redis;
});

$di->setShared('modelsCache', function () {
    return $this->get('redis');
});
```
and use task action to clearing modelsCache:
```php
public function clearModelsCacheAction()
    {
        /** @var Phalcon\Cache\Backend\Redis $cache */
        $cache = $this->di->get('modelsCache');
        if ($cache->flush()) {
            echo "success";
        } else {
            echo "not work";
        }
    }
```
When I have about 150 keys this clearing action works perfectly, however with over 2000 keys clearing action doesn't delete any key (and return success). Than I use Predis to clear database and it deletes all keys.

I use redis-cli and command: keys * to check existing keys,

* Phalcon version: 3.0.3
* PHP Version: 5.6
* Operating System: Ubuntu 14
* Installation type: compiling git repository
* Zephir version (if any):
* Server: Apache
* Other related info (Database, table schema): MariaDB, Redis 3.0.3

**Comment by nanotronic** [comment]
You could use a bash script to delete: http://stackoverflow.com/questions/4006324/how-to-atomically-delete-keys-matching-a-pattern-using-redis
`redis-cli EVAL "local keys = redis.call('keys', ARGV[1])  for i=1,#keys,5000 do redis.call('del', unpack(keys, i, math.min(i+4999, #keys))) end return keys" 0 "pattern"`
