### ISSUE TITLE
Phalcon not support 7.1.x ?

### ISSUE THREAD

**Issue by tiepvb** [phalcon/cphalcon#12532]
I have build phalcon 3.x with php7.1 but when i add extension phalcon for php. php is not running.
Phalcon not support php7.1?

> Starting php-fpm: /bin/bash: line 1:  5620 Segmentation fault      /usr/sbin/php-fpm --daemonize

**Comment by tembem** [comment]
Not yet. See https://github.com/phalcon/cphalcon/issues/12055
