### ISSUE TITLE
Method $request::getHeader should better return null instead of empty string if the specified key not exists in header list

### ISSUE THREAD

**Issue by NextSeason** [phalcon/cphalcon#12530]
I think `$request->getHeader` should better return an null so that it would have the same feature with native php getting header value from $_SERVER array. Than it is enable to use `??` operator like `$request->getHeader( 'something-not-exists' ) ?? $request->get('')`;

An empty string is returned in current version 3.0.3.

**Comment by gguridi** [comment]
The shorthand use of the ternary operator is what you need:

```php
$request->getHeader( 'something-not-exists' ) ?: $request->get('something-else');
```

This way it's even compatible with PHP <7 versions.
