### ISSUE TITLE
HAVING after nested SELECT doesn't work correctly in PHQL

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#12548]
```sql
SELECT grandParent.id, SUM(parent.total) AS total
FROM Parents AS parent
INNER JOIN GrandParents AS grandParent
ON parent.grandParent = parent.id
WHERE NOT EXISTS (
  SELECT * FROM Childs AS child
  WHERE parent.id = child.parent
)
HAVING total > 1
```

That causes the PHQL parser to throw an exception that "total is not a column". If I switch to:
"HAVING SUM(parent.total) > 1" it works fine.

PHP 7 with Phalcon 3.0 (master).

**Comment by Jurigag** [comment]
Im guessing PHQL is just following **SQL standard** which **doesn't allow** aliases in columns. Other engines like for example MySQL can allow it, but this is not part of sql standard.

**Comment by nsossonko** [comment]
It allows using the alias when not using a subquery...

**Comment by Jurigag** [comment]
Oh okay then.
