### ISSUE TITLE
2017 year in every classes

### ISSUE THREAD

**Issue by PolDeveloper** [phalcon/cphalcon#12544]
Hello,
there should be 2017 year instead of 2016 in every classes's descriptions.
Kind regards
Mike

**Comment by stamster** [comment]
?

**Comment by PolDeveloper** [comment]
> /*
 +------------------------------------------------------------------------+
 | Phalcon Framework                                                      |
 +------------------------------------------------------------------------+
 | Copyright (c) 2011-2016 Phalcon Team (https://phalconphp.com)          |
 +------------------------------------------------------------------------+
 | This source file is subject to the New BSD License that is bundled     |
 | with this package in the file docs/LICENSE.txt.                        |
 |                                                                        |
 | If you did not receive a copy of the license and are unable to         |
 | obtain it through the world-wide-web, please send an email             |
 | to license@phalconphp.com so we can send you a copy immediately.       |
 +------------------------------------------------------------------------+
 | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
 |          Eduar Carvajal <eduar@phalconphp.com>                         |
 |          Rack Lin <racklin@gmail.com>                                  |
 +------------------------------------------------------------------------+
 */

**Comment by Jurigag** [comment]
T be honest i would really remove this year class to get rid out of this big commits with just year update.

**Comment by virgofx** [comment]
My 2cents - The license should be a simple `LICENSE.md` at root project level and removed from individual files.

**Comment by sergeyklay** [comment]
In general I don't think this is such a serious problem due to which we should keep the issue open. In fact, we have enough other tasks and this issue just creates the appearance that problems are actually more.

I think we can solve this task in background among other commits.

Thank you for contributing.

**Comment by PolDeveloper** [comment]
Your welcome
