### ISSUE TITLE
Why config.ini value change?

### ISSUE THREAD

**Issue by sanwinthetaung** [phalcon/cphalcon#12545]
Using phalcon 3.0.2 with PHP Version 7.0.12

config.ini
```ini
[dev]
id = 235240354674768
```

* read from config.ini file using `Phalcon\Config\Adapter\Ini`
* it give result as : id => int 2142287225
* expected result is 235240354674768

if anyone know why, answer me pls.
TIA

**Comment by sergeyklay** [comment]
**config.ini**

```ini
[dev]
id = 235240354674768
```

```sh
php -a
Interactive mode enabled

php > $config = new Phalcon\Config\Adapter\Ini("/config.ini");
php > var_dump($config);

class Phalcon\Config\Adapter\Ini#1 (1) {
  public $dev =>
  class Phalcon\Config#2 (1) {
    public $id =>
    int(235240354674768)
  }
}

php > echo $config->dev->id;
235240354674768
```

```sh
php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.3
Build Date => Dec 24 2016 19:16:03
Powered by Zephir => Version 0.9.5a-dev

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```

**Comment by sanwinthetaung** [comment]
using window 8.1

<?php 
	$config = new Phalcon\Config\Adapter\Ini("config.ini");
	var_dump($config);

	echo $config->dev->id;
?>

--- config.ini ---
[dev]
id = 235240354674768

run it -- http://localhost/test.php

here is what i get back :

C:\Apache24\htdocs\test.php:3:
object(Phalcon\Config\Adapter\Ini)[1]
  public 'dev' => 
    object(Phalcon\Config)[2]
      public 'id' => int 700905552
700905552

**Comment by Jurigag** [comment]
I guess it's another windows related thing. Just don't use windows with php. Vagrant/docker to rescue.

**Comment by sergeyklay** [comment]
@sanwinthetaung Could you please explain

> `run it -- http://localhost/test.php`

**Comment by sanwinthetaung** [comment]
it is my test.php url.. 

i'm newbie to php and phalcon.
so when i need to test some with php, i make a file under the apache/htdocs folder and i'm using window os

test.php contains following codes,
```
<?php 
	$config = new Phalcon\Config\Adapter\Ini("config.ini");
	var_dump($config);

	echo $config->dev->id;
?>
```
and config.ini file too .... codes are no change
after saving it, i run it in browser using that url... that's what i mean it, sir

sorry for my inconvenience code and writing skill
