### ISSUE TITLE
Phalcon v 3.3 Csrf Token error in Chrome 

### ISSUE THREAD

**Issue by MohammadReza10** [phalcon/cphalcon#12550]
Hi
i have to os
1 - win 10 && 2 - win 7
phalcon v 3.3 error is :+1: 

```
Token Validation Failed*
#0 [internal function]: PostController->createAction()
#1 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(PostController), 'createAction', Array)
#2 [internal function]: Phalcon\Dispatcher->_dispatch()
#3 [internal function]: Phalcon\Dispatcher->dispatch()
#4 D:\wamp64\www\phalcon\public\index.php(73): Phalcon\Mvc\Application->handle()
#5 {main}
```

in chrome 
but in firfox not error :| !!!

**Comment by Jurigag** [comment]
Post code to reproduce. Also there is no phalcon 3.3, i guess you meant 3.0.3

**Comment by jeebus3000** [comment]
Probably because Chrome requests favicon.ico in background. If it does not find it, it requests the page again and you get a new csrf token. Add favicon.ico
