### ISSUE TITLE
Model::setSnapshotData causes memory leak

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#12556]
```php
echo memory_get_usage(true) / 1024; // Memory in KB
$robot = Robots::findFirst();
$robot->update(array('foo' => 'bar'));
$robot->setSnapshotData($robot->toArray());
echo memory_get_usage(true) / 1024; // Benchmark memory after 1 model loaded
for ($i = 0; $i < 10; $i++) {
  $robot = Robots::findFirst();
  $robot->update(array('foo' => 'bar'));
  $robot->setSnapshotData($robot->toArray());
  echo memory_get_usage(true) / 1024; // <-- Leak
}
```

For some reason calling setSnapshotData causes a leak in Phalcon and memory usage continuously goes up each time it is called.

**Comment by Jurigag** [comment]
Where is this memory leak? You posted 1024 everywhere so same size or i miss something?

**Comment by nsossonko** [comment]
I just divided by 1024 to get memory size in KB.

PHP Info:
PHP 7.0.11 (cli) (built: Sep 13 2016 15:37:04) ( NTS )
Copyright (c) 1997-2016 The PHP Group

Phalcon Info:
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.3
Build Date => Dec 24 2016 12:42:29
Powered by Zephir => Version 0.9.5a-dev

This was on Windows, but I observed a similar leak on Linux as well (Ubuntu) with same version details.

**Comment by nsossonko** [comment]
This seems like our own issue, I am investigating further to be sure. Once confirmed, I'll close this. Sorry about that.

**Comment by nsossonko** [comment]
This was due to returning a variable by reference from a static method. I removed the by-reference operator and it no longer leaks. I have no idea why. In any event, it is not a phalcon issue.

**Comment by nsossonko** [comment]
Issue filed with php: https://bugs.php.net/bug.php?id=73960
