### ISSUE TITLE
PHP7 Mongo Support

### ISSUE THREAD

**Issue by dlairetang** [phalcon/cphalcon#12558]
My environment based on PHP7 and When i read the document of Phalcon using it to solve my problem connecting MongoDB Client . I install the mongodb plugin on pecl command 'pecl install mongodb' , But the ODM for MongoDB is invailable.

**Comment by sergeyklay** [comment]
Refs: 
* https://github.com/phalcon/cphalcon/issues/11156
* https://github.com/phalcon/cphalcon/issues/12074
