### ISSUE TITLE
RuntimeException::__toString() must return a string in Unknown on line 0 Fatal error

### ISSUE THREAD

**Issue by wflashy** [phalcon/cphalcon#12563]
```
Warning: RuntimeException::__toString() must return a string in Unknown on line 0 Fatal error: 
Uncaught thrown in /acs/app/var/bootstrap.php on line 68
```

### Details

* Phalcon version: 3.0.3
* PHP Version: 5.6
* Operating System:CentOS Linux release 7.1.1503 (Core)
* Installation type: installing via package manager
* Server: Nginx

**Comment by Jurigag** [comment]
Post script to reproduce?

**Comment by wflashy** [comment]
$config = include __DIR__ . "/../app/config/config.php";
include __DIR__ . "/../app/config/loader.php";
include __DIR__ . "/../app/config/services.php";
$application = new \Phalcon\Mvc\Application($di);
echo $application->handle()->getContent() ;

Error  line：
echo $application->handle()->getContent() ;

**Comment by sergeyklay** [comment]
> Uncaught thrown in /acs/app/var/bootstrap.php on line 68

We need script to reproduce

**Comment by Izopi4a** [comment]
you have error in your views / xml is not returning correct data ?
