### ISSUE TITLE
[NFR] Magic method for sum of related models

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#12587]
Today PhalconPHP is a great framework that brings many usefull classes/methods for rapid prototyping, one of this is Model, that class have a set of methods in order to work with the related models in a easy way without the need to write SQL code.

It has a useful magic methods count and get, so:
```php
Model::count[RelatedModel]()  gets a count for related models
Model::get[RelatedMethod]()     gets the records for related models
```

It will be good if extend this feature to get others aggregate querys like: Sum, Maximum, Minum or Average, like this:

```php
Model::sum[RelatedModel]("columnInRelatedModel")
Model::maximum[RelatedModel]("columnInRelatedModel")
Model::minimum[RelatedModel]("columnInRelatedModel")
Model::average[RelatedModel]("columnInRelatedModel")
```

### Details

* Phalcon version: 3.0.3
* PHP Version: 7.0.14
* Operating System: CentOS AWS Amazon
* Installation type: Compiling from source
* Zephir version (if any): None
* Server: Apache

**Comment by Jurigag** [comment]
I don't like this. Similar issue was closed not long ago i think. What's a problem with query builder? don't need to write any sql code and handles problem fine.

**Comment by gtux** [comment]
Yes, you are right @Jurigag but, if that is the criteria for implement this kind of magic methods, so the count method don't need to exists either? Right?

**Comment by Jurigag** [comment]
Why count method don't need to exists? It needs to exist for counting from Model class.

**Comment by gtux** [comment]
Sorry If I write bad, what that I mean is for the criteria for discard to made others magic methods that you said. Of course the method "count" may have others reasons to exists, I don't said the opposite. I hope made myself clear
