### ISSUE TITLE
[4.0.0] Add getRelationRecords to \Phalcon\Mvc\Model\ManagerInterface

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#12588]
`getRelationRecords()` is referenced from Model as called from numerous methods when hooked from the manager instance referenced from `getModelsManager()` which returns `ManagerInterface` type.  Therefore, need to ensure that `getRelationRecords()` is added into the `ManagerInterface`.

**Comment by Jurigag** [comment]
It's 4.0.0 change. Also we should add other methods to other interfaces.

**Comment by virgofx** [comment]
Yeah, just a slight cleanup to ensure interface has all required methods would be nice ;P

**Comment by Jurigag** [comment]
I would even like to create some list of all missing methods in interfaces.

**Comment by Jurigag** [comment]
Can you close this in favor of https://github.com/phalcon/cphalcon/issues/12676 ?
