### ISSUE TITLE
[NFR]Dialect FunctionInterface

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12583]
Currently there are two ways to make custom dialect function, one is dirty way which exists in incubator https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Db/Dialect/MysqlExtended.php just override getSqlExpression. Second is registerCustomFunction which is better, but still not enough.

I would like to introduce just `Phalcon\Db\Dialect\FunctionInterface` which would require to implement two methods - `getName` and `getDefinition`.

And then we could just add some method to dialect class like `registerCustomFunctionClass(new DateInterval());` for example.

**Comment by nsossonko** [comment]
This would effectively address Issue #12553 no?

**Comment by Jurigag** [comment]
No, your issue is diffrent FunctionInterface what i proposed is just overall way to register custom phql functions. Just some standardized and better way to do it.
