### ISSUE TITLE
Update primary key not working

### ISSUE THREAD

**Issue by VincentMolinie** [phalcon/cphalcon#12590]
I was trying to update a table with no primary key so Phalcon use the unique key on this table the problem is that when you try to update one of the column of this unique key it doesn't work.
For example:
```
test_contact (
    contact_id VARCHAR(255),
    name VARCHAR(255),
    more_info TEXT,
    CONSTRAINT my_unique_key UNIQUE (contact_id, name)
);
```
I have my contact like this `TestContact('Test', 'My Super Name', 'Info')` and when I try to update the name for example I get this request:
`UPDATE test_contact SET test_contact more_info = 'Info' WHERE contact_id = 'Test' and name = 'My New Name'`
So as you can see it does not update the name but try to use it in the where condition. We should use the snapshot value (the old value) for the where not the new one and still update the field

I'm using MySql and Phalcon 3.0.3

**Comment by Jurigag** [comment]
It's not a bug, it's expected behaviour. Phalcon just doesn't allow to update primary keys by design.
