### ISSUE TITLE
[BUG] Gettext::query() can't pass domain param

### ISSUE THREAD

**Issue by mervick** [phalcon/cphalcon#12598]
`Gettext::query()` have ability ([gettext.zep#L100](https://github.com/phalcon/cphalcon/blob/master/phalcon/translate/adapter/gettext.zep#L100)) to change translations domain, by passing third argument, but php throws error

```
BadMethodCallException: Wrong number of parameters
```

seems due to lack of declaration in the method [gettext.zep#L87](https://github.com/phalcon/cphalcon/blob/master/phalcon/translate/adapter/gettext.zep#L87)

> Provide minimal script to reproduce the issue

```php
$gettext = new \Phalcon\Translate\Adapter\Gettext([
    'locale' => 'en_US',
    'defaultDomain' => 'translations',
    'directory' => '/path/to/files',
]);

$gettext->query('text', null, 'domain');

```
### Details

* Phalcon version: (`php --ri phalcon`)
```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 2.0.12
Build Date => Nov  7 2016 02:43:30
Powered by Zephir => Version 0.9.4a-dev-eda63b3263

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```
* PHP Version: (`php -v`)
```
PHP 5.6.29-1+deb.sury.org~xenial+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```
* Operating System: Ubuntu 16.04, Linux 4.4.0-57-generic x86_64
* Installation type: Compiling from source
* Zephir version: 0.9.4a-dev-eda63b3263
* Server: Nginx

**Comment by sergeyklay** [comment]
Declaration of `Phalcon\Translate\Adapter\Gettext::query` must be compatible with `Phalcon\Translate\AdapterInterface::query`. We can't extend the `query` method.

As noticed @mervick in the https://github.com/phalcon/cphalcon/pull/12606#issuecomment-279186086 we can create 

```zep
public function dquery(string! domain, string! index, placeholders = null) -> string
```
or
```zep
public function dquery(string! index, placeholders = null, string! domain = null) -> string
```

or users can override `Phalcon\Translate\Adapter\Gettext` class to add new method.
