### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by limingxinleo** [phalcon/cphalcon#12597]
~~~
php run test_test 
MyApp\Tasks\TestTestTask handler class cannot be loaded

php run Test\\test_test 
MyApp\Tasks\Test\test_testTask handler class cannot be loaded
~~~
### Details

* Phalcon version: 3.0.3
* PHP Version: 7.0.14
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
And where is your code to reproduce a problem?

**Comment by limingxinleo** [comment]
When I run test_test will be converted to TestTestTask 
but when I run Test\\test_test will be converted to Test\\test_testTask, why is the task name different?

**Comment by Jurigag** [comment]
But add your tasks code.

**Comment by stamster** [comment]
And you haven't provided full stack details (OS, Web server, SAPI...).

It is very likely that your loader is wrong, i.e. it cannot load your CLI app.

**Comment by limingxinleo** [comment]
When I run the cli task with namespace, the task name test_test can converted to TestTestTask, but the Test\\test_test not converted to Test\\TestTest. It converted to Test\\test_test , so I think it can be some error.

**Comment by limingxinleo** [comment]
> 很抱歉，我英文实在有点差，一直表达不明白

具体问题是这样的，我写的cli脚本是有命名空间的，默认情况下我在dispatch中设置了默认的命名空间。
`$dispatcher->setDefaultNamespace('MyApp\\Tasks');`
但是呢，我有其他脚本的命名空间是这样的MyApp\Tasks\Test。
我这么运行我的脚本
`php run Test\\Mytask`
但当我们的脚本是双峰形式的时候，不主动输入Test和主动输入Test的结果就不一样了。
例如：
`php run Test\\MyTest`
以上代码运行的就是MyApp\Tasks\Test下的MyTestTask类的MainAction。
`php run MyTest`
以上代码运行的时MyApp\Tasks下的MytestTask类的MainAction。
同样的。
`php run Test\\my_test`
以上代码运行的就是MyApp\Tasks\Test下的my_testTask类的MainAction。
`php run my_test`
以上代码运行的就是MyApp\Tasks下的MyTestTask类的MainAction。
这种区分是不是对使用者略微有点不友好。
以下是我的项目
[https://github.com/limingxinleo/simple-subcontrollers.phalcon](https://github.com/limingxinleo/simple-subcontrollers.phalcon)

**Comment by sergeyklay** [comment]
@dreamsxin Could you please take a look?

**Comment by dreamsxin** [comment]
如果类名带了斜杆，就不会去转换的：
```zep
if !memstr(handlerName, "\\") {
	let camelizedClass = camelize(handlerName);
} else {
	let camelizedClass = handlerName;
}
```

**Comment by limingxinleo** [comment]
这样啊。。谢谢啦@dreamsxin 不过我总觉得这么设计不是很好 @dreamsxin

**Comment by dreamsxin** [comment]
这是为了满足不需要转的情况。
