### ISSUE TITLE
Service 'filter' wasn't found in DI

### ISSUE THREAD

**Issue by dellert** [phalcon/cphalcon#12594]
I have validation filters in model

```php
$validator = new Validation();
$validator->setFilters('text', 'trim');
```

After update Phalcon to version 3.0.3 I have this error: Service 'filter' wasn't found in the dependency injection container!

**Comment by Jurigag** [comment]
Then add it to DI.

**Comment by dellert** [comment]
Is this from 3.0.3 version?

**Comment by Jurigag** [comment]
No, it was always using filter service.

**Comment by dellert** [comment]
But what is the problem? on version 3.0.1 all works fine

**Comment by Jurigag** [comment]
Idk, post full code which causes a problem.

**Comment by dellert** [comment]
```php
public function validation()
{
        $validator = new Validation();
        $validator->setFilters('text', 'trim');

        $validator->add('text', new PresenceOf([
            'message' => 'Write text please'
        ]));

        return $this->validate($validator);
 }
```

Error throws in here

```php
return $this->validate($validator);
```

**Comment by Jurigag** [comment]
Yes. Just check my comment above. This is totally expected. Just add filter service to DI. Previously filters in model on 3.0.0 and 3.0.1 weren't working at all

**Comment by dellert** [comment]
@Jurigag can you show an example please?:)

**Comment by Jurigag** [comment]
Updated above how to add filter service.

**Comment by dellert** [comment]
@Jurigag thank you. Please, add to documentation!

**Comment by Jurigag** [comment]
Yea sure.

**Comment by dellert** [comment]
there is no info about adding filter component to DI:)

**Comment by Jurigag** [comment]
Cuz in factorydefault it's by default.
