### ISSUE TITLE
How to Use MongoDB In PHP Cli mode

### ISSUE THREAD

**Issue by dlairetang** [phalcon/cphalcon#12607]
In the product , We get the requirement that using redis queue as middleware and saving data into mongodb . But there's something mistake in it ,when i enter phalcon cli mode , i can realize that use the mongodb odm is useless and i solve it with PHP MongoDB Driver not Phalcon ODM.
Dev ENV：PHP7 & Phalcon 3.0.x
Thanks a lot

**Comment by Jurigag** [comment]
You just need to use classes from incubator

**Comment by david-duncan** [comment]
Per issue template 
> Questions should go to https://forum.phalconphp.com 

This can be closed as a question
