### ISSUE TITLE
Micro router does not properly abide by removeExtraSlashes

### ISSUE THREAD

**Issue by jesseforrest** [phalcon/cphalcon#12602]
### Expected and Actual Behavior

I have the following Phalcon code:
```
$app->get('/robots.txt', function() {
    // stub
});
```

What’s interesting is that `/robots.txt` endpoint works, but so does `/robots.txt/` and multiple slashes like `/robots.txt///////`

I expected `/robots.txt` to work, but not the others.

I’ve been toying with the router’s `removeExtraSlashes`, but that doesn’t seem to have an effect:
```
$di->set('router', function () {
    $router = new Router(false);

    // Stop remove trailing slashes automatically
    $router->removeExtraSlashes(false);

    // Use $_SERVER["REQUEST_URI"] instead of the default $_GET['_url']
    $router->setUriSource(Router::URI_SOURCE_SERVER_REQUEST_URI);
    return $router;
});
```

It seems that micro always removed extra slashes:
```
public function getRouter() -> <RouterInterface>
    {
        var router;

        let router = this->_router;
        if typeof router != "object" {

            let router = this->getSharedService("router");

            /**
             * Clear the set routes if any
             */
            router->clear();

            /**
             * Automatically remove extra slashes
             */
            router->removeExtraSlashes(true);

            /**
             * Update the internal router
             */
            let this->_router = router;
        }

        return router;
    }
```

I'm trying to understand how to use the Micro framework, but not allow the trailing slashes.

### Details

* Phalcon version: 
```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.3
Build Date => Dec 24 2016 19:16:23
Powered by Zephir => Version 0.9.5a-dev

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```
* PHP Version: 
```
PHP 7.0.15-1+deb.sury.org~trusty+1 (cli) (built: Jan 20 2017 09:16:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-1+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```
* Operating System: Ubuntu
* Installation type: package manager
* Server: Apache

**Comment by stamster** [comment]
Exactly - Micro app will remove slashes by default as you saw in the source code.
What's wrong with it? I guess you expected to actually rewrite routes on the fly in order to remove extra slashes? It doesn't work like that, it only treats your routes in a different manner, i.e. both `/login` and `/login/////` routes will match handler behind `/login` route.

**Comment by jesseforrest** [comment]
@stamster / @sergeyklay : Sure I can extend the default Router object to do whatever I want, but that seems like unnecessary additional overhead since there is a function `removeExtraSlashes` that is available on the Router object.

imo, it should be possible to use the Micro App out of the box to match a route to `/robots.txt`, but not `/robots.txt/`.

In order to accomplish this, it would seem natural to use `removeExtraSlashes(false)` and a route of `$app->get('/robots.txt', function() {});`

Perhaps I’m missing something though.  This isn’t a huge deal for me, but I do think it’s a bug since `removeExtraSlashes(false)` does not disable removing of extra slashes.

On similar lines I would actually recommend that future versions of Router do not automatically remove extra slashes by default.  I know that would create a breaking change, but just a recommendation.

I apologize if I’m missing something — I really do appreciate you guys taking the time to respond.

**Comment by stamster** [comment]
I guess this auto feature in Micro is being put in place in order to make it as easy as possible for REST API's development. In other words, to make it convenient to use just `app->method(do it...)` short syntax.

**Comment by Jurigag** [comment]
@stamster 

As you see service is already overloaded:

```php
$di->set('router', function () {
    $router = new Router(false);

    // Stop remove trailing slashes automatically
    $router->removeExtraSlashes(false);

    // Use $_SERVER["REQUEST_URI"] instead of the default $_GET['_url']
    $router->setUriSource(Router::URI_SOURCE_SERVER_REQUEST_URI);
    return $router;
});
```

But it still doesn't work because micro changes remove slashes anyway.

**Comment by Jurigag** [comment]
Well i see two ways to change this:

- remove this removeExtraSlashes(true)
- add some global variable to set slashes removal

**Comment by gguridi** [comment]
I think this can be easily solved by adding a setRouter method to the Micro object. So anyone can inject the router into the Micro application to bypass this removeExtraSlashes/clear call if they really don't want to have them, and it's backwards compatible.

So basically, if the Micro class implements:

```php
public function setRouter(RouterInterface router) {
  this->_router = router;
}
```
We can inject the router into the Micro application instead of letting it retrieve from the DI container, modifying it during the process.

```php
$di->set('router', function () {
    $router = new Router(false);

    // Stop remove trailing slashes automatically
    $router->removeExtraSlashes(false);

    // Use $_SERVER["REQUEST_URI"] instead of the default $_GET['_url']
    $router->setUriSource(Router::URI_SOURCE_SERVER_REQUEST_URI);
    return $router;
});

$micro = new \Phalcon\Mvc\Micro();
$micro->setRouter($di->getShared('router')); //This will avoid the default behaviour of router set by the Micro app while keeping backwards compatibility.
```

For v4 I would remove the clear/removeExtraSlashes call. Is the Micro responsibility to initiate the router?
