### ISSUE TITLE
phalcon create-controller --name="hep" --directory="app\frontend\controllers"  Phalcon DevTools (3.0.2)     Error: This command should be invoked inside a Phalcon project directory.

### ISSUE THREAD

**Issue by VijayTanikella** [phalcon/cphalcon#12601]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues
while creating a controller

phalcon create-controller --name="hep" --directory="app\frontend\controllers"

Phalcon DevTools (3.0.2)

  Error: This command should be invoked inside a Phalcon project directory.

shows up.
### Details

* Phalcon version: (`php --ri phalcon`)
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.1
Build Date => Aug 24 2016 10:49:16
Powered by Zephir => Version 0.9.4a-dev-7e304ba18c

* PHP Version: (`php -v`)   5.5.12
* Operating System: Windows 10
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any): NA
* Server: Nginx | Apache | Other: Apache
* Other related info (Database, table schema):  mysql

**Comment by sergeyklay** [comment]
This is Devtools issue. Could you please re-open this issue in [the corresponding repo](https://github.com/phalcon/phalcon-devtools)?
