### ISSUE TITLE
PhalconPHP incompatible with PHP7.1.1 ? Segfault at runtime

### ISSUE THREAD

**Issue by IvanDelsinne** [phalcon/cphalcon#12605]
I'm developing a few websites using PHP 7.x and PhalconPHP.
My workspace have been working fine and flawlessly for a long time until the latest PHP 7.1.1 update, where every call to `php` returns a segmentation fault if the phalcon.so module is enabled.

```
$~ php -v
[1]    4954 segmentation fault (core dumped)  php -v
```

With the `extension=phalcon.so` line commented out, I have this result running `php -v`:

```
$~ php -v
PHP 7.1.1 (cli) (built: Jan 18 2017 18:44:22) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.1, Copyright (c) 1999-2017, by Zend Technologies
```

### Details

* Phalcon version: 3.0.3
* PHP Version: 7.1.1
* Operating System: Arch-based Linux Manjaro v.4.4.45 x86-64
* Installation type: From the AUR and from source: same crash
* Server: Httpd

**Comment by Jurigag** [comment]
Phalcon doesn't work with php 7.1 yet.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/12055
