### ISSUE TITLE
Phalcon\Validation\Validator::Validate should accept a Phalcon\ValidationInterface as its first param instead of Phalcon\Validation 

### ISSUE THREAD

**Issue by tempcke** [phalcon/cphalcon#12603]
This not a 'bug' but really a request.
in:
https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validator.zep#L99
https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validatorinterface.zep#L44

the validate method should accept a Phalcon\ValidationInterface as its first param instead of Phalcon\Validation 

beings a ValidationInterface exists it seems silly not to type hint for that instead?  Would simplify unit testing of Validator derivatives.

**Comment by dreamsxin** [comment]
You can create new request fix this PR.
