### ISSUE TITLE
Forbidden error with given index like a controller

### ISSUE THREAD

**Issue by Mr-Eluzive** [phalcon/cphalcon#12611]
Hi
I have a small issue with my app on localhost. On a server it works normally but localy it throws me an error. The Forbidden Error appears when I write index like a controller in the url. So for example for url like this:
_localhost/project/_
It works great. But when I add index/ at the end it throws me something like this:
_You don't have permission to access /project/public/redirect:/project/public/index.html on this server._
Why does it happen? I have normal, standard .htaccess files.
/.htaccess

`<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule  ^$ public/    [L]
RewriteRule  (.*) public/$1 [L]
</IfModule>`

/public/.htaccess

`AddDefaultCharset UTF-8
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]
</IfModule>`

And here you have all of my routing settings in app/config/services.php:
` $router->add(
        '/{controller}/{id:\d+}',
        array(
            "action" => "index",
        )
    );
	
	$router->add(
        '/profile/view/{nazwa:/[a-zA-Z0-9_-]+}',
        array(
           'controller' => 'profile',
           'action'     => 'view'
        )
	);`

Does anyone have any idea? I will be very grateful.

Kamil

**Comment by Jurigag** [comment]
File permissions maybe?
