### ISSUE TITLE
URIs do not decode automatically as expected

### ISSUE THREAD

**Issue by jesseforrest** [phalcon/cphalcon#12614]
**Issue in Detail:**
For our use case, we didn't want to have to change our Apache conf to redirect the URI to a `_url` GET parameter.  Instead we wanted to use the alternative `Router::URI_SOURCE_SERVER_REQUEST_URI` approach, as described in https://docs.phalconphp.com/en/3.0.1/reference/routing.html .

For example, we wanted to do this:
```
$router->setUriSource(Router::URI_SOURCE_SERVER_REQUEST_URI);
```

Instead of the default:
```
$router->setUriSource(Router::URI_SOURCE_GET_URL);
```

However, when using `Router::URI_SOURCE_SERVER_REQUEST_URI` instead of `Router::URI_SOURCE_GET_URL`, the route is no longer automatically URI decoded.

Let’s say we have the following route:
```
$app->get('/images/{file}', function($file) use ($app) {
    echo $file;
});
```

I should be able to go to a URL with these URL encoded pieces:
https://example.com/images/example%402x.jpg

The `$file` variable should automatically be URL decoded to `example@2x.jpg`, but it's not.

This works fine with the `Router::URI_SOURCE_GET_URL` approach, because superglobals `$_GET` and `$_REQUEST` are already decoded.  However, it does not with `Router::URI_SOURCE_SERVER_REQUEST_URI`.

**Requests:**
1. `Router::URI_SOURCE_SERVER_REQUEST_URI` should behave identical to `Router::URI_SOURCE_GET_URL` and URL decode automatically.
2. Why are we limited to 2 specific route options (`URI_SOURCE_SERVER_REQUEST_URI` and `URI_SOURCE_GET_URL`)?  Why not just change `$router->setUriSource(int $uri_source)` to be `$router->setUri(string $uri)`?  Then developers can pass in the URI as desired.

**Workaround:**
Here is a temporary workaround that you can do if you don't want to change your Apache confs, but still need routing to properly URL decode. 

```
// Phalcon parses the `url` GET parameter by default to determine the route so we need to set it
$uri_parts = explode('?', $_SERVER['REQUEST_URI'], 2);
$_GET['_url'] = urldecode($uri_parts[0]);

// build the Phalcon micro app
$app = new Micro();
```

**Comment by Jurigag** [comment]
Phalcon is not decoding anything. It's to developer decode the url when he uses other url source.

**Comment by jesseforrest** [comment]
@Jurigag : Thanks for the feedback. I'm also not for any automated magic, but I am for consistency.  I'm not sure why the Apache `_url` GET parameter rewrite rule is the default recommended approach by Phalcon, since that does automagically get decoded.  I'm curious why it wasn't just something like `RewriteRule ^ index.php` and `REQUEST_URI` was used.

All I'm recommending is for consistency.  If the recommended methodology is automatically decoding, then shouldn't the `REQUEST_URI` method be be decoding?

There are also problems regarding leveraging `micro->handle($url)`. I would need to dig back into it again, but there were issues tied to it.  I believe it had something to do with when you get the route information it actually isn't correct still.

If nothing is going to get changed, I would like to request that the docs be updated to distinguish between the behavior of `Router::URI_SOURCE_GET_URL` and `Router::URI_SOURCE_SERVER_REQUEST_URI`.

**Comment by david-duncan** [comment]
100% for consistency or a documentation update

**Comment by sergeyklay** [comment]
@jesseforrest Hello. We will not be able to change it because it is one of the core things of the Phalcon. At least in the near future. This is not a difficult changes. However, if we introduce a change for this right now, we will definitely break existing applications.

So, right now this is mostly [documentation](https://github.com/phalcon/docs) issue. Could you please create docs related issues in the appropriate repository?

Thank you for contributing.

**Comment by stamster** [comment]
I'm not sure what issue are you having here? I'm not using Apache for years now, so I'm not sure what's wrong with htaccess rules etc.
But I can tell you for sure there aren't any issues with nginx and Router which reads from `REQUEST_URI` superglobal.

**Comment by jesseforrest** [comment]
Thanks @sergeyklay , I created an issue in the docs repo.

@stamster: I haven’t had a chance to repeat the issue for nginx, but I assume it would have a similar issue. If you follow the docs here:
https://docs.phalconphp.com/en/latest/reference/nginx.html

Create a route like this:
```
$app->get('/images/{file}', function($file) use ($app) {
    echo $file;
});
```

Lets say you used the default nginx `$_GET[‘_url’]` method:
```
location / {
        try_files $uri $uri/ /index.php?_url=$uri&$args;
    }
```

Hit this endpoint, https://example.com/images/example%402x.jpg , and output the contents of the `$file` variable.

Now lets say you used the alternate `$_SERVER['REQUEST_URI’]` method:
```
location / {
        try_files $uri $uri/ /index.php;
    }
```

Hit this endpoint again, https://example.com/images/example%402x.jpg , and output the contents of the `$file` variable.

My hypothesis is that you will see two different values for the `$file` variable, which is the inconsistency I'm trying to showcase.

**Comment by stamster** [comment]
Hmmm. I'm unable to make such setup right now, but have you tried to use this setup alongside with Router set to read from REQUEST_URI?

**nginx conf:**
```nginx
location / {
    try_files $uri $uri/ /index.php$is_args$query_string;
}
```

For sure this is required to read POST etc. from sub-controllers, but with Micro auto routing I'm not sure whenever it'll make any difference.
