### ISSUE TITLE
cache->save('key',$value,6) the time is not valid

### ISSUE THREAD

**Issue by limingxinleo** [phalcon/cphalcon#12612]
* php code
```php
        $cache = di('cache');
        if (empty($cache->get('CACHE:TEST:1', 6))) {
            $cache->save('CACHE:TEST:1', date("Y-m-d H:i:s"));
        }
        dump($cache->get('CACHE:TEST:1'));

        if (empty($cache->get('CACHE:TEST:2'))) {
            $cache->save('CACHE:TEST:2', date("Y-m-d H:i:s"), 6);
        }
        dump($cache->get('CACHE:TEST:2'));
```
* php result
~~~
string(19) "2017-02-10 15:00:39"
string(19) "2017-02-10 15:00:08"
~~~
### Details
The first code ,the time is valid.But the second code, the time is not valid.

* Phalcon version: (3.0.3)
* PHP Version: (7.0.15)
* Operating System:
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
And how you exactly know this is phalcon issue?

**Comment by limingxinleo** [comment]
My question is when I use 
$cache->get(key,second)
the result is ok.
But when I use $cache->save(key,value,second);$cache->get(key),
the result is error.Is the second not the expiretime?
My cache engine is file.

**Comment by limingxinleo** [comment]
@dreamsxin 麻烦再帮我看看这个吧，当我使用cache的时候，超时时间不能在创建缓存的时候设置

**Comment by dreamsxin** [comment]
@limingxinleo 用文件存储，超时时间确实是无法在创建的时候指定，因为文件存储中没有记录`lifetime`，所以方法`save`的第三个参数lifetime是没有用的。当然在同一个实例中，是可以通过对类的属性赋值获得。
@Jurigag When use file\ save cache, Whether store lifetime in the data file.

**Comment by limingxinleo** [comment]
@dreamsxin 我去看了源码，确实发现了这个问题。那以后这里可能会修改么？

**Comment by dreamsxin** [comment]
目前应该不会修改
