### ISSUE TITLE
\Phalcon\Config::offsetUnset property not unset

### ISSUE THREAD

**Issue by cottton** [phalcon/cphalcon#12613]
`Phalcon\Config::offsetUnset` does not unset the propery - it sets it to `null`.
I saw here https://github.com/phalcon/cphalcon/blob/master/phalcon/config.zep#L147
that the unset has commented out. Was there a reason for that?

Problem: comparing 2 configs `::toArray` are not the same (just found that out while writing a unit test).

**Test:**

    $config = new \Phalcon\Config(['foo' => 'bar', 'bar' => 'baz']);
    $config->offsetSet('baz', 1);
    unset($config['baz']);
    $config->offsetUnset('foo');
    var_export($config->toArray());

**Expected:**

    array (
        'bar' => 'baz',
    ) 

**Actual:**

    array (
        'foo' => NULL,
        'bar' => 'baz',
        'baz' => NULL,
    )
 
_I know `isset(null)` it false but having a container that holds data i would expect that unset actually unsets the property._ 

### Details

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.1
Build Date => Oct  4 2016 18:23:02
Powered by Zephir => Version 0.9.4a-dev-7e304ba18c

PHP 7.0.11

**Comment by Jurigag** [comment]
As i remember it's not possible to unset property from objects in zephir for some reason.

**Comment by cottton** [comment]
I see. 
If anybody has the same problem then just overwrite `Phalcon\Config` with

    public function offsetUnset($index)
    {
        parent::offsetUnset($index);
        unset($this->{$index});
    }

Btw - is it possible to add that fix directly into phalcon and let PHP do the work?

**Comment by Jurigag** [comment]
What you mean directly into phalcon? See above, it's not possible.

**Comment by cottton** [comment]
I mean a `Config.php` in `scripts/Phalcon/` that overwrites the method.

**Comment by Jurigag** [comment]
What you mean? It can't be in repository. Just add such an class to your app if you need fix.
