### ISSUE TITLE
php7.dll Not Found!

### ISSUE THREAD

**Issue by AnthonyDS** [phalcon/cphalcon#12625]
OpenServer 5.2.2
Phalcon 3.0.3 - Windows x64 for PHP 7.0.0 NTS (vc14) 
Windows 7 x64 Ultimate

php.ini
   extension=php_phalcon.dll

php7.dll Not Found!

**Comment by Jurigag** [comment]
Then add it.

**Comment by AnthonyDS** [comment]
And where can I get it?

**Comment by Jurigag** [comment]
I don't know. You should already have it installed if you have php7. What produces this error? Any steps to reproduce? Follow pls issue template.
