### ISSUE TITLE
CheckToken doesn't work sometimes

### ISSUE THREAD

**Issue by Myrai** [phalcon/cphalcon#12624]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**
Hello! https://github.com/Myrai/issuetest if we go url '/login', and submit form.

We doesn't get successful checktoken... 

Why?! And, how fix it?!

**1 favicon on place. 2. post data and session data IDENTICAL, and HAVEN'T different with same.**

### Details

* Phalcon version: (`php --ri phalcon`)
3.0.3
* PHP Version: (`php -v`)
7.0.8
* Operating System: windows
* Installation type: installing via package manager
* Zephir version (if any):
* Server: Apache 
* Other related info (Database, table schema): session adapter Redis in php.ini. 
Without database and table.

**Comment by Jurigag** [comment]
And where you have session adapter set?

**Comment by Myrai** [comment]
Redis, in php ini.
But if route at one action - all normal.
Forgot about session adapter. so sorrow.

**Comment by Myrai** [comment]
**Jurigag** session start in action getlogin. in index
``$di->getShared('session');

All of that.

**Comment by Jurigag** [comment]
It doesn't start session - https://github.com/phalcon/cphalcon/blob/master/phalcon/session/adapter.zep#L46

**Comment by Myrai** [comment]
Yes, but i don't understand why need on every action start session?
Isn't perfomance. :-(

**Comment by Myrai** [comment]
Sorry, but
Get session interface?
https://github.com/phalcon/cphalcon/blob/master/phalcon/security.zep#L374
Get session data?
https://github.com/phalcon/cphalcon/blob/master/phalcon/security.zep#L401
why they doesn't work?

**Comment by Myrai** [comment]
thanks, There isn't issue.

**Comment by Jurigag** [comment]
Yes you need to set it ton every action - this is how php works - those actions are completely other requests and other appliaction states, objects etc, then don't know anything about them. Just set session service properly on di.
