### ISSUE TITLE
All download links are in trouble

### ISSUE THREAD

**Issue by aunhappy** [phalcon/cphalcon#12636]
I downloaded php-phalcon.dll on https://phalconphp.com/en/download/windows ,but it doesn't work .when I click 'download' ,the url turn to https://phalconphp.com/en/download/windows# .More than one # .I want to download Phalcon 3.0.3 - Windows x64 for PHP 7.0 NTS (vc14) .please help me.Thanks!

**Comment by niden** [comment]
This has been fixed... well just now :)

Thanks for reporting this. In the future if you don't mind, please report website issues to the website repository :)

Thanks again

**Comment by aunhappy** [comment]
@niden Great !thank you
