### ISSUE TITLE
Question about afterSave

### ISSUE THREAD

**Issue by kamenevn** [phalcon/cphalcon#12649]
Hello!
I have model "transactions" and related models "operations".
One transactions have many operations.
Now I use afterSave hook to update user balance (add operations sum to cache), but afterSave hook run on "transaction model" save.
I need afterSave run after all "operations" save.

How can I do that?

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
