### ISSUE TITLE
Paginator with large tables. 

### ISSUE THREAD

**Issue by trentramseyer** [phalcon/cphalcon#12642]
A basic employees table with 300,000 records uses quite a bit of memory and slows down the response time.  As if the Paginator is looping through every record. This example would use about 90MB of memory. 

```php
	
use Phalcon\Paginator\Adapter\Model as Paginator;

$paginator = new Paginator(
    [
        "data"  => Employees::find(),
        "limit" => 10,
        "page"  => 1,
    ]
);

```

**Comment by grigoriygithub** [comment]
Use QueryBuilder Adatper.
```php
 use Phalcon\Paginator\Adapter\QueryBuilder;

 $builder = $this->modelsManager->createBuilder()
                 ->columns('id, name')
                 ->from('Robots')
                 ->orderBy('name');

 $paginator = new QueryBuilder(
     [
         'builder' => $builder,
         'limit'   => 20,
         'page'    => 1,
     ]
 );
```

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
