### ISSUE TITLE
Add methods to interfaces

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12676]
This is list for Phalcon 4.0.0 with missing methods which should be in interfaces, feel free to add new comments here or discuss this list, i suggest one point - one interface with missing methods.

I ignored `Phalcon\Http` namespace cuz it's planned to switch to PSR7 anyway.

- [ ] `Phalcon\Annotations\AdapterInterface` - read, write
- [ ] `Phalcon\Cache\BackendInterface` - increment, decrement, flush
- [x] `Phalcon\Cli\Router\RouteInterface` - delimiter, getDelimiter
- [x] `Phalcon\Cli\DispatcherInterface` - setOptions, getOptions
- [x] `Phalcon\Db\AdapterInterface` - fetchColumn, insertAsDict, updateAsDict
- [x] `Phalcon\Db\DialectInterface` - registerCustomFunction, getCustomFunctions, getSqlExpression
- [x] `Phalcon\Di\ServiceInterface` - getParameter, isResolved
- [x] `Phalcon\Events\ManagerInterface` - hasListeners
- [x] `Phalcon\Mvc\Model\Query\BuilderInterface` - distinct, getDistinct, forUpdate, offset, getOffset
- [x] `Phalcon\Mvc\Model\Transaction\ManagerInterface` - setDbService, getDbService, setRollbackPendent, getRollbackPendent
- [x] `Phalcon\Mvc\Model\CriteriaInterface` - distinct, leftJoin, innerJoin, rightJoin, groupBy, having, cache, getColumns, getGroupBy, getHaving
- [x] `Phalcon\Mvc\Model\ManagerInterface` - isVisibleModelProperty, keepSnapshots, isKeepingSnapshots, useDynamicUpdate, isUsingDynamicUpdate, addHasManyToMany, existsHasManyToMany, getRelationRecords, getHasManyToMany, registerNamespaceAlias, getNamespaceAlias
- [x] `Phalcon\Mvc\Model\MessageInterface` - setModel, getModel, setCode, getCode
- [x] `Phalcon\Mvc\Model\QueryInterface` - getSingleResult, setBindParams, getBindParams, setBindTypes, setSharedLock, getBindTypes, getSql
- [x] `Phalcon\Mvc\Model\RelationInterface` - getParams
- [x] `Phalcon\Mvc\Model\ResultsetInterface` - setHydrateMode, getHydrateMode, getMessages, update, delete, filter
- [x] `Phalcon\Mvc\ModelInterface::getModelsMetaData`
- [x] `Phalcon\Session\AdapterInterface` - setId, status
- [x] `Phalcon\Validation\MessageInteraface` - getCode, setCode
- [x] `Phalcon\CryptInterface` - setPadding

**Comment by niden** [comment]
* Phalcon\Annotations\AdapterInterface - read, write <- Could not find that
* Phalcon\Cache\BackendInterface - Cache will be refactored

**Comment by niden** [comment]
This has been addressed
