### ISSUE TITLE
Annotation cache dependency

### ISSUE THREAD

**Issue by HanXHX** [phalcon/cphalcon#12675]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

Currently, annotations (cache) adapter:
* instantiates backend cache [Redis in phalcon incubator](https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Annotations/Adapter/Redis.php#L72)
* uses low-level function (apc_fetch) in [apc.zep](https://github.com/phalcon/cphalcon/blob/master/phalcon/annotations/adapter/apc.zep#L67).

This mode is not very extensible (new backend = new class). My request is a new generic backendcache adapter.

Pros:
* Flushing cache can be done easily.
* All Backend Cache is compatible.
*  "One ring to rule them all".
* Can remove few parts of old apc* functions (without apcu-bc in php7).

Cons:
*  "One ring to rule them all"... one more ring

Something like:

```php
use Phalcon\Annotations\AdapterInterface;
use Phalcon\Annotations\Adapter;
use Phalcon\Cache\BackendInterface as Cache;

class Custom extends Adapter implements AdapterInterface
{
    /**
     *
     * @var Cache
     */
    protected $cache;

    public function __construct(Cache $cache)
    {
        $this->cache = $cache;
    }

    public function read($key)
    {
        return $this->cache->get($this->prepareKey($key));
    }

    public function write($key, $data)
    {
        $this->cache->save($this->prepareKey($key), $data);
    }

    protected function prepareKey(string $key)
    {
        return strval($key);
    }
}
```

### Details

* Phalcon version: 3.0.3
* PHP Version: 7.0.13

**Comment by Jurigag** [comment]
As i remember @sergeyklay was planning to make this change in 4.0.0 so we have only `Phalcon\Cache\Backend\Adapter` classes and other components which requires caching stuff use this namespace instead of creating a new one.
