### ISSUE TITLE
SQL generation by model (entity) like as on Symfony

### ISSUE THREAD

**Issue by coll3ctor** [phalcon/cphalcon#12671]
Hello, guys!

When you add that incredible feature ?

It very useful and comfortable. I mean in Symfony: php app/console doctrine:schema:update. Also, Symfony has migrations, etc.

**Comment by Jurigag** [comment]
Phalcon has migrations too, doesn't have though generating database from doctrine. Also it's not symfony feature, it's doctrine feature.

**Comment by coll3ctor** [comment]
@Jurigag Yes, you are right, it is feature by Doctrine, but no matters.

And if Phalcon got this feature - this will be really cool! It is just one option, which not exist in Phalcon, comparing with Symfony (excepting services on Symfony).

Hope, it will be!

**Comment by Jurigag** [comment]
Yea, but it's many work, need to better model annotations, reader for them and generating query. Some work to do. About migrations it's already in devtools - https://github.com/phalcon/phalcon-devtools

**Comment by coll3ctor** [comment]
@Jurigag May be, simplest way is integrate with Doctrine ?

And annotations can be as option. If you annotate fileds of your entity - you can generate SQL. Reflections give simple way to parse with annotations, i think it is not very hard, but it generally should be very flexible.

**Comment by Jurigag** [comment]
You can always use doctrine :) No problem there.
