### ISSUE TITLE
Bug request method hasFiles()

### ISSUE THREAD

**Issue by KlassT** [phalcon/cphalcon#12687]
If there is form with enctype multipart/form-data and file input, method hasFiles() need to return TRUE then files is upload and FALSE then else.
But method hasFiles() always return TRUE then form has enctype.

Form:
```PHP
$form = new \Phalcon\Forms\Form();
$form->add(new \Phalcon\Forms\Element\File('file'));
```

View:
```PHP
echo $this->tag->form('url/path', 'enctype' : 'multipart/form-data');
echo $form->render('file');
echo $this->tag->submit_field('Добавить');
echo $this->tag->endForm();
```

```PHP
var_dump($this->request->hasFiles()); // Always TRUE
```

* Phalcon version: any
* PHP Version: any
* Operating System: any
* Installation type: any
* Zephir version (if any): any
* Server: Apache (but as for me any)

**Comment by KlassT** [comment]
Sorry for my english

**Comment by gguridi** [comment]
@KlassT The method hasFiles by default detects if the form submit contains files or not. Even if you have not uploaded a file, the request comes with an empty file information array so the validation is to true (check $_FILES for example).

If you want to check whether the request actually comes with a file or not then you must pass a parameter TRUE to that method:

```php
var_dump($this->request->hasFiles(true)); //true if the file has been uploaded, false if it is empty.
```
