### ISSUE TITLE
[4.0.0] Returning array in handler

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12697]
Since from Phalcon 3 when returning string is causing to set it as content i would suggest for phalcon 4 to add support for returning array too. Then it would just calls setJsonContent internally.

**Comment by makerlabs** [comment]
I really like the symfony framework approach more I would go for deprecating the setJsonContent and use:

```php
public function someAction()
{
   return new \Phalcon\Http\Response\Json(array('some' => 'data'));
}
```
Or (actually ur case would have a small problem here)
```php
public function someAction()
{
   return new \Phalcon\Http\Response\Json(new SomeObject());
}
```

And as for the return array set the view variables instead.
