### ISSUE TITLE
Restart php-fpm failed after installing phalcon

### ISSUE THREAD

**Issue by alawnchen** [phalcon/cphalcon#12701]
My php's version is 7.1.2. I have found restarting failed after installing phalcon. The version of phalcon installed is 3.0.4. Terminal had shown me some errors' output similar to the following:
```
Starting php-fpm /etc/init.d/php-fpm: line 53: 32553 Segmentation fault      (core dumped) $php_fpm_BIN --daemonize $php_opts
 failed
```
Is it a bug? And how can I solve this problem?

**Comment by Jurigag** [comment]
Phalcon doesn't work with php 7.1 you need to use php 7.

**Comment by alawnchen** [comment]
@Jurigag Thank you for your help!
