### ISSUE TITLE
View partials do not properly maintain scope

### ISSUE THREAD

**Issue by jesseforrest** [phalcon/cphalcon#12705]
### Expected and Actual Behavior

Typically in MVC frameworks, each partial view gets variables in an encapsulated scope.  Therefore if a variable is changed it will not affect any other view partial that used that same variable name.  I'm noticing different behavior with Phalcon.  There may be performance reasons for doing it this way, but unfortunately larger teams can not work this way since they are dirtying other view partials.  I think there should be an option (if one doesn't already exist) to make sure each partial gets its own scope of variables.

For example, let's say we have the following controller:

```php
class ExampleController extends Phalcon\Mvc\Controller
{
   public function exampleAction()
   {
      $this->view->partial('example/index', ['count' => 1]);
   }
}
```

Now lets say we have the follow `example/index.phtml` view:

```php
<?= $count; ?>
<?php $this->view->partial('example/subIndex', ['items' => ['x', 'y', 'z']]); ?>
<?= $count; ?>
```

Let's then say this is the contents of `example/subIndex.phtml`:

```php
<?php
$count = count($items);
echo $count;
```

I would expect that `subIndex` would have it's own scope, so that `$count` does not override the parent `$count` variable.  

The desired output should be:
```
131
```

The actual output is:
```
133
```

### Details

* Phalcon version: 3.0.3
* PHP Version: 7.0.16
* Operating System: Linux
* Server: Apache

**Comment by Jurigag** [comment]
I think there were actually created the same issue here not long ago.

**Comment by Jurigag** [comment]
Oh there it is - https://github.com/phalcon/cphalcon/issues/12648 similar issue

**Comment by sergeyklay** [comment]
I hope we managed to sort out with this issue finally here https://github.com/phalcon/cphalcon/pull/13606. All necessary changes are already in the appropriate branch. We will try to release the next version in the coming days.  Thank you for your patience, the report, and for helping us make Phalcon better.
