### ISSUE TITLE
ORM cache issue

### ISSUE THREAD

**Issue by addinm** [phalcon/cphalcon#12717]
Docs say:

> When `Phalcon\Mvc\Model` requires a service to cache resultsets, it will request it to the Dependency Injector Container with the convention name `"modelsCache"`.

AND 

```php
// Use the 'cache' service from the DI instead of 'modelsCache'
$products = Products::find(
    [
        "cache" => [
            "key"          => "my-cache",
            "cacheService" => "cache",
        ],
    ]
);
```

If you use "cacheService" parameter, the following error occurs:

**"Fatal error: Class 'modelsCache' not found in"**

**Comment by grigoriygithub** [comment]
https://docs.phalconphp.com/en/latest/reference/models-cache.html#caching-resultsets
Set modelsCache in your DI for use caching in the ORM
`
<?php

use Phalcon\Cache\Frontend\Data as FrontendData;
use Phalcon\Cache\Backend\Memcache as BackendMemcache;

// Set the models cache service
$di->set(
    "modelsCache",
    function () {
        // Cache data for one day by default
        $frontCache = new FrontendData(
            [
                "lifetime" => 86400,
            ]
        );

        // Memcached connection settings
        $cache = new BackendMemcache(
            $frontCache,
            [
                "host" => "localhost",
                "port" => "11211",
            ]
        );

        return $cache;
    }
);
`

**Comment by grigoriygithub** [comment]
@addinm 
Try: 
```php
$products = Products::find(
    [
        "cache" => [
            "key"          => "my-cache",
            "service" => "cache",
        ],
    ]
);
```

**Comment by sergeyklay** [comment]
Fixed in the docs repo. Thank you
