### ISSUE TITLE
bug or feature? the \Phalcon\Mvc\View load file by iteration?

### ISSUE THREAD

**Issue by GanLuo96214** [phalcon/cphalcon#12718]
the \Phalcon\Mvc\View load file by iteration?

when I access url : /index/index.

the \Phalcon\Mvc\View will use "webroot/view/index/index.volt" and "webroot/view/index.volt".

when "webroot/view/index.volt" doesn't exists and "webroot/view/index/index.volt" exists it will use "webroot/view/index/index.volt".

when "webroot/view/index.volt" exists and "webroot/view/index/index.volt" exists. it will use "webroot/view/index.volt".

it maybe can solve some problem but it will fired (new EventsManager())->attach("view:notFoundView"), and it's confuse.

**Comment by GanLuo96214** [comment]
the matter is the \Phalcon\Mvc\View load file work will fire (new EventsManager())->attach("view:notFoundView")

**Comment by Jurigag** [comment]
It's just hierarchical rendering. https://docs.phalconphp.com/pl/latest/reference/views.html#hierarchical-rendering

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
