### ISSUE TITLE
Cache system problem

### ISSUE THREAD

**Issue by pedped** [phalcon/cphalcon#12714]
Hi, please consider these codes

    $frontCache = new FrontData([
        'lifetime' => \Simpledom\Core\Classes\Config::GetCacheLifetime()
    ]);

    // Create the Cache setting redis connection options
    $cache = new Redis($frontCache, [
        'host' => "127.0.0.1"
        'port' => 2020,
        'persistent' => false,
        'index' => 0,
    ]);

    // consider redis take down befor executing the following line
    $cache ->save('my-data', [1, 2, 3, 4, 5])
the problem with the save method is that it does not throw any catchable exception and It only shows : "Could not connect to the Redisd server" and do not allow the application to continue

please consider adding exception for save, get, etc methods and also make function to know whether the Redis is Up or Down

regards
comments
* Phalcon version: 3.0.2
* PHP Version: 5.5.9
* Operating System: Ubunto 14.0.4
* Installation type: Compiling from source 
* Server:Apache

**Comment by Jurigag** [comment]
But it's throwing an exception - `Phalcon\Cache\Exception` https://github.com/phalcon/cphalcon/blob/master/phalcon/cache/backend/redis.zep#L124

**Comment by pedped** [comment]
it only throws in connect, now think a situation that you loose connection between _connect() and save() functions. also in the documentation of phalcon, never stated that we have to using connect function before save :


// Cache data for 2 days
$frontCache = new FrontData(
    [
        "lifetime" => 172800,
    ]
);

// Create the Cache setting redis connection options
$cache = new Redis(
    $frontCache,
    [
        "host"       => "localhost",
        "port"       => 6379,
        "auth"       => "foobared",
        "persistent" => false,
        "index"      => 0,
    ]
);

// Cache arbitrary data
$cache->save("my-data", [1, 2, 3, 4, 5]);

// Get data
$data = $cache->get("my-data");

**Comment by Jurigag** [comment]
Save is always calling connect if not connected, if lost connection then find out why it's lost, we can't ping redis each time before doing save/get.
