### ISSUE TITLE
Failed to authenticate with the Redisd server

### ISSUE THREAD

**Issue by limingxinleo** [phalcon/cphalcon#12736]
```php
use Phalcon\Cache\Backend\Redis as BackRedis;
$cache = new BackRedis(
                $frontCache,
                [
                    'host' => $config->redis->host,
                    'port' => $config->redis->port,
                    'auth' => $config->redis->auth,
                    'persistent' => $config->redis->persistent,
                    'index' => $config->redis->index,
                    'prefix' => ':cache:',
                    'statsKey' => '_PHCM',
                ]
            );
```
### Details
When I use cache service by redis and my redis auth is null.
Failed to authenticate with the Redisd server

#### phalcon/cache/backend/redis.zep
``` zep
		if fetch auth, options["auth"] {
			let success = redis->auth(auth);

			if !success {
				throw new Exception("Failed to authenticate with the Redisd server");
			}
		}
```
I think, if auth is null ,not execute redis->auth(auth);

* Phalcon version: 3.0.4
* PHP Version: 7.0.15
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open new issue if the problem appears again. Thank you for contributing.
