### ISSUE TITLE
variable in volt template confilct with variable in vuejs template

### ISSUE THREAD

**Issue by wnewstar** [phalcon/cphalcon#12732]
this is html code block, {{tab.content}} is vuejs variable, but it will parse by volt, how to handle it?
```html
<section class="main">
    <el-tabs id="tabs" type="border-card" v-model="tab">
        <el-tab-pane
            v-for="tab of tabs"
            v-bind:key="tab.name"
            v-bind:name="tab.name"
            v-bind:label="tab.label"
            v-bind:closable="tab.close">
            {{tab.content}}
        </el-tab-pane>
    </el-tabs>
</section>
```

**Comment by mzf** [comment]
You can change [delimiters in Vue](https://vuejs.org/v2/api/#delimiters)

**Comment by wnewstar** [comment]
If you use others components libarays, change delimiters can not handle this confilict.
In Smarty, tag {literal} can use for not parse code block, if volt has tag like {literal}?

**Comment by Jurigag** [comment]
Then you can create function in volt to output `{{ }}`

**Comment by wnewstar** [comment]
You suggestion is a way to solve this confilict.
I use php template engine `Phalcon\Mvc\View\Engine\Php` to solve this problem.
```php
$view->registerEngines(['.html' => 'php', '.volt' => 'volt']);
```

**Comment by Jurigag** [comment]
Volt is imho better, you have two ways to do this currently - change in vuejs delimiters, or use function like this in phalcon:

```
$compiler = $volt->getCompiler();
                            $compiler->addFunction('strftime', 'strftime');
                            $compiler->addFunction(
                                'vue',
                                function ($resolvedArgs, $exprArgs) use ($compiler) {
                                    $value = $compiler->expression($exprArgs[0]['expr']);

                                    return '"{{".'.$value.'."}}"';
                                }
                            );
```

and then just {{ vue('tab.content') }} will output in html `{{ tab.content }}`

**Comment by wnewstar** [comment]
@Jurigag
Thank you, I will try you suggestion.

**Comment by andmm** [comment]
This is really necessary for javascript client side templates. I think Laravel has an elegant solution, you can escape the template parser by putting an @ symbol in front of the statement like this:

`<h1> @{{ javascript_var }} </h1>`

Much cleaner IMO.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/1253

**Comment by ronbon** [comment]
new Vue(
{
	data: 
	{ `foo:` "",
        }
});
Vue variable within volt: `<span v-text="foo"></span>`
