### ISSUE TITLE
Phalcon 3.1 Model Changed Fields is not right for numeric string

### ISSUE THREAD

**Issue by leupom** [phalcon/cphalcon#12735]
Hi, I just test the Phalcon 3.1 Model Changed Fields behavior.
It is not right for numeric string, for example:

a int type column named "is_disabled" with value 1,
after findFirst in PHP, it has converted to string type '1'.

now I invoke $model->is_disabled = 1, then getChangedFields and hasChanged contains the "is_disabled" field.

I suggest Model Changed Fields use rules:
**if model value or snapshot value is null or empty string, using type operator  !==  for changed,
elses using normal operator  !=.**
@bilikaz

Thanks, Phalcon Team.
@sergeyklay which IDE when you write Zephir code, I would contribute some code to Phalcon, it is an essential framework.
@dreamsxin PhpStorm 或其它 IDE 下能写 Zephir 代码吗？我是重度的 IDE 依赖者，不会用 vim 之类的编辑器，感觉很麻烦。你平时用什么开发环境提交 Zephir 代码的？

**Comment by dreamsxin** [comment]
我目前的话在用 Atom，在 Ubuntu 以及 Mac 下结合 GitHub Desktop 还是挺方便的。

**Comment by sergeyklay** [comment]
@leupom Could you please provide script to reproduce

**Comment by dreamsxin** [comment]
@sergeyklay https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L3946, The values extracted from the database, It's always a string. So int `0` !== string `'0'`

**Comment by Jurigag** [comment]
No, it's not always string, it's only your problem that you are not using mysqlnd.

**Comment by Izopi4a** [comment]
```
$class = new \Phalcon\Db\Adapter\Pdo\Mysql([
                'host'     => ......
               .........
                "options"  => [
                    \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
                    \PDO::ATTR_PERSISTENT         => false,
                    \PDO::ATTR_EMULATE_PREPARES   => false, <----- this one
                    \PDO::ATTR_STRINGIFY_FETCHES  => false <--- and this one
                ]
            ]);
```

**Comment by sergeyklay** [comment]
@dreamsxin What about this https://forum.phalconphp.com/discussion/15529/bug-regarding-getchangedfields-and-haschanged#C45969

**Comment by Jurigag** [comment]
He wrote, do some dirty check to check if it's null or empty string...

**Comment by sergeyklay** [comment]
Even in column real string with zero?

**Comment by dreamsxin** [comment]
My suggestion is that automatic conversion of data taken from the database, based on the field type, When `enable_strict` is true.

**Comment by leupom** [comment]
@sergeyklay @Jurigag @Izopi4a
I mean if a value in Model Snapshot is a numeric or numeric string, the Changed behavior is not precise. Like these:
snapshot value is string '1', when change model field value to int 1;
snapshot value is int 1, when change model field value to string '1';

snapshot value is string '1.20', when change model field value to float 1.2;
snapshot value is float 1.2, when change model field value to string '1.20';

If using !== , these changed are true, but not right in PHP weakly-typed way.
So I suggest just using !== , if model field or snapshot value is null or empty string, others keep != , it would satisfy most cases.

**Comment by hakimio** [comment]
@leupom If you simply configure your Mysql adapter with the options shown by lzopi4a your integers will be integers instead of strings to begin with.
The Phalcon behavior is correct. This should be closed.
