### ISSUE TITLE
Ubuntu 16 installation

### ISSUE THREAD

**Issue by harrywebster** [phalcon/cphalcon#12734]
Attempted to install Phalcon for PHP 7.0 Ubuntu 16 (fresh install) using:

```
curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
```

... reports a successful installation however the package php7.0-phalcon cannot be found.

After a quick dig i found the URL in `/etc/apt/sources.list.d/phalcon_stable.list`, `https://packagecloud.io/phalcon/stable/ubuntu` is a 404.

I manually downloaded `php7.0-phalcon_3.0.4-1_amd64.deb` and it worked like a charm.

**Comment by sergeyklay** [comment]
This is phalcongelist/packagecloud issue. Could you please re-open this issue in [the corresponding repo](https://github.com/phalcongelist/packagecloud)?

**Comment by harrywebster** [comment]
Done
