### ISSUE TITLE
Scoping issues in volt templates

### ISSUE THREAD

**Issue by fichtner** [phalcon/cphalcon#12744]
### Expected and Actual Behavior

On Phalcon 3.0.x and PHP 5.6, scoping works as expected, variables not getting overwritten / mashed up, macro definitions not being errored out as already defined.

Since using the same Phalcon and PHP 7.0, the scoping seems to not exist anymore, variables and macros being declared in a single global scope leaving partial templates with variable values of other or top templates.

Is anyone aware of such issues?

### Details

* Phalcon version: 3.0.4
* PHP Version: 7.0.16
* Operating System: FreeBSD / OPNsense
* Installation type: package manager
* Server: Lighttpd

**Comment by Jurigag** [comment]
Duplicate of https://github.com/phalcon/cphalcon/issues/12648

**Comment by fichtner** [comment]
I don't know. We've done extensive testing of PHP 7.0 while we were still using PHP 5.6 in production and this seemed to be an issue only with PHP 7.0.

**Comment by Jurigag** [comment]
Yes it's issue only with php 7, as i wrote, it's duplicate of above issue.

**Comment by fichtner** [comment]
Alright, thanks, closing this to watch the other ones. :)
