### ISSUE TITLE
Default values and snapshot

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12745]
### Expected and Actual Behavior

Right now default values are never set as properties to model, causing that they are always returned as changed in getChangedFields() after saving model. This is caused by this line https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L3938 Not sure really how to solve this. Maybe here add second conidtion if it's not part of default fields?

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
array (size=7)
  'name' => string 'asd' (length=3)
  'type' => string 'mechanical' (length=10)
  'year' => null
  'datetime' => string '1952-01-01 00:00:00' (length=19)
  'deleted' => null
  'text' => string 'text' (length=4)
  'id' => string '127' (length=3)
array (size=3)
  0 => string 'name' (length=4)
  1 => string 'year' (length=4)
  2 => string 'deleted' (length=7)
array (size=7)
  'id' => string '127' (length=3)
  'name' => string 'asds' (length=4)
  'type' => string 'mechanical' (length=10)
  'year' => null
  'datetime' => string '1952-01-01 00:00:00' (length=19)
  'deleted' => null
  'text' => string 'text' (length=4)
```
> Provide minimal script to reproduce the issue

```php
$di = new FactoryDefault();
$di->set(
    'db',
    function () {
        $adapter = new \Phalcon\Db\Adapter\Pdo\Mysql(
            [
                'host'     => 'localhost',
                'username' => 'root',
                'password' => '',
                'dbname'   => 'phalcon_test',
                'options'  => [
                    PDO::ATTR_EMULATE_PREPARES   => false,
                    PDO::ATTR_STRINGIFY_FETCHES  => false,
                    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
                ],
                'charset'  => 'utf8',
            ]
        );

        return $adapter;
    }
);

class Robots extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
        $this->keepSnapshots(true);
    }
}

$robot = new Robots();
$robot->name = "asd";
$robot->type = "mechanical";
$robot->text = "text";
$robot->datetime = "1952-01-01 00:00:00";
$robot->save();
$robot->name = "asds";
var_dump($robot->getSnapshotData());
var_dump($robot->getChangedFields());
var_dump($robot->toArray());
```
### Details

* Phalcon version: 3.1.0
* PHP Version: 7.0.13
* Operating System: ubuntu 14.0.4
* Installation type: zephir
* Zephir version (if any):Version 0.9.6a-dev-1bad5e7742
* Server: apache
* Other related info (Database, table schema): phalcon_test database

**Comment by gguridi** [comment]
What do you think about merging the default values within the snapshot, in:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L3832

```php
$reflection = new \ReflectionClass(get_called_class());
$defaults = $reflection->getProperties(\ReflectionProperty::IS_PUBLIC);
let this->_snapshot = array_merge($defaults, snapshot);
```

I've mixed zephir with php, but it's just to show the idea.

**Comment by Jurigag** [comment]
The problem is that we never set an field to model, maybe if attribute is default value and it's doesn't exists on model set it to default value(like null?)
