### ISSUE TITLE
Model getChangedFields() returning empty array

### ISSUE THREAD

**Issue by garyrutland** [phalcon/cphalcon#12743]
When updating a model I'm doing some checks on the changed fields which was working up until `3.1.0` where it now seems to return an empty array every time now.

In the example is the PHP printing out the model details and the changed fields after each call, the model saves into the DB without issue but the changed fields is not reflecting that.
My models have `keepSnapshots` set to true and `deleted` is not part of `skipAttributes`.

Example output:
```php
print_r($model->toArray());
print_r($model->getChangedFields());

Array
(
    [id] => 1
    [created] => 2017-03-23 20:34:20
    [updated] => 2017-03-23 20:41:53
    [deleted] => 
)
Array
(
)

Array
(
    [id] => 1
    [created] => 2017-03-23 20:34:20
    [updated] => 2017-03-23 20:41:49
    [deleted] => 2017-03-23 20:41:53
)
Array
(
)

```
Code to reproduce:

```php
$model->save([
    'someField' => 'someValue',
]);

print_r($model->toArray());
print_r($model->getChangedFields());
```

Calling `hasChanged` also returns a boolean result of false.

### Details

* Phalcon version: 3.1.0
* PHP Version: (7.0.17)
* Operating System: Debian (Docker)
* Installation type: Compiling from source
* Server: Nginx

**Comment by Jurigag** [comment]
The old behawior was actually a long sitting bug here https://github.com/phalcon/cphalcon/issues/11007 https://github.com/phalcon/cphalcon/issues/11818 https://github.com/phalcon/cphalcon/issues/11424 there were a lot of discussion and from most opinions as i saw that snapshot after save should be updated which right now is happening. From 3.0.4 after saving obviously there are no changed fields because they are saved - this is why you have empty array and i think this is much more expected result. To make your code working again:

```php
$model->assign([
    'someField' => 'someValue',
]);

print_r($model->toArray());
print_r($model->getChangedFields());
$model->save();

**Comment by garyrutland** [comment]
Ok, so I had an event being triggered on `afterSave` as it confirmed any changes were already saved.  
I guess I have the option to move it to `beforeSave` or try and find a different approach?

**Comment by Jurigag** [comment]
Yes, move it to beforeSave - here you will getChangedFields and it will return changed fields before saving correctly.

**Comment by garyrutland** [comment]
Moving it to `beforeSave` seems to resolve it, not ideal for what I'm trying to achieve but I'll figure something out.

**Comment by Jurigag** [comment]
Oh also this change is from 3.0.3

**Comment by Jurigag** [comment]
@garyrutland i think we could reopen this as a new feature request with some method like `getUpdatedFields()`

**Comment by garyrutland** [comment]
Ah cool, you read my mind.  
Was going to ask if this could be added as a feature.

**Comment by Jurigag** [comment]
This can be closed

**Comment by PostavkiExpert** [comment]
3.4.5 using getUpdatedFields or getChangedFields throw error "The record doesn't have a valid data snapshot"
