### ISSUE TITLE
[NFR]Get advantage of (group)prefix in router

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12758]
Currently `Phalcon\Mvc\Router` is handling all routes even when using groups and prefixes. I made an PR where i propose:

- change this behavior, routes are handled in prefix groups - when group doesn't have any prefix set it as `/` or just empty `''` prefix group depending how route pattern begins
- add `prefix` or `_prefix`(not sure if `prefix` alone can affect somehow route named parameters) to paths argument in `Phalcon\Mvc\Router::add` - so people could possibly optimize their applications by adding this ability - it also comes with `Phalcon\Mvc\Router::usePrefix` to tell if prefix should be used to really prefix with `pattern`

For example this code:

```php
$di = new \Phalcon\Di\FactoryDefault();

\Phalcon\Mvc\Router\Route::reset();
$router = new \Phalcon\Mvc\Router(false);
$router->setDI($di);
for ($i = 0; $i < 10; $i++) {
    $group = new \Phalcon\Mvc\Router\Group();
    $group->setPrefix("/test$i");
    for ($j = 0; $j < 10; $j++) {
        $group->addGet("/asd$i");
    }
    $router->mount($group);
}

echo "Getting first route 10000x time: ";

$startTime = microtime(true);
for ($i = 0; $i < 10000; $i++) {
    $router->handle('/test0/asd0');
}
echo microtime(true) - $startTime.PHP_EOL;
echo "Getting middle route 10000x time: ";
$startTime = microtime(true);
for ($i = 0; $i < 10000; $i++) {
    $router->handle('/test4/asd4');
}
echo microtime(true) - $startTime.PHP_EOL;
echo "Getting last route 10000x time: ";
$startTime = microtime(true);
for ($i = 0; $i < 10000; $i++) {
    $router->handle('/test9/asd9');
}
echo microtime(true) - $startTime.PHP_EOL;
```

With changes i proposed here - https://github.com/phalcon/cphalcon/pull/12756

Returns:

```
Getting first route 10000x time: 0.29063892364502
Getting middle route 10000x time: 0.29391598701477
Getting last route 10000x time: 0.28825283050537
```

On original code it returns:

```
Getting first route 10000x time: 13.590741872787
Getting middle route 10000x time: 7.8661091327667
Getting last route 10000x time: 0.29496097564697
```

Quite a difference. Of course 10000x handling same route is not real situation, but it should still give some small performance boost to real live applications especially if they are big and if you are using many route groups with prefixes and you have many routes in group(i guess when we talk about something 500-1000 routes in total it could make noticeable difference in application).

Also on some point we could should possibly add support for some other kind of routers or rewrite current one totally.

**Comment by virgofx** [comment]
👍 Will need to do a few more tests comparing a flat route list (>1000 -- which is common for large sites) and then a heavily nested one (say 20 x 5 x 5). In general, there definitely have been very few updates to the routing since initial implementation and there are areas we can squeeze more performance. Another reference for a great routing article : http://nikic.github.io/2014/02/18/Fast-request-routing-using-regular-expressions.html

**Comment by Jurigag** [comment]
Also despite of algorithm itself we could also switch having all routes in one array to having seperated arrays for get/put/post etc methods and instead of checking each route against current method we will only iterate routes in method we want.
