### ISSUE TITLE
Uniqueness validator except 

### ISSUE THREAD

**Issue by garyrutland** [phalcon/cphalcon#12763]
Hi,

I have a discussion open on the Phalcon forum at the moment and there could be something for a feature request.  
https://forum.phalconphp.com/discussion/15847/uniqueness-validation-when-using-soft-delete

At the moment `except` only seems to allow for a value or an array of values.  
As my `deleted` column is a timestamp in my database I was hoping to do an `except` based on whether the value is null or more specifically, not null.

Would it be possible to get an update to allow that or possible (as the forum post suggest) add something like `exceptNull` and/or `exceptNotNull` to the options?

Thanks,  
Gary

**Comment by Jurigag** [comment]
Lately I had similar problem but I need even more, to totally change this query to somehow more sophisticated. Could adding method `getSql` which will return string with condition solution to you problem? So you just extends getSql and return whatever query you want? I think it's more generic and cleaner way to solve this issue.
