### ISSUE TITLE
Seems to be an issue with relations in 3.1.2

### ISSUE THREAD

**Issue by garyrutland** [phalcon/cphalcon#12775]
I'm not exactly sure what the exact scenario is but in 3.1.2 some of my relations have stopped working (since downgrading to 3.1.1 they have started working again).

If I get the ID directly via `$model->getAccountID();` I can get the ID but if I call the magic method `$model->getAccount();` it comes back as `null`.

I have the following relation setup in my model:

    $this->belongsTo('accountId', Account::class, 'id', [
        'alias' => 'account',
    ]);

Not sure what other details to give you.

### Details

* Phalcon version: 3.1.2
* PHP Version: 7.0.17
* Operating System: Linux (Docker)
* Server: Git

**Comment by niden** [comment]
Is this a typo `$model->getAccountID();` or this is how you call it? 

If so shouldn't it be `$model->getAccountId();`

**Comment by garyrutland** [comment]
Sorry, may have typed that too quickly.  
There's not type in the code.

**Comment by niden** [comment]
lol OK . Just checking.

**Comment by sergeyklay** [comment]
Cc: @Jurigag

**Comment by Jurigag** [comment]
I didn't check anything relation related so don't sure what happens.

**Comment by sergeyklay** [comment]
@garyrutland Could you please provide minimal code to reproduce the issue. I mean table schema, models, and test script to reproduce.

**Comment by garyrutland** [comment]
Hmm quite tricky to do without giving you quite a bit of code.  
I'll try and figure something out.

**Comment by Jurigag** [comment]
Just db service, model class and find, you can use `phalcon_test` table.

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/master/unit-tests/ModelsRelationsTest.php#L146 here it passed, you really need to provide full code what is causing a problem without any code form your project.

**Comment by garyrutland** [comment]
I'll try and get something together, what was odd was that some relations were working.

**Comment by garyrutland** [comment]
So fantastically, my test script works perfectly fine but in my project `getAccount();` still won't work.  
I've updated to PHP 7.1 in case there was an oddity there but still nothing.

Even more frustratingly, it does work in the opposite direction.  
So if I call `Account::findFirst()->getAudits()->getFirst();` I get the audit that won't return the account.

I don't think I'm missing anything in my tests script that's different to my project.

**Comment by Jurigag** [comment]
So the script you provided works fine? Then problem is somewhere in your project, idk where.

**Comment by michanismus** [comment]
There are no fields defined in your test script. Do you have public/protected properties defined for your models in your real project?

**Comment by garyrutland** [comment]
In the project there are private properties with setters and getters, did have them in the test script but didn't make a difference if I had them or not.  
I'm at a bit of a loose end, there's definitely some issue somewhere as it works fine with 3.1.1 but I can't figure out what the scenario is.

**Comment by garyrutland** [comment]
Alternatively, if you guys have Docker Hub and BitBucket accounts I could give you temporary access to the service that has the issue?

**Comment by Jurigag** [comment]
@garyrutland if you have by any chance `$account` property then it can make a difference. Just try to create script to reproduce it. As i already wrote - nothing was changed between phalcon 3.1.1 and 3.1.2 about relation stuff, not sure why this happens.

**Comment by garyrutland** [comment]
Ok, I've got it sorted.  

I was extending the audit model from another repo/library and must have been working by fluke before.  
Having moved the model into the current repo/library and having it match the others it seems to work fine.

Thank,  
Gary
