### ISSUE TITLE
How to fix php-config is not installed???

### ISSUE THREAD

**Issue by tuanbaros** [phalcon/cphalcon#12774]
I am a new phalconer, after 
git clone --depth=1 "git://github.com/phalcon/cphalcon.git"
cd cphalcon/build
sudo ./install
then have error: 
./install: line 55: --version: command not found
php-config is not installed

How to fix it???

**Comment by Jurigag** [comment]
apt-get install php-dev/php5-dev

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

**Comment by jayjupdhig** [comment]
OK thx
