### ISSUE TITLE
The release of phalcon_x64_vc14_php7.0_3.1.2.zip is wrong

### ISSUE THREAD

**Issue by ejzhang** [phalcon/cphalcon#12770]
The size of phalcon_x64_vc14_php7.0_3.1.2.zip is only 2.06kb, and there isn't the dll in it.
![Uploading image.png…]()

**Comment by sergeyklay** [comment]
We know about this problem and trying to solve it.

Cc: @niden

**Comment by sergeyklay** [comment]
Fixed
