### ISSUE TITLE
Load file with registered namespaces

### ISSUE THREAD

**Issue by mixinix** [phalcon/cphalcon#12780]
Is there any built-in library or helper from Phalcon to load file with registered namespaces?

Example:

```
$loader->registerNamespaces([
    'Foo\Bar' => '/foo/bar/'
]);
```
```
Phalcon\Helper::loadFileWithNS('Foo\Bar', 'file.php');
```

**Comment by michanismus** [comment]
I guess you are looking for the `Phalcon\Loader`

https://docs.phalconphp.com/en/3.0.2/api/Phalcon_Loader.html

**Comment by mixinix** [comment]
I think not.
I close this. Thank for you response.
