### ISSUE TITLE
Feature request: pass array of strings into flash methods

### ISSUE THREAD

**Issue by garyrutland** [phalcon/cphalcon#12781]
Hi,

Currently you can only pass strings into flash messages, which when you have a bunch of messages can look a bit odd.  
Would be nice if an array of strings or possibly even `Phalcon\Validation\Message` could be passed into the flash methods which either outputs the messages wrapped in `<p></p>` or just a `<br>` at the end of each message.

Thanks,  
Gary

**Comment by Jurigag** [comment]
Are you sure about this? https://github.com/phalcon/cphalcon/blob/master/phalcon/flash.zep#L249 there is already array detection.

About Message - i think casting everywhere message to string should be enough in this class since Message has `__toString` method.
