### ISSUE TITLE
isset(defined in Volt)  return false on ORM attribute in Volt

### ISSUE THREAD

**Issue by fonqing** [phalcon/cphalcon#12796]
### 

Code in Controller
```php
//...
public  function editAction(){
    //...
    $this->view->field = Fields::findFirst(5);
}
//...
```
Code in View
```php
<?php var_dump(isset($field->name));?>Output false
<?php var_dump($field->name)?> Can be output value correct
```
### Details

* Phalcon version:3.1.1
* PHP Version: 5.6.4 x86 vc11 Thread safe
* Operating System: Windows 10
* Installation type: Download dll from github release 
* Zephir version (if any): Version 0.9.6a-dev-3a72ba9bb5 (in phpinfo page)
* Server: Apache
* Other related info (Database, table schema):

**Comment by mbrostami** [comment]
Check that value of the ```$field->name``` is not Null. Isset will return false if variable is null.

**Comment by fonqing** [comment]
The problem is that $field->name is not null but a string form a ORM object ,isset return false,Is there a shortcut for  property_exists method in volt?

**Comment by mbrostami** [comment]
I think there is no volt function for property_exist. You need to add custom function to volt compiler.
