### ISSUE TITLE
Feature Request: Phalcon DB - Change Column (Rename)

### ISSUE THREAD

**Issue by phil-directedge** [phalcon/cphalcon#12805]
ORM currently supports:

    Phalcon\Db\Adapter::addColumn(...)
    Phalcon\Db\Adapter::modifyColumn(...)
    Phalcon\Db\Adapter::dropColumn(...)

ORM is currently missing the ability to change the column without using dialect specific SQL.

### Expected and Actual Behavior

Add ability to rename columns (and tables).

### Details

* Phalcon version: 3.1.1
* PHP Version: 7.1.4
* Other related info (Database, table schema): mysql, postgres, sqlite

**Comment by efimBistrov** [comment]
+1

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
