### ISSUE TITLE
Uncaught Error: Access to undeclared static property: Phalcon\\Di::$_default

### ISSUE THREAD

**Issue by mohamedziada** [phalcon/cphalcon#12803]
It works fine with PHP 5.6 but when I upgrade to PHP7 this error happens

> **Uncaught Error: Access to undeclared static property:
 Phalcon\\Di::$_default bootstrap_web.php.**
```
[:error] [pid 28022:tid 140093905889024] [client xxx.xxx.xxx.xxx:53064] PHP Fatal error: 
Uncaught Error: Access to undeclared static property:
 Phalcon\\Di::$_default in /path/to/website/app/bootstrap_web.php:20
Stack trace:
#0 [internal function]: Phalcon\\Di->__construct()
#1 /path/to/website/app/bootstrap_web.php(20): Phalcon\\Di\\FactoryDefault->__construct()
#2 /path/to/website/public/index.php(18): require(/path/to/website/app/b...')
#3 {main}
```
```
Next Error: Access to undeclared static property: Phalcon\\Di::$_default in /path/to/website/app/bootstrap_web.php:20
Stack trace:
#0 [internal function]: Phalcon\\Di->__construct()
#1 /path/to/website/app/bootstrap_web.php(20): Phalcon\\Di\\FactoryDefault->__construct()
#2 /path/to/website/public/index.php(18): require('/path/to/website/app/b...')
#3 {main}
  thrown in /path/to/website/app/bootstrap_web.php on line 20, referer: http://website.url
 ```

### Details
* Phalcon version:  3.1.2
* PHP Version:  PHP 7.0.15 (cli) (built: Feb 27 2017 23:58:56) (Zend Engine v3.0.0 ,with Zend OPcache v7.0.15,)
* Operating System: CentOS Linux release 7.3.1611 (Core)
* Installation type: Compiling from source 
* Server:   Apache and Compiling from source 
* Other related info (Database, table schema): DB Mysql 5.7

**Comment by sergeyklay** [comment]
@mohamedziada Could you please provide script / steps to reproduce?

**Comment by grigoriygithub** [comment]
Something similar in #12056

**Comment by sergeyklay** [comment]
If @mohamedziada use Windows - yes

**Comment by hakimio** [comment]
Can you reproduce with OPcache disabled? Do you use ApcMetaData?
Can you reproduce running test case provided by renatomjr: https://github.com/phalcon/cphalcon/issues/12056#issuecomment-243447917 ?

**Comment by hakimio** [comment]
ownCloud users are experiencing similar issue with PHP 7 on linux (openSUSE) too :
https://www.bountysource.com/issues/30829375-access-to-undeclared-static-property-oc-files-filesystem-normalizedpathcache
So, it might be possible that it's not only Windows issue.

**Comment by Jurigag** [comment]
@hakimio but this test case doesn't have phalcon calls so how it's phalcon issue?

**Comment by hakimio** [comment]
@Jurigag you put your Phalcon calls in your index.php .

**Comment by Jurigag** [comment]
I just never had this problem on debian 7/ubuntu 14 and php 7/5.6, this is really weird.

**Comment by hakimio** [comment]
This never happens on PHP 5.6. It's only PHP 7 issue. I guess, that's because they made some major changes to the way GC and static properties work in PHP 7.

It's easy to just blame the OS without investigating the issue.

**Comment by Jurigag** [comment]
Im not blaming the OS, im blaming apache.

**Comment by mohamedziada** [comment]
@sergeyklay I use CentOS  7.3.1611 with compile Apache and PHP and Phalcon as above
Btw it works fine with ubuntu with same versions 
>sleep(1);
 is not a good solutions as i use Phalcon for speed not to sleep :)
My scripts is 

public/index.php
`<?php require '../app/bootstrap_web.php';`

* And files here in gist

[ https://gist.github.com/mohamedziada/b347247f40bd8f54e8e7717132c4965c
](url)

**Comment by hakimio** [comment]
The sleep() call was just for a simple test case. Solution is to run php-cgi.exe with fcgi+apache or nginx,

**Comment by mohamedziada** [comment]
@hakimio 

> sleep() ;

no effect still the same error

**Comment by hakimio** [comment]
What??? Do you actually understand what I am saying?
I don't think so...

**Comment by mohamedziada** [comment]
@hakimio yes i try sleep() ; for test  
i didn't use  
"run php-cgi with fcgi+apache or nginx" 
i can't change server settings right now

**Comment by mohamedziada** [comment]
@hakimio you can explain to me, maybe i understand wrong

**Comment by hakimio** [comment]
Ok, can you provide some virtual machine or docker image which can reproduce the issue?

**Comment by mohamedziada** [comment]
@hakimio this is wt i do now, Virtual Machine (vagrant) and will test, but it may takes time from me, cuz i am not in my office next a few days

**Comment by salva-flores** [comment]
I got the same issue after upgrading to PHP 7.1.1 and phalcon 3.1.2.

**Comment by Jurigag** [comment]
- @salva-flores as already mentioned in many places, use php-fpm

**Comment by sergeyklay** [comment]
Close in favor of #12056
