### ISSUE TITLE
Feature request: flash has message

### ISSUE THREAD

**Issue by garyrutland** [phalcon/cphalcon#12804]
Hi,

Have a scenario where it would be useful where I could check if there are any flash messages set, possibly via `$this->flash->has($type = null);` with null being any message type.  
As far as I can tell, there is nothing in place for that at the moment?

Thanks,
Gary

**Comment by Jurigag** [comment]
Hmmm the problem is currently flash messages aren't stored by type keys. Not sure if adding storing them like that will introduce any breaking change? @sergeyklay
