### ISSUE TITLE
ACL: dropResourceAccess does not drop access if list is string

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#12806]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior
When using `dropResourceAccess` with a string as the `accessList` parameter, the access is not properly removed.

> Provide minimal script to reproduce the issue

```php
$acl = new Memory();
$acl->setDefaultAction(Acl::DENY);
$role = new Role('Guests');
$resource = new Resource('Post');

$acl->addRole($role);
$acl->addResource($resource, ['index', 'update', 'create']);
$acl->allow('Guests', 'Post', 'index');

expect($acl->isAllowed($role, $resource, 'update'))->true(); 

$acl->dropResourceAccess($resource, 'update');

expect($acl->isAllowed($role, $resource, 'update'))->false();  // < Returns TRUE
```
### Details

* Phalcon version: (`php --ri phalcon`) 3.1.2
* PHP Version: (`php -v`) 7.0.15
* Operating System: xubuntu
* Installation type: Compiling from source || installing via package manager - Phalcon repo
* Zephir version (if any):
* Server: Nginx | Apache | Other - nginx
* Other related info (Database, table schema):

**Comment by Daredzik** [comment]
can you provide what's expect() return when you move 
`expect($acl->isAllowed($role, $resource, 'update'))->true(); `
to line number 5 ?

**Comment by Jurigag** [comment]
It's just code for codeception test.

**Comment by Daredzik** [comment]
Yes i know it's a test case, but i want to get value from isAllowed before setting roles, resources ;)

**Comment by Jurigag** [comment]
@niden you sure it works when it's accessList in dropResourceAccess is array?

**Comment by Jurigag** [comment]
Well actually it doesn't work. `dropResourceAccess` do exactly what it tells, remove access from resource, it doesn't remove already created rules for roles for certain resources and accesses. If it should remove then i think this should be phalcon 4 change.

**Comment by niden** [comment]
Yes I believe so. I jsut have to run the tests first to ensure that it works as expected.

**Comment by Daredzik** [comment]
Problem is `dropResourceAccess` uses a `this->_accessList`, but `isAllowed` uses `this->_access` hover `allow` and `deny` methods use too `this->_access`. I'm correct ?

**Comment by Jurigag** [comment]
Well updated last answer, actually it doesn't work too.
