### ISSUE TITLE
Feature Request: Database Existence validator (similar to Uniqueness)

### ISSUE THREAD

**Issue by adhocore** [phalcon/cphalcon#12802]
Often we need to validate if given value is existing in certain column (attribute) of a table (model).

Most probably the validation logic can be mostly the same as for `Uniqueness`, except the comparison [here](https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validator/uniqueness.zep#L182) can be something like `> 0`

A possible usage scenario:

```php
use Phalcon\Validation\Validator\Existence as ExistenceValidator;

$validator->add(
      "country_id",
      new ExistenceValidator(
          [
              "model" => new Countries(),
              "attribute" => "id",
              "message" => "Country with given ID does not exist",
          ]
      )
 );
```

Thanks :)

**Comment by Jurigag** [comment]
For this exact case you can use virtual foreignKey.

**Comment by adhocore** [comment]
it is not really limited to foreign key though the example was one. with such validator one can check existence of any arbitrary value of any column. or is this still possible with virtual FK?

**Comment by Jurigag** [comment]
Well i think you could use perhaps https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Validation/Validator/Db/Uniqueness.php

**Comment by Jurigag** [comment]
Well it will check for uniqueness anyway, so i guess maybe it's needed this validator, bot not sure if in core, i think better in validator. In most cases the usage with it will be with FK to check existance of some other relation - and this can be done using vitual foreignkey.
