### ISSUE TITLE
[ BUG ] Fatal error in Phalcon\Mvc\Model::_postSaveRelatedRecords()

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#1280]
Hi all,

I have a model, Transaction, with a hasMany relationship set up like so:
```php
$this->hasMany('id','\Pay\Model\ProviderField','transaction_id',['alias'=>'provider_fields']);
```

In a method in the Transaction model I am calling:
```php
////$fields is an array like: [ 'iso_code' => 12, 'date' => '2013-09-20' ]
$this->provider_fields = $fields;
$this->save()
```

I am getting this error as a result:

```
Fatal error: Phalcon\Mvc\Model::_postSaveRelatedRecords(): Call to method writeattribute() on a non object in /var/www/htdocs/app/models/Transaction.php on line 85
```

I realize I shouldn't be setting `$this->provider_fields` to an array - I'll just call that a brain fart.  Nonetheless, I think this should be handled with an exception being thrown, rather than a fatal error.

**Comment by andresgutierrez** [comment]
Could you please check if this still happens in 2.0.x?

**Comment by Green-Cat** [comment]
No reproduction script provided. No reply for almost a year.
This can probably be closed.
@sergeyklay
