### ISSUE TITLE
Backslash printed when use related model (ORM)

### ISSUE THREAD

**Issue by victorhramos** [phalcon/cphalcon#12810]
### Expected and Actual Behavior
After an upgrade to phalcon 3.1.2 im having trouble with ORM. When i try to get related models a backslash is being outputed to my view.

My Controller:
![image](https://cloud.githubusercontent.com/assets/9410768/25353627/5201de24-2906-11e7-8d27-1bffd82aa32d.png)

My view:
![image](https://cloud.githubusercontent.com/assets/9410768/25353654/6d193a36-2906-11e7-8901-8ba0ea11ec59.png)

### Details

* Phalcon version: 3.1.2
* PHP Version: PHP 7.0.12
* Operating System: Windows 10
* Installation type: dll
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema): MariaDB 10.1

**Comment by sergeyklay** [comment]
@victorhramos 
Could you please try to compile Phalcon from master (v3.1.2) by using ff769131f3751b590da702e3c7595411c07b0919 Zephir's commit?
