### ISSUE TITLE
Centos 6.7 php-config is not installed

### ISSUE THREAD

**Issue by yusufdamat** [phalcon/cphalcon#12820]
How can i find this solution in vps server setup i am getting this error

**Comment by sergeyklay** [comment]
yum install php-devel

**Comment by yusufdamat** [comment]
[root@server ~]# yum install php-devel
Loaded plugins: fastestmirror, presto, priorities
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.prometeus.net
 * extras: mirrors.prometeus.net
 * updates: mirrors.prometeus.net
Resolving Dependencies
--> Running transaction check
---> Package php-devel.x86_64 0:5.3.3-49.el6 will be installed
--> Processing Dependency: php(x86-64) = 5.3.3-49.el6 for package: php-devel-5.3.3-49.el6.x86_64
--> Running transaction check
---> Package php.x86_64 0:5.3.3-49.el6 will be installed
--> Processing Dependency: php-common(x86-64) = 5.3.3-49.el6 for package: php-5.3.3-49.el6.x86_64
--> Processing Dependency: php-cli(x86-64) = 5.3.3-49.el6 for package: php-5.3.3-49.el6.x86_64
--> Processing Dependency: httpd-mmn = 20051115 for package: php-5.3.3-49.el6.x86_64
--> Processing Dependency: httpd for package: php-5.3.3-49.el6.x86_64
--> Running transaction check
---> Package httpd.x86_64 0:2.2.15-59.el6.centos will be installed
--> Processing Dependency: httpd-tools = 2.2.15-59.el6.centos for package: httpd-2.2.15-59.el6.centos.x86_64
--> Processing Dependency: apr-util-ldap for package: httpd-2.2.15-59.el6.centos.x86_64
---> Package php-cli.x86_64 0:5.3.3-49.el6 will be installed
---> Package php-common.x86_64 0:5.3.3-49.el6 will be installed
--> Running transaction check
---> Package apr-util-ldap.x86_64 0:1.3.9-3.el6_0.1 will be installed
--> Processing Dependency: apr-util = 1.3.9-3.el6_0.1 for package: apr-util-ldap-1.3.9-3.el6_0.1.x86_64
---> Package httpd-tools.x86_64 0:2.2.15-59.el6.centos will be installed
--> Running transaction check
---> Package apr-util.i686 0:1.3.9-3.el6_0.1 will be installed
--> Processing Dependency: libuuid.so.1 for package: apr-util-1.3.9-3.el6_0.1.i686
--> Processing Dependency: libexpat.so.1 for package: apr-util-1.3.9-3.el6_0.1.i686
--> Processing Dependency: libapr-1.so.0 for package: apr-util-1.3.9-3.el6_0.1.i686
--> Running transaction check
---> Package apr.i686 0:1.3.9-5.el6_2 will be installed
---> Package expat.i686 0:2.0.1-13.el6_8 will be installed
---> Package libuuid.i686 0:2.17.2-12.28.el6 will be installed
--> Finished Dependency Resolution
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:

         1. You have an upgrade for apr which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of apr of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude apr.otherarch ... this should give you an error
            message showing the root cause of the problem.

         2. You have multiple architectures of apr installed, but
            yum can only see an upgrade for one of those arcitectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.

         3. You have duplicate versions of apr installed already.
            You can use "yum check" to get yum show these errors.

       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).

       Protected multilib versions: apr-1.3.9-5.el6_2.i686 != apr-1.5.2-2.x86_64
Error: Protected multilib versions: apr-util-1.3.9-3.el6_0.1.i686 != apr-util-1.5.4-2.x86_64
[root@server ~]#

**Comment by sergeyklay** [comment]
1. This issue is not relevant to the Phalcon
2. As I understand it you have PHP 5.3. Probably you need to install an older version of Phalcon. For example 1.3.x

**Comment by yusufdamat** [comment]
PHP Version 5.6.30
Centos 6.7 
What do I have to do now and I hope to be able to run the system

**Comment by sergeyklay** [comment]
Please do not use cphalcon repo as Google or forum 

* [can't install php-devel on centos](http://stackoverflow.com/questions/12325109/cant-install-php-devel-on-centos)
* [Install php-devel centos](http://stackoverflow.com/questions/13147824/install-php-devel-centos)
* [How to install php-devel under CentOS](https://serverfault.com/questions/425841/how-to-install-php-devel-under-centos-6-3-x64)
