### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by dongasai** [phalcon/cphalcon#12824]
https://github.com/phalcon/cphalcon/blob/3.1.x/phalcon/dispatcher.zep#L599

Why not at this location to judgment, the return false for the continue while?

**Comment by virgofx** [comment]
Current documentation seems to have removed some of the event details. Old ones are here.

https://docs.phalconphp.com/en/master/reference/dispatching.html

Initialize is used a constructor equivalent throughout Phalcon in various components. It's used to perform one-time initialization of the class.

Please use issues for bugs only. Refer to the forums for questions.

**Comment by dongasai** [comment]
I already know what it looks like, and I want to know why @virgofx .
Why "**_Can stop operation?_**"It is not.

**Comment by Jurigag** [comment]
Because there is no check for false. Not sure why would you like to stop execution when initializing controller?

**Comment by dongasai** [comment]
Here's what I thought:
In several events in the initialize attachment, such as "dispatch: afterInitialize", "dispatch: afterBinding", both provide the option to stop dispatch, but this location is not

**Comment by virgofx** [comment]
Initialize is constructor equivalent. It's type **void**. No return allowed.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
