### ISSUE TITLE
Response setHeaders overwrites setContentType

### ISSUE THREAD

**Issue by linxlad** [phalcon/cphalcon#12836]
Reponse `setHeaders` is scrubbing `setContentType`.

### Expected and Actual Behavior

**Expected:**
I expected the `reponse->setHeaders` to merge with what was already in headers.

**Actual :**
I had `response->setContentType('application/json')` before `response->setHeaders`. The result meant I was losing the desired content type and it was reverting back to `text/html`.

**Working:**
```php
$this->response->setHeaders($headers);
$this->response->setContentType('application/json', 'UTF-8');
```

**Not working:**
```php
$this->response->setContentType('application/json', 'UTF-8');
$this->response->setHeaders($headers);
```

### Details

* Phalcon version: 3.1.2
* PHP Version: 7.0.18
* Operating System: Windows running a Doker environment for development.
* Installation type: Docker box.
* Zephir version (if any):
* Server: Nginx

**Comment by dschissler** [comment]
I recommend that this be added to the Phalcon 4 milestone with merging on by default.  If it is added in Phalcon 3 then merging will need to be off by default.  It can be currently worked around by extending the Response class and calling `getHeaders` in `setHeaders`.

**Comment by Jurigag** [comment]
@linxlad 

Well not sure what you exactly do further but `$this->response->setContentType('application/json', 'UTF-8');` is most likely not needed just do:

```
$model = $model->toArray();
return $this->request->setJsonContent($model);
```

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/13669

Thank you @linxlad
