### ISSUE TITLE
modifyColumn on postgres different than mysql

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#12832]
Modifying a column's size/scale is impossible in postgres since it won't detect a change in the type. In the postgres dialect there are checks that the currentColumn is different than the proposed column and only then is the sql generated, but it does not take into account the size/scale parts.

```php
$columns = $this->db->describeColumns('mytable'); // Table with only one 'id' column
$newColumn = new \Phalcon\Db\Column(
  'id',
  array(
    'size' => 32 // Originally was size 16
  )
);
$sql = $this->db->getDialect()->modifyColumn('mytable', 'mydb', $newColumn, $columns[0]);
echo $sql . PHP_EOL . "  does not contain correct alter statement." . PHP_EOL;
```
### Details

* Phalcon version: 3.0.3/3.0.4
* PHP Version: 7.0.15
* Operating System: Windows/Linux
* Installation type: Windows: dll, Linux, packagecloud
* Zephir version (if any):  Version 0.9.5a-dev
* Server: IIS | Nginx
* Other related info (Database, table schema): 'mydb' database with one table 'mytable' with one column 'id varchar(16) PRIMARY'

**Comment by nsossonko** [comment]
Also, this causes the referenceType system to not work correctly because there's no referenceType set when using describeColumns. In general, I think that should be changed to always storing the Column constant in type and using 'actualType' for the underlying sql type. Then that can be stored correctly for all dbs and proper modification of columns can be made.

**Comment by nsossonko** [comment]
Was this fixed? I doubt it...

**Comment by sergeyklay** [comment]
Open a new issue then
