### ISSUE TITLE
Standardize the session interface

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#12833]
The implementation of `destroy` between `Phalcon\Session\Adapter` and `Phalcon\Session\Adapter\*` when destroying is totally different. For example:

**`Phalcon\Session\Adapter`**:
```zep
public function destroy ( boolean removeData = false ) -> boolean
```

**`Phalcon\Session\Adapter\Redis`**:
```zep
public function destroy ( string sessionId = null ) -> boolean
```

[**`SessionHandlerInterface`**](http://php.net/manual/en/sessionhandlerinterface.destroy.php):

```php
public function destroy ( string $session_id ) : boolean
```

I propose to refactor:
- [ ] **`Phalcon\Session\AdapterInterface`**
- [ ] **`Phalcon\Session\Adapter`**
- [ ] **`Phalcon\Session\Adapter\Files`**
- [ ] **`Phalcon\Session\Adapter\Libmemcached`**
- [ ] **`Phalcon\Session\Adapter\Memcache`**
- [ ] **`Phalcon\Session\Adapter\Redis`**

for full compliance with PHP's `SessionHandlerInterface`.

I believe that `Phalcon\Session\AdapterInterface` should inherit `SessionHandlerInterface`.

Obviously these are backward incompatible changes and they should be done in 4.x branch.

Refs:
* #2326
* #12835
* #11722
* #11341
* #10883
* #12981

Cc: @phalcon/core-team, @phalcon/framework-team

**Comment by rianorie** [comment]
+1ed - I believe consistency is key, any change that will promote that has my vote.

**Comment by linxlad** [comment]
I use Aerospike, worth checking if that needs a refactor :)

**Comment by niden** [comment]
Absolutely yes

We need to be consistent in all interfaces, all implementations of adapters. This has to be refactored and introduced in 4.x version.

```
public function destroy (string sessionId = null) -> bool
```
It will : 
* if `null` it will destroy the current `sessionId` 
* remove a particular `sessionId`

If successful returns `true`. If not `false` or if the `sessionId` was not found `false` again.

**Comment by linxlad** [comment]
Also no underscored variables in any interfaces or in general :(

**Comment by Jurigag** [comment]
You mean in methods body? @linxlad yea i agree. But underscored properties should remain - simply to give people option to add their own property for example like `$name` and we should use property `_name` imho.

**Comment by sergeyklay** [comment]
@linxlad This is different issue, not related to the session

**Comment by linxlad** [comment]
@sergeyklay I know, I just turned into an annoying PSR-2 warrior lol

**Comment by virgofx** [comment]
👍

**Comment by dschissler** [comment]
I'm not understanding why the new standard interface doesn't allow a default argument for the session id: `public function destroy ( string $session_id ) : bool`.

**Comment by dschissler** [comment]
It seems like that the way the signature is working it should be a static method, but its not.  I'm not familiar with most of the adapter backends but it seems like the interface is so overly general that it will be annoying in the most simple cases.

**Comment by sergeyklay** [comment]
@dschissler What do you mean? Could you please explain a bit more?

**Comment by dschissler** [comment]
So in `Phalcon\Session\Adapter\Files` the object will already know what the session id, probably as a protected variable in the class.  However then to tear down the session you need to specify the session id in the `destroy` method.  Doesn't that seem weird?

**Comment by dschissler** [comment]
Has anyone thought about this?  As far as I can see `SessionHandlerInterface` seems like a faulty standard.

**Comment by sergeyklay** [comment]
@dschissler Could you elaborate on that. Why?

**Comment by dschissler** [comment]
This seems strange.

`$session->destroy($session->getId());`

**Comment by sergeyklay** [comment]
Yes, you may need remove not current session, owned by some user

**Comment by dschissler** [comment]
How about we add API sugar?:

```php
public function destroyCurrent()
{
    $this->destroy($this->getId());
} 
```

**Comment by dschissler** [comment]
@sergeyklay How does `Phalcon\Session\Adapter\Redis` work with [SessionHandlerInterface::open](http://php.net/manual/en/sessionhandlerinterface.open.php)?  I don't understand how `string $save_path` is relevant to service based sessions.

**Comment by sergeyklay** [comment]
This sugar is not compatible with the interface

**Comment by sergeyklay** [comment]
https://github.com/nrk/predis/blob/v1.1/src/Session/Handler.php

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/13673
