### ISSUE TITLE
Phalcon\Mvc\Url

### ISSUE THREAD

**Issue by sunchuo** [phalcon/cphalcon#12848]
```php

$router->add('/:controller/:action/aaa.html', [
    'controller' => 1,
    'action' => 2
])->setHostname('domain.com')->setName('testurl');


echo $url->get(['for' => 'testurl', 'controller' => 'testc', 'action' => 'testa']);

result:

/testc/testa/aaa.ht

should be:

http://domain.com/testc/testa/aaa.html

```

### Details

Phalcon DevTools (3.2.0 ALPHA 1)

Environment:
  OS: Linux localhost.localdomain 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64
  PHP Version: 7.1.4
  PHP SAPI: cli
  PHP Bin: /usr/local/php/bin/php
  PHP Extension Dir: /usr/local/php/lib/php/extensions/no-debug-non-zts-20160303
  PHP Bin Dir: /usr/local/php/bin
  Loaded PHP config: /usr/local/php/etc/php.ini
Versions:
  Phalcon DevTools Version: 3.2.0 ALPHA 1
  Phalcon Version: 3.1.2
  AdminLTE Version: 2.3.6

**Comment by sergeyklay** [comment]
It is not a bog report.  I want to close this issue because I don't want a bunch of these lying around.
