### ISSUE TITLE
Remove View from Depedency Injector or Using Phalcon Devtools + Migration in Micro

### ISSUE THREAD

**Issue by msdme** [phalcon/cphalcon#12843]
Hi, 
I'm not using micro to create restfull API, because I want to use phalcon devtools and migrations. But when I disable view from depedency injector, it seems phalcon require it mandatory. 
So, how can I disable view from depedency injector safely ? Or, can I use phalcon devtools and migration in phalcon micro?

**Comment by michanismus** [comment]
Thats quite simple. Just create an event listener for the event `application:boot`

```php

class ApplicationListener extends \Phalcon\Di\Injectable
{
    public function boot($event, $application)
    {
        $application->useImplicitView(false);

        return true;
    }
}

$eventsManager->attach('application', new ApplicationListener);

```

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
