### ISSUE TITLE
Volt length filter returns 0 on object

### ISSUE THREAD

**Issue by n0nag0n** [phalcon/cphalcon#12844]
Hey there,

This was pretty simple I thought, but didn't understand why it was working this way. I'm running Phalcon 3.1.2 and when I run this code.....

``` volt
{% if user|length == 0 %}
<h1>Add User</h1>
{% else %}
<h1>Update User</h1>
{% endif %}
{{ user|length }}
```

`user|length` always returns 0. So I ran `user|json_encode` and there is indeed a loaded object getting ran through json_encode there with a bunch of values, but it just returns 0 for the length and makes me sad :(. I know I can just run`$this->view->is_user = count($user);` in the controller, but I thought it was silly it didn't work here.

### Details

* Phalcon version: 3.1.2
* PHP Version: 7.1.4
* Operating System: macOS Sierra
* Installation type: Installed via brew
* Zephir version (if any): Powered by Zephir => Version 0.9.7-1fae5e50ac
* Server: PHP Server

**Comment by n0nag0n** [comment]
:'(

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

**Comment by n0nag0n** [comment]
Isn't this a bug if the expected output is supposed to be > 0? That `user` object has at least 10 field properties (first_name, last_name), and it's returning 0 for me.
