### ISSUE TITLE
fix invo security plugin persistent acl

### ISSUE THREAD

**Issue by luguiant** [phalcon/cphalcon#12855]
buenas noches a todos, disculpen que escriba en español (mi lenguaje nativo), tengo una web con dos implementación phalcon diferentes, las dos en la estructura invo, y el security plugin me dio problemas. 

encontré una solución muy artesanal para esto;

```php
if (!isset($this->persistent->acl)) {
    // ..
} else {
    $this->persistent->acl = null;
    unset($this->persistent->acl);
    $this->getAcl();
}
```

ustedes que opinan de esto, pese a que soy el autor de esta solución, para mi es muy artesanal pese a que funciona.

**Comment by Jurigag** [comment]
Could you use english please? Anyone can translate this?

**Comment by luguiant** [comment]
When you have two projects phalcon invo in the same application, the acl security plugin can generate a conflict by acl persistence, the solution is to put the persistence in null at the end, give unset to persistence and invoke again The getAcl () function, in the current project I'm working on, has two phalcon components which had conflict with the acl persistence of the security plugin, can solve this conflict by following these steps.

This is a very rudimentary solution. What do you think ??

```
if (!isset($this->persistent->acl)) {

}esle{
$this->persistent->acl = null;
unset($this->persistent->acl);
$this->getAcl();
}
```

**Comment by sergeyklay** [comment]
@andresgutierrez Could you please help with translation

**Comment by sergeyklay** [comment]
@luguiant What kind of issue do you face. Could you please explain a bit more.

**Comment by luguiant** [comment]
I have two applications phalcon invo, working on the same project, the two presented an intermittent operation, when I was going from functionalities between one and the other, ie when I passed to phalcon A from phalcon B, phalcon A did not work and bisverse, The problem was in the security plugin, persistence validation was the root of the problem, when phalcon was passed from B to phalcon A the security plugin had already loaded the acl persistence, which generated an error in phalcon A that stopped its work.

Please forgive my english

**Comment by andresgutierrez** [comment]
@luguiant You should set a different unique prefix for every application so their values won't get mixed after using one or another. 

Take a look at: https://docs.phalconphp.com/en/latest/reference/session.html#isolating-session-data-between-applications
