### ISSUE TITLE
Problems on Phalcon DB Adapters generating errors on migrations

### ISSUE THREAD

**Issue by jhonatasrein** [phalcon/cphalcon#12854]
I am try run migrations with devtools, but the SQL generated by phalcon many has errors of syntax, like follow below:
I have yet problems with Column type ENUM on created class by devtools and phalcon and others...
My errors:

On create below the problem is "DOUBLE(10) NOT NULL", in the Mysql the correct syntax is: DOUBLE NOT NULL
```sql
CREATE TABLE `bmq`.`crmMeta` (  `id` INT(11) NOT NULL AUTO_INCREMENT,  `nome` VARCHAR(45),  `descricao` TEXT,  `valor` DOUBLE(10) NOT NULL,  `tipo` INT(11) NOT NULL,  `data_inicio` DATETIME,  `data_fim` DATETIME,  PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ciERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') NOT NULL,
	`tipo` INT(11) NOT NULL,
	`data_inicio` DATETIME,
	`data_fim` DATET' at line 5
```

In this case the devtools are applying alter table in the column that don't have modifications, dont have difference bettwen the original table and the destination table

```php
1495054638.3138: ALTER TABLE `temp_importacao_di` MODIFY `datadi` DATE NOT NULL AFTER `numerodi`ERROR: SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value
```
Phalcon 3.1.2
Devtools: 3.1.2
Zephir 0.97
Server: Apache 2.4 with Ubuntu 16.04

**Comment by Jurigag** [comment]
Could you post any steps to reproduce this error?

**Comment by jhonatasrein** [comment]
Hi, to reproduce this problems and others do you need restore the file "database-FromMigrate.sql" and create classes from this database "teste", after the class of migrations created do you need run migration to another database "bmq".
If you do that you can see many errors generated in devtools.


[databases.zip](https://github.com/phalcon/cphalcon/files/1015459/databases.zip)

**Comment by sergeyklay** [comment]
@jhonatasrein Could you please provide a simple script to reprodie

**Comment by jhonatasrein** [comment]
Sorry, but i dont have any script to reproduce, i put in a previuos post the steps to reproduce, script ready to use i don't have!!!
I can send for you the version of devtools that i did many workaround to work fine for me, do you wanna?

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com). Foror devtools-related issue the devtools repo.
