### ISSUE TITLE
Model after save id becomes 0 (phalcon 3.1.2-2)

### ISSUE THREAD

**Issue by odat** [phalcon/cphalcon#12868]
Hello,

i get id zero after use model->save() 

example : 

            $photos = new Photos();
            $photos->name = $sGenerateName;
            $photos->size = $file->getSize();
            $photos->save() ;
           var_dump($photos->id) ;   // i get string '0' (length=1)

**Comment by mzf** [comment]
`id` field is autoincrement?

**Comment by odat** [comment]
yes of course, and it's fine on the tables but when i printed it after save() method i get 0

**Comment by sergeyklay** [comment]
@Jurigag Could you please take a look

**Comment by Jurigag** [comment]
Weird, not sure what happens here. What `$metaData->getIdentityField($photos)` return?

**Comment by odat** [comment]
@Jurigag i get (id)

`string 'id' (length=2)`

**Comment by Jurigag** [comment]
Then idk, settings this identity field is pretty straight forward, maybe it's somehow retruned from database like this? Maybe try to clear metadata if it's in some cache?

**Comment by dugwood** [comment]
Just hit the same issue this morning, with Phalcon 3.0.1. What is really weird is that it was working yesterday, and today it's broken, only on my dev' environment. Production is fine (3.0.1 too). Running `INSERT` directly in the database returns an incremented id too. Running it through `$model-save()` creates the record in the database with all the correct values.

**Comment by dugwood** [comment]
OK, nailed it! I had `$eventsManager->attach('db', ...)`, in which I did a `select('SHOW WARNINGS')` (because MySQL with PDO doesn't give warnings natively!), and I think that it changes the request. I'll run the debug in something else than `afterQuery`.

**Comment by sergeyklay** [comment]
```php
use Vokuro\Models\Users;

$user = new Users();
$user->name = 'John Doe ' . uniqid();
$user->email = uniqid() . ' -doe@john.com';
$user->password = 'secret';
$user->mustChangePassword = 1;
$user->profilesId = 1;
$user->banned = 0;
$user->suspended = 0;
$user->active = 1;

var_dump($user->save()); // TRUE
var_dump($user->id); // 11

$user = new Users([
    'name'               => 'John Doe ' . uniqid(),
    'email'              => uniqid() . ' -doe@john.com',
    'password'           => 'secret',
    'mustChangePassword' => 1,
    'profilesId'         => 1,
    'banned'             => 0,
    'suspended'          => 0,
    'active'             => 1,
]);

var_dump($user->save()); // TRUE
var_dump($user->id); // 11

$user = new Users();
$user->assign([
    'name'               => 'John Doe ' . uniqid(),
    'email'              => uniqid() . ' -doe@john.com',
    'password'           => 'secret',
    'mustChangePassword' => 1,
    'profilesId'         => 1,
    'banned'             => 0,
    'suspended'          => 0,
    'active'             => 1,
]);

var_dump($user->save()); // TRUE
var_dump($user->id); // 12
```
