### ISSUE TITLE
[NFR] UNION ALL

### ISSUE THREAD

**Issue by hafah** [phalcon/cphalcon#12867]
### Missing UNION ALL for PHQL

> **A very important operator if you ask me**

I don't see a UNION or UNION_ALL in

`ext/phalcon/mvc/model/query/parser.c`

```php
 #message: """
    Syntax error, unexpected token IDENTIFIER(UNION), near to ' ALL SELECT DISTINCT\n
            NULL AS banner ,\n
            NULL AS title ,\n
            NULL AS lead ,\n
            NULL AS tags ,\n
            p.user_id AS user_id ,\n
```

### Details

* Phalcon version: (`3.1.2`)
* PHP Version: (`7.0.15`)
* Operating System: Ubuntu 16.04
* Installation type: apt-get phalcon
* Zephir version (0.9.7):
* Server: Nginx
* Database type: Mysql 5.7.18

**Comment by denzyldick** [comment]
Did you try using the rawSql method https://docs.phalconphp.com/en/3.0.1/reference/phql.html#using-raw-sql

**Comment by Jurigag** [comment]
PHQL doesn't support UNION.

**Comment by hafah** [comment]
@denzyldick 

Thanks, but I'd rather use PHQL.

@jurigag

Isn't it possible for PHQL to support UNION, because I'm asking for Feature Request. 😀

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/issues/2882

**Comment by stamster** [comment]
I often see many developers rely on this operator.
