### ISSUE TITLE
¿how set model instance on controller contructor? Gratitude

### ISSUE THREAD

**Issue by incubux** [phalcon/cphalcon#12865]
Thank you for responding, indeed my error was in $ this -> $ index, very common mistake, thank you niden, God pay you, ultimater and david-duncan thank you very much for your time, your majesty jurigag, sorry for the inconvenience, do not stress for I will not bother you again here.

**Comment by niden** [comment]
@incubux it will be easier to get replies in our forum (https://phalcon.link/forum) or even our discord server (https://phalcon.link/discord).

Let us know if you need anything else.
