### ISSUE TITLE
MongoDB Delete Not Working

### ISSUE THREAD

**Issue by LearnPhalcon** [phalcon/cphalcon#12874]
Software Used:
  + PHP 7.1.5
  + Phalcon 3.1.2
  + MongoDB 3.4.3

Using this MongoDB incubator adapter from;
https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Db/Adapter

I was able to use `find()` `findFirst()` `save()` for create/update.
But when I try using **`delete()`** I receive an error.

Bootsrap File Code:
```php
$di->setShared('mongo', function() {
  $mongo = new \Phalcon\Db\Adapter\MongoDB\Client();
  return $mongo->selectDatabase('mytable');
}); #mongo

$di->setShared('collectionManager', function () {
  return new \Phalcon\Mvc\Collection\Manager();
}); #manager
```

Robots Model Code:
```php
<?php // Robots Model

namespace App\Models;

class Robots extends \Phalcon\Mvc\MongoCollection {

  public function getSource() {
    return 'mytest';
  } #getSource

} #class
```

Code Example Used:
```php
  $robot = Robots::findFirst();
  $robot->delete();
```

Backtrace:
Error: ``Call to a member function notifyEvent() on array``
File (Line): ``/Library/Phalcon/Mvc/MongoCollection.php (353)``
File Code: ``Phalcon\Mvc\MongoCollection->fireEventCancel(beforeDelete)``

**Comment by sergeyklay** [comment]
It is not Phalcon issue. Could you please create docs related issues in the [appropriate repository](https://github.com/phalcon/incubator)?
