### ISSUE TITLE
should findfirst can be like find return an empty array when the query mathes null

### ISSUE THREAD

**Issue by leslie5803** [phalcon/cphalcon#12879]
if i want to find a user:
`$user = User::findFirstById(3);`
but in mysql, this user isn't exists,now the user is false; if i use
`$user->toArray()`
there will throw an error,should findfirst can be like find return an empty array when the query mathes null

**Comment by sergeyklay** [comment]
Actually the `find` method acts as the collection's find. Eg. gets all items matched the criteria. So collection can be empty (array).

However the `findFirst` tries to get an entity but the entity can't be empty (array).

**Comment by Jurigag** [comment]
When user doesn't exists there is false returned, that add some condition like 

```php
if ($user) {
    $user->toArray();
}
```
