### ISSUE TITLE
Add support to use class names or services for Events\Manager::attach

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#12886]

**Comment by andrew-demb** [comment]
But it's not responsibility for the event manager. For why?

Let's keep about don't make super classes in framework

**Comment by Jurigag** [comment]
What's a problem with current behavior as it is?

**Comment by sergeyklay** [comment]
Actually I want to use something like this:
```php
$lazyEventsMap = [
    'event_name' => [
        'Namespace\To\The\Listener',
        'Yet\Another\Listener',
    ],
    'yet_another_event_name' => [
        'Namespace\To\The\Listener',
        'Yet\Another\Listener',
   ],
];

array_walk($lazyEventsMap, function ($listeners, $event) {
    array_map(function ($listener) use ($event) {
        $this->getEventsManager()->attach($event, $listener);
    }, $listeners);
});
```

**Comment by andrew-demb** [comment]
How about this?

`
if (is_string($listener)) {
     $listener = $container->get($listener);
}

$this->getEventsManager()->attach($event, $listener);
`

**Comment by sergeyklay** [comment]
I don't want to use `if`, also `$container->get` will create a new instance right now

**Comment by andrew-demb** [comment]
I don't understand. You can replace it by `getShared()`, or `new $listener()` (smell).

How you imagine for realization in event manager?

**Comment by Jurigag** [comment]
I guess in event manager it should do exactly what you posted @andrew-demb

**Comment by andrew-demb** [comment]
@Jurigag it will take place for configuring events in the application by simple arrays.

I prefer variant with initializing before attaching, or by adding some decorator by event

**Comment by sergeyklay** [comment]
The `get`, `getShared`, etc will create object. At least once. I don't want to create object If the event does not occur

**Comment by andrew-demb** [comment]
I think it would be a solution. Only need to replace 

```php
...
// Check if the listener has implemented an event with the same name
if method_exists(handler, eventName) {
...
```

To
```php
// I don't know, is Zephir have this function (is_callable)
if method_exists(handler, eventName) || is_callable([handler, eventName]))
```

```php
class Proxy
{
    private $container;
    private $service;
    private $options;

    private $wrappedObject;

    public function __construct($container, $service, $options = null)
    {
        $this->container = $container;
        $this->service    = $service;
        $this->options    = $options;
    }

    public function __call($name, $arguments)
    {
        if (null === $this->wrappedObject) {
            $this->wrappedObject = $this->createObject();
        }

        return $this->wrappedObject->{$name}(...$arguments);
    }

    private function createObject()
    {
        return $this->container->get($this->service, $this->options);
    }
}

$proxy = new Proxy(Di::getDefault(), 'modelsManager', null);

var_dump($proxy->isInitialized('Model\Robot'));
```

As result, we don't make class event manager as super

**Comment by sergeyklay** [comment]
This is why I want to incapsulate it into framework. To not to force developers to do it themselves

**Comment by andrew-demb** [comment]
OK, but let's do it more accuracy and extensible. Otherwise, it will add more complexity to search problem while debugging. Working with DI container as a service locator, class creator (not by defined configs) by internals is one of the reasons, why I want to don't use it in next project. And because this is often implicitly.

We can write interface EventHandlerStorageInterface, with method `getHandler('name')`.
And register it as a dependency of the dispatcher. As a default, it will be a ContainerStorage with behavior store previously requested handlers.

But, please, don't hardcode it as part of the main class. For allow, the devs remove this feature or change behavior

**Comment by michanismus** [comment]
Hmm, I don't like it.
You create a lazy map and when an event is fired you start to walk through the "map", check for instance and create it if needed? And you do it for every triggered event? I don't see any benefit.

I guess this is something for Incubator repo.

**Comment by andrew-demb** [comment]
@michanismus plus one `if` in every event (array_key_exists) VS initialize all subscribers on bootstrapping application.

**Comment by sergeyklay** [comment]
@michanismus Nope. When an event is fired the events manager can call `di->get(class)` or just `new class` without loop on the "map". This is how currently works `attach`. I want to introduce attaching just "string" to the event, not object only.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/3133
