### ISSUE TITLE
nginx stopped suddenly

### ISSUE THREAD

**Issue by kolkata1234** [phalcon/cphalcon#12885]
nginx conf file
---------------
user  nginx;
worker_processes  4;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  150;

    #gzip  on;
    client_max_body_size 200M;
    server_names_hash_bucket_size 64;
    #include /etc/nginx/conf.d/*.conf;

   server {
    listen       80;
    server_name localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

    location / {
      proxy_pass http://localhost:3000/;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection 'upgrade';
                        proxy_set_header Host $host;
                        proxy_cache_bypass $http_upgrade;
                }
    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
 }
 server {
   listen       90;
    server_name  localhost;
location / {
            root   html;
            index  index.html index.htm;
        }

    location /local/var/www/images {
            alias /home/xxxx/work/upload/data;
        }
    }

}
-------------------------------------------
Error is showing nginx error.log
-----------------------------------
2017/06/07 10:19:14 [error] 857#857: *99011 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 213.254.241.7, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "xxxx.com"
2017/06/07 10:19:14 [warn] 857#857: *99011 upstream server temporarily disabled while reading response header from upstream, client: 213.254.241.7, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "xxxx.com"
----------------------------------

Please suggest some solution..

**Comment by virgofx** [comment]
This is a configuration issue with your web server and not a Phalcon issue.

**Comment by kolkata1234** [comment]
Please let me know what would be the configuration issue...

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
