### ISSUE TITLE
EventsManager detach listener issue

### ISSUE THREAD

**Issue by addinm** [phalcon/cphalcon#12882]
Hi!

It looks like there is a problem with detaching listeners from events.

> Example

```php
use Phalcon\Events\Event;

$eventsManager->attach(
    'test:event',
    function(Event $event, $source, $data) {
        echo 'test';
    }
);

$eventsManager->fire('test:event', $context, ['foo' => 'bar'], true);

$eventsManager->detach(
    'test:event',
    function(Event $event, $source, $data) {
        echo 'test';
    }
);

$eventsManager->fire('test:event', $context, ['foo' => 'bar'], true);
```

> Result:

test
test

**Comment by sergeyklay** [comment]
Did you echo `test ` in `attach` and `detach`? Could you please explain a bit more?

**Comment by addinm** [comment]
Hi,

Here is a simplified example:

1. First of all I attach the listener to the "test:event" event:

```php
<?php

use Phalcon\Events\Event;

$eventsManager->attach(
    'test:event',
    function(Event $event, $source, $data) {
        echo 'fired!';
    }
);
```
2. Next I ask the eventsManager to fire the "test:event" event:

```php
$eventsManager->fire('test:event', $context);
```

3. This outputs the following: "**fired!**". This is еру expected behaviour.

4. Now I detach the listener from the eventsManager using the "detach" method that accepts 2 parameters according to your docs: "eventType" and "handler". "eventType" is "test:event" and the handler is the callable object: function(Event $event, $source, $data) {echo 'fired!';}:

```php
$eventsManager->detach(
    'test:event',
    function(Event $event, $source, $data) {
        echo 'test';
    }
);
```
At this moment I expect that the listener is just removed from the "test:event" event.

5. Let's see if the listener was removed:

 ```php
$eventsManager->fire('test:event', $context);
```
This outputs the following: "fired!" and this is unexpected behaviour. This means that the listener wasn't removed. 

If you debug the "detach" method, you'll see that the following code always returns TRUE because the registered "data['data']" handler is never equal to the handler from the argument.:

(https://github.com/phalcon/cphalcon/blob/master/phalcon/events/manager.zep#L116) 

if data["data"] !== handler {
    newPriorityQueue->insert(data["data"], data["priority"]);
}

Does this make sense?

**Comment by yaronius** [comment]
@addinm Have you tried code that detaches the very same callable? I.e. like this:
```php
$handler = function(Event $event, $source, $data) {
        echo 'test';
};
$eventsManager->attach(
    'test:event',
    $handler
);

$eventsManager->fire('test:event', $context, ['foo' => 'bar'], true);

$eventsManager->detach(
    'test:event',
    $handler
);

$eventsManager->fire('test:event', $context, ['foo' => 'bar'], true);
```

**Comment by addinm** [comment]
@yaronius Yes, the result is the same.

**Comment by sergeyklay** [comment]
```php
$priorityQueue = [];
$priorityQueue[] = function () { echo "Hello"; };
$key = array_search(function () { echo "Hello"; }, $priorityQueue, true);
var_dump($key); // FALSE

$priorityQueue = [];
$handler = function () { echo "Hello"; };
$priorityQueue[] = $handler;
$key = array_search($handler, $priorityQueue, true);
var_dump($key); // 0
```

**Comment by sergeyklay** [comment]
```php
<?php

class Stack
{
    protected $handlers = [];

    public function add($handler)
    {
        $handler = $this->resolve($handler);
        $id = $this->getHandlerIdentifier($handler);

        $this->handlers[$id] = $handler;
    }

    public function remove($handler)
    {
        $handler = $this->resolve($handler);
        $id = $this->getHandlerIdentifier($handler);

        unset($this->handlers[$id]);
    }

    public function count()
    {
        return count($this->handlers);
    }

    protected function resolve($handler)
    {
        if (!is_object($handler)) {
            throw new InvalidArgumentException("Handler must be an object");
        }

        return $handler;
    }

    private function getHandlerIdentifier($handler)
	{
		return spl_object_hash($handler);
	}
}

$stack = new Stack();

$stack->add(function () { echo "Hello World"; });
var_dump($stack->count()); // 1

$stack->remove(function () { echo "Hello World"; });
var_dump($stack->count()); // 1


$stack = new Stack();
$handler = function () { echo "Hello World"; };

$stack->add($handler);
var_dump($stack->count()); // 1

$stack->remove($handler);
var_dump($stack->count()); // 0
```

**Comment by addinm** [comment]
Thank you for your work, @sergeyklay

I think it would be great if the "**attach**" method that adds listener to the event can accept (or accepts) the third parameter - "**listenerID**". In your example above and in the current version of the framework we need to pass the handler in the "**attach**" and the "**detach**" methods. 

What if we have a large modular application and we want to remove the third-party extension listener from the event? Using the existing approach we'll need to copy-paste the handler of the listener we are interested in and then pass it in the  "**detach**" method. This will be a headache. Instead of this, we can simply detach the listener using its ID, like this:

Attaching:
`$result = $eventsManager->attach('component:event', $handler,  'listenerID');`

Detaching: 
`$result = $eventsManager->detach('component:event', 'listenerID');`

What do you think?

**Comment by sergeyklay** [comment]
Could you please open a NFR for `listenerID`.

**Comment by sergeyklay** [comment]
Actually I can't imagine a real use case when someone does something like that:

```php
$eventsManager->attach('event', function () {
    // Multilines lines closure
    // Not just foobar
});

// ..

$eventsManager->detach('event', function () {
    // So we need again copy and paste previous multiline closure here
});
```

Note, in this case detach does not work because each time `function () {}` is **new** closure with **new** identity (hash / id / etc). It is PHP-related stuff.

But [as you can see](https://github.com/phalcon/cphalcon/pull/12883) this approach works well without introducing a `listenerID`:

```php
$handler = function () {
    // Multilines lines closure
    // Not just foobar
};

$eventsManager->attach('event', $handler);

// ..

$eventsManager->detach('event', $handler);
```

 So, I'm not sure about this. This is why I added `Not a bug` label.

**Comment by andrew-demb** [comment]
If a zephir have a function, similar to `spl_object_hash`, we can use it instead of search by objects

**Comment by sergeyklay** [comment]
> It is PHP-related stuff.

Zephir is based on PHP
