### ISSUE TITLE
Why :name, :name: or '?' don't working for query with LIMIT?

### ISSUE THREAD

**Issue by manyopensource** [phalcon/cphalcon#12893]
Example:
```PHP
$sql = 'SELECT * FROM night LIMIT ?';
$items = new Simple(null, $gtg, $gtg->getReadConnection()->query($sql, [100]));
```
Error:

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''100'' at line 1

**Comment by manyopensource** [comment]
Example:
$sql = 'SELECT * FROM night LIMIT ?';
$items = $this->db->query($sql, [100]);

Error:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''100'' at line 1

**Comment by manyopensource** [comment]
''100'' = ' '100' ' (don't "100")

**Comment by sergeyklay** [comment]
```php
use Phalcon\Db\Column;
use Phalcon\Mvc\Model\Resultset\Simple;

$phql = 'SELECT * FROM Vokuro\Models\Users LIMIT :LIMIT:';

$this->getDI()->getModelsManager()
    ->createQuery($phql)
    ->execute(
        ['LIMIT' => 3], 
        ['LIMIT' => Column::BIND_PARAM_INT]
);

var_dump($result instanceof  Simple); // TRUE
var_dump($result->count() === 3); // TRUE
```

**Comment by sergeyklay** [comment]
https://stackoverflow.com/questions/2269840/how-to-apply-bindvalue-method-in-limit-clause
