### ISSUE TITLE
Query data some times show data binding mismatch

### ISSUE THREAD

**Issue by nealwon** [phalcon/cphalcon#12890]
### Querying data using model find or findFirst or count sometimes show me mismatch param binding
 This disturbed me for a long time! 

```php
MyModel::findFirst([
        'conditions'    => 'mid=?0', // I also used binding param with :MID:,same exception occurred
        'bind'          => [
            $mid,   // I confirmed this is not empty
        ],
    ]);
```

errors:
> SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens<br><pre>#0 [internal function]: PDOStatement->execute()
 #1 [internal function]: Phalcon\Db\Adapter\Pdo->executePrepared(Object(PDOStatement), Array, Array)
 #2 [internal function]: Phalcon\Db\Adapter\Pdo->query('SELECT `my_...', Array, Array)
 #3 [internal function]: Phalcon\Mvc\Model\Query->_executeSelect(Array, Array, Array)
 #4 [internal function]: Phalcon\Mvc\Model\Query->execute()
 #5 /opt/www/web/app/common/models/ModelBase.php(181): Phalcon\Mvc\Model::findFirst(Array)
 #6 /opt/www/web/app/common/models/MyModel.php(89): 
  Magic\Common\Models\ModelBase::findFirst(Array)
 #7 /opt/www/web/app/modules/v1/controllers/AController.php(305): 
    Magic\Common\Models\MyModel::findFirst(Array)
 #8 /opt/www/web/app/modules/v1/controllers/AController.php(64): 
    Magic\Modules\V1\Controllers\AController->check(Array)
 #9 [internal function]: Magic\Modules\V1\Controllers\AController->autoAction()
 #10 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(Magic\Modules\V1\Controllers\AController), 'autoAction', Array)
 #11 [internal function]: Phalcon\Dispatcher->_dispatch()
 #12 [internal function]: Phalcon\Dispatcher->dispatch()
 #13 /opt/www/web/app/bootstrap_web.php(58): Phalcon\Mvc\Application->handle()

### Details

* Phalcon version: (3.2.0a) / 3.1.2 also produces this error
* PHP Version:
  PHP 7.1.4 (cli) (built: May 13 2017 17:32:17) ( NTS )
  Copyright (c) 1997-2017 The PHP Group
  Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
* Operating System: CentOS 7.2
* Installation type: Compiling from source 
* Zephir version (if any):
* Server: Nginx
* Database: mysql
* Table Schema:   
  > CREATE TABLE `my_lists` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(100) DEFAULT NULL,
  `status` tinyint(1) DEFAULT '0',
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by Jurigag** [comment]
You could check in beforeQuery event what `getSqlVariables` returns.

**Comment by nealwon** [comment]
I've tried many times these days, but none appearance. I will continue watching this and append infos here when it appear again.

thx anymore!

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. Feel free to open this again or ping me if the need arises. Thank you for contributing.
