### ISSUE TITLE
Request getPut

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12892]
Currently getPut is working only on form data, like on raw body request. When you send json it doesn't work and you need to use `getJsonRawBody` anyway. Im thinking about checking request header - if it's `application/json`, then use `getJsonRawBody` instead of `getRawBody` in `getPut` method.

To not introduce some big breaking change(will it break anything though?) it could be as php.ini option to enable this behavior.

Any thoughts?

**Comment by sergeyklay** [comment]
Could you please provide a small script to reproduce

**Comment by Jurigag** [comment]
What you mean? It's NFR.

```
$this->request->getPut('id');
```

When sending json body with id value will don't return anything. Just go into surce code of getPut method, you will already see what i mean.

**Comment by sergeyklay** [comment]
did you try php://input ?

**Comment by itbdw** [comment]
@Jurigag you have pointed this problem at 2017?

And now is 2018, still exists 😢

**Comment by sergeyklay** [comment]
Fixed in the `3.4.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
