### ISSUE TITLE
Missing packages for Debian wheezy @packagecloud

### ISSUE THREAD

**Issue by stamster** [phalcon/cphalcon#12900]
### Expected and Actual Behavior

> **Installing Phalcon on a server running Debian GNU/Linux 7.11, codename Wheezy**

> Provide minimal script to reproduce the issue

Following guide on official site: https://phalconphp.com/en/download/linux

> cat phalcon_stable.list 
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/phalcon/stable

deb https://packagecloud.io/phalcon/stable/debian/ wheezy main
deb-src https://packagecloud.io/phalcon/stable/debian/ wheezy main
```
Install for PHP 5.6.x
```
apt-get install php5-phalcon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php5-phalcon
```

Results:
https://packagecloud.io/app/phalcon/stable/search?filter=all&q=&dist=wheezy

### Details

* Phalcon version: (`none yet`)
* PHP Version: (`5.6.30`)
* Operating System:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.11 (wheezy)
Release:	7.11
Codename:	wheezy
```
* Installation type: installing via package manager
* Zephir version (if any): n/a
* Server: Nginx | Apache | Nginx
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
It is not Phalcon issue. Could you please create docs related issues in the [appropriate repository](https://github.com/phalcongelist/packagecloud)?
