### ISSUE TITLE
Windows builds for 3.2.1 are reporting 3.2.0 in phpinfo

### ISSUE THREAD

**Issue by echodreamz** [phalcon/cphalcon#12907]
### Expected and Actual Behavior

> phpinfo output is showing Phalcon v3.1.1 with build date Jun 18 2017 16:23:55

Expected `v3.2.0 with build date Jun 18 2017 16:23:55`

This applies to PHP 5.5, 5.6, 7.0 and 7.1

![capture](https://user-images.githubusercontent.com/18668727/27264850-b32b360e-5445-11e7-84a0-2fde6b5ac25b.PNG)

### Details

* Phalcon version: 3.1.1 (should be 3.2.0)
* PHP Version: 7.0.20
* Operating System: Windows Server 2016
* Installation type: pre-compiled package from github releases
* Zephir version (if any): NA
* Server: IIS
* Other related info (Database, table schema): NA

**Comment by sergeyklay** [comment]
@echodreamz Could you check `Phalcon\Version::get()`

**Comment by niden** [comment]
Let me recompile them @echodreamz

**Comment by echodreamz** [comment]
@sergeyklay
 
`3.1.1`

is the output of `Phalcon\Version::get()`

**Comment by niden** [comment]
@echodreamz Could you be so kind and download the DLL again? I recompiled them and uploaded them in the release.

**Comment by echodreamz** [comment]
@niden PHP 7.x fixed, PHP 5.5 and 5.6 still show 3.1.1.

**Comment by echodreamz** [comment]
@niden any updates for the 5.x builds?

Thanks!

**Comment by niden** [comment]
@echodreamz I am at work at the moment but will get to it in 2-3 hours.

**Comment by niden** [comment]
@echodreamz I just uploaded new php 5.x DLLs. Do you mind checking and letting me know?

**Comment by echodreamz** [comment]
@niden All fixed up! Thank you sir!

**Comment by echodreamz** [comment]
The issue has occured again with the 3.2.1 builds, they now show version 3.2.0 with a build date of Jul 10 2017 09:59:44.

**Comment by sergeyklay** [comment]
@niden Could you please try to sort out?

**Comment by niden** [comment]
@echodreamz I recompiled the DLLs. Can you check it out that it all works for you please?

**Comment by echodreamz** [comment]
@niden All is well in the world now. Thank you!

**Comment by virgofx** [comment]
Thanks @echodreamz
