### ISSUE TITLE
Twice Insert db service

### ISSUE THREAD

**Issue by bestirani2** [phalcon/cphalcon#12917]
After execute below code, twice record added in my table.
```php
 $config = new \Phalcon\Config([
    'database' => [
    ]
]);

$di = new FactoryDefault();
$di->setShared('db', function () use ($config) {
    $dbConfig = $config->database->toArray();
    $adapter = $dbConfig['adapter'];
    unset($dbConfig['adapter']);
    $class = 'Phalcon\Db\Adapter\Pdo\\' . $adapter;
    return new $class($dbConfig);
});

**$di->get('db')->query("INSERT INTO dbname.table VALUES ('', '');")->execute();**
```

### Details

* Phalcon version: 3.2.0
* PHP Version: 7
* Operating System: Ubuntu
* Server: Nginx

**Comment by Jurigag** [comment]
Can't reproduce.

**Comment by Jurigag** [comment]
Query and execute are both executing sql statement. query method returns db object, and you execute again same query. Query should be used if there is result returned(rows), execute if no.

**Comment by stamster** [comment]
`execute()` -> Sends SQL statements to the database server returning the success state. **Use this method only when the SQL statement sent to the server doesn’t return any rows**
`query()` -> Sends SQL statements to the database server returning the success state. **Use this method only when the SQL statement sent to the server is returning rows**

**Comment by Jurigag** [comment]
@stamster well you missed that query return other object than db adapter, i first thought the same, but still, object returned have execute method too - so generally speaking he just executes two times query.
