### ISSUE TITLE
PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/phalcon.so' - /usr/lib64/php/modules/phalcon.so: undefined symbol: zend_error_noreturn in Unknown on line 0

### ISSUE THREAD

**Issue by einaranjo** [phalcon/cphalcon#12914]
error on install PHP-PHALCON

OS : CentOS release 6.9 (Final)
PHP 5.6.30 (cli) (built: Jan 19 2017 08:09:42)
nginx version: nginx/1.12.0
error : PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/phalcon.so' - /usr/lib64/php/modules/phalcon.so: undefined symbol: zend_error_noreturn in Unknown on line 0

readelf -d /usr/lib64/php/modules/phalcon.so 

Dynamic section at offset 0x4821f8 contains 21 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [phalcon.so]
 0x000000000000000c (INIT)               0x63370
 0x000000000000000d (FINI)               0x3dc0b8
 0x000000006ffffef5 (GNU_HASH)           0x1b8
 0x0000000000000005 (STRTAB)             0x83c0
 0x0000000000000006 (SYMTAB)             0x1bb0
 0x000000000000000a (STRSZ)              35559 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x6831f0
 0x0000000000000002 (PLTRELSZ)           14664 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x5fa28
 0x0000000000000007 (RELA)               0x11788
 0x0000000000000008 (RELASZ)             320160 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x11758
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x10ea8
 0x000000006ffffff9 (RELACOUNT)          12835
 0x0000000000000000 (NULL)               0x0

```
[root@localhost build]# ./install --phpize /usr/bin/phpize --php-config /usr/bin/php-config
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f 
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*
Cleaning..
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
libtool: compile:  gcc -I. -I/root/cphalcon/build/php5/64bits -DPHP_ATOM_INC -I/root/cphalcon/build/php5/64bits/include -I/root/cphalcon/build/php5/64bits/main -I/root/cphalcon/build/php5/64bits -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -c /root/cphalcon/build/php5/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
libtool: link: gcc -shared  .libs/phalcon.o    -march=native -mtune=native   -Wl,-soname -Wl,phalcon.so -o .libs/phalcon.so
libtool: link: ( cd ".libs" && rm -f "phalcon.la" && ln -s "../phalcon.la" "phalcon.la" )
libtool: install: cp ./.libs/phalcon.so /root/cphalcon/build/php5/64bits/modules/phalcon.so
libtool: install: cp ./.libs/phalcon.lai /root/cphalcon/build/php5/64bits/modules/phalcon.la
libtool: finish: PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ein/bin:/sbin" ldconfig -n /root/cphalcon/build/php5/64bits/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /root/cphalcon/build/php5/64bits/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/lib64/php/modules/
Installing header files:           /usr/include/php/

Thanks for compiling Phalcon!
Build succeed: Please restart your web server to complete the installation
```

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/12909

**Comment by remicollet** [comment]
@einaranjo use my repository, everything available there, including most PHP versions and most extensions (of course, including this extension)   ;)

**Comment by einaranjo** [comment]
how i can use your repository ?

**Comment by remicollet** [comment]
@einaranjo see https://rpms.remirepo.net/wizard/
