### ISSUE TITLE
Binding parameters with IN({placeholder:array}) only works when array is 0 indexed.

### ISSUE THREAD

**Issue by nikolay-mihaylov** [phalcon/cphalcon#12928]
Binding parameters with `IN({placeholder:array})` only works when array is 0 indexed.

Code snippet to reproduce:

```php
// Works with 0 indexed arrays
$types = [
    0 => 3,
    1 => 4,
];

// Does not work. 
// Causes PDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
$types = [
    1 => 3,
    2 => 4,
];
$items = $this->modelsManager->createBuilder()
    ->columns([
        'id',
        'type',
    ])
    ->from('Models\Pages')
    ->where('type IN({types:array})', ['types' => $types])
    ->getQuery()->execute();
```
### Details
* Phalcon version: 3.0.2 and 3.2.x
* PHP Version: 7.0.13
* Operating System: Windows 10
* Installation type: Windows DLL
* Server: Apache
* Other related info (Database, table schema): MySQL with PDO

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/11842
