### ISSUE TITLE
Raw Query causing SQLSTATE[HY000]: General error, in 95% of the cases

### ISSUE THREAD

**Issue by Slind14** [phalcon/cphalcon#12920]
### Expected and Actual Behavior

I'm trying to run a raw sql query. This worked fine with phalconphp legacy, but does not longer with the latest ubuntu package. According to the docs, this is still the way to do it. The odd thing is, that this query works fine in 5% of the cases. So if one refreshes the page a hundred times, it loads without error a few times.

> Schema

```SQL
CREATE TABLE `ticket_read` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `ticket_id` int(11) NOT NULL,
  `ticket_read_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `ticket_read`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `user_id` (`user_id`,`ticket_id`);
ALTER TABLE `ticket_read`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
```

> the sql
```php
        $sql = "INSERT INTO ticket_read (user_id, ticket_id, ticket_read_at)
            VALUES (1, 55, NOW())
            ON DUPLICATE KEY UPDATE
            ticket_read_at = NOW()";
```

> Exception

```php
SQLSTATE[HY000]: General error
```

> minimal script to reproduce

```php
        $ticketRead = new TicketRead();

        return new Resultset(
            null,
            $ticketRead,
            $ticketRead->getReadConnection()->query($sql, null)
        );
```
> running the query directly through pdo works fine

```php
        $di             = \Phalcon\DI::getDefault();
        $db             = $di['db'];
        $data           = $db->query( $sql );
        $results        = $data->execute();
```
### Details

* Phalcon version: 3.1.2
* PHP Version: 7.0.18
* Operating System: ubuntu
* Installation type: via package manager
* Zephir version (if any): -
* Server: Apache
* Database: MariaDB 10.2.6 - Mysql 15.1 (phalcon adapter setting: Mysql)

**Comment by Jurigag** [comment]
Wait, so this second code works fine but first not? Interesting. Also please provide table schema.

**Comment by Slind14** [comment]
> Wait, so this second code works fine but first not? Interesting. Also please provide table schema.

Yes. The first one also works with phalcon legacy, but according to the doc it didn't change since.
I added the schema.

**Comment by Jurigag** [comment]
Well internally both of them are doing pretty much the same stuff.

**Comment by Slind14** [comment]
hmm, are you able to reproduce it?

**Comment by Jurigag** [comment]
I will check it tomorrow maybe.

**Comment by Jurigag** [comment]
Also provide what database adapter what you use, what database server and version.

**Comment by Slind14** [comment]
sure, updated.

**Comment by stamster** [comment]
MariaDB 10.2.x has some nasty behavior - take a look at docs, especially for "SQL MODE".
My 5 cents only, IDK if that is your issue.

**Comment by Slind14** [comment]
It worked fine with phalcon legacy;

**Comment by stamster** [comment]
I'll try to reproduce this case.

**Comment by Slind14** [comment]
Did you have any luck with reproduction?

**Comment by RayHughes** [comment]
This issue is occurring frequently since the new phalcon release.

**Comment by Slind14** [comment]
de-stale
