### ISSUE TITLE
Phalcon\Cache\Exception: Failed to authenticate with the Redisd server 

### ISSUE THREAD

**Issue by artisanBill** [phalcon/cphalcon#12925]
Phalcon\Cache\Exception: Failed to authenticate with the Redisd server File=phalcon/cache/backend/redis.zep Line=131 #0 [internal function]: Phalcon\Cache\Backend\Redis->_connect() #1 [internal function]: Phalcon\Cache\Backend\Redis->get('cvrhndg252o9bbb...', 2592000) #2 [internal function]: Phalcon\Session\Adapter\Redis->read('cvrhndg252o9bbb...') #3 [internal function]: session_start() #4 /developer/company/leyou/web/app/config/services.php(90): Phalcon\Session\Adapter->start() #5 [internal function]: Closure->{closure}() #6 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault)) #7 [internal function]: Phalcon\Di->get('session', NULL) #8 [internal function]: Phalcon\Di->getShared('session') #9 /developer/company/leyou/web/app/controllers/ControllerBase.php(17): Phalcon\Di\Injectable->__get('session') #10 [internal function]: ControllerBase->afterExecuteRoute(Object(Phalcon\Mvc\Dispatcher), NULL) #11 [internal function]: Phalcon\Dispatcher->_dispatch() #12 [internal function]: Phalcon\Dispatcher->dispatch() #13 /developer/company/leyou/web/public/index.php(32): Phalcon\Mvc\Application->handle() #14 {main}

**Comment by artisanBill** [comment]
Environment
php: 7.1.5
nginx: 1.12.0
redis: v=3.2.9

**Comment by Jurigag** [comment]
Duplicate https://github.com/phalcon/cphalcon/issues/12736
