### ISSUE TITLE
Call to undefined method ::beforeexecuteroute() Phalcon 3.2.0

### ISSUE THREAD

**Issue by YamiChat** [phalcon/cphalcon#12924]
I updated Phalcon from 3.1.2 to 3.2.0 version and now have exception: `Exception: Call to undefined method ::beforeexecuteroute()`

```php
class AuthController extends Controller {
  public function beforeExecuteRoute($dispatcher) {
     ... 
  }
  ...
}
```

This function exists in the 3.2.0 version: https://docs.phalconphp.com/en/3.2/controllers Can you help me?

### Details

* Phalcon version: 3.2.0
* PHP Version:PHP 7.1.1
* Operating System: macOS Sierra
* Installation type: Compiling from source
* Powered by Zephir	Version 0.9.9-868cb1f92b

**Comment by Jurigag** [comment]
I think this is somehow zephir issue @sjinks

**Comment by YamiChat** [comment]
Returned 3.1.2 version but the error still remains,
Installation type: `brew install php71-phalcon`
Phalcon version: 3.1.2
PHP Version: 7.1.5
Zephir: Version 0.9.7-1fae5e50ac

**Comment by stamster** [comment]
Did you restarted web server after you re-installed 3.1.2?

**Comment by YamiChat** [comment]
Yes, of course

**Comment by Jurigag** [comment]
Can't reproduce.

**Comment by YamiChat** [comment]
I think the problem with PHP 7.1.5 (+phalcon), 
Yesterday I used Phalcon 3.1.2 with php5.6.29 without any problems

**Comment by Jurigag** [comment]
But i use php 7.1.0, do you use TS or NTS?

**Comment by YamiChat** [comment]
I use mamp php 7.1.1 https://www.mamp.info/en/downloads/

**Comment by Jurigag** [comment]
Just check in `phpinfo()` is this TS or NTS?

**Comment by YamiChat** [comment]
PHP Extension Build	API20160303,NTS
Thread Safety	disabled
this?

**Comment by Jurigag** [comment]
Yea, then idk, need full code to reproduce issue.

**Comment by YamiChat** [comment]
oh, the problem was that now we need 
`public function beforeExecuteRoute($dispatcher) {`
not
`protected function beforeExecuteRoute($dispatcher) {`

thanks

**Comment by Jurigag** [comment]
Haha, good to know.

**Comment by Jurigag** [comment]
Well we need to update it to is_callable and hopefully it will be fixed.
