### ISSUE TITLE
Bug: $this->getDI()->getShared('dispatcher') returned bool

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#12929]
Hello. I'm not very good know English language, Russian is better.

```php
<?php

class TranslationPlugin extends \Phalcon\Mvc\User\Plugin
{
    public function __construct()
    {
        var_dump(
            $this->getDI()->getShared('dispatcher')
        );
        var_dump(
            $this->getDI()->getShared('request')
        );
    }

```
why is the first var_dump returns bool(true), and the second \Phalcon\Request?
The idea is to return the object \Phalcon\Mvc\Dispatcher, but instead returns bool(true).
Explain to me, can I something not so do?

### Details

* Phalcon version: 3.2.0
* PHP Version: PHP Version 7.1.5-1+deb.sury.org~xenial+2
* Operating System: Ubuntu 16.04 TLS Xenial
* Installation type: installing via package manager
* Zephir version (if any): 	Version 0.9.8-6335775f25
* Server: Apache 2

**Comment by stamster** [comment]
https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_User_Plugin
https://olddocs.phalconphp.com/en/latest/api/Phalcon_Mvc_User_Plugin

**Comment by andrew-demb** [comment]
@stamster, about constructor: why don't use? He can do it without any danger.

@TimurFlush, please, provide a script to reproduce.

P.S.: I have no problem with it - https://gist.github.com/andrew-demb/8f1bfcd37561efe3ed09dc3627e13a41

**Comment by TimurFlush** [comment]
@andrew-demb, I, too, have with your code no problem.
@stamster, You can use a constructor.

Don'T know how to describe it to you, it at least needs to see.
https://youtu.be/eViIviXw4zA
