### ISSUE TITLE
Why does Redis adds a "_PHCR" prefix ?

### ISSUE THREAD

**Issue by ricardofiorani** [phalcon/cphalcon#12923]
https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/cache/backend/redis.zep#L157

It already adds a prefix with the prefixable trait, so why add another prefix ? It only makes harder for people to migrate from Phalcon 1...

**Comment by sergeyklay** [comment]
The redis cache backend adds `_PHCR` prefix to every cached key and uses `_PHCR` set to store all the cached keys. It required to be able to flush the Redis database.

We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
