### ISSUE TITLE
MYSQL_ATTR_USE_BUFFERED_QUERY = false    result in find() return empty!

### ISSUE THREAD

**Issue by fxm5547** [phalcon/cphalcon#12933]
`MYSQL_ATTR_USE_BUFFERED_QUERY = false`  result in find() return empty!

**Comment by stamster** [comment]
RDBMS version, details? OS?
Table structure sample?
PHP version, PhalconPHP version?

**Comment by fxm5547** [comment]
- CentOS 7.2  
- MySQL 5.6
- PHP 7.1 Phalon 3.0.2
- Any Table structure

**Comment by fxm5547** [comment]
- 目前已经对接4大出版社，数据在表ecs_onix_products
- 从亚马逊、豆瓣等抓取更详尽的图片、属性和介绍

**Comment by fxm5547** [comment]
$di->set('unbufferedRDb', function () use ($config) {
    return new DbAdapter(array(
        "host" => $config->database->readhost,
        "username" => $config->database->username,
        "password" => $config->database->password,
        "dbname" => $config->database->dbname,
        "charset" => $config->database->charset,
        "options" => array(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false, PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION)
    ));
});
