### ISSUE TITLE
[BUG] Calling flush() on \Phalcon\Cache\Backend\Apcu fails

### ISSUE THREAD

**Issue by ilogs-sepa** [phalcon/cphalcon#12934]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

I want to clear/purge the complete APCU cache by calling the flush method from the Backend class.
At the moment this just yields the following exception text:

`Call to undefined function apc_delete()`

The exepcted behaviour is to silently purge what is there to purge.

Seems to be a simple bug.

### Details

* Phalcon version: 3.2.0
* PHP Version: 7.1.5

**Comment by sergeyklay** [comment]
There is two extension:
* APC
* APCU

These extensions provides own functions:
* `apc_`
* `apcu_`

To use old APC functions like `apc_delete` (note, not `apcu_delete`) with APCU extensions you have to install and enable `acpu_bc` extension. https://pecl.php.net/package/apcu_bc

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open new issue if the problem appears again. Thank you for contributing.
