### ISSUE TITLE
appendMessage before execute validation

### ISSUE THREAD

**Issue by hufersil** [phalcon/cphalcon#12943]
**Steps to recreate**
1. create a validator
2. add some rules
3. add a custom message with **appendMessage**
4. execute validation

### Expected and Actual Behavior
**expected**: return all messages in validator
**actual behavior**: only messages included by validators are returned

**example:**

```php
class Robot extends Model 
{
    public function validation()
    {
        $validator = new \Phalcon\Validation();

        # add some rules
        $validator->add("field1", ...);
        $validator->add("field2", ...);
        $validator->add("field3", ...);

        # add custom message
        # this message is not returned!!!
        $validator->appendMessage(new \Phalcon\Validation\Message(...));

        # execute
        return $this->validate($validator);
    }
}
```

looking at **validation.zip**, I think the problem is at line 121
```let this->_messages = messages;```

It resets the **_messages** property. In imo, it should check if the property is not null first.

If I append the message **after** the validation gets executed, it will not be included in model's messages, so the validate method of **\Phalcon\Mvc\Model** may return incorrect value.

Thanks in advanced!

**Comment by Jurigag** [comment]
You should append messages to model using `$this->appendMessage` and class `Phalcon\Mvc\Model\Message` i think.

**Comment by hufersil** [comment]
@Jurigag 

First, thanks for replying so quickly!

The model.validate method gets the messages from validation.validate method. So I thought I should append the messages in the **Phalcon\Validation object, and the call to Phalcon\Mvc\Model.validate should get them even if I add them manually**

And I don't think this is a workaround.
Once the validation allows me to append messages manually, imo it should consider them in the validation proccess.

For now, I'm adding the messages directly to the model, as you suggested.

Best regards.

**Comment by Jurigag** [comment]
I mean what i proposed is workaround, it's pretty much doing the same stuff.
