### ISSUE TITLE
[MVC] Add afterFind event

### ISSUE THREAD

**Issue by Wirone** [phalcon/cphalcon#12945]
### Expected and Actual Behavior

There is no `afterFind` event for database models. In this case, there is no easy way to implement re-usable extensions (behaviors) for manipulating data after retrieving from database and before returning model(s).

If such an event were triggered after finding records, `SoftDelete` behavior could automatically filter results and exclude deleted records.

### Details

* Phalcon version: 3.2.0
* PHP Version: 7.1.4
* Operating System: Windows 7
* Installation type: downloaded DLL
* Zephir version (if any): n/a
* Server: Apache
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
There is afterFetch, not sure what more you need?

**Comment by Wirone** [comment]
I've read [the docs](https://docs.phalconphp.com/en/3.2/db-models-events) today and there isn't `afterFetch` event. I would never create this issue if I found it there :-)

**Comment by Jurigag** [comment]
@niden you missed afterFetch event :D

Also keep in mind that afterFetch is fired ONLY on MODEL CREATION, so Model::find() won't fire it, only when accessing certain row from resultset or when doing Model::findFirst and only on full models.

**Comment by Wirone** [comment]
@Jurigag so basically `afterFetch` is not what I was thinking about.

Maybe issue's title is misleading. What I would like to achieve is core API for automatic data retrieval condition manipulation ;-) Take `SoftDelete` behavior as example, docs states: "Note that you need to specify the deleted condition in your queries to effectively ignore them as deleted records, this behavior doesn't support that." - in my opinion such non-automatic behavior is useless. It should integrate with core API in a way that models using this behavior would be automatically filtered (the best option is to modify query conditions before executing, filtering after fetching is acceptable but less efficient).

Also, core API should allow to disable some behaviors while fetching, so soft-deleted models wouldn't be fetched as default, but could be retrieved when needed (for example admin should see all, even deleted).

Is it possible to do it with current API? I am new to Phalcon and maybe I missed something.

**Comment by Jurigag** [comment]
You can just override find/findFirst method and add there proper condition you want.

**Comment by Wirone** [comment]
But this is not reusable and automatic solution. We've implemented custom `AbstractSoftdeleteableModel` which overrides `find` / `findFirst` but this enforces inheritance instead of composition. It should be possible to achieve such kind of condition manipulation automatically with behaviors.
