### ISSUE TITLE
Phalcon exception handler in Dispatcher not handle PHP Errors

### ISSUE THREAD

**Issue by Kachit** [phalcon/cphalcon#12946]
Phalcon exception handler in Dispatcher not handle PHP Errors based on Throwable

Details

Phalcon version: 3.2.0
PHP Version: 7.0.4
Operating System: Windows 7
Installation type: downloaded DLL
Zephir version (if any): n/a
Server: Apache
Other related info (Database, table schema):

**Comment by stamster** [comment]
Related to #12932
