### ISSUE TITLE
$validation->setFilters("name", "trim") doesn't work

### ISSUE THREAD

**Issue by dellert** [phalcon/cphalcon#12952]
```php
public function validation()
{
    $validator = new  #Validation();
    $validator->setFilters('field', 'trim');

    return $this->validate($validator);
}
```

This code doesn't work on data save. All data for property "field" save with whitespaces. Besides, I tried creating self custom filter, it doesn't work too 

try on versions 3.0.3 and 3.2

#12254

**Comment by Jurigag** [comment]
You already created issue. Why another one?

**Comment by Jurigag** [comment]
Well you need to add any validator i think. Filters works only when getting value which is triggered when validating field.

**Comment by dellert** [comment]
it's not normal behavior. I wanna use filter not using any validator like presenceof or other

**Comment by JABirchall** [comment]
This is not how the validator is intended to be used, if all you want to do is filter the input use [Phalcon/Filter](https://docs.phalconphp.com/en/3.2/filter)

**Comment by dellert** [comment]
thx

**Comment by Jurigag** [comment]
Well `Phalcon/Filter` is more like standalone component. I feel like we should add option to use filters in validation without any validators, but not sure what you think.

**Comment by dellert** [comment]
> I feel like we should add option to use filters in validation without any validators

Yes, it would be cool!
