### ISSUE TITLE
Widgetize pattern to boost performance even much more

### ISSUE THREAD

**Issue by imanghafoori1** [phalcon/cphalcon#12953]
Since falcon is very fast, I think the bottleneck of many falcon web apps lies in heavy DB queries.
So if the framework starts to offer an easy way to cache them the overall resulting app whould be truely fast.

I have created a package called "laravel-widgetize" for laravel apps.

💡 Let me explain the concept:

Imagine we have an online shop.
- We show the top 10 most sale products on the home page.
- We need to perform a haevy sql query to find the top 10 products for each time a user visits homepage.
(~5000 times a day) and then produce a bit of HTML with query result.

🐍 The problem here, is that we do not need real-time calculated results for top-ten products at all.
we can perfectly afford updating that section of the page only once a day, hence executing the SQL query just once a days no matter how many times the home page is visited.

To solve that issue I have written a framework level package for laravel framework which offers an easy way to cache the html and create much faster web application.

It's just a matter of translating my code php to falcon's equivalent.

You can find extensive description about that :
https://github.com/laravel/internals/issues/624
https://github.com/imanghafoori1/laravel-widgetize

**Comment by imanghafoori1** [comment]
It is a __feature request__ and not a bug

**Comment by Jurigag** [comment]
You can already cache parts of views in phalcon volt super easy:

```
{% cache 'some-key' %}
// content from here will be cached
{% endcache %}
```

**Comment by virgofx** [comment]
Caching is already included with Phalcon. The well tested adapters work with various data components including the database, metadata, models, etc.

**Comment by imanghafoori1** [comment]
Anyway this design pattern bring other benefits in term of application structure and etc. You may want to consider. @virgofx
