### ISSUE TITLE
Boolean column type always return true in PHP 7.1 on Windows 7

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/cphalcon#12965]
I update PHP 7.0.14 to 7.1.7 and all column type bit in db and boolean in ORM are always in true
If I turn back to PHP 7.0.14 work great

```mysql
CREATE TABLE `robots` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `isPublic` BIT(1) NOT NULL DEFAULT b'1',
    `year` YEAR NULL DEFAULT NULL,
    ....
```
Adding some data

| id | name | isPublic | year |
| --- | --- | --- | --- |
| 1 | Robocop | 0 | 1987 |
| 2 | R2D2 | 1 | 1977 |

```php
\Phalcon\Mvc\Model::setup([
    'castOnHydrate'      => true,
    'notNullValidations' => false,
]);

Robots::findFirst(1)->isPublic; //true <<< must be false
Robots::findFirst(2)->isPublic; //true
```
### Details

* Phalcon version: 3.2.1
* PHP Version: 7.1.7
* Operating System: Windows 7 x64
* Installation type: Xampp and then download phalcon from github release 
* Zephir version (if any): 0.9.9-868cb1f92b
* Server: Apache 2.4.23
* Other related info (Database, table schema): MariaDb 10.1.25

**Comment by Jurigag** [comment]
What is returned with castOnHydrate => false? Also why you use bit?

**Comment by stamster** [comment]
I work with bits too, but instead doing this:

```php
$query = 'SELECT *, BIN(Active + 0) AS Active FROM Table WHERE Active = ? ORDER BY PrimID DESC';
```

**Comment by emiliodeg** [comment]
@Jurigag when I turn ```castOnHydrate => false``` get a big string integer 
```php
Robots::findFirst(1)->isPublic; //string(19) "7667037173396275200" insteand of false
Robots::findFirst(2)->isPublic; //string(19) "7667037173396275201" insteand of true but ends in 1
```

@stamster in Linux works great, I try in Centos, PHP 7.1.7, MySQL
