### ISSUE TITLE
router and placeholders

### ISSUE THREAD

**Issue by be4i** [phalcon/cphalcon#12964]
When text is set after a placeholder the last character is removed.

```php
$router->add('/test/:int/test', [
    'action'        => 'index',
    'controller'    => 'index',
    'id'            => 1
])
->setName('test');
```

`{{ link_to(['for': 'test', 'id': '123'], 'test') }}`

extected:
`<a href="/test/123/test">test</a>`
actual:
`<a href="/test/123/tes">test</a>`

### Details

* Phalcon version: 3.2.1
* PHP Version: PHP 7.0.20-1~dotdeb+8.2
* Operating System: Debian Jessie
* Installation type: installing via package manager
* Zephir version (if any): 0.9.9-868cb1f92b
* Server: Apache2

**Comment by stamster** [comment]
Define your route as: `$router->add('/test/:int/test/'`
(with a trailing slash)

**Comment by be4i** [comment]
this is expected behavior ?

**Comment by sergeyklay** [comment]
Looks weird for me. I'll try to sort out ASAP.

**Comment by sergeyklay** [comment]
@be4i The `/:int`  placeholder alias for `/([0-9]+)`. Try group `int` as workaround. I'll try to deal with this

**PHP**
```php
$router = new Phalcon\Mvc\Router();

$router->add('/test/(:int)/test', [
    'action'        => 'index',
    'controller'    => 'index',
    'id'            => 1
])
->setName('test');
```

**Volt**
```volt
{{ link_to(['for': 'test', 'id': '123'], 'test') }}
```

**HTML**
```html
<a href="/test/123/test">test</a>
```
-----------
**PHP**
```php
$router = new Phalcon\Mvc\Router();

$router->add('/test/{id:[0-9]+}/test', [
    'action'     => 'index',
    'controller' => 'index',
])
->setName('test');
```

**Volt**
```volt
{{ link_to(['for': 'test', 'id': '123'], 'test') }}
```

**HTML**
```html
<a href="/test/123/test">test</a>
```

-----------
**PHP**
```php
$router = new Phalcon\Mvc\Router();

$router->add('/test/([0-9]+)/test', [
    'action'     => 'index',
    'controller' => 'index',
    'id'         => 1,
])
->setName('test');
```

**Volt**
```volt
{{ link_to(['for': 'test', 'id': '123'], 'test') }}
```

**HTML**
```html
<a href="/test/123/test">test</a>
```

**Comment by be4i** [comment]
okay, thank you
