### ISSUE TITLE
Cache need process synchronisation to avoid slamming

### ISSUE THREAD

**Issue by tztztztz** [phalcon/cphalcon#12968]
Cache slamming is a big issue few know about, making most of the caching systems pretty ineffective, including those in Phalcon.

Creating cache with process synchronisation would rise Phalcon into higher level, well above other frameworks in that regard.

So what's the problem with Phalcon cache system - regardless if it's based on Files, Memcached or anything else?

It's lack of process synchronisation. 

Here is example:

Let's say we have very resource consuming work, that we want to cache. Let's say it involves several DB calls, and overally it takes few seconds to complete, which is very long on busy sytems.

Now, on busy system, where can be few or more requests per sec. demanding such resource, here is what happens when resource is not cached, or expired:

1. First process fails to extract cached resource, so it begins to create it, which will take few seconds and a lot of server power (processor/memory/io)

2. In the meantime, when first process is creating the resource and consuming server resources, other precesses are trying to read cache, fails, and doing the same work what process nr 1 is doing.

3. Performance downspike happens, everything is slowed down, and it continues to the moment when last of the processes will put the resource in the cache.

This is called cache slamming and it's wrong! 

There should be only one process creating the resource while other should wait and sleep until process nr 1 will finish and put resource in cache, after that rest of the waiting processes should be woken up and extract resource from cache.

Te best solution I've found is to use the sync library and reader/writer class - as it's very reliable and works the same under Windows and Linux:

http://php.net/manual/en/class.syncreaderwriter.php

but it requires different approach to creating the resource, NOT like this:

if (!resurce in cache) {
	1. create resource
 	2. put in cache
}

It must be done like this:

1. object with interface to create resource ( let's say method: createResourceForCache )

2. object is passed to cache manager, cache manager is doing synchronisation, and finally returns the resource created by object passed to the manager

Something like this:

$cachedResourceCreator = new \MyClassImplementingInterfaceForCreatingResource();

$manager = new \CacheManager( $cacheMethod, $expireTimeInSeconds );

$resourceWeWant = $manager->getCachedResource($cachedResourceCreator);

Where $cacheMethod can be filesystem, memcached, and so on...

Cache slamming is big issue on busy systems when there is a lot of caching, and it's worth to do it better in the next big version of Phalcon (4?)

**Comment by virgofx** [comment]
Well written and describes the issue thoroughly. There's always a fine line from where the framework ends and what can be implemented in user-land. I'm not sure if this belongs in Phalcon's default adapters but like you said adding another layer that doesn't impact existing usage via some sort of CacheSynchronizationManager API where original adapters can be used independently (thus, no issues with those who don't want to incur the overhead of synchronization) may be the optimal approach. 

Will definitely need to investigate the approaches for syncing overhead though. Curious as to the penalty for this.

**Comment by tztztztz** [comment]
I hopei will find time, to finish my project for universal "no slamming cache" for PHP, which will be based on synchronisation solutions im already using - just gathered toghether into one universal package. 

I will create repository/project in GitHub, and it could be starting poing to further discussion and implementation. ETA 14-21 days.

**Comment by Jurigag** [comment]
Agree it's a problem, we should solve it in next phalcon version.

**Comment by tztztztz** [comment]
Im also thinking about multiple options for creating the resource:
* the most "elegant" with interface for creating resource (downside: more code, complications with passing parameters)
* using callbacks
* using recursion in method which creating the resource (i actually prefer and use that way, I will give code example it the project, to better explain that concept)

**Comment by stamster** [comment]
When I read about this, I immediately think of dead locks. 
The thing is - very nice idea, and it should get attention to details as much as possible.

**Comment by tztztztz** [comment]
If we're talking about deadlocks, the synchornisation solution im proposing (SYNC library), forbids nested locks, that is: if you try to aquire another lock within process the previous lock will be released.

It will preventing deadlocks.

BUT

Im thinkig about synchro interface, where advanced user will have opportunity to change default lock mechanism (SYNC library) to different one enabling nested locks.

Anyway i think the default synchro mechanism should be one without possibility of nested locks / deadlocks, because IMO it's too advanced and confusing topic for most of the users.

**Comment by tztztztz** [comment]
Actually, during working on it, i've discovered that SyncReaderWriter class is allowing nested write locks, and thus providing possibility of deadlocks. 

I will protect it from happening by monitoring if any lock has been acquired using global static variable, but it will not prevent deadlocks by making locks out of the Cache Class...

The other thing that somewhat protects from deadlocks, is a lock timeout. It will be set to for example 30 sec by default, and will be configurable at cache construction stage.

**Comment by tztztztz** [comment]
Hello, 

I've created repository called: php-no-slam-cache (https://github.com/tztztztz/php-no-slam-cache), where first, tested version of the caching system resides. 

It comes with testing script intended to be run in command line windows concurrently.

In the next days I will add some detailed documentation and some examples to it, and then we can talk about porting this mechanism into Phalcon.

Despite deadlock danger, it can be pretty safely used for some internal Phalcon caching like model definitions or annotations, it can take some time, and synchronisation would help here. 

Besides that, sycnhronisation could be disabled by default.

Whole system uses callbacks for creating resources, and it's generally simple. 

One thing that I may change in next days is the transformation process of resource FROM <-> TO currently it's pretty safe but conservative: serialisation and then encoding by base64 for safe storage of special characters/binary data.

**Comment by stamster** [comment]
pity this was closed?

**Comment by tztztztz** [comment]
Well when I find some time (hopefully in the next 30 days), I will make bridge between my cache system with synchro (https://github.com/tztztztz/php-no-slam-cache) and Phalcon, for easy replacement of Phalcon native caching system. If anyone is interested please follow my repository.

**Comment by tztztztz** [comment]
Well, sorry guys, but I just realised that's quite impossible to implement php-no-slam-cache cache system into Phalcon.

Here's why.

Typical / Phalcon cache system:

1. First call to Phalcon Cache System: checking if item exists in the Cache. If exist -> fetch it, end of strony
2. If it not exist, create resource and put it into Cache (second call to Phalcon  Cache System) -> which may lead to cache slamming/stampede, slowing down the system or even freeze

php-no-slam-cache:

1. You define recipe for creating resource in form of callback

2. Calling cache method (files, memcached, etc.) providing key and recipe -> First and only call to php-no-slam-cache System.

Caching method / manager will execute callback only if item does not exist in the cache, synchronising whole thing, preventing cache slamming/stampede from happening and protecting Your System.

Sadly, it can't be done with Phalcon Cache interfaces, as they are constructed to fit the traditional, double cache system call way, which is not very efficient in case of heavy load. 

You can still use php-no-slam-cache in Phalcon for critical parts, but You can't register it as Cache Provider that will for example automaticly intercept Queries of ORM and cache it in the background.

Anyway I will still develop that library as it is very usefull at least for me.
