### ISSUE TITLE
Bug with getRelated with columns provided when they are initialised in relation params

### ISSUE THREAD

**Issue by broneq** [phalcon/cphalcon#12972]
### Expected and Actual Behavior

Actualy when I have defined some relation like:

```php
$this->belongsTo(
            'robots_id',
            'Store\Toys\Robots',
            'id',
            [
                'alias' => 'Robots',
                'params' => [
                    'columns' => 'id,name'
                ]
            ]
        );
```
And ask for 
```php
$model->getRobots() 
```
in result I have two columns id and name, and its expected result.

But if i as for:
```php
$model->getRobots(['columns'=>'id,price,name'])
```
in result I have again two columns without price.

I think that is a bug in https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/manager.zep#L1307

```php
let builder = this->createBuilder(this->_mergeFindParameters(extraParameters, parameters));
```
we are overwriting relation parameters on provided parameters...
It's suprising that in https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/manager.zep#L1364 it''s reverse logic.

### Details

* Phalcon version: 3.1.2
* PHP Version: 7.1.4
* Operating System: Ubuntu 14.04.1 LTS
* Installation type:  installing via package manager
* Server: Nginx
* Other related info (Database, table schema): PostgreSQL 9.5.5
--
Przemek

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
