### ISSUE TITLE
Phalcon\Http\Response\Cookies->send() cause "The argument is not initialized or iterable"

### ISSUE THREAD

**Issue by Zaporozhec7** [phalcon/cphalcon#12978]
I try use `Phalcon\Http\Response\Cookies`, separate from `Phalcon\Http\Response`. In my app "Cookies" object can contain cookie, or not. And i do not have way to check, is there exists at least one cookie in it, or not, before try to send it, because class do not provide method for this.
So if there are was not added at least one cookie, on calling `send()` method appear exception **"The argument is not initialized or iterable"**. 
I think that because `_cookies` variable in class defined without value and stay `null` if there are no cookie set (if i understand Zephir right). And we try to iterate through it in `send() `  method when `_cookies` is `null`

There are few ways to fix that:

1. Make `protected _cookies = [];` instead `protected _cookies;`
2. Check is `_cookies` not empty/iterable before try iterate through it
3. Provide for `Phalcon\Http\Response\Cookies` class method that allow to check, is there are added cookie (something about `isEmpty()`)

> **Expected behavior**

When there are no cookie set, do nothing

> **How to reproduce**

```php
(new Phalcon\Http\Response\Cookies())->send();
```
### Details

* Phalcon version: 3.1.2
* PHP Version: 7.1.4

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
