### ISSUE TITLE
Fatal error: Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default

### ISSUE THREAD

**Issue by yanancom** [phalcon/cphalcon#12979]
Fatal error: Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default

my environment:
windows7 + xampp-win32-7.1.7-0-VC14-installer.exe + phalcon_x86_vc14_php7.1.0_3.2.1

my codes:

	try {
		$di = new Phalcon\DI\FactoryDefault();
		
		$loader = new Loader();
		include BASE_PATH . "/app/config/services.php";
		$config = $di->getConfig();
		
		$loader->register();
		
		$application = new Application($di);
		$controler = $application->handle();
		echo $controler->getContent();
	} catch (Exception $e) {
	..
	}

error info:
```
Fatal error: Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default in C:\xampp\htdocs\brh\public\index.php:18 
Stack trace: 
#0 [internal function]: Phalcon\Di->__construct() 
#1 C:\xampp\htdocs\brh\public\index.php(18): Phalcon\Di\FactoryDefault->__construct() 
#2 {main} 

Next Error: Access to undeclared static property: Phalcon\Di::$_default in C:\xampp\htdocs\brh\public\index.php:18 
Stack trace: #0 [internal function]: Phalcon\Di->__construct() 
#1 C:\xampp\htdocs\brh\public\index.php(18): Phalcon\Di\FactoryDefault->__construct() 
#2 {main} thrown in C:\xampp\htdocs\brh\public\index.php on line 18
```
there are no errors on normal operation,the error occurs when I request twice continuely in javascript:

	var $content = $('<div></div>');
	$content.load(url1, params1, function (response, status, xhr) { //error will not occur on this request
		$content.load(url2, params2);  //error will occur on this request everytime.
	});
	
I also found that when my computer disk is busy, the error ofen occur.

**Comment by yanancom** [comment]
no solution? really?

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/12056
