### ISSUE TITLE
Session adapter interface is outdated

### ISSUE THREAD

**Issue by janisbizkovskis** [phalcon/cphalcon#12981]
So, long story short:

This - https://github.com/phalcon/cphalcon/blob/master/phalcon/session/adapter/redis.zep#L135 is not complying with session adapter interface - https://github.com/phalcon/cphalcon/blob/master/phalcon/session/adapterinterface.zep#L77

As well, session handler `destroy` method accepts `$session_id` as parameter: http://php.net/manual/en/class.sessionhandler.php

Would be cool to have a fix for this, so adapter interfaces are complying with PHP SessionHandler class.

**Comment by sergeyklay** [comment]
Is there any issue with building/compilation? This is how PHP (ZendEngine) works inside - does not check method declaration :) Anyway you're right it is a minor bug.

Refs: https://github.com/phalcon/cphalcon/issues/12833

**Comment by janisbizkovskis** [comment]
@sergeyklay nope, there are no issues regarding this with building/compilation. Basically I was writing an adapter for RedisCluster and noticed this minor bug under interface, so I posted here. Was a bit ugly implementation due to param...

Hopefully I'll have enough free time to port it to Zephir, so it could be integrated in 4.0. :)
