### ISSUE TITLE
Bug with view

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#12983]
I have a code that allows you to restrict users access to certain parts of the website: https://pastebin.com/HPN2gsyW

I have a AclResource service: https://pastebin.com/VJHjghTY
I have a IndexController: https://pastebin.com/bRSWgEV0

const User::ROLE_USER = 'Users';
const User::ROLE_ADMINISTRATORS = 'Administrators';

For example establish for registration of a private access only for the user group.
Next, it calls the beforeDispatch event which doesn't pass us next, and then the usual Forward IndexСontroller in action notAllowedAction.
Next, I want to make the output template echo $this->view->render(...), but it doesn't work (the template is not empty). This is a bug?

* Phalcon version: 3.2.1
* PHP Version: 7.1.7
* Operating System: Ubuntu 16.04 LTS Xenial
* Installation type: installing via package manager
* Zephir version (if any): Version 0.9.9-868cb1f92b
* Server: Apache

**Comment by Jurigag** [comment]
You don't have to add `$this->view->render`, it will be done automatically if you have implictView enabled. Also use getRender method if you want to actually get output as a string.

**Comment by TimurFlush** [comment]
ImplicitView already off. The problem most likely lies in the forward, because after that $view->render does not want to work.
