### ISSUE TITLE
[NFR] Multiple memcached server support for memcache clusters

### ISSUE THREAD

**Issue by tsnyder91** [phalcon/cphalcon#1299]
I'm building out a distributed memcache system over 3 servers in the near future and would like to support for a distributed memcached system in the memcache cache code natively.  Currently it only supports one host.  

http://www.php.net/manual/en/memcached.addservers.php 
http://www.php.net/manual/en/memcached.addserver.php

Since the constuct is already created with requiring server info, I was thinking of supporting both string and array for host. Similarly for the port, if only one port is given then use that port for all hosts. If it's an array then map the ports to the hosts (it would need to match the count of the number of hosts or throw an exception). 
There should be new support for the weight param found in the docs above as I may one to not do an even distribution among the cluster.
Something like the following.
$cache = new Phalcon\Cache\Backend\Memcache($frontCache, array(
    'host' => array('localhost','localhost2','localhost3')
    'port' => array(11211,11212,11211),
    'weight' => array(40,50,10),
    'persistent' => false
 ));
##

**Comment by jaskaransingh156** [comment]
I fixed this issue by adding a function "addServers" to the Phalcon\Cache\Backend\Memcache class. Code is available here:

https://github.com/jaskaransingh156/cphalcon

Example of using addServers method is following:

$frontCache = new \Phalcon\Cache\Frontend\Data( array ( "lifetime" => 172800 ));
$memcache = new \Phalcon\Cache\Backend\Memcache($frontCache, array ( 'host' => 'memcache_host1', 'port' => 11211,
)); 
$memcache->addServers('memcache_host2', 11211);

**Comment by Jurigag** [comment]
There is `addServers` method in memcache backend, not sure though how it's working exactly.
