### ISSUE TITLE
Break API: Only allow class strings or closures in simple and normal view registerEngines

### ISSUE THREAD

**Issue by stefanchiriac** [phalcon/cphalcon#12996]
### Expected and Actual Behavior
If I create a simple view and I register the engines classes as objects, doesn't seems to render the view. It works only when I set the engine classes as strings.

The expected behavior should be to render the view either the engine is registered as an object or as a string

```php
       // Bootstrap
        $view = new \Phalcon\Mvc\View();
        $view->setLayoutsDir('path/to/layouts/');
        $view->setPartialsDir('path/to/partials/');
        $view->setMainView('path/to/mainView');
        $view->setLayout('default');

        // Simple render file
        $viewApp = $this->getDI()->get('view');
        $view = $this->getDI()->get('\Phalcon\Mvc\View\Simple');
        $view->setViewsDir("path/to/views');
        $view->registerEngines([
            ".phtml" => new \Phalcon\Mvc\View\Engine\Php($viewApp, $this->getDI()),
            ".volt" => new \Phalcon\Mvc\View\Engine\Volt($viewApp, $this->getDI())
        ]);

//    Works only if is set like this
//        $view->registerEngines([
//            ".phtml" => "Phalcon\\Mvc\\View\\Engine\\Php",
//            ".volt" => "Phalcon\\Mvc\\View\\Engine\\Volt",
//        ]);

        echo $view->render('view-to-be-rendered', null); // returns null if engines are registered as objects
```
### Details

* Phalcon version: 3.1.1+ (possible on lower too)
* PHP Version: 7.0
* Operating System: Ubuntu 14.04
* Installation type: Compiling from source
* Server: Apache

**Comment by stamster** [comment]
Where did you get info that one could instantiate objects and pass them to Volt configuration like that?

This works since early versions of Phalcon/Volt, I think it's covered by documentation as well:

```php
'.phtml' => 'Phalcon\Mvc\View\Engine\Php'

// or with a closure, where you instantiate object inside the anonymous function itself

'.volt' => function ($view, $di) use ($config) {
            // Note: this is Phalcon\Mvc\View\Engine constructor inherited by Volt engine
            $volt = new VoltEngine($view, $di);
...
}
```

The thing is - Volt component is lower level extension - pure C. So it's gotta be different a bit.

**Comment by dschissler** [comment]
@stefanchiriac Do something like this:

```php
    use Phalcon\Mvc\View\Engine\Php as PhpEngine;

    '.phtml' => PhpEngine::class,
```

@sergeyklay This seems like a close.

**Comment by stefanchiriac** [comment]
The way I see it, if Phalcon\Mvc\View accepts objects, you either make all views classes to accept the same definition or remove what should not be allowed. All views should work in the same ways and be standardized. If you don't consider this is a bug for Phalcon\Mvc\View\Simple then is one for Phalcon\Mvc\View.

**Comment by dschissler** [comment]
@stefanchiriac Are you recommending that we make the `registerEngines` method only be able to accept strings of class names?  I suppose that we could check this to prevent confusion.

**Comment by stefanchiriac** [comment]
@dschissler  that's exactly what I'm saying, to make `registerEngines` method accept only strings and closures. This will standardize views classes and prevent confusion. Thanks

**Comment by dschissler** [comment]
but is there any inconsistency there?  You wrote that in one case an object can be used but not in the other.  Can you give a specific and small code example of the use case where it works and when it doesn't.  If its something that is inconsistent then we could relabel the issue and add it to the Phalcon 4 milestone as inconsistent behavior to fix.

**Comment by stefanchiriac** [comment]
Like I said in my first post, phalcon is more freely in the way how you can register the engines for Phalcon\Mvc\View but more restrictive for Phalcon\Mvc\View\Simple.

For example if you define Phalcon\Mvc\View like following in Bootstrap, it will render views without problems :
```php
$view = new \Phalcon\Mvc\View();
$view->setLayoutsDir('path/to/layouts/');
$view->setPartialsDir('path/to/partials/');
$view->setMainView('path/to/mainView');
$view->setLayout('default');
$view->registerEngines([
            ".phtml" => new \Phalcon\Mvc\View\Engine\Php($view, $this->getDI()),
            ".volt" => new \Phalcon\Mvc\View\Engine\Volt($view, $this->getDI())
        ]);
```

Next if you want to reuse the registered engines from  Phalcon\Mvc\View on Phalcon\Mvc\View\Simple or define the engines in the same way, when you try to render a view it will always return null and no errors.

Not working example 1
```php
 $viewApp = $this->getDI()->get('view');
 $view = $this->getDI()->get('\Phalcon\Mvc\View\Simple');
 $view->setViewsDir("path/to/views');
 $view->registerEngines($viewApp.getRegisteredEngines());
```

Not working example 2
```php
$view = new \Phalcon\Mvc\View\Simple();
$view->setViewsDir("path/to/views');
$view->registerEngines([
            ".phtml" => new \Phalcon\Mvc\View\Engine\Php($view, $this->getDI()),
            ".volt" => new \Phalcon\Mvc\View\Engine\Volt($view, $this->getDI())
        ]);
```
In all cases works fine if registered engines are strings or closures.

If registering an engine as an object is the wrong way or not allowed, Phalcon should not let me do it in the first place and throw an error.

**Comment by dschissler** [comment]
Can you re-title this issue to something like `Break API: Only allow class strings in registerEngines`?  It doesn't need to be exactly that and probably you can come up with something better.  So suggest a course of action in the title.  Then I'll propose that this be added to the 4.0 milestone.

**Comment by dschissler** [comment]
Also I think that it is bad style to be able to put in strings and then having Phalcon figure out if it is a name of a service or a namespace.  I think that it should be limited to ONLY a closure or a fully qualified namespace.

So only:

```php
use Phalcon\Mvc\View\Engine\Volt as VoltEngine;

$view->registerEngines([
            ".volt" => VoltEngine::class,
        ]);
```

or 

```php
$view->registerEngines([
            ".volt" => $this->getVolt(),
        ]);
```

This stuff was designed to work back with PHP 5.3 and it hasn't been broken since.  We can do things better now.

**Comment by stefanchiriac** [comment]
changed as requested
@sergeyklay can you reopen this issue? Thanks
