### ISSUE TITLE
Missing translation in NativeArray should (optionaly) raise a warning

### ISSUE THREAD

**Issue by dugwood** [phalcon/cphalcon#13007]
### Expected and Actual Behavior

When using NativeArray (https://github.com/phalcon/cphalcon/blob/master/phalcon/translate/adapter/nativearray.zep) on a missing key, the key itself is returned if there's no translation for this key.

A warning should be raised to deal with such a situation, avoiding displaying keys on the production website. It's not a security issue, but that should help displaying what's intended.

### Details

* Phalcon version: since 2.x
* PHP Version: not relevant
* Operating System: not relevant
* Installation type: compilation (Linux)
* Zephir version (if any): not relevant
* Server: not relevant

I can create a pull request for this, just tell me if you have a specific implementation to follow: throw an exception (I see that you have `Phalcon\Translate\Exception`), passing a function...
And option would be `exceptionOnMissingKey` or anything you'd prefer, defaulting to false of course.

**Comment by dugwood** [comment]
An exception may be too difficult to deal with, it should be a function:
`new NativeArray(['content' => [], 'onMissingKey' => $myfunction]`

The function may return the key, overriding the code:
https://github.com/phalcon/cphalcon/blob/master/phalcon/translate/adapter/nativearray.zep#L63

Example of function to pass:
```php
function missingKey($key) {
    trigger_error('Can\'t find translation key: '.$key);
    return $key; // or better, return nothing with «return '';»
}
```

**Comment by niden** [comment]
This has been addressed
