### ISSUE TITLE
E_WARNING: finfo_file(/tmp/phpEDf24x): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by PatchRanger** [phalcon/cphalcon#13003]
I see lots of similar warnings in my logs:

> E_WARNING: finfo_file(/tmp/phpEDf24x): failed to open stream: No such file or directory: finfo_file(/tmp/phpEDf24x): failed to open stream: No such file or directory
> File "<internal>" line (unknown) in \<main\>
> File "<internal>" line (unknown) in errorHandler
> File "/var/www/html/api/v1/Controllers/AllController.php" line 317 in finfo_file
> File "/var/www/html/api/v1/Controllers/AllController.php" line 97 in getRealType
> File "<internal>" line (unknown) in uploadDocument
> File "<internal>" line (unknown) in profileAction
> File "<internal>" line (unknown) in callActionMethod
> File "<internal>" line (unknown) in _dispatch
> File "/var/www/html/site/index.php" line 90 in dispatch

AllController, line 97:
```php
$this->uploadDocument($file, $opportunity, $client);
```
AllController, line 317:
```php
$file->getRealType()
```
\- and it (judging by the backtrace above) calls `finfo_file`, which finally fails.

Here is the corresponding piece of code, which calls `getRealType` at line 317:
```php
    private function uploadDocument($file, $opportunity, $client) {
        $newTempName = tempnam(sys_get_temp_dir(), 'doc-upload');
        if ($file->moveTo($newTempName)) {
            $this->attachFile(
                    $client,
                    self::OPPORTUNITY_ENTITY,
                    $opportunity['id'],
                    basename($file->getName()),
                    base64_encode(file_get_contents($newTempName)),
                    $file->getRealType()
                );

            @unlink($newTempName);
        }
    }
```

Could you please tell me how to fix this issue? It looks like a bug - is it really?

### Details

* Phalcon version: 3.1.0
* PHP Version: 5.5.9-1ubuntu4.20
* Operating System: Ubuntu
* Installation type: installing via package manager
* Zephir version (if any): 0.9.4a-dev-7e304ba18c
* Server: Apache
* Other related info (Database, table schema): Fileinfo module version: 1.0.5-dev

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

**Comment by PatchRanger** [comment]
@sergeyklay I've posted an issue here to let you know that in my case `getRealType` following the `moveTo` call fails - it is bug, isn't it? Could you please investigate the source code of `getRealType` in order to make sure it doesn't contain obvious bug, that could be the reason of aforementioned behavior?

**Comment by sergeyklay** [comment]
I'll take a look a bit later.

**Comment by PatchRanger** [comment]
@sergeyklay We're going to upgrade to the latest Phalcon release soon - I'll notify you if this issue persists. Is there any additional data we could provide for better debugging?

**Comment by sergeyklay** [comment]
@PatchRanger Unfortunately I can't reproduce this issue. Is there any ability to provide complete and minimal steps to reproduce?

**Comment by PatchRanger** [comment]
@sergeyklay I guess, minimal steps set is as follows (not tested, sorry):

```php
$file = new \Phalcon\Http\Request\File([
    'name'        => 'test',
    'type'        => 'text/plain',
    'tmp_name'    => PATH_DATA . '/assets/phalconphp.jpg',
    'size'        => 1,
    'error'       => 0,
]);
$newTempName = tempnam(sys_get_temp_dir(), 'doc-upload');
if ($file->moveTo($newTempName)) {
    $file->getRealType();
    @unlink($newTempName);
}
```

The key point (in my view) - is a call to `getRealType` immediately after `moveTo` on temp file.

**Comment by sergeyklay** [comment]
I still can't reproduce. Works fine for me without any notice/warning. Could you please provide output of:

```
php --ri fileinfo
```

**Comment by PatchRanger** [comment]
@sergeyklay 

```
root@mailer:~# php --ri fileinfo

fileinfo

fileinfo support => enabled
version => 1.0.5-dev
```

**Comment by sergeyklay** [comment]
Is there any ability to use latest stable PHP 5.5.38 (Released: 21 Jul 2016) ?
