### ISSUE TITLE
Json serialization for JSON column types

### ISSUE THREAD

**Issue by ChangePlaces** [phalcon/cphalcon#13009]
### Expected and Actual Behavior

I have a column in a table that is of type JSON in mysql. I have set the column type to 'json' in the model annotation for the property and I am using the annotation strategy.

I intend to use this json array to store an array of data, so I set a default value of `[]` in the `onConstruct` but when I save it, I get the PDO error `number of bound variables does not match number of tokens` from `Db\Adapter`. I'm not sure why - the value should be `json_encode`'d on save/create/update and then `json_decode`d on fetch?

### Details

* Phalcon version: (`php --ri phalcon`)  3.2.1
* PHP Version: (`php -v`) 7.0
* Operating System: ubuntu
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx 
* Other related info (Database, table schema): mysql

**Comment by JABirchall** [comment]
Heres is the docs for mysql json objects https://dev.mysql.com/doc/refman/5.7/en/json.html
