### ISSUE TITLE
The integer id field is being populated as a string after save

### ISSUE THREAD

**Issue by ChangePlaces** [phalcon/cphalcon#13002]
### Expected and Actual Behavior

When I save a model, the id field is automatically populated with the id value, however, instead of it being an integer value, it's populated as a string value. When outputting json this is an issue. In the database, the id field is an `integer auto_increment primary key`, and in the annotations, the `@Column' type is an integer. (I'm using the annotation strategy)

e.g. instead of seeing: `"id":5,` I get `"id":"5"`

### Details

* Phalcon version: (`php --ri phalcon`) 3.2.1
* PHP Version: (`php -v`) 7
* Operating System: 
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema):

**Comment by virgofx** [comment]
Yes, good catch. We need to respect column map types and cast appropriately right here as MySQL lastInsertId() always returns string

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L2432-L2434

Always returns string
http://php.net/manual/en/pdo.lastinsertid.php

**Comment by ChangePlaces** [comment]
Ahh I thought lastinsertid may have been the root cause but never had time to check! I'm still new to Phalcon so wouldn't know how to check the mapped type! Thanks for the work on narrowing it down.

**Comment by magroski** [comment]
Any updates on this?

**Comment by zeecher** [comment]
Anything on this ?

**Comment by niden** [comment]
@zeecher I will check on this this coming week after I attend some other pressing matters.

Thank you for reporting this

**Comment by Jeckerson** [comment]
What is complete version of MySQL? And show output of `SHOW VARIABLES LIKE 'sql_mode';`

**Comment by zeecher** [comment]
for now solved it by overriding model's toArray

 ```
public function toArray($columns = null): array
    {
        $array = parent::toArray($columns);

        $metadata = $this->getDI()->get('modelsMetadata');

        $types = $metadata->getDataTypes($this);

        if((isset($types['id']) && isset($array['id'])) && $types['id'] === Column::TYPE_INTEGER) {

            $array['id'] = (int)$array['id'];
        }

        return $array;
    }
```

**Comment by virgofx** [comment]
The proper solution is to just cast to (int) here:

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L2486-L2489

PHP returns string from MySQL's internal call which returns bigint. There's no reason why we shouldn't just cast to int in the code ...

**Comment by magroski** [comment]
This gets really annoying when using `castOnHydrate`, because it will cast when you do a `find`, but won't when saving.

**Comment by virgofx** [comment]
I've been talking about this with the core team. 

The issues at play are:
    * MySQL PDO options -- Are we emulating prepares? If so, (default) , everything is string. If false , PDO returns native PHP types. This is similar to phalcon's:
   * CastOnHydate is specified which forces SELECTs to cast appropriately via cloneResultMap ... 

If either if the above are true. I believe ... that we should properly handle for the following PDO extensions:
   * MySQL + MariaDB

```
MySQL:
"With no argument, LAST_INSERT_ID() returns a BIGINT UNSIGNED (64-bit) value representing the first automatically generated value successfully inserted for an AUTO_INCREMENT column as a result of the most recently executed INSERT statement."

MariaDB:
"LAST_INSERT_ID() (no arguments) returns the first automatically generated value successfully inserted for an AUTO_INCREMENT column as a result of the most recently executed INSERT statement."
```

Thus, with respect to MySQL/MariaDB ... lastInsertId() should always be sufficient to fit inside a PHP 64bit integer.  However, we can't do this for 100% of the cases (e.g. users that use default PDO with emulate prepares) and cast_on_hydrate is for SELECTs for the most part.

So we could introduce a new global value `orm.cast_last_insert_id_to_int` that would solve it for all the unique cases. Otherwise, Phalcon would have to do much work to determine the type of PDO connection as other PDOs could have different sequence values.

Thoughts?

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14068
