### ISSUE TITLE
[Bug] \Phalcon\Mvc\Model\Query->addFrom() disregarding "with" argument

### ISSUE THREAD

**Issue by kornerita** [phalcon/cphalcon#13023]
Hi,

We can see in `\Phalcon\Mvc\Model\Query` [here](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L415), that the `with` parameter is disregarded in the `addFrom` method, I believe than [this](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L206) line of code is missing (taken from the constructor where is not disregarded).

Regards,
Federico.

**Comment by sergeyklay** [comment]
@kornerita Good catch! Thank you

**Comment by kornerita** [comment]
No problem, I found it just browsing code hehe.

**Comment by sergeyklay** [comment]
Long story short. This feature was introduced at Jun 1, 2015 (https://github.com/phalcon/cphalcon/commit/3e43192750367ae0343fbe42c65a97fd04b3444b) was removed at Aug 6, 2015 (https://github.com/phalcon/cphalcon/commit/3ca25046ff484aedb7c38ac5aa994f183cba2415).  Actually this feature was never used in stable releases. 

We will not add this feature into 3.x branch and most likely will refactor QueryBuilder in 4.x branch.  Thus I just mark (#13109) this feature as deprecated to avoid misunderstandings for future developers.

To see team's opinion about Eager Loading refer to: https://github.com/phalcon/cphalcon/issues/1117 .

Thank you for the report, and for helping us make Phalcon better.
