### ISSUE TITLE
[Enhancement] Phalcon\Mvc\Model\Query\BuilderInterface Definition

### ISSUE THREAD

**Issue by kornerita** [phalcon/cphalcon#13021]
Hi,

It would be nice to complete the [BuilderInterface](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builderinterface.zep) definition to match the intended method from [Builder](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep) 

The missing methods are:

[distinct](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L304)
[getDistinct](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L313)
[andHaving](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L833) since v3.2.0
[orHaving](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L868) since v3.2.0
[betweenHaving](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L891) since v3.2.0
[notBetweenHaving](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L903) since v3.2.0
[inHaving](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L915) since v3.2.0
[notInHaving](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L927) since v3.2.0
[forUpdate](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L949)
[offset](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L998)
[getOffset](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L1009)

If someone is implementing BuilderInterface, this would break their compatibility; this would be for an incompatible version change.

This affects Phalcon v3.2.2 and before.

Regards,
Federico.

**Comment by kornerita** [comment]
Hi,

I would like to add a question about this:

In [\Phalcon\Mvc\Model\Query\Builder->inWhere](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep#L708l) the method signature is:
```
public function inWhere(string! expr, array! values, string! operator = BuilderInterface::OPERATOR_AND) -> <Builder>
```
while in [\Phalcon\Mvc\Model\Query\BuilderInteface->inWhere](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builderinterface.zep#L173) is:
```
public function inWhere(string! expr, array! values, string! operator = BuilderInterface::OPERATOR_AND) -> <BuilderInterface>;
```
The difference is the return type.

Which one is correct?
- The first
- The second (my choice)
- Both.

I believe that an class implementing an interface should preserve signature exactly like it's presented on the interface, regardless than in this case `Builder` is implementing `BuilderInterface`.

There is also the case where `BuilderInterface->betweenWhere()` differs from `Builder->betweenWhere() -> <Builder>` but specifying which type of object it returns.

Is there a default criteria for this or it's just decided by convenience case by case?

Regards,
Federico.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
This has been addressed in v4
