### ISSUE TITLE
[NFR] Exception Error Page Handling

### ISSUE THREAD

**Issue by JABirchall** [phalcon/cphalcon#13038]
### Expected and Actual Behavior
Recently I wanted to throw errors based on database output for instance if a user tries to view an ID of object that's not in the database I want to throw a 404. I find my self-having to manually dispatch the error controller to do this.

Exepected behavour:
```php
$player = Players::findFirstByPid($id);
    if(!$player) {
        return throw new HttpNotFoundException('message');
    }
// continue execution
````
should then be caught and invoke the defined not found controller::method

Actual behavour:
```php
$player = Players::findFirstByPid($id);
if(!$player) {
    return $this->dispatcher->forward([
        'controller' => 'Index',
        'action' => 'httpError',
        'params' => ["No player found for ID: {$id}"]
    ]);
}
```
This then also re-execution the ControllerBase::initialize() method, wich adds extra unwanted load

**Comment by virgofx** [comment]
Just wrap your own exception that dispatches just as you've specified. Create your own HttpExceptions to dispatch what you want. The framework provides the tools required for you to build/extend your application.

**Comment by JABirchall** [comment]
>Just wrap your own exception that dispatches just as you've specified. Create your own HttpExceptions to dispatch what you want. The framework provides the tools required for you to build/extend your application.

While entirely possible. Having something readily available for such a common problem would be a better solution then telling everyone just make your own wrapper.

I worked and currently still work with symphony and using their HttpExeceptions is so easy to quickly and easily throw a 404, 403 or any status code you need to use to display to the user.

http://api.symfony.com/3.2/Symfony/Component/HttpKernel/Exception.html

**Comment by virgofx** [comment]
The framework shouldn't couple application specific actions and controllers to an exception. So no, the framework shouldn't implement this.

**Comment by Jurigag** [comment]
Well i totally agree. This is useless, what you would expect phalcon should do with this throwed exception? You would need to configure it somehow or create some handler so create some class and method anyway. Much faster and easier is just to write your own code in php.
