### ISSUE TITLE
[NFR] Add openssl options to \Phalcon\Crypt 

### ISSUE THREAD

**Issue by kornerita** [phalcon/cphalcon#13035]
Hi,

I need to switch using `mcrypt` in favor of `openssl` since `mcrpyt` is deprecated since [php 7.1 ](http://php.net/ChangeLog-7.php#7.1.8)

So, why not use `\Phalcon\Crypt`?

`openssl`  uses PKCS#7 Padding [see here](https://crypto.stackexchange.com/questions/12621/why-does-openssl-append-extra-bytes-when-encrypting-with-aes-128-ecb) and `mcrypt` does not so, there is a -nopad option in `openssl` cli command (and then you can pad as you wish or as mcrypt does) and an `OPENSSL_NO_PADDING` option for php's `openssl` function.

**Migrating from mcrypt to openssl**

mcrypt:
```php
$value = mcrypt_decrypt(MCRYPT_3DES, $key, $data, MCRYPT_MODE_ECB);
```
openssl:
```php
$value = openssl_decrypt($data, "des-ede3", $key, OPENSSL_RAW_DATA | OPENSSL_NO_PADDING);
```

The issue is that `\Phalcon\Crypt` has coded [here](https://github.com/phalcon/cphalcon/blob/master/phalcon/crypt.zep#L358) only `OPENSSL_RAW_DATA` option and does not provide a way to add extra `openssl` options.

So I would like to ask for a way to add those options like i.e.:

```php
$cr = new \Phalcon\Crypt();
$cr->setOpensslOptions(OPENSSL_NO_PADDING | OPENSSL_... );
```

Thanks,
Federico.

**Comment by virgofx** [comment]
The Crypt class has used OpenSSL for quite a while. No changes need to be done on your part. The Crypt class doesn't have a few odd pall padding options as you probably shouldn't be using no_padding as you need to provide data in exact length for encrypt/decrypt. 

Ideally, the crypt classes can be specific to implementation. So inline with the rest of Phalcon, there should just be a crypt interface with a default \Crypt\Adapter\OpenSSL adapter that implements it (pretty much a straight 1-1 copy).

Then a second sodium can be added as well. There is no mcrypt support in Phalcon now.

**Comment by michanismus** [comment]
Hmm, I thought Crypt class already uses OpenSSL!?
Or did I miss something? :)
https://github.com/phalcon/cphalcon/blob/master/phalcon/crypt.zep#L358

**Comment by kornerita** [comment]
Hi,

The `\Phalcon\Crypt` class use the OpenSSL and that is **just fine**, no complains there.

The problem comes when you try to decrypt i.e. third party encrypted data with openssl and it does not has PKCS#7 Padding.

For instance this code show the difference with encrypted result:

```php
<?php

$data = '12345678'; // one 8 bytes block
$key = "THIS_IS_A_LONG_KEY_12345"; // 24 bytes key for 3des.

echo "Data no encryption: " . PHP_EOL . bin2hex($data) . PHP_EOL;

// Encrypt with openssl, default PKCS#7 Padding.
$value_pkcs7 = openssl_encrypt($data, "des-ede3", $key, OPENSSL_RAW_DATA);

echo "Encrypted data openssl pkcs#7: " . PHP_EOL . bin2hex($value_pkcs7) . PHP_EOL;

// Encrypt the same thing with mcrypt
$value_mcrypt = mcrypt_encrypt(MCRYPT_3DES, $key, $data, MCRYPT_MODE_ECB);

echo "Encrypted data mcrypt: " . PHP_EOL . bin2hex($value_mcrypt) . PHP_EOL;

// Now, encrypt with openssl without padding.
$value_no_padding = openssl_encrypt($data, "des-ede3", $key, OPENSSL_RAW_DATA | OPENSSL_NO_PADDING);

echo "Encrypted data openssl no padding: " . PHP_EOL . bin2hex($value_no_padding) . PHP_EOL;

```
The output is:
```
Data no encryption: 
3132333435363738
Encrypted data openssl pkcs#7: 
4e482868ad8cea12cb174766443668f6
Encrypted data mcrypt: 
4e482868ad8cea12
Encrypted data openssl no padding: 
4e482868ad8cea12
```
The difference in the output is one more block with PKCS#7 Padding which forces to always end with a padded block, in the case that the data size ends with a full block, it adds one more block as you can see in the example; and if you do not have a full block at the end, and you want to use **no padding** with openssl you should pad that final block by yourself

**\Phalcon\Crypt**

This one uses openssl, and does not provide a way to use **no padding** and manually pad data as you would like because it's forced to PKCS#7 by default.

If I were encrypting and decrypting data I personally would **NOT** use 3DES with ecb, and if I were, I wouldn't have problems with padding, since I'm encrypting and decrypting the data; but when a third party software does not use PKCS#7 Padding which is the case, I must disable that padding on openssl which cannot be achieved with actual `\Phalcon\Crypt` behavior.

Regards,
Federico.

**Comment by virgofx** [comment]
Federico -- You're correct.. It's one of the slight options right not included as it's a rare case. Typically, crypt is handling both Encrypt/Decrypt. However, the right approach in fixing the API interfaces, creating adapters for each (OpenSSL and Libsodium) and allowing the native options for both padding, schemes, and few other areas would solve this issue.

I've actually had it on my list for awhile as I've made some other changes to the adapters internally to make them faster. I'll see if I can get around to updating these.

**Comment by kornerita** [comment]
@virgofx 

I agree, the right approach is to have a \Phalcon\CryptInterface, \Phalcon\Crypt\Adapter, \Phalcon\Crypt\Adapter\OpenSSL and \Phalcon\Crypt\Adapter\Libsodium or something like that.

Thanks for looking into this, and if you can get it faster, the better.

In the meantime I am using openssl manually, I open this NFR to enhance the Phalcon framework since I like it so much :)

Regards,
Federico.
