### ISSUE TITLE
How to supress rowcount before create/update

### ISSUE THREAD

**Issue by chinalu** [phalcon/cphalcon#13031]
Before create a new model,  Phalcon will `SELECT COUNT(*) "rowcount" FROM `table` WHERE `id` = ?`, how to supress exists check?

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
