### ISSUE TITLE
Response content could not be send manually

### ISSUE THREAD

**Issue by woody712** [phalcon/cphalcon#13037]
when I use Micro Applications,
I don't want to send the response automatically,
so I get the values by method "$app->getReturnedValue()" and put them in "Response Content".
At the last, send them by manual.
```php
    try {
        $app = new Micro($di);
        ...
        $app->handle();
    } catch (\Exception $e) {
        
    }
    $app->response->send();
```

```php
// right
class PressureController
{
    public function test()
    {
        return ['hello world'];
    }
}
// wrong
class PressureController
{
    public function test()
    {
        return 'hello world';
    }
}
```
But I got a strange question, If I return an array in handler, everything is be OK, for strings, it will be send automatically and throw exception below:
```php
// 
hello world<br />
<b>Fatal error</b>:  Uncaught Phalcon\Http\Response\Exception: Response was already sent in phalcon/http/response.zep:611
Stack trace:
#0 /data/web/open-leo/src/app/public/index.php(32): Phalcon\Http\Response-&gt;send()
#1 {main}
  thrown in <b>phalcon/http/response.zep</b> on line <b>611</b><br />
```

### Details

* Phalcon version: 3.2.0
* PHP Version:  7.0.19-1
* Operating System: debian 9
* Installation type: Compiling from source
* Server: Nginx

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/12908

**Comment by sergeyklay** [comment]
Refactored in the https://github.com/phalcon/cphalcon/pull/12378
