### ISSUE TITLE
My php version is 7.0.10，which phalcon could I download？

### ISSUE THREAD

**Issue by williamtse** [phalcon/cphalcon#13055]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
// paste output here
```
> Provide minimal script to reproduce the issue

```php
// paste code
```
### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
3.2.2

https://phalconphp.com/en/download/linux
https://phalconphp.com/en/download/windows

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
