### ISSUE TITLE
Namespace aliases don't work in many to many

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#13051]
> **Describe what you are trying to achieve and what goes wrong.**

When using namespace aliases in models in Many To Many relation they don't work, there is just error unknown model or alias.

> Provide minimal script to reproduce the issue

```php
$modelsManager = $di->get('modelsManager')->registerNamespaceAlias('MN', 'MyNamespace');

namespace MyNamespace;

class User extends Model
{
    public function initialize()
    {
        $this->hasManyToMany('id', 'MN:ProductUser:', 'userId', 'productId', 'MN:Product', 'id', ['alias' => 'products']);
    }
}

class ProductUser extends Model
{
}

class Product extends Model
{
}
```
### Details

* Phalcon version: 3.2 (`php --ri phalcon`)
* PHP Version: 7.0.13 (`php -v`)
* Operating System: Ubuntu 14.04
* Installation type: Compiling from source
* Zephir version (if any):
* Server: apache
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
I think it's still a issue.

**Comment by Ark4ne** [comment]
I'm not sure, i don't use namespace alias,  but "MN:ProductUser:" should be "MN:ProductUser" ? 
There is a ":" too much, right ?

And you can use this : 

```php
namespace MyNamespace;

class User extends Model
{
    public function initialize()
    {
        $this->hasManyToMany('id', ProductUser::class, 'userId', 'productId', Product::class, 'id', ['alias' => 'products']);
    }
}

class ProductUser extends Model
{
}

class Product extends Model
{
}
```

no need for aliases, and better for refactoring if you use an IDE that supports refactor.
