### ISSUE TITLE
clustered template rendering

### ISSUE THREAD

**Issue by svfnix** [phalcon/cphalcon#13050]
I want to suggest to adding a new template rendering mechanism which i named CTR. 
it is very efficient and comfortable and usable
if this is possible, please add it to view object

### clustered template rendering
in this mechanism every template has a phtml file and a directory beside that shapes a tree of parent-child[s] templates

something like these :

> views/fa.phtml
> views/fa/admin.phtml
> views/fa/admin/news.phtml
> views/fa/admin/news/index.phtml
> views/fa/admin/news/add.phtml
> views/fa/admin/news/edit.phtml
> views/fa/admin/blog.phtml
> views/fa/admin/blog/index.phtml
> views/fa/admin/blog/add.phtml
> views/fa/admin/blog/edit.phtml

> views/en.phtml
> views/en/admin.phtml
> views/en/admin/news.phtml
> views/en/admin/news/index.phtml
> views/en/admin/news/add.phtml
> views/en/admin/news/edit.phtml
> views/en/admin/blog.phtml
> views/en/admin/blog/index.phtml
> views/en/admin/blog/add.phtml
> views/en/admin/blog/edit.phtml
> ...

in this onion like structure we have n layer and every inner layer will be wrapped by parent layer **Automatically**

at the moment i've written a function which can render this kind of structure. i want to suggest this mechanism to be added to the core of phalcon.

```php
namespace App;

class Controller extends \Phalcon\Mvc\Controller
{
    protected function ctrRender(){
        $args = func_get_args();
        $args = explode('/', implode('/', $args));

        $param = [];
        if(is_array(end($args))) {
            $param = array_pop($args);
        }
        while($args){
            $this->view->render(implode('/', $args), $param);
            array_pop($args);
        }
    }
}
```
usage:
```php
class IndexController extends \App\Controller
{
    public function indexAction()
    {
        $this->ctrRender('fa/admin/blog/add');
        // or
        $this->ctrRender('fa', 'admin', 'news', 'index');
        // or
        $this->ctrRender('en', 'admin', 'news', 'edit', [
                'news' => $news
        ]);

        // there is no limit in number of layers
        $this->ctrRender('en', 'admin', 'news', 'index', 'bla', 'bla', 'bla', ...);
    }
}
```

```php
// fa.phtml
<div class="fa">
        <?= $this->getContent() ?>
</div>
```

```php
// fa/admin.phtml
<div class="admin">
        <?= $this->getContent() ?>
</div>
```

```php
// fa/admin/news.phtml
<div class="news">
        <?= $this->getContent() ?>
</div>
```

```php
// fa/admin/news/index.phtml
<div class="index">
        <h1>hello there</h1>
</div>
```

```php
// result
<div class="fa">
        <div class="admin">
                <div class="news">
                        <div class="index">
                                <h1>hello there</h1>
                        </div>
                </div>
        </div>
</div>
```

**Comment by Jurigag** [comment]
Doesn't this already working like this? Phalcon renders already each level.

**Comment by svfnix** [comment]
related to phalcon's document :
https://docs.phalconphp.com/en/3.2/views

it picks some certain template from fixed position and i think it is not very flexible.
maybe i'm wrong

**Comment by Jurigag** [comment]
Yes you wrong, there is hierarchical rendering - https://docs.phalconphp.com/en/3.2/views#hierarchical-rendering

**Comment by svfnix** [comment]
document says that **Hierarchical Rendering** offers a 3 level template system (Action view, Controller layout and Main layout) and this is not n layer. also it picks this templates from certain position.

i want to have a main layout. 
// main.phtml

 for each language i have a sub layout which wrapped ba main.phtml
// main/fa.phtml
// main/en.phtml

// also have a layout for each role in each sub layout which wrapped by en.phtml
// main/en/admin.phtml
// main/en/user.phtml
// main/en/guest.phtml

for each controller a layout which wrapped by admin.phtml
// main/en/admin/news.phtml

for each action a layout which wrapped by news.phtml
// main/en/admin/news/index.phtml
// main/en/admin/news/add.phtml
// main/en/admin/news/edit.phtml

i needs a 5 layer mechanism. also i need to choose this layouts manual

`
if($user->role() == ROLE_ADMIN){
$this->render(main/en/admin/news/index.phtml);
} else {
$this->render(main/en/user/news/index.phtml);
}
`

**Comment by Jurigag** [comment]
You can choose layouts manual. If you need this then do PR, tbh it seems like only application specific thing, not many will use this.

**Comment by svfnix** [comment]
yep i did.
i just wanted to offer something more efficient and comfortable.
thank you

**Comment by Jurigag** [comment]
You can just mix `{% extends %}` and hierarchical rendering and you will almost have what you want. Though i didn't test it.

**Comment by svfnix** [comment]
extending is a great method for sharing chunks of code but i prefer to have separated layouts.
any way, it was just a suggestion. 

Phalcon is a grate and easy to use framework and i liked to have this functionality in it.

i've already written a function to solve my problem.
thank you.
