### ISSUE TITLE
[NFR] Improve Filter Service

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/cphalcon#13060]
Hi I think the actual filter service is very rigid and not very customizable. Although we can add functions can not be encapsulated in objects which is a great loss of usability and maintenance.

### New Filter Service
1. Be able to define each of the available filters and their params
2. Filters, even pre-defined filters, that have configuration parameters
3. A magic method to easily access them from the service
4. All filters must be objects and implement a FilterInterface interface

### Example Proposal One
New filter service
```php
$di = new Phalcon\Di();
$di->set('filter', function() {
    $filter = new Phalcon\Filter(true); // true/false => to load or not default filters (string, email, absint, etc)
    $filter->loadDefaultFilters();
    $filter->removeDefaultFilters();
    $filter->set('someFilter', new Phalcon\Filter\SomeFilter()); //add new filter
    $filter->remove('email'); //remove filter
    $filter->set('absint', new My\Filter\AbsInt()); //rewrite filter
});
```

### Example Proposal Two
Configurations params
```php
class Striptags implements FilterInterface {
    public function __construct($whitelist = null) {}
}
``` 

### Example Proposal Three
A magical method for rapid access to sanitize()
```php
$this->getDI()->filter->absint(-1555);
$this->getDI()->filter->trim(' hello world!!      '); 
```` 

### Example Proposal Four
Filter are objects and implement an interface
```php
interface FilterInterface {
     public function sanitize($value);
}
```

Well what do you think?

**Comment by niden** [comment]
This has been implemented. Thank you @emiliodeg for the idea

https://docs.phalconphp.com/4.0/en/filter
