### ISSUE TITLE
Feature request: add asynchronous method for db

### ISSUE THREAD

**Issue by sunchuo** [phalcon/cphalcon#13068]
It will be great if phalcon provided ways to write data asynchronously

`
$this->db->queryAsync();
`

**Comment by virgofx** [comment]
Phalcon is a framework that extends on top of the DB adapters. Most adapters do not support async. /close

**Comment by sunchuo** [comment]
http://www.myleftstudio.com/api/Phalcon_Async.html

**Comment by stamster** [comment]
@sunchuo that's fork of old Phalcon which is pure C, - does not even use Zephir. 

But in general, something like ReactPHP to be incorporated in Phalcon would be amazing, not only DB functions.

**Comment by gouchaoer** [comment]
it's run in php-fpm.
impossible to use async api.

**Comment by gouchaoer** [comment]
You can use this `$this->db->queryAsync();` in php-fpm applications.
But you must call some blocking method just like `$this->db->waitResult()`. It's useless.
