### ISSUE TITLE
[Enhancement] Phalcon\Http\RequestInterface

### ISSUE THREAD

**Issue by kornerita** [phalcon/cphalcon#13061]
Hi,

I would like to ask for an update in [Phalcon\Http\RequestInterface](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/requestinterface.zep) to match the following [Phalcon\Http\Request](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep) methods for compatibility:

- [RequestInterface::get](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/requestinterface.zep#L38) to match [Request::get](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep#L93)
- [RequestInterface::getPost](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/requestinterface.zep#L48) to match [Request::getPost](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep#L110)
- [RequestInterface ::getQuery](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/requestinterface.zep#L58) to match [Request::getQuery](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep#L157)
- Add [Request::getPut](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep#L126) to RequestInterface.

This would be for Phalcon 4+ for backward compatibility on 3rd party existing implementations of RequestInterface.

Thanks,
Federico.

**Comment by sergeyklay** [comment]
Good catch. Thank you 👍

**Comment by kornerita** [comment]
No problem :)

**Comment by virgofx** [comment]
Also missing `getURI()`

Found this existing issue for you Niden. I would just run through both side by side to see if any additional ones are missing.

CC: @niden

**Comment by sergeyklay** [comment]
@niden Whether this addressed?

**Comment by niden** [comment]
@sergeyklay The PR synched the interfaces between Request and RequestInterface

https://github.com/phalcon/cphalcon/pull/13666
