### ISSUE TITLE
Custom filter makes system slow

### ISSUE THREAD

**Issue by Iworb** [phalcon/cphalcon#13065]
I've created custom filter to compile *.scss to *.css. It's really simple:
```
class Scss implements FilterInterface
{
    protected $_compiler;

    public function __construct() { $this->_compiler = new Compiler(); }

    public function filter($contents)
    {
        return $this->_compiler->compile($contents);
    }
}
```
And I'm using it like so:
```
$am = new \Application\Assets\Manager();
$collection = $am->collection("css-head")
    ->setLocal(true)
    ->addFilter(new \Application\Assets\Filter\Scss()) // My filter
    ->setTargetPath(PUB_PATH . "/assets/head.css")
    ->setTargetUri("/assets/head.css")
    ->join(true);
$collection->addCss('path/to/bootstap.css');
$collection->addCss('path/to/my.scss');
```
I'm using this filter for both css and scss collection of files and when I've add a big css (bootstrap), it stucks. I think that filter tried to compile all files and then check result file with existing one, even is there no changes.
I know that I just could separate css and scss colletions, but what if I want to use scss version of bootstrap? Even if I won't change it, but will change my own scss file, it still compile all of it to check the result.
Is there a way to check files changes first and if there no changes in all files and compiled file in his place DO NOTHING?

**Comment by JABirchall** [comment]
I believe phalcon does try to compile the files on every request. I just build them on release there isn't a need to have it compiled all the time or even have code checking if it needs building.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/1756 https://github.com/phalcon/cphalcon/issues/925
