### ISSUE TITLE
can you add a new function setPath() to Phalcon\Logger\Adapter\File

### ISSUE THREAD

**Issue by feelsad** [phalcon/cphalcon#13071]
```php
use Phalcon\Logger\Adapter\File as FileLogger;

$di->set('logger', function ($file = null) {
    $logger = new FileLogger(BASE_DIR . '/running/logs/' . ($file ? $file : date('Ymd')));
    return $logger;
}, true);

$di->get('logger', ['logFile1.txt'])->log('this is a text 1', Logger::INFO);
$di->get('logger', ['logFile2.txt'])->log('this is a text 2', Logger::INFO);
```

**I want to write different type logs to different files,
but when i tried i found that the shared DI get service can`t resolve this problem**

I know i can set a DI service without shared which can solve it, but i don`t want to create the second logger object

**could you add a function setPath() to the class Phalcon\Logger\Adapter\File**

**Comment by stamster** [comment]
Base class for `Phalcon\Logger` adapters implements `AdapterInterface`.

So method should be put there as well: https://github.com/phalcon/cphalcon/blob/master/phalcon/logger/adapterinterface.zep

Additionally, it would good idea to adopt `Psr\Log\LoggerInterface` https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

**Comment by niden** [comment]
@feelsad Thank you for reporting this.

The Logger has been rewritten to follow the PSR-3 interface. With the new logger you can do the following:

```php
use Phalcon\Logger;
use Phalcon\Logger\Adapter\Stream;

$adapter1 = new Stream('/logs/first-log.log');
$adapter2 = new Stream('/remote/second-log.log');
$adapter3 = new Stream('/manager/third-log.log');

$logger = new Logger(
    'messages',
    [
        'local'   => $adapter1,
        'remote'  => $adapter2,
        'manager' => $adapter3,
    ]
);

// Log to all adapters
$logger->error('Something went wrong');

// Log to specific adapters
$logger
    ->excludeAdapters(['manager'])
    ->info('This does not go to the "manager" logger);
```

This way you can log to all adapters or only the ones you want.

https://github.com/phalcon/cphalcon/pull/13636

Closing

**Comment by feelsad** [comment]
@niden  Get it , Thank you
