### ISSUE TITLE
[NFR] Implement Model\MetaData\Apcu

### ISSUE THREAD

**Issue by hakimio** [phalcon/cphalcon#13078]
### Expected and Actual Behavior

I would expect APC extension dependency to be fully removed in Phalcon 3.2, but it seems "Phalcon\Mvc\Model\MetaData\Apc" is still using it.

### Details
* Phalcon version: 3.2.2
* PHP Version: 7.1
* Operating System: Windows 10
* Installation type:  precompiled Windows dll
* Zephir version (if any): 0.9.9-868cb1f92b
* Server: Apache

**Comment by Jurigag** [comment]
It will be in phalcon 4. We follow semver so we couldn't remove it in phalcon 3.2. Don't really see a problem, just install apcu_bc.

**Comment by hakimio** [comment]
I am using apcu_bc, but ideally I would like to get rid of it.
You could leave "Phalcon\Mvc\Model\MetaData\Apc" as is for compatibility and simply introduce a new one called "Phalcon\Mvc\Model\MetaData\Apcu" for those who want to use it.
Later in version 4, you can remove it entirely.

**Comment by Jurigag** [comment]
Yea i was proposing this already. But this should be in 3.3, so w really need version 3.3 @sergeyklay

**Comment by sergeyklay** [comment]
Implemented in the `3.3.x` branch. Thank you for contributing.
