### ISSUE TITLE
how to install specific phalcon framework version 2.0

### ISSUE THREAD

**Issue by wahd6** [phalcon/cphalcon#13075]
i have a application which is working fine with version 2.0

for that i am unable to install phalcon **version 2.0** only latest version **version 3.2.2** is installing so how can i install v 2.0..??

```
curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh" | sudo bash
sudo apt-get install php5-phalcon
sudo apt-add-repository ppa:phalcon(2.0x)/legacy
```

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
