### ISSUE TITLE
LIKE BINARY in Model::findFirst() search condition results in Fatal exception: Syntax error

### ISSUE THREAD

**Issue by tdely** [phalcon/cphalcon#13077]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

Trying to use LIKE BINARY for case-sensitivity in search condition for Model::findFirst() results in fatal error. LIKE BINARY is necessary when required to perform case-sensitive searches on tables/columns that are have case-insensitive collation.

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
Fatal exception: Syntax error, unexpected token STRING(:some_col:), near to ' LIMIT :APL0:', when parsing: SELECT [Vendor\Models\Test].* FROM [Vendor\Models\Test] WHERE some_col LIKE BINARY :some_col: LIMIT :APL0: (169) in /var/www/controllers/TestController.php on line 74#012#0 [internal function]: Phalcon\Mvc\Model\Query->parse()#012#1 [internal function]: Phalcon\Mvc\Model\Query->execute()#012#2 /var/www/controllers/TestController.php(74): Phalcon\Mvc\Model::findFirst(Array)#012#3 [internal function]: Vendor\Controllers\TestController->bindAction('2B1zAU-3e3tiF-1...')#012#4 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(Vendor\Controllers\TestController), 'bindAction', Array)#012#5 [internal function]: Phalcon\Dispatcher->_dispatch()#012#6 [internal function]: Phalcon\Dispatcher->dispatch()#012#7 /var/www/lib/application/Application.php(439): Phalcon\Mvc\Application->handle()#012#8 /var/www/public/index.php(45): Vendor\Application\Application->run()#012#9 {main}
```
> Provide minimal script to reproduce the issue

```php
$condition = array(
    'some_col LIKE BINARY :some_col:',
    'bind' => array(
        'some_col' => $mystring,
    )
);

$license = Model::findFirst($condition);
```
### Details

* Phalcon version: 3.2.2
* PHP Version: 5.6.30-0+deb8u1
* Operating System: Debian Jessie
* Installation type: Installing via package manager
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema): MariaDB

**Comment by Jurigag** [comment]
Well most likely it looks like phql assume this is `LIKE BINARY`, and then :some_col: is not recgonized. I guess it doesn't know what `LIKE BINARY column means`. Most likely you need to make some dialect extension with function LIKE_BINARY or something like this.
