### ISSUE TITLE
 I think "OR" here should be "AND".

### ISSUE THREAD

**Issue by kspotfujita** [phalcon/cphalcon#13085]
https://github.com/phalcon/cphalcon/blob/44ce3c6d5d00cfe0626ff09c0ce4b825e39389d0/phalcon/validation/validator/uniqueness.zep#L301

Even if "<>, NOT IN" condition is connected with "OR", the set does not converge.

**Comment by Jurigag** [comment]
But this is EXCEPT conditions, so don't select records where some column is some value. When you have multiple except provided obviously you want to have OR here. So you don't have records with this columns with this value or with this column with this value and so on. AND doesn't make sense in this case.

**Comment by kspotfujita** [comment]
Hm. I could not think of any business logic example that would have to use OR.
Currently I extend Uniqueness and use it.
I wanted to use it like the following.
```
$validator->add(
    'email',
    new Uniqueness([
        'except'=>[
            'deleted'=>'1',
            'email'=>['',null]
        ]
     ])
 );
```

**Comment by Jurigag** [comment]
For example - i don't want results which are deleted = 0 or active = 0.

**Comment by kspotfujita** [comment]
I want condition "deleted <> '1' and email is not null".
However, the current implementation gets "deleted <> '1' or email is not null".
 I want to unique only when email is not null.

**Comment by Jurigag** [comment]
But you want unique email. So it's like:

`WHERE email <> :email: AND (deleted <> '1' or email is not null)`

Then it's making huge difference. If you would have AND here then it doesn't make sense.
