### ISSUE TITLE
run phalcon in php-cli and use coroutine to do io

### ISSUE THREAD

**Issue by gouchaoer** [phalcon/cphalcon#13088]
hey, i am a big fan of phalcon and zephir.
I have explained my idea that the bottle neck of phalcon in:https://github.com/phalcon/zephir/issues/694#issuecomment-331716887

I think use coroutine(which is only possible in php-cli) is the key to improve performance. 
Swoole has already do it and get great improvement: https://github.com/swoole/swoole-src

I think run phalcon in php-cli and use coroutine deserves a try. As you can see swoole does not have  a strong community as phalcon. so if you are interested in the idea, why not try to run phalcon in swoole or implement coroutine in phalcon itself?

**Comment by sergeyklay** [comment]
Close in favor of #13068

**Comment by gouchaoer** [comment]
No, coroutine is different from asynchronous method.
ReactPHP, swoole1.x are asynchronous framework. they run in php-cli and act like nodejs early days. But call-back hell problem make it difficult to develop application(Althoug many framework use Generators to implement semi-coroutine to overcome this).
swoole2.x implemented full coroutine and it's possible to run laravel/yii in swoole http server(whichi is run as php-cli coroutine). Of course you should change something in laravel/yii and disallow blocking method.

**Comment by kideny** [comment]
phalcon is a web framework.

**Comment by stamster** [comment]
I support any idea which will improve core stuff. Even some ideas might sound too unrealistic for real world apps to take into account... but at least it's got to see a community full of nice ideas!

Thumbs up @gouchaoer

**Comment by gouchaoer** [comment]
not unrealistic.
some framework has already use coroutine like:https://github.com/swoft-cloud/swoft(it's in chinese and in developing at present)
