### ISSUE TITLE
Syntax error, unexpected token NUMERIC PLACEHOLDER(?1), near to ' HOUR)'

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#13084]
I've changed auth example of Vokuro to work with datetime field in mysql and stumbled on an error.
When running a count with parameters on my model I get:

_Syntax error, unexpected token NUMERIC PLACEHOLDER(?1), near to ' HOUR)', when parsing: SELECT COUNT(*) AS rowcount FROM_ 

```
$attempts = FailedLogin::count([
            'ip = ?0 AND created_at > DATE_SUB(NOW(), INTERVAL ?1 HOUR)',
            'bind' => [
                '127.0.0.1',
                10
            ]
        ]);
```
Running a query like the one below works fine.

SELECT COUNT(*) AS rowcount FROM failed_logins WHERE ip = '127.0.0.1' AND created_at > DATE_SUB(NOW(), INTERVAL 10 HOUR)

**Comment by Jurigag** [comment]
PHQL doesn't support interval. You need to use https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Db/Dialect/MysqlExtended.php

**Comment by ruudboon** [comment]
Ah ok, sorry. Missed that in the docs. thnx
