### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library

### ISSUE THREAD

**Issue by huyquyet** [phalcon/cphalcon#13096]
I installation php phalcon via https://docs.phalconphp.com/en/3.2/installation#installation-macos-brew

```php
// brew install php70-phalcon
```
and Edit your php.ini file and then append at the end:
```php
// extension=php_phalcon.so
```
> path file : usr/local/etc/php/7.0/php.ini

but when i run terminal php -i, php -m or php -v ... show Warning
```php
// php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.23_15/lib/php/extensions/no-debug-non-zts-20151012/php_phalcon.so' - dlopen(/usr/local/Cellar/php70/7.0.23_15/lib/php/extensions/no-debug-non-zts-20151012/php_phalcon.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.23_15/lib/php/extensions/no-debug-non-zts-20151012/php_phalcon.so' - dlopen(/usr/local/Cellar/php70/7.0.23_15/lib/php/extensions/no-debug-non-zts-20151012/php_phalcon.so, 9): image not found in Unknown on line 0
PHP 7.0.23 (cli) (built: Sep 25 2017 08:07:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

Please help me!

**Comment by oscarmolinadev** [comment]
Try

`brew reinstall --build-from-source php70-phalcon`

**Comment by huyquyet** [comment]
i run 
brew reinstall --build-from-source php70-phalcon
but is not yet success

**Comment by sergeyklay** [comment]
It is not Phalcon issue.

* https://stackoverflow.com/questions/22384764/osx-php-error-localhost-and-unable-to-load-dynamic-library
* https://stackoverflow.com/questions/6827880/phpunit-dynamic-library-warnings-image-not-found 
* https://github.com/Homebrew/homebrew-php/issues/3842

When creating new issues please be extra detailed and thorough. If you have any questions please drop into [official forums](https://forum.phalconphp.com).

Also you can open an issue at [Homebrew/homebrew-php](https://github.com/Homebrew/homebrew-php) repo.
