### ISSUE TITLE
Codeception not able to load Class 'Phalcon\Mvc\MongoCollection' using Phalcon Loader

### ISSUE THREAD

**Issue by bkvaiude** [phalcon/cphalcon#13090]
Hello Guys,

I'm using PHP7 and phlacon3.2.2 for my project.
I have written few test cases for the model and run them using following steps

> `vendor/bin/codecept generate:test unit Timezone`

> `vendor/bin/codecept run unit`

> Unit Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> - TimezoneTest: Some featurePHP Fatal error:  Class 'XXX\Models\Timezone' not found in /home/xx/Documents/projects/xxx/tests/unit/TimezoneTest.php on line 17

> Fatal error: Class 'xx\Models\Timezone' not found in /home/xxx/Documents/projects/xxx/tests/unit/TimezoneTest.php on line 17

Don't know the reason. Then loaded the class using `require` function and got following output

> Codeception PHP Testing Framework v2.3.5

> Powered by PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

> PHP Fatal error:  Class 'Phalcon\Mvc\MongoCollection' not found in /home/xxx/Documents/projects/falcon/app/models/Timezone.php on line 5

> Fatal error: Class 'Phalcon\Mvc\MongoCollection' not found in /home/xxx/Documents/projects/falcon/app/models/Timezone.php on line 5

I was hoping that phalcon will load the classes using loader (at beginning level), but it was not working in that way.

I would appreciate the help and guidance on this issue.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/11156
