### ISSUE TITLE
[NFR] Model Relationship improvments

### ISSUE THREAD

**Issue by JABirchall** [phalcon/cphalcon#13098]
## Expected and Actual Behavior

Phalcon's table joins are weird in a sense if you join a oneToMany, phalcon returns a resultset of MANY of the same users with ONE row of the joined table each. This would be considered backwards by many who like me have used Symfony and|or Laravel for most of their developer career.

Laravel relationships: https://laravel.com/docs/5.5/eloquent-relationships#one-to-many
Doctrine Associations: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#one-to-many-bidirectional

This is already done for Lazy loading oneToMany but for cases where the developer wants to join the table within the query 1 row is returns per result.

### Expected Behavior

Phalcon should join the table and store the joined resultset in the model's properties for the developer.

## Extra New Feature Request

Add an annotation|function to EAGER load a table relationship to a specific property either by adding an option to model relationships functions to eager load the table and|or by adding a with() function to the model.

Doctrines annotation 
```
/*
 * Join users role
 * @OneToMany(model="Roles")
 * @JoinColumn(name="role_id", referencedColumnName="id", fetch="EAGER")`
 */
public $role
```
Laravel with() function `$user = User::with('roles')->get();`

This helps to reduce query overhead

### Details
* Proposed version: 4.0

**Comment by Jurigag** [comment]
Eager loading is available in incubator. Also eager loading most of the time is just slow.

**Comment by JABirchall** [comment]
I know there is `with()` in them incubator, But I think it should be built into the framework, also eagerload/joining is slow if you don't setup your database correctly.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/1117
