### ISSUE TITLE
[BUG] Phalcon Models integers are type numeric string

### ISSUE THREAD

**Issue by JABirchall** [phalcon/cphalcon#13108]
### Expected Behavior
When using strict type condition of an integer against a model property of integer, the condition should return true or false based on the value.

```php
const ROLE_ADMIN = 1,
      ROLE_MODERATOR = 2,
      ROLE_PARTNER = 3,
      ROLE_ADVERTISER = 4,
      ROLE_USER = 5;

    /**
     *
     * @var integer
     * @Identity
     * @Column(type="integer", length=2, nullable=false)
     */
    public $role;

if ($user->role === self::ROLE_ADMIN) {
    // Allow user to restricted pages
}

echo (new \Phalcon\Debug\Dump())->variables($user->role === self::ROLE_ADMIN, $user->role, self::ROLE_ADMIN);
```
Expected Output:
```php
var 0 Boolean (TRUE)
var 1 Integer (1)
var 2 Integer (1)
```

### Actual Behavior
Because phalcon models populate integer properties with type numeric string, any type of strict conditions will undoubtedly fail

Actual Output:
```php
var 0 Boolean (FALSE)
var 1 Numeric string (1) "1"
var 2 Integer (1)
```
### Details

* Phalcon version: 3.2.0
* PHP Version: 7.0.11
* Operating System: Windows 10
* Installation type: Github release
* Server: Nginx
* Other related info (Database, table schema): Mysql

**Comment by sergeyklay** [comment]
Did you check https://github.com/phalcon/cphalcon/issues/12608 ?

**Comment by JABirchall** [comment]
Ill try it out.
