### ISSUE TITLE
Allow to get response without headers

### ISSUE THREAD

**Issue by benfavre** [phalcon/cphalcon#13101]
Could you please wrap theses with an if statement so I can wrap the application class to emulate PSR-7
Right now I have no easy way of only getting the reponse back and handling it as i please.

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L394
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L395

**Comment by stamster** [comment]
Indeed this might be useful (actually required) to integrate ReactPHP with Phalcon. So Phalcon would not send raw HTTP headers nor body but rather return entire Response object instead.

**Comment by sergeyklay** [comment]
Implemented in the `3.3.x` branch. Thank you for contributing.
