### ISSUE TITLE
[NFR] JsonSerializable for all Message classes

### ISSUE THREAD

**Issue by grigoriy-ivanov** [phalcon/cphalcon#13113]
It will make code more simple when we are sending json response. 
At the moment:
```php
$messages = $robot->getMessages();
foreach ($messages as $message) {
    $response[] = $message->getText();
 }
$request->setJsonContent($response);
```
I would like to:
```php
$messages = $robot->getMessages();
$request->setJsonContent($messages);
```
P.S. Phalcon has two different MessageInterfaces. Maybe should are be merged into one?

**Comment by sergeyklay** [comment]
Could you please open a separated issue about MessageInterfaces

**Comment by grigoriygithub** [comment]
Yes. of course. #13114
