### ISSUE TITLE
Different MessageInterfaces in Models and Validation

### ISSUE THREAD

**Issue by grigoriy-ivanov** [phalcon/cphalcon#13114]
Phalcon has two different MessageInterfaces: 
```Phalcon\Validation\MessageInterface```, ``` Phalcon\Mvc\Model\MessageInterface``` with same code.

I think will be perfect to create Phalcon Messages component ```Phalcon\Messages```:

 ```Phalcon\Messages\MessageInterface``` for message
 ```Phalcon\Messages\GroupInterface``` for a collection of Messages with filter/map/etc. methods

**Comment by niden** [comment]
This has been implemented in 4.x
