### ISSUE TITLE
[NFR] Model::toArray() exclude columns

### ISSUE THREAD

**Issue by lajosbencz** [phalcon/cphalcon#13118]
It would be really neat if we could provide a list of excluded columns when calling ```toArray()``` on a model.

### Current behaviour

```php
$excluded = ['sensitive'];
$included = ['id','name','and','a','few','more','columns','except','one','etc'];
$robot = Robots::findFirst()->toArray($included);
// OR
$robot = Robots::findFirst()->toArray();
foreach($excluded as $x) {
    unset($robot[$x]);
}
```

The current way is either tedious (you have to whitelist columns), or inefficient (you query all the columns, then unset)

### Expected behaviour

```php
$excluded = ['sensitive'];
$included = ['id','name','and','a','few','more','columns','except','one','etc'];
$robot = Robots::findFirst()->toArray(null, $excluded);
array_key_exists('sensitive', $robot); // false
array_key_exists('id', $robot); // true
```

If there is some other way to achieve this that i'm unaware of, please ignore this and let me know! :]

**Comment by sergeyklay** [comment]
Did you try 
```php
$robots = Models\Robots::find(array(
    'columns' => 'id' 
    'limit' => 1 
));
```

**Comment by lajosbencz** [comment]
```php
function toArray($include=null, $exclude=null)
{
    $a = parent::toArray($include);
    if(is_array($exclude)) {
        foreach($exclude as $x) {
            unset($a[$x]);
        }
    }
    return $a;
}
```

My use case is a CRUD via websockets and it would be convenient if i could blacklist columns easily, like a hashed password field for example.

So i figured the second parameter for toArray could be the blacklist array, but now it seems a bit limited use-case... and i've already implemented it in the base model, even if its inefficient :]

**Comment by grigoriygithub** [comment]
@sergeyklay  It's a good solution. But when  ```columns() ``` are used, result is ```Phalcon\Mvc\Model\Row```
It would be perfect to get result as a Model instance.

**Comment by Jurigag** [comment]
You can't because you don't select full model. And all the events and other stuff won't be correct. Like for example you could have in some event updating of column which you didn't select. What then? This is by design that when you don't select full model - you get row object. And it will never change because this is one and only correct way. Maybe in data mapper we could change this.
