### ISSUE TITLE
Issues with view->pick

### ISSUE THREAD

**Issue by guillaumesmo** [phalcon/cphalcon#13125]
Hi,

I think there are inconsistencies in the view->pick mechanism
I'm using phalcon 3.2.2

according to the doc:
```php
        // Pick 'views-dir/products/search' as view to render
        $this->view->pick('products/search');

        // Pick 'views-dir/books/list' as view to render
        $this->view->pick(
            [
                'books',
            ]
        );

        // Pick 'views-dir/products/search' as view to render
        $this->view->pick(
            [
                1 => 'search',
            ]
        );
```

The first one will render products/search correctly

The second will not render books/list, but just books. Except if the layout was set to list I guess

The third one should not work (let renderView = pickView[0];)

and also $this->view->pick(['products', 'search']); renders 'products'

Not sure what the rules are

**Comment by sergeyklay** [comment]
/ cc: @phalcon/documentation

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/docs#1363
