### ISSUE TITLE
Dispatcher's params override any setVar()

### ISSUE THREAD

**Issue by dugwood** [phalcon/cphalcon#13121]
### Expected and Actual Behavior

#13046 introduce a fix and a breaking change: params are now send to `setVars()`, erasing previously set variables. Works great, but:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L351
=> injects dispatcher's params, and erase previously set variables in controllers.

### Before 3.2.3
Url: /test-page/1234
```php
$router->add('/test-page/{bar:[0-9]+}', ['controller' => 'MyController', 'action' => 'test']);
```
in MyController::testAction():
```php
$this->view->setVar('bar', 'foo');
```
in test.volt:
```
{{ bar }}
```
Returns:
```
foo
```

### After 3.2.3
Returns:
```
1234
```

### Details

* Phalcon version: 3.2.3
* PHP Version: 7.0
* Operating System: Linux
* Installation type: package from packagecloud.io
* Server: Other

**Comment by sergeyklay** [comment]
Fixed in the [latest stable version](https://github.com/phalcon/cphalcon/releases/tag/v3.2.4). Feel free to open a new issue if the problem appears again.  Thank you for contributing, and for helping us make Phalcon better.
