### ISSUE TITLE
Raw server response instead of custom 404 page if site is acessed via URL https://site.com/index/whatever/

### ISSUE THREAD

**Issue by ch3ll0v3k** [phalcon/cphalcon#13138]
### Details

* Phalcon version: (`php --ri phalcon`)
```
toor@abi:~$ php --ri phalcon
phalcon

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.4
Build Date => Oct 21 2017 16:27:43
Powered by Zephir => Version 0.10.4-11e39849b0

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```

* PHP Version: (`php -v`)
```
toor@abi:~$ php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

* Operating System: 
```
toor@abi:~$ uname -a
Linux abi 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```
```
toor@abi:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie
```

* Installation type: Compiling from source || installing via package manager
```
>>> package manager
```

* Zephir version (if any):
```
Zephir => Version 0.10.4-11e39849b0
```

* Server: 
```
Apache: 2.4.10-10+deb8u11
```

* Other related info (Database, table schema): 
```
IS NOT DB RELATED
```
=========================

Hay, i get raw server response instead of custom 404 page, if site is accessed via URL 

https://site.com/**index**/whatever/

It does not matter will be passed in as action name https://site.com/index/**action**/ or not

Phalcon does not get initiated, and server show default 404 page with text.

Maybe is it just *SERVER THING* ? 

```
Not Found

The requested URL /index/whatever/ was not found on this server.
Apache/2.4.10 (Debian) Server at site.com Port 443
```  

I have tested this on 2 diff. servers and result is same.
Have 2 Modules setup configuration. Can provide link so you can see it. p2p.
Also, if any server logs are needed, just ask. 

Thank you

**Comment by Jurigag** [comment]
Must likely server thing. For me it works correctly.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

**Comment by ch3ll0v3k** [comment]
Oke. Thank you and sorry fr posting in wrong section.
