### ISSUE TITLE
groupBy modifiers causing mysql exception

### ISSUE THREAD

**Issue by deulos** [phalcon/cphalcon#13135]
In PHQL I'm trying to set a groupBy ordered (ref: https://dev.mysql.com/doc/refman/5.7/en/group-by-modifiers.html) and it causes an exception when running the query.

Just using $queryBuilder->groupBy('user_id desc') returns this: 
Syntax error, unexpected token DESC, near to ') ...

And it is caused because the modifier is inside parenthesis.

This causes exception: group by (user_id desc)
This does not: group by (user_id) desc

* Phalcon version: 3.2.0
* PHP Version: 5.6.31
* Operating System: FreeBSD 11
* Installation type: installing via package manager
* Server: Apache

**Comment by Jurigag** [comment]
Simply PHQL doesn't support syntax like this. PHQL != MySQL or whatever other syntax. Add dialect extension to have it working.

**Comment by Jurigag** [comment]
Though those paranthesis thing is weird but still, pretty sure that GROUP BY was never implemented to expect anything more after column name.
