### ISSUE TITLE
Loader not lowercasing subdirectories of PS-4 namespaces

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#13142]
I have an auth class in library/auth/Auth.php
I'm trying to load it with the example below

```
$loader = new Loader();

$loader->registerNamespaces(
    [
        "Test\\Library" => "/project/application/library/"
    ]
);

$eventsManager = new Phalcon\Events\Manager();

// Listen all the loader events
$eventsManager->attach(
    'loader:afterCheckClass',
    function (Phalcon\Events\Event $event, Loader $loader) {
        echo $loader->getCheckedPath();
    }
);

$loader->setEventsManager($eventsManager);

$loader->register();
$test = new Test\Library\Auth\Auth();
```
The class isn't found and the check path gives back: /project/application/library/Auth/Auth.php that should be /project/application/library/auth/Auth.php

**Comment by kornerita** [comment]
Hi,

Try 

```php
$loader->registerNamespaces(
    [
        "Test\\Library\\Auth" => "/project/application/library/auth"
    ]
);
```
:)

**Comment by ruudboon** [comment]
This is working, but shouldn't it be possible to have subdirectories like PSR-4 specify? Otherwise I have to register +50 namespaces.

**Comment by kornerita** [comment]
I had the same problem and used this fix, but I only have 4 or 5 namespaces, I didn't dig into it but I think that's ambient dependent; I use Mac and Linux (debian and CentOS) with ph 5.6 and 7.0, and I remember it worked without specifying every sub namespace on one ambient, but not on another.

Which OS are you using?

We can try on different systems to see if it's related.

Can you provide a minimal script to reproduce the issue?

I'll help on the testing.

**Comment by ruudboon** [comment]
Running on docker based on phalconphp/php:alpine-3-php7 image. Looks like it's working if I link volumes to my Mac but fails when the files are inside the container.
The script above is almost the test script. I will see if I can create a custom docker image to show the issue.

**Comment by kornerita** [comment]
The issue is Mac related, the Mac's filesystem and php are case insensitive, while on linux they are not.

Sample script:

```php
<?php
  
touch("hi");

var_dump(file_exists("hi"));
var_dump(file_exists("Hi"));

```
true true for Mac.
true false for Linux.

**Comment by ruudboon** [comment]
Accidently it works on Mac (that I use for development). But the issue persist on production.
Reading the Phalcon documentation it mentions that the loader is PS-4 compatible so I think that the Phalcon Loader should lower case the path based on the namespace before trying to include it.

**Comment by kornerita** [comment]
@ruudboon I've use Mac for devel too :)

Last time I've checked Phalcon's Loader uses PHP's `is_file` function:

[here](https://github.com/phalcon/cphalcon/blob/v3.2.4/phalcon/loader.zep#L272)
[here](https://github.com/phalcon/cphalcon/blob/v3.2.4/phalcon/loader.zep#L368)
[here](https://github.com/phalcon/cphalcon/blob/v3.2.4/phalcon/loader.zep#L421)

That is case insensitive for Macs at least or case insensitive filesystems.

Should lowercase `fixedDirectory` [here](https://github.com/phalcon/cphalcon/blob/v3.2.4/phalcon/loader.zep#L355)?

**Comment by kornerita** [comment]
Btw, [Loader's doc](https://docs.phalconphp.com/en/3.2/api/Phalcon_Loader) shows register on every sub namespace, so maybe this is a new feature request?

**Comment by ruudboon** [comment]
Hmm indeed. Maybe somebody from the core team (@sergeyklay ? :D ) could give some insight.

**Comment by kornerita** [comment]
Sure [here](https://docs.phalconphp.com/en/3.2/loader) it states that Loader is PSR-4 compliant, so I've read [PSR-4](http://www.php-fig.org/psr/psr-4/) carefully and correct me if I'm wrong but it doesn't imply that lowercase directories corresponds to ucfirst namespaces / subnamespaces ;)

**Comment by ruudboon** [comment]
You're right! I misinterpreted the PSR-4. I gonna change my dir names. Thnx
