### ISSUE TITLE
INVO does not have order management ?

### ISSUE THREAD

**Issue by salesiss** [phalcon/cphalcon#13147]
### Expected and Actual Behavior
INVO sample application does not have or is not showing any order management (create/edit/delete) for 'INVOICES'.

> **Describe what you are trying to achieve and what goes wrong.**
Create, edit, delete and manage invoices.

> Provide output if related. Provide coredump if any. 

> Provide minimal script to reproduce the issue
simply install invo from a fresh php 7.1 / ngnix 1.12 and try to add an invoice.
there was no functionalty avaliable.

```php
// paste code
```
### Details

* Phalcon version: (`php --ri phalcon`) 3.2.4
* PHP Version: (`php -v`)  7.1.7
* Operating System: amazon ami ec2 / m3.large
* Installation type: Compiling from source || installing via package manager
compiling via source
* Zephir version (if any):
* Server: Nginx 1.12.1
* Other related info (Database, table schema): mysql 5.6 new/fresh install.

![something very strange with invo - it s not showing neither edit nor manage invoices - is this normal qt](https://user-images.githubusercontent.com/19622775/32422577-39da38fc-c288-11e7-82bf-6392dae2b135.png)

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/invo#65
