### ISSUE TITLE
Please offer a method to set the rawBody

### ISSUE THREAD

**Issue by woody712** [phalcon/cphalcon#13152]
Hi buddy:

I use phalcon without fpm & nginx, but I use Swoole as the web service.

In my issue,
when the client sends a request (method "PUT") to server.
In ordinary way, we will get the params by `file_get_contents("php://input")`
phalcon source code:

cphalcon/phalcon/http/request.zep

`public function getRawBody() -> string
{
	var rawBody, contents;

	let rawBody = this->_rawBody;

	if empty rawBody {

			let contents = file_get_contents("php://input");
			/**
			 * We need store the read raw body because it can't be read again
			 */
			let this->_rawBody = contents;
			return contents;
	}
	return rawBody;
}`
the content will be saved in $_rawBody and can not be modified by outer.

I hope there will be another way to set the $_rawBody,
like `public function setRawBody($content) -> string`

**Comment by andrew-demb** [comment]
As a workaround, you can define your own Request (extends from Phalcon) class with `rawBody` in the constructor and set it to DI on init app.

As you can see, Request haven't any methods to change the state. So, I'm against to not implement this method in a request (while request is not immutable).

**Comment by Jurigag** [comment]
There is already PSR-7 issue, psr-7 have method withBody which allows you to change body of request.

**Comment by woody712** [comment]
@andrew-demb 
Actually, I did it in my project, thx.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/11789
