### ISSUE TITLE
Volt BUG: Embedding blocks into other blocks is not supported 

### ISSUE THREAD

**Issue by SimBioT1954** [phalcon/cphalcon#13155]
I'm getting the given error without of any real reason. This is because of  **if var > 0** condition.

```php
{% set vars = [1,2,3] %}

{% for var in vars if var > 0 %}
{% endfor %}

{% block container %}
{% endblock %}
```

Phalcon version: **3.2.3**
PHP Version: PHP **7.1.7**
Server: **Nginx**

**Comment by TimurFlush** [comment]
Most likely, this is because you declare the block "container" inside any other block. And this opportunity does not support the Volt.

**Comment by SimBioT1954** [comment]
Hello @TimurFlush! Do you see any embedded blocks in my example?

**Comment by SimBioT1954** [comment]
This does not work:
````
{% set vars = [1,2,3] %}

{% for var in vars if var > 0 %}
{% endfor %}

{% block container %}
{% endblock %}
````
But this one works fine:
````
{% set vars = [1,2,3] %}

{% for var in vars %}
{% endfor %}

{% block container %}
{% endblock %}
````

**Comment by TimurFlush** [comment]
See. Understand the essence of the problem. Most likely it is possible because of this:
https://github.com/phalcon/cphalcon/blob/23b4100faa3ef91863d7f05de3f1c7a450cd52bc/ext/phalcon/mvc/view/engine/volt/parser.c#L6469

**Comment by stamster** [comment]
Perhaps you could do if check before for loop. I think that's syntax problem there - so if you separate those IF and FOR... it should work, no?
