### ISSUE TITLE
[NFR] Add event router:beforeMount a group.

### ISSUE THREAD

**Issue by oscarmolinadev** [phalcon/cphalcon#13158]
I would like to have an event before mount a group of routes for manipulate the group. I'm developing a very big app with a lot of modules and each one have a group of routes, so in my case I want set a hostname by config, eg:

```
// config
<?php
$hosts = [
  'webModule' => 'example.com'
  'appModule' => 'test.com'
]

// groups
<?php

use Phalcon\Mvc\Router\Group 

$groupWeb = new Group();
$groupWeb->setHostName('#webModule#');
...

$groupApp = new Group();
$groupApp->setHostName('#appModule#');
...

```

With an event `router:beforeMount` I can replace the hostname, add one by default for each group, etc.. a lot of posibilites not only for edit the hostname.

Thanks, oscarmolinadev

**Comment by sergeyklay** [comment]
Implemented in the 3.3.x branch
