### ISSUE TITLE
Binding value to multiple placeholders

### ISSUE THREAD

**Issue by tigerstrikemedia** [phalcon/cphalcon#13179]
Binding value to multiple placeholders is not working the following script on a model gives me an invalid parameters errors from PDO 

Im sure this was working a few weeks ago, i'm not sure what has changed in that time. Is this supported by Phalcon?

```php
$builder = Di::getDefault()->get( 'modelsManager' )->createBuilder();

$builder->from( [ 'a' => Administrator::class ] );

$builder->where( "a.first_name LIKE :search: OR a.last_name LIKE :search: OR a.display_name LIKE :search: OR a.email LIKE :search:", [
    'search' => '%' . $search . '%'
] );
```

### Details

* Phalcon version: 3.2.4
* PHP Version: PHP 7.1.11
* Operating System: MacOS
* Installation type: Homebrew
* Server: LAMP Stack

**Comment by Jurigag** [comment]
You sure you have PDO::ATTR_EMULATE_PREPARES option set to true in db service?

**Comment by stamster** [comment]
Indeed `PDO` flag for `ATTR_EMULATE_PREPARES ` needs to be set for this to work.

**Comment by tigerstrikemedia** [comment]
@Jurigag @stamster 
Guys, I beat my head against this for hours, over multiple days and its as simple as that.........

Thank you!!

**Comment by sergeyklay** [comment]
@tigerstrikemedia Could we close this?

**Comment by Jurigag** [comment]
Sure thing

**Comment by tigerstrikemedia** [comment]
Yep, closing in 3.2.1.....
