### ISSUE TITLE
在使用jpa时，javax.persistence.DiscriminatorColumn经常用到，\Phalcon\Mvc\Model有没有类似的功能？

### ISSUE THREAD

**Issue by sprufu** [phalcon/cphalcon#13187]
像jpa中的`javax.persistence.DiscriminatorColumn`应用场景不少，但看完了phalcon文档没有发现类似的功能，请问这个能实现吗？

**Comment by andrew-demb** [comment]
Phalcon ORM doesn't have this feature.
