### ISSUE TITLE
Phalcon\Filter int!

### ISSUE THREAD

**Issue by sunchuo** [phalcon/cphalcon#13184]
```php
$filter = new Phalcon\Filter;
echo $filter->sanitize('100001l', 'int!');
//output 0 ,not 100001
```

### Details
  OS: Linux 10.10.10.200 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64
  PHP Version: 7.1.9
  PHP SAPI: cli
  PHP Bin: /usr/local/php/bin/php
  PHP Extension Dir: /usr/local/php/lib/php/extensions/no-debug-non-zts-20160303
  PHP Bin Dir: /usr/local/php/bin
  Loaded PHP config: /usr/local/php/etc/php.ini
Versions:
  Phalcon DevTools Version: 3.2.3
  Phalcon Version: 3.2.2
  AdminLTE Version: 2.3.6

**Comment by stamster** [comment]
If you expect there `100001` as integer, you should only remove `!` in your filter name.
```
$filter->sanitize('100001l', 'int');
```

**Comment by sunchuo** [comment]
`
case Filter::FILTER_INT_CAST:
return intval(value);
`

https://github.com/phalcon/cphalcon/blob/3.2.x/phalcon/filter.zep#L165

**Comment by stamster** [comment]
But one would usually want/need:

```php
case Filter::FILTER_INT:
				/**
				 * 'int' filter sanitizes a numeric input
				 */
return filter_var(value, FILTER_SANITIZE_NUMBER_INT);
```

https://github.com/phalcon/cphalcon/blob/3.2.x/phalcon/filter.zep#L157

As shown, that will use native PHP filter which just works as expected.


Frankly, I have no idea what is the use of `FILTER_INT_CAST` flag.

**Comment by Ark4ne** [comment]
Yes, but the strange thing is that the intval function works very well when you pass the value directly :

```php
$val = "100001l";
$filter = new Phalcon\Filter;

echo intval($val) . PHP_EOL;

echo $filter->sanitize($val, 'int!') . PHP_EOL;
```

Output : 
```
100001
0
```

**Comment by stamster** [comment]
@Ark4ne of course it gets you different result when you pass `int!` instead of `int`.

```php
$str = '100001l';

$filter = new \Phalcon\Filter;
// int! ???
$phalconRes = $filter->sanitize($str, 'int!');

//this is what you want to use to sanitize integer
$phalconResReal = $filter->sanitize($str, 'int');

//raw PHP
$vanillaRes = intval($str);

var_dump($str, $phalconRes, $vanillaRes, $phalconResReal);
```

Results:

```
string(7) "100001l"
int(0)
int(100001)
string(6) "100001"
```

**Comment by Ark4ne** [comment]
Yes yes, no problem for that, but my incomprehension must surely be related to a lack of knowledge on my part.

In the Phalcon \ Filter code, sanitize ($ str, 'int!') uses "intval".
So for me the behavior should be the same as that of the php intval function.

After, it is perhaps normal that the function "intval" in zephir realizes a cast int, and not a call to the php function "intval". 

It's just when reading the code like that, it does not seem logical ^^
