### ISSUE TITLE
Phalcon vc15 x64 for php 7.2.0?

### ISSUE THREAD

**Issue by vovamedinsky** [phalcon/cphalcon#13193]
How can I create this, or where I can fird Phalcon vc15 x64 for php 7.2.0?
last updated phalcon_x64_vc14_php7.1.0_3.2.4.zip doesnt work. no ext in php info
I use TS version.

**Comment by Jurigag** [comment]
We just don't have binary for php 7.2.0 yet. You would need to compile it yourself, it will be faster to use vagrant box i guess than doing it.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
