### ISSUE TITLE
Segmentation fault when DI set abstract class and attempting to get it 

### ISSUE THREAD

**Issue by Panoptik** [phalcon/cphalcon#13194]
### Expected and Actual Behavior
Expect to receive any exception instead of segfault

```php
Segmentation fault (core dumped)
```
> Provide minimal script to reproduce the issue

```php
abstract class A {}

$di = new \Phalcon\Di();
$di->set(A::class, A::class, false);
$di->get(A::class);
```
### Details

* Phalcon version: (`php --ri phalcon`)

phalcon

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.2
Build Date => Aug 14 2017 21:19:02
Powered by Zephir => Version 0.9.9-868cb1f92b

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

* PHP Version: (`php -v`)
PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

* Operating System:
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

* Installation type: Compiling from source || installing via package manager
Any type of installation 
* Zephir version (if any):
* Server: Nginx | Apache | Other
php-cli
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
You can't create instance of abstract class obviously. I guess there should be some exception instead of seg fault but thanks for reporting anyway.

**Comment by Jurigag** [comment]
Well that's weird, as i checked in source code of zephir it checks for constructor if it exists or not so there shouldn't be such issue. Or maybe abstract class in ZE doesn't have constructor property.

**Comment by Jurigag** [comment]
Okay it's zephir issue, fix on the way.

**Comment by Panoptik** [comment]
Good work, guys! Thanks a lot!

**Comment by Jurigag** [comment]
Keep in mind it will be fixed in next phalcon release, right now to have it working you need to build phalcon using latest zephir.
