### ISSUE TITLE
Error parsing PUT request encoded with multipart/form-data

### ISSUE THREAD

**Issue by ShpatAjvazi** [phalcon/cphalcon#13199]
**Details:**
I am having a problem creating a PUT request encoded with multipart/form-data.
I have this endpoint: /v1/users/{id} where I want to update a specific user and also upload the profile image for that particular user.
When I am trying to create a user everything works fine and it has the exact same request headers  and request data as update endpoint what differs is the request method POST.

**Printed response:**
 ["------WebKitFormBoundary4crbvp4LZVDHRNgu
Content-Disposition:_form-data;_name"]=>
  string(470) ""username"

test
...

**Printed request:**
["Accept-Language"]=>
  string(32) "en-US,en;q=0.9,de;q=0.8,sq;q=0.7"
  ["Accept-Encoding"]=>
  string(17) "gzip, deflate, br"
  ["Accept"]=>
  string(3) "*/*"
  ["Postman-Token"]=>
  string(36) "cfcb8090-ab83-5b07-409a-bfd2d85244a9"
  ["Authorization"]=>
  string(192) "JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI0IiwidXNlcm5hbWUiOiJtZmRvb3BtY2MiLCJpYXQiOjE1MTI0ODI5MjgsImV4cCI6MTUxMzA4NzcyOCwiYWNjZXNzIjpbXX0.y5-lGAOVMoo_8ir8FMSuvm27fzigHzSM35vDa-Kf-YA"
  ["Content-Type"]=>
  string(68) "multipart/form-data; boundary=----WebKitFormBoundarymfsiqk6jlg0xFYhc"
  ["Origin"]=>
  string(51) "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop"
  ["Cache-Control"]=>
  string(8) "no-cache"
  ["User-Agent"]=>
  string(120) "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
  ["Content-Length"]=>
  string(3) "549"
  ["Connection"]=>
  string(10) "keep-alive"
  ["Host"]=>
  string(9) "localhost"
}

* Phalcon version:
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.1
Build Date => Nov 24 2016 22:40:37
Powered by Zephir => Version 0.9.4a-dev-7e304ba18c

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off

* PHP Version: 
PHP 7.0.18 (cli) (built: Apr 16 2017 12:12:20) ( NTS )

* Operating System:
OS X EL Capitan 10.11.6

* Server: Nginx, using Docker.

**Comment by Jurigag** [comment]
Yea i had similar issue in my rest api, like both update user and his image, not sure what needs to be fixed in phalcon to have it working properly, in my action i have just workaround like this:

```php
$params = json_decode($this->request->getPost('teacher'), true); // not sure if you don't need to use here getPut, however i have PUT request and still the data is here only if i use getPost
$files = $this->request->getUploadedFiles(); 
```

I guess it's same with your case. With code above i don't have any issues.

**Comment by ShpatAjvazi** [comment]
Yes that is pretty much the same work around, converting the endpoint to POST and than getting files from request.

**Comment by Jurigag** [comment]
First we need to know if it's really any phalcon issue really.
