### ISSUE TITLE
Incorrect Snapshot Response with Model::getUpdatedFields() with Non-Changed Models

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#13202]
When a model that is using dynamic updates/snapshots is saved with no changes (either because no `sets()` took place or because all sets resulted in exactly identical previous values) the corresponding snapshot updated values returns the **entire set** of fields. It should return an empty array.

Sample Code:

```php
// Robot model is using dynamic updates + snapshots
$robot = Robot::findFirst();   // [ 'a' => 1, 'b' => 2 ]

print_r($robot->getChangedFields()); // Empty Array -- Good
print_r($robot->getUpdatedFields()); // Exception (Not saved yet) -- Good

$robot->save();

print_r($robot->getUpdatedFields()); // Full Robot Array [ 'a' => 1, 'b' => 2 ]

// Expected: Empty array since no fields were updated
```

cc @Jurigag 
cc @sergeyklay 

#### Reference Lines:
First block detects zero changed fields and returns without setting the old snapshot
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L2614-L2616

Call into `getUpdatedFields()` has an empty array for `_oldSnapshot` where the current logic assumes this is a new field and thus reports every field in the model.
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L4062-L4068

#### System Details
* Phalcon version: 3.2.4
* PHP Version: 5.6.32
* Operating System: CentOS 7.4
* Installation type: Packagecloud - php56u-phalcon3.2.4.ius.el7

**Comment by sergeyklay** [comment]
Fixed in the `3.3.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
