### ISSUE TITLE
Micro app 's get()  cannot use array params?

### ISSUE THREAD

**Issue by varobjs** [phalcon/cphalcon#13204]
`$this->app = new Micro($this->di);
`
`
$this->app->get('/', ['Api\IndexController', 'index'])`

this is will get a **error**
`Phalcon\\Mvc\\Micro::handle(): instanceof expects an object instance`

**Comment by Jurigag** [comment]
https://docs.phalconphp.com/hu/3.2/application-micro#routing-handlers-controllers

**Comment by varobjs** [comment]
@Jurigag 
thank you
