### ISSUE TITLE
A proposal for model in multi database

### ISSUE THREAD

**Issue by limingxinleo** [phalcon/cphalcon#13209]
### Expected and Actual Behavior

> **When I want to use a model to query the data of the same structure table in multiple schemas. But the result is not what I expected. For example, the following code, my default schema is test, but I want to query the data under test2. I want a parameter to modify schema.**

```php
class Order extends \Phalcon\Mvc\Model
{
    public $id;
    public $name;

    public function getSchema()
    {
        return 'test';
    }
}

$res = Order::find([
    'conditions' => 'id = ?0',
    'bind' => [1],
    'schema' => 'test2'
]);
```

### Details

* Phalcon version: (`3.2.4`)
* PHP Version: (`7.0`)
* Operating System: mac
* Installation type: brew
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema): mysql

**Comment by limingxinleo** [comment]
Of course, I can build two models to correspond to two libraries, But I don't think it's a good way to do it.

**Comment by limingxinleo** [comment]
I read the source code, I think the issue may affect the model relationship. So It may not be a good suggestion. Then I write a script for a new model extends the base model to solve this problem.If you have a good solution, I hope you can tell me about it.

**Comment by oscarmolinadev** [comment]
Look at **Setting multiple databases** in https://docs.phalconphp.com/en/3.2/db-models

**Comment by limingxinleo** [comment]
@oscarmolinadev Thanks
