### ISSUE TITLE
Inconsistent Phalcon\Config::merge()

### ISSUE THREAD

**Issue by pentagonal** [phalcon/cphalcon#13201]
Inconsistent config merge 

On some case of `Phalcon\Config::merge` that contain numeric (string/float/double) values possible lack of key name of config.

Because `Phalcon\Config` convert all keys into string, and when config doing merge process it will be validate the keys as numeric value not an integer (`string -> integer`).

Because on some case, config has been used to handle dynamic array values, eg: versioning.
Remove the `is_numeric` logic to `is_int` maybe better to make it more relevance.

## CASE (Logic numeric)

https://github.com/phalcon/cphalcon/blob/a0560cb3174b37d3b45a46986f5ac7aa1c7ffd81/phalcon/config.zep#L325

> Code Execution

```php
<?php
    use Phalcon\Config;
    $config        = new Config(['0.4' => 0.4]);
    $configToMerge = new Config(['1.1' => 1, '1.2' => 1.2, '2.8610229492188E-6' => 3]);
    $config->merge($configToMerge);
```
> Result

```text
Phalcon\Config Object
(
    [0.4] => 0.4
    [1] => 1
    [2] => 1.2
    [3] => 3
)

```

## CASE (arrayaccess increments)  -> offsetSet

And when config set as the increment also does not follow the `array` rules on method `offsetSet`

https://github.com/phalcon/cphalcon/blob/a0560cb3174b37d3b45a46986f5ac7aa1c7ffd81/phalcon/config.zep#L172

> Code

```php

$config   = new Config();
$config[] =  'a';
```
> Result
```text
Phalcon\Config Object
(
    [] => a
)
```

The increment if produce array

> Idea for increment key values (example code) -> like array reproduce of increment

```php
/**
 * php code start for increment
 *
 * @var \Phalcon\Config $this
 */
$array = get_object_vars($this);
// manipulate array this will be reproduce increment values
$array[] = true;
// move pointer into last array
end($array);
// real last increment
$increment = key($array);


```

the `offsetSet(index, value)` the index will be contains key as `null` if the increment set as empty array increment

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14186
