### ISSUE TITLE
php72 install with debug & enchant options + phalcon 3.2.0 may got 502 bad gateway

### ISSUE THREAD

**Issue by lanlin** [phalcon/cphalcon#13211]
install php 7.2 + phalcon 3.2.0 with homebrew-php may got 502 status.
here's the issues link from homebrew-php
[https://github.com/Homebrew/homebrew-php/issues/4649](https://github.com/Homebrew/homebrew-php/issues/4649)

it could be a phalcon problem or homebrew-php problem, i dont know.

macOS version: 10.13.2 (17C88)
Homebrew version: 1.4.0
PHP version in use: 7.2
Xcode version: 9.2 (9C40b)

```shell
brew install php72 --with-debug --with-enchant --with-homebrew-curl --with-pear --with-phpdbg --with-postgresql --without-legacy-mysql
```
with options above, install failed, enchant compile error.
remove "--with-enchant" install success, but got "502 bad gateway" after i install phalcon 3.2.0.
though i install phalcon with --build-from-source, still got 502 status.

when remove both "--with-enchant" and "--with-debug", it works.

**Comment by sergeyklay** [comment]
Is there any logs?

**Comment by Jurigag** [comment]
Most likely seg fault? Try running in gdb.

**Comment by lanlin** [comment]
@sergeyklay @Jurigag 

I find it's not the enchant problem, it's the php debug option.
Finally i install php 7.2 without "--with-debug", the problem solved.

I tried both phalcon 3.2.0 & 3.2.4, when php 7.2 installed with "--with-debug"  option got 502 bad gateway. But if without debug option, it works fine.

The strange thing is none error found in php error log, just find upstream closed in nginx log.
I have no more time to try strace the error. Sorry about that.

**Comment by Jurigag** [comment]
Yea in gdb you could possibly trace it. But it's seg fault for sure. Well you should use non debug version anyway for production or even developing.

**Comment by sergeyklay** [comment]
@lanlin The `--with-debug` option needed for PHP maintainers or/and extensions developers, who can/able use gdb and dig into core dumps : ) You shouldn't use this option for nothing.
