### ISSUE TITLE
When will be compiled dlls with phalcon_3.2.9?

### ISSUE THREAD

**Issue by vovamedinsky** [phalcon/cphalcon#13219]
When will be compiled dlls with phalcon_3.2.9? or how can I create them by myself from sourse code?

**Comment by sergeyklay** [comment]
@vovamedinsky  There is no 3.2.9 version. For DLLs please take a look at release page: https://github.com/phalcon/cphalcon/releases

We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
