### ISSUE TITLE
can get json type from mysql

### ISSUE THREAD

**Issue by shangxin2533** [phalcon/cphalcon#13213]
$types = $oMetaData->getDataTypes($this);
我的数据库里有一个字段是json类型，但该方法获取到的类型是string,请问什么原因，
phalcon版本：3.2 mysql:5.7

**Comment by zGaron** [comment]
从3.3.x这个版本开始支持

**Comment by zGaron** [comment]
see. https://github.com/phalcon/cphalcon/blob/c80c9286e9d472f5f855159a482f9f219dea080c/phalcon/db/column.zep#L131

**Comment by shangxin2533** [comment]
thank you
