### ISSUE TITLE
phalcon 3.2不支持mysql的json类型

### ISSUE THREAD

**Issue by shangxin2533** [phalcon/cphalcon#13214]
请问，phalcon获取数据库字段类型，支持mysql的json类型吗，我的数据库里有个字段是json类型的，问什么phalcon返回2呢，正常不应该是15吗

**Comment by zGaron** [comment]
@shangxin2533   这个问题你可以重新开一下，这里应该是 phalcon 的没有做到支持 JSON 类型。

**Comment by zGaron** [comment]
看了下 issue 里面的记录，发现现在 3.2.x 只作 bugfix 的维护，这种 带 NFR性质的，都让提交到 4.0.x。你可以在 4.0.x 上看下相关问题 看看有没有相同的。

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/12546
