### ISSUE TITLE
Modules in Cli

### ISSUE THREAD

**Issue by Laxilef** [phalcon/cphalcon#13221]
Здравствуйте.
При разработке заметил некоторые баги:
1. [Phalcon\Cli\Console::handle](https://github.com/phalcon/cphalcon/blob/master/phalcon/cli/console.zep#L145) не передает dispatcher'у имя модуля. Просто отсутствует вызов _dispatcher->setModuleName_.
Тот же [Phalcon\Mvc\Application::handle](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep) это прекрасно делает [на 266 строке](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L266):
`dispatcher->setModuleName(router->getModuleName());`

2. Тот же [Phalcon\Cli\Console::handle](https://github.com/phalcon/cphalcon/blob/master/phalcon/cli/console.zep#L132) не передает DI в метод Phalcon\Mvc\ModuleDefinitionInterface::registerAutoloaders:
`moduleObject->registerAutoloaders();`
Но при этом _Phalcon\Mvc\Application::handle_  [это делает](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L229):
`moduleObject->registerAutoloaders(dependencyInjector);`

* Phalcon version: 3.2.4
* PHP Version:  7.1.10

**Comment by Laxilef** [comment]
Эти баги кто-то исправлять планирует?

**Comment by grigoriygithub** [comment]
Duplicate #13229 
CLI не поддерживает модули. Но можно попробовать сделать самому: https://forum.phalconphp.com/discussion/7283/multiple-module-cli
