### ISSUE TITLE
[NFR] Enhanced JOIN syntax

### ISSUE THREAD

**Issue by afbora** [phalcon/cphalcon#13224]
I tried to use IN operator on LEFT JOIN with Phalcon PHQL but i get errors like that:

> Phalcon\Mvc\Model\Exception: Syntax error, unexpected token COMMA, near to

SQL raw string working great! SQL string like that:

```sql
LEFT JOIN articles AS art ON (art.id, art.journal_id, art.issue_id) IN ((sin.article_id, sin.journal_id, sin.issue_id))
```

But with PHQL format doesnt working. Phalcon PHQL line like that:

```php
->leftJoin("\App\Models\Articles", "(art.id, art.journal_id, art.issue_id) IN ((sin.article_id, sin.journal_id, sin.issue_id))", "art")
```
### Details

* Phalcon version: 3.2.4
* PHP Version: 7.0.26
* Operating System: CLOUDLINUX 7.4
* Installation type: EA4
* Server: Apache

**Comment by Jurigag** [comment]
Most likely PHQL doesn't support join syntax like this.

**Comment by afbora** [comment]
@Jurigag Can not implement this feature?

Solved with query builder that created my self

**Comment by Jurigag** [comment]
It's about PHQL parser, i don't know how to implement it so i can't. Few people here know this, don't expect it in near future to have it implemented, sorry.

**Comment by sergeyklay** [comment]
@afbora We can implement this. Could you please follow NFR form: https://docs.phalconphp.com/en/3.2/new-feature-request

**Comment by afbora** [comment]
@sergeyklay Thanks! It would be better to label it as NFR 😄
