### ISSUE TITLE
please help me !!!

### ISSUE THREAD

**Issue by shangxin2533** [phalcon/cphalcon#13223]
1.I want to define date_type in model,but it does't effect,below is my model:

class Canvases extends Model
{
/**
* @var integer
/
public $id;
/*
* @var string
*/
public $name;
}
2.$ret = $canvasModel->findFirstById(1), var_dump($ret->id);
the id type is string****

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
