### ISSUE TITLE
model 定义数据类型不起作用

### ISSUE THREAD

**Issue by shangxin2533** [phalcon/cphalcon#13220]
1.我建立了一个model
 /**
     * @var int
     */
    public $create_time;
2.Canvases::findFirstById(122)得到的create_time为什么是string类型呢

**Comment by zGaron** [comment]
注释跟字段定义的是没关系的。

**Comment by leupom** [comment]
数据库的连接配置一下：
'options' => array(
            Pdo::ATTR_EMULATE_PREPARES => false,
            Pdo::ATTR_STRINGIFY_FETCHES => false
        )
