### ISSUE TITLE
No code in validation message [Phalcon\Validation\Validator\Date]

### ISSUE THREAD

**Issue by iflagri** [phalcon/cphalcon#13236]
Phalcon\Validation\Validator\Date
No "code" in validation message.

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validator/date.zep#L95 yea that's true

**Comment by sergeyklay** [comment]
@Jurigag Could you please prepare a patch

**Comment by sergeyklay** [comment]
Fixed in the `3.3.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
