### ISSUE TITLE
Phalcon homepage has rendered php at the bottom left of the page

### ISSUE THREAD

**Issue by troglodyte** [phalcon/cphalcon#13231]
slate('about') ?> 

^-- is rendered on the bottom left.
https://phalconphp.com/en/

Not sure where else to put this bug...

> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
// paste output here
```
> Provide minimal script to reproduce the issue

```php
// paste code
```
### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
This PR is for issues with phalcon. Please create it here https://github.com/phalcon/website

**Comment by JABirchall** [comment]
This issue is encountered on this page https://github.com/phalcon/website/blob/96567a1d644e15dc6e16a2a5784a3856efc0a7b0/app/views/include/footer.volt#L31

However this looks normal, So it maybe an issue with Phalcon::Volt 3.3 if that is what the website is running.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/website#469
