### ISSUE TITLE
Why Phalcon\Mvc\Model __isset method doesn't check if getter method exists

### ISSUE THREAD

**Issue by erisrayanesh** [phalcon/cphalcon#13249]
https://github.com/phalcon/cphalcon/blob/f0732e9c2ac4c234afa30fcd4dff1b94d24fe24a/phalcon/mvc/model.zep#L4592

In the line which is mentioned, __get method checks if a method with a special format exists or not? If exists, then it will call that.
example if a model has a method `modelInstance.getSomeProperty()`  then you can use it as a property `modelInstance.some_property`

The question is why the __isset method doesn't return true? The result of this code `isset(modelInstance.some_property)` is `false`. I think it is very good to put another check for getter method existence.

I have used phalcon/incubator with twig template engine for my project views. The twig engine checks if the property is set then it will call it. The model __isset returns false and the __call will execute.

**Comment by sergeyklay** [comment]
@erisrayanesh Could you please provide a code to reproduce the issue. Also would be better for understanding problem is to provide model and db schema.

**Comment by erisrayanesh** [comment]
Here is an example. In the example below the idea is about to generate slug from the title attribute. I know it is not a best practise to have slug attribute.

```php
use Phalcon\Mvc\Model;

class Product extends Model
{
    public $id;
    public $title;
    // other attributes .... except slug! which is not a real db column and
   // will be generated at runtime

    public function getSlug()
    {
        //for example write some code to produce a 
        //slug from the title attribute
        return generateProductSlug($this->title);
    }
}

$product = Product::findFirst(2);

echo $product->slug;
// the output is a string returned by getSlug method of product model
// output : 'samsung-galaxy-note-7'
//But if try to check slug attribute with isset method, it returns false
if (isset($product->slug)) {
    echo 'this is slug ' . $product->slug; 
}
```
At the line **4590** and **4592** of [cphalcon/phalcon/mvc/model.zep](https://github.com/phalcon/cphalcon/blob/f0732e9c2ac4c234afa30fcd4dff1b94d24fe24a/phalcon/mvc/model.zep#L4592) it checks if a getter method exists and if true, it will call it. That's why `getSlug` method executes. But as I mentioned at my previous comment's last paragraph, some libraries like Twig use `isset()` method before call for `$product->slug` which causes to run `__get` method. If it returns `false` then Twig expect `slug` is a method of `$product` object and then it will call it and causes to run `__call` method and unfortunately `__call` method doesn't check for a getter method.
