### ISSUE TITLE
Mvc_Router_Route coredump

### ISSUE THREAD

**Issue by cq-z** [phalcon/cphalcon#13255]
docker 64899484/phalcon
in mac is OK ,but in linux is coredump . dockerfile build in This machine the image run php is ok.
coredump:
```
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.
[New LWP 1]
[New LWP 8]
[New LWP 7]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php /data/www/public2/index.php'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f920b0007b0 in zim_Phalcon_Mvc_Router_Route___construct ()
   from /usr/local/lib/php/extensions/no-debug-non-zts-20170718/phalcon.so
[Current thread is 1 (Thread 0x7f92176f3740 (LWP 1))]
```
#12172

**Comment by cq-z** [comment]
![image](https://user-images.githubusercontent.com/3038490/34916363-50194f56-f972-11e7-972a-1a17fce49fd2.png)

**Comment by cq-z** [comment]
* Phalcon version: 3.3.1
* PHP Version: 7.2.1
* Server: Nginx

**Comment by sergeyklay** [comment]
Hello

> Core was generated by `php /data/www/public2/index.php'.

We'll need core dump. Also please provide minimal code to reproduce.

**Comment by cq-z** [comment]
[归档.zip](https://github.com/phalcon/cphalcon/files/1631395/default.zip)

**Comment by 51systems** [comment]
I've also experienced this.
In my case I build the image on one linux machine, and then when executing on my laptop I get the core dump in the route constructor.

Curiously, if I rebuild phalcon on my laptop (in a docker container) it runs ok. My laptop is a bit older so it may be possible it doesn't have all the cpu features that the other linux box does.

I suspect this may be due to the use of `-march=native -mtune=native` for the `CFLAGS` in the install script but I haven't preformed extensive research.

Install script:
```
cd /tmp \
    && wget https://github.com/phalcon/cphalcon/archive/v$PHALCON_VERSION.tar.gz \
    && tar xf v$PHALCON_VERSION.tar.gz \
    && cd cphalcon-$PHALCON_VERSION/build && ./install
```

**Comment by cq-z** [comment]
in the hub.docker build . mac is working ,linux is not woring.
This information hopes to help you
mac cpu:
![image](https://user-images.githubusercontent.com/3038490/38461627-e2e42f78-3b07-11e8-9e47-6e08e7bf5692.png)
linux cpu (Cpu23):
![image](https://user-images.githubusercontent.com/3038490/38461629-f454cd94-3b07-11e8-9cc0-659bbd783a01.png)

**Comment by cq-z** [comment]
Use swoole as http server is ok 
Use fpm is error

**Comment by sergeyklay** [comment]
@cq-z Could you please remove `-march=native -mtune=native`, recompile Phalcon and test again?

https://github.com/phalcon/cphalcon/blob/caeac66e7db02fd54c44a27cf22a6381654af2ee/build/install#L27

**Comment by cq-z** [comment]
@sergeyklay It is ok!
I am add 
```
  && sed -i "s/-march=native -mtune=native -O2 -fomit-frame-pointer/-O2 -fomit-frame-pointer/" ./install && ./install \
```
centos 7.2 already no coredump

**Comment by cq-z** [comment]
thank you @sergeyklay @51systems
