### ISSUE TITLE
Can't getActionName with Dispatcher in Micro Applications?

### ISSUE THREAD

**Issue by dxkrs** [phalcon/cphalcon#13251]
## description

I want to do some interceptors at my controller ``` onConstruct()```, and I want to get current atction name.
I can do that if I use the 

```
$application = new \Phalcon\Mvc\Application($di);   
echo $application->handle()->getContent(); 
```
in the `index.php`

e.g.
```
class TestController extends \Phalcon\Mvc\Controller
{
        public function onConstruct()
        {
             echo $this->dispatcher->getActionName();
        }

        public function test()
        {
               echo '<br>'; 
               echo 'this is test action';
        }
}
```
Request the "localhost/test/test" I will see 
```
test
this is test action
```
#### BUT
It does'n work if use **Micro Applications** in the `index.php`
```
$application = new \Phalcon\Mvc\Micro($di)
$application->handle();
```
 I try to `var_dump($this->dispatcher->getActionName())` and the result is NULL.
And I found the `beforeExecuteRoute()` doesn't work too.
It is right?
I want to get the action name in the controller in Micro Applications, how can I do it?

**Comment by Jurigag** [comment]
There is no dispatcher used in micro apps. Yes, it is right. Not a bug.

You need to use `micro:beforeExecuteRoute` if you want to use such event.

For recognizing route and do something for it(like an acl) - i would use `$this->router->getRoute()->getPattern()` or `$this->router->getRoute()->getName()` - in this case you need to name it obviously.
