### ISSUE TITLE
Class inheritance abnormal behavior (undefined method \u0001::)

### ISSUE THREAD

**Issue by yergo** [phalcon/cphalcon#13263]
### Expected and Actual Behavior

I am willing to extend Phalcon\Cache\Backend\Redis to allow it in using RedisCluster (a class from phpredis php extension.)

I have to change the internal _redis of parent class.

Expected behavior is it proceeds properly after replacing _connect() method with some slight changes.

The class looks like this:

```php
namespace Custom\Mvc\Cache;

use Phalcon\Cache\Exception;

class Redis extends \Phalcon\Cache\Backend\Redis
{
	protected $_redis = null;
	protected $clusterMode = false;

	/**
	 * Overriding to achieve Cluster functionality.
	 *
	 * Translated from:
	 * https://github.com/phalcon/cphalcon/blob/83ba827b4019bfca7a9b76ec13933fa53ca99786/phalcon/cache/backend/redis.zep
	 */
	public function _connect()
	{
		$options = $this->_options;

		$persistent = $options['persistent'];
		$host = $options['host'];

		if (!is_array($host)) {
			return parent::_connect();
		}
		$this->clusterMode = true;
		$this->_redis = new \RedisCluster(null, $host, false, 0, $persistent);
	}
}
```

Than I've declared service:

```php
$di->set('redis', function () use ($di)
{
	$config = $di->getConfig();
	if (empty($config->redis)) {
		throw new \Exception('Configuration [redis] section missing');
	}

	$frontCache = new \Phalcon\Cache\Frontend\Data(array(
		"lifetime" => 3600
	));

	$host = is_string($config->redis->host) ? $config->redis->host : (array) $config->redis->host;

	$cache = new \Custom\Mvc\Cache\Redis(
		$frontCache,
		[
			'prefix' => $config->redis->prefix,
			'persistent' => (bool) $config->redis->persistent,
			'host' => $host
		]
	);

	return $cache;
});
```
And by far its working. I can event connect, but problems happen after trying to do anythung related to keys in class:

No matter if I declare the line of `protected $_redis = null;` or not, whatever else I am trying to do after class instantiation:

```php
$redis = $di->getRedis(); // this goes ok
$redis->delete('test'); // fails with undefined \u0001::delete()
$redis->save('test', md5(mt_rand()), 10); // fails with undefined \u0001::set()
```

with the wierdest error message so far:

```
Call to undefined method \u0001::delete()
or
Call to undefined method \u0001::set()
```

now **FOCUS**: `\u0001::delete()` .... ????

* Phalcon version:
```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.1
Build Date => Jul 10 2017 17:03:55
Powered by Zephir => Version 0.9.9-868cb1f92b

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```

* PHP Version: (`php -v`)
```
PHP 7.1.12-3+0~20180105140140.13+jessie~1.gbp691a82 (cli) (built: Jan  5 2018 14:21:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-3+0~20180105140140.13+jessie~1.gbp691a82, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

* Operating System: debian based
* Installation type: phalcon - Compiling from source || php-redis - almost sure that via package manager
* Server: Nginx

**Comment by yergo** [comment]
Also, if I rewrite code for save or delete, class start to work properly in particular, rewritten case. But I am not willing to rewrite whole class ;)

**Comment by yergo** [comment]
Was able to reproduce with simple docker composition: yergo/phalcon_issue_13263. Hopefully would support in fixing this bug.

**Comment by yergo** [comment]
Looks like it never gonna be done. So Phalcon.

**Comment by niden** [comment]
Never say never. It will be addressed when time allows. The Redis adapter is going to be rewritten also so that might be a good idea to check this one out also.

**Comment by niden** [comment]
Having written the above, we will need to verify this for v4 and PHP 7.2+ since we are not working on v3 any more unless it is a security issue.

If you see the bot closing the issue, feel free to comment on it and it will reopen it.

**Comment by ViltusVilks** [comment]
Have You compiled Phalcon with Redis already enabled?
I had similar issue (segfault) and could not extend class  when Collection has reference to \MongoId()  (in Zephir code). No warning in compile time either.

What I did - loaded official latest mongodb extension "driver" and replaced MongoId() to \MongoDB\BSON\MongoID()

Now I can extend class and no SegFaults and can use that MongoDB driver.
Take in advance, that it looks like for each PHP version C/opcode is working differently. 
Try to use 7.2.14.

**Comment by yergo** [comment]
As of thatsamguy/xenial-php71, phalcon is being compiled in docker example afterwards redis installation.

I am quite not flexible with versions juggling, error happened at environment with potentially 30krpm traffic. Luckily was tested pre-prod.
