### ISSUE TITLE
Phalcon 3.3 Micro error handler

### ISSUE THREAD

**Issue by mignz** [phalcon/cphalcon#13262]
### Expected and Actual Behavior

> The [Micro Application error handler](https://docs.phalconphp.com/bg/3.2/application-micro#error-handling) isn't working properly on the latest version of Phalcon. The exception isn't caught by the handler.

> Expected output

`{"code":401,"status":"error","message":"Invalid email or password."}`

> Actual output

<img width="766" alt="screen shot 2018-01-17 at 15 24 30" src="https://user-images.githubusercontent.com/358114/35058821-9fcff10c-fba8-11e7-85c5-824f8bc3a7be.png">

> Script to reproduce

```php
<?php

$app = new Phalcon\Mvc\Micro();

$app->get(
    '/',
    function () {
        throw new \Exception('Invalid email or password.', 401);
    }
);

$app->error(
    function ($exception) {
        echo json_encode(
            [
                'code'    => $exception->getCode(),
                'status'  => 'error',
                'message' => $exception->getMessage(),
            ]
        );
    }
);

$app->handle();
```
### Details

* Phalcon version: 3.3
* PHP Version: 7.1 & 7.2
* Operating System: macOS & Ubuntu 16.04
* Installation type: Installing via package manager
* Server: Nginx & Apache

**Comment by virgofx** [comment]
You have Xdebug enabled. That is the correct behavior. /close

**Comment by mignz** [comment]
That makes no sense, and my Plesk server doesn't have Xdebug enabled but the logs are still being filled with errors. Isn't this error handler supposed to handle the errors?

**Comment by Doehl** [comment]
Can you describe what is wrong with your output. Because it looks fine to me.

If what you expect is for the error handler to "catch" the exception, then this will not happen by design.
The error handler is a function that will purely be called in case of an fatal error, it does not have any "try/catch" functionality. It is just there for you, to be able to send a valid response back to the client.

**Comment by mignz** [comment]
Then I must have understood it wrong. The documentation says "can be used to trap any errors that originate from exceptions", so I thought it would catch them and handle the error. I don't see the point of this error handler then. I can't even send a valid JSON when it prints a PHP error.

**Comment by Doehl** [comment]
You can just disable the printing of PHP error in you php.ini.
That I will always recommend on a production server anyway.

**Comment by virgofx** [comment]
You're exception is caught everything is handled normally. XDebug handles all exceptions as well with their own table output. Just disable it and everything works as expected.

**Comment by mignz** [comment]
It's not XDebug. I've tried on a server without XDebug and it still throws a Fatal Error:

```
{"code":401,"status":"error","message":"Invalid email or password."}
Fatal error: Uncaught Exception: Invalid email or password. in .../teste.php:8 Stack trace: #0 [internal function]: Closure->{closure}() #1 .../teste.php(24): Phalcon\Mvc\Micro->handle() #2 {main} thrown in .../teste.php on line 8
```

So is it supposed to catch the exception or not? I think I'll check the source myself... :D

**Comment by virgofx** [comment]
Ah above comment is right ... it's the built in display error setting for PHP.

**Comment by mignz** [comment]
@virgofx So, do you agree if I say that I shouldn't use this error handler for, as an example, throw a 401 response with a Invalid password or even a 400 error with a bad response error.

Because if I do, even if the error isn't shown in the browser/app, it is logged. The logs would get huge because of failed login attempts. <-- Just an example...

**Comment by sergeyklay** [comment]
It is [`html_errors = On`](http://php.net/manual/en/errorfunc.configuration.php#ini.html-errors) guys.

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/micro.zep#L977

As you see you either need to return response or false here.

**Comment by mignz** [comment]
@Jurigag I suppose that's some other error handler. You can't throw an Exception and then return some boolean on the same function.

**Comment by Jurigag** [comment]
Not on the same function! You need to return false or response object in $app->error()  handler

**Comment by mignz** [comment]
Yeah, `return false` does the trick. Why isn't that on the documentation?
Thanks mate.

**Comment by Jurigag** [comment]
I don't know, ask @niden xD

**Comment by diogoca** [comment]
@Jurigag do you know if is possible to put the error code handler on middleware? Like we do on ResponseMiddleware to format successfully responses?

**Comment by Ark4ne** [comment]
It's `display_errors = On`
