### ISSUE TITLE
Injectable::__get() is ignoring shared flag

### ISSUE THREAD

**Issue by hubertnnn** [phalcon/cphalcon#13272]
### Expected and Actual Behavior
myService was added like this:
`$this->di->set('myService', function() { return rand(0, 100);}, false);`
Shared parameter was set to false;

$this is a class that extends injectable.
```php
$a = $this->myService;
$b = $this->myService;
$c = $this->myService;
```
$a, $b and $c should contain different values

They contain the same value (service is shared)

### Details

* Phalcon version: 3.2.4
* PHP Version: 7.0.25
* Operating System: ubuntu
* Installation type: apt
* Server: Nginx

**Comment by Jurigag** [comment]
It's not ignoring it. It adds it as property. I think this is just how it is designed and that's it. Just access `$this->di->get('serviceName')`

**Comment by hubertnnn** [comment]
If I access it using $this->di then it works fine, but problem is when I access it using the magic method.
_get implementation is bad since it not only calls $this->di->getShared() instead of $this->di->get(), but it also caches it without checking if its allowed to do so.

**Comment by Jurigag** [comment]
There is no problem as i wrote. It's just adding it as a property. This is a how it is designed, it's not a bug really. It's a NFR, and we can change it for phalcon 4.
