### ISSUE TITLE
[NFR] Batch Fetch by Relation

### ISSUE THREAD

**Issue by alexbusu** [phalcon/cphalcon#13287]
I found it would be great to make possible to `getRelationRecords` from a `Model\Resultset\Simple`, or with [another](https://github.com/phalcon/cphalcon/blob/a8635777097ac4b3ad6c51ec6bc1fe5fb86ca90e/phalcon/mvc/model/manager.zep#L1247) `Model\Manager` method, that would build/run a single PHQL/query, resulting in another Resultset. What do you think?

**Comment by sergeyklay** [comment]
@alexbusu Sounds good to me

**Comment by alexbusu** [comment]
There is one issue though (I came across it implementing this feature with php in a _batch loader_ function). When using _LIMIT_ this feature cames hard to deal with. Maybe it could ignore the **limit** parameter at query time and then return a LimitIterator for each `referenceModel` input value, or, easier, to fallback to the current flow (a query for each entry).

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
