### ISSUE TITLE
getPaginate() in Phalcon/Paginator/Adapter problem with Autocomplete in IDE's

### ISSUE THREAD

**Issue by nadorator** [phalcon/cphalcon#13280]
I would like to have a proper object returning from getPaginate like a PaginatorItem classes for exemple instead I get a stdClass with the required fields. Then I would have the aucompletion working in phpStorm for example when doing:

```php
/** var PaginatorItems $pageItems
$pageItems=$myQueryBuilders->getPaginate(
[
                "builder" => $builder,
                "limit"   => $elementsPerPage,
                "page"    => $pageNumber
            ]
);
```
I could have autocomplete when typing things like:

```php
$pageItems->before
```

It would also be better to have a defined class instead of a std class for that result.

### Details

* Phalcon version: 3.3.1
* PHP Version: 7.0.27.0
* Operating System: Debian 9.3
* Installation type: installing via package manager
* Server: Apache 2.4

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

**Comment by nadorator** [comment]
Ok So I'll add a Pagination class and an extension to the Paginator class in the incubator project then if had understood.
