### ISSUE TITLE
\Phalcon\Mvc\Controller to allow constructor parameters

### ISSUE THREAD

**Issue by ricardovsilva** [phalcon/cphalcon#13299]
It would be great if Phalcon controllers accepts dependencies through injection.
I'm facing problem similar to #2186, but in my case is to mock and do some unit tests just using phpunit. I know that Phalcon has a way to configure DI, but it's too much overload and boilerplate to do a simple test.

For example, if I have some foo controller I cannot inject dependency to simple unit test like below:
```php
class FooController extends Controller
{
    public function __construct($barRepository)
    {
        parent::__construct();
        $this->barRepository = $barRepository;
    }

    public function fooWantToReceiveNews($fooId)
    {
        return $this->barRepository->wantToReceiveNews($fooId);
    }
}
```
```php
class BarRepositoryStub
{
    public function __construct($enabledUserIds)
    {
        $this->enabledUserIds = $enabledUserIds;
    }

    public function wantToReceiveNews($userId)
    {
        return in_array($this->userId, $this->enabledUserIds);
    }
}
```
```php
class FooControllerTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        $enabledUserIds = [0, 1];
        $barRepository = new BarRepositoryStub($enabledUserIds);
        $this->fooController = new fooController($barRepository);
    }
}
```

Is there any good reason that I'm not seeing to make Controller final?

**Comment by Ark4ne** [comment]
I think the reason the constructor is final is that the dispatcher will not be able to transmit the desired build parameters.

This is why we must use the injection of dependence, and the injection of configuration, for this:

```php
$di->set(BarRepositoryStub::class, function(){
  return new BarRepositoryStub($this->config->repositories->bar->userIds);
})

class BarRepositoryStub {
    public function __construct($enabledUserIds)
    {
        $this->enabledUserIds = $enabledUserIds;
    }

    public function wantToReceiveNews($userId)
    {
        return in_array($this->userId, $this->enabledUserIds);
    }
}

class FooController extends Controller
{
    public function onConstruct()
    {
        $this->barRepository = $this->di->get(BarRepositoryStub::class);
    }

    public function fooWantToReceiveNews($fooId)
    {
        return $this->barRepository->wantToReceiveNews($fooId);
    }
}

class FooControllerTest extends \PHPUnit_Framework_TestCase
{
    public function testFooWantToReceiveNews()
    {
        $mockBarRepository = $this->createMock(BarRepositoryStub::class);
        $mockBarRepository
           ->expects($this->once())
           ->method('wantToReceiveNews')
           ->with([0, 1])
           ->willReturn([123]);

        $di = \Phalcon\Di::getDefault();
        $di->setShared(BarRepositoryStub::class, $mockBarRepository);

        $enabledUserIds = [0, 1];
        $fooController = new fooController();

        $this->assertEquals([123], $fooController->fooWantToReceiveNews($enabledUserIds));
    }

    public function tearDown(){
        \Phalcon\Di::reset();
   } 
}
```

There are other solutions but that's what I'll do.

**Comment by ricardovsilva** [comment]
@Ark4ne about the test, your example works. But with controller as final I always have to set the DI in tests, that requires some boilerplate.

In my opinion, controller tests could be cleaner and even use the $di. Also, with injection through constructor approach, my controller could be totally decoupled of $di and even know it's existence.

An example of test code would be:
```php
public function testFooWantToReceiveNews()
    {
        $mockBarRepository = $this->createMock(BarRepositoryStub::class);
        $mockBarRepository
           ->expects($this->once())
           ->method('wantToReceiveNews')
           ->with([0, 1])
           ->willReturn([123]);

        $enabledUserIds = [0, 1];
        $fooController = new fooController($mockBarRepository);

        $this->assertEquals([123], $fooController->fooWantToReceiveNews($enabledUserIds));
    }
```

**Comment by Ark4ne** [comment]
@ricardovsilva You're absolutely right, it would be much simpler if you could use the controller's constructor.

Does anyone know the benefit of the final constructor and the use of `onConstruct` methods?

**Comment by sergeyklay** [comment]
Final methods faster in Zend Engine. At least using Zephir implementation. Anyway you are free to create your own base controller and imlement controller inerface.

**Comment by ricardovsilva** [comment]
@sergeyklay Sorry for my lack of knowledge, but don't makes sense to me that a final class is faster. Do you have any benchmark or can point to docs that explains that behavior?

**Comment by Ark4ne** [comment]
@sergeyklay Thanks for your answer !
@ricardovsilva logically, I would say that the fact that the function is final will change the compilation, since the method will be "locked", a higher level compilation can be made, and thus get better performance.

**Comment by ricardovsilva** [comment]
But this performance improvement is relevant? It's really exists? I googled it since @sergeyklay answer and found nothing even in zephir documentation or zend docs. Also I never saw this behavior in other pre-compiled languages (like C#).
Make class final, and consequently the constructor, is a huge downside only to get some performance (minor or major) improvement. And I'm not convinced about this performance improvement at all. Any refeer will be really welcome to clarify this assumption.

**Comment by dgmike** [comment]
I believe the reason why Phalcon does not [recommend](https://github.com/phalcon/docs/blob/3.3/en/controllers.md/#initializing-controllers) the use of constructor is not due to the performance factor but the organization of the code.

There is a discussion on stackoverflow about this subject - it is related to ZendFramework, but I believe it applies to the case. https://stackoverflow.com/a/8210930

> I think the main reason for me is that it stops other developers from fiddling. You can do anything with init() but not with __construct() as this needs to run correctly with all the correct params in place. 
> -- Jake N

You can use `initialize` or `onConstruct` methods - checkout the [documentation](https://github.com/phalcon/docs/blob/3.3/en/controllers.md/#initializing-controllers).

About tests, I recommend check the [tutorial](https://docs.phalconphp.com/ar/3.2/unit-testing) about tests and how to setup dependency injection using `Phalcon\Test\UnitTestCase`.

Need to make some tests but I think it can be so clean as expected using something like...

```php
$mockStorageInstance = new Mock(Storage::class);
$this->getDi()->set('storage', $mockStorageInstance);

$controller = $this->getDi()->get('UserController');
// or
$controller = new Controller(); // inside, uses defaultDi.
```

**Comment by ricardovsilva** [comment]
@Mike there is some downsides in your approach that can be simple solved by allowing to override constructor.
- I cannot treat my controller as simple object;
- I have to configure an entire DI container just to do a simple unit test;
- Service locator pattern, already declared as anti pattern by majority of community (you can see Martin Fowler opinion with a referral to a post that explains better why https://twitter.com/martinfowler/status/938178363340066816?s=20)
- Zend uses the approach of "I do not recommend but you can do". I'm the architect of my system and I know what fits me better, the framework should be a tool and not limit me.
- My controller should never know about the existence of a DI container, it should be transparent.

I believe that unit tests should be as simple as possible, and the needs to configure a dependency injection container just to test something looks very wrong to me.
Another point is that my test can be the live docs of my code. If I inject mock through a pre-configured service locator I will cannot:
- Check if my mock was called or not;
- Look to the test and see "Oh, my controller use FooService and BarService. In a given condition FooService should never be call" because it is hidden by DI;

I don't think that the argument of "I'm doing this to avoid programmers that use my framework do some mess" is valid. We, as community, should educate and bring light to doubts, not only hide.

All the points above can be simple solved by not making Controller final.

And @sergeyklay yeah, I can implement my own Controller, but it's really necessary only to remove final of class?

**Comment by dgmike** [comment]
@ricardovsilva I wrote in my last message about how the Phalcon works and what is the proposed solution for the problem. I was not saying Phalcon uses the right solutions.

I made some tests and I was able to write something like this:

```php
<?php

use Phalcon\Mvc\Controller;

class EasyController extends Controller
{
  protected $injected = 'original';

  public function indexAction()
  {
    return $this->injected;
  }

  public function onConstruct()
  {
    print 'FROM onConstruct' . PHP_EOL;
  }

  public function initialize(Person $person = null)
  {
    print 'FROM INITIALIZE' . PHP_EOL;
  }
}
```

And the follow code (aka test):

```php
$c = new EasyController;
var_dump($c->indexAction());
```

And this is the output:

```
FROM onConstruct
string(8) "original"
```

So, the `Phalcon\Mvc\Controller::__constructor()` do not calls `initialize()` method. So you can use the initialize as your `__constructor()` / dependency injector method. The constructor _maybe_ makes some setup stuffs on object and it's not recomended to use it (I still don't know the really why). You can use the `onConstruct()` method to do this.

Look, I'm not saying Phalcon is correct or uses the most new design patterns. I'm just telling what you can do to solve your problem immediately.

If Phalcon must change to adapt to more recommended design patterns, this is another history....

**Comment by ricardovsilva** [comment]
@dgmike thank you for clarification. I opened this issue to discuss and find the best solution for phalcon. None framework uses all the best solutions, and they are all improving day by day. I believe that phalcon also can.
I would love to remove the final from controller constructor and open a PR.

**Comment by virgofx** [comment]
The reason it was designed that way was to reuse controllers for dispatchers. IT won't be removed. In 4.0.0 the order will be reversed where `initialize()` will come before `beforeExecuteRoute()` if you check dispatcher code. All initialization should be done inside `initialize()` AT that time.
