### ISSUE TITLE
[NFR] Allow size parameter for datetime and timestamp columns

### ISSUE THREAD

**Issue by robin-rozo** [phalcon/cphalcon#13297]
When I want to add a size parameter to a column definition, the size is not added in the generated query. This size is mandatory in MySQL to create columns with fractionnal time values [see doc](https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html).

**Comment by niden** [comment]
@robin-rozo Do you happen to have an example or a small code snippet handy?

**Comment by niden** [comment]
Actually I think I got it.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14654
