### ISSUE TITLE
Implicit Transactions during relation is interrupting my db operations

### ISSUE THREAD

**Issue by sm0nster** [phalcon/cphalcon#13305]
### Actual Behavior

I was updating two models using relation and during the save operation, an (irrelevant) error occured and didn't show up in my logger.
After some debbuging I found out there's an Implicit Transaction going (from saving model with relation) and that's why my error logger isn't working,

```php
try {
    ...
    $entity->relation = $relationEntity;
    $entity->save();
} catch (\Throwable $e) {
    // log an exception in db <- not working
}
```

### Expected Behavior
I would like the error to be saved in the database ;)

### Details
* Phalcon 3.2.0
* PHP Version: 7.1.11
* Server: Apache

**Comment by Zaszczyk** [comment]
Confirm, I occured same issue.

**Comment by Zaszczyk** [comment]
It is still occuring.
