### ISSUE TITLE
Request filter not filtering (int) properly

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#13309]
This isn't a bug, but an issue with the documented and actual behaviour.

When filtering a request variable:

```php
$this->request->getPost('barcode','int');
```
one would expect the result of that to be an integer, or at least an integer-like string.  Casting to (int) would do the trick, but the filter just strips out non-integer characters.

So a POSTed variable of `-------234---34-888833--------------` would pass through.  That is clearly not an integer.

**Comment by andrew-demb** [comment]
Phalcon uses PHP `filter_var()` function with flag `FILTER_SANITIZE_NUMBER_INT` to sanitize integer values. So, this is PHP behaviour.

```php
echo filter_var('-------234---34-888833--------------', FILTER_SANITIZE_NUMBER_INT);
// -------234---34-888833--------------
```

**Comment by quasipickle** [comment]
Ah, I see.  I still propose this be changed to casting to an integer.  In my brain, this
```php
$this->request->getPost('barcode','int');
```
means "give me an integer representation of the string", not "give me a string with only integer-type characters in it".

**Comment by andrew-demb** [comment]
Use `int!` to force cast. It will use `intval()`, and result for your data is 0, but it responsible for casting

**Comment by quasipickle** [comment]
Thanks for that information.  I'm aware how to get around the issue, but that doesn't mean I believe it to still be an issue.  It's semantically misleading.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/docs#1595
