### ISSUE TITLE
[NFR] Websockets

### ISSUE THREAD

**Issue by oscarmolinadev** [phalcon/cphalcon#13301]
Add support for create websocket server/client. I don't know if it is better create a wrapper for ReactPHP (temporary) like Beanstalkd or create from scratch without dependencies and take advandtage of performance of c-exstension.

**Comment by Jurigag** [comment]
To be honest - no point, since there are already projects like this, even in c. Phalcon is MVC framework for HTTP based protocol. If you need websocket server/client in c as extension then go for swoole.

**Comment by oscarmolinadev** [comment]
Thanks @Jurigag  I didn't know of existence of swoola :) I tested and it is easy to install and easy to build anything 👍 Maybe I'll create a wrapper for incubator.

For me it can be closed.

oscarmolinadev
