### ISSUE TITLE
no dll in release archive  phalcon_x64_vc15_php7.2.0_.zip

### ISSUE THREAD

**Issue by alexandrufulop** [phalcon/cphalcon#13318]
### Expected and Actual Behavior

> Expecting to find the php_phalcon.dll file in the phalcon_x64_vc15_php7.2.0_.zip archive.

> There is no other file besides the README in the phalcon_x64_vc15_php7.2.0_.zip archive.

[https://github.com/phalcon/cphalcon/releases/tag/v3.3.2](https://github.com/phalcon/cphalcon/releases/tag/v3.3.2)

### Details

I could not find any dll extensions in https://github.com/phalcon/cphalcon/releases/download/v3.3.2/phalcon_x64_vc15_php7.2.0_.zip

Thank you!

**Comment by JABirchall** [comment]
haha, @sergeyklay ya missed one.

@alexandrufulop just use 3.3.1 for now, unless that release is also just a license.txt

**Comment by sergeyklay** [comment]
Fixed:[ phalcon_x64_vc15_php7.2.0_3.3.2.zip](https://github.com/phalcon/cphalcon/releases/download/v3.3.2/phalcon_x64_vc15_php7.2.0_3.3.2.zip).  Thank you for the report.

**Comment by alexandrufulop** [comment]
Thank you for your effort!
