### ISSUE TITLE
Event handlers should be also possible to be callable not just closures

### ISSUE THREAD

**Issue by pwilkowski** [phalcon/cphalcon#13322]
https://github.com/phalcon/cphalcon/blob/master/phalcon/events/manager.zep

Why Event handlers must be objects (ie. Closures)? It should be perfectly fine if event handlers would also be a callable as one of your comments says:

```php
	/**
	 * Attach a listener to the events manager
	 *
	 * @param string eventType
	 * @param object|callable handler
	 * @param int priority
	 */
	public function attach(string! eventType, var handler, int! priority = 100)
	{
...
	}
```
Yet the first check in the function is:

```php
		if typeof handler != "object" {
			throw new Exception("Event handler must be an Object");
		}
```
### Details

* Phalcon version: 3.2.4 (but it is present in master branch at this moment as well)
* PHP Version: 7.0.0
* Operating System: Windows
* Installation type: From release page
* Server: Nginx and Apache

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15045
