### ISSUE TITLE
Query builder "alias" parameter

### ISSUE THREAD

**Issue by Xerphis** [phalcon/cphalcon#13328]
Hi.

Let us assume a simple situation in which, for example, we want get "articles" by referring to the model and using the built-in "find" method. Morover, for the "articles" we would like to include the model of the "authors" of the article.

### Actual Behavior
In this situation, the code would look like:
```php
$articeles = \Models\ArticlesModel::find([
    'joins' => [
        'Models\Authors',
        'author.id = [Models\Articles].fk_author',
        'author',
        'inner'
    ],
	'columns' => [
        '[Models\Correspondences].*',
		'author.*'
    ],
]);
```

I understand that we can also use the "createBuilder" method from the shared "modelsManager" service and use the parameter "models", but then we do not refer to the selected model class. I would still like to use the model class and the "find" method.

Unfortunately, in this situation, the main model we refer to appears in the object  "models\Articles". Object of result shows:
```
Object Phalcon\Mvc\Model\Row (
->models\Articles (public) = Object Models\Articles extends Abstr\Models\AbstractArticles (
     Models\Articles methods: (98) (
       ->initialize();
       ->validation();
       ->setId();
 	  ...
 ->author = Object Models\Authors extends Abstr\Models\AbstractAuthors (
     Models\Authors methods: (98) (
       ->initialize();
       ->validation();
       ->setId();
 	  ...
 )
```

It is not easy to appeal to him because it would be necessary to use:
```php
$articles->getFirst()->{'models\Articles'};
```
In addition, you probably can not refer from the Volt template in this way.

### Expected Behavior
In this situation, it would help to add the "alias" parameter to the builder. This parameter would be used as an alias for the main model to which we refer. In this way, it would replace "models\Articles" with the definition of "articles". For example:

```php
$articeles = \Models\ArticlesModel::find([
    'alias' => 'article',
    'joins' => [
        'Models\Authors',
        'author.id = [Models\Articles].fk_author',
        'author',
        'inner'
    ]
	...
]);
```
Result:
```
 Object Phalcon\Mvc\Model\Row (
 ->article = Object Models\Articles extends Abstr\Models\AbstractArticles (
     Models\Articles methods: (98) (
       ->initialize();
       ->validation();
       ->setId();
 	  ...
 ->author = Object Models\Authors extends Abstr\Models\AbstractAuthors (
     Models\Authors methods: (98) (
       ->initialize();
       ->validation();
       ->setId();
 	  ...
 )
```

I was able to overwrite the built-in method "getPreparedQuery". Works as it should. The zephir method would look like this:
```zep

	/**
	 * shared prepare query logic for find and findFirst method
	 */
	private static function getPreparedQuery(var params, var limit = null) -> <Query> {
		var builder, bindParams, bindTypes, transaction, cache, manager, query, dependencyInjector;

		let dependencyInjector = Di::getDefault();
		let manager = <ManagerInterface> dependencyInjector->getShared("modelsManager");

		/**
		 * Builds a query with the passed parameters
		 */
		let builder = manager->createBuilder(params);
		
		if isset params["alias"] {
			builder->from([params["alias"] => get_called_class()]);
		} else {
			builder->from(get_called_class());
		}

		if limit != null {
			builder->limit(limit);
		}

		let query = builder->getQuery();
		
		...
```

### Details
* Phalcon version:
> Web framework delivered as a C-extension for PHP
> phalcon => enabled
> Author => Phalcon Team and contributors
> Version => 3.3.1
> Build Date => Jan  8 2018 16:44:47
> Powered by Zephir => Version 0.10.7-2917ebe8ae
> 
> Directive => Local Value => Master Value
> phalcon.db.escape_identifiers => On => On
> phalcon.db.force_casting => Off => Off
> phalcon.orm.events => On => On
> phalcon.orm.virtual_foreign_keys => On => On
> phalcon.orm.column_renaming => On => On
> phalcon.orm.not_null_validations => On => On
> phalcon.orm.exception_on_failed_save => Off => Off
> phalcon.orm.enable_literals => On => On
> phalcon.orm.late_state_binding => Off => Off
> phalcon.orm.enable_implicit_joins => On => On
> phalcon.orm.cast_on_hydrate => Off => Off
> phalcon.orm.ignore_unknown_columns => Off => Off
> phalcon.orm.update_snapshot_on_save => On => On
> phalcon.orm.disable_assign_setters => Off => Off

* PHP Version:
> PHP 7.1.9 (cli) (built: Aug 30 2017 18:34:46) ( ZTS MSVC14 (Visual C++ 2015) x64 )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

* Operating System: Windows 10 64-bit
* Installation type:  installing via package manager
* Server: Apache

**Comment by sergeyklay** [comment]
@Xerphis Could you please send a patch?

**Comment by sergeysviridenko** [comment]
@sergeyklay `mvc/model.zep`
