### ISSUE TITLE
php 7.2.3 fpm start with segment fault

### ISSUE THREAD

**Issue by ideamean** [phalcon/cphalcon#13329]
php version:
=======================================================
PHP 7.2.3 (cli) (built: Mar 19 2018 16:13:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies

bin/php --ri phalcon
============================
phalcon
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.4
Build Date => Mar 20 2018 15:13:44
Powered by Zephir => Version 0.10.4-11e39849b0

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

**when start php-fpm there is error:**
================================
service php-fpm start
Starting php-fpm /etc/init.d/php-fpm: line 53:  8211 Segmentation fault      $php_fpm_BIN --daemonize $php_opts
 failed

gdb php-fpm
==================================

[Thread debugging using libthread_db enabled]
Detaching after fork from child process 7210.

Program received signal SIGSEGV, Segmentation fault.
zend_hash_destroy (ht=0x1777c30) at /root/soft/php-7.2.3/Zend/zend_hash.c:1247
1247							zend_string_release(p->key);
Missing separate debuginfos, use: debuginfo-install GeoIP-1.6.5-1.el6.x86_64 boost-system-1.41.0-28.el6.x86_64 bzip2-libs-1.0.5-7.el6_0.x86_64 cyrus-sasl-gssapi-2.1.23-15.el6_6.2.x86_64 cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64 cyrus-sasl-plain-2.1.23-15.el6_6.2.x86_64 db4-4.7.25-22.el6.x86_64 freetype-2.3.11-17.el6.x86_64 glibc-2.12-1.209.el6_9.2.x86_64 gmp-4.3.1-12.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libcurl-7.19.7-53.el6_9.x86_64 libgcc-4.4.7-18.el6.x86_64 libgcrypt-1.4.5-12.el6_8.x86_64 libgearman-1.1.8-2.el6.x86_64 libgpg-error-1.7-4.el6.x86_64 libidn-1.18-2.el6.x86_64 libjpeg-turbo-1.2.1-3.el6_5.x86_64 libpng-1.2.49-2.el6_7.x86_64 libselinux-2.0.94-7.el6.x86_64 libssh2-1.4.2-2.el6_7.1.x86_64 libstdc++-4.4.7-18.el6.x86_64 libuuid-2.17.2-12.28.el6_9.2.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64 libxslt-1.1.26-2.el6_3.1.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 net-snmp-libs-5.5-60.el6.x86_64 nspr-4.13.1-1.el6.x86_64 nss-3.28.4-3.el6_9.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 nss-util-3.28.4-1.el6_9.x86_64 openldap-2.4.40-16.el6.x86_64 openssl-1.0.1e-57.el6.x86_64 readline-6.0-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64

**Comment by sergeyklay** [comment]
@ideamean Could you please provide a full backtrace?

**Comment by ideamean** [comment]
how to get a full backtrace?

**Comment by sergeyklay** [comment]
Please follow this guide to understand how to generate the backtrace.

+ https://bugs.php.net/bugs-generating-backtrace.php
+ http://bugs.php.net/bugs-generating-backtrace-win32.php

**Comment by ideamean** [comment]
thks your help. when I reinstall php-7.2.3 with install phalcon 3.2.4, it's everything goes well. I'm not sure if it is cause of the other extension. I forgot backup the problem php-7.2.3 version, so I can't cacth the backtree now.  If it  reappear the problem, I will catch the backtree as soon as possible.
what a pity!

**Comment by sergeyklay** [comment]
I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks
