### ISSUE TITLE
Proposal: ability to add Route object directly into Router

### ISSUE THREAD

**Issue by webmasterlv** [phalcon/cphalcon#13326]
First of all, thank you for work you've done, this is outstanding framework.
While developing my application routing structure, one particular feature would be useful - if i could pass Route object directly into Router instance. This way by extending Route object it is would be possible to attach some additional data to object and use it somewhere else in application.
As i understand, this shouldn't break BC, because internally Router stores them as Route objects already.
This could be like:

```
class CustomRoute extends Phalcon\Mvc\Router\Route {

}

$route = new CustomRoute();

$router = new Phalcon\Mvc\Router();
$router -> add($route);
```

**Comment by sergeyklay** [comment]
Implemented in the `3.4.x` branch. Thank you for contributing.
