### ISSUE TITLE
MySQL - Models update problem with BIGINT

### ISSUE THREAD

**Issue by HACKHERS** [phalcon/cphalcon#13320]
### Expected and Actual Behavior
Simply when I try to update UNSIGNED BIGINT (I tried signed too) value, relevant column sets to **0**.  I checked metadata cache for it. Surprisingly BIGINT columns saved as type 1 (which is `TYPE_DATE`) instead of **14** (`TYPE_BIGINTEGER`). I tried BIGINT with Annotations strategy too, same result.

```php
        $coin = Coins::findBySymbol("XRP")->getFirst();
        $coin->save([
            "supply" => 38305873865
        ]); // result = 0

        $update = $this->db->query("UPDATE coins SET supply = 38305873865 WHERE symbol = 'XRP';");
        $update->execute(); // result = 38305873865
```
Result of table describe: 
![image](https://user-images.githubusercontent.com/2204282/37262544-bec256be-25b4-11e8-9b50-e5fd814841e6.png)

Metacache[9]:
```
    'id' => 1,
    'symbol' => 2,
    'name' => 2,
    'logo' => 2,
    'logo_small' => 2,
    'change_value' => 32,
    'change_ptc' => 32,
    'open' => 32,
    'low' => 32,
    'high' => 32,
    'supply' => 1, // BIGINT
    'market_cap' => 1, // BIGINT
    'volume' => 1, // BIGINT
    'volume_ccy' => 2,
    'last_time' => 2,
    'active' => 1,
    'proof_type' => 2,
    'website' => 2,
    'twitter' => 2,
    'description' => 2,
    'features' => 2,
    'seo_title' => 2,
    'seo_description' => 2,
    'tech' => 2,
    'total_supply' => 1,
    'price' => 32,
    'post_count' => 1,
    'featured' => 1,
```

___
### Annotations: 

```
    /**
     *
     * @var biginteger
     * @Column(column="supply", type="biginteger", length=20, nullable=true)
     */
    public $supply;
```

Note: When I update the metadata cache It works just fine. (bigint fields 1 to 14)

### Details
* Phalcon version: 3.3.2
* PHP Version: 7.2.2
* Operating System: Windows 10
* Installation type: DLL
* Zephir version (if any): 0.10.7-2917ebe8ae
* Server: Apache
* Other related info (Database, table schema): MySQL

**Comment by 41646F6C666F** [comment]
I'm working with bigints and get some issues on updates too.
