### ISSUE TITLE
Allow to disable transaction rollback exception

### ISSUE THREAD

**Issue by chilimatic** [phalcon/cphalcon#13324]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior
a manual rollback always results in an exception that needs to caught.

as an Example
```php
   } catch (\Exception $e) {
            $this->logThrowable($e);
            if ($transaction && $transaction->isValid()) {
                try {
                    $transaction->rollback();
                } catch (\Phalcon\Mvc\Model\Transaction\Failed $e) {
                    // this behaviour is irrelevant since we did it on purpose
                }
            }
        }
```
this is makes sense to some degree. But In my case it's just annoying and cluttering the application. 

the suggested change would be in the transaction.zep
```zephir
....
    protected _throwExceptionOnRollback { get };
....

	/**
	 * Phalcon\Mvc\Model\Transaction constructor
	 */
	public function __construct(<DiInterface> dependencyInjector, boolean autoBegin = false, string service = null)
	{
.....
		let this->_messages = [];
		let this->_throwExceptionOnRollback = true;
......
	}
.....


	/**
	 * Rollbacks the transaction
	 */
	public function rollback(rollbackMessage = null, <ModelInterface> rollbackRecord = null) -> boolean
	{
.......
		if connection->rollback() {
			if !rollbackMessage {
				let rollbackMessage = "Transaction aborted";
			}
........
		        if this->_throwExceptionOnRollBack != false {
                                throw new TxFailed(rollbackMessage, this->_rollbackRecord);
		        }
.........
       public function setThrowExceptionOnRollback(boolean throwExceptionOnRollback) {
	    let this->_throwExceptionOnRollback = throwExceptionOnRollback;
	}
}
```

This would maintain the default behaviour but allows the option to disable the transaction rollback exception contextualized. 

> **Describe what you are trying to achieve and what goes wrong.**

The goals is that for example a chained batch that fails in 1 case does not abort the whole process.
and less "clutterting" in the code.

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

> Provide minimal script to reproduce the issue

```php

$di = new \Phalcon\DI\FactoryDefault();

$di->set(SERVICE_DB, function () use ($config, $di) {
    $db = new \Phalcon\Db\Adapter\Pdo\Mysql([
        'host' => 'localhost',
        'username' => 'my-user',
        'password' => 'something',
        'port' => '3306',
        'dbname' =>'my-db',
    ]);

    $db->query('set names utf8');
    return $db;
}

$transaction = new Transaction($di);
$transaction->begin();
$transaction->rollback();

```
### Details

* Phalcon version: (`php --ri phalcon`) current 3.3.x 
* PHP Version: (`php -v`) 7.1 (irrelevant)
* Operating System: arch
* Installation type: Compiling from source || installing via package manager compiled
* Zephir version (if any): lastest
* Server: Nginx
* Other related info (Database, table schema): non relevant it's a software behaviour

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14053
