### ISSUE TITLE
ORM Model bug

### ISSUE THREAD

**Issue by reanx** [phalcon/cphalcon#13335]
I've created a model using phalcon-devtools, later I've removed some fields from the model. I'm using that model under a controller to insert some data. In the insertion part I didn't remove that fields which I removed from the model. I'm setting value for it. When I'm creating it actually inserting the data without showing any errors or warning even that field is not in the model. Is this a normal behaviour?

**Comment by trentramseyer** [comment]
I would recommend using the Whitelist param to select which values you can set.  If you did not protect the variables in the model and use getters/setters then they are able to be set.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
