### ISSUE TITLE
[NFR] Phalcon\Assets - Subresource Integrity

### ISSUE THREAD

**Issue by nask0** [phalcon/cphalcon#13333]
I think it would be good idea to add support for [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to Phalcon\Assets when working with local assets.
For remote loaded assets, currently this can be achieved by setting 'attributes' parameter to addJs()/addCss() functions:
```php
$cssFilter = new Phalcon\Assets\Filters\Cssmin();
$this->assets
    ->collection('headerCss')
    // ...
    ->addCss(
        'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
        false,
        false,
        [
            'integrity'=> 'sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u',
            'crossorigin' => 'anonymous'
        ]
);
```

It would be nice if Assets Manager can calculate and add this attribute to local resources automatically or when some flag is set, for example:
```php
$assetsManager
    |
    ->collection('headerCss')
    ->setTargetPath( 'css/header.css' ) // resources/ is prefixed here
    ->setTargetUri( 'resources/css/header.css' )
    ->addFilter( new Phalcon\Assets\Filters\Cssmin() )
    ->join( true )
    ->integrity( true ) // calculate script integrity
    ->setIntegrityHash(  'sha512' ) // optional, can have some default value like 'sha384'
    ->addCss( 'css/style.css'  )
    ->addCss( 'css/menu.css'  )
    ->addCss( '...'  )
```

### Details

* Phalcon version: 
```
Version => 3.3.2
Build Date => Mar 21 2018 12:36:41
Powered by Zephir => Version 0.10.7-2917ebe8ae
```
* PHP Version: 
```
PHP 7.1.15 (cli) (built: Feb 28 2018 11:19:18) ( NTS )
```
* Operating System: Fedora release 27 (Twenty Seven)
* Installation type: compiling from source
* Zephir version: 0.10.7-2917ebe8ae
* Server: Apache/2.4.29

**Comment by nask0** [comment]
Hello guys, any updates on this? 
Is it implemented or we should close the issue?

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
