### ISSUE TITLE
Slow Benchmarks with: $response->setStatusCode(200,  "OK");

### ISSUE THREAD

**Issue by trentramseyer** [phalcon/cphalcon#13339]
Running  AB benchmarks against system with and without 
$response->setStatusCode(200,  "OK");

WITHOUT, just using php's header() to set status code:
Requests per second:    593.90 [#/sec] (mean)
Time per request:       168.377 [ms] (mean)

WITH
Requests per second:    17.44 [#/sec] (mean)
Time per request:       5733.279 [ms] (mean)

This is Phalcon 3.3.1  - Happened on 3.1.x as well
PHP 7.0.28-0ubuntu0.16.04.1

Not sure why it would cause benchmarks to not like that command, but it slows down quite a bit
ab -c 100 -n 1000  ((url))

**Comment by sergeyklay** [comment]
@trentramseyer Could you please provide PHP version? Also did you test [latest stable](https://github.com/phalcon/cphalcon/releases/latest) Phalcon?

**Comment by trentramseyer** [comment]
Phalcon DevTools (3.2.5)

Environment:
  OS: Linux NewContent 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
  PHP Version: 7.0.28-0ubuntu0.16.04.1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.0
  PHP Extension Dir: /usr/lib/php/20151012
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.0/cli/php.ini
Versions:
  Phalcon DevTools Version: 3.2.5
  Phalcon Version: 3.2.2
  AdminLTE Version: 2.3.6



I create a Project using Devtools.  I updated the IndexController to 

`$response = new \Phalcon\Http\Response();

		$response->setStatusCode(200, "OK");
		$response->setContent("<html><body>Hello!</body></html>");

		
		$response->send();
		exit();`

Run AB test against it with and without the response code line !

**Comment by trentramseyer** [comment]
This is with the code in 

Requests per second:    926.57 [#/sec] (mean)
Time per request:       107.925 [ms] (mean)
Time per request:       1.079 [ms] (mean, across all concurrent requests)
Transfer rate:          180.07 [Kbytes/sec] received


this is without

Total transferred:      196000 bytes
HTML transferred:       32000 bytes
Requests per second:    17.66 [#/sec] (mean)
Time per request:       5661.626 [ms] (mean)
Time per request:       56.616 [ms] (mean, across all concurrent requests)
Transfer rate:          3.38 [Kbytes/sec] received


I noticed TECHEMPOWER's Benchmarks had that line in and Phalcon on their last benchmarks was "running as slow as Laravel and Symfony" ....    However their Micro Phalcon was blazing fast and it did not include that.

**Comment by sergeyklay** [comment]
I'll take a look

**Comment by wajdijurry** [comment]
See this also
https://github.com/phalcon/cphalcon/issues/13471

**Comment by ruudboon** [comment]
Closing this one. We can reopen this if we find performance issues regarding v4
