### ISSUE TITLE
ORM bug - search by primary key

### ISSUE THREAD

**Issue by zvonchuk** [phalcon/cphalcon#13336]
### Expected and Actual Behavior

When searching for a record by primary key equal to false,  then ORM simply selects the first record from the table.
I think it would be more logical if ORM returned an error. 

> Provide minimal script to reproduce the issue

```php
$clientId = false;
$client   = (new \CRM\Client\Client)::findFirst ($clientId);
print_r($client->toArray());
```

Responce:
![image](https://user-images.githubusercontent.com/3234413/38018618-76bcdb26-3286-11e8-8bbf-02468d948fe2.png)

### Details

* Phalcon version:  3.3.1
* PHP Version: PHP 7.1.13-1+0~20180105151310.14+jessie~1.gbp1086fa
* Operating System: Debian GNU/Linux 8
* Installation type: installing via package manager
* Zephir version (if any): 0.10.7-2917ebe8ae
* Server: nginx/1.12.2 
* Other related info (Database, table schema):  
mysql  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (x86_64) using readline 6.3
ENGINE=InnoDB

```
CREATE TABLE `client_base` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=611788 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by JABirchall** [comment]
Agreed, If the paramiter passed is not null the orm should throw an exeption
While maintaining expected behavour if no value is passed or null to fetch the first row.

**Comment by niden** [comment]
This has been addressed
