### ISSUE TITLE
Invalid callback error in Phalcon\Mvc\Dispatcher::_throwDispatchException

### ISSUE THREAD

**Issue by fragag03** [phalcon/cphalcon#13340]
Since we upgraded to PHP 7.0 and Phalcon 3.3.x I'm always getting the following error when my dispatcher try to throw an exception:

> Invalid callback Phalcon\Mvc\Dispatcher\Exception::__construct, cannot access protected method Phalcon\Mvc\Dispatcher\Exception::__construct()

To be sure it was not my project's code which was interfering with the Exception class, I tried an helloWorld project (https://github.com/markopo/phalcon-helloworld) and get the error when I call a route that has no controller.

Here is the complete output of the error:

> Warning: Invalid callback Phalcon\Mvc\Dispatcher\Exception::__construct, cannot access protected method Phalcon\Mvc\Dispatcher\Exception::__construct() in /mnt/svn_dev_100g/fragag03/phalcon_test/public/index.php on line 44
> object(RuntimeException)#37 (7) { ["message":protected]=> string(41) "Call to undefined method ::__construct()" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(56) "/mnt/svn_dev_100g/fragag03/phalcon_test/public/index.php" ["line":protected]=> int(44) ["trace":"Exception":private]=> array(3) { [0]=> array(4) { ["function"]=> string(23) "_throwDispatchException" ["class"]=> string(22) "Phalcon\Mvc\Dispatcher" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(45) "TestController handler class cannot be loaded" [1]=> int(2) } } [1]=> array(4) { ["function"]=> string(8) "dispatch" ["class"]=> string(18) "Phalcon\Dispatcher" ["type"]=> string(2) "->" ["args"]=> array(0) { } } [2]=> array(6) { ["file"]=> string(56) "/mnt/svn_dev_100g/fragag03/phalcon_test/public/index.php" ["line"]=> int(44) ["function"]=> string(6) "handle" ["class"]=> string(23) "Phalcon\Mvc\Application" ["type"]=> string(2) "->" ["args"]=> array(0) { } } } ["previous":"Exception":private]=> NULL } PhalconException: Call to undefined method ::__construct()

### Details

* Phalcon version: 3.3.2
* PHP Version: 7.0.27-0+deb9u1
* Operating System: Linux Debian 9.4
* Installation type: Compiled from source
* Zephir version (if any): Version 0.10.7-2917ebe8ae
* Server: Apache with PHP-FPM

**Comment by fragag03** [comment]
Anybody else can't get their dispatcher to throw exception on their php7-Phalcon3.3.2 setup?

**Comment by virgofx** [comment]
Lots of us are using PHP7.x with no issues. You'll need to provide relevant sections for how your bootstrapping the relevant sources (`router`, `dispatcher`) and other view related sections. Essentially, help us reproduce the issue because the error above is saying the issue is in your code; however, the exception text is coming from elsewhere.

**Comment by fragag03** [comment]
I'm pretty sure it's not my code because I'm having the issue with the tutorial bootstrap. It's pretty simple to reproduce (on my setup at least...)

1. Get a linux apache-php7.0-Phalcon3.3.2 server
2. make yourself the simplest bootstrap file (tutorial one is fine https://docs.phalconphp.com/en/3.3/tutorial-base). You only need this and the .htaccess files.
3. open a browser, type http://{myserver}/{pathtoproject}/controlerthatdontexist/undefinedaction
4. Invalid callback Phalcon\Mvc\Dispatcher\Exception::__construct, cannot access protected method Phalcon\Mvc\Dispatcher\Exception::__construct() error instead of "controlerthatdontexist handler class cannot be loaded" exception

**Comment by sergeyklay** [comment]
@fragag03 Could you please re-build cphalcon using _latest stable_ Zephir and test again?

**Comment by fragag03** [comment]
@sergeyklay Yes I think I'll need help with this. I followed the steps on the download page for the compilation but Zephir is not mentioned in it.
