### ISSUE TITLE
Micro app error handler

### ISSUE THREAD

**Issue by academici** [phalcon/cphalcon#13350]
replace \Exception with \Throwable exception
https://github.com/phalcon/cphalcon/blob/4b37bdfaf277b4493532e5ead1dfc9449fe3ed17/phalcon/mvc/micro.zep#L954

**Comment by niden** [comment]
This has already been implemented for `4.0.0`

https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/mvc/micro.zep#L929
