### ISSUE TITLE
cache empty model data

### ISSUE THREAD

**Issue by zuozhehao** [phalcon/cphalcon#13369]
The result is empty and is cached, causing the function to always return empty data before the cache expires.

If the result is empty, can it not be cached

```php
function getByEmail(string $email)
{

    $key = 'user_email_' . $email;

    $result = UserModel::findFirst(

        [
            'conditions' => 'email = ?0',
            'bind'       => [$email],
            'cache'      => ['key' => $key]
        ]

    );
    
    return $result;
    
}
```
### Details

* Phalcon version: (`3.3.2`)
* PHP Version: (`7.2.5`)
* Operating System:Centos7
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx 
* Other related info (Database, table schema):

**Comment by Jeckerson** [comment]
Can you provide code of cache driver that you declared in services?

**Comment by zuozhehao** [comment]
```
$di->set(
    'modelsCache',
    function () use ($config) {
        $front = new \Phalcon\Cache\Frontend\Data;
        return new \Phalcon\Cache\Backend\Redis( $front , $config['redis']);
    }
);
```
