### ISSUE TITLE
[NFR] behaviors for Collection

### ISSUE THREAD

**Issue by anggiaj** [phalcon/cphalcon#1336]
I think it would be nice if there's behaviors for [\Phalcon\Mvc\Collection](http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Collection.html) as in [\Phalcon\Mvc\Model](http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model.html) ([\Phalcon\Mvc\Model\BehaviorInterface](http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model_BehaviorInterface.html) & [\Phalcon\Mvc\Model\Behavior](http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model_Behavior.html))

CMIIW

**Comment by Green-Cat** [comment]
I implemented this in 2.0.3 (#10416).
@sergeyklay
