### ISSUE TITLE
toArray() not called on models from Phalcon\Mvc\Model\Resultset\Simple

### ISSUE THREAD

**Issue by five07** [phalcon/cphalcon#13371]
### Expected and Actual Behavior

When fetching a Resultset\Simple using Model::find(), calling toArray() on the resultset does not call the toArray() method on the instances.

Example:

```php

class Test {
  public $foo;

  public function toArray($columns = null) {
    $data = parent::toArray($columns);
    // transform some data
    $data['foo'] = strtolower($data['foo']);
    return $data;
  }
}

// When we iterate in our code:

$items = Test::find(); // $items is typeof Resultset\Simple
foreach ($items as $item) {
  // $item is typeof \Test
  $output[] = $item->toArray(); // the Test::toArray() method is called.
}

// When we ask Resultset\Simple to iterate

$items = Test::find(); // $items is typeof Resultset\Simple
$output = $items->toArray();  // the Test::toArray() method is NOT called on each instance.
```

### Details

* Phalcon version: 3.3.0
* PHP Version: 7.2.2
* Operating System: all
* Installation type: Compiled from source

**Comment by Jurigag** [comment]
This is expected behavior. When using resultset phalcon never hydrates models. Models are hydrated once you access them from resultset.

**Comment by Jurigag** [comment]
Also to be honest - you should either do strtolower before saving model, or strtolower just when doing query.

**Comment by five07** [comment]
I think calling it a "stupid idea" without knowing the use case is pretty ignorant...

**Comment by Jurigag** [comment]
Yea so post real use case but still, hydrating model for just displaying means you are doing it wrong.
