### ISSUE TITLE
PHP gets segfault error when loading phalcon.so in  fpm-pool.conf

### ISSUE THREAD

**Issue by zishon** [phalcon/cphalcon#13374]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

What I want was:
Defined several fpm pool，and load phalcon.so in fpm-{pool}.conf , such as:

```ini
[test_project]
user = nobody
group = nobody

;listen = /tmp/fpm.$pool.sock
listen = 127.0.0.1:9000

;pm = static
pm = dynamic
pm.max_children = 8
pm.start_servers = 4
pm.min_spare_servers = 4
pm.max_spare_servers = 8
pm.max_requests = 100
slowlog = /logs/php/$pool.log.slow
request_slowlog_timeout = 3
request_terminate_timeout = 120
php_admin_value[error_log] = /logs/php/fpm-php.$pool.log
php_admin_flag[log_errors] = on
php_admin_value[open_basedir] = /srv/www/test_project/:/tmp/
php_admin_value[extension] = "phalcon.so"
```

after configured, I wrote a simple testAction()  which echo "hello,world!".
Then I request the action from browser,  when I request it five times, for the fifth request, I got an 502 from nginx.
Same time, an system error occured just like below：

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

system occured error ：   php-fpm[471]: segfault at 20600000001 ip 0000020600000001 sp 00007ffd54d3cd28 error 14 in phalcon.so[7fe51493a000+481000]

```php
// paste output here
```
> Provide minimal script to reproduce the issue

```php
// paste code
```
### Details

* Phalcon version: 3.3.2
* PHP Version: 7.1.6
* Operating System: Centos7
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema):  none

If necessary, I would like to provide the fully source code of the test project.

**Comment by sergeyklay** [comment]
@zishon Hello. When you get a chance can you provide coredump. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference. Also could you enable phalcon.so using standard way by adding extension=phalcon.so to php.ini.

**Comment by virgofx** [comment]
Agreed. Will need additional information as this is most likely a configuration error since other CentOS 7.4 / phalcon-3.3.2 via PackageCloud/IUS work fine in production.

**Comment by zishon** [comment]
@sergeyklay    using standard way by adding extension=phalcon.so to php.ini works fine for me.
ok, I will provide coredump for this.

**Comment by zishon** [comment]
@sergeyklay  When I visit https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace, It shows me  "You do not have permission to update this wiki."

**Comment by sergeyklay** [comment]
@zishon Correct URL is https://docs.phalconphp.com/en/latest/generating-backtrace

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
