### ISSUE TITLE
php 5.4 not longer supported,but the version of php is 7 in my centos 7.

### ISSUE THREAD

**Issue by kg-web** [phalcon/cphalcon#13377]
php 5.4 not longer supported,but the version of php is 7 in my centos 7.

**Comment by sergeyklay** [comment]
@kg-web Could you please describe your question a bit more? We'll need the steps to reproduce.

**Comment by stamster** [comment]
They're getting error message during installation that 5.4 is no longer supported. So the problem is with the paths on your system - you have both PHP7 and PHP 5.4 on your system (usually after upgrade or so).
Get rid of PHP 5.4 and you'll be able to compile.

**Comment by kg-web** [comment]
Thanks,I haved resolve the question.When I installed LNMP.org ,I selected PHP7.But the PHP5.4 is installed by centos 7.So after I removed PHP5.4,It works.
