### ISSUE TITLE
[NFR]  improve memory consumption and velocity

### ISSUE THREAD

**Issue by pmanup** [phalcon/cphalcon#13387]
In file query.zep

method: executeSelect always execute numrows

`
		/**
		 * Check if the query has data
		 */
		if result instanceof ResultInterface && result ->numRows(){
			let resultData = result;
		} else {
			let resultData = false;
		}
`

if the query is good, result always it's instanceof ResultInterface, numrows it's unnecesary

because if you work with sqlite, numrows execute other select, and if we don't want execute other select ?

If you have attibute bufer disabled in php, numrows mysql and postgre don't work, so phalcon not work.

the problem is in query.zep and resultset.zep, 

resultset.zep -> if we have 32 rows, make one fetchall¿why 32? 12, 24 64 512 ??? has no sense.

so, if don't has sense, numrows it's only necessary if we want, not ALWAYS.

if we could configure this, the performance it would improve a lot.

memory and velocity.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14059
