### ISSUE TITLE
Model::getChangedFields() mark fields as changed that not really changed

### ISSUE THREAD

**Issue by topotru** [phalcon/cphalcon#13384]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

SnapshotData holds integer values as strings.
We can see it on debug dumps in beforeValidationOnUpdate method

```php
    public function beforeValidationOnUpdate()
    {
        if ($this->hasChanged()) {
            echo 'toArray:<pre>', var_dump($this->toArray()), '</pre>';
            echo 'getChangedFields:<pre>', var_dump($this->getChangedFields()), '</pre>';
            echo 'getSnapshotData:<pre>', var_dump($this->getSnapshotData()), '</pre>';
            $this->setUpdatedAt(new DateTime());
        }
    }
```

Output
```php
toArray:
array(14) {
  ["id"]=>
  string(1) "1"
  ["subject_id"]=>
  int(1)
  ["status"]=>
  int(1)
  ["host"]=>
  string(10) "host.example"
  ["created_at"]=>
  string(19) "2018-02-16 22:02:06"
  ["updated_at"]=>
  string(19) "2018-05-22 16:54:05"
}

getChangedFields:
array(3) {
  [0]=>
  string(10) "subject_id"
  [2]=>
  string(6) "status"
}

getSnapshotData:
array(14) {
  ["id"]=>
  string(1) "1"
  ["subject_id"]=>
  string(1) "1"
  ["status"]=>
  string(1) "1"
  ["host"]=>
  string(10) "host.example"
  ["created_at"]=>
  string(19) "2018-02-16 22:02:06"
  ["updated_at"]=>
  string(19) "2018-05-22 16:54:05"
}
```

I think this because  of a strict comparison (Identical) of the values here https://github.com/phalcon/cphalcon/blob/4b37bdfaf277b4493532e5ead1dfc9449fe3ed17/phalcon/mvc/model.zep#L4116

solutions is: 
1. types cast in SnapshotData depends on ModelsMetaData
2. non-strict (equals) comparsion

### Details

* Phalcon version: (`php --ri phalcon`)
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.3.2
Build Date => Mar  7 2018 08:47:22
Powered by Zephir => Version 0.10.7
Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

* PHP Version: (`php -v`)
PHP 7.2.0 (cli) (built: Nov 28 2017 23:48:49) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies

* Operating System: windows 10 pro
* Installation type: dll
* Zephir version (if any): -
* Server: Nginx
* Other related info (Database, table schema): MySQL 5.7

**Comment by virgofx** [comment]
Strict comparison is correct and the intended behavior for changed/updated field detection is also correct. The issue is specific to your application with type juggling. You're retrieving values most likely from the database and storing these in snapshot as string. Thus, the intended behavior is correct.

/close

**Comment by topotru** [comment]
> Strict comparison is correct
its true

> The issue is specific to your application with type juggling
No

>  You're retrieving values most likely from the database and storing these in snapshot as string but converting/using them in your application's models in a different format.
No
I have integer types in database and $this->keepSnapshots(true); in Model::initialize()

> Updating your model and database types to be consistent will fix your issue.
Have you tried reproducing the problem?

**Comment by topotru** [comment]
And also I have private int members in model

**Comment by virgofx** [comment]
My above comments are still 100% correct. You need to familiarize yourself with how the database drivers internally manipulate types. The issue is specific to your application. By default they will all be strings unless you disable prepared statement emulation.
