### ISSUE TITLE
Form isValid method doesn't pass entity to validation

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#13383]
### Expected and Actual Behavior

Currently if we are doing `form->isValid()` without entity but we have form created like:

 ```php
$user = User::findFirst($id);
new Form($user);
```

Then if we don't add model keyword in Uniqueness validator we get a exception that model keyword is required, because form doesn't pass our $user entity to validation, but it's set when we are creating it, not sure if this is correct behavior, we might need to set here `let entity = this->_entity;` to correct things and make validation works properly.

**Comment by sergeyklay** [comment]
@Jurigag Could you provide the test which will produce the error and patch :)

**Comment by sergeyklay** [comment]
@Jurigag ping :)
