### ISSUE TITLE
chechToken() not found, problem with the sessions.

### ISSUE THREAD

**Issue by mateoagudelo** [phalcon/cphalcon#13399]
When I run this conditional in DesktopController, the checkToken() function of the indexController not working, return false.

```php
        if (!$this->session->has('id') AND !$this->session->has('docente')) {
            $this->response->redirect('ingreso/');
            $this->response->send();
        } 
```

**Comment by scrnjakovic** [comment]
Either be clear in describing your problem and provide relevant code to reproduce it, or start a topic on a FORUM instead of opening an issue here.
