### ISSUE TITLE
phalcon 3.3.2 - Getters not working when query()->columns() or find(['columns' => [...]]) is defined

### ISSUE THREAD

**Issue by 6562680** [phalcon/cphalcon#13404]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

1) phalcon 3.3.2 - Getters not working when query()->columns() or find(['columns' => [...]]) is defined
2) Also i cant use ->orderBy('order') because it is reserved word "order". I tried wrap it in

```
`order`
```
but got parse error. I tried to find practice like using placeholders to define column names like in node-js mysql module:
"?" -> value
"??" -> fieldname
but denied.

> Provide minimal script to reproduce the issue

```php
// model.php
class MyModel extends \Phalcon\Mvc\Model {
  protected $code;
  public function getCode() {
    return $this->code . '123';
  }
}

// controller.php
$set = Model::query()
  ->columns(['title', 'code'])
  // ->orderBy('order') // will cause expected EOF for me or "unable to use reserved ORDER"
  // ->orderBy('`order`') // will cause fatal parse error
  ->orderBy('ordering') // worked for me (if i modify the table schema)
  ->execute();

print_r($set[0]->code); // will be database value, no map included because "columns" defined
```

### Details

* Phalcon version: (`php --ri phalcon`) 3.3.2
* PHP Version: (`php -v`) 7.2 zts
* Operating System: win10
* Installation type: official DLL
* Server: Nginx 1.12
* Other related info (Database, table schema):
mysql 5.6

Schema:
table
id(bigint unsigned 20 auto) | title(TEXT) | code(TEXT) | order(int 10)

**Comment by Jurigag** [comment]
When you select columns there is no full model selected. There is object `Phalcon\Mvc\Model\Row` used.

**Comment by Jurigag** [comment]
You just need to select full columns, simple as that.

**Comment by 6562680** [comment]
When I started applying Phalcon I thought this was a terrific solution to almost all web development problems.

1. Spit the json it can not - make the headers clean php
2. $ depInjector is flooded so that after a while it becomes impossible to test the project simply because you can not put everything that needs to be displayed on the screen
3. Views system is killed in trash - the original is inconvenient, simple does not pull events out of the box
4. router does not support conditional operators of the form / (a-z)? / - they turn into an extra slash because of which links on the site then perish
5. I hoped that at least the models work in a human way. but even here they managed to natupit

The project is genius, brilliant for delivering material, for how it should be, to educate people for ease of development.

But it's terrible when you need everything and immediately for a corporate site and several applications. It is convenient to build API on it. Learning and understanding it is very convenient. But that's all.

And even when I point to trash, I'm told that "it's so necessary" and "how to get around" instead of "yes, +1, let's fix it."

**Comment by Jurigag** [comment]
But it's not a bug, you don't select full model so why you expect full model? What with other fields which you don't select or events which might work on empty values? This is a nfr not a bug. Feel free to do pull request with features you need.
