### ISSUE TITLE
phalcon/mvc/uri get() method working incorectly

### ISSUE THREAD

**Issue by 6562680** [phalcon/cphalcon#13400]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

Getting URL with language provided in argument.
**Attention - argument marked with question mark!**

> Provide minimal script to reproduce the issue
```php
$router->addGet('{language:(/[a-z]{2})?}/test/', callback)->setName('test');

$uri->get([ 'for' => 'test' ]); // or, no differences
$uri->get([ 'for' => 'test', 'language' => null ]); // or, no differences
$uri->get([ 'for' => 'test', 'language' => '' ]);

// returns
www.host.com//test/

// expected (one slash)
www.host.com/test/
```

### Details

* Phalcon version: (`php --ri phalcon`) 3.3.2
* PHP Version: (`php -v`) 7.2 ts
* Operating System: win10
* Installation type: Compiling from source || installing via package manager - DLL file downloaded from official repo
* Server: Nginx or Apache, no difference

**Comment by Jurigag** [comment]
Hmmm you should also write your baseUri and prefix if any, it might be added from one of those.
