### ISSUE TITLE
Unable to Use Disaptcher from Library

### ISSUE THREAD

**Issue by LearnPhalcon** [phalcon/cphalcon#13405]
Unable to access "getControllerName()" from inside my library. All I see is blank page when trying to use in controller. I'm using PHP 7.2.6 and Phalcon 3.4.0

```php
<?php // Library Example
namespace App\Libraries;
use Phalcon\Mvc\Dispatcher;
class Helper {
  function test() {
    $dispatcher = new Dispatcher();
    return $dispatcher->getControllerName();
  } #test
} #class
```

```php
<?php // Example Controller
namespace App\Controllers;
use Phalcon\Mvc\Controller;
use App\Libraries\Helper;
class Index extends Controller {
  function index() {
    exit(Helper::test());
  } #index
} #class
```

**Comment by Jurigag** [comment]
You need to acces dispatcher from di. You are creating just new object here. Also you can access controller name in controller. No reason to create seperated class for it. You can for example do:

```php
class Helper extends Phalcon\Di\Injectable
{
    public function test()
    {
        return $this->dispatcher->getControllerName();
    }
}
```

Also you should use forum for questions, github is only used for NFR and bugs.

**Comment by LearnPhalcon** [comment]
@Jurigag My apologies for using GitHub for this, but I really thought this was a bug. But sence we are here now. Can you please show an example on how to use ``Phalcon\Di\Injectable`` and also use ``$dispatcher->getControllerName()`` in Library? I need this to work in library not control. Perhaps how to access $di inside class would work too. Thank you!

**Comment by LearnPhalcon** [comment]
I need this to work from my library not controller or anywhere else. Perhaps there is a way to access Di from inside my library class ? Please show an example if you can.

So turns out it works when I use it like this, with ``$helper = new Helper()``

```php
<?php // Library Example
namespace App\Helper;
use Phalcon\Mvc\User\Plugin;
class Helper extends Plugin {
  function test() {
    return $this->dispatcher->getControllerName();
  } #test
} #class
```

```php
<?php // Controller Example
namespace App\Controller;
use Phalcon\Mvc\Controller;
use App\Libraries\Helper;
class Index extends Controller {
  function index() {
    $helper = new Helper();
    exit($helper->test());
  } #index
} #class
```

But its not working when I try to call this as static function, with ``Helper::test()``.

```php
<?php // Library Example
namespace App\Helper;
use Phalcon\Mvc\User\Plugin;
class Helper extends Plugin {
  public static function test() {
    return $this->dispatcher->getControllerName();
  } #test
} #class
```

```php
<?php // Controller Example
namespace App\Controller;
use Phalcon\Mvc\Controller;
use App\Libraries\Helper;
class Index extends Controller {
  function index() {
    exit(Helper::test());
  } #index
} #class
```

How can I use static function instead here? Thank you for your help!

**Comment by LearnPhalcon** [comment]
I've also tried using ``$di`` in my library class but all I see is just blank page.

```php
<?php // Library Example
namespace App\Helper;
use Phalcon\Mvc\User\Plugin;
class Helper extends Plugin {
  public static function test() {
    $di = \Phalcon\DI::getDefault();
    return $di->get('dispatcher')->getControllerName();
  } #test
} #class
```

```php
<?php // Controller Example
namespace App\Controller;
use Phalcon\Mvc\Controller;
use App\Libraries\Helper;
class Index extends Controller {
  function index() {
    exit(Helper::test());
  } #index
} #class
```

**Comment by LearnPhalcon** [comment]
I've found a workaround without using static function. I would still like to know how it can be done with static function too. But for what I'm doing, this workaround will work as well. By registering my library class globally I can access it anywhere in my project without even having to redeclare it on each Controller. What I want to know now is it safe registering own library class like that in $di and having global access to it?

```php
<?php // Bootstrap Example
use App\Libraries\Helper;
$di->set('helper', function() {
  return new Helper();
}); #helper
```

```php
<?php // Library Example
namespace App\Helper;
use Phalcon\Mvc\User\Plugin;
class Helper extends Plugin {
  function test() {
    return $this->dispatcher->getControllerName();
  } #test
} #class
```
```php
<?php // Controller Example
namespace App\Controller;
use Phalcon\Mvc\Controller;
# use App\Libraries\Helper; # <!-- No Longer Needed!
class Index extends Controller {
  function index() {
    exit($this->helper->test());
  } #index
} #class
```

**Comment by Jurigag** [comment]
Yes it's safe. In model you need to access di first and access your service.

Also as i wrote, please stop writing here, create thread on forum and close this issue @sergeyklay
