### ISSUE TITLE
[NFR] add method "closeResultset" to Phalcon\Mvc\Model\Resultset.

### ISSUE THREAD

**Issue by kornerita** [phalcon/cphalcon#13412]
Hello,

I would like to ask for a method to close the PDO Statement opened to release the resources.

PHP Closes the statement when the variable holding the reference is "destroyed", but when you use pointers the procedure is not straight forward, when the references are lost due to unset them, if the garbage collector does not comes into action then the resources stay opened until the gc passes by (10k references reached by default) or by calling it maually with gc_collect_cycles(). This may lock the database then long procedures with multiple operations do not close resources and there is not really a straight forward way to close them.

By the way, this problem came for me when I changed the PHP version from 5.6 to 7+, on a method that opens a resultset holding a blob resource, I tried to release it but I could not. I tried to replicate the problem with MySQL but I couldn't, blobs or clobs are not returning php's resources (I use ORACLE). 

Thanks!

### Details

* Phalcon version: 3.4.0
* PHP Version: 7.0 and 7.1
* Operating System: macOS, Centos 7
* Installation type: Compiling from source / installing via package manager
* Server: None required

**Comment by Jurigag** [comment]
Well, oracle support was dropped actually.
