### ISSUE TITLE
[Bug] 3.4.x Fix performance of getRouteByName/Id #13413

### ISSUE THREAD

**Issue by michanismus** [phalcon/cphalcon#13417]
Critical for my apps!

See https://github.com/phalcon/cphalcon/pull/13413#issuecomment-400226832

**Comment by sergeyklay** [comment]
@Jurigag Could you please take  a look?

**Comment by Jurigag** [comment]
Keep in mind it's not released yet. You should always build from release version.

**Comment by Jurigag** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/13420

**Comment by michanismus** [comment]
If I would have built from 3.4 tag we would have a serious bug in coming stable release...
Everything is working well again.
