### ISSUE TITLE
No make file during installation

### ISSUE THREAD

**Issue by magroski** [phalcon/cphalcon#13419]
Following the docs, I'm trying to install like this:
```
 cd cphalcon/build/php7/64bits

make clean
phpize --clean

export CFLAGS="-O2 -march=core-avx-i -mtune=core-avx-i"
./configure --enable-phalcon

make
make install
```

But I'm getting ` *** No targets specified and no makefile found.  Stop.`

And the docs for `./install` don't tell how to override the CFLAGS

* Installation type: Compiling from source

**Comment by Jurigag** [comment]
If you want to build phalcon using make install you should use cphalcon/ext folder.
