### ISSUE TITLE
db adapter can't read dialect class from php

### ISSUE THREAD

**Issue by stefanchiriac** [phalcon/cphalcon#13421]
I'm trying to set MysqlExtended Dialect from incubator but I'm getting class not found error. I tried to create my own dialect and seems to have the same problem. It works without problem if is the cphalcon dialect (\Phalcon\Db\Dialect\Mysql)
 
Fatal error: Class '\Phalcon\Db\Dialect\MysqlExtended' not found

```php
 $connection = new \Phalcon\Db\Adapter\Pdo\Mysql([
      'host'         => 'localhost',
      'username'     => 'root',
      'password'     => 'secret',
      'dbname'       => 'enigma',
      'dialectClass' => \Phalcon\Db\Dialect\MysqlExtended::class,
  ]);
```

### Details

* Phalcon version: 3.4
* PHP Version: 7.0
* Operating System: Ubuntu 16.04
* Installation type: Compiling from source
* Server: Apache

**Comment by Jurigag** [comment]
Are you sure you are loading this class? Did you loaded it with loader or you registered composer file using phalcon loader? Github is for bugs and NFR only. Please use forum for questions and problems.

**Comment by stefanchiriac** [comment]
Nevermind. Was a late night lack of concentration. I was loading the db before the classloader and no matter what class I was putting was not working, so was looking like a phalcon bug. Thanks anyway
