### ISSUE TITLE
BLOBS save incorrectly in phalcon 3.4 and php 7.2

### ISSUE THREAD

**Issue by jymboche** [phalcon/cphalcon#13423]
### Expected and Actual Behavior
Saving data to a BLOB column using the Mysql adapter in phalcon 3.4 and php 7.2 results in the blob incorrectly being saved as "1".

Mysql.zep here shows the bind type for TinyBlob being set to BOOL, even though TinyBlobs should support up to 255 chars of course
https://github.com/phalcon/cphalcon/blob/65183349743e899977adc643f103b887612ffe98/phalcon/db/adapter/pdo/mysql.zep#L170-L181

I'm unsure why I dont experience this in 7.1.x php releases....
### Details

* Phalcon version: 3.4.0
* PHP Version: 7.2.7
* Operating System: docker php:7.2.7-fpm
* Installation type: Compiled from source
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
Fixed in the `3.4.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
