### ISSUE TITLE
Will the official components consider supporting swoole extension？

### ISSUE THREAD

**Issue by kcloze** [phalcon/cphalcon#13435]
In the swoole env: initializes framework once and then handles requests/responses.
it will be more faster and more efficient. but the possibility of a problem is greater.
We very much hope that officials can support swoole extensions.

like this :
https://github.com/zendframework/zend-expressive-swoole

**Comment by niden** [comment]
From what I have seen in that implementation as well as the Laravel one, this is a command line implementation. So swoole is leveraged to speed up CLI tasks.

Is that the purpose of the integration?

**Comment by Jurigag** [comment]
@niden no it's not only cli tasks. It can work on all stuff, http, websockets etc. It's just something like phpreact, like working on events in single loop - but written as extension and works much, much better.
