### ISSUE TITLE
Is there a way to express subquery in the form clause in the Falcon framework?

### ISSUE THREAD

**Issue by yusng00** [phalcon/cphalcon#13430]
```sql
select * from (select *,(6371*acos(cos(radians(00.00000))*cos(radians(ch_lat))*cos(radians(ch_lng)-radians(00.00000))+sin(radians(00.00000))*sin(radians(ch_lat)))) AS distance,(ch_area / 1000) as kmiter FROM ls) as tab where distance < kmiter
```
I'm trying to print the above query through the Phalcon framework
I would like you to know if you know how to output it in a model

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
