### ISSUE TITLE
Multiple date columns in a table problem

### ISSUE THREAD

**Issue by threelight** [phalcon/cphalcon#13436]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

Hello,

I have stumbled upon a strange error:

I have a table in MySQL:

CREATE TABLE event ( id int(11) NOT NULL AUTO_INCREMENT, start_date date NOT NULL, end_date date DEFAULT NULL, PRIMARY KEY (id), );

My model looks like that: class Event extends \Phalcon\Mvc\Model {

public $id;
public $start_date;
public $end_date;

public function initialize() {
    $this->setSchema("MyDatabase");
    $this->setSource("event");
}

public function getSource() {
    return 'event';
}

public static function find($parameters = null) {
    return parent::find($parameters);
}

public static function findFirst($parameters = null) {
    return parent::findFirst($parameters);
}

When I do:

$event = new Event; $event->start_date = '2018-01-01'; $event->end_date = '2018-02-02';

$event->save();

Nothing is happening - no data inserted into the database I have implemented a listened on the database

$dbListener = new MyDbListener(); $eventsManager->attach('db', $dbListener);

Not even a qury is executed.

When I remove one of the date columns all works fine!

It looks like phalcon does not like two columns with date type in one table.

The thing is: it does not rearch that line, it dies inside of the save fumction. When I connect xdebug and stop on
When I try to debug with Xdebug:

$event->save(); // break point here 
if (!$event->save()) { // but this line is not reached 
    var_dump($event->getMessages());
}
and then just go over that line, the debug session is stopped and the whole process is finished.

I have updated phalcon to the newest version but I get the same result.

From the db listener I get:

[Sat, 14 Jul 18 17:14:12 +1000][INFO] SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME`= 'event' AND `TABLE_SCHEMA` = 'Test'
[Sat, 14 Jul 18 17:14:12 +1000][INFO] DESCRIBE `Test`.`event`
And it ends here

As soon as I remove the second DATE from the model and the table all works fine. Proper insert SQL is executed.

I think it might be a genuine problem.

> Provide output if related. Provide coredump if any. Use https://docs.phalconphp.com/en/latest/generating-backtrace as reference

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by Jurigag** [comment]
Provide details like phalcon version etc, I have 2 date columns in my app and no problem, did you clean models metadata? Maybe you just have some exception or try getMessages method on model.
