### ISSUE TITLE
Volt problem with interpreting url_field() function

### ISSUE THREAD

**Issue by sera527** [phalcon/cphalcon#13447]
I think Volt misinterprets the function url_field()

```php
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')' in /var/www/html/apps/cache/_var_www_html_apps_frontend_views_client_edit.volt.php on line 131
```

> Provide minimal script to reproduce the issue

```php
{{ url_field("facebook","id": "facebook","class":"form-control") }}
```
interpreted as

```php
<?= $this->tag->urlField('facebook', 'id' => 'facebook', 'class' => 'form-control') ?>
```

### Details

* Phalcon version: 3.4.0
* PHP Version: 7.1.19
* Operating System: Lubuntu 16.04
* Installation type: installing via package manager
* Server: Apache

**Comment by Jurigag** [comment]
You forgot about array.

**Comment by sera527** [comment]
@Jurigag, but the Volt documentation does not contain anything about arrays.
```php
<label for='name'>Name</label>
{{ text_field('name', 'size': 32) }}
```
[https://docs.phalconphp.com/ru/3.3/volt#tag-helpers](url)

**Comment by sera527** [comment]
@Jurigag also look at this.
This line
```php
{{ tel_field("name","class":"form-control") }}
```
is interpreted by Volt as
```php
<?= $this->tag->telField(['name', 'class' => 'form-control']) ?>
```
And this line
```php
{{ url_field("name","class":"form-control") }}
```
is interpreted by Volt as
```php
<?= $this->tag->urlField('name', 'class' => 'form-control') ?>
```
Why such difference? I think it's a bug.

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt/compiler.zep#L483 well yea you might actually be right.

**Comment by frsbarbier** [comment]
I have the same error with search_field
`{{ search_field('name', 'class': 'form-control') }}`

Like url_field, search_field is missing in arrayHelpers https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt/compiler.zep#L483

I think it's the same with
```
color_field
range_field
date_time_field
date_time_local_field
month_field
time_field
week_field
```

**Comment by niden** [comment]
This has been addressed with work by @CameronHall

**Comment by frsbarbier** [comment]
Thanks for this fix but i think `search_field` was forgotten in arrayHelpers.

**Comment by niden** [comment]
@frsbarbier I just added it. Nice catch. Thanks!
