### ISSUE TITLE
Router annotations with multi modules project

### ISSUE THREAD

**Issue by wajdijurry** [phalcon/cphalcon#13452]
Good evening,

Description of my case:

I have multi modules project and need to use Annotations routing rather than default routing. The problem (as I see) that I have to register controllers of each module globally to make routing with annotations work. This behavior opposite the encapsulation principle, as you have to define each controller in a global autoloader.

I read many threads about same issue, but the replies come with that modules are loaded after routes executed. Is there any way to load modules before routing ? Or is there any way to tell routes to go to the correct module instead of throwing an exception that "Project\Modules\Example\Controllers\IndexController" does not exist ?

**Comment by Jurigag** [comment]
Github is only for bugs and NFR, for questions use https://forum.phalconphp.com
