### ISSUE TITLE
Bug with volt

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13459]
Hello. 
I create empty volt template and text it:
```
{{ select_static(['name': 'kek'], ['Y': 'Yes', 'N': 'No']) }}
```

Volt interpretated it as:
```
$this->tag->selectStatic([['name' => 'kek'], ['Y' => 'Yes', 'N' => 'No']]);
```

And i catch next error:
```
Phalcon\Tag\Exception: Value at index: 'id' type: 'array' cannot be rendered
```

Screenshot: https://prnt.sc/keq6it

### Details

* Phalcon version: 3.4.0
* PHP Version: PHP 7.2.8
* Operating System: Ubuntu 16.04 TLS
* Installation type: installing via package manager
* Zephir version (if any): Version 0.10.10-d1b4cc68d9
* Server: Apache

**Comment by TimurFlush** [comment]
Please https://travis-ci.org/TimurFlush/phalcon-bug/builds/412177947
https://github.com/TimurFlush/phalcon-bug
@sergeyklay accept my request for contributig my packe by you

**Comment by sergeyklay** [comment]
I'll take a look as soon as I can

**Comment by TimurFlush** [comment]
This is due to the fact that Phalcon looks for the id key in the first argument-array and does not find it, so it assigns a zero key as an ID and it is an array, on this basis it cannot render it and throws an error. So the error is related to Volt.

Excuse me for my english.

**Comment by niden** [comment]
This has been resolved
