### ISSUE TITLE
Handling not found routes with Router\Annotations

### ISSUE THREAD

**Issue by wajdijurry** [phalcon/cphalcon#13453]
Hello all,

How to handle not found (404) routes with Router\Annotations component ?
I tried to set it in the router component with no luck:
> $di->setShared('router', function() {
>     $router = new Router\Annotations(false);
>     $router->addModuleResource('api', 'Project\Modules\Api\Controllers\Index', '/api');
>     $router->notFound('Project\Modules\Api\Controllers\NotFoundController.php');
>     return $router;
> });

**Comment by Jurigag** [comment]
Github is only for bugs and NFR, for questions use https://forum.phalconphp.com
