### ISSUE TITLE
[BUG] When bind variable value set as a boolean FALSE causes an error (Postgresql adapter)

### ISSUE THREAD

**Issue by YerlenZhubangaliyev** [phalcon/cphalcon#13460]
Hello there,

```php
Model::find(
[
   'conditions' => 'isDone = :isDone:',
   'bind' => ['isDone' => false]
]
);
```

causes this:

```bash
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: ""
```

all other values such as 
```php
['isDone' => 'false'], // string
['isDone' => '0'], // string
['isDone' => 0], // integer
```

produces a normal result

### Details

* Phalcon version: 3.3.0
* PHP Version: 7.1.17
* Operating System: Debian 8
* Installation type: installing via package manager
* Zephir version (if any): 0.10.5-04eb3288bf
* Server: Nginx
* Other related info (Database, table schema): PostgteSQL 10.0.4

```sql
create table test_boolean
(
  id        bigint default '0' :: bigint not null,
  "isDone" boolean
);
```

**Comment by Tanami** [comment]
Eventually a true or false value will be cast to a string for the database query so why are you trying to use it in a language-specific form?
