### ISSUE TITLE
Bad result when using Model findFirst().

### ISSUE THREAD

**Issue by dying318** [phalcon/cphalcon#13463]
### Expected and Actual Behavior

>The test script is ok when without line 2, when add the line2, findFirst will return the first row in database which is not related to the condition.

> Provide minimal script to reproduce the issue

```php
$parameters = [[["id=470"]]];
$conditions = &$parameters[0];  // the problem code
$model = Model::findFirst($parameters);
```

### Details

* Phalcon version: (3.4.0)
* PHP Version: (7.2.6)
* Operating System: macOS 10.13.6
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema):

**Comment by niden** [comment]
You are passing the `$parameters[0]` by reference. (see the `&`). Also you have a 3 level nested array there so Phalcon will never match the contents of that array to `findFirst`.

**Comment by dying318** [comment]
> You are passing the `$parameters[0]` by reference. (see the `&`). Also you have a 3 level nested array there so Phalcon will never match the contents of that array to `findFirst`.

Thanks for your reply, but I don't quite understand it. Phalcon support a 3 level nested array parameter, if I remove the second line, the findFirst works well, also the second line doing nothing to the `$parameters`, just a reference to it.

**Comment by niden** [comment]
Check what happens if you do this:

```php
$parameters = [[["id=470"]]];
$conditions = $parameters[0];
$model = Model::findFirst($parameters);
```

You can also do this

```php
$model = Model::findFirst(
[
    'conditions' => 'id = :id:',
    'bind'       => [
        'id' => 470,
    ],
);
```

**Comment by dying318** [comment]
It's very strange, the code runs well now with the reference, I used test it on my workmate‘s computer too, but both ok now.
Sorry to trouble you, really appreciate  for your reply.

**Comment by dying318** [comment]
By accident, when I was reading a document about php internal, I guess I got the answer. A reference could change the php value's is_ref property saved in zval, maybe phalcon did something different when that property is changed.
`
$foo['love'] = 1;
$bar  = &$foo['love'];
$tipi = $foo;
$tipi['love'] = '2';
echo $foo['love'];
`
the result is '2'.
copy from: http://www.php-internals.com/book/?p=chapt06/06-06-copy-on-write

**Comment by dying318** [comment]
And also, I test the code I post in my question again, it runs not well again, I doubt whether it ever runs well or I make a mistake the last time I test it.
