### ISSUE TITLE
Inconsistent naming convention in Dispatcher classes, no way to retrieve a settable value (handler suffix)

### ISSUE THREAD

**Issue by terax6669** [phalcon/cphalcon#13468]
## Expected:

Available methods:
```
\Phalcon\Dispatcher::getHandlerSuffix()
\Phalcon\Dispatcher::setHandlerSuffix()

or

\Phalcon\Cli\Dispatcher::getTaskSuffix()
```

## Actual
There is a `\Phalcon\Cli\Dispatcher::setTaskSuffix()` method that sets `_handlerSuffix` - this is inconsistent.
After using `setTaskSuffix` there is no way to read the new value from the dispatcher.

### Details

* Phalcon version: 3.4.1

**Comment by niden** [comment]
This has been implemented in 4.x
