### ISSUE TITLE
PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/phalcon.so' -  undefined symbol: php_json_decode_ex in Unknown on line 0 

### ISSUE THREAD

**Issue by LaJun** [phalcon/cphalcon#13467]
### Details

* Phalcon version: 3.31
* PHP Version:  5.6
* Operating System: centos7 
Linux iZ948im4rnxZ 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64
* Installation type: git clone source code master
* Zephir version (if any):
* Server: Apache2 use php5-mod not php-fpm
i make it complies the source code  and when i  make test, the error happened
then i find the solutions on the internet,  show that json should be loaded  before  phalcon, then i add  extension = phalcon.so  into end of php.ini, it doesnt work
then i find the json  loaded in  json.ini, i try  to create a file  named 30-phalcon.ini include extension.so，
it still doesn't work
please help me  to solve this problem，
thanks

**Comment by sergeyklay** [comment]
Please provide steps to reproduce

**Comment by nask0** [comment]
@LaJun try to add "_extension=json.so_" to _/etc/php.d/20-json.ini_ and "_extension=phalcon.so_" to _/etc/php.d/50-phalcon.ini_ and restart your httpd server. It should be fine.

**Comment by niden** [comment]
Please re-open this if it continues to be a problem. As @nask0 wrote, I usually put Phalcon last so `30-phalcon.ini` is usually `80-phalcon.ini` for me.

**Comment by magosla** [comment]
I also encountered the same issue and was able to resolve it by removing "extension = phalcon.so" from php.ini file while having /etc/php.d/50-phalcon.ini untouched
