### ISSUE TITLE
[BUG] httpOnly flag is ignored in set() for cookies

### ISSUE THREAD

**Issue by mohahn** [phalcon/cphalcon#13464]
System:
```
$ phalcon info

Phalcon DevTools (3.4.0)

Environment:
  OS: Linux vmv 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
  PHP Version: 7.0.30-0+deb9u1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.0
  PHP Extension Dir: /usr/lib/php/20151012
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.0/cli/php.ini
Versions:
  Phalcon DevTools Version: 3.4.0
  Phalcon Version: 3.4.0
  AdminLTE Version: 2.3.6
```

By default `httpOnly` seems to be active ([see](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L58)). In [API documentation](https://docs.phalconphp.com/de/latest/api/Phalcon_Http_Response_Cookies) one can see, that with the last parameter of method `set` this flag can be set.
But, regardless of value I'm using, the cookie is sent with active `httpOnly` to browser, always.

Ex. in controller:
```
$this->cookies->set(
    'uid', // name
    $id, // value
    time() + 86400, // expire
    '/', // path
    false, // secure
    $domain, // domain
    false // http only
);
```

The only way I get `httpOnly` removed is by calling following statements right after `set()`:

```
$cookie = $this->cookies->get('uid');
$cookie->setHttpOnly(false);
```

So the flag in `set()` seems to be ignored (all other parameters are working correctly, only `httpOnly` is set to `true` always). That's not very comfortable. This is urgent to me, so to be sure I fall back to native `setcookie()` now.
What I do not understand is, that the flag `httpOnly` is optional and declared with `null` when calling `set()`. But as property in class `Cookie` it's initialized with `true`, see [here](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L60).

**Comment by mohahn** [comment]
I'm executing the following code

```
$this->cookies->set(
    'uid', // name
    $id, // value
    time() + 86400, // expire
    '/', // path
    false, // secure
    $domain, // domain
    false // http only
);
$check = $this->cookies->get('uid');
var_dump($check->getHttpOnly());
```

which gives me `true`. Seems like an internal bug.
BTW: It's a feature request, but I don't think it's correct to enable `httpOnly` as default, when native PHP function `setcookie` expects this parameter as NULL if not set.

**Comment by avionwd** [comment]
I have the same issue! Phalcon version 3.4.1 (migrated from 3.3.x).
So, our application sets a cookie at the backend, but frontend (JS) cannot get it because it has flag HttpOnly. 
Pls, fix this.

**Comment by antsokol** [comment]
I have the same. Strange, because source code looks like right.

> Version => 3.4.2
Build Date => Dec  2 2018 17:24:20
Powered by Zephir => Version 0.10.14

**Comment by niden** [comment]
Thsi has been resolved
