### ISSUE TITLE
update query occurred by create method.

### ISSUE THREAD

**Issue by nagaho** [phalcon/cphalcon#13478]
If it calls $model->create() at the same time in multiple processes, Rarely an update query occurred.

- sample script
https://gist.github.com/nagaho/b62f6be070674fc8aec645b0cd5bc09b

- _exists method of create method -> false
- _exists method of save method -> true
(It was inserted by other process between create and save methods)

I think Phalcon isn’t intentional that update query occurs in create method, Is it correct?
Thanks,

### Env

* Phalcon version: 3.4.1
* PHP Version: 7.2.9
* Operating System: macOS
* Installation type: Compiling from source

**Comment by Jurigag** [comment]
Yes it is correct because this id can already exists in database, then phalcon will perform update because it's primary key. I guess maybe we should throw exception there.
