### ISSUE TITLE
Error minify with vue.js

### ISSUE THREAD

**Issue by JCauz** [phalcon/cphalcon#13475]
Hello,

I set up the minification via phalcon assets. The file is created and the js are put in the general file. But I use vue.js and there is a problem with the minification of these. I have an error in the console that is:
SyntaxError: Invalid regular expression: missing /

I initialize the asset as below:
`$collectionCss = $assets->collection($collection)
                    ->setTargetPath(Frog::$sitePath . '/media/css/cache/' . $fileCache)
                    ->setTargetUri(Frog::$webRoot . '/media/css/cache/' . $fileCache)
                    ->join(true)
                    ->addFilter(new Phalcon\Assets\Filters\Cssmin());`

And I add the view.js file with the addJs method.
The file is already minified by view.js I do not know if it is because it is already minified that the problem occurs.

Here is a screenshot of the code in the general minified file.
![capture](https://user-images.githubusercontent.com/6204939/44847599-4afb1780-ac54-11e8-914a-6fc217adf665.PNG)

I do not know if you need more information. If ever do not hesitate.

Thank you in advance for your help.

### Details

* Phalcon version: 3.4.1
* PHP Version: php 7
* Vue.js Version: 2.5

**Comment by Jeckerson** [comment]
I don't think it is good idea to add Phalcon assets as wrapper to minify files that were already processes and minified by Webpack... 

Just call webpack output files directly in your views.

And about your error - you are trying to minify **JS** files with **CSS**min filters!

**Comment by JCauz** [comment]
Thank you for your reply.

So actually I was wrong code. I posted the one for the css but the one for js does not work.
What I would have wanted is to gather all the files js in a single file with assets even if they come from webpack. It is not possible?

**Comment by Jeckerson** [comment]
It is possible, but don't minify them (without any filters), just join.

```
// Join all the resources in a single file
->join(true)
```

**Comment by JCauz** [comment]
yes but so we will not be able to miniify the eventielles files that are not minified by webpack then.

**Comment by JCauz** [comment]
The minification and joining does not exist by default in webpack, it is an external plugin. Also the assets usage permits to join only the necessary javascript based on a URI (using rewriting) instead of putting all javascripts in a big webpack compilation.  So yes we can use webpack OR phalcon but it is not as performant as using both webpack and phalcon.   

The problem of the minification is that we use both webpack files, and classic js files outside of the webpack so we need to minify them and join them as well.

**Comment by JCauz** [comment]
I no longer have the file minified with the problem.
I have finally created a collection where I am my files vues.js and I just do a join on it. I created a filter that does nothing to use the join.
So I have two js files. One with the classic js thumbnails and the others with the files vues.js which are minified by webpack.
