### ISSUE TITLE
Where/how is validation->getData() implemented?

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13470]
I see this references to this method, like [here](https://github.com/phalcon/cphalcon/blob/caeac66e7db02fd54c44a27cf22a6381654af2ee/phalcon/validation/validator/callback.zep#L86) but I cannot find it's implementation anywhere?

An error maybe?

**Comment by JABirchall** [comment]
It is abstracted from Phalcon\Di\Injectable from the __get magic method.

It returns the protected variable _data from Phalcon\Validation

**Comment by Jurigag** [comment]
`protected _data { get };` it's here
