### ISSUE TITLE
It's email sanitizing problem? 

### ISSUE THREAD

**Issue by Linvas** [phalcon/cphalcon#13487]
when I need to get a request value of email address, and use sanitizer and filter, like this:
> $this->request->getPost('email_addr', 'email')
and email_addr data is __123Abc@-_.$%^'*__
those characters __!#$%&*+/=?^\`{\|}~[]__ they all can pass! they all can pass!
I've never seem any email address use those characters __!#$%&*+/=?^\`{\|}~.[]__ before.
it can be SQL inject like __'__ and __*__ , I think it just need to keep __\_-@.__ those four characters and letters and numbers are enough, or I think this sanitizer should change a name but not __email__
it's make lots of developers confusing.
most of time, we just need to get a normal email address without any sql inject.

**Comment by Jurigag** [comment]
This email filter is using built-in php http://php.net/manual/en/function.filter-var.php so if it can accept such email then phalcon filter email the same.

If you need your own filter then write it.
