### ISSUE TITLE
Response set within dispatch:beforeException gets wiped

### ISSUE THREAD

**Issue by terax6669** [phalcon/cphalcon#13482]
### Expected and Actual Behavior

Steps to reproduce:

1.  Throw an exception.
2. `dispatch:beforeException` -> handle exception, `response->setContent()`, `return false`, now the app flow returns to `application.zep`.
3. `application.zep` -> now `possibleResponse === NULL` and  `implicitView === true` (default).
4. `application.zep` -> `possibleResponse` was not `false` and was not a Response object, so eventually *this* gets executed on line 399 `response->setContent(view->getContent())` and wipes out any reponse I have previously set.
5. App returns to `index.php` ->
```php
$response = $application->handle();
$response->send();
```
the Response is now empty, because it was cleared in step 4.

Perhaps handle returning a response object from `dispatch:beforeException`? Because currently Phalcon is clearing a response when it IMO shouldn't.

> Provide minimal script to reproduce the issue

```php
<?php
class IndexController {
    public function indexAction() {
        throw new \Exception('important error message');
    }
}

$app = new \Phalcon\Mvc\Application;
$di = new \Phalcon\Di\FactoryDefault;
$di->setShared('view', \Phalcon\Mvc\View::class);
$app->setDi($di);

$eventsManager = $di->getEventsManager();
$eventsManager->attach('dispatch:beforeException', function($event, $dispatcher, $exception) {
    $dispatcher->getDi()->getResponse()->setContent('whoops: ' . $exception->getMessage());
    return false;
});

$di->getDispatcher()->setEventsManager($eventsManager);

$response = $app->handle('/');
var_dump($response->getContent()); // expected: string(31) "whoops: important error message" | actual: string(0) ""
```

### Details

* Phalcon version: **3.4.1**
* PHP Version: **7.2.8**
* Operating System: **Debian 9.5 (Linux 4.9.0)**
* Installation type: **https://packagecloud.io/phalcon/stable/debian/ stretch main**

**Comment by virgofx** [comment]
Adding myself as a watcher, will investigate.

**Comment by zsilbi** [comment]
```php
$eventsManager->attach('dispatch:beforeException', function($event, $dispatcher, $exception) {
    $dispatcher->setReturnedValue('whoops: ' . $exception->getMessage());
    return false;
});
```

You should not modify the response there, use `Dispatcher::setReturnedValue()`.
Added test to confirm this here: https://github.com/phalcon/cphalcon/pull/15175
