### ISSUE TITLE
[BUG] Double slashes problem

### ISSUE THREAD

**Issue by krazzer** [phalcon/cphalcon#13495]
The issue described in https://github.com/phalcon/cphalcon/issues/3222#issuecomment-70374037 was fixed in an earlier version, but has resurfaced. 

When I set my baseUri to `https://mydomain.com/` and I run `$this->response->redirect('/test');`, the output will be `https://mydomain.com//test` while it should be `https://mydomain.com/test`

This was fixed in 2.0.0:
```zep
if local {
	if ((substr(baseUri, -1) == "/") && (substr(uri, 0, 1) == "/")) {
		let uri = baseUri . substr(uri, 1);
	} 
	else {
		let uri = baseUri . uri;
	}
}
```

But in 3.4.x:
```zep
if local {
	let strUri = (string) uri;
	if baseUri == "/" && strlen(strUri) > 2 && strUri[0] == '/' && strUri[1] != '/' {
		let uri = baseUri . substr(strUri, 1);
	} else {
		if baseUri == "/" && strlen(strUri) == 1 && strUri[0] == '/' {
			let uri = baseUri;
		} else {
			let uri = baseUri . strUri;
		}
	}
}
```

So I guess it should be:
```zep
if local {
	let strUri = (string) uri;
	if substr(baseUri, -1) == "/" && strlen(strUri) > 2 && strUri[0] == '/' && strUri[1] != '/' {
		let uri = baseUri . substr(strUri, 1);
	} else {
		if baseUri == "/" && strlen(strUri) == 1 && strUri[0] == '/' {
			let uri = baseUri;
		} else {
			let uri = baseUri . strUri;
		}
	}
}
```

**Comment by Jurigag** [comment]
Well we will need to analyze git history and check why it was removed, if it was just a mistake somehow or something more.

**Comment by niden** [comment]
This has been addressed
