### ISSUE TITLE
Unexpected difference in behaviors of Form::getValue() and Element::getValue()

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13498]
Take following expressions:
```php
$value = $form->getValue('name');
$value = $form->get('name')->getValue();
```
When you logically interpret this, you think:
```
get value of form's element "name"
get form's element "name" and get its value
```

Naturally, those should produce the same output under same conditions. But it's not how these two methods are implemented. Calling `$element->getValue()` will:
 - Call `$form->getValue($name)` if form exists
 - If form exists but returns `null`, it will call `Tag::getValue($name)`
 - Lastly, it will return default value

Compared to `$element->geValue()`, `$form->getValue($name)` will:
 - not call `Tag::getValue($name)`
 - not return element's default value if nothing else produces a value

Is there something that requires this specific behavior? If not, my proposition is to:
 - Move `Tag::getValue($name)` call from `$element->getValue()` method to `$form->getValue()` method just above `return null`.
 - If nothing above yields a value, return elements default value (which is effectively `null` if default wasn't specified) if element exists
 - Lastly, return `null`

If I haven't oversaw something, this should lead to following behavior:
`$form->getValue($name)` and `$element->getValue()` methods produce the same result unless `$element` is independent element (it doesn't belong to a form) in which case element's default value will be returned (or `null`). 

I will create a pull request for this one.

What do you think?

**Comment by niden** [comment]
I see the problem. You are correct these two should be the same.

I want the core team to look into this because this will definitely introduce unintended side effects in existing applications. I really do not want this to go into the 3.x version because it is a big caution item for existing applications.

Also tests are failing. (see travis). This is what I meant by the above.

@phalcon/core-team

**Comment by Jurigag** [comment]
Overall i agree, going with this on 4.0.x is way to go.

**Comment by scrnjakovic** [comment]
@niden that's what I figured and why I sent pull request to 4.0 branch. I think travis fails because of the way element's value is cleared which is too inconsistent. Element's clear method should, too, call form's clear method if form exists.

**Comment by niden** [comment]
@scrnjakovic In that case we need a few things before this gets into the repo
- Send it only to 4.0
- Update the `CHANGELOG`
- Update the tests
- Write a small brief so that I can go in the 4.0 documentation and change the contents to reflect the behavior. 

The blog post for 4.0 will be massive lol

**Comment by scrnjakovic** [comment]
And I think that [Element::clear()](https://github.com/phalcon/cphalcon/blob/65183349743e899977adc643f103b887612ffe98/phalcon/forms/element.zep#L515) instead of:

```zep
/**
 * Clears every element in the form to its default value
 */
public function clear() -> <Element>
{
    Tag::setDefault(this->_name, null);
    return this;
}
```
Should be:
```zep
/**
 * Clears every element in the form to its default value
 */
public function clear() -> <Element>
{
    Tag::setDefault(this->_name, this->_value);
    return this;
}
```
I think that test would pass after this.

**Comment by scrnjakovic** [comment]
Okay, I added more commits to pull requests changing how `Phalcon\Forms\Form::clear()` and `Phalcon\Forms\Element::clear()` work. To some up, these are the changes:

- `Phalcon\Forms\Form::clear()` method will no longer call `Phalcon\Forms\Element::clear()`, instead it will clear element's value itself
- `Phalcon\Forms\Element::clear()` will now call `Phalcon\Forms\Form::clear()` passing its name or will clear itself if form does not exist
- `Phalcon\Forms\Element::getValue()` will now call `Phalcon\Forms\Form::getValue()` or return its default value (instead of hardcoded `null`) if form does not exist
- 'Phalcon\Forms\Form::getValue()` will now also try to get element's value from the `Tag` or calling element's `getDefault()` method before returning null

The idea is to standardize form's and element's `getValue()` and `clear()` methods so they have same effect, but also having element's methods remain functional in case its standalone element (without parent form).

- [ ] Fix some f*** ups
- [ ] I will update tests if travis still fails after I fix those errors.
- [ ] I will update the `CHANGELOG`
- [x] I think above qualifies as brief? If not, let me know.

**Comment by scrnjakovic** [comment]
Are we good to close?

**Comment by niden** [comment]
Thank you!
