### ISSUE TITLE
phalcon.so

### ISSUE THREAD

**Issue by expeditedtravel** [phalcon/cphalcon#13490]
I can't get the phalcon.so to load, I'm trying to install phalcon on my centOS server running php 7.2. 

I upgraded my gcc to 5.4.0 

[root@myCentOS ~]# gcc --version
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This is the error I'm getting :  php -r 'print_r(get_loaded_extensions());'

PHP Warning:  PHP Startup: Unable to load dynamic library 'phalcon.so' (tried: /usr/lib64/php/modules/phalcon.so (/usr/lib64/php/modules/phalcon.so: undefined symbol: php_json_decode_ex), /usr/lib64/php/modules/phalcon.so.so (/usr/lib64/php/modules/phalcon.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'phalcon.so' (tried: /usr/lib64/php/modules/phalcon.so (/usr/lib64/php/modules/phalcon.so: undefined symbol: __builtin_saddl_overflow), /usr/lib64/php/modules/phalcon.so.so (/usr/lib64/php/modules/phalcon.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Please help.

CentOS Linux release 7.5.1804 (Core) 
PHP 7.2.10 (cli) (built: Sep 11 2018 11:22:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group

**Comment by zzplab** [comment]
I've had my issues with installing Phalcon on php7+ too from the standard documentation.
My setup is CentOS 7+ / cpanel / php 7.2.
Adding the right paths to PHP7.2 helped me to have a successful installation and make it work:
```
cd /usr/local/src

mkdir -p /usr/local/src/cphalcon

rm -dfR /usr/local/src/cphalcon

git clone git://github.com/phalcon/cphalcon.git

cd /usr/local/src/cphalcon/build/php7/64bits/

/opt/cpanel/ea-php72/root/usr/bin/phpize --enable-phalcon --with-php-config=/opt/cpanel/ea-php72/root/usr/bin/php-config

./configure --with-php-config=/opt/cpanel/ea-php72/root/usr/bin/php-config

make

make install
```

**For your server** change `/opt/cpanel/ea-php72/root/usr/bin` and `/opt/cpanel/ea-php72/root/etc` to whatever is the right path on your server where php7.2 is and the phpize / php-config / ini files.

Add `extension=phalcon.so` to `/opt/cpanel/ea-php72/root/etc/php.d/20-phalcon.ini` or your own php.ini file.

Then restart httpd (+ php-fpm).
Hope this may help you if that was the issue.

**Comment by Jurigag** [comment]
You need to load phalcon after loading json.so
