### ISSUE TITLE
Rename property of pagination page object to be more intuitive

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13492]
I propose changing `before` property of `page` object to `previous` which is far more intuitive for given context, as `before` goes better with `after`, not `next`.

I know this is minor and breaks BC, but maybe we can do it in 4.0? Or for some time, allow both properties.

**EDIT:** I also think that having `total_pages` and `last` is a bit redundant. I propose removing `last`.

**EDIT2:** I'd also rename `$paginator->getPaginate()` to either `$paginator->getPage()` or `$paginator->paginate()` for the same reason - being more intuitive.

**Comment by Jurigag** [comment]
Overall i agree. If we are going to release next minor version then we can add new methods.

**Comment by niden** [comment]
Implemented
