### ISSUE TITLE
CLI ORM  Memory leak

### ISSUE THREAD

**Issue by ekliu** [phalcon/cphalcon#13505]
php code:
for ($i = 1; $i < 100000; $i++) {
            $phql = "SELECT *  FROM YH\Models\CpsOrder where order_id = ?0 ";
            $data = $this->modelsManager->executeQuery(
                $phql,
                [
                    $i,
                ]
            );
            unset($data);
            echo "M: " . memory_get_usage() . " de " . ini_get("memory_limit") . "\n";
        }
        die;

Console：

M: 1536336 de 128M
M: 1537232 de 128M
M: 1538128 de 128M
M: 1539024 de 128M
M: 1539920 de 128M
M: 1540816 de 128M
M: 1541712 de 128M
M: 1542608 de 128M
M: 1543504 de 128M
M: 1544400 de 128M
M: 1545296 de 128M
M: 1546192 de 128M
M: 1547088 de 128M
M: 1547984 de 128M
M: 1548880 de 128M
M: 1549776 de 128M
M: 1550672 de 128M
M: 1551568 de 128M
M: 1552464 de 128M
M: 1553360 de 128M
M: 1554256 de 128M
M: 1555152 de 128M
M: 1556048 de 128M
M: 1556944 de 128M
M: 1557840 de 128M

### Details
CLI Running Mode: Grabbing a large amount of data and increasing memory, how to use an ORM query and destroy it。

* Phalcon version: 3.4.1
* PHP Version: 7.2.4

**Comment by Jurigag** [comment]
You could try `Query::clean` on each after querying each data.

**Comment by ekliu** [comment]
> You could try `Query::clean` on each after querying each data.

    $this->modelsManager->__destruct();
    \Phalcon\Mvc\Model\Query::clean();

No effect ！！！

**Comment by Jurigag** [comment]
Hmmmm, maybe you have `ATTR_EMULATE_PREPARES` set to true? Though it's really a big guess. To be honest don't really see this as a big problem since it's like a few hundred bytes.

**Comment by Jeckerson** [comment]
This is problem of PHP, not Phalcon. PHP's garbage collection isn't perfect... Your example shows that.

**Comment by FaimMedia** [comment]
1557840 == 1,5 MB, that's almost nothing.
Also you're still executing in the loop, it's logical the garbage collector doesn't pick up code that's still executing. Unset it after the loop, sleep for 5 seconds and check again.

**Comment by Jurigag** [comment]
Well some previous phalcon versions actually had some problems with orm/phql and memory leaks, but as far as i know it was fixed.

**Comment by niden** [comment]
Closing this until we get real data that Phalcon has a memory leak etc. This is related to PHPs gc
