### ISSUE TITLE
Is it possible to support two tier cache mechanism

### ISSUE THREAD

**Issue by mia0x75** [phalcon/cphalcon#13512]
Local cache and distributed cache, such as APCu + Redis

**Comment by niden** [comment]
You can register two cache services in your DI container and then save the data you want to save in the cache on either according to the needs of your application.

Alternatively if you want to save data at the same time in both, you can create your own cache class that will be responsible for saving on both services when you call save, or delete from both when you call delete. Something like this:

```
class MyCache
{
    public function save(string $key, $data)
    {
        $localResult = $this->localCacheService->save($key, $data);

        if (true !== $localResult) {
            throw new Exception('Cannot save in the local cache');
        }

        $remoteResult = $this->remoteCacheService->save($key, $data);

        if (true !== $remoteResult) {
            throw new Exception('Cannot save in the remote cache');
        }
    }
}
```

**Comment by Jurigag** [comment]
There is actually built-in way for this:

https://docs.phalconphp.com/bg/3.3/cache#multi-level
