### ISSUE TITLE
Use DISTINCT for some columns

### ISSUE THREAD

**Issue by maxttor** [phalcon/cphalcon#13513]
### Details

* Phalcon version: (`php --ri phalcon`) 3.4.1
* PHP Version: (`php -v`) 7.2.9
* Operating System: Ubuntu 16.04.5 LTS
* Installation type: installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other: Nginx
* Other related info (Database, table schema): MySQL

How to use DISTINCT on multiple columns for selecting from a database?

**Comment by niden** [comment]
@maxttor The issue tracker is only for bugs, PRs and NFRs. You can use the forum (https://phalcon.link/forum) or Discord (https://phalcon.link/discord) to ask any questions regarding usage.

To answer your question:

Distinct can be used just like you use it in a straight SQL statement (comma delimited).

For the query builder you can use `->distinct('a, b')` or if you use `find` you will need the `distinct` key in your parameter array
