### ISSUE TITLE
Shared lock bug

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13529]
Hello, and...

And I want to tell you about yet another a bug.

Class: Phalcon\Db\Dialect
Method: sharedLock() etc

Note, that the method contains only in abstract class \Phalcon\Db\Dialect, all the dialects not contain specifically the method sharedLock, therefore PostgreSQL can't execute query with LOCK IN SHARE MODE because the operator not supported for PostgreSQL, and only for mysql

Latest Phalcon version.

**Comment by niden** [comment]
Fixed. Thank you for reporting this
