### ISSUE TITLE
Model relation reusable=>false not working

### ISSUE THREAD

**Issue by nilsm** [phalcon/cphalcon#13531]
### Expected and Actual Behavior

I have a model with a relation set to 'reusable' => false.
I would expect the relation to be fetched from the database every time it is accessed.
However the relation is cached after the first call, even though 'reusable' => false.
Using 'getRelated()' to access the relation works as intended.

Note: 'reusable' => false is the default setting, so models do not work as intended by default.

Here is some sample code:

```php
class Robots extends \Phalcon\Mvc\Model
{
    public $id;
    public $name;
    public function initialize()
    {
        $this->hasMany("id", "Parts", "robot_id", ['reusable' => false]);
    }
}

class Parts extends \Phalcon\Mvc\Model
{
    public $id;
    public $robot_id;
    public $name;
    public static function find($parameters = NULL)
    {
    	echo 'find';
    	return parent::find($parameters);
    }
    public function initialize()
    {
        $this->belongsTo("robot_id", "Robots", "id", ['alias' => 'robot']);
    }
}

// actual code to test
$robot = new Robot();
$robot->name = 'Bob';
$robot->save();

$robot->parts; // first query - echos 'find'
$robot->parts; // 2nd query - no echo, even though it should re-query
$robot->getRelated('parts'); // echo 'find', as intended
$robot->getRelated('parts'); // echo 'find', as intended
```

### Severity
Critical - this is stopping us from upgrading to Phalcon 3 + model relations do not work as documented.

### Details

* Phalcon version: 3.4.1
* PHP Version: 5.6
* Operating System: n/a
* Installation type: Compiling from source
* Zephir version (if any): n/a
* Server: n/a
* Other related info

```
CREATE TABLE `robots` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(70) NOT NULL,
    PRIMARY KEY (`id`)
);
CREATE TABLE `parts` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `robot_id` int(10) unsigned NOT NULL,
    `name` varchar(70) NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (robot_id) references robots(id)
);
```

**Comment by nilsm** [comment]
I've dug around in the source code and am pretty sure that this is the cause of the problem:

https://github.com/phalcon/cphalcon/pull/11983/files

Once accessed, the related records are stored as an instance property and returned every time, regardless of what 'reusable' is set to.

**Comment by Jurigag** [comment]
Why it should requery? After first getting it it adds as a property, this is intended. You can use getParts for example(and you imh should).

**Comment by nilsm** [comment]
@Jurigag I would expect it to requery because reusable is false - I didn't know that some access methods behave differently to others and (to me at least) this isn't clear from the documentation. Also in Phalcon 2 it does requery and I suspect it was an unintended consequence of the pull request I linked to?

**Comment by Jurigag** [comment]
I think this is intentional to keep behavior with magic properties etc.

**Comment by nilsm** [comment]
Thanks Jurigag - what do you think about the way it's changed from Phalcon 2 to Phalcon 3? It does requery (depending on the reusable setting) in Phalcon 2, even when using ->Parts. This is causing lots of upgrade problems for us - but it also makes me think that it's a bug, as the behaviour has changed without being documented.

**Comment by CameronHall** [comment]
I disagree @Jurigag. I noticed this when I created the PR for the `isRelationshipLoaded` method. Perhaps I misunderstand what the `reusable` attribute is meant to do on relationships, but my assumption would be that instance of the relationship would never be cached if  "reusable" is `false`.

**Comment by CameronHall** [comment]
@niden this is a bug

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14035
