### ISSUE TITLE
Please add method close() to Phalcon\Session\AdapterInterface

### ISSUE THREAD

**Issue by michalzielanski** [phalcon/cphalcon#13535]
Please add the `close` method in the session adapters. For `Phalcon\Session\Adapter\Files`, the method should call `session_write_close()`. This will allow to close the session and unlock the session file.

http://konrness.com/php5/how-to-prevent-blocking-php-requests/
https://stackoverflow.com/questions/13651195/long-running-background-php-script-blocks-other-php-pages-until-it-is-finished

**Comment by Jurigag** [comment]
Well it's actually good idea, i actually even used it for event source that you need to close it to make everything working properly.

**Comment by niden** [comment]
@michalzielanski Thank you for reporting this. Addressed in https://github.com/phalcon/cphalcon/pull/13673
