### ISSUE TITLE
Phalcon\Validation\Validator\Url improvement

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13548]
I think this validator should accept flags.

Flag | Used with | Description
--| -- | --
~FILTER_FLAG_SCHEME_REQUIRED~ | ~FILTER_VALIDATE_URL~ | ~Requires the URL to contain a scheme part.~ **deprecated**
~FILTER_FLAG_HOST_REQUIRED~ | ~FILTER_VALIDATE_URL~ | ~Requires the URL to contain a host part.~ **deprecated**
FILTER_FLAG_PATH_REQUIRED | FILTER_VALIDATE_URL | Requires the URL to contain a path part.
FILTER_FLAG_QUERY_REQUIRED | FILTER_VALIDATE_URL | Requires the URL to contain a query string.

```php
$url->addValidator(
    new Url(
        [
            'flags' => [
                'FILTER_FLAG_PATH_REQUIRED'
        ]
    )
);
```

**Actually** given that those two flags had no effect since 5.x.x maybe we should consider custom URL validator because `filter_var` sucks. We need more control, like whether or not to consider protocol for an example. Or simply ditch Url altogether and use Regex...

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14057
