### ISSUE TITLE
To back the behavior of the cancelOnFail option

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13540]
Hello again =)

**It's a new feature request for 4.x.x branch.**
I suggest to back the behavior of the cancelOnFail option as it was in 2.x.x version.

For example, we have the sign in form:
```php
define('PRESENCE_OF_LOGIN', 'Пожалуйста, введите логин');
define('PRESENCE_OF_PASSWORD', 'Пожалуйста, введите пароль.');
define('LOGIN_EXISTS', 'Такой логин уже зарегистрирован');
define('INVALID_PWD', 'Пароль ненадёжный.');

$login = new Text('login');
$password = new Text('password');

$login->addValidators(
    [
        new PresenceOf(['cancelOnFail' => true, 'message' = PRESENCE_OF_LOGIN]),
        new Callback(
            [
                'message' => LOGIN_EXISTS,
                'callback' => function ($data) {
                    $login = is_string($data['login']) ? &$data['login'] : null; //Protection from an array
                    return (bool)User::countByLogin($login);
                }
            ]
        )
    ]
);

$password->addValidators(
    [
        new PresenceOf(['cancelOnFail' => true, 'message' => PRESENCE_OF_PASSWORD]),
        new Callback(
            [
                'message' => INVALID_PWD,
                'callback' => function ($data) {
                    $password = is_string($data['password']) ? &$data['password'] : null; //Protection from an array
                    return (int)mb_strlen($password) > 5;
                }
            ]
        )
    ]
);
$this->add($login);
$this->add($password);
```
**The current behavior:**
If the login is empty and password is unreliable, we get the next error: PRESENCE_OF_LOGIN const.

**The needed behavior:**
If the login is empty and password is unreliable, we get the next errors: PRESENCE_OF_LOGIN const AND INVALID_PWD const.

**The Conclusion**
Judge for yourselves. In the current case, the user needs to submit the form twice to find out their mistakes.
And in the new case - just one time (That makes more sense).

P.S Excuse me my english, i just from Russia)

**Comment by Jurigag** [comment]
Not sure if i understand, but why just not remove cancelOnFail? This is exactly why cancelOnFail exists. It cancel validation if validator fails.

**Comment by Jurigag** [comment]
@TimurFlush on my mistake, i just somehow read wrongly your code, yea i agree we could change this for 4.0.0, it's actually good idea.

**Comment by scrnjakovic** [comment]
+1 for this. I solved this currently with my custom `ChainValidator` which receives and validates multiple validator instances until first one fails.

**Comment by TimurFlush** [comment]
I suggest not just to return the behavior, but to make two separate flags: **cancelOnFail** and **continueOnFail**.

**cancelOnFail** will save itself behavior. 
**continueOnFail** will stop the check in the current element and move to the next one

@Jurigag @scrnjakovic

**Comment by niden** [comment]
Closing in favor of #13149
