### ISSUE TITLE
New feature for Phalcon\Mvc\Model

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13546]
Hello.

**New feature request for 4.x.x**
I suggest to write the following methods for the class \Phalcon\Mvc\Model:
1.
```
public function enableTheSupportOfCreatedAtField()
{
        $this->addBehavior(
            new \Phalcon\Mvc\Model\Behavior\Timestampable(
                [
                    'beforeCreate' => [
                        'field' => 'created_at',
                        'format' => 'Y-m-d H:i:s'
                    ]
                ]
            )
        );
}
```

2.
```
public function enableTheSupportOfUpdatedAtField()
{
        $this->addBehavior(
            new \Phalcon\Mvc\Model\Behavior\Timestampable(
                [
                    'beforeCreate' => [
                        'field' => 'updated_at',
                        'format' => 'Y-m-d H:i:s'
                    ]
                ]
            )
        );
}
```

I think it's very actually things =)

**Comment by Jurigag** [comment]
To be honest i don't like this. It should be handled be developer, some are using timestamps created by database, some doesn't need this at all.

What we could do is some trait in incubator(isn't there already thing like this?), but nothing more is needed imho.

**Comment by TimurFlush** [comment]
@Jurigag Too bad, uh, I thought those were really necessary buns(

**Comment by TimurFlush** [comment]
@Jurigag It's a shame, looking at Eloquent to understand and realize that this will not be in Phalcon ORM )

**Comment by scrnjakovic** [comment]
Nay on this from me. It's too project-specific and actually very easy to implement for those who need it :)
