### ISSUE TITLE
Add more types for PDO

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#13543]
### Expected and Actual Behavior

Some types are not recognized in the PDO. This is primarily due to the fact that MySQL/PostgreSql and Sqlite do not have the same types throughout.

This is an effort to offer more flexibility to the framework

**Comment by virgofx** [comment]
@niden ... is this issue now resolved?

**Comment by niden** [comment]
@virgofx Some tests are not passing in the original PR. I think I will merge it and fix the tests after that. There is also a huge PR coming in with the local environment

**Comment by niden** [comment]
Implemented
