### ISSUE TITLE
Main page language item is incorrect

### ISSUE THREAD

**Issue by jimmyadaro** [phalcon/cphalcon#13545]
Sorry if this should not be here and if this issue does not follow the contribution guidelines, but I've seen this errors in the **/es/ version** of the main project page.

![phalcon](https://user-images.githubusercontent.com/20187699/47298404-11101700-d5ee-11e8-9532-a3d81948ae35.png)

1. The arabic language flag is actually the Argentina flag 
2. The catalan language flag is actually the Canada flag
3. The language selector is positioned down in the menu (at least in my MBP 2011 13" 1280x800 display)

Hope this is useful somehow.

**Comment by niden** [comment]
@jimmyadaro Would you be so kind as to open this issue in the `phalcon/website` repository since it relates to that?

Thanks!

**Comment by jimmyadaro** [comment]
@niden For sure. Sorry, I didn't see that repo.
