### ISSUE TITLE
Why not to use ioc/factory style for validators like filters?

### ISSUE THREAD

**Issue by 6562680** [phalcon/cphalcon#13567]
So, when i talking with Symfony devs, they say the better way for services is DI Injector who configures using the config - you directly write the class using for the service, and then declare required interfaces in constructor.

Using the ReflectionClass stuff constructor will be like callback to Injector, who receives config declared attributes. They confirm it as easier testing - you should not write $di->get() as antipattern, you just create the object, who automatically calls injector who creates other instances and that way.

So phalcon solutions is very handly to read in future. Code looks easier (for me, subjectively).

But as i see - Forms / Validators stuff is hardly extended from Symfony code style.
I really dont understand why not to create validator class like a filter thing where we can declare callbacks and pass parameters as an array and have file with all filters or ability to require several files with filters declared like
$validator->add('name' / default params, callback);
and then call like $validator->get('name', params');

pretty easier for read, same stuff as Ioc container, phalcon like.
Of course symfony devs will explode their asses if read about it.

But can you explain me why not? Maybe there is certain reason for use that hardcoded extendable class structure for forms (select extends field) and extension for validator from validator, using message as class confusing between return as array and return as collection... 

As i think - form purpose is check data, save session/cookies/services data, get data after page reload, and collect messages / save it.

Same stuff = for model. Even it can be form interface, and model can implements it. Form is the model like class just without connection to source (i tried to create easy accessible multiple field with same name and i forced to rewrite all classes architecture because, hardcoded field class using $form->getValue() except of $element->getAttribute('value') - you cant simple print field using array as value to output next value in next field. And you cant replace value for next one in Form class, because it using in validator.

I mean forms could be combine/factory like (formfactory->get('select'));

thank you

**Comment by niden** [comment]
I will address your concerns later on today. 

Two things to note. Phalcon is not Symfony and Symfony is not Phalcon. Different developers have different views and implementations. Indeed certain aspects of the framework might be difficult for you or me to understand or use and the implementation of Symfony might be better. But that is as you mentioned subjective.

I would like to keep this discussion open in order to see how we can help developers do their job much easier. If the Symfony way is better for everyone then by all means we will adjust the code accordingly. 

Having written that, refactoring the DI container will be difficult but it is in the roadmap for v4 to make it PSR compliant.

As for the validators, have you checked the `Callback` validator?

**Comment by 6562680** [comment]
I count the same. Symf guys tells everyone that we doing all wrong. I think position where everyone has own point is more pieceful.

Tried callback validator. I just about the filters was realized handly, di container realized handly but validators realized... mmm right way?

Yep, i saw almost all framework components in zep, and really its very diffucult to just rewrite.

I want only understand - is injector better than ioc or no? is it a future, or just new symfony mem.

**Comment by niden** [comment]
`but i have channels in my telegram only one phalcon devs channel where's 82 guys total`

I don't think that there is an official Telegram channel or chat room for Phalcon. We use Discord for our communications with the community.

If you haven't tried it the link is : https://phalcon.link/discord

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
