### ISSUE TITLE
cast_on_hydrate ignored when columns are specified in Query Builder

### ISSUE THREAD

**Issue by richmilns** [phalcon/cphalcon#13581]
### Expected and Actual Behavior
With `phalcon.orm.cast_on_hydrate` set to **on**, the results from a Query Builder instance or *Model::find()* style call should cast the returned values according to the DB schema.

e.g. an **int(11)** field should be an *int* type when debugged with var_dump().

This works perfectly when using *Model::find()* style methods.

When using Query Builder with custom columns, it returns strings only and none of the values get cast according to the schema.

### Steps to Reproduce
In my bootstrap I have used **ini_set()** to set the value of *cast_on_hydrate*
`ini_set('phalcon.orm.cast_on_hydrate', 'on');` and I'm using Phalcon 3.4.0 on PHP 7.2.11.

If I use **Model::find()** style methods, *cast_on_hydrate* seems to be working fine. This changes when I use Query Builder though. Note that I'm using a multi-module style app with Model Namespacing enabled.

If I use Phalcon's Query Builder to create a simply query:
```php
$di = \Phalcon\Di::getDefault();
$modelsManager = $di->getModelsManager();
$builder = $modelsManager
     ->createBuilder()
     ->from(['Jobs' => 'Jobs:Jobs']);
$results = $builder->getQuery()->execute();
var_dump($results[0]->id); // int(87)
```
var_dump displays the result, correctly casted as an integer: `int(87) `

If I then add some columns into the mix:
```php
// using same getModelsManager() as above
$builder = $modelsManager
     ->createBuilder()
     ->columns(['Jobs.id', 'Jobs.user_id'])
     ->from(['Jobs' => 'Jobs:Jobs']);
$results = $builder->getQuery()->execute();
var_dump($results[0]->id); // string(2) "87"
```
The output from var_dump is now `string(2) "87"`

The class type of the `$results` variable with the returned data in the example above is:
`Phalcon\Mvc\Model\Resultset\Simple`. 

### Details

* Phalcon version: 3.4.0
* PHP Version: 7.2.11
* Operating System: macOS Mojave
* Installation type: installed using HomeBrew
* Zephir version (if any): -
* Server: Apache
* Other related info (Database, table schema): MySQL 5.7.24
* I raised this query in the forum first, [please see the original discussion](https://forum.phalconphp.com/discussion/18957/castonhydrate-ignored-when-columns-are-specified-in-query-builde)

Example schema:
```
CREATE TABLE `jobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `notes` text,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```

**Comment by emiliodeg** [comment]
Can you share us yours models entities too?

**Comment by richmilns** [comment]
Yep OK, here's the model
```php
<?php

namespace Modules\Jobs\Models;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Behavior\SoftDelete;
use Phalcon\Mvc\Model\Behavior\Timestampable;

class Jobs extends Model
{
    public $id;
    public $user_id;
    public $notes;
    public $created;
    public $updated;
    public $deleted;

    const DELETED = 1;
    const NOT_DELETED = 0;

    /**
     * Set the DB table name & associations
     * @return void
     */
    public function initialize()
    {
        $this->setSource('jobs');
        $this->addBehavior(
            new SoftDelete(
                [
                    'field' => 'deleted',
                    'value' => self::DELETED,
                ]
            )
        );
        $this->addBehavior(
            new Timestampable(
                [
                    'beforeCreate' => [
                        'field' => 'created',
                        'format' => 'Y-m-d H:i:s',
                    ],
                    'beforeUpdate' => [
                        'field' => 'updated',
                        'format' => 'Y-m-d H:i:s',
                    ],
                    'beforeDelete' => [
                        'field' => 'deleted_date',
                        'format' => 'Y-m-d H:i:s',
                    ],
                ]
            )
        );
    }

    /**
     * Return the jobs
     * @return Phalcon\Mvc\Model\Resultset\Simple
     */
    public static function getJobs()
    {
        $di = \Phalcon\Di::getDefault();
        $modelsManager = $di->getModelsManager();
        $builder = $modelsManager
            ->createBuilder()
            ->columns(['Jobs.id', 'Jobs.user_id'])
            ->from(['Jobs' => 'Jobs:Jobs']);
        $results = $builder->getQuery()->execute();
        var_dump($results[0]->id);exit;
        return $results;
    }
}
```

I have a very basic controller in another namespace that just called `Jobs::getJobs()` so I won't bother posting that!

**Comment by Jurigag** [comment]
Make sure to add those options to db service:

```
'options'  => [
                PDO::ATTR_EMULATE_PREPARES   => false,
                PDO::ATTR_STRINGIFY_FETCHES  => false,
            ],
```

It should then work fine. Feel free to reopen to issue if this doesn't solve your problem. You need to keep in mind that when you select columns you don't select full model and there is no types casting.

**Comment by richmilns** [comment]
Works - thank you very much @Jurigag

**Comment by emiliodeg** [comment]
> Make sure to add those options to db service:
> 
> ```
> 'options'  => [
>                 PDO::ATTR_EMULATE_PREPARES   => false,
>                 PDO::ATTR_STRINGIFY_FETCHES  => false,
>             ],
> ```
> It should then work fine. Feel free to reopen to issue if this doesn't solve your problem. You need to keep in mind that when you select columns you don't select full model and there is no types casting.

we should leave these two options set by default to `false`
