### ISSUE TITLE
Scanner: Unknown opcode 58 when trying to use :?:

### ISSUE THREAD

**Issue by terax6669** [phalcon/cphalcon#13580]
### Expected and Actual Behavior

Trying to bind a non-assoc array of arguments to a database query. I've tried `?`, `:?`, `:?:`. I know this worked in Phalcon 1.3.4, because I've used it in another project.

```php
PHP Fatal error:  Uncaught Phalcon\Mvc\Model\Exception: Scanner: Unknown opcode 58 in /tmp/op.php:18
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 [internal function]: Phalcon\Mvc\Model\Query->execute()
#2 /tmp/op.php(18): Phalcon\Mvc\Model::find(Array)
```

>Minimal script to reproduce the issue

```php
<?php

$di = new Phalcon\Di\FactoryDefault;

$db = new \Phalcon\Db\Adapter\Pdo\Mysql([
    'unix_socket' => '/var/run/mysqld/mysqld.sock',
    'username' => '',
    'password' => '',
    'dbname' => '',
]);

class User extends Phalcon\Mvc\Model
{

}

$status = 1;
User::find(['status = :?:', 'bind' => [$status]]);
```

### Details

* Phalcon version: 3.4.1
* PHP Version: 7.2.11
* Operating System: Debian 9
* Installation type: https://packagecloud.io/phalcon/stable/debian/
* Database: 10.3.10-MariaDB

**Comment by niden** [comment]
Your query needs to be either:

```php
User::find(['status = :status:', 'bind' => ['status' => $status]]);
```
or
```php
User::find(['status = ?1', 'bind' => [1 => $status]]);
```

If you use numbers then you use the `?<number>`. If you use strings then you enclose it in semicolons `:<index>:`
