### ISSUE TITLE
Phalcon Route Group do not work as expected

### ISSUE THREAD

**Issue by Abdulla1995** [phalcon/cphalcon#13588]
In my router.php file I have router group as below.

```
$router = new Router();
$api = new Router\Group();
$api->setPrefix('/api');

```
I have added multiple API routes which they are working as expected. But now I have added new route for old API user  also to be able to use old API route. 

`$api->add('/currency_converter/currency_list', 'MyController::myAction', ['GET']);`
and at the end mounting group to router. 
`$router->mount($api);`
This route is not working as expected. It always reloads the page without errors to same location but the URL address stays as `(/api/currency_converter/currency_list)` .

I have tried normal way without group which is `$router->add('/api/currency_converter/currency_list', 'MyController::myAction', ['GET']);` and it worked. 

I have inspected source code of phalcon but can't get what is the problem of this weird issue. 
Also tried as below:
```
$api->add('/currencyconverter/currency_list', 'MyController::myAction', ['GET']); //worked
$api->add('/currency_converter', 'MyController::myAction', ['GET']); //worked
$api->add('/currency_converter/currencylist', 'MyController::myAction', ['GET']); //not worked
$api->add('/currency_converter/currency_list', 'MyController::myAction', ['GET']); //not worked
$api->add('/currencyconverter/currencylist', 'MyController::myAction', ['GET']); //worked
```
I have controller named CurrencyConverterController. I guess it conflicts with Phalcon's defaults. 

### Details

* Phalcon version: Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.0
Build Date => Nov  9 2018 09:28:31
Powered by Zephir => Version 0.10.10-d1b4cc68d9

* PHP Version: PHP 7.1.3 (cli) (built: Mar 23 2017 17:19:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

* Operating System: Mac OS High Sirra 10.13.6
* Installation type: Compiling from source 
* Server: Apache

**Comment by ViltusVilks** [comment]
If it is redirected then something is defined to do that.
Firstly You need to identify how controller is named, which namespace used, is namespace auto-loaded (PSR/etc...)

For me it is works very OK.   Faked/custom-endpoint API uri to differently named controller in different namesapce and different folder with multi-module setup :)

Make sure your routes are in **CORRECT order** from above, because some routes can _"intercept"_ and say "I matched route but could not find implementation". This is why error triggered and can be catched by before-exception/before-dispatch in Dispatcher.

**Router Group**
```
$api = new Router\Group();
$api->setPrefix('/api');
$api->add('/supa_dupa/other_stuff/', [
                    'module' => 'indexer',
                    'action' => 'get',
                    'controller' => 'demo_camelcase',
                    'namespace' => 'Indexer\\Controller\\Admin',
], ['GET']);
$router->mount($api); 
```

**Request** `GET /api/supa_dupa/other_stuff/`
```
{
   "Class": "Indexer\\Controller\\Admin\\DemoCamelcaseController",
   "Action": "getAction",
   "Data": "<br \/>\n<b>Notice<\/b>:  Undefined variable: x in <b>\/var\/www\/app\/modules\/indexer\/controllers\/admin\/DemoCamelcaseController.php<\/b> on line <b>14<\/b><br \/>\n"
 }
```

Controller **DemoCamelcaseController**  source
```
<?php
namespace Indexer\Controller\Admin;

class DemoCamelcaseController extends \Phalcon\Mvc\Controller
{
    public function getAction()
    {
        $this->view->disable();
        $this->response->setContentType('application/json', 'UTF-8');
        
        ob_start();
        try
        {
            $x++;
        }
        catch (\Throwable $ex)
        {
            echo $ex->getMessage();
        }
        
        $data = ob_get_contents();
        ob_end_clean();
        
        echo json_encode([
            'Class' => __CLASS__,
            'Action' => __FUNCTION__,
            'Data' => $data
        ], JSON_PRETTY_PRINT );
        die(0);
    }
}
```
