### ISSUE TITLE
Problems when modelsMetadata caching in Redis

### ISSUE THREAD

**Issue by qishibo** [phalcon/cphalcon#13586]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

I have two phalcon projects `A` and `B`, which use the `same redis instance` as the cache. Project A uses the database `db_a`, and Project B uses the database `db_b`. These two databases contain a table with the same name, named `users`, but the structure is different. The corresponding model class names in both projects are also the same (`app\models\Users`). Then the problem comes, the metadata cache key is similar to the structure `_PHCRmeta-app\\models\\users-users`, which is "class name + table name", so the cache of two tables with the same name will overlap each other, because there is no put the `database name` into it. So I suggest that the database name should be spelled into the metadata key, so that it is completely unique, so as to prevent the above problem from happening.

Thanks

### Details

* Phalcon version: (`php --ri phalcon`)
```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.1
Build Date => Aug 27 2018 10:35:43
Powered by Zephir => Version 0.10.10-d1b4cc68d9

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```
* PHP Version: (`php -v`)

```
PHP 7.2.4-1+b1 (cli) (built: May 12 2018 13:03:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4-1+b1, Copyright (c) 1999-2018, by Zend Technologies
```
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by qishibo** [comment]
Sorry, I find the way.....

the key defined here:

https://github.com/phalcon/cphalcon/blob/caeac66e7db02fd54c44a27cf22a6381654af2ee/phalcon/mvc/model/metadata.zep#L243-L249

So do like this

```php
class Users extends Phalcon\Mvc\Model
{
    public function getSchema()
    {
        return 'db_a';
    }

    public function getSource()
    {
        return 'users';
    }
}
```

Then the key generated like this `"_PHCRmeta-app\\models\\users-db_ausers"`

**Comment by niden** [comment]
Closing as it was resolved with a different key
