### ISSUE TITLE
I absolute hate the current View code - or maybe I'm wrong

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13594]
I'm see that the engines take a single view and continue to reuse it over the course of the the lifetime.  So then I was thinking that this heavy reuse and mutation is done to make it run as fast as possible.  However then I saw the following in the `View::getRender` method:

```zephir
	public function getRender(string! controllerName, string! actionName, array params = [], configCallback = null) -> string
	{
		let view = clone this;
		view->reset();
		if typeof params == "array" {
			view->setVars(params);
		}
		// ...
		return view->getContent();
	}
```

Gosh that is weird.  Is there really such a big time difference in cloning an object vs instantiating it for several views?

Additionally the possibly identical long functions `_loadTemplateEngines` appear to be logically the same between `Phalcon\Mvc\View` and `\Phalcon\Mvc\View\Simple`.  Maybe there is a tiny difference in there but visually I could only see some difference in the comments.  Worse is that they appear to be maintained both separately with for example `==` and `!=` logic with inverted blocks between them.

To me the view code just reeks of having grown organically without ever having a refactor.  Its like it is a straight port from C land where everything is already a clusterfuck and so people just go with the fastest code path and call it a day.  It seems like its so long and smelly that nobody dares to refactor it because it works good enough and its difficult to follow.  Maybe I'm wrong.

**Comment by ViltusVilks** [comment]
Em, what is the problem? Have You read the comments/docs for this function?
It is pretty clear - `Perform the automatic rendering returning the output as a string`

If You want You always can do manual rendering and instantiate every time with some helper services utilizing Simple view

**Comment by sergeyklay** [comment]
We only accept _bug reports_ (with code to reproduce), new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
