### ISSUE TITLE
PSR-11 4.0.x Use DI Presets instead of clunky factory defaults

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13593]
I've found the Phalcon DI factory default classes to be very clunky and inflexible and so I designed a new method of creating boring default services.  These di presets are more flexible because they are both a DI that can be created and used directly and they also have the ability to extend an existing DI.  Note that I wrote it this way since at the time I couldn't find a better way to accomplish the task while working around Zephir's inflexibility.

```zephir
namespace Phalcon\Di;

use Phalcon\DiInterface;

interface PresetInterface
{

    public static function configure(<DiInterface> di);
}
```

```zephir
namespace Phalcon\Di\Preset;

use Phalcon\Di\PresetInterface;
use Phalcon\Di;
use Phalcon\DiInterface;

class Cli extends Di implements PresetInterface
{

    public static function configure(<DiInterface> di)
    {
        var serviceName, className, services;

        let services = [
            "dispatcher"           : "Phalcon\\Cli\\Dispatcher",
            // ...
        ];

        for serviceName, className in services {
            di->set(serviceName, className, true);
        }
    }

    public function __construct()
    {
        parent::__construct();

        self::configure(this);
    }
}
```

If a no-clobber setting option was added to `::configure` then a DI (from preset or vanilla) can be configured using multiple presets.  This allows extensions/packages to provide a preset to automatically configure service classes that they include in however mechanism that they want to.

So for example.

```php
$di = new Phalcon\Di;
Phalcon\Di\Preset\Cli::configure($di);
MyExtension\Di\Preset\Dev::configure($di);
```

and then later in some other bootstrap setup after the composer autoload has been brought in:

```php
Dschissler\Di\Preset\BigStuff::configure($di);
```

Also for simpler projects the standard di factory default can be instantiated directly and that is that.

```php
$di = new Phalcon\Di\Preset\Cli;
```

Now keep in mind that I'm doing things differently in my project but just to demonstrate the flexibility of this approach.

Additionally, I'm quite offended by the web-centric naming of the current factory defaults and if this proposal is not to be accepted on its technical merits then I demand that it be done so to remedy this quite offensive and incendiary language so that web and cli can exist without users of either run mode being discriminated against.

As an example of this wanton Phalcon language just observe the following:

```php
Phalcon\Di\FactoryDefault\Cli;
Phalcon\Di\FactoryDefault;
```

Do you see!  There is no web there for the web factory default.

Last night after fighting through the tears I decided to wait a day until I had calmed down enough to write about this rationally.  Phalcon should change from its web-centric beginnings to consider other run modes as equals.

[edit] I just want to thank the people who have supported me during this difficult time.  Its been a roller coaster of emotions but I feel that I'm stronger for it.

[edit] I've also just recently come out as identifying as CLI.  It just feels right for me.

**Comment by niden** [comment]
Valid points. Since you are now identifying as CLI:

```
./phalcon --say-hello-to-david
```

Joking apart, the DI container will undergo an overhaul for v4 to implement the PSR-11 interface. At that point I see no reason why we cannot extend the Di class where a simple `yml` or `json` file to name a couple, can be used for setting up services. It is very similar to your approach really.

Looking forward to hearing what the community has to say about this.

**Comment by dschissler** [comment]
As far as I'm aware the PHP yaml extension lags seriously behind to the point that its not reliable enough to use in a PHP extension.  Does PECL yaml even support PHP 7.2 now?  Additionally json 5 will be out soon enough and it provides most of the better parts of yaml with a much simpler parser.  Additionaly using json allows much easier integration with nodejs and there are better tools around json like `jq` for the CLI.  Additionally the json schema spec is coming along quite nicely and its very powerful.

Btw my pronoun is "prompt" not "you".

**Comment by JABirchall** [comment]
I agree, Phalcon factory default enables alot of things that someone may not want enabled and for me, loads the router to automatic routing. Which I prefer to define my routes explicitly. 

@dschissler PHP have been discussing dropping PECL for awhile now since its unmaintained and a PITA to use. they are looking to build a system which works simularly to composer.

**Comment by dschissler** [comment]
That is fine if they make something better than PECL but its still just made up of extensions and that code has to come from somewhere.  I've already had my heart broken by abandoned PHP extensions and I don't see how a new better repo system changes that.

**Comment by dschissler** [comment]
> At that point I see no reason why we cannot extend the Di class where a simple yml or json file to name a couple, can be used for setting up services. It is very similar to your approach really.

That is nice but how do you offer presets written in Zephir this way if it loads in a yml or json file?  I think that my approach is required for that but you could also include a `Preset::createFromFile` kind of method but then it would need to return a generic preset class that also implemented the interface.  Not too crazy.

**Comment by dschissler** [comment]
That wasn't my intention to simply undo the title change.
