### ISSUE TITLE
Missing offset in Query Builder Interface

### ISSUE THREAD

**Issue by Izopi4a** [phalcon/cphalcon#13599]
Builder class interface is missing offset function

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builder.zep

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query/builderinterface.zep

https://github.com/phalcon/cphalcon/pull/13592

**Comment by CameronHall** [comment]
This can be closed as it was implemented in #13600.
