### ISSUE TITLE
Add getStatusCode() in Phalcon\Http\ResponseInterface

### ISSUE THREAD

**Issue by ajcerezo** [phalcon/cphalcon#13618]
### Expected and Actual Behavior

I would like to add the getStatusCode method in Phalcon \ Http \ ResponseInterface, I think it is necessary because a response interface does not make sense without being able to get the status code.

```php
public function getStatusCode(): int;
```

### Details

* Phalcon version: 3.4.1
* PHP Version: 7.2.12
* Operating System: GNU/linux Ubuntu 18.04.1 LTS
* Installation type: installing via package manager
* Server: Apache
* Other related info (Database, table schema): n/a

Thanks

**Comment by stamster** [comment]
https://github.com/phalcon/cphalcon/blob/master/phalcon/http/response.zep#L228

The method is there for sure? And it certainly works. 

You propose to be added in interface as well? Well, why not, nice to have.

**Comment by niden** [comment]
This has been resolved. Thank you
