### ISSUE TITLE
Discussion if Phalcon\Config::merge should also accept a basic array

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13610]
This is the current merge code of `Phalcon\Config`.  Is there a reason why `::merge` is unable to take a basic array?

```zephir
	public function merge(<Config> config) -> <Config>
	{
		return this->_merge(config);
        }
```

```zephir
	protected final function _merge(<Config> config, var instance = null) -> <Config>
        {
```

  I've found myself overloading this `::merge` on a few occasions and I'm wondering if it shouldn't be relaxed to:

```zephir
	public function merge(var config) -> <Config>
```

and then with a simple `switch typeof config` to do the conversion if its an array.  Is there any reason why this is a bad idea, has noticeably reduced performance?

**Comment by dschissler** [comment]
What about for Phalcon 4 using a "iterable pseudo-type"?  While writing my own extension and reviewing the Phalcon code I often feel that much of it has been written around the limitations of Zephir and of course earlier PHP versions.

http://php.net/manual/en/migration71.new-features.php#migration71.new-features.iterable-pseudo-type

I've already promoted the idea that Phalcon 4 Zephir should require > PHP 7.1.  This would be a nice feature that would likely be free.

**Comment by dschissler** [comment]
@CameronHall Is there a math or CS term for "merging" that touches on set theory, etc?  I'm always for that if it is keeping with established terms, but otherwise having a "merge" and "append" that do very similar things but differing in a way that requires reading the docs just seems kind of funky.

**Comment by CameronHall** [comment]
Not that I'm aware of. You're right, I retract what I said. It would be kind of funky and really unnecessary to add another layer of complexity. I don't see any reason why we can't just make `Phalcon\Config::merge` accept arrays.

**Comment by dschissler** [comment]
Code was merged.
