### ISSUE TITLE
Mapping toArray fails

### ISSUE THREAD

**Issue by cfv1000** [phalcon/cphalcon#13623]
https://github.com/phalcon/cphalcon/blob/caeac66e7db02fd54c44a27cf22a6381654af2ee/phalcon/mvc/model/resultset/simple.zep#L193

This loop should take into account the ignoreUnknownColumns setting for models

**Comment by cfv1000** [comment]
> +1
> 
> And also we have this ways:
> 
> global.ignoreUnknownColumns (as you say above)
> columnMap
> allowedColumns
> metadata
> getters/setters
> 
> And all of it possible should be implemented.
> 
> Would be great to remove $di object from all resultsets / rows, if you want to get it - it should be method linked to get default or model manager property.
> Getting $di and keeping link in each model breaks var_dump/print_r to model - you should toArray() first. Just to display di inside.
> 
> When i printing model - i wants to see how current getters/setters + props is working and what values model have in current moment. Except of "di instance", "modelsManager instance" - enough to be bool properties "isModelManagerExists"
> 
> All of it because we can work with protected properties in model, and framework is using protected properies to save system objects.

try to implement __debugInfo magic method in your objects.

**Comment by 6562680** [comment]
my god, it was so easy???

man, you're awesome.
