### ISSUE TITLE
Phalcon\Mvc\Model assign method works on metadata, but must over passed data

### ISSUE THREAD

**Issue by 6562680** [phalcon/cphalcon#13627]
Am trying to create base rest controller with access/columns limitation per input/output.
And my rest actions is getting input data from request using previously defined in controller array of columns.

So, then i tried to write like $user->assign($this->request->getPost(), null, $allowedColumns).
In post data i provide column "password", but this column is protected in model and not exists in database at all. But i use it to create `password_hash` that will be stored in database.

When i passing $_POST['password'] to model that expected `password_hash` - nothing happens, even if i have setter for password.

There's a way to solve, just foreach data and pass directly to model through arrow what will callback. But is the assign working correctly?

That can be explained because `assign` method iterates over model metadata instead of iterating by given data using columnMap, metadata and allowedColumns just as filter.

### Details

* Phalcon version: (`php --ri phalcon`) 3.4.1
* PHP Version: (`php -v`) 7.2
* Operating System: win10

**Comment by Jurigag** [comment]
You can always override assign method but overall i agree, it's kind of pain in the ass.
