### ISSUE TITLE
router/route getRoutePath forgets to cut "controller/action" word

### ISSUE THREAD

**Issue by 6562680** [phalcon/cphalcon#13625]
You provide posibility to write routes like "Main::index" and there in the code we have parsing to namespace.

But actually, dispatcher will run "Main**Controller**" not "Main".

I wrote

```
use App\Controllers\MyController;
$router->add('/', MyController::class . '::index');
```

and receive 404 because i have controller word, what will automatically appended later.
It should be cutted before append.

### Details

* Phalcon version: (`php --ri phalcon`) 3.4.1
* PHP Version: (`php -v`) 7.2.10 zts
* Operating System: win10
* Installation type: dll file
* Zephir version (if any): ?
* Server: Apache
* Other related info (Database, table schema): MySQL 5.6

**Comment by virgofx** [comment]
This is an error in your application. This works by design. Routes should not be created using the ::class suffix as these will quickly break with namespaces.

**Comment by 6562680** [comment]
Not sure you remember the code but there is an check to namespace before controller.

So, nobody wants to hear: "your application is wrong" - its not an information for listener.
Please, when closing the topic, drop comments like "this working by design that is required by this situation" - it will make me clever and next i will answer my friends want to learn Phalcon same as you say.

But you write something like "we are good, you are bad, thats the point, bye"

**Comment by virgofx** [comment]
We only accept _bug reports_ (with code to reproduce), new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
