### ISSUE TITLE
Cannot read property on phtml engine in 3.4.2 this version

### ISSUE THREAD

**Issue by Linvas** [phalcon/cphalcon#13631]
I using .phtml for my view engine, after I upgrade 3.4.2 this version, I found it cannot use 
> <?=$config->domain->cdn?>
to get config property. Instead, I have to use 
<?=$this->config->domain->cdn?> 
why change this suddenly ?

**Comment by niden** [comment]
@Linvas This was because the implementation was wrong in the first place i.e. view vars were being exposed as globals which could _potentially_ have security implications. That was the reason behind it.

**Comment by niden** [comment]
Closing this.
