### ISSUE TITLE
Acl Resource rename

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#13639]
I suggest to rename `Resource`, because it's on soft reserved word of PHP.

---

To rename:
- [x] `Phalcon\Acl\Resource`  (???)
- [x] `Phalcon\Acl\ResourceInterface`
- [x] `Phalcon\Acl\ResourceAware` (I doubt in the necessity of this class)
---

Phalcon\Acl\Resource -> Phalcon\Acl\Subject
Phalcon\Acl\ResourceInterface -> Phalcon\Acl\SubjectInterface
Phalcon\Acl\ResourceAware -> Phalcon\Acl\SubjectAware

Phalcon\Acl\Role -> Phalcon\Acl\Operation
Phalcon\Acl\RoleInterface -> Phalcon\Acl\OperationInterface
Phalcon\Acl\RoleAware -> Phalcon\Acl\OperationAware

**Comment by scrnjakovic** [comment]
+1, especially about rethinking `ResourceInterface` and `ResourceAware`, it's bit confusing.

**Comment by Jurigag** [comment]
`ResourceAware` is interface for implementing anything which can be use as resource in `$acl->isAllowed()` `ResourceInterface` on other hand is mainly for defining Resources as classes so you can use `$acl->addResource` and add object here.

**Comment by scrnjakovic** [comment]
I still maintain this is confusing if not unnecessary, or maybe I’m missing something? Why do we need two interfaces? Anything that needs to be passed to `isAllowed` as a resource should implement `ResourceInterface`. Same goes for `addResource`. I still don’t see the reason/benefit.

**Comment by niden** [comment]
@scrnjakovic I see your point. Let me talk to the core team and see whether we can remove the aware interface and what use case serves. With 4.x coming up, now is the time to do this.

**Comment by Jurigag** [comment]
For me it's simple @scrnjakovic just check ResourceInterface, it has methods like getDescription etc. ResourceAware and RoleAware where implemented so you can for example do something like:

```php
class Article extends Model implements ResourceAware
{
    public function getResourceName()
    {
        return 'article';
    }
}
```

```php
class User extends Model implements RoleAware
{
    public function getRoleName()
    {
        return 'user';
    }
}
```

And then do:

```php
$acl = new Memory();
$acl->addResource('article', ['update']);
$acl->allow('user', 'article', ['update']);
$article = Article::findFirst();
$user = User::findFirst();
$canUpdate = $acl->isAllowed($user, $article, 'update'); // will return result
```

So pretty much `ResourceAware` and `RoleAware` allows to to pass any objects implementing them to isAllowed, while on other hand `RoleInterface` and `ResourceInterface` have methods like `getName` `getDescription` and `__toString` which can have do totally different things in many classes. They are just for defining resources and roles.

**Comment by danhunsaker** [comment]
To attempt to clarify, based on what I'm reading above, `ResourceInterface` is used to identify (and define common methods for) objects which _are_ resources, while `ResourceAware` is used to identify (and define common methods for) objects which _use_ resources. Similarly, `RoleInterface` is for roles, while `RoleAware` is for things that respect those roles.

Is that accurate? Because if so, they do serve very distinct purposes. Though I'd probably argue, at that point, that `*Aware` might be better as traits instead of interfaces.

**Comment by Jurigag** [comment]
Exactly this @danhunsaker

**Comment by danhunsaker** [comment]
Sorry for not catching the `Operation` thing the first pass.
