### ISSUE TITLE
Discussion on 4.x CORS Response helper/assistance

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13635]
It seems that every time that I turn around the CORS protection is being tightened down by browsers or CMSs by default.  Maybe everything has landed already or that its slowed down, I don't know.  Is there any way that Phalcon could help out with this stuff in the 4.x?  Perhaps its not suitable to build it into the framework but rather to just use conventions or custom private code each time.  Can anyone think of a nice way of adding built-in pre-flighting?  Its not something that I'm trying to solve right now for myself but more of something that I'd like to have in the future.  Perhaps something as simple as `indexAction` could use `indexPreflight` if it exists and `OPTIONS` is used and otherwise it would just use the normal action method.

Ideas?

**Comment by dschissler** [comment]
This is unlikely to happen for a long time.  I will reopen many months from now.

**Comment by david-duncan** [comment]
I actually see a lot of value in this.

**Comment by dschissler** [comment]
So do I, but its unlikely to happen since I'm focusing on other things.  There is a big new release to get out and IMO everything else is noise.
