### ISSUE TITLE
[NFR] Forms should also have attributes

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13646]
I suggest implementing attributes collection for `Phalcon\Forms\Form`. Like other HTML tags/elements, `<form>` has attributes as well so I don't see why we shouldn't support that?

```php
$form->setAttribute('data-field', 'myValue');
```
How would we use it?
I know there is a difference between elements and the form as you render elements with the help of the form and you render form with the help of the `Phalcon\Tag` but it would still be helpful to be able to set attributes outside of the view.

```volt
{{  form('action', myForm.getAttributes()) }}
{# or #}
{{  form(myForm) }}
{# or #}
{{ myForm.renderSelf() }}
```

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
cc @emiliodeg

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14082
