### ISSUE TITLE
Refactor Unit Tests - Add more tests

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#13655]
Refactoring unit tests and adding new ones
Tests: 3488, Assertions: 8134, Skipped: 444

#### Refactor
- [ ] Acl\Adapter\MemoryCest.php

#### Acl\Adapter\Memory
- [ ] Acl\Adapter\Memory\DropComponentAccessCest.php

#### Refactor
- [x] Annotations\Adapter\ApcuCest.php
- [ ] Annotations\Adapter\FilesCest.php
- [x] Annotations\Adapter\MemoryCest.php
- [x] Annotations\ReaderCest.php
- [x] Annotations\ReflectionCest.php

#### Annotations\Adapter\Apcu
- [ ] Annotations\Adapter\Apcu\ConstructCest.php
- [ ] Annotations\Adapter\Apcu\GetCest.php
- [ ] Annotations\Adapter\Apcu\GetMethodCest.php
- [ ] Annotations\Adapter\Apcu\GetMethodsCest.php
- [ ] Annotations\Adapter\Apcu\GetPropertiesCest.php
- [ ] Annotations\Adapter\Apcu\GetPropertyCest.php
- [ ] Annotations\Adapter\Apcu\GetReaderCest.php
- [ ] Annotations\Adapter\Apcu\ReadCest.php
- [ ] Annotations\Adapter\Apcu\SetReaderCest.php
- [ ] Annotations\Adapter\Apcu\WriteCest.php

#### Annotations\Adapter\Files
- [ ] Annotations\Adapter\Files\ConstructCest.php
- [ ] Annotations\Adapter\Files\GetCest.php
- [ ] Annotations\Adapter\Files\GetMethodCest.php
- [ ] Annotations\Adapter\Files\GetMethodsCest.php
- [ ] Annotations\Adapter\Files\GetPropertiesCest.php
- [ ] Annotations\Adapter\Files\GetPropertyCest.php
- [ ] Annotations\Adapter\Files\GetReaderCest.php
- [ ] Annotations\Adapter\Files\ReadCest.php
- [ ] Annotations\Adapter\Files\SetReaderCest.php
- [ ] Annotations\Adapter\Files\WriteCest.php

#### Annotations\Adapter\Memory
- [ ] Annotations\Adapter\Memory\GetCest.php
- [ ] Annotations\Adapter\Memory\GetMethodCest.php
- [ ] Annotations\Adapter\Memory\GetMethodsCest.php
- [ ] Annotations\Adapter\Memory\GetPropertiesCest.php
- [ ] Annotations\Adapter\Memory\GetPropertyCest.php
- [ ] Annotations\Adapter\Memory\GetReaderCest.php
- [ ] Annotations\Adapter\Memory\ReadCest.php
- [ ] Annotations\Adapter\Memory\SetReaderCest.php
- [ ] Annotations\Adapter\Memory\WriteCest.php

#### Annotations\Annotation
- [ ] Annotations\Annotation\ConstructCest.php
- [ ] Annotations\Annotation\GetArgumentCest.php
- [ ] Annotations\Annotation\GetArgumentsCest.php
- [ ] Annotations\Annotation\GetExprArgumentsCest.php
- [ ] Annotations\Annotation\GetExpressionCest.php
- [ ] Annotations\Annotation\GetNameCest.php
- [ ] Annotations\Annotation\GetNamedArgumentCest.php
- [ ] Annotations\Annotation\GetNamedParameterCest.php
- [ ] Annotations\Annotation\HasArgumentCest.php
- [ ] Annotations\Annotation\NumberArgumentsCest.php

#### Annotations\Collection
- [ ] Annotations\Collection\ConstructCest.php
- [ ] Annotations\Collection\CountCest.php
- [ ] Annotations\Collection\CurrentCest.php
- [ ] Annotations\Collection\GetAllCest.php
- [ ] Annotations\Collection\GetAnnotationsCest.php
- [ ] Annotations\Collection\GetCest.php
- [ ] Annotations\Collection\HasCest.php
- [ ] Annotations\Collection\KeyCest.php
- [ ] Annotations\Collection\NextCest.php
- [ ] Annotations\Collection\RewindCest.php
- [ ] Annotations\Collection\ValidCest.php

#### Annotations\Reader
- [ ] Annotations\Reader\ParseCest.php
- [ ] Annotations\Reader\ParseDocBlockCest.php

#### Annotations\Reflection
- [ ] Annotations\Reflection\ConstructCest.php
- [ ] Annotations\Reflection\GetClassAnnotationsCest.php
- [ ] Annotations\Reflection\GetMethodsAnnotationsCest.php
- [ ] Annotations\Reflection\GetPropertiesAnnotationsCest.php
- [ ] Annotations\Reflection\GetReflectionDataCest.php
- [ ] Annotations\Reflection\SetStateCest.php

#### Application
- [ ] Application\ConstructCest.php
- [ ] Application\GetDefaultModuleCest.php
- [ ] Application\GetDICest.php
- [ ] Application\GetEventsManagerCest.php
- [ ] Application\GetModuleCest.php
- [ ] Application\GetModulesCest.php
- [ ] Application\HandleCest.php
- [ ] Application\RegisterModulesCest.php
- [ ] Application\SetDefaultModuleCest.php
- [ ] Application\SetDICest.php
- [ ] Application\SetEventsManagerCest.php
- [ ] Application\UnderscoreGetCest.php

#### Assets\Asset\Css
- [ ] Assets\Asset\Css\SetFilterCest.php
- [ ] Assets\Asset\Css\SetLocalCest.php

#### Assets\Asset\Js
- [ ] Assets\Asset\Js\SetFilterCest.php
- [ ] Assets\Asset\Js\SetLocalCest.php

#### Assets\Collection
- [ ] Assets\Collection\AddCssCest.php
- [ ] Assets\Collection\AddFilterCest.php
- [ ] Assets\Collection\AddInlineCest.php
- [ ] Assets\Collection\AddInlineCssCest.php
- [ ] Assets\Collection\AddInlineJsCest.php
- [ ] Assets\Collection\AddJsCest.php
- [ ] Assets\Collection\ConstructCest.php
- [ ] Assets\Collection\CountCest.php
- [ ] Assets\Collection\CurrentCest.php
- [ ] Assets\Collection\GetAssetsCest.php
- [ ] Assets\Collection\GetAttributesCest.php
- [ ] Assets\Collection\GetCodesCest.php
- [ ] Assets\Collection\GetFiltersCest.php
- [ ] Assets\Collection\GetJoinCest.php
- [ ] Assets\Collection\GetLocalCest.php
- [ ] Assets\Collection\GetPositionCest.php
- [ ] Assets\Collection\GetPrefixCest.php
- [ ] Assets\Collection\GetRealTargetPathCest.php
- [ ] Assets\Collection\GetSourcePathCest.php
- [ ] Assets\Collection\GetTargetLocalCest.php
- [ ] Assets\Collection\GetTargetPathCest.php
- [ ] Assets\Collection\GetTargetUriCest.php
- [ ] Assets\Collection\JoinCest.php
- [ ] Assets\Collection\KeyCest.php
- [ ] Assets\Collection\NextCest.php
- [ ] Assets\Collection\RewindCest.php
- [ ] Assets\Collection\SetAttributesCest.php
- [ ] Assets\Collection\SetFiltersCest.php
- [ ] Assets\Collection\SetLocalCest.php
- [ ] Assets\Collection\SetPrefixCest.php
- [ ] Assets\Collection\SetSourcePathCest.php
- [ ] Assets\Collection\SetTargetLocalCest.php
- [ ] Assets\Collection\SetTargetPathCest.php
- [ ] Assets\Collection\SetTargetUriCest.php
- [ ] Assets\Collection\ValidCest.php

#### Assets\Inline
- [ ] Assets\Inline\ConstructCest.php
- [ ] Assets\Inline\GetAssetKeyCest.php
- [ ] Assets\Inline\GetAttributesCest.php
- [ ] Assets\Inline\GetContentCest.php
- [ ] Assets\Inline\GetFilterCest.php
- [ ] Assets\Inline\GetTypeCest.php
- [ ] Assets\Inline\SetAttributesCest.php
- [ ] Assets\Inline\SetFilterCest.php
- [ ] Assets\Inline\SetTypeCest.php

#### Assets\Manager
- [ ] Assets\Manager\AddAssetByTypeCest.php
- [ ] Assets\Manager\AddInlineCodeByTypeCest.php
- [ ] Assets\Manager\AddInlineCodeCest.php
- [ ] Assets\Manager\AddInlineCssCest.php
- [ ] Assets\Manager\AddInlineJsCest.php
- [ ] Assets\Manager\CollectionAssetsByTypeCest.php
- [ ] Assets\Manager\CollectionCest.php
- [ ] Assets\Manager\ConstructCest.php
- [ ] Assets\Manager\GetCollectionsCest.php
- [ ] Assets\Manager\GetCssCest.php
- [ ] Assets\Manager\GetJsCest.php
- [ ] Assets\Manager\GetOptionsCest.php
- [ ] Assets\Manager\OutputInlineCest.php
- [ ] Assets\Manager\OutputInlineCssCest.php
- [ ] Assets\Manager\OutputInlineJsCest.php
- [ ] Assets\Manager\SetCest.php
- [ ] Assets\Manager\SetOptionsCest.php
- [ ] Assets\Manager\UseImplicitOutputCest.php

#### Refactor
- [ ] Crypt\CryptCest.php

#### Crypt
- [ ] Crypt\GetCipherCest.php
- [ ] Crypt\GetHashAlgoCest.php
- [ ] Crypt\GetKeyCest.php
- [ ] Crypt\SetCipherCest.php
- [ ] Crypt\SetHashAlgoCest.php
- [ ] Crypt\SetKeyCest.php
- [ ] Crypt\UseSigningCest.php

#### Debug
- [ ] Debug\ClearVarsCest.php
- [ ] Debug\DebugCest.php
- [ ] Debug\DebugVarCest.php
- [ ] Debug\DumpCest.php
- [ ] Debug\GetCssSourcesCest.php
- [ ] Debug\GetJsSourcesCest.php
- [ ] Debug\GetVersionCest.php
- [ ] Debug\HaltCest.php
- [ ] Debug\ListenCest.php
- [ ] Debug\ListenExceptionsCest.php
- [ ] Debug\ListenLowSeverityCest.php
- [ ] Debug\OnUncaughtExceptionCest.php
- [ ] Debug\OnUncaughtLowSeverityCest.php
- [ ] Debug\SetShowBackTraceCest.php
- [ ] Debug\SetShowFileFragmentCest.php
- [ ] Debug\SetShowFilesCest.php

#### Refactor
- [ ] Di\DiCest.php
- [ ] Di\ServiceCest.php

#### Di
- [ ] GetCest: Test Di\FactoryDefault - get() 
- [ ] GetDefaultCest: Test Di\FactoryDefault - getDefault() 
- [ ] GetInternalEventsManagerCest: Test Di\FactoryDefault - getInternalEventsManager() 
- [ ] GetRawCest: Test Di\FactoryDefault - getRaw() 
- [ ] GetServiceCest: Test Di\FactoryDefault - getService() 
- [ ] GetServicesCest: Test Di\FactoryDefault - getServices() 
- [ ] GetSharedCest: Test Di\FactoryDefault - getShared() 
- [ ] HasCest: Test Di\FactoryDefault - has() 
- [ ] LoadFromPhpCest: Test Di\FactoryDefault - loadFromPhp() 
- [ ] LoadFromYamlCest: Test Di\FactoryDefault - loadFromYaml() 
- [ ] OffsetExistsCest: Test Di\FactoryDefault - offsetExists() 
- [ ] OffsetGetCest: Test Di\FactoryDefault - offsetGet() 
- [ ] OffsetSetCest: Test Di\FactoryDefault - offsetSet() 
- [ ] OffsetUnsetCest: Test Di\FactoryDefault - offsetUnset() 
- [ ] RegisterCest: Test Di\FactoryDefault - register() 
- [ ] RemoveCest: Test Di\FactoryDefault - remove() 
- [ ] ResetCest: Test Di\FactoryDefault - reset() 
- [ ] SetCest: Test Di\FactoryDefault - set() 
- [ ] SetDefaultCest: Test Di\FactoryDefault - setDefault() 
- [ ] SetInternalEventsManagerCest: Test Di\FactoryDefault - setInternalEventsManager() 
- [ ] SetSharedCest: Test Di\FactoryDefault - setShared() 
- [ ] UnderscoreCallCest: Test Di\FactoryDefault - __call() 
- [ ] SetDICest: Test Di\Injectable - setDI() 
- [ ] UnderscoreGetCest: Test Di\Injectable - __get() 
- [ ] BuildCest: Test Di\Service\Builder - build() 
- [ ] ConstructCest: Test Di\Service - __construct() 
- [ ] GetNameCest: Test get name 
- [ ] GetParameterCest: Test Di\Service - getParameter() 
- [ ] IsResolvedCest: Test Di\Service - isResolved() 
- [ ] ResolveCest: Test Di\Service - resolve() 
- [ ] SetDefinitionCest: Test Di\Service - setDefinition() 
- [ ] SetParameterCest: Test Di\Service - setParameter() 
- [ ] SetSharedInstanceCest: Test Di\Service - setSharedInstance() 

### Dispatcher
- [ ] Dispatcher\CallActionMethodCest.php
- [ ] Dispatcher\DispatchCest.php
- [ ] Dispatcher\ForwardCest.php
- [ ] Dispatcher\GetActionNameCest.php
- [ ] Dispatcher\GetActionSuffixCest.php
- [ ] Dispatcher\GetBoundModelsCest.php
- [ ] Dispatcher\GetDefaultNamespaceCest.php
- [ ] Dispatcher\GetDICest.php
- [ ] Dispatcher\GetEventsManagerCest.php
- [ ] Dispatcher\GetHandlerClassCest.php
- [ ] Dispatcher\GetHandlerSuffixCest.php
- [ ] Dispatcher\GetModelBinderCest.php
- [ ] Dispatcher\GetModuleNameCest.php
- [ ] Dispatcher\GetNamespaceNameCest.php
- [ ] Dispatcher\GetParamCest.php
- [ ] Dispatcher\GetParamsCest.php
- [ ] Dispatcher\GetReturnedValueCest.php
- [ ] Dispatcher\HasParamCest.php
- [ ] Dispatcher\IsFinishedCest.php
- [ ] Dispatcher\SetActionNameCest.php
- [ ] Dispatcher\SetActionSuffixCest.php
- [ ] Dispatcher\SetDefaultActionCest.php
- [ ] Dispatcher\SetDefaultNamespaceCest.php
- [ ] Dispatcher\SetDICest.php
- [ ] Dispatcher\SetEventsManagerCest.php
- [ ] Dispatcher\SetHandlerSuffixCest.php
- [ ] Dispatcher\SetModelBinderCest.php
- [ ] Dispatcher\SetModuleNameCest.php
- [ ] Dispatcher\SetNamespaceNameCest.php
- [ ] Dispatcher\SetParamCest.php
- [ ] Dispatcher\SetParamsCest.php
- [ ] Dispatcher\SetReturnedValueCest.php
- [ ] Dispatcher\WasForwardedCest.php

#### Refactor
- [ ] Events\ManagerCest.php

#### Events
- [ ] ConstructCest: Test Events\Event - __construct() 
- [ ] AttachCest: Test Events\Manager - attach() 
- [ ] CollectResponsesCest: Test Events\Manager - collectResponses() 
- [ ] DetachAllCest: Test Events\Manager - detachAll() 
- [ ] EnablePrioritiesCest: Test Events\Manager - enablePriorities() 
- [ ] FireCest: Test Events\Manager - fire() 
- [ ] FireQueueCest: Test Events\Manager - fireQueue() 
- [ ] GetListenersCest: Test Events\Manager - getListeners() 
- [ ] GetResponsesCest: Test Events\Manager - getResponses() 
- [ ] HasListenersCest: Test Events\Manager - hasListeners() 

#### Factory
- [ ] Factory\LoadCest.php

### Filter
- [ ] Filter\AddCest.php
- [ ] Filter\GetFiltersCest.php
- [ ] Filter\SanitizeCest.php

#### Refactor
- [ ] Flash\Direct\FlashDirectCustomCSSCest.php
- [ ] Flash\Direct\FlashDirectEmptyCSSCest.php

#### Flash
- [ ] ClearCest: Test Flash\Direct - clear() 
- [ ] ConstructCest: Test Flash\Direct - __construct() 
- [ ] ErrorCest: Test Flash\Direct - error() 
- [ ] GetAutoescapeCest: Test Flash\Direct - getAutoescape() 
- [ ] GetCustomTemplateCest: Test Flash\Direct - getCustomTemplate() 
- [ ] GetEscaperServiceCest: Test Flash\Direct - getEscaperService() 
- [ ] MessageCest: Test Flash\Direct - message() 
- [ ] NoticeCest: Test Flash\Direct - notice() 
- [ ] OutputCest: Test Flash\Direct - output() 
- [ ] OutputMessageCest: Test Flash\Direct - outputMessage() 
- [ ] SetAutoescapeCest: Test Flash\Direct - setAutoescape() 
- [ ] SetAutomaticHtmlCest: Test Flash\Direct - setAutomaticHtml() 
- [ ] SetCssClassesCest: Test Flash\Direct - setCssClasses() 
- [ ] SetCustomTemplateCest: Test Flash\Direct - setCustomTemplate() 
- [ ] SetEscaperServiceCest: Test Flash\Direct - setEscaperService() 
- [ ] SetImplicitFlushCest: Test Flash\Direct - setImplicitFlush() 
- [ ] SuccessCest: Test Flash\Direct - success() 
- [ ] WarningCest: Test Flash\Direct - warning() 
- [ ] ClearCest: Test Flash\Session - clear() 
- [ ] ConstructCest: Test Flash\Session - __construct() 
- [ ] ErrorCest: Test Flash\Session - error() 
- [ ] GetAutoescapeCest: Test Flash\Session - getAutoescape() 
- [ ] GetCustomTemplateCest: Test Flash\Session - getCustomTemplate() 
- [ ] GetEscaperServiceCest: Test Flash\Session - getEscaperService() 
- [ ] GetMessagesCest: Test Flash\Session - getMessages() 
- [ ] HasCest: Test Flash\Session - has() 
- [ ] MessageCest: Test Flash\Session - message() 
- [ ] NoticeCest: Test Flash\Session - notice() 
- [ ] OutputCest: Test Flash\Session - output() 
- [ ] OutputMessageCest: Test Flash\Session - outputMessage() 
- [ ] SetAutoescapeCest: Test Flash\Session - setAutoescape() 
- [ ] SetAutomaticHtmlCest: Test Flash\Session - setAutomaticHtml() 
- [ ] SetCssClassesCest: Test Flash\Session - setCssClasses() 
- [ ] SetEscaperServiceCest: Test Flash\Session - setEscaperService() 
- [ ] SetImplicitFlushCest: Test Flash\Session - setImplicitFlush() 
- [ ] SuccessCest: Test Flash\Session - success() 
- [ ] WarningCest: Test Flash\Session - warning() 

#### Html\Tag
- [ ] Html\Tag\FormCest.php

#### Refactor
- [ ] Http\Cookie\CookieCest.php
- [ ] Http\Request\AuthHeaderCest.php
- [ ] Http\Request\FileCest.php
- [ ] Http\Request\RequestCest.php
- [x] Http\Response\CookiesCest.php
- [ ] Http\Response\HeadersCest.php
- [ ] Http\Response\ResponseCest.php

#### Http\Cookie
- [ ] Http\Cookie\ConstructCest.php
- [ ] Http\Cookie\DeleteCest.php
- [x] Http\Cookie\GetDICest.php
- [ ] Http\Cookie\GetDomainCest.php
- [ ] Http\Cookie\GetExpirationCest.php
- [ ] Http\Cookie\GetHttpOnlyCest.php
- [ ] Http\Cookie\GetNameCest.php
- [ ] Http\Cookie\GetPathCest.php
- [ ] Http\Cookie\GetSecureCest.php
- [ ] Http\Cookie\GetValueCest.php
- [ ] Http\Cookie\IsUsingEncryptionCest.php
- [ ] Http\Cookie\RestoreCest.php
- [ ] Http\Cookie\SendCest.php
- [x] Http\Cookie\SetDICest.php
- [ ] Http\Cookie\SetDomainCest.php
- [ ] Http\Cookie\SetExpirationCest.php
- [ ] Http\Cookie\SetHttpOnlyCest.php
- [ ] Http\Cookie\SetPathCest.php
- [ ] Http\Cookie\SetSecureCest.php
- [ ] Http\Cookie\SetSignKeyCest.php
- [ ] Http\Cookie\SetValueCest.php
- [ ] Http\Cookie\ToStringCest.php
- [ ] Http\Cookie\UseEncryptionCest.php

#### Http\Request\File
- [ ] Http\Request\File\MoveToCest.php

#### Http\Response
- [ ] Http\Response\AppendContentCest.php
- [ ] Http\Response\ConstructCest.php
- [ ] Http\Response\GetContentCest.php
- [ ] Http\Response\GetCookiesCest.php
- [ ] Http\Response\GetHeadersCest.php
- [ ] Http\Response\GetReasonPhraseCest.php
- [ ] Http\Response\GetStatusCodeCest.php
- [ ] Http\Response\IsSentCest.php
- [ ] Http\Response\RedirectCest.php
- [ ] Http\Response\RemoveHeaderCest.php
- [ ] Http\Response\SendCest.php
- [ ] Http\Response\SendCookiesCest.php
- [ ] Http\Response\SendHeadersCest.php
- [ ] Http\Response\SetCacheCest.php
- [ ] Http\Response\SetContentCest.php
- [ ] Http\Response\SetContentLengthCest.php
- [ ] Http\Response\SetContentTypeCest.php
- [ ] Http\Response\SetCookiesCest.php
- [ ] Http\Response\SetEtagCest.php
- [ ] Http\Response\SetExpiresCest.php
- [ ] Http\Response\SetFileToSendCest.php
- [ ] Http\Response\SetHeaderCest.php
- [ ] Http\Response\SetJsonContentCest.php
- [ ] Http\Response\SetLastModifiedCest.php
- [ ] Http\Response\SetNotModifiedCest.php
- [ ] Http\Response\SetRawHeaderCest.php
- [ ] Http\Response\SetStatusCodeCest.php

#### Http\Response\Cookies
- [ ] Http\Response\Cookies\ConstructCest.php
- [ ] Http\Response\Cookies\DeleteCest.php
- [ ] Http\Response\Cookies\GetCest.php
- [ ] Http\Response\Cookies\GetCookiesCest.php
- [ ] Http\Response\Cookies\HasCest.php
- [ ] Http\Response\Cookies\IsUsingEncryptionCest.php
- [ ] Http\Response\Cookies\ResetCest.php
- [ ] Http\Response\Cookies\SendCest.php
- [ ] Http\Response\Cookies\SetCest.php
- [ ] Http\Response\Cookies\SetSignKeyCest.php
- [ ] Http\Response\Cookies\UseEncryptionCest.php

#### Http\Response\Headers
- [ ] Http\Response\Headers\GetCest.php
- [ ] Http\Response\Headers\HasCest.php
- [ ] Http\Response\Headers\RemoveCest.php
- [ ] Http\Response\Headers\ResetCest.php
- [ ] Http\Response\Headers\SendCest.php
- [ ] Http\Response\Headers\SetCest.php
- [ ] Http\Response\Headers\SetRawCest.php
- [ ] Http\Response\Headers\SetStateCest.php
- [ ] Http\Response\Headers\ToArrayCest.php

#### Refactor
- [ ] Image\Adapter\ImagickCest.php

#### Image
- [ ] DestructCest: Test Image\Adapter\Gd - __destruct() 
- [ ] LiquidRescaleCest: Test Image\Adapter\Gd - liquidRescale() 
- [ ] BlurCest: Test Image\Adapter\Imagick - blur() 
- [ ] CheckCest: Test Image\Adapter\Imagick - check() 
- [ ] GetHeightCest: Test Image\Adapter\Imagick - getHeight() 
- [ ] GetImageCest: Test Image\Adapter\Imagick - getImage() 
- [ ] GetMimeCest: Test Image\Adapter\Imagick - getMime() 
- [ ] GetRealpathCest: Test Image\Adapter\Imagick - getRealpath() 
- [ ] GetTypeCest: Test Image\Adapter\Imagick - getType() 
- [ ] GetWidthCest: Test Image\Adapter\Imagick - getWidth() 
- [ ] LiquidRescaleCest: Test Image\Adapter\Imagick - liquidRescale() 
- [ ] PixelateCest: Test Image\Adapter\Imagick - pixelate() 
- [ ] RenderCest: Test Image\Adapter\Imagick - render() 
- [ ] SetResourceLimitCest: Test Image\Adapter\Imagick - setResourceLimit() 

#### Security
- [ ] HashCest.php
- [ ] Random\BytesCest.php

**Comment by niden** [comment]
Some guidelines:

The list above contains all the test stubs that correspond to each public method of each component of the framework. 

Some of those stubs will be removed or renamed. For instance if we are testing `setDI` we need to use `getDI` to validate it. In that case we can change the `Cest` file to `GetSetDICest` and have one test.

Please communicate below if you are taking on a particular set of tests so that we do not duplicate work.

If you are refactoring old tests, please ensure that if there is a link to an issue in the test's docblock, that link is copied to your new test.

Also please ensure that if there is an `@author` tag in the docblock, that same tag gets moved over to the new test. We need to ensure that credit is given to contributors that helped with tests in the past.

If you are writing brand new tests, feel free to adjust the `@since` and `@author` tags of the docblock. It would be great if you could use only your github profile but if you wish you can use your email address.

**Comment by jenovateurs** [comment]
Hi @niden ,
I'm currently working on the tests of Phalcon\Annotations\Reflection/*.
And I noticed that the ReflectionCest file contains all the missing tests in the Reflection folder.
What can I do? Do I move the tests? Or do I remove the Need Implementation ?

Thanks for your answer

**Comment by jenovateurs** [comment]
I work on Assets/Manager tests ;-).
