### ISSUE TITLE
Refactor CLI Tests - Add more tests

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#13654]
- [x] GetOptionCest: Test Cli\Dispatcher - getOption() 
- [x] GetReturnedValueCest: Test Cli\Dispatcher - getReturnedValue() 
- [x] GetTaskNameCest: Test Cli\Dispatcher - getTaskName() 
- [x] GetTaskSuffixCest: Test Cli\Dispatcher - getTaskSuffix() 
- [x] HasOptionCest: Test Cli\Dispatcher - hasOption() 
- [x] IsFinishedCest: Test Cli\Dispatcher - isFinished() 
- [x] SetActionNameCest: Test Cli\Dispatcher - setActionName() 
- [x] SetActionSuffixCest: Test Cli\Dispatcher - setActionSuffix() 
- [x] SetDefaultActionCest: Test Cli\Dispatcher - setDefaultAction() 
- [x] SetDefaultTaskCest: Test Cli\Dispatcher - setDefaultTask() 
- [x] SetHandlerSuffixCest: Test Cli\Dispatcher - setHandlerSuffix() 
- [x] SetReturnedValueCest: Test Cli\Dispatcher - setReturnedValue() 
- [x] SetTaskNameCest: Test Cli\Dispatcher - setTaskName() 
- [x] SetTaskSuffixCest: Test Cli\Dispatcher - setTaskSuffix() 
- [x] WasForwardedCest: Test Cli\Dispatcher - wasForwarded() 
- [x] AddCest: Test Cli\Router - add() 
- [x] ConstructCest: Test Cli\Router - __construct() 
- [x] GetActionNameCest: Test Cli\Router - getActionName() 
- [x] GetMatchedRouteCest: Test Cli\Router - getMatchedRoute() 
- [x] GetMatchesCest: Test Cli\Router - getMatches() 
- [x] GetModuleNameCest: Test Cli\Router - getModuleName() 
- [x] GetParamsCest: Test Cli\Router - getParams() 
- [x] GetTaskNameCest: Test Cli\Router - getTaskName() 
- [x] CompilePatternCest: Test Cli\Router\Route - compilePattern() 
- [x] ConstructCest: Test Cli\Router\Route - __construct() 
- [x] DelimiterCest: Test Cli\Router\Route - delimiter() 
- [x] ExtractNamedParamsCest: Test Cli\Router\Route - extractNamedParams() 
- [x] GetBeforeMatchCest: Test Cli\Router\Route - getBeforeMatch() 
- [x] GetCompiledPatternCest: Test Cli\Router\Route - getCompiledPattern() 
- [x] GetConvertersCest: Test Cli\Router\Route - getConverters() 
- [x] GetDelimiterCest: Test Cli\Router\Route - getDelimiter() 
- [x] GetNameCest: Test Cli\Router\Route - getName() 
- [x] GetPatternCest: Test Cli\Router\Route - getPattern() 
- [x] GetRouteIdCest: Test Cli\Router\Route - getRouteId() 
- [x] ReConfigureCest: Test Cli\Router\Route - reConfigure() 
- [x] ResetCest: Test Cli\Router\Route - reset() 
- [x] SetNameCest: Test Cli\Router\Route - setName() 
- [x] SetDefaultActionCest: Test Cli\Router - setDefaultAction() 
- [x] SetDefaultModuleCest: Test Cli\Router - setDefaultModule() 
- [x] SetDefaultTaskCest: Test Cli\Router - setDefaultTask() 
- [x] SetDefaultsCest: Test Cli\Router - setDefaults() 
- [x] WasMatchedCest: Test Cli\Router - wasMatched() 
- [x] HasCest: Test Di\FactoryDefault\Cli - has()

**Comment by sergeyklay** [comment]
Refs:
- [Codeception: Suite Configuration](https://codeception.com/docs/reference/Configuration#Suite-Configuration)
- [Codeception's CLI suite](https://github.com/Codeception/Codeception/blob/2.5/tests/cli.suite.yml)
- [Codeception::Modules::CLI](https://github.com/Codeception/base/blob/2.4/docs/modules/Cli.md)

**Comment by npfedwards** [comment]
Having a go at some of the currently skipped ones. Might have enough to bother pulling in by the end of the week.

**Comment by ruudboon** [comment]
Implemented tasks https://github.com/phalcon/cphalcon/pull/14453

**Comment by ruudboon** [comment]
Few more tests left. Will pick this up in this sprint as well so we can clean up a bit. :D

**Comment by ruudboon** [comment]
All tests are in! 🎉
