### ISSUE TITLE
MySQL point field support missing

### ISSUE THREAD

**Issue by cnyyk** [phalcon/cphalcon#13670]
There's no ```point``` type support via https://docs.phalconphp.com/en/3.4/api/Phalcon_Db_Column.

When try to save point value to point field, error occurs:
```
SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field
```

@alsosee https://stackoverflow.com/a/27967277/9386595

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
Related https://github.com/phalcon/cphalcon/issues/14769

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/17029
