### ISSUE TITLE
Feature request for 4.x branch: add hiding certain variables on the page for Phalcon\Debug

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13687]
Hello.

For the convenience and security of some developers, I propose to add hiding environment variables from the report page of Phalcon\Debug as in Laravel.

![default](https://user-images.githubusercontent.com/29764676/50387577-8a78d280-0721-11e9-854d-b209cf0bc127.PNG)

**Comment by niden** [comment]
Resolved
