### ISSUE TITLE
[NFR] Validation - Change field(s) in failed message

### ISSUE THREAD

**Issue by AdryanSignor** [phalcon/cphalcon#13685]
# Overview
Add an option to set the name(s) of the field(s) other than the name of the model attribute in the message object returned by the validation object.

# Use cases
## UC 1
Working with Uniqueness validation, internal fields can be hidden.

## UC 2
Working without field mapping for forms / APIs inputs

# Example
```php
<?php

use Phalcon\Mvc\Model;
use Phalcon\Validation;
use Phalcon\Validation\Validator\Uniqueness;
use Phalcon\Validation\Validator\PresenceOf;

class Category extends Model {

	private const UNIQUE_ATTRIBUTE = ['name', 'accountId'];

	private $name;

	private $accountId;

	private $attribute;

	//...

	public function validation(): bool {
		$this->_messages = [];

		$validation = new Validation();

		#USE CASE 1
		$validation->add(self::UNIQUE_ATTRIBUTE, new Uniqueness([
			'label' => 'category name',
			'aliasField' => 'name'
		]));

		#USE CASE 2
		$validation->add('attribute', new PresenceOf([
			'aliasField' => 'category_attribute'
		]));

		return $this->validate($validation);
	}
}
```

```php
<?php

$category = new Category();
$category->setName('Test');
$category->setAccountId(1);
$category->setAttribute('foo');
$category->save();

$category2 = new Category();
$category2->setName('Test');
$category2->setAccountId(1);

if (!$category2->save()) {
	foreach ($category2->getMessages() as $error) {
		echo 'Message: ' . $error->getMessage() . PHP_EOL;
		echo 'Field:' . $error->getField() . PHP_EOL;
		echo PHP_EOL;
	}
}

// Message: Field category name must be unique
// Field: name
// 
// Message: Field attribute is required
// Field: category_attribute
//
```

# Details
Phalcon version: 3.4.2
PHP Version: 7.2.13
Operating System: GNU/Linux Fedora 29
Installation type: Compiled
Zephir version (if any): n/a
Server: Apache
Other related info (Database, table schema): MariaDB 10.3.10

**Comment by cnyyk** [comment]
Also need a way to customize the validation message for default notNullValidations.
Model.zep line 2201:
```let this->_errorMessages[] = new Message(attributeField . " is required", attributeField, "PresenceOf"),```

Now, it seems  no possibility to change the default notNullValidations messages

**Comment by AdryanSignor** [comment]
@cnyyk 

> Also need a way to customize the validation message for default notNullValidations.
> Model.zep line 2201:
> `let this->_errorMessages[] = new Message(attributeField . " is required", attributeField, "PresenceOf"),`
> 
> Now, it seems no possibility to change the default notNullValidations messages

@cnyyk I understand is complicated to do this, field validation could follow a PresenceOf annotation, so it would be possible to contruct the object according to the already predefined rules of this class.
Something like this:

```
<?php

use Phalcon\Mvc\Model;

class Category extends Model {

    // without null=false
    /**
     * @var string
     * @Column(column='name', type='string', length=100)
     * @PresenceOf(message='The field "attribute" is really required')
     */
    private $attribute;

    //...
}
```

To solve this question "manually", I had to disable orm.not_null_validations and set the PresenceOf rule in entity validation.
This way:

```
<?php

use Phalcon\Mvc\Model;
use Phalcon\Validation;
use Phalcon\Validation\Validator\PresenceOf;

class Category extends Model {

    private $attribute;

    //...

    public function validation(): bool {
        $this->_messages = [];

        $validation = new Validation();

        $validation->add('attribute', new PresenceOf([
            'message' => 'The field "attribute" is really required',
        ]));

        return $this->validate($validation);
    }
}
```

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
