### ISSUE TITLE
Repository packages instalation naming and versioning breaking

### ISSUE THREAD

**Issue by rudiservo** [phalcon/cphalcon#13705]
Guys, it's great that phalcon is getting attention and all, but here is the thing,

if you have a package on the server, and suddenly you put a 4.0 Alpha replacing a stable 3.4.4, nothing good is going to happen (nothing good has happen)!

So either:

1. change the package to php7.2-phalcon4
2. don't put alphas in production repos.
3. name a php7.2-phalcon-alfa for alpha only

Please don't do this again...

**Comment by sinbadxiii** [comment]
I agree

**Comment by koskiOvaa** [comment]
Please, please don't do this again. Please don't break the stable.

What I did now to stay in an actual stable release (after I just casually ran apt-get upgrade...):

`sudo apt-get remove php7.2-phalcon`
`sudo apt-get install php7.2-phalcon=3.4.2-2+php7.2`
`sudo apt-mark hold php7.2-phalcon`

(To unhold the package: apt-mark unhold php7.2-phalcon).

Disclamer: please correct me if I'm wrong. I just learned the above by reading docs.

**Comment by rudiservo** [comment]
@koskiOvaa yes you are about right, but I think you don't need to remove to revert to a previous version.

The issue here is how to organize the repositories and what will the convention be about what version goes in them.
I am not angry with this, it is an honest mistake, it happens, and for those who don't know this is one of the hardest things to organize and decide, so kudos for the maintainers for trying.

in my case it is a bit of a problem because we got a lot of projects on phalcon in a shared hosting environment, so it would break a lot of stuff in production, also since it is a major version means that things will break no matter what.
The good thing and bad thing about phalcon is that it is built in php extension, you don't have to update the framework in every project but you might have to fix some stuff that actually breaks, I'm ok with it I just need a graceful period for production changes.

So the hardest thing to decide is when do you break stuff, because I for one don't want to anyone to maintain and update version 3 and 4 at the same time, it takes a lot of time of coarse, but also breaking things also leaves  a nasty surprise in the morning and some phone calls.

the only thing I can give is suggestion and a bit a help.

**Comment by koskiOvaa** [comment]
Is it now that php7.2-phalcon=3.4.2-x.x.x.x will not get any new updates or fixes through  https://packagecloud.io/phalcon/stable/ubuntu/ bionic main - now that that repository upgraded to 4.0.x ?

**Comment by dschissler** [comment]
Maybe you could unpublish the Phalcon 4 alpha 1 and then push it out as `phalcon4-php7.2-unstable`.  Then remove the `-unstable` when its released.  I like the `phalcon4` part first (without Phalcon minor version) because if there ever was something like a PPA for a default Ubuntu distro then it would line up better.  I think that its fine to break development machines with something minor like this than to continue affecting everyone who just wants to easily update, upgrade their LTS server.

**Comment by dschissler** [comment]
Btw I'm still trying to live down breaking a server when Ubuntu 18.04 quietly slipped in an Image Magick policy XML setting that by default turned off the stuff that I do.  What are you guys trying to do to me here?

**Comment by ajcerezo** [comment]
I think you can not release a non-stable version in a stable repository (https://packagecloud.io/phalcon/stable/ubuntu/ bionic main)
Unstable packages should go to a non-stable repository (for example: https://packagecloud.io/phalcon/(alpha|beta|non-stable)/ubuntu/ bionic main)

**Comment by sergeyklay** [comment]
Please take a look https://stackoverflow.com/a/54066201/1661465

**Comment by dschissler** [comment]
Now I should be able to work on my alternative Phalcon bash setup scripts.  I'm going to take a look at the variables available between a git clone and package install to see if some of the variables can be combined.  Then I'll create a separate repo with the same thing to setup Phalcon as well as my extension framework.  You guys can then link to the Phalcon only one.  I see that my scripts are better for setting up a development machine and the box ones are better for testing.

**Comment by koskiOvaa** [comment]
sudo apt-get upgrade on "stable" seems to work now again as one might expect. Or what do you think @rudiservo ?

Thank you for fixing this!

**Comment by rudiservo** [comment]
@koskiOvaa yes it's a big step forward, now we only need to have our apps updated to phalcon4 before it moves to stable.

@sergeyklay @niden Thanks for fixing

**Comment by ajcerezo** [comment]
@sergeyklay  and @niden  Thank for fixing.

**Comment by niden** [comment]
Closing this one. Again sorry for the mixup everyone. There is a new channel in https://packagecloud.io/phalcon (mainline) for alpha/beta releases
