### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by elcreator** [phalcon/cphalcon#13701]
As stable PHP 7.3 released, have we support soon?

**Comment by niden** [comment]
Yes of course. We are working on the 7.3 release too. I am pretty sure that when v4 is out as stable it will support php 7.3

v4 has a lot of changes and we wanted to push out an alpha release to give the community a lot of time to find out potentially bugs as well as to see what will happen when trying to refactor existing applications.

**Comment by sergeyklay** [comment]
I am working on this in these days

**Comment by virgofx** [comment]
Remi has a build of phalcon that works on 7.3 just FYI.

**Comment by sergeyklay** [comment]
Remi Collet have never run our test suite ;-)

**Comment by sergeyklay** [comment]
Also FYI: https://forum.phalconphp.com/discussion/18959/cssmin-not-minifying-css-files

**Comment by ViltusVilks** [comment]
Released 7.2.14 and 7.3.1 with more segfaults/bufferoverflow fixes (SPL/opcache/Core/opcode), may be something related?

**Comment by sergeyklay** [comment]
Implemented:

- https://travis-ci.org/phalcon/cphalcon/builds/477834654
- https://github.com/phalcon/cphalcon/pull/13757

Notice: Latest known Xdebug does not work properly on PHP 7.3
