### ISSUE TITLE
Add psr as a mandatory module to the zend_module_dep

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#13702]
Todo for @sergeyklay

**Comment by dschissler** [comment]
@sergeyklay This would be a good one to get into v4-alpha4.  That will give plenty of time to work out any build issue stuff that comes up well in advance of a beta.

**Comment by sergeyklay** [comment]
I'll do that in a near future.

**Comment by ruudboon** [comment]
@sergeyklay I see some Zephir features are added Zephir 0.12.2. What is left before we can close this?

**Comment by sergeyklay** [comment]
Yes. Thank you
