### ISSUE TITLE
Prefix support for Phalcon\Mvc\Model\Metadata\Redis

### ISSUE THREAD

**Issue by CameronHall** [phalcon/cphalcon#13717]
I'd like to propose key prefixing support on `Phalcon\Mvc\Model\Metadata\Redis`. I've been extending the class since Phalcon 2.0 and I think it's about time it becomes a part of the framework.

**Comment by CameronHall** [comment]
For some reason, it never occurred to me that Phalcon creates a new instance of `Phalcon\Cache\Backend\Redis` and passes all the options given to the `Phalcon\Mvc\Model\Metadata\Redis` constructor straight to the Redis Cache adapter. So it's already possible. I'll still submit a PR to clean up the options in the `Phalcon\Mvc\Model\Metadata\Redis` constructor as they're made redundant in `Phalcon\Cache\Backend\Redis::__construct`.

**Comment by niden** [comment]
Implemented
