### ISSUE TITLE
Upgrade 3.42 to 4.0,Some errors occurred during the upgrade:PHP Fatal error:  Class 'psr\container\containerinterface' not found in Unknown on line 0,Can give me some help?

### ISSUE THREAD

**Issue by Tccui** [phalcon/cphalcon#13716]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://docs.phalconphp.com/en/latest/generating-backtrace as reference

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by niden** [comment]
@Tccui Have a look at the changes and this blog post

https://blog.phalconphp.com/post/upgrading-to-v4-alpha-1

You need to have the `PSR` extension installed before you load Phalcon.

**Comment by Tccui** [comment]
It works，thanks very much
