### ISSUE TITLE
Upgraded to php7.2-phalcon:amd64 (3.4.2-2+php7.2, 4.0.0-alpha1-1+php7.2): core dump on php start

### ISSUE THREAD

**Issue by alar77** [phalcon/cphalcon#13715]
### Expected and Actual Behavior

> Just trying to run php -i

Core dump attached
[core.zip](https://github.com/phalcon/cphalcon/files/2712984/core.zip)

```php -i 
root@giovanni-pc:/etc/php/7.2/cli# php -i
Errore di segmentazione (core dump creato)

```

> Provide minimal script to reproduce the issue

```php -i

```

### Details

* Phalcon version: (`php --ri phalcon`) crashes
* PHP Version: (`php -v`)  Crashes
* PHP Version: (`php -nv`)  PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )

* Operating System: Linux giovanni-pc 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Installation type: Both Compiling from source and installing via package manager
* Zephir version (if any):
* Server: Apache and simple command line
* Other related info (Database, table schema):

**Comment by alar77** [comment]
Ok, I had a look to release notes and looks like there are some new requirements
So the bgug is not that is crash but probbaly the fact that an apt update happily installed and alpha version over a stable one even if apt list clearly states: 
phalcon_stable.list contains
```
this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/phalcon/stable

deb https://packagecloud.io/phalcon/stable/ubuntu/ bionic main
deb-src https://packagecloud.io/phalcon/stable/ubuntu/ bionic main
```

**Comment by niden** [comment]
@alar77 Did the `psr` extension loaded before solve the issue?

I agree we need a bit more work on the packages to ensure that psr is loaded before the main extension.

Apologies for this, this is really new for all of us so we are learning as we go.

**Comment by alar77** [comment]
I was in a hurry to end a task for a customer which is using phalcon, so I just cloned v 3.4.x and compilend and installed for source.
That obviously fixed the issue.
I didnt go the install psr extension way because phalcon 4.x.x is tagged as "non backward compatible" so I really didnt want it.

Now that I know I can restore a working phalcon quickly I'll try to repeat the update and install psr extension but afaik it's not packaged (that's probably why you could not add it as a dependency) and having to manually compile something to installa a packaged component sort of voids the whole point of havint things packaged :)

Btw, you dont need to apologize. Phalcon is an amazing piece of software and it's free... minor issues in packaging are absolutely acceptable.
