### ISSUE TITLE
Idea for extending the automatic setup of services along how InjectionAwareInterface already works

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13728]
Towards the end of the `DI:get` method the service can have the service set with the DI automatically if the service object implements the `InjectionAwareInterface` interface.

```zephir
if typeof instance == "object" {
    if instance instanceof InjectionAwareInterface {
        instance->setDI(this);
    }
}
```

This is good but I want to extend the DI to be able to run a `setup` method on the service so that more automatic setup is done.  I'm still experimenting with this so I haven't concluded anything.  It seems that for now I need to create my own DI class to achieve this so I'm simply taking the Phalcon DI and giving it a new namespace.

I'm about to add the following to my version that will be something like the following.  For initial tests I'll make the service classes set a flag after the first `setup` call so that the method can be called twice.  The idea is that the services can be setup custom.  Later I might add something like `wasSetup` but I don't particularly like that at this time.  I want to maintain flexibility for the custom case while still making the auto default work well.

```zephir
if typeof instance == "object" {
    if instance instanceof InjectionAwareInterface {
        instance->setDI(this);
    }

    // Setup with default values.
    if instance instanceof SetupInterface {
        instance->setup();
    }
}
```

So that is the feature hard coded but I'm thinking that it would be better if the DI class could have a function assigned to it that would allow for this customization.

```zephir
if typeof instance == "object" {
    if instance instanceof InjectionAwareInterface {
        instance->setDI(this);
    }

    if !is_null(this->getSetupFunc) {
        call_user_func(this->getSetupFunc, this, instance);
    }
}
```

Then probably in PHP for most users (but in my case done in Zephir).

```php
function ($di, $service) {

    // Setup with default values.
    if ($service instanceof SetupInterface) {
        $service->setup();
    }
}
```

The idea is that people could extend the DI to autoset their services anyway that they like.  I haven't concluded anything so its possible that I suck, but I think that its good.

**Comment by ViltusVilks** [comment]
Hm. There is already possible to instantiate service with anonymous func when consumed. Do whatever you want inside.

Isnt the same thing you want to achieve?

**Comment by dschissler** [comment]
Yes but too much boilerplate goes into setting up these services.  Its currently either all of the boilerplate setup is done automatically with no way to interrupt it or it needs to be written out every time in the service definition.  Its impossible to have a clean opinionated layer on top of Phalcon because Phalcon insists that everything is highly generic.  There is no way to hide any of this away.

Lets not forget the DI factory default session service which appeared to be usable on first glance but needs to be manually setup for it to work.  That misleading situation existed for the first three major releases.  Its the same related problem is that any service worth a damn is broken and worthless without boilerplate setup.

**Comment by dschissler** [comment]
There is one method that sets thing up and that is using a constructor with a default value like [Phalcon\Mvc\Router](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/mvc/router.zep#L102).  That is fine for this one use but it could also be done using something like my SetupInterface idea.

Its a just very minor gripe but I've been annoyed by needing to pass in false to the router to be able to use it in a custom matter.  I think that a better API would be to simply configure the object if you want and then if you do so it doesn't auto configure it (true/false in the constructor in the MVC router).

@sergeyklay @niden Would you consider a pull request from me for 4.0 if I added this in?  I realize that its much far too late in the process to do something radical in 4.0 but I think that I could put in a tiny bit of code that wouldn't have any meaningful performance impact (only checking if a variable is null).  Then I could have all of the nice things.  You'll be able to see all of the nice things in my upcoming Zephir and Phalcon based framework that I've been working on for quite a while now.  Then when Phalcon 5.0 comes around I can bring in the best of the ideas into mainline Phalcon.  I'm simply exploring some concepts that nobody else in the community is doing publicly.  If you aren't interested then I can maintain a modified DI in my project.

**Comment by dschissler** [comment]
Ahh so after working on this I remember something that I'd forgotten.  Relying on the service class constructor for setup is incredibly limited because it doesn't yet have access to the DI.  That is a good most of the problem right there.  For a second there I was wondering "Why don't I just rely on the constructors more?" and then I remembered the issue that they are limited.

**Comment by dschissler** [comment]
This is currently working for me:

```zephir
if typeof instance == "object" {
    if instance instanceof InjectionAwareInterface {
        instance->setDI(this);
    }

    // Automatically setup instances.
    if instance instanceof SetupInterface && !instance->shouldSetup() {
        instance->setup();
    }
}
```

```zephir
namespace Project\Di\Service;

interface SetupInterface
{
    public function setup(array options = []);

    public function shouldSetup() -> boolean;
}
```

Then of course I noticed that `DI::getShared` short circuits a lot of the checking logic so I'll switch to using that internally.  Now I have a loader, cli and web router that self-starts completely setup for my DI preset/factory default.

I'm considering changing the `setup(array options = [])` to `setup(var options = true)` so that `setup(false)` can be called to cleanly disable auto-setup in a custom service without adding another method to the interface.  The idea is that for custom setup that it doesn't call anything other than publically available methods and so it can be redone in a custom way.  Also if someone just wants to augment the setup then they can pass in data to the `setup` method.

**Comment by ViltusVilks** [comment]
Yep, but this is why You can override setDi() in service and start consuming any config services.

`
$di->addShared( ...
$svc = new MyService($options);
return $svc;
);

MyService::setDi($di) {
    if ($di->has(...))
     ....
    $this->letSetupSomething("interesting");
}
`

**Comment by jturbide** [comment]
Don't get into the trap of overthinking/overengineering something that require to be as flexible as possible. I'm not sure if I understood right, but this is kind of what I see: 

https://github.com/phalcon/forum/blob/master/app/provider/AbstractServiceProvider.php
https://github.com/phalcon/forum/blob/master/app/provider/

**Comment by dschissler** [comment]
I see that there are some abstracted things but really they are still just putting the setup into these classes that are specific to that project.  What I'm doing is creating an opinionated layer around Phalcon provided by a zephir extension and a composer development package.  To reiterate, in the forum software they are doing the same old stuff but they've just moved the service boilerplate junk to wrapper classes specific to that project.  Phalcon doesn't have a single generalized framework.  "Phalcon Framework" no it is not.  Phalcon has projects and a library, not a single framework.

**Comment by ViltusVilks** [comment]
You still can use EventsManager and fire event in your generic service. Listener is exact thing which is project or even module dependant stuff.

Other way - see how cache implemented. There is frontend and backend adapters which can be initialized for specific project in many ways.

Phalcon is complete framework because it has DI and eventing. You can do anything whatever you want ot of the box now.

**Comment by dschissler** [comment]
@ViltusVilks Ok thanks for the advice but I'm not quite sure if you know what I'm trying to do.  An events manager setup for a service is a perfect way to hack new features into a project but it doesn't seem suitable for autoconfiguring instances before the user receives them.  I could force the setting of an events manager on specific services but then it seems that I would have violated their service definition if they had chosen to customize it.  I love the events manager but its best left as a ultimate way for them to hack new peculiar stuff into a project.  I've creating an opinionated framework layer over Phalcon and it doesn't seem appropriate.

I've been looking at the source of `DI::get` and the events manager class and it doesn't quite seem to do what I need.  The issue is that if the service definition is just coming as a string (default service) then its not going to have an events manager yet for the otherwise perfect `di:afterServiceResolve` event.  I don't see how I can do that with a service coming from a factory default DI.  I've created my own which I call presets.  It seems that they would not be capable of being setup this way to if a string definition is being used to autoconfigure.  I feel like that I'm close but I don't see a solution with the events manager.

**Comment by niden** [comment]
@dschissler Based in your comment above, you pretty much want another "hook" if you like to do additional setup for your object - correct me if I am wrong here.

Based on your snippet:

```zephir
if typeof instance == "object" {
    if instance instanceof InjectionAwareInterface {
        instance->setDI(this);
    }

    // Automatically setup instances.
    if instance instanceof SetupInterface && instance->shouldSetup() {
        instance->setup();
    }
}
```

```zephir
namespace Project\Di\Service;

interface SetupInterface
{
    public function setup(array options = []);

    public function shouldSetup() -> boolean;
}
```
Why the `shouldSetup`? One would assume that since you implement the `SetupInterface` then you need additional setup no?

**Comment by dschissler** [comment]
@niden `shouldSetup` isn't strictly necessary.  The trick is making it autosetup and also being able to turn that off for custom setup in the service definition.  So I'm thinking that it could just use the shouldSetup internally in the service to prevent it being setup twice.

In the service.

```php
public function setup($options = true)
{
    // Prevent multiple setups.
    if ($this->hasSetup) {
        return;
    {

    $this->hasSetup = true;

    // Prevent autosetup in a service so that it can be custom setup.
    // Later the DI call to setup will drop out in the first conditional.
    if ($options === false) {
        return;
    }

    // All of the setup is done with public methods so it can be done custom in the annon function.
}
```

Then in the service:

```php
function()
    $thing = new Thing();
    $thing->setDI($this);

    // Disable autosetup.
    $thing->setup(false);

    // Or instead tweak the setup.
    $thing->setup([
        'differently' => 123,
    ]);

    // Or just do it all manually.
    $this->registerStuff(1234);
    $this->enableThings('abc');
}
```

Jeeze though, whats really needed is for Zephir to support traits.

**Comment by ViltusVilks** [comment]
Still do not get the point? As I said this is done mostly with custom anonymous call in services definition and this is how is done "custom booting".

And just remembered one more way - **ServiceProviderInterface**. It acts like a "Load additonal services on top of the base". So You can customize there project specific setup too.

And look at the Di FactoryDefault approach... it is a Factory/Builder pattern. You can provide pre-configured builder/factory, if You want to share your code with composer. You can also provide  MyThing\ServiceProviders\FactoryDefault

in code
```
$di->register(new MyThing\ServiceProviders\FactoryDefault());
```

Like in AspNet(Core 2.0/2.1), you have simple IoC pattern. You register service, it has some lambda/func for boot, also can be used any other service as constructor parameter. 

In Phalcon You do exact the same way, except that PHP executes code always from top to end and additional CPU ticks will lower req/sec. It is not like in pooled app (NETCore) - **veeeeeery** custom and heavy boot and fast middleware processing (CoR pattern)

**Comment by dschissler** [comment]
I'm not sure that I understand all that you are writing.  I think that I could go a service factory default from my DI preset/FD for each but I would still run into the scenario where there is no autoconfig happening after the DI has been added.  Look at `DI:get` to see what I mean.

I'm still not aware of a built-in mechanism that first sets the DI on the instance, **then** runs the setup on the instance while allowing the class to be interchangeable with any other similar class while still allowing the FD class to be extended as normal.  My solution does this and others so far fail to achieve all aspects of this.  The FD solution you proposed is pretty good but if the FD style can't be extended itself (for the reasons I've long written about) then once the user wants to make changes they are forced to copy all of the setup out of the service FD in zephir to php and then begin making modifications.  I'd prefer a more flexible approach where they can completely do it custom this way or to pick and choose from the options in`setup(var options)`.  Maybe I want all of the FD setup and only want to tweak one thing that has been provided for me by a setup option.  Then with feedback I can make the setup handle a few more basic cases before they have to go rogue coding.

**Comment by dschissler** [comment]
In case that I'm just not getting what you are saying I welcome anyone to supply some 10 line code blocks to demonstrate what the heck.

**Comment by ViltusVilks** [comment]
First, provide real world example with working phalcon app to see why separate setup is needed.

**Comment by dschissler** [comment]
Yeah I'll give you that.

**Comment by dschissler** [comment]
@niden @ViltusVilks I have some updates.  I was working on getting the provision tool [setupify](https://github.com/perch-foundation/setupify) out and now I'm working on Perch extension again.  I' working on getting the Perch extension into better shape for the initial code drop.  In the meantime any other dramatically different solution is going to be a "nope, won't work", "nope", "nope", etc.

I've come up with a real code working solution that works well and allows flexibility:

`DI::get`

```zephir
            if typeof instance == "object" {
                if instance instanceof InjectionAwareInterface {
                    instance->setDI(this);
                }

                // Automatically setup instances.
                if instance instanceof SetupInterface {
                    instance->setup();
                }
            }
```

The more flexible setup would be to allow the DI to run an user supplied anonymous function at that moment:

```zephir
            if typeof instance == "object" {
                if instance instanceof InjectionAwareInterface {
                    instance->setDI(this);
                }

                // Automatically setup instances.
                if this->getConfigFunc !== null {
                    call_user_func(this->getConfigFunc, ...);
                }
            }
```

Then something like:

```php
$di->setConfigFunc(function($instance) {
    if $instance instanceof SetupInterface {
        $instance->setup();
    }
})
```

Amusingly, since Zephir has very poor support of anon functions I'd likely need to supply the config function by a static class method.

Here is my project specific loader.  It needs to have access to the DI to provide auto-setup capabilities.  Notice that the steps in `performSetup` are publicly accessible.  I will likely improve it to allow the user to add project specific namespaces.  I've covered many of the basics that I feel are bread and butter.

```zephir
namespace Perch;

use Phalcon\DiInterface;
use Phalcon\Di\InjectionAwareInterface;
use Phalcon\Loader;
use Perch\Application\Config as AppConfig;
use Perch\Di\Service\SetupInterface;

class Loader extends Loader implements InjectionAwareInterface, SetupInterface
{
    protected _dependencyInjector;

    protected shouldSetup = true;

    public function getDI() -> <DiInterface>
    {
        return this->_dependencyInjector;
    }

    public function setDI(<DiInterface> di)
    {
        let this->_dependencyInjector = di;
    }

    public function setup(array options = null)
    {
        // Prevent multiple setups.
        if (!this->shouldSetup) {
            return;
        }

        let this->shouldSetup = false;

        // Prevent autosetup in a service so that it can be custom setup.
        // Later the DI call to setup will drop out in the first conditional.
        if (is_null(options)) {
            return;
        }

        this->performSetup(options);
    }

    public function registerComposerAutoloader()
    {
        var composerAutoloadFile, config, paths;

        let config = <AppConfig> this->_dependencyInjector->get("config");
        let paths = config->offsetGet("paths");

        // Run composer autoload.
        let composerAutoloadFile = paths->offsetGet("composerPackageDir") . "autoload.php";
        if (is_file(composerAutoloadFile)) {
            require composerAutoloadFile;
        }
    }

    public function registerAppNamespaces()
    {
        var config, namespaces, paths;

        let config = <AppConfig> this->_dependencyInjector->get("config");

        let namespaces = config->offsetGet("namespaces");
        let paths = config->offsetGet("paths");

        this->registerNamespaces([
            namespaces->offsetGet("abstracts")   : paths->offsetGet("abstractsDir"),
            namespaces->offsetGet("commands")    : paths->offsetGet("commandsDir"),
            namespaces->offsetGet("controllers") : paths->offsetGet("controllersDir"),
            namespaces->offsetGet("forms")       : paths->offsetGet("formsDir"),
            namespaces->offsetGet("models")      : paths->offsetGet("modelsDir"),
            namespaces->offsetGet("plugins")     : paths->offsetGet("pluginsDir"),
            namespaces->offsetGet("app")         : paths->offsetGet("libraryDir")
        ], true);
    }

    protected function performSetup(array options = [])
    {
        this->registerComposerAutoloader();
        this->registerAppNamespaces();
    }
}
```

If Zephir provided traits then it would be real nice.  For now I'll just be using the `setup` method as a paste-in.

The loader with traits:

```zephir
namespace Perch;

use Phalcon\DiInterface;
use Phalcon\Di\InjectionAwareInterface;
use Phalcon\Loader;
use Perch\Application\Config as AppConfig;
use Perch\Di\Service\SetupInterface;

class Loader extends Loader implements InjectionAwareInterface, SetupInterface
{
    use DIInjectableTrait;
    use SetupTrait;

    public function registerComposerAutoloader()
    {
        var composerAutoloadFile, config, paths;

        let config = <AppConfig> this->_dependencyInjector->get("config");
        let paths = config->offsetGet("paths");

        // Run composer autoload.
        let composerAutoloadFile = paths->offsetGet("composerPackageDir") . "autoload.php";
        if (is_file(composerAutoloadFile)) {
            require composerAutoloadFile;
        }
    }

    public function registerAppNamespaces()
    {
        var config, namespaces, paths;

        let config = <AppConfig> this->_dependencyInjector->get("config");

        let namespaces = config->offsetGet("namespaces");
        let paths = config->offsetGet("paths");

        this->registerNamespaces([
            namespaces->offsetGet("abstracts")   : paths->offsetGet("abstractsDir"),
            namespaces->offsetGet("commands")    : paths->offsetGet("commandsDir"),
            namespaces->offsetGet("controllers") : paths->offsetGet("controllersDir"),
            namespaces->offsetGet("forms")       : paths->offsetGet("formsDir"),
            namespaces->offsetGet("models")      : paths->offsetGet("modelsDir"),
            namespaces->offsetGet("plugins")     : paths->offsetGet("pluginsDir"),
            namespaces->offsetGet("app")         : paths->offsetGet("libraryDir")
        ], true);
    }

    protected function performSetup(array options = [])
    {
        this->registerComposerAutoloader();
        this->registerAppNamespaces();
    }
}
```

**Comment by dschissler** [comment]
I've noticed that its too much code floating around and Zephir doesn't have traits.  I'm trying a simplified approach that only requires the user to implement a single method.  I changed `setup` to `autosetup`.  Now `autosetup` takes only a single argument for disabling the autosetup.  It used to take an array options but that was too much.

```zephir
interface AutosetupInterface
{
    public function autosetup(bool disable = false);
}
```

Just implement the `AutosetupInterface` and it will be run.  You don't need to implement anything else to start with but without extra work the autosetup won't be cancelable.

```zephir
class Thing implements AutosetupInterface
{
    public function autosetup(bool disable = false)
    {
        // do stuff
    }
}
```

If you want to allow it to be canceled in a service function definition then record if disable was set to true.

```zephir
class Thing implements AutosetupInterface
{
    public function autosetup(bool disable = false)
    {
        if disable || !this->autosetupEnabled {
            let this->autosetupEnabled = false;
            return;
        }

        // do stuff
    }

}
```

Then in the service set it up like this:

```php
function() {
    $thing = new Thing();
    $thing->autosetup(false);
    // more customizations here.    
}
```

The `autosetup` could check settings to determine if steps should be taken.  The user might have already configured something.  This approach allows autosetup to be added to many classes that weren't built with it in mind.  The new interface doesn't dictate too much.

This is unlikely to be useful for single projects but it really offers a lot to opinionated framework developers like myself.  The important part is to only call publically accessible methods inside the `autosetup` so that it can be done a different way.  It is possible to design the internal steps using flags so that the autosetup would never need to be explicitly disabled.  That is ideal but unlikely to happen immediately for all classes.  In the meantime there are a variety of ways to support it in the meantime.

**Comment by dschissler** [comment]
I'm going to close this issue for now since the evolution of my APIs has lead me to a path in which this can be done with the `di:afterServiceResolve` event.  I'm still convinced that the way that I originally wanted to do it is not possible using a DI event.  I came up with a really tight bit of code that could be pasted around but Zephir doesn't support traits and so its not good enough.  I feel that I'm missing a bit of flexibility but with the event I should be able to accomplish anything within my classes.  In the end its not at all clear cut and mostly about moving forward.

**Comment by dschissler** [comment]
I want to add that my final approach wouldn't have been possible with Zephir finally supporting anonymous functions.  As far as I'm concerned, one day they just appeared in the documentation and I looked very not that long ago.
