### ISSUE TITLE
Problem to update packege php7.2-phalcon in version 3.4.2 to 4.0.0-alpha1

### ISSUE THREAD

**Issue by ajcerezo** [phalcon/cphalcon#13726]
### Expected and Actual Behavior

I'm using the php7.2-phalcon package in version 3.4.2, when I updated the OS packages this package has been updated to version 4.0.0-alpha1, I just want to use stable versions of the phalcon package, but in this way I can not do it.

Thanks and happy new year!!!

### Details

* Phalcon version: 3.4.2
* PHP Version: 7.2.13-1
* Operating System: Ubuntu
* Installation type: installing via package manager
* Zephir version (if any):
* Server: Apache

**Comment by vleboulanger** [comment]
I have same problem : https://stackoverflow.com/questions/54004316/phalcon-choose-version-to-install

**Comment by Nazariy** [comment]
Possibly duplicate https://github.com/phalcon/cphalcon/issues/13705#issuecomment-450125147

**Comment by ajcerezo** [comment]
Thanks for response, and sorry for duplicating this issue.
I proceed to close this incident because it is duplicated

**Comment by sergeyklay** [comment]
@ajcerezo https://stackoverflow.com/a/54066201/1661465
