### ISSUE TITLE
php 7.2.13 report error message "PHP Fatal error:  Class 'psr\container\containerinterface' not found in Unknown on line 0"

### ISSUE THREAD

**Issue by anziguoer** [phalcon/cphalcon#13729]
download cphalcon 3.4.2, phalcon.so report error  : 
PHP Fatal error:  Class 'psr\container\containerinterface' not found in Unknown on line 0

download cphalcon 4.0.0, phalcon.so report error the same  "PHP Fatal error:  Class 'psr\container\containerinterface' not found in Unknown on line 0"

use php7.3 version report message the same.

the system is ubuntu18.10

**Comment by dschissler** [comment]
It sounds like you have the 4.0.0 version installed already. Uninstall the Phalcon extension and then install 3.4.2.  I'm guessing that you are using the package repository.

I might as well just post it here.  User `koskiOvaa` came up with this.

```
sudo apt-get remove php7.2-phalcon
sudo apt-get install php7.2-phalcon=3.4.2-2+php7.2
sudo apt-mark hold php7.2-phalcon
```

**Comment by rudiservo** [comment]
This is a problem related to phalcon4, and speaking of it I tried to compile it, anter I install psr on 7.3 (compiled and thru pecl) still go the same error.
