### ISSUE TITLE
virtual column always be updated when model->save(). virtual column should be auto avoid.

### ISSUE THREAD

**Issue by cnyyk** [phalcon/cphalcon#13737]
### Expected and Actual Behavior

> Virtual column always be updated when model->save(), and error raised: could not set value to virtual field. And when do model update, virtual column should be auto skipped. Now must be added all virtual column via model->skipAttributes to avoid this. I mean, if possible, 4.0 release should consider include this feature.

### Details

* Phalcon version: 3.4.2
* PHP Version: 7.2
* Operating System: macOS
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Apache
* Other related info (Database, table schema):

**Comment by niden** [comment]
@cnyyk can you provide an example please?

**Comment by cnyyk** [comment]
### Expected and Actual Behavior

> Virtual column always be updated when model->save(), and error raised: could not set value to virtual field. And when do model update, virtual column should be auto skipped. Now must be added all virtual column via model->skipAttributes to avoid this. I mean, if possible, 4.0 release should consider include this feature.

SQL schema
```sql
DROP TABLE IF EXISTS `demos`;
CREATE TABLE `demos`
(
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `first_name` varchar(32) COLLATE utf8mb4_unicode_520_ci NOT NULL COMMENT 'First Name',
  `last_name`  varchar(32) COLLATE utf8mb4_unicode_520_ci NOT NULL COMMENT 'Last Name',
  `full_name`  varchar(64) GENERATED ALWAYS AS (concat_ws(' ', `first_name`, `last_name`)) VIRTUAL COMMENT 'Full Name',
 PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci COMMENT ='Demos';
```

> Provide minimal script to reproduce the issue

```php
class Demos extends \Phalcon\Mvc\Model {
}
```

```php
$demo = new Demos();
$demo->firstName = 'Bill';
$demo->lastName = 'Gates';
$result = $demo->save(); // $result === true, everything goes well, record saved into db.


$demo = Demos::findFirst($demo->id);
var_dump($demo);
// firstName: Bill
// lastName: Gates
// fullName: Bill Gates
$demo->firstName = 'Jeff';
$demo->lastName = 'Bezos';
$result = $demo->save(); // Exception: could not set value to virtual field 'full_name'
```

MUST DOING THIS WAY TO AVOID EXCEPTION:

```php
// MUST BE ADD VIRTUAL COLUMN TO SKIP ATTRIBUTES
$demo->skipAttributes( [ 'fullName' ] ); // or did this in Models\Demos.php initialize();
$result = $demo->save(); // $result === true
```


SO, IS THERE A POSSIBILITY TO ADD VIRTUAL COLUMN TO SKIP ATTRIBUTES AUTOMATICLY WITHIN PHALCON FRAMEWORK?


### Details

* Phalcon version: 3.4.2
* PHP Version: 7.2.15
* Operating System: macOS 10.14.3
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Apache
* Other related info (Database, table schema):

**Comment by niden** [comment]
I had a look at this and this cannot be done automatically. There is a way to do it _manually_ when setting up the model. 

The underlying table uses `GENERATE ALWAYS` on a field. This is specific to mysql and cannot be reported back using PDO which Phalcon uses so Phalcon cannot know which column is a _virtual_ based on a calculation in the database.

Examples on how you can do this:

```php
<?php

use Phalcon\Mvc\Model;

class Demos extends Model
{
    public function initialize()
    {
        // Skips fields/columns on both INSERT/UPDATE operations
        $this->skipAttributes(['fullName']);

        // Skips only when inserting
        $this->skipAttributesOnCreate(['fullName']);

        // Skips only when updating
        $this->skipAttributesOnUpdate(['fullName']);
    }
}
```

**Comment by niden** [comment]
Closing this

**Comment by cnyyk** [comment]
OK.  Thanks for your reply.
Now we read all fields attributes when model init then auto add all virtual fields into skip list to avoid this issue.
