### ISSUE TITLE
BadMethodCallException: Wrong number of parameters

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13733]
I compiled and installed psr.so (v0.6.1) and phalcon.so (v4.0.0-alpha1) and using PHP (v7.3.0 + Zend v3.3.0-dev) and using Nginx + PHP-FPM (v1.15.8) Everything compiled and installed succesffuly under Arch Linux. However, I can't get even basic micro app to work for me now. This worked perfectly under phalcon v3.

```php
<?php

use Phalcon\Mvc\Micro;

$debug = new \Phalcon\Debug();
$debug->listen();

$app = new Micro();

$app->get('/', function() {
	echo '<h1> Phalcon v4.0 </h1>';
});

$app->handle();
```

Here is another example with basic app that worked with v3 which gives exactly same error.
```php
echo $app->handle()->getContent();
```

Never had such issues with phalcon v3, what has changed in v4 that it would trow this errors ? Is this a bug or am I doing something wrong here?

**Comment by ViltusVilks** [comment]
Handle now has mandatory parameter (uri) which to handle.

**Comment by niden** [comment]
Closing since this is the new behavior

**Comment by infatu8** [comment]
the dosc was so bad
https://github.com/phalcon/docs/blob/4.0/en/api/Phalcon_Application.md
