### ISSUE TITLE
NativeArray No Longer Works in Phalcon v4.0

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13739]
Is this a bug? [1] Phalcon v4.0 removed "getPaginate()" and now paginator no longer works!

[1] https://forum.phalconphp.com/discussion/19173/nativearray-no-longer-works-in-phalcon-v40

**Comment by v00v** [comment]
@CameronHall WOW I would never think the solution was this simple. I can't beliave it I haven't tried it LOL My apologies for reposting the link here from the forum. But I trually tought this was a bug. Would like to see this type of changes in changelog examples somewhere or at least in documentation in the future. Thank you so much for your help buddy!

**Comment by CameronHall** [comment]
Don't worry about it! :)
> Would like to see this type of changes in changelog examples somewhere or at least in documentation in the future.
I believe @niden has been hard at work on the docs and the latest 4.0 docs should come out soon.
