### ISSUE TITLE
Why can't I find our version update strategy?

### ISSUE THREAD

**Issue by dongasai** [phalcon/cphalcon#13731]
If inscribe,I could not understand the version update strategy of this project correctly, which gave me the illusion that the version you used could be updated at any time and would not be backward-compatible. I think this is very bad.

The lack of an "LTS" version was the main reason my friend refused to use the project.
I can't explain this to them, it's really bad, I hope I can recommend something good to them.

**Comment by dschissler** [comment]
They haven't broken LTS or semver exactly.  They slipped in an alpha version of the upcoming 4.0 into the repository.  There is a solution for this in another issue.  They were doing a lot of work for over a month and they now appear to be dormant.  The team never recruited and retained talent to provide uninterrupted support. This is Phalcon life.

**Comment by dschissler** [comment]
I might as well just post it here.  User `koskiOvaa` came up with this solution for alpha 4.0 packages being included in the package repository..

```
sudo apt-get remove php7.2-phalcon
sudo apt-get install php7.2-phalcon=3.4.2-2+php7.2
sudo apt-mark hold php7.2-phalcon
```

**Comment by ruudboon** [comment]
See also https://github.com/phalcon/cphalcon/issues/13705 
The team is doing the best they can and @dschissler feel free to help out the Phalcon community by sending in pull requests

**Comment by dongasai** [comment]
I don't think I have expressed myself correctly, What I want to say is:
It should be explicitly noted that those versions are long maintained, those versions are backward compatible, and those versions are not backward compatible.

but:
@jturbide  @ruudboon @dschissler  The problem described is how to install a version

**Comment by dongasai** [comment]
I'm terribly sorry that I didn't read the blog

**Comment by dongasai** [comment]
But I think we also need a similar set with "https://nodejs.org/en/download/" version of the page, to the user guide

**Comment by ruudboon** [comment]
New docs are in the making. I agree it would be nice if this basic information can be easily found. Let's wait how the new docs will look and open an issue if still needed.

**Comment by dschissler** [comment]
@ruudboon My time has come and gone for helping out in that sort of way.  What is needed is overlapping permissions and responsibilities to overcome tardy behaviour.  Oh but that would be a cold day in hell in this project.  So I'm resigned to get what I get as I put my time into my own overlapping Zephir project.  Well others want to know and this is how I think on the matter.  Any solution is going to come for new blood.  Personally as a lesson from Phalcon I will run my project differently and that is I will give full commit access to everyone in the organization after they've simply proven themselves with some good commits.  Then they will only lose access if they become inactive for a long time or do really stupid stuff.  I'll maintain package push access and versioning for NPM and Composer until someone proves themselves.  I'll just see how that goes.

**Comment by sergeyklay** [comment]
Please see https://stackoverflow.com/a/54066201/1661465
