### ISSUE TITLE
Wrong data type returned for JSON field

### ISSUE THREAD

**Issue by cnyyk** [phalcon/cphalcon#13743]
### Expected and Actual Behavior

> When get data types from metadata of a json field, wrong type returned(TYPE_VARCHAR=2), should be return TYPE_JSON=15.

SQL schema
```sql
DROP TABLE IF EXISTS `demos`;
CREATE TABLE `demos`
(
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `metadata` json  NULL DEFAULT NULL COMMENT 'Meta Data',
 PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci COMMENT ='Demos';
```

> Provide minimal script to reproduce the issue

```php
class Demos extends \Phalcon\Mvc\Model {
}
```

And there's no attributes defined in model class.

Now get field type from metadata and SQL DSL:

```php
// Get types from metadata
$demo = new Demo();
$fieldTypes = $demo->getModelsMetaData()->getDataTypes( $demo );
var_dump($fieldTypes);

// Get types from dsl
$result = $this->getReadConnection()->query( 'SHOW FULL COLUMNS FROM demos' );
$result->setFetchMode( \Phalcon\Db::FETCH_ASSOC );
while ( $obj = $result->fetch() ) {
	var_dump($obj['Field']);
	var_dump($obj['Type']);
}
```

will output
```
array(
    'id' => 14,
    'metadata' => 2
)

string "id"
string "bigint(20) unsigned"
string "metadata"
string "json"
```

### Details

* Phalcon version: 3.4.2
* PHP Version: 7.2.11
* Operating System: macOS 10.14.2
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Apache
* Other related info (Database, table schema): 

![wx20190108-212611](https://user-images.githubusercontent.com/275233/50833443-1cbcdf80-138c-11e9-8de2-b5667aa32f64.png)

**Comment by cnyyk** [comment]
got it. thanks for reply, @JABirchall .

**Comment by niden** [comment]
@cnyyk 3.x does not support JSON. We introduced those column types in 4.0 and from the tests we have they do return the correct type. 

Now for v3 you can do what @JABirchall mentioned. Text field and `json_encode`/`json_decode` on it.

**Comment by niden** [comment]
The `JSON` type was there (id 15) as you mentioned - for v3 but the implementation happened in v4.

Just FYI
