### ISSUE TITLE
Fatal error:  Uncaught Error: Access to undeclared static property: Phalcon\Di::$_default

### ISSUE THREAD

**Issue by hks2002** [phalcon/cphalcon#13760]
when i use ajax send an request, this error comes out frequently.
but i use the same url in one new page, it works fine! I keep the new page, then fresh the page contains ajax request. It works fine also.

### Details

* Phalcon version: 3
* PHP Version: 7.2.13
* Operating System: windows
* Installation type: binary .dll distribute.
* Zephir version (if any):
* Server:  Apache24
* Other related info (Database, table schema):

**Comment by hks2002** [comment]
With Apache you have to use the Thread Safe (TS) versions of PHP.

**Comment by CameronHall** [comment]
Please check out the latest reply on #12056. https://github.com/phalcon/cphalcon/issues/12056#issuecomment-453997034
