### ISSUE TITLE
Fatal error when returning empty resultset from database

### ISSUE THREAD

**Issue by byfareska** [phalcon/cphalcon#13763]
> [Sun Jan 13 15:09:50 2019] PHP Fatal error:  Uncaught TypeError: Return value of App\Entity\User::findFirst() must implement interface Phalcon\Mvc\ModelInterface, boolean returned in /home/eska/PhpstormProjects/obrazy/src/Entity/User.php:122

I'm getting this, because it returns false. Maybe change it to null?

**Comment by niden** [comment]
Can you provide more information please? Phalcon version, sample code etc.

Thank you

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by SmartyGunjan** [comment]
Phalcon 4.1
PHP 7.4
nginx centos 8
Please let me know as I am getting the same error.
Fatal error: Uncaught TypeError: Return value of TransactionDetail::findFirst() must implement interface Phalcon\Mvc\ModelInterface, null returned in /usr/share/nginx/html/luminous_api/models/TransactionDetail.php:152 Stack trace: #0 /usr/share/nginx/html/luminous_api/models/CceLeaddata.php(832): TransactionDetail::findFirst() #1 /usr/share/nginx/html/luminous_api/models/CceLeaddata.php(572): CceLeaddata->createConsumerProject() #2 /usr/share/nginx/html/luminous_api/index.php(770): CceLeaddata->createLeadData() #3 [internal function]: Closure->{closure}() #4 /usr/share/nginx/html/luminous_api/index.php(2502): Phalcon\Mvc\Micro->handle() #5 {main} thrown in /usr/share/nginx/html/luminous_api/models/TransactionDetail.php on line 152
