### ISSUE TITLE
Code correction Suggestions

### ISSUE THREAD

**Issue by dongasai** [phalcon/cphalcon#13765]
In this file:
```
phalcon/cache/backend/file.zep
```
There is a similar piece of code:
```
let prefixedKey =  this->_prefix . this->getKey(keyName);
```

I think this is used for compositing the names of the final cache keys,But shouldn't this code be part of the "getKey" method? Why is it replicated in multiple places, which I think is bad

**Comment by ViltusVilks** [comment]
Because it is proxy function for "use safe key" in File. and cache key still needs to be The Key and not the final prefixed key (partitioned cache).

Yes,  getPrefixedKey() can be implemented, but it is just another function call (+1 operation in call-stack?).

**Comment by dongasai** [comment]
I mean there is duplication in this code:
```
this->_prefix . this->getKey(keyName)
```

**Comment by niden** [comment]
@dongasai The cache will be rewritten (actually it is halfway done). I agree there is a lot of duplication in certain adapters and have cleaned up quite a bit in the Session for instance but more needs to be done.

**Comment by dongasai** [comment]
~(｡≧3≦)ﾉ⌒☆

**Comment by niden** [comment]
Closing this. We can revisit if need be when the cache is refactored
