### ISSUE TITLE
General discussion: Explaining the magic...

### ISSUE THREAD

**Issue by joeyhub** [phalcon/cphalcon#13778]
I'm finding quite a lot of magic in Phalcon which is not only not unusual for frameworks but something I often dabble in myself (including coding by convention, etc).

The problem is that if ill explained or not obvious things sometimes just magically work or worse not work and it's really confusing.

This includes things such as this:

	/**
	 * Phalcon\Di constructor
	 */
	public function __construct()
	{
		var di;
		let di = self::_default;
		if !di {
			let self::_default = this;
		}
	}

Which I bumped into in an issue where my model class Users somehow isn't able to get something I've definitely put in Di (which it's getting through Di::getDefault it turns out). for various reasons I'd accidentally instantiated the di twice (copied a switch statement of two things I want's to separate and forgot to remove that from the second set). When you hit that it's one thing but then you start to wonder well what about things like the static functions on a collection and you realise these short hands are kind of messy.

Generally speaking I'm wondering if it might be worth thinking about ways to document this kind of thing more clearly especially to the effect of clearly demonstrating direct use versus magic under the hood as in here's how to do it the exact way but here's also the magic?

For this kind of thing I'm also thinking there should almost be a magic keyword that could be used to label things doing that. Phalcon does already as least help a bit making it easy to jump to the source though that becomes awkward when multiple layers are in play. This isn't only a phalcon issue as anywhere you go you find poorly explained magic (sort of one of the reasons perl could get so so confusing syntactically eventually to be replaced with python).

This is a potentially expansive subject with the intention for people to share their experiences and thoughts. Especially around describing, identifying and perhaps how to better document magic as well as make better implementation choices when using it.

**Comment by dschissler** [comment]
One thing that bothers me is `Phalcon\Mvc\Model::setup` but I don't know what to do about it.  I think that it really sucks that potentially many code regions could require a static call to set themselves up properly.
