### ISSUE TITLE
[REQUEST] Phalcon JSON Flat-File CRUDS Support

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13783]
Can we have a good (CRUDS: Create, Read, Update, Delete, Search)
 JSON adapter in Phalcon? For people who need good basic flat-file json for offline localhost development or small production projects that do not require full databaseses. It can use similar function names like in Phalcon ODM [1].

[1] https://docs.phalconphp.com/3.2/en/db-odm

Examples:
* https://github.com/filebase/Filebase
* https://github.com/typicode/lowdb
* https://github.com/Greg0/Lazer-Database

**Comment by Jeckerson** [comment]
IMO, your request is not for phalcon core, but is for external PHP library

**Comment by ViltusVilks** [comment]
For CRUD you can use existing Cache with persistance (File adapter). Just make sure you have specified path.

One big JSON file will have performance issue, cache always is faster (KV storage).

```
class OfflineModelBase implements IOfflineModel
{
	function getById($id)
	{
	  $schema = $this->getSchema();
	  $table =  $this->getSource() ?? get_class($this);
	  return $this->cacheForOfflineDB->get("{$schema}.{$table}.${id}");
	}
```

**Comment by TimurFlush** [comment]
@v00v Why don't you consider SQLite?

**Comment by ViltusVilks** [comment]
@TimurFlush SQLite is schema RDBMS, JSON is schemaless.

Of cause you can use SQLite to store serialized json strings but will not be able to query. The same for file-storage, but for small projects you can create some custom "indexing" stuff.

But I would suggest to use MongoDB Atlas cluster, which is free for 512Mb of data (compressed), and this is very big dataset. Already using this.

**Comment by v00v** [comment]
@TimurFlush SQLite is a database, and what I'm requesting is pure JSON flat-file storage  support with CRUDS type functions for simplicity right from Phalcon.

@ViltusVilks Why would I use MangoDB Atlas if I want flat-file? I know about MangoDB and SQLite and what I'm asking is different. The idea behind basic CRUDS JSON flat-file support is to use it for offline development without the need for any other database and ability to be able to create/read/edit this JSON files manually if needed.

**Comment by ViltusVilks** [comment]
You can take a look into WiredTiger, but you need php extension to be compiled.
https://github.com/kjdev/php-ext-wiredtiger

Basically You can re-implement MongoDB, incl. indexing/searching stuff.
Yes, it is not flat-file, but it is close to DB, like a caching. Huh.. but no searching by default.

**Comment by niden** [comment]
To clear any confusion. 

@v00v  thank you for the suggestion. Definitely something to consider in the near future.

In our recent hangout on youtube, I mentioned that we are working on a `Storage` class, to offer CRUD for storage (file, memcached, redis etc.). That class will be used by developers but also internally by other components such as cache, logger etc.

We can easily implement a JSON storage adapter there where you can use a simple CRUD. 

We will revisit this when we have the storage class ready.

**Comment by ViltusVilks** [comment]
Hey. But CRUD already implementrd by cache.
He wants also search.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
