### ISSUE TITLE
 Unable to load dynamic library 

### ISSUE THREAD

**Issue by mark0325** [phalcon/cphalcon#13789]
PHP Warning:  PHP Startup: Unable to load dynamic library 'D:\\php\\php\\ext\\php_phalcon.dll' - \xef\xbf\xbd\xd2\xb2\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xd6\xb8\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xc4\xa3\xef\xbf\xbd\xe9\xa1\xa3\r\n in Unknown on line 0
[Tue Jan 29 01:02:46.574460 2019] [mpm_winnt:notice] [pid 5792:tid 728] AH00354: Child: Starting 64 worker threads.

php 7.1

**Comment by ruudboon** [comment]
Is you extension there and readable by the webserver (D:\php\php\ext\php_phalcon.dll)?
What version of Phalcon are you trying to running? 
Do you have all required libraries installed for that version?
And what are you using, php-fpm or php with apache module?

**Comment by niden** [comment]
Also check whether you are using the correct DLL (NTS vs non NTS)

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by mark0325** [comment]
> Is you extension there and readable by the webserver (D:\php\php\ext\php_phalcon.dll)?
> What version of Phalcon are you trying to run?
> Do you have all required libraries installed for that version?
> And what are you using, php-fpm or php with apache module?

version  >=  3.4
php width apache module   (apache version  2.2.38)
php version 7.1.27
