### ISSUE TITLE
A compile and install issue

### ISSUE THREAD

**Issue by dafa168** [phalcon/cphalcon#13786]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://docs.phalconphp.com/en/latest/generating-backtrace as reference

```php
// paste output here
``` php v7.2.9

> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

[root@none 64bits]# make && make install
/bin/sh /fadata/soft/cphalcon-3.4.2/build/php7/64bits/libtool --mode=compile cc  -I. -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits -DPHP_ATOM_INC -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits/include -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits/main -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits -I/fadata/server/php/include/php -I/fadata/server/php/include/php/main -I/fadata/server/php/include/php/TSRM -I/fadata/server/php/include/php/Zend -I/fadata/server/php/include/php/ext -I/fadata/server/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /fadata/soft/cphalcon-3.4.2/build/php7/64bits/phalcon.zep.c -o phalcon.lo 
mkdir .libs
 cc -I. -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits -DPHP_ATOM_INC -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits/include -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits/main -I/fadata/soft/cphalcon-3.4.2/build/php7/64bits -I/fadata/server/php/include/php -I/fadata/server/php/include/php/main -I/fadata/server/php/include/php/TSRM -I/fadata/server/php/include/php/Zend -I/fadata/server/php/include/php/ext -I/fadata/server/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /fadata/soft/cphalcon-3.4.2/build/php7/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [phalcon.lo] Error 1

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
@dafa168  We'll need the compiler and OS versions. Did you try just use `build/install.sh` ?

**Comment by sergeyklay** [comment]
@dreamsxin Could you please help us to understand the issue?

**Comment by dafa168** [comment]
Thanks !  My system version is CentOS Linux release 7.5.1804 (Core）。
When I used this tool (build/install.sh), there was a very strange problem: the php version in the system changed from 7.2 to 5.4.

**Comment by dafa168** [comment]
I think I still need a more detailed documentation, thank you again.

**Comment by dreamsxin** [comment]
目前 CentOS 直接使用 build 下得大文件编译才会发生此问题。不知你的内存是多少？
Then try to add swap.

You can regenerate zephir code:
```shell
zephir compile
cd ext
phpize
./configure
make && make install
```

**Comment by dafa168** [comment]
well, thanks

**Comment by niden** [comment]
Added the instructions in the v4 documentation. Thank you both,.
