### ISSUE TITLE
Phalcon4 - Model _postSaveRelatedRecords getType

### ISSUE THREAD

**Issue by rudiservo** [phalcon/cphalcon#13782]
My reading of the Model class on the master branch is going to get some very weird things on the _postSaveRelatedRecords

i.e.
```
let relation = <RelationInterface> manager->getRelationByAlias(className, name);
    if typeof relation == "object" {

        /**
          * Discard belongsTo relations
          */
          if relation->getType() == Relation::BELONGS_TO {
              continue;
}
```

now, if I am not wrong Resultset\Simple will be regarded has an object

and the static variable BELONGS_TO = 0

Problem is Resultset\Simple::getType() will return 0 or 1 if the rows are an array full fetched/overloaded or a partial one, it may not save anything that is an array (inherited from Resultset).

`public function getType() -> int
	{
		return typeof this->_rows == "array" ? self::TYPE_RESULT_FULL : self::TYPE_RESULT_PARTIAL;
}`

I don't know if I am reading this right, haven't tested it yet.

Any kind of ORM is a very tricky thing, my sugestion would be to try and fully incorporate Objects into the relation and modeling process.

i.e.
``
$this->robotparts->append($part);
``

I wouldn't mind putting this to work and giving some attention to the ORM.

**Comment by ruudboon** [comment]
Maybe we could start with adding some unit tests to check this behaviour.

**Comment by niden** [comment]
I would love to see some tests on this even failing ones or some code to reproduce or verify this behavior. 

For now I am keeping it in this `sprint` but if we don't have info we will leave it for 4.1
