### ISSUE TITLE
[NFR] Volt/View Partial NoCache

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13798]
Request for `{% nocahe %} {% endnocache%}` to partially disable cache in Volt/View. This can be very useful for example were there is dynamic data that always changes like "counter", "countdown", "datetime".

**Comment by niden** [comment]
So you want to cache the whole page/partial except of a particular snippet?

**Comment by v00v** [comment]
@niden Yes, good example would be to use this for places like "countdown" timers or "relative days/time".

Example:
```
{% nocache %}
Page Updated: 1 day, 2 hours, 30 seconds ago.
{% endnocache %}
```

If whole page is changed this above example will remain the same until you flash the cache. But if something like "nocache" could be used to update this part with every page refresh this would work. Note that this is not JavaScript or JQuery. This is PHP based related date function that shows this page updates.

**Comment by ViltusVilks** [comment]
It means that every rendered part (view/partial) should save cached sub-parts between uncached.
And if they are 10x on one template?, then in result it will be 11 chunks saved to cache (11 prefixed keys, or array of chunks under one key).

1. More easier with some custom Tag and JS/jQuery for complete cache of whole page.
2. Less work is like documentation says: 
```
.. everything uncached ..
{% cache 'heavy-content' %}
...
{% endcache %}
.. everything uncached ..
{% get_update_time() %}
.. everything uncached ..
```

**Comment by niden** [comment]
I need to check this. It might be difficult to implement, if at all possible. The current implementation for the `{% cache ... %}` for instance creates a small file as a fragment to be injected in the compiled view file. For now (I have not looked at the code carefully) I don't know how to do the reverse which is what this issue requires.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
