### ISSUE TITLE
[NFR] Cache Sub-Folders

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13797]
Can we please have cache sub-folders for better organization? For example, so we can do something like this and it will auto-create those folders and then place the cached file inside. Note anytime **/** "forward-slash" used it can be auto-create folder, and the last name is for filename.

```php
$this->cache->save('folder/file-name', $data);
```

Thank You!

**Comment by ViltusVilks** [comment]
Why? Cache is cache and it is a KV store.
To save files just use normal mkdir with recursive and fileputcontents.

Otherwise extend file cache adapter.

**Comment by v00v** [comment]
To organize everything better, and eliminate issues with too many files in one folder.
How would I extend file cache adapter to achive something like this? *newbie*
Please show me a basic example for this if you have time. Thank you so much!

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/14051
