### ISSUE TITLE
Annoucing Setupify Provision Tool code release

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13796]
I just publicly dropped my [setupify](https://github.com/perch-foundation/setupify) code in a public repo.

This project is the fulfilment of my blood oath as sworn in issue #13578

I created setupify to ease the provisioning of a Phalcon environment and to provide an alternative testing environment.  The project now has a good base to fill out.  I'm looking for suggestions on how to fill out the tool so that it can complete the full Phalcon test suite on a single PHP environment (ex 7.2).  I think that its a great project and it will be the basis of any future projects for many years to come.

I'm in the process of making some videos for it since the material is so dry.  The light bar menu wizard helps to give a boring subject a little flair.  I was going to make the video tonight but I have a limo part to go to that I can't get out of, even for you guys.

Here are a few teasers from the README.

![Setupify Customize Overview](https://github.com/perch-foundation/media-resources/raw/master/setupify/v0.1/customize.png)

![Phalcon Repository Channel](https://github.com/perch-foundation/media-resources/raw/master/setupify/v0.1/phalcon-repository.png)

So I'll let you in on a little secret: my main motivation for creating setupify was to have a good way to provision a system for my upcoming Perch Framework. I've been working on this framework for a long time and I even took more than two months off to work on it full time.  The Perch Framework is provided in the form of a Zephir based PHP extension. The optional features and tools will be delivered in the form of PHP Composer packages and NPM modules.  There is a full first class optional Webpack integration.  Its my third gen tech and so I've worked out quite a lot more things.  The Perch Framework first needs the best Phalcon and Zephir tech and so this will be my first code release.

Putting all of that Perch Framework stuff aside, I need assistance to turn setupify into both an ideal starting point for open ended development as well as being a great place to run test suites.  It will likely be a huge win if it can serve both needs at once .

**Comment by ruudboon** [comment]
Well done. Currently running Nanobox but curious about your approach. Will check it out.

**Comment by dschissler** [comment]
@ruudboon Nanobox seems fine but you really give up quite a lot of control.

For example from the blog:

> First create a free Nanobox account, then download and run the Nanobox installer.

I really don't need additional accounts or proprietary environments/runtimes.  I want to be able to transition from a development environment to a production environment without getting the permission of one more middle man.  I want to be able to easily remove a broken system package to compile it myself if needed.  I also want to be able to type just a single command to install the entire system.  I want to be able to easily change dependency versions without redoing my development environment.  I want the installation to be easy on the first go and most importantly to be idempotent for all updates except for the changed part.  Maybe you want the latest `zephir_parser` or Zephir, so just run setupify again.  Also then painless to jump back.  It might do some unnecessary work here and there but you can manually skip the more time consuming parts such as building Phalcon (if you were building it and not installing from the repo).

If you want to use Docker then just put `setup/` your root directory and then run `./setup/provision.sh ubuntu1804` in the Dockerfile.  I personally like KVM libvirt so I just use it like a normal VM.

If you want more system packages then just add them to the [package list](https://github.com/perch-foundation/setupify/blob/master/setup/os/ubuntu1804/lists/package).  Personally I like to start working with the Ubuntu release before the next LTS to make sure that I'm up to speed on the latest Ubuntu stack before the next LTS drops.  Its super easy to do that with setupify.  Just copy the `./setup/os/ubuntu1804/` directory to the `ubuntu####` and change it until it works properly.

Setupify comes in a directory named `setup/` and one of its intended uses is to be dropped into another project and customized.  The scripts are broken out so that you could easily follow the latest maintained `setupify` repo by just dropping several files into your local version.  If you added new conf.d init scripts then just leave those files as they are and drop in the fixed up versions from the main repo.

**Comment by niden** [comment]
@dschissler Do you want to take the lead on that and add documentation on how we can use this tool for Phalcon?

**Comment by dschissler** [comment]
Sure.  If you check out the README for it then you'll see that there is already a significant amount of documentation.  I'll also be creating 1-2 videos as well.  There will be a pause on it for a while until it can be use to install a public Perch Framework.  By default Perch and Node will be left blank and you can use the menu to fill it in (or set it manually in the settings).  The node repo support already exists in this form.
