### ISSUE TITLE
Cascade update in ORM

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13804]
Hello.

As far as I know, and also by the documentation the Phalcon does not implement cascading data updates when the virtual foreign key is enabled for hasOne and hasMany relations. If that's not the case, correct me.

I suggest adding this, or I'll be very happy to hear from you if it doesn't need to be added and why.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
