### ISSUE TITLE
[4.0.0] Rename Acl\Resource to Acl\Component

### ISSUE THREAD

**Issue by tempcke** [phalcon/cphalcon#13808]
As was determined here: https://github.com/phalcon/cphalcon/issues/13791
Phalcon\Acl\Role should revert back to what it is in 3.4 and Phalcon\Acl\Resource should be renamed Phalcon\Acl\Component

This also relates to https://github.com/phalcon/cphalcon/issues/13639

`Phalcon\Acl\Resource` -> Phalcon\Acl\Component
`Phalcon\Acl\ResourceInterface` -> Phalcon\Acl\ComponentInterface
`Phalcon\Acl\ResourceAware` -> Phalcon\Acl\ComponentAware

These should remain unchanged from 3.4:
`Phalcon\Acl\Role`
`Phalcon\Acl\RoleInterface`
`Phalcon\Acl\RoleAware`

----

Update change log as well as blog post

**Comment by niden** [comment]
This has been addressed
