### ISSUE TITLE
Code has to be at least ad-hoc signed.

### ISSUE THREAD

**Issue by Jarboox** [phalcon/cphalcon#13806]
Hello, I'm try to use phalcon-devtools. The instalations in web is ok, but when I add the phalcon.so to my php.ini in /etc/php.ini I have the next error. I install phalcon with brew, the phalcon.so files is in /usr/local/Cellar/php71-phalcon/3.4.2/phalcon.so. The error is when I try to use phalcon in my terminal.

```php
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71-phalcon/3.4.2/phalcon.so' - dlopen(/usr/local/Cellar/php71-phalcon/3.4.2/phalcon.so, 0x0009): code signature in (/usr/local/Cellar/php71-phalcon/3.4.2/phalcon.so) not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71-phalcon/3.4.2/phalcon.so' - dlopen(/usr/local/Cellar/php71-phalcon/3.4.2/phalcon.so, 0x0009): code signature in (/usr/local/Cellar/php71-phalcon/3.4.2/phalcon.so) not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. in Unknown on line 0

### Details

* Phalcon version: not found
* PHP Version: PHP 7.1.23 (cli) (built: Nov  7 2018 18:20:35) ( NTS )
* Operating System: Mac OS Mojave
* Installation type: Brew
* Zephir version (if any):
* Server: Apache

**Comment by CameronHall** [comment]
Hi @Jarboox,

You'll have to install Apache or Nginx and load Phalcon that way. Since Mojave, Apple are enforcing code signing on the modules :\

**Comment by Jarboox** [comment]
> Hi @Jarboox,
> 
> You'll have to install Apache or Nginx via homebrew and load Phalcon that way. Since Mojave, Apple are enforcing code signing on the modules :\

I did install apache with brew.  :\

**Comment by CameronHall** [comment]
My mistake, sorry. Did you try installing PHP via brew?

**Comment by CameronHall** [comment]
Can you have a look at this and let us know how you go?
https://superuser.com/questions/1363013/apache-cant-load-php-unsigned-extensions-on-mac-os-mojave

**Comment by Jarboox** [comment]
I can't do it :/, and not have much time for this. I think will return to linux :D

**Comment by scrnjakovic** [comment]
@Jarboox do yourself a favor and transition to NGINX :)

@CameronHall how will a web server aid in loading a php extension?

**Comment by CameronHall** [comment]
I was trying to remember the steps I had to take after I upgraded my Macbook from High Sierra to Mojave. One of the first things I did was move away from the Apache that shipped with the OS.

**Comment by Jarboox** [comment]
@scrnjakovic 'course, I'm going to learn it, but for now I will use a docker with phalcon. 
@CameronHall @scrnjakovic thanks. Regards.
