### ISSUE TITLE
Related model messages

### ISSUE THREAD

**Issue by zsilbi** [phalcon/cphalcon#13811]
There is no way to tell the source of the messages at the moment.

Previously `Phalcon\Mvc\Model\Message` contained information about its origin.
Now both `getModel()` and `setModel()` methods are missing from `Phalcon\Message`. but  `setModel()`  is still in use here: https://github.com/phalcon/cphalcon/blob/171b6cda908154c96e4358a75707a668b2346323/phalcon/mvc/model.zep#L4160

Maybe extending `Message` with these methods in a new `Message/Model` class could solve this issue.

### Details
* Phalcon version: v4.0.0-alpha.2

**Comment by niden** [comment]
Thanks for reporting this. I will get on it shortly.

**Comment by scrnjakovic** [comment]
That part of the code will throw an error as soon as it is hit. It's a bug.

As for the source part, having another class extending `Phalcon\Messages\Message` and implementing said method will throw us back to `Phalcon\Validation\Message` and `Phalcon\Mvc\Model\Message` situation.

**Comment by niden** [comment]
Maybe instead of `setModel` we can use `setMetadata` so that the particular method can be reused for other situations in the framework

**Comment by niden** [comment]
Resolved and merged
