### ISSUE TITLE
Discussion to change Phalcon class "dependencyInjector" properties to simply "di"

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13829]
Currently chaining off of the dependency injector is very ugly.  I propose that the DI properties be changed from the verbose "dependencyInjector" or "_dependencyInjector" to simply "di".  I think that the DI is so central to Phalcon that there is basically zero chance that they won't know what it is.  So this would trade some theoretical correctness about verbosity for a first time user for a quality of life improvement for everyone else all of the time.

This is particularly relevant when I know that I will only be accessing the DI a single time in the method.  I like to write my Zephir short and sweet and not to have two extra lines of boiler plate just to be able to have some clean looking lines after it.

For example this:

```zephir
var di;

let di = this->dependencyInjector;

di->get("blah");
```

I'd prefer to do the following:

```zephir
this->di->get("blah");
```

The current situation is particularly ugly when chaining off of a service.

**Comment by ruudboon** [comment]
Maybe we should move this discussion to the [Zephir repo](https://github.com/phalcon/zephir).

**Comment by Jurigag** [comment]
Well as far as i know there is performance difference when doing:

```zep
var di;

let di = this->dependencyInjector;

di->get("blah");
```
And :

```zep
this->di->get("blah");
```

As far if we are going to access it many times. But overall i agree that we should rename it to di.

**Comment by dschissler** [comment]
I agree that we shouldn't remove the `let di = ...` code.  Just to clarify, I'm proposing just renaming `dependencyInjector` and `_dependencyInjector` to `di`.

This will break many things such as user controllers (in php) which are referencing the di directly from the property instead of through `getDI()`.

Oh I want to point out that if for some reason this is seen as being too disruptive then at the very least the versions with the `_` prefix should be changed.  This has caught me at least once.

**Comment by niden** [comment]
The variables in the code have been renamed to `container`
