### ISSUE TITLE
[NFR] Create a view method to simple render template to a string.

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#13825]
As a regular user I would like to have something like this:

```php
$html = $view->toString($template, $params);
mail("someone@example.com", "My subject", $html);
```

without setting any additional params eg base path, layout, base template, etc.

**Comment by dschissler** [comment]
Since when are you a normal user?

Perhaps a third parameter for using a file path to read with `file_get_contents`.

```php
$html = $view->toString($template, $params);
$html = $view->toString($templatePath, $params, true);
```

**Comment by Jeckerson** [comment]
This is actually useful. Not only for email templates, but for ajax responses when you need to return rendered html inside json.

**Comment by JABirchall** [comment]
Wait, doesn't view->getRender() already do this?

https://github.com/phalcon/cphalcon/blob/v3.4.0/phalcon/mvc/view.zep#L1118-L1165

**Comment by ViltusVilks** [comment]
As I remember it is not so trivial. GetRender triggers events and can break something at the end. Partial can be used.

Otherwise only forking can do safe render.

**Comment by Jurigag** [comment]
@JABirchall you still have here controllerName and actionName. Right now this can be achieved by some hacky way - like simply create temporary new volt template in /tmp and then render it, but this is just workaround.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14058

**Comment by EcLaboratory** [comment]
Watching the changes in code it seems the only real change is not to fire events. Is it planned to make available a method to do the action an the begining of this blog exposed?

I mean

$html = $view->toString($template, $params);

where $template is an string with the volt template content and $params an array to use to render the template

Thanks in advance

**Comment by niden** [comment]
@EcLaboratory This particular change is for the `View` which will take a template as a controller/action/view and will load it and send it back.

If you want a specific template to be parsed and returned, you can use the `View\Simple` component which does the same thing.
