### ISSUE TITLE
Proposal to change .zep tabs to spaces, class files capital camel case like PSR

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13823]
I propose that the `phalcon/` directory be changed to resemble more like PHP PSR file names.  In addition for the tabs to be changed to four spaces.  I think that it would be much easier to switch between PHP and Zephir Phalcon if the conventions were the same.  I understand that Zephir came from C programmers but I don't think that its helpful to think of it as C.  There are just a few Zephir language developers and everyone else is thinking in terms of PHP.

Its all just arbitrary but why did Zephir need to provide completely different standards than PHP?

**Comment by Jeckerson** [comment]
Really strange, that current topic rises only now.

**Comment by dschissler** [comment]
I've brought it up at least twice before (elsewhere) but I was shot down.  I'm hoping for a popular revolt.

**Comment by dschissler** [comment]
Also I can do the bitch work for this.

**Comment by dschissler** [comment]
@niden Maybe we could start with just tabs to spaces first?  Knowing you guys its impossible for someone who is not one of two people to do it because literally every single line will change.  That is a security nightmare because who can really analyse that?  Best for you to do it :).  Haha!

**Comment by Jeckerson** [comment]
It need to be started from code sniffers, and add rules smoothly directory by directory. Which, in future, could be added into github Pull request checks for automation purposes.
