### ISSUE TITLE
scaffold in search view

### ISSUE THREAD

**Issue by zzroche** [phalcon/cphalcon#13842]
There is a problem with case sensitive table.

Scaffold create this code:

 foreach ($page->items as $studi): 
            <tr>
            <td><?php echo $Studi->Studi_ID ?></td>

----------------------
Instead of this:
----------------------
foreach ($page->items as $Studi):
            <tr>
            <td><?php echo $Studi->Studi_ID ?></td>

> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://docs.phalconphp.com/en/latest/generating-backtrace as reference

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

* Phalcon version: (`php --ri phalcon`)

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.2
Build Date => Dec  2 2018 17:22:43
Powered by Zephir => Version 0.10.14

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

* PHP Version: (`php -v`)

PHP 7.2.15 (cli) (built: Feb  5 2019 23:14:06) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

* Operating System: Windows 10

* Installation type: Compiling from source || installing via package manager: download dll from site
* Zephir version (if any):
* Server: Apache
* Other related info (Database, table schema):

**Comment by niden** [comment]
@zzroche Thank you for reporting this. Would you be so kind as to open an issue in the `devtools` repository since that is where this needs to be?

We will try to solve this as fast as we can there.

Thank you
