### ISSUE TITLE
Using `spl_object_hash()` instead of `Di::isFreshInstance()` in the Dispatcher

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13853]
I'm evaluating the use of [DI::wasFreshInstance()](https://github.com/phalcon/cphalcon/blob/b19d84a287477992cfabf258db8784486e140d1d/phalcon/dispatcher.zep#L495) in the `Phalcon\Dispatcher`.  I think that the `Di:wasFreshInstance` method is a bad design and that it could instead be achieved with a "handler" cache that stores whether a handler instance has been seen before.  If there is a miss on the handler cache using spl_object_hash then it could be assumed to be new and `wasFresh` could then be set to true.  Implementing something like this would simplify the DI.  Although I'm not positive on this I suspect that this design limitation goes way back to when Phalcon was changed to be HMVC.

**Comment by niden** [comment]
This has been addressed
