### ISSUE TITLE
Nanobox 7.3 config not working

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#13858]
The instructions to run the unit test for PHP 7.3 on Nanobox are not working for PHP 7.3.

``` 
cp -v ./tests/_ci/nanobox/boxfile.7.3.yml ./boxfile.yml 
nanbox run
```
results in 
```
 Can not find php73-xdebug to install
```
Probably we need to install the xdebug beta.

**Comment by niden** [comment]
Resolved
