### ISSUE TITLE
[NFR] Voting for your favorite NFR

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#13855]
There are a lot of great ideas regarding the framework and additional functionality to help developers. Sadly we cannot do everything in one go, so we have been concentrating in bugs mostly and neglecting NFRs. As such, there have been pages and pages of issues as NFRs that never got any attention.

In an effort to introduce functionality that the community wants mostly, please read the list below (link to the original issue for reference) and vote in the comments by using the number next to each line below. At the end we will gather the top 5-10 (depending on time constraints) and concentrate on those NFRs.

This issue will be kept open to track the list of NFRs so that we can address them all if possible. If a NFR does not get any support, it does not mean that we will ignore it.

#### Application
- **3** - Application: When using controller as micro app handler, Controller::initialize should be invoked [#1036](https://github.com/phalcon/cphalcon/issues/1036)

#### Assets
- **4** - Assets: Assets\Collection: Helpers for combining JS/CSS [#2009](https://github.com/phalcon/cphalcon/issues/2009)
- **5** - Assets: Phalcon\Assets - Subresource Integrity [#13333](https://github.com/phalcon/cphalcon/issues/13333)

#### Cache
- **6** - Cache: Cache Compression [#13740](https://github.com/phalcon/cphalcon/issues/13740)
- **7** - Cache: Cache Sub-Folders [#13797](https://github.com/phalcon/cphalcon/issues/13797)
- **8** - Cache: Libmemcached do not setup setSaslAuthData on Memcached [#13394](https://github.com/phalcon/cphalcon/issues/13394)

#### Compilation
- **9** - Compilation: Add generated files /ext to .gitignore [#12284](https://github.com/phalcon/cphalcon/issues/12284)
- **10** - Compilation: Consider purging ancient ext/ directory data [#13727](https://github.com/phalcon/cphalcon/issues/13727)

#### DI
- **12** - DI: Make shared instances removable [#13440](https://github.com/phalcon/cphalcon/issues/13440)
- **13** - DI: Phalcon\Di add alias [#13042](https://github.com/phalcon/cphalcon/issues/13042)

#### Dispatcher
- **16** - Dispatcher: beforeThrowable, beforeError in dispatcher [#12289](https://github.com/phalcon/cphalcon/issues/12289)
- **17** - Dispatcher: setDefaultNamespace() Alias setNamespace() [#13814](https://github.com/phalcon/cphalcon/issues/13814)

#### Forms
- **20** - Forms: Forms should also have attributes [#13646](https://github.com/phalcon/cphalcon/issues/13646)
- **21** - Forms: Support of nested forms and adding collections of elements to the form [#11579](https://github.com/phalcon/cphalcon/issues/11579)

#### Http
- **22** - Http: HTTP/2 Preload support [#13128](https://github.com/phalcon/cphalcon/issues/13128)
- **23** - Http: SetLocale() not support multiple parameters [#12202](https://github.com/phalcon/cphalcon/issues/12202)
- **25** - Http: generate URL for route with hostName [#9913](https://github.com/phalcon/cphalcon/issues/9913)

#### Modules
- **26** - Modules: Add module name to module class name format in Application::registerModules [#12252](https://github.com/phalcon/cphalcon/issues/12252)

#### Mongo
- **27** - Mongo: Any plan about support PHP MongoDB Driver? [#11156](https://github.com/phalcon/cphalcon/issues/11156)
- **28** - Mongo: Phalcon3/PHP7 Mongo Backend Cache support [#12074](https://github.com/phalcon/cphalcon/issues/12074)

#### ODM
- **29** - ODM: Abstraction layer for ODM [#507](https://github.com/phalcon/cphalcon/issues/507)

#### ORM
- **30** - ORM: Allow size parameter for datetime and timestamp columns [#13297](https://github.com/phalcon/cphalcon/issues/13297)
- **31** - ORM: Cascade update in ORM [#13804](https://github.com/phalcon/cphalcon/issues/13804)
- **32** - ORM: Different types of messages in virtual foreign keys [#13801](https://github.com/phalcon/cphalcon/issues/13801)
- **33** - ORM: Factory for Metadata [#13780](https://github.com/phalcon/cphalcon/issues/13780)
- **35** - ORM: MySQL point field support missing [#13670](https://github.com/phalcon/cphalcon/issues/13670)
- **36** - ORM: Phalcon DB - Change Column (Rename) [#12805](https://github.com/phalcon/cphalcon/issues/12805)
- **37** - ORM: Phalcon JSON Flat-File CRUDS Support [#13783](https://github.com/phalcon/cphalcon/issues/13783)
- **38** - ORM: Phalcon\Mvc\Model\Query\BuilderInterface Definition [#13021](https://github.com/phalcon/cphalcon/issues/13021)
- **40** - ORM: ReusableInterface [#13474](https://github.com/phalcon/cphalcon/issues/13474)
- **41** - ORM: UPDATE query with JOIN in PHQL [#11637](https://github.com/phalcon/cphalcon/issues/11637)
- **42** - ORM: Way of improving generic database setup [#13647](https://github.com/phalcon/cphalcon/issues/13647)
- **44** - ORM: getRealSQLStatement and getSQLStatement has no differences [#12196](https://github.com/phalcon/cphalcon/issues/12196)

#### Translation
- **50** - Translation: Support 'context' in Gettext (msgctxt) [#12201](https://github.com/phalcon/cphalcon/issues/12201)

#### Validation
- **52** - Validation: Change field(s) in failed message [#13685](https://github.com/phalcon/cphalcon/issues/13685)
- **53** - Validation: Validation messages [#13208](https://github.com/phalcon/cphalcon/issues/13208)
- **54** - Validation: Why not to use ioc/factory style for validators like filters [#13567](https://github.com/phalcon/cphalcon/issues/13567)

#### View/Volt
- **56** - View: View active render path not return to prev path after partial render [#13554](https://github.com/phalcon/cphalcon/issues/13554)
- **57** - Volt: Allow \Phalcon\Mvc\View\Engine\Volt to accept Phalcon\Mvc\View\Engine\Volt\Compiler in the constructor [#2700](https://github.com/phalcon/cphalcon/issues/2700)
- **61** - Volt: Volt with "Literal" tag [#1253](https://github.com/phalcon/cphalcon/issues/1253)

Update: 2019-03-11

**Comment by Jeckerson** [comment]
Really hard to select one from big list... Will change my comment with some number if would choose some.

**Comment by niden** [comment]
@Jeckerson Yes it is a big list. However we will keep this issue open so as to get as many people to have a look and decide on what is more important to be addressed. Take your time and give us input whenever you can.

**Comment by StudioMaX** [comment]
@niden maybe you can choose by the [most commented](https://github.com/phalcon/cphalcon/issues?q=is%3Aissue+label%3A%22New+Feature+Request%22+sort%3Acomments-desc)/[most voted](https://github.com/phalcon/cphalcon/issues?q=is%3Aissue+label%3A%22New+Feature+Request%22+sort%3Areactions-%2B1-desc) issues?

**Comment by JABirchall** [comment]
I vote for

- 22
- 44
- 45
- 47
- 51
- 60

**Comment by Mouvedia** [comment]
49

**Comment by scrnjakovic** [comment]
- 19
- 34
- 39
- 45

Are top in my book

**Comment by dschissler** [comment]
I vote for my two issues that already have twice approved PRs.

**Comment by ekmst** [comment]
1, 2, 31

**Comment by TimurFlush** [comment]
- 1

- 3

- 6

- 11

- 16

- 18

- 19

- 31

- 33

- 45 🔥🔥🔥

- 46

- 47

- 51 🔥

- 55

**Comment by angelvega93** [comment]
- 6
- 34
- 60

**Comment by Ultimater** [comment]
- 1
- 15
- 27
- 39
- 45
- 47

**Comment by lanlin** [comment]
- 15
- 16
- 22
- 26
- 27
- 45
- 46

**Comment by olegatro** [comment]
- 1
- 19
- 39
- 45

**Comment by grigoriy-ivanov** [comment]
- 1
- 11
- 19
- 21
- 22
- 33
- 34
- 38
- 39
- 40
- 45
- 48
- 51
- 54
- 60

**Comment by Jurigag** [comment]
Well overall i don't want to vote on anything, but overall i think any improvements made to DI and PHQL/ORM will be great and we should focus on those.

**Comment by quasipickle** [comment]
- **2 (use REQUEST_URI by default)**
- 4 (Combine assets)
- 11 (Argon2)
- 24 (Get Best Language )
- **34 (Many-to-Many)**
- **38 (BuilderInterface Definition)**
- **53 (Validation messages)**
- 59 (Embedding blocks)
- 60 (Output filters)

In general I think it would be a good practice to fix any low hanging fruit (bolded) before adding new stuff

**Comment by BasSteenbeeke** [comment]
- 18

**Comment by mj-tm** [comment]
* **39** - ORM: Query builder for raw sql [#2052](https://github.com/phalcon/cphalcon/issues/2052)
Thank you as always

**Comment by hisune** [comment]
- 27
- 28
Waited for too many years...

**Comment by krazzer** [comment]
Ditch Volt and all Maintenance it swallows up and use Twig by default. More time and resources for other stuff.

**Comment by cnyyk** [comment]
35 - ORM: MySQL point field support missing #13670

**Comment by woody712** [comment]
47

**Comment by richmilns** [comment]
* 2
* 15
* 17
* 18
* 25
* 43 :)
* 61

**Comment by Ark4ne** [comment]
- __2 - Application: Use REQUEST_URI by Default__
- 11 - Crypt: Implement Argon2 for password hashing
- 12 - DI: Make shared instances removable
- __13 - DI: Phalcon\Di add alias__
- 22 - Http: HTTP/2 Preload support
- 34 - ORM: Many to Many behaviour
- 36 - ORM: Phalcon DB - Change Column (Rename)
- __48 - Router: Router enhancements and changes (caching support like [Jurigag/fast-micro-router-phalcon](https://github.com/Jurigag/fast-micro-router-phalcon/blob/master/fastmicro/FastRouter.zep) :rocket:)__
- 57 - Volt: Allow Phalcon\Mvc\View\Engine\Volt to accept Phalcon\Mvc\View\Engine\Volt\Compiler in the constructor

**Comment by krazzer** [comment]
- 59
- 41
- 45

**Comment by emiliodeg** [comment]
I've been thinking like a week in this post, and I think all NFR in Application, Cache and Redis, Compilation, Crypt, DI, Dispatcher, Http, ORM and Validation are mandatories but I know our limitations... said the adobe, I do my list
- 4
- 5
- 18
- 20 *
- 24
- 40 *
- 43
- 45
- 46
- 47
- 48
- 49 *
- 50
- 51
- 53 *
- 55
- 59
- 60
- 61

\* I can help coding in that points which I consider the easiest for me

**Comment by niden** [comment]
2019-03-11 - Issues with more than 2 votes have been added to the 4.1 project. 

We will consider the rest as time allows.

**Comment by diegosardina** [comment]
20
21
22
61

**Comment by Rajeshr34** [comment]
35

**Comment by reedzhao** [comment]
Mongo
27 - Mongo: Any plan about support PHP MongoDB Driver? #11156
28 - Mongo: Phalcon3/PHP7 Mongo Backend Cache support #12074

**Comment by v00v** [comment]
Very nice page, thank you @niden I think this is great idea to help developers decide on what to concentrate more and not waist there time on things no one needs. Everyone should follow niden's format in there reply, instead of just posting numbers.

```
**Example Title**
- Number - Description #ID
```

**Assets**
- 4 - Assets: Assets\Collection: Helpers for combining JS/CSS #2009

**Cache**
- 6 - Cache: Cache Compression #13740
- 7 - Cache: Cache Sub-Folders #13797

**DI**
- 12 - DI: Make shared instances removable #13440
- 13 - DI: Phalcon\Di add alias #13042

**Dispatcher**
- 17 - Dispatcher: setDefaultNamespace() Alias setNamespace() #13814

**Http**
- 22 - Http: HTTP/2 Preload support #13128
- 23 - Http: SetLocale() not support multiple parameters #12202
- 25 - Http: generate URL for route with hostName #9913

**Modules**
- 26 - Modules: Add module name to module class name format in Application::registerModules #12252

**Mongo**
- 27 - Mongo: Any plan about support PHP MongoDB Driver? #11156
- 28 - Mongo: Phalcon3/PHP7 Mongo Backend Cache support #12074

**ODM**
- 29 - ODM: Abstraction layer for ODM #507

**ORM**
- 33 - ORM: Factory for Metadata #13780
- 37 - ORM: Phalcon JSON Flat-File CRUDS Support #13783

Thank you! Phalcon is the only php framework I've used for years now. I tried many others, even Laravel. Phalcon is the best! With many of this improvements phalcon will beat any other other php framework hands down!

**Comment by LenoM** [comment]
4, 20, 22, 30, 50, 60.

**Comment by emiliodeg** [comment]
@niden @sergeyklay can you assign my the issue #13646 (form attribs)? I'm working on it for the Bugfest

**Comment by wajdijurry** [comment]
I vote for:
13
42

**Comment by v00v** [comment]
I just want to say, that all of this NFRs look epic, good job phalcon community and I hope everyone of us will have something from this list. I wish GitHub had a visual poll, so we could do real votes and then see nice graph results :-) Its a bit hard to count all this numbers in the post when we have such a big community ^_^ Anyway, keep up great work everyone!

**Comment by lifewcody** [comment]
27 + 28

**Comment by armezit** [comment]
27
28
29

**Comment by niden** [comment]
Closing this but keeping it as a reference for all the NFRs listed here. The top ones have already been added into 4.1

**Comment by irvv17** [comment]
56

**Comment by v00v** [comment]
@niden Can you please re-open this for reference and also mark NFRs that were added to 4.1 so everyone can see better what is going on? Or alternativly create a v4.1-NFRs.md please.

**Comment by xorinzor** [comment]
Pretty shocked that 61 isn't a feature yet.

**Comment by zak-wojtek77** [comment]
I vote for:
21

**Comment by lanlin** [comment]
27 - Mongo: Any plan about support PHP MongoDB Driver? #11156

**Comment by ruudboon** [comment]
@lanlin Yes for 4.1, @14729 please use https://github.com/phalcon/cphalcon/issues/14608 for voting.

**Comment by machel2** [comment]
21,30,31,41,61

**Comment by KBulmer** [comment]
35

**Comment by wajdijurry** [comment]
27
28
29

**Comment by niden** [comment]
@wajdijurry Here please

https://github.com/phalcon/cphalcon/issues/14608

**Comment by shuqiangzhou** [comment]
44

**Comment by niden** [comment]
@shuqiangzhou Here please

#14608
