### ISSUE TITLE
JSONB support for Query\Builder using Postgresql

### ISSUE THREAD

**Issue by iamdann** [phalcon/cphalcon#13865]
Hey all! I'm trying to use Postgresq's [JSONB](https://www.postgresql.org/docs/11/functions-json.html) features inside of my `Query\Builder`. 

I have the following code: 
```
(new Builder())
        ->addFrom('MyModel', 'mm')
        ->columns([
            'name' => 'mm.name',
            'data' => 'mm.data->0'
        ])
        ->getQuery()->execute();
```

Wich results in the following exception to be thrown: 
```
Syntax error, unexpected token >, near to '0 AS [data] FROM [MyModel] AS [mm]', when parsing: SELECT mm.name AS [name], mm.data->0 AS [data] FROM [MyModel] AS [mm]
```

When using raw SQL everything works as it's supposed to. 
```
Di::getDefault()->get('db')->query(
     'SELECT mm.name AS name, mm.data->0 AS data FROM public.MyModel AS mm'
)->fetch();
```

I rather not write raw SQL queries every time I need to use Postgresql's JSONB features. Any good solution or workaround for this?

### Details

* Phalcon version: 3.4
* PHP Version: 7.2.15
* Operating System: macOS Mojave 10.14.3
* Installation type: [docker](https://hub.docker.com/r/mileschou/phalcon/)
* Server: Apache
* Database: Postgres 11.2

**Comment by Jurigag** [comment]
Dialect extension i guess could be workaround for this now. Where you will have just something like `JSONB('mm.data->0')` and it will just work. Most likely we need to add new types on db adapters and allow syntax like thins PHQL.

**Comment by sergeyklay** [comment]
I'll try to provide support a bit later.

**Comment by iamdann** [comment]
@Jurigag Could you provide a more complete example please? Or is [this](https://forum.phalconphp.com/discussion/17245/building-extension-of-postgresql-dialect-for-json-support-few-qu) what you had in mind?

**Comment by niden** [comment]
Support for this has been added https://github.com/phalcon/cphalcon/pull/17109
