### ISSUE TITLE
exit code 0 instead of error

### ISSUE THREAD

**Issue by zhituha** [phalcon/cphalcon#13878]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

I've tried to ./install the phalcon on the low-memory system, but script does something strange:

make: *** [phalcon.lo] Ошибка 1

Thanks for compiling Phalcon!
Build succeed: Please restart your web server to complete the installation

So, I get a '0' exitcode when compilator was killed by OOM Killer

### Details

* Phalcon version: latest for today.

**Comment by niden** [comment]
Can you please have a look at this and try it 

https://web.archive.org/web/20141202015428/http://hostingfu.com/article/compiling-with-gcc-on-low-memory-vps

**Comment by Jeckerson** [comment]
Try to create swap file with 1-2Gb of space, could help...

**Comment by zhituha** [comment]
I know what does OOM mean. But I'd like to get error..

**Comment by Jeckerson** [comment]
It make no sense to output `Build succeed: Please restart your web server to complete the installation` in this case...
