### ISSUE TITLE
Security when comparing hashes

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13875]
Hello.

Please see the \Phalcon\Security::checkHash() method.
How protected is it from the time attack?

Thank.

**Comment by CameronHall** [comment]
I'm not a cryptography expert by any means so take this with a grain of salt. The method `checkHash` method is protected. It is designed with `constant-time` in mind. Meaning it'll keep processing and won't check the match until it's finished checking everything. Opposed to a method that actively checks the result and terminates the execution as soon as a mismatch is found.

Take a read of [this article](https://en.wikipedia.org/wiki/Timing_attack). The examples in that article explain it far better than I can.
