### ISSUE TITLE
[BUG] Volt - "in" array check did not work as expected if multiple conditions

### ISSUE THREAD

**Issue by borisdelev** [phalcon/cphalcon#13880]
### Expected and Actual Behavior

Well, the issue is ease to reproduce. Lets look that example in volt:

```twig
    {% if 'Tes' in ['Tes', 'Test2'] %}
        YEY
    {% endif %}
```
Will return "YEY", but in that example:

```twig
    {% if 'Tes' in ['Tes', 'Test2'] and 'Tes2' in ['Tes2', 'Test3'] %}
        YEY
    {% endif %}
```
...will throw exception: "Phalcon\Mvc\View\Exception: Invalid haystack" and the reason is (volt php generated code):
```php
    <?php if ($this->isIncluded($this->isIncluded('Tes', ['Tes', 'Test2'] && 'Tes2'), ['Tes2', 'Test3'])) { ?>
        YEY
    <?php } ?>
```

If I place the conditions in brackets - it works. The question is- is it a feature i didnt know about... or it is a little volt bug?

:) Greeeetings! and may the force be with u!

### Details

* Phalcon version: 3.4.3
* PHP Version: 7.3.2
* Operating System: Windows 64
* Server: Apache

**Comment by niden** [comment]
Can you try this?

```twig
{% if ('Tes' in ['Tes', 'Test2']) and ('Tes2' in ['Tes2', 'Test3']) %}
```

**Comment by borisdelev** [comment]
Well... When i place brackets it works. Yes, i already confirm that in first post.
Amm... okay. Just dont think regular developer will think about that... Php 'if-else' conditions can be used without brackets.

**Comment by niden** [comment]
@borisdelev It is most likely something that we can work with in the volt parser to make it identical to PHP. Personally I don't recall seeing this because I am always using parentheses and @sergeyklay is nagging at me all the time :)

If you want you can add an issue to be checked in the future.

**Comment by borisdelev** [comment]
@niden no worries, u right. 
Have fun and... be happy :)
