### ISSUE TITLE
Error Phalcon DevTools Models Oracle

### ISSUE THREAD

**Issue by verde3ro** [phalcon/cphalcon#13881]
I have the following problem when generating the models of an Oracle database.

```
phalcon create-all-models --mapcolumn --doc --force --schema=MGR_ARVYC

Phalcon DevTools (3.4.0)

ERROR: SQLSTATE[HY000]: General error: 24337 OCIStmtExecute: ORA-24337: statement handle not prepared (ext\pdo_oci\oci_statement.c:159)
```

I hope you can help me.

**Comment by Jeckerson** [comment]
Try to create single model by model and check if problem still occurs.

**Comment by niden** [comment]
@verde3ro Can you please open an issue in the devtools repository? You will get more help there. Also Phalcon does not come with an Oracle adapter. The available adapter as far as I understand is in the incubator so not _officially_ supported

Thanks
