### ISSUE TITLE
Phalcon\Collection

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#13886]
`Phalcon\Collection` is a collection is a supercharged OO array. It implements `Countable`, `ArrayAccess`, `Serializable` and `JsonSerializable`. 

It is used as a base for collections through the application, especially when in need to access globals such as `$_POST`, `$_GET` etc.

**Comment by JABirchall** [comment]
Implement a zephir version of Illuminate/Collection

**Comment by niden** [comment]
@JABirchall never seen that before lol. For now we will create it with phalcon -> zephir. Maybe later we can speed it up using a more native C/Zephir implementation

**Comment by JABirchall** [comment]
@niden Im just saying, Illuminate's collection is very verbose and useful, I use it on a ton of things and even pull it into phalcon projects to collect database results.

**Comment by niden** [comment]
I will check it out bud thanks.

**Comment by niden** [comment]
Implemented
