### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by mark0325** [phalcon/cphalcon#13888]
PHP Warning: PHP Startup: Unable to load dynamic library 'D:\php\php\ext\php_phalcon.dll' - \xef\xbf\xbd\xd2\xb2\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xd6\xb8\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xc4\xa3\xef\xbf\xbd\xe9\xa1\xa3\r\n in Unknown on line 0
[Tue Jan 29 01:02:46.574460 2019] [mpm_winnt:notice] [pid 5792:tid 728] AH00354: Child: Starting 64 worker threads.

### Details

* Phalcon version: (`version >= 3.4`)
* PHP Version: (` version  7.1.27`)
* php width apache module 
* apache version 2.2.38

**Comment by Jeckerson** [comment]
You have several .dll for the same version. Try all of them.

**Comment by sergeyklay** [comment]
@mark0325 Please provide exact version you did download
