### ISSUE TITLE
undefined symbol: zend_ce_countable in Unknown on line 0

### ISSUE THREAD

**Issue by l3l4c7-h4t** [phalcon/cphalcon#13887]
Hi
first of all im sorry for bad type english.

Im using Phalcon more than 4 years and now I upgrade my centos 6.9 to 7 and my PHP version is  7.0.33 (cli) and I installed Phalcon last version and installed successfully.

> Build complete.
> Don't forget to run 'make test'.
> 
> Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20170718/
> Installing header files:          /usr/local/include/php/
> 
> Thanks for compiling Phalcon!
> Build succeed: Please restart your web server to complete the installation

and in php.ini i add :

> extension=/usr/local/lib/php/extensions/no-debug-non-zts-20170718/phalcon.so

and then i restart Nginx service.

but dont show phalcon in phpinfo() ...

and when i run php -v , i get this warning:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20170718/phalcon.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20170718/phalcon.so: undefined symbol: zend_ce_countable in Unknown on line 0
> 

about 3days i searching and try try try but no any result :(

all of my site is down  :((

before i never have that problem.

pls help me....

**Comment by sergeyklay** [comment]
@l3l4c7-h4t 

> undefined symbol: zend_ce_countable in Unknown on line 

You have enable `SPL` extension.

**Comment by sergeyklay** [comment]
Also we'll need the way you used to install the Phalcon as detailed as possible
