### ISSUE TITLE
[NFR] Add Gmagic adapter for Phalcon\Image

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13884]
Hello.

I propose add a gmagic adapter for Phalcon\Image component.
Link: https://pecl.php.net/package/gmagick

Why yet another? 
Because gmagick more faster than imagick and works better with colors comparing than gd.

P.S Russian benchmark https://habr.com/ru/post/188666/

**Comment by dschissler** [comment]
In the past I've found that I've needed both since they can both misbehave when doing complex things.

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
