### ISSUE TITLE
[NFR] Many-To-Many relation with composite PKs

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13890]
Consider following code:
```php
/**
 * Initialize method for ItineraryBranch model.
 */
public function initialize()
{
    $this->hasManyToMany(
        [
            'tourId',
            'itineraryId',
            'branchId'
        ],
        __NAMESPACE__ . '\\ItineraryExclusionBranch',
        [
            'tourId',
            'itineraryId',
            'branchId'
        ],
        [
            'exclusionId',
            'branchId'
        ],
        __NAMESPACE__ . '\\ExclusionBranch',
        [
            'exclusionId',
            'branchId'
        ],
        [
            'alias' => 'ExclusionsInBranch'
        ]
    );
}
```
Such relationship will cause `Exception` with message `Not supported` to be thrown by either https://github.com/phalcon/cphalcon/blob/9fae862af1f2685872f9f2d1ed2489eff7e9c535/phalcon/mvc/model/manager.zep#L1252

or

https://github.com/phalcon/cphalcon/blob/9fae862af1f2685872f9f2d1ed2489eff7e9c535/phalcon/mvc/model/manager.zep#L1264

So basically, Many-To-Many relationships can be used only with single primary keys. This isn't a bug, obviously, since the code is clear about not supporting that, but it's a real bummer, hence this NFR.

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
