### ISSUE TITLE
Phalcon not work with xampp

### ISSUE THREAD

**Issue by matupaarela** [phalcon/cphalcon#13896]
I have installed everything as indicated by the Phalcon documentation https://docs.phalconphp.com/3.4/en/webserver-xampp but still the phpinfo does not show phalcon.

**I'm using:**
* xampp v3.2.3
* PHP 7.3.2

I have installed everything as indicated by the Phalcon documentation but still the phpinfo does not show phalcon.

I'm using:
xampp v3.2.3
PHP 7.3.2

*I downloaded phalcon according to the PHP version and architecture of xampp and it still does not work*
![error phalcon](https://user-images.githubusercontent.com/33232227/54293469-0abf0f00-457e-11e9-83b3-596ec9e7b4e7.jpg)

**Comment by TimurFlush** [comment]
Phalcon framework is not console application.
Can you tell what you want to do?

**Comment by Jeckerson** [comment]
@matupaarela Did you tried to reboot your xampp?

**Comment by sergeyklay** [comment]
Could you provide Phalcon and Devtools version? BTW, there is at least 2 PHP: CLI and FPM/CGI. So you have to enable Phalcon for both versions. Finally, I agree with @Jeckerson, you should restart web server after installing Phalcon.

**Comment by lubber-de** [comment]
Did you install phalcon 3.4.3? That's the only phalcon version which runs under php 7.3

I also highly suggest upgrading to php 7.3.3, because php 7.3.2 had several bugs causing at least phalcon incubator to crash php completely
