### ISSUE TITLE
Proposal on adding a LocaleAwareInterface for Translate adapters (and interpolators)

### ISSUE THREAD

**Issue by challet** [phalcon/cphalcon#13905]
Hello,

Some of the Translate adapters and interpolators must be, by design, locale aware. They are currently using various ways to achieve it  : *language* and *locale* constructor options, constructor argument or through a *setLocale* method.

Would it be beneficial to make them all follow the same mechanism ? I'm thinking about a *LocaleAwareInterface* that would remain to be specified.

## Exemples of the interface specifications : 

* one interface for both adapters and interpolators ?
* specifying the constructor ? i.e. don't use an option but add a second param 
* specifying set/getLocale methods ?

## Classes involved : 

(the links are pointing to the locale parts).

* [Phalcon/Translate/Adapter/Gettext](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/translate/adapter/gettext.zep#L188)
* [Phalcon/Translate/Adapter/Database](https://github.com/phalcon/incubator/blob/3.4.x/Library/Phalcon/Translate/Adapter/Database.php#L63) (incubator)
* [Phalcon/Translate/Adapter/Mongo](https://github.com/phalcon/incubator/blob/3.4.x/Library/Phalcon/Translate/Adapter/Mongo.php#L57) (incubator)
* [Phalcon/Translate/Adapter/Redis](https://github.com/phalcon/incubator/blob/3.4.x/Library/Phalcon/Translate/Adapter/Redis.php#L55) (incubator)
* [Phalcon/Translate/Adapter/ResourceBundle](https://github.com/phalcon/incubator/blob/3.4.x/Library/Phalcon/Translate/Adapter/ResourceBundle.php#L49) (incubator)
* [Phalcon/Translate/Adapter/CsvMulti](https://github.com/phalcon/incubator/blob/3.4.x/Library/Phalcon/Translate/Adapter/CsvMulti.php#L79) (incubator)
* [Phalcon/Translate/Interpolator/Intl](https://github.com/phalcon/incubator/blob/3.4.x/Library/Phalcon/Translate/Interpolator/Intl.php#L14) (incubator)

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
