### ISSUE TITLE
Elasticsearch DB Adapter

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#13906]
So im wondering how many people of here are using Elasticsearch and would be interested for having build-in adapter of it in Phalcon(working with ORM/ODM models). We currently have some kind of adapter, it's not perfect, and surely would require a lot of more work but it works for our use cases most of the time, but it's written in php.

I got some kind of green light to introduce it if i want it to phalcon - the question is if we need it.

**Comment by Jeckerson** [comment]
I don't know it makes any sense. Only if wrapper would be something basic which can be extended.

**Comment by Jurigag** [comment]
Well best will be if I provide what you can achieve with it a guess, will try to do it later.

**Comment by david-duncan** [comment]
Sounds like this should be closed in favor of implementing it inside of incubator and then porting here when stability / critical mass is achieved.

**Comment by Jurigag** [comment]
I think the same - i guess first way will be to implement this for incubator, then we can think about moving it to core.
