### ISSUE TITLE
[Bug] Result of empty construction on model properties

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13900]
Hello.

Actual for 3.4.2, and possibly for 4.0 branch.

Please see:
```php
class SomeModel extends \Phalcon\Mvc\Model 
{
    # It's a protected property.
    protected $someProperty;

    # It are getters.
    public function setSomeProperty(){}
    public function getSomeProperty(){ return 'someValue'; }
}

/** @var SomeModel $model **/

var_dump(empty($model->someProperty)); //true (Actual behavior)
var_dump(empty($model->getSomeProperty())); //false (Need behavior)
```

**Comment by ViltusVilks** [comment]
`getSomeProperty() { return 'someValue'; }` returns non-empty result. 
Or this is just a typo in the example code?

**Comment by TimurFlush** [comment]
@ViltusVilks 
**getSomeProperty()** is a getter for **someProperty**, because **someProperty** is protected property. In this case, **empty construction** must be return **false**

**Comment by CameronHall** [comment]
This is because `empty` will call `__isset` (if defined) on inaccessible properties. Related to #13518.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14659
