### ISSUE TITLE
[NFR] Volt Option For Default Output

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13941]
Request for default data output in ``OBJECT``, ``ARRAY``, or even ``JSON``.
So we can use ``{{data.name}}`` instead of ``{{data['name']}}``.
Not having to define ``return (object) $array;`` in all functions.

```php
$di->set('view', function() {
 $view = new View();
 $view->setViewsDir('../app/view/');
 $view->registerEngines([
  '.volt' => function($view, $di) {
   $volt = new Volt($view, $di);
   $volt->setOptions([
    'compiledPath' => '../app/cache/',
    'compiledExtension' => '.html',
    'compiledSeparator' => '_',
    'output' => 'object',
  ]); #options
  return $volt;
 } #volt
]); #engines
  return $view;
}); #view
```

**Comment by JABirchall** [comment]
This will cause a lot more issue then it solves.

**Comment by sergeyklay** [comment]
@v00v Could you please provide an example of pseudo code?

**Comment by ruudboon** [comment]
I agree with @JABirchall I think this will cause a lot of confusion.

**Comment by v00v** [comment]
If you guys think this would make more problems than never mind :)
