### ISSUE TITLE
Phalcon model interface doens't allow false return

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#13947]
When I overload the findFirst and run a query that doesn't match I get the following error:
``fatal error: Uncaught TypeError: Return value of MyModel::findFirst() must implement interface Phalcon\Mvc\ModelInterface, bool returned in xxxxx on line xx``

Looks like the findFirst can return false but isn't allowed by the interface. Unsure why this only show when overloading the method.

**Comment by talal424** [comment]
return null or an instance of Phalcon\Mvc\ModelInterface

**Comment by ruudboon** [comment]
@talal424 Interface doesn't allow null.

**Comment by ruudboon** [comment]
Fastest bug fix ever

**Comment by SmartyGunjan** [comment]
phalcon 4.1 php 7.4 getting the same error.
