### ISSUE TITLE
Transaction rollback exception throwing should be optional

### ISSUE THREAD

**Issue by david-duncan** [phalcon/cphalcon#13949]
Revival of https://github.com/phalcon/cphalcon/issues/13324

### Expected behavior

Rolling back a transaction should rollback a transaction. Not have unintended side effects.

Currently $transaction->rollback() throws an exception if successful, and if not, it just returns true

This makes exception handling on the implementation side unwieldy if the user wants a proper exception to be thrown out of their code, or if they want to resume operation post rollback

### Current workaround if you don't want an exception throw
```php
try {
catch (\Exception $e) {
  //something went wrong, roll back our transaction
  try {
    $transaction->rollback()
  catch (TransactionFailed $e) {
    //throw a proper userland exception, or swallow if behavior can be continued as normal
  }
}

```

### Solutions

I see 4 options to be had here:

1. Exception throwing is removed from rollback
2. Exception throwing is made optional via an extra parameter
3. Exception throwing is disabled via an extra parameter
4. Scoping the boolean to the transaction class

1 makes the most sense to me but breaks anyone who is relying on this behavior. However, it seems to be the cleanest based on the existing method signature

3 seems to be the path of least resistance to implementation and would suffice.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14053
