### ISSUE TITLE
[NFR] Remove Single Quotes From Volt Names

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13942]
It would be nice to remove all the single quotes from volt names. For example right now to do an array I would type; ``{{data['name']}}`` why not simply do ``{{data[name]}}`` eliminating the need to type single quotes.

**Comment by JABirchall** [comment]
Propose if the definition of a string were removed, how would you define a string?

**Comment by v00v** [comment]
@JABirchall String can be used with optional double quotes. Like ``{{"some string here"}}``, I'm talking about actual data item from array or object to be used like ``{{array[name]}}`` to be a bit more similar to object ``{{object.name}}''. Or maybe we can have something more simlar for array's too like ``{{array_name}}`` for example. This would remove brackets completely. If its done internally, then both object and array can use the same period seperator like ``{{item.name}}``.

**Comment by SidRoberts** [comment]
It's not possible. Take this example:

```php
$data = [
    'name' => 'Sid',
    'type' => 'person',
];

$name = 'type';
```

What would this display?

```volt
{{ data[name] }}
```

**Comment by Jurigag** [comment]
How we should know then that `name` is not variable in your first example?

**Comment by niden** [comment]
Good suggestion but we are not going to make this change. Doing what is suggested here would require significant changes to the volt parser and would pretty much require all existing applications to be fully rewritten (at least their volt templates).

The reward by doing this is not justifying the effort to refactor or benefit to the users.

**Comment by v00v** [comment]
Maybe in Phalcon 5.0 then? ^_^
