### ISSUE TITLE
[NFR] Offical Package for Arch Linux

### ISSUE THREAD

**Issue by LearnPhalcon** [phalcon/cphalcon#13944]
Request for official "php-phalcon" pacakge for Arch Linux OS. Current AUR packages is outdated most of the time, see https://aur.archlinux.org/packages/?O=0&K=phalcon  Latest package in AUR is 3.4.2 :( The only other option is to compile it manually. It would be nice to see such a great php framework like Phalcon in official arch core packages. But I think for this to be achived, actual offical phalcon package has to be created by Phalcon developers. Similarly how you done it for DEB/RPM on https://packagecloud.io/phalcon I think one of the reasons why not many Arch users use phalcon because its not in core packages. Thank you!

**Comment by sergeyklay** [comment]
Please open a feature request [in the corresponding repository](https://github.com/phalcongelist/packagecloud).

**Comment by v00v** [comment]
@sergeyklay Done, Thank you! #41
