### ISSUE TITLE
[NFR] Shorter Volt Filter Names or Optional Shorter Alias Names

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13940]
Request for shorter volt filter names or at least optional alias names. Try to stay away from underline names ``example_name_here``. When using this filters directly in volt templates, the shorter the names the better. Also it would be nice to not having to use single quotes in filter functions. For example, something like this ``{{'désolé'|ce('utf8', 'latin1')}}`` should simply be ``{{'désolé'|ce(utf8, latin1)}}``. Note there is no single quotes around utf8 and latin1.

**Existing Filters**
(current filter names -> alias names request)
* capitalize -> title ``{{'hello'|title}}``
* convert_encoding -> encode and/or ce ``{{'désolé'|ce(utf8, latin1)}}``
* e -> esc ``{{'<h1>Hello</h1>'|esc}}``
* escape_attr -> eattr ``{{string|eattr}}``
* escape_css -> ecss ``{{stylesheet|ecss}}``
* escape_js -> ejs ``{{javascript|ejs}}``
* json_encode -> jenc and/or je ``{{arraydata|je}}``
* json_decode -> jdec and/or jd ``{{jsondata|jd}}``
* left_trim -> ltrim and/or lt ``{{string|ltrim}}``
* right_trim -> rtrim and/or rt ``{{string|rtrim}}``
* length -> len ``{{string|len}}``
* lower -> lc ``{{string|lc}}``
* upper -> uc ``{{string|uc}}``
* url_encode -> uenc and/or ue ``{{post.link|ue}}`` _similar to ``e`` name_

**Additional Filters Request**
* date ``{{posted|date(Y-m-d)}}``
* explode ``{{genres|explode( | )}}``
* count ``{{array|count}}``

Thank you!

**Comment by JABirchall** [comment]
Some of these are ok, some are not. 


    capitalize -> title {{'hello'|title}} - This is good
    convert_encoding -> encode and/or ce {{'désolé'|ce(utf8, latin1)}} 
    e -> esc {{'<h1>Hello</h1>'|esc}} - This is good, though people would use `e` more
    escape_attr -> eattr {{string|eattr}} - this could be confusing to some
    escape_css -> ecss {{stylesheet|ecss}} - this could be confusing to some
    escape_js -> ejs {{javascript|ejs}} - this could be confusing to some
    json_encode -> jenc and/or je {{arraydata|je}} - this could be confusing to some, maybe json_enc
    json_decode -> jdec and/or jd {{jsondata|jd}} - this could be confusing to some, maybe json_dec
    left_trim -> ltrim and/or lt {{string|ltrim}} - This is good
    right_trim -> rtrim and/or rt {{string|rtrim}} - This is good
    length -> len {{string|len}} - This is good
    lower -> lc {{string|lc}} - I would rather keep this upper
    upper -> uc {{string|uc}} - I would rather keep this lower
    url_encode -> uenc and/or ue {{post.link|ue}} similar to e name - this could be confusing to some, maybe url_enc

**Comment by v00v** [comment]
I don't see why it would be confussing if it can be properly documented O_o Like what is ``e`` if I haven't looked in documentation I would never knew. So a lot of confussion you describing is not valid. Will have shorter names and its very easy to remember after you read documentation. You can't code in Phalcon without reading it anyway. There is a lot of custom non standard code that Phalcon does differently form PHP.

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
