### ISSUE TITLE
[NFR] When no Event "data" is supplied, do not pass the parameter

### ISSUE THREAD

**Issue by CameronHall** [phalcon/cphalcon#13965]
When firing an event without "data" the default value passed to the event is "null". IMO, this shouldn't be passed at all when it's not provided to the event and left up to the event itself to set a default value in the parameters.

https://github.com/phalcon/cphalcon/blob/master/phalcon/events/manager.zep#L325

For example:
```php
<?php
declare(strict_types=1);
namespace Hello;

use Phalcon\Events\Event;
use Phalcon\Mvc\Model;

class MyComponent
{
    public function detect(Event $event, Model $model, array $extra = []): bool
    {
```

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
