### ISSUE TITLE
[BUG] Updating a model fails after fetching its related records

### ISSUE THREAD

**Issue by zsilbi** [phalcon/cphalcon#13964]
When fetching a record (`Robots`) and getting it's related models (`RobotParts`) a `RuntimeException` is being thrown when trying to save/update afterwards.

My observations:
- It only happens when after accessing `hasMany` or `hasManyToMany` type of relations.
- I have tried a lot of different models (names, aliases) and relations
- When creating a new model the error not occurs
- It doesn't matter if there are any related records in `RobotParts` table
- It only occurs when accessing the related records as property (saving after `$robot->getRobotParts()` works fine)

Output error when using hasMany

```php
RuntimeException
Call to undefined method \x01::writeattribute() 
```
Output error when using  hasManyToMany

```php
RuntimeException
Call to undefined method \x01::save() 
```

Script to reproduce the issue (only the relevant parts)
```php
class Robots extends \Phalcon\Mvc\Model {
    public function initialize() {
        $this->hasMany('id', 'RobotParts', 'robotId', [
            'alias' => 'robotParts'
        ]);
    }
}

public function main() {
    $robot = Robots::findFirst();
    $robot->robotParts;
    $robot->save(); // or $robot->update();
}
```

Current workaround:
```php
public function main() {
    $robot = Robots::findFirst();
    $robot->getRobotParts();
    $robot->save();
}
```

It's a widely used feature and it's very easy to reproduce so I think - and hope - that it must be some kind of incompability, otherwise it would have been discovered previously.

### Details
* Phalcon version: 4.0.0-alpha.3
* PHP Version: 7.2.16-1
* Operating System: Ubuntu 16.04
* Installation type: Compiling from source
* Zephir version (if any): Version 0.11.11-b661a58
* Server: nginx
* Other related info (Database, table schema): MariaDB 10.1.37

**Comment by zsilbi** [comment]
I wrote tests to confirm the issue and it failed in CI with a rather strange error message.

` [PHPUnit\Framework\Exception] Invalid callback , no array or string given`

**Comment by niden** [comment]
Resolved

**Comment by niden** [comment]
Actually my bad, this was not resolved 100%. We need to do a lot more regression testing with the proposed fix from the PR attached to this issue.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14035
