### ISSUE TITLE
Volt view cache inconsistent service name

### ISSUE THREAD

**Issue by davihu** [phalcon/cphalcon#13961]
Currently volt cache service `viewCache`

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/engine/volt/compiler.zep#L1696

is not consistent with the name in FactoryDefault `viewsCache`

https://docs.phalconphp.com/3.4/en/di.html#service-name-conventions

It should be `viewsCache` or `viewCache`.
Thanks

**Comment by SidRoberts** [comment]
It should be `viewCache`. I've submitted a PR to fix it in the documentation for 4.0.
