### ISSUE TITLE
[NFR] Make Micro Collection create handler instance with DI

### ISSUE THREAD

**Issue by berrymore** [phalcon/cphalcon#13967]
As I see in the MVC `Application`, the `Dispatcher` creates a `Controller` using the `Di`. When I have been started to use the `Micro` I expected the same behavior with a `Micro\Collection` in the `lazy` mode.

As I understood the `Handler` instance is created by the `\Phalcon\Mvc\Micro\LazyLoader` at [49 line](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/micro/lazyloader.zep#L49). The `LazyLoader` is used in the [Micro](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/micro.zep#L372) where the `Di` is presented.

So I think it's possible to pass the `Di` as an argument to the `LazyLoader` constructor to make the new `Handler` instance.

**Comment by sergeyklay** [comment]
@berrymore Could you please provide a minimal example which shows the issue?

**Comment by berrymore** [comment]
@sergeyklay When you have composed your MVC Application, you can pass the controller definition to the DI.

```php
// Somewhere in bootstrap.php
<?php
// ...
$di->setShared('App\\Controllers\\IndexController', [
     'className' => 'App\\Controllers\\IndexController',
     'arguments' => [
         ['type' => 'service', 'name' => 'router']
      ]
]);
```

```php
<?php
// IndexController.php
public function __constructor($router)
{
    var_dump($router->getDefaults());
}
```

But if you'll do the similar in a Micro application.

```php
$main->setHandler('App\\Controllers\\IndexController', true);
$app->mount($main);
```

You will get an Exception that `IndexController` cannot be instantiated because 0 arguments was specified instead of 1.

Because "lazy-handler" is created by [this code](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/micro/lazyloader.zep#L49) with a simple `new` statement, while "MVC Controllers" are being created by Dispatcher using `Di` within [this code](https://github.com/phalcon/cphalcon/blob/master/phalcon/dispatcher.zep#L496)

------

I think it is possible to pass the DI from `Micro` to `LazyLoader` class [at this point](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/micro.zep#L372) to achieve the same behavior as in MVC Controllers.

Otherwise it should be refactored to give a developer an opportunity to specify a custom "resolver" instead of `LazyLoader` class.

**Comment by SidRoberts** [comment]
(I fixed a typo in @berrymore's code, just in case anybody copies and pastes it into their project :wink: )

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
