### ISSUE TITLE
[BUG] Volt compiled options not working

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13968]
In phalcon version **4.0.0-alpha.3** all compiled options in volt not working properly.

```php
$di->set('view', function() {
  $view = new View();
  $view->setViewsDir('../app/views/');
  $view->registerEngines([
    '.volt' => function($view) {
      $volt = new Volt($view, $this);
      $volt->setOptions([
        'compiledPath' => '../app/cache/',  /* NO LONGER WORKS */
        'compiledExtension' => '.html',  /* NO LONGER WORKS */
        'compiledSeparator' => '_',  /* NO LONGER WORKS */
        'stat' => true,
        'compileAlways' => true,
      ]); #options
      return $volt;
    } #volt
  ]); #engines
  return $view;
}); #view 
```

* Update-1: Looks like **4.0.0-alpha.4** is out now, will try it and report back - if it has same issue.
* Update-2: Same issue with **4.0.0-alpha.4** did something change again in volt?
* Update-3: My bad, it looks like it has changed per my request LOL https://github.com/phalcon/cphalcon/issues/13815

**Comment by v00v** [comment]
Re-opening this bug, looks like this new changes and old options not working for me in **4.0.0-alpha.4**. Here is the code I used to test it. All it does is place all the cached files in my ``/project/public/`` directory were my ``index.php`` file is. This is very bad for security.

```php
$di->set('view', function() {
  $view = new View();
  $view->setViewsDir('../app/views/');
  $view->registerEngines([
    '.volt' => function($view) {
      $volt = new Volt($view, $this);
      $volt->setOptions([
        'path' => '../app/cache/',  /* NOT WORKING */
        'extension' => '.html',  /* NOT WORKING */
        'separator' => '_',  /* NOT WORKING */
        'stat' => true,
        'always' => true,
      ]); #options
      return $volt;
    } #volt
  ]); #engines
  return $view;
}); #view 
```

**Comment by v00v** [comment]
Okay, I done more testes and only thing works properly is when only one option set ``compiledPath`` if anything else added like ``compiledExtension`` it will cache to wrong directory ``/project/public/``.

**Comment by niden** [comment]
Resolved
