### ISSUE TITLE
[RFC][NFR] Volt PHP 7 strict type support

### ISSUE THREAD

**Issue by JABirchall** [phalcon/cphalcon#13978]
Volt should support but not be limit to strict types in views. A number of changes would be needed for this. First would be a Volt option to enforce strict types in views.

```php
$volt->setOptions([
    'strictTypes' => true,
]);
```
With this option set, all compiled volt views MUST have typed variables. Which inherently requires the second change. The volt `set` keyword requires a type to be set, this is not required but allowed if `strictTypes` is set to false or not set.

```twig
{% set int price = 100; %}
{% set array myArray = {'Apple', 'Banana', 'Orange'} %}
{% set string world = 'hello' %}
{% set bool external = false %}
```

[List of reserved types](https://www.php.net/manual/en/reserved.other-reserved-words.php)

**Discuss**

Proposed version: 4.x

**Comment by Jurigag** [comment]
Well, there is actually no variable types in php yet. I guess we could make it - but it would introduce additional overhead to templates.

PHP 7.4 will support only https://wiki.php.net/rfc/typed_properties_v2

I guess then we could just then use some kind of local objects per view, but still, not typed variables in php - creating such variables in volt would require to just call some kind of function which will create this variable and check if value type is correct.

**Comment by CameronHall** [comment]
I don't want to sound like a negative nancy. But what value/benefits does strict types bring to Volt templates besides being something that'd be "cool to have"? It's an interesting idea, and definitely worth consideration but I'm not sure it'd be worthwhile if it introduces more overhead while providing little value.
