### ISSUE TITLE
[NFR] Dispatcher setNoSuffix()

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13984]
Personally I don't like using standard suffix for example like ``IndexController`` or ``indexAction()`` and always remove it with ``setControllerSuffix('')`` and ``setActionSuffix('')``. If its not too much to ask, can we please have one option to use both of those with something like ``setNoSuffix()`` ? Note that ``setNoSuffix()`` should also remove the use of quotes inside.

It can be an additional option for example. It's not a very big deal, but its shorter and makes more sense, when both suffixes are not used. Also, please do not remove this suffix removal options completely in the future phalcon releases. At least leave the old ``setControllerSuffix()`` and ``setActionsuffix()`` in place.

Old Options Code Example:
```php
$di->set('dispatcher', function() {
  $dp = new Dispatcher();
  $dp->setControllerSuffix(''); // OLD OPTION
  $dp->setActionSuffix(''); // OLD OPTION
  $dp->setDefaultNamespace('App\Controllers');
  return $dp;
}); #dispatcher
```

Request New Option Code Example:
```php
$di->set('dispatcher', function() {
  $dp = new Dispatcher();
  $dp->setNoSuffix(); // NEW OPTION
  $dp->setDefaultNamespace('App\Controllers');
  return $dp;
}); #dispatcher
```

Thank you. Phalcon Is The Best!

**Comment by sergeyklay** [comment]
In general I'm prefer something more human readable like:
```php
$dispatcher->disablePrefixes();
```
or even:
```php
$dispatcher->withoutPrefixes();
```

**Comment by v00v** [comment]
@sergeyklay Yeah ``disablePrefixes()`` works too.

**Comment by sergeyklay** [comment]
Yes, you're right. Of course  suffixes

**Comment by v00v** [comment]
This maybe weird but I hate using standard suffixes. So please at least don't remove ability to disable this with ``$dp->setControllerSuffix('');`` ``$dp->setActionSuffix('');`` Thank yoU!

**Comment by sergeyklay** [comment]
I want to close this issue because adding (and maintaining) a new method, which is not something fundamentally new, and also aims to reduce the project code by 1 line, is not our current priority.
