### ISSUE TITLE
New chunk() method for Phalcon ORM

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#14005]
Hello.

I suggest to add the chunk() method for Phalcon ORM

Please see below image (from Laravel documentation) for to know his behavior:
![Снимок](https://user-images.githubusercontent.com/29764676/56430683-8b410000-62e0-11e9-841c-78f7e5f12e6c.PNG)

**Comment by david-duncan** [comment]
Cursors already exist: https://docs.phalconphp.com/3.4/en/db-models#model-resultsets

**Comment by TimurFlush** [comment]
@david-duncan okay, thank you

**Comment by ekmst** [comment]
I suggest adding the `chunk` parameter in the options of the`Model::find` method. Instead of a separate method.

```php
Robots::find(
    [
        'chunk' => 3
    ]
);
```

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
