### ISSUE TITLE
[NFR] Map record to target model (Inheritance mapping)

### ISSUE THREAD

**Issue by wajdijurry** [phalcon/cphalcon#14007]
This is a new feature request to add ability in Phalcon ORM to map records to it's target models.
Example:
Products table
![Screenshot from 2019-04-21 00-08-19](https://user-images.githubusercontent.com/25797257/56462293-9de33400-63c9-11e9-96ed-1410a3adaaf2.png)

And target models:
```
class Physical extends Product
{
    // physical product attributes go here
}

class Downloadable extends Product
{
    // downloadable product attributes go here
}
```

So, when you fetch the records using query builder or find method(s), you'll get results like this:
```
/* array(2) {
  [0]=> object(Physical)#5 (1) {
    ["product_weight"] => float(1.5)
  }
  [1]=> object(Downloadable)#3 (1) {
    ["product_digital_size"]=> int(89128960)
  }
} */
```

This is very useful feature and keep you away from using third parties ORM libraries.

**Comment by CameronHall** [comment]
Polymorphism is the word we're after I think

**Comment by wajdijurry** [comment]
> Polymorphism is the word we're after I think

Will this feature be included in future releases of Phalcon ?

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
