### ISSUE TITLE
[NFR] BCMath wrapper

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#14008]
Hello!

I suggest to add a bcmath wrapper in one of two ways:
1) Phalcon\Helper\Math class
2) Or extend the \Phalcon\Helper\Number class

This will allow you to perform mathematical operations with high accuracy at the framework level if it is relevant.

Please see my library for example:  https://github.com/TimurFlush/Math

**Comment by TimurFlush** [comment]
It would be nice if Phalcon provided his own wrapper, because bcmath cannot automatically calculate the full accuracy of multiplication/division.

**Comment by virgofx** [comment]
I think this is a bad idea. 

There is no need for a wrapper for very specific math functions in BCMath. Phalcon could wrap every other extension with mindless `if` extension loaded checks ... which hurts performance and takes away from the core simplicity of Phalcon.

**Comment by TimurFlush** [comment]
@virgofx Please note that some methods in my library are not specific to BCMath.
