### ISSUE TITLE
[BUG] Flash\Session output() throws exception when session is empty

### ISSUE THREAD

**Issue by zsilbi** [phalcon/cphalcon#14023]
### Actual Behavior

Flash is initialized in bootstrap.
```php
$di->set('flashSession', function () {
   return new \Phalcon\Flash\Session();
});
```

In index.volt
```html
<div id="flash-messages">{{ flashSession.output() }}</div>
```

Result when there are no messages:

```php
phalcon/Flash/Session.zep:90: [Exception] The argument is not initialized or iterable()
```

Expected behavior would be an empty output.

### Details

* Phalcon version: 4.0.0-alpha.4
* PHP Version: 7.2.16 and 7.3.4
* Operating System: Ubuntu 16.04
* Installation type: Compiling from source
* Zephir version (if any): Version 0.11.12
* Server: nginx
* Other related info (Database, table schema): MariaDB 10.1.37

**Comment by niden** [comment]
Addressed in: https://github.com/phalcon/cphalcon/pull/14024
