### ISSUE TITLE
Model cache empty data

### ISSUE THREAD

**Issue by zuozhehao** [phalcon/cphalcon#14022]
When I try to set caching parameters when using queries, I query a record that does not exist, Phalcon caches empty data.

When I write the data to Mysql, I execute it again.
When the cache does not expire, I execute the query, and Phalcon returns the cached data (empty), even though the record has been written to the database.

```php
function getByEmail(string $email)
{

    $key = 'user_email_' . $email;

    $result = UserModel::findFirst(

        [
            'conditions' => 'email = ?0',
            'bind'       => [$email],
            'cache'      => ['key' => $key]
        ]

    );
    
    return $result;
    
}
```
### Details

* Phalcon version: (`3.4.3`)
* PHP Version: (`7.2.9`)
* Operating System:Centos7
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx 
* Other related info (Database, table schema):

**Comment by CameronHall** [comment]
Have you registered a modelCache service?

**Comment by zuozhehao** [comment]
Yes.

Maybe I am not clear enough, the cache configuration is ok, I see redis is data.
When I query a data that doesn't exist, Phalcon also performs a cache operation, except that it caches empty data.

**Comment by zuozhehao** [comment]
```
DROP TABLE IF EXISTS `table_email`;
CREATE TABLE `table_email`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(150) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `email`(`email`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
```

Create a table without writing any data.

```
function getByEmail(string $email)
{

    $key = 'user_email_' . $email;

    return EmailModel::findFirst(

        [
            'conditions' => 'email = ?0',
            'bind'       => [$email],
            'cache'      => ['key' => $key],
        ]

    );

}

// First
$email = 'example@mail.com';
$result= getByEmail($email); // empty data, At this time, the redis cache already has a data with the key user_email_example@mail.com.

// Second
$emailModel = new EmailModel;
$emailModel->email = $email;
$email->save(); // success 

// Third
$result = getByEmail($email); // empty data, Because it uses the data inside redis.

```

**Comment by zsilbi** [comment]
>@zuozhehao: When I query a data that doesn't exist, Phalcon also performs a cache operation, except that it caches empty data.

In my opinion, caching that a row is non-existent in a database can be useful in some cases.

From the docs:

> When a cached resultset needs to be invalidated, you can simply delete it from the cache using the key specified as seen above.
https://docs.phalconphp.com/3.4/en/db-models-cache

In this example you should have invalidated the cache after saving the new `$emailModel`.

**Comment by niden** [comment]
Closing this after @zsilbi 'e explanation
