### ISSUE TITLE
[BUG] Config\Adapter\Ini array to string conversion notices

### ISSUE THREAD

**Issue by zsilbi** [phalcon/cphalcon#14025]
### Actual Behavior

config.ini
```ini
myArray[] = value1
myArray[] = value2
```

> Provide minimal script to reproduce the issue

```php
$config = new \Phalcon\Config\Adapter\Ini('config.ini');
```

Result:

```
Notice: Array to string conversion
Notice: Array to string conversion
```

### Details

* Phalcon version: 4.0.0-alpha.4
* PHP Version: 7.2.16 and 7.3.4
* Operating System: Ubuntu 16.04
* Installation type: Compiling from source
* Zephir version (if any): Version 0.11.12
* Server: nginx
* Other related info (Database, table schema): MariaDB 10.1.37

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14026
