### ISSUE TITLE
Html\Tag::prependTitle() and Html\Tag::appendTitle() inconsistency with Tag counterparts

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#14039]
As per changelog, `Phalcon\Tag` is to be replaced with `Phalcon\Html\Tag`, yet some of their methods have not only different signatures, but completely different implementations.

While that is not an issue itself, the way above mentioned methods behave in `Phalcon\Html\Tag` is wrong.

`Phalcon\Tag::prependTitle(var title)` implementation
https://github.com/phalcon/cphalcon/blob/1d4e2f19c8f4a83ba1d90e4be9f72050d4091b08/phalcon/Tag.zep#L919-L933

`Phalcon\Html\Tag::prependTitle(array title)` implementation
https://github.com/phalcon/cphalcon/blob/1d4e2f19c8f4a83ba1d90e4be9f72050d4091b08/phalcon/Html/Tag.zep#L1075-L1083

`Phalcon\Tag` implementation is better.

**Comment by niden** [comment]
Nice catch. Thanks. We will align those shortly.

**Comment by emiliodeg** [comment]
Why there are 2 ways to do the same? `Phalcon\Tag` should not be a `Phalcon\Html\Tag` proxy? implementing `DI` or maybe `Phalcon\Tag` should desappear in favor of `Phalcon\Html\Tag`?

**Comment by scrnjakovic** [comment]
@emiliodeg `Phalcon\Tag` is going away, as said earlier. It will, however, stay for a while for backward compatibility.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14052
