### ISSUE TITLE
[NFR] Dynamic Loop Counters When Using Pagination

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14046]
Can we please have dynamic loop counter when using pagination? Because right now if you use ``loop.index`` or ``loop.revindex`` and then paginate your array, it will show same numbers on each page.

This code when using NativeArray pagination will show exactly same numbers on each page. So if I have array of 10 items and then paginate my items 2 per page, all I will see is # 1 & # 2 on each page. Even if I click on second page it will still show # 1 & # 2.
```php
{% for robot in robots %}
Index: # {{loop.index}}
RevIndex: # {{loop.revindex}}
{% endfor %}
```

Request to have something like ``loop.count`` and ``loop.revcount`` so when we do code something like this, we will have proper counted numbers. Any page we click will show proper counter of items # 1 & # 2 on page 1 and then when we click on page 2 it should show # 3 & # 4 and so on.
```php
{% for robot in robots %}
Count: # {{loop.count}}
RevCount: # {{loop.revcount}}
{% endfor %}
```

Right now the only workaround is to make own counter and pass that in array. But it would be very useful if we can automate this process similarly like we do with ``loop.index`` and ``loop.revindex`` when content is not paginated.

**Comment by JABirchall** [comment]
Is this not already in?

loop.index | The current iteration of the loop. (1 indexed)
-- | --
loop.index0 | The current iteration of the loop. (0 indexed)
loop.revindex | The number of iterations from the end of the loop (1 indexed)
loop.revindex0 | The number of iterations from the end of the loop (0 indexed)
loop.first | True if in the first iteration.
loop.last | True if in the last iteration.
loop.length | The number of items to iterate

**Comment by v00v** [comment]
As explained above, this doesn't work properly with native array pagination for some reason.

**Comment by niden** [comment]
@v00v Can you open an issue with a small script to replicate what is not working with nativearray?

**Comment by v00v** [comment]
@niden Sure, I'll do more testes locally, than report back with source code.

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
