### ISSUE TITLE
[NFR] Phalcon\Countdown

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14047]
Request for phalcon countdown feature for relative dates and times. So we can convert dates like "2019-05-07" to "Today" or "2019-05-06" to "Yesterday" or "2019-05-08" to "Tomorrow" and if there is more than one day then say "2 days ago" or if the date until then say "in 2 days" and so on.

#### Example Functions:
* ``Countdown::timer($dt)`` -- Should auto detect if the date/time is before (since) or after (until).
* ``Countdown::diff($dt1, $dt2)`` -- Should be used for comparing two dates/times.
* ``Countdown::since($dt)`` -- Should be used only for before dates/times.
* ``Countdown::until($dt)`` -- Should be used only for after dates/times.
* ``Countdown::live($dt)`` -- Should be used for live counter of dates/times since or until.

``$dt`` -- simply means any format of date and/or time.

#### Example Imput:
All functions should accept dates/times in any given format using ``strtotime``. For example;
* ``yyyy`` -- Years
* ``yyyy-mm`` -- Years & Months
* ``yyyy-mm-dd`` -- Years & Months & Days
* ``yyyy-mm-dd hh`` -- Years & Months & Days & Hours
* ``yyyy-mm-dd hh:ii`` -- Years & Months & Days & Hours & Minutes
* ``yyyy-mm-dd hh:ii:ss`` -- Years & Months & Days & Hours & Minutes & Seconds
* (Maybe even accept ``am`` and ``pm``

**Comment by Jeckerson** [comment]
What about Carbon?

https://carbon.nesbot.com/

`Carbon::since()`
`Carbon::diff()`
etc...

**Comment by ruudboon** [comment]
Also the native php  \DateTime functions could be helpful.
```
<?php
function names($nrOfDays)
{
    switch ($nrOfDays){
        case 0 : return "today";
        case 1 : return "yesterday";
        case 7 : return "last week";
        default:
            return "No idea how to call it. Let's say ".$nrOfDays." of days.";
    }
}


$now= new \DateTime();
$compare= new \DateTime("2019-05-11");
$diff= $compare->diff($now);
echo names($diff->format("%a"));
```

**Comment by scrnjakovic** [comment]
You mean like phalcon's native [moment.php](https://github.com/fightbulc/moment.php) implementation? As in `Phalcon\Moment` or `Phalcon\Date`? I'd vote for it. I'm not sure I'd call it Countdown though.

**Comment by virgofx** [comment]
👎 Not framework functionality - too specific ... plus other specific alternatives exist as well as NATIVE alternatives.

**Comment by niden** [comment]
I will close this. There are alternatives such as `Carbon`, `DateTime` and `moment.php` that can do this task easily. Maybe in the future we can revisit this but if anyone wants to take a stab at this we can add it to the incubator.
