### ISSUE TITLE
"PHP Warning:  count(): Parameter must be an array or an object that implements Countable" in Phalcon Volt for loop

### ISSUE THREAD

**Issue by naig97** [phalcon/cphalcon#14042]
### Expected and Actual Behavior

I just upgraded my DEV server to PHP 7.3 and Phalcon 3.4.3 and checked my Apache Error Log while testing. The following error appears since the upgrade:

"PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /opt/qtools/cache/volt/common%%controllers%%..%%views%%partials%%header.volt.php on line 27"

Line 27 in .volt.php file:
```php
<?php $v137575430011460628521iterator = $externalLinks; $v137575430011460628521incr = 0; $v137575430011460628521loop = new stdClass(); $v137575430011460628521loop->self = &$v137575430011460    628521loop; $v137575430011460628521loop->length = count($v137575430011460628521iterator); $v137575430011460628521loop->index = 1; $v137575430011460628521loop->index0 = 1; $v137575430011460628521loop->revindex     = $v137575430011460628521loop->length; $v137575430011460628521loop->revindex0 = $v137575430011460628521loop->length - 1; ?><?php foreach ($v137575430011460628521iterator as $name => $url) { ?><?php $v137575430    011460628521loop->first = ($v137575430011460628521incr == 0); $v137575430011460628521loop->index = $v137575430011460628521incr + 1; $v137575430011460628521loop->index0 = $v137575430011460628521incr; $v13757543    0011460628521loop->revindex = $v137575430011460628521loop->length - $v137575430011460628521incr; $v137575430011460628521loop->revindex0 = $v137575430011460628521loop->length - ($v137575430011460628521incr + 1)    ; $v137575430011460628521loop->last = ($v137575430011460628521incr == ($v137575430011460628521loop->length - 1)); ?>
```
Referring code in header.volt:
```php
<ul class="dropdown-menu" role="menu">
                    {% for name, url in externalLinks %}
                        <li>
                            <a target="_blank" href="{{ url(url) }}"> {{ name }} </a>
                        </li>
                    {% endfor %}
                </ul>
```

Line wich provides $externalLinks to view:
```php
$this->view->externalLinks = json_decode(\MyApp\Common\Models\SystemSettings::findFirstByLabel('externalLinks'));
```

### Details

* Phalcon version: 3.4.3
* PHP Version:  7.3.5 (cli)
* Operating System: CentOS Linux release 7.6.1810 (Core) 
* Installation type: installing via package manager
* Zephir version (if any): 0.10.15
* Server: Apache

**Comment by Jeckerson** [comment]
What is type of `externalLinks` variable, make `var_dump()` and check if it is array type and not boolean.

**Comment by Jeckerson** [comment]
Also, seems that you upgraded from 7.0 or 7.1 to 7.3...

> PHP 7.2 deprecated quite a lot of functions and buggy use cases. In PHP 7.2, if you call count() on a variable that is not "countable", PHP **shows a warning about it**. A common fix was to check if the given variable is "countable" before calling count() on it.

**Comment by Jurigag** [comment]
Looks like we would need to update this generated code in php file to check is variable is array or implements countable. Also This is also case in php 7.2, in php 7.3 there is method for this - `is_countable` which we could potentially use.

**Comment by sergeyklay** [comment]
@Jurigag Could you send a patch

**Comment by Jurigag** [comment]
Well, im not specialist in volt departments and how it produces php, so it's not so easy for me.

**Comment by sergeyklay** [comment]
You have to change this code
```diff
$this->view->externalLinks = json_decode(
-    \MyApp\Common\Models\SystemSettings::findFirstByLabel('externalLinks')
+    \MyApp\Common\Models\SystemSettings::findFirstByLabel('externalLinks'),
+    true
);
```
to be able to iterate through `externalLinks`.

We cannot do anything about it. PHP 7.3 has become stricter to checks of this type and in my opinion it is even better when a language finds errors in your code (instead of you).

**Comment by naig97** [comment]
thank you, works fine

**Comment by tot-ra** [comment]
adding 
```
{% if somevar %}
{% endif %}
```
around foreach block also helps :D

**Comment by OrangeTanguine** [comment]
Hi !
Force type with (array) solved for me...
` (array)json_decode(json_encode([...]),FALSE);`
