### ISSUE TITLE
Router returns notFound when using query parameters

### ISSUE THREAD

**Issue by Enzo-life** [phalcon/cphalcon#14087]
I have a simple router config in Phalcon 4.0:
```
use Phalcon\Mvc\Router;
$router = new Router(false);
$router->notFound(['controller' => 'Http', 'action' => 'code404']);
$router->add('/', ['controller' => 'index', 'action' => 'index']);
```
http://my.domain/ returns something from index controller. But when i add even symbol '?' to my url (http://my.domain/?), it returns 404 page. I can't get what should i change in route and didn't found any information about routing query parameters in documentation.

P.S. I debugged $_GET when using any parameters, they are present.

I asked at discussion forum, but Emilio Degiovanni said it's probably a bug. But as i see in topics, people can use GET parameters as well, so maybe i'm just doing something wrong. 

Help pls :)

**Comment by scrnjakovic** [comment]
What is your [URI source](https://docs.phalconphp.com/3.4/en/routing#uri-sources)?

```php
<?php

use Phalcon\Mvc\Router;

// ...

// Use $_GET['_url'] (default)
$router->setUriSource(
    Router::URI_SOURCE_GET_URL
);

// Use $_SERVER['REQUEST_URI']
$router->setUriSource(
    Router::URI_SOURCE_SERVER_REQUEST_URI
);
```
Very likely it's `Router::URI_SOURCE_GET_URL`. The query string does not have any effect on the router if the source is `Router::URI_SOURCE_SERVER_REQUEST_URI`. On the other hand, `Router::URI_SOURCE_GET_URL` depends on it, so I'd say it's beacuse of that.

**Comment by Enzo-life** [comment]
` Call to undefined method Phalcon\Mvc\Router::setUriSource() `
As i see in sources, Phalcon v4.0 doesn't have that method. 

I pass source to handler:
`$response = $application->handle($_SERVER['REQUEST_URI']);`
As i understand, this means `Router::URI_SOURCE_SERVER_REQUEST_URI` :)

**Comment by Enzo-life** [comment]
But i've got your point and changed request uri to `$_GET['_url']` and it seems like works now.

**Comment by scrnjakovic** [comment]
Those methods were removed in #12380, as of 4.0.x you have to pass URI to the `$application->handle()` method. Whether you will pass `$_GET['_uri']` or `$_SERVER['REQUEST_URI']` depends on your server configuration.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14158
