### ISSUE TITLE
[NFR] Add indexHint parameter to find() and findFirst() methods, query builder and PHQL

### ISSUE THREAD

**Issue by wajdijurry** [phalcon/cphalcon#14091]
I suggest to add new parameter/method which is indexHint/indexHint() to the find() and findFirst() methods to tell the query to use/force use an index.

Like this: 
```
$results = Model::find([
    'conditions' => '....',
    'indexHint' => [
        'name' => 'index_name',
        'force' => true
    ]
]);
```

Or the query builder:
```
$query = Model::query()
                 ->where('...')
                 ->indexHint('index_name', true)
                 ->execute();
```

**Comment by scrnjakovic** [comment]
Uhm... that's query optimizer's job?

**Comment by niden** [comment]
This is specific only to MySQL and therefore we will not be adding it. Postgresql does not allow this particularly for the reason of developers not over using this and causing more issues later on.

The ORM has to be as generic as possible and as a result, just offering a feature only for one RDBMS is not helping.

Closing this and thank you for the suggestion.
