### ISSUE TITLE
Improve code quality/consistency in Phalcon\Mvc\View

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#14095]
Any particular reason for using `ob_end_clean();` instead of `$view->finish()` ? :)
https://github.com/phalcon/cphalcon/blob/65183349743e899977adc643f103b887612ffe98/phalcon/mvc/view.zep#L1146-L1159

**Comment by niden** [comment]
None really. They both do the same thing. We should change that though to `view->finish()` to keep the consistency.

Nice catch.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14098
