### ISSUE TITLE
Cache\Adapter\Libmemcached::set() is not working under special circumstances

### ISSUE THREAD

**Issue by zsilbi** [phalcon/cphalcon#14100]
`$cache->set()` is not working when `Libmemcached` is used at the same time for `cache` and `modelsMetadata`.

```php
class Robots extends \Phalcon\Mvc\Model {}

$di->setShared(
    'cache',
    function () {
        return new \Phalcon\Cache\Cache(
            new \Phalcon\Cache\Adapter\Libmemcached(
                new \Phalcon\Storage\SerializerFactory(),
                [
                    'servers' => [
                        [
                            'host' => 'my-host',
                            'port' => 11211
                        ]
                    ],
                    'prefix'  => 'my-cache-prefix'
                ]
            )
        );
    }
);

$di->setShared(
    'modelsMetadata',
    function () {
        return new \Phalcon\Mvc\Model\MetaData\Libmemcached(
            new \Phalcon\Cache\AdapterFactory(
                new \Phalcon\Storage\SerializerFactory()
            ),
            [
                'servers' => [
                    [
                        'host' => 'my-host',
                        'port' => 11211
                    ]
                ],
                'prefix'  => 'my-metadata-prefix'
            ]
        );
    }
);
```

> Provide minimal script to reproduce the issue

```php
$cache = $di->getShared('cache');

var_dump($cache->get('my-test-key')); // NULL

$testData = ['my-test-data'];

Robots::findFirst();

var_dump($cache->set('my-test-key', $testData)); // bool(true)
```
This script should run more than once, of course.

`$cache->set()` always returns `true`, but fails to save the test data.

It works:
- When `MetaData` cache is not used
- If `Robots::findFirst()` is called  before `$cache->get()`
- Without `Robots::findFirst()`
- Without `$cache->get()`

### Details

* Phalcon version: 4.0.0-alpha.5
* PHP Version: 7.3.4
* Operating System: Ubuntu 16.04
* Installation type: Compiling from source
* Zephir version: Version 0.12.0 (from the development branch)
* Server: nginx

**Comment by zsilbi** [comment]
The problem is, that two `Memached` instances are running at the same time using "persistent" connections with same `persistentId` option set. I am sending a PR to correct this.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14106
