### ISSUE TITLE
tinyint, smallint, mediumint cannot be autoincrement

### ISSUE THREAD

**Issue by DestinyMKas** [phalcon/cphalcon#14102]
I have mysql table where autoincrement column is smallint type.

```
CREATE TABLE `attribute` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `image` int(10) unsigned DEFAULT NULL,
  `sort` smallint(5) unsigned NOT NULL,
  `price` decimal(9,2) NOT NULL,
  `limit` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```php
$attribute = Attribute::find();
```

throws an exception `Column type cannot be auto-increment`

https://github.com/phalcon/cphalcon/blob/master/phalcon/Db/Column.zep#L415

### Details

phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.0-alpha.3
Build Date => May 20 2019 19:19:33
Powered by Zephir => Version 0.11.11-b661a58

Linux => Fedora 30
Build from source

10.3.12-MariaDB-log - MariaDB Server 

PHP 7.3.5 (cli) (built: Apr 30 2019 08:37:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/issues/14102
