### ISSUE TITLE
VOLT select_static is not array helper anymore

### ISSUE THREAD

**Issue by DestinyMKas** [phalcon/cphalcon#14101]
In phalcon 3.x select_static didn't required array. In phalcon 4.x it requires to have an array.
I see that this function is not included in arrayHelpers list: https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/View/Engine/Volt/Compiler.zep#L1710

Phalcon 3.x style (expected)
```
{{ select_static('time', values, 'class': 'form-control') }}
```

Phalcon 4.x style (actual)
```
{{ select_static(['time', values, 'class': 'form-control']) }}
```

### Details

phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.0-alpha.3
Build Date => May 20 2019 19:19:33
Powered by Zephir => Version 0.11.11-b661a58

Linux => Fedora 30
Build from source

PHP 7.3.5 (cli) (built: Apr 30 2019 08:37:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

**Comment by DestinyMKas** [comment]
I'm talking not about custom tag. This tag was in all phalcon versions. Just behaviour changed, so it became as breaking change.

**Comment by TimurFlush** [comment]
Unfortunately {{ select_static }} alias for \Phalcon\Tag::SelectStatic has been removed.

**Comment by niden** [comment]
In v4 `Phalcon\Tag` is still registered in the `FactoryDefault` so it can be used. `selectStatic` exists still in that class.

The future replacement `Phalcon\Html\Tag` does not have a `selectStatic`. The same class has been renamed to `select`.

I have to check on the volt helper or you can do what @TimurFlush recommended:

```php
$container->set('tag', new Phalcon\Html\Tag());
```

and then you can use:

```twig
{{ tag.select('time', ['class': 'form-control'], values) }}
```

**Comment by DestinyMKas** [comment]
Sorry, didn't knew that select_static is deprecated. Then there is no issue.

**Comment by niden** [comment]
@DestinyMKas Not a problem. We have been working to fix all the bugs and all the functionality so that we can get to a beta release. Once we hit that we will go through the whole documentation and ensure that the upgrade instructions are as thorough as possible
