### ISSUE TITLE
Update PSR composer to v0.6.1

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/cphalcon#14118]
There is a new version PSR extension v0.6.1
Currently in `composer.json` file is required v0.6.0

### Expected and Actual Behavior

When creating a new nanobox installation, an error is generated because version v0.6.1 (last) is downloaded and the composer file is assigned v0.6.0

### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: 7.2.14
* Operating System: nanobox 7.2 from `tests/_ci`
* Installation type: Compiling from source
* Zephir version (if any): 0.11.8
* Server: Apache
* Other related info (Database, table schema):

**Comment by SidRoberts** [comment]
Fixed in https://github.com/phalcon/cphalcon/issues/14119
