### ISSUE TITLE
[BUG] Foreign key constraint checks do not use transactions

### ISSUE THREAD

**Issue by crnjakovic** [phalcon/cphalcon#14114]
If this is confirmed bug, which I'm pretty sure is, it was reported for the first time way back in 2015 in #9944 and closed without resolution.

Steps to reproduce:

1. Create two models **Model A** and **Model B** and setup relations so that **Model A** cannot be deleted if it is used in **Model B**
2. Start a transaction and set both models to use that same transaction
3. Delete **Model B** first so that **Model A** passes FK constraint check successfully
4. Then try to delete **Model A**

FK constraint check will still fail, even though you deleted **Model B** previously.

It seems that FK constraint check is performed outside of the transaction and therefore still sees **Model B**.

@niden @sergeyklay what you think?

**Comment by zsilbi** [comment]
Created test in https://github.com/phalcon/cphalcon/pull/15174 and it confirmed that it has already been fixed previously.
