### ISSUE TITLE
streaminterface not found in Unknown

### ISSUE THREAD

**Issue by rajankapila** [phalcon/cphalcon#14121]
Getting this after install on OSX with php 7.2

```
php --ri phalcon
PHP Fatal error:  Class 'psr\http\message\treaminterface' not found in Unknown on line 0

Fatal error: Class 'psr\http\message\streaminterface' not found in Unknown on line 0
Segmentation fault: 11
```

**Comment by niden** [comment]
You are using the 4.x version which is still in alpha and have not loaded the PSR extension before Phalcon.

Have a look at this installation guide for v4: https://docs.phalconphp.com/4.0/en/upgrade

If you want to install v3 you can click the releases tag and grab the necessary code using the relevant tag.

**Comment by niden** [comment]
Closing this
