### ISSUE TITLE
Image::pixelate get error with imagecolorat()

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/cphalcon#14139]
The php function `imagecolorat` get a color from (x,y) pixel, but works with `index - 1`

[source](https://github.com/phalcon/cphalcon/blob/master/phalcon/Image/Adapter/Gd.zep#L312) 

```php
while x < this->width {
            let y = 0;

            while y < this->height {
                let x1 = x + amount/2; // here x1 can be equal or great than the image width
                let y1 = y + amount/2; // here y1 can be equal or great than the image height
```

when x1 or y1 are equal or great throw an error

### Details

* Phalcon version: 4.0.0 beta 1
* PHP Version: 7.2.14
* Operating System: nanobox 7.2
* Installation type: Compiling from source
* Zephir version (if any): 0.11.8
* Server: Apache
* Other related info (Database, table schema):

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/14140
