### ISSUE TITLE
ServerRequest  nvalid header value

### ISSUE THREAD

**Issue by cq-z** [phalcon/cphalcon#14150]
Fatal error: Uncaught InvalidArgumentException: Invalid header value in phalcon/Http/Message/ServerRequest.zep:753
Stack trace:
#0 [internal function]: Phalcon\Http\Message\ServerRequest->checkHeaderValue(Array)
#1 [internal function]: Phalcon\Http\Message\ServerRequest->getHeaderValue(Array)
#2 xxxxx: Phalcon\Http\Message\ServerRequest->withAddedHeader('connection', 'keep-alive')
#3 {main}
thrown in phalcon/Http/Message/ServerRequest.zep on line 753

php code
````
$arr = [
    "host"=> "127.0.0.1:9000",
    "connection"=> "keep-alive",
    "pragma"=>"no-cache",
    "cache-control"=>"no-cache",
    "user-agent"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
    "dnt"=> "1",
    "accept"=>"image/webp,image/apng,image/*,*/*;q=0.8",
    "referer"=> "http://127.0.0.1:9000/",
    "accept-encoding"=> "gzip, deflate, br",
    "accept-language"=>"zh-CN,zh;q=0.9,en;q=0.8",
];
$ServerRequest = new \Phalcon\Http\Message\ServerRequest();
foreach($arr as $name=>$value ) {
    $ServerRequest->withAddedHeader($name,$value);
}
````
### Details
php:7.3.4-fpm-alpine3.9
4.0.0-alpha.5

**Comment by cq-z** [comment]
````
$ServerRequest->withAddedHeader($name,[$value]);
    $ServerRequest->withHeader($name,[$value]);

````
it is ok!

**Comment by zsilbi** [comment]
I couldn't reproduce this. 

According to the code, `ServerRequest->checkHeaderValue()` should never get an `array` as parameter when called in `getHeaderValue()`.
My best guess is that you may have compiled Phalcon with an older version of Zephir.

I tried this:
```php
foreach ($arr as $name => $value) {
   $serverRequest = $serverRequest->withHeader($name, $value);
}

print_r($serverRequest->getHeaders());
```
and got everything as expected:
```
Array
(
    [host] => Array
        (
            [0] => 127.0.0.1:9000
        )

    [connection] => Array
        (
            [0] => keep-alive
        )
    ...
```

**Comment by cq-z** [comment]
hi @zsilbi 
you can run 
````
docker run --rm -it 64899484/php bash -c "echo '<?php (new \Phalcon\Http\Message\ServerRequest())->withHeader(\"host\",\"127.0.0.1:9000\");' > test.php &&php test.php"
````
[dockerfile](https://hub.docker.com/r/64899484/php/dockerfile)

**Comment by cq-z** [comment]
### Details

Phalcon version：4.0.0-alpha.5
php:7.3.4
System:alpine3.9

**Comment by Jeckerson** [comment]
Currently this is fixed in `4.0.x` branch and will enter to the next release.

**Comment by cq-z** [comment]
So is this related to the gcc version?

**Comment by cq-z** [comment]
4.0.0-beta.1 is ok ! thanks!
