### ISSUE TITLE
[Bug] Session Redis Adapter when statsKey is enabled it grows forever.

### ISSUE THREAD

**Issue by kornerita** [phalcon/cphalcon#14177]
Phalcon version: 3.4.x

Hi,

As title says, when the statsKey is enabled to track the sessions, the value grows forever on a server with moderate traffic.

If the statsKey is accessed on any session movement, it gets refreshed and never released, hence growing forever, on my production server it gets eight seconds to dump the statsKey via redis-cli.

https://github.com/phalcon/cphalcon/blob/5b77d81e3ddcd69ac85efb803e58be5298b241cc/phalcon/session/adapter/redis.zep#L155

Would be nice to fix this on 3.4.x

My current workaround is use my own adapter overriding the garbage collection method:

```php
namespace Phalcon\Session\Adapter;

class RedisExtended extends Redis {

  public function gc()
  {
    $redisOptions = $this->_redis->getOptions();
    if (isset($redisOptions["statsKey"])) {
        foreach ($this->_redis->queryKeys() as $FullkeyName) {
            if (isset($redisOptions['prefix']) && substr($FullkeyName, 0, strlen($redisOptions['prefix'])) == $redisOptions['prefix']) {
                $keyName = substr($FullkeyName, strlen($redisOptions['prefix']));
            } else {
                break;
            }
            if (!$this->_redis->exists($keyName)) {
                $this->_redis->delete($keyName);
            }
        }
    }
  }

}
```

Since 4.0 is not a released yet and I have several sites using 3.4, it will be long time since I get the change to migrate then all.

Please take a little time to translate this into Zephyr and add it to 3.4.x.

Thanks,
Federico.

**Comment by Jurigag** [comment]
Well on other hand you add here much more CPU cycles because you each time on gc you query keys.

**Comment by kornerita** [comment]
@Jurigag gc method always adds more cycles, it is used on session clear for sure, and others. The current default is 1/1000 requests calls the gc method.

**Comment by sergeyklay** [comment]
The `3.4.x` branch is not longer supported. We don't add new features and enhancements to it. I propose to switch to `4.0.x` branch and see if a problem is still there. So, I'm closing this issue but if described issue is relevant for 4.0.x branch fell free to open a new issue.
