### ISSUE TITLE
suggest adding the alias method to the model

### ISSUE THREAD

**Issue by sowork** [phalcon/cphalcon#14185]
So i have to use model with full namespaces in columns method ? Its kind of bad, i think there should be parameter in query for setting alias of model.

_Originally posted by @Jurigag in https://github.com/phalcon/cphalcon/issues/10479#issuecomment-136358640_

**Comment by scrnjakovic** [comment]
```php
use My\Models\Namespace\Robot;
use My\Models\Namespace\Parts;
...
$builder->columns(
    [
        'robotName' => 'robot.name',
        'partName' => 'part.name'
        ...
    ]
);
$builder->from(
    ['robot' => Robot::class]
);
...
$builder->join(
    Parts::class,
    'part.partId = robotPart.partId',
    'part'
);
```

**Comment by sowork** [comment]
tks, would be more convenient to use the model directly.

**Comment by Jurigag** [comment]
@scrnjakovic yea, using builder it works, my comment meant that using Model::query() there is no way to set alias for current model from which we select.

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
