### ISSUE TITLE
 Why is the Redis prefix parameter fixed?

### ISSUE THREAD

**Issue by zuozhehao** [phalcon/cphalcon#14188]
https://github.com/phalcon/cphalcon/blob/b69fed7ded18590a2c9488484aa24dfdaf9165ef/phalcon/Storage/Adapter/Redis.zep#L39-L46

```php
 this->prefix          = "ph-reds-",
```

Is it possible to change the prefix by parameter to facilitate differentiating between different items?

**Comment by CameronHall** [comment]
Yes. It will reassign `this->prefix` to the argument provided in `options` in the parent constructor.

https://github.com/phalcon/cphalcon/blob/b69fed7ded18590a2c9488484aa24dfdaf9165ef/phalcon/Storage/Adapter/AbstractAdapter.zep#L73

**Comment by zuozhehao** [comment]
ok, thanks.
