### ISSUE TITLE
[NFR] More Array Helpers

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14195]
Will we see more of this array helpers in the future? I only see some implemented so far from (https://github.com/bakaphp/support) I would also like to see this in ``Phalcon\Helper\Arr``.

* all -- Returns true if the provided function returns true for all elements of an array, false otherwise.
* any -- Returns true if the provided function returns true for at least one element of an array, false otherwise.
* drop -- Returns a new array with n elements removed from the left.
* groupBy -- Groups the elements of an array based on the given function.
* hasDuplicates -- Checks a flat list for duplicate values. Returns true if duplicate values exists and false if values are all unique.
* head -- Returns the head of a list.
* last -- Returns the last element in an array.
* pull -- Mutates the original array to filter out the values specified.
* reject -- Filters the collection using the given callback.
* remove -- Removes elements from an array for which the given function returns false.
* tail -- Returns all elements in an array except for the first one.
* take -- Returns an array with n elements removed from the beginning.
* without -- Filters out the elements of an array, that have one of the specified values.

Also try to stick to one worded functions like for example instead of calling it ``hasDuplicates`` you can simply call it ``dupes``. Just use common logic for this.

Recently implemented functions in Arr and Str can also be shorter. Like ``isUnique`` can simply be ``unique`` or even ``uniq``.

Things like ``sliceLeft`` and ``sliceRight`` why not combine this all into one simple function similar to php ``substr()`` and call it simply ``slice`` and can be used just like ``substr`` as in ``slice($str, $start, $length)`` which would also allow negative start like ``slice($str, -3, 1)``.

``validateAll`` can simply be called ``valid``.

``countVowels`` very rarely used function but it can be simply called ``vowels``.

``isAnagram``very rarely used function but it can be simply called ``anagram``.

I think you get the idea. Less camelCased or unders_score functions and more of one worded functions whenever possible. This not only makes coding faster, it also make code look much cleaner ^_^ Plus easier on your fingers when you type tousands of lines of code.

Just be creative with one worded functions, there is litterly tousands of words to choose from. If you need any help use sites like (https://www.wordnik.com/) or even (https://www.urbandictionary.com/)

**Comment by emiliodeg** [comment]
Looks like nice for me

**Comment by v00v** [comment]
@emiliodeg, indeed :-) I work with arrays a lot, and could use most of the requested additons on daily basis. Also having simpler one-worded functions is a must have in Phalcon. But Phalcon team is on a good track so far. By simplifying all the namespaces and adding other NFRs quicly. I love Phalcon and can't leave without it ^_^

**Comment by v00v** [comment]
There is another good example of functions @ (https://laravel.com/docs/5.8/collections) See Available Methods section :-)

**Comment by sergeyklay** [comment]
I would not want to add all these functions simply because they exist somewhere. We should go another way: For each function described abowe, should be created an NFR with a description of the necessary functionality, code examples and a descriptive reason why it should be added to the core and why a task cannot be done by other means.
