### ISSUE TITLE
Wrong options comparisons in Validator/File

### ISSUE THREAD

**Issue by ekmst** [phalcon/cphalcon#14196]
Found invalid comparison options:

[Validator/File.zep#L105](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Validation/Validator/File.zep#L105) - must be "minsize"
[Validator/File.zep#L129](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Validation/Validator/File.zep#L129) - must be "mazsize"
[Validator/File.zep#L154](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Validation/Validator/File.zep#L154) - must be equalsize
[Validator/File.zep#L172](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Validation/Validator/File.zep#L172) - must be allowedtypes
[Validator/File.zep#L189](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Validation/Validator/File.zep#L189)
[Validator/File.zep#L213](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Validation/Validator/File.zep#L213)
[Validator/File.zep#L237](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Validation/Validator/File.zep#L237)

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14197

**Comment by niden** [comment]
Thank you @ekmst
