### ISSUE TITLE
Build from source problem

### ISSUE THREAD

**Issue by ustmaestro** [phalcon/cphalcon#14199]
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
appending configuration tag "CXX" to libtool
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make: *** [Makefile:194: phalcon.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make: *** [Makefile:194: phalcon.lo] Error 63

Thanks for compiling Phalcon!
Build succeed: Please restart your web server to complete the installation

**Comment by ustmaestro** [comment]
OS: Solus OS
$ php -v
PHP 7.3.3 (cli) (built: Apr 25 2019 04:00:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.3, Copyright (c) 1999-2018, by Zend Technologies
$ gcc --version
gcc (Solus) 8.3.1 20190320
$ libtool --version 
libtool (GNU libtool) 2.4.6
$ autoconf --version
autoconf (GNU Autoconf) 2.69

**Comment by sergeyklay** [comment]
Try another way:

1. `cd ext`
2. `phpize`
3. `./configure`
4. `make`
5. `sudo make install`

**Comment by ustmaestro** [comment]
$ phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731



$ ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules/
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 1.0.3 (ok)
checking for gawk... gawk
checking whether to enable phalcon... yes, shared
checking whether HAVE_BUNDLED_PCRE is declared... no
checking whether HAVE_JSON is declared... yes
checking for ext/json/php_json.h... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h


$ make
/bin/sh /home/ustmaestro/myphalcon/cphalcon/ext/libtool --mode=compile cc  -I. -I/home/ustmaestro/myphalcon/cphalcon/ext -DPHP_ATOM_INC -I/home/ustmaestro/myphalcon/cphalcon/ext/include -I/home/ustmaestro/myphalcon/cphalcon/ext/main -I/home/ustmaestro/myphalcon/cphalcon/ext -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/ustmaestro/myphalcon/cphalcon/ext/phalcon.c -o phalcon.lo 
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make: *** [Makefile:194: phalcon.lo] Error 63

**Comment by sergeyklay** [comment]
Here is what you can do to recreate the configuration files for the build process:
```sh
phpize
aclocal
libtoolize --force
autoheader
autoconf
./configure
make
```

**Comment by ustmaestro** [comment]
Thanks @sergeyklay !
Also the pcre2, pcre2-devel library must be installed to make a build from source.
Now with last commands everything works and build successful.

**Comment by ustmaestro** [comment]
There is a module dependency psr php module
https://forum.phalconphp.com/discussion/19143/update-package-php72phalcon-crash-php72fpm
https://github.com/jbboehr/php-psr

**Comment by ustmaestro** [comment]
psr module extension must be loaded before phalcon module extension

**Comment by sergeyklay** [comment]
@ustmaestro Yes, Phalcon v4.x depends on PSR module. So right now is only way to get it working is to load phalcon.so after psr.so.  I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks
