### ISSUE TITLE
PaginatorQueryBuilder looses distinct and sub select 

### ISSUE THREAD

**Issue by jbruceh88** [phalcon/cphalcon#14205]
I have fairly complex query using distinct, subselects and a few joins, that I built using the modelsManager, this query returns 166 records. However when I pass this into PaginatorQueryBuilder, the total number of items in the pagination is 1438 with a total page count of 96. 

Looking in our sql logs we can see that the initial query runs correctly, however the query to return the pagination, does not include the distinct or the sub select we have in the actual query. 

Is it not possible to use  PaginatorQueryBuilder with a distinct and a subselect?

**Comment by CameronHall** [comment]
@jbruceh88 that sounds like a bug. Can you please specify what version of Phalcon you're using by providing the output of `php --ri phalcon`.

If you could please provide the two different queries as well that'd be good.

Thanks :)

**Comment by jbruceh88** [comment]
@CameronHall I am using  version  3.4.3 . would you prefer the two sql raw queries, or as it is build using modelsManager? 

:)

**Comment by CameronHall** [comment]
Both would be good thank you 😊

**Comment by Jeckerson** [comment]
No test script was provided, closing. Feel free to reopen.
