### ISSUE TITLE
Query Builder duplicating JOIN clause

### ISSUE THREAD

**Issue by ronald677br** [phalcon/cphalcon#14214]
I was building a query using the Phalcon QueryBuilder class.
My query consists of two tables being added with the `$builder->addFrom($model)` method and one table being added using the  `$builder->rightJoin($model, $params)`

**- Expected behavior:**

Query works, executing the following converted SQL on the database:
```
SELECT * FROM "Robots", "Parts" RIGHT JOIN "RobotsParts" ON "Parts"."Id" = "RobotsParts"."PartId"
WHERE "Robots"."Name" = 'Robot Name'

```
**- Actual behavior:**
The execute fails, giving the following error:
`SQLSTATE[42712]: Duplicate alias: 7 ERROR: table name "RobotsParts" specified more than once`

While debugging, I found out that  the executed query was:
```
SELECT * FROM "Robots", "Parts" RIGHT JOIN "RobotsParts" ON "Parts"."Id" = "RobotsParts"."PartId"
RIGHT JOIN "RobotsParts" ON "Parts"."Id" = "RobotsParts"."PartId"
WHERE "Robots"."Name" = 'Robot Name'
```

It simply duplicated the RIGHT JOIN clause. I found out that if I removed the second `$builder->addFrom($model)`, the query works just fine without any problems, giving the expected output.

### Details

* Phalcon version: 3.4.3
* PHP Version: PHP 7.3.6
* Operating System: Ubuntu 18.04
* Installation type: Compiling from source
* Server: Apache
* Other related info: using PostgreSQL database

**Comment by scrnjakovic** [comment]
May I ask why do you use two FROM clauses? This is one very odd query for such a simple task, if you ask me. May I suggest you rewrite the query and give it a shot? Maybe something like
```php
$builder
    ->from(
        ['robot' => Robots::class],
    )
    ->leftJoin(
        RobotParts::class,
        'robotPart.robotId = robot.robotId',
        'robotPart'
    )
    ->leftJoin(
        Parts::class,
        'part.partId = robotPart.partId',
        'part'
    )
    ->where(
        'robot.name = :robotName:',
        [
            'robotName' => 'Robot name'
        ]
    );
```

Depending on your use of namespaces and autoloading setup, you may need to add use statements to the top like
```php
use My\Models\Robots;
use My\Models\RobotParts;
use My\Models\Parts;
```

**Comment by ronald677br** [comment]
I understand that there is no real need of two FROM clauses, but I think that it shouldn't be a problem at all.
On raw SQL you can achieve this without any problem, just taking care to keep the left table (where the joins will be performed) to be inserted before the first JOIN clause.

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
