### ISSUE TITLE
Remove __set_state

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#14212]
Check where `__set_state()` is used and remove it accordingly.

**Comment by scrnjakovic** [comment]
There is some in `Phalcon\Config` afair.

**Comment by CameronHall** [comment]
@scrnjakovic it was removed in https://github.com/phalcon/cphalcon/pull/14186 :)

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/14223
