### ISSUE TITLE
[BUG] Phalcon\Forms\Form::clear() variable never initialized

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#14217]
Condition on line 694 will never evaluate to true as variable `field` is `null` (v3.4.x)
https://github.com/phalcon/cphalcon/blob/65183349743e899977adc643f103b887612ffe98/phalcon/forms/form.zep#L679-L698

**Comment by SidRoberts** [comment]
Fixed in #14218 and #14219.
