### ISSUE TITLE
phalcon/mvc/model::hasChanged documentation typo?

### ISSUE THREAD

**Issue by cottton** [phalcon/cphalcon#14237]
See https://github.com/phalcon/cphalcon/blob/3.4.x/phalcon/mvc/model.zep#L4001

    $robot = new Robots();
    // ...
    // $hasChanged = $robot->hasChanged(["type", "name", true]); <--- , true is written in the array
    $hasChanged = $robot->hasChanged(["type", "name"], true); // returns false

`["type", "name", true]`
to
`["type", "name"], true`

**Comment by niden** [comment]
The second one seems to be the correct one. @cottton do you mind opening a pull request to the `4.0.x` branch? Thanks

**Comment by cottton** [comment]
`4.0.x` branch already has the correct docu: 

    $hasChanged = $robot->hasChanged(["type", "name"], true); // returns false

The typo is in the `3.4.x` branch.

**Comment by sergeyklay** [comment]
@cottton Could you send a patch to the 3.4.x branch then?

**Comment by cottton** [comment]
`3.4.x` docu fix PR: https://github.com/phalcon/cphalcon/pull/14239/files

Just saw that the `4.0.x` missing the `allFields` param doc.
PR: https://github.com/phalcon/cphalcon/pull/14240

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14240
