### ISSUE TITLE
session stored memcached empty, phalcon version is 2.0.1

### ISSUE THREAD

**Issue by huang-winter-snow** [phalcon/cphalcon#14244]
The session is stored in memcache. During the packet capture process using Wireshark, 
the value is found to be empty. However, after Wireshark has fetched multiple times, the session cannot be replayed. 
What are the reasons for this? The following is the code

	Class VerifyController extends \ Phalcon \ Mvc \ Controller
	{
		public function imageAction()
		{
			$this -> view -> disable();

			$params = $ this-> dispatcher-> getParams();
			if (!isset($ params [0]) || empty($ params [0])) return;

			$sign = substr($ params [0],0,20); // longest length

			$verifyCode = (new Captcha()) -> entry();
			User::getInstance()->set(Verify::PREFIX_KEY_NAME.$ sign,strtolower($verifyCode));
		}
	}

**Comment by stamster** [comment]
2.0.1 is really old && deprecated release, to start with.

Next, show your session adapter - e.g. are you using `libmemcached`?

**Comment by huang-winter-snow** [comment]
Since our PHP version is 5.6 and has not been upgraded, the cache library is libmemcached

**Comment by niden** [comment]
@huang-winter-snow Sadly we cannot help with this. The last release for v2 was in 2016 so it is not supported. Additionally v2 was written in C and not Zephir so we cannot even get the code to change or even diagnose what might be going on.

Has this been working before and is not working now?

**Comment by huang-winter-snow** [comment]
The previously written memcached is empty. After multiple captures by Wireshark, the data can be written to the memcached cache normally.

**Comment by stamster** [comment]
@niden I strongly believe PhalconPHP v2.x was/is written in Zephir. And only v1 was pure C.

Here's code:
https://github.com/phalcon/cphalcon/tree/phalcon-v2.0.13/phalcon/http

In any case - latest v2 release was v2.0.13. So I'd try with that if I was OP.

Codebase: https://github.com/phalcon/cphalcon/tree/phalcon-v2.0.13
Release: https://github.com/phalcon/cphalcon/releases/tag/phalcon-v2.0.13

Lastly - PHP 5.6 is deprecated for a while, and shall not be used on production env (yeah, some hosts are still running 5.1 or 5.2, but... )

**Comment by niden** [comment]
@stamster Yes you are correct. Minor brain fart there. v2 was the first version we introduced Zephir.

**Comment by huang-winter-snow** [comment]
@stamster  this is session library code
$di->setShared('session', function() use ($config) {

    $memcache = $config->toArray()['memcache'];
    session_set_cookie_params($memcache['expiration'], '/', '.' . $config['site']['subdomain']);
    
    $session = new \Phalcon\Session\Adapter\Libmemcached(array(
        'uniqueId' => 'hg_session',
        'servers' => array(
            array('host' => $memcache['host'], 'port' => $memcache['port'], 'weight' => 1),
        ),
        'client' => array(
            \Memcached::OPT_HASH => \Memcached::HASH_MD5,
//             \Memcached::OPT_PREFIX_KEY => 'prefix.',
        ),
        'lifetime' => $memcache['expiration'],
        'prefix' => $memcache['prefix'],
    ));
    if (session_status() == PHP_SESSION_NONE) {
        $session->start();
    }
    return $session;
});
