### ISSUE TITLE
Phalcon\Mvc\Micro not allowed http method not exists

### ISSUE THREAD

**Issue by saulosousasoares** [phalcon/cphalcon#14246]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

1) In a Restful API we need to differentiate what is "not found (404)" from "not allowed (405)". In Phalcon \ Mvc \ Micro apparently this is not possible.

2) When I test in a controller any $ bool = $ this-> request-> isGet () for an HTTP call "COPY" or "LOCK" or "LINK" ... I get $ bool === true
> Provide output if related. Provide coredump if any. 

Use https://docs.phalconphp.com/en/latest/generating-backtrace as reference

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by ruudboon** [comment]
Please create separate issues for each bug you find.
For the not found you can sent a 403 in the controller using header.

**Comment by sergeyklay** [comment]
> In a Restful API we need to differentiate what is "not found (404)" from "not allowed (405)". In Phalcon \ Mvc \ Micro apparently this is not possible.

What do you mean by saying "is not possible"? Phalcon's Response component supports all standard status codes, incl 403, 404, 405, etc Can you elaboprate on that?

> When I test in a controller any $ bool = $ this-> request-> isGet () for an HTTP call "COPY" or "LOCK" or "LINK" ... I get $ bool === true

Phalcon's Request supports only following HTTP methods https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by andrew-demb** [comment]
@saulosousasoares you can try to override request method `Phalcon\Http\Request::isValidHttpMethod()` to add support for missed methods.

https://github.com/phalcon/cphalcon/blob/master/phalcon/Http/Request.zep#L1146-L1163

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
