### ISSUE TITLE
PHQL "NOT BETWEEN" clause issue

### ISSUE THREAD

**Issue by ronald677br** [phalcon/cphalcon#14253]
While using the Query Builder $builder->notBetweenWhere() function, I ran into the same issue referenced by peterphalcon on this post:

https://forum.phalconphp.com/discussion/8759/can-not-use-not-between-in-find-and-query-function

I searched on the issues, here on github, but didn't found anything relating to it, so I created this post to keep the issue tracked... this seems to be a bug at Phalcon's PHQL.

**Details**

- Phalcon version: 3.4.3
- PHP Version: PHP 7.3.6
- Operating System: Ubuntu 18.04
- Installation type: Compiling from source
- Server: Apache
- Other related info: using PostgreSQL database

**Comment by sergeyklay** [comment]
@ronald677br Could you please provide script to reproduce and table schema (if possibe)?

**Comment by sergeyklay** [comment]
Fixed in the `4.0.x` branch. Feel free to open a new issue if the problem appears again. Thank you for the bug report.
