### ISSUE TITLE
[NFR] Alpine package

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14257]
Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc and busybox with the focus on small, simple & secure and often used as docker base image.

I think this strokes with the Phalcon mindset and it would be great if we can publish an Alpine package also.

See also:
https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

**Comment by sergeyklay** [comment]
Close in favor of https://github.com/phalcongelist/packagecloud/issues/41
