### ISSUE TITLE
Antivirus, false positive?

### ISSUE THREAD

**Issue by M4theuz** [phalcon/cphalcon#14252]
Hello, I tried to move the version 4 file and the antivirus lock, would it be a false positive?
https://i.imgur.com/T4vXmEO.png

The chrome appears the same way.

**Comment by niden** [comment]
Hello @M4theuz. Thank you for reporting this. We build our DLLs using AppVeyor so anything that is downloaded from the Github Release pages comes from there. 

I think this is the commit that built all the DLLs

https://ci.appveyor.com/project/sergeyklay/cphalcon/builds/25970835

If you click on either of the jobs and download artifacts you will get each DLL. I am wondering if they will also report false positives.

**Comment by M4theuz** [comment]
Hello @niden, I did the test at all, it looks like everything is fine now.

**Comment by niden** [comment]
Thank you!.

Closing this.
