### ISSUE TITLE
"$this->eventsManager" return null

### ISSUE THREAD

**Issue by zuozhehao** [phalcon/cphalcon#14269]
phalcon 4

I found that "protected event manager" would affect the magic method _get to get "eventsManager" when I did not use "setEventsManager"

https://github.com/phalcon/cphalcon/blob/4173bca9b85b4b7e3493146036ed91b977dff390/phalcon/Di/Injectable.zep#L60-L82

**Comment by CameronHall** [comment]
In which case we will need to add the `__isset` magic method to catch that. @niden

**Comment by niden** [comment]
Sorry I do not understand the issue. The code is identical to v3 meaning `eventsManager` is protected 

What are you trying to do?

**Comment by niden** [comment]
Never mind @CameronHall explained it

**Comment by CameronHall** [comment]
It's worth considering removing the `eventsManager` property from the `DI` altogether alongside the `setEventsManager` method altogether. Considering no one has noticed (until now) that it hasn't been an issue, there should be minimal impact (if any).

**Comment by CameronHall** [comment]
@zuozhehao can you please provide a code sample?

**Comment by zuozhehao** [comment]
```php
class BaseController extends \Phalcon\Mvc\Controller
{

    public function afterExecuteRoute($dispatcher)
    {

        $this->eventsManager->fire('someEvent' ,$this);

    }

}
```

@CameronHall

**Comment by CameronHall** [comment]
@zuozhehao how do you populate your Di? With `FactoryDefault`?

**Comment by zuozhehao** [comment]
@CameronHall yes, `Phalcon\Di\FactoryDefault`

**Comment by CameronHall** [comment]
Thanks @zuozhehao I'll take a look.

**Comment by CameronHall** [comment]
@zuozhehao I've tried reproducing this but haven't be able too. After rereading through all the code, there's no reason why this shouldn't work, the only reason it wouldn't is if the the eventsManager isn't in your DI.

**Comment by zuozhehao** [comment]
@CameronHall  
When initializing the controller, the `setEventsManager` was not executed,
When I used `this->eventsManager`, it did not go into the magic method`__get`
```php
<?php

class BaseController {


    /**
     * Events Manager
     *
     * @var \Phalcon\Events\ManagerInterface
     */
    protected $eventsManager;


    /**
     * Magic method __get
     */
    public function __get($propertyName) {

        var_dump($propertyName);

    }

    /**
     * Sets the event manager
     */
    public function setEventsManager($eventsManager)
    {

        $this->eventsManager = $eventsManager;

    }

}

class IndexController extends BaseController {


    public function indexAction() {

        var_dump($this->eventsManager);

    }

}


(new IndexController)->indexAction();
```

**Comment by ruudboon** [comment]
@sergeyklay If you could check why this [pull](https://github.com/phalcon/cphalcon/compare/4.0.x...ruudboon:fix-issue-with-di-14269?expand=1) is [failing](https://travis-ci.org/ruudboon/cphalcon/jobs/586855401) and working in nanobox it would be great.

**Comment by niden** [comment]
This has been addressed in https://github.com/phalcon/cphalcon/pull/14445
