### ISSUE TITLE
[NFR] Add constants to Phalcon\Http\Response

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14264]
In the incubator we have a list of http statuscodes declared as class constants.
https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Http/Response/StatusCode.php
Can we integrate these constants in v4? We already have some kind of constant list here.
https://github.com/phalcon/cphalcon/blob/a0b25edcfc143b780ec69d5b92cae9c0c37c1987/phalcon/Http/Response.zep#L701

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/pull/14033#issuecomment-488651127

**Comment by ruudboon** [comment]
Thnx @sergeyklay for clarifying this. I will keep it in the incubator.
