### ISSUE TITLE
Error when compiling from source  Phalcon on  Linux raspberrypi PHP 7.3.4-2

### ISSUE THREAD

**Issue by rigin** [phalcon/cphalcon#14282]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

When compiling Phalcon v3.4.4 and v4.0.0.beta.1, the zephir v0.12.0 on  Linux raspberrypi 4.19.58-v7+   armv7l PHP Version 7.3.4-2 
 
Console in sudo mode

*****************************************
\# git clone https://github.com/phalcon/cphalcon
\# cd cphalcon/
\# git checkout tags/v4.0.0-beta.1, ./
or
\# git checkout tags/v3.4.4 ./
\# zephir fullclean
\# zephir build

compiler produces the following error.

[ERROR] Global 'orm.exception_on_failed_metadata_save' cannot be read because it isn't defined in
/home/pi/git/cphalcon/phalcon/Mvc/Model/MetaData.zep on line 715 

********************************************

phpinfo [https://yadi.sk/d/wo91rryL2ivXIQ](url)
*********************************************
> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://docs.phalconphp.com/en/latest/generating-backtrace as reference

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by ruudboon** [comment]
@rigin Can you add your solution here? Maybe it can help somebody

**Comment by rigin** [comment]
I figured out the reasons for the error. I ran the installer for version 4.0.0, even though I copied version 3.4.4 from the repository.

\$ sudo -s

\# git clone https://github.com/phalcon/cphalcon

\# cd cphalcon/

\# git checkout tags/v3.4.4 ./

\# zephir fullclean

\# zephir build

But it had to be done:

\$ sudo -s

\# git clone https://github.com/phalcon/cphalcon

\# cd cphalcon/

\# git checkout tags/v3.4.4 ./

\# cd build

\# ./install

If you need version 4.0.0, then we must do as is written in the manual for 4.0.0, a little tweak version

\$ sudo -s

\# git clone https://github.com/phalcon/cphalcon

\# cd cphalcon/

\# git checkout tags/v4.0.0-beta.1 ./

\# zephir fullclean

\# zephir build

And also, it was necessary to increase the swap file from default 100 MB to at least 2000 MB. Because, the compiler lacks RAM. 1 GB.

\$ sudo -s

\# nano /etc/dphys-swapfile

Replacing CONF_SWAPSIZE=100 with CONF_SWAPSIZE=2000
