### ISSUE TITLE
RedisEngine setTimeout has deprecated

### ISSUE THREAD

**Issue by alex-aff** [phalcon/cphalcon#14281]
`setTimeout` function of Redis has deprecated so it should be replaced by `expire` function.
right now it is throwing following exception.

```
Redis::setTimeout() is deprecated
```

https://github.com/phpredis/phpredis/pull/1572

* PHP Version: >7.0
* Redis Version: >5.0.0

**Comment by CameronHall** [comment]
We don't use `setTimeout` anywhere so this should be okay to close.

**Comment by sergeyklay** [comment]
Fixed in the `4.0.x` branch: https://github.com/phalcon/cphalcon/pull/14284. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Comment by alex-aff** [comment]
@sergeyklay understood . However version `v3.4.4` still uses `setTimeout()`. Shouldn't we fix it for that version?
https://github.com/phalcon/cphalcon/blob/3.4.x/phalcon/cache/backend/redis.zep#L261

**Comment by jesugmz** [comment]
Same issue here for v3.4.4 and PhpRedis 5.0.2.
As v3.4.4 is the recomended version in https://phalconphp.com/en/ you should reconsider to reopen this issue @sergeyklay.

**Comment by SergioFloresG** [comment]
Same issue in.

- PHP 7.1
- Phalcon 3.4.4
- Redis 5

When run i get this message.

> ( ! ) Deprecated: Function Redis::setTimeout() is deprecated in Unknown on line 0

And my config is this.
``` php
$session = new SessionRedis([
    'host' => env('REDIS_HOST'),
    'port' => env('REDIS_PORT', 6379),
    'persistent' => false,
    'uniqueId' => env('SESSION_ID', 'my-app'),
    'lifetime' => env('SESSION_LIFETIME', 3600),
    'prefix' => env('SESSION_PREFIX', 'my_')
]);
```

**Comment by sergeyklay** [comment]
We're not plan to release 3.x in near future. I'm sorry. In other hand, there are simple steps to build Phalcon from source code. This is so easily done that everyone can do it himself. Feel free to ping me in case of any building problem.

**Comment by sergeyklay** [comment]
We're release Phalcon v3.4.5 right now

**Comment by Jeckerson** [comment]
@mahen3d As far, as I remember, you need to make own build from `3.4.x` branch - https://github.com/phalcon/cphalcon/tree/3.4.x

Latest `3.4.5` version do not contain that fix.

See, for more details - https://docs.phalcon.io/3.4/en/installation#compile-from-sources
