### ISSUE TITLE
Segfault when passing non builder object in to Phalcon\Paginator\Adapter\QueryBuilder

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14299]
### Expected and Actual Behavior
Exception when passing in wrong object. Currently results in Segfault

> Provide minimal script to reproduce the issue
```php
        $paginator = new Phalcon\Paginator\Adapter\QueryBuilder(
            [
                'builder'  => new \stdClass(),
                'limit' => 10,
                'page'  => 1,
            ]
        );
```

### Details

* Phalcon version: 4.0.0-beta.1
* PHP Version: 7.3.7 
* Operating System: Alpine
* Installation type: Compiling from source)

**Comment by sergeyklay** [comment]
Fixed in the `4.0.x` branch. Thank you for contributing!
