### ISSUE TITLE
Str::includes return unexpected result

### ISSUE THREAD

**Issue by ZhangRuiMingZRM** [phalcon/cphalcon#14301]
* Phalcon version: `4.0.0-beta.1`
* PHP Version: `7.3.6`
* Operating System: ubuntu
* Installation type: Compiling from source
* Server: php web server

In the code example
https://docs.phalconphp.com/4.0/en/helper#includes
```php
echo Str::includes('start', 'start-a-horse');
```
Result expect `true` but ` false`  given

Because `strpos()` or `mb_strpos` may return Boolean FALSE, but may also return a non-Boolean value which evaluates to FALSE

https://github.com/phalcon/cphalcon/blob/a0b25edcfc143b780ec69d5b92cae9c0c37c1987/phalcon/Helper/Str.zep#L364
https://github.com/phalcon/cphalcon/blob/a0b25edcfc143b780ec69d5b92cae9c0c37c1987/phalcon/Helper/Str.zep#L366

Use `===` for testing the return value
```
  final public static function includes(string! needle, string! haystack) -> bool
    {
        if function_exists("mb_strpos") {
            return (bool) false !== mb_strpos(haystack, needle);
        } else {
            return (bool) false !== strpos(haystack, needle);
        }
    }
```

**Comment by sergeyklay** [comment]
Fixed in the `4.0.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
