### ISSUE TITLE
[4.0.0-beta.2] Error: Class 'Phalcon\Db' not found

### ISSUE THREAD

**Issue by diplopito** [phalcon/cphalcon#14311]
### Expected and Actual Behavior
When trying to use `Phalcon\Db` a fatal error occurs: `Fatal error: Uncaught Error: Class 'Phalcon\Db' not found`.

Sample code:
```php
<?php

use Phalcon\Db;

echo Db::FETCH_ASSOC;
```
Expected result: `2`

A workaround is to use `Phalcon\Db\Enum`, but since the Db statics are so widely used, it might be better to stick to Db::FETCH_ASSOC and not to `Db\Enum::FETCH_ASSOC` --same can be said for `Phalcon\Db`

### Details

* Phalcon version: 4.0.0-beta.2
* PHP Version: 7.2
* Operating System: Windows | Ubuntu
* Installation type: Dll || installing via package manager
* Zephir version (if any):
* Server: Apache

**Comment by niden** [comment]
`Phalcon\Db` has been removed. Its functionality has been split into:

`Phalcon\Db\AbstractDb` for necessary methods
`Phalcon\Db\Enum` for the constants. 

So all you need is 

```php

use Phalcon\Db\Enum;

echo Enum::FETCH_ASSOC;
```

**Comment by diplopito** [comment]
Ok Nikos, thank you, I'll update the upgrade file.
