### ISSUE TITLE
Phalcon\Mvc\Model Invalid callback , no array or string given

### ISSUE THREAD

**Issue by vvangelov** [phalcon/cphalcon#14326]
I tried to fetch the content of the user table but I get the same error every time. Both models and phql doesn`t work. I couldn't found similar issue. I am not sure if phalcon(3.4.4) support mysql 8 or the problem is somewhere else.

```php
"Invalid callback , no array or string given"
```

```php
$query = $this->modelsManager->createQuery('SELECT * FROM Core\Entity\User');
$users  = $query->execute();

  $user = new User();
   $user->create(
      [
           "password" => "password",
           "name" => "Astro Boy",
      ]
);

use Phalcon\Mvc\Model;

class User extends Model
{
    /**
     * @var
     */
    public $id;
    /**
     * @var
     */
    public $username;
    /**
     * @var
     */
    public $password;

    /**
     *
     */
    public function initialize()
    {
        $this->setSource('users');
    }
}
```

### Details

* Phalcon version: (`3.4.4`)
* PHP Version: (` 7.3.8`)
* Operating System:docker with debian image
* Installation type: Compiling from source 
* Server: Nginx
* database mysql:8.0.14 docker image

**Comment by ruudboon** [comment]
Do you have some more info on your config and di setup?

**Comment by vvangelov** [comment]
I have class
`class DbService
{
    use DiTrait;

    public const SERVICE_ID = 'db';

    public function __construct(array $config = [])
    {
        return \Phalcon\Db\Adapter\Pdo\Factory::load([
            'host'     => 'mysql',
            'dbname'   => 'dbname',
            'port'     => 3306,
            'username' => 'user',
            'password' => 'pass',
            'adapter'  => 'mysql',
        ]);
    }
}`
And I am  passing it to $DI like this
`      $di->set(
            DbService::SERVICE_ID,
            [
                'className' => DbService::class
            ]
        );`
The same thing works for view service. Now I found that if I do this it is working.
```
        $di->set(
            "db",
            function () {
                return \Phalcon\Db\Adapter\Pdo\Factory::load([
                    'host'     => 'mysql',
                    'dbname'   => 'nextPoint',
                    'port'     => 3306,
                    'username' => 'root',
                    'password' => 'root',
                    'adapter'  => 'mysql',
                ]);
            }
        );
```

**Comment by Jeckerson** [comment]
Well, you didn't instantiated class inside `db` service.

**Comment by vvangelov** [comment]
I am returning \Phalcon\Db\Adapter\Pdo\Factory::load inside DbService class. The same thing I do inside anonymous functions and it is working.

**Comment by ruudboon** [comment]
I don't think this issue is happening in the latest version. Please reopen if needed. Thnx

**Comment by lianulloa** [comment]
Happening in Phalcon 4

**Comment by niden** [comment]
> Happening in Phalcon 4

@lianulloa Probably not what you want to read as a reply, but Phalcon 4 is no longer supported. If possible, please upgrade to v5 and let us know if this issue persists.
