### ISSUE TITLE
Upgrade Devtools to v4

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14321]
Progress will be tracked [here](https://github.com/phalcon/phalcon-devtools/issues/1315)

To get a good overview what is left for the release of v4 we keep this issue open until the parent issue is fixed.

**Comment by Jeckerson** [comment]
:nine: :five:% done.

**Comment by Jeckerson** [comment]
Upgraded.

**Comment by ruudboon** [comment]
RC.1 is out. Closing this. Any issues will be handled inside the project.
