### ISSUE TITLE
Incorrect parsing of volt function select()

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#14328]
Code example is from Vokuro
https://github.com/phalcon/vokuro/blob/master/app/views/permissions/index.volt#L13

Code example:
```php
{{ select('profileId', profiles, 'using': ['id', 'name'], 'useEmpty': true, 'emptyText': '...', 'emptyValue': '') }}
```

Generates current PHP code:
```php
<?= $this->tag->select('profileId', $profiles, 'using' => ['id', 'name'], 'useEmpty' => true, 'emptyText' => '...', 'emptyValue' => '') ?>
```

Error is:
```
PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'
```

### Details

* Phalcon version: (`4.0.0-beta.2`)
* PHP Version: (`7.2.19-0ubuntu0.18.04.2`)
* Operating System: Ubuntu 18.04
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema):

**Comment by ruudboon** [comment]
Not completely sure if this is a bug or the documentation that is not up2date. Will investigate this.

**Comment by Jurigag** [comment]
Not sure but don't we need there just `[]` or `{}` ?

**Comment by CameronHall** [comment]
I'm hesitant to call this a bug, as far as the error goes, it's not wrong... 

Let's just settle with updating the code in Vokuru to what I've put below and move on.
```volt
{{ select('profileId', profiles, { 'using': ['id', 'name'] }, 'useEmpty': true, 'emptyText': '...', 'emptyValue': '') }}
```

**Comment by Jeckerson** [comment]
@CameronHall Nope, doesn't work as you suggested. Same error.

```
<?= $this->tag->select('profileId', $profiles, ['using' => ['id', 'name']], 'useEmpty' => true, 'emptyText' => '...', 'emptyValue' => '') ?>
```

**Comment by CameronHall** [comment]
@Jeckerson it looks like I made a mistake, the right curly brace should end right before we close the `select()` and not after the `using` element. 

I'd test this myself, but I don't have Vokuru installed.

```volt
{{ select('profileId', profiles, { 'using': ['id', 'name'], 'useEmpty': true, 'emptyText': '...', 'emptyValue': '' } ) }}
```

**Comment by ruudboon** [comment]
Looks like a documentation issue. Closing this for now. Volt docs will be updated soon (https://docs.phalcon.io/4.0/en/volt)
