### ISSUE TITLE
All model attributes have string type

### ISSUE THREAD

**Issue by maxttor** [phalcon/cphalcon#14323]
```php
$days = HabitMark::find(['goal_id = ?0', 'bind' => [$this->id]])->toArray();
echo '<pre>';
var_dump($days);
exit();
```

> array (size=1)
>   0 => 
>     array (size=5)
>       'goal_id' => string '116' (length=3)
>       'date' => string '2019-08-21' (length=10)
>       'status' => string '0' (length=1)
>       'days_count' => null
>       'date_fail' => null

But in DB fileds goal_id and status have integer type. How can I get attributes with correct types?

### Details

* Phalcon version: 4.0.0-beta.2
* PHP Version: 7.2.18-1
* Operating System: ubuntu16.04.1
* Installation type: installing via package manager
* Server: Nginx

**Comment by ruudboon** [comment]
Thank you for your intrest in Phalcon. This intended behavior. Please use github for bugs only.
For questions you can use [Discord](https://phalcon.link/discord) and the [Forum](https://phalcon.link/forum)
In the forum you will find some posts how to achieve this.

**Comment by Jurigag** [comment]
You can disable this behavior by setting:

```
'options'  => [
                PDO::ATTR_EMULATE_PREPARES   => false,
                PDO::ATTR_STRINGIFY_FETCHES  => false,
                PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
            ],
```

At least it works for me in 3.x

**Comment by Jeckerson** [comment]
Install correct mysql driver, which is auto casting values into correct type and passing it to PHP.
