### ISSUE TITLE
provide a persistent id for redis persistent connection

### ISSUE THREAD

**Issue by lanlin** [phalcon/cphalcon#14334]
### Description

we'd better provide a persistent id for Redis `pconnect()` method.

cause without it we can't switch between multiple databases in the same PHP process.

the data will always be saved to the last database without it.

as I know all Phalcon versions have this bug.

check this: https://github.com/phpredis/phpredis#pconnect-popen

### Details
![image](https://user-images.githubusercontent.com/3468024/63759007-575d9300-c8ef-11e9-87c8-c08c8797f25e.png)

* Phalcon version: all versions
* Adapter location: https://github.com/phalcon/cphalcon/blob/master/phalcon/Storage/Adapter/Redis.zep#L126
* My code modification reference:
https://github.com/lanlin/cphalcon/commit/856dd1c07e0f26966e86894abfad9013444153d3

**Comment by niden** [comment]
Implemented
