### ISSUE TITLE
Invalid return type of Phalcon\Flash\AbstractFlash methods

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#14349]
The Following methods should always return `void`, not `string`:

- `Phalcon\Flash\AbstractFlash::error`
- `Phalcon\Flash\AbstractFlash::notice`
- `Phalcon\Flash\AbstractFlash::success`
- `Phalcon\Flash\AbstractFlash::warning`

**Comment by niden** [comment]
Resolved
