### ISSUE TITLE
7.4 Tests (GD)

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#14348]
Check if the GD extension is loaded for the Image/GD tests

https://travis-ci.org/phalcon/cphalcon/jobs/579952736#L1562

**Comment by ruudboon** [comment]
Founded some info about changed build params. https://github.com/php/php-src/blob/9499484ed2f0377678b2b4d88573327ee0e4ce6d/UPGRADING#L394

**Comment by sergeyklay** [comment]
@ruudboon We're not build PHP form source, Travis team uses this project: https://github.com/php-build/php-build

**Comment by ruudboon** [comment]
@sergeyklay Hmm they already fixed it there

**Comment by ruudboon** [comment]
For bionic the correct config is missing in Travis. I've created a pull that should solve this. https://github.com/travis-ci/php-src-builder/pulls

**Comment by sergeyklay** [comment]
Fixed in the `4.0.x` branch.
