### ISSUE TITLE
3.4.4 - Installation not working as described in docs

### ISSUE THREAD

**Issue by abcpremium** [phalcon/cphalcon#14352]
### Expected and Actual Behavior

Hey everyone, I wanted to make a clean new installation of Phalcon version 3.4.4 and followed the instructions issued in the documentation here: [https://docs.phalcon.io/3.4/en/installation](https://docs.phalcon.io/3.4/en/installation).

> **Step 1: Adding the repository**

I ran `curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash` which worked perfectly to add the repository to my apt list.

> **Step 2: Installing Phalcon**

Then I ran `sudo apt-get update`, which leads to the following output:

```
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease          
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease        
Ign:4 https://packagecloud.io/phalcon/stable/raspbian buster InRelease 
Err:5 https://packagecloud.io/phalcon/stable/raspbian buster Release
  404  Not Found [IP: 54.183.241.58 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/phalcon/stable/raspbian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

When I then run `sudo apt-get install php7.3-phalcon`, I only get the output that the package could not be found. I even tried `sudo apt-get install php7.0-phalcon` where I get the same response.

Can someone explain me what is going on here please and how I can fix that?

Thank you very much guys!

### Details

* PHP Version: 7.3.4-2
* Operating System: Raspbian 10 (buster)
* Installation type: installing via package manager
* Server: Apache

**Comment by ruudboon** [comment]
Currently we don't have support for Raspbian packages. While Raspbian is based on Debian, it's not identical. You may need to compile from source on your Pi.

**Comment by Jeckerson** [comment]
You can try to build it from source.

**Comment by abcpremium** [comment]
I got it working by compiling from source as you both mentioned. Thank you very much! I'm closing this now =).
