### ISSUE TITLE
[NFR] Read & Write JSON File Helper

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14372]
I really like the new ``Phalcon\Helper`` in Phalcon v4. But I think it can use more functions like this to help with Jsons. By combining ``file_get_contents() with json_decode()`` or ``file_put_contents() with json_encode()`` or similar.

Json to Object & Array from File
```php
$file = '../storage/file.json';
$data = file_get_contents($file);
$json = json_decode($file, true);
```
Add Simple Json Read From File:
```php
use Phalcon\Helper\Json; // or put this in Phalcon\Helper\File
Json::read($file, $mode);
// modes:
// 0 or FALSE - (default) Array
// 1 or TRUE - Object
```

Array to Json File
```php
$file = '../storage/file.json';
file_put_contents($file, $data, FILE_APPEND);
```
Add Simple Json Write To File:
```php
use Phalcon\Helper\Json; // or put this in Phalcon\Helper\File
Json::write($file, $data, $mode);
// modes:
// 0 or FALSE - (default) overwrite file
// 1 or TRUE - append to file if exists.
```

**Comment by ruudboon** [comment]
If you ask me the reading and writing of the files maybe a bit too much for the helper.

**Comment by sergeyklay** [comment]
Please stop propose create all-in-one Helper namespace :) Are we going to introduce new Kohana inside a Phalcon\Helper namespace? Helper is a function, no class. Why not Phalcon\Json?  Why we're need static nature in the DI & IoC century?

**Comment by v00v** [comment]
@ruudboon so is some other helper functions, but if we are going this route reading/writing files is actually very useful.

@sergeyklay It can be Phalcon\Json of course, this was just an example. Also it doesn't have to use PHP's ``file_get_contents()`` and ``file_put_contents()`` functions. It can use native C/Zephir functions to achive this for best performance. The idea behind request is to have something that reads/writes files with performnace of Phalcon instead of having to use PHP functions directly. I think this will be very useful for those like me who work with flat-files or json files regularly. Having something like ``Json::read`` and ``Json::write`` is very usefl. This can also be extended to ``Phalcon\XML`` and ``Phalcon\CVS`` for example. It can also be just called ``Phalcon\File`` and everything that relateds to that can be there.

But if you guys think this is not needed in Phalcon, I understand. Coding own custom class library with those functions is not that hard. But I'm sure performance will be slower.

**Comment by v00v** [comment]
Thank you for not closing this NFR and considering in future versions. Whichever way you choose to organize this, dosn't really matter. As long as we at least have basic flat-file support for Read (similar to file_get_contents) / Write (similar to file_put_contents) / Index (similar to globe) of different files. THANK YOU!

**Comment by Jurigag** [comment]
I would vote more for something like serializer class as in symfony. So we would have method like encode and decode and maybe encodeToFile and decodeFromFile?

**Comment by v00v** [comment]
@Jurigag You do not always need serializer. Sometimes you seemply need to use ``file_get_contents()`` and ``json_decode()`` or ``json_encode()`` and ``file_put_contents()`` without serializer. This is why I'm requesting to have simple functions to read and write flat files which can be seperated by type. Like ``Phalcon\File\Json`` and ``Json::read()`` or ``Json::write()`` and similar for TXT, CVS, XML etc...

**Comment by sergeyklay** [comment]
We don't believe that this feature should be developed as a part of the Phalcon framework. Consider using a separated library to implement json helpers.
