### ISSUE TITLE
Volt Newlines Cleanup

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14375]
If something is commented out with ``{# comment #}`` or volt syntax ``{% something %}`` used in volt file, it leaves empty newlines. This newlines should be auto-removed by default on any html output.

Volt File:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    {# <link rel="stylesheet" href="file1.css"> #}
    {# <link rel="stylesheet" href="file2.css"> #}
    {# <script src="file1.min.js"></script> #}
    {# <script src="file2.min.js"></script> #}
  </head>
<body>
{% include 'file.volt' %}
{% block content %}{% endblock %}
</body>
</html>
```

HTML Output: (14-lines, 113-bytes)
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    
    
    
    
  </head>
<body>


</body>
</html>
```

Expected HTML Output: (8-lines, 91-bytes)
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
  </head>
<body>
</body>
</html>
```

Much cleaner, and less useless newlines ^_^

**Comment by sergeyklay** [comment]
Use
- `{#- comment #}` 
- `{# comment -#}` 
- `{#- comment -#}` 
- `{%- something %}`
- `{% something -%}`
- `{%- something -%}`
