### ISSUE TITLE
[RFC] Change property order in model->assign()

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14386]
Our current implementation looks like this:
```
assign(array $data, [mixed $dataColumnMap], [array $whiteList])
```
Often you will setup the column map in the model and don't specify it when assigning data to the model. When using the whitelist you should always put null on the dataColumnMap.
It would be me more logical to have the whitelist first.
```
assign(array $data, [array $whiteList], [mixed $dataColumnMap])
```

**Comment by niden** [comment]
Resolved
