### ISSUE TITLE
[Phalcon v4.0.0-beta2] Model fields underscores not being converted to camelCase

### ISSUE THREAD

**Issue by diplopito** [phalcon/cphalcon#14384]
### Expected and Actual Behavior

Fields with underscores should be treated as camelCase by default. Actually, not happening: fields need to be used with underscores or is mandatory to use a column mapper.

Example: please check the use of the fields in the test cases:  https://github.com/diplopito/phalconModel

### Details

* Phalcon version: 4.0.0-beta2
* PHP Version: 7.2
* Operating System: Windows 10
* Installation type: dll
* Server: 2.4
* Other related info (Database, table schema): provided in example app

**Comment by Jurigag** [comment]
? It was always like this, not sure what's a bug here.

**Comment by Jurigag** [comment]
Well as according to slack conversation there is no bug.

**Comment by ruudboon** [comment]
Discord :D
