### ISSUE TITLE
[Phalcon v4.0.0-beta2] Error when updating models

### ISSUE THREAD

**Issue by diplopito** [phalcon/cphalcon#14382]
### Expected and Actual Behavior
When updating a model, submitted fields data should be updated. Actual behavior: not updating records but trying to create new ones (and fails).

To reproduce this error, please run the tests in https://github.com/diplopito/phalconModel

### Details

* Phalcon version: 4.0.0-beta2
* PHP Version: 7.2
* Operating System: Windows 10
* Installation type: dll
* Server: Apache
* Other related info (Database, table schema): provided in example app.

**Comment by diplopito** [comment]
If using getters and setters, underscores must be used as well, otherwise the field won't be found. The bug persists as well with them.

```php
<?php

use Phalcon\Mvc\Model;

class Users extends Model
{
    protected $id;

    protected $firstName;

    protected $lastName;

    protected $password;

    public function getId()
    {
        return $this->id;
    }

    public function setFirstName($name)
    {
        $this->first_name = $name;
    }

    public function getFirstName()
    {
        return $this->first_name;
    }
}

```

**Comment by diplopito** [comment]
Just added an events manager to print the sql queries.

**Comment by diplopito** [comment]
Created a BaseModel to handle afterSave() and notSaved() events. Worth noticing that when using the whitelist option (last test case), the notSaved() event is not even fired.

**Comment by ruudboon** [comment]
The whitelist was used as column map. We will add some extra tests. The assign method is missing in not fully tested.

**Comment by diplopito** [comment]
The white list feature works only when updating **and** using `update()`. Not with `save()` because it will require mandatory fields even if they are not in the white list.

So, if the user wants to implement the white list to update a record, the use of `save()` should be discouraged (it won't work as it is now). The steps to update a record using the white list are then:

```php
<?php

use Store\Toys\Robots;

$post =  [
      'name' => 'Astro Man',
      'type' => 'bot'
];

$robot = Robots::findFirst(1);

$robot->assign(
   $post ,
   null,
   [ 
     'price'
   ]
);

$robot->update();  //not interchangeable with `save()`: if there are mandatory fields in the model not included in the white list, fails.

```
> `null` given as second parameter if there is no column map array given for the white list.
