### ISSUE TITLE
[BUG]: Di->remove doesn't work

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14396]
**Describe the bug**
When using di->remove('test') $di->has('test') will return true on the object

**To Reproduce**
> Provide output if related. Provide coredump if any. Use 

```php
$di->set('escaper', Escaper::class);

$I->assertCount(1, $di->getServices());

$di->remove('escaper');
$I->assertFalse($di->has('escaper'));
```

See also https://github.com/phalcon/cphalcon/pull/14176

Related to https://github.com/phalcon/zephir/issues/1259

**Comment by niden** [comment]
Resolved
