### ISSUE TITLE
[NFR] Ability to handle the request via Psr ServerRequest

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#14390]
Now Phalcon handle and get data from request via URI and native Phalcon\Http\Request.

I want to use RoadRunner in my application, but RoadRunner provide request as Psr ServerRequest.
Therefore I cant 't use RoadRunner in my Phalcon 4 application.

Sure, I can to write my realization of Phalcon\Http\RequestInterface for get data from Psr ServerRequest, but it so many code and i want to see this realization from Phalcon Developers.

Thank.

**Comment by Jeckerson** [comment]
As I can see, they do integrations to frameworks by them self

![image](https://user-images.githubusercontent.com/3289702/65181818-d3af4600-da57-11e9-86e9-b46d480ce19b.png)

Also here, work in progress for Laravel - https://github.com/spiral/roadrunner/issues/96

**Comment by niden** [comment]
v4 does have the PSR related components in the `Http\Message` namespace. You can use them directly from there. 

In future versions the goal is to rewrite the full HTTP layer so that it only uses PSR classes. That will probably not happen until 4.2 maybe later.

**Comment by TimurFlush** [comment]
Thank you, @niden 
I will be waiting for 4.2)

**Comment by wolfy-j** [comment]
We do not integrations by ourselves... that will be too much. You can also use underlying Http consumer to skip psr-7 step if needed.

**Comment by kcloze** [comment]
I write a simple adapt, you canrefer to the implementation.
https://github.com/kcloze/phalcon-roadrunner

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608

**Comment by Slach** [comment]
guys common direct link for voting
https://github.com/phalcon/cphalcon/issues/14608#issuecomment-563472103
