### ISSUE TITLE
[NFR]: Classes should not have application defaults

### ISSUE THREAD

**Issue by harm-smits** [phalcon/cphalcon#14412]
**Is your feature request related to a problem? Please describe.**
When I tried to initialize the router class, it would not give me a '404' because a default route was initialized, even though I created a new instance. Instead, it tried initializing a controller I used with a random action, which threw an error.

**Describe the solution you'd like**
I would like the coding standards of Phalcon to include a mention about classes not having default application data like routes in them. For these things there are factory classes, so it makes more sense to have such things in there as otherwise there is no real point in creating factory classes.

**Describe alternatives you've considered**
No real alternatives, except for in the case of the router, to pass a 'false' parameter, to indicate that it should not load default routes.

**Additional context**
Phalcon is both a framework and somewhat an application at the same time. Mangling these two things together results in unexpected behavior on both ends. Some classes might not be loaded with application defaults, and others might be. In order to provide a consistent experience for developers and to make more clear what is part of the application and what is part of the framework, there should be a clear line about these default application values in classes. 

My opinion is that classes by itself should not have application values by default (e.g. routes), but that these should be initialized by means of the factory / application classes. Not only will this clean up the code by a fair bit, but it will also prevent these kinds of cases where defaults leave someone puzzling about an error for hours. It will also show developers how these classes are initialized in e.g. the case of Invo. Furthermore, there can also be serious security implications that can be application specific. I will not go into further details on this as this could have serious effects on some production domains.

Lastly, I think the community should vote on a matter like this. It is a breaking change in some scenarios and it should be thoroughly checked before being implemented.

P.S. Do mind the difference between 'application defaults' and 'default values'. Application defaults can be things like routes, acl roles, etc. whilst default values are things like default controller names, actions, etc.

**Comment by v00v** [comment]
Are you talking about ``$router = new Router(false);``  ? I always use it as ``false`` and then have this in my routes.php to handle my 404 errors.

```php
$rt->notFound([
	'controller' => 'base',
	'action' => 'error'
]);
```

**Comment by harm-smits** [comment]
@v00v Yes I am. I think the class should not load with default routes when you use `$router = new Router();`, it makes not a lot of sense from a framework perspective.

**Comment by v00v** [comment]
I only used non-default routes, so I agree. Better have ``$router = new Router(true)`` But its not a very big deal to just use ``false`` value :-)

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
