### ISSUE TITLE
[BUG]: form POST fails in Firefox when accessing with IPv6 literals and 1st party isolation enabled

### ISSUE THREAD

**Issue by jospanier** [phalcon/cphalcon#14428]
**Bug Description**
POST not handled correctly while accessed via IPv6 literal, e.g. https://[2001:db8:1111:2222::1] when Firefox first party isolation is enabled (privacy.firstparty.isolate = true). Same works corrctly with IPv4.

**To Reproduce**
1. assign IPv6 to host
2. enable first party isolation in FF (privacy.firstparty.isolate = true)
3. access/login to site with IPv6 literal (e.g. https://[2001:db8:1111:2222::1]/ )
4. browse to any form that would POST data
5. submit form

**Expected behavior**
same page is loaded with new parameters, instead a new login is requested
this works fine with IPv4 on same site

**Additional context**
POST results in 302, but followed by GET with new PHPSESSID

This issue was redirected here from https://github.com/opnsense/core/issues/3731

**Comment by ruudboon** [comment]
@jospanier What Phalcon version & Php version are you using?
Do you also have a some code examples how you handle the post?

**Comment by jospanier** [comment]
I will try to ask the maintainers of the appication for assistance, since it I am not the developer of the application (OPNsense) where the bug appeared to me.

Meanwhile here are the versions used in OPNsense 19.7.4_1

PHP 7.2.22 (cli) (built: Sep  9 2019 22:34:07) ( NTS )
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.4
Build Date => Jul 14 2019 03:00:07
Powered by Zephir => Version 0.10.16-6826149172

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

**Comment by ruudboon** [comment]
@jospanier Any updates regarding this issue?

**Comment by jospanier** [comment]
Since I am not the original developer of the code where the bug appeared to me (OPNsense GUI) and not fluent in PHP I can not comment further on this issue. Is it possible that you head on over the the linked OPNsense issue and ask for the code examples there please? All I can do at this point is to try to facilitate a conversation between the two projects.

**Comment by ruudboon** [comment]
@jospanier We're gonna move this one to 4.1. Please let us know if you have some more information on this issue.
