### ISSUE TITLE
[BUG]: cacheDir option should be renamed

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14420]
The storage adapters in v4 should not be binded to cache.
Currently we have cacheDir for the stream.

Would like to change this to something like storageDir. Maybe keep cacheDir as deprecated option?

**Comment by niden** [comment]
The stream storage adapter needs a directory so this option is required. We just need to change the name of the option to `storageDir`

**Comment by SidRoberts** [comment]
I'm just going to slide into this thread and suggest `dir`. :wink:

**Comment by sergeyklay** [comment]
A "directory" for what purpose? IMO just "directory" is the same as "hullaballoo".

**Comment by ruudboon** [comment]
At long as it isn't cacheDir I don't really mind. This has nothing to do with cache. You can use it to store anything.  StorageDir sounds good to me but I'm open for other suggestions. Something like destination could also work for me.

**Comment by sergeyklay** [comment]
How will work "directory" word for Apcu or Libmemcached adapters?

**Comment by niden** [comment]
`storageDir` would be enough I believe.

**Comment by niden** [comment]
Resolved https://github.com/phalcon/cphalcon/pull/14423
