### ISSUE TITLE
[BUG]: Phalcon\Forms\Form setAction() Exception

### ISSUE THREAD

**Issue by richmilns** [phalcon/cphalcon#14430]
When trying to set the action in the class for your form using the `setAction()` method, an exception is thrown:

**RuntimeException: Trying to call method set on a non-object**

Trace:
> 0 /app/modules/core/lib/Forms/Login.php(16): Phalcon\Forms\Form->setAction('/users/login')
1 [internal function]: Modules\Core\Forms\Login->initialize(NULL, Array)
2 /app/modules/core/controllers/UsersController.php(48): Phalcon\Forms\Form->__construct()
3 [internal function]: Modules\Core\Controllers\UsersController->loginAction()
4 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(Modules\Core\Controllers\UsersController), 'loginAction', Array)
5 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
6 /app/modules/core/lib/Bootstrap/Mvc.php(541): Phalcon\Mvc\Application->handle('/')
7 /app/modules/core/lib/Bootstrap/Main.php(589): Modules\Core\Bootstrap\Mvc->runApplication()
8 /app/public/index.php(8): Modules\Core\Bootstrap\Main->run()
9 {main}

```php
use Phalcon\Forms\Form;

class Login extends Form
{
    public function initialize()
    {
        $this->setAction('/users/login');
    }
}
```

**Details**
 - Phalcon version: 4.0.0-rc1
 - PHP Version: 7.3.8
 - Operating System: macOS 10.14.6
 - Installation type: Compiling from source
 - Zephir version (if any): n/a
 - Server: Apache 
 - Other related info (Database, table schema): n/a

**Comment by TimurFlush** [comment]
I confirm this behavior

**Comment by niden** [comment]
This has been resolved. Thank you @richmilns
