### ISSUE TITLE
[NFR]: Volt: Block functions

### ISSUE THREAD

**Issue by harm-smits** [phalcon/cphalcon#14436]
**Is your feature request related to a problem? Please describe.**
In our code-base, we use a lot of block functions in Smarty. Sadly there is no way to add these to Phalcon.

**Describe the solution you'd like**
Block functions to be implemented in Phalcon.

**Describe alternatives you've considered**
Using a function with a separate template, but this just ends up being too much of a mess.

**Additional context**
Block functions are functions of the form: `{% function %} .... {% endfunction %}` In other words, they enclose a template block and operate on the contents of this block.

I would advice to use a similar structure to Smarty for this. Prototyped, it will look as follows:
```
class Compiler
{
    ....
    public function addBlockFunction($alias, function ($params, $content, &$compiler, &$repeat) {});
    ....
}
```

This callable should be called as follows:
- By default the function implementation is called twice: once for the opening tag, and once for the closing tag. (You can use $repeat to change this, see below)
- Only the opening tag of the block function should have attributes. All attributes passed to template functions from the template are contained in the `$params` variable as an associative array. The opening tag attributes should also accessible to the function when processing the closing tag.
- The value of the `$content` variable should depend on whether the function is called for the opening or closing tag. In case of the opening tag, it ought to be NULL, and in case of the closing tag it ought to be the contents of the template block. Note that the template block will then have already been processed, so all it is the template output, not the template source.
- The parameter `$repeat` is passed by reference to the function implementation and provides a possibility for it to control how many times the block is displayed. By default `$repeat` should be TRUE at the first call of the block-function (the opening tag) and FALSE on all subsequent calls to the block function (the block's closing tag). Each time the function implementation returns with $repeat being TRUE, the block contents should be evaluated and the function implementation should be called again with the new block contents in the parameter `$content`.

Use cases?
- css block function that can automatically inline CSS:
```
{% css %}
html {color: red}
{% endcss %}
```
- capturing contents and setting it in a variable
```
{% capture "test" %}
<div class="test"></div>
{% endcapture %}

{{ volt.capture.test }}
```
- markdown parser
```
{% markdown %}
## Hello!
{% endmarkdown %}
```
- And many more, I can add more when required, but I think that with a little imagination a lot of possibilities can be seen.

**Comment by v00v** [comment]
I would like to see something like this too. Good request @harm-smits

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608
