### ISSUE TITLE
[BUG]: Error Compiling from source

### ISSUE THREAD

**Issue by saravanank90** [phalcon/cphalcon#14443]
**Describe the bug**
   Error building cphalcon

**To Reproduce**
```
git clone https://github.com/phalcon/cphalcon
cd cphalcon/
git checkout tags/v4.0.0-alpha1 ./
zephir fullclean
zephir build
```

> Error Output

```
StaticTypeInference=mcall undefined
StaticTypeInference=mcall undefined                                                       
 [ERROR] Global 'orm.exception_on_failed_metadata_save' cannot be read because  
         it isn't defined in                                                    
         /home/saravanan/Projects/cphalcon/phalcon/Mvc/Model/MetaData.zep on line  
         715                                                                                                                                                
```

**Details**
 - Phalcon version: `4.0`
 - PHP Version: `7.3.9`
 - Operating System: `fedora 30`
 - Installation type: `Compiling from source`
 - Zephir version (if any): `0.12.4`
 - Server: `Apache(Bitnami lamp stack)`

**Additional context**
Similar error was reported that this error had occurred in raspberry pi and the solution(increase dphys-swapfile from 100 to 2000MB)  given was not suitable for fedora.

**Comment by Jeckerson** [comment]
Can you try with latest `v4.0.0-rc.1` tag?

**Comment by saravanank90** [comment]
Yes I tried and installed. In the beginning i was thinking why checkout alpha while rc-1 is available. Really my bad.

![image](https://user-images.githubusercontent.com/56083993/66139841-ba44f700-e61e-11e9-8871-194e1bec9b59.png)
