### ISSUE TITLE
[NFR]: Prevent unnecessary database requests for relationships where key is NULL

### ISSUE THREAD

**Issue by wurst-hans** [phalcon/cphalcon#14471]
Having a simple relationship in model

```
class Requests extends Model {
    public function initialize() {
        $this->belongsTo('customerId', 'App\Models\Customers', 'id', [ 'alias' => 'Customer' ]);
	}
}
```

I can get a customer like this

```
$request = Requests::findFirst();
$customer = $request->getCustomer();
```

As I have enabled logging of native MySQL queries in my development environment, I can see that Phalcon queries database for customer even when `customerId` in model `Requests` is `NULL`:

```
SELECT `customers`.`id` [...] FROM `customers` WHERE `customers`.`id`=:APR0 LIMIT :APL0
```
(having `APR0=NULL` and `APL0=1`)

For performance reasons I suggest, that Phalcon immediately returns `NULL` when accessing a related model, when key column is `NULL`.

**Comment by niden** [comment]
@wurst-hans I have been looking at this and have been trying to write some tests just to make sure that everything is fine. 

So the change needs to happen in the `Mvc\Manager` class where the `APR0` parameter is used. There are two spots, one for a simple relationship and one for a compound one.

I have some reservations for this change, here is why

In your example things are pretty straight forward. The relationship is `Request` -> `Customer`. If you have `null` as `customer_id` then there is no `Customer` record. This assumes that the `customer_id` is a primary key and not just a key. So if you allow for more (one to many) then one might actually want to get records that have that foreign key `null`.

The situation becomes more complex in compound relationships. One might need field `x` to be `null` or not and `y` to be for instance `1` or `2` etc.

This will definitely remove one query from the process but aren't we going to start restricting peoples choices on how their apps work? This is definitely going to be a breaking change potentially for many apps.

**Comment by niden** [comment]
I am going to close this. We can revisit this later if it becomes a huge issue with performance.

**Comment by wurst-hans** [comment]
Hope my comment will not re-open this issue, but just to give my 2ct.

I understand what you mean. My approach was not to restrict people in designing their apps. I just wanted to prevent some unnecessary database requests, I have a use case where I create a PDF for list of objects having some relations. So, when there are some dozens or hundreds of these queries returning `NULL` because the column is `NULL` and no related record can be found, then one *could* avoid these queries just for performance reasons.

Sure, I can check it the following way:

```
if (is_null($request->customer_id)) {
    $customer = null;
} else {
    $customer = $request->getCustomer();
}
```

But this should be a thing, I expect the framework to handle for me. And from my perspective it shouldn't be that complex, even with compound keys. Simply check if *all* of the keys/properties defined in `hasMany` or whatever are `NULL` and return `NULL` in this case, else continue with default behavior. I want to describe it with some simple logic:

```
$skip = true;
foreach ($column in $referencedFields) {
    if (!is_null($this->column)) {
        $skip = false;
        break;
    }
}
if ($skip) {
    return null;
}
// default behavior...
```

If my consideration is too naive, then please apologize me :-) But I thought that would be an easy thing to integrate.
So, currently, this is not a technical problem, but a cosmetic thing. As you said, maybe in future, we come back to this.

**Comment by niden** [comment]
Thank you @wurst-hans 

I will keep this closed for now. I want to see how the DataMapper will perform in v6 before we start tinkering with the performance of the existing Active Record implementation.

Your issue is definitely something to keep in mind, to ensure that the minimum amount of queries is executed in the database.
