### ISSUE TITLE
[BUG]: Wrong #1 parameter given to Phalcon\Cache constructor

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#14481]
**Describe the bug**

```
Parameter #1 $adapter of class Phalcon\Cache constructor expects Phalcon\Cache\Adapter\AdapterInterface, Phalcon\Cache\Adapter\AbstractAdapter given.
```

_Current issue is also related to ide-stubs, but maybe there might be some internal rework in `Phalcon\Cache` class.._

**To Reproduce**
Picked from documentation - https://docs.phalcon.io/4.0/en/cache#cache-1
```
<?php

use Phalcon\Cache;
use Phalcon\Cache\AdapterFactory;
use Phalcon\Storage\Serializer\SerializerFactory;

$serializerFactory = new SerializerFactory();
$adapterFactory    = new AdapterFactory($serializerFactory);

$options = [
    'defaultSerializer' => 'Json',
    'lifetime'          => 7200
];

$adapter = $adapterFactory->newInstance('apcu', $options);

$cache = new Cache($adapter);
```

**Expected behavior**
* Update Phalcon\Cache constructor
* Update ide-stubs

**Details**
 - Phalcon version: `4.0.0-rc.1`
 - PHP Version: any
 - Operating System: any

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14482
