### ISSUE TITLE
[BUG]: Update Changelog v4 - Removed Logger setLogLevel() method

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#14480]
Can't find in Phalcon v4. If It was really removed, so it breaks compatibly.

Example from devtools v3.4:
```
$logger->setFormatter($formatter);
$logger->setLogLevel(Logger::ERROR);  // <---
```

**Comment by niden** [comment]
I don't recall what the `setLogLevel` was used for. I am sure it was removed - checked the code.

**Comment by niden** [comment]
Need to add the minimum log level as an option to the logger

**Comment by niden** [comment]
Implemented https://github.com/phalcon/cphalcon/pull/14483
