### ISSUE TITLE
[BUG]: ignore_unknown_columns isn't always accounted for

### ISSUE THREAD

**Issue by CameronHall** [phalcon/cphalcon#14485]
There are no checks if we've set the `phalcon.orm.ignore_unknown_columns` value on [`Phalcon\Mvc\Model\Resultset\Simple`](https://github.com/phalcon/cphalcon/blob/a48b31967a1ce27c10cbed61bee42e0c90addc86/phalcon/Mvc/Model/Resultset/Simple.zep#L184-L231)

There are similar instances on Phalcon [`Phalcon\Mvc\Model`](https://github.com/phalcon/cphalcon/blob/a48b31967a1ce27c10cbed61bee42e0c90addc86/phalcon/Mvc/Model.zep#L3452), [`Phalcon\Mvc\Model\Query\Builder`](https://github.com/phalcon/cphalcon/blob/a48b31967a1ce27c10cbed61bee42e0c90addc86/phalcon/Mvc/Model/Query/Builder.zep#L674) and [`Phalcon\Mvc\Model\Query`](https://github.com/phalcon/cphalcon/blob/a48b31967a1ce27c10cbed61bee42e0c90addc86/phalcon/Mvc/Model/Query.zep#L3300)

This is an issue on both 3.4.x and 4.0.x

**Comment by niden** [comment]
Resolved: https://github.com/phalcon/cphalcon/pull/14486
