### ISSUE TITLE
[BUG]: v4.0.0-rc.2 - Blank Page!

### ISSUE THREAD

**Issue by LearnPhalcon** [phalcon/cphalcon#14496]
I have blank page with newest phalcon version **4.0.0-rc.2** project works just fine with **4.0.0-rc.1** It maybe has something to do with newest change #14407.

Code That Works In RC1 but not in RC2.
```php
$REQUEST = $_SERVER['REQUEST_URI'];
echo $app->handle($REQUEST)->getContent();
```

It might also be something with my view code in RC2. This works on RC1.
```php
$di->set('view', function() {
	$view = new View();
	$view->setViewsDir('../app/view/');
	$view->registerEngines([
		'.volt' => function($view) {
			$volt = new Volt($view, $this);
			$volt->setOptions([
				'path' => '../app/cache/',
				# 'prefix' => 'cache',
				# 'separator' => '-',
				# 'extension' => '.cache',
				'stat' => true,
				'always' => true,
			]); #options
			return $volt;
		} #volt
	]); #engines
	return $view;
}); #view
```
I just don't see what has changed from RC1 to RC2 and why its does not work anymore. It dosn't trow any errors, nothing in logs at all - just blank page. It looks like it dosn't load my views properly. When I do simple test like ``exit('TEST')'`` before showing my view - it seems to work fine.

**Comment by andrew-demb** [comment]
See #14491

Workaround now - use `setShared` for view service

**Comment by ruudboon** [comment]
Closing this in favour of #14491
