### ISSUE TITLE
[BUG]: cphalcon-4.0.0-rc.2 $this->partial not work

### ISSUE THREAD

**Issue by jonnywang** [phalcon/cphalcon#14512]
Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**
$this->partial and $this->view->setVars not work

**To Reproduce**
```php
<?php $this->partial('_partials/header'); ?>
<?php echo $this->getContent(); ?>
<?php $this->partial('_partials/footer'); ?>
```

**Details**
 - Phalcon version: cphalcon-4.0.0-rc.2
 - PHP Version: 7.2.10
 - Operating System: macos

**Additional context**

**Comment by sergeyklay** [comment]
Closing this in favor of #14491
