### ISSUE TITLE
[BUG]: modelCache Error  "Data for JSON serializer cannot be of type object"

### ISSUE THREAD

**Issue by bain2018** [phalcon/cphalcon#14528]
**Describe the bug**

// set a modelCache di

$di->setShared('modelsCache', function () {

    $config = $this->getConfig();

    $serializerFactory = new \Phalcon\Storage\SerializerFactory();
    $adapterFactory    = new \Phalcon\Cache\AdapterFactory($serializerFactory);

    $options = [
        'defaultSerializer' => 'Json',
        'lifetime'          => 7200,
        'host' => $config->redis->host,
        'port' => $config->redis->port,
        'auth' => $config->redis->auth,
        'index' =>1,
    ];

    $adapter = $adapterFactory->newInstance('redis', $options);

    return new \Phalcon\Cache($adapter);
});

find a result:
        $data=config::find([
            'conditions'=>'status=1',
            'cache'=>[
                'key'      => 'model-config',
                'lifetime' => 3600*24*7,
            ],
        ]);

get error :
 "Data for JSON serializer cannot be of type object"

debugtrace

#0 [internal function]: Phalcon\Storage\Serializer\Json->serialize()
#1 [internal function]: Phalcon\Storage\Adapter\AbstractAdapter->getSerializedData(NULL)
#2 [internal function]: Phalcon\Storage\Adapter\Redis->set('model-config', Object(Phalcon\Mvc\Model\Resultset\Simple), 604800)
#3 [internal function]: Phalcon\Cache->set('model-config', Object(Phalcon\Mvc\Model\Resultset\Simple), 604800)
#4 [internal function]: Phalcon\Mvc\Model\Query->execute()

**Details**
 - Phalcon version:4.0 rc2
 - PHP Version: 7.3.11
 - Operating System: ubuntu

**Comment by niden** [comment]
Resolved in: https://github.com/phalcon/cphalcon/pull/14529
