### ISSUE TITLE
[BUG]: Method getIdentityField() not always return string

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#14523]
**Describe the bug**
Not sure if bug, but according to method interface declaration it must return always the **string**.
https://github.com/phalcon/cphalcon/blob/033c708b15d727e00e740bfc5650556a154251fb/phalcon/Mvc/Model/MetaDataInterface.zep#L71

But, in case, if primary key does not exist, it return **false**.

**To Reproduce**

```sql
 CREATE TABLE test (id INT, name VARCHAR(55));
```

```php
$entity = new ModelTest();
$identityField = $this->modelsMetadata->getIdentityField($entity);
var_dump($identityField); // bool(false)
```

**Expected behavior**
Probably, return **null** or empty string (''), but not **false**.
That way assert interface contract declaration:

```php
public function getIdentityField(\Phalcon\Mvc\ModelInterface $model): string;
```
or 
```php
public function getIdentityField(\Phalcon\Mvc\ModelInterface $model): ?string;
```

And then return:
```php
$entity = new ModelTest();
$identityField = $this->modelsMetadata->getIdentityField($entity);
var_dump($identityField); // null
```

**Details**
 - Phalcon version: `4.0.0-rc.2`
 - PHP Version: `7.2.19`
 - Operating System: Ubuntu 18
 - Installation type: Compiling from source

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14530/
