### ISSUE TITLE
[BUG]: Annotations Router - conversor

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#14532]
We need to rename the `Conversor` annotation (and any similar references to variables or other entities) to `Converter`

**Comment by niden** [comment]
cc @sergeyklay

**Comment by Jeckerson** [comment]
May be related - https://github.com/phalcon/cphalcon/issues/14524

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14541
