### ISSUE TITLE
[BUG]: Phaclon Model properties conflicts with the database column

### ISSUE THREAD

**Issue by bain2018** [phalcon/cphalcon#14538]
create a table user only have three fields  id,username,source

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `source` varchar(255) NOT NULL  // pls attent this field name *****
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

and pls add a record as the follow
id=1
username=bain
source=conflict

Magic error : // in Chinese：见证奇迹的时刻

$user=User::findFirst([
         'conditions'=>'id=1'
]);
var_dump($user->getSource());  // user

$user->username='obama';
$user->save();

catch an error:
Table 'conflict' doesn't exist in database when dumping meta-data for User

if u rename the field source to another name,such as  address and flush the modelcache ,if get well

Phalcon version:4.0 rc2
PHP Version: 7.3.11
Operating System: ubuntu

**Comment by niden** [comment]
Only happens if the model does not have public properties defined i.e.

```
class Sources extends Phalcon\Mvc\Model
{
    public function initialize()
    {
        $this->setSource('sources');
    }
}
```

If the model is defined like this:
```
class Sources extends Phalcon\Mvc\Model
{
    public $id;
    public $username;
    public $source;

    public function initialize()
    {
        $this->setSource('sources');
    }
}
```
the issue does not appear.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14542

**Comment by niden** [comment]
Thank you @bain2018
