### ISSUE TITLE
[NFR]: Change prefix hash in component security

### ISSUE THREAD

**Issue by duythien** [phalcon/cphalcon#14544]
**Is your feature request related to a problem? Please describe.**
With default option 
```
<?php
use Phalcon\Security;
$security = new Security();
$security->setWorkFactor(8);
echo $security->hash('aa');
```
This will be get result like below
```
$2y$08$alZBRC9xTWU4MWQ3L2VmKu4hhdIPEAgU9zDgCEaR.SDvOderL5KFK
```
My expected we can  change random `$2y$08$` to any string I wish, for example with the string `$2a$08$`, may be with function `$security->setRandPrefix('$2a$08$`)

**Comment by niden** [comment]
I am not sure what `crypt` will return if you replace the prefix with something else `abcdef` etc.

If you really want to change the `y` to `a` i.e.

`$2y$08$` becomes `$2a$08$`

then all you have to do is change the hash to `Security::CRYPT_BLOWFISH_A` (5), and that will change the letter. The `08` is the work factor.

Do you want to change the `y` only?
`

**Comment by duythien** [comment]
Yes. Thanks it work for now
```
$security->setDefaultHash(5);
```
