### ISSUE TITLE
[BUG]: modelsCache hardcoded prefix 'ph-mm-reds-'

### ISSUE THREAD

**Issue by zordon13** [phalcon/cphalcon#14549]
**Describe the bug**
If we have more then one application working with one instance of Redis, and models name in that applications match together, then possible models of one of applications fill metata other application, becose they have same metadata-cache perfix **ph-mm-reds-** in
https://github.com/phalcon/cphalcon/blob/c4a804a70c9b89728f010b23935f450c79690bd7/phalcon/Mvc/Model/MetaData/Redis.zep#L46

**Expected behavior**
I think, need check if is set in **options** key **prefix**, then using this prefix. 
This will isolate the data of different applications and avoid undefined behavior.
**Details**
```
php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.0-rc.3
Build Date => Nov 19 2019 00:59:13
Powered by Zephir => Version 0.12.10-fedc314

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On
```

**Comment by niden** [comment]
Addressed it in https://github.com/phalcon/cphalcon/pull/14550

Funny, we had the optional default in `Libmemcached` but not in `Redis` and `Apcu`.

Nice catch. Thank you @zordon13

**Comment by niden** [comment]
Resolved
