### ISSUE TITLE
[NFR]: Bump up the work factor of security->hash()

### ISSUE THREAD

**Issue by Ruzgfpegk** [phalcon/cphalcon#14551]
**Is your feature request related to a problem? Please describe.**
Not a problem, rather a security enhancement.
In Security.zep, the [default work factor for bcrypt](https://docs.phalcon.io/4.0/en/security#password-hashing) is set to 8:
https://github.com/phalcon/cphalcon/blob/a48b31967a1ce27c10cbed61bee42e0c90addc86/phalcon/Security.zep#L58

The [Perils of the default bcrypt cost factor](https://labs.clio.com/bcrypt-cost-factor-4ca0a9b03966) article by Clio Labs is what made me question this value.
As I learned through this article, 8 is the value that was [suggested 20 years ago](https://www.usenix.org/legacy/publications/library/proceedings/usenix99/provos/provos_html/node6.html), and computing power has improved quite a bit since then.
[PHP uses a default value of 10](https://www.php.net/manual/en/function.password-hash.php), which means that, again by default, using Phalcon's security->hash instead of PHP's password_hash leads to passwords that are 4 times weaker; +1 to the work factor leading to a twice slower, so twice more robust, hash generation.

This article advised for a value of 12 three years ago (it would probably be higher today), but it may not be suitable for everybody as a default value.

**Describe the solution you'd like**
Bumping up the default work factor for bcrypt to at least 10, like PHP does by default.

**Describe alternatives you've considered**
Well of course it's up to people to adjust this setting themselves while developing, and relying on default values that can change over time may not be a good idea if you're not aware of them, but having a more secure default value for this setting would be nice.

**Additional context**
I encourage people to check the benchmarks on the mentioned article, they're a well-needed reality check, not even mentioning the fact that core count increased a lot recently in consumer-level CPUs.

**Comment by ruudboon** [comment]
I don't see an issue aligning this with the PHP default factor or higher. @niden @sergeyklay any thoughts?

**Comment by sergeyklay** [comment]
I'm ok with this.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14552

Thank you @Ruzgfpegk
