### ISSUE TITLE
[BUG/REGRESSION]: Phalcon\Escaper::escapeHtml() no longer accepts null in v4

### ISSUE THREAD

**Issue by terax6669** [phalcon/cphalcon#14553]
**Describe the bug**
v4 compiled with Zephir 0.12.x no longer allows to pass null to the method.

**To Reproduce**
```twig
{{ request.getPost('email') | e }}
```

Use the above piece of code in volt view on a GET request.

**Expected behavior**
When null is passed to the Escaper it returns null or empty string back to the view.

**Screenshots**
![image](https://user-images.githubusercontent.com/19204073/69448212-5e623900-0d58-11ea-89cb-be783dbeef50.png)

**Details**
 - Phalcon version: 4.0.0-rc3
 - PHP Version: 7.2
 - Operating System: Debian
 - Installation type: packagecloud.io
 - Server: Nginx

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14554

Thank you @terax6669
