### ISSUE TITLE
[BUG]: Phalcon\Di::setRaw() and getRaw() are misleading and/or incorrect

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#14555]
So `Di` has these three methods (Zephir translated to PHP):

- `getRaw(string $name) : mixed` which returns service definition, i.e. `return $service->getDefinition()`
- `setRaw(string $name, ServiceInterface $service)` which sets a *service*, i.e. `$this->services[$name] = $service`
- `getService(string $name) : ServiceInterface` which returns a *service*, i.e. `return $this->services[$name]`

Obviously, `getRaw()` and `setRaw()` do not match. By looking at the names, one would assume that if`getRaw()` returns just the definition, then `setRaw()` must set the definition of the service with the name provided as the first parameter, which is not the case. Instead, `setRaw()` actually sets the service, therefore it would make more sense to rename `setRaw()` to `setService()`.

Furthermore, I think that name argument in `setRaw()` is redundant, given that it could be obtained from the service which is the second argument.

```php
public function setRaw(string $name, ServiceInterface $service)
{
    ...
    $this->services[$name] = $service;
    ...
}
```
Should be
```php
public function setService(ServiceInterface $service)
{
    ...
    $name = $service->getName();
    $this->services[$name] = $service;
    ...
}
```
It doesn't need to break BC:
```php
/**
 * Must be properly documented here...
 */
public function setRaw(string $name, ServiceInterface $service)
{
    $this->setService($service);
}

public function setService(ServiceInterface $service)
{
    ...
    $name = $service->getName();
    $this->services[$name] = $service;
    ...
}
```

cc @niden @sergeyklay @Jurigag

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14561
