### ISSUE TITLE
[BUG]: {{ flash.output() }} output nothing

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#14565]
**Describe the bug**
By using `{{ flash.output() }}` inside .volt templates, messages do not appear. 

But, when using `{{ content() }}` it works!

https://docs.phalcon.io/4.0/en/flash#direct

**To Reproduce**

**1.**
```php
use Phalcon\Flash\Direct as FlashDirect;

$flash = new FlashDirect();
$flash->setCssClasses([
    'error' => 'alert alert-danger',
    'success' => 'alert alert-success',
     'notice' => 'alert alert-info',
     'warning' => 'alert alert-warning'
]);

return $flash;
```

**2.**
```php
$this->flash->error('Some message');
```

**3.**
```html
<div>
{{ flash.output() }}
</div>
```

**Screenshots**
Current example is with `{{ content() }}`
![image](https://user-images.githubusercontent.com/3289702/69906290-25aa0b80-13b9-11ea-8991-fe7dd6629127.png)

**Details**
 - Phalcon version: `4.0.0-RC.3`
 - PHP Version: `7.2`
 - Operating System: Ubuntu
 - Installation type: Compiling from source
 - Server: PHP Built-in

**Comment by Deathamns** [comment]
What if you add `$flash->setImplicitFlush(false);`?

**Comment by Jeckerson** [comment]
@Deathamns yep, with `$flash->setImplicitFlush(false)` during service registration it works.

@niden In docs it need to be specified. That outputting `{{ flash.output() }}` need to be in combo with `$flash->setImplicitFlush(false)`.

**Comment by niden** [comment]
We will update the docs accordingly. So this can be closed.
