### ISSUE TITLE
[BUG]: Fix AppVeyor build 

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#14563]
For more see https://ci.appveyor.com/project/sergeyklay/cphalcon/builds/29223700/job/q9gimp3bm8dg9mvc

**Comment by ruudboon** [comment]
Looks like a temporary glitch. It's working again. https://ci.appveyor.com/project/sergeyklay/cphalcon/builds/29229509/job/ovrlmt93i2vb0xm0

**Comment by ruudboon** [comment]
This is happening again. https://ci.appveyor.com/project/sergeyklay/cphalcon/builds/29232775/job/0ra787v60fjumw37

**Comment by ruudboon** [comment]
Looks like it stabilised again. Closing this now.
