### ISSUE TITLE
[NFR]: Postgres Arrays and array operators support

### ISSUE THREAD

**Issue by denysaw** [phalcon/cphalcon#14579]
It would be cool to start support Postgres Arrays and it's operators of containing one into another: `<@`, `@>`.
Whole list: https://www.postgresql.org/docs/9.6/functions-array.html

**Comment by niden** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608

**Comment by niden** [comment]
This was resolved in https://github.com/phalcon/cphalcon/pull/17109
