### ISSUE TITLE
[NFR]: Phalcon\Mvc\Model::_invokeFinder should merge provided arguments

### ISSUE THREAD

**Issue by CameronHall** [phalcon/cphalcon#14573]
**Is your feature request related to a problem? Please describe.**
You should be able to provide arguments to findFirstBy and findFirst. I.e.
```php
MyModel::findFirstByName('poato', [
    'order' => 'id DESC',
]);
```

**Describe the solution you'd like**
To be able to provide the argument and have them work...

**Describe alternatives you've considered**
I was going to resort to overloading `_invokeFinder` but the effort to reward was not worth it - considering I'd also be rewriting a method in userland vs. Zephir/C. Oh, and it's `final`.

**Comment by niden** [comment]
Implemented in https://github.com/phalcon/cphalcon/pull/14580

**Comment by CameronHall** [comment]
Appreciate this one getting done so promptly, I think this should have also given us the ability to specify secondary arguments. For example;

```
MyModel::findFirstByName('poato', [
   'conditions' => 'status = :status:',
    'bind' => [
        'status' =>MyModel::STATUS_ACTIVE,
    ]
    'order' => 'id DESC',
]);
// OR
MyModel::findFirstByName('poato', [
   'status = :status:',
    'bind' => [
        'status' =>MyModel::STATUS_ACTIVE,
    ]
    'order' => 'id DESC',
]);
```

Then the conditions will be joined with an `AND (<second condition>)`. It's really syntaxical sugar, but I feel like its a neat little time saver and the function call defines the intent. 

What do you think @niden, @ruudboon ?

**Comment by niden** [comment]
Well it kind of defeats the `findBy<field>`  objective. If you have more than one field you can use `find` and since you are defining `conditions` in your array, then one more (for the `by`) does not use much time. This is why I did not add more into this.
