### ISSUE TITLE
[BUG]: Cache adapter getKeys does not return only the prefixed keys

### ISSUE THREAD

**Issue by duongkhoangiam** [phalcon/cphalcon#14575]
This function very helpful
Example i have 3 cache key
result-post-all.hash
result-post-1.hash
result-post-2.hash

when i edited post with id = 1
i need only delete 2 key
result-post-all.hash
result-post-1.hash

this maybe make best performance ?

**Comment by niden** [comment]
In v4 you can get the keys from the adapter itself

```
$keys = $cache->getAdapter()->getKeys();
```

**Comment by duongkhoangiam** [comment]
yes , but it's return all keys

**Comment by niden** [comment]
Are you talking about only the prefixed keys? or all keys?

**Comment by duongkhoangiam** [comment]
prefixed keys.

**Comment by niden** [comment]
OK I see the issue. The APCu does take into account the prefixed keys, others do not. This is a bug.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14582

**Comment by duongkhoangiam** [comment]
how to get queryKeys with prefix ?
this is function in phalcon 3.x
when queryKeys with prefix only return the cache key match
```php
$cache->save("users-ids", [1, 2, 3]);
$cache->save("projects-ids", [4, 5, 6]);

var_dump($cache->queryKeys("users")); // ["users-ids"]
```

iam tried to using getKeys
```php
$cache->set("users-ids", [1, 2, 3]);
$cache->set("projects-ids", [4, 5, 6]);

var_dump($cache->getKeys("users")); all keys 
```
return all keys

**Comment by ruudboon** [comment]
@niden Can you have a look at @duongkhoangiam feedback?

**Comment by niden** [comment]
For v4 the method is `getKeys` in the adapter. There is no option for now to get the keys that are prefixed with something. 

I will switch this to a NFR and see if we can squeeze this in.

**Comment by niden** [comment]
Implemented in https://github.com/phalcon/cphalcon/pull/14618
