### ISSUE TITLE
[BUG]: Missing parameters in Collection v4.0

### ISSUE THREAD

**Issue by jenovateurs** [phalcon/cphalcon#14583]
Hi,
I used Phalcon v4.0.0-rc.3.
I tried to use Collection. I read the documentation about it and there are some errors of parameters.
I don't know if it's an error in Phalcon or in the documentation.

In the documentation:
```
public function get(
    string $element, 
    mixed $defaultValue = null, 
    bool $insensitive = true, 
    string $cast = null
):  mixed
```
But in the last version of Phalcon it's:
```
    public function get(
        string element,
        var defaultValue = null,
        string! cast = null
    )
```
The parameter insensitive don't exist.

Same things with function has. In documentation:
`public function has(string $element, bool $insensitive = true):  bool`
In Phalcon:
`public function has(string element) -> bool`

Same things with remove. In documentation:
`public function remove(string $element, bool $insensitive = true):  void`
In Phalcon:
`public function remove(string element) -> void`

**Comment by niden** [comment]
Source code is the winner. Need to update the docs.

**Comment by niden** [comment]
This has been addressed 

https://github.com/phalcon/docs/commit/85c56f0a084e7719a50460850f145d37b14c29b7
https://github.com/phalcon/docs/commit/bcb8754763de97ec4f603ead56cdd14febf89ea2
