### ISSUE TITLE
[BUG]: V4 Str::decrement doesn't exist

### ISSUE THREAD

**Issue by jenovateurs** [phalcon/cphalcon#14599]
Hi !

Which is right: Documentation or Source code ?
There is an increment function but not decrement. Is it normal ?

Thanks

**Comment by ruudboon** [comment]
@jenovateurs docs are correct. There isn't a decrement. I think this method is ment for generating for example a new filename when the original already exists. Like when copying files to a dir. If file already exists sometime the os will create filename_1.jpg filename_2.jpg. 
Probably you don't need decrement. But if you got a good use case where this can be helpful you can change the issue in an NFR.

See source.
https://github.com/phalcon/cphalcon/blob/master/phalcon/Helper/Str.zep#L368

**Comment by jenovateurs** [comment]
@ruudboon I haven't got a good use case, I just tested elements in the documentation.
And I found this section in the documentation: https://docs.phalcon.io/4.0/en/helper#decrement.

**Comment by ruudboon** [comment]
@jenovateurs Sorry. And I need some more coffee on Sunday morning ;)
Let's file it as a bug and add this.

**Comment by jenovateurs** [comment]
@ruudboon no problem :-)

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/pull/14601
