### ISSUE TITLE
[BUG]: GD error under PHP 7.4

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14609]
Under PHP 7.4 out unit test fails.
```
imagecolorallocatealpha(): Alpha component is out of range
```
https://travis-ci.org/ruudboon/cphalcon/jobs/623171082

**Details**
 - Phalcon version: Phalcon 4.x branch
 - PHP Version: PHP 7.4

**Comment by niden** [comment]
Resolved
