### ISSUE TITLE
[BUG]: Http\Response can't setCookies

### ISSUE THREAD

**Issue by jenovateurs** [phalcon/cphalcon#14602]
The function setCookies needs an object which implements Phalcon\Http\Response\CookiesInterface. 
https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Http/Response.zep
This interface doesn't exist, Cookie without the s exists.
If I'm right, I think that the function setCookies should be renamed to setCookie.

**Comment by jenovateurs** [comment]
I discovered this bug because I was creating the test. So if you correct this bug, can I pull request my test ?

**Comment by niden** [comment]
Create the pr with the test that fails. We merge iy then fix the code so that test passes

-------- Original Message --------

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14604

Thank you @jenovateurs
