### ISSUE TITLE
not able to install phalcon ubuntu 19.10 with php7

### ISSUE THREAD

**Issue by urfusion** [phalcon/cphalcon#14613]
I am trying to install `phalcon` on `ubuntu 19.10` where php version is `php7.3`, `php7.1` and `php7.0`. 

When I try to install `php-phalcon` 

> sudo apt-get install php7.0-phalcon

> Reading package lists... Done

> Building dependency tree   
     Reading state information... Done 

>E: Unable to locate package php7.0-phalcon 

>E: Couldn't find any package> by glob 'php7.0-phalcon' 

> E: Couldn't find any package by regex 'php7.0-phalcon'

Same with `php7.1` and `php7.3`

Is there any way to install.

I also tried with `apt-cache search` but same.

**Comment by ruudboon** [comment]
Did you add the repository?
```
curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
``
https://docs.phalcon.io/3.4/en/installation

**Comment by urfusion** [comment]
Yes, Here is the output
```
curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
Detected operating system as Ubuntu/eoan.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/phalcon_stable.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
```
and after that I tried to install `phalcon` with many ways and below is the output of one of those.

`apt install php-phalcon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php-phalcon`

**Comment by ruudboon** [comment]
You need the version as well.
```
apt-get install php7.0-phalcon
```

**Comment by sergeyklay** [comment]
We're not provide support of non-LTS Ubuntu version. At this time supported Ubuntu versions are:
- Ubuntu 14.04 LTS (Trusty)
- Ubuntu 16.04 LTS (Xenial)
- Ubuntu 18.04 LTS (Bionic)


Please compile from source.
