### ISSUE TITLE
[BUG - V4]: Iterator on Collection with sub-array

### ISSUE THREAD

**Issue by jenovateurs** [phalcon/cphalcon#14614]
I tried to use the class Collection like it's written in the documentation : 
https://docs.phalcon.io/4.0/en/collection#iteration
```
$data = [
    'colors' => [
        'red',
        'white',
        'blue',
    ],
    'year'   => 1776,
];

$collection = new Collection($data);

foreach ($collection as $key => $value) {
    echo $key . ' - ' . $value . PHP_EOL;
}
```
But I had an error because the element 'colors' is an array. I don't know if it's a wrong way to show how to iterate a collection in the doc or if we need to do something in the Collection class.

Thanks for your help :-).

**Comment by ruudboon** [comment]
This is a typo in the documentation. Created a pull. The `$value` can be converted to a string since it contains an array.

**Comment by jenovateurs** [comment]
Thanks @ruudboon
