### ISSUE TITLE
[BUG]: Deprecated: The 'compiledPath' option is deprecated. Use 'path' instead.

### ISSUE THREAD

**Issue by bnlambert** [phalcon/cphalcon#14623]
![image](https://user-images.githubusercontent.com/4788731/70853793-4000e080-1eb3-11ea-84e1-039005c9a4e6.png)

That happens when you try to use volt in phalcon v4.0 modules app on win 10

I resolved it by changing `compiledPath` to `path`

I think phalcon devtools should take care of that during app generation

Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste output here
```

**Expected behavior**

```php
// paste code
```

**Screenshots**

**Details**
 - Phalcon version: (`php --ri phalcon`)
 - PHP Version: (`php -v`)
 - Operating System:
 - Installation type: Compiling from source || installing via package manager
 - Zephir version (if any):
 - Server: Nginx | Apache | Other
 - Other related info (Database, table schema):

**Additional context**

**Comment by niden** [comment]
This is not a bug it is intended behavior. The options have been changed for Volt.

I see that the section is not yet there in the upgrade guilde. I will mark this as Docs needed to address the issue.

Thank you for reporting it!

**Comment by niden** [comment]
https://docs.phalcon.io/4.0/en/upgrade

**Comment by Jeckerson** [comment]
https://github.com/phalcon/phalcon-devtools/issues/1395
