### ISSUE TITLE
Minor enhancement for Query Builder

### ISSUE THREAD

**Issue by ekmst** [phalcon/cphalcon#14621]
Now, when calling the `Model:findFirst` method, the following sql queries are generated:

```
Users::findFirst(47);
// SELECT `users`.`id`, `users`.`fields`... FROM `users` WHERE `users`.`id` = 47 LIMIT :APL0
// Array
// (
//     [APL0] => 1
// )


// and 
Users:findFirst(
    [
        'user_id = :uid:',
        'bind' => [
            'uid' => 47,
        ],
    ]
);
// SELECT `users`.`id`, `users`.`fields`... FROM `users` WHERE `users`.`id` = :uid LIMIT :APL0
// Array
// (
//     [uid] => 47
//     [APL0] => 1
// )
```

I suggest in both cases to generate this request, which reduces the likelihood of a possible SQL injection.

```
// SELECT `users`.`id`, `users`.`fields`... FROM `users` WHERE `users`.`id` = :uid LIMIT :APL0
// Array
// (
//     [uid] => 47
//     [APL0] => 1
// )
```

**Details:**
Phalcon Version: `4.0.0`

**Comment by ruudboon** [comment]
@ekmst Have you tried inserting some invalid/injection id? Looking quickly at the code I think it's escaped when building the query. If that's the case we can make this an NFR and move it to 4.1.

**Comment by ekmst** [comment]
@ruudboon 
I personally have no problems with this, because I try to filter input data everywhere.
But if suddenly the wrong data gets there, then injections will take place.

For example:

```php
$uid = '1=1 AND role=\'admin\'';
Users::findFirst($uid);
```
Get the next query and it returns the result:
```
 SELECT `users`.`id`, `users`.`fields...` FROM `users` WHERE 1 = 1 AND `users`.`role` = 'admin' LIMIT :APL0 - Array
(
    [APL0] => 1
)
```

And when you call
```php
$uid = '1=1 AND role=\'admin\'';
Users::findFirst(
    [
        'user_id = :uid:',
        'bind' => [
            'uid' => $uid
        ]
    ]
);
```

Get a request that returns nothing and is correct:
```
SELECT `users`.`id`, `users`.`fields...` FROM `users` WHERE `users`.`user_id` = :uid LIMIT :APL0 - Array
(
    [uid] => 1=1 AND role='admin'
    [APL0] => 1
)
```
