### ISSUE TITLE
ErrorException: setcookie() expects at most 7 parameters, 8 given

### ISSUE THREAD

**Issue by mvanvu** [phalcon/cphalcon#14643]
The issue when I use `(new Phalcon\Debug)->listen(true, true)` and delete a cookie name from CONTROLLER like below
```
if ($this->cookies->has('cms.site.language'))
{
          $this->cookies->delete('cms.site.language');
}
```
It works fine when $lowServerity === false

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14647

Thank you @mvanvu

**Comment by mikacalvo** [comment]
Hello, warning keeps being printed if we do : 
   $cookie = $this->cookies->get('cms.site.language');
   $cookie->delete();

**Comment by niden** [comment]
> Hello, warning keeps being printed if we do :
> 
> ```
> $cookie = $this->cookies->get('cms.site.language');
> $cookie->delete();
> ```

@mikacalvo What version of Phalcon and PHP are you using?

**Comment by mikacalvo** [comment]
I just did the migration PHP 7.4 with Phalcon 4.0. 
In our app's cacheService we were doing a get then a delete, I changed it for a delete with the key as parameter. I reported still the 'bug' just in case

**Comment by BeMySlaveDarlin** [comment]
Checked out on clean installation.
Phalcon v.4.0.x, v.4.1.x.
Cannot reproduce, perhaps fixed already.
