### ISSUE TITLE
[NFR]: Phalcon Changelog Documentation Link

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14642]
Can you please include link to documentation for each feature change/addition in phalcon changelog? [1]

[1] https://github.com/phalcon/cphalcon/releases/tag/v4.0.0

Example:
`` Added Exception storing and getting in the Phalcon\Domain\Payload\* #14575 [(DOC)](https://docs.phalcon.io/4.0/en/api/phalcon_domain) ``

Preview:
Added Exception storing and getting in the Phalcon\Domain\Payload\* #14575 [(DOC)](https://docs.phalcon.io/4.0/en/api/phalcon_domain)

-OR- (Like This, Even Better!)
`` Added Exception storing and getting in the [Phalcon\Domain\Payload\*](https://docs.phalcon.io/4.0/en/api/phalcon_domain) #14575  ``

Preview:
Added Exception storing and getting in the [Phalcon\Domain\Payload\*](https://docs.phalcon.io/4.0/en/api/phalcon_domain) #14575

**Comment by ruudboon** [comment]
Closing this: Please vote for this feature here: https://github.com/phalcon/cphalcon/issues/14608#issuecomment-570157137

**Comment by niden** [comment]
Resolved in d347e97f79
