### ISSUE TITLE
[BUG]: Router getRewriteUri

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/cphalcon#14655]
In Phalcon 4.0.0 stopped exists function "getRewriteUri" in service "Router"

**Comment by ruudboon** [comment]
Related to #14559 
The getRewriteUri() is removed from v4. The superglobal ($_SERVER['REQUEST_URI'] or $_GET['_url']) handeling must now be done outside the framework. See https://docs.phalcon.io/4.0/en/application#overview

**Comment by zak-wojtek77** [comment]
I suggest that this information will be saved here https://docs.phalcon.io/4.0/en/upgrade

**Comment by niden** [comment]
Added https://github.com/phalcon/docs/commit/d82623a4d131b768c245c19c0b62cbb8f90d619e

**Comment by zak-wojtek77** [comment]
Thank you
