### ISSUE TITLE
[BUG]: Phalcon\Plugin

### ISSUE THREAD

**Issue by LearnPhalcon** [phalcon/cphalcon#14660]
``Phalcon\Plugin`` no longer works!? What do I use instead? I also tried ``Phalcon\Mvc\User\Component``

This code worked before;
```php
namespace App\Helper;

use Phalcon\Plugin;

class Test extends Plugin {

  function text($name) {
    return "<h1>$name</h1>";
  }

}
```

I would like to use ``Phalcon\Plugin`` or similar to be able to call things like ``$this->disaptcher->getParam()`` for example in my helper class.

**Comment by Deathamns** [comment]
Try `\Phalcon\Di\Injectable` -  [CHANGELOG-4.0](https://github.com/phalcon/cphalcon/blob/master/CHANGELOG-4.0.md) - [Docs/Upgrade](https://docs.phalcon.io/4.0/en/upgrade)

**Comment by LearnPhalcon** [comment]
@Deathamns Okay, tried... it seems to work but I have one problem.
I can't seem to access ``$this->disaptcher->getParam()`` from this class.

**Comment by Deathamns** [comment]
You didn't show your full code. Somewhere you have to attach a dependency injector container as well.
If you haven't, then in your example you could:

```php
$di = new \Phalcon\Di\FactoryDefault;
$test = new Test();
$test->setDi($di);

// or simply do this (it seems that it will use as default)
$di = new \Phalcon\Di\FactoryDefault;

echo $test->text('hello');
```

**Comment by LearnPhalcon** [comment]
So why I can access ``$this->dispatcher->getParam()`` from my controllers but not from inside my helper classes? What is the point of ``extending ``Phalcon\DI\Injectable`` if I can't use disaptcher directly like that?

**Comment by LearnPhalcon** [comment]
This worked for me, but I have to use this in every function like this;

```php
function test($text) {
  $di = \Phalcon\DI::getDefault();
  $dp = $di['dispatcher'];
  $test = $dp->getParam('test');
  return "<h1>$text - $test</h1>";
}
```

Is there  a way to use this globally like I do inside my controllers?

**Comment by Deathamns** [comment]
I've made libraries and in those I don't have to use `setDI`, so there is something else on your end.
Have you properly registered the namespaces (just guessing)?

**Comment by LearnPhalcon** [comment]
This is how I have my dispatcher in bootstrap file.

```php
$di->set('dispatcher', function() {
	$dp = new Dispatcher();
	$dp->setControllerSuffix('');
	$dp->setActionSuffix('');
	$dp->setDefaultNamespace('App\Controller');
	return $dp;
});
```

**Comment by ruudboon** [comment]
@LearnPhalcon this looks good.
If you need service from you DI in you closure you can pass it in.
```
$di->set('dispatcher', function() use ($di) {
        // $service = $di->getShared('someService');
	$dp = new Dispatcher();
	$dp->setControllerSuffix('');
	$dp->setActionSuffix('');
	$dp->setDefaultNamespace('App\Controller');
	return $dp;
});
```

**Comment by LearnPhalcon** [comment]
@ruudboon I tried this just now and it gives me "Error 502 - Bad Gateway" in log I see (104: Connection reset by peer).

```php
$di->set('dispatcher', function() use ($di) {
	$sdp = $di->getShared('dispatcher');
	$dp = new Dispatcher();
	$dp->setControllerSuffix('');
	$dp->setActionSuffix('');
	$dp->setDefaultNamespace('App\Controller');
	return $dp;
});
```

Then I called ``$sdp->getParam()`` inside my helper class.

**Comment by ruudboon** [comment]
```
$sdp = $di->getShared('dispatcher');
```
Probably your dispatcher doesn't exist in your di.
I don't think this is a bug, can we close this and help you out on discord or the forum?
