### ISSUE TITLE
[BUG]: Installation from Sources problem

### ISSUE THREAD

**Issue by nauhein** [phalcon/cphalcon#14665]
git clone -b v4.0.0 https://github.com/phalcon/cphalcon.git
cd cphalcon/build
sudo ./install
then have error:
./install: line 59: --version: command not found
php-config is not installed
my linux is centos phpversion is php7.2
 
How to fix it

**Comment by nauhein** [comment]
then  i 
cd cphalcon/build/php7/64bits /
export CFLAGS="-O2 --fvisibility=hidden"
./configure --enable-phalcon
make && sudo make install
still has a error

configure: error: in `/data/soft/cphalcon/build/php7/64bits':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by niden** [comment]
You can install it from packagist using your package manager as outlined here:

https://docs.phalcon.io/4.0/en/installation#linux

If you want to build it from source (as you show in your code) you need to have certain packages already installed in your system. These are:
- PHP development sources (usually `php-dev`, contains `phpize` for instance)
- GCC compiler
- re2c
- libpcre-dev

Once you have those then you can follow the instructions here:

https://docs.phalcon.io/4.0/en/installation#compile-from-sources

Please note: Phalcon v4 **requires** that the PSR extension is installed in your system (`php-psr` usually in package managers).

The installation document https://docs.phalcon.io/4.0/en/installation has a lot more information.

Let us know how it goes.

**Comment by nauhein** [comment]
thinks
