### ISSUE TITLE
[BUG-v4]: can't delete cookie

### ISSUE THREAD

**Issue by jenovateurs** [phalcon/cphalcon#14667]
Hi, 

With v4, I created a cookie:
```
$sNameCookie = 'user_name';
$this->cookies->set(
      $sNameCookie,
      'Franck',
      time() + 86400
);
$this->cookies->send();
```
Then, I tried to delete the cookie by doing:
 ```
$sNameCookie = $this->cookies->get('user_name');

$sNameCookie->delete();
```
But since the cookie still existed, I also tried this:
`$this->cookies->delete('user_name');`
It still doesn't work...

Thanks for your help :-)

**Comment by ruudboon** [comment]
I think this already fixed in https://github.com/phalcon/cphalcon/issues/14643

**Comment by ruudboon** [comment]
@jenovateurs If possible can you check the 4.0.x branch? Feel free to reopen if needed

**Comment by jenovateurs** [comment]
@ruudboon No problem, I will ckeck it, thanks for your help.

**Comment by jenovateurs** [comment]
@ruudboon Indeed, it works with the 4.0.x branch.

**Comment by ruudboon** [comment]
@jenovateurs thnx for confirming. Will be part of the 4.0.1 release (jan 2020)
