### ISSUE TITLE
[BUG]:  Can't read session vars provided by another app 

### ISSUE THREAD

**Issue by oleghind** [phalcon/cphalcon#14688]
I am trying to read session vars provided by another app, but phalcon always adds "#" prefix while reading values from $_SESSION although I did not set any unique id.

I think "getUniqueKey" function of Manager.zep should only add "#" if uniqueId is not empty

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14689

@oleghind thanks for reporting this
