### ISSUE TITLE
[NFR]: Make Request not rely on superglobals

### ISSUE THREAD

**Issue by alexbusu** [phalcon/cphalcon#14706]
**Is your feature request related to a problem? Please describe.**
Nowadays the PHP async approach is getting traction, and I've considered to test Phalcon based app using this approach (I guess I'm not the only one). To do this, there's a list of _constraints_, one of which is "do not use/rely on global variables" for an HTTP request.

**Describe the solution you'd like**
As a solution, I see the option of setting the HTTP data in protected fields, initialized in constructor (the data being fed as arguments (optional parameters)). The globals usage in class methods would be replaced by the newly added fields.
To keep BC for default Di container one could initialize the Request class by calling a static helper method that would _collect_ data from globals and the use to initialize and return a new class instance. E.g.
```php
$di->setShared('request', function () {
    return Request::createFromGlobals();
});
```

**Describe alternatives you've considered**
An alternative is the Symfony's HttpFoundation component, for example, the `Symfony\Component\HttpFoundation\Request` class. There's a [method that creates the request object from globals](https://github.com/symfony/http-foundation/blob/v5.0.2/Request.php#L283), as described above.

**Additional context**
\-

**Comment by niden** [comment]
@alexbusu This is the direction we are moving to. The whole HTTP layer needs to be rewritten so as to use PSR-7 compatible requests, responses etc.

There is a component already available here:

https://github.com/phalcon/cphalcon/blob/master/phalcon/Http/Message/ServerRequest.zep#L115

that you can use to inject superglobals. There will be quite a bit of work on you to make it work but we are getting there. 

Related NFRs: #14390 #12485

**Comment by alexbusu** [comment]
That looks nice; thanks for pointing it!
