### ISSUE TITLE
Windows 10, latest XAMPP with PHP 7.4.1 [BUG]: 

### ISSUE THREAD

**Issue by mpotoc** [phalcon/cphalcon#14707]
Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**
I have Windows 10 development station with latest XAMPP (PHP 7.4.1), and when i download latest dll for Phalcon 4.0.2, it is not working. It does not load the library. I have put in php.ini extension=php_phalcon.dll. When i tried with latest XAMPP (PHP 7.3.13) it also does not work, but on this version works Phalcon 3.4.5.

So am i missing some libraries that need to be enabled (there is nothing in the docs), or what is the problem?

Help please, we use Phalcon regularly. 

It works great on my Ubuntu 18.04.3 with PHP 7.3.13 and Phalcon 4.0.2, but i also need it to work on windows workstation.

Thanks

**Comment by ruudboon** [comment]
Did you installed PSR?

https://docs.phalcon.io/4.0/en/installation

**Comment by mpotoc** [comment]
no, you're right i forgot about that

**Comment by ruudboon** [comment]
Ok closing this assuming install PSR will solve your issue.
