### ISSUE TITLE
Volt, PHP7.4, join

### ISSUE THREAD

**Issue by Deathamns** [phalcon/cphalcon#14711]
This is filling my logs recently with PHP 7.4 (nothing serious, just something to address sometimes):
> PHP deprecated   join(): Passing glue string after array is deprecated. Swap the parameters

https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
https://www.php.net/manual/en/function.implode.php

Volt
```
{{ [1, 2]|join(',') }}
```

Generated PHP
```php
<?= join([1, 2], ',') ?>
```

**Comment by ruudboon** [comment]
Fixed. Will be part of the 4.0.3 release. Thnx for reporting @Deathamns

**Comment by niden** [comment]
https://github.com/phalcon/cphalcon/pull/14712
