### ISSUE TITLE
[BUG]: Session Redis Adapter Wrong number of parameters

### ISSUE THREAD

**Issue by duongkhoangiam** [phalcon/cphalcon#14724]
**Describe the bug**
Session Redis Wrong number of parameters

```php
<?php

use Phalcon\Session\Manager;
use Phalcon\Storage\AdapterFactory;
use Phalcon\Session\Adapter\Redis;

$options = [
    'host'  => '127.0.0.1',
    'port'  => 6379,
    'index' => '1',
];

$session = new Manager();
$factory = new AdapterFactory();
$redis   = new Redis($factory, $options);

$session
    ->setAdapter($redis)
    ->start();
```

> Provide minimal script to reproduce the issue

```php
Error : Wrong number of parameters
```

**Details**
 - Phalcon version: 4.0.2
 - PHP Version: 7.3.7
 - Operating System: Mac Os catalina
 - Server: Nginx
 - Redis: 4.1.1

**Comment by ruudboon** [comment]
You're missing your serialiser. https://docs.phalcon.io/4.0/en/api/phalcon_storage#methods-7
```
<?php


use Phalcon\Session\Manager;
use Phalcon\Storage\AdapterFactory;
use Phalcon\Session\Adapter\Redis;
use Phalcon\Storage\SerializerFactory;

$options = [
    'host' => '127.0.0.1',
    'port' => 6379,
    'index' => '1',
];

$session = new Manager();
$serializer = new SerializerFactory();
$factory = new AdapterFactory($serializer);
$redis = new Redis($factory, $options);

$session
    ->setAdapter($redis)
    ->start();

```

**Comment by duongkhoangiam** [comment]
Yes working , so need edit document in phalcon.io
https://docs.phalcon.io/4.0/en/session#redis

**Comment by janisbiz** [comment]
@duongkhoangiam I would recommend you to use https://github.com/phalcon/ide-stubs, as it will save you quite a lot of time regarding reading docs.

**Comment by janisbiz** [comment]
@duongkhoangiam I would recommend you to use https://github.com/phalcon/ide-stubs, as it will save you quite a lot of time regarding reading docs.

**Comment by niden** [comment]
I added the relevant section in the docs. Thanks @duongkhoangiam for pointing this out.
