### ISSUE TITLE
[NFR]: Concern regarding strict return types on core classes

### ISSUE THREAD

**Issue by janisbiz** [phalcon/cphalcon#14741]
> Before we start discussing - this supposedly is not a concern on php 7.4

**Is your feature request related to a problem? Please describe.**
Currently there are quite a lot of classes returning either strict types of "self", e.g. full class name or an interface it implements. This is not good practice in case of extendable software, as it makes almost impossible to overwrite the class in clear way - proper return types. (example could be https://github.com/phalcon/cphalcon/blob/master/phalcon/Acl/Adapter/AbstractAdapter.zep#L75, if I extend this class with my abstract, which then has its own `ManagerInterface`, extented from base managers interface, I cannot override it, or even return the object due to strict return type)

**Describe the solution you'd like**
Avoid doing strict return types on classes, as it will allow developers to extend core in every way they want (e.g. case of a bug, and need to override methods)

**Describe alternatives you've considered**
Up to discuss.

**Additional context**
Not applicable.

**Comment by Jeckerson** [comment]
Well, in your case, you need to extend not only `AbstractAdapter`, but also `ManagerInterface` interface. And inside your extended `AbstractAdapter` use your own interface as return type.

**Comment by janisbiz** [comment]
Sure, but you cannot override the return type of ‘ManagerInterface’ with e.g. ‘MyManagerInterface’ which implememts ‘ManagerInterface’.

**Comment by ruudboon** [comment]
But you will be able to return `MyManagerInterface` since it returns the `ManagerInterface` due to Covariance. See php docs as well. https://www.php.net/manual/en/language.oop5.variance.php

**Comment by janisbiz** [comment]
@ruudboon as I mentioned at the beginning of my NFR, I quote myself:
> Before we start discussing - this supposedly is not a concern on php 7.4

**Comment by ruudboon** [comment]
@janisbiz Sorry. I still don't understand the issue.

Something like this will work in 7.2, 7.3
```php
<?php
    class MyInterface extends \Phalcon\Events\Event {

    }

    class MyAdapter extends Phalcon\Acl\Adapter\Memory {

        public function getEventsManager(): \Phalcon\Events\ManagerInterface
        {
            return new MyInterface();
        }
    }

    new MyAdapter();
```
 Can you give us a code example that illustrates your problem?

**Comment by janisbiz** [comment]
@ruudboon by taking your example and updating it a little bit, this will not work:
```
<?php

interface MyManagerInterface extends \Phalcon\Events\ManagerInterface {
    public function myFunction();
}

class MyEventsManager implements MyManagerInterface {
    public function myFunction() {}

    public function detach(string $eventType, $handler) {}

    public function detachAll(string $type = null) {}

    public function hasListeners(string $type): bool { return false; }

    public function fire(string $eventType, $source, $data = null, bool $cancelable = true) {}

    public function attach(string $eventType, $handler) {}

    public function getListeners(string $type): array { return []; }
}

class MyAdapter extends Phalcon\Acl\Adapter\Memory {
    public function getEventsManager(): MyManagerInterface
    {
        return new MyEventsManager();
    }
}

new MyAdapter();
```

So, if you look at the code - `MyManagerInterface` is compatible with `\Phalcon\Events\ManagerInterface`, but due to typehint of `public function getEventsManager()` it is not possible to override it.

**Comment by ruudboon** [comment]
But you can just keep using the interface and return `MyEventsManager` object.
```
public function getEventsManager(): \Phalcon\Events\ManagerInterface
    {
        return new MyEventsManager();
    }
```
If you want to make it stricter by forcing a `MyManagerInterface` you need to be on 7.4. But you can return your own implementation as long as you make sure the interfaces is implemented.
You can always add an extra check inside your method to check the type of object but it will come with some extra performance cost. Something we don't want as default in the framework when we have a fast solution using strict returns.

**Comment by janisbiz** [comment]
I know that I can keep returning the `\Phalcon\Events\ManagerInterface`, but the problem is really critical, when starting to implement stuff, which requires specific interface injection as a return instead of predefined one from framework thus causing issues/bugs by satisfying an injection from core interface even though it should be something else. And it gets worse in some places, as it is not returning an interface, but a strict class instead.

Sure, you don't want to do that, but from my perspective, as a framework user it had caused problems. If I could upgrade my application to 7.4, then there would be no problem. But at the same time - if Phalcon is stating a support for 7.2 and 7.3, it should not limit possibility to extend/override core parts. That's the main reason, why even frameworks like Symfony are not implementing strict return types of interfaces/classes.

**Comment by janisbiz** [comment]
Anyaway - closing this, as probably I am the only one having this problem...
