### ISSUE TITLE
Phalcon 2.0.0 migration

### ISSUE THREAD

**Issue by phalcon** [phalcon/cphalcon#1474]
Hey Guys, 

We're migrating the code from 1.3 to 2.0. Migrating to Zephir will make the code base more maintainable and readable, allowing us to easily add more features and release more features soon and better. By introducing Zephir, we are taking the opportunity to do something unprecedented in the PHP world, a chance to do something revolutionary as Phalcon is.

Current Status
---------------------
We now have about a 70% of the expected functionality implemented in Zephir, (very sure it is not perfect) but this does not stop us to continue migrating the code from 1.3 to 2.0. 

If you are reading this and have experience with Phalcon Internals, please help us to finish the migration and keep 1.3 and 2.0 in sync, so we could release a 2.0.0 that implement the same functionality as 1.x. We need more hands to make his happen!

2.0.0 branch
https://github.com/phalcon/cphalcon/tree/2.0.0

This directory contains a lot of examples on how to write Zephir code:
https://github.com/phalcon/cphalcon/tree/2.0.0/phalcon

This page contains the 2.0.0 evolution:
https://github.com/phalcon/cphalcon/wiki/Progress-2.0

Thank you!

cc: // @sjinks @dreamsxin @Cinderella-Man @carvajaldiazeduar @andresgutierrez @niden @xboston

This issue will be closed when we complete the migration.

**Comment by andresgutierrez** [comment]
Release is scheduled to April 17th, 2015
