### ISSUE TITLE
[BUG]: ph 4.x, phalcon/Mvc/Model/Binder cache problem

### ISSUE THREAD

**Issue by AdamWawrzynowski** [phalcon/cphalcon#14743]
**Describe the bug**
While using phalcon/Mvc/Model/Binder with cache enabled, we receive an error, because Binder still uses removed methods (exists() and save()), which are not available in AdapterInterface

```php
$serializer = new \Phalcon\Storage\SerializerFactory();
$dispatcher->setModelBinder(new \Phalcon\Mvc\Model\Binder(), new \Phalcon\Cache\Adapter\Apcu($serializer));
```

**First Error**
> 'message' => string 'Call to undefined method Phalcon\Cache\Adapter\Apcu::exists()'
> 'function' => string 'getParamsFromCache'
> 'class' => string 'Phalcon\Mvc\Model\Binder'
https://github.com/phalcon/cphalcon/blob/ef31ca8fdfdcbaeef24bd93a32107a43b6c1ba6b/phalcon/Mvc/Model/Binder.zep#L124

**Second Error**
> 'message' => string 'Call to undefined method Phalcon\Cache\Adapter\Apcu::save()'
> 'function' => string 'getParamsFromCache'
> 'class' => string 'Phalcon\Mvc\Model\Binder'
https://github.com/phalcon/cphalcon/blob/ef31ca8fdfdcbaeef24bd93a32107a43b6c1ba6b/phalcon/Mvc/Model/Binder.zep#L216

**Working Quick Fix with Apcu**
```php
class Apcu extends \Phalcon\Cache\Adapter\Apcu
{    
    public function exists($key)
    {
        return $this->has($key);
    }
    
    public function save(string $key, $value, $ttl = null)
    {
        return $this->set($key, $value, $ttl);
    }
}
```

Renaming method exists() to has() and save() to set() inside /Mvc/Model/Binder should solve the problem.

**Details**
 - Phalcon version: 4.0.0
 - PHP Version: 7.2
 - Operating System: Windows 10
 - Server: Apache

**Comment by Jurigag** [comment]
Thanks for this, yea obvious fix for next release.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14747

Thank you @AdamWawrzynowski
