### ISSUE TITLE
[BUG]: Unable to remove files create by storage adapter under windows.

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14753]
Our windows tests related to storing files using our stream adapter are currently failing.

https://github.com/phalcon/cphalcon/runs/402909157#step:27:346

Looks like the file isn't closed after writing. Need to be investigated on a windows machine. 
Could be Phalcon or unit test/codeception related.

**Comment by harm-smits** [comment]
I will see what I can find on Windows

**Comment by ruudboon** [comment]
@harm-smits thnx. You can use this branch https://github.com/phalcon/cphalcon/tree/4.0.x-ci-and-tests
We've update Codeception in that branch as well so please make sure you run composer. 
Running `vendor/bin/codecept run unit` should show the issues. Any PR could be targeted to this branch as well.

**Comment by sergeyklay** [comment]
@ruudboon Could you please cherry pick codeception to the 4.0.x branch? So that we'll have only CI integration in the `4.0.x-ci-and-tests` branch. Another advantage of this approach is to not block the rest of the changes  by one single.

**Comment by ruudboon** [comment]
@sergeyklay It will involve some CI changes regarding env and db import as well. I'm not sure if we can easily separate this.

**Comment by ruudboon** [comment]
We forgot to close the adapter in our tests. Fixed now
