### ISSUE TITLE
[BUG]: ConfigFactory::Load() fails if path contains dot

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14756]
If the path contains a dot the extension will not be added.

https://github.com/phalcon/cphalcon/runs/403253837#step:12:74

Expecting bug here: https://github.com/phalcon/cphalcon/blob/master/phalcon/Config/ConfigFactory.zep#L104

Phalcon 4.0.2
Php: any

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14757#event-2972673742
