### ISSUE TITLE
[BUG]: Phalcon\Translate\Adapter\Gettext:setLocale doesn't allow multiple locales

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14764]
In our [docs](https://github.com/phalcon/cphalcon/blob/master/phalcon/Translate/Adapter/Gettext.zep#L207) we mention that `setLocale` in `Phalcon\Translate\Adapter\Gettext` allows multiple arguments just like the native [setLocale](https://www.php.net/manual/en/function.setlocale.php) 

The logic to handle this is [there](https://github.com/phalcon/cphalcon/blob/master/phalcon/Translate/Adapter/Gettext.zep#L212) but our method doesn't allow it and will return a `wrong number of parameters`.

Phalcon: 4.0.2
Php: 7.4

**Comment by niden** [comment]
Doesn't the `func_get_args()` offer it or is this coming from the method signature?

**Comment by ruudboon** [comment]
@niden That's what I meant. I think the implementation is there but we are unable to do:
```
$gettextObject->setLocale(LC_ALL, "de_DE@euro", "de_DE", "de", "ge");
``` 
Only this allowed:
```
$gettextObject->setLocale(LC_ALL, "de_DE@euro");
```

**Comment by niden** [comment]
We will probably need to remove the parameters from the signature so that `func_get_args` can work. I will need to test this

**Comment by ruudboon** [comment]
@niden Maybe we should be fully compatible as well. Second argument can hold an array as well.

**Comment by niden** [comment]
This will have to be moved to 4,1 or 5.0. 

If we move it to 4.1 we can create a second method (`setLocaleNative` or something like that), that will have no parameters but will use `function_get_args` to get everything passed in the `setlocale`.

Alternatively, wait for v5 when we can change the method signature

**Comment by niden** [comment]
Moved to 4.1 to introduce temporarily a new method that will allow this functionality. We can clean things up with v5

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15454
