### ISSUE TITLE
[NFR]: Integrate PSR into Phalcon as module

### ISSUE THREAD

**Issue by diplopito** [phalcon/cphalcon#14767]
Since Phalcon is depending now on PSR and PSR is already a mature library written in C, could it be possible to integrate it as an extra module in Phalcon using Zephir? In this way the installation should be more transparent and, in a way, the dependency would be gone.

**Comment by niden** [comment]
Actually this is not feasible. You cannot create one extension with two namespaces. The only way this could work would be if we have two projects, one to create the PSR extension and one the Phalcon one.

Then we will add the `psr.so` in the `php.ini` before we do the `phalcon.so` one. 

If we are to build 2 extensions with one build command we are pretty much replicating what is already available i.e. install psr from PECL for instance and then the Phalcon extension.
