### ISSUE TITLE
getJsonRawBody throws an exception instead of a boolean value as in 3.4

### ISSUE THREAD

**Issue by chelipf** [phalcon/cphalcon#14765]
It seems that now getJsonRawBody uses the new \Phalcon\Helper\Json that makes my old code crash because it throws a json_decode exception:

> json_decode error: Syntax error

In version 3.4.5 it just returned a boolean value.

The 4.0 doc says:

> public function getJsonRawBody( bool $associative = bool ): \stdClass | array | bool;
> 
> Gets decoded JSON HTTP raw request body

No problem, I could just catch the exception but the question is, Should this be the new behavior?

**Comment by Jurigag** [comment]
Yes, that was one of changes in 4.0 as I checked in code, I guess we should maybe update return values because it's much better to just return exception.

**Comment by niden** [comment]
This has been addressed here: https://github.com/phalcon/cphalcon/issues/14936
