### ISSUE TITLE
[NFR]: Integration Suite Rework

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#14779]
- Check all tables created by the integration suite
- Remove any data from the dump files
    - adjust tests accordingly
- Enable auto reloading of the schema from Codeception
- Utilize `_envs` folder and configs to run tests on each RDBMS
- Ensure that each test can run independent of any other

Nice to have - integrate it with GitHub actions

**Comment by ruudboon** [comment]
Preferable we merge this after https://github.com/phalcon/cphalcon/issues/14775 or merge it to that branch

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14803
