### ISSUE TITLE
[NFR]: Global variable for reusable in ORM 

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/cphalcon#14788]
In every model every relationship does not use cache. If I want to use cache I have to write 'reusable' => true:
```php
$this->hasOne(
            'inv_cst_id',
            Customers::class,
            'cst_id',
            [
                'alias'    => 'customers',
                'reusable' => true,
            ]
        );
```
My proposal: add new global option:
phalcon..orm.reusable = false
if I don't write in relationship  "'reusable' => true" but I write
phalcon..orm.reusable = true
then will be the same like I write "'reusable' => true".

Priority of global variable would be less than option "reusable" written in relationship.

**Comment by TimurFlush** [comment]
The offer is good, but dangerous

**Comment by zak-wojtek77** [comment]
why dangerous?

**Comment by TimurFlush** [comment]
@zak-wojtek77 A very large amount of data from the DBMS may get into the cache. If you do this thing, you should turn it off by default.

**Comment by niden** [comment]
I agree with @TimurFlush. This can be abused if set to `true` by default.

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/cphalcon/issues/14608

Please vote for this feature there

**Comment by zak-wojtek77** [comment]
> I agree with @TimurFlush. This can be abused if set to `true` by default.

Of course by default it should be 'false'.
