### ISSUE TITLE
[NFR]: Add a method that describes an exception to HTML format

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#14794]
Hello!

The `Phalcon\Debug` class now generates an HTML view with every new exception.

My idea is to add public method `renderHtml(\Throwable $ex): string`.
That is, the class work will not change, but developers can use this method in their solutions to generate HTML representation as a string.
For example, the developer does not want to use the standard mechanism of catching exceptions which provides Phalcon, and wants just to receive HTML representation from this mechanism as a string.

Thanks.
I'm waiting for feedback.

**Comment by TimurFlush** [comment]
I created a new method `renderHtml()` in the `Phalcon\Debug` class.
I just tested it, and it's working fine.
Can I create a Pull Request?

@niden Please see

**Comment by Jurigag** [comment]
Feel free to always create PR if you want, you don't have to ask for permission @TimurFlush :)

**Comment by niden** [comment]
Thank you @TimurFlush 

Resolved in https://github.com/phalcon/cphalcon/pull/14812

**Comment by TimurFlush** [comment]
> Thank you @TimurFlush
> 
> Resolved in #14812

And you (:
