### ISSUE TITLE
[BUG]: $this->security->checkToken second param by default don't get requestToken

### ISSUE THREAD

**Issue by programenot** [phalcon/cphalcon#14795]
**Describe the bug**
in method:
`$this->security->checkToken() ` second param by default don't get requestToken from post request
but ` $this->security->requestTokent()` is exist and code:
`$this->security->checkToken($this->security->getTokenKey(), $this->security->getRequestTokent())`

is working

**Details**
 - Phalcon version: 4.0.3
 - PHP Version: 7.3.14
 - Operating System: CentOS 7
 - Installation type: installing via package manager
 - Zephir version (if any):
 - Server: Nginx | Apache

**Comment by ruudboon** [comment]
Will have a look at this

**Comment by ruudboon** [comment]
@programenot I'm looking into this but not exactly sure what you mean. Are you trying to set only the token key and expecting that security get the value from you post like this:
```
$this->security->checkToken($this->security->getTokenKey()) 
```

**Comment by ruudboon** [comment]
I'm sorry, I tried a few methods of retrieving but unable to reproduce your issue.
@programenot can you have look at this test to see if we missed a case that applies to your issue? 
https://github.com/phalcon/cphalcon/blob/master/tests/unit/Security/CheckTokenCest.php#L57

**Comment by ruudboon** [comment]
Closing this to the lack of response and unable to reproduce. Feel free to reopen if some new info is available.
