### ISSUE TITLE
[NFR]: Add a global suffix to URL

### ISSUE THREAD

**Issue by palcoder** [phalcon/cphalcon#14806]
Hello,

I think URL the class should have a method to add a global suffix to the URLs it generate. For example: we running an old system that should keep the suffix (.html) in the URL and we have to add it through controllers but if we implement this method it will allow us to add/remove the global suffix based on the app config.

Currently, we make a workaround by extending the URL class:

`
    private $suffix;

    public function get($uri = null, $args = null, bool $local = null, $baseUri = null): string
    {
        return parent::get($uri, $args, $local, $baseUri) . $this->suffix;
    }

    public function getSuffix(): string
    {
        return $this->suffix;
    }

    public function setSuffix(string $suffix)
    {
        $this->suffix = $suffix;
    }

    public function removeSuffix()
    {
        $this->setSuffix(null);
    }
`

Also, it would be good to allow to override the staticBaseUri in the method getStatic by passing it as a second parameter which will allow us to easily change the base URI for some of the assets without the need to change the global config.

**Comment by ruudboon** [comment]
Closing this in favour of https://github.com/phalcon/cphalcon/issues/14608#issuecomment-581779401
