### ISSUE TITLE
[BUG]: $config = $di->getConfig(); 502 bad gateway

### ISSUE THREAD

**Issue by zihjielitw** [phalcon/cphalcon#14807]
Hi 

I found $config = $di->getConfig();  make PHP 502 bad gateway.

My system environment is:

PHP : 7.3.14
Phalcon: 4.0.3
OS: CentOS 8

**Comment by Jurigag** [comment]
Most likely it means seg fault, can you add stacktrace from gdb?

**Comment by ruudboon** [comment]
@zihjielitw Please check you have all dependencies installed as well. Maybe something like mbstring is missing. https://docs.phalcon.io/4.0/en/installation#software

**Comment by zihjielitw** [comment]
@ruudboon Thank you for your tips. Saving my times. I was lost mbstring module.
