### ISSUE TITLE
[NFR]: Implement additional methods in class \Phalcon\Helper\Arr.

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#14801]
Hello!

In my opinion, the `Phalcon\Helper\Arr` helper lacks two important methods:
1. `Phalcon\Helper\Arr::blackList()` - is a method that removes the specified keys from the passed array. In its own way it is the opposite copy of the `Arr::whiteList()`

2. `Phalcon\Helper\App::map()`- is the alias of `\array_map()`

**P.S I will create PR as soon as i can**

**Comment by ruudboon** [comment]
1. This could be helpful

2. I wouldn't vote for adding a method that is creating an alias only. It will create unnecessary overhead and would advice just to use the native array_map.

 Any additional methods should go to 4.1 release otherwise we break semver.

**Comment by TimurFlush** [comment]
> 1. This could be helpful
> 2. I wouldn't vote for adding a method that is creating an alias only. It will create unnecessary overhead and would advice just to use the native array_map.
> 
> Any additional methods should go to 4.1 release otherwise we break semver.

Then I wonder why there are methods `Arr::chunk()` and `Arr::filter()`?

**Comment by niden** [comment]
`Arr::filter()` was introduced to reduce the common code in the class. As you will see it is used in quite a few methods there so...

**Comment by TimurFlush** [comment]
> `Arr::filter()` was introduced to reduce the common code in the class. As you will see it is used in quite a few methods there so...

Okay

**Comment by TimurFlush** [comment]
Resolved in #14809

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14809

Thank you @TimurFlush
