### ISSUE TITLE
[NFR]: Add method to Mvc/Model/CriteriaInterface

### ISSUE THREAD

**Issue by maxc62** [phalcon/cphalcon#14818]
**Is your feature request related to a problem? Please describe.**
When I create a query, the IDE never shows me the "columns" method

**Describe the solution you'd like**
So I checked the "CriteriaInterface" class, and I don't see this function
So I compared all the functions between "CriteriaInterface" and "Criteria" and found some differences:
```php
public function setDI(<DiInterface> container) -> void
public function getDI() -> <DiInterface>
public function columns(var columns) -> <CriteriaInterface>
public function join(string! model, var conditions = null, var alias = null, var type = null) -> <CriteriaInterface>
public static function fromInput(<DiInterface> container, string! modelName, array! data, string! operator = "AND") -> <CriteriaInterface>
public function createBuilder() -> <BuilderInterface>
```
So I don't know, if we need to add all this functions. I think we need to add "columns" and "join" (even if we have leftJoin and innerJoin)

**Comment by TimurFlush** [comment]
Also you can use 
`
/** @var Phalcon\Mvc\Model\Criteria $criteria`
$criteria = 5;
$criteria->columns(); // IDE will think that it's the Criteria object

**Comment by maxc62** [comment]
Yes, I agree.
But I always use Model::query()->columns();

And method query (Phalcon/Mvc/Model) return CriteriaInterface
```php
query(\Phalcon\Di\DiInterface $container = null): CriteriaInterface
```

**Comment by ruudboon** [comment]
What IDE are you using?

**Comment by maxc62** [comment]
I use Intellij IDEA, with your plugin Phalcon 4 (thanks @ruudboon)
=> https://plugins.jetbrains.com/plugin/12776-phalcon-4-autocomplete
Source Here: 
https://github.com/ruudboon/phpstorm-phalcon-4-autocomplete/blob/master/plugin/src/Phalcon/Mvc/Model/CriteriaInterface.php
Based on Phalcon CriteriaInterface

Today I'm overloading method query in IDEA to return Criteria after query()

This code works
```php
Model::query()
->columns('var2, var3')//return CriteriaInterface
->where('var = :var:')//return CriteriaInterface
->bind([
		'var' => Model::VAR_YES
])//return CriteriaInterface
```

Not this one
```php
Model::query()
->where('var = :var:')//return CriteriaInterface
->bind([
		'var' => Model::VAR_YES
])//return CriteriaInterface
->columns('var2, var3')//Error function not exists
```

**Comment by wmamrak** [comment]
Same on Visual Studio Code.
Also, in ValidationInterface::add first argument's type is string, whereas it can be string or an array.

**Comment by niden** [comment]
Tracked in https://github.com/phalcon/cphalcon/issues/14608
