### ISSUE TITLE
PhalconException: Column type does not support scale parameter

### ISSUE THREAD

**Issue by wxd237** [phalcon/cphalcon#1482]
when i try to find data from a model .
how can i set the model's column 's scale.

the table include int ,double type.

```
    CREATE TABLE `carddatalist` (
  `dataseq` int(11) NOT NULL,
  `data_type` varchar(255) DEFAULT NULL,
  `brclvl` varchar(1) DEFAULT NULL,
  `brc` varchar(8) DEFAULT NULL,
  `desc1` varchar(16) DEFAULT NULL,
  `desc2` varchar(32) DEFAULT NULL,
  `numval` int(11) DEFAULT NULL,
  `amtval` double(21,2) DEFAULT NULL,
  `datatype2` varchar(2) DEFAULT NULL,
  KEY `datalist_idx1` (`dataseq`,`brclvl`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

my model is simple:

```
class  Carddatalist extends \Phalcon\Mvc\Model{
      public function initialize()
    {
         $this->setConnectionService('mysql');
    }

    public function getSource(){
            return "carddatalist";
    }
```

}

i just `Carddatalist:find();` in `IndexController`

PhalconException: Column type does not support scale parameter

i don's know how can i define the scale of column.

**Comment by overbid** [comment]
This happen again in 2.0.0

**Comment by lothern** [comment]
@overbid Yes, I'm experiencing this bug as well with 2.0.0

**Comment by Kelsett** [comment]
Same here with 2.0.0.

**Comment by Green-Cat** [comment]
There is a pull request for 2.0.x to fix this.

**Comment by spuy767** [comment]
If you're comfortable compiling the extension from the .zep, you can add

```
/**
* Float/Smallfloats/Decimals are float
*/
if memstr(columnType, "double") {
        let definition["type"] = Column::TYPE_DOUBLE,
        definition["isNumeric"] = true,
        definition["bindType"] = Column::TYPE_DOUBLE;
        break;
}
```

at line ~197 of phalcon/db/adapter/pdo/mysql.zep until my pull request gets approved.

**Comment by Surt** [comment]
I still have this problem on 2.0.1.

**Comment by kostjantin** [comment]
Version 2.0.2
I have this problem:

I created a table:
CREATE TABLE `razor`.`phalcon_test` (
`id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE(7,2) NULL,
  `agreement` TINYINT(4) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idphalcon_test_UNIQUE` (`id` ASC));

Model not created and shows error: "Error: Column type does not support scale parameter"

When i change "`price` DOUBLE(7,2) NULL," to   "`price` DOUBLE NULL," all right.

**Comment by overbid** [comment]
@commit aa12ad95bd4870af0a06003a22b9eab2e34a3115 It's same to me.

**Comment by overbid** [comment]
It's fix both master or 2.0.x branch.

**Comment by basilgon** [comment]
The old error has appeared again, although the **scale** is present in the source texts:
Phalcon version: 5.6.1
Column type does not support scale parameter
file: phalcon/Db/Column.zep
line: 398

**Comment by niden** [comment]
> The old error has appeared again, although the **scale** is present in the source texts: Phalcon version: 5.6.1 Column type does not support scale parameter file: phalcon/Db/Column.zep line: 398

Can you post an example please? This code has not been touched since 2019

**Comment by basilgon** [comment]
Class example:
<?php
use Phalcon\Db\Column as Column;

class TestScale extends Column
{
    protected $colspan;
    public function __construct($name, array $definition)
    {
        print_r($definition);                
        if (isset($definition['colspan'])) {
            $this->colspan = $definition['colspan'];
        }       
        parent::__construct($name, $definition);  
    }
    public function getColspan()
    {
        return $this->colspan;
    } 
}

Call example:
            $column = [
                'name' => 'id',
                'caption' => 'ID',
                'type' => 'hidden',
                'size' => null,
                'scale' => null,
                'colspan' => 0,
            ];
            $test = new TestScale('id', $column);

Result:
Array ( [name] => id [caption] => ID [type] => hidden [size] => [scale] => [colspan] => 0 )
Column type does not support scale parameter
file: phalcon/Db/Column.zep
line: 398

**Comment by basilgon** [comment]
Class example:
![image](https://github.com/phalcon/cphalcon/assets/162685998/57fd2496-66c5-40dc-b4e4-ecdb743eb343)
Call example:
![image](https://github.com/phalcon/cphalcon/assets/162685998/53472c74-e5ea-4b21-9b51-c0928d619023)
Result:
Array ( [name] => id [caption] => ID [type] => hidden [size] => [scale] => [colspan] => 0 )
Column type does not support scale parameter
file: phalcon/Db/Column.zep
line: 398

**Comment by niden** [comment]
They `type` you have there is `hidden`. That is not a recognized type for a column. If your type is numeric then it will go in that `if` block and will get the scale, otherwise it will show what you are seeing (the exception).

**Comment by basilgon** [comment]
Thanks for the answer
