### ISSUE TITLE
[NFR]: tag service should have button  method (instead of submit button)

### ISSUE THREAD

**Issue by olegatro** [phalcon/cphalcon#14826]
Button tag have more feature, like add additional tag

So I suggest migrating from

`<input type="submit">` to 

`<button type="submit">send</button>`

**Comment by niden** [comment]
The current `Phalcon\Tag` service (`tag` in DI) does not have the option to create a button for `submit`. You only have the input field as you mentioned.

There is however the `tagHtml` method can be used to create such a button

https://github.com/phalcon/cphalcon/blob/master/tests/unit/Tag/TagHtmlCest.php#L31

```
Tag::tagHtml('button', params)` and you can close that with `Tag::tagHtmlClose('button')
```
We are going to slowly move away from the `Tag` class which uses static methods and instead use a TagFactory to allow more flexibility in creating such elements. For v4 the factory is already in there 

https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Html/TagFactory.zep#L68
https://github.com/phalcon/cphalcon/blob/4.0.x/tests/unit/Html/Helper/ButtonCest.php#L32

and for v4.1 more elements have been added.

https://github.com/phalcon/cphalcon/blob/4.1.x/phalcon/Html/TagFactory.zep#L68

**Comment by olegatro** [comment]
I see, thank you ! 
Sorry for issue.

**Comment by niden** [comment]
Not a problem. I hope the above helps.
