### ISSUE TITLE
[BUG]: ModelsManager column alias bug

### ISSUE THREAD

**Issue by danbgit** [phalcon/cphalcon#14823]
When executing a query and specifying an alias for the model, the column names have the alias prepended to them (model_alias + _ + column_name)

```
SELECT u.id FROM User u
```
**Expected behavior**
Column name is: `id`

**Actual behavior**
Column name is: `u_id`

**Details**
 - Phalcon version: 4.0.1
 - PHP Version: 7.3

### Important
Works as expected in phalcon 3.4.x

**Comment by ruudboon** [comment]
Thnx for reporting. Look like a duplicate of https://github.com/phalcon/cphalcon/issues/14657 and https://github.com/phalcon/cphalcon/issues/14488

**Comment by ruudboon** [comment]
Closing this as duplicate. Please feel free to reopen if you think this is a different issue.
