### ISSUE TITLE
[NFR]: Make testsuite PHPUnit 9 compatible

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14837]
Currently our test suite is failing under PHPUnit 9.
Looks like `assertInternalType` is deprecated. Our tests using this method should be refactored before upgrading.

**Comment by niden** [comment]
This will have to wait until fall, when PHP 7.2 is EOL.

**Comment by dicamoises** [comment]
[License.txt](https://github.com/phalcon/cphalcon/files/4476587/License.txt)

**Comment by niden** [comment]
@dicamoises What should we do with that? I did not notice any of the software in the license file you attached that we use...

**Comment by niden** [comment]
Resolved
