### ISSUE TITLE
[NFR]: Unexpected jump from version 3.4 to version 4.0 during the system update process.

### ISSUE THREAD

**Issue by rigin** [phalcon/cphalcon#14840]
**Is your feature request related to a problem? Please describe.**

My project used version 3.4. When updating Ubuntu with the apt update|apt upgrade commands, phalcon spontaneously switched to version 4.0. Accordingly, the project fell, and it took several days to process it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

To provide a safeguard against such a situation.

**Additional context**

ubuntu 18.04

**Comment by ruudboon** [comment]
You can use `apt-mark` to pinpoint a version.
I will keep this open for the rest of the team to have a look and discuss if we need reconsidered this procedure when moving from 4->5. 
See [forum](https://forum.phalcon.io/discussion/20057/for-existing-v3-installations-via-packagecloudio-what-will-happe) as well

**Comment by niden** [comment]
Since we are only using PECL now for installation, this is not an issue anymore. 

Thank you for reporting @rigin 

Closing this.
