### ISSUE TITLE
Phalcon 4.0.4 release

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14849]
Phalcon 4.0.4 will be released on 15-02-2020. This is our todo list for the release.
Pull regarding the release can reference this issue

* [x] Check pending pulls that need to be merged with 4.0.4
* [x] Update ext + build dir with Zephir 0.12.17 and verify generation
* [x] Update release notes and date package.xml (Pecl)
* [x] Tag release in Github / prepare release notes
* [x] Upload Pecl package to Pecl
* [x] PackageCloud packages
* [x] Create blog post
* [x] Post to social.zoho.com
* [x] Post to Gab.com
* [x] Post to parler.com
* [x] Post to mewe.com
* [x] Post to telegram
* [x] Ping freebsd / openbsd maintainer
* [x] Post to LinkedIn
* [x] Update & release stubs
* [x] Update PhpStorm Stubs plugin
* [x] Update wikipedia
* [x] Update Homebrew package

**Comment by ninjapanzer** [comment]
Catalina macOS .so [phalcon_macOS_catalina_php7.4.2_4.0.4_so.zip](https://github.com/phalcon/cphalcon/files/4209067/phalcon_macOS_catalina_php7.4.2_4.0.4_so.zip)

**Comment by ruudboon** [comment]
Sweet, thnx @ninjapanzer

**Comment by ruudboon** [comment]
Release is done
