### ISSUE TITLE
[BUG]: Parsing error within ternary operator in Volt

### ISSUE THREAD

**Issue by ewaldberkers** [phalcon/cphalcon#14864]
**Describe the bug**
Within the ternary operator in Volt, the test part doesn't recognize the 'is' and 'defined' operators.

**To Reproduce**
```
{#   {% set button_class='btn' %}  #}
{{ button_class is defined ? 'IS DEFINED' : 'NOT DEFINED' }}
```

**Expected behavior**
Volt code should print out whether the variable is defined, but gives error message:
``` Phalcon\Mvc\View\Exception: Syntax error, unexpected token IDENTIFIER(is) in .. ```. When replacing 'is' with '==': ``` Phalcon\Mvc\View\Exception: Syntax error, unexpected token DEFINED in .. ```

**Details**
 - Phalcon version: 4.0.4
 - PHP Version: 7.4.2 
 - Operating System: CentOs 7
 - Installation type: Compiling from source
 - Zephir version (if any): 0.12.17-6724dbf
 - Server: Apache 2.4.41

**Additional context**
Worked fine in Phalcon 3.4.

**Comment by Deathamns** [comment]
#14476

**Comment by ruudboon** [comment]
@ewaldberkers we will use #14476 for tracking this issue. Thnx for reporting and @Deathamns for noticing the duplicate.
