### ISSUE TITLE
[BUG]: Inserting boolean false with insertAsDict gives PDOException

### ISSUE THREAD

**Issue by ewaldberkers** [phalcon/cphalcon#14889]
**Describe the bug**
When inserting boolean values FALSE with insertAsDict() in Phalcon 4.0.4, a PDOException is thrown. This worked fine in Phalcon 3.4 (and earlier).

**To Reproduce**
```
CREATE TABLE `test_bool` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,  
  `test` boolean NOT NULL
) ENGINE='InnoDB';
```
This goes fine:
```
        $data = ['id' => null, 'test' => true];
        $this->db->insertAsDict('test_bool', $data);
```
The following gives this error message: ```PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column some_database.test_bool.test at row 1```

```
        $data = ['id' => null, 'test' => false];
        $this->db->insertAsDict('test_bool', $data);
```

**Expected behavior**
In Phalcon 3.4 and before, this worked fine, booleans could be persisted without problem.

**Details**
 - Phalcon version: 4.0.4
 - PHP Version: 7.4.2
 - Operating System: CentOS 7
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Apache

**Comment by zsilbi** [comment]
Adapters handle boolean types differently.
You have to specify how do you want your values inserted by using bind types:

```php
$this->db->insertAsDict(
    'test_bool',
    $data,
    [
        \Phalcon\Db\Column::BIND_PARAM_INT,
        \Phalcon\Db\Column::BIND_PARAM_BOOL
    ]
);
```

https://docs.phalcon.io/4.0/en/db-models#binding-parameters
