### ISSUE TITLE
Problem with Cyrillic(UTF-8)

### ISSUE THREAD

**Issue by Aleksst95** [phalcon/cphalcon#14884]
**Describe the bug**

I have a route: `$api->add('/is_unique_term/{term}', ['action' => 'isUniqueTerm']);`
This is my action for the route: `public function isUniqueTermAction(string $term)`
When i try to send cyrillic characters(UTF-8) in the term part Phalcon removes my characters and heads to other route. 
Example of URI: `/is_unique_term/фалкон`.
Instead of my route is described above Phalcon heads to `/is_unique_term` (if this exists of course).

**Comment by ruudboon** [comment]
@Aleksst95 Can you add the versions (php + phalcon) you are using and some example cyrillic characters?

**Comment by Aleksst95** [comment]
Yes, I already updated my issue(I accidentally clicked "submit new issue" before when it was not ready).
Phalcon version: 3.4.4
I'm not sure about version php, because I don't have access to a server with the app now.
But this should be 7.2 or 7.3(it is more likely).

**Comment by ruudboon** [comment]
@Aleksst95 With `normal` alpha numeric characters this works fine?

**Comment by Aleksst95** [comment]
Yes. It will work even if I add just one latin character. For example: `/is_unique_term/qфалкон` or `/is_unique_term/фалконq`. 
But Phalcon removes utf-8 characters anyway. I'll get just 'q' in $term variable.

**Comment by ruudboon** [comment]
@Aleksst95 Thnx for reporting. I will check if the happens in Phalcon 4 as well.

**Comment by zsilbi** [comment]
Duplicate: https://github.com/phalcon/cphalcon/issues/15102
Fixed in #15162
