### ISSUE TITLE
[BUG]: Volt Shared Class loop problem

### ISSUE THREAD

**Issue by ismail0234** [phalcon/cphalcon#14891]
**Describe the bug**
If there is a shared class, it creates problems in volt loops.

```php

// services.php
$di->setShared('order', function () {
	return new Order();
});

// IndexController in IndexAction
public function IndexAction()
{
        $orders = new Orders();
        $this->view->activeOrders = $orders->findOrderByMemberId(1);
}

```

**Screenshots**

**Volt:**
![image](https://user-images.githubusercontent.com/20711301/75860812-7e9c9c00-5e0d-11ea-9e0f-c580f846aa31.png)

**PHP Wrong Output:**
![image](https://user-images.githubusercontent.com/20711301/75860724-590f9280-5e0d-11ea-9266-ee8e3deb1c84.png)

**Details**
Phalcon version: v3.4.5
PHP Version: 7.3
Operating System: Linux
Zephir version (if any): -
Server: FASTCGI

**Comment by zsilbi** [comment]
In Volt, defined global service names are not reusable
https://docs.phalcon.io/4.0/en/volt#services
