### ISSUE TITLE
[BUG]: Unable to update Sqlite record in model.

### ISSUE THREAD

**Issue by rigin** [phalcon/cphalcon#14895]
Unable to update Sqlite record in model.

Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**
When trying to update a record in the Sqlite database, the save and update methods return false and do not save the changes.

To change an entry, you must first delete the entry, and then overwrite it with the same id.

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.

```php
            $item_ =  Model::findFirst($id);

            $item_->assign($item);

            $ret = $item_->save();
```

> Provide minimal script to reproduce the issue

```php
// paste output here
```

**Expected behavior**

```php
// paste code
```

**Screenshots**

**Details**
 - Phalcon version: (`php --ri phalcon`)

Version | 4.0.4
-- | --
Build Date | Feb 15 2020 23:14:24
Powered by Zephir | Version 0.12.17-6724dbf

 - PHP Version: (`php -v`)

PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies

 - Operating System:

  | Linux rigin64-xubuntu 4.15.0-88-lowlatency #88-Ubuntu SMP PREEMPT Tue Feb 11 20:51:55 UTC 2020 x86_64
-- | --

 - Installation type: Compiling from source || installing via package manager
 installing via package manager
 - Zephir version (if any):
 - Server: Nginx | Apache | Other
lighttpd
 - Other related info (Database, table schema):

PDO Driver for SQLite 3.x | enabled
-- | --
SQLite Library | 3.22.0

**Additional context**

**Comment by zsilbi** [comment]
Added tests here to verify that this is working as intended: https://github.com/phalcon/cphalcon/pull/15165
Please try again with the 4.1.x branch.
