### ISSUE TITLE
[NFR]: Previous versions of Phalcon in Git repository through tags

### ISSUE THREAD

**Issue by ewaldberkers** [phalcon/cphalcon#14890]
**Is your feature request related to a problem? Please describe.**
When Phalcon 4.0 was still in Alpha, the Git repository contained tags for various versions 3.4, and 4.0 Alpha versions. I had hoped to use that to compile the latest of 3.4, to check if some problems I encountered came from Phalcon 4.0.4 or elsewhere. Unfortunately, ```git tag -l``` only lists tag ```v4.0.4```. Apparently, all older tags have been removed.

**Describe the solution you'd like**
Have tags in the git repository, so that developers can get back to at least the latest of 3.4, and also to the other 4.0 minor versions.

**Describe alternatives you've considered**
Getting Phalcon installed on my VPS goes easiest by compiling from source; I ran into difficulties when trying to use ```yum``` for that.

**Comment by niden** [comment]
We do not delete tags that have been used for releases (or other tags).

If you click the "Release" tab you will see all the releases and tags of Phalcon

https://github.com/phalcon/cphalcon/tags

**Comment by ewaldberkers** [comment]
I hadn't realized that I could download a specific version of Phalcon for compiling. That seems a doable alternative for me to cloning the repository and checking out a tag.

**Comment by niden** [comment]
you can use the `-b` flag to dictate what you want. For instance:

`git clone --depth=1 https://github.com/phalcon/cphalcont -b v3.3.4l'

This will get your repo to have a detached head but for your purposes to install the framework it is just fine. Also the `depth` will ensure that you do not clone the whole repository, making the clone process much faster.

**Comment by ewaldberkers** [comment]
Thanks for explaining. Now I understand the function of the --depth option, which caused my cloned repository to not contain the tags I wanted.

So, this is not an issue. I close it.
