### ISSUE TITLE
[NFR]: Phalcon 4 & Cssmin/Jsmin

### ISSUE THREAD

**Issue by bhairava3** [phalcon/cphalcon#14903]
The documentation says that due to licensing restrictions, you cannot use jsmin in phalcon by default, but I did not find any restrictions with Douglas Crockford "https://github.com/douglascrockford/JSMin/blob/master/jsmin.c"
Why was this wonderful feature removed from the box?

https://docs.phalcon.io/4.0/en/assets#custom-filters
The current implementation of custom filters unfortunately does not work correctly, the filter is applied not to the overall result, but to each connected file.

Please, if possible, return the minification functionality from phalcon 3.4

**Comment by CameronHall** [comment]
The license must have changed. See #10118.

**Comment by bhairava3** [comment]
Thank you. Oh my God, how sad and stupid everything is.

**Comment by niden** [comment]
Tracked in https://github.com/phalcon/cphalcon/issues/14608

**Comment by RobinvanderVliet** [comment]
> The documentation says that due to licensing restrictions, you cannot use jsmin in phalcon by default, but I did not find any restrictions with Douglas Crockford "https://github.com/douglascrockford/JSMin/blob/master/jsmin.c"
> Why was this wonderful feature removed from the box?

"The Software shall be used for Good, not Evil."

More information: https://en.wikipedia.org/wiki/Douglas_Crockford#Software_license_for_%22Good,_not_Evil%22

**Comment by niden** [comment]
We had lengthy discussions with Remi Collet, who maintains an excellent RPM repository, and he found issues with the licensing. As such, we removed it so as not to have any issues. A different solution will be added as we move towards v6 for sure because this is a feature that the community wants.

**Comment by niden** [comment]
Actually, reading a bit more about this, the fact that that statement exists is a vague restriction and therefore _not free_ as in open source. Someone might want to use the software for _evil_ (at least how some people might perceive the definition of evil). As such, that becomes a restriction, so it is not free. 

Crazy world!

**Comment by niden** [comment]
Going once more on this, we will not implement it for cphalcon. There are no libraries available that we can use in the C/Zephir world. There are CLI tools that can perform minification better than we would ever be able to. For v6 we are already using minify from Mathias Mullie and that library is actively supported. Any port we do from that library to cphalcon would mean that we would have to update it whenever the source updates.

Adding this to support the rationale of "won't fix"
