### ISSUE TITLE
[NFR]: can we add controller filter like cakephp4

### ISSUE THREAD

**Issue by wcj343169893** [phalcon/cphalcon#14902]
If we add permission verification, we must add if judgment in each action.
CakePHP has an advantage. In basecontroller, beforefilter can take precedence over action execution. Here, you can judge permissions and define the global variable $allowedactions = [], The action in it does not need permission. Others need to judge whether the role has access to this action. If the user has permission, beforefilter can return true or null. If there is no permission, beforefilter returns response object in the general process, such as: abstractdispatcher's handler - > initialize(); 
[https://github.com/phalcon/cphalcon/blob/c4a804a70c9b89728f010b23935f450c79690bd7/phalcon/Dispatcher/AbstractDispatcher.zep](url)
In the same way, judge the return value of beforefilter. If it is response, jump or display the content directly。
Although exceptions can be thrown here to intercept permissions, exceptions will be written into the error log, which increases the difficulty of troubleshooting other problems。
thanks every body

**Comment by wcj343169893** [comment]
I find [https://github.com/phalcon/cphalcon/issues/13790](url) and i try,it work,it`s ok?
```
public function beforeExecuteRoute($obj){
        $session = $this->getDI()->get("session");
        $role = $session->get("role");
        if($role == "admin"){
           return true;
       }
        $this->response->redirect('/admin/login/index' );
       //echo json_encode(["code"=>401]);
       // $this->response->setContentType("application/json");
        return false;
    }
```

**Comment by Jeckerson** [comment]
In Phalcon you have [events manager](https://docs.phalcon.io/4.0/en/events), which can be called during some specific part of the code execution.

And here is the full list of events - https://docs.phalcon.io/4.0/en/events#list-of-events

**Comment by niden** [comment]
Tracked in https://github.com/phalcon/cphalcon/issues/14608
