### ISSUE TITLE
[BUG]: replace part of column name in query builder started with "NOT_" prefix

### ISSUE THREAD

**Issue by yurik3zzz** [phalcon/cphalcon#14918]
I have a mysql model product with column "not_for_free_delivery"

After run query
`$products = \Products::query()->where('not_for_free_delivery = 1')->execute();`

Have error 
`Error exception: Column '_for_free_delivery' doesn't belong to any of the selected models (1), when preparing: SELECT [Products].* FROM [Products] WHERE not_for_free_delivery = 1`

column named as "not_for_free_delivery" was replaced to '_for_free_delivery' in sql

phalcon version 4.0.4

**Comment by niden** [comment]
Quick workaround would be to enclose the field with `[]` i.e. `[not_for_delivery]`.

Duplicate issue: https://github.com/phalcon/cphalcon/issues/14641
