### ISSUE TITLE
[BUG]: Updating rows with columns that have default values

### ISSUE THREAD

**Issue by Deathamns** [phalcon/cphalcon#14924]
**Describe the bug**
`obj_type is required`
`last_used_utc is required`

Query doesn't execute because of the `PresenceOf` filter for columns with default values.
Creation works though.

**To Reproduce**
Run the script more than once (first to create a new row, then to try updating it):
```php
<?php
class Objects extends \Phalcon\Mvc\Model
{
	public $obj_id;
	public $obj_type;
	public $last_used_utc;
}

$di = new \Phalcon\Di\FactoryDefault;

$di['db'] = new \Phalcon\Db\Adapter\Pdo\Mysql([
	'dbname'   => 'test',
	'username' => 'test',
	'password' => 'test',
]);

$obj = new Objects;
$obj->obj_id = '1';

if ( !$obj->save() ) {
	print_r($obj->getMessages());
}
```

**Expected behavior**
The query should execute even for `update()` without assigning values to columns with defaults.

**Details**
 - Phalcon version: 4.0.5
 - PHP Version: PHP 7.4.3
 - Operating System: Win 10 x64
 - MySQL: 5.7.29
 - Other related info (Database, table schema):

```sql
CREATE TABLE `objects` (
  `obj_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `obj_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `last_used_utc` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`obj_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

**Comment by Jeckerson** [comment]
> It worked in v4.0.4. #14881 might be related.

Current PR is not related, as in your case you do not alter/create table or alter column.

As far as I saw, Phalcon checks only if column is nullable, in your case it is not `last_used_utc datetime NOT NULL DEFAULT`. 

Probably make sense to also check if it has default? /cc @phalcon/core-team

Anaway need more investigation and testing...

**Comment by Deathamns** [comment]
I might have been mistaken here...
This seems to be more like a request then (or it could be a bug too), as the problem is, that `update()`  doesn't use default values for any of the columns, however `create()` does use them.

**Comment by zsilbi** [comment]
I did some testing and found out that `update()` fails when the updated row in the database contain `not null` fields, that are empty strings. These existing rows could only be created manually, as they would also fail the validation on create.

Added the tests here: https://github.com/phalcon/cphalcon/pull/15179

If you still have issues with this, please feel free to reopen this.
