### ISSUE TITLE
[BUG]: Phalcon\Db\Adapter\Pdo\Postgresql::createTable() does not accept null anymore

### ISSUE THREAD

**Issue by terax6669** [phalcon/cphalcon#14923]
**Describe the bug**
`PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Phalcon\Db\Adapter\Pdo\Postgresql::createTable() must be of the type string, null given`

**To Reproduce**

```php
$db->createTable('test', null, $definition);
```

**Expected behavior**
NULL creates table in the default schema, like in Phalcon 3

**Details**
 - Phalcon version: 4.0.5-923+php7.2 amd64
 - PHP Version: 7.2.28-4+0\~20200224.38+debian9~1.gbp1ca010
 - Operating System: Debian 9.12
 - Installation type: packagecloud.io
 - Server: Nginx
 - Other related info (Database, table schema): Postgresql 12

**Comment by zsilbi** [comment]
This is not a bug, the interface has changed from v3 to v4.
