### ISSUE TITLE
[NFR]: Micro removeExtraSlashes should be false by default

### ISSUE THREAD

**Issue by andrew-s** [phalcon/cphalcon#14920]
**Is your feature request related to a problem? Please describe.**
When using the Micro controller, the router gets `removeExtraSlashes` set to `true` by default. It's not mentioned in the documentation but, I think this is a little misleading as it removes any trailing slash on the function (while my URI remains static).

There's an argument that if I explicitly define say `/profiles/{slug}/` then I'd expect that to match be the both the minimum and maximum, I'm unsure as the reason to post-process all routes.

See; https://github.com/phalcon/cphalcon/blob/fe17e3ae897b8d3f41d65ed328fcb734d1955b51/phalcon/Mvc/Micro.zep#L303

**Describe the solution you'd like**
There's multiple solutions to this problem;

- Update the documentation to highlight this happens by default (maintains backwards compatibility) and add examples - however, this doesn't fix the illogical naming nor what it does
- Update the Micro framework to have `removeExtraSlashes` set to `false` by default (as I presume it is elsewhere?) and update the documentation on how to enable it
- Rename `removeExtraSlashes` to be `removeTrailingSlash` (which seems to be what it actually does) and set it to `false` by default (with updated documentation in *all* the relevant places) (this is the most backward breaking change, but likely the one that makes the most sense)

Happy to help make any relevant change/PR (or even just update any documentation) given the direction the project chooses.

**Comment by niden** [comment]
This is tracked in https://github.com/phalcon/cphalcon/issues/14608. Please vote if you want this feature.
