### ISSUE TITLE
Storage/Adapter/Redis Not support unix

### ISSUE THREAD

**Issue by kkstun** [phalcon/cphalcon#14938]
* @param array $options = [
     *     'host' => '127.0.0.1',
     *     'port' => 6379,
     *     'index' => 0,
     *     'persistent' => false,
     *     'auth' => '',
     *     'socket' => '',
     *     'defaultSerializer' => 'Php',
     *     'lifetime' => 3600,
     *     'serializer' => null,
     *     'prefix' => ''
     * ]

where config /tmp/redis.sock?

**Comment by TimurFlush** [comment]
```php
[
    'host' => '/tmp/redis.sock', 
    'port' => null
]
```

**Comment by kkstun** [comment]
Yes,it's work!
 'port' => null     √
I just try  'port' => 0

**Comment by kkstun** [comment]
Yes,it's work!
 'port' => null     √
I just try  'port' => 0
