### ISSUE TITLE
Form Breaks on file Equal Resolution Failed

### ISSUE THREAD

**Issue by assadnazar** [phalcon/cphalcon#14930]
Hi,
My file field is as follows:
```php
$facilityimage = new File('facilityimage');

$facilityimage->addValidators([
    new FileValidator([
        'maxSize' => '0.5M',
        'messageSize' => 'Your image is too big. Max file size: 500KB',
        'allowedTypes' => array('image/jpeg', 'image/png'),
        'messageType' => 'Your image must be a JPEG or PNG file',
        'equalResolution' => '130x80',
        'messageEqualResolution'    => 'Image resolution should be 130px by 80px.',
        'allowEmpty' => (!empty($options['edit']) ? true : false)
    ])
]);

$this->add($facilityimage);
```

and my validation check is as follows:
```php
if (!$form->isValid(array_merge($this->request->getPost(), $_FILES))) {
    foreach ($form->getMessages() as $message)
        $this->flash->error((string) $message);
}
```

When I upload bigger resolution image, the form somehow breaks and does not show file field as expected in my editAction.

***UPDATE***
The field `facilityimage` is getting populated by $_FILES array even when it is not validated. Should not it be reverted to the old value or empty value by default?

For now, I just explicitly replaced `facilityimage` to it's old value by either re querying the model or saving old value before validating form.

**Comment by assadnazar** [comment]
Bump

**Comment by Izopi4a** [comment]
in 5.0.x seems to be fine, can you share more of the code to reproduce please?

**Comment by Jeckerson** [comment]
Feel free to re-open with reproducible code.
