### ISSUE TITLE
Fatal error: Declaration of EP\Validators\UserPassword::validate(Phalcon\Validation $validator, $attribute) must be compatible with Phalcon\Validation\AbstractValidator::validate(Phalcon\Validation $validation, $field): bool

### ISSUE THREAD

**Issue by sanjayhais** [phalcon/cphalcon#14932]
`<?php
namespace EP\Validators;

use Phalcon\Validation\Message;
use Phalcon\Validation\AbstractValidator as Validator;
use Phalcon\Validation\ValidatorInterface;

class UserPassword extends Validator implements ValidatorInterface
{
    public function validate(\Phalcon\Validation $validator, $attribute)
    {
        if (!$this->getOption('validpass')) {
            $message = $this->getOption('message');
            if (!$message) {
                $message = 'Wachtwoord is niet correct';
            }
            $validator->appendMessage(new Message($message, $attribute, 'UserPassword'));
            return false;
        }

        return true;
    }
}`

**Comment by Jeckerson** [comment]
You need to include `: bool` in method declaration

https://github.com/phalcon/cphalcon/blob/d3e94630156a0c4441bf5f72e6ed071941c5908b/phalcon/Validation/AbstractValidator.zep#L171

Like that:
```
public function validate(\Phalcon\Validation $validator, $attribute): bool
```

**Comment by sanjayhais** [comment]
Thank you from the deepest corner of my heart for this quick fix. I have been struggling with function overrides from last 3 days.
