### ISSUE TITLE
[NFR]: Add the merge mode for the Model::skipAttributes()

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#14934]
Hello!

I propose to add the merge mode for the Model::skipAttributes()
This is useful when the model is extended by traits that contain ignored fields and etc.

Example:
```php
Model::skipAttributes(array $attributes, bool $merge = true);
```

**Comment by niden** [comment]
This NFR is tracked here: https://github.com/phalcon/cphalcon/issues/14608
