### ISSUE TITLE
[BUG]: QueryBuilder bug?when column starts with 'not'

### ISSUE THREAD

**Issue by feelingseas** [phalcon/cphalcon#14940]
```
$builder = $this
    	->modelsManager
    	->createBuilder()
    	->from(Notice::class)
    	->where("notice_category_id = $id")
    	->orderBy("id desc");
```
then error message shows like this :

`Column 'ice_category_id' doesn't belong to any of the selected models.....`

notice's 'not'is gone...combine where not ice_category_id 
is this a bug ,or I used QueryBuilder by wrong way?

**Comment by feelingseas** [comment]
phalcon version is 4.0.4

**Comment by TimurFlush** [comment]
Please see the https://github.com/phalcon/cphalcon/issues/14918

You should use the PHQL escaping to fix your issue (and placeholders to avoid the SQL Injection) : 

```php
->where'([notice_category_id] = :id:', ['id' => $id]) ;
```

**Comment by feelingseas** [comment]
@TimurFlush 
ok.I see.Thanks for your answer.

**Comment by alexbusu** [comment]
I'm happy to see someone did open a ticket already. I can confirm this bug, and also the woraround to fix it (use the escapers `[]`). While escapers are recommended, but not required, this should be considered a bug.

**Comment by alexbusu** [comment]
It seems the problem is in PHQL parser, in `\Phalcon\Mvc\Model\Query\Lang::parsePHQL()`, therefore in internal `phql_parse_phql()`, and... C is not my land... At least for now :smile:

**Comment by robinbertram** [comment]
I also got this error by naming a column "notes".

**Comment by zsilbi** [comment]
Duplicate issue: https://github.com/phalcon/cphalcon/issues/14641

**Comment by yesworld** [comment]
Phalcon 5, the same problem.
Will you fix it?
