### ISSUE TITLE
[BUG]: field is required when soft deletion operates

### ISSUE THREAD

**Issue by itknight** [phalcon/cphalcon#14943]
in the table scheme,  a  varchar filed ,called 'column1' for example , is  not null default '' ,and the flag field of soft delete is 'deleted' , 
if  there is a recod  ,and its column1 is '' ,and where operates soft deletion .
a error  "column1 is required" occurs.

how can we avoid this happening.

**Comment by TimurFlush** [comment]
Can you attach/text examples?

**Comment by zsilbi** [comment]
SoftDelete has been updated recently: https://github.com/phalcon/cphalcon/pull/15163

Please reopen this if it still occurs on the 4.1.x branch and provide more information.
