### ISSUE TITLE
[BUG]: error when call the set method of \Phalcon\Http\Response\Cookies

### ISSUE THREAD

**Issue by lanlin** [phalcon/cphalcon#14944]
**Describe the bug**
```shell
Fatal error: 
Uncaught RuntimeException: 
Trying to call method get on a non-object 
Phalcon\Http\Response\Cookies->set('test', 'test', 1586494844) 
```

**To Reproduce**
> Provide minimal script to reproduce the issue
```php
<?php
$cookies = new \Phalcon\Http\Response\Cookies();
$cookies->set(
    'test',
    'test',
    time() + 3600
);
```

**Expected behavior**
I just want to set a simple cookie with the `set` method of `\Phalcon\Http\Response\Cookies`, but it not works.

**Details**
 - Phalcon version: 4.0.5
 - PHP Version: 7.4.4
 - Operating System: osx 10.13.6
 - Installation type: installing via package manager (phpbrew ext install phalcon)
 - Zephir version (if any): Version 0.12.17-6724dbf
 - Server: Nginx 1.17.9
 - Other related info (Database, table schema):

```shell
PHP -v

PHP 7.4.4 (cli) (built: Mar 20 2020 16:29:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
```

```shell
php --ri phalcon

phalcon
Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.5
Build Date => Mar 20 2020 17:26:45
Powered by Zephir => Version 0.12.17-6724dbf

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On
```

**Comment by TimurFlush** [comment]
Temporary fix
```php
        $cookies = new \Phalcon\Http\Response\Cookies();
        $cookies->setDI(Di::getDefault()); // Attention on it
        $cookies->set(
            'test',
            'test',
            time() + 3600
        );
```

**Comment by TimurFlush** [comment]
This bug is here.

https://github.com/phalcon/cphalcon/blob/d3e94630156a0c4441bf5f72e6ed071941c5908b/phalcon/Http/Response/Cookies.zep#L244

This is because the dependency container is not contained in this class.
So you need to specify it explicitly
I don't know if it's a bug or not, therefore please keep this issue open

**Comment by lanlin** [comment]
@TimurFlush
thanks, but that's really confusing for a cookie setting. 
it's still not working after setting the di.

1. when passing the `\Phalcon\Di` instance

```php
$cookies = new \Phalcon\Http\Response\Cookies();
$cookies->setDI(new \Phalcon\Di());
$cookies->set(
    'test',
    'test',
    time() + 3600
);
$cookies->send();
```

```shell
Fatal error: 
Uncaught Phalcon\Di\Exception: 
Service 'response' wasn't found in the dependency injection container 
Stack trace: 
#0 [internal function]: Phalcon\Di->get('response', NULL)
#1 [internal function]: Phalcon\Di->getShared('response')
#2: Phalcon\Http\Response\Cookies->set('test', 'test', 1586503663)
#3 {main}
```

2. when passing the `\Phalcon\Di\FactoryDefault` instance

```php
$cookies = new \Phalcon\Http\Response\Cookies();
$cookies->setDI(new \Phalcon\Di\FactoryDefault());
$cookies->set(
    'test',
    'test',
    time() + 3600
);
$cookies->send();
```

```shell
Fatal error: 
Uncaught Phalcon\Di\Exception: 
Service 'session' wasn't found in the dependency injection container in 
Stack trace:
#0 [internal function]: Phalcon\Di->get('session', NULL) 
#1 [internal function]: Phalcon\Di->getShared('session') 
#2 [internal function]: Phalcon\Http\Cookie->send() 
#3 Phalcon\Http\Response\Cookies->send() 
#4 {main}
```

**Comment by TimurFlush** [comment]
If you use the FactoryDefault you need to register the 'session' service in DI
FactoryDefault provides a standard service kit, but it's not contain the 'session' service

Also please read the documentation

**Comment by lanlin** [comment]
ok, thanks very much.
I read the docs already, it tells me

![image](https://user-images.githubusercontent.com/3468024/78971884-2315aa80-7b3f-11ea-8e57-8c9529b6c06d.png)
NOTE: If your DI container contains the session service, the cookies will be stored in the session automatically. If not, they will not be stored, and you are responsible to persist them if you wish to.

what does the 'If your DI container contains the session service' mean?
why did we have to init both response & session for a cookie setting?

**Comment by lanlin** [comment]
well, it seems not to check if there's a session service
![image](https://user-images.githubusercontent.com/3468024/78973297-3118fa80-7b42-11ea-919a-b93a4dbda7f6.png)

https://github.com/phalcon/cphalcon/blob/master/phalcon/Http/Cookie.zep

**Comment by TimurFlush** [comment]
Don't bad, thank you for the fix!

**Comment by lanlin** [comment]
the phalcon:4.1.x has already fixed this problem. close this.
