### ISSUE TITLE
[BUG]: ValidationInterface - add : parameters not correct

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#14946]
Same on Visual Studio Code.
Also, in ValidationInterface::add first argument's type is string, whereas it can be string or an array.

_Originally posted by @wmamrak in https://github.com/phalcon/cphalcon/issues/14818#issuecomment-582931599_

**Comment by Jeckerson** [comment]
@zsilbi Are we really need to push that fix to the `6.0`. As it seems to be bug, or at least make sense to fix that in `v5`?

**Comment by zsilbi** [comment]
> @zsilbi Are we really need to push that fix to the `6.0`. As it seems to be bug, or at least make sense to fix that in `v5`?

I labeled every issue with v6 which requires interface changes by default. Please override that wherever you think.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15352
