### ISSUE TITLE
[NFR] Add Phalcon packages to Ubuntu 20.04

### ISSUE THREAD

**Issue by Nialld** [phalcon/cphalcon#14958]
Tried following the installation instructions on https://docs.phalcon.io/4.0/en/installation

"curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash" this was successful

sudo apt-get update

and received the following error

"The repository 'https://packagecloud.io/phalcon/stable/ubuntu focal Release' does not have a Release file"

**Comment by Jeckerson** [comment]
For, now you can install via pecl or build from sources.

**Comment by sergeyklay** [comment]
Ubuntu 20 was released a few days ago

**Comment by sergeyklay** [comment]
I'll prepare packages ASAP.

**Comment by slothstronaut** [comment]
Ubuntu 20.04 has been out for months now, is there any update on this? Documentation should either be updated, or removed if packages are not released soon. 

New installers from Ubuntu 20 might get discouraged from using Phalcon since documentation does not work correctly.

**Comment by contactjavas** [comment]
@Jeckerson :
> For now you can install via pecl or build from sources.

No man, even using PECL (Ubuntu 20.04, Nginx, PHP FPM 7.4), the installation will be failed & stopped.

&nbsp;

@slothstronaut : 
> New installers from Ubuntu 20 might get discouraged from using Phalcon since documentation does not work correctly.

You're true , it's stopping me from using Phalcon. I'll wait until it's ready for Ubuntu 20.04 😃

**Comment by ruudboon** [comment]
@contactjavas Can you open a new issue for the PECL install failure with the error messages so we can investigate it? Thnx

**Comment by contactjavas** [comment]
Hi @ruudboon , if i remember well, the error message i got _across installations_ (pecl, source, apt-get) using Ubuntu 20.04 + Nginx + PHP FPM 7.4 is the same. #15078

**Comment by sinbadxiii** [comment]
Hey guys, if anyone has a problem installing Phalcon on ubuntu 20.04, then just change

`sudo nano /etc/apt/sources.list.d/phalcon_stable.list`

this is

```
deb https://packagecloud.io/phalcon/stable/ubuntu/ focal main
deb-src https://packagecloud.io/phalcon/stable/ubuntu/ focal main
```

on is

```
deb https://packagecloud.io/phalcon/stable/ubuntu/ bionic main
deb-src https://packagecloud.io/phalcon/stable/ubuntu/ bionic main
```

and run `sudo apt update && sudo apt upgrade`

**Comment by attndeficit** [comment]
Please add note to the official documentation that the latest version of Ubuntu cannot be used at this time.  I have to start all over now with 18.04 to complete my assignment and I just checked the official doc again, I did not spot any mention that 20.04 would be unsupported and thus had no reason to suspect an issue this lame this far down the installation process.  The bionic workaround did NOT work for me on fresh 20.04LTS installation today.  Downloading 18.04 and **starting over**

**Comment by slothstronaut** [comment]
I can confirm this, also tested it last week and nothing worked on 20.04 except compiling it myself. 

Also the v3 branch can no longer be compiled on 20.04 - it has issues.

So if you're using Ubuntu 20.04 your *only* option is to use 4.0.X and compile it yourself. 18.04 seems to work fine for now though, and is still supported for a few years.

**Comment by Jeckerson** [comment]
Done in https://github.com/phalcongelist/packagecloud/issues/63

**Comment by Jeckerson** [comment]
Installation example via docker:

```
docker run -it --rm ubuntu:20.04 bash
apt-get update
apt-get install curl php-cli
curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | bash
apt-get install php7.4-phalcon
```

**Comment by souhail-5** [comment]
> Installation example via docker:
> 
> ```
> docker run -it --rm ubuntu:20.04 bash
> apt-get update
> apt-get install curl php-cli
> curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | bash
> apt-get install php7.4-phalcon
> ```

This doesn't work anymore 😕 . What I got:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.4-phalcon
E: Couldn't find any package by glob 'php7.4-phalcon'
E: Couldn't find any package by regex 'php7.4-phalcon'
```
