### ISSUE TITLE
[BUG]: Call to imagettfbbox() failed

### ISSUE THREAD

**Issue by rumnky** [phalcon/cphalcon#14950]
`$image = new Gd(BASE_PATH . '/public/800x600.jpg');`
`$image->text('Phalcon Framework', 10, 10, 75, '000033', 14, BASE_PATH . '/app/assets/fonts/Arial.ttf');`

Windows 10 + PHP 7.4 + Gd2 library with enabled FreeType Support, but code above runs with error.

**Comment by Jeckerson** [comment]
https://github.com/phalcon/cphalcon/blob/a8035814aa9a8a2438f92ebf5128964e7c48fd3f/phalcon/Image/Adapter/Gd.zep#L602-L612

Check path to your font. Also there are many errors related to that function `imagettfbbox()`.

**Comment by Jeckerson** [comment]
Closing in favor #15188.
