### ISSUE TITLE
[BUG]: DB\Dialect\Postgresql does not support SMALLINT column type

### ISSUE THREAD

**Issue by armezit** [phalcon/cphalcon#14968]
**Describe the bug**
DB\Dialect\Postgresql does not support SMALLINT column type
Running db migration on Postgresql database throws an error:
```
DB Error: Unrecognized PostgreSQL data type at column <COLUMN_NAME>
```

**To Reproduce**

Run a db migration on Postgresql database for a table which has a smallint column:
```php
$this->morphTable('table_name', [
        'columns' => [
            new Column(
                'status',
                [
                    'type' => Column::TYPE_SMALLINTEGER,
                    'notNull' => true,
                    'unsigned' => true,
                    'size' => 1,
                    'after' => 'role'
                ]
            ),
        ]
    ]
);
```
**Details**
 - Phalcon version: 4.0.5
 - PHP Version: 7.4.4
 - PostgreSQL: 12.2

**Additional context**
Seems it's related to https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Db/Dialect/Postgresql.zep#L380 
which has no column definition for Column::TYPE_SMALLINTEGER

**Comment by Jeckerson** [comment]
Implemented in #15187
