### ISSUE TITLE
[BUG]: Incorrect return type hints for Phalcon\Http\Response

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#14983]
There is no restriction for `content` data type:
https://github.com/phalcon/cphalcon/blob/d3e94630156a0c4441bf5f72e6ed071941c5908b/phalcon/Http/Response.zep#L67-L79

But `Phalcon\Http\Response::getContent` has to return string:

https://github.com/phalcon/cphalcon/blob/d3e94630156a0c4441bf5f72e6ed071941c5908b/phalcon/Http/Response.zep#L94-L97

The following code leads to a fatal error:
```php
$response = new Response(['user' => 'jeremy']);
$response->getContent();
```

```
PHP Fatal error:
Return value of Phalcon\Http\Response::getContent()
must be of the type string, array returned in Unknown on line 0
```

**Comment by sergeyklay** [comment]
Fixed in 4.0.x branch

**Comment by jenovateurs** [comment]
Well done @sergeyklay :-)

**Comment by sergeyklay** [comment]
Thank you
