### ISSUE TITLE
[BUG]: getEventsManager returning `null`

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#15010]
The `getEventsManager()` could return null in certain circumstances. The signature needs to change throughout the framework

`public function getEventsManager() ->  <EventsManagerInterface> | null`

**Comment by Izopi4a** [comment]
changes are in https://github.com/phalcon/cphalcon/pull/15348

**Comment by niden** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/15348
