### ISSUE TITLE
[NFR] Named scopes in Models

### ISSUE THREAD

**Issue by Agent-J** [phalcon/cphalcon#1502]
There is a great feature in Yii framework called [Named Scopes](http://www.yiiframework.com/doc/guide/1.1/en/database.ar#named-scopes).
// The original idea of named scopes came from Ruby on Rails.

It is like query builder, but more usable 'cause of custom conditions set.
Check it out:

``` php
// This is Post model class
class Post extends CActiveRecord
{
    // through "scopes" method, which will be used with magic __call method
    public function scopes()
    {
        return array(
            'published' => array(
                'condition' => 'status=1',
            )
        );
    }

    // through named method with additional params
    public function recently($limit = 5)
    {
        $this->getDbCriteria()->mergeWith(array(
            'order' => 'create_time DESC',
            'limit' => $limit,
        ));
        return $this;
    }

    // this is default scope that would be applied for all queries (including relational ones) 
    public function defaultScope()
    {
        return array(
            'condition'=>"language='en'",
        );
    }
}

// now I can find records with named conditions
$posts = Post::model()
    ->published()  // only posts with status=1
    ->recently(10) // SORT BY create_time DESC and LIMIT 10
    ->findAll();
```

Also through scope you can join other models.
Really miss this functionality in Phalcon.

This issue may be similar to #926

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
