### ISSUE TITLE
[NFR]: Not require database connection for Unit Testing (PHPUnit)

### ISSUE THREAD

**Issue by RayHughes** [phalcon/cphalcon#15035]
**Is your feature request related to a problem? Please describe.**
When unit testing and using a mocking a model class, the database driver is needed and a connection is required to the database. 

This should not be the case when mocking objects and it could potentially create problems in the automated build pipelines as they too will require a connection to the database.

If a user does not properly mock their model interactions, data can be persisted to the database which is not ideal.

**Describe the solution you'd like**
A way to test model manipulation without a database connection.

**Describe alternatives you've considered**
Creating a direct clone of the model without extending the model and mocking it based on a common interface in testing. This is less than ideal as two objects would need to be maintained.

**Additional context**
N/A

**Comment by Jeckerson** [comment]
Could you provide code example of your mockable model?

**Comment by RayHughes** [comment]
@Jeckerson I am using a partial mock and setting the model up in the `setUp()` as a member variable. 

I just dont want a database connection. It shouldn't be a requirement.

**Comment by RayHughes** [comment]
Please close. This was more of a product of the way the documentation says to configure the helper. I have resolved it.

**Comment by niden** [comment]
@RayHughes If there is something lacking in our docs can you send a PR for it please?

**Comment by RayHughes** [comment]
@niden yes I will in the next few days
\

**Comment by RayHughes** [comment]
https://github.com/phalcon/docs/pull/2735
