### ISSUE TITLE
Phalcon\Validation\Validator\Ip validate fail

### ISSUE THREAD

**Issue by shuqiangzhou** [phalcon/cphalcon#15049]
Phalcon\Validation\Validator\Ip validate fail
![image](https://user-images.githubusercontent.com/26402118/82671847-1920b480-9c72-11ea-8cd2-dc389a3be097.png)

![image](https://user-images.githubusercontent.com/26402118/82673285-29d22a00-9c74-11ea-8280-25d711376dab.png)

![image](https://user-images.githubusercontent.com/26402118/82673369-58e89b80-9c74-11ea-9adb-5f7c0ba55106.png)

is validate fail ?how i can to do?

**Comment by Jeckerson** [comment]
In your code, you are testing private IP address (`192.x`)

```
$validator = new Validation();
$validator->add('ip', new Ip([
    'message' => 'ip fail',
    'version' => Ip::VERSION_4 |Ip::VERSION_6,
    //'allowPrivate' => true,
]));

var_dump(count($validator->validate(['ip' => '192.168.1.1'])));
```

So you need to add `'allowPrivate' => true` option inside array

Another example
```
new Ip(
    [
        'message'       => 'This is a test message',
        'version'       => Ip::VERSION_4 | Ip::VERSION_6,
        'allowPrivate'  => false,
        'allowReserved' => false,
        'allowEmpty'    => false,
    ]
)
```
