### ISSUE TITLE
Typed 'id' property on Models throws error in PHP 7.4 due to access before initialization

### ISSUE THREAD

**Issue by ldennison** [phalcon/cphalcon#15048]
I'll start this by saying I'm not 100% sure if this is a bug, or just something that needs to change in my workflow. But here's my case.

```php
<?php

## app/models/SomeModel.php
class SomeModel extends Phalcon\Mvc\Model {
    private int $id; // column is an INT NOT NULL
    // ...
}

## app/controllers/SomeController.php
class SomeController extends Phalcon\Mvc\Controller {
    public function someControllerAction() {
        $newModel = new SomeModel([
            'someOtherProp' => 'whatever',
            // ... never setting $id because it's a new record
        ]);

        $newModel->save(); // this throws the Error listed below
    }
}
```

That `$newModel->save()` is generating the following exception under PHP 7.4:
```
Typed property App\Models\SomeModel::$id must not be accessed before initialization
#0 [internal function]: Phalcon\Mvc\Model->_exists()
#1 app/controllers/SomeController.php: Phalcon\Mvc\Model->save()
```

This is on PHP 7.4.5, Phalcon 4.0.3, with PostgreSQL 11.7 database.

It would seem to me that Phalcon should not be trying to access the `$id` property if it is uninitialized (checkable via `isset()`). If it's not set, Phalcon shouldn't be sending any value (even null) to PostgreSQL for that column. I can bypass the issue by changing the property definition to `private ?int $id = null;`, but that's not a great solution. The `id` column is NOT nullable in the database because it's a primary key.

Am I wrong in my understanding or workflow here, or is this indeed a bug?

**Comment by Jurigag** [comment]
Well, i partially agree. From ORM perspective if you create new model using auto incrementing id then you have for certain amount of time actually null id - until model is indeed created and then id is populated using last inserted id. But if we think about database perspective then yea, it never will be null.

**Comment by Jeckerson** [comment]
You need to write like that

```
private ?int $id = null;
```

There is no another solution atm.
