### ISSUE TITLE
If no controller suffix `dispatch` quietly dies

### ISSUE THREAD

**Issue by mirazasx** [phalcon/cphalcon#15056]
If I have something like this
```
$app = new Micro($di);
$app->dispatcher->setControllerSuffix('');
```
Then this dies quietly:
```
$app->get(
    '/api/test',
    function($pr)  {
          $this->dispatcher->setControllerName('App\Api\Api');
          $this->dispatcher->setActionName('get');
          $this->dispatcher->dispatch();
          return $this->dispatcher->getReturnedValue();
});
```
What I found out is that this happens due to DI not having instance of an controller. So if I register it manually:
```
$this->di->setShared(
            'App\Api\Api',
            new App\Api\Api()
        );
```
Then is works!!! 
If it's expected behavior I would at least expect to see an error rather then nothing.

I used:
```

Phalcon: 4.0.5
PHP: 7.4.6
Os Debian: 10

```

**Comment by Jeckerson** [comment]
Are you sure that errors are not disabled inside your php.ini configuration?

Also, try to load it via Phalcon Loader or via composer PSR-4 and check if it is also works or not.

**Comment by mirazasx** [comment]
🤔  not sure what happened, but after I have redone all my environment (build docker images, reconfigured), it suddenly works, can't reproduce it my self. I suspect I made some misconfiguration first time. Sorry for false bug 🙈
