### ISSUE TITLE
[BUG]: second iteration on Resultset\Simple

### ISSUE THREAD

**Issue by vikilaboy** [phalcon/cphalcon#15065]
**Describe the bug**
Hi guys,
I'm facing this issue:
I try to get items from the database by using ```php find()``` or whatever method returns ```php Phalcon\Mvc\Model\Resultset\Simple``` then I make a first foreach through. 
Everything is fine until i try to make a second foreach when the models aren't there. 
No more objects
I get the error: 

Error: Call to a member function getId() on null

This happens only on Phalcon v4.0.6 . I was trying to upgrade from 3.4.5 and i got this. 

Am i doing something wrong ?

**To Reproduce**

```php
        $projectCollection = Project::find();
        
        foreach ($projectCollection as $project) {
            echo $project->getId();
            echo '<br>';
        }

        foreach ($projectCollection as $secondProject) {
//here comes the issues. $secondProject is null !!!
            echo $secondProject->getId();
            echo '<br>';
        }
```

**Details**

Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.6
Build Date => May 16 2020 18:34:53
Powered by Zephir => Version 0.12.17-6724dbf

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On

PHP 7.4.6 (cli) (built: May 14 2020 10:03:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies

**Comment by zsilbi** [comment]
How many records do you have in `Projects`?
Did you modify `orm.resultset_prefetch_records` setting?

I couldn't reproduce the issue here: https://github.com/zsilbi/cphalcon/commit/dff04f4ddc651581d961b2f59f8335c00ab66059
It would be helpful if you could please provide the Model and the database schema.

**Comment by zsilbi** [comment]
I added tests for this issue: https://github.com/phalcon/cphalcon/pull/15177

Please feel free to reopen, if the issue still persists.

**Comment by dugwood** [comment]
@vikilaboy sorry for digging this up, I think I have the bug too (v3 upgrade to v4).

One thing I can think of, in my code so perhaps in yours too: do you remove relations between the two iterations? That could explain why some of the elements are missing (hence `null` in the loop) because these were deleted (by Phalcon) before the second iteration.

This didn't happen in v3, perhaps because v4 cleans all dirty relations.

**Comment by dugwood** [comment]
@zsilbi @vikilaboy I can confirm my suggestion: between my two iterations, there was a deletion.

I think that v3 handles this correctly, and v4 is buggy (my assumption was the other way around in my previous message):

- I'm using relations from a model, but `find()` does the same thing (as far as I recall, `$this->relations` is built with `Relation::find()`)
- if one relation is destroyed, it should be destroyed in the array/iterator as well
- so v4 keeps the relation and set it to null, where it should have destroyed it completely

Perhaps one test would be to dump the `count()` of objects. Something like:

```php
$projectCollection = Project::find();
        
var_dump(count($projectCollection)); // say that the collection is 10 entries, should return 10

$projectCollection[0]->delete();

var_dump(count($projectCollection)); // should return 9 in v3 and 10 in v4
```
