### ISSUE TITLE
[BUG]: CLI console:boot event not be triggered 

### ISSUE THREAD

**Issue by ivanovbg** [phalcon/cphalcon#15060]
Hello guys. 

I try to add boot event in cli application. 
I have this dispatcher: 

```
 $dispatcher = new CliDispatcher();
 $dispatcher->setDefaultNamespace('SFC\Tasks');

 $dispatcher->setActionSuffix('');
 $dispatcher->setTaskSuffix('');
 $dispatcher->setDefaultTask('help');
 container('eventsManager')->attach("console", new CliInputListener());
 $dispatcher->setDI(container());
 $dispatcher->setEventsManager(container('eventsManager'));
```

In CliInputListener I have boot method. 

```
public function boot(Event $event, Application $application)
{

  $parsedOptions = OptionParser::parse($application->getRawArguments());
  $definition    = $this->setUpTaskDefinition($parsedOptions);
  $application->setArguments($definition);
   return true;
}
```

But boot event never be triggered.

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: 7.3
 - Operating System: Windows/Linux
.

**Comment by ruudboon** [comment]
Can you drop the code how you setup the di? Looks like you have some global function wrapper around it would to check if something is happening there.

Can you try to attach an event manually as well?
```
    $eventsManager->attach(
            'console:boot',
            function (Event $event, $console) {
                throw new Exception('Console Boot Event Fired');
            }
        );
```

**Comment by ivanovbg** [comment]
Hi, again. I tried to add event manually - no difference - event not triggered.

The code: I have Dispatcher provider:
```

<?php
namespace SFC\Providers\Dispatcher;

use Phalcon\Cli\Dispatcher as CliDispatcher;
use Phalcon\Di\DiInterface;
use Phalcon\Di\ServiceProviderInterface;
use Phalcon\Mvc\Dispatcher as MvcDispatcher;
use SFC\Listeners\CliInputListener;
use SFC\Listeners\DispatcherListener;

class DispatcherProvider implements ServiceProviderInterface {
    private static $PROVIDER = "dispatcher";

    public function register(DiInterface $di):void {
        $di->setShared(self::$PROVIDER, function() use ($di) {
            $mode = container('bootstrap')->getMode();

            switch ($mode){
                case 'web':
                    $dispatcher = new MvcDispatcher();
                    $dispatcher->setDefaultNamespace('SFC\Modules'.DIRECTORY_SEPARATOR.ucfirst(config('modules')->list->get(config('modules')->default)).DIRECTORY_SEPARATOR.'Controllers');
                    container('eventsManager')->attach("dispatch", new DispatcherListener());
                    break;
                case 'cli':
                    $dispatcher = new CliDispatcher();
                    $dispatcher->setDefaultNamespace('SFC\Tasks');

                    $dispatcher->setActionSuffix('');
                    $dispatcher->setTaskSuffix('');
                    container('eventsManager')->attach("console", new CliInputListener());
                    break;
                default:
                    throw new \Exception();
            }

            $dispatcher->setDI(container());
            $dispatcher->setEventsManager(container('eventsManager'));

            #var_dump($dispatcher->getEventsManager());
            #exit;

            return $dispatcher;
        });
    }
}
```

`<?php
namespace SFC\Listeners;

use Phalcon\Cli\Dispatcher;
use Phalcon\Events\Event;
use SFC\Common\Library\Console\OptionParser;
use SFC\Library\Console\Application;

/**
 * Phosphorum\Listener\CliInputListener
 *
 * @package Phosphorum\Listener
 */
class CliInputListener
{
    const SEPARATOR = ':';

    /**
     * Parse and prepare the task definition from the input options.
     *
     * @param  Event       $event
     * @param  Application $application
     * @return bool
     */
    public function boot(Event $event, Application $application)
    {

        $parsedOptions = OptionParser::parse($application->getRawArguments());
        $definition    = $this->setUpTaskDefinition($parsedOptions);
        $application->setArguments($definition);

        //TODO: Add log

        return true;
    }


    public function beforeHandleTask(Event $event, Application $application){
        echo 123;
        exit;
    }

    public function beforeException(Event $event, Dispatcher $dispatcher){
        var_dump($dispatcher->getTaskName());
        exit;
    }

    /**
     * @param  array $parsedOptions
     * @return array
     */
    public function setUpTaskDefinition(array $parsedOptions)
    {
        $task   = null;
        $action = null;
        $params = [];

        if (isset($parsedOptions[0])) {
            $task = $parsedOptions[0];
        }

        if (isset($parsedOptions[1])) {
            $action = $parsedOptions[1];
        } elseif (strpos($task, self::SEPARATOR)) {
            list($task, $action) = explode(self::SEPARATOR, $task, 2);
        }

        if (count($parsedOptions) > 2) {
            $params = array_slice($parsedOptions, 2);
        } elseif (count($parsedOptions) > 1) {
            $params = array_slice($parsedOptions, 1);
        }

        if ($task == null) {
            $task = $this->findCommandFromOptions($parsedOptions);
        }

        return compact('task', 'action', 'params');
    }

    protected function findCommandFromOptions(array $options)
    {
        if (empty($options)) {
            return null;
        }

        switch (key($options)) {
            case 'H':
            case 'help':
                return 'help';
            case 'version':
            case 'V':
                return 'version';
            case 'list':
                return 'commands';
        }

        return null;
    }
}
`

For info - i copied CliInputListener from Phacon forum repo - I hope it will not be a problem.

**Comment by ruudboon** [comment]
I'm unable to reproduce it based on the code above. Please share a link to the project or try to isolate the issue so we can have a look. 
We have a test covering the boot event (https://github.com/phalcon/cphalcon/blob/master/tests/cli/Cli/Console/HandleCest.php#L221) here that is passing.

**Comment by ivanovbg** [comment]
Repo is this - https://github.com/ivanovbg/softmotion-cms

**Comment by ivanovbg** [comment]
When i dump eventsManager i see this - event is attach: 
```
object(Phalcon\Events\Manager)#108 (4) {
  ["collect":protected]=>
  bool(false)
  ["enablePriorities":protected]=>
  bool(false)
  ["events":protected]=>
  array(1) {
    ["console"]=>
    object(SplPriorityQueue)#110 (3) {
      ["flags":"SplPriorityQueue":private]=>
      int(1)
      ["isCorrupted":"SplPriorityQueue":private]=>
      bool(false)
      ["heap":"SplPriorityQueue":private]=>
      array(1) {
        [0]=>
        array(2) {
          ["data"]=>
          object(SFC\Listeners\CliInputListener)#109 (0) {
          }
          ["priority"]=>
          int(100)
        }
      }
    }
  }
  ["responses":protected]=>
  NULL
}

```

**Comment by ivanovbg** [comment]
Hi, again. 

I tried this: 

```
container('eventsManager')->attach('console', new CliInputListener());
$this->setEventsManager(container('eventsManager'));
```

And everything is work, no why?

**Comment by ruudboon** [comment]
I think your `container()` global function is returning a new instance.

**Comment by ivanovbg** [comment]
container() return $default = Di::getDefault();

**Comment by ivanovbg** [comment]
I add ` $this->app->setEventsManager(container('eventsManager'));` in my bootstrap class, after load providers and every thing is work fine. Thank you very much for your time and sorry for the mistake.

Greetings from Bulgaria

**Comment by ruudboon** [comment]
Thnx for using Phalcon!
