### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by JuriBurakov** [phalcon/cphalcon#15069]
Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste output here
```

**Expected behavior**

```php
// paste code
```

**Screenshots**

**Details**
 - Phalcon version: (`php --ri phalcon`)
 - PHP Version: (`php -v`)
 - Operating System:
 - Installation type: Compiling from source || installing via package manager
 - Zephir version (if any):
 - Server: Nginx | Apache | Other
 - Other related info (Database, table schema):

**Additional context**

**Comment by ruudboon** [comment]
@JuriBurakov Can you update your issue with the requested information? Otherwise I need to close this one.

**Comment by ruudboon** [comment]
Looks like spam to me
