### ISSUE TITLE
[BUG]: The routing controller name changes when using syntax sugar.

### ISSUE THREAD

**Issue by fagai** [phalcon/cphalcon#15067]
Example

```php
$eventsManager->attach(
    "dispatch:beforeDispatch",
    function(\Phalcon\Events\Event $event, \Phalcon\Mvc\Dispatcher $dispatcher) {
        log($dispatcher->getControllerName());
    }
);
```

```php
$router->add('hoge/huga', ['controller' => 'HogeHoge', 'action' => 'huga'];
// controller_name: HogeHoge
$router->add('hoge/huga', ['controller' => 'hoge-hoge', 'action' => 'huga'];
// controller_name: hoge-hoge

$router->add('hoge/huga', 'HogeHoge::huga'];
// controller_name: hoge_hoge
```

The operation is different when passing in an array and passing in a string.
Because it is uncamelize by the following process.

https://github.com/phalcon/cphalcon/blob/634e7233a86780c9509614a8d835b188c8be76e5/phalcon/Mvc/Router/Route.zep#L451

Although it is a syntax sugar, the processing is different...

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15770
