### ISSUE TITLE
[BUG]: Can't install Phalcon on Ubuntu 20.04 with Nginx + PHP FPM (7.4)

### ISSUE THREAD

**Issue by contactjavas** [phalcon/cphalcon#15078]
**Describe the bug**
Always failed to install Phalcon with various way. Try it in all available methods if you want.

**To Reproduce**
- Try Ubuntu 20.04
- Install Nginx
- Install PHP-FPM 7.4
- Install Phalcon with it's requirement

**Screenshots**
https://twitter.com/contactjavas/status/1269958005371490305/photo/1

**Details**
 - Ubuntu 20.04
 - Nginx
 - PHP FPM 7.4
 - Latest Phalcon (mainline, stable)
 - Installation type: Whatever method available, the installation failed

**Additional context**
I can provide the server/ SSH to do the experiment to fix the issue.

**Comment by ruudboon** [comment]
Thnx for reporting this. Closing this in favour of https://github.com/phalcon/cphalcon/issues/14958

**Comment by ruudboon** [comment]
@contactjavas Maybe it's a good idea if I give it a shot on your server. Can you ping me on Discord so I can drop you my PK?

**Comment by contactjavas** [comment]
Great! i've DM-ed you @ruudboon
