### ISSUE TITLE
[BUG]: Cannot access private property Phalcon\\Http\\Message\\ServerRequest::$attributes

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#15088]
**Describe the bug**
This error caused by compilation with **wrong** version of **Zephir** and Phalcon 4.0.5. But I want to check if current error do not occur in `4.1.x` branch.

During call of `withAttribute()` method, occur error:

```
Cannot access private property Phalcon\\Http\\Message\\ServerRequest::$attributes
```

**To Reproduce**

```php
$request = new ServerRequest();
$request->withAttribute('key', 'value');
```

**Expected behavior**
No error.

**Details**
 - Phalcon version: (`4.0.5`)
 - PHP Version: (`7.4.6`)
 - Installation type: Compiling from source
 - Zephir version (if any): `0.12.19`

**Comment by ruudboon** [comment]
Can you drop a pull with a unit test for this?

**Comment by Jeckerson** [comment]
```
php -r 'echo Phalcon\Version::get();' // 4.1.0
```

```
<?php

$request = new \Phalcon\Http\Message\ServerRequest();
$request->withAttribute('key', 'value');
```

No error on call.
