### ISSUE TITLE
debian package - PHP FPM require php-psr 

### ISSUE THREAD

**Issue by lota** [phalcon/cphalcon#15082]
I successfully installed your Debian package from
https://packagecloud.io/phalcon/stable

on my servers we use PHP+FPM and seems phalcon extension require php-psr to works

```
PHP Warning:  Cannot load module 'phalcon' because required module 'psr' is not loaded in Unknown on line 0
PHP Fatal error:  Uncaught Error: Class 'Phalcon\Version' not found in Command line code:1
```

but in control file I found only something like

```
Depends: ucf, libc6 (>= 2.14), phpapi-20190902
Suggests: php7.4-mysql, php7.4-sqlite3, php7.4-pgsql, php7.4-memcached
```

could be useful insert something like

`Depends: ucf, php-psr, phpapi-20190902 | phpapi-20180731 | phpapi-20170718, libc6 (>= 2.14)`

complete output from another debian package

```
apt-cache show php-phalcon4
Package: php-phalcon4
Version: 4.0.6-1+0~20200518.4+debian9~1.gbp1d3528
Architecture: amd64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 17848
Pre-Depends: php-common (>= 2:69~)
Depends: ucf, php-psr, phpapi-20190902 | phpapi-20180731 | phpapi-20170718, libc6 (>= 2.14)
Breaks: php-phalcon (<< 3.4.5-2)
Replaces: php-phalcon (<< 3.4.5-2)
Provides: php-phalcon, php7.2-phalcon4, php7.3-phalcon4, php7.4-phalcon4
Homepage: https://phalconphp.com/
Priority: optional
Section: php
Filename: pool/main/p/php-phalcon4/php-phalcon4_4.0.6-1+0~20200518.4+debian9~1.gbp1d3528_amd64.deb
Size: 3257566
SHA256: 91836f3aed0e89c2e19051c293d5a96b0c248e74d6060189b44a8a2c97ccd866
SHA1: 8f8f366cdc7d8ec5dbf51a69d6c507f224b1a791
MD5sum: 72b0e20f980bba0e961f7ab59adae5cd
Description: full-stack PHP framework delivered as a C-extension
 Phalcon is an open source full stack framework for PHP, written as a
 C-extension. Phalcon is optimized for high performance. Its unique architecture
 allows the framework to always be memory resident, offering its functionality
 whenever it’s needed, without expensive file stats and file reads that
 traditional PHP frameworks employ.
Description-md5: c7e4e38f1b2936c741eeb19f150112a1
```

HTH
Alessandro - Lota

**Comment by Jurigag** [comment]
I agree. I think when installing via apt phalcon 4 there should be also psr installed.

**Comment by lota** [comment]
`Depends: ...php-psr...`
should be enough

**Comment by HiralRajgor** [comment]
You must need to add the **psr.so**  or your **php-psr** file name under the **extension** keword to **phalcon.ini** file of php,

**Comment by lota** [comment]
my post is only about how Debian packaging works

Debian sysadmin wish use "apt-get" and nothing else, a Debian package should declare in Depends others packages required

in short: your phalcon package is wonderful but "control" file is incomplete, on Debian 9.13 I need to do manually

apt-get install php7.2-psr
apt-get install php7.3-psr
apt-get install php7.4-psr

to get Phalcon load in phpinfo();
![2021-03-11_10-07](https://user-images.githubusercontent.com/956392/110764460-6139b380-8253-11eb-922f-fcabd0d5af51.png)

The better solution could be someone upload phalcon package in official Debian repository

HTH
Alessandro - https://qa.debian.org/developer.php?login=lota@nonlontano.it

**Comment by Jeckerson** [comment]
Implemented in https://github.com/phalcon/packagecloud

![](https://cdn.discordapp.com/attachments/310910488152375297/869342005384314910/unknown.png)
