### ISSUE TITLE
[BUG]: Installation instructions for Ubuntu 20.04 no longer valid

### ISSUE THREAD

**Issue by slothstronaut** [phalcon/cphalcon#15094]
**Describe the bug**
The installation instructions for source, PECL, and from package all have errors using Ubuntu 20.04.

Here is the command straight from the documentation to install PHP 7...

```
$ sudo apt-get install php7-dev php7-mysql gcc libpcre3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7-dev
E: Unable to locate package php7-mysql
```

On Ubuntu 20.04, need to use this to install: 

```
sudo apt install php7.4-dev php7.4-mysql gcc libpcre3-dev
```

Try any part of the documentation, nothing works.

Ubuntu 20.04 has been out for months.

See issues related to PECL and packages on another thread: https://github.com/phalcon/cphalcon/issues/14958

**Comment by Jeckerson** [comment]
Related - https://github.com/phalcon/cphalcon/issues/14958

**Comment by Jeckerson** [comment]
Done in https://github.com/phalcongelist/packagecloud/issues/63
