### ISSUE TITLE
[BUG]: Phalcon\Mvc\Model::cloneResultMap(): __clone method called on non-object in Phalcon/Mvc/Model/Query

### ISSUE THREAD

**Issue by djvibegga** [phalcon/cphalcon#15090]
Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**
I called Model::findFirst(). If I use caching I get the error mentioned above.

**Comment by ruudboon** [comment]
Can you give us some more information (like version, os etc) and some code example to reproduce this?

**Comment by zsilbi** [comment]
Closing this for now.
Please feel free to reopen it, if you would like to provide all the required information to locate the problem.
