### ISSUE TITLE
dispatcher forward method dispatch other controller method failed 

### ISSUE THREAD

**Issue by shuqiangzhou** [phalcon/cphalcon#15097]
phpinfo
![image](https://user-images.githubusercontent.com/26402118/85915473-53d1ca00-b87a-11ea-881e-dfeef8acf4d2.png)

Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.4
Build Date => Feb 22 2020 11:42:14
Powered by Zephir => Version 0.12.17-6724dbf

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On

When I perform forwarding to other controllers in the basic controller initialization method, $this->dispatcher->forward(), this will fail scheduling!

basc controller :
```php
<?php
declare(strict_types=1);
namespace At\Controllers;

use At\Modules\Backend\Controllers\AuthenticationController;

class BackendController extends WebController
{
    protected $Authentication = [];

    protected function onConstruct()
    {
        $this->rbac();
    }

    protected function rbac(){
        if(!$this->Authentication){
            if(in_array('*',$this->Authentication)){
                return true;
            }
            if(!in_array($this->dispatcher->getActionName().$this->dispatcher->getActionSuffix(),$this->Authentication)){
                phpinfo();
                print_r(get_class_methods($this->dispatcher));
                //dispatcher fail
                $this->dispatcher->forward([
                    "controller" => "Authentication",
                    "action"     => "no_permission",
                ]);
                die;
                return $this->dispatcher->callActionMethod(new AuthenticationController(),'noAction');
            }


            if(!$this->session->get("admin")){
                return $this->response->redirect("backend/login/index");
            }


        }
    }


}

```

dispatched controller:
```php
<?php
declare(strict_types=1);

namespace At\Modules\Backend\Controllers;
use At\Controllers\BackendController;
class AuthenticationController extends BackendController
{
    protected $Authentication = ['*'];

    public function noPermissionAction()
    {
        if($this->request->isAjax()){
            return $this->_ajax([],0,'您没有权限访问此内容');
        }

        return $this->_ajax([],0,'您没有权限访问此内容');
    }

}


```
Maybe I can only use the call event for authentication

**Comment by zsilbi** [comment]
This is not a bug.

If you `die` after `$this->dispatcher->forward` your application will stop there.
You should use `return` instead of `die` in your action after forwarding if you want to stop the action.
