### ISSUE TITLE
[BUG]:  Phalcon Query Builder cuts fieldname with 'not' in the beginning

### ISSUE THREAD

**Issue by JanEhlbeck83** [phalcon/cphalcon#15100]
**Describrion:**
I tried to use the query builder and when I selected a field named 'notification' e.g.: user.notification I get an error that the field user.ification doesn't exist. The query builder seems to remove the 'not' of 'notification'. It works fine when I double the the word 'not' e.g.: user.notnotification    

**To Reproduce**
The reproduction is easy. Just use the query builder and try to fetch the field 'notification' of any table 

`$this->modelsManager->createBuilder()
            ->columns(['cMI.name', 'cMI.type', 'cMI.uniqueName', 'cMI.notification', 'creatorName' => 'creator.name', 'creatorName' => 'creator.name', 'modifierName' => 'modifier.name'])
            ->from(['cMI' => 'Common\Models\CompanyMediaImages'])
            ->leftJoin('Common\Models\Users', 'cMI.createdBy=creator.id', 'creator')
            ->leftJoin('Common\Models\Users', 'cMI.modifiedBy=modifier.id', 'modifier')
            ->where('cMI.companyId = :companyId:', ['companyId' => $this->company->id])
            ->orderBy('cMI.createdAt DESC');
 $currentPage = isset($_GET['page']) ? (int)$_GET['page'] : 1;

        $paginator = new QueryBuilder(
        [
            "builder" => $builder,
            "limit"   => $this->itemsPerPage,
            "page"    => $currentPage,
        ]);
        $paginationData = $paginator->paginate();
`
**Expected behavior**
I expected that the fieldname not got cutted and getting a valid resultset

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: 7.4.7
 - Operating System: Windows 10
 - Installation type: compiled dll 
 - Server: Apache (XAMPP)

**Comment by JanEhlbeck83** [comment]
Sorry for the issue. I saw there are many people faced this problems. [Dublicated Bug Report] Finally I found a solution by adding [] around the cMI.notification. Don't wanted to disturb you... Can be closed... I guess

**Comment by zsilbi** [comment]
Duplicate issue, see: #14641
