### ISSUE TITLE
[BUG]: Paginate - 502 Bad Gateway - PHP 7.4.8

### ISSUE THREAD

**Issue by yunusberkayaksoy** [phalcon/cphalcon#15109]
Today I updated the php from 7.4.7 to 7.4.8 and the application on phalcon4 gives a 502 error.

**Details**
Phalcon version: 4.0.6
PHP Version: 7.4.8
Operating System: Ubuntu 18.04
Installation type: Package of Repository
Zephir version (if any): 0.12.17-6724dbf
Server: Nginx

**Problem**
$paginator->paginate();
When I run the function it gets 502 error.

**Nginx Error Log**
[error] 12630#12630: *883 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: -, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:"

**PHP-FPM Log**
WARNING: [pool www] child 30939 exited on signal 11 (SIGSEGV - core dumped) after 89.772629 seconds from start

**Comment by ruudboon** [comment]
Closing this as related to https://github.com/phalcon/cphalcon/issues/15109
