### ISSUE TITLE
[NFR]: Add ConfigInterface

### ISSUE THREAD

**Issue by BeMySlaveDarlin** [phalcon/cphalcon#15106]
**Is your feature request related to a problem? Please describe.**
It smells as hack typehinting `Phalcon/Config` in other services when extending it by custom class => feels as LSP violation.

**Describe the solution you'd like**
- Add `Phalcon/ConfigInterface` filled with most methods from `Phalcon/Config` itself and from `Phalcon/Collection`.
- Implement it in `Phalcon/Config`.
- Replace all internal typehints to interface.

**Describe alternatives you've considered**
It also can be `Phalcon/CollectionInterface`, but less usable.

Thanks.

**Comment by niden** [comment]
Resolved in #15114
