### ISSUE TITLE
[BUG]: Phalcon 3.4 Caching Performance Is Slower Than Database Query

### ISSUE THREAD

**Issue by nhhoanglong** [phalcon/cphalcon#15101]
Hi , i have an issue with cache.
When i use model cache for caching query , it was very show than i use query on database. Already test on APC and Memcache
$di->set(
        'modelsCache',
        function () {
            $frontCache = new FrontData(
                [
                    "lifetime" => 259200,
                ]
            );
              // $cache = new Apc(
              //     $frontCache,
              //     [
              //         "prefix" => "models"
              //     ]
              // );
              $cache = new Memcache(
                $frontCache,
                [
                    "host"       => "localhost",
                    "port"       => 11211,
                    "persistent" => false,
                ]
            );
            return $cache;
        }
      );

$users = Users::find(['cache'=>['key'=>"all_user"]]); 
I run it first time to save the cache , then run second time to read the cache and this is slowly that then query without cache about 50% . 

I don't know why , should it be an issue ? 

**Details**
 - Phalcon version: 3.4
 - PHP Version: 5.6
 - Operating System: Linux
 - Installation type: Compiling from source 
 - Zephir version (if any): Version 0.9.2a-dev
 - Server: Apache 
 - Other related info (Database, table schema):

**Comment by Jurigag** [comment]
It might happen like this because there is additional time spent for serializing and unserializing.

What i can suggest is don't use objects(use toArray here for example) and use IgBinary as frontend for example.

**Comment by Jeckerson** [comment]
Do not store big amount of data as serialized object. 

In your case your query is simple and will return all data that is in database. Which means bottleneck will be in network (when data is transferred from SQL to PHP). So it no need to cache that information inside another data format. You won't gain any performance boost, or on the contrary, like in your case - it is even slower.

Make cache when query is complex and/or slow... Tune your code according clients and business requirements.

**Comment by Jeckerson** [comment]
Just noticed, that you specified `PHP Version: 5.6`. That version is much slower, then `PHP 7.x` in terms of serialized data iteration.

**Comment by Jeckerson** [comment]
@nhhoanglong In case if you have related questions how to optimize your code with cache, please follow the Discord link and community might help you.
