### ISSUE TITLE
[BUG]: \Phalcon\Http\Response\CookiesInterface::set options parameter

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#15120]
**Describe the bug**
https://github.com/phalcon/cphalcon/blob/master/phalcon/Http/Response/CookiesInterface.zep#L64 here is options parameter defined which is not used anywhere in https://github.com/phalcon/cphalcon/blob/master/phalcon/Http/Response/Cookies.zep#L235

**Expected behavior**
Don't have this parameter, or do something with it.

**Details**
 - Phalcon version: 4.0
 - PHP Version: 7.4
 - Operating System: Ubuntu 18.04
 - Installation type: Compiling from source
 - Zephir version (if any): 0.12.19
 - Server: Nginx
 - Other related info (Database, table schema):

**Comment by zsilbi** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/15150
