### ISSUE TITLE
[BUG]: Unused Phalcon\Mvc\Router::uriSource

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#15123]
**Describe the bug**
This property is not used anywhere.

**Expected behavior**
Remove it in next version

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: 7.4
 - Operating System: ubuntu 18.04
 - Installation type: Compiling from source
 - Zephir version (if any): 0.12.19
 - Server: Other
 - Other related info (Database, table schema):

**Comment by zsilbi** [comment]
Fixed in #15147
