### ISSUE TITLE
[BUG]: When saving [],0,'0',false in cache null is returned

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#15125]
**Describe the bug**
When using libmemcached for cache adapter and saving empty array or false or 0 and then getting a key null is returned instead of empty array/0/false.

**To Reproduce**

```php
use Phalcon\Cache;
use Phalcon\Cache\AdapterFactory;
use Phalcon\Storage\SerializerFactory;

$serializerFactory = new SerializerFactory();
$adapterFactory    = new AdapterFactory($serializerFactory);

$options = [
    'defaultSerializer' => 'Php',
    'lifetime'          => 7200
];

$adapter = $adapterFactory->newInstance('libmemcached', $options);

$cache = new Cache($adapter);
$cache->set('test', [], 7200);
var_dump($cache->get('test')); // returns NULL

$cache->set('test', 0, 7200);
var_dump($cache->get('test')); // returns NULL

$cache->set('test', false, 7200);
var_dump($cache->get('test')); // returns NULL

$cache->set('test', '0', 7200);
var_dump($cache->get('test')); // returns NULL

$memcached = new \Memcached();
$memcached->addServer('localhost', 11211);
$memcached->setOption(Memcached::OPT_SERIALIZER, Memcached::SERIALIZER_PHP);
$memcached->set('test', [], 7200);
var_dump($memcached->get('test')); // returns array(0) {}

$memcached->set('test', 0, 7200);
var_dump($memcached->get('test')); // returns int(0)

$memcached->set('test', '0', 7200);
var_dump($memcached->get('test')); // returns string(1) "0"
```

**Expected behavior**
Return empty array instead of null

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: 7.2, 7.4
 - Operating System: Ubuntu 18.04
 - Installation type: Compiling from source 
 - Zephir version (if any): 0.12.19
 - Server: Cli
 - Other related info (Database, table schema):

**Comment by Jurigag** [comment]
As a workaround for now i just override set/get methods and saved other value for this empty values and then return correct one if someone other had similar issue.

**Comment by Jeckerson** [comment]
DId you try to specify server config?

```
$options = [
    'defaultSerializer' => 'Json',
    'lifetime'          => 7200,
    'servers'           => [
        0 => [
            'host'   => '10.4.13.100',
            'port'   => 11211,
            'weight' => 1,
        ],
    ],
];
```

**Comment by Jurigag** [comment]
Yes, when saving 1 or 2 or any non empty value it works correctly @Jeckerson

**Comment by zak-wojtek77** [comment]
I use Phalcon 4.0.6 and also is the same problem. I use cache with file and cache with APCu. In cache file is correct write value "false" in file on the disk, error is in method "get()".

**Comment by zak-wojtek77** [comment]
It is problem:
```php
    // phalcon/Storage/Adapter/AbstractAdapter.zep
    protected function getUnserializedData(var content, var defaultValue = null) -> var
    {
        // HERE IS PROBLEM
        if !content {
            return defaultValue;
        }

        // .....
    }
```
https://github.com/phalcon/cphalcon/blob/master/phalcon/Storage/Adapter/AbstractAdapter.zep
line 208

**Comment by Jeckerson** [comment]
Why save empty value cache when it can be just removed?

**Comment by zak-wojtek77** [comment]
Empty value such FALSE, 0, '0', [] is normal value. For example, any product has price = 0, it does not mean that the produkt stop exists.

**Comment by Jurigag** [comment]
Exactly empty value is normal value.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15350
