### ISSUE TITLE
Difficulty with localizing the error.

### ISSUE THREAD

**Issue by rigin** [phalcon/cphalcon#15127]
Hello, I have a problem that I do not know how to solve.

While I was working with the console part of my application, my web interface broke.
The application crashes without any error messages.

In file:
`/public/index.php`

The process reaches the operator:
 $handle = $application->handle($_SERVER["REQUEST_URI"]);
and silently crashes without error messages.
The controller is not connected.

Please tell me how you can localize the cause of the error.

```
<?php
namespace Cat;
...................
...................
    $application = new Application($di);
  // test point 1
    $handle = $application->handle($_SERVER["REQUEST_URI"]); // error point
   // test point 2
    echo $handle->getContent();
```
content of $application variable

https://yadi.sk/d/GX48fgxFAjKoQA

**Comment by yassinrais** [comment]
Hello @rigin , 

Have you check that is not caused by an exit() call ? in your application code or something like that ?

**Comment by rigin** [comment]
I think I figured it out, 
There was a problem with the namespace.
Returned to the original state and everything worked.
