### ISSUE TITLE
[BUG]: modelsManager Query Builder issue column name 'note', parse as "not" + Column 'e' doesn't belong 

### ISSUE THREAD

**Issue by yassinrais** [phalcon/cphalcon#15122]
**Describe the bug**
When  i use note as a column name in the queryBuilder
they wrong parse it , the builder considere it as a "not" + a column named "e" 
 

```php
$builder = $this->modelsManager->createBuilder()
                          ->columns('id, name, title, note, hostname, ip, port')
                          ->from(Discordbots::class);
```

> Provide minimal script to reproduce the issue

```php
    columns('id, name, title, note, hostname, ip, port')
```

**Expected behavior**
expected that note is a column name and not an operation "not"

**Details**
 - Phalcon version: 4.0.3
 - PHP Version: 7.3.12 (ZTS MVC15 - x64)
 - Operating System: Windows
 - Installation type: Dll
 - Zephir version (if any): 3.3.12
 - Server: Apache (wamp64)
 
sorry if this is duplicated before ♥

**Comment by Jurigag** [comment]
Does `[note]` work?

**Comment by yassinrais** [comment]
@Jurigag thx its work good !

**Comment by Jurigag** [comment]
Don't close it please, it's still a bug which sould be addressed, this is just workaround for now.

**Comment by yassinrais** [comment]
@Jurigag i belive that normally in a `createBuilder()->columns()` method .. we dont need to check if `not` inside , because it just select the columns names . also i made a  search about "using `not` in `select columns`"  and no results found that we use it

**Comment by Jurigag** [comment]
@yassinrais any idea if the same error happens when trying to save model with property note? Because if yea then we would need most likely to increase priority of this.

**Comment by yassinrais** [comment]
no , the are just this one error 

all worked fine !

**Comment by zsilbi** [comment]
Duplicate issue, see: #14641
