### ISSUE TITLE
[BUG]: Strange error with "$volt->getCompiler();"

### ISSUE THREAD

**Issue by Roninju** [phalcon/cphalcon#15137]
Hi. I don't know if it's a mistake or something I'm not doing right. When I add functions or filters to Volt and then in the view I use a function of an object, an error occurs.

For example.
When registering the Volt service:
```php
$compiler = $volt->getCompiler();
$compiler->addFunction('shuffle', 'str_shuffle');
```

In the view:
```html
{{ flash.output() }}
```

Produces:
```html
Notice: Undefined variable: flash in...
```
```html
Fatal error: Uncaught Error: Call to a member function output() on null in...
```

However, if I call Flash in PHP or remove the Volt compiler, it works fine.

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: 7.4.6
 - Operating System: Windows 10
 - Server: Apache 2.4.43

**Comment by ruudboon** [comment]
Can you share your di setup, especially the full part where you register your view?

**Comment by Roninju** [comment]
In the end it is not a bug. I just wasn't passing the DI to Volt. My fault, sorry. I close the topic.
