### ISSUE TITLE
[BUG]: phalcon3.4.5 Execute findFirst|find when the transaction is rolled back，throw new RuntimeException

### ISSUE THREAD

**Issue by xyqweb** [phalcon/cphalcon#15138]
**Describe the bug**
Execute findFirst|find when the transaction is rolled back
threw new RuntimeException Trying to call method prepare on a non-object

**To Reproduce**
> RuntimeException Object
(
    [message:protected] => Trying to call method prepare on a non-object
    [string:Exception:private] => 
    [code:protected] => 0

```php
$transaction = new \Phalcon\Mvc\Model\Transaction\Manager();
$transaction->get();
try {
      //Business code
     $transaction->commit();
} catch (\Exception $e) {
      $transaction->rollback();
}
BaseMerchantCustomer::findFirst([
       'customer_id=:customer_id:',
       'bind' => [
           'customer_id' => 1,
       ],
]);
```

**Details**
 - Phalcon version: 3.4.5
 - PHP Version: 7.1.24
 - Operating System: Centos7.2
 - Installation type: Compiling from source 
 - Zephir version (if any):Version 0.10.16-6826149172
 - Server: Nginx 
 - Database,): mysql5.7

**Comment by Jeckerson** [comment]
Are you sure that your code do not generate SQL error?

**Comment by xyqweb** [comment]
No SQL error，You can throw an error to roll back transaction, and then execute a query

**Comment by xyqweb** [comment]
This is the entire test code and error message
<img width="1358" alt="QQ20200831-210129" src="https://user-images.githubusercontent.com/12839346/91722755-4cf26b00-ebcd-11ea-83c1-b5d3c4b222c8.png">

**Comment by weiyuyungx** [comment]
$transaction_manager = new \Phalcon\Mvc\Model\Transaction\Manager();
$transaction = $transaction_manager->get();
$transaction->begin();
.........
