### ISSUE TITLE
[BUG]: CriteriaInterface where method differs from implementation method parameter.

### ISSUE THREAD

**Issue by fagai** [phalcon/cphalcon#15144]
**Describe the bug**

CriteriaInterface where method differs from implementation method parameter.

https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/Model/CriteriaInterface.zep#L248
```
public function where(string! conditions) -> <CriteriaInterface>;
```

https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/Model/Criteria.zep#L808

```
public function where(string! conditions, var bindParams = null, var bindTypes = null) -> <CriteriaInterface>
```

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: PHP 7.4.10
 - Operating System: debian(docker)
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Apache
 - Other related info (Database, table schema):

**Comment by zsilbi** [comment]
Fixed in #15146
