### ISSUE TITLE
[BUG]: use memcached to store sessions ,but cannot work well for first serveral times(15?)

### ISSUE THREAD

**Issue by feelingseas** [phalcon/cphalcon#15141]
**Describe the bug**
i use memcached to store sessinos.but when i restart the memcached service (service memcached restart),i found the session doesnot work well(about for the first 15 times).
how i found this ?I have a login page,I use the wrong password to login,then i use flash session to show the login failed message,but i cannt get the message in the login page(login failed will redirect back).after 15 times of failed login,then if i login failed ,then the login page will show the error message like  "wrong password".

eg:
service session like this :
```
$di->setShared('session', function () {
    /*
    //this default config works well.
    $session = new SessionManager();
    $files = new SessionAdapter([
        'savePath' => sys_get_temp_dir(),
    ]);
    $session->setAdapter($files);
    $session->start();

    return $session;
    */
    
    
    
    $options = [
        'client'  => [],
        'servers' => [
                [
                    'host'   => 'memcachedhost',
                    'port'   => 11211
                    //'weight' => 1
                ]
        ]
    ];
    
    $session           = new Manager();
    $serializerFactory = new SerializerFactory();
    $factory           = new AdapterFactory($serializerFactory);
    $libmemcached      = new Libmemcached($factory, $options);
    
    $session
    ->setAdapter($libmemcached)
    ->start();
    
    return $session;
});
```
----------------------------
```
class IndexController extends ControllerBase
{   
	//set session and go to getAction
    public function indexAction()
    {
        $this->session->set('role', 'teacher');
        return $this->response->redirect("/index/get");
        
    }
	//first 15 times ,echo empty ,then always echo "teacher";
    public function getAction()
    {
        echo $this->session->get('role')."<br>";        
    }
       

}
```

so ,it's a bug or wrong config about memcached?
if i use file(default) to store sessions,it works well.

php version:7.4.8
phalcon version :4.0.4 and 4.0.6
php-memcached:3.1.5
server memcached:1.6.6

**Comment by Jeckerson** [comment]
Try to check on the same action (`indexAction()`), without redirect:

```
$this->session->set('role', 'teacher');
echo $this->session->get('role')."<br>"; 
```

**Comment by feelingseas** [comment]
> Try to check on the same action (`indexAction()`), without redirect:
> 
> ```
> $this->session->set('role', 'teacher');
> echo $this->session->get('role')."<br>"; 
> ```

this is ok.it alwyas echo "teacher".and i have checked that session SET always success.GET is not good.

**Comment by zsilbi** [comment]
@feelingseas I ran your code, and found no problems at all.

Please test your Memcached independently from Phalcon and Session.
Also please describe your operating system, etc.

**Comment by zsilbi** [comment]
Closing this for now, please feel free to reopen if you would like to provide more information.
