### ISSUE TITLE
[NFR]:  Add Method getInherits in Acl\Memory : Get Role Herits

### ISSUE THREAD

**Issue by yassinrais** [phalcon/cphalcon#15154]
**Is your feature request related to a problem? Please describe.**
Need a methd ``getInherits`` in Acl\Memory - roleInherits is protected (no get method exist)

**Describe the solution you'd like**
$acl->getInherits(String $roleName = null ) : array  

_I need this method to get the menus allow for each role but at the moment i have a role inHerits i need to get the roles herited menus_

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15707
