### ISSUE TITLE
[BUG]: return in the variable name

### ISSUE THREAD

**Issue by ismail0234** [phalcon/cphalcon#15156]
**Describe the bug**
If there is a return in the variable name, it creates a problem.

**Example**
```php
{{ reservation.extras.travel.return.referenceNo }}
```

**Error**
![Adsız](https://user-images.githubusercontent.com/20711301/93176001-46213780-f739-11ea-9aa2-e8eaa57f5db0.png)

**Details**
 - Phalcon version: 3.4.6
 - PHP Version: PHP 7.3
 - Operating System: Linux (Centos 7)
 - Installation type: package manager
 - Zephir version (if any): No

**Comment by niden** [comment]
`return` is a reserved word for Volt. You can use a different name for the variable so as to avoid collisions.

Apologies for taking this long to reply to this. 

Closing it.

**Comment by ismail0234** [comment]
> `return` is a reserved word for Volt. You can use a different name for the variable so as to avoid collisions.
> 
> Apologies for taking this long to reply to this.
> 
> Closing it.

only four years later
