### ISSUE TITLE
Again facing the Uniqueness error on updating

### ISSUE THREAD

**Issue by sanmayad** [phalcon/cphalcon#15168]
I think this issue was resolved in phalcon3, but I think the 4 has got the issue again.

**Comment by Jeckerson** [comment]
Hello. Please provide code examples.

**Comment by sanmayad** [comment]
@Jeckerson Hi,

This is in my model:

`

    public function validation()
    {
        $validator = new Validation();
        
        $validator->add(
        	[
		    'raw_import_data',
            	],
	    	new Uniqueness(
		[
		    "model"   => new $this,
		    "message" => "Duplicate transaction found",
            	    'allowEmpty' => true,
		]
		)
        );
        
        $validator->add(
            'transaction_date',
	    	new Date(
		[
		    //"model"   => $this,
		    "message" => ":field must be a Date type",
		]
		)
        );

        return $this->validate($validator);
    }`

and this goes in controller:

`

			$bank_statement = BankStatement::findFirst(['id='.$id,'company_id',$cid]);
			if($bank_statement){
				$bank_statement->category = 'unique';
				if (!$bank_statement->update()) {
				    foreach ($bank_statement->getMessages() as $message) {
					$this->flash->error((string) $message);
				    }
				} else {
				    	$this->flash->success("Success");
			    	 	// after success
			    	 	
				}
				
			} else{
				$this->flash->success("BankStatement was not found.");			
			}`

**Comment by Jeckerson** [comment]
Exist option called `except`

https://github.com/phalcon/cphalcon/blob/634e7233a86780c9509614a8d835b188c8be76e5/phalcon/Validation/Validator/Uniqueness.zep#L107

So, during model update, add this option.

```
$validator->add(
            'raw_import_data',
            new Uniqueness(
                [
                    "model"   => new $this,
                    "message" => 'Duplicate transaction found',
                    'allowEmpty' => true,
                    'except' => $this->raw_import_data
                ]
            )
        );
```

Also, you passed wrong parameters in this line:

```
$bank_statement = BankStatement::findFirst(['id='.$id,'company_id',$cid]);
```

Need to be changed:

```
$bank_statement = BankStatement::findFirst([
    'id = ?0 AND company_id = ?1',
    'bind' => [$id, $cid],
]);
```

**Comment by Jeckerson** [comment]
https://github.com/phalcon/docs/issues/2742

**Comment by sanmayad** [comment]
thanks a lot @Jeckerson :)  Yeah.

but shouldn't it be automatically understanding it's an update query! I understand we have made validation as a separate plugin to be used anywhere, but may be we need to think about the context too.

Plus the documentation is a must.
This one plus the allowEmpty option etc.

I think I should add these to documentation at phalcon/docs and push. Docs need to be improved a lot. 
We can have like "Common difficulties" and "Current issues/common issues" section in the documentation.
That'll keep it awesome.

**Comment by sanmayad** [comment]
@Jeckerson but now it's not validating on create or save function only except for null values in DB

**Comment by Jeckerson** [comment]
@sanmayad Use `beforeValidationOnUpdate()` and `beforeValidationOnCreate()` methods inside model class, instead of `validation()`.

**Comment by Jeckerson** [comment]
> but shouldn't it be automatically understanding it's an update query! I understand we have made validation as a separate plugin to be used anywhere, but may be we need to think about the context too.

No, because there are cases when you need specific rules for update of create.

**Comment by Jeckerson** [comment]
> I think I should add these to documentation at phalcon/docs and push. Docs need to be improved a lot.

We are always open for the contributions!

**Comment by sanmayad** [comment]
> @sanmayad Use `beforeValidationOnUpdate()` and `beforeValidationOnCreate()` methods inside model class, instead of `validation()`.

yes already done. Thanks
