### ISSUE TITLE
[BUG]: 'prefix' option does not work for Phalcon\Session\Adapter\Redis

### ISSUE THREAD

**Issue by poz** [phalcon/cphalcon#15184]
**Describe the bug**
In the source documentation: https://github.com/phalcon/cphalcon/blob/v4.0.0/phalcon/Session/Adapter/Redis.zep , it was shown that the options can accept prefix option. However it was hardcoded back into 'sess-reds' in the constructor no matter what was set.

**To Reproduce**

```php
$options = [
    'host'  => '127.0.0.1',
    'port'  => 6379,
    'index' => '0',
    'prefix' => 'custom-prefix-'
];

$session           = new Manager();
$serializerFactory = new SerializerFactory();
$factory           = new AdapterFactory($serializerFactory);
$redis             = new Redis($factory, $options);

$session
    ->setAdapter($redis)
    ->start();
```

Result of session key in redis:
```
> KEYS *
sess-reds-h4h1fa8oh5epr3vf4upabbknni
sess-reds-f1tbr5tjsskrj6vtp4uieleva4
```

**Expected behavior**
The KEYS in redis session store should be using the `custom-prefix-xxxxx` instead of default `sess-reds`

```
> KEYS *
custom-prefix-h4h1fa8oh5epr3vf4upabbknni
custom-prefix-f1tbr5tjsskrj6vtp4uieleva4
```

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: 7.4.7
 - Operating System: Ubuntu 18.04.4 LTS
 - Installation type: via laradock
 - Zephir version (if any):
 - Server: Nginx
 - Other related info (Database, table schema): Redis server v=5.0.7

**Additional context**

**Comment by zsilbi** [comment]
Fixed in #15185
