### ISSUE TITLE
[NFR]: Do we have beforeFetch option

### ISSUE THREAD

**Issue by sanmayad** [phalcon/cphalcon#15181]
**Is your feature request related to a problem? Please describe.**

I want to encrypt and decrypt ids in the model itself. So I can easily implement while fetching with following code:
`afterFetch(){
      $this->id = myEncryption($this->id);
}`

But I want to implement decryption before the fetch too, so findFind, find etc all functions can be handled easily without me writing everything in controller, which I can miss a lot of times. 

**Describe the solution you'd like**

I want this beforeFetch method to handle all such things in query, join everywhere etc.
 
`beforeFetch(){
      $this->id = myDecryption($this->id);
}`

**Describe alternatives you've considered**

I have tried get set etc, but seems complex

**Additional context**

Also is there a way I can implement session values inside model itself in Phalcon4.
So I can implement the restriction of company_id from the session itself, before and after fetch.

**Comment by Jeckerson** [comment]
https://docs.phalcon.io/4.0/en/db-models#beforeafter-fetching

**Comment by zsilbi** [comment]
> **Describe the solution you'd like**
> 
> I want this beforeFetch method to handle all such things in query, join everywhere etc.
> 
> `beforeFetch(){ $this->id = myDecryption($this->id); }`

Even if this function would exist, it wouldn't work because you want to decrypt the `id` passed to `findFirst()`
You should override the default `findFirst()` method in your models to handle this when only a numeric condition is passed.

**Comment by sanmayad** [comment]
Yes, can't we build a overridden query for just everything both for Find and FindFirst etc.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zsilbi** [comment]
> Yes, can't we build a overridden query for just everything both for Find and FindFirst etc.

You could also use a custom `Query\Builder` and customize the `getQuery()` method to your needs.

**Comment by sanmayad** [comment]
Okay. Thanks Seems like I need to

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
