### ISSUE TITLE
ORM setSource failed

### ISSUE THREAD

**Issue by studyzhanglei** [phalcon/cphalcon#15206]
![image](https://user-images.githubusercontent.com/43992249/98664699-acb38200-2385-11eb-9c9c-3249d8f62aeb.png)

![image](https://user-images.githubusercontent.com/43992249/98664729-b5a45380-2385-11eb-9a7a-b4447043458e.png)
![image](https://user-images.githubusercontent.com/43992249/98664754-be952500-2385-11eb-88dd-99dd98cd4e43.png)

![image](https://user-images.githubusercontent.com/43992249/98664805-cbb21400-2385-11eb-99ae-84182fc359fc.png)

On the first time,  i setSource successed， but second failed， How to solve this problem？

thanks!

https://docs.phalcon.io/3.4/zh-cn/db-models

**Comment by studyzhanglei** [comment]
The same table is used for both queries

**Comment by studyzhanglei** [comment]
function "find" is successed

**Comment by Jeckerson** [comment]
Hello. What version of phalcon are you using?

**Comment by shuqiangzhou** [comment]
the problem has happened in phlacon 4.0

**Comment by shuqiangzhou** [comment]
> Hello. What version of phalcon do you use?

the problem has happened in phlacon 4.0

**Comment by Jeckerson** [comment]
Are you using caching adapter for Models metadata?

**Comment by shuqiangzhou** [comment]
![image](https://user-images.githubusercontent.com/26402118/98756565-d01e1180-2405-11eb-8c4a-8defefa9751e.png)
![image](https://user-images.githubusercontent.com/26402118/98756607-e3c97800-2405-11eb-82e6-819df2bb3f82.png)
![image](https://user-images.githubusercontent.com/26402118/98756627-ecba4980-2405-11eb-814b-5d70de214b9f.png)

**Comment by studyzhanglei** [comment]
> adapter

No

**Comment by studyzhanglei** [comment]
> Are you using caching adapter for Models metadata?

no

**Comment by studyzhanglei** [comment]
![image](https://user-images.githubusercontent.com/43992249/98760179-b2ed4100-240d-11eb-89f7-750f1b6f6333.png)
![image](https://user-images.githubusercontent.com/43992249/98760191-b97bb880-240d-11eb-86ff-33f526b8d7ab.png)

"find" has the same problem without condition

**Comment by studyzhanglei** [comment]
> ![image](https://user-images.githubusercontent.com/43992249/98760179-b2ed4100-240d-11eb-89f7-750f1b6f6333.png)
> ![image](https://user-images.githubusercontent.com/43992249/98760191-b97bb880-240d-11eb-86ff-33f526b8d7ab.png)
> 
> "find" has the same problem without condition

![image](https://user-images.githubusercontent.com/43992249/98760625-a4535980-240e-11eb-9aca-21d924976a45.png)
![image](https://user-images.githubusercontent.com/43992249/98760643-acab9480-240e-11eb-9cbf-6af178aada4e.png)

**Comment by studyzhanglei** [comment]
How can i use the diffrent table name with the same model?

**Comment by Jeckerson** [comment]
According to the design of Model class - https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Mvc/Model.zep#L56
It is not correct approach to try reuse same model for several tables. It means, that in normal case, you need to create separate class for each DB table.

You could try to implement your own approach by using repository pattern with entities and Phalcon\Db https://designpatternsphp.readthedocs.io/en/latest/More/Repository/README.html .

Also, if you really need model functionality, you could try by rewriting method `setModelSource` in https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Mvc/Model/Manager.zep#L392

and creating your own method `setSource` (because this is final)
https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Mvc/Model.zep#L5622

**Comment by studyzhanglei** [comment]
![image](https://user-images.githubusercontent.com/43992249/99244138-a36e5d80-283c-11eb-9e6d-d18ffb533a88.png)

This method also failed， I guess the problem is due to caching 

If query conditions different，the table name is right。

**Comment by studyzhanglei** [comment]
![image](https://user-images.githubusercontent.com/43992249/99244739-79696b00-283d-11eb-9491-9d6cec8ef273.png)

**Comment by studyzhanglei** [comment]
I find the way to solve the problem .

$model = new User();
        $this->modelsManager->setModelSource($model, 'user_1_7');
        $query = $this->modelsManager->createBuilder()->addFrom(User::class)->getQuery();
        $query::clean();

        $res = $model::findFirst([
            "conditions" => '1 = 1',
        ]);
        var_dump($model->getReadConnection()->getSQLStatement());

        $this->modelsManager->setModelSource($model, 'user_1_14');
        $query = $this->modelsManager->createBuilder()->addFrom(User::class)->getQuery();
        $query::clean();

        $res = $model::findFirst(
            [
                "conditions" => '1 = 1',
            ]
        );
        var_dump($model->getReadConnection()->getSQLStatement());


        $this->modelsManager->setModelSource($model, 'user_1_15');
        $query = $this->modelsManager->createBuilder()->addFrom(User::class)->getQuery();
        $query::clean();

        $res = $model::findFirst(
            [
                "conditions" => '1 = 1',
            ]
        );
        var_dump($model->getReadConnection()->getSQLStatement());

        die;

**Comment by studyzhanglei** [comment]
![image](https://user-images.githubusercontent.com/43992249/99340295-b1ff5800-28c2-11eb-8f11-a34bd01172dd.png)

**Comment by Jeckerson** [comment]
Closing for now.
