### ISSUE TITLE
4.1.0 is missing on pecl

### ISSUE THREAD

**Issue by remicollet** [phalcon/cphalcon#15201]
I noticed version 4.1.0 being tagged / released, but nothing on pecl

Please push the update there.

**Comment by niden** [comment]
@remicollet We are having some issues updating PECL. @ruudboon somehow was unable to login to PECL but was able to login to PHP.net with the same credentials.

We will upload it as soon as we can. Thanks for the ping.

**Comment by remicollet** [comment]
Perhaps, as a workaround,  you can temporarily add the generated pecl archive to the release asset on github ?

**Comment by KalleZ** [comment]
@niden The PHP.net credentials is different from those you use to log in to PECL with and the two log in systems are separate, meaning he has to use the username from PECL to login (which is `ruudboon`), see:

https://pecl.php.net/user/ruudboon

- Having a `@php.net` email allows PHP.net VCS access, Wiki, Master, etc
- Having a PEAR/PECL account allows access to the respective websites for managing packages

If you are still unable to authenticate, then please do not hessitate to contact either me or another active Core Developer and we should be able to get in touch with the right people regarding this.

**Comment by niden** [comment]
@remicollet I have uploaded the pecl package in the 4.1 release here in GitHub.

@KalleZ Thank you for the help. I believe Ruud was contacting Derrick to try and sort it out. I will point him to this comment.

Thanks again all and apologies for the delay

**Comment by ruudboon** [comment]
@remicollet I will drop you an e-mail. thnx

**Comment by ruudboon** [comment]
Released on Pecl now. Sorry for the delay.
