### ISSUE TITLE
Phalcon Acl Class not found - PHP 7.4.12 & Ubuntu 20.04

### ISSUE THREAD

**Issue by nad33mahm3d** [phalcon/cphalcon#15209]
I have installed the framework on my Ubuntu and try to run the code which is working fine on the live server. But I got error

`Fatal error</b>: Uncaught Error: Class 'Phalcon\Acl' not found in`

**Comment by ruudboon** [comment]
Looks like you got Phalcon 3.4 running on your server and installed Phalcon 4 locally.
https://docs.phalcon.io/4.0/en/upgrade#overview

**Comment by nad33mahm3d** [comment]
@ruudboon Thanks, I am on ubuntu 20.04 and now I am going to try it with docker so I can match the live environment.

**Comment by ruudboon** [comment]
@nad33mahm3d ok. Closing this for now. Feel free to re-open if this issue occurs again.
