### ISSUE TITLE
Phalcon\Flash\Session::has return true when messages array is empty

### ISSUE THREAD

**Issue by yannux** [phalcon/cphalcon#15204]
Hi,

Using `Phalcon\Flash\Session::has()` return true whereas the messages array is empty.

https://github.com/phalcon/cphalcon/blob/a8035814aa9a8a2438f92ebf5128964e7c48fd3f/phalcon/Flash/Session.zep#L43

```
/**
     * Checks whether there are messages
     */
    public function has(type = null) -> bool
    {
        var messages;

        let messages = this->getSessionMessages(false);

        if typeof type != "string" {
            return true;
        }

        return isset messages[type];
    }
```

Sorry I don't understand why `type != 'string` return true,
but maybe it's possible to add something like :
```
if empty messages {
    return false;
}
```

Regards,

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15353
