### ISSUE TITLE
Unable to locate package php5-phalcon

### ISSUE THREAD

**Issue by andrejmaya** [phalcon/cphalcon#15228]
Following the installation guide [here ](https://docs.phalcon.io/3.4/en/installation) I executed:
```
curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
sudo apt-get update
sudo apt-get install php5-phalcon
```

and got this error message `E: Unable to locate package php5-phalcon`

**Comment by Jeckerson** [comment]
Hello. What OS dist and version are you running?

**Comment by andrejmaya** [comment]
@Jeckerson Ubuntu 20.04

**Comment by Jeckerson** [comment]
Default version of PHP, on Ubuntu 20.04, is `7.3` or `7.4` and default version of phalcon is `4.1` atm. Is there are any specific cases why you need PHP5 and phalcon 3.4 on latest Ubuntu LTS?

**Comment by andrejmaya** [comment]
@Jeckerson a specific customer project :)

**Comment by Jeckerson** [comment]
In this case, easier way would be compile from source latest `3.4.x` version.

https://docs.phalcon.io/3.4/en/installation#compile-from-sources

Keep in mind to change to correct tag during `git clone` and if you will compile on VPS with low RAM, better to create temporary swap file with 1Gb ~ 2Gb of size.

**Comment by andrejmaya** [comment]
@Jeckerson I did that already. If that's the only way to get it, then it'S fine. What do you think about updating the documentation here: https://docs.phalcon.io/3.4/en/installation#phalcon-installation ?

It is a bit misleading for users of latest Ubuntu distros.

**Comment by Jeckerson** [comment]
@andrejmaya Could you please submit PR for this file - https://github.com/phalcon/docs-app/blob/master/3.4/en/installation.md ?
As you already knows what need to be changed.

**Comment by Jeckerson** [comment]
Closing, feel free to re-open in case of another similar problem.
