### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Phalcon\Di\FactoryDefault' not found

### ISSUE THREAD

**Issue by mrainyo** [phalcon/cphalcon#15223]
PHP version 7.4.3.Phpinfo also has a phalcon extension.The request always shows Fatal error: Uncaught error: Class 'Phalcon\Di\FactoryDefault' not Found

![image](https://user-images.githubusercontent.com/19492741/100304429-b2da6d00-2fd9-11eb-874e-4a00839b0ee7.png)

**Comment by Jeckerson** [comment]
Please provide code where is happens.
