### ISSUE TITLE
I think there is no need to add this feature

### ISSUE THREAD

**Issue by ZhangRuiMingZRM** [phalcon/cphalcon#15222]
I think there is no need to add this feature

https://github.com/phalcon/cphalcon/commit/772a002acf0daaa0ad57470694e1e8f08a62a95e#diff-65d61901f4ab5f1161d4c42a99a483fdefda443080527a1094a34a01e3b32c2bR140-R142
 

https://github.com/phalcon/cphalcon/blob/523b539e56c97f959016cb46a4e6b662a663d61f/phalcon/Di/Service.zep#L137-L139

Caused #15032 , but it doesn't matter whether you extends class `Di\Injectable` or not

It is confusing and may make the code difficult to maintain if someone does like this

```php
class Foo
{

}
```

```php
use Phalcon\Di;

$container = new Di();
$container->set("foo", foo::class);
$container->set("bar", 'foo');
$container->set("baz", 'bar');
$container->set("qux", 'baz');

try {

    $container->get("qux");

} catch (\Exception $e) {

}
```

Expect  object `Foo` but  object `SomeOne` given if does like this

```php
use Phalcon\Di;

$container = new Di();
$container->set("Foo", function () {
    return new SomeClass();
});


$container->set("bar", foo::class);

try {

    $container->getShared("bar");


} catch (\Exception $e) {

}
```

When registering a registered service in `container`,  should be like this
```php
$container->set("foo", foo::class);
$container->set("bar", $container->getRaw('foo'));
```
When the type of the parameter (`definition`) is string, it must be the class name and not the registered service name

```php
$container->set("foo", foo::class);
```

**Comment by Fenikkusu** [comment]
This feature was added in to further enforce and support the DIC concept of SOLID Coding and simplify the process of initializing the service. As seen in the original PR, It intentionally allows you to do exactly what you demonstrated in your first example. This is also referred to a Aliasing. Mind you, I don't see anyone going so deep into the code as you demonstrated, and I argue why would you. By abstracting the code out, it gives you the power to do something like the following:

```php

use Phalcon\Di;
use Psr\LoggerInterface;
use App\MyAwesomeAdapter;
use App\MyAwesomeAdapterSoap;

$di = new Di();
$di->setShared('logger', LoggerInterface::class);
$di->set(LoggerInterface::class, function () {
   return MyAwesomeAdapter();
});

// ... (I forget the exact code off the top of my head here)

class MyModule implements ModuleAwareInterface {
   public function initializeService(Di $di) {
      $di->set(LoggerInterface::class, MyAwesomeAdapterSoap::class);
   }
}

```

Without this, you are forced to do additional registrations that just ultimately clutter the code. For your second example, I would point out that you aren't using Namespaces. Simply by properly name spacing your code, the issue as defined goes away. This is also in line with the PSR-1 Standards (https://www.php-fig.org/psr/psr-1/#3-namespace-and-class-names)
