### ISSUE TITLE
Phalcon 4.2 on EasyApache 4

### ISSUE THREAD

**Issue by ruhafzazahedi** [phalcon/cphalcon#15226]
Is Phalcon 4.2 available on Easy Apache 4? I could not find the Phalcon 4 among changes logs of that. please direct me

**Comment by Jeckerson** [comment]
Hello

Phalcon 4.2 does not exist. Latest version is `4.1.0` (You can check list of versions here - https://github.com/phalcon/cphalcon/releases)

About Easy Apache 4, you better to ask in their forums or ask support where are you hosting your sites.
