### ISSUE TITLE
Routing errors when upgrading Phalcon 4 (underscore in action names)

### ISSUE THREAD

**Issue by mesaglam** [phalcon/cphalcon#15232]
Hi, thank you all. I have a SaaS application written with phalcon 3.4. Now I'm triying to upgrade to phalcon 4. I'm using axios. I have problem with action names which have underscore. I'm getting "404 Not Found" response. Sample post url is "http://localhost/login/captcha_renew". This url is working with phalcon 3.4.

If I change the action name as captchaRenew, it's working. But I have nearly 1000 actions. It will take days to change them all. Is there an easy way to allow such action names?

Thanks for your help...

- Open SUSE Leap 15.2
- PHP 7.4.6
- Phalcon 4.1.0
- Nginx 1.16.1

**Comment by Jeckerson** [comment]
Hello. What router service configuration do your application has?

**Comment by mesaglam** [comment]
It's lke this;

> $router = $di->getRouter();

> $router->removeExtraSlashes(true);

> $router->handle($_SERVER['REQUEST_URI']);

But I also tried 

> use Phalcon\Mvc\Router;

> $router = new Router();

> $router->handle($_SERVER['REQUEST_URI']);

same error...

**Comment by Jeckerson** [comment]
So you have automatic routes enabled? If so, try to add custom route with underscore and check if it works now.

**Comment by mesaglam** [comment]
I tried. Even with regular expression like /([a-zA-Z0-9_-]+)
But no luck...

This error appears in the nginx error.log file:

![image](https://user-images.githubusercontent.com/7021706/101348541-d7b5c680-389c-11eb-82a7-fd6e65ca30ec.png)

**Comment by v00v** [comment]
It kind of looks like your Nginx web server is not properly configured. Check your logs!

**Comment by mesaglam** [comment]
Thanks for the answer. I think it's not about nginx conf. I tried to post raw php file with underscore and can able to get the response successfully. 

With phalcon4 I'm getting the following error:

**Action 'captcha_renew' was not found on handler 'login'**

**Comment by Jeckerson** [comment]
> This error appears in the nginx error.log file:

Your nginx log showing `public/` folder, it really seems problem or with nginx `root` or incorrect `index.php` location. Try to dump `$_SERVER` and see if document root and another variables contain correct path the `index.php`.

Also check if query string contains `?_url=/login/captcha_yenile`.
Also, see output of `$_SERVER['REQUEST_URI']` and check if it correct...

**Comment by mesaglam** [comment]
That may be nginx problem. Nevermind, I started to change action names....

**Comment by bakos** [comment]
@Jeckerson 
I had the same problem. Here is the source of it: https://github.com/phalcon/cphalcon/commit/411cfe72
It is not configurable and it should be described in docs upgrade section:  https://docs.phalcon.io/4.0/en/upgrade
