### ISSUE TITLE
Controller Unit Test Example

### ISSUE THREAD

**Issue by atelic** [phalcon/cphalcon#15238]
I'm working on a project that has a lot of "thick" controllers that contain a lot of business logic. I'd like to write tests for them to support future refactors. Are are there any examples of how to write unit tests for Phalcon controllers?

**Comment by Jeckerson** [comment]
Hello!

There are, at least, two options:
1. Create acceptance tests by simulating the browser requests - https://github.com/phalcon/vokuro/tree/master/tests/acceptance/controllers
2. Create functional or international tests that will initialize controller object (ex: `new IndexController()`) and call action method

In first approach, it depends if your frontend contain many js logic, which might difficult test write, on another hand, you will have almost E2E tests.

Acceptance test example:
```
public function login(AcceptanceTester $I): void
{
    $I->amOnPage('/session/login');
    $I->see('Log In');
    $I->fillField('email', 'bob@phalcon.io');
    $I->fillField('password', 'password1');
    $I->click('//form/*[@type="submit"]');
    $I->see('Search users');

    $this->cookie = $I->grabCookie('PHPSESSID');
}
```

Meanwhile in second approach, you can focus only on controller logic, which will call all internal functionality of framework and business logic itself. Also, it can be possible to make code coverage with this approach. Drawbacks by using this approach - all service providers must be reset each test, so do not forget to clean `$_SESSION`, `$_GET` and another superglobal variables, also database and another related persistent things...

Functional test example:
```
public function login(): void
{
    $class = new AccountController();
    $class->login();
    
    $this->assert(true, \Phalcon\Di::getDefault()->getShared('session')->has('auth'));
}
```

**Comment by Jeckerson** [comment]
In case you have more questions and want to discuss them, feel free to use more related sources:

* Discord - https://phalcon.io/discord
* Forum - http://phalcon.io/forum

Github issues section is more for NFRs, bugs and issues. :)
