### ISSUE TITLE
Session expire time

### ISSUE THREAD

**Issue by yaseminhocaoglu** [phalcon/cphalcon#15248]
Hello, I have an application developed with Phalcon 3.4 with heavy data flow. But I have a problem with the session. Sometimes, if the user does not operate in the application for about an hour, the session ends when the application returns. Using load balancer. Could it be losing the session file during migrations? Thank you for your help

**Comment by Jeckerson** [comment]
Hello, if you are using file session adapter and put your sessions into `/tmp` directory, you will depend on OS schedules, as it clear folder time to time. Try to use different folder outside public view and clear it manually, or by using another approaches.

**Comment by yaseminhocaoglu** [comment]
The problem is not due to the load balance. When we increased the session maxlifetime in the php.ini file, the problem was solved. (Session.gc_maxlifetime) The default time was 24 minutes and this time was insufficient. I increased the time to 3 hours. Thank you
