### ISSUE TITLE
Profiler time error.

### ISSUE THREAD

**Issue by cat9** [phalcon/cphalcon#15249]
https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Db/Profiler/Item.zep#L58

The value of method(getTotalElapsedSeconds ) return is not a time in seconds.

https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Db/Profiler.zep#L190

**Comment by Jeckerson** [comment]
Hello

Could you please provide minimal script example?

**Comment by cat9** [comment]
hello,
you can check this function below:
https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Db/Profiler.zep#L173

```
public function stopProfile() -> <Profiler>{
        var activeProfile, finalTime, initialTime, version;

        let version = phpversion();

        /**
         * @todo Remove this check when we target min PHP 7.3
         */
        if starts_with(version, "7.2") {
            //microseconds
            let finalTime = microtime(true);  
        } else {
           //nanoseconds
            let finalTime = hrtime(true);  
        }

        let activeProfile = <Item> this->activeProfile;

        activeProfile->setFinalTime(finalTime);

        let initialTime = activeProfile->getInitialTime(),
            //call by diffrent unit. (totalSeconds:seconds, initialTime & finalTime: microseconds or nanoseconds
            this->totalSeconds = this->totalSeconds + (finalTime - initialTime),
            this->allProfiles[] = activeProfile;

        if method_exists(this, "afterEndProfile") {
            this->{"afterEndProfile"}(activeProfile);
        }

        return this;
    }
```

I add some comments in the codes, you can check it out.
initialTime & finalTime may be microseconds or nanoseconds case different function call, and this->totalSeconds in seconds.
Also what activeProfile->getTotalElapsedSeconds() return may be microseconds or nanoseconds,and not as the function's comment say "Returns the total time in seconds spent by the profile". here is the codes:
https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Db/Profiler/Item.zep#L58
```
 /**
     * Returns the total time in seconds spent by the profile
     */
    public function getTotalElapsedSeconds() -> double
    {
        return this->finalTime - this->initialTime;
    }
```
