### ISSUE TITLE
Error in documentation wrt persistent MySQL connection

### ISSUE THREAD

**Issue by DrJLT** [phalcon/cphalcon#15241]
Hello,

In the documentation, it is written that 'persistent' is a parameter: https://docs.phalcon.io/4.0/en/db-layer#connect

As I've been tuning the code, I noticed that it doesn't really create a persistent connection. To do so, it's necessary to add

`'options' => [\PDO::ATTR_PERSISTENT] => true`

However, that is just an option passed to PDO. The MySQL adapter will continue to create new connections, because the adapter simply creates a connection each time it is called. 

https://github.com/phalcon/cphalcon/blob/master/phalcon/Db/Adapter/Pdo/AbstractPdo.zep

This should be made clear in the documentation.

**Comment by niden** [comment]
This was indeed an omission in the code. The `persistent` flag is now taken into account

Thank you @DrJLT for reporting this.

Resolved in https://github.com/phalcon/cphalcon/pull/15419/
