### ISSUE TITLE
phalcon will auto filter html tag which string contains html tags

### ISSUE THREAD

**Issue by liaojiansong** [phalcon/cphalcon#15255]
The code looks like this.
```php
$model = new PostModel();
$model->titile = 'hello world';
$model->content = '<p>this is something ...</p>';
$model->save();
```
That's what I want.
| title | content                         |
| ----- | ------------------------------- |
| hello | \<p>this is something ...\</p> |

But ,what is actually preserved is like below,the phalcon removed my  \<p>  tag 
| title | content                         |
| ----- | ------------------------------- |
| hello | <p>this is something ...</p> |

So,what am I supposed to do?

PHP:7.4.8
Phalcon:4.1.0
Mysql:5.7.24
OS:Centos7

By the way,in win10 it is ok,only in centos will remove html tag

**Comment by Jeckerson** [comment]
Hello

Please show your PostModel class

**Comment by liaojiansong** [comment]
```php
<?php


namespace Castle\Models;

use Phalcon\Mvc\Model;

class PostModel extends Model
{
    public $id;

    public $title;
    public $content;


    public function initialize()
    {
        $this->setSource("post");
        $this->useDynamicUpdate(true);
    }

}
```

**Comment by liaojiansong** [comment]
Here is  database config 
```php
    $di->setShared('db', function () use ($config,$di) {
        $dbConfig = $config->database;
        $connection = new \Phalcon\Db\Adapter\Pdo\Mysql([
            'host'     => $dbConfig->host,
            'username' => $dbConfig->username,
            'password' => $dbConfig->password,
            'dbname'   => $dbConfig->dbname,
            'charset'  => $dbConfig->charset,
            'port'     => $dbConfig->port,
        ]);

        return $connection;
    });
```

**Comment by liaojiansong** [comment]
Thank you,Jeckerson. Maybe i used the 'string' filter in the getPost() method,so my html tag was filtered out. Now,I close this issue
