### ISSUE TITLE
[ERROR] Class 'Phalcon\Html\Helper\Input\AbstractInput' does not implement method: 'renderTag' 

### ISSUE THREAD

**Issue by jayjupdhig** [phalcon/cphalcon#15251]
I was thinking i will open a new issug regarding that problem described on my other issue here: https://github.com/phalcon/cphalcon/issues/15250

Maybe somebo knows what that is. Seems to be sourcecode-related, not a problem with build config.

**Comment by Jeckerson** [comment]
Hello, please provide code example.

**Comment by jayjupdhig** [comment]
I don't want to use phalcon by an web app - i just want to compile it for another developer.

And i used that steps here: https://docs.phalcon.io/4.0/en/installation#raspberry-pi

(As described in the link above: https://github.com/phalcon/cphalcon/issues/15250)

So the source code is 100% original from the phalcon team - unmodified & uncustomized.

```
git clone https://github.com/phalcon/cphalcon
cd cphalcon/
git checkout tags/v4.0.0 ./
zephir fullclean
zephir build
```

**Comment by Jeckerson** [comment]
Use latest tag: `v4.1.0`, instead of `v4.0.0`. Latest Zephir can't be compiled with `v4.0.x`

**Comment by jayjupdhig** [comment]
Thank you very much, seems to work until now:

![345345](https://user-images.githubusercontent.com/42765391/103788424-1c20b780-503f-11eb-8536-4ed11ecfb8b6.jpg)


But, so you see in the screenshot, there are any warning... but the comile process is still in progress. :-)
