### ISSUE TITLE
form validation Confirmation strict comparison  

### ISSUE THREAD

**Issue by InstaDaky** [phalcon/cphalcon#15252]
Hi guys,
we have a problem using password confirmation validator, 

https://github.com/phalcon/cphalcon/blob/3241d96e4bb01dc7746b74c9ce586250b8887c46/phalcon/Validation/Validator/Confirmation.zep#L136

When we use the confirmation form validation it doesn't consider the type of the data. which is a problem when comparing numbers .
This returns true for `000012345` = `12345`

it should be either `return strcmp($a, $b) === 0;`
or allow us to override the compare method, which we cannot at the moment because of `final protected`

thanks

**Comment by Jeckerson** [comment]
Hello! It really seems to be the bug.

You can also create your own elements by extending the `Phalcon\Forms\Element\ElementInterface` interface (https://docs.phalcon.io/4.0/en/api/phalcon_forms#forms-element-elementinterface).

**Comment by niden** [comment]
Resolved with https://github.com/phalcon/cphalcon/pull/15347
