### ISSUE TITLE
phalcon for Debian 10 "Buster" ?

### ISSUE THREAD

**Issue by jayjupdhig** [phalcon/cphalcon#15256]
Hi there

How to install phalcon on Debian 10 "Buster" ?

Can't find any manuals when i do a google search for it...

Thank you very very much for your feedback.

**Comment by Jeckerson** [comment]
Hello

Please follow current one of current links:
* https://docs.phalcon.io/4.0/en/installation#installation-platforms
* https://packagecloud.io/phalcon/stable

**Comment by jayjupdhig** [comment]
1.) curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash

2.) apt-get update && apt-get upgrade

3.) apt-get install php7.2-phalcon



Then, `find / | grep phalcon.so` shows me that: `/usr/lib/php/20180731/phalcon.so`

A file `/var/www/html/info.php` with a `phpinfo()` method call shows me only 1 entry when i search for "phalcon" in the phpinfo output content:

`/etc/php/7.3/apache2/conf.d/50-phalcon.ini`


(and a lot of more, different .ini file includes, but they are not phalcon-related)

The Linux Version is use it Debian 10 "Buster" with most current updates on 2021-01-11...

Thank you very much for your feedback. Best regards.

**Comment by jayjupdhig** [comment]
I restarted apache2 service manually once, but it doesn't help: `service apache2 restart`

**Comment by jayjupdhig** [comment]
Maybe somebody can re-open that issue and un-flag is as bug. Doesn't seems to be a bug (on source level), but there are some other issues. Thanks.

**Comment by Jeckerson** [comment]
Will check it on my raspberry pi.

**Comment by jayjupdhig** [comment]
Thank you... BUT:

That's completely different, then you need to compile by yourself.

I don't mean Raspbian, i mean the "normal", original Debian 10 "Buster" from debian.org...

It's debian based, but there a A LOT of differrences - in every way.

**Comment by Jeckerson** [comment]
Ah, I confused with another issue. Ok then even simpler to check. Will give more details after my checks.

**Comment by jayjupdhig** [comment]
Here is the output of phpinfo.

[PHP 7.3.19-1_deb10u1 - phpinfo().zip](https://github.com/phalcon/cphalcon/files/5801158/PHP.7.3.19-1_deb10u1.-.phpinfo.zip)


If you can tell me to to debug problems with PHP extensions loading (i don't think it's in the apache2 log on /var/log...) i can also send it. Thank you very much for your support, that's very nich!! :-)

**Comment by jayjupdhig** [comment]
Maybe i need the extension php-psr and/or change from "apache module" to "fpm" or "fcgi"...?

**Comment by jayjupdhig** [comment]
now i tried it with `apt-get install php-psr-*` & `service apache2 restart`

Still the ssame problem - doesn't work...

**Comment by jayjupdhig** [comment]
...or do i need to use `apt-get install php-phalcon4` instead of `apt-get install php7.3-phalcon`

Is that just another repository or is it another version, maintained by the owner of that APT source??

**Comment by Jeckerson** [comment]
Here is video example how to install all in 3 min

https://www.youtube.com/watch?v=CFTj2YNg5n8

And here are commands from video:

```bash
apt update
apt install curl nano
apt install php7.3-phalcon
apt install php-pear
apt install php7.3-dev
pecl install psr
php -m | grep 'phalcon'
apt purge php7.3-dev
```

**Comment by jayjupdhig** [comment]
Will try it, thank you.

Then, your manual seems to be incomplete. When i remember right, the phalcon team has written a manual which describes that it's the same procedure for Jessie, Stretch and Buster... (maybe the `x` is different on `apt-get install php7.x-phalcon`)

https://docs.phalcon.io/4.0/en/installation#installation-platforms

...which is not 100% correctly. Buster seems to need some additional steps regading your information.

**Comment by jayjupdhig** [comment]
I think it would be useful to add the other steps to your manual on https://docs.phalcon.io/4.0/en/installation#installation-platforms or https://packagecloud.io/phalcon/stable

???

**Comment by jayjupdhig** [comment]
Another question:

"For your case with apache/nginx, also add extension=psr.so into /etc/php/7.3/fpm/conf.d/50-phalcon.ini and reboot your webserver."

Can't i use it as an apache module extension instead of FPM? Do i need to use the FPM approch in every case to use phalcon 4.x with apache2?

**Comment by Jeckerson** [comment]
> Can't i use it as an apache module extension instead of FPM?
You can. Just gave an example.

P.S. Also, I suggest to use Nginx as it is faster and requires less resources.

**Comment by jayjupdhig** [comment]
Thank you very much, will look about it!!

**Comment by jayjupdhig** [comment]
Now i can confirm that it works, also as an apache module. (nginx bay be more performant and easier to configure than apache - but we have some existing (working) configuration customizations and there is not a lot of traffic on that web page (almost zero, it's just an admin GUI for a smart home system)

:-)

**Comment by jayjupdhig** [comment]
Does not work anymore with newer version / packages:

After ´pecl install psr´ get same message that ´php -m | grep 'phalcon'´ shows:

**_"PHP Warning:  Cannot load module 'phalcon' because required module 'psr' is not loaded in Unknown on line 0"_**

But it's in file ´/etc/php/7.3/apache2/php.ini´:

´´´
;extension=soap
;extension=sockets
;extension=sodium
;extension=sqlite3
;extension=tidy
;extension=xmlrpc
;extension=xsl

extension=psr
´´´

QUESTION: Why the modules suddenly don't have ´.so´ at the end? Doens't work either

´extension=psr´

OR

´extension=psr.so´

(then service apache2 restart, sure.,..)

thx for feedbacks...


kind regards,
jan

**Comment by jayjupdhig** [comment]
**_"Does not work anymore with newer version / packages"_**

-> Or the problem is that now apache2 php runs as module and not as FPM??

**Comment by jayjupdhig** [comment]
OH... problem was that nasty combination of that:

1.) Browser cache from phpinfo(), opened that script BEFORE adding phalcon

AND

2.) The error message that sill persists with ´php -m | grep 'phalcon'´:

´´´
root@xxx-alpr:~# php -m | grep 'phalcon'
PHP Warning:  Cannot load module 'phalcon' because required module 'psr' is not loaded in Unknown on line 0
root@xxx-alpr:~#

´´´

So WTF...??!

**Comment by jayjupdhig** [comment]
And what's that:

![111](https://user-images.githubusercontent.com/42765391/121710133-90bdbd80-cad9-11eb-9c17-aef57d37474d.JPG)


I was thinkg i need to add three quotes for source...?
