### ISSUE TITLE
Missing support for Dependency Inversion Principle and for serving the purpose of Interface Segregation Principle

### ISSUE THREAD

**Issue by fakharak** [phalcon/cphalcon#15283]
Forewords:
I have put this note up on PHP8 official documentation (but i know that will take huge time fo them to work on). However, as you are working to extend PHP (with Asynchronous syntax), therefore i am bringing this very important, needful and valuable requirement in your acknowledgement which is related to core principle of programming (SOLID) and is missing in PHP, with a hope that you will come as a help to the PHP Community.

Requirements:
We do not have Interface variables in PHP, which means the client-side code (consumer) can not point to abstraction. That means PHP does not  adheres to A) Dependency Inversion Principle (DIP) and B) it also does not serve the actual purpose behind Interface Segregation Principle ('I' in S.O.L.I.D).

Those are two powerful techniques for extensibility with flexibility.

Can you please add support to that syntax like through a separate module in Swoole ?

As example please See P-13 and P-15 in that blog
https://www.codeproject.com/Articles/18743/Interfaces-in-C-For-Beginners

**Comment by niden** [comment]
We would be happy to discuss this more with concrete examples and potentially a pull request in the future. For now this is not in our radar.
