### ISSUE TITLE
ServerRequestFactory::load Not Working Correctly

### ISSUE THREAD

**Issue by Fenikkusu** [phalcon/cphalcon#15286]
I don't have time right now to dig into this, but I presume it's an easy fix. If you use the Phalcon\Http\Message\ServerRequestFactory::load method without passing any arguments, the values are coming back as empty (IE: getUploadedFiles). If you pass all of the args manually, it seems to work fine.

**Comment by niden** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/15380

Thank you @Fenikkusu
