### ISSUE TITLE
Phalcon/Security/JWT/Builder - Can't access setClaim() through inheritance

### ISSUE THREAD

**Issue by JMoodyFWD** [phalcon/cphalcon#15322]
Extending _Phalcon/Security/JWT/Builder_ doesn't allow for accessing the _setClaim_ method:

[Reference Discussion Post](https://github.com/phalcon/cphalcon/discussions/15321)

Edit: /cc @niden per request

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15323
