### ISSUE TITLE
Phalcon\Image\Adapter\GD resize optional parameters bug

### ISSUE THREAD

**Issue by flyingangel** [phalcon/cphalcon#15333]
Code taken from the documentation itself https://docs.phalcon.io/4.0/mn-mn/image#resize

    $image = new Gd($destination);
    $image->resize(300, null, Enum::HEIGHT);

Throws Phalcon\Image\Exception

    height must be specified

Using Phalcon extension v4.1.0

**Comment by flyingangel** [comment]
It's probably a documentation bug. When using the enum HEIGHT, the width could be ignored

    $image->resize(null, 300, Enum::WIDTH);

Could an admin confirm this?

**Comment by flyingangel** [comment]
So it's just a documentation typo. Check my link https://docs.phalcon.io/4.0/mn-mn/image#resize

**Comment by niden** [comment]
@flyingangel Thanks for reporting this. It has been fixed in the docs
