### ISSUE TITLE
[BUG]: Improve stubs generation

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#15343]
1. Generate stubs
2. Pick static code analyzers
3. Run them against generated stubs
4. Fix Phalcon's code in Zephir

**Comment by Jeckerson** [comment]
Below psalm errorLevel 5 is blocked by https://github.com/zephir-lang/zephir/issues/2239

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15362
