### ISSUE TITLE
Misleading PeCL info

### ISSUE THREAD

**Issue by waghanza** [phalcon/cphalcon#15359]
Hi,

According to the information on https://pecl.php.net/package/phalcon, I could understood that `phalcon` support php8.

However, this is not (yet) the case. 

Should / could those info be updated ?

Regards,

**Comment by Jeckerson** [comment]
Hello

Yes, there was a problem that wasn't released in `4.1.x` version.

https://github.com/phalcon/cphalcon/discussions/15279#discussioncomment-379406

/cc @phalcon/core-team

**Comment by Jeckerson** [comment]
`v4.1.1` with fix released.
