### ISSUE TITLE
[ BUG ] Segfault when printing model

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#1535]
Using v1.3.0, I have a function called by my save action:

```php
public function saveDepartment(){

		// extraneous code

		$posted_users = explode(',',$this->request->getPost('users','string')[$save_id]);
		
		$dept_users = [];
		foreach($posted_users as $ccid){
			$DeptUser = new \Store\Model\DepartmentUser();
			$DeptUser->department_id = $save_id;
			$DeptUser->ccid = trim($ccid);
			$dept_users[] = $DeptUser;
		}

		print_r($dept_users); // segfault generated here
```

Store\Model\DepartmentUser model is this:
```php
<?PHP
namespace Store\Model;

class DepartmentUser extends BaseModel{
	public function initialize(){
		$this->belongsTo('department_id','Store\Model\Department','id');
		$this->setSource('department_user');
	}
}
```

`BaseModel` class merely defines a `di()` function for easing retrieval of the DI container.

Trying to print out `$DeptUser` inside the foreach() also causes the segfault.  Actually, 3 segfaults are happening.

I'm running v1.3.0

**Comment by Green-Cat** [comment]
@andresgutierrez Shouls probably be closed, no reproduction code or environment details provided and no other reports of this bug. I have tried with a model in my own code, and I am able to print_r and var_dump it without a segfault occuring.

**Comment by andresgutierrez** [comment]
@quasipickle Could you please try again using Phalcon 2?

**Comment by quasipickle** [comment]
I'll close this. I can't upgrade to Phalcon 2 yet, and the code has changed so much I can't reproduce.
