### ISSUE TITLE
[BUG]: Model::findFirst set columns, error: must implement  ModelInterface Or null

### ISSUE THREAD

**Issue by tidytrax** [phalcon/cphalcon#15356]
Error:

> Return value of App\Models\Test::findFirst() must implement interface Phalcon\Mvc\ModelInterface or be null, instance of Phalcon\Mvc\Model\Row returned

```
    $model = Test::findFirst([
        'conditions' => 'column_id = ?0',
        'bind' => [
            1
        ],
        'columns' => ['title'],
        'hydration' => Resultset::HYDRATE_ARRAYS //with or without same bug
    ]);
```

Works fine with 

`Test::find([
        'conditions' => 'column_id = ?0',
        'bind' => [
            1
        ],
        'columns' => ['title']
    ]);`

**Comment by zsilbi** [comment]
Duplicate of #15212.
This has been fixed but not released yet.

**Comment by Jeckerson** [comment]
@zsilbi I prefer to review it again in v5, at least try to check if it possible to look at Model\Simple and always return `?ModelInterface`. And it might break compatibility.

**Comment by as882301** [comment]
No one fixed this bug? 4.1.2 still exists!

**Comment by Jeckerson** [comment]
@as882301 This bug can and will be fixed only since v5, as it breaks compatibility. Stay tuned.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15760

**Comment by kvityasya** [comment]
Bag is actual on v5.0.0beta2
