### ISSUE TITLE
[BUG]: PHP 8 db->delete throw exception if not pass empty array

### ISSUE THREAD

**Issue by tidytrax** [phalcon/cphalcon#15363]
Works on update and insert.
Throw exception if not pass empty array as third argument.

```
PHP 8.0.3 
Version | 4.1.0
Build Date | Apr 1 2021 10:53:26
Powered by Zephir | Version 0.13.0-d89a471

```

$db =  \Phalcon\Db\Adapter\Pdo\Postgresql 

```
$this->db->delete('logs.test', 'updated_at < :date', [
            'date' => $this->dateHandler->newDateTimeInstance()
            ->substract()
        ]);
```
**Throws** 

> Phalcon\Db\Adapter\Pdo\AbstractPdo::execute(): Argument #3 ($bindTypes) must be of type array, null given

But if i pass as third argument an empty array works.

```
$this->db->delete('logs.test', 'updated_at < :date', [
            'date' => $this->dateHandler->newDateTimeInstance()
            ->substract()
        ],
[]); // EMPTY ARRAY
```

**Comment by Jeckerson** [comment]
You are using `v4.1.0` which isn't compatible with PHP8.

**Comment by tidytrax** [comment]
Yes, but i did compile from v5.0.0-alpha.1

which is the correct php8 branch?

Thanks

**Comment by tidytrax** [comment]
Is the only bug between php8 and phalcon 4.1.0? because i have tested all app and this is the only error

**Comment by Jeckerson** [comment]
There are miss match in the interfaces, which gives you that exception.

**Comment by tidytrax** [comment]
oh ok, so which branch should i use to test on php8?

**Comment by Jeckerson** [comment]
> oh ok, so which branch should i use to test on php8?

`v5.0.x`

**Comment by tidytrax** [comment]
> > oh ok, so which branch should i use to test on php8?
> 
> `v5.0.x`

Hi, can you help me I`m on branch v 5.0.x , i did compile at least 4 times,

```
zephir fullclean
zephir compile
cd ext
phpize
./configure
make && make install
```

i also have use  gen-build.php

Always give me the same phalcon  4.1.0 on phpinfo

i`m on ubuntu 20.1

**Comment by tidytrax** [comment]
Version | 5.0.0-alpha.1
Build Date | Apr 2 2021 12:38:32
Powered by Zephir | Version 0.13.0-99f0e65

Same error!
