### ISSUE TITLE
[BUG]: Logger variable %type% not in uppercase

### ISSUE THREAD

**Issue by wurst-hans** [phalcon/cphalcon#15375]
Using Phalcon v4.1.0 I've set following format for logger `[%date%] [%type%] %message%` but this results in:

```
[2021-04-05T09:52:56+02:00] [warning] Use of undefined constant a - assumed 'a' (this will throw an Error in a future version of PHP) in /code/src/Bootstrap/Application.php on line 21
[2021-04-05T10:12:57+02:00] [notice] Undefined variable: y in /code/Bootstrap/Application.php on line 20
```

I expect, that type of message is written in uppercase.

**Comment by kowach** [comment]
Same here.
I see that [Logger::getLevels()](https://github.com/phalcon/cphalcon/blob/master/phalcon/Logger.zep#L388) are hard coded lowercase. But why?

**Comment by niden** [comment]
@kowach @wurst-hans Can you guys have a look at this PR?

https://github.com/phalcon/cphalcon/pull/15401

Maybe I am setting the test wrong but that is how I understood it from your description. Any pointers welcome.

Thanks!

**Comment by wurst-hans** [comment]
Sorry, don't understand much of testing, but as I see in your PR, the test expects `$expected = '[info] info message ' . $unique;` but shouldn't it be `$expected = '[INFO] info message ' . $unique;`. The log level has to be in upper case according to [documentation](https://docs.phalcon.io/4.0/de-de/logger#log-levels)

**Comment by niden** [comment]
I was trying to replicate the error you posted

`[warning] Use of undefined constant a - assumed 'a' `

I thought that the `undefined constant...` was coming from the type conversion.

If it is the uppercase that is the issue, we can certainly change the docs (easiest) or change the code. I don't mind doing either.

@Jeckerson thoughts?

**Comment by Jeckerson** [comment]
@niden I think we should change to uppercase in the code, as in docs it always was uppercase, but never was noticed.

@kowach Because it is not intended to be changed. However, the method is protected and you can easily extend it and put naming as you wish.

**Comment by wurst-hans** [comment]
This isn't a showstopper for me and isn't worth it to overwrite protected `getLevels()` method. I just wondered about one more thing, silently changed. Because in Phalcon v3.4 the log level was printed uppercase to log (see [code](https://github.com/phalcon/cphalcon/blob/3.4.x/phalcon/logger/formatter.zep#L35)).
And from most other projects, the log level is used to be printed uppercase, too. So I prefer a change of code, but no hurry.

**Comment by niden** [comment]
In case anyone is wondering. I remember why this was changed:

https://github.com/php-fig/log/blob/master/Psr/Log/LogLevel.php#L10

PSR has everything lowercase.

We will change it to upper to keep with 3.4. Maybe put an option in to have them up or down or something

**Comment by wurst-hans** [comment]
Thanks for clarification. No problem if PSR requires it to be lowercase. But then it makes no sense do switch back to uppercase, doesn't it?

**Comment by niden** [comment]
PSR does not "require" it I think so long as you can identify what the level is - uppercase or lowercase. I checked Monolog and they print out their levels in uppercase.

I will change it to the way 3.4 was (uppercase). Also since `getLevels` is protected, it can be overridden if someone wants it to be lowercase

I will have the PR ready shortly

**Comment by niden** [comment]
This has been resolved for v5
