### ISSUE TITLE
[BUG]: Uncaught Phalcon\Tag\Exception with Phalcon\Debug and Phalcon\Session\Bag

### ISSUE THREAD

**Issue by diplopito** [phalcon/cphalcon#15381]
**Describe the bug**
Using \Phalcon\Session\Bag without DI container generates an uncaught error by Phalcon\Debug

**To Reproduce**

```php
(new \Phalcon\Debug())->listen();

$path = new \Phalcon\Session\Bag("path");

```
Output:

```php
Fatal error: Uncaught Phalcon\Tag\Exception: A dependency injection container is required to access the 'url' service in phalcon/Tag.zep:469 
Stack trace: #0 [internal function]: Phalcon\Tag::getUrlService() 
#1 [internal function]: Phalcon\Tag::linkTo() 
#2 [internal function]: Phalcon\Debug->getVersion() 
#3 [internal function]: Phalcon\Debug->renderHtml() 
#4 [internal function]: Phalcon\Debug->onUncaughtException() 
#5 {main} thrown in phalcon/Tag.zep on line 469
```

**Expected behavior**
Phalcon Debug results interface

**Details**
 - Phalcon version: 4.0 and 4.1
 - PHP Version: 7.2 and 7.4
 - Operating System: Ubuntu 20.04 and Windows 10
 - Installation type: installing via package manager
 - Server: Apache

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15786
