### ISSUE TITLE
[BUG]: Phalcon\Session\Bag needs a session service in DI

### ISSUE THREAD

**Issue by diplopito** [phalcon/cphalcon#15382]
**Describe the bug**
According to the documentation ([Phalcon\Session\Bag](https://docs.phalcon.io/4.0/en/session)) this code should work:

```php
<?php

use Phalcon\Di;
use Phalcon\Session\Bag as SessionBag;

$container = new Di();
$user      = new SessionBag('user');

$user->setDI($container);

$user->name     = 'Dark Helmet';
$user->password = 12345;
```

**Error:**
```php
Fatal error: Uncaught Phalcon\Di\Exception: Service 'session' wasn't found in the dependency injection container in /mnt/f/xampp/htdocs/test/bag.php:33 
Stack trace: 
#0 [internal function]: Phalcon\Di->get() 
#1 [internal function]: Phalcon\Di->getShared() 
#2 /mnt/f/xampp/htdocs/test/bag.php(33): Phalcon\Session\Bag->__construct() 
#3 {main} thrown in /mnt/f/xampp/htdocs/test/bag.php on line 33
```

**Expected behavior**
```php
echo $user->name  // should return 'Dark Helmet'
```

**Details**
 - Phalcon version: 4.1
 - PHP Version: 7.4
 - Operating System: Ubuntu 20.04
 - Installation type: installing via package manager
 - Server: Apache

**Additional context**
Adding a session service to DI solves the issue: ideally, according to the docs,`SessionBag` should reside in global session (especially if presented as an alternative to `Phalcon\Registry`), but in the [zep file](https://github.com/phalcon/cphalcon/blob/v4.0.0/phalcon/Session/Bag.zep), a session service in the DI is necessary for it to work.

**Comment by niden** [comment]
@diplopito Just to understand this a bit better. The `Bag` needs to store stuff in the session so that it can persist. As such we need the session service to be present in the container. This I believe has been the case for quite a while now (the docs of course might be misleading which we can fix).

Are you saying that if the `session` service exists then perfectly fine go ahead as normal but if it does not exist, the `Bag` should act as a `Registry` and lose the keys/values after the request is completed?

**Comment by diplopito** [comment]
Thanks for looking into this @niden. As it is described in the documentation, indeed `Bag` could act as a `Registry` with volatile keys/values; considering the case of the error reported, if no `session` has been started, it could start one perhaps with `memory` as default adapter (informing the developer about this default setting). It would be very practical --besides the creation of namespaces in session. If the developer wants to use `persistent`, then a different adapter should be used for it. 

If this scenario is not viable, then the documentation should be updated: it is misleading that there is a `new Di()` declaration followed by `new SessionBar('user')` but no `session` declared inside the `Di` in between (this step would be missing then). In https://docs.phalcon.io/4.0/en/session#persistent-data happens the same: since there is no `session` service declaration, it could be assumed that `bag` **and** `persistent` are standalone components.

**Comment by niden** [comment]
@diplopito Got it.

I will update the documentation so that it is clear. 

I do not want to use the `persistent` property (in controllers etc.) which ties to the `Bag` since it can be misleading if no session is defined.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/docs/commit/eba8e331eec582662b04591ffd686562c01ceca9

Thanks @diplopito !
