### ISSUE TITLE
[NFR]: Move out from Travis/AppVeyor to Github Actions

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#15390]
Move all things that left from this x2 CI's and make it all inside single Github Actions.

**Comment by niden** [comment]
Also produce the artifacts (DLLs) in Actions, so that they can be downloaded and added. Potentially we could tie this to an automatic release of sorts with Actions.

**Comment by Jeckerson** [comment]
> Also produce the artifacts (DLLs) in Actions, so that they can be downloaded and added. Potentially we could tie this to an automatic release of sorts with Actions.

Yep, it is about time to not suffer each release with all this mess...

**Comment by niden** [comment]
Implemented https://github.com/phalcon/cphalcon/pull/15392
