### ISSUE TITLE
error:  Call to undefined method Phalcon\Paginator\Adapter\Model::getPaginate()

### ISSUE THREAD

**Issue by vlad2005** [phalcon/cphalcon#15409]
Hi!
I try to use Paginator but i got this error:
`error:  Call to undefined method Phalcon\Paginator\Adapter\Model::getPaginate()`

My code is this (from documentation)
`
use Scmd\Test;
use Phalcon\Paginator\Adapter\Model as PaginatorModel;

class TestController extends ControllerBase
{

    public function indexAction()
    {
    	
		$currentPage = isset($_GET['page']) ? (int) $_GET['page'] : 1;

		$paginator = new PaginatorModel(
			[
				'data'  => Test::find(),
				'limit' => 5,
				'page'  => $currentPage,
			]
		);

		$page = $paginator->getPaginate();
    	        $this->view->items = $page;
    }
`
Thanks in advance!
L.E.
Phalcon version 4.1.0
Php> 7.4.16

_Originally posted by @vlad2005 in https://github.com/phalcon/cphalcon/discussions/15406_

**Comment by ekmst** [comment]
```
$paginator = new PaginatorModel(
		[
			'model'  => Test::class,
			'limit' => 5,
			'page'  => $currentPage,
		]
	);
```

**Comment by vlad2005** [comment]
same error

**Comment by wurst-hans** [comment]
@vlad2005 There is no `getPaginate()` method in Paginator

**Comment by vlad2005** [comment]
Thank you!
I see now in source code that there are no method getPaginate, but simply paginate.
So, $paginator->getPaginate() need to be $paginator->paginate();
Anyway, documentation need to be updated.

Another strange issue is that I cannot access object properties when use paginator, but as an array.
`
//in controller:
$this->view->collection = $paginator->paginate();
`
`
//in view (volte template)
{% for object in collection.items %}
..........................................
{{ object.phone }}  //this not show anything
{{ object['phone'] }}  //this work ok
`
I say it's weird because collection.items encoded as json and output to page looks identical to what I get using in controller method find and send result to view, but in that case i can use object property.
