### ISSUE TITLE
[BUG]: Different types for Query\BuilderInterface::orderBy() and Query\Builder::orderBy(). 

### ISSUE THREAD

**Issue by StudioMaX** [phalcon/cphalcon#15415]
**Describe the bug**
Different types are specified for the `Phalcon\Mvc\Model\Query\Builder::orderBy()` and `Phalcon\Mvc\Model\Query\BuilderInterface::orderBy()` 

**To Reproduce**
https://github.com/phalcon/cphalcon/blob/0d8e2b6ce8f3b00848ee516a21bf8427e2553dc5/phalcon/Mvc/Model/Query/Builder.zep#L1309-L1316
https://github.com/phalcon/cphalcon/blob/0d8e2b6ce8f3b00848ee516a21bf8427e2553dc5/phalcon/Mvc/Model/Query/BuilderInterface.zep#L226

**Expected behavior**
Most likely an error in the interface, since the type allows arrays.
Probably this is also must be fixed in 5.x.

**Details**
 - Phalcon version: v5.0.0-alpha.1
 - PHP Version: -
 - Operating System: -
 - Installation type: -
 - Zephir version (if any): -
 - Server: -
 - Other related info (Database, table schema): -

**Comment by niden** [comment]
@StudioMaX Thank you for reporting this!

Resolved in: https://github.com/phalcon/cphalcon/pull/15416
