### ISSUE TITLE
Can't access object property for items -> Paginator\Adapter\Model

### ISSUE THREAD

**Issue by vlad2005** [phalcon/cphalcon#15410]
Description:
`//in controller:`
`$paginator = new PaginatorModel(`
`			[`
`				'model' => MyModel::class,`
`				'limit' => 5,`
`				'page'  => $currentPage,`
`			]`
`);`
`$this->view->collection = $paginator->paginate();`

and in view: (volte template)

`{% for object in collection.items %}`
`{{ object.phone }}`  //this not show anything, error in web server log file: `Trying to get property 'phone' of non-object`
`{{ object['phone'] }}`  //this work ok
`{% endfor %}`

Using QueryBuilder adapter for paging and no issue, so i think that Model adapter need to pe fixed.

_Originally posted by @vlad2005 in https://github.com/phalcon/cphalcon/issues/15409#issuecomment-822022437_

**Comment by aa65535** [comment]
FYI: #15074

**Comment by Jeckerson** [comment]
Use extended class inside your project - https://gist.github.com/Jeckerson/08be8255c541fca381d9c32713916f1c
