### ISSUE TITLE
[BUG]: Dynamic update model issue

### ISSUE THREAD

**Issue by chinalu** [phalcon/cphalcon#15413]
**Describe the bug**
Same as [#12773](https://github.com/phalcon/cphalcon/issues/12773),  when field type is `Decimal` or `Float`。

If old value in database is 1.0, then use RawValue to update this field, will reproduce this bug. Because of following logic
```
case Column::TYPE_DECIMAL:
case Column::TYPE_FLOAT:
    let changed = floatval(snapshotValue) !== floatval(value);
    break;
```

Because:
```
floatval(new \Phalcon\Db\RawValue("f+1")) === float(1)
```

So to reproduce the issue, should be 

1. snapshotValue is 1, 
2. use  RawValue to update this field
3. the field type is DECIMAL or FLOAT

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15781

**Comment by LlamaDuckGoose** [comment]
It looks like this change has broken how it handles mysql functions e.g.
This is taken from the function example Docblock.
`
 $subscriber->createdAt = new \Phalcon\Db\RawValue("now()");
`

```
PDOException #22007

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'now()' for column `database`.`table`.`created_at` at row 1
```
