### ISSUE TITLE
[BUG]: After upgrading to 4.1, a fatal error occurs when attempting to read from Redis cache if the model features private properties

### ISSUE THREAD

**Issue by RayHughes** [phalcon/cphalcon#15439]
**Describe the bug**
After upgrading to 4.1, a fatal error occurs when attempting to read from Redis cache if the model features private properties. The records from the cache are hydrated to a ResultSet so that they can be used in an OOP style.

This occurs using the QueryBuilder, PHQL, and ModelsManager.

```php
Fatal error: Uncaught Phalcon\Mvc\Model\Exception: Cannot access property 'some_id' (not public). in /var/www/app/src/Some/Repository/SomeRepository.php:54 

Stack trace: #0 [internal function]: Phalcon\Mvc\Model->__set('some_id', NULL) 
#1 [internal function]: Phalcon\Mvc\Model->unserialize('a:13:{s:7:"some...') 
#2 [internal function]: unserialize('a:6:{s:5:"model...') 
#3 [internal function]: Phalcon\Mvc\Model\Resultset\Simple->unserialize('a:6:{s:5:"model...') 
#4 [internal function]: Redis->get('cef116a4f2d770c...') 
#5 [internal function]: Phalcon\Storage\Adapter\Redis->get('cef116a4f2d770c...', NULL) 
#6 [internal function]: Phalcon\Cache->get('cef116a4f2d770c...') 
#7 /var/www/app/src/Some/Repository/SomeRepository.php(54): Phalcon\Mvc\Model\Query->execute(Array) 
#8 /var/www/app/src/Some/Service/SomeService.php(93): App\Some\Repository\SomeRepository->findActive() 
#9 /var/www/app/app/Controller/League/SomeController.php(32): Sh in /var/www/app/src/Some/Repository/SomeRepository.php on line 54
```

**To Reproduce**

1. Have a model with private properties 
2. Read / Write from Redis Cache

SomeRepository (Repository)

```php
class SomeRepository
{
    public function findActive(): ResultsetInterface
    {
        return Some::find([
            'conditions' => 'is_active != false',
            'cache' => [
                'key' => $this->calculateCacheKey(__METHOD__, []), 
                'lifetime' => self::CACHE_1D,
            ]
        ]);
    }
}
```

Some.php (Model)

```php
class Some extends Model
{
    private ?int $some_id = null;

    private ?bool $is_active = false;

    public function getSomeId(): ?int
    {
        return $this->some_id;
    }
    
    public function isActive(): ?int
    {
        return $this->is_active;
    }

    public function setIsActive(?int $isActive): void
    {
        $this->is_active = $isActive;
    }
    
    public function initialize(): void
    {
        $this->setSchema('public');
        $this->setSource('some');
    }
}
```

**Expected behavior**
1. ResultSet is returned from cache
2. Model private properties can be accessed via getters

**Details**
 - Phalcon version: 4.1.0
 - PHP Version: 7.4.16
 - Operating System: Ubuntu (Docker)
 - Installation type: Compiling from source
 - Zephir version (if any): N/A
 - Server: Nginx 
 - Other related info Postgres 12

**Comment by Jeckerson** [comment]
> Installation type: Compiling from source

What version of Zephir was used?

**Comment by RayHughes** [comment]
> > Installation type: Compiling from source
> 
> What version of Zephir was used?

this is what was used. I didn’t use Zephir

git clone --depth=1 "git://github.com/phalcon/cphalcon.git"
cd cphalcon/build
sudo ./install

**Comment by RayHughes** [comment]
Any comment on this? Not sure how to proceed. May have to stay v4 until this is resolved.

**Comment by niden** [comment]
@RayHughes I have not had time confirming this with a test. I will try and get to this this week coming if not earlier.

**Comment by RayHughes** [comment]
@niden np. We are okay for the time being on the 4.x branch. Just hoping its resolved sooner than later so we can get on the v5/6 upgrade path.

@Jeckerson 

```
Version => 4.1.0
Powered by Zephir => Version 0.12.19-4345593
```

**Comment by niden** [comment]
@RayHughes when you get a chance have a look at this:

https://github.com/niden/cphalcon/blob/T15439-model-redis-private-properties/tests/database/Mvc/Model/FindCest.php#L268

and the model is very similar to yours:

https://github.com/niden/cphalcon/blob/T15439-model-redis-private-properties/tests/_data/fixtures/models/Invoices.php#L47

I am unclear as to how you intend this to work. If I do a `find` in the model it will pick things up from the database so none of your private variables will be populated, they will keep their default values unless you change them somehow while you have the objects loaded. When you get them from Redis it will be the same, i.e. read from db -> store it to cache -> return it back to the user. (of course if cached already you get it straight from the cache).

Can you explain a bit more? Am I missing something?

**Comment by RayHughes** [comment]
It fails to hydrate to a model when coming to cache.

**Comment by niden** [comment]
@RayHughes Revisiting this issue.

I have compiled with the latest Zephir (14 beta 3) and run the tests on this branch. They seem to work fine. Can you have a look at the test itself and the logic and let me know if the test case covers the issue you are experiencing? The test is here:

https://github.com/niden/cphalcon/blob/T15439-model-redis-private-properties/tests/database/Mvc/Model/FindCest.php#L268

and the model is here:

https://github.com/niden/cphalcon/blob/T15439-model-redis-private-properties/tests/_data/fixtures/models/Invoices.php#L33

One thing I did notice is that I had not before was that in your example for your model:

```php
class Some extends Model
{
//...
    private ?bool $is_active = false;
//...
    public function isActive(): ?int
    {
        return $this->is_active;
    }

    public function setIsActive(?int $isActive): void
    {
        $this->is_active = $isActive;
    }
//...
}
```

The `is_active` is a private property and is `?bool`. There is also a database column (I think) called `is_active` and that is `?int`. Is this what you are referring to?  The db column and a private property having the same name?

**Comment by RayHughes** [comment]
Yea I caught that after I posted. It was a typo on my part with the incorrect column type but the issue still persists

**Comment by RayHughes** [comment]
After revisiting the issue I was able to resolve it by changing `isActive()` to `getIsActive()`.

**Comment by Jeckerson** [comment]
@RayHughes Hello, yes it is, please check this whole subsection - https://docs.phalcon.io/4.0/en/db-models#creating-models

> Additionally, getters and setters allow for future changes without changing the interface of the model class. So if a field name changes, the only change needed will be in the private property of the model referenced in the relevant getter/setter and nowhere else in the code.
