### ISSUE TITLE
[NFR]: Please Update CHANGELOG-4.1.md

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#15449]
Please update ``CHANGELOG-4.1.md`` at https://github.com/phalcon/cphalcon/blob/master/resources/CHANGELOG-4.1.md

for v4.1.2 what has changed? O_o You need to keep track of changes in CHANGELOG for those of us who do not wish to read every single bit of code LOL THANK YOU!

**Comment by niden** [comment]
Nothing much has changed really. 4.1.1 and 4.1.2 were maintenance releases. Actually 4.1.2 was released because we made a mistake when trying to update PECL

https://github.com/phalcon/cphalcon/releases

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15465

Thank you @v00v
