### ISSUE TITLE
[BUG]: Unable to change foreign key id after loading relation

### ISSUE THREAD

**Issue by berlinger-mschwartz** [phalcon/cphalcon#15442]
**Describe the bug**

My team and I are currently trying to upgrade from to Phalcon 4.1.2 from 4.0.6. Somehow, a seemingly trivial piece of code is no longer working as expected.

Saving an object after changing the id corresponding to a loaded relation does not yield the expected result of the object being saved correctly.

**To Reproduce**

This is a part of our model definition.

```
class CustomerModel extends Model
{
  // more code here
}

class Excursion extends CustomerModel
{
  protected $id;
  protected $root_cause;

  $this->hasOne('root_cause', RootCause::class, 'id', ['alias' => 'rootCause']);

  public function getRootCause(): ?RootCause
  {
    return $this->getRelationValue('rootCause');
  }
}

class RootCause extends CustomerModel
{
  protected $id;
  protected $root_cause;

  public function validation(): bool
  {
    $validator = (new Validation())
      ->add('root_cause', new Required(['label' => 'name']))
      ->add('root_cause', new Uniqueness(['label' => 'name']));

    return $this->validate($validator);
  }
}
```

```
$excursion = Excursion::findFirst(1);
// problem does not occur without the line below
$excursion->getRootCause(); // value of 1
$excursion->assign([
  'root_cause' => 2
]);
$excursion->update();
```

Then the Uniqueness validator fails, assumingly because it tries to (re-)insert the original root cause as a new record.

`[Phalcon\Mvc\Model\ValidationFailed] Field name must be unique`

A similar case that was being investigated by a colleague resulted in the object being saved, but without the new id being set.

**Expected behavior**

I expect the foreign key to be updated without any problem (as before).

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: 7.3
 - Operating System: macOS Big Sur 11.3

**Additional remarks**
Our application is quite complicated, so it can not be ruled out that we do some magic ourselves that is causing the issue (e.g. in `CustomerModel`). If that is indeed the case, then I'd like to know that as well.

**Comment by elexhani** [comment]
I am also facing same errors, If you found any helpful [guide](https://slotpg.games/) please let me know. Thanks

**Comment by BeMySlaveDarlin** [comment]
Can not reproduce error with given example.
Can you provide more detailed tables schema and models code?

**Comment by berlinger-mschwartz** [comment]
If the given example doesn't suffice, then it's likely to be caused by some magic we do in our application.

Thanks for checking this out. The issue can be closed now.

**Comment by BeMySlaveDarlin** [comment]
@berlinger-mschwartz 
As alernative, i can suggest using direct assigning pattern to change relations
```
$article = Articles::findFirst(1);
$tag = Tags::findFirst(1);
$article->tag = $tag;
$article->update();
```
