### ISSUE TITLE
[NFR]: Phalcon v5 Name Change

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#15450]
Can you guys change the name for Phalcon v5 to something else? To remove any confusions between v4 (Zephir/C) extension and new native (dynamic PHP) versions? This will also allow you to develop or maintain both versions seperately from each other. Especially if in the future some one well knowledged in Zephir/C decides to contiue v4 as extension. I think this would be the best move. Because as of right now, there is so much confusion between the versions and the work on Phalcon that makes me wana stop using it completely. I loved phalcon all this years, and you basicly killed the project with v5. Remember the main reason why people used Phalcon in the first place was SPEED. v5 is horrible speed in comparison. So I don't see this as an improvement.

Maybe call v5 something like "Phylum" or something...
"a principal taxonomic category that ranks above class and below kingdom."
seems appropriate for this change ^_^

**Comment by Jeckerson** [comment]
Hello

> Especially if in the future some one well knowledged in Zephir/C decides to contiue v4 as extension.

No one stopped to develop Zephir, use `watch` for Zephir to be with more opened eyes - https://github.com/zephir-lang/zephir/watchers . We continue to improve it for Phalcon use.

`phalcon/cphalcon` -> Zephir
`phalcon/phalcon` -> PHP + Zephir + C

`v5` will be as full C extension, first alpha release already occur - https://github.com/phalcon/cphalcon/releases/tag/v5.0.0-alpha.1 (with Zephir 0.13 - https://github.com/zephir-lang/zephir/blob/development/CHANGELOG.md#0130---2021-03-25)
`v6` will be parallel as PHP with `v5`

Both `v5` and `v6` will continue to use Zephir.

P.S. Also please stop to spam everywhere with your opinions, if you have questions - you can ask in real time in our discord - http://phalcon.io/discord

Closing.
