### ISSUE TITLE
[NFR]: Merge PECL `build/php7` and `build/php8` directories into one

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#15456]
Instead of having x2 separate directories, try to merge into single and generalize version check inside code.

Based on PR #15428

**Comment by remicollet** [comment]
Just to confirm, pecl archive created from the 5.0.0-akpha.2 tag works as expected

So RPM packages available in my repo https://twitter.com/RemiRepository/status/1390213609188470784

**Comment by ruudboon** [comment]
> Just to confirm, pecl archive created from the 5.0.0-akpha.2 tag works as expected
> 
> So RPM packages available in my repo https://twitter.com/RemiRepository/status/1390213609188470784

I do see some issues pushing this out on Pecl.
```Extension version mismatch between the package.xml (5.0.0alpha2) and the source code (5.0.0-alpha.2).```
