### ISSUE TITLE
does Phalcon support "IN BOOLEAN MODE" when using fulltextsearch in MySQL?

### ISSUE THREAD

**Issue by sonority** [phalcon/cphalcon#1546]
if you have a MySQL-table like this:
```sql
CREATE TABLE `filecontent` (
  `uid` int(11) NOT NULL DEFAULT '0',
  `fulltextdata` mediumtext,
  PRIMARY KEY (`uid`),
  FULLTEXT KEY `fulltextdata` (`fulltextdata`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```
...and if you want to use the fulltextsearch-capabilities of MySQL and query the following with Phalcon, everything works as expected:
```php
$filecontent = $this->modelsManager->createBuilder()
	->columns('*')
	->from('Filecontent')
	->where('MATCH(fulltextdata) AGAINST (:search:)', array('search' => $searchString))
	->getQuery()
	->execute();
```
but if you want to use the "*IN BOOLEAN MODE*" modfier, which is very important in some cases, you will get the following error:
```php
$filecontent = $this->modelsManager->createBuilder()
	->columns('*')
	->from('Filecontent')
	->where('MATCH(fulltextdata) AGAINST (:search: IN BOOLEAN MODE)', array('search' => $searchString))
	->getQuery()
	->execute();
```
```
Syntax error, unexpected token IDENTIFIER(BOOLEAN), near to ' MODE)', when parsing: SELECT * FROM [Filecontent] WHERE MATCH(fulltextdata) AGAINST (:search: IN BOOLEAN MODE)
```
does phalcon support this in PHQL? it seems that the "*IN*" is interpreted or parsed as "*...WHERE uid IN ()...*".

**Comment by andresgutierrez** [comment]
Check this: https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Db#dialectmysqlextended

**Comment by andresgutierrez** [comment]
You can use custom dialect functions since Phalcon 2.0.3 to support any SQL extension: https://blog.phalconphp.com/post/phalcon-2-0-3-released
