### ISSUE TITLE
[NFR]: Review and improve builds

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#15462]
Current implementation of `builds/` folder is a mess that was done ages ago and need to be implemented in more native form.

- [x]  Sort out with SDK and Dev tools for Windows builds
- [x] Unify win/mac/linux build to cross-platform build flow
- [ ] Replace build scripts with build system

Example: CMake - https://cmake.org/

**Comment by niden** [comment]
Closing this because it is ancient. Our builds are currently working with GitHub Actions and in the future we will enhance them as needed
