### ISSUE TITLE
[BUG]: Phalcon 5.0.0-A-2 Fatal error: Uncaught TypeError: Phalcon\Db\Dialect::getSqlExpressionFunctionCall()

### ISSUE THREAD

**Issue by borisdelev** [phalcon/cphalcon#15486]
Hello again :)

Today i try to run another project and see if PHP 8 / Phalcon 5 Alpha will work correctly. 
Well, i was surprised to see that error:
```
Fatal error: Uncaught TypeError: Phalcon\Db\Dialect::getSqlExpressionFunctionCall(): Argument #3 ($bindCounts) must be of type ?string, array given
```
... in such a so common line.

```php
        $new_orders = \Models\Orders::count([
            'conditions' => 'status IN ({statuses:array})',
            'bind' => [
                'statuses' => ['paid']
            ]
        ]);
```
That is all u need to reproduce that error.
I have not idea what is wrong and where is my mistake or its 5 Alpha bug.

Thanks again for everything and be happy :)

**Details**
 - Phalcon version: 5.0.0-alpha.2
 - PHP Version: 8.0.6
 - Operating System: Windows
 - Server: Apache
 - Other related info: mySql

![image](https://user-images.githubusercontent.com/4441663/117929375-68d61100-b305-11eb-99bf-f974b77e3ae3.png)
![image](https://user-images.githubusercontent.com/4441663/117929414-77bcc380-b305-11eb-8ca9-3b283c36d85f.png)

**Comment by Jeckerson** [comment]
Partially blocked by https://github.com/zephir-lang/zephir/issues/2245

**Comment by Jeckerson** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/15488

Thanks for report!
