### ISSUE TITLE
[BUG]: The expiration iImplementing of the Cache adapter is inconsistent.

### ISSUE THREAD

**Issue by aa65535** [phalcon/cphalcon#15485]
Description of expiration in PSR-16: 

> **Expiration** - The actual time when an item is set to go stale. This is calculated by adding the TTL to the time when an object is stored.
> 
> An item with a 300 second TTL stored at 1:30:00 will have an expiration of 1:35:00.
> 
> Implementing Libraries MAY expire an item before its requested Expiration Time, but MUST treat an item as expired once its Expiration Time is reached. If a calling library asks for an item to be saved but does not specify an expiration time, or specifies a null expiration time or TTL, an Implementing Library MAY use a configured default duration. **If no default duration has been set, the Implementing Library MUST interpret that as a request to cache the item forever, or for as long as the underlying implementation supports.**
> 
> **If a negative or zero TTL is provided, the item MUST be deleted from the cache if it exists, as it is expired already.**

The current status of each adapter:

| Adapter | Apcu | Libmemcached | Memory | Redis | Stream |
|--|-----|------------------|-----------|--------|---------|
|ttl = null|default TTL|default TTL|not work|default TTL|default TTL|
|ttl = 0|persistent|persistent|not work|report an error|expired|

The default TTL should be set by each adapter to ensure that the adapter can cache the item forever.
| Adapter | Apcu | Libmemcached | Memory | Redis | Stream |
|--|-----|------------------|-----------|--------|---------|
|default TTL|0|0|not work|null|large number or null|

If the default TTL of Stream is set to null, the `isExpired(array! payload)` method should return false.

**Comment by niden** [comment]
@aa65535 Can you look at this please and let me know if we got the definition correctly?

https://github.com/phalcon/phalcon/issues/208

**Comment by aa65535** [comment]
@niden It looks good.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15751

Thanks @aa65535
