### ISSUE TITLE
[BUG]: Loader should not load already loaded files

### ISSUE THREAD

**Issue by michalzielanski** [phalcon/cphalcon#15489]
I use `Phalcon\Loader` as the main autoloader, but some libraries (for example `laminas/laminas-zendframework-bridge`) register their autoloaders to load files before I can do so with `$loader->loadFiles()`, resulting in a "Cannot redeclare XYZ" error is raised.
`Phalcon\Loader` should use `require_once` instead of `require` so that the error does not appear.

https://github.com/phalcon/cphalcon/blob/20356b6e0c3d3aa9cc5d4963c918cd2dfef904fe/phalcon/Loader.zep#L121
https://github.com/phalcon/cphalcon/blob/20356b6e0c3d3aa9cc5d4963c918cd2dfef904fe/phalcon/Loader.zep#L194
https://github.com/phalcon/cphalcon/blob/20356b6e0c3d3aa9cc5d4963c918cd2dfef904fe/phalcon/Loader.zep#L253
https://github.com/phalcon/cphalcon/blob/20356b6e0c3d3aa9cc5d4963c918cd2dfef904fe/phalcon/Loader.zep#L378

**To Reproduce**
```php
// file_to_load.php
<?php
function onlyTest()
{
}

// script.php
<?php
$loader = new \Phalcon\Loader();
$loader->register();

$file = __DIR__ . DIRECTORY_SEPARATOR . 'file_to_load.php';
// Simulation of loading by another autoloader.
require $file;

$loader->registerFiles([$file]);
$loader->loadFiles();
```

**Comment by Izopi4a** [comment]
if you change

```
require $file;
``` 

to 
```
require_once $file;
```

i think it will be fine. Also i don't think you should be manually including files

**Comment by michalzielanski** [comment]
@Izopi4a, this is just a very simple example showing the bug. In fact, the code that registers the additional autoloader is in the composer package (`laminas/laminas-zendframework-bridge` required by `laminas/laminas-escaper`) which in turn is depending on the package I need (`phpoffice/phpword:0.18.1`).

**Comment by Jeckerson** [comment]
Will be possible to implement since Zephir `0.14.0` stable.
