### ISSUE TITLE
[BUG]: Storage adapter getKeys method return empty array when set prefix = ''

### ISSUE THREAD

**Issue by aa65535** [phalcon/cphalcon#15480]
```php
use Phalcon\Storage\Adapter\Libmemcached;
use Phalcon\Storage\SerializerFactory;

$factory = new SerializerFactory();
$options = [
    'servers'           => [
        [
            'host'   => '127.0.0.1',
            'port'   => 11211,
            'weight' => 1
        ]
    ],
    'defaultSerializer' => 'Php',
    'lifetime'          => 3600,
    'prefix'            => '' // set empty string
];

$adapter = new Libmemcached($factory, $options);

$adapter->getKeys(); // return empty array
```

If `pattern`is an empty string, `keys` should be returned directly.

https://github.com/phalcon/cphalcon/blob/c7a713de79d6a20739c6b524a34a188e67ea7d29/phalcon/Storage/Adapter/AbstractAdapter.zep#L138-L154

**Expected behavior**

```
When prefix is set to empty string, all keys should be returned
```

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: 7.4.16
 - Operating System:  CentOS 7
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Nginx

**Comment by BeMySlaveDarlin** [comment]
I suppose its related to `Libmemcached` adapter constructor
https://github.com/phalcon/cphalcon/blob/c7a713de79d6a20739c6b524a34a188e67ea7d29/phalcon/Storage/Adapter/Libmemcached.zep#L45-L61
As we can see, it sets `this->prefix  = "ph-memc-";`, so pattern is never empty.

**Comment by niden** [comment]
@aa65535 I am not convinced that this should happen.

By using the prefix we are namespacing so to speak the keys stored in the storage (Libmemcached in this case). If there are other processes using the same server, without the prefix, you will be able to retrieve keys that do not necessarily belong to your application.

Thoughts?

**Comment by aa65535** [comment]
Of course, the best practice is to set a unique prefix for each application, but you can use the constructor to set the prefix to an empty string.
The problem is that when the prefix is an empty string, getKeys() does not return the expected value.

```php
use Phalcon\Storage\Adapter\Libmemcached;
use Phalcon\Storage\SerializerFactory;

$factory = new SerializerFactory();
$options = [
    'prefix' => '' // set empty string
];

$mem = new Libmemcached($factory, $options);

var_dump($mem->getPrefix()); // string(0) ""
var_dump($mem->getKeys()); // array(0) {}

$redis = new Redis($factory, $options);
var_dump($redis->getPrefix()); // string(0) ""
var_dump($redis->getKeys()); // array(0) {}
```

**Comment by niden** [comment]
I will write a couple of tests to ensure that the key can be changed if need be but never be empty. I do not recall the code right now but will check just in case.

**Comment by niden** [comment]
After discussions with @Jeckerson we decided to offer this functionality. If the user wishes to not use a prefix, they can specify an empty prefix with the passed `$options` array.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15654
