### ISSUE TITLE
[BUG]: Redis storage adapter uses the wrong connection timeout

### ISSUE THREAD

**Issue by aa65535** [phalcon/cphalcon#15484]
`this->lifetime` is the default TTL of the adapter.

https://github.com/phalcon/cphalcon/blob/c7a713de79d6a20739c6b524a34a188e67ea7d29/phalcon/Storage/Adapter/AbstractAdapter.zep#L35-L40

But it is used for the redis connection timeout.

https://github.com/phalcon/cphalcon/blob/c7a713de79d6a20739c6b524a34a188e67ea7d29/phalcon/Storage/Adapter/Redis.zep#L137-L142

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15487

Thank you @aa65535 for reporting this
