### ISSUE TITLE
[NFR]: Using init() on session bag should store data in session

### ISSUE THREAD

**Issue by wurst-hans** [phalcon/cphalcon#15494]
The `init()` method for session bag should persist the array data in session, too. Currently, this true only for setting a new value via `set()` (see [here](https://github.com/phalcon/cphalcon/blob/4.1.x/phalcon/Session/Bag.zep#L114)).

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15706

Thanks @wurst-hans
