### ISSUE TITLE
[BUG]: The cipher algorithm "AES-256-ECB" is not supported on this system.

### ISSUE THREAD

**Issue by mahen3d** [phalcon/cphalcon#15496]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**

In phalcon 4.1.2  does phalcon\crypt has support for AES-256-CBC?

```
$di->set('crypt', function () use($config) {
        $crypt = new Crypt();
        $crypt->setCipher("aes-256-ecb");
        $crypt->setPadding(2);
        $crypt->setKey(
            $config->security->network_key
        );
        return $crypt;
    });
```

gives the following error

**Phalcon\Crypt\Exception: The cipher algorithm "AES-256-ECB" is not supported on this system.**

 Php7.4 
 Centos 8

**Comment by niden** [comment]
This is correct. 

The `ecb` algos are not supported. The same as `des`, `rc2`, `rc4`, `md5`. The manual states that `ecb` should be avoided and therefore we filter it out.

https://www.php.net/manual/en/function.openssl-get-cipher-methods.php (Scroll to the first example)

Here is where the filtering happens: https://github.com/phalcon/cphalcon/blob/master/phalcon/Crypt.zep#L585
