### ISSUE TITLE
estou tentando instalar o Phalcon , win10

### ISSUE THREAD

**Issue by antoniocarlosferreira** [phalcon/cphalcon#15505]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste output here
```

**Expected behavior**

```php
// paste code
```

**Screenshots**

**Details**
 - Phalcon version: (`php --ri phalcon`)
 - PHP Version: (`php -v`)
 - Operating System:
 - Installation type: Compiling from source || installing via package manager
 - Zephir version (if any):
 - Server: Nginx | Apache | Other
 - Other related info (Database, table schema):

**Additional context**

**Comment by Jeckerson** [comment]
Please describe exactly what is the problem.
