### ISSUE TITLE
[NFR]: Support of PHP-PSR 1.1.0

### ISSUE THREAD

**Issue by StudioMaX** [phalcon/cphalcon#15504]
**Is your feature request related to a problem? Please describe.**
Docs says that we are required to use `php-psr 1.0.*`.
> NOTE: You will need the PSR 1.0 extension installed. 

But this is a problem if other frameworks are used at the same time like Symfony, which in new versions requires `psr/container ^1.1`. The PHP-PSR 1.0.x specifies version `1.0.0` for `psr/container`. Because of this, we are in an incomprehensible situation when a project requires `psr/container ^1.1` in the composer.json, successfully installs it, and in fact, `psr/container` from PHP-PSR extension is used, since it has priority over the composer's library. 

**Describe the solution you'd like**
Allow to install [PHP-PSR extension 1.1.0](https://github.com/jbboehr/php-psr/releases/tag/v1.1.0)

**Additional context**
According to the PHP-PSR changelog, the difference between version 1.0.1 and version 1.1.0 is only in fixing support for `psr/container` to version `1.1.1`.

Also I have installed the PSR extension 1.1.0 locally and don't see any problems with my project. Maybe this only needs to be fixed in the documentation?

**Comment by niden** [comment]
@StudioMaX We rely on PECL's PSR package. As of this moment there is no extension that offers container 1.1.1. The PR has been put on draft until that happens.

**Comment by StudioMaX** [comment]
Thanks! As one of the possible improvements to the support of PSR interfaces - do you see the possibility of removing the requirement for the mandatory presence of the PSR extension in runtime?
Since most projects now work through Composer, I think it would be nice to determine the presence of PSR interfaces through autoloading. Thus, it was possible to use two ways to find interfaces: 
1) As now, with an installed PSR extension
2) By autoloading, installed via composer or manually

And just throw an exception if someone try to use the Logger/Cache and any other component if the required interfaces are not found.

**Comment by StudioMaX** [comment]
Further to my previous comment.
I found this issue related to my problem - https://github.com/jbboehr/php-psr/issues/88
It seems impossible to abandon the use of the PHP-PSR extension in favor of autoloading, since only in this way the extension (Phalcon) can load the interfaces.

**Comment by Jeckerson** [comment]
Related #15610

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15506
