### ISSUE TITLE
[BUG]: Some Custom Validators don't handle the allowEmpty

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#15515]
I'm trying to use the built-in Date validator in 4.1.2, and it seems to be ignoring the "allowEmpty" option.

Something analogous to this still generates an error when `payment_2_date` is NULL;
```php
$Validator->add(
	[
		'payment_1_date',
		'payment_2_date'
	],
	new Date([
		'format'=>[
			'payment_1_date'=>'Y-m-d',
			'payment_2_date'=>'Y-m-d H:i:s'
		]
		'message'=>[
			'payment_1_date'=>'Payment 1 date is not valid',
			'payment_2_date'=>'Payment 2 date is not valid'
		]
		'allowEmpty'=>[
			'payment_1_date'=>FALSE,
			'payment_2_date'=>TRUE
		]
	])
);
```

Looking at the [Zephir source for the Date validator](https://github.com/phalcon/cphalcon/blob/master/phalcon/Validation/Validator/Date.zep), it has `allowEmpty()` as an option in the comments for `__construct()`, but doesn't act on it anywhere.  I also checked the `Alnum` and `Alpha` validators - same deal.

I know comments in Zephir source code aren't considered "public documentation", but there's been a mistake somewhere - either in copy-pasting the comments, or omitting this necessary functionality.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15772
