### ISSUE TITLE
[BUG]: Db::fetch_func error could not call user-supplied function

### ISSUE THREAD

**Issue by dranzers** [phalcon/cphalcon#15543]
I have code like this:

```
$sql = "SELECT id_cp_mk id, id_mk mataKuliahId, deskripsi, deskripsi_inggris deskripsiEn , bobot, urutan 
            FROM cp_mk WHERE id_mk = :idmk ";
$query = $this->db->query($sql, ['idmk' => $id]);
$result = $query->fetchAll(Db::FETCH_FUNC, array(RencanaEvaluasiMk::class, 'buildFromPdo'));
```
and function static

```
class RencanaEvaluasiMk {

public static function buildFromPdo( $id, $mataKuliahId, $deskripsi,
$deskripsiEn, $bobot, $urutan )
{
$this->id = new RencanaEvaluasiMkId($id);
$this->mataKuliahId = new MataKuliahId($mataKuliahId);
$this->deskripsi = $deskripsi;
$this->deskripsiEn = $deskripsiEn;
$this->urutan = $urutan;
$this->bobot = $bobot;
}
}
```

then i'm get error
could not call user-supplied function

how to fix this. ?

**Comment by Jeckerson** [comment]
Hello, could you specify error message?

**Comment by dranzers** [comment]
I want get data with Phalcon\Db::FETCH_FUNC but its not working. In php pdo it works like this (https://stackoverflow.com/questions/15393763/how-do-i-use-an-object-method-in-pdofetch-func/15394144). I try with phalcon still not working.  Can you help me ?

**Comment by dranzers** [comment]
sorry if my english bad

**Comment by dranzers** [comment]
i change query sql in where like this
id_mk = ?

then
 $this->db->query($sql, [ $id]);
