### ISSUE TITLE
[BUG]: BelongsTo relation values are not correctly stored in Phalcon 4

### ISSUE THREAD

**Issue by krazzer** [phalcon/cphalcon#15572]
**Describe the bug**
When trying to store a value of a BelongsTo relation, it is not stored. Worked in v3.4.5 but not in v4

**To Reproduce**
```php
use Phalcon\Db\Adapter\Pdo\Sqlite;
use Phalcon\Db\Column;
use Phalcon\Db\Index;
use Phalcon\Di;
use Phalcon\Mvc\Model;

$di = new Di();
$db = new Sqlite(["dbname" => ":memory:"]);

$di->set('db', $db);
$di->set('modelsManager', new Model\Manager());
$di->set('modelsMetadata', new Model\MetaData\Memory());

Di::setDefault($di);

$db->createTable('person', '', [
    'columns' => [new Column('id', ['type' => 0]), new Column('name', ['type' => 2])],
    'indexes' => [new Index('PRIMARY', ['id'])]]);

$db->createTable('person_hair', '', [
    'columns' => [new Column('person_id', ['type' => 0]), new Column('color', ['type' => 2]), new Column('length', ['type' => 2])],
    'indexes' => [new Index('PRIMARY', ['person_id'])],
]);

class Person extends Model
{
    public function initialize()
    {
        $this->setSource('person');
        $this->hasOne('id', PersonHair::class, 'person_id', ['alias' => 'hair', 'reusable' => true]);
    }
}

class PersonHair extends Model
{
    public function initialize()
    {
        $this->setSource('person_hair');
        $this->belongsTo('person_id', Person::class, 'id', ['alias' => 'person', 'reusable' => true]);
    }
}

$db->insert('person', [1, 'Tim Cook'], ['id', 'name']);
$db->insert('person_hair', [1, 'Black', 'Long'], ['person_id', 'color', 'length']);

$timCook = Person::findFirst(1);

echo $timCook->name . PHP_EOL;

$timCookHair = PersonHair::findFirst(1);

$timCookHair->person->name = 'Timothy Cook';
$timCookHair->save();

$timCook2 = Person::findFirst(1);

echo $timCook2->name . PHP_EOL;

// outputs:
// Tim Cook
// Tim Cook
```

**Expected behavior**

```php
// Tim Cook
// Timothy Cook
```

**Screenshots**

**Details**
 - Phalcon version: 4.1.0
 - PHP Version: 7.4.13
 - Operating System: MacOS
 - Installation type: Compiling from source / Cloudlinux
 - Server: Apache
 - Other related info (Database, table schema): See code example

**Additional context**
This problem occurs in 4.1.0 but not in 3.4.5

**Comment by wurst-hans** [comment]
Same behavior here.

**Comment by Jeckerson** [comment]
Probably related https://github.com/phalcon/cphalcon/issues/15649

**Comment by BeMySlaveDarlin** [comment]
As we see in 3.4.x codebase, this behaviour was default since start of phalcon
https://github.com/phalcon/cphalcon/blob/3.4.x/phalcon/mvc/model.zep#L2866
https://github.com/phalcon/cphalcon/blob/3.4.x/phalcon/mvc/model.zep#L2778
Due to this behavior, you are not allowed save master records from child relations.

@Jeckerson @niden If there is no specific reasons for this restriction, i created #15771 with removal of this behavior.

**Comment by BeMySlaveDarlin** [comment]
UPD: after some workarounds with that changes in pr, got infinite loop:
`relation->save() ==> master->save() ==> relation->save() ...`

In this cases i can only recommend to do explicit save.
