### ISSUE TITLE
[BUG]: dirty state isn't saved when serialize a model

### ISSUE THREAD

**Issue by stijn1989** [phalcon/cphalcon#15571]
**Describe the bug**
When you have a form with an existing entity (state is persisted) and then you save the form in a session. When you retrieve the form on the next request (or more future requests), you get the form with it's entity. Every data is restored, except the dirty state.
This is because the serialize() method in Model class, only saves the data and not the state. 
When unserializing the entity, it returns to it's default dirty state, transient. 

**To Reproduce**

```php
class Person extends \Phalcon\Model
{
    public $name;
}

....

$person  = Person::findFirst();
echo "Dirty state = " . $person->getDirtyState(); //Dirty state = 0
$serialized = serialize($person);
$person = unserialize($serialized);
echo "Dirty state = " . $person->getDirtyState(); //Dirty state = 1
```

**Expected behavior**
You should expect that the dirty state isn't changed.

```php
$person  = Person::findFirst();
echo "Dirty state = " . $person->getDirtyState(); //Dirty state = 0
$serialized = serialize($person);
$person = unserialize($serialized);
echo "Dirty state = " . $person->getDirtyState(); //Dirty state = 0
```

**Details**
 - Phalcon version: 4.1
 - PHP Version: 7.3
 - Operating System: Debian
 - Installation type: PECL
 - Zephir version (if any):
 - Server: Nginx
 - Other related info (Database, table schema): MariaDB

**Additional context**
I found this out because I save my form to session and then restore it from session when submitted.
One of the entities has a validator Uniqueness validator. There is a check in which the entity is check on dirty state == 0.
So when submitted with the same value as in the database row, it failed on this validator. Because the state == 1 and so it doesn't leave out the row linked with the entity while validating. 

I extended the serialize() method so it saves the dirty state. Maybe there is a reason behind this why state is not saved?

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15780
