### ISSUE TITLE
Assign ID on group of radios

### ISSUE THREAD

**Issue by stijn1989** [phalcon/cphalcon#15591]
https://github.com/phalcon/cphalcon/blob/44aa04c9871b4d9f14c8815b3b46df1817316074/phalcon/Tag.zep#L1473

I have a group of radios, which has the same name but different value. But they get the same ID. This gives a warning in the browser console.

One question: why?

**Comment by Jeckerson** [comment]
Hello

You can specify manually the id during radio input construction.
