### ISSUE TITLE
[BUG]: model keepSnapshots and set empty array in relation

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/cphalcon#15590]
**Describe the bug**
This is the continuation of the error #14822. If is set empty array to relation and if in model is set keepSnapshots = TRUE then is internal error.

**To Reproduce**
If exitsts entity A and has many entities B

```php
class A extends Model
{
    public function initialize()
    {
        // if is TRUE is ERROR if is FALSE NO ERROR
        $this->keepSnapshots(true);
        $this->hasMany(
            'id',
            B::class,
            'a_id',
            'manyB'
        );
    }
}
class B extends Model
{
    // ...
}
```

and run this code:
```php
$a = \A::findFirst();
// it is important
$a->manyB = [];
$records = $a->getRelated('manyB');
var_dump($records);
```

**Expected behavior**
After running above code is internal error

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: 7.4
 - Operating System: Linux Debian
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Nginx
 - Other related info (Database, table schema): MariaDb

**Comment by BeMySlaveDarlin** [comment]
First of all, thanks for report.

Setting model relations expects:
- `Resultset`
- `Model`
- `null`

If you want to set empty relation, use `null` instead of empty array

**Comment by niden** [comment]
Closing

**Comment by zak-wojtek77** [comment]
> If you want to set empty relation, use null instead of empty array

I used NULL and is OK. Thank you.
