### ISSUE TITLE
[BUG]: php-fpm7.2[952]: segfault at 7fff0197af40 ip 00007f39a2b2fc1b sp 00007fff0197aee0 error 6 in phalcon.so[7f39a2ac3000+483000]

### ISSUE THREAD

**Issue by amitc005** [phalcon/cphalcon#15612]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
Php-FPM7.2 is failing to execute

**To Reproduce**

N/A

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste output here
```

**Expected behavior**
Should execute the code.

Code is Calling a database and the result has 4000 rows. 

**Screenshots**
```
php-fpm7.2[976]: segfault at 7fff0197af40 ip 00007f39a2b2fc1b sp 00007fff0197aee0 error 6 in phalcon.so[7f39a2ac3000+483000]
```

**Details**
 - Phalcon version: 3.4.5
 - PHP Version: (`php -v`)
```
PHP 7.2.24-0ubuntu0.18.04.8 (cli) (built: Jul  5 2021 17:41:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.8, Copyright (c) 1999-2018, by Zend Technologies
``` 
 - Operating System: Ubuntu 18
 - Server: Nginx 
 - Other related info (Database, table schema):

**Comment by Jeckerson** [comment]
You are using legacy Phalcon's version `3.4.5`, which isn't supported. Please upgrade to latest version.
