### ISSUE TITLE
[BUG]: install throws warning

### ISSUE THREAD

**Issue by DestinyMKas** [phalcon/cphalcon#15628]
**Describe the bug**
When I try to do ./install I get warning

**To Reproduce**
$ git clone --depth=1 "git://github.com/phalcon/cphalcon.git"
$ cd cphalcon/build
$ sudo ./install
**./install: line 66: [: missing `]'**
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la      modules/* libs/*
Cleaning..
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902

**Comment by Jeckerson** [comment]
Will be fixed in #15648
