### ISSUE TITLE
[BUG]: Lang:parsePHQL using phql_parse_phql removes "not" in column name

### ISSUE THREAD

**Issue by velser** [phalcon/cphalcon#15635]
**Describe the bug**
When adding condition to where, phql parse function removes "not" part if column name is starting with "not".

**To Reproduce**

1. Create query builder
2. Add where(andWhere) condition such as andWhere('notification_sent = true')
3. Get sql query via getSql
4. Result will be "ification_sent = true" instead of "notification_sent = true"

Phql before parse:
`SELECT mf.* FROM [Ns\Entity\MyObject] AS [mf] WHERE (mf.status = :status:) AND (mf.notification_sent = false)`

Sql after parse:
`SELECT "mf"."id", "mf"."notification_sent" FROM "month_fer" AS "mf" WHERE ("mf"."status" = :status) AND ("mf"."ification_sent" = FALSE)`

As you can see, it properly parses object columns, but not the where part...

> Provide minimal script to reproduce the issue

```php
$result = (new Builder())
            ->where('id = 1')
            ->andWhere('notification_sent = true')
            ->getQuery()
            ->execute()
        ;
```

**Expected behavior**
Proper query to be built

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: php-fpm 7.4.22
 - Operating System: alphine
 - Installation type: Compiling from source

**Additional context**

I saw related post here: https://www.gitmemory.com/issue/phalcon/cphalcon/14940/693322840

Had no issues with phalcon 3, now migrating to 4 having such an issue

**Comment by Jeckerson** [comment]
Duplicate, closing in favour https://github.com/phalcon/cphalcon/issues/14641
