### ISSUE TITLE
BIGINT truncated when use intval() 

### ISSUE THREAD

**Issue by chinalu** [phalcon/cphalcon#15632]
https://github.com/phalcon/cphalcon/blob/44aa04c9871b4d9f14c8815b3b46df1817316074/phalcon/Mvc/Model.zep#L884

**Comment by chinalu** [comment]
`BIGINT` **Should not** treated like `int`

https://github.com/phalcon/cphalcon/blob/44aa04c9871b4d9f14c8815b3b46df1817316074/phalcon/Db/Adapter/Pdo/AbstractPdo.zep#L522

**Comment by Jeckerson** [comment]
Could you provide example in numbers?

**Comment by chinalu** [comment]
> Could you provide example in numbers?

Thank you for your reply. 

Try numbers like 13672236791008669868, 13672252041003479307

**Comment by Izopi4a** [comment]
hmmm... it looks like you are pushing it a bit too far https://www.php.net/manual/en/reserved.constants.php#constant.php-int-max

I mean this is above bigint and close to unsigned bigint, I am not sure PHP is the right tool if you are planning to work with such big numbers

**Comment by Jeckerson** [comment]
This only occur when `BIGINT` column is defined as `UNSIGNED`. PHP's max int is **signed**.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15703
