### ISSUE TITLE
[BUG]: Model::find result iteration internally calls findFirst multiple times

### ISSUE THREAD

**Issue by elcreator** [phalcon/cphalcon#15699]
**Describe the bug**
Model::find internally calls findFirst multiple times for each item and it's relations leading to huge amount of queries

**To Reproduce**

```php
use Phalcon\Mvc\Model;
class BaseModel extends Model
{
…
/**
 * @param array $filter
 * @return Model[]
 */
public static function listFiltered(array $filter = [])
{
    $items = [];
    $all = self::find($filter);
    foreach ($all as $item) {
        $items[] = $item;
    }
    return $items;
}
}


class Device extends \BaseModel
{

public function initialize()
{
  …
  $this->belongsTo('lastSubscriptionId', Subscription::class, 'id', ['alias' => 'subscription']);
  $this->belongsTo('subscriptionId', Subscription::class, 'id', ['alias' => 'subscription']);
}

…
public static function listDevices($userId)
{
    $result = self::listFiltered(['userId = ?0', 'bind' => [$userId]]); // Why this calls findFirst so many times?
    …
}
}

Device::listDevices(1);
```

**Expected behavior**
find output returns single select query results

**Screenshots**
![Screenshot 2021-10-01 at 15 07 11](https://user-images.githubusercontent.com/974975/135617472-7629f746-db68-4a08-a409-9b0763fd1d37.png)

**Details**
 - Phalcon version: (`php --ri phalcon`) 5.0.0alpha6
 - PHP Version: (`php -v`) 7.4
 - Operating System: Ubuntu 20
 - Installation type: pear install
 - Zephir version (if any): 0.14.0-beta.3-0be9ad5
 - Server: Nginx
 - Other related info (Database, table schema): MySQL

**Comment by BeMySlaveDarlin** [comment]
By default orm behavior is `lazy-loading`.
`$all = self::find($filter);` returns ResultSet instance.
It does no requests and hydrations before you call record itself (as native php iterators and generators works).
This loop acts as callable, hydrating and initializing records with its relations (which requires requests for each)
```
    foreach ($all as $item) {
        $items[] = $item;
    }
```
To make it one-request thingy, most of ORMs uses `eager-loading`.
For example Laravel Eloquent `with('relation')` method provides this behavior.

RN you can use:

- custom query-builder for building complex request
- or find something fresh enough like [phalcon.eager-loading](https://github.com/stibiumz/phalcon.eager-loading)

**Comment by niden** [comment]
Closing.

**Comment by elcreator** [comment]
Thank you. Shouldn't this be a part of Phalcon? Looks like a very common thing

**Comment by BeMySlaveDarlin** [comment]
Yes. This is common feature, but we have not enough resources to implement it till v6 native php gets released.
