### ISSUE TITLE
[NFR]: HJSON Config Support

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#15696]
Request for HJSON (https://hjson.github.io/) in phalcon configs it supports comments and allows to write easier to read JSON configs. It can have similar functions to existing Configs in https://docs.phalcon.io/4.0/en/api/phalcon_config

HJson config example:
```hjson
/* HJson Config Example 
 Created Sep. 29th, 2021 */
[
  # Phalcon Config
  phalcon: [
    // App Base URI
    baseuri: /phalcon/
    # Some Models
    models: [
      metadata: memory
    ]
  ]
]
```

PHP example based on docs:
```php
use Phalcon\Config\Adapter\HJson;
$config = new HJson("path/config.hjson");
echo $config->phalcon->baseuri;
echo $config->models->metadata;
```

Valid HJSON File:
```hjson
{
  # Comment
  // Comment
  human:   Hjson
  /* Comment */
  machine: JSON
  /* RegEx Allowed */
  RegEx: \s+
  # Multi Line Allowed
  md:
    '''
    First line.
    Second line.
      This line is indented by two spaces.
    '''
  // allow trailing commas
  list: [
    1,
    2,
  ]
}
```

**Comment by niden** [comment]
We will let the community decide on this.

My 2 cents though: why is this necessary? I can see the benefit of having such functionality but `json_encode` and `json_decode` are the two main methods used when parsing JSON and are part of PHP. To introduce HJSON one has to implement something that would allow the parsing of the file with HJSON format. 

I checked GitHub and there is such a parser but it is around 1-2k lines long. To introduce such complexity into Phalcon will make this parsing slower and not faster plus it will be bloat on the framework.

/0.02 USD.

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/cphalcon/issues/14608#issuecomment-932505725 Will revisit if the community votes for it, or in later versions.
