### ISSUE TITLE
Documentation: querying specific fields

### ISSUE THREAD

**Issue by kcalliauw** [phalcon/cphalcon#1570]
I had a tough time finding this syntax. Can I suggest it is added to the documentation?

``` php
$myRobots = Robots:find(array(
        "fields" => array("name" => 1)
    )
);
```

The above find() only returns the name. It can be combined with a condition as well. Below only returns the name of the robots with type = maid.

``` php
$myRobots = Robots:find(array(
        array("type" => "maid"),
        "fields" => array("name" => 1)
    )
);
```

Adding this to the docs (and source code comments for the find() method) might help people.

/Koen
##

**Comment by Green-Cat** [comment]
Not a bug, should probably be opened on the documentation repo instead.
