### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by ZMNOTZ** [phalcon/cphalcon#15708]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
/usr/bin/php -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=127.0.0.1 /Users/emery/PhpstormProjects/server/public/index.php

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

```php
 $di = new FactoryDefault();
```
the script interrupted while the debugger stepped into this block

**Expected behavior**
it can step next

**Screenshots**
![image](https://user-images.githubusercontent.com/22322315/135749817-c5c3ec9d-2e87-48bf-a678-c9234015dedf.png)

**Details**
 - Phalcon version: (4.1.2)
 - PHP Version: (7.3.11)
 - Operating System: MacOS 10.15.4
 - Installation type: Compiling from source
 - Server: Apache 
 - IDE: PhpStorm 2021.2.2

**Additional context**

**Comment by Jeckerson** [comment]
> Installation type: Compiling from source

From `build/` directory or via zephir?

**Comment by ZMNOTZ** [comment]
> > Installation type: Compiling from source
> 
> From `build/` directory or via zephir?

build/

**Comment by ZMNOTZ** [comment]
> > Installation type: Compiling from source
> 
> From `build/` directory or via zephir?
```
phpize
```
```
.configure -with-php-config
```
```
make
```
```
make test
```
finally, I copy /module/phalcon.so to my php extention dir

**Comment by Jeckerson** [comment]
Could you provide example code? Also could you upgrade your PHP `7.3.11` until latest `7.3.31`?

**Comment by ZMNOTZ** [comment]
I use phalcon dev-tools create project  and I debug run index.php script 

the console log
```
/usr/bin/php -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=127.0.0.1 /Users/emery/PhpstormProjects/store/public/index.php

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

```
```
<?php
declare(strict_types=1);

use Phalcon\Di\FactoryDefault;

error_reporting(E_ALL);

define('BASE_PATH', dirname(__DIR__));
define('APP_PATH', BASE_PATH . '/app');
define('APP_NAME', 'store');

try {
    /**
     * The FactoryDefault Dependency Injector automatically registers
     * the services that provide a full stack framework.
     */
    $di = new FactoryDefault();
    $requset = new \Phalcon\Http\Request();

    /**
     * Read services
     */
    include APP_PATH . '/config/services.php';

    /**
     * Handle routes
     */
    include APP_PATH . '/config/router.php';

    /**
     * Get config service for use in inline setup below
     */
    $config = $di->getConfig();

    /**
     * Include Autoloader
     */
    include APP_PATH . '/config/loader.php';

    /**
     * Handle the request
     */
    $application = new \Phalcon\Mvc\Application($di);

    $application->handle($requset->getURI())->send();
} catch (\Exception $e) {
    echo $e->getMessage() . '<br>';
    echo '<pre>' . $e->getTraceAsString() . '</pre>';
}

```
