### ISSUE TITLE
[BUG]: Rename `\Phalcon\Support\Collection\Readonly` for PHP 8.1 support

### ISSUE THREAD

**Issue by KalleZ** [phalcon/cphalcon#15767]
**Describe the bug**
The `\Phalcon\Support\Collection\ReadOnly` class (previously known as `\Phalcon\Collection\ReadOnly`) does not work with PHP 8.1's new read-only feature:

https://wiki.php.net/rfc/readonly_properties_v2

**To Reproduce**
https://3v4l.org/ioc85

**Details**
 - Phalcon version: Irrelevant
 - PHP Version: PHP 8.1
 - Operating System: Irrelevant
 - Installation type: Irrelevant
 - Zephir version (if any): Irrelevant
 - Server: Irrelevant
 - Other related info (Database, table schema): None

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15768
