### ISSUE TITLE
[BUG]: Camelize helper does not camelCase, and also fails with space delimiters

### ISSUE THREAD

**Issue by lcdennison** [phalcon/cphalcon#15850]
**Describe the bug**
The Camelize string helper fails on a few fronts. See obvious issues below.

**To Reproduce**

```php
## Issue #1: Outputting pascal case, not camel case
echo (new \Phalcon\Support\Helper\Str\Camelize())('customer-session'); // default delimiters are "-_"
// outputs "CustomerSession"

// This is PascalCase, not camelCase. The correct result should be "customerSession" if you're calling it a "camelize" function.

## Issue #2: Using space delimiter consumes capital characters
echo (new \Phalcon\Support\Helper\Str\Camelize())('customer Session', ' -_'); // Note the additional space in the delimiters
echo (new \Phalcon\Support\Helper\Str\Camelize())('customer-Session', ' -_'); // Note the additional space in the delimiters
// both statements output "CustomerEssion"

// The correct result is "customerSession" for both. Note this does NOT happen if the string
//   is "customer-session" or "customer session" (i.e. if the "S" is not capital, it does not get removed from the string)
```

**Expected behavior**
I use the following function, which converts the above test strings to `customerSession` as expected in all cases.
```php
// camelCase:
lcfirst(str_replace(' ', '', ucwords(preg_replace('/[^a-zA-Z0-9\x7f-\xff]++/', ' ', $input))));
```

If you want PascalCase and snake_case as well:
```php
// PascalCase
str_replace(' ', '', ucwords(preg_replace('/[^a-zA-Z0-9\x7f-\xff]++/', ' ', $input))); // same as above, just without the lcfirst()
// snake_case
strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $input));
```

**Details**
 - Phalcon version: 5.0.0-beta1
 - PHP Version: 8.0.14

**Comment by niden** [comment]
@lcdennison We have a few things going on here.

For v4 and before the `camelize` method was using a built in method (written in C) in Zephir. For v5 I rewrote the method to a non pure C implementation, with the later goal to translate that to PHP.

Running your examples with the v3/v4 version of camelize produces:

```
-'customer-session' : +'CustomerSession'
-'customer-Session' : +'CustomerSession'
-'customer Session' : +'CustomerSession'
```

So for the v4 version of this method and before you get `CustomerSession` for all examples. The particular method has not changed for prior versions so it was always returning the first character capitalized.

Running this with the current code, gives the results you gave and for sure the last case (`" -_"`) produces the wrong result, removing the `S` from `Session`.

I can correct at least the last example but I am afraid if I change this method, a lot of current applications will break because for better or worse, this method was always returning the first character capitalized.

Thoughts?

**Comment by niden** [comment]
We could also introduce one more parameter in the `__invoke` to do the lower case for the first letter. This way we can have the current functionality but also allow for new one. Additional helpers can be created for pure pascal or snake case

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15851

**Comment by lcdennison** [comment]
@niden Sorry for the delayed reply. I certainly understand about not wanting to break existing usages that rely on the capitalized first letter. The changes you committed seem to solve everything nicely. For anyone that wants to make Camelize truly camelCase, they can pass the $lowerFirst = true flag on that invocation. Or additionally, for new codebases, just extend the Camelize class to set $lowerFirst = true by default and use that extended class instead of the base Phalcon one.

I also see a few extra helper classes for pascal, snake, and kebab. Thanks for that!

**Comment by lcdennison** [comment]
@niden One minor bug/inconsistency I think with your fix, didn't notice before. The "Kebab" and "Snake" case delimiters are swapped. The comment for kebab says "kebab-case" but uses the "_" delimiter:
https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/KebabCase.zep#L14
https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/KebabCase.zep#L32

 Similarly, the comment for snake says "snake_case" but uses the "-" delimiter:
https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/SnakeCase.zep#L14
https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/SnakeCase.zep#L32

I believe those delimiters just need to be swapped (and the corresponding tests updated).

**Comment by niden** [comment]
> @niden One minor bug/inconsistency I think with your fix, didn't notice before. The "Kebab" and "Snake" case delimiters are swapped. The comment for kebab says "kebab-case" but uses the "_" delimiter:
> 
> https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/KebabCase.zep#L14
> 
> 
> https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/KebabCase.zep#L32
> 
> Similarly, the comment for snake says "snake_case" but uses the "-" delimiter:
> 
> https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/SnakeCase.zep#L14
> 
> 
> https://github.com/phalcon/cphalcon/blob/c25cb64d144c8ed79ace5be1e690982b9a82c63b/phalcon/Support/Helper/Str/SnakeCase.zep#L32
> 
> I believe those delimiters just need to be swapped (and the corresponding tests updated).

@lcdennison 

Thank you for the heads up. Resolved in https://github.com/phalcon/cphalcon/pull/15875
