### ISSUE TITLE
[BUG] File caching with lifetime not working on Windows

### ISSUE THREAD

**Issue by WooDzu** [phalcon/cphalcon#1585]
In version 1.3.0 CacheTest::testOutputFileCache() fails unit test on line 97

``` php
$content = $cache->start('testoutput');
$this->assertTrue($cache->isStarted());

if ($content !== null) {
    $this->assertTrue(false); // <-- HERE
}
```

The test is using Phalcon\Cache\Backend\File, which lead me to **ext/kernel/file.c**
and declaration of the function **phalcon_filemtime()**

ext/backend/file.c

``` c
PHALCON_INIT_VAR(modified_time);
phalcon_filemtime(modified_time, cache_file TSRMLS_CC);
if (unlikely(Z_TYPE_P(modified_time) != IS_LONG)) {
   convert_to_long(modified_time);
}

mtime   = Z_LVAL_P(modified_time);
diff    = now - ttl;
expired = diff > mtime;
```

ext/kernel/file.c

``` c
void phalcon_filemtime(zval *return_value, zval *path TSRMLS_DC)
{
    if (likely(Z_TYPE_P(path) == IS_STRING)) {
        php_stat(Z_STRVAL_P(path), (php_stat_len)(Z_STRLEN_P(path)), FS_MTIME, return_value TSRMLS_CC);
    }
    else {
        ZVAL_FALSE(return_value);
    }
}
```

**Result:**
Phalcon\Cache\Backend\File::get() receives invalid modified_time and thinks the file should not expiry.

Ubuntu 13.10 is passing this test correctly.

It fails on:
- Windows 7 Business Edition Service Pack 1 i586 
- PHP 5.5.3 - x86
- Phalcon 1.3.0 - x86 (current, compiled from ext)
##

**Comment by andresgutierrez** [comment]
Can you please try again using Phalcon 2 or close this issue?

**Comment by WooDzu** [comment]
Sorry but I can't test it easily. Was kind of lucky being able to leave Windows since.
