### ISSUE TITLE
[BUG]: Volt filter escape_attr - v5.0.0beta1

### ISSUE THREAD

**Issue by phptux** [phalcon/cphalcon#15853]
Hey Phalcon Team,

I am using the Volt filter `escape_attr`.

Simple example:
```twig
<meta charset="{{ charset | escape_attr }}"/>
```

I get the following error message:
```
Call to undefined method Phalcon\Html\Escaper::attr()
```
In the file [Mvc/View/Engine/Volt/Compiler.zep](https://github.com/phalcon/cphalcon/blob/v5.0.0beta1/phalcon/Mvc/View/Engine/Volt/Compiler.zep) on the line 2519 I find the following code:

```php
/**
 * "escape_attr" filter uses the escaper component to escape HTML
 * attributes
 */
if name == "escape_attr" {
    return "$this->escaper->attr(" . arguments . ")";
}
```

In the Phalcon version 4.2.x I find in the same file [Mvc/View/Engine/Volt/Compiler.zep](https://github.com/phalcon/cphalcon/blob/4.2.x/phalcon/Mvc/View/Engine/Volt/Compiler.zep) this code on line 2397:

```php
/**
 * "escape_attr" filter uses the escaper component to escape HTML
 * attributes
 */
if name == "escape_attr" {
    return "$this->escaper->escapeHtmlAttr(" . arguments . ")";
}
```

Please can you change this bug?

Thank you very much and please keep it up. You are a great team.

**Details**
 - Phalcon version: (`v5.0.0beta1`)
 - PHP Version: (`8.0.14`)
 - Operating System: Linux Mint
 - Installation type: Compiling from source
 - Zephir version: 0.15.2
 - Server: Apache

**Comment by niden** [comment]
@phptux Thank you for reporting this. There is a PR ready, once it gets merged it will be in Beta 2 (releasing probably tonight or tomorrow).

**Comment by niden** [comment]
This has been resolved in https://github.com/phalcon/cphalcon/pull/15854
