### ISSUE TITLE
Mustache.php v2.14.1 security release

### ISSUE THREAD

**Issue by bobthecow** [phalcon/cphalcon#15869]
Mustache.php v2.14.1 was released today. It contains a security improvement, and should be a straightforward update.

https://github.com/bobthecow/mustache.php/releases/tag/v2.14.1

(You're receiving this issue because Packagist says you depend on Mustache.php)

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15870

**Comment by niden** [comment]
Thank you @bobthecow
