### ISSUE TITLE
Route::getName() return type

### ISSUE THREAD

**Issue by jarnstedt** [phalcon/cphalcon#15880]
Hi!
The `\Phalcon\Mvc\Router\Route::getName()` return type `string` seems to be incorrect.

```php
$route = new \Phalcon\Mvc\Router\Route('example');
var_dump(\Phalcon\Version::get());
var_dump($route->getName());
```
outputs
```
string(5) "4.1.2"
NULL
```

https://github.com/phalcon/ide-stubs/blob/v4.1.0/src/Phalcon/Mvc/Router/Route.php#L202

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15881

Thank you @jarnstedt and @dcolt
