### ISSUE TITLE
[BUG]: Lib\\Models\\RobotError::findFirst(): Return value must be of type ?Phalcon\\Mvc\\ModelInterface, Phalcon\\Mvc\\Model\\Row returned

### ISSUE THREAD

**Issue by kvityasya** [phalcon/cphalcon#15883]
When overriding the `findFirst` method with `columns` I get an error:
`"Lib\\Models\\RobotError::findFirst(): Return value must be of type ?Phalcon\\Mvc\\ModelInterface, Phalcon\\Mvc\\Model\\Row returned"`

Model without redefining method findFirst
```php
<?php

namespace Lib\Models;

use Phalcon\Mvc\Model;

class RobotCorrect extends Model
{
    public $id;
    public $title;
    public $deleted;
}

RobotCorrect::findFirst(['columns' => 'title']); 

// Result: correct behavior 
```

Model with redefining method findFirst
```php
<?php

namespace Lib\Models;

use Phalcon\Mvc\Model;

class RobotError extends Model
{
    public $id;
    public $title;
    public $deleted;

    public static function findFirst($params = null): ?ModelInterface
    {
        return parent::findFirst($params);
    }
}

RobotError::findFirst(['columns' => 'title']);

// Result: error "Lib\\Models\\RobotError::findFirst(): Return value 
// must be of type ?Phalcon\\Mvc\\ModelInterface, Phalcon\\Mvc\\Model\\Row returned"
```

**Details**
 - Phalcon version: `5.0.0beta2`
 - PHP Version: `8.0.15`
 - Operating System: `Docker from php:8.0-fpm-alpine`
 - Installation type: `pecl package`
 - Server: `Nginx + fpm`
 - Database: `Mysql 8`

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15890

Thank you @kvityasya

**Comment by HL56** [comment]
I also get this error using phalcon 4, Can we merge #15890 together into 4? Thanks for any answers.

#### Details
- Phalcon version: 4.1.2
- PHP Version: 7.3.33

**Comment by HL56** [comment]
I also get this error using phalcon 4, Can we merge https://github.com/phalcon/cphalcon/pull/15890 together into 4? For some reason, I was unable to upgrade to 5. Thanks for any answers. @niden 

#### Details
Phalcon version: 4.1.2
PHP Version: 7.3.33
