### ISSUE TITLE
[NFR]: Get the internal translate array in Translate NativeArray

### ISSUE THREAD

**Issue by palcoder** [phalcon/cphalcon#15902]
Hello,

In Phalcon\Translate\Adapter\NativeArray we cannot access the whole internal translate array.

Sometimes it may help increase the performance when print the translation in view using the arrays instead of calling ( _ ) method on every word or sentence in the page especially in large pages.

For example: in beforeExecuteRoute event we can this

```
public function beforeExecuteRoute(Dispatcher $dispatcher)
{
        // Set translate data
        $this->view->setVar('_t', $this->translator->getAll());
}
```

and in the view we may use this:

`{{ _t['title'] }}`

instead of 

`this.translator._('title')`

Thanks

**Comment by niden** [comment]
@palcoder That would work for translations that do not have placeholders. So for instance if you have this:

```
"hi" : "Hello"
"bye" : "Goodbye"
```

then dumping that array out will work just fine, and you will be able to use those array elements wherever you need.

If you use placeholders though:

```
"hi" : "Hello :name:"
"bye" : "Goodbye :name:"
```

the placeholder will not be replaced by the data you pass or should pass. We don't know what the user will need to send as placeholders for any given translation string, (see above the `:name:` placeholder) so returning that will not help.

We can introduce the method of course but that should be only with the understanding that it will have to be just strings, not placeholders. I am thinking to check whether there are any placeholders and not return those results back.

Thoughts?

**Comment by someson** [comment]
almost the same problem i faced trying to extend the `NativeArray` in order to aggregate some data from `translate` class var:
https://github.com/phalcon/cphalcon/discussions/15958

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15968

Thank you @palcoder
