### ISSUE TITLE
[BUG]: Phalcon\Storage\Adapter\Redis.zep method getAdapter(), redis connect method use wrong params

### ISSUE THREAD

**Issue by ucando** [phalcon/cphalcon#15918]
phalcon version is 4.1.x
line 137
```php
if !persistent {
    let result = connection->connect(host, port, this->lifetime);
} else {
    let persistentid = "persistentid_" . index;
    let result = connection->pconnect(host, port, this->lifetime, persistentid);
}
```
the third param in connect and pconnect is connection timeout, not lifetime. use lifetime may cause bug sometimes

**Comment by niden** [comment]
@ucando Thanks for reporting this. We actually did find this and have corrected it in v5

https://github.com/phalcon/cphalcon/blob/5.0.x/phalcon/Storage/Adapter/Redis.zep#L272
