### ISSUE TITLE
[DOC]: Clarification of security document

### ISSUE THREAD

**Issue by BSarmady** [phalcon/cphalcon#15951]
in issue templates there is no tag for documentation, so please add if necessary.

documentation at https://docs.phalcon.io/4.0/en/security mentions 

_"Getter and setter for the default hash that the component will use. By default the hash is set to CRYPT_DEFAULT (0). The available options are:"_

I think it needs clarification that which one of these are used as default

- CRYPT_BLOWFISH_A
- CRYPT_BLOWFISH_X
- CRYPT_BLOWFISH_Y
- CRYPT_MD5
- CRYPT_SHA256
- CRYPT_SHA512
- CRYPT_DEFAULT

Also  mentioned

_"In the above example, the setWorkFactor() sets the password hashing factor to 12 rounds."_

What does it mean? Is it hashing the text 12 times?

**Comment by niden** [comment]
This has been resolved. Thank you @BSarmady for bringing this to our attention.

https://docs.phalcon.io/5.0/en/encryption-security#overview
https://docs.phalcon.io/5.0/en/encryption-security#work-factor


https://github.com/phalcon/docs/commit/a7bf8a20c30dd8a522afb4613cf65d1ad3b19b37
https://github.com/phalcon/docs/commit/ec37a63948faee6e9b8a12fa049c1d7b67d321e9
