### ISSUE TITLE
[NFR] Volt: allow to access object property using variable as the property name

### ISSUE THREAD

**Issue by Agent-J** [phalcon/cphalcon#1596]
``` php
$obj = new sdClass;
$obj->attr = 'some value';

$key = 'attr';

echo $obj->$key; // some value
```

Now it's impossible to access obj property like this

```
{{ obj[key] }}
{{ obj.key }}
```
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. If anyone wants to get started, I'd love that.
