### ISSUE TITLE
[NFR]: getBuilder() method for builder manager

### ISSUE THREAD

**Issue by TheAlg** [phalcon/cphalcon#15966]
I think it would be interesting to have more flexibility using builder, like adding new queries to the current builder instead of creating new one eache time. for example, I would like to add new queries after verifiying parameters passed to url, something like
if ($param !== null){
$this->model->manager->getBuilder()->join(...)
}

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16008
