### ISSUE TITLE
[BUG]: Filter::StringVal with <<>>

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#15978]
`FILTER_SANITIZE_STRING` is to be removed from PHP 8.1. The `StringVal` filter relies on `filter_var()` to sanitize strings. 

As per the documentation as well as the relevant RFC that removes the constant, `htmlspecialchars()` is a better alternative to the functionality.

The current implementation - which no longer uses `filter_var` is based on `preg_match` is:

```php
public function __invoke($input)
{
    $input = str_replace(chr(0), "", (string) $input);
    $input = preg_replace("/<[^>]*>?/", "", $input);

    return str_replace(["'", "\""], ["&#39;", "&#34;"], $input);
}
```

When using the following string:

```php
$input = '<< >> ' ' ' ' " " " " < >  - -  ... '
```

the expected result is:

```php
' &#39; &#39; &#39; &#39; &#34; &#34; &#34; &#34;   - -  ... '
```
but instead we get:

```php
'> &#39; &#39; &#39; &#39; &#34; &#34; &#34; &#34;   - -  ... '
```

Options: 
1. correct the `preg_match` to pick up the `>`
2. Change the `StringVal` filter to use `htmlspecialchars()` and also introduce `StringValLegacy` as a new filter which will only work for PHP 7.4 and 8.0 and will utilize `filter_var()`. This way we have something that people can use as they have been, and offer a path to upgrade the filter within the next major version.

**Comment by niden** [comment]
I am more inclined to go with no 2.

**Comment by Jeckerson** [comment]
@niden OK for option 2.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15983
