### ISSUE TITLE
[BUG]: Php8, Model bug

### ISSUE THREAD

**Issue by VladKuch** [phalcon/cphalcon#15971]
**Describe the bug**
Fatal error: Uncaught TypeError: Phalcon\Mvc\Model\Relation::__construct(): Argument #5 ($options) must be of type array, null given in /var/www/html/phalcon/app/Admin/models/Admin.php:22 Stack trace: #0 [internal function]: Phalcon\Mvc\Model\Relation->__construct(2, 'App\\Admin\\Model...', 'id', 'admin_id', NULL) #1 [internal function]: Phalcon\Mvc\Model\Manager->addHasMany(Object(App\Admin\Models\Admin), 'id', 'App\\Admin\\Model...', 'admin_id', NULL) #2 

With php7.4 works fine, but with php8.0 parameter `options` expected array, but null given
**To Reproduce**

$this->hasMany(
    'id',
    SomeModel::class,
   "ref_id'
);

**Screenshots**
![2022-05-24_17-49-27](https://user-images.githubusercontent.com/103261573/170065407-3f3c884c-c3a1-433e-a72b-e2749c6d2727.png)

**Details**
 - Phalcon version: v.5.0.3
 - PHP Version: 8.0.19
 - Operating System: Debian
 - Installation type: Compiling from source(Docker compose)
 - Server: Nginx

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15969

Thank you @VladKuch
