### ISSUE TITLE
[BUG]: Model afterDelete event, can't use delete, update method on result of relationship

### ISSUE THREAD

**Issue by phatnt93** [phalcon/cphalcon#15972]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
[Model]
When use delete, update method from result of relationship in afterDelete event. It's not working.
But check delete, update method still exists in object result

**To Reproduce**
![image](https://user-images.githubusercontent.com/26946722/170825202-d5f11de3-4668-4909-a06d-49955216de88.png)

1. Declare relationship in model class
2. In afterDelete event, use delete or update method from result of relationship
3. Error

**Expected behavior**
Use delete, update method.

**Screenshots**
Declare relationship for category childs, post-category map
![image](https://user-images.githubusercontent.com/26946722/170825029-7b73f1e7-e093-478a-affd-995eca85a0e9.png)

afterDelete event in model
![image](https://user-images.githubusercontent.com/26946722/170825010-f06f18ec-a234-4156-bd69-2b6437e47431.png)

Error when delete category then delete child categories
![image](https://user-images.githubusercontent.com/26946722/170825202-d5f11de3-4668-4909-a06d-49955216de88.png)

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: 7.4.27
 - Operating System: Docker linux
 - Installation type: Compiling from source || installing via package manager
 - Zephir version (if any): Version 0.12.21-8a412a1
 - Server: Apache
 - Database: mariadb 10.5.9

**Comment by borisdelev** [comment]
Hmm... i think is not related with models, because ::update() method is not on stdClass. However, if you want to delete child elements, you can use foreignKey in relation... or in DB - with index and foreign key.

**Comment by phatnt93** [comment]
Thanks.

It does not work with relation (index and index). But work with relation (index and foreign key).

parent[index]
code [index]
cate_code [index]
