### ISSUE TITLE
PHP 8.1 deprecation of null arguments

### ISSUE THREAD

**Issue by Deathamns** [phalcon/cphalcon#15984]
With the recent [v5.0.0RC1](https://github.com/phalcon/cphalcon/releases/tag/v5.0.0RC1) and PHP 8.1 I'm seeing entries in my log files about passing null parameters to built-in functions.

For example calling `Phalcon\Http\Request\getLanguages()` when the `HTTP_ACCEPT_LANGUAGE` header is not present, I get messages such as:
`preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated`

https://github.com/phalcon/cphalcon/blob/b6e86887708578ec853b6c08b9ba0825f9a43566/phalcon/Http/Request.zep#L1404

These deprecation messages might surface in other places as well, I've only noticed this specific case.

[Passing null to non-nullable parameters of built-in functions](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.null-not-nullable-internal)
[PHP 8.1 : Passing null to non-nullable arguments of internal functions is deprecated](https://phpbackend.com/blog/post/php-8-1-passing-null-to-non-nullable-arguments-of-internal-functions-is-deprecated)

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15985

Thank you @Deathamns

**Comment by Jeckerson** [comment]
Released in [v5.0.0RC2](https://github.com/phalcon/cphalcon/releases/tag/v5.0.0RC2)

**Comment by dz3n** [comment]
Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in

Same issue if you using StringLength validator with nullable column

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15995

@dz3n Thank you for reporting this!

**Comment by Deathamns** [comment]
https://github.com/phalcon/cphalcon/blob/b6e86887708578ec853b6c08b9ba0825f9a43566/phalcon/Mvc/View/Engine/Volt.zep#L191-L202

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16004
