### ISSUE TITLE
volt - text_area & htmlspecialchars

### ISSUE THREAD

**Issue by davidcorreia** [phalcon/cphalcon#15992]
### Discussed in https://github.com/phalcon/cphalcon/discussions/15991

<div type='discussions-op-text'>

<sup>Originally posted by **davidcorreia** June 11, 2022</sup>
I have been testing phalcon v5 (RC1 and just now RC2) with php8.1 and i keep getting warnings like

`PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/cache/_var_www_html_app_views_index.volt.php on line 453`

when i edit the "compiled" file what i see in line 453 is this:
` <?= \Phalcon\Tag::textArea(['suggest', 'class' => 'form-control', 'style' => 'height:100px']) ?>`
origin code is `{{ text_area("suggest", 'class':'form-control', 'style':'height:100px') }}`

after i replaced it to simple html the warnings disappeared.
Also if, `Tag::setDefault('suggest', '');` is set in the controller, the warning also disappeared.

its a simple workaround, but is it the expected behavior? 
</div>

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15993

Thank you @davidcorreia
