### ISSUE TITLE
[BUG]: Dispacher: Exception on nullable module value (PHP 8.1)

### ISSUE THREAD

**Issue by palcoder** [phalcon/cphalcon#15997]
Hello,

The dispatcher will throw the following exception when you pass a null value for the module parameter in route but when you pass an empty string it works fine.

`Phalcon\Dispatcher\AbstractDispatcher::setModuleName(): Passing null to parameter #1 ($moduleName) of type string is deprecated`

`$router->add(
    '/session',
    [
        'module'     => null,
        'controller' => 'session',
        'action'     => 'index'
    ]
);`

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16009
