### ISSUE TITLE
[BUG]:  Can not show HTML title in front.

### ISSUE THREAD

**Issue by zikezhang** [phalcon/cphalcon#16026]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
Can not show HTML title in front.

**To Reproduce**
>[ Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.](https://github.com/phalcon/cphalcon/blob/master/phalcon/Html/TagFactory.zep)

In Controller:
```php
$this->tag->setTitle(' - Welcome to Site');
```

> in the View of volt file:

```
{{ get_title() }}
```
it returns empty;

Neither:
```
{{ title() }}
```

But:
```
{{ title('My Title') }}
```
will show:
`My Title<title></title>`
(As you can see, "My Title" is out of the tag).

**Comment by Jeckerson** [comment]
What is the version of Phalcon?

**Comment by niden** [comment]
If you are talking about v5 then:

`get_title()` will use `Phalcon\Tag` internally so you need to set the title there for it to appear.

`title()` or `tag.title()` (both work) uses `Phalcon\Html\Helper\Title` through the `TagFactory`. The signature for that is:

```php
title(string $indent = '    ', string $delimiter = PHP_EOL): string
```
if you cast that to a string then it will print your title. Volt will do that automatically for you. In your last example you are passing `My Title` as the `$indent` parameter and this is why it shows up outside the `<title>` tags.

```php
echo $this->tag->title()->set('My Title');

$this
    ->tag
    ->title()
    ->setSeparator(' : ')
    ->set('APPLICATION')
;
// .....
$this->tag->title()->append("My ");
```
and in the view
```twig
{{ tag.title() }}
```

**Comment by zikezhang** [comment]
Thanks, @Jeckerson & @niden . it works well.
