### ISSUE TITLE
Compilation Installation Issue with Documentation

### ISSUE THREAD

**Issue by kgrammer** [phalcon/cphalcon#16020]
In the on-line documentation for Phalcon (3, 4 and 5), in the # Compilation sections, the instructions say:

"Download the latest zephir.phar from... "

And then... 

"Add it to a folder that can be accessed by your system."

You are then asked to clone the repository and after a few more steps, asked to enter the following two Zephir command:

zephir fullclean
zephir build

However, the download instructions for zephir.phar has you downloading zephir.phar to your local machine, which in many cases is a Windows dev PC/Laptop.  The instructions do nothing to help the user get zephir.phar uploaded to the proper folder (e.g., /bin) on the Linux server, or that in order to enter the commands as provided above that you need to rename "zephir.phar" to "zepher" and set the permissions to zephir ("chmod 775 zephir" or "chmod +x zephir).  

So the compilation documentation needs a few more steps.

And yes, I understand that devs compiling Phalcon should be able to figure these steps out, but if your goal is to help your users by providing on-line compilation steps, they need to be complete.  Adding a few additional comments to the doc pages could really save the day for devs who are not up to speed on zephir or don't realize you need to drop the ".phar" part of the name to match the compilation commands.

**Details**
 - Phalcon version: version 3.0, 4.0 and 5.0 documentation found at phalcon.io
 - PHP Version: n/a
 - Operating System: All Linix compilation installs
 - Installation type: Compiling from source
 - Zephir version (if any): All
 - Server: n/a
 - Other related info (Database, table schema): n/a

**Comment by kgrammer** [comment]
Here are the commands that added to the Phalcon installation notes that I use when setting up a new installation:

**_Download zephir.phar from https://github.com/zephir-lang/zephir/releases and copy it to the /bin folder on the server as /bin/zephir (omit the .phar extension).  Then set the permission to executable:

chmod +x /bin/zephir

Install Zephir Parser:

pecl install zephir_parser_**

I forgot to mention that zephir_parser also seems to be required but it's not mentioned in the docs.

**Comment by niden** [comment]
This has been addressed in the v5 docs.

Thank you @kgrammer
