### ISSUE TITLE
[BUG]: RawValue no longer supports mysql functions

### ISSUE THREAD

**Issue by LlamaDuckGoose** [phalcon/cphalcon#16037]
**Describe the bug**
It looks like the change in this PR https://github.com/phalcon/cphalcon/issues/15413 has broken how it handles MySQL functions

**To Reproduce**
This is taken from the function example Docblock.
`
 $subscriber->createdAt = new \Phalcon\Db\RawValue("now()");
`
Or something like:
`
 $subscriber->expiry = new \Phalcon\Db\RawValue("now()  + INTERVAL 30 DAY");
`
```
PDOException #22007
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'now()' for column `database`.`table`.`created_at` at row 1
PDOException #22007
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'now() + INTERVAL 30 DAY' for column `database`.`table`.`expiry` at row 1
```

**Details**
 - Phalcon version: 5.0.0RC3
 - PHP Version: 7.4.30
 - Operating System: Ubuntu 20.04.4
 - Installation type: Any
 - Zephir version (if any): NA
 - Server: Apache

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16038
