### ISSUE TITLE
[BUG]: Paginator Model Adapter Incorrect total items when grouped

### ISSUE THREAD

**Issue by LlamaDuckGoose** [phalcon/cphalcon#16042]
**Describe the bug**
This is currently always returning 1 for total items when grouped which also breaks the last page/total page count as well.

**To Reproduce**
Create a model paginator without passing a group in the parameters and then one with group.

```php
    $paginator = new \Phalcon\Paginator\Adapter\Model([
        'model' => Model::class,
        'parameters' => [
            'type IN ({type:array})',
            'bind' => [
                'type' => [
                    Model::TYPE_1,
                    Model::TYPE_2,
                ],
            ],
            'group' => 'type'
        ]
    ]);
```

Since this is grouped by type and 2 types are provided, you'd expect it to return total items as 2 but this will return 1

**Details**
 - Phalcon version: 5.0.0RC3
 - PHP Version: 7.4.30
 - Operating System: Ubuntu 20.04.4
 - Installation type: Any
 - Zephir version (if any): NA
 - Server: Apache

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16043/
