### ISSUE TITLE
[BUG]: PHP Deprecated - setcookie() when using cookies->delete

### ISSUE THREAD

**Issue by sinbadxiii** [phalcon/cphalcon#16053]
Hi

When using the `$this->cookies->get("name")->delete();`, a deprecation warning is issued:
`PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in`

**Details**
 - Phalcon version: Phalcon v5 RC4
 - PHP Version: PHP 8.1
 - Operating System:Linux Mint 20
 - Installation type: Compiling from source
 - Zephir version (if any): 0.16.0
 - Server: Nginx

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16054
