### ISSUE TITLE
[BUG]: Documentation site search doesn't work

### ISSUE THREAD

**Issue by dknight10** [phalcon/cphalcon#16050]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
When performing a search on the documentation site (https://docs.phalcon.io/4.0/en/introduction), nothing happens. After typing a search term and hitting enter, the page seems to stutter and return to initial state. 

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.

1. Visit the documentation site https://docs.phalcon.io/4.0/en/introduction
2. Enter any search term
3. Press return to execute search 

**Expected behavior**

Search is executed and shown a page of results. 

**Screenshots**

https://user-images.githubusercontent.com/10201947/183659135-60bc853d-3098-4987-8ca3-a6ffb20f63e6.mov

**Comment by niden** [comment]
This has been fixed today and it takes into account version and language so that the results come clean!

Thank you @dknight10 for reporting this.

(_now all we need is some CSS gurus to make the search box nicer_)
