### ISSUE TITLE
The collection does not exist in the manager

### ISSUE THREAD

**Issue by jesselpereira** [phalcon/cphalcon#16060]
Hello, I use the framework and just out of nowhere I started getting build errors, can anyone help me to solve it?

I use docker to run Phalcon and other images.

![image](https://user-images.githubusercontent.com/77973110/184627685-4b7e968c-5eda-4993-9330-43de198a04d5.png)

**Comment by niden** [comment]
Do you happen to have a `default` collection in the Assets manager? Can you post your setup code?

**Comment by niden** [comment]
Closing this - if the problem persists please open a new issue with relevant information
