### ISSUE TITLE
[BUG]: Validator\Numericality If not continuous, many letters and symbols will slip through

### ISSUE THREAD

**Issue by s-ohnishi** [phalcon/cphalcon#16070]
Validator\Numericality::validate() uses this regular expression according to [.zep.](https://github.com/phalcon/cphalcon/blob/5.0.x/phalcon/Filter/Validation/Validator/Numericality.zep)
```pattern = "/((^[-]?[0-9,]+(.[0-9]+)?$)|(^[-]?[0-9.]+(,[0-9]+)?$))/";```

But isn't `(.[0-9]+)?` a mistake for `(\.[0-9]+)?`?

**Details**
 - Phalcon version: 5.0.0 RC4
 - PHP Version: 8.1.9
 - Operating System: Debian on Docker (WSL2)
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Nginx/1.22.0

**Comment by niden** [comment]
Can you give an example of a string that would fail this?

**Comment by s-ohnishi** [comment]
define form
```
class SampleForm extends \Phalcon\Forms\Form
    public function initialize($entity = null, $options = [])
    {
        $elm = new Element\Text('foo');
        $elm->addValidator(
            new Validator\Numericality([
                'message'=>'enter numeric value, please',
                'allowEmpty'=>true
            ]),
        );
        $this->add($elm);
    }
}
```
in the controller
```
        $SampleForm = new \App\Forms\SampleForm();
        $ret = $SampleForm ->isValid($_POST);
```
results
```
$_POST['foo']   $res
'-12,000'       true
'-12,0@0'       true
'-12,0@@0'      false
```

Would you like a sample like this?

**Comment by niden** [comment]
Yes. Thank you. I will fix this shortly

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16071

Thank you @s-ohnishi
