### ISSUE TITLE
misleading comment line

### ISSUE THREAD

**Issue by someson** [phalcon/cphalcon#16076]
https://github.com/phalcon/cphalcon/blob/98cd09047faf3299ee8f8bfbeeb8db7e53f90d91/ext/phalcon/di/injectable.zep.c#L51

should be `Phalcon\Html\TagFactory` instead of given `Phalcon\Tag`.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16077

Thank you @someson
