### ISSUE TITLE
[BUG]: PHPUnit Mock / Mockery Mock : SIGSEGV

### ISSUE THREAD

**Issue by kevcomparadise** [phalcon/cphalcon#16080]
**Describe the bug**
PHPUnit throw sigfault error when we try mock Model 

Error
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

We tried with `Mockery` & `PHPUnit` 

**To Reproduce**

Create Empty model like
```php
use Phalcon\Mvc\Model;

class TestModel extends Model
{

}
```
Create unit test and try to create mock of this model
```php 
class AffiliateCampaignForbiddenMiddlewareTest extends TestCase 
{
        public function testA() 
        {
              $mockBuilder = $this->getMockBuilder(TestModel::class);
              $mockBuilder->getMock();
        }
}

```

**Expected behavior**
In Phalcon 3.4 its work

**Details**
 - Phalcon version: 5.0.0RC4
 - PHP Version: 8.1.6
 - Operating System: Debian
 - Installation type: PECL
 - Server: Apache
- Xdebug : v3.1.2

Thanks

**Comment by Jeckerson** [comment]
Tried with PHP7.4 got this error:

> Fatal error: Cannot use 'null' as class name as it is reserved in /srv/vendor/phpunit/phpunit/src/Framework/MockObject/MockClass.php(51) : eval()'d code on line 9

**Comment by kevcomparadise** [comment]
> Tried with PHP7.4 got this error:
> 
> > Fatal error: Cannot use 'null' as class name as it is reserved in /srv/vendor/phpunit/phpunit/src/Framework/MockObject/MockClass.php(51) : eval()'d code on line 9
> 
> Investigating with `8.1`...

We have never tried in 7.3 because Phalcon 3.4 is only available 7.3

**Comment by Jeckerson** [comment]
Property getter was generating wrong `ARG_INFO` of method, which were causing segmentation fault.

Wrong:
```c
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_mvc_model_gettransaction, 0, 0, IS_NULL, 1)
ZEND_END_ARG_INFO()
```

Correct:
```c
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_mvc_model_gettransaction, 0, 0, Phalcon\\Mvc\\Model\\TransactionInterface, 1)
ZEND_END_ARG_INFO()
```

**Comment by Jeckerson** [comment]
Related: https://github.com/zephir-lang/zephir/issues/2386

**Comment by niden** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/16085
