### ISSUE TITLE
[BUG]: PHP crashes without any message when trying mocking classes, inherited from Phalcon\Mvc\Model

### ISSUE THREAD

**Issue by ktsv** [phalcon/cphalcon#16096]
[BUG]: PHP crashes without any message when trying mocking classes, inherited from Phalcon\Mvc\Model

Create test, mock any class, inherited from Phalcon\Mvc\Model.

```php
        $this->entity = $this->createMock(Entity::class);
```

I expect mock to be returned
Actually system fails without any message

 - Phalcon version:  5.0.0RC4
 - PHPunit version 9.5.24
 - Codeception version: 4.2.2
 - PHP Version: 8.0.23
 - Operating System: Debian linux
 - Installation type: Compiling from source
 - Server: Nginx

**Comment by ktsv** [comment]
this probably happens because some methodh in Phalcon (I was able to find few besides this one) have `null` as return type

**Comment by Jeckerson** [comment]
Related https://github.com/phalcon/cphalcon/issues/16080

**Comment by Jeckerson** [comment]
Already fixed in https://github.com/phalcon/cphalcon/issues/16080

**Comment by Jeckerson** [comment]
This issue will be used to fix another similar bugs.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16100

Thank you @ktsv
