### ISSUE TITLE
[BUG]: Database manager throws 'Invalid parameter number' when bind parameter used in query more than once

### ISSUE THREAD

**Issue by ktsv** [phalcon/cphalcon#16091]
when performing queries to database with bind parameters, and query contains same parameter more than once - 'Invalid parameter number' is thrown by DB manager (or medel)

Current behaviour:
$this->db->query('select * from test where id=:id or id=:id',
        ['id' => 1]);
throws PDOException: SQLSTATE[HY093]: Invalid parameter number

Expected behaviour:
Query runs without exception

 - Phalcon version: 5.0.0RC4
 - PHP Version: 7.4, 8.0, 8.1
 - Operating System: Debian Linux (in Docker)
 - Installation type: Compiling from source
 - Zephir version (if any):
 - Server: Nginx
 - Other related info (Database, table schema): MariaDB, MySQL

**Comment by linyuanchang** [comment]
Maybe you can try the query like
```
$this->db->query('select * from test where id=:id: or id=:id:',
['id' => 1]);
```

In the condition, it is ```id=:id:``` but not ```id=:id```.

**Comment by niden** [comment]
I believe this is a PDO related issue - having the same name for two or more variables. Honestly your query does not make sense (unless it is just an example).

If you really need to use the same parameter you have to name them differently `id1`, `id2` etc.

https://stackoverflow.com/questions/18028706/php-pdoexception-sqlstatehy093-invalid-parameter-number

**Comment by ktsv** [comment]
> 

It user to work in our system for years before we try to update from phalcon 4.0.6 to phalcon 5.0.0RC4. This is one most annoying bug we've got.

**Comment by sinbadxiii** [comment]
there the default pdo attribute has changed to `false`
https://github.com/phalcon/cphalcon/issues/15810

**Comment by niden** [comment]
> there the default pdo attribute has changed to `false` #15810
> 
> need to edit db config
> 
> ```
> 'database' => [
>       'adapter'     => $_ENV['DB_CONNECTION'],
>       'host'        => $_ENV['DB_HOST'],
>       'username'    => $_ENV['DB_USERNAME'],
>       'password'    => $_ENV['DB_PASSWORD'],
>       'dbname'      => $_ENV['DB_DATABASE'],
>       'charset'     => $_ENV['DB_CHARSET'],
>       'options' => [
>           \PDO::ATTR_EMULATE_PREPARES => true
>       ]
> ],
> ```

Ack. Thank you @sinbadxiii. 

I need to add a warning to the docs about this - I thought I did but just in case.

**Comment by niden** [comment]
Addressed in: https://github.com/phalcon/docs/commit/efaa70c41e0f3052949f91db0f6aed2447bd1857

Thank you all for bringing this to our attention!
