### ISSUE TITLE
[BUG]: Volt Render Notice : Undefined index: name

### ISSUE THREAD

**Issue by kevcomparadise** [phalcon/cphalcon#16097]
**Describe the bug**
When we try to access a public method of a sub class contained in a public property of a root class, Volt generates a Notice.
PS : Return value OK

**To Reproduce** 

* 1 : Create Controller and pass to volt an object contain an sub-object 

```php
class TestController extend Controller {

   public function indexAction()
   {

       $subObject = new class {

            public function getValue() {
                return 'Value';
            }

        };

        $rootObject = new class ($subObject) {

            public $sub_object = null;

            public function __construct($subObject)
              {
                  $this->sub_object =  $subObject;
              }
        };

        $this->view->testObject = $rootObject
  }
}

```
* 2 : Create related view (/test/index.volt)
```twig
{{ testObject.sub_object.getValue() }}
```

**Note : If we use a getter for sub_object (like : getsubObject()) it work** 

**Expected behavior**
Render without notice 

**Details**
 - Phalcon version: 5.0RC4
 - PHP Version: 8.1.6
 - Operating System: Debian 
 - Installation type:  installing via package manager (PECL)
 - Server: Apache

**Comment by niden** [comment]
Does it work if you use different files for classes vs the `new class` syntax?

I have not tested this but I am not sure Volt works with that (yet).

**Comment by kevcomparadise** [comment]
> Does it work if you use different files for classes vs the `new class` syntax?
> 
> I have not tested this but I am not sure Volt works with that (yet).

Nop same result
This work with Phalcon 3.4

**Comment by colinpieper** [comment]
I'm also experiencing this issue (in v5.0.2). A workaround that seems to work for my situation is to first set a variable, and then display that variable. Using your example:

Change:
```
{{ testObject.sub_object.getValue() }}
```

To:
```
{% set foo = testObject.sub_object.getValue() %}
{{ foo }}
```

**Comment by rtiagom** [comment]
same problem here

**Comment by palcoder** [comment]
I have the same issue and the releases from v5.0.0RC4 to v5.0.4 have the issue but the release v5.0.0RC3 works fine

**Comment by ccc-nghia-le** [comment]
Any update on when this will be fixed please?

**Comment by niden** [comment]
We are working on this one guys. Hopefully we can figure out where it comes from. 

I checked a bit the code and it seems to fail in the code to `ob_start()` so that might be happening in Zephir.

**Comment by niden** [comment]
This has been resolved in https://github.com/phalcon/cphalcon/pull/16187.

Thank you @kevcomparadise @colinpieper
