### ISSUE TITLE
[BUG] Error performing MySQL fulltext query

### ISSUE THREAD

**Issue by hugoduraes** [phalcon/cphalcon#1609]
I'm getting the following error:

```
Syntax error, unexpected token IDENTIFIER(BOOLEAN), near to ' MODE)'
```

while executing this query:

```php
$result = Model::find(array(
    'conditions' => "MATCH (column) AGAINST ('string' IN BOOLEAN MODE)"
));
```

Executing the same query without the **IN BOOLEAN MODE** switch works fine.

Is there a way to workaround this issue? Can it be fixed?

**Comment by andresgutierrez** [comment]
You can use custom dialect functions since Phalcon 2.0.3 to support any SQL extension: https://blog.phalconphp.com/post/phalcon-2-0-3-released
