### ISSUE TITLE
[BUG] Phalcon\Mvc\Model::afterSave() is called before related Models are saved

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#1615]
The `Phalcon\Mvc\Model::afterSave` is called before related Models are saved. To me it looks like an incorrect behaviour, as I might want to perform additional actions depending on the outcome of saving of related objects.

Thanks!

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
