### ISSUE TITLE
[BUG]: Mvc\Model::fireEvent(): Return value must be of type bool, null returned

### ISSUE THREAD

**Issue by hellobbq** [phalcon/cphalcon#16161]
https://github.com/phalcon/cphalcon/blob/caedb80703b5da4dcf7058755d49f99a389d4a38/phalcon/Mvc/Model.zep#L1760

https://github.com/phalcon/cphalcon/blob/caedb80703b5da4dcf7058755d49f99a389d4a38/phalcon/Mvc/Model/Manager.zep#L1969-L1974

also found:
https://github.com/phalcon/cphalcon/blob/caedb80703b5da4dcf7058755d49f99a389d4a38/phalcon/Mvc/Model.zep#L1783

**Details**
 - Phalcon version: 5.0.3
 - PHP Version: 8.1.11
 - Operating System: centos
 - Installation type: Compiling from source
 - Zephir version (if any): 0.16.3
 - Server: Nginx

**Comment by niden** [comment]
Do you have an example model where this message appears? It seems that the `notifyEvent` _could_ return `null` but the return type of that method is not set to return only boolean.

**Comment by niden** [comment]
@hellobbq never mind. I found the issue :)

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16162
