### ISSUE TITLE
[BUG]: PdoResult::fetchAll() does not accept string for class name in FETCH_CLASS mode

### ISSUE THREAD

**Issue by ccc-emile-antognetti** [phalcon/cphalcon#16177]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
When calling `fetchAll` on a Result\PdoResult object using the \PDO::FETCH_CLASS mode, the following error is returned :
```
Argument 2 passed to Phalcon\Db\Result\PdoResult::fetchAll() must be of the type int, string given
```

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.
```
#0 /var/www/html/phalcon5.[REDACTED].com/app/Model/Repository/CompanyRepo.php(29): Phalcon\Db\Result\PdoResult->fetchAll()

#1 /var/www/html/phalcon5.[REDACTED].com/app/Model/WebUser.php(368): [REDACTED]\Model\Repository\CompanyRepo::[REDACTED]()

#2 /var/www/html/phalcon5.[REDACTED].com/app/Auth/LoginTrait.php(21): [REDACTED]\Model\WebUser->shouldSeePasswordUpdateNotice()

#3 /var/www/html/phalcon5.[REDACTED].com/app/Controller/DefaultController.php(330): CareerCross\Controller\DefaultController->buildLoginRedirectUsingString()

#4 [internal function]: [REDACTED]\Controller\DefaultController->loginAction()

#5 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod()

#6 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()

#7 /var/www/html/phalcon5.[REDACTED].com/public/index.php(15): Phalcon\Mvc\Application->handle()


#8 {main}
```

Call `fetchAll` on a Result\PdoResult object using FETCH_CLASS mode 

> Provide minimal script to reproduce the issue

```php
use Phalcon\Db\Adapter\Pdo\Mysql as Connection;

$connection = new Connection(
                [
                    'host' => foo,
                    'username' => bar,
                    'password' => foo,
                    'dbname' => bar,
                    'port' => foo,
                    'charset' => 'utf8',
                    'dialectClass' => new \Phalcon\Db\Dialect\MySQL();
                    'persistent' => false,
                ]
            );

$sql = "SELECT * FROM automobiles WHERE date_manufactured = :date";

$result = $connection->query($sql, ['date' => '1998'])->fetchAll(\PDO::FETCH_CLASS, Model\Automobiles::class, null);
var_dump($result);
```

```php
// paste output here
Argument 2 passed to Phalcon\Db\Result\PdoResult::fetchAll() must be of the type int, string given
```

**Expected behavior**
`fetchAll` should return instances of the specified class, mapping the columns of each row to named properties in the class.
https://www.php.net/manual/en/pdostatement.fetchall.php 

```php
// paste code
[
   0 => 'Model\Automobiles' {
               [...]
              "date_manufactured" : "1998"
              }
    1 => (so forth so on)
]
```

**Screenshots**

**Details**
 - Phalcon version: 5.0.4
 - PHP Version: PHP 7.4.32
 - Operating System: Linux  5.15.0-50-generic #56~20.04.1-Ubuntu
 - Installation type: Compiling from source 
 - Zephir version (if any): Version 0.16.3-$Id$
 - Server: Apache 
 - Other related info (Database, table schema): N/A

**Additional context**
The error seems to be thrown because in Phalcon 5, the second argument of the fetchAll function is specified as an `int`
https://github.com/phalcon/cphalcon/blob/cfe0df1e477ab4f7f352ba14a485c8a9152bb9d2/phalcon/Db/Result/PdoResult.zep#L214
Previously in Phalcon 4, no type was set for this argument. 
https://github.com/phalcon/cphalcon/blob/ca304adbf66f1d447e89311f47f190d24a034339/phalcon/Db/Result/Pdo.zep#L180-L181
Restricting this argument to an int is problematic because in the FETCH_CLASS mode, the second argument should be a string used to specify the Class that the results should be mapped to
```
public PDOStatement::fetchAll(int $mode = PDO::FETCH_CLASS, string $class, ?array $constructorArgs): array
```
https://www.php.net/manual/en/pdostatement.fetchall.php

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16178

Thank you @ccc-emile-antognetti

**Comment by ccc-emile-antognetti** [comment]
Thanks so much for the speedy turnaround!
