### ISSUE TITLE
[BUG]: Phalcon\Config created by Phalcon\Config should keep insensitive choice

### ISSUE THREAD

**Issue by dugwood** [phalcon/cphalcon#16171]
**Describe the bug**
Phalcon\Config creates instances of Phalcon\Config for all arrays and sub-arrays. These Phalcon\Config should keep the `insensitive` value as the one of their parent.

**To Reproduce**

```php
$c = ['key' => 'value', 'key_for_array' => ['key' => 'value']];
$config = new Phalcon\Config($c, false);
```

**Expected behavior**
$config->key_for_array should have the property `insensitive` set to `false` as its parent $config.

**Line to change**
https://github.com/phalcon/cphalcon/blob/master/phalcon/Config/Config.zep#L253
change for `new Config(value, this->insensitive)`

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: 7.4
 - Operating System: Debian
 - Installation type: compiled from source
 - Zephir version (if any): irrelevant
 - Server: irrelevant

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16172

Thank you @dugwood

**Comment by dugwood** [comment]
Wow, that was fast :-) Thanks @niden!
