### ISSUE TITLE
[BUG]: Cannot fetch a `PATCH` request payload

### ISSUE THREAD

**Issue by danielcosta-94** [phalcon/cphalcon#16188]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
Cannot fetch a `PATCH` request payload (sanitized or not), because we don't have equivalent like a `POST` request `getPost` or `getFilteredPost`

**To Reproduce**
Check available methods in class `Request.php` in namespace `Phalcon\Http`

**Expected behavior**
To have the equivalent methods `getPatch` and `getFilteredPatch`

**Details**
 - Phalcon version: (`5.0.4`)
 - PHP Version: (`8.1.11`)
 - Operating System: Linux Ubuntu 20.04.5 LTS
 - Installation type: installing via package manager
 - Zephir version (if any): (`0.16.3`)
 - Server: Nginx

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16190

Thank you @danielcosta-94
