### ISSUE TITLE
[BUG]: Escaper fails to escape string "0"

### ISSUE THREAD

**Issue by zacek** [phalcon/cphalcon#16202]
In `Phalcon\Html\Escaper::html(string input = null)` the validation of the input string is not correct:

```
if !input {
    return "";
}
```
In PHP, the implicit conversion of string `"0"` to `bool` results to `false`. Therefore, string `"0"` is escaped to an empty string.
The correct validation should read

```
if input === null {
    return "";
}
```

**How to reproduce:**
```
php -r "var_export((new \Phalcon\Html\Escaper())->html('0'));"
```
Expected result is `"0"` and not an empty string.

**Details**
 - Phalcon version: 5.0.2 (Build Date Sep 28 2022 09:09:44)
 - PHP Version: 8.1.11
 - Operating System: CentOS Stream release 8
 - Installation type: via package manager
 - Zephir version (if any): Version 0.16.3

**Comment by Jeckerson** [comment]
Fixed in https://github.com/phalcon/cphalcon/pull/16204

**Comment by niden** [comment]
Thank you @zacek
