### ISSUE TITLE
[NFR]: Return getInternalImInstance to Imagick Adapter

### ISSUE THREAD

**Issue by stdnk** [phalcon/cphalcon#16224]
**Is your feature request related to a problem? Please describe.**
In previous versions of the framework, it was possible to access the image driver using `getInternalImInstance `. In version 5 this method was removed from the adapter.

**Describe the solution you'd like**
I'd like method to be returned to the adapter.

Thank you!

**Comment by niden** [comment]
You can use the `getImage()` method that comes from the `AbstractAdapter`. That was the reason that the `getInternalImInstance()` was removed.

Granted, not the best name for a method but we did not want to break compatibility.

On `__construct` the `this->image` contains the `Imagick()` instance.

**Comment by stdnk** [comment]
Thanks @niden!
