### ISSUE TITLE
Phalcon\Acl\Adapter\Memory::allow, wrong parameter type check in callback function (4th params)

### ISSUE THREAD

**Issue by joepsyko** [phalcon/cphalcon#16264]
**Describe the bug**
It looks like the parameters type check is wrong for function passed as argument in `Phalcon\Acl\Adapter\Memory::allow`, as it tries to always check if the given type exists as a class.

**To Reproduce**
```
$this->getAcl()->allow(Role::USER, EventController::class, ['getOpenEvents'],
            function (string $userId, \stdClass $payload, string $workspaceId) {
                return (new GetListAssertion())->assert($userId, $workspaceId);
            });
```

This code yields this error:

```
[2023-01-16T17:49:31.137964+00:00] application.ERROR: Class "string" does not exist [] []
[2023-01-16T17:49:31.143865+00:00] application.ERROR: Class "string" does not exist [] []
[2023-01-16T17:49:31.144455+00:00] application.ERROR: Uncaught Exception Phalcon\Http\Response\Exception: "Response was already sent" at phalcon/Http/Response.zep line 337 {"exception":"[object] (Phalcon\\Http\\Response\\Exception(code: 0): Response was already sent at phalcon/Http/Response.zep:337)"} []
```

If I remove the two `string` types:
```
$this->getAcl()->allow(Role::USER, EventController::class, ['getOpenEvents'],
            function ($userId, \stdClass $payload, $workspaceId) {
                return (new GetListAssertion())->assert($userId, $workspaceId);
            });
```

then the code is executed without errors.

**Details**
 - Phalcon version: (5.1.4)
 - PHP Version: (8.1.14)
 - Operating System: docker container
 - Installation type: Compiling from source 
 - Server: Apache

**Comment by niden** [comment]
@joepsyko Apologies for the late reply.

At the moment Phalcon does not support such syntax for the callables.

Out of curiosity is this syntax allowed? I have not seen this in the release notes for 8.1

**Comment by joepsyko** [comment]
Do you mean that I cannot add the param type in the callback?

**Comment by joepsyko** [comment]
Do you mean that PHP doesn't support this?

**Comment by niden** [comment]
I was asking because I don't know if PHP supports this. I have not seen this in any notes of new features etc.

The issue comes when we check for the type of each parameter. When the type is a class or an object we check if this is a RoleAware or ComponentAware object. In your example, the type comes back as `string` when using Reflection. Since `string` is not a class, that is why we see the issue here

**Comment by joepsyko** [comment]
Got it, I believe I can close this then

**Comment by niden** [comment]
Thank you.
