### ISSUE TITLE
[BUG]: Model::findFirst - Invalid parameter number when using single bind parameter for two conditions (5.1.4)

### ISSUE THREAD

**Issue by aircodepl** [phalcon/cphalcon#16275]
**Describe the bug**
For some reason, we cannot to use the same parameter for two conditions.

Example usages:
- Find firm by search phrase (search for phrase in firm name, firm nip, firm address etc.)

**To Reproduce**
> PDOException
> SQLSTATE[HY093]: Invalid parameter number

1. Try to find a row by using the same parameter for multiple conditions

> Provide minimal script to reproduce the issue

```php
/** @var Category $category */
$category = Category::findFirst([
    'conditions' => 'slugPL = :slug: OR slugEN = :slug:',
    'bind' => [
        'slug' => $slug
    ]
]);
```

```php
/** @var Category $category */
$category = Category::findFirst([
    'conditions' => 'slugPL = :slug1: OR slugEN = :slug2: OR slugEN = :slug1:',
    'bind' => [
        'slug1' => $slug,
        'slug2' => $slug
    ]
]);
```

**Expected behavior**
Phalcon should use the 'slug' parameter value for both conditions.

If we have a search box in the app and want to search in multiple columns with one phrase, it would be stupid to write multiple (but the same) bind params...

**What is working?**

```php
/** @var Category $category */
$category = Category::findFirst([
    'conditions' => 'slugPL = :slug1: OR slugEN = :slug2:',
    'bind' => [
        'slug1' => $slug,
        'slug2' => $slug
    ]
]);
```

**Details**
 - Phalcon version: 5.1.4
 - PHP Version: 8.1-apache
 - Operating System: Ubuntu
 - Installation type: Docker + Pecl
 - Server: Apache

**Comment by sinbadxiii** [comment]
> **Describe the bug**
> For some reason, we cannot to use the same parameter for two conditions.
> 
> Example usages:
> - Find firm by search phrase (search for phrase in firm name, firm nip, firm address etc.)
> 
> **To Reproduce**
> > PDOException
> > SQLSTATE[HY093]: Invalid parameter number
> 
> Steps to reproduce the behavior:
> 
> 1. Try to find a row by using the same parameter for multiple conditions
> 
> > Provide minimal script to reproduce the issue
> 
> ```php
> /** @var Category $category */
> $category = Category::findFirst([
>     'conditions' => 'slugPL = :slug: OR slugEN = :slug:',
>     'bind' => [
>         'slug' => $slug
>     ]
> ]);
> ```
> 
> ```php
> /** @var Category $category */
> $category = Category::findFirst([
>     'conditions' => 'slugPL = :slug1: OR slugEN = :slug2: OR slugEN = :slug1:',
>     'bind' => [
>         'slug1' => $slug,
>         'slug2' => $slug
>     ]
> ]);
> ```
> 
> **Expected behavior**
> Phalcon should use the 'slug' parameter value for both conditions.
> 
> If we have a search box in the app and want to search in multiple columns with one phrase, it would be stupid to write multiple (but the same) bind params...
> 
> 
> **What is working?**
> 
> 
> ```php
> /** @var Category $category */
> $category = Category::findFirst([
>     'conditions' => 'slugPL = :slug1: OR slugEN = :slug2:',
>     'bind' => [
>         'slug1' => $slug,
>         'slug2' => $slug
>     ]
> ]);
> ```
> 
> **Details**
>  - Phalcon version: 5.1.4
>  - PHP Version: 8.1-apache
>  - Operating System: Ubuntu
>  - Installation type: Docker + Pecl
>  - Server: Apache
> 
> 

@aircodepl duplicate https://github.com/phalcon/cphalcon/issues/16091

**Comment by aircodepl** [comment]
@sinbadxiii I'm sorry, I didn't find it when looking for. I should Google it first, would find it. Thanks for the review.
