### ISSUE TITLE
[BUG]: return value of view::getVar() is not specified

### ISSUE THREAD

**Issue by s-ohnishi** [phalcon/cphalcon#16276]
**Describe the bug**
Since the return value of View::getVar() is not specified, it is not reflected in ide-stubs and an error is displayed in the IDE.
[View::getVar()](https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/View.zep#L540)

**Screenshots**
![getVar](https://user-images.githubusercontent.com/6782530/215773882-888e3fc0-80f4-4498-afb2-81665a7726bf.png)

**Details**
 - Phalcon version: 5.1.3
 - PHP Version: 8.1.14
 - Operating System: Debian 10.13
 - Installation type: PECL, composer(for phalcon/ide-stubs)
 - Zephir version (if any):
 - Server: Nginx 1.22.1

**Comment by sinbadxiii** [comment]
@s-ohnishi Can you show function `getVar()` from `vendor/phalcon/ide-staubs/src/Mvc/View.php`?

**Comment by s-ohnishi** [comment]
of course.
This is how it looks in my current environment (phalcon/ide-stubs 5.1.0).
```PHP
    /**
     * Returns a parameter previously set in the view
     *
     * @param string $key
     */
    public function getVar(string $key)
    {
    }
```
The latest on git is the same
https://github.com/phalcon/ide-stubs/blob/master/src/Mvc/View.php#L486

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16379

Thank you @s-ohnishi
