### ISSUE TITLE
[BUG]: Issue using model columns starting with not*

### ISSUE THREAD

**Issue by wurst-hans** [phalcon/cphalcon#16277]
Currently using v4.1.0, so I don't know, if this issue persists in newer versions.

I have some database models using a colum, for example `notification_date`. When querying database using

```
$result = Orders::find([
    'conditions' => 'notification_date IS NULL',
]);
```

I get an error from Phalcon, saying (you can see, that Phalcon cuts off `not`):

```
"Column 'ification_date' doesn't belong to any of the selected models (1), when preparing: SELECT [App\\Models\\Orders].* FROM [App\\Models\\Orders] WHERE notification_date IS NULL"
```

Even when using backticks in conditions ``` `notification_date` ``` I'm getting another error:

```
"Scanning error before 'notification_date...' when parsing: SELECT [App\\Models\\Orders].* FROM [App\\Models\\Orders] WHERE `notification_date` IS NULL"
```

The only solution is to rename column to anything **not** starting with `not`.

**Comment by dcolt** [comment]
You can fix it by doing the PHQL "escaping" in your queries
```
$result = Orders::find([
    'conditions' => '[notification_date] IS NULL',
]);
```

**Comment by LlamaDuckGoose** [comment]
reported in https://github.com/phalcon/cphalcon/issues/14641

**Comment by niden** [comment]
Closing this as duplicate https://github.com/phalcon/cphalcon/issues/14641
