### ISSUE TITLE
[BUG]: Phalcon 4.1.2 - Custom Validators - not working

### ISSUE THREAD

**Issue by phatnt93** [phalcon/cphalcon#16301]
**Describe the bug**
Method validate() is not compatible when I extend \Phalcon\Validation\AbstractValidator class to create new Validator

See example: https://docs.phalcon.io/4.0/en/validation#custom-validators

**Expected behavior**
I wanna create a Custom Validator

**Screenshots**
![image](https://user-images.githubusercontent.com/26946722/222309258-d08df117-6a8f-4c0f-9051-14fe732f0aa1.png)

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: 7.4
 - Operating System: Ubuntu 20.4
 - Installation type: installing via package manager
 - Server: Nginx

**Comment by Jeckerson** [comment]
You forgot to add `: bool` at the end of definition:

https://github.com/phalcon/ide-stubs/blob/77384e4f42542f11b065b2a860b9bca2ea20ad5a/src/Phalcon/Validation/ValidatorInterface.php#L45

**Comment by phatnt93** [comment]
Thank you!!!
