### ISSUE TITLE
Exception: Service linkto is not registered

### ISSUE THREAD

**Issue by jordantsap** [phalcon/cphalcon#16324]
I follow the tutorial here
https://docs.phalcon.io/5.0/en/tutorial-basic
but i get Exception: Service linkto is not registered

**Comment by vanthuanqs** [comment]
For anyone got the same problem as me, please use `$this->tag->a` instead of `$this->tag->linkTo`

https://github.com/phalcon/tutorial/blob/master/app/views/index/index.phtml
