### ISSUE TITLE
[BUG]: Model->toArray not checking/using getters

### ISSUE THREAD

**Issue by noone-silent** [phalcon/cphalcon#16320]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
toArray uses the value directly instead using getters if exists. If a getter for a field exists, it should always be used.

**To Reproduce**
[See linked line in code](https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/Model.zep#L3268)

```php

CREATE TABLE test_table (
    id SERIAL,
    db_field VARCHAR(50) NULL
);

INSERT INTO test_table VALUES (1, 'test value');

class TestModel extends \Phalcon\Mvc\Model
{

    /**
     * @Primary
     * @Identity
     * @Column(type="integer", nullable=false, column="id")
     */
    private ?int $id = null;

    /**
     * @Column(type="string", nullable=true, column="db_field")
     */
    private ?string $dbField = null;

    public function initialize(): void
    {
        $this->setSource('test_table');
    }

    public function getDbField(): string
    {
        return 'Some Prefix: ' . ($this->dbField ?? '');
    }
}

$test = TestModel::findFirst(1);
var_dump($test->toArray()); 
// array(2) {
//  ["id"]=> int(1)
//  ["dbField"]=>  string(10) "test value"
// }

```

**Expected behavior**
toArray should call the getters.

```php
// Expected output from script above

echo $test->toArray();
// array(2) {
//  ["id"]=> int(1)
//  ["dbField"]=>  string(23) "Some prefix: test value"
// }
```

**Details**
 - Phalcon version: v4 and v5
 - PHP Version: 8.1.2
 - Operating System: debian
 - Installation type: installing via package manager
 - Zephir version (if any):
 - Server: Nginx
 - Other related info (Database, table schema): Mariadb

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16469

Thank you @noone-silent
