### ISSUE TITLE
[BUG]: Operands have incompatible types in `Validation:validate()` method

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#16337]
**Describe the bug**
Incorrect return type is defined in `Phalcon\Filter\Validation:validate()` method.
It also can return `false` in line https://github.com/phalcon/cphalcon/blob/fc183e11e8b96c43daf7d893244846206dc2aa73/phalcon/Filter/Validation.zep#LL515C26-L515C26

**To Reproduce**
You need to define `beforeValidation()` method, which requires `bool` return type and is called in lines above.

```php
<?php

use Phalcon\Filter\Validation;

class MyValidator extends Validation
{
    public function beforeValidation(array|object $data, $entity, Messages $messages): bool
    {
        return false;
    }

    public function initialize(): void
    {
        // Validation rules...
    }
}
```

> Provide minimal script to reproduce the issue

```php
$validator = new MyValidator();
if ($validator->validate() === false) {
    // This is valid.
}
```

**Expected behavior**

Return type of `Phalcon\Filter\Validation\ValidationInterface:validate()` must be `Messages|false`

**Details**
 - Phalcon version: 5.2
 - PHP Version: 8.1
 - Operating System: any

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16338
