### ISSUE TITLE
[BUG]: Random exceptions when retrieving data using Stream + Json

### ISSUE THREAD

**Issue by krazzer** [phalcon/cphalcon#16339]
**Describe the bug**
The Json serialiser uses `if unlikely` when determining if json_decode gives an error or not. This is faster, but can give unexpected results. https://igoro.com/archive/fast-and-slow-if-statements-branch-prediction-in-modern-processors/.

This is no problem for caching scenario's, but the Stream storage adapter may as well be used for permanent storage. 

**To Reproduce**
This is not easy to reproduce with just a simple script, you need to run a lot of writing / reading of Streams over some time. Then exceptions will appear.

**Expected behavior**
Not have random errors when reading stream data with the Json adapter.
Of course this is easily fixed by simply using `if` instead of `if unlikely`, but this probably more a design philosophy question.

**Details**
 - Phalcon version: 4.2 (But still present in 5.x)
 - PHP Version: 7.4
 - Operating System: Linux
 - Installation type: Cloudlinux
 - Server: Apache

**Comment by niden** [comment]
This has been addressed in https://github.com/phalcon/cphalcon/pull/16347

Thank you @krazzer
