### ISSUE TITLE
[BUG]: Multiple binds not working

### ISSUE THREAD

**Issue by FaimMedia** [phalcon/cphalcon#16351]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**

**To Reproduce**
> Provide output if related. Provide coredump if any. Use https://docs.phalcon.io/en/latest/generating-backtrace as reference.

```php
CustomerPlanModel::findFirst([
	'conditions' => 'dateStart <= :date: AND dateEnd > :date:',
	'bind'       => [
		'date' => date('Y-m-d'),
	],
]);
```

```php
echo $this->getDi()->getShared('db')->getRealSQLStatement();
```

PHQL, second bind doesn't get replaced:
```sql
SELECT ... FROM `customer_plan` WHERE `customer_plan`.`date_start` <= '2023-06-03' AND `customer_plan`.`date_end` > :date LIMIT 1
```

MySQL query log, prepared statement does look okay:
```sql
SELECT ... FROM `customer_plan` WHERE `customer_plan`.`date_start` <= ? AND `customer_plan`.`date_end` > ? LIMIT ?
```

**Details**
 - Phalcon version: `5.2.1`
 - PHP Version: `8.2.6`
 - Operating System: Alpine 3.18 (Docker)
 - Installation type: Source
 - Zephir version (if any): -
 - Server: Apache / PHP-FPM
 - Other related info (Database, table schema): MySQL

**Comment by Jeckerson** [comment]
You will need to enable (set to `true`) `PDO::ATTR_EMULATE_PREPARES` option.

https://www.php.net/manual/en/pdo.setattribute.php
> If set to true PDO will always emulate prepared statements, otherwise PDO will attempt to use native prepared statements. In case the driver cannot successfully prepare the current query, PDO will always fall back to emulating the prepared statement.

Code example:
```php
$di->setShared('db', function () {
    return new Mysql([
        'host'        => $_ENV['DB_HOST'],
        'port'        => $_ENV['DB_PORT'],
        'dbname'      => $_ENV['DB_NAME'],
        'charset'     => $_ENV['DB_CHARSET'],
        'options'  => [
            PDO::ATTR_EMULATE_PREPARES   => true,
        ],
        'username'    => $_ENV['DB_USERNAME'],
        'password'    => $_ENV['DB_PASSWORD'],
    ]);
});
```

Otherwise, in your example, use different names for each named bind parameter:
```php
$date = date('Y-m-d');

CustomerPlanModel::findFirst([
    'conditions' => 'dateStart <= :dateStart: AND dateEnd > :dateEnd:',
    'bind'       => [
        'dateStart' => $date,
        'dateEnd'   => $date,
    ],
]);
```
