### ISSUE TITLE
[NFR]: Add a WeakCache using WeakReference

### ISSUE THREAD

**Issue by rudiservo** [phalcon/cphalcon#16372]
The idea is to add a key => value Cache service that uses a WeakReference Object has value.

WeakReference was implemented in PHP 7.4, it uses creates an objects that has a reference to an object but does not prevent it from being destroyed by the Garbage Collector.

So we can have a key => value cache that will return an object if it exists anywhere in memory and has not been destroyed by the GB.

This will help solve issues with the ORM in the future.

For more information about WeakReference

https://www.php.net/manual/en/class.weakreference.php

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16377

Thank you again @rudiservo

**Comment by rudiservo** [comment]
No problem, hopefully you will be approving more :)
It's always a good experience and I am learning.
