### ISSUE TITLE
[BUG]: ORM infinite save loop

### ISSUE THREAD

**Issue by rudiservo** [phalcon/cphalcon#16395]
**Describe the bug**
The Model::save has no checks if a model has been called to be saved before, this can cause a infinite save loop.

```php
$customer = Customers::findFirst();
$invoice = new Invoices();
$invoice->customer = $customer
$customers->invoices = [ $invoice ];
$customer->save();
```
![image](https://github.com/phalcon/cphalcon/assets/1518071/6991bb4f-3f12-4dbd-b1ad-888c856c7258)

**Expected behavior**
it is expected not so run save on the model that has already been called to saved.

**Details**
 - Phalcon version: 5.* but it affects all versions
 - PHP Version: 8.2
 - Operating System: Ubuntu
 - Installation type: docker

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16399
