### ISSUE TITLE
[BUG]: undefined column with columnMap and model caching

### ISSUE THREAD

**Issue by Deathamns** [phalcon/cphalcon#16420]
**Describe the bug**
`modelsMetadata` and `columnMap` don't work well together since [v5.3.0](https://github.com/phalcon/cphalcon/releases/tag/v5.3.0). In [v5.2.3](https://github.com/phalcon/cphalcon/releases/tag/v5.2.3) everything was fine.
The following script runs at first time, and its output should be `1`.
After creating the models' cache, every following execution will result in an error:
`Column 'user_id' doesn't belong to any of the selected models (1), when preparing: SELECT user_id FROM Users`
Deleting the cache directory allows the script to run correctly once more.

Removing the `$di->setShared('modelsMetadata', ...);` part or not using `columnMap` "solves" the problem.
Possible culprit #16393.
Maybe related #16411, but I'm not sure.

**To Reproduce**
```php
<?php

class Users extends \Phalcon\Mvc\Model {
	public $user_id;
	public $user_name;

	public function columnMap() {
		return [
			'acc_id' => 'user_id',
			'user_name' => 'user_name'
		];
	}
}

$di = new \Phalcon\Di\FactoryDefault();

$di->setShared('db', function() {
	return new \Phalcon\Db\Adapter\Pdo\Mysql([
		'dbname'   => 'test',
		'username' => 'test',
		'password' => 'test'
	]);
});

$di->setShared('modelsMetadata', function() {
	is_dir('cache/models') || mkdir('cache/models', 0777, true);

	return new \Phalcon\Mvc\Model\Metadata\Stream([
		'metaDataDir' => './cache/models/'
	]);
});

try {
	$app = new \Phalcon\Mvc\Application($di);
	echo $app->modelsManager->executeQuery(
		'SELECT user_id FROM Users'
	)->getFirst()->user_id;
} catch ( Exception $ex ) {
	print_r($ex->getMessage());
}
```

**Expected behavior**
Print `1` every time the script is executed.

**Details**
 - Phalcon [v5.3.0](https://github.com/phalcon/cphalcon/releases/download/v5.3.0/phalcon-php8.1-nts-windows2019-vs16-x64.zip)
 - PHP 8.1.22 (cli) (built: Aug  1 2023 17:14:28) (NTS Visual C++ 2019 x64)
 - MySQL 8.1.0 schema:
```sql
CREATE DATABASE IF NOT EXISTS `test`;
USE `test`;

CREATE TABLE IF NOT EXISTS `users` (
  `acc_id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_name` varchar(15) COLLATE utf8mb4_0900_bin NOT NULL,
  PRIMARY KEY (`acc_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

INSERT INTO `users` (`acc_id`, `user_name`) VALUES (1, 'test');
```

**Comment by rudiservo** [comment]
hi @Deathamns, I think I have detected the bug, trying to replicate it in the tests, a fix will be issued soon.

**Comment by rudiservo** [comment]
@Deathamns just to confirm, are you using APCU or any other cache metadata?

**Comment by Deathamns** [comment]
I had the `apcu` extension enabled in PHP, but the issue persists after I disable it.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16421

Thank you @Deathamns and @rudiservo
