### ISSUE TITLE
[BUG]: Call to undefined function zephir_parse_file() when trying to generate docs

### ISSUE THREAD

**Issue by r-martins** [phalcon/cphalcon#16443]
Questions? Forum: https://phalcon.io/forum or Discord: https://phalcon.io/discord

**Describe the bug**
I followed the steps to generate docs for v 5.3 and 5.3.1 and it throws the error 
> Fatal error: Uncaught Error: Call to undefined function zephir_parse_file() in /var/www/cphalcon/tests/_config/generate-api-docs.php on line 199

**To Reproduce**
Reproduced the steps in the README.md.
1. git clone https://github.com/phalcon/cphalcon.git
2. cd cphalcon
3. git checkout v5.3.1
4. php tests/__config/generate-api-docs.php

**Expected behavior**
See the generated updated docs.

**Details**
Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 5.3.0
Build Date => Sep 20 2023 05:26:37
Powered by Zephir => Version 0.17.0-9f99da6
PHP Version: 8.2.10

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.resultset_prefetch_records => 0 => 0
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.dynamic_update => On => On
phalcon.warning.enable => On => On

**Comment by Jeckerson** [comment]
Did you installed zephir extension?

```bash
pecl install zephir_parser
```

**Comment by Jeckerson** [comment]
Just simulated your steps, yes you need to install `zephir_parser` PHP extension, enable it and only then it will be possible to execute `generate-api-docs.php`, here is example via docker:
```
docker exec -it php:8.2-cli bash
apt update && apt install git -y
pecl install zephir_parser
docker-php-ext-enable zephir_parser
```
After these commands you might run `generate-api-docs.php`.

Closing, feel free to ask any questions related to this topic.
