### ISSUE TITLE
[BUG]: PdoFactory::load() pass only 'options' without credentials to PdoFactory::newInstance()

### ISSUE THREAD

**Issue by mhz-tamb** [phalcon/cphalcon#16465]
**Describe the bug**
PdoFactory::load() pass only 'options' without credentials to PdoFactory::newInstance()

**To Reproduce**

```php
// php config file
return [
    'database' => [
        'db' => [
            'adapter'  => 'postgresql',
            'host'     => 'postgres',
            'dbname'   => 'test',
            'username' => 'postgres',
            'password' => 'postgres'
            'options' => ''
        ],
    ]
]

// db provider
public function register(DiInterface $container): void
{
    foreach ($container->getShared('config')->get('database') as $name => $config) {
        $container->setShared($name, fn() => (new PdoFactory())->load($config));
    }
}
```

**Expected behavior**
Registered db service and connected to database

**Details**
 - Phalcon version: 5.4.0
 - PHP Version: 8.2.12
 - Operating System: macOS Sonoma 14.1
 - Installation type: installing via package manager
 - Zephir version (if any):
 - Server: Nginx
 - Database): Postgresql

**Additional context**
The load() method does not pass credentials to newInstance() from parameters and to use this method you have to modify the config as: 
```php
return [
    'database' => [
        'db' => [
            'adapter'  => 'postgresql',
            'options' => [
                'host'     => 'postgres',
                'dbname'   => 'test',
                'username' => 'postgres',
                'password' => 'postgres',
                'options' => []
            ]
        ],
    ]
]
```
https://github.com/phalcon/cphalcon/blob/5.0.x/phalcon/Db/Adapter/PdoFactory.zep#L56

**Comment by niden** [comment]
Checking the code, it was intended to be like that. Two elements: One for the adapter name and the second one for `options` which includes username/password.

Shouldn't it be this way?

**Comment by niden** [comment]
I see now. The documentation tells a different story :/

Let me correct that

**Comment by niden** [comment]
Have a look at this:

https://github.com/phalcon/docs/commit/3aaaaf81cf5e710bf46fb2629328a868b799789c

and live:

https://docs.phalcon.io/5.0/en/db-layer#load

**Comment by mhz-tamb** [comment]
@niden  Ok. Thank you! It just looks a little weird with PDO options.
