### ISSUE TITLE
[BUG]: `Column '0' is not part of the column map`. After iterating for the second time in a Resultset

### ISSUE THREAD

**Issue by JoaoSetas** [phalcon/cphalcon#16467]
We have a problem in our project since the upgrade from phalcon `3.4.5` to the latest version `5.4.0`.
When using the `\Phalcon\Mvc\Model\Query\Builde`r in any of our models we have the same issue after iterating the second time over the `ResultSet` we get the error `Column '0' is not part of the column map` when doing `toArray()` in that result set.

**To Reproduce**

**Code example of bug:**

```php
$result = $models_manager
    ->createBuilder()
    ->addFrom(Products::class, 'p')
    ->limit(10)
    ->getQuery()
    ->execute();

foreach ($result as $value) {}
foreach ($result as $value) {}

$result->toArray();  // Error here - `Column '0' is not part of the column map` 
```

We can also reproduce the error like this.

```php
$result = $models_manager
    ->createBuilder()
    ->addFrom(Products::class, 'p')
    ->limit(10)
    ->getQuery()
    ->execute();

$result->rewind();
$result->next();
dump($result);
$result->rewind();
dump($result); exit;
```

We notice that in the second dump, the property `row` has more properties and with the wrong indexs.

**Screenshots**
**First dump:**
![image](https://github.com/phalcon/cphalcon/assets/30462063/4b2d6832-b0fe-49ed-b3a3-a6842b7e035b)

**Second dump:**
![image](https://github.com/phalcon/cphalcon/assets/30462063/6ba91564-21f4-4cc7-8789-fa6e2e727021)

**Details**
 - Phalcon version: 5.4.0
 - PHP Version: 8.1.25
 - Operating System: Docker image - php:8.1-fpm
 - Installation type: installing via package manager
 - Server: Nginx 
 - Database: mysql:8

**Comment by dfernandesbsolus** [comment]
I have the same problem :(

**Comment by apoca** [comment]
Same problem here!!!

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16468

Thank you @JoaoSetas @dfernandesbsolus and @apoca  for reporting this
