### ISSUE TITLE
[BUG]: apcu_fetch(): Argument 2 ($success) must be passed by reference

### ISSUE THREAD

**Issue by kowach** [phalcon/cphalcon#16489]
Weird bug in phpApcuFetch()
"PHP message: PHP Warning:  apcu_fetch(): Argument 2 ($success) must be passed by reference, value given in method... in $cache->get(...)

To reproduce:
```php
    $adapter = (new AdapterFactory(new SerializerFactory()))
        ->newInstance('apcu');
    $cache = new Cache($adapter);
    $cache->get('key');
```
Workaround (I just extended adapter and put same code as in Storage/Adapter/Apcu.zep):
```php
   class MyApcu extends \Phalcon\Cache\Adapter\Apcu
   {
       protected function phpApcuFetch($key, $success = null): mixed
       {
           return apcu_fetch($key, $success);
       }
   }
   $myAdapter = new MyApcu(new SerializerFactory());
   $cache = new Cache($myAdapter);
```

**Details**
Fresh installed server:
 - Phalcon version: 5.5.0 (Compiled from source)
 - Zephir: Version 0.17.0-9f99da6
 - PHP Version: 8.1.27
 - Operating System: Ubuntu server 22.04
 - Server: Nginx

I can't reproduce the bug with same configuration on my dev machine.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16497

Thank you @kowach
