### ISSUE TITLE
php 7.4.16   install phalcon extension failed

### ISSUE THREAD

**Issue by jason-gao** [phalcon/cphalcon#16506]
I want to try  all this version in https://pecl.php.net/package/phalcon,but always failed!
why?

error like this:
                                                                                                                 ^~~~~~~~~
/private/tmp/pear/temp/phalcon/phalcon.zep.c:69393:89: note: passing argument to parameter 'position' here
zval *phalcon_replace_marker(int named, zval *paths, zval *replacements, unsigned long *position, char *cursor, char *marker)
                                                                                        ^
/private/tmp/pear/temp/phalcon/phalcon.zep.c:69585:64: warning: incompatible pointer types passing 'zend_ulong *' (aka 'unsigned long long *') to parameter of type 'unsigned long *' [-Wincompatible-pointer-types]
                                                replace = phalcon_replace_marker(0, paths, replacements, &position, cursor, marker);
                                                                                                         ^~~~~~~~~
/private/tmp/pear/temp/phalcon/phalcon.zep.c:69393:89: note: passing argument to parameter 'position' here
zval *phalcon_replace_marker(int named, zval *paths, zval *replacements, unsigned long *position, char *cursor, char *marker)
                                                                                        ^

**Comment by jason-gao** [comment]
I installed like this  crystal@crystaldeMac tmp $ sudo pecl install phalcon-4.1.0

**Comment by Jeckerson** [comment]
You need to specify what version to install, ex: `pecl install phalcon-5.4.0`. As for some reason PECL tool can't detect PHP version and will install latest Phalcon version, which doesn't supported by PHP7.
