### ISSUE TITLE
[BUG]: Argument #2 ($fetchMode) must be passed explicitly

### ISSUE THREAD

**Issue by vanthuanqs** [phalcon/cphalcon#16512]
**Describe the bug**
Using named param in php 8.1 and it caused the bug

**To Reproduce**
Run this code
```php
$sql = "select * from product where id = :id";
$item = $this->db->fetchOne($sql,  bindParams: ['id' => $id]);
var_dump($item);die;
```

The table is PosgreSQL database
```sql
create table product
(
    id          serial,
    title       varchar(500),
    description text,

    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    deleted_at  timestamp with time zone default null,

    primary key (id)
)
```

**Result**
Got an error:
```
<br />
<b>Fatal error</b>:  Uncaught ArgumentCountError: Phalcon\Db\Adapter\AbstractAdapter::fetchOne(): Argument #2 ($fetchMode) must be passed explicitly, because the default value is not known in [__local_code__php]
Stack trace:
#0 /app/site/src/Services/ServiceCrud.php(81): Phalcon\Db\Adapter\AbstractAdapter-&gt;fetchOne()
#1 [__local_code__php]
#2 [internal function]: [__local_code__php]
#3 [internal function]: Phalcon\Mvc\Micro\LazyLoader-&gt;callMethod()
#4 /app/site/src/app.php(51): Phalcon\Mvc\Micro-&gt;handle()
#5 /app/site/public/index.php(11): require_once('...')
#6 {main}
  thrown in [__local_code__php]
```

**Expected behavior**
The function should return the values, not throw the error

**Screenshots**
-none-

**Details**
 - Phalcon version: 5.1.2
 - PHP Version: ```PHP 8.1.27 (cli) (built: Dec 21 2023 20:19:54) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies```
 - Operating System: Ubuntu 22.04.3 LTS (inside Docker)
 - Installation type: installing via package manager `/bin/bash -c 'sudo add-apt-repository ppa:ondrej/php && sudo apt-get update && sudo apt-get install php8.1-phalcon5'`
 - Zephir version (if any):
 - Server: Nginx
 - Other related info (Database PosgreSQL):

**Additional context**
-none-

_Thank you for reviewing this bug!_

**Comment by niden** [comment]
At the moment Zephir and Phalcon subsequently does not support named arguments. If you wish to use them, you will need to use the PDO adapter directly:

```php
getInternalHandler
$this->db->getInternalHandler()->fetchOne($sql,  bindParams: ['id' => $id]);
```

**Comment by vanthuanqs** [comment]
Thank you for your response!

I am using a child class to extend Postgresql, so this is my solution:

```php
<?php
declare(strict_types=1);

namespace ZAdmin\Library\Db;

use Phalcon\Db\Adapter\Pdo\Postgresql as PostgresqlAdapter;
use Phalcon\Db\Enum;

class Postgresql extends PostgresqlAdapter
{
    public function __construct(array $descriptor)
    {
        parent::__construct($descriptor);
    }

    /**
     * @param string $sqlQuery
     * @param array $bindParams
     * @return object|bool
     */
    public function fetchOneObject(string $sqlQuery, array $bindParams = [])
    {
        /** @var object|bool $value */
        $value = parent::fetchOne($sqlQuery, Enum::FETCH_OBJ, $bindParams);
        return $value;
    }

}
```
