### ISSUE TITLE
[BUG]: Phalcon Compile Command has Incorrect Version  

### ISSUE THREAD

**Issue by kgrammer** [phalcon/cphalcon#16511]
In the "How to upgrade" section of the Phalcon docs (https://docs.phalcon.io/latest/upgrade/), in the section titled "Alternative installation", the "Compile Phalcon" section contains the following:

```
cd cphalcon/
git checkout tags/5.3.0 ./
zephir fullclean
zephir build
```

I believe the tag checkout version should be updated to match the latest release.  As if this bug report, the latest release was 5.6.0.

**Comment by niden** [comment]
This has been resolved https://github.com/phalcon/documentation/commit/bf43cd91aac8cac8f52e3520cc1a3d2997c48355

Thank you @kgrammer
