### ISSUE TITLE
[BUG] Phalcon\Mvc\Model::find() fails when using "columns" and "limit" params with Oracle

### ISSUE THREAD

**Issue by rlaffers** [phalcon/cphalcon#1652]
~~I am using **Phalcon 1.2.1** (unable to upgrade at the moment but seeing the changelog up to 1.2.4, this issue has presumably not been addressed yet)~~
The issue confirmed in Phalcon 1.2.4 with **Oracle 10g** (release 10.2.0.3.0),             PDO::ATTR_CASE is set to PDO::CASE_LOWER.
Related issue: https://github.com/phalcon/cphalcon/issues/760

```php
$robots = Models\Robots::find(array(
    'columns' => 'id' 
));
```
Fails with the following error:
> Phalcon\Mvc\Model\Exception: Column 'id' doesn't belong to any of the selected models (1), when preparing: SELECT id FROM [MyApp\Models\Robots]

My db table is called "robots":
```
        ID   NAME                   TYPE                         YEAR   CURRENT_STATUS
----------   --------------------   --------------------   ----------   --------------------
         1   Robotina               mechanical                   1972   on
         2   Astro Boy              mechanical                   1952   off
         3   Terminator             cyborg                       2029   on

```

My model:
```php
namespace MyApp\Models;
class Robots extends \Phalcon\Mvc\Model {
    public function getSource() {
        return 'robots';
    }
}
```

According to the docs, this *ought* to work but does not.

A workaround is to specify $columnMap in the model (which is not optimal and should not be necessary):

```php
class Robots extends \Phalcon\Mvc\Model {
    public $id;
    public $name;
    public $type;
    public $year;
    public $current_status;
    public $db_rownum;

    public function getSource() {
        return 'robots';
    }

    public function columnMap() {
        return array(
            'id' => 'id',
            'name' => 'name',
            'type' => 'type',
            'year' => 'year',
            'current_status' => 'current_status',
            'db_rownum' => 'db_rownum',
        );
    }
}
```
Now it works fine, however, it will fail again if I try:
```php
$robots = Models\Robots::find(array(
    'columns' => 'id' 
    'limit' => 1 
));
```
> Phalcon\Mvc\Model\Exception: Column "db_rownum" doesn't make part of the column map

Please note that I included db_rownum in the columnMap as suggested in https://github.com/phalcon/cphalcon/issues/760 . It helps only when:
```php
$robots = Models\Robots::find(array(
    'limit' => 1 
));
```
If both "limit" and "columns" are used the find() always fails with the above error.

I suspect Oracle is the culprit here, Phalcon does not play nice with it. 
Phalcon\Mvc\Model::findFirst() is affected by the same issue.

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.x branch (Phalcon 2.0.4), you have to change a global ORM setting to allow unexpected columns:

```php
\Phalcon\Mvc\Model::setup(['ignoreUnknownColumns' => true]);
```
