### ISSUE TITLE
[BUG]: \Phalcon\Cli\Router must be compatible with \Phalcon\Cli\RouterInterface

### ISSUE THREAD

**Issue by jturbide** [phalcon/cphalcon#16551]
**Describe the bug**
- The `\Phalcon\Cli\Router` must be compatible with `\Phalcon\Cli\RouterInterface`
- The `\Phalcon\Cli\Router` should implements `\Phalcon\Cli\RouterInterface`

**To Reproduce**
```php
class Router extends \Phalcon\Cli\Router implements \Phalcon\Cli\RouterInterface
{
}
```

**Will result in:**
- Fatal error: Declaration of Phalcon\Cli\Router::getRouteById($id) must be compatible with Phalcon\Cli\RouterInterface::getRouteById($id): Phalcon\Cli\Router\RouteInterface

**Comment by niden** [comment]
This has been resolved in https://github.com/phalcon/cphalcon/pull/16554

Thank you @jturbide
