### ISSUE TITLE
[BUG]: "SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens" produced when you use the same named binded parameter more than once in query conditions

### ISSUE THREAD

**Issue by matricali** [phalcon/cphalcon#16573]
**Describe the bug**

"SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens" produced when you use the same named binded parameter more than once in query conditions

**To Reproduce**

Use the same named binded parameter more than once in your condition

```php
$holidays = Holidays::find([
    'conditions' => '(date_start >= :date_start: AND date_start <= :date_end:) OR (date_end >= :date_start: && date_end <= :date_end:)',
    'bind' => [
        'date_start' => $date_search_min->format('Y-m-d H:i:s'),
        'date_end' => $date_search_max->format('Y-m-d H:i:s'),
    ],
]);
```
**Expected behavior**

It should be create a query like this:
`SELECT * FROM holidays WHERE (date_start >= "2024-04-24 14:30:00" AND date_start <= "2024-05-01 16:00:00") OR (date_end >= "2024-04-24 14:30:00" && date_end <= "2024-05-01 16:00:00")`

It works on previous versions (3.x).
I'm encountered this error migrating an app from Phalcon 3.4 to 5.6

**Details**
 - Phalcon version: (`php --ri phalcon`)

```
phalcon


Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 5.6.2
Build Date => Apr 23 2024 10:54:03
Powered by Zephir => Version 0.18.0-$Id$

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.resultset_prefetch_records => 0 => 0
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.dynamic_update => On => On
phalcon.warning.enable => On => On
```
 - PHP Version: (`php -v`) PHP 8.3.6 (cli) (built: Apr 11 2024 17:57:50) (NTS)
 - Operating System: Docker using WSL
 - Installation type: Installed via PECL
 - Server: Apache
 - Other related info (Database, table schema): pdo_mysql, MariaDB 10.1

**Comment by matricali** [comment]
I think it could be related to PDO::ATTR_EMULATE_PREPARES flag

**Comment by s-ohnishi** [comment]
You're probably right.
The official manual says the following:
"You must include a unique parameter marker for each value you wish to pass in to the statement when you call PDOStatement::execute(). You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on."
https://www.php.net/manual/en/pdo.prepare.php

And since Phalcon has not changed since [the issue](https://github.com/phalcon/cphalcon/issues/16474), the your system setting is probably `off`.
In my environment, it was `on`, so I could use placeholders with the same name without any problems.

I tried it again just to be sure.
```PHP
$test = Users::find([
    'conditions' => '([createdAt] >= :date_start: AND [createdAt] <= :date_end:) OR (updatedAt>:date_start: AND [updatedAt] <= :date_end:)',
    'bind' => [
        'date_start' => date('Y-m-d', strtotime('-7 days')),
        'date_end' => date('Y-m-d', strtotime('today')),
    ]
]);
```
(It's a shame that I have to use meaningless square brackets because of [another issue](https://github.com/phalcon/cphalcon/issues/16502))
It runs without any problems.

When I checked with `getRealSQLStatement()`, it was as follows
```SQL
SELECT .... FROM `users` WHERE (`users`.`createdAt` >= '2024-04-18' AND `users`.`createdAt` <= '2024-04-25') OR (`users`.`updatedAt` > :date_start AND `users`.`updatedAt` <= :date_end)
```
The general log was output as follows.
```SQL
SELECT .... FROM `users` WHERE (`users`.`createdAt` >= '2024-04-18' AND `users`.`createdAt` <= '2024-04-25') OR (`users`.`updatedAt` > '2024-04-18' AND `users`.`updatedAt` <= '2024-04-25')
```
It's fine that it's being executed properly, but the fact that `getRealSQLStatement()` doesn't return the correct value is another issue.

**Comment by matricali** [comment]
If I add `'options' => [  PDO::ATTR_EMULATE_PREPARES => true  ] ` to my database configuration, then I get this error `Scanner: Unknown opcode 403`

My code:
```php
$holidays = Holidays::find([
    'conditions' => '(date_start >= :date_start: AND date_start <= :date_end:) OR (date_end >= :date_start: && date_end <= :date_end:)',
    'bind' => [
        'date_start' => $date_search_min->format('Y-m-d H:i:s'),
        'date_end' => $date_search_max->format('Y-m-d H:i:s'),
    ],
]);
```

Exprected result:
`SELECT * FROM holidays WHERE (date_start >= "2024-04-24 14:30:00" AND date_start <= "2024-05-01 16:00:00") OR (date_end >= "2024-04-24 14:30:00" && date_end <= "2024-05-01 16:00:00")`

**Comment by matricali** [comment]
After fixing and error in the query and enabling PDO::ATTR_EMULATE_PREPARES => true in my database configuration everything works fine
