### ISSUE TITLE
[NFR][1.3.0] Multimodule dispatching problem

### ISSUE THREAD

**Issue by lantian** [phalcon/cphalcon#1658]
When I use in module 'Pesite':

``` php
$this->dispatcher->forward(
    [
        'module'     => 'Core',
        'namespace'  => 'Core\Controller',
        'controller' => 'Error',
        'action'     => 'show404'
    ]
);
```

I've an error: 
> **[ERROR]** View not found - `".../app/modules/Pesite/View/Error/show404.volt"`

It's tries to pick view from current module...

**Comment by sergeyklay** [comment]
Implemented in #12857
