### ISSUE TITLE
Phalcon 5.7.0 Release Reports 5.6.2 as Internal Version Number 

### ISSUE THREAD

**Issue by kgrammer** [phalcon/cphalcon#16597]
**Describe the bug**
After issuing pecl command to update to Phalcon 5.7.0, Phalcon's internal version is still reported as the last release, which was 5.6.2.

**To Reproduce**
Use pecl to update to the latest 5.7.0 release.
Issue "php -i" and you will see Phalcon 5.7.0 listed as the installed version.

Issue php -r "echo (new \Phalcon\Support\Version())->get();" and you will see version 5.6.2 returned.

In the code, the following returns "5.6.2".

        $phalcon_version = new \Phalcon\Support\Version();
        $dashboard['phalcon_version'] = $phalcon_version->get();                    # Get the version of Phalcon we are running

**Expected behavior**
The expected behavior is for the internal Phalcon version returned to be "5.7.0".

**Details**
 - Phalcon version: 5.7.0
 - PHP Version: 8.3.7
 - Operating System: Ubuntu 22.04
 - Installation type: Installing via pecl
 - Zephir version (if any): 1.6.0
 - Server: Apache

**Additional context**
Nothing more to add.

**Comment by fln** [comment]
Can confirm the issue:

```
# php -i | grep -A 2 'phalcon =>'
phalcon => enabled
Author => Phalcon Team and contributors
Version => 5.7.0
```

But:

```
# php -r "echo (new Phalcon\Support\Version())->get();"
5.6.2
```

**Comment by fln** [comment]
Version is hard-coded in `PHP_METHOD(Phalcon_Support_Version, getVersion)`:

https://github.com/phalcon/cphalcon/blob/master/ext/phalcon/support/version.zep.c#L101

**Comment by niden** [comment]
Sorry about that guys. I forgot to change the version in the `Version.zep`.

I just pushed a commit on 5.0.x that solves this.

**Comment by kgrammer** [comment]
@niden, I just installed again from pecl and the internal version is still returning 5.6.2.

**Comment by niden** [comment]
> @niden, I just installed again from pecl and the internal version is still returning 5.6.2.

Yes the internal for now will still report 5.6.2. If you install from the 5.0.x branch it will show the correct one.

I will be releasing a new version this week coming so this will be resolved in pecl also.

**Comment by niden** [comment]
This has been resolved with the new release.
