### ISSUE TITLE
[BUG]: Classes that implement Serializable have wrong function declaration

### ISSUE THREAD

**Issue by noone-silent** [phalcon/cphalcon#16591]
**Describe the bug**
For example the `\Phalcon\Mvc\Model` class implements `\Serializable`. This class is defined as:

```php
interface Serializable {
    public serialize(): ?string
    public unserialize(string $data): void
}
```

The `\Phalcon\Mvc\Model` has it implemented like this:

```zephir
public function serialize() -> string
public function unserialize(var data)
```

**Expected behavior**
Follow the interface definition.

**Details**
 - Phalcon version: 5.6.2
 - PHP Version: 8.2
 - Operating System: debian
 - Installation type: installing via package manager
 - Zephir version (if any): 0.17.0
 - Server: Nginx
 - Other related info (Database, table schema): none

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16592

Thank you again @noone-silent
