### ISSUE TITLE
[BUG]: Fatal error on route group getHostname

### ISSUE THREAD

**Issue by oleghind** [phalcon/cphalcon#16601]
There is a fatal error when using Route Group without hostname restriction.
`PHP Fatal error:  Phalcon\Mvc\Router\Group::getHostname(): Return value must be of type string, null returned in Unknown on line 0`

I suggest changing functions return type to `string | null` instead of just `string`.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16602

Thank you @oleghind
