### ISSUE TITLE
[BUG] Wrong interface on compileSource leads to fatal error

### ISSUE THREAD

**Issue by oleghind** [phalcon/cphalcon#16608]
` protected function compileSource(string! viewCode, bool extendsMode = false) -> string`

**compileSource** method returns string, but sometimes it returns array

Example:
```
                    if extendsMode {
                        let finalCompilation[] = block;
                    } else {
                        let finalCompilation .= block;
                    }
                }
            }

            return finalCompilation;
```

... which leads to a crash:
`PHP Fatal error:  Phalcon\Mvc\View\Engine\Volt\Compiler::compileSource(): Return value must be of type string, array returned`

Better adjust interface to `string | array`

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16609

Thank you @oleghind
