### ISSUE TITLE
[BUG]: Email validation does not allow UTF8SMTP

### ISSUE THREAD

**Issue by noone-silent** [phalcon/cphalcon#16637]
**Describe the bug**
With the UTF8SMTP Extension, it is possible to allow any utf-8 character in the local part. Also domain names can have umlauts, but needs different parsing. RFC: https://www.rfc-editor.org/rfc/rfc5336#section-3.2

**To Reproduce**
Use any email, like `täst@example.com`

```php
            $validation = new Validation();
            $validation->add('email', new Validation\Validator\Email());
            var_dump($validation->validate(['email' => 'täst@example.com']));
```

**Expected behavior**
Add a flag/option to allow UTF8SMTP email addresses.

When this filter is set, pass `FILTER_FLAG_EMAIL_UNICODE` to the `filter_var` function.

**Details**
 - Phalcon version: v5.8.0
 - PHP Version: 8.2.20
 - Operating System: debian
 - Installation type: Compiling from source
 - Zephir version (if any): -
 - Server: Nginx
 - Other related info (Database, table schema): MariaDB

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16638

Thank you @noone-silent
