### ISSUE TITLE
Allow View::render() without any arguments

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#1735]
I currently have some standalone pages in my application. These live inside the public folder and directly call a bootstrap. In any case, they don't need any routing or controller logic but do rely on the View API for some of its features (view levels, layouts, main view, pick, etc).

Currently the call to `render($controllerName, $actionName, $params = [])` is tightly coupled to the router since the `$controllerName` and `$actionName` are mandatory. These should default to `null` and it might be a good idea to have the signature as `render($controllerName = null, $actionName = null, $params = [])` instead. This will decouple the view API and in my case, support a legitimate use-case scenario.
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
