### ISSUE TITLE
[NFR] Model find conditionally include or exclude related table

### ISSUE THREAD

**Issue by nghenglim** [phalcon/cphalcon#1746]
After reading the documentation on model at `http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model.html`, I've find that all related model will be included by default. I'm worrying about speed lost and resources it consume when scaling.

From other frameworks experience, will it be nice to do something like
    
    // fetches all related model
    $robot = Robots::findFirst(array("type = 'virtual'", "order" => "name"));
    
    //fetches only robotParts model
    $robot = Robots::findFirst(array("type = 'virtual'", "order" => "name","contain"=>array("robotParts")));

    // fetches no model
    $robot = Robots::findFirst(array("type = 'virtual'", "order" => "name","contain"=>array("")));

and is the source code inside `cphalcon-master\build\64bits\phalcon.c` ? Perhaps it will be more practical after looking on how findFirst function ( sadly still having trouble looking into the source code )

**Comment by andresgutierrez** [comment]
Duplicate of #1117
