### ISSUE TITLE
[Bug]Retrieve service with camelCase name from Volt

### ISSUE THREAD

**Issue by nexik** [phalcon/cphalcon#1760]
I set in my DI service sevice with camelCase name:

```
$di->set('formFormatter', 'formFormatter');
```

I cannot access it in the view, but if I change its name to formformatter (whole name in lower case) than volt will retrieve service with no problem.

Is this a bug or some sort of convention?

**Comment by SidRoberts** [comment]
@sergeyklay This is no longer a bug in the 2.0.x series.

**Comment by sergeyklay** [comment]
Yeah. I saw
