### ISSUE TITLE
[NFR] \Phalcon\Mvc\Model::columnMap() - Auto-map database columns that are not defined (like aliases)

### ISSUE THREAD

**Issue by tilleps** [phalcon/cphalcon#1780]
**Summary**

Adding columns to a database table causes exceptions if those added columns were not defined in \Phalcon\Mvc\Model::columnMap() prior.  This makes working with a live/production database difficult.  I feel that columnMap() should feel and act like column aliases.

**Database table schema:**
```
Product
    product_id
    product_key
    product_label
```

**Model**
```php
class Product extends \Phalcon\Mvc\Model
{
    public function columnMap()
    {
        return array(
            'product_id' => 'id',
            'product_key' => 'key',
            'product_label' => 'label',
        );
    }
}
```

**Issue: Adding a column to database table**
```
Product
    product_id
    product_key
    product_label
    product_description
```

**Results in:**
`Phalcon\Mvc\Model\Exception: Column "product_description" doesn't make part of the column map`

**New Feature Request**:
For database table columns that are not defined in `columnMap()`, could those columns automatically be added to the columnMap() (as if there was no column alias)?  

```php
class Product extends \Phalcon\Mvc\Model
{
    public function columnMap()
    {
        return array(
            'product_id' => 'id',
            'product_key' => 'key',
            'product_label' => 'label',

            // automatically add to columnMap()
            'product_description' => 'product_description',
        );
    }
}
```

***Suggested Solution***
In the following `\Phalcon\Mvc\Model` methods: `assign()`, `cloneResultMap()`, `cloneResultMapHyrdate()`, `setSnapshotData()`
```php
$key = array_key_exists($key, $columnMap) ? $columnMap : $key;
```

**Comment by timbrand** [comment]
Any progress on this?
Would also like to seen an option to prevent an exception on new columns. Would be nice if we have the chance to ignore or auto-map them.

**Comment by samijnih** [comment]
:+1: for all the recommandations, I have the same problem and it would be nice if it can escape unimplemented columns in the columnMap method

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.x branch (Phalcon 2.0.4), you have to change a global ORM setting to allow unexpected columns:

```php
\Phalcon\Mvc\Model::setup(['ignoreUnknownColumns' => true]);
```

**Comment by timbrand** [comment]
It seems that the "ignoreUnkownColumns" isn't working (anymore).
Or maybe it doesn't work when creating/saving an item. I've enabled the ignoreUnknownColumns, by code and by setting the php.ini setting. They are recognised, but seem to be ignored for saving the model.

**Comment by sergeyklay** [comment]
@timbrand Create please separated issue with small script to reproduce

**Comment by wajdijurry** [comment]
+1
