### ISSUE TITLE
->cookies->set() doesn't work everytime

### ISSUE THREAD

**Issue by ogarbe** [phalcon/cphalcon#1800]
Hello,

We've had a problem with ->cookies->set() for deletion.

Problem : 
We're having cookies on multiple sub domains with the same name

- name = XXX, domain = vpg.com
- name = XXX, domain = sub.vpg.com

```php
->cookies->delete('XXX');
```
won't delete both cookies
```php
->cookies->set('XXX',null, ..., 'vpg.com'); 
```
will delete the cookie 'sometimes'
```php
->cookies->set('XXX',null, ..., 'vpg.com'); 
->cookies->set('XXX',null, ..., 'sub.vpg.com'); 
```
will only delete one of both cookies...

We've had to use the regular php
```php
setcookie('XXX', null, ..., 'vpg.com'):
```
to manage a regular deletion of cookies.

I don't have a working test case as this pb seems random.

**Comment by imuneer** [comment]
I have the same issue with cookie. In my login I have set a remember me option. It never work unless I use php's native `setcookie` function. To trace this I manually created the testing as below.
`
        setcookie('b', 'bbb');
        echo $_COOKIE['b'];
        $expire = time() + 86400 * 8;
        $this->cookies->set('a', 'abc', $expire);
        die($this->cookies->get('a'));
`
It prints only 'bbb'

and in my browser inspection I can see only the cookie I set from php cookie.

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2.0?

**Comment by fl0pp** [comment]
I fixed it in earlier version by replacing
```
$this->cookies->delete('remember_user');
$this->cookies->delete('remember_account');
```
to
```
$this->cookies->get('remember_user')->delete();
$this->cookies->get('remember_account')->delete();
```

This also works in Phalcon 2.0.

Please add a correct way of doing this in the docs with an example (http://docs.phalconphp.com/en/latest/reference/cookies.html).

From API Indice (http://docs.phalconphp.com/en/latest/api/Phalcon_Http_Response_Cookies.html):
```
public boolean delete (unknown $name)
```

**Comment by khoan** [comment]
@fl0pp ```$this->cookies->get('remember_user')->delete();``` works!

**Comment by imuneer** [comment]
>
> @fl0pp <https://github.com/fl0pp>
> $this->cookies->get('remember_user')->delete(); works!


This is for deleting. How to use if I want to set?

>

**Comment by fl0pp** [comment]
I have setup the following in my servies.php:
```
$di->set('cookies', function() {
    $cookies = new Phalcon\Http\Response\Cookies();
    $cookies->useEncryption(true);
    return $cookies;
});
```

This is an example from my "SignIn"/"User"-controller:
```
$this->cookies->set('remember_user', $user->id, time() + $this->config->application->cookie_remember_timeout);
```
