### ISSUE TITLE
My application isn't loading JS collection from Assets Management

### ISSUE THREAD

**Issue by chiefGui** [phalcon/cphalcon#1817]
Hi there!
### Code

Look the following code:

**bootstrap.php**

``` php
    $di['assets']
            ->collection('headerCss')
            ->addCss('stylesheets/vendor/reseter.css')
            ->addCss('stylesheets/application.css');

    $di['assets']
            ->collection('application')
            ->addJs('js/vendor/jquery.js')
            ->addJs('js/vendor/sensitive.js')
            ->addJs('bower_components/angular/angular.min.js')
            ->addJs('js/core.js')
            ->addJs('js/controllers.js')
            ->addJs('js/responsive.js');
```
### Brief

As you can see, the second assets' collection is responsible for JS. But, when I call it in my view using Volt, I get a blank page without errors - even if I force them.

The funny thing is that the css' assets works very well.
### Observations
- Paths are correctly;
- If I let application's collection alone, without success too.

Suggestions?
##

**Comment by Jurigag** [comment]
Well, not enough info, similar code works for me without any problem.
