### ISSUE TITLE
PSR2 Compliance for Dispatcher

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#1832]
I have some test cases for my dispatcher which return mixed method names. Now that Phalcon is PSR-2 compliant, I am hoping these can be fixed:

```
// Class "Foo" exists in file "Foo.php"
$dispatcher->getControllerName(); // returns "foo"
```

However, if the route is added with the controller name explicitly set then the controller name is returned as defined:

```
$di['router']->add(..., ['controller' => 'Foo']);
$dispatcher->getControllerName(); // returns "Foo"
```

Similarly, for action names, the default name returns is PascalCase even if it is defined as camelCase as per PSR-2. Unless the action is explicitly spelt out in a route.

This has caused my test cases to be all over the place.
##

**Comment by sergeyklay** [comment]
+1

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
