### ISSUE TITLE
[NFR] [VOLT] Support for displaying "{{" and "}}" without hard manipulation with code

### ISSUE THREAD

**Issue by 3axap4eHko** [phalcon/cphalcon#1838]
Very difficult to use VOLT engine with different javascript template engines like handlebars or mustache and especially hard to use with angularJS. For example add construction like:

```
{% raw %}
Where {{ and }} will not be parsed by VOLT
{% endraw %}
```

or parse `-{` as `{` or some thing like this. It will be very useful feature.
##

**Comment by Jurigag** [comment]
Well it's not difiicult really. Just adding proper function and this is current solution without and hard code manipultion and i think it's fine right now.
