### ISSUE TITLE
Online Demo for XSS Testing In Different Contexts

### ISSUE THREAD

**Issue by soaj1664** [phalcon/cphalcon#1839]
Hi Guys!

Is there online demo page available from where I can test phalcon for XSS in different escaping contexts e.g., attribute, HTML, URL and CSS context? If not, would you guys please make it available?

e.g.,
HTML Purifier has a demo page: http://htmlpurifier.org/demo.php

&

htmLawed also has a test-bed for XSS testing: http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawedSafeModeTest.php
##

**Comment by Vaibs** [comment]
I didnt get, If looking to test for XSS then this may help http://www.iseebug.com/test-xss-online/

**Comment by sergeyklay** [comment]
I'm closing since this is a not a bug report. Feel free to discuss on the [official forums](https://forum.phalconphp.com), and/or the internals repo.
