### ISSUE TITLE
[NFR] Stand-alone object hydrators

### ISSUE THREAD

**Issue by moderndeveloperllc** [phalcon/cphalcon#1844]
Currently, hydrators are designed to work solely with models and result sets. I would very much like functions to help hydrate arrays or anything Traversable into objects. Similar functionality in in [ZF2](https://github.com/zendframework/zf2/tree/master/library/Zend/Stdlib/Hydrator). I'm asking because the majority of the data I'm dealing with is not pulled from a database, but from a json API. I would love to be able to convert this data from an array of arrays into an array of typed objects. The referenced ZF2 library has the ability to hydrate based off of setters in the object, or defined public properties for instance.
##

**Comment by andrefigueira** [comment]
+1

**Comment by livingdeadfr** [comment]
any solution ?

**Comment by dschissler** [comment]
Create a method on your class and iterate over it using `cloneResultMapHydrate` or `cloneResultMapHydrate`.

**Comment by sergeyklay** [comment]
Solution is simple with existing methods. I would like this more in Incubator somehow.  I want to close this issue because I don't want a bunch of these lying around.
