### ISSUE TITLE
[NFR] Community Widgets/Bundles/Modules/Packages

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#1845]
Most popular frameworks allow some standardized way of contributing individual modules and it works out really well for the community at large (code reuse; easy to make small contribution; faster to get off the ground). This isn't just limited to MVC frameworks (think jQuery, Node, Composer).

Some examples of plugin repositories:
- [Symfony](http://knpbundles.com/)
- [CodeIgniter](http://getsparks.org/)
- [Zend](http://modules.zendframework.com/)
- [YII](http://www.yiiframework.com/extensions/)
- [CakePHP](http://plugins.cakephp.org/)
- [WordPress](http://wordpress.org/plugins/)

I am not sure to what extent composer packages solves this. But if there were a base Widget class or interface to allow for standalone widgets that would be a good start. The class/interface could work with a convention to allow inclusion of JS/CSS/partials and have methods to render()

Some base widget class examples:

[Yii2](https://github.com/yiisoft/yii2/blob/71e4d408c9abf4f903023c41e1b927668ad9448c/docs/guide/view.md#widgets)
[Symfony2](http://symfony.com/doc/current/book/templating.html#embedding-controllers)
[Symfont1](http://www.symfony-project.org/api/1_4/sfWidget)

Implementing a widget class is fairly trivial but I suppose a well thought-out pattern and convention could benefit everyone.
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
