### ISSUE TITLE
Application events are not fired

### ISSUE THREAD

**Issue by Mech7** [phalcon/cphalcon#1851]
On phalcon 1.2.5

Mvc
http://docs.phalconphp.com/en/latest/reference/applications.html#application-events
beforeHandleRequest, afterHandleRequest never seem to be fired?

Micro
http://docs.phalconphp.com/en/latest/reference/micro.html#micro-application-events
Only beforeHandleRoute is fired?

**Comment by Green-Cat** [comment]
@Mech7 Can you check if you are still able to reproduce this on phalcon 2.0?
