### ISSUE TITLE
[NFR] Factory interface for service locator

### ISSUE THREAD

**Issue by cdekok** [phalcon/cphalcon#1855]
It would be nice if there was a factory interface which would set the di and try to create the service. (similiar to what ZF2 has)
Benefits would be make DI lighter if there are many services but only a few are used in the request and it would be easier to read if there are services which have many dependencies.

Example interface:

``` php
namespace Phalcon\Di;

interface FactoryInterface extends InjectionAwareInterface
{
   public function createService();
}
```

Example service

``` php
namespace MyModule\Post;

use Phalcon\Di\FactoryInterface;

class RepoFactory implements FactoryInterface
{
    public function createService()
    {
        $repo = new Repot();

        return $repo
            ->setDb($this->getDi()->get('db'));
    }
}
```

Example DI

``` php
use Phalcon\Di\FactoryDefault;

$di = new FactoryDefault();

$di->set('\MyModule\Post\Repo', '\MyModule\Post\RepoFactory');
$di->set('\Other', '\Other\Factory');
$di->set('\Etc', '\EtcFactory');
```

**Comment by sergeyklay** [comment]
We think that advancements in the DI have made this NFR irrelevant. Thank you for contributing.
