### ISSUE TITLE
View cache with memcache as backend is not using lifetime param

### ISSUE THREAD

**Issue by sindivinch** [phalcon/cphalcon#1856]
services.php

``` php
use Phalcon\Cache\Frontend\Output;
use Phalcon\Cache\Backend\Memcache;

$di->set('viewCache', function() use ($config) {  
    return new Memcache(
        new Output(['lifetime' => 10]),
        $config->memcache->toArray()
    );
});
```

In controller action I'm using this:

``` php
$this->view->cache([
    "key"      => $cacheName,
    "lifetime" => 14400,
]);
```

It should use `lifetime=14400`, but it uses `lifetime` param form frontend and it's equal **10** seconds. It's ignore 'service' param too. It is using only 'key' parameter.
I'm tested it with file backend cache and it woks fine!

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
