### ISSUE TITLE
Possible bug - updating column with integer value

### ISSUE THREAD

**Issue by calinrada** [phalcon/cphalcon#1881]
There is  a possible bug in 1.3.0 and 1.2.5/6 . When i try to update a record that has a column with integer value, the column is not updated. Example case:

``` php
foreach ($records as $record) {
    // ....
    $record->setStatus(1);
    $record->update()
}
```

The above will fail - the status column is not updated but the update() method return true. Also, enabling keepSnapshots, calling $record->getChangedFields() is returning an empty array.

Forcing the the value of status to string, the update() method will work as expected. So, this is working:

``` php
foreach ($records as $record) {
    // ....
    $record->setStatus('1');
    $record->update()
}
```
- Phalcon 1.3.0, 1.2.5, 1.2.6
- Linux 3.5.0-45-generic 
- PHP 5.5.7

**Comment by sergeyklay** [comment]
The 1.3.x branch is not longer supported. If there are bugs in the 3.2.x, we can follow up in separate issues.
