### ISSUE TITLE
\Phalcon\Db::FETCH_BOTH has value 2, the expected value for FETCH_ASSOC

### ISSUE THREAD

**Issue by corretge** [phalcon/cphalcon#1887]
When I execute fetch(\Phalcon\Db::FETCH_ASSOC) in a prepared statement, the result is an object.

Investigating I view that:

     var_dump(\Phalcon\Db::FETCH_ASSOC);   >   int(1)
     var_dump(\Phalcon\Db::FETCH_BOTH);   >   int(2)
     var_dump(\Phalcon\Db::FETCH_NUM);   >  int(3)
     var_dump(\Phalcon\Db::FETCH_OBJ);    >  int(4)

and executing fetch(number) I view that the result is as:

     0    >   FETCH_BOTH
     1    >   FETCH_OBJ     
     2    >   FETCH_ASSOC
     3    >   FETCH_NUM
     4    >   FETCH_BOTH

I'm in version 1.2.5 - 1020540

**Comment by andresgutierrez** [comment]
This was fixed in Phalcon 1.3.0
