### ISSUE TITLE
[BUG]  i'm try set 'shared_lock' option true, but not include statement.

### ISSUE THREAD

**Issue by iwai** [phalcon/cphalcon#1923]
In document http://docs.phalconphp.com/en/latest/reference/models.html#finding-records

i used 'shared_lock' option set true, but 'LOCK IN SHARE MODE' not include statement.

**Comment by ohmcoe** [comment]
+1 It same problem in 2.0.9

**Comment by sergeyklay** [comment]
Fixed in 2.0.x branch
