### ISSUE TITLE
View::getLayoutsDir method by default returns an empty string

### ISSUE THREAD

**Issue by ianbytchek** [phalcon/cphalcon#1930]
But if I do $view->setLayout('default') it finds and renders the correct layout in '/views/layouts/'. Logic on line [988](https://github.com/phalcon/cphalcon/blob/master/ext/mvc/view.c#L988) should move to constructor, so we have our default layout directory set out from the beginning and have it accessible via View::getLayoutsDir.

**Comment by sergeyklay** [comment]
I apologize for completely overlooking this. I hope this works well in the `3.2.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing, and again I am sorry about the delay.
