### ISSUE TITLE
$file->getRealType() and $file->getSize() not working? Phalcon 1.2.6

### ISSUE THREAD

**Issue by liesislukas** [phalcon/cphalcon#1931]
my code: 
foreach ($this->request->getUploadedFiles() as $file) {
   var_dump($file, $file->getName(), $file->getTempName(), $file->getType(), $file->getSize(), $file->getRealType());
}

example dump:

object(Phalcon\Http\Request\File)#82 (6) {
  ["_name":protected]=>
  string(11) "suspect.gif"
  ["_tmp":protected]=>
  string(14) "/tmp/phpUNwfs6"
  ["_size":protected]=>
  int(0)
  ["_type":protected]=>
  string(9) "image/gif"
  ["_error":protected]=>
  int(0)
  ["_key":protected]=>
  string(7) "files.2"
}
string(11) "suspect.gif"
string(14) "/tmp/phpUNwfs6"
string(9) "image/gif"
int(0)
NULL

the answer is is it normal, that getType gives type, getRealType - not and the size of the file is not available either?  after this i also use $file->moveTo() and it works fine, the file is uploaded and saved, but i still wonder about getRealType and getSize, are these functions buggy? Why size = 0 nad realtype = null? while type is correct

my phalcon version: 1.2.6

**Comment by TrogWarZ** [comment]
+1
Phalcon 1.3.4

Anybody has solution/workaround?

**Comment by stanislav-web** [comment]
Try to use my suggestion https://github.com/stanislav-web/phalcon-uploader

**Comment by Slasict** [comment]
Enable php_fileinfo.dll in your php.ini file.

**Comment by TrogWarZ** [comment]
@Slasict can you explain what is this?
Don't use any windows many years. Is this working for *nix too (e.g. ubuntu 12 LTS)?
I've already installed "libmagic1" but "locate fileinfo.so" (and even "locate fileinfo") cant' find anything.

**Comment by TrogWarZ** [comment]
@stanislav-web thans for workaround, maybe for someone it wold be helpful! But i need to use getRealType method with temporary files, read some info, process (e.g. images) and then upload them to another server.

**Comment by sergeyklay** [comment]
рьогюб

**Comment by ruudboon** [comment]
+1 for implementing this wuthoud php_fileinfo.dll
Phalcon 1.3.4

**Comment by andresgutierrez** [comment]
Can you please try again using Phalcon 2 or close this issue?

**Comment by TrogWarZ** [comment]
For me (ubuntu 12.04, php 5.6.8-1, Phalcon 2.0.x and master (2.0.1)) – not repeated, size and type seems good.

**Comment by Green-Cat** [comment]
@andresgutierrez @phalcon Fixed in 2.0
