### ISSUE TITLE
Odd view behavior with layouts + pick

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#1933]
I noticed some odd behavior with calling `setLayout()` and `pick()`.

```
1. $view->setLayout('fancy');
2. $view->pick('someview');
```

1. Turns out if I call `setLayout()` then `pick()` then the `setLayout()` gets ignored. If there is a default layout, that gets picked which is worse since the framework ignores user intent (line 1).

2. The work around right now is to call `pick(['view', 'layout'])`. This behavior is undocumented and I gleaned it by reading the C source. Is this undocumented because it's unsupported and liable to change or is this okay to use?

3. It would be nice to be able to fix this bug and leave out the undocumented array syntax since the code legibility is better and it allows full control to the user to compose views throughout the application lifecycle (set a main, a layout and a view at different stages of the app lifecycle).

**Comment by sergeyklay** [comment]
Fixed in `2.1.x` branch
