### ISSUE TITLE
Crash dumps with Volt alwaysRecompileView=TRUE

### ISSUE THREAD

**Issue by icex** [phalcon/cphalcon#1949]
Hi,

We're getting a lot of crash dumps. I've tried with cphalcon 1.2.5/1.2.6/1.3.0, it's the same issue. 
I think it's the 'alwaysRecompileView' => TRUE. With FALSE it works just fine. This happens when we stress the server with many concurent requests to check the performance. Probably a IO thing with writing files.

#0  lex_scan (zendlval=0x7fff8ec82bc8) at Zend/zend_language_scanner.c:1091
#1  0x0000000000734ef0 in zendlex (zendlval=0x7fff8ec82bc0) at /usr/local/src/php-5.5.7/Zend/zend_compile.c:6749
#2  0x000000000071d753 in zendparse () at /usr/local/src/php-5.5.7/Zend/zend_language_parser.c:3436
#3  0x0000000000729e15 in compile_file (file_handle=0x7fff8ec85190, type=<value optimized out>) at Zend/zend_language_scanner.l:588
#4  0x0000000000595391 in phar_compile_file (file_handle=0x7fff8ec85190, type=8) at /usr/local/src/php-5.5.7/ext/phar/phar.c:3383
#5  0x00007f2a531d4474 in xc_compile_file (h=0x7fff8ec85190, type=8) at /usr/local/src/xcache-3.1.0/mod_cacher/xc_cacher.c:2196
#6  0x00007f2a50cb07cc in phalcon_internal_require () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#7  0x00007f2a50d3729f in zim_Phalcon_Mvc_View_Engine_Volt_render () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#8  0x00007f2a50cbb6d0 in phalcon_call_method_vparams () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#9  0x00007f2a50cbbeb7 in phalcon_call_method_params () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#10 0x00007f2a50e0996d in zim_Phalcon_Mvc_View__engineRender () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#11 0x00007f2a50cbb6d0 in phalcon_call_method_vparams () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#12 0x00007f2a50cbbeb7 in phalcon_call_method_params () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#13 0x00007f2a50deac9b in zim_Phalcon_Mvc_View_render () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#14 0x00007f2a50cbb6d0 in phalcon_call_method_vparams () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#15 0x00007f2a50cbbeb7 in phalcon_call_method_params () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#16 0x00007f2a50d2a3a3 in zim_Phalcon_Mvc_Application_handle () from /usr/local/lib/php/extensions/no-debug-non-zts-20121212/phalcon.so
#17 0x00000000007d91c2 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /usr/local/src/php-5.5.7/Zend/zend_vm_execute.h:552
#18 0x00000000007ca9b0 in execute_ex (execute_data=0x7f2a61bff708) at /usr/local/src/php-5.5.7/Zend/zend_vm_execute.h:363
#19 0x0000000000756da9 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/src/php-5.5.7/Zend/zend.c:1320
#20 0x00000000006f8c19 in php_execute_script (primary_file=0x7fff8ec8a9e0) at /usr/local/src/php-5.5.7/main/main.c:2489
#21 0x000000000080f9b2 in main (argc=<value optimized out>, argv=<value optimized out>) at /usr/local/src/php-5.5.7/sapi/fpm/fpm/fpm_main.c:1933
(gdb)

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as 1.3.x is no longer supported

**Comment by tobispace** [comment]
We experienced the same issue, see:
https://forum.phalconphp.com/discussion/14869/php5fpm-on-nginx-crash-zendzendlanguagescannerc-no-such-file-or-
