### ISSUE TITLE
[NFR] file in phalcon's repository with current stable framework version

### ISSUE THREAD

**Issue by liesislukas** [phalcon/cphalcon#1963]
i would like to have a place, where i could always check if my installation is up-to-date. How can i do it automatically? I want to get email only when I'm out-of-date and recheck it once a week or month.

I think if you would add simple folder with version for different distros/Operating systems, developers could make curl request to this git file and check if their version is up-to-date or not. Number's format should be equal to what this method returns:

Phalcon\Version::get();
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
