### ISSUE TITLE
setFileToSend fails on large file download

### ISSUE THREAD

**Issue by konsultaner** [phalcon/cphalcon#1975]
I tryed to download a file of 1.5GB through the setFileToSend method of the response object. Which is quite handy to use. It caused this error:

``` PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1155588096 bytes) in ... ```

In respect of [this source](http://www.richnetapps.com/the-right-way-to-handle-file-downloads-in-php/) I think it would be necessary to let phalcon handle the download like this:

```php
set_time_limit(0);
$file = @fopen($file_path,"rb");
while(!feof($file))
{
	print(@fread($file, 1024*8));
	ob_flush();
	flush();
}
```

**Comment by Green-Cat** [comment]
@andresgutierrez Not a phalcon bug, it is a php issue.
