### ISSUE TITLE
Add $model->validationHasPassed

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#1995]
Currently most validation code looks like this:

```
public function validation()
{

    // ...

    if ($this->validationHasFailed() == true) {
        return false;
    }
}
```

While that can be shorted to `return !$this->validationHasFailed()` it would improve legibility if it were just written as `return $this->validationHasPassed()`.
##

**Comment by Jurigag** [comment]
Since validation in models in phalcon 3 was changed this can be closed.

**Comment by sergeyklay** [comment]
@Jurigag I agree with deprecation. Could you add `deprecated` tag in next commit?
