### ISSUE TITLE
\Assets\Collection should ignore duplicates

### ISSUE THREAD

**Issue by kolypto** [phalcon/cphalcon#2008]
[\Assets\Collection](http://docs.phalconphp.com/en/latest/api/Phalcon_Assets_Collection.html) should remove duplicate files paths: this will allow developers to include JS & CSS dependencies right inside their templates!

At least it needs to have a method that allows to eliminate duplicate sources.

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open new issue if the problem appears again. Thank you for contributing.
