### ISSUE TITLE
\Assets\Collection: Helpers for combining JS/CSS

### ISSUE THREAD

**Issue by kolypto** [phalcon/cphalcon#2009]
Most web projects need to serve their JS & CSS in a combined and, possibly, minified state. As this task is very common, Phalcon, being a mature framework, needs to support some automation out of the box.

The following steps should be taken:
- Each bundle of assets should be merged into a separate file
- Merged file name should depend on the input files and, in development mode, their contents
- No action should be taken if the output file already exists and is up to date.

As JS is part of the presentation, in comtempt of Phalcon documentation, developers will set JS & CSS links in templates. Thus, this kind of processing can't happen in any event handler: only in the template.

To solve the above, I had to extend `Manager`:

``` php
<?php namespace lib\Phalcon\Assets;

use \Phalcon\Assets;

class Manager extends Assets\Manager {
    # TODO: outputCssMin()

    function outputJsMin($collectionName = null){
        $options = $this->getOptions();
        $sourceBasePath = $options['sourceBasePath'];
        $targetBasePath = $options['targetBasePath'];
        $targetBaseUri = $options['targetBaseUri'];

        # Collection
        $collection = $collectionName
            ? $this->get($collectionName)
            : $this->getJs();

        # TODO: remove duplicates

        # Make up the output filename: md5(*filenames)
        $target_name = '';
        foreach ($collection as $js)
            $target_name .= $js->getPath();
        $target_name = md5($target_name).'.js';

        # Set up the collection so it combines & minifies
        $collection
            ->setTargetPath($target_name)
            ->setPrefix($targetBaseUri)
            ->setTargetUri($target_name)
            ->join(true)
            ->addFilter(new \Phalcon\Assets\Filters\Jsmin())
        ;

        # If output file exists, do not recompile it
        if (file_exists($collection->getTargetPath())){
            # Replace the collection with a single file: the generated one
            $col = new Assets\Collection();
            $col->addJs($collection->getTargetUri());
            $collection = $col; # this collection will be outputted instead
        }

        # Output
        return $this->output($collection, ["Phalcon\\Tag", "javascriptInclude"], "js");
    }
}
```

Provided all assets live in 'web/i/{js,css}', and the generated files go into '/web/assets/', the following initialization should be done:

``` php
<?php
$di->setShared('assets', function(){
    $assets = new \lib\Phalcon\Assets\Manager([
        'sourceBasePath' => 'web/',
        'targetBasePath' => 'web/assets/',
        'targetBaseUri' => 'assets/'  # new option for the generated files
    ]);
    $assets->collection('css')
        ->setSourcePath('i/css/')
        ->setPrefix('i/css/');
    $assets->collection('js')
        ->setSourcePath('i/js/')
        ->setPrefix('i/js/');
    return $assets;
});
```

I believe this should be a part of the framework, so one can use a one-liner to do all the above.

Some drawbacks:
- Does not currently allow to specify another filter class
- Lacks some flexibility
##

**Comment by arnoldbird** [comment]
I tend to think this should be part of the framework.  Initially, I thought the addCss method did this.  Took me a little while to figure out that all the addCss method does is add the tag to the head.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
