### ISSUE TITLE
Bug when Phalcon\Mvc\Model working table has `tinyint(1)` field type

### ISSUE THREAD

**Issue by temafey** [phalcon/cphalcon#2012]
When I try to save/update/create row, method returns true, method getMessages returns empty array, but row is not inserted/updated!
I run many different tests and found that if my mysql table has field with type 'tinyint(1)' I can't save/update/create row if this field value is integer, but if I change value integer to string everything is inserted/updated normally! (test configuration: Ubuntu 13.04, php 5.5.6, Mysql 5.5.35, phalcon 1.2.5,1.2.6)

Field with type 'tinyint(1)' Phalcon\Mvc\Model\MetaData return '8' type number (TYPE_BOOLEAN constant in Phalcon\Db\Column), but if I change field type to int(1), smallint(1) or tinyint(2) Metadata return '0' type number (TYPE_INTEGER constant in Phalcon\Db\Column)!

**Comment by andresgutierrez** [comment]
Fixed in 2.0.x
