### ISSUE TITLE
Volt: escaping Volt delimiters

### ISSUE THREAD

**Issue by kolypto** [phalcon/cphalcon#2031]
It's absolutely necessary to escape Volt tags, as some the developers may want to insert `{%` and `{{` into their templates. 

Some client-side template engines use `{{ }}` to output values. Example: [mustache](http://mustache.github.io/mustache.5.html), [AngularJS](http://docs.angularjs.org/tutorial/step_02)

Proposed syntax: `\{% ... %}`, `\{{ ... }}`

**Comment by andmm** [comment]
Was this ever added to volt? It's really necessary for javascript client side templates. I think laravel has an elegant solution, you can escape the template parser by putting a @ in front of the statement like this: 

<h1> @{{ javascript_var }}  </h1>

Much cleaner IMO.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/1253
