### ISSUE TITLE
Volt: ignore Volt delimiters in PHP code

### ISSUE THREAD

**Issue by kolypto** [phalcon/cphalcon#2032]
While trying to workaround #2031 (use AngularJS template in Volt), encountered another issue:

```php
<?php echo 1; ?>
```

is rendered to:

```html
1
```

correct.

---

```php
<?php echo '{{ var }}'; ?>
```

is rendered to

```php
<?php echo $var; ?>
```

whoops, `{{ ... }}` was processed by Volt even though it's enclosed with `<?php ... ?>`!

**Comment by andmm** [comment]
Is this solved yet? This is a must for any javascript frontend framework that uses {{ }} for templating

**Comment by Green-Cat** [comment]
@sergeyklay This is not resolved. Can be an issue with js frameworks like angular.

**Comment by bombless** [comment]
I was caught in similar scenario and I used something like
```php
<?php echo '\{\{ var \}\}'; ?>
```
to work  around it.

**Comment by andmm** [comment]
I like the way Laravel's Blade handle this, they just prepend an @ an the output is escaped.
