### ISSUE TITLE
Session will not start after installing Version 1.2.6

### ISSUE THREAD

**Issue by konsultaner** [phalcon/cphalcon#2033]
Yesterday I updated from Phalcon 1.2.1 to 1.2.6 and my session handler stopped working. After reinstalling the 1.2.1, it worked perfectly.

I use my own handler. That might be the problem:

```php
class SessionHandler extends SessionAdapter
{
    /** @var User */
    private static $userCache = null;

    public function someMethods(){
        ...
    }

    ...
}
```

I start my session like this, which will return a true, eventhough it doesn't work.

```php
self::$dependencyInjector->get('session')->start(); // true
```

I'm on a windows 7 with xampp 32bit ts

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2
