### ISSUE TITLE
[NFR] Phalcon\Mvc\Collection support for hint

### ISSUE THREAD

**Issue by omgnull** [phalcon/cphalcon#2043]
[Hint](http://docs.mongodb.org/manual/reference/operator/meta/hint/) support feature will be great to tell mongo which index to use.

``` php
Robots::find([
    'conditions' => [
        'material' => $plastic,
        'price'    => $price
    ],
    'sort' => [
        'price' => 1
    ],
    'hint' => [
        'price'    => 1
    ]
]);
```

Also it will be great to [explain](http://docs.mongodb.org/manual/reference/operator/meta/explain/) support.

``` php
Robots::find([
    'conditions' => [],
    'explain' => true
]);
```

Workaround example at the moment:

``` php
Robots::find([
    'conditions' => [
        '$query'   => [],
        '$hint'    => [
            '_id' => 1
        ],
        '$explain' => 1
    ]
]);
```
##

**Comment by Green-Cat** [comment]
The use of both $hint and $explain in queries is deprecated as of mongodb 3.0.
