### ISSUE TITLE
Uniformize Phalcon\Mvc\Model\Validator\ and Phalcon\Validation\Validator\

### ISSUE THREAD

**Issue by xavier-rodet** [phalcon/cphalcon#2050]
Hi,

I wanted to use the new "Between" Validator in my model validation, but it only exists for Phalcon\Validation\Validator\ !

I think this could be great to "uniformize" both ?

Here's the difference between both i just noticed:

Phalcon\Validation\Validator\  which 'Model' don't have:
+ Between
+ Confirmation
+ Identical

Phalcon\Mvc\Model\Validator\ witch 'Validation' don't have:
+ Numericality
+ Uniqueness
+ Url

These 6 Validators should available in both case don't you think ?

(API Indice: http://docs.phalconphp.com/en/latest/api/index.html)

Thanks

**Comment by salarmehr** [comment]
@mruz Has the issue solved in Phalcon 2?

**Comment by mruz** [comment]
No, there are still two different (but with the same behavior) validators.

**Comment by sergeyklay** [comment]
@naNuke  Besides that Email Validator has more holes. See #3227

**Comment by sergeyklay** [comment]
@xavier-rodet Some missed validators https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Mvc/Model/Validator

**Comment by salarmehr** [comment]
In a blog post @phalcon said he is want to unify them (standalone and model ) validator (perhaps  also coleection validators) in 2.0.4. He also introduces Entity super class.

**Comment by mruz** [comment]
This is planned in the 2.1 https://blog.phalconphp.com/post/phalcon-2-0-2-released

> Later on, we will be planning the features to include in Phalcon 2.1, for now:

>Complete deprecation of PHP 5.3
Unification of Phalcon\Mvc\Model\Validation and Phalcon\Validation

**Comment by salarmehr** [comment]
@mruz Oh, my bad.

**Comment by sergeyklay** [comment]
This is unified in 2.1.x
