### ISSUE TITLE
[NFR] Query builder for raw sql

### ISSUE THREAD

**Issue by hugoduraes** [phalcon/cphalcon#2052]
It would be nice to have a query builder for raw sql queries, similar to Zend_Db_Select:
http://framework.zend.com/manual/1.12/en/zend.db.select.html

This would be useful when you need to build select queries which rely on specific SQL extensions that aren’t supported by PHQL.

The syntax should be similar to the creation of queries using the Query Builder:
http://docs.phalconphp.com/en/latest/reference/phql.html#creating-queries-using-the-query-builder
##

**Comment by Samhayn** [comment]
Actually standard query builder ALMOST allows to build raw sql, it just wraps table's name with square brackets.

example:
$this->modelsManager->createBuilder()->from('table')->where('a = "a"')->limit(1)->getPhql()

result:

SELECT [table].* FROM [table] WHERE a = "a" LIMIT 1

**Comment by mohammadhzp** [comment]
+1

**Comment by salarmehr** [comment]
+1

**Comment by tmihalik** [comment]
+1

**Comment by Surt** [comment]
+1

**Comment by sergeyklay** [comment]
+1

**Comment by salarmehr** [comment]
Using Model class instead of table name give me the creeps.

**Comment by anettan** [comment]
This would be useful when you need to build select queries which rely on specific SQL extensions that aren’t supported by PHQL.?-Using Model class instead of,?,

**Comment by marianacapelo** [comment]
+1

**Comment by nejtr0n** [comment]
+1

**Comment by aleksandrzen** [comment]
+1

**Comment by mansoorriaaz** [comment]
+1

**Comment by andrew-demb** [comment]
+1

**Comment by gunelism** [comment]
1+

**Comment by dacgray** [comment]
1+

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
@hugoduraes and others,

How do you envision this to work i.e. what would the result be? Is it going to be an array just like `fetchAll` returns when running a pure PDO based query or will this return a Complex/Simple resultset object

Since this issue has the most votes I was thinking of taking a stab at it and tying it with the new ORM that we are building but also offering functionality for the current ORM.

**Comment by niden** [comment]
Implemented in https://github.com/phalcon/cphalcon/issues/14734
