### ISSUE TITLE
[NFR] Event improvements.

### ISSUE THREAD

**Issue by andersonamuller** [phalcon/cphalcon#2055]
- [ ] Create a EventInterface.

``` php
namespace MyProject;

class Event implements \Phalcon\Events\EventInterface 
{
    // Implement the methods
}
```
- [ ] Let the developer specify an event object to fire. This could be implemented in both or one of these ways:

1) Modify the `fire` method to add a new parameter.

``` php
$event = new \MyProject\Event();
$eventsManager->fire("my-component:afterSomeTask", $this, $extraData, false, $event);
```

2) Create a new method `trigger`.

``` php
$event = new \MyProject\Event();
$event->setSource($this);
$event->setCancelable(true);
$event->setData([
    'name' => 'TestData'
]);
$eventsManager->trigger("my-component:afterSomeTask", $event);
```
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
