### ISSUE TITLE
[BUG] DB adapters: port, where is it???

### ISSUE THREAD

**Issue by lantian** [phalcon/cphalcon#2117]
I don't know... sad this or funny story... but i had an issue with forgotten parameter 'port' for database connection, I have laughed of this (https://github.com/lantian/PhalconEye/issues/20). But now I can see that not only me forgot about that =)))))))). 

In documentation we can see such parameter http://phalcon-php-framework-documentation.readthedocs.org/en/latest/api/Phalcon_Db_Adapter_Pdo_Mysql.html . But it is not used!!!!

**Comment by RDelorier** [comment]
😡 localhost should not change the behavior zzzzz
