### ISSUE TITLE
[BUG] v1.3.0 ::findFirst() stopped working as a result of a recent commit

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#2118]
Hi,

It looks like last month has been rough on Phalcon branch 1.3.0.

My code has suddenly stopped working as a result of commit 7e54b69dcd4c32953c2856c8e92bd29781d4664e:

```php
Column 'id' doesn't belong to any of the selected models (2), when preparing: SELECT [App\User\Account].* FROM [App\User\Account] WHERE [id] = ?0 AND [record_status] = ?1 LIMIT 1
```

```php
$parameters = [
    'bind' => [
        0 => 114,
        1 => 1
    ],
    'conditions' => '[id] = ?0 AND [record_status] = ?1'
];
$model = App\User\Account::findFirst($parameters);
```

Thanks!

**Comment by Green-Cat** [comment]
@RenaudParis @temuri416 Could you try it under 2.0?

**Comment by temuri416** [comment]
@Green-Cat Why?

**Comment by Green-Cat** [comment]
@temuri416 Both components were rewritten while keeping the same outside api. 
So your code should work out of the box (with minor modifications at most) and the issue may have been resolved.

**Comment by temuri416** [comment]
That's good. But I'm not switching to Phalcon 2.0 just yet. I'll test when I get there.

**Comment by andresgutierrez** [comment]
Could you please check if this still happen in 2.0.x?

**Comment by temuri416** [comment]
2.0.x seems to work fine.

**Comment by andresgutierrez** [comment]
Thanks
