### ISSUE TITLE
[NFR] Microsoft SQL Server Support

### ISSUE THREAD

**Issue by chesney** [phalcon/cphalcon#2137]
It would be great to have MSSQL Server support.

eg.

'database' => array(
        'adapter'     => 'sqlsrv',
        ....

**Comment by chesney** [comment]
I hope this will still be considered.

**Comment by Green-Cat** [comment]
@andresgutierrez duplicate of #1184

**Comment by ruudboon** [comment]
+1

**Comment by Green-Cat** [comment]
@sergeyklay duplicate of #1184

**Comment by brunomdev** [comment]
+1
