### ISSUE TITLE
[BUG] Lost layout content when call Phalcon\Mvc\View->render

### ISSUE THREAD

**Issue by AlloVince** [phalcon/cphalcon#2160]
Hi Guys

I did a really simple view test as below:

File structures as below:

```
│  view_test.php
│
├─layouts
│      admin.phtml
│
└─views
    └─user
            index.phtml
```

test codes in view_test.php are

``` php
use Phalcon\Mvc\View;
error_reporting(E_ALL);
$view = new View();

$view->setLayoutsDir(__DIR__ . '/layouts/');
$view->setLayout('admin');
$view->setViewsDir(__DIR__ . '/views/');
echo $view->render('user', 'index', array(
    'title' => 'abc'
));
```

The output result only content the text in `views/user/index.phtml`, but no layout info and no exceptions.

Full test codes could be found in https://github.com/AlloVince/phalcon_bugs/tree/master/render_bug

I got that this issue maybe caused by layout folder is not a sub folder of views. test codes here could work : https://github.com/AlloVince/phalcon_bugs/tree/master/render_correct  

But I don't understand why it is necessary. Currently my project has multi modules, some modules need a sharing layout, but each module must have thier own view files. So I think this rule need change. I holp the view folder and the layout folder could be separated folders.

Looking forward for your response.

Best
##

**Comment by web777** [comment]
+1 
layout as sub-dir of viewsDir not usable for multi modules
