### ISSUE TITLE
[BUG] Volt: escape filtering broken in macros

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#2164]
I have defined a macro, and in that macro I am trying to escape a string like so:

```HTML
<input type = "hidden" class = "definition" value = "{{ Field.definition_string|escape_attr }}" />
```

Instead, though, the output contains:
`Fatal error: Using $this when not in object context`

The line in the compiled template that is generating this error:
```PHP
<input type = "hidden" class = "definition" value = "<?php echo $this->escaper->escapeHtmlAttr($Field->definition_string); ?>" />
```
This error does not occur when I use a filter such as `striptags` or `capitalize`.
This error also does not occur when I use the filter outside the macro.

I'm using v1.3.0 as it existed on February 18th.  I tried updating to the latest codebase, but Phalcon did not install itself properly.

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2.0.4 (2.0.x branch)
