### ISSUE TITLE
Query execute & perfomance

### ISSUE THREAD

**Issue by wojtek77** [phalcon/cphalcon#2175]
When this code is executed:
<pre>
$query = Models\Test::query();
$query->execute();
</pre>
is sent to the database query:
<pre>
SELECT IF(COUNT(*)>0, 1 , 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME`='test'
</pre>
which can in certain conditions worse the performance.

Here is an example:
http://wojtek77.pf-control.de/phalcon-slowly/
where:
<pre>SELECT IF(COUNT(*)>0, 1 , 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME`='test'</pre> took around 1000 ms
<pre>DESCRIBE `test`</pre> around 2 ms
<pre>SELECT `test`.`id`, `test`.`name` FROM `test`</pre> around 0.8 ms

I think that this SQL <pre>SELECT IF(COUNT(*)>0, 1 , 0) FROM `INFORMATION_SCHEMA`.`TABLES`...</pre> is unnecessary.

Now, to quote an email from the server administrator:

> after much debugging and taking Phalcon's internal Mysql logic apart (see http://wojtek77.pf-control.de/phalcon-slowly/ ) I have been able to pinpoint the exact cause of it's slowness: The PDO driver.

> Specifically this query is causing the misery: 

> `SELECT IF(COUNT(*)>0, 1 , 0) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='test'`

> In short it reads _all_ informations about _all_ tables from Mysql's pseudo-database information_scheme only to determine if the table exists. There are 2 major problems with that Phalcon-code:

> a) INFORMATION_SCHEME contains all informations about all tables of all customers. For obvious reasons you can only see your very own tables but it still has to walk through all of them. And with the current amount of databases that is a _HUGE_ amount of tables which takes some time...

> b) It does simply not need to execute that query. If it tries to fetch from the table and gets an error, then it already knows the table does not exist. Adding a big overhead on each and every Mysql query just for the sake of exactness shows a very poor performance analysis by either the PDO or Phalcon driver.

Can I disable the execution of SQL "SELECT IF(COUNT(*)>0, 1 , 0) FROM INFORMATION_SCHEMA.TABLES..."?

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2.0.0

**Comment by lutsifer** [comment]
I have Phalcon 2.0.8 and again before each query I can clearly see in slow log this:

`SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = 'teams' AND `TABLE_SCHEMA` = DATABASE();`

**Comment by Jurigag** [comment]
But you have modelsMetadata service in di registered ?

**Comment by lutsifer** [comment]
right...
`$di->set('modelsMetadata', function () {
    return new MetaDataAdapter();
});`

What is the best option to escape this constant mysql query?

**Comment by Jurigag** [comment]
Yes if this is apc/files/xcache adapter.

**Comment by lutsifer** [comment]
Oh I see :) Thank you!

**Comment by niboge** [comment]
u can add metaData function to oneModel  prevent from query mysql db
function metaData() {
     return ['id','name',''......];
}
