### ISSUE TITLE
[NFR] Volt Compiler - beforeCompile, afterCompile events

### ISSUE THREAD

**Issue by naNuke** [phalcon/cphalcon#2182]
Hello, I would like to request relatively simple feature (I think) and that is beforeCompile and afterCompile events for volt compiler.

View component atm supports beforeRender and afterRender events which can be called everytime a view file is being rendered.

The idea behind beforeCompile and afterCompile is to enable possibility of modifying the compiled view file before it is saved to hdd and not during every request like beforeRender and afterRender.

Thank you for considering this.
##

**Comment by niden** [comment]
This has been addressed. (took a while....)
