### ISSUE TITLE
\Phalcon\Mvc\Model to allow constructor parameters

### ISSUE THREAD

**Issue by hlegius** [phalcon/cphalcon#2186]
Hi, guys!
Would be nice if Phalcon adds a readable and transparent way to require/collect parameters on object construction like below:

```php
use Phalcon\Mvc\Model;

class Foo extends Model
{
    public function onConstruct($bar, $baz)
    {
        // do stuff with $bar and $baz
    }
}
```

"It prepares the new object for use, often accepting arguments that the constructor uses to set member variables required." - [Wikipedia](http://en.wikipedia.org/wiki/Constructor_%28object-oriented_programming%29)

**Comment by andresgutierrez** [comment]
Implemented in 2.1.x as follows:

```php
$robot = new Robots(array(
    'name' => 'hello'
    'type' => 'Mechanical'
));
$robot->save();
```

**Comment by marianacapelo** [comment]
@andresgutierrez 
This is cool. Still, I think it would be event better if we could pass the arguments in QueryBuilder.
I am now trying to dynamically set a source to a model, and I find it impossible to use it when working with QueryBuilder - and I need to use in to join the model. 
Is it a cool feature? 
For my project it would be really great :).

**Comment by lee-iweb** [comment]
@andresgutierrez
if we use find() or findFirst() to get data, it will call onConstruct method again without parameters, is this right?
such as ..
```
$robot->find();
or
$robot->findFirst();
```

some log in my local.
```
#0  App\Models\Robots->onConstruct(Array ([name] => hello,[type] => Mechanical))
#1  Phalcon\Mvc\Model->__construct(Array ([name] => hello,[type] => Mechanical)) called at [...]
#2  App\Models\BaseModel::getModel(Robots, Array ([name] => hello,[type] => Mechanical)) called at [...]
#3  App\Controllers\Test2Controller->tAction()
#4  Phalcon\Dispatcher->callActionMethod(App\Controllers\Test2Controller Object (...))
#5  Phalcon\Dispatcher->_dispatch()
#6  Phalcon\Dispatcher->dispatch()
#7  Phalcon\Mvc\Application->handle() called at [...]


#0 [internal function]: App\Models\Robots->onConstruct(NULL)
#1 [internal function]: Phalcon\Mvc\Model->__construct(NULL, Object(Phalcon\Di\FactoryDefault), Object(Phalcon\Mvc\Model\Manager))
#2 [internal function]: Phalcon\Mvc\Model\Manager->load('App\\Models\\Robots', true)
#3 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#4 [internal function]: Phalcon\Mvc\Model\Query->parse()
#5 [internal function]: Phalcon\Mvc\Model\Query->execute()
...
```
