### ISSUE TITLE
Model inheritance in Phalcon

### ISSUE THREAD

**Issue by lucaswxp** [phalcon/cphalcon#2194]
Hey guys.

I have a architectural problem with my phalcon application encapsulating my persistence logic correctly.

Basically I have a GenericUser model which every type of specific User must inherits from. So, if I was going to have a specific user like "Admin", I would like to have something like this:

```<?php
// ideally, the class GenericUser should be abstract, but that might not be the case for certain business rules

abstract class GenericUser extends \Phalcon\Mvc\Model {
   public $id;
   public $username;
   public $password;

   public function getSource(){ return 'generic_users'; } 
}

final class Admin extends GenericUser {
   public $id; // this "overwrite" the parents id
   public $generic_user_id; // the relationship between the generic_users table and de admins table
   public $roles;
   public $unique_field_only_admins_have; 

   public function getSource(){ return 'admins'; } 
}
```

So I can do something like this:
```
$user = new Admin;
$user->username = 'lucaswxp';
$user->password = 'pass';
$user->roles = 'add, update, exclude';
$user->save(); // saves in the generic_users table and already link to the admins table
````

Is something like this planned in Phalcon? That's a feature I would really enjoy using, and I think it makes our code much more object-oriented.

FYI: I have much more complex entities than the ones I demonstrated here.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
