### ISSUE TITLE
Model value difference between int(0) and null

### ISSUE THREAD

**Issue by naNuke** [phalcon/cphalcon#2200]
Hello, recently I have stumbled upon a problem when setting value to model. I am not quite sure if this is bug or not but it seems like weird behaviour to me. Just to note, my model is using dynamic update because it is quite large table and updating all fields is pointless in most cases.

Field is simple unsigned tinyint that allows null value. 
When setting value to int(0) while the value is null, it is completely ignored by Phalcon and not updated in database.
When setting value to string('0') while the value is null, it updates without problem.

Think it might be some type comparison issue in model possibly tied to dynamic update feature.

Thanks for checking this out.

**Comment by andresgutierrez** [comment]
This was fixed in Phalcon 2.0.1
