### ISSUE TITLE
[NFR] CSS pre-processor in Assets

### ISSUE THREAD

**Issue by konsultaner** [phalcon/cphalcon#2206]
To have something like [Sass](http://sass-lang.com/) or [less](http://lesscss.org/) integrated within phalcon would be awesome.

Developers that can write something like Phalcon and Zephir are definitly able to build a CSS extension too.

I would really love to see this feature in phalcon.
##

**Comment by liesislukas** [comment]
Phalcon could have some "default" Sass / less compiler built in and if you want, you could change it. 

If it's hard to maintain, there could be tutorial (at least links to tutorials) how to do this here: 

https://docs.phalconphp.com/en/latest/reference/assets.html

**Comment by Jurigag** [comment]
You can add sass/less pre processor using some filter. I think incubator could be place for built-in sass/less etc compilers.
