### ISSUE TITLE
Forwarding doesn't work in the finished dispatcher – is that for a debate?

### ISSUE THREAD

**Issue by ianbytchek** [phalcon/cphalcon#2226]
When forwarding in dispatcher that has finished dispatching the `dispatch` method will not be called (for the second time), but `_finished` will be reset to `false`, which will make dispatcher appear like it is still dispatching. This is fine when making a forward from controller / actions, but this becomes an issue when trying to "reuse" the dispatcher.

In my case I’m overriding the `dispatch` method and handle extra logic in there to forward to another controller / action when needed.
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
