### ISSUE TITLE
1.2.6: $this->getContent() returns nothing

### ISSUE THREAD

**Issue by ryanwalters** [phalcon/cphalcon#2243]
I have a very basic `.volt` page ([gist](https://gist.github.com/ryanwalters/9815568)).

You can see from the output that the rest of the volt markup is being rendered, with the exception of `{{ content() }}`.

I have this same code running on a Windows (Dev) machine, and a Linux (Prod) machine. While this works perfectly in Dev, it does not work in Prod.

Prod specs:
Linux 32-bit (Media Temple Grid)
PHP 5.3.27
Phalcon 1.2.6

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2.0.0?
