### ISSUE TITLE
Phalcon\Mvc\Model\Transaction\Failed::getRecordMessages

### ISSUE THREAD

**Issue by jbaez** [phalcon/cphalcon#2266]
Using phalcon v1.3.0 and PHP 5.5.

During a transaction if there is a validation error when saving one of the models, the
Failed transaction exception: `$e->getRecordMessages()` returns  a string, the same as `$e->getMessage()`, instead of an array of Phalcon\Mvc\Model\MessageInterface validation messages.
##

**Comment by sergeyklay** [comment]
The `1.3.x` branch is not longer supported.
