### ISSUE TITLE
[NFR] ORM fetch related Joins

### ISSUE THREAD

**Issue by jbaez** [phalcon/cphalcon#2268]
It would be nice to use PHQL to get a model and a related models pre-hydrated in the model (like in Doctrine Fetch Joins http://docs.doctrine-project.org/en/2.1/reference/dql-doctrine-query-language.html#joins)

At the moment with PHQL it is possible to do:

`SELECT user.*, cars.* FROM UserModel user JOIN CarModel cars ON user.id = cars.userId WHERE user.id = 1`

This would return a Complex ResultSet with Rows containing UserModel and CarModel.
It would be great to return a single UserModel  with the cars already pre-hydrated in it so when accessing the cars `$user->cars` there is no need to run another Select query.
##

**Comment by sszdh** [comment]
+1

**Comment by Green-Cat** [comment]
+1

**Comment by tmihalik** [comment]
+1

**Comment by galki** [comment]
+1
