### ISSUE TITLE
[BUG] Debug page broken on HTTPS

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#2271]
This is basically a re-issuing of #987 because the problem is back.

When viewing a page via https that has a debug message, all the resources (CSS/JS) are blocked.  The certificate doesn't identify itself as static.phalconphp.com, and even if you bypass that, the file doesn't exist anyway.

I don't think it should be too difficult to simply add a certificate to the phalconphp.com server. This is basically breaking the built-in debugger for anyone who develops on an https host. Yes, it will cost a little more, but that's the price the organization has to pay for choosing to host files.  If you don't want to maintain the service, just include the CSS & javascript code in the generated page, rather than having the browser get it from static.phalconphp.com

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2.0.3
