### ISSUE TITLE
CSRF token bug

### ISSUE THREAD

**Issue by ongley** [phalcon/cphalcon#2279]
First time calling $this->security->getToken() generates values that are not equal to $PHALCON/CSRF/KEY$ and $PHALCON/CSRF$ that are stored in session.

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as 1.3.x is no longer supported

**Comment by rudiservo** [comment]
@sergeyklay Probably the same issue with double browser request. to close maybe?
