### ISSUE TITLE
Connecting to Oracle

### ISSUE THREAD

**Issue by leandroafonso** [phalcon/cphalcon#2287]
when I try run this code bellow on controller, its fine! returns data from database:

>         $test = new Phalcon\Db\Adapter\Pdo\Oracle(array(
>             'adapter'     => 'Oracle',
>             'username'    => 'SAAS',
>             'password'    => 'saas',
>             'dbname'      => '//192.168.120.27/XE',
>             'schema' => 'SAAS'
>         ));
>         $rs=$test->query("select * from USERS");
>         print_r($rs->fetchAll());
        
**It's ok! returns data from oracle DB.**

**When I run this code below, hoping to use the connection as defined in config.:**
> 
>   $user = new Users();
> 
>         $user->name = 'leandro';
>         $user->email = 'leandro@leandroafonso.com';
>         $user->id = 1;
>         $user->save();
>         print_r($user);
> 		die;

**My database config session:**

>     'database' => array(
>         'adapter'     => 'Oracle',
>         'username'    => 'TEKNISA_SAAS',
>         'password'    => 'teknisa',
>         'host'        => '192.168.120.27',
>         'dbname'      => 'XE',
>         'schema'      => 'TEKNISA_SAAS'
>     ),
> **

**Dont works! :-(**

Returns error:

SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it. (translated from portuguese)

I believe this is a bug in the config class because even defining an Oracle adapter is being instantiated the Mysql adapter. 

I commented to the config database session and created the adapter instance in the oracle bootstrap and set the oracle adapter in di as follows and it worked perfectly.

> 
$config = array(

>         "dbname" => "//192.168.120.27/XE",
>         "username" => "SAAS",
>         "password" => "saas"
>     );
>     $connection = new Phalcon\Db\Adapter\Pdo\Oracle($config);
>     $di->set('db',$connection);

**Comment by sergeyklay** [comment]
Phalcon does not support Oracle. Refer to #12008
