### ISSUE TITLE
[NFR] Volt v2.0 should change its default interpolater pattern for out of box Angular integration and allow for each to be change in configuration

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#2290]
In Volt the "{{" pattern clashes with Angular.  While Angular does provide a way to set its pattern to something I would like to instead switch it with Volt.  I think that Angular is going to be numerous times larger of a project as Phalcon and I think that that ultimately it would be better if Volt was by default setup to integrate with Angular.  I think that Phalcon v2 Volt should change its defaults and in the migration guide it could show to set it to the current behaviour with two additional lines with one for each pattern.

**Comment by qrazi** [comment]
Some other further reference (without me knowing all the implementation differences between Volt and Twig): Twig does support changing the delmiter: http://twig.sensiolabs.org/doc/recipes.html#customizing-the-syntax as does the original Jinja-template engine.
