### ISSUE TITLE
How to integrate javascript to .volt template engine

### ISSUE THREAD

**Issue by piavgh** [phalcon/cphalcon#2292]
I need to use http://blueimp.github.io/jQuery-File-Upload/ in my project which use framework PhalconPHP

In order to do so, my .volt file need to contain a javascript code like this

```
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %} //The problem begin here, with javascript code
 <tr class="template-upload fade">
  <td>
  <span class="preview"></span>
    ........//Some similar code here
  </td>
 </tr>
{% } %} //problem here too
</script>
```

But the problem is {% and %} is .volt template syntax. When I use `{% for (var i=0, file; file=o.files[i]; i++) { %}` like that, the .volt syntax and javascript syntax are conflict. Browser such as Chrome or Firefox will show the error : "Syntax error, unexpected token ( in /var/www/.... on line 77" where 77 is that line start with {%

In .phtml it works fine, but I don't want to rebuild my whole view template with .phtml How can I use this code with .volt? Is there other syntax for javascript which is different from {% and %} ? If not, I think this should be a necessary feature. Thank you!
##

**Comment by romanlex** [comment]
How I can fix this trouble( I have js template( Maybe I can include file to volt template without parse?

**Comment by Siteograf** [comment]
{{ "{{#each sales}}" }} ...

**Comment by dschissler** [comment]
I think that what you are asking for is the ability to escape Volt control characters.

**Comment by dschissler** [comment]
Related to #9966.  Volt needs better escaping options.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/cphalcon/issues/2292
