### ISSUE TITLE
save() fails to update (silently) when a related object is loaded

### ISSUE THREAD

**Issue by hlasso** [phalcon/cphalcon#2302]
When updating a related object we have found that first accesing the related object's attributes does not allow to update the relation.

We have a couple of classes:

```
class Contact extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
        $this->belongsTo('email_id', 'Email', 'id', ['alias' => 'Email']);
    }
}

class Email extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
        $this->hasMany('id', 'Contact', 'email_id', ['alias' => 'Contacts']);
    }
}
```

If we have valid contact and want to replace the email related object with a new object the system works:

```
$str = 'email@somewhere.com'; // New address
$contact = Contact::findFirst(123); // 123 is a valid ID
$newemail = new Email();
$newemail->emailaddress = $str;
$contact->email = $newemail;
$contact->save();
```

However, if we first validate that we are not updating to the same email...

```
$str = 'email@somewhere.com'; // New address
$contact = Contact::findFirst(123); // 123 is a valid ID
if ($contact->email->emailaddress != $str) {
    $newemail = new Email();
    $newemail->emailaddress = $str;
    $contact->email = $newemail;
    $contact->save();
}
```

This in fact does not work... SAVE() is called, the new Email object (and record) is created... but Contact's relation to email is not updated to reflect the change.

We started a thread a few months ago on Stackoverflow, but until today we were able to replicate the issue and found a workaround.
http://stackoverflow.com/questions/18346569/phalconphp-framework-how-to-update-a-model-object-and-the-related-object

I don't know if this is a bug, an undocumented feature or an expected outcome, so decided to report it.
##

**Comment by sergeyklay** [comment]
@dreamsxin Any news?

**Comment by dreamsxin** [comment]
@sergeyklay
It should be closed.
