### ISSUE TITLE
findFirst / findFirstBy... can give potentially unintended result

### ISSUE THREAD

**Issue by oh-ren** [phalcon/cphalcon#2312]
In my opinion findFirst() and findFirstBy...() are potentially dangerous to use.

e.g. when I pass <code>true</code>, <code>false</code> or <code>null</code>, or an arbitrary array findFirst will execute a query without a WHERE clause, thus returning the first row found.
I would expect it to return false, or perhaps raise an error or something.

FindFirstBy..() works a bit 'better':

<pre>
false: WHERE xxx = ''
true:  WHERE xxx = '1'
null:  WHERE xxx = NULL
</pre>

I think these functions need some input checking?
It's potentially dangerous, e.g. when you're finding a user by id via variable.
This forces me to double-check the data I pass to these functions (in sensitive places).

Btw; TRUE === 1 and FALSE === 0 in MySQL, but I believe the application layer should protect for such mistakes / unintended use.
##

**Comment by berliner** [comment]
I have run into the same issue and would like to back this up. I'm using phalcon 2.0.1.
I would the findFirst or findFirstBy* methods to return either NULL or FALSE in case an argument is given that can't be evaluated. It happens for example if you pass in an empty variable. It certainly feels like a bug to return the first row of the model table in that case.

**Comment by oh-ren** [comment]
Verified, is still an actual bug/feature as of v2.0.8

**Comment by jeiel** [comment]
I have the version 2.08 and have the same problem to generate a CRUD with webtools

**Comment by sergeyklay** [comment]
All Webtools  related issues should be [published here](https://github.com/phalcon/phalcon-devtools/issues)

**Comment by jeiel** [comment]
Thanks at this time I review

**Comment by dschissler** [comment]
Is the behavior still the same in Phalcon 3.*?

**Comment by Jurigag** [comment]
Most likely yes.

**Comment by niden** [comment]
This is actually not a bug. The responsibility of sanitizing input is on the developer and the code not necessarily on the framework. Yes the framework does have sanitizing features but whatever `find`/`findFirst` needs to be controlled by the developer.
