### ISSUE TITLE
Phalcon\Http\Cookie->delete() not working when session.cookie_domain is set

### ISSUE THREAD

**Issue by CoDanny** [phalcon/cphalcon#2329]
I'm using cookies that should be valid for subdomain and therefore set 
```ini
session.cookie_domain = .mydomain.com
```

when I call `Phalcon\Http\Cookie->delete()` the cookies don't get deleted. 
```php
$this->cookies->get('MyCookie')->delete();
```
I've had to result to this php code to have them deleted:
```php
setcookie('MyCookie', null, -1, '/', ini_get('session.cookie_domain'));
```
I'm using v1.3.1

**Comment by benfavre** [comment]
My auth system login/logout was working prior to me setting domain and httponly.
The only way to get the cookie to delete was to set negative expire time.
thanks @j3l3v 

Needs fixing

**Comment by addinm** [comment]
Any update?

**Comment by sergeyklay** [comment]
@addinm The `1.3.x` branch is not longer supported. Could you please try `3.2.x`.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/2329

**Comment by sergeyklay** [comment]
Closing in favor of #13052.
