### ISSUE TITLE
Add support to use default namespace in Phalcon\Mvc\Router\Annotations::addResource

### ISSUE THREAD

**Issue by baryshev** [phalcon/cphalcon#2350]
Default namespace defined by `Phalcon\Mvc\Router::setDefaultNamespace` is ignored in `Phalcon\Mvc\Router\Annotations::addResource`.

```
$router = new \Phalcon\Mvc\Router\Annotations(false);
$router->setDefaultNamespace('MyApp\Controllers');
// Expected: add resource MyApp\Controllers\IndexController
$router->addResource('Index', '/'); // This is not working. Phalcon don't use previously defined default namespace
$router->setDefaultController('Index'); // But this is works fine.
```

I think this behaviour of semantic similar methods is unexpected.
But we still need the possibility to add resource from not default namespace by passing full class name include namespace.

**Comment by Green-Cat** [comment]
@sergeyklay I fixed this in 2.1.x (PR #11276).
