### ISSUE TITLE
Volt extends block

### ISSUE THREAD

**Issue by ayak7** [phalcon/cphalcon#2355]
Version: 1.3.1

Parent template(parent.volt):
<pre>
{% block test1 %}{% endblock %}
</pre>

Child template (p.volt):
<pre>
{% include "parent.volt" %}
{% block test2 %}{% endblock %}
</pre>

Child template:
<pre>
{% extends "p.volt" %}

{% block test1 %}
 Test1
{% endblock %}

{% block test2 %}
  Test2
{% endblock %}
</pre>

Result:

<pre>
Test2
</pre>

Test1????

**Comment by Green-Cat** [comment]
@andresgutierrez Not a bug.
