### ISSUE TITLE
Latest Phalcon 1.3.2 crashes Vokuro sample app

### ISSUE THREAD

**Issue by temuri416** [phalcon/cphalcon#2356]
Hi,

1. I've compiled 1.3.2 latest
2. I've installed Vokuro sample app, configured DB access.

I'm seeing this in `/var/log/kern.log`:
```php
Apr 16 14:47:05 kernel: [3757822.534200] traps: php-fpm[8807] trap invalid opcode ip:7ffa4420d3b8 sp:7fff87c00c70 error:0 in phalcon.so[7ffa440a8000+28e000]
```

Line that's crashing it: https://github.com/phalcon/vokuro/blob/master/app/config/loader.php#L7

I'm on php5.5.7/php-fpm/nginx/Ubuntu 13.10. Compiled with `./install`.

Thanks!

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as Phalcon 1.3.x is no longer supported

**Comment by temuri416** [comment]
Not using Phalcon 2. Closing the issue.
