### ISSUE TITLE
Calling create on Model with composite primary key - with other fields

### ISSUE THREAD

**Issue by skintagain** [phalcon/cphalcon#2361]
I have the following table structure:

Table A
id

Table B
id

Table C
id

AhasB
_a-id_
_b-id_
c-id

a-id and b-id are a composite primary key
c-id is a foreign key

If I create a new AhasB model and set new values for each column and then call Model->create() I get some unexpected behaviour:

If the row already exists Phalcon runs the following SQL:
```sql
SELECT COUNT(*) "rowcount" FROM `AhasB` WHERE `a-id` = '1' AND `b-id` = '1';
UPDATE `AhasB` SET `c-id` = '1' WHERE `a-id` = '1' AND `b-id` = '1';
```
If the row doesn't exist:
SELECT COUNT(*) "rowcount" FROM `AhasB` WHERE `a-id` = '1' AND `b-id` = '1';
INSERT INTO `AhasB` (`a-id`, `b-id`, `c-id`) VALUES ('1', '1', '1');

Whilst I understand why the above happens (with the PK needed to guarantee uniqueness and the fact that c-id could have changed) the execution of a create() on a row that already exists needs to be flagged in some way. 

Thanks

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
