### ISSUE TITLE
Why does `Phalcon\Mvc\View\EngineInterface` contain `__construct` definition?

### ISSUE THREAD

**Issue by ianbytchek** [phalcon/cphalcon#2363]
That's counter productive. If it needs to extend another interface it should do so. Constructor does not define any interface-specific functionality and in my case comes as an obstruction as I don't want it to receive the `$dependencyInjector` argument.

**Comment by andresgutierrez** [comment]
Fixed in the 2.0.x branch (Phalcon 2.0.4)
