### ISSUE TITLE
stylesheet_link and LESS

### ISSUE THREAD

**Issue by rhodrykorb** [phalcon/cphalcon#2371]
Using LESS with stylesheet_link in app\views\index.volt

`{{ stylesheet_link(["href": "themes/default/less/default.less", "type": "text/css", rel="stylesheet/less"]) }}`

Which matches the suggestion from the Forum http://forum.phalconphp.com/discussion/417/how-to-use-stylesheet-link-for-a-less-file-

However this breaks in the browser and does not appear to work correctly. The output in the browser is:

`<link rel="stylesheet" href="themes/default/less/default.less" type="text/css" rel="stylesheet/less" />`

LESS does not work when `rel="stylesheet"` is present.

Order of stylesheet_link does not seem to make a difference.
##

**Comment by Jurigag** [comment]
It was merged so i guess we can close this.
