### ISSUE TITLE
[Security] Fatal error while trying to get not encrypted cookie

### ISSUE THREAD

**Issue by baryshev** [phalcon/cphalcon#2372]
If we are trying to get not encrypted cookie with enabled (by default) cookie encryption we got two bad scenarios:

1. If cookie have small length we got `Fatal error: Size of IV is larger than text to decrypt in ...`. This behaviour gets the way to down our site with any XSS for all affected users by changing his cookies.
2. If cookie have long length we got binary trash as result of `Phalcon\Http\Response\Cookies::get`. This is not such critical as first, but also dangerous scenario.

I think we need this behaviour:

1. If cookie can't be decrypted `Phalcon\Http\Response\Cookies::get` will result `null`.
2. Maybe `Phalcon\Http\Response\Cookies::has` will result `false`? Not sure about that.
3. Maybe we need silently delete broken cookies to prevent extra work on deciphering? This behaviour can be configured via settings.
 
Phalcon: 1.3.2 (compiled from ext)
MacOS: 10.9.2
PHP: 5.5.11

**Comment by Knallcharge** [comment]
+1

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2.0.0?
