### ISSUE TITLE
PHQL placeholders doesn't work with bitwise operators

### ISSUE THREAD

**Issue by baryshev** [phalcon/cphalcon#2373]
`$this->modelsManager->executeQuery('UPDATE Users SET flags = flags | :flag:', ['flag' => 2]);` throws `PDOException` with message `SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters`.

`$this->modelsManager->executeQuery('UPDATE Users SET flags = flags | 2');` - works fine.
##

**Comment by sheaujye** [comment]
Bump into this issue, any plan to have it fixed? it's been 2 years.
