### ISSUE TITLE
skipAttributesOnCreate does not support column maps

### ISSUE THREAD

**Issue by parhamdoustdar** [phalcon/cphalcon#2374]
Here is an example:

``` php
class People extends Model
{

    public $id;

    public function columnMap()
    {
        return ['id' => 'theId'];
    }

    private function initialize()
    {
        $this->skipAttributesOnCreate(['theId']);
    }
}
```
##

**Comment by Jurigag** [comment]
But columnMap is for having different column names in database than fields in class. skipAttributes is just checking field names.

**Comment by dschissler** [comment]
@Jurigag @sergeyklay If a column map is used then the new aliases names should be able to be used in all parts of the model.  So how is it currently being done in Phalcon 3.  If this is still not doing it then it definitely needs to be changed in Phalcon 4 and so it should be put on the milestone.

Its looking like Phalcon 4 needs to do a lot of small breakage to have a more consistent problem.  In particular I remember having lots of problems with anything to do with mapping in all parts of the system.  Its difficult to run all code paths through the mapping routines at the correct time and we need to do better.

**Comment by Jurigag** [comment]
Yea for phalcon 4 i think it's good idea to change this to use columnMap actually.

**Comment by niden** [comment]
https://github.com/phalcon/cphalcon/pull/13692
