### ISSUE TITLE
Bug in getSequenceName()

### ISSUE THREAD

**Issue by netoec84** [phalcon/cphalcon#2376]
When define the getSequenceName like:

    public function getSequenceName() {
        return 'table_name_Id_seq';
    }

Phalcon aparently change the value from "table_name_Id_seq" to "table_name_id_seq" so in PostgreSQL it produce an erro like:

SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "table_name_id_seq" does not exist

PostgreSQL is case sensitive with names of columns and tables.

**Comment by jeiel** [comment]
also it works in Oracle
