### ISSUE TITLE
Dispatcher forwarding does not call initialize() on Controller

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#2381]
The documentation states that the `initialize()` method of a controller is called before any action on that controller is executed. Consequently, if I forward to a controller action:

```
$dispatcher->forward(array('controller'=>'foo', 'action' => 'bar'));
```

The method `Foo::initialize()` should be called before `barAction()` but this is not the case.

**Comment by aleemb** [comment]
+1 Any possibility of fixing this?

**Comment by andresgutierrez** [comment]
I can't reproduce this, if the controller was initialized before the forward initialize is called, but initialize is called once per request per controller.

**Comment by aleemb** [comment]
It's been a year since but the scenario is:

```
FooController {
  barAction() {
     $dispatcher->forward(array('controller'=>'Qiz', 'action' => 'qux'));
  }
}

QizController {
  initialize() {
    die('I do NOT get called!');
  }
}
```

**Comment by aleemb** [comment]
I verified and indeed this bug still exists.

**Comment by phalcon** [comment]
Can you point me where in the documentation says that?

**Comment by aleemb** [comment]
@phalcon,

> Phalcon\Mvc\Controller offers the initialize method, which is executed first, before any action is executed on a controller. The use of the “__construct” method is not recommended.

But I am sure you already knew that, not sure :( Either way, now the initialise is called even on forward() so this issue is obsolete.

**Comment by sszdh** [comment]
initialize() method is called once per request per controller in dispatching loop.

I think forwarded action is in same dispatch loop.
