### ISSUE TITLE
ComplexResultset array access does multiple queries

### ISSUE THREAD

**Issue by mrjameshamilton** [phalcon/cphalcon#2391]
I ran a PHQL query like the following and attempted to access the result via the ArrayAccess interface. Each array access executes the query again - in the example code the query would be executed 3 times. It does not happening with the Iterator interface (i.e. ```foreach ($result as $row)...```).

```php
$phql = "SELECT t1.*, t2.* FROM table1 t1 INNER JOIN table2 t2 ON t1.id = t2.id WHERE t1.userId = :userId:";
$query = new Query($phql, $this->getDI());
$result = $query->execute(['userId' => 1]);

$result[0]['t1'];
$result[1]['t1'];
```

I'm using PHP 5.5 and Phalcon 1.3.1.

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.2
