### ISSUE TITLE
[Bug] - \Session\Adapter\Files crashes apache

### ISSUE THREAD

**Issue by nazwa** [phalcon/cphalcon#2398]
Seems like there is a problem with the default session adapter. 
Apache crashes completely when creating an instance of \Session\Adapter\Files.

As always, works totally fine with Phalcon 1.2.6

```php

<?php     

// test.php

  $session = new \Phalcon\Session\Adapter\Files(); // <---- This is what causes problems
  $session->start();
  
  var_dump($session->getOptions());             
  
?>
```
Win 8.1 Pro
Apache 2.4.7
PHP 5.4.22
Phalcon 1.3.1

**//Edit**
The same seems to be happening with using Database adapter from Incubator. Could it be a generic issue with the Adapter base class?

**//Edit 2**
IIS 7.5 with PHP 5.5.12 is fine
Aache 2.4.7 with PHP 5.5.8 is fine

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.x
