### ISSUE TITLE
[BUG] Redirect not sending correct http header

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#2399]
I try to redirect when access is not allowed.
When I do something like this.

```php
$this->response->redirect('auth/login/', false, 403)->sendHeaders();
```

I'm expecting this.
```
HTTP/1.1 403 Restricted Content
Location:/auth/login/
Status:403 Redirect
```

I get the following headers back.
```
HTTP/1.1 302 Found
Location:/auth/login/
Status:403 Redirect
```

Running Phalcon 1.3.1

**Comment by ajsooter** [comment]
I am experiencing this as well. Any update?

**Comment by sergeyklay** [comment]
Firstly read please documentation related to the redirection status codes

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection

**Comment by ruudboon** [comment]
@sergeyklay thnx. Will dive into this, didn't know that redirecting after 403 is not allowed. Will change my implementation.
