### ISSUE TITLE
[BUG] Controller method beforeExecuteRoute and Initialize problem

### ISSUE THREAD

**Issue by jimjim2a** [phalcon/cphalcon#2413]
Hello people,

I think I found an issue in the dispatch process. Here is my code :

```php
<?php
class MyController extends \Phalcon\Mvc\Controller
{
    public function beforeExecuteRoute($dispatcher)
    {
        if (!mytest()) {
           $dispatcher->forward(array("action" => "action2"));
           return false;
       }
    }
    public function initialize()
    {
         echo "Initialized !";
    }

    public function action1Action()
    {
         echo "Action 1 !";
    }

    public function action2Action()
    {
         echo "Action 2 !!";
    }
}
```

I'm attempting to go to action1, but for some reason I have to perform some test in my beforeExecuteRoute method in my controller.

In some case, I need to dispatch to another action in the <b>SAME</b> controller, and in that special case, the initialize method is not fired (because "<b>beforeExecuteRoute</b>" is called before "<b>initialize</b>").

In the doc it is said that the initialize method is called once per request, which is fine, but If i forward to another method in the same controller before "<b>initialize</b>", it has to be perform after the forward.

The output will be :

"Action 2 !!"

Where it should be :

"Initialized !"
"Action 2 !!"

Thanks guys !

**Comment by Green-Cat** [comment]
@andresgutierrez Fixed in 2.0
