### ISSUE TITLE
Phalcon generates invalid query for UniqueNess validator on MySQL

### ISSUE THREAD

**Issue by skintagain** [phalcon/cphalcon#2416]
When using the UniqueNess validator on a MySQL server, Phalcon creates an invalid query to find matching records:

Code in model:
```php
public function validation() {
      $this->validate(new Uniqueness(array(
          'field' => 'c',
      )));
      if ($this->validationHasFailed() == true) {
           return false;
      }
}
```

The model in question has a composite primary key across columns a and b but column c is also unique.

Looking at the mysql logs the query generated is as follows:
```sql
SELECT COUNT( * ) AS  `rowcount` 
FROM  `tablename` 
WHERE  `tablename`.`c` =  'foobar'
AND  `tablename`.`a` <> NULL 
AND  `tablename`.`b` <> NULL
```
This query always results in a result of 0 as MySQL should use:
```sql
SELECT COUNT( * ) AS  `rowcount` 
FROM  `tablename` 
WHERE  `tablename`.`c` =  'foobar'
AND  `tablename`.`a` IS NOT NULL 
AND  `tablename`.`b` IS NOT NULL
```

Thanks for all your work!

**Comment by andresgutierrez** [comment]
This is strange because Phalcon does not use literals like that. They look like:

```php
SELECT COUNT(*) AS `rowcount` FROM `robots` WHERE `robots`.`name` = :0 AND `robots`.`id` <> :1
```

**Comment by andresgutierrez** [comment]
@skintagain ping

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
