### ISSUE TITLE
[NFR] Form getValues

### ISSUE THREAD

**Issue by cdekok** [phalcon/cphalcon#2419]
Currently the form does not have a way to get all values in an array.
There is only a getValue method, would be a nice addition to have a method to return all data.

Similar to the message, there is a getMessages and getMessageFor method.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. If anyone wants to get started, I'd love that.
