### ISSUE TITLE
Mongo is deprecated

### ISSUE THREAD

**Issue by skynetweb** [phalcon/cphalcon#2422]
ErrorException: Phalcon\Cache\Backend\Mongo::_getCollection(): The Mongo class is deprecated, please use the MongoClient class 
/var/www/domain.com/public_html/app/engine/ApplicationInitialization.php (259)

**Comment by Green-Cat** [comment]
@phalcon @andresgutierrez 
This is fixed in 2.0.
https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/cache/backend/mongo.zep#L117
