### ISSUE TITLE
Foreign Key Constraints ON UPDATE and ON DELETE

### ISSUE THREAD

**Issue by reelmedia** [phalcon/cphalcon#2431]
Hello Phalcon Team!

Your documentation is a little unclear on this, but how do you setup a `\Phalcon\Mvc\Model\Relation::NO_ACTION`, `ACTION_RESTRICT` or `ACTION_CASCADE` when setting up a Foreign Key Constraint on Models **while specifying a DELETE or UPDATE action**?

I have the following code, but this only constraints `ON DELETE`, how about `ON UPDATE`?

```
$this->hasOne('routeId', 'App\Module\Core\Model\Page', 'routeId', array(
    'foreignKey' => array(
        'action' => Relation::ACTION_CASCADE
    )
));
```

**Additional Note:** Is there support for "`ACTION_SET_NULL`" action on constraints?

Thank you for the greatest PHP Framework I had ever seen!
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. If anyone wants to get started, I'd love that.
