### ISSUE TITLE
[NFR] Phalcon\Mvc\Model\Resultset - Slice Function

### ISSUE THREAD

**Issue by webgelistiricisi** [phalcon/cphalcon#2445]
Hi,
I could not find any function like array slice.I want to slice resultsets by parts.But there is no native way.For example:

```
$robots = Robots::find();

$robots_0_2 = $robots->slice(0, 2) // first two records, slice(offset, legth)
```

**Comment by Green-Cat** [comment]
@phalcon This is already part of the core, please close.
