### ISSUE TITLE
[NFR] Partial Caching

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#2452]
I did some profiling on my app and realised that it spends most of its time on partials.

I extended the view class and tacked on partial caching which has helped me cut down page load times by half (though the initial load takes 80% longer for the same profile but this is a one-time hit).

I calculate the hash of `$partial` and `$params` to generate the cache key. This allows caching of partials even when the data is dynamic.

The only thing to be careful about is that if the `$params` to a partial are constantly changing, the cache directory can fill up pretty soon. However,  this has probably been the biggest optimisation win I have had in my app in quite some time.

It would be nice to have a well though-out solution to allow partial-caching and/or partial-caching with dynamic data.

Another very useful feature for partial caching would be to allow disabling it on a per-request basis. This is because it doesn't make sense to cache long-tail pages that are seldom accessed (this will fill up the cache, incur a one-time penalty and the cache will rarely be used again). So disabling partial caching for certain controllers or within certain actions based on criteria, would make this a huge performance win.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. If anyone wants to get started, I'd love that.
