### ISSUE TITLE
[BUG] Phalcon\Mvc\Model - Zombie Model Relations

### ISSUE THREAD

**Issue by camcima** [phalcon/cphalcon#2464]
When running a phpunit test suite, I've noticed there is a problem with model relations that are not updated from test to test. I've managed to prepare a test script:

https://github.com/camcima/phalcon-model-bug

I'm using the latest Phalcon extension 1.3.1.

**Comment by sergeyklay** [comment]
The `1.3.x` branch is not longer supported. If there are bugs in the 3.2.x, we can follow up in separate issues.
