### ISSUE TITLE
illegal instruction in phalcon_realpath

### ISSUE THREAD

**Issue by TheIrritainer** [phalcon/cphalcon#2468]
i tried setting up another project with phalcon today, my first one didn't include views and it is workin superb. So now i fired up the phalcon devtools, created a skeleton project and used scaffold for a table; just a quickie.

on windows it is working fine but when i pushed it to my centos digitalocean server i ran into 'illegal instruction'.

server: centos 6.5 32 bit
php: 5.3.3
Phalcon Version	1.3.1

did a core dump, seems that there goes something wrong in phalcon_realpath?

GNU gdb (GDB) Red Hat Enterprise Linux (7.2-60.el6_4.1)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/php...Reading symbols from /usr/lib/debug/usr/bin/php.debug...done.
done.
[New Thread 11436]

... cutted ....

Core was generated by `php index.php'.
Program terminated with signal 4, Illegal instruction.
#0  0x03c3a118 in phalcon_realpath () from /usr/lib/php/modules/phalcon.so
Missing separate debuginfos, use: debuginfo-install audit-libs-2.2-2.el6.i686 cyrus-sasl-lib-2.1.23-13.el6_3.1.i686 freetype-2.3.11-14.el6_3.1.i686 keyutils-libs-1.4-4.el6.i686 libX11-1.5.0-4.el6.i686 libXau-1.0.6-4.el6.i686 libXpm-3.5.10-2.el6.i686 libc-client-2007e-11.el6.i686 libcurl-7.19.7-37.el6_4.i686 libedit-2.11-4.20080712cvs.1.el6.i686 libidn-1.18-2.el6.i686 libjpeg-turbo-1.2.1-3.el6_5.i686 libmcrypt-2.5.8-9.el6.i686 libpng-1.2.49-1.el6_2.i686 libselinux-2.0.94-5.3.el6_4.1.i686 libssh2-1.4.2-1.el6.i686 libxcb-1.8.1-1.el6.i686 mysql-libs-5.1.73-3.el6_5.i686 ncurses-libs-5.7-3.20090208.el6.i686 nspr-4.10.2-1.el6_5.i686 nss-3.15.3-6.el6_5.i686 nss-softokn-freebl-3.14.3-10.el6_5.i686 nss-util-3.15.3-1.el6_5.i686 openldap-2.4.23-34.el6_5.1.i686 pam-1.1.1-17.el6.i686 php-mcrypt-5.3.3-3.el6.i686 sqlite-3.6.20-1.el6.i686
[?1034h(gdb) quit

----

gcc info:

[root@emtay public]# gcc -march=native -mtune=native -Q -O2 --help=target
The following options are target specific:
  -m128bit-long-double                  [disabled]
  -m32                                  [enabled]
  -m3dnow                               [disabled]
  -m3dnowa                              [disabled]
  -m64                                  [disabled]
  -m80387                               [enabled]
  -m96bit-long-double                   [enabled]
  -mabm                                 [disabled]
  -maccumulate-outgoing-args            [disabled]
  -maes                                 [disabled]
  -malign-double                        [disabled]
  -malign-functions=
  -malign-jumps=
  -malign-loops=
  -malign-stringops                     [enabled]
  -march=                               pentium-m
  -masm=
  -mavx                                 [disabled]
  -mbmi                                 [enabled]
  -mbranch-cost=
  -mcld                                 [disabled]
  -mcmodel=
  -mcrc32                               [disabled]
  -mcx16                                [enabled]
  -mf16c                                [disabled]
  -mfancy-math-387                      [enabled]
  -mfma                                 [disabled]
  -mfma4                                [disabled]
  -mforce-drap                          [disabled]
  -mfp-ret-in-387                       [enabled]
  -mfpmath=
  -mfsgsbase                            [disabled]
  -mfused-madd                          [enabled]
  -mglibc                               [enabled]
  -mhard-float                          [enabled]
  -mieee-fp                             [enabled]
  -mincoming-stack-boundary=
  -minline-all-stringops                [disabled]
  -minline-stringops-dynamically        [disabled]
  -mintel-syntax                        [disabled]
  -mlarge-data-threshold=
  -mlwp                                 [disabled]
  -mmmx                                 [disabled]
  -mmovbe                               [disabled]
  -mms-bitfields                        [disabled]
  -mno-align-stringops                  [disabled]
  -mno-fancy-math-387                   [disabled]
  -mno-push-args                        [disabled]
  -mno-red-zone                         [disabled]
  -mno-sse4                             [enabled]
  -momit-leaf-frame-pointer             [disabled]
  -mpc
  -mpclmul                              [disabled]
  -mpopcnt                              [enabled]
  -mpreferred-stack-boundary=
  -mpush-args                           [enabled]
  -mrdrnd                               [disabled]
  -mrecip                               [disabled]
  -mred-zone                            [enabled]
  -mregparm=
  -mrtd                                 [disabled]
  -msahf                                [enabled]
  -msoft-float                          [disabled]
  -msse                                 [disabled]
  -msse2                                [disabled]
  -msse2avx                             [disabled]
  -msse3                                [disabled]
  -msse4                                [disabled]
  -msse4.1                              [disabled]
  -msse4.2                              [disabled]
  -msse4a                               [disabled]
  -msseregparm                          [disabled]
  -mssse3                               [disabled]
  -mstack-arg-probe                     [disabled]
  -mstackrealign                        [enabled]
  -mstringop-strategy=
  -mtbm                                 [disabled]
  -mtls-dialect=
  -mtls-direct-seg-refs                 [enabled]
  -mtune=                               generic
  -muclibc                              [disabled]
  -mveclibabi=
  -mxop                                 [disabled]

------------

[root@emtay public]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 2
model name      : QEMU Virtual CPU version 1.0
stepping        : 3
cpu MHz         : 2399.998
cache size      : 4096 KB
fdiv_bug        : no
hlt_bug         : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm up unfair_spinlock pni vmx cx16 popcnt hypervisor lahf_lm
bogomips        : 4799.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as 1.3.x is no longer supported
