### ISSUE TITLE
[NFR] Proposal for MySQL dialect INTEGER type juggling

### ISSUE THREAD

**Issue by WooDzu** [phalcon/cphalcon#2470]
Currently, using the mysql dialect forces INT type for all columns declared INTEGER.
An optional "size" is allowed (eg. INT(5)), which as you might know is not being used neither by storage engines or MySQL optimizer. In short words INT(1) requires the same amount of storage bytes and momory allocation as INT(11). What I'd like to propose is reworking the following condition:

https://github.com/phalcon/cphalcon/blob/1.3.2/ext/db/dialect/mysql.c#L133

so that it's using the `size` declaration in a far better way to dynamically juggle the MySQL internal type between TINYINT, SMALLINT, MEDIUMINT, INT and BIGINT. It doesn't matter for small tables, but definitelly those with millions of rows will benefit from smaller indexes especially when using secondary indexes where it's important to keep custered index as small as possible.

Pseudo code:

```
if (size < 5)
  type = TINYINT    // 1 byte
elseif (size < 7)
  type = SMALLINT   // 2 bytes
elseif (size < 10)
  type = MEDIUMINT  // 3 bytes
elseif (size > 11)
  type = BIGINT     // 8 bytes
else
  type = INT        // 4 bytes

```

Again, this gives benefits for storage as well as db performance.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. If anyone wants to get started, I'd love that.
