### ISSUE TITLE
[NFR] Iban validator

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#2475]
It would be nice if Phalcon can validate the International Bank Account Number (IBAN).

From what I found the base of an IBAN is validated by converting it into an integer and performing a basic mod-97 operation (as described in ISO 7064) on it. If the IBAN is valid, the remainder equals 1. Besides that I think you also need to parse the local information about the country and bank.
Maybe we could take a look at the Zf2 validator.

https://github.com/zendframework/zf2/blob/master/library/Zend/Validator/Iban.php
http://framework.zend.com/apidoc/2.0/classes/Zend.Validator.Iban.html

**Comment by sergeyklay** [comment]
IBAN banking codes is too specific to be in core. This feature request should be moved to the Incubator.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/incubator#809
