### ISSUE TITLE
Radio elements in group don't store values from request

### ISSUE THREAD

**Issue by slechtic** [phalcon/cphalcon#2476]
I try to implement group of radio elements:

``` php
$form = new \Phalcon\Forms\Form();
$group1 = new Element\Radio('r1', array(
       'name' => 'group[]',
            'value' => 1
        ));
$form->add($group1);

$group2 = new Element\Radio('r2', array(
            'name' => 'group[]',
            'value' => 2
        ));
$form->add($group2);

$save = new Element\Submit('save');
$form->add($save);
```

but when I check one of them and submit the form, the checked radio are not checked after submit and I lost the form state. When I remove attribute name (group[]) it works but the elements are not in the group.

I use Phalcon 1.3.1.

Here is my example app: 
https://github.com/slechtic/phalcon_test_elements
##

**Comment by ruudboon** [comment]
Any updates on this? I'm having issues where I can't use a bind to map the post to the radiobuttons of a form.
