### ISSUE TITLE
[NFR] \Phalcon\Tag: Add meta-related methods

### ISSUE THREAD

**Issue by kjdev** [phalcon/cphalcon#2483]
**NFR**:

Adding new methods:

class \Phalcon\Tag {

public static function appendMeta($type, $key, $content = null);
public static function prependMeta($type, $key, $content = null);
public static function appendMetaName($key, $content);
public static function prependMetaName($key, $content);
public static function appendMetaProperty($key, $content);
public static function prependMetaProperty($key, $content);
public static function appendMetaHttpEquiv($key, $content);
public static function prependMetaHttpEquiv($key, $content);
public static function getMeta();

}

**USE**:

Set a  stiring to document meta.

```
Tag::appendMeta('charset', 'utf-8');
Tag::appendMetaHttpEquiv('Content-Type', 'text/html; charset=utf8');
Tag::appendMetaProperty('description', 'Description Text');
```

Gets the document meta.

```
echo Tag::getMeta();
```

Output:

```
<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<meta property="description" content="Description Text" />
```

**IMPLEMENTATION**:

[https://github.com/karakurihiden/cphalcon/compare/1.3.2...1.3.2-tag](https://github.com/karakurihiden/cphalcon/compare/1.3.2...1.3.2-tag)
##

**Comment by code100** [comment]
yes, this will be a feature really useful and make volt code more organized.

**Comment by sergeyklay** [comment]
I suggest something like this:

`config.php`:
```php
'meta' => [
    'links' => [
        'http://company.com/favicon.ico' => [
            'rel'  => 'shortcut icon',
            'type' => 'image/x-icon'
        ],
        'http://company.com/rss' => [
            'rel'   => 'alternate',
            'type'  => 'application/rss+xml',
            'title' => 'Read more about comopany via RSS 2.0'
        ],
        'httpL//company.com/' => [
            'rel'   => 'index',
            'title' => 'Company Title'
        ],
    ],
    'tags' => [
        'charset'    => 'utf-8',
        'generator'  => 'Phalcon v2.0.6',
        'author'     => 'Company',
        'copyright'  => 'Copyright (c) The Company 2014-2015. All rights reserved.',
        'robots'     => 'index, follow, noodp',
        'viewport'   => 'width=device-width, initial-scale=1.0',
    ],
],
```

view layout:
```php
<?php echo Tag::metaLinks(); ?>
<?php echo Tag::metaTags(); ?>
```

for `<meta ...>` and `<link ...>`
