### ISSUE TITLE
Add HHVM compile flag

### ISSUE THREAD

**Issue by Swader** [phalcon/cphalcon#2494]
As per [this suggestion](http://forum.phalconphp.com/discussion/2429/build-phalcon-for-hhvm-), compiling Phalcon would let it spread its wings in all PHP environments.

Some adjustments will be necessary, as per instructions on the [comp layer's README](https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext_zend_compat), but it does seem possible.

In short - look into adding a flag to Zephir's compilation process to generate HHVM compatible code.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises.
