### ISSUE TITLE
[BUG] Model triggers notSave and notSaved events

### ISSUE THREAD

**Issue by scento** [phalcon/cphalcon#2495]
**Problem**
The [documentation](http://docs.phalconphp.com/en/latest/reference/models.html#validation-failed-events) refers to an event handler named `notSave`, which should be called when an _INSERT_ or _UPDATE_ operation failes. Considering the real code, this event is only triggered when `_postSave` failes and at that point in addition to the `notSaved` handler is called. The `notSaved` handler fulfills all attributes described in the documentation.

**Solution**
On the one hand one could update the documentation and add both event handlers with their specific purpose or on the other hand one could remove the `notSave` handler and entirely replace its function with the `notSaved` handler. The documentation should be updated in case @phalcon decides to use the second solution.

**Comment by andresgutierrez** [comment]
Fixed in 2.0.4
