### ISSUE TITLE
Better HMVC module support in Phalcon

### ISSUE THREAD

**Issue by al35mm** [phalcon/cphalcon#2496]
Admittedly I'm new to Phalcon. I'm porting a large app to Phalcon. Due to the complexity of the app I need to modularize the different sections of it, such as forums etc. There doesn't seem to be much support for true HMVC in Phalcon. For example, common/universal template views are a major problem with modules when the module views are in the module directory. Dispatching to controllers outside of a module seems to be impossible.

**Comment by sergeyklay** [comment]
Implemented in `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
