### ISSUE TITLE
Phalcon Controller's action is not working properly

### ISSUE THREAD

**Issue by itpedia-la** [phalcon/cphalcon#2501]
I have downloaded Phalcon Skeleton and upload into my site http://www.returnquick.com/rqadmin
and it working fine and display the page with 

"Congratulations!
You're now flying with Phalcon."

which mean the IndexController.php is load and working fine, even I try to pass the variable through $this->view->setVar('$var', 'Hello World') to display on /app/views/index/index.phtml.

the problem is when I try to access the another action ex: TestAction in IndexController.php it show me the 404 Page Not Found! 

I'm pretty sure that all my configs and .htaccess are correct and all the same with http://returnquick.com/demo which also use Phalcon framework with same hosting

p.s apologize for my poor English..

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
