### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by phanthos** [phalcon/cphalcon#2515]
While running the Vokuro example on a clean Windows Apache Server at first everything seems ok, but while trying to create an account (Sign Up) the app just stops and the server returns an ERR_CONNECTION_RESET. The error appears just after the Sign Up page is filled correctly and the user clicks the button to submit the form.
Tests performed:

Scenario 1 - With XDebug DISABLED I try to Create an Account and I get the ERRCONNECTIONRESET error.

Scenario 2 - Using XDebug WITHOUT PROFILING I get until this point while doing a remote debug: 
The application calls:
https://github.com/phalcon/vokuro/blob/master/app/controllers/SessionController.php#L50
```php
if ($user->save()) { 
```
Then when the following line gets called and validates successfully the application returns the error ERRCONNECTIONRESET to the browser
https://github.com/phalcon/vokuro/blob/master/app/models/Users.php#L129 
```php
return $this->validationHasFailed() != true; 
```
Sometimes the SessionController::signupAction() gets called several times, I have no idea why.

Scenario 3 - Using XDebug with PROFILING ENABLED and no remote debug everything works just fine.

Scenario 4 - Using XDebug with PROFILING ENABLED and debugging the same thing as Scenario 2 occurs.

Tested using Windows 7 x64, PHP Version 5.3.10, Apache/2.2.21 (Win32) mod_ssl/2.2.21 OpenSSL/1.0.0e PHP/5.3.10 mod_perl/2.0.4 Perl/v5.10.1, Phalcon 1.3.1
This error also happens with Phalcon 1.3.2.
If needed I could provide the profiliing generated by XDebug in Scenario 3.

Using Phalcon 1.2.6 everything works ok

**Comment by andresgutierrez** [comment]
Fixed in 1.3.3
