### ISSUE TITLE
SessionBag data doesn't get updated when closing and opening the session

### ISSUE THREAD

**Issue by ianbytchek** [phalcon/cphalcon#2522]
It appears session bag has an internal data object which gets set up only when the session bag is created and there after it remains independent of the $_SESSION. When I close the session and open it again, I get fresh data in my the `$_SESSION` but data in the session bag appears old. I get the desired behaviour only by creating new instances of session bags after reopening the session.

This behaviour is observed in `persistent` property of controllers and other classes supporting it. I'm not sure you can reset it there, making this a dead end.
##

**Comment by dschissler** [comment]
Is this still broken?

**Comment by ianbytchek** [comment]
@dschissler haven't touched this in a while and don't have the means to check it now. The above code and suggestion to use `$_SESSION` directly are still valid and would solve this, if they aren't implemented. Especially since more session functions joining PHP 5.6 making this whole subject a little more complicated to track.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
