### ISSUE TITLE
[NFR] MySQL SELECT query: REGEXP

### ISSUE THREAD

**Issue by zsilbi** [phalcon/cphalcon#2532]
**Problem**

Here you can find the original post: http://forum.phalconphp.com/discussion/1193/select-query-by-regexp-error

>Hi,
>
>When i try to execute a query using the mysql regexp, i get this error:
>
>```Phalcon\Mvc\Model\Exception: Syntax error, unexpected token IDENTIFIER(regexp), near to ' "^:name:"', when parsing: SELECT * FROM Model WHERE name regexp "^:name:" (79)```

I can confirm this.

**Possible solution**

Add REGEXP function be recognized by Phalcon\Mvc\Model.

**Comment by hailie-rei** [comment]
Will it be implemented?
I have a set if queries that depends on options:
`            $sql = $this->getModelsManager()->createBuilder()
                ->from(array('wgl' => '\Model\WGloss'))
                ->...
                ->where('wgr.lang = "ru"');
            if (isset($data['f']) && $data['f'] == 'y') {
                $sql->andWhere('LOWER(wgl.gloss) REGEXP :text:', array(
                    'text' => '[[:<:]]' . $data['text'] . '[[:>:]]'
                ));
            } else {
                $sql->andWhere('LOWER(wgl.gloss) LIKE :text:', array(
                    'text' => '%' . $data['text'] . '%'
                ));
            }
`
and it's not useful to write all set of queries using MySQL string. Is there a possibility to avoid this and use more flexible variant?

**Comment by Green-Cat** [comment]
This is not a bug, although phql only has standard SQL functions, you can add any vendor specific functions yourself since 2.0.10, see https://blog.phalconphp.com/post/phalcon-2-0-3-released.

**Comment by hailie-rei** [comment]
@Green-Cat Thanks! It's useful!
