### ISSUE TITLE
[NFR] Phalcon\Mvc\Collection to support insert()

### ISSUE THREAD

**Issue by valheranze** [phalcon/cphalcon#2536]
MongoDB distinguish between ->save() and ->insert(). Would be nice to have insert() function added to Collection.

http://docs.mongodb.org/manual/reference/method/db.collection.insert/
 * Create document, fails if already exists

http://docs.mongodb.org/manual/reference/method/db.collection.save/
 * Create/Update document

**Comment by Green-Cat** [comment]
@andresgutierrez Implemented in #2552
