### ISSUE TITLE
[BUG] [1.3.2] Router sets incorrect params for actions

### ISSUE THREAD

**Issue by waplet** [phalcon/cphalcon#2540]
In payments controller there is a function

``` php
public function chooseAction($cart_hash = null)
{
    echo "Cart hash:".$cart_hash;
    die;
}
```

Routes:

``` php
$router->add(
    "/{locale:en}/:controller/:action/:params",
    [
        "namespace"  => '\App\Controllers',
        "locale"     => 1,
        "controller" => 2,
        "action"     => 3,
        "params"     => 4,
    ]
);
```

And instead of printing `null` it prints out `en`.

Why is it like that? Why is locale, set as chooseAction's first param?

```
site/en/payments/choose
```

echoes: `en`

```
site/en/payments/choose/test
```

echoes: `test`

**Comment by sergeyklay** [comment]
It is Phalcon `1.3.x` issue. The `1.3.x` branch is not longer supported. I hope this resolved in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
