### ISSUE TITLE
getExtension method from Phalcon\Http\Request\File always returns a blank string

### ISSUE THREAD

**Issue by phpFR** [phalcon/cphalcon#2549]
Hi

I use Phalcon v 1.3.2 

Extract from cphalcon / ext / http / request / file.c 
Notice the trailing space after "_extension" ...

```php
/**
* Returns the file extension
*
* @return string
*/
PHP_METHOD(Phalcon_Http_Request_File, getExtension){
RETURN_MEMBER(this_ptr, "_extension ");
}
```

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/2744567-getextension-method-from-phalcon-http-request-file-always-returns-a-blank-string?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F50707&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by Green-Cat** [comment]
@andresgutierrez Fixed.
