### ISSUE TITLE
[BUG] [1.3.2] Cannot JOIN aliased model with Many-To-Many relation

### ISSUE THREAD

**Issue by HitoriSensei** [phalcon/cphalcon#2567]
I have three models with relations:
**Models\Certyfikaty**
```php
$this->belongsTo( 'uzytkownik_id', 'Models\Uzytkownicy', 'uzytkownik_id', [ 'alias' => 'uzytkownik' ] );
```

**Models\Uzytkownicy**
```php
$this->hasManyToMany(
    'uzytkownik_id',
    'Models\UzytkownicyRole',
    'uzytkownik_id_uzytkownicy_dane', 'rola_id_role',
    'Models\Role',
    'rola_id',
    [ 'alias' => 'uzytkownikRole' ]
);

$this->hasMany(
    'uzytkownik_id',
    'Models\Certyfikaty',
    'uzytkownik_id',
    [ 'alias' => 'uzytkownikCertyfikaty' ]
);
```

**Models\Role**
```php
$this->hasManyToMany(
    'rola_id',
    'Models\UzytkownicyRole',
    'rola_id_role', 'uzytkownik_id_uzytkownicy_dane',
    'Models\Uzytkownicy',
    'uzytkownik_id'
);
```

When I try to execute a query (n-n relation between models):
```sql
SELECT Models\Role.* 
from Models\Role
JOIN Models\Uzytkownicy
where Models\Uzytkownicy.login = "erkerk"
```
everything works properly.

But, when I try to execute a query with an alias:
```sql
SELECT Models\Role.* 
from Models\Role
JOIN Models\Uzytkownicy as something
where something.login = "erkerk"
```
it throws an exception `Unknown model or alias 'Models\Uzytkownicy'`

What's interesing, the same situation with aliased model but with a simple relation (1-n, note that I've changed *Models\Role* to *Models\Certyfikaty*):
```sql
SELECT Models\Certyfikaty.* 
from Models\Certyfikaty
JOIN Models\Uzytkownicy as something
where something.login = "erkerk"
```
works properly.

**Comment by slclub** [comment]
There are same proplem too .when i using phql (version 1.3.4); 
$robots = $this->modelsManager->createBuilder()
    ->from('Article\Robots')
    ->join('Article\RobotsParts')
    ->orderBy('Article\Robots.name')
    ->getQuery()
    ->getSingleResult();

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as 1.3.x is no longer supported
