### ISSUE TITLE
Class not found error when Controller has uppercase letters in class & its file name

### ISSUE THREAD

**Issue by amsharma9** [phalcon/cphalcon#2572]
I have setup Php 5.5, Phalcon 1.3.1 on 64bit Linux on a shared hosting server. I was able to run my application on Wamp on Windows 7 with Phalcon 1.3.1 & Php 5.5 but when I moved the application to production on a Linux 64 bit (most probably CentOS) I got the below error:

    Fatal error: Uncaught exception 'Phalcon\Mvc\Dispatcher\Exception' with message 'CIAB\Controllers\ChooseprojectController handler class cannot be loaded' in /home/myproj/public_html/ciab/public/index.php:35
    Stack trace: #0 [internal function]: Phalcon\Mvc\Dispatcher->_throwDispatchException('CIAB\\Controller...', 2)
    #1 [internal function]: Phalcon\Dispatcher->dispatch()
    #2 /home/myproj/public_html/ciab/public/index.php(35): Phalcon\Mvc\Application->handle()
    #3 {main} thrown in /home/myproj/public_html/ciab/public/index.php on line 35

It looks like Phalcon doesn't allow uppercases in Controller class and file names except as the first letter. To get rid of this error I had to **change the controller class name and the name of the file containing the class, i.e. ChooseProjectController.php, with a lower case 'P'**. As mentioned earlier, it worked fine on Windows but on linux it didn't till I changed as above. You should easily be able to recreate this bug and it seems to be related to an older bug ` Error parsing annotations router #1040` bug. I am new to Github so I hope this is the correct way to inform you of a potential bug.

Regards

**Comment by Yurist-85** [comment]
I just found something interesting... It could be useful for all of you.

When I use Routing based on Annotations, paths stored in autogenerated routes contains third parameter `'exact' => true`.
Otherwise, when routes were declared using 
```php
$router->add('/some/link',"SomeController::someAction")
```
there was no such parameter `'exact'`.
I'm not sure, but I think this parameter says Phalcon to use 'exact' controller name or generate it with first uppercased letter.

UPD: I was wrong... Couple of tests showed me that `'exact'` parameter useless.
BUT!
When you use custom routes, there're few interesting facts:
```php
// Declare route using paths array
$router->add('/demo',['controller' => 'DemoCamelCased' , 'action' => 'index']);
// Declare route using paths short string
$router->add('/demo2','DemoCamelCased::sampleCamelCased');
```
First case:
```
// go to http://doma.in/demo
DemocamelcasedController handler class cannot be loaded
```
Second case:
```
// go to http://doma.in/demo2
Whoa! All works properly!
```
So, if you want to use CamelCasedClassNames, use custom routes with short path string.

P.S. `It's a BUG`. Because paths array and paths short string should to give us the same result, I think. But they are not...

**Comment by luhuiya** [comment]
it is totally bug.

When we using CamelSomeClassController it will throw 404
your file class Need to be CamesomeclassController to work 
this is just stupid

**Comment by amsharma9** [comment]
I also think its a bug but it seems its hard to convince the Phalcon community. Its hard to fight an argument like below by @phalcon 

*This how it currently works, you can say, sure let's change the camelize function so it works as we like but again we don't know how many developers already have addressed this behavior by implementing their applications as the framework currently does behave.*

Just because some people have code working the wrong way we don't change the functionality to what should be the correct way. What will happen five years down the line. Won't it be still more difficult? IMHO if we have to correct our mistake, it must be done now. The earlier we get on the right path, the better for all of us.

**Comment by UndergroundLabs** [comment]
@phalcon please provide a demonstration on how to use camel cased controller names with Dispather::forward(). I've tried, it doesn't work:

    public function indexAction() {
        return $this->dispatcher->forward([
            'controller' => 'CreateSnap',
            'action' => 'show'
        ]);
     }

I get the follow exception:

    PhalconException: CreatesnapController handler class cannot be loaded

**Comment by andresgutierrez** [comment]
@UndergroundLabs it shouldn't be camel-cased

```php
public function indexAction() {
    return $this->dispatcher->forward([
        'controller' => 'create-snap',
        'action' => 'show'
    ]);
 }
```

**Comment by UndergroundLabs** [comment]
@andresgutierrez Damn that was a fast reply. I was about to comment that I solved it by using 'create_snap', but I like the hyphenated version better. Thanks :)

**Comment by berliner** [comment]
The hyphenated version doesn't work for me on OS X using phalcon 2.0.1, only the underscore version works. The same is true for route definitions.

**Comment by dimhoLt** [comment]
Hello!

 

Important message, visit http://chiropractorinfayetteville.com/company.php?o3

 

helge.soderstrom@fightingdreamers.se

**Comment by dimhoLt** [comment]
Hey friend!

 

Check it out http://www.7del7.com/carried.php?gz

 

helge.soderstrom@fightingdreamers.se

**Comment by dimhoLt** [comment]
Hey!

 

Important message, please visit <http://krtfm.com/I.php?ru3yp>

 

helge.soderstrom@fightingdreamers.se

**Comment by dimhoLt** [comment]
Hey!

 

Important message, please visit <http://somaticyoga.com/corner.php?d49n>

 

helge.soderstrom@fightingdreamers.se

**Comment by michaelzf** [comment]
it is totally bug.

**Comment by dropu** [comment]
same ....

PHP Fatal error:  Uncaught exception 'Phalcon\Cli\Dispatcher\Exception' with message 'Bblive\Modules\Cli\Tasks\WebsocketeventworkerstartTask handler class cannot be loaded' in /data/webroot/www/websocket/app/modules/cli/tasks/WebsocketTask.php:75

file name is  'WebsocketEventWorkerStartTask.php' 

how to fix this bug

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/issues/2572#issuecomment-65152912 It's not a bug actually, it's exepcted behaviour unforunately which i don't like too.

**Comment by dropu** [comment]
interesting, development machine is work fine,  product machine not work, 很奇怪的命名方式

**Comment by Jurigag** [comment]
Because windows is not case sensitive, linux is.

**Comment by dropu** [comment]
@Jurigag en... development on centos 6.7 , production same

**Comment by Jurigag** [comment]
Then idk, somehow your dev machine is not case sensitive or you are lying about file name.

**Comment by Ni-vek** [comment]
What about your class name?

**Comment by antsokol** [comment]
I used temporary solve

$eventsManager = new EventsManager();
`$eventsManager->attach(
	"dispatch:beforeDispatchLoop",
	function (PhEvent $event, $dispatcher) {
		$ctrlName = $dispatcher->getControllerName();
		$normalizedName = strtolower(preg_replace('/(?<!^)([A-Z])/', '-\1' ,$ctrlName));
		$dispatcher->setControllerName($normalizedName);
	}
);`
$dispatcher->setEventsManager($eventsManager);

**Comment by antsokol** [comment]
I use temporary solve
someControllerName -> some-controller-name
SomeControllerName -> some-controller-name

```php
$eventsManager = new EventsManager();
$eventsManager->attach(
	"dispatch:beforeDispatchLoop",
	function (\Phalcon\Events\Event $event, $dispatcher) {
		$ctrlName = $dispatcher->getControllerName();
		$normalizedName = strtolower(preg_replace('/(?<!^)([A-Z])/', '-\1' ,$ctrlName));
		$dispatcher->setControllerName($normalizedName);
	}
);
$dispatcher->setEventsManager($eventsManager);
```

**Comment by GenaANTG** [comment]
I have same issue. This is a bug, guys.

**Comment by guihouchang** [comment]
it is a  bug....

**Comment by sergeyklay** [comment]
@guihouchang Open a new issue then :)
