### ISSUE TITLE
Phalcon\Mvc\Model\Validator\Uniqueness didn't support mongodb

### ISSUE THREAD

**Issue by lookingatsky** [phalcon/cphalcon#2585]
Phalcon\Mvc\Model\Validator\Uniqueness didn't support mongodb:
Fatal error: Phalcon\Mvc\Model\MetaData::readMetaDataIndex() [<a href='phalcon\mvc\model\metadata.readmetadataindex'>phalcon\mvc\model\metadata.readmetadataindex</a>]: Call to undefined method getschema() on class Users in Users.php on line 20

**Comment by salarmehr** [comment]
From 2.0.4 changelog:
Introduced Phalcon\Mvc\EntityInterface to allow parameters receive both Phalcon\Mvc\Model and Phalcon\Mvc\Collection instances. This interface allow Mvc\Model\Validators being used in Mvc\Collection

Try that.

**Comment by andresgutierrez** [comment]
Fixed in Phalcon 2.0.4

**Comment by noel-ykt** [comment]
is not fixed.
i have this bug in 2.0.5 version
```
...Uncaught exception 'RuntimeException' with message 'Call to undefined method Tops::getschema()'...
```

**Comment by re8260** [comment]
still same bug, version 2.0.10.
