### ISSUE TITLE
Model::save($array_post_data, $array_fields) - will empty the fields not in array_post_data

### ISSUE THREAD

**Issue by rrlledo** [phalcon/cphalcon#2587]
Updating a record with $array_post_data will empty the fields not in the $array_post_data even if you specified the second parameter $array_fields containing the fields to be updated.

Example:

Table: employees
id: 1
lastname: Public
firstname: John
middlename: Q

$employee = new Employees();
// $_POST['id'] = 1;
// $_POST['lastname'] = 'Doe';
// $_POST['firstname'] = 'John';
$employee->save($_POST);

The above will empty middlename field after the call to save().

$employee->save($_POST, array_keys($_POST));

Same as above.  

From the documentation: 

"You can set an additional parameter in ‘save’ to set a whitelist of fields that only must taken into account when doing the mass assignment:"

```php
<?php

$robot = new Robots();
$robot->save($_POST, array('name', 'type'));
```

The second parameter is ignored.

The solution:

```
$employee = Employees::findFirstById($id)
$employee->lastname = $this->request->getPost('lastname', 'striptags');
$employee->firstname = $this->request->getPost('firstname', 'striptags');
$employee->save();
```

**Comment by andresgutierrez** [comment]
Can't reproduce this issue in Phalcon >= 2.0.0
