### ISSUE TITLE
Creation of Resourses and Roles implicity

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#2588]
I think the `Acl::allow()` should create roles and resources implicitly when they are not defined in advance. Indeed there is no need to user `addRole` and `addRecource`. (Only when we want declare an inheritance relation the `addRole method can be useful.  )
##

**Comment by sergeyklay** [comment]
I'm closing since this is a not a bug report.  No work was put towards this, contributions welcome. Also feel free to discuss on the [official forums].
