### ISSUE TITLE
Phalcon\Queue\Beanstalk crashes when beanstralkd is not available

### ISSUE THREAD

**Issue by demkinmaxim** [phalcon/cphalcon#2594]
Hello. I'm using Phalcon 1.3.2

```
 $queue = new \Phalcon\Queue\Beanstalk(); 
```
Everythings works ok, but when the beanstalkd server is down I get:
``
Unable to connect to Beanstalk server at 127.0.0.1:11300 (Connection refused)
``

And 500 error. It does not throw an exception, so I can't make a graceful degradation on something like that. There should be an exception or something to manage connections error. 

Thank you!

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2?

**Comment by amin-ajami** [comment]
dear demkinmaxim
you need install beanstalkd on server and run beanstalkd:
Mac OS:
```
brew install beanstalkd
beanstalkd -p 11300
```
Ubuntu
```
apt-get install beanstalkd
beanstalkd -p 11300
```

after instal and run beanstalkd run your phalcon code
