### ISSUE TITLE
Add constraint to foreign key

### ISSUE THREAD

**Issue by nsossonko** [phalcon/cphalcon#2604]
It's not possible to add constraints (ON UPDATE CASCADE, etc) to foreign keys with Phalcon\Db\AdapterInterface::addForeignKey. It accepts a Phalcon\Db\ReferenceInterface which does not have an "action" or similar parameter for constraints. This would be very useful.

Thanks.
##

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open new issue if the problem appears again. Thank you for contributing.
