### ISSUE TITLE
[NFR] Gettext support for Volt templates

### ISSUE THREAD

**Issue by snolflake** [phalcon/cphalcon#2605]
I'm aware that it is already possible to use `gettext` within Volt templates, but the way that twig does it is very nice and handy. The usage of a new `trans` keyword  would be almost identical to the current one that Twig have: [here's the documentation](http://twig.sensiolabs.org/doc/extensions/i18n.html).
### Why `gettext`?

Since the main goal of Phalcon is performance, I believe that `gettext` should be the tool of choice for internationalization ([the docs](http://docs.phalconphp.com/en/latest/reference/intl.html) doesn't even mention it as an option); first because it's one of the [fastest ways to retrieve localized strings](http://mel.melaxis.com/devblog/2006/04/10/benchmarking-php-localization-is-gettext-fast-enough/) plus a [few more advantages](http://stackoverflow.com/a/1415670/741981).
### poEdit and string extractor

Long ago I've used this [string extractor](https://github.com/umpirsky/Twig-Gettext-Extractor) for Twig and take a look in the source code and by this I can say that the implementation would be almost identical using a volt compiler. So that's a sure thing to deliver within this new `trans` keyword; It will make very easy to maintain catalogs for all your templates and manage translations using poEdit, surely this will make Phalcon more attractive for large projects.
### Now what?

I'm wiling to implement it myself but here at work my projects are running late(what a surprise) so I'll postpone this and meanwhile just share the idea with you guys. So, if anyone has some insights on how I do even start this implementation I would be glad to hear it, same for suggestions about changes from the way that Twig works with it.

**Comment by dschissler** [comment]
I created [gettext-volt](https://github.com/perchlayer/gettext-volt) which integrates into [gettext-template](https://github.com/gmarty/xgettext) to provide gettext message extraction for Volt templates.
