### ISSUE TITLE
Model fields default values. Once again

### ISSUE THREAD

**Issue by quantum13** [phalcon/cphalcon#2620]
Related to https://github.com/phalcon/cphalcon/issues/109

I have model with some fields (not null, default values). Sometimes I want to create model with no setted fields (db default values must be setted), sometimes with setted values. 

If i use skipAttributes a can't create model with manual setting of this fields. Using new \Phalcon\Db\RawValue('default') each time is ugly (especially when u have many such fields).

As I understood main trouble in:

    I'm not sure what could be the best behavior in this case:
    $robot->name = null; // this must store null or the column's default?

Maybe ORM should track, field setted or not. If field setted (even if setted to null), it must using in sql query (insert and update), if not it must not used in this queries (in create queries will used default values, in update queries this fields will skipped).

PS For example django (greate python framework) have no such trouble, so phalcon also may be more beautifully

**Comment by andresgutierrez** [comment]
This is implemented in 2.0.2
