### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by SeeWatson** [phalcon/cphalcon#2641]
On this page: http://docs.phalconphp.com/en/latest/reference/tags.html

Under the Volt portion of "Generating Links," this code is shown as an example:

{{ link_to(['for': 'show-product', 'id': 123, 'name': 'carrots'], 'Show','class'=>'edit-btn') }}

It should read:
{{ link_to(['for': 'show-product', 'id': 123, 'name': 'carrots'], 'Show','class':'edit-btn') }}

...with a colon between class and the class name.

**Comment by Green-Cat** [comment]
This should be reported in the documentation repository, not this one.

**Comment by andresgutierrez** [comment]
Fixed in the docs
