### ISSUE TITLE
Uploaded Files bug

### ISSUE THREAD

**Issue by RaTm7** [phalcon/cphalcon#2643]
Hello,

i encountered few Days ago an Error in uploaded Files.

u have:
<input type="file" name="file[11]"/>
<input type="file" name="file[22]"/>

when u upload both or just the first, it works fine
but when u upload only the second one, u get only one File in Request::getUploadedFiles(), that is right, but this file get "file.1122" as key, not "file.22", as i would expect.

I solved it with JS for now, by disabling empty file-uploads, but thats not really a fix, its just "somehow it works for now".

Would be amazing if u could fix it. :)

So far, RaTm7

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
