### ISSUE TITLE
Can't define a route with optional parts

### ISSUE THREAD

**Issue by dedalozzo** [phalcon/cphalcon#2646]
To define a route that allows to match `/year/`, `/year/month/` and `/year/month/day/`, I would use a reg ex like this:

```php
$this->addGet('/([0-9]{4})/(?:([0-9]{2})/(?:([0-9]{2})/){0,1}){0,1}', ['action' => 'perDate', 'year' => 1, 'month' => 2, 'day' => 3]);
```

As you can see there are two non capturing groups and 3 capturing groups. The non capturing groups allow to make optionals both month and day. This is the way the route should be written. But Instead I have to use 3 different routes:

```php
$this->addGet('/([0-9]{4})/', ['action' => 'perDate', 'year' => 1]);
$this->addGet('/([0-9]{4})/([0-9]{2})/', ['action' => 'perDate', 'year' => 1, 'month' => 2]);
$this->addGet('/([0-9]{4})/([0-9]{2})/([0-9]{2})/', ['action' => 'perDate', 'year' => 1, 'month' => 2, 'day' => 3]);
```

This happens because Phalcon ignores the 3 capturing groups defined in the first reg ex.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
