### ISSUE TITLE
The Volt filter function is broken for my use case with gettext (but defining a helper function is not)

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#2651]
In my project I'm trying to unify gettext for both PHP and Javascript so that any front end for xgettext will scan them for translation IDs.  Currently I'm using Poedit and I find it to be a fully featured xgettext front end.

I successfully implemented the '[underscore]' helper function for translating and it looks like the following for the singular case: `{{ _('hello_world') }}` and `_('hello_world', 'hello_worlds', 5)` for the plural case.

It Volt compiler reatomizes it to the following format:
~~~
<?php echo $this->translate->gettext('hello_world'); ?>
<?php echo $this->translate->ngettext('hello_world', 'hello_worlds', 5); ?>
~~~

Then later xgettext scans through the compiled Volt files in `/tmp/supersecretprojectname-cache-0bcfc5b25b8f885a7906329ed577630d/volt` and picks it out.

So this is all good and I thought that I would add in a Volt translate filter function just for giggles and I've found that the function doesn't supply the proper information for me to be able to do this.  I need something like `function ($resolvedArgs, $exprArgs)` for the helper function.  The issue is that I need to know how many parameters the filter function supplies and it is all coming in as a string and when it is supplied as an string it looks like `'array(\'hello_world\', \'hello_worlds\', 5)'`.  I could play with that but I'd rather not be doing eval twice on it.  The second parameter in the filter function seems to always be null and it would be great if it provided something comparable to that of a helper function.

For those not intimate with gettext it I'll add that its CLI tool for gettext needs to be able to find specific functions that are the defaults or defined that either use the singular or plural form.  For this it needs to be able to see these specific functions either singular or plural specifically in a PHP file (which is what a compiled Volt template is).

I'll add as a commentary that it is rather fortunate that PHP works while being embedded in HTML as this allows me to use the PHP parser of xgettext on the compiled Volt templates without adding additional parser dependencies to my project.  Next step is Javascript which is also supported natively with xgettext and so I will be pointing xgettext at my compiled [webpack](http://webpack.github.io/) bundle.  There is a loader for webpack which allows me to compile Handlebar templates into my bundle with a single commonjs require.  I'll be needing to ensure that the output in the bundle ends up with hard coded strings that are supplied to gettext and ngettext functions.  Without this it will be impossible to have something to automate message string ID retrieval from both environments.  Hopefully it will be really slick and will unify the two environments.

Here is my initial draft of the translate with the '_' helper function.  I'm sure that it could be made prettier but it does the job for now:
~~~
$compiler->addFunction('_', function ($resolvedArgs, $exprArgs) {
    $count = count($exprArgs);
    if ($count === 1) {
        $str = sprintf('$this->translate->gettext(\'%s\')', $exprArgs[0]['expr']['value']);
    } else if ($count === 3) {
        $val1 = $exprArgs[0]['expr']['value'];
        $val2 = $exprArgs[1]['expr']['value'];
        $val3 = $exprArgs[2]['expr']['value'];
        $str = sprintf('$this->translate->ngettext(\'%s\', \'%s\', %d)', $val1, $val2, $val3);
    } else {
        $str = 'Volt Compiler Error for translation function.';
        error_log('Volt Compiler Error for translation function.');
    }

    return $str;
});
~~~

btw I stopped using the incubator Translation since it has an overly generic function called "query" and it simply supplies too much variety in the functions and I don't want to maintain the function parameter specs on those for each locale.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
