### ISSUE TITLE
afterExecuteRoute is never called for a controller, using Phalcon\Mvc\View\Simple

### ISSUE THREAD

**Issue by dedalozzo** [phalcon/cphalcon#2661]
I have replaced the standard View with Phalcon\Mvc\View\Simple:

```php
$di->setShared('view',
  function() use ($root, $config) {
    $view = new Simple();
    $view->setViewsDir($root.$config->application->viewsDir);
    $view->registerEngines(['.volt' => 'volt']);
    return $view;
  }
````

My bootstrap file is something like this:

```php
$application = new Application();

// Disable automatic rendering.
$application->useImplicitView(FALSE);

$application->setDI($di);
echo $application->handle()->getContent();
````

I have a `BaseController` class with a method `afterExecuteRoute`, in which I define the variable `year` using:

```php
$this->view->setVar('year', '2014');
```

`BaseController` has two subclasses: `IndexController` and `UserController`. When the second controller is triggered, it returns the following error:

```
Undefined variable: year
```

Everything works fine using the standard View component, but with `Phalcon\Mvc\View\Simple` only the `IndexController` works, like the `afterExecuteRoute` is never called for the `UserController`.

I forgot to mention, to display the route I use:

```php
echo $this->view->render('user', NULL);
```

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
