### ISSUE TITLE
[NFR] New Release Tag Format for Phalcon 2 Onwards

### ISSUE THREAD

**Issue by rushmorem** [phalcon/cphalcon#2674]
Phalcon 1 is using release tags that are in the form of `phalcon-v1.3.2`. I propose for Phalcon 2 onwards we change to format `v2.0.0`.

This makes it easy to manage Phalcon 2 using `composer`. Some say Composer is not well suited to managing PHP extensions but this is not totally true. Composer can run custom scripts, which makes it trivial to manage extensions using it.

**Comment by KorsaR-ZN** [comment]
Duplicate for #10066

**Comment by rushmorem** [comment]
The newer issue was the duplicate. In any case, this has since been fixed so it's no longer relevant. Closing now...
