### ISSUE TITLE
Multiple Issues - Cookies - delete and update both

### ISSUE THREAD

**Issue by acpadhi** [phalcon/cphalcon#2679]
PHP Version 5.5.9-1ubuntu4.3
Apache Version	Apache/2.4.7 (Ubuntu)
Phalcon Version	1.3.2

If the cookie domain is set, specially like .xyz.com to support *.xyz.com or httponly is set to true, then there are multiple issues with both deletes and updates.

1) if HTTP only is set to true, then further calls in next requests to the same cookie using 
$cookies->set() does not update the cookie or its values. Sometimes it does, but most of the times it does not. Not able to replicate the exact steps that make them work and what fail them, but tested using Firefox.
2) Delete cookies does not work either in the above conditions. In fact I could not just get delete to work properly at all.

For the time being, for all people who are having delete issues, you could probably use this to delete and it is verified to be working. 

You would need to send an expire in past time for it to delete. But how would one do that when an update is also not working properly. Worst case scenario, you would need to use PHP setcookie function directly.

Also, I would suggest to just forget using the cookies using Phalcon now, till the devs can make necessary corrections to take care of these silly but fundamentally deal breaking errors.

Also, please note the changes in order of the parameters - The domain and secured params are swapped from standard PHP. Why ? Intentional or documentation error ?

Phalcon : public Phalcon\Http\Response\Cookies set (string $name, [mixed $value], [int $expire], [string $path], [boolean $secure], [string $domain], [boolean $httpOnly])

Standard PHP : setcookie ( string $name [, string $value [, int $expire = 0 [, string $path [, string $domain [, bool $secure = false [, bool $httponly = false ]]]]]] )

Just fallback to using plain old PHP  code for the cookies and you will be much happier accessing them with those superglobals :) and setcookie to make modifications/deletion.

There simply are too many issues with the cookies based on the other issues list I see here. I think it may need a fresh take at it to see why there are so many issues with the cookies. Or at least attract a little bit more of the attention from the devs.

COOKIES are just way too fundamental to any framework and for that matter extremely basic to even the most simplest of applications. What is the use to use a framework if I cannot track my users effectively and efficiently ?

**Comment by Green-Cat** [comment]
@andresgutierrez Not a bug.
