### ISSUE TITLE
Phalcon\Config\Adapter\Php error with AOP

### ISSUE THREAD

**Issue by hu2008yinxiang** [phalcon/cphalcon#2684]
while use phalcon alone, it works fine, but when i enabled aop, there is an error.
I just find that there is #237 ,but the class is Phalcon\Config\Adapter\Php, my phalcon version is 1.3.2.
@phalcon i'll really appreciate for your reply.

and here is the Stack.
( ! ) Fatal error: Maximum function nesting level of '100' reached, aborting! in /vagrant_data/poker_php/www/app/config/config.php on line 7 
Call Stack 
# Time Memory Function Location 
1 0.0285 268272 {main}( ) ../micro.php:0 
2 0.0288 273968 __construct ( ??? ) ../micro.php:7 
3 0.0363 275096 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
4 0.0389 275432 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
5 0.0412 275768 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
6 0.0435 276104 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
7 0.0478 276440 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
8 0.0502 276776 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
9 0.0522 277112 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
10 0.0541 277448 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
11 0.0557 277784 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
12 0.0573 278120 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
13 0.0590 278456 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
14 0.0605 278792 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
15 0.0624 279128 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
16 0.0640 279464 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
17 0.0657 279800 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
18 0.0670 280136 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
19 0.0680 280472 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
20 0.0691 280808 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
21 0.0702 281144 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
22 0.0716 281480 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
23 0.0731 281816 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
24 0.0747 282152 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
25 0.0775 282488 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
26 0.0794 282824 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
27 0.0819 283160 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
28 0.0836 283496 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
29 0.0853 283832 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
30 0.0868 284168 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
31 0.0883 284504 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
32 0.0899 284840 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
33 0.0914 285176 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
34 0.0945 285512 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
35 0.0960 285848 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
36 0.0975 286184 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
37 0.0991 286520 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
38 0.1010 286856 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
39 0.1024 287192 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
40 0.1035 287544 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
41 0.1046 287880 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
42 0.1058 288216 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
43 0.1080 288552 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
44 0.1109 288888 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
45 0.1128 289224 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
46 0.1144 289560 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
47 0.1160 289896 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
48 0.1176 290232 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
49 0.1190 290568 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
50 0.1207 290904 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
51 0.1227 291240 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
52 0.1256 291576 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
53 0.1273 291912 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
54 0.1286 292248 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
55 0.1299 292584 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
56 0.1315 292920 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
57 0.1330 293256 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
58 0.1351 293592 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
59 0.1369 293928 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
60 0.1388 294264 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
61 0.1414 294600 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
62 0.1432 294936 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
63 0.1446 295272 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
64 0.1460 295608 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
65 0.1473 295944 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
66 0.1490 296280 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
67 0.1504 296616 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
68 0.1519 296952 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
69 0.1542 297288 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
70 0.1570 297624 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
71 0.1587 297960 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
72 0.1606 298296 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
73 0.1619 298632 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
74 0.1634 298968 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
75 0.1650 299304 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
76 0.1665 299640 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
77 0.1680 299976 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
78 0.1703 300312 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
79 0.1724 300648 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
80 0.1741 300984 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
81 0.1758 301320 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
82 0.1777 301656 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
83 0.1793 301992 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
84 0.1810 302328 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
85 0.1822 302664 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
86 0.1838 303000 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
87 0.1861 303336 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
88 0.1876 303672 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
89 0.1892 304008 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
90 0.1904 304344 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
91 0.1918 304680 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
92 0.1934 305016 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
93 0.1949 305352 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
94 0.1963 305688 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
95 0.1975 306024 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
96 0.1990 306360 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
97 0.2022 306696 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
98 0.2044 307032 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7 
99 0.2062 307368 Phalcon\Config\Adapter\Php->__construct( ??? ) ../micro.php:7

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2.0.0
