### ISSUE TITLE
Phalcon v1.3.2 Memory leak in Phalcon\Mvc\Model::findFirst

### ISSUE THREAD

**Issue by temafey** [phalcon/cphalcon#2705]
In phalcon version 1.3.2 if I'm using in loop this function, script leak more memory each time
```php
function getRow($id) {
   $model = new \Model\Mysql\Mymodel();
   $model->setReadConnectionService($adapter);
   $model->setWriteConnectionService($adapter);
   $row = $model->findFirst(["id = '".$id."'", 'order' => "taken_at DESC"]);
}
```
for other versions the same problem

**Comment by quantum13** [comment]
2.0:
```php
    for($i=0;$i<100000;$i++) {
            $cat = new Category();
            // setting attributes..
            $cat->save();
    }
```
Memory usage grows on every iteration. Maybe models caches somewhere in manager? How to disable it?

**Comment by wolftail** [comment]
my version is 2.0.7, run in cli mode, still leak memory. my code is :
$max_video = Videos::findFirst(array('order' => 'id desc'));
        $max_video_id = $max_video->id;
        $video_id = 1;
        $video = null;
        $begin_memory = memory_get_usage() / 1024;
        while (true) {
            $video = Videos::findFirst(array('conditions' => 'id  = ' . $video_id));
            $video = null;
            unset($video);
            $video_id++;
            echoLine('use memory ' . memory_get_usage() / 1024);
            if ($video_id > $max_video_id) {
                break;
            }

        }
        $end_memory = memory_get_usage() / 1024;
        echoLine('begin memory ' . $begin_memory . ' end memory ' . $end_memory);

**Comment by wolftail** [comment]
but findFirstById is ok

**Comment by wolftail** [comment]
$video = Videos::findFirst(array('conditions' => 'id  =  :id: ', 'bind'=>array('id' => $video_id)));
is still ok? what happen in findFirst?

**Comment by dercoder** [comment]
I have the same issue.
"findFirstById" works great but "findFirst" uses to much memory.
Phalcon 2.0.9
PHP 5.6.14

**Comment by phalcon** [comment]
Someone please read this: http://docs.phalconphp.com/en/latest/reference/models-cache.html#caching-of-phql-planning

If you use constants instead of bound parameters in your PHQL it creates a new planning consuming more memory

**Comment by KrisvanWaterschoot** [comment]
I have a case where it's not possible to put the phql outside the wile loop. I'm using a process manager which launches pieces of code after a predefined number of seconds. This specific code cannot be placed outside the wile loop to reduce memory usage, it's also not a good and clean solution.

The clearing of objects in memory is crucial for our framework to choose for Phalcon or another PHP framework..

Can you please provide a better solution?

**Comment by seliver** [comment]
Binding variables did solved my memory leak. Thanks @phalcon .

**Comment by alanbarber111** [comment]
@phalcon I have a situation where we are using the query builder in combination with another layer of abstraction.

It's not possible to use bound parameters - is there no way to disable the parser cache at run time?

**Comment by nsossonko** [comment]
I don't think this should be closed as "not a bug". It is clearly a bug. While there is a workaround, the underlying problem still exists. PHQL caching should not be endless, eventually starving the system of memory completely...

**Comment by Jurigag** [comment]
First of all - this 1.x and 2.x is not supported anymore. Second - ony 3.x when using bind parameters there is no such a problem like memory leak.

**Comment by nsossonko** [comment]
I'm talking 3.x (my issue #12456 was duped to here). There is a memory leak when not using bound parameters and, even when using bound parameters, there can be a memory leak if there are very many different queries based on other elements. Both issues are bugs that, while maybe not urgent, are valid.
