### ISSUE TITLE
Testing ModelsCalculationsTest

### ISSUE THREAD

**Issue by hexogen** [phalcon/cphalcon#2709]
UnitTest failed on:
Testing ModelsCalculationsTest Literals are disabled in PHQL statements
#0 [internal function]: Phalcon\Mvc\Model\Query->parse()
#1 [internal function]: Phalcon\Mvc\Model\Query->execute(NULL, NULL)
#2 [internal function]: Phalcon\Mvc\Model::_groupResult('COUNT', 'rowcount', 'estado='A'')
#3 /home/user/Builds/cphalcon/unit-tests/ModelsCalculationsTest.php(137): Phalcon\Mvc\Model::count('estado='A'')
#4 /home/user/Builds/cphalcon/unit-tests/ModelsCalculationsTest.php(77): ModelsCalculationsTest->_executeTestsNormal(Object(Phalcon\DI))
#5 /home/user/Builds/cphalcon/unit-tests/manual-unit.php(133): ModelsCalculationsTest->testCalculationsMysql()
#6 /home/user/Builds/cphalcon/unit-tests/manual-unit.php(176): PHPUnit_Framework_TestCase::main('ModelsCalculati...')
#7 {main}

Environment:
OS: Ubuntu 14.04 x64
Server: Apache 2.4
Phalcon: 1.3.2
CPU: i5 4690k

**Comment by hexogen** [comment]
$ phpunit --debug -c unit-tests/phpunit.xml
PHPUnit 3.7.9 by Sebastian Bergmann.

Configuration read from /home/hexogen/Builds/phalcon/cphalcon/unit-tests/phpunit.xml


Starting test 'AnnotationsAdaptersTest::testMemoryAdapter'.
.
Starting test 'AnnotationsAdaptersTest::testFilesAdapter'.
.
Starting test 'AnnotationsAdaptersTest::testApcAdapter'.
S
Starting test 'AnnotationsAdaptersTest::testXcacheAdapter'.
S
Starting test 'AnnotationsTest::testParser'.
.
Starting test 'AnnotationsTest::testParserNoClass'.
.
Starting test 'AnnotationsTest::testReflection'.
.
Starting test 'ApplicationMvcTest::testApplicationSingleModule'.
.
Starting test 'ApplicationMvcTest::testApplicationModulesDefinition'.
.
Starting test 'ApplicationMvcTest::testApplicationModulesDefinitionClosure'.
.
Starting test 'BeanstalkTest::testBasic'.
S
Starting test 'BeanstalkTest::testReleaseKickBury'.
S
Starting test 'CacheResultsetTest::testCacheResultsetNormal'.
.
Starting test 'CacheResultsetTest::testCacheResultsetBinding'.
.
Starting test 'CacheResultsetTest::testCacheResultsetSimple'.
.
Starting test 'CacheResultsetTest::testCacheResultsetSimpleNoComplete'.
.
Starting test 'CacheResultsetTest::testCacheResultsetSimpleNoComplex'.
.
Starting test 'CacheResultsetTest::testCacheResultsetSimpleMemcached'.
.
Starting test 'CacheResultsetTest::testCacheResultsetSimpleLibmemcached'.
Segmentation fault (core dumped)

**Comment by hexogen** [comment]
With phpunit 4.4 i can't launch tests.

**Comment by hexogen** [comment]
phalcon 2.0.0

**Comment by andresgutierrez** [comment]
This is now fixed in 2.0.0
