### ISSUE TITLE
[NFR] #Volt Improve variable dot notation

### ISSUE THREAD

**Issue by ebuildy** [phalcon/cphalcon#2712]
I understand in Volt

```
item.title
```

Will render PHP:

```
$item->title
```

And I know it's already possible to use item['title'] for associative array. But, as a lazy programmer (should I say just a programmer ^^), I would like to use the same notation for both (like Twig does, but without an extra function call).

What I suggest is to have an option to choice if dot notation will render as object or associative array fashion. This option could be "dynamic", so in a template you could mix object and associative array property retrieval without changing VOLT notation.

For those who want to "hardcode" the dot notation behavior, you can edit https://github.com/phalcon/cphalcon/blob/master/ext/mvc/view/engine/volt/compiler.c, remove line 709 (the line that adds the ->) and edit like this :

```
phalcon_concat_self_str(&expr_code, SL("['") TSRMLS_CC);

    PHALCON_OBS_VAR(right);
    phalcon_array_fetch_quick_string(&right, expr, SS("right"), 6953978916291UL, PH_NOISY);

    PHALCON_OBS_VAR(right_type);
    phalcon_array_fetch_quick_string(&right_type, right, SS("type"), 210729590247UL, PH_NOISY);
    if (PHALCON_IS_LONG(right_type, PHVOLT_T_IDENTIFIER)) {
            PHALCON_OBS_VAR(member);
            phalcon_array_fetch_quick_string(&member, right, SS("value"), 6954126163842UL, PH_NOISY);
            phalcon_concat_self(&expr_code, member TSRMLS_CC);
    } else {
            PHALCON_CALL_METHOD(&right_code, this_ptr, "expression", right);
            phalcon_concat_self(&expr_code, right_code TSRMLS_CC);
    }

    phalcon_concat_self_str(&expr_code, SL("']") TSRMLS_CC);

    RETURN_CCTOR(expr_code);
```
##

**Comment by JCMais** [comment]
+1 for that, however I don't see how that can be implemented with the current code generation.

**Comment by Green-Cat** [comment]
:+1:
