### ISSUE TITLE
beanstalk doc improvements

### ISSUE THREAD

**Issue by AndreBaumeier** [phalcon/cphalcon#2713]
http://docs.phalconphp.com/en/latest/reference/queue.html

although put() method is calling serialize internally on the first parameter - looked it up in the c source (https://github.com/phalcon/cphalcon/blob/master/ext/queue/beanstalk.c#L264). I don't think that this should serve as a good example. The function docs themselves state put(String $data) as well, so another mismatch which confused me in the first place.

Also I guess it will be pretty complicated for other non php + non phalcon environments to decode the serialized php array. I think it would be better to put a simple json_encode here in the docs instead of showing some ugly magic.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
