### ISSUE TITLE
Router placeholder regex and non latin characters

### ISSUE THREAD

**Issue by peuh** [phalcon/cphalcon#2714]
Hi All,
I have an issue with the annotation router. 
Consider the following annotation on a controller action : 

```php
/**
 *@Route("/{slug:[\p{L}\p{N}\-]+}", methods={"GET"}, name="core_index_page")
 */
public function pageAction($slug)
{
     //do some stuff
}
```

While it works fine with latin characters, the router never match slugs made of non latin characters. For example : `example.com/древесное` is considered not found.

The string древесное should match the regex` [\p{L}\p{N}\-]+`

Strange thing : `\W` match it (`\W` : non word character)

Am I doing something the wrong way or is it a bug? 

Environment info : 
all locales installed.
Phalcon 1.3.2
PHP version 5.5.15-1
PHP default encoding : utf8
Server : Nginx
OS : Debian 7 

PS : Congrats to the Phalcon team for the awesome job you're doing :-)

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2.0.6
