### ISSUE TITLE
Override magic __get in Session\Adapter\Files and in Session\Bag 1.3.3

### ISSUE THREAD

**Issue by Druid33** [phalcon/cphalcon#2735]
In phalcon 1.2.6 it was not possible override magic getter and setter in Session\Adapter\Files and Session\Bag. (...or it's only me, who don't know how? :) )

Now in 1.3.3 i see, that i can override  magic setter, but not magic getter. 

Is it bug or feature? :)

I ask, because i need to do some operation before and after reading data from session.

Thanks

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2
