### ISSUE TITLE
[NFR] More flexible routing system with optional parameters

### ISSUE THREAD

**Issue by AmazingDreams** [phalcon/cphalcon#2758]
The current routing system requires you to define routes like this.

```
$router->add('/:controller/:action/:params, array(
    'controller' => 1,
    'actions'     => 2,
    'params'     => 3,
));
```

Though if I want the ':action' parameter to be optional I have to create a new route

```
$router->add('/:controller', array( .... ));
```

I think it would be a huge improvement if I were able to define optional parameters in a manner similar to this.

```
$router->add('/(:controller(/:action(/:params)))', array( ... ));
```

This is currently not possible as the `()` would be interpreted as regex.
A solution would be to separate the route from the regex and then set some default values to use when a parameter is not present. EG:

```
$router->add('/(:controller(/:action(/:params)))', array(
   ':controller' => '<regex-for-controller>',
   ':action'      => '<regex-for-action>',
))->defaults(array(
   ':controller' => 'index',
   ':action'      => 'index',
));
```

It would be great is something like this could be added
Note: I 'borrowed' the above proposal from Kohana's routing system http://kohanaframework.org/3.3/guide/kohana/routing
##

**Comment by tmihalik** [comment]
+1

**Comment by f3l1x** [comment]
:+1:

**Comment by sergeyklay** [comment]
+1

**Comment by sszdh** [comment]
nice shoot...

**Comment by googlle** [comment]
+1
