### ISSUE TITLE
creating model with force

### ISSUE THREAD

**Issue by verma-neeraj-in** [phalcon/cphalcon#2763]
After creating model using dev tool. If we change the structure of our table and forcefully create the model again using dev tool. It will duplicate the columnMap function in the model. Which will generate the  internal sever error.

![phalconbug](https://cloud.githubusercontent.com/assets/5779289/4113903/1bc58d8c-325b-11e4-9e93-9986251d9c09.png)

**Comment by verma-neeraj-in** [comment]
All information is already there, no class can have two functions with same name and its happening here with columnMap() while creating this model using dev-tools

**Comment by sergeyklay** [comment]
Already fixed in Devtools
