### ISSUE TITLE
Add HTTP Status Codes constants to Phalcon\Http\ResponseInterface

### ISSUE THREAD

**Issue by smilesrg** [phalcon/cphalcon#2777]
Add HTTP Status Codes constants to Phalcon\Http\ResponseInterface to be able to use it like ```ResponseInterface::HTTP_STATUS_CREATED```

For example:
```php
$response->setStatusCode(ResponseInterface::HTTP_STATUS_CREATED, "Created");
```

instead of 
```php
$response->setStatusCode(201, "Created");
```

**Comment by cnelissen** [comment]
+1 It makes no sense to have to specify the content since they are well defined.

It would be nice to just be able to write things like:
```
$response->setStatusCode(ResponseInterface::HTTP_STATUS_200);
$response->setStatusCode(ResponseInterface::HTTP_STATUS_404);
```

**Comment by smilesrg** [comment]
Why not ```ResponseInterface::HTTP_NOT_FOUND``` or ```ResponseInterface::HTTP_404_NOT_FOUND``` ?

**Comment by golovanov** [comment]
-1

**Comment by smilesrg** [comment]
@golovanov @sergeyklay Oh, come on guys! This is a magic number code smell
https://refactoring.com/catalog/replaceMagicNumberWithSymbolicConstant.html
See how it's done in Symfony framework
http://api.symfony.com/3.2/Symfony/Component/HttpFoundation/Response.html

This can add extra benefit to search via "Found usages" in IDE.

**Comment by sergeyklay** [comment]
@smilesrg 

Whenever a C program (C extension) is executed some memory is allocated in the RAM for the program execution. This memory is used for storing the frequently executed code (binary data), program variables etc. Below memory segments talks about same:

+ Local variables (also called as automatic variables in C)
+ Global variables
+ Static variables
+ You can have global static or local static variables but above 3 are parent types

This feature request has negative side - for each constant memory will be allocated in **each request startup**. Basically, in the low level, a constant is stored in RAM memory and created after launching your application, it always has an address in RAM. Even if you never use this constant.

Note: C !== PHP

**Comment by smilesrg** [comment]
@sergeyklay thanks for a great explanation!

**Comment by sergeyklay** [comment]
Depends on server architecture. The status codes already are constants. It is unlikely that they ever will be changed. Probably never. For examle:

```php
if ($request->getStatusCode() === 403) {
}
```

the same as:
```php
if ($request->getStatusCode() === \Phalcon\Http\Request::STATUS_FORBIDDEN) {
}
```

These two examples are identical. In both cases, the values are constants. But in the first case, your code is more concise
