### ISSUE TITLE
Create library for generating routes in javascript

### ISSUE THREAD

**Issue by smilesrg** [phalcon/cphalcon#2779]
There is no possibility for generating routes in Javascript. Could you add some tools for this?
##

**Comment by lubberscorrado** [comment]
+1

**Comment by Jurigag** [comment]
What's wrong with https://docs.phalconphp.com/pl/latest/reference/url.html ?

**Comment by smilesrg** [comment]
@Jurigag it's PHP part, but we need Javascript routing generator.

**Comment by Jurigag** [comment]
What you mean javascript routing generator ? Just call url in volt in `<script>` tag

**Comment by smilesrg** [comment]
@Jurigag it isn't possible to call url inside ```<script>``` tag dynamically (during runtime).

```
$url->get(
    [
        "for"   => "all-posts",
        "year"  => "2015",
    ]
);
```

Imagine that this route should be generated dynamically. E.g. user selects a year and posts should be reloaded using Ajax.

**Comment by Jurigag** [comment]
Well keep in mind that phalcon is php framework, not js framework.

**Comment by smilesrg** [comment]
@Jurigag probably you understand this feature request wrong.

**Comment by Jurigag** [comment]
Then can you explain it ?
