### ISSUE TITLE
Problem with MySQL database connection

### ISSUE THREAD

**Issue by ahmedkamals** [phalcon/cphalcon#2796]
If the password contains "@", e.g. "p@ssword", an exception is thrown.

SQLSTATE[28000] [1045] Access denied for user 'test'@'localhost' (using password: YES)

**Comment by andresgutierrez** [comment]
Can you try again using latest Phalcon 2.0.5?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
