### ISSUE TITLE
Aggregate options - PECL Mongo 1.5.0

### ISSUE THREAD

**Issue by vinixhenri** [phalcon/cphalcon#2803]
By virtue of a new parameter in the aggregate method in PECL Mongo 1.5.0, some options like 'allowDiskUse' and 'cursor' cannot be used in Phalcon due to its aggregate function does not accept more than one parameter.
##

**Comment by sergeyklay** [comment]
We don't support Mongo anymore. We'll try to implement the new driver support but anyway it is different issue.
