### ISSUE TITLE
Phalcon segfault php-fpm

### ISSUE THREAD

**Issue by tunh** [phalcon/cphalcon#2809]
I'm using phalcon 1.3.2, php-fpm 5.5.16 (remi package), centos 6.5.
Nginx frequently return the error "502 bad gateway".

Nginx error log:
2014/09/12 11:57:19 [error] 26060#0: *82 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: <ipaddrress>, server: <domain>, request: "POST <request> HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "<domain>", referrer: "<domain>"

Php-fpm error log:
[12-Sep-2014 11:57:19] WARNING: [pool www] child 26045 exited on signal 11 (SIGSEGV) after 82.764425 seconds from start
[12-Sep-2014 11:57:19] NOTICE: [pool www] child 26079 started

CentOS syslog:
Sep 12 11:57:19 CentOS kernel: php-fpm[26045]: segfault at 18 ip 000000000058d839 sp 00007fff9460e130 error 4 in php-fpm[400000+323000]

I think it's a bug in Phalcon 1.3.x core. Someone has the same issue https://github.com/phalcon/cphalcon/issues/2516
##

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as 1.3.x is no longer supported

**Comment by Jurigag** [comment]
So `Request::getHeaders()` is causing this? Need to check this on 3.0.x.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
