### ISSUE TITLE
migration problem with TIMESTAMP columns

### ISSUE THREAD

**Issue by yonexyonex** [phalcon/cphalcon#2850]
The command `phalcon migration generate` mapped TIMESTAMP (MySQL) columns to `TYPE_DATE`.
`phalcon migration run` creates a new table with those columns as DATE columns.
http://docs.phalconphp.com/en/latest/api/Phalcon_Db_Column.html
I think `TYPE_TIMESTAMP` may be needed

**Comment by akudryav** [comment]
you may use string 'TIMESTAMP' in 'type' => values for the column instead of phalcon constant Column::TYPE_...

**Comment by sergeyklay** [comment]
@yonexyonex Now Phalcon supports `Column::TYPE_TIMESTAMP`

**Comment by yonexyonex** [comment]
Great, thanks!
