### ISSUE TITLE
[BUG] Wrong value variable of _activeRenderPath in event handler 'view:afterRenderView' in hierarchical mode render.

### ISSUE THREAD

**Issue by InteLigent** [phalcon/cphalcon#2855]
Example:

<pre>
$view = new View();
$view->setLayoutsDir('layouts/')
 ->setPartialsDir('partials/')
 ->disableLevel(View::LEVEL_MAIN_LAYOUT)
 ->registerEngines([".volt" => 'volt'])
->setLayout('main');

$eventsManager->attach("view", function($event, $view)  {
    echo $view->getCurrentRenderLevel() . ' ' . $event->getType() . ' - ' . $view->getActiveRenderPath();
});
</pre>

Output:

<pre>
LEVEL_NO_RENDER      beforeRender -                                                                                                                  
LEVEL_ACTION_VIEW    beforeRenderView - /var/www/phalcon/public/views/Index/index.volt                                       
LEVEL_ACTION_VIEW    beforeRenderView - /var/www/phalcon/public/views/partials/index.volt                           
LEVEL_ACTION_VIEW    afterRenderView - /var/www/phalcon/public/views/partials/index.volt                            
LEVEL_ACTION_VIEW    afterRenderView - /var/www/phalcon/public/views/partials/index.volt                            
LEVEL_LAYOUT         beforeRenderView - /var/www/phalcon/public/views/layouts/main.volt                             
LEVEL_LAYOUT         beforeRenderView - /var/www/phalcon/public/views/partials/menu/portal/head_control_panel.volt  
LEVEL_LAYOUT         afterRenderView - /var/www/phalcon/public/views/partials/menu/portal/head_control_panel.volt   
LEVEL_LAYOUT         beforeRenderView - /var/www/phalcon/public/views/partials/portal_header.volt                   
LEVEL_LAYOUT         afterRenderView - /var/www/phalcon/public/views/partials/portal_header.volt                    
LEVEL_LAYOUT         afterRenderView - /var/www/phalcon/public/views/partials/portal_header.volt                    
LEVEL_NO_RENDER      afterRender - /var/www/phalcon/public/views/partials/portal_header.volt
</pre>

##

**Comment by sergeyklay** [comment]
I want to close this issue because the `1.3.x` branch is not longer supported and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
