### ISSUE TITLE
Email validator passes on abc@abc

### ISSUE THREAD

**Issue by rzajac** [phalcon/cphalcon#2869]
As in the title. When you do validation in model like this:

```
$this->validate(new Email(['field' => 'email']));
```

It will pass.

**Comment by sergeyklay** [comment]
rzajac@localhost strictly follow the RFC 2822 ;)

**Comment by Jurigag** [comment]
How about check mx flag ? @sergeyklay

**Comment by sergeyklay** [comment]
It is slow, not always true and can be implemented separately

**Comment by Jurigag** [comment]
Yea i know, but by default it could be just false maybe ? Well i know not always true, but still better than abc@abc.

**Comment by sergeyklay** [comment]
root@localhost is vlalid email address and most likely mx check returns true

**Comment by Jurigag** [comment]
Then what's wrong ? :D Or maybe you mean false ? Then we can check first if it's localhost = dont check mx.

**Comment by sergeyklay** [comment]
But abcde@myawesomehost it correct too

**Comment by Jurigag** [comment]
What about: abcde@abc.xyz ?

**Comment by sergeyklay** [comment]
This is why mx check does not have to be integrated to the email validator. At least at this time

**Comment by sergeyklay** [comment]
```php
exec(sprintf('dig -t MX %s +noall +answer +short +time=1', escapeshellarg($sanitizedDomain)), $result);

return  !empty($result);
```
