### ISSUE TITLE
[NFR] Support join for aggregations helpers such as COUNT, SUM, AVERAGE,...

### ISSUE THREAD

**Issue by redstrike** [phalcon/cphalcon#2870]
I want to do something like this:

```php
    $count = MediaDataSearch::count([
        'join' => 'MediaData d',
        "conditions" => 'm_title_search LIKE ?0 AND (d.m_cat = 2 OR d.m_cat != 2 AND d.m_type = 2)',
        'bind' => ['%'.$keyword.'%']
    ]);
```

But Phalcon 1.3.2 doesn't support join in this method. I think this will be a useful improvement for those helpers. At this moment, I have to build query manually to accomplish this.
##

**Comment by Jurigag** [comment]
Or `::query`. Well im not sure if this should be implemented though.
