### ISSUE TITLE
Rendering a Simple view throught the typical voltService will break layouts

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#2872]
I've found that I need to create a lamba function like this

```
$voltService = function($view, $di) {
    ...
}
```

and then feed it into the voltService DI like this:

```
$di->set('voltService', $voltService);
```

Then I can pass the `$voltService variable into a `viewSimple` service like this:

```
$di->set('viewSimple', function($simplePath = false) use ($di, $voltService) {
    $view = new ViewSimple();
    // NOTICE that its taking $voltService and not `voltService`
    $view->registerEngines([
        '.volt' => $voltService
    ]);
    ...
```

So all of this appears necessary because I found that my mailer that uses Simple Views to render Volt email templates will cause the main controller::action view to not display layouts.

It would be great if someone familiar with the source could check if a long running voltService gets confused when a simple view is passed in.  This appears to be a bug that could/should be changed to remove some assumptions.

I'm currently using a shared voltService to render all of the parts so that it doesn't need to reload every time a new view is created.  I'm creating a new Volt object for simple views since it will not be very common and its the only work around that I've found.

**Comment by sergeyklay** [comment]
@dschissler

**Comment by dschissler** [comment]
So just so that I'm sure of it the "use a closure" solution is the same as my `lamda` solution?  I've had this working for a few years now with `$voltService = function($view) { ` ...

**Comment by dschissler** [comment]
Perhaps we could solve this with just a little bit of convention changes in our documentation and example projects?

When we make our normal views:

```php
$view->registerEngines([
    '.volt'  => 'voltShared'
]);
```

```php
$di->setShared('voltShared', function($view) {
    return $this->getVolt($view);
});

$di->set('volt', function ($view) {
    $volt = new VoltEngine($view, $this);
    ...
});
```

**Comment by dschissler** [comment]
I'm closing this issue because it is something that can easily be solved by adopting the above `volt`, `voltShared` convention.
