### ISSUE TITLE
[NFR] Don't show first record if params is null with findFirst()

### ISSUE THREAD

**Issue by kpitn** [phalcon/cphalcon#2873]
When you use `Admin::findFirst($id)` and don't test if $id is > 0, you have the first record.

`Admin::findFirst(NULL)` must return null value.

http://forum.phalconphp.com/discussion/3563/findfirst-null-dangerous#C11809

**Comment by Green-Cat** [comment]
This is expected behaviour because findFirst(null) is meant to return the first record, without applying any conditions.
