### ISSUE TITLE
[v1.3.3] $this->security->checkToken returns false when use session_name()

### ISSUE THREAD

**Issue by stano1** [phalcon/cphalcon#2876]
I found this bug, when you changed session_name by using function session_name, Function $this->security->checkToken() always return false.

Please check.
##

**Comment by andresgutierrez** [comment]
Could you please try again using latest 2.0.x?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
