### ISSUE TITLE
[BUG] 1.3.3 & 1.3.2 Phalcon\Dispatcher::setParams() doesn't work

### ISSUE THREAD

**Issue by yankos** [phalcon/cphalcon#2886]
...
$dispatcher->setControllerName('Foo');
$dispatcher->setActionName('bar');
$dispatcher->setParams([ 'param1' => 'value1', 'param2' => 'value2']);
var_dump($dispatcher->getParams()); // Output array - Ok
$dispatcher->dispatch();
....

Foo::barAction($param1, $param2)
{
    echo $param1; // Output 'value1' - Ok
    echo $param2; // Output 'value2' - Ok
    echo $this->dispatcher->getParams() - // Output is empyt - Error
    echo $this->dispatcher->getParam('param1') - // Output is empyt - Error
}

As result cann't set params for HMVC request
Code based on https://github.com/phalcon/mvc/tree/master/hmvc

**Comment by andresgutierrez** [comment]
Can you please try again using Phalcon 2?
