### ISSUE TITLE
View::render returns false instead of this

### ISSUE THREAD

**Issue by ianbytchek** [phalcon/cphalcon#2896]
During the view rendering if its disabled and in some other cases the returned value is `false` instead of `$this`, which breaks chaining. That's not the expected behaviour. I found it only [here](https://github.com/phalcon/cphalcon/blob/master/ext/mvc/view.c#L1180) and [here](https://github.com/phalcon/cphalcon/blob/master/ext/mvc/view.c#L1265):

``` c
/** 
 * If the view is disabled we simply update the buffer from any output produced in
 * the controller
 */
PHALCON_OBS_VAR(disabled);
phalcon_read_property_this(&disabled, this_ptr, SL("_disabled"), PH_NOISY TSRMLS_CC);
if (PHALCON_IS_NOT_FALSE(disabled)) {
    PHALCON_INIT_VAR(contents);
    phalcon_ob_get_contents(contents TSRMLS_CC);
    phalcon_update_property_this(this_ptr, SL("_content"), contents TSRMLS_CC);
    RETURN_MM_FALSE;
}

/** 
 * Call beforeRender if there is an events manager
 */
if (Z_TYPE_P(events_manager) == IS_OBJECT) {
    PHALCON_INIT_VAR(event_name);
    ZVAL_STRING(event_name, "view:beforeRender", 1);
    PHALCON_CALL_METHOD(&status, events_manager, "fire", event_name, this_ptr);
    if (PHALCON_IS_FALSE(status)) {
        RETURN_MM_FALSE;
    }
}
```
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
