### ISSUE TITLE
[BUG] [1.3.3] [PHP 5.6] Cache serialization failure

### ISSUE THREAD

**Issue by ykurtbas** [phalcon/cphalcon#2907]
Working perfectly with 1.3.2. Since the 1.3.3 upgrade I get "Invalid serialization data"

<pre>
class Test extends Model
{
.......
public function test($test)
    {
        return self::query()
            ->cache(['key' => 'test')
            ->where('CustomerNo = :customerno:')
            ->bind(['customerno' => $test])
            ->execute();
    }
}
</pre>

If I disable the cache, framework resumes normal operations.

Thanks.

**Comment by andresgutierrez** [comment]
Can you try again using Phalcon 2.0.3?

**Comment by ykurtbas** [comment]
Seems like working with 2.0.3, no segfault
