### ISSUE TITLE
Errors on Phalcon 2 build

### ISSUE THREAD

**Issue by Mech7** [phalcon/cphalcon#2910]
I am getting the following errors when trying to build phalcon 2

Warning: Class "APCIterator" does not exist at compile time  in /home/chris/www/cphalcon/phalcon/cache/backend/apc.zep on 224 [nonexistent-class]

	   apc = new \APCIterator("user", prefixPattern);
	------------------------------------------------^

Warning: Function "mcrypt_get_iv_size" does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 334 [nonexistent-function]

	  let ivSize = mcrypt_get_iv_size(cipher, mode);
	-----------------------------------------------^

Warning: Function "mcrypt_create_iv" does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 340 [nonexistent-function]

	  let iv = mcrypt_create_iv(ivSize, MCRYPT_RAND);
	------------------------------------------------^

Warning: Constant 'MCRYPT_RAND' does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 340 [nonexistent-constant]

	  let iv = mcrypt_create_iv(ivSize, MCRYPT_RAND);
	-----------------------------------------------^

Warning: Function "mcrypt_get_block_size" does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 345 [nonexistent-function]

	  let blockSize = mcrypt_get_block_size(cipher, mode);
	-----------------------------------------------------^

Warning: Function "mcrypt_encrypt" does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 358 [nonexistent-function]

	  return iv . mcrypt_encrypt(cipher, encryptKey, padded, mode, iv);
	------------------------------------------------------------------^

Warning: Function "mcrypt_get_iv_size" does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 392 [nonexistent-function]

	  let ivSize = mcrypt_get_iv_size(cipher, mode);
	-----------------------------------------------^

Warning: Function "mcrypt_decrypt" does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 404 [nonexistent-function]

	  let decrypted = mcrypt_decrypt(cipher, decryptKey, substr(text, ivSize), mode, substr(text, 0, ivSize));
	---------------------------------------------------------------------------------------------------------^

Warning: Function "mcrypt_get_block_size" does not exist at compile time in /home/chris/www/cphalcon/phalcon/crypt.zep on 406 [nonexistent-function]

	  let blockSize = mcrypt_get_block_size(cipher, mode);
	-----------------------------------------------------^

Warning: Possible attempt to use non-object in "new" operator in /home/chris/www/cphalcon/phalcon/mvc/model.zep on 584 [non-valid-new]

	   let hydrate = new \stdclass();
	--------------------------------^

Warning: Function "phalcon_orm_singlequotes" does not exist at compile time in /home/chris/www/cphalcon/phalcon/mvc/model/query.zep on 512 [nonexistent-function]

	       let escapedValue = phalcon_orm_singlequotes(value);
	---------------------------------------------------------^

Warning: Variable 'sqlJoinConditions' was assigned for the first time in conditional branch, consider initialize it at its declaration in /home/chris/www/cphalcon/phalcon/mvc/model/query.zep on 936 [conditional-initialization]

	  ];
	--^

**Comment by sergeyklay** [comment]
@Mech7 If you are __enabled__ APC and still see warrning:
```
apc = new \APCIterator("user", prefixPattern);
```
add to your `apcu.ini` file `apc.enable_cli = On`:

```ini
; File /etc/php5/mods-available/apcu.ini
extension=apcu.so

apc.enable_cli = On
````

**Comment by sergeyklay** [comment]
Hi @phalcon  
I keep getting some warnings.

```bash
$ git status
On branch 2.0.0
Your branch is up-to-date with 'origin/2.0.0'.

nothing to commit, working directory clean

$ git branch 
* 2.0.0
  master

$ git pull
Already up-to-date.

$ whereis zephir
zephir: /usr/local/bin/zephir

$ zephir generate
Warning: Class "Phalcon\Http\ViewInterface" does not exist at compile time in /home/klay/projects/c/cphalcon/phalcon/http/response.zep on 464 [nonexistent-class]

	   view->disable();
	------------------^


Warning: Function "phalcon_orm_singlequotes" does not exist at compile time in /home/klay/projects/c/cphalcon/phalcon/mvc/model/query.zep on 513 [nonexistent-function]

	       let escapedValue = phalcon_orm_singlequotes(value);
	---------------------------------------------------------^


Copying new kernel files...
/usr/local/bin/zephir: line 39:  7567 Segmentation fault      (core dumped) php $ZEPHIRDIR/compiler.php $*
```

So, what I need do with /usr/local/bin/zephir at line 39?
```
 7567 Segmentation fault  (core dumped) php  $ZEPHIRDIR/compiler.php $*
```

-----------------------------------------------------------

Some system info:
```sh
$ php --version
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

```sh
$ php -m
[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gearman
geoip
gettext
gnupg
hash
iconv
imagick
imap
intl
json
libxml
MapScript
mbstring
mcrypt
memcache
memcached
mhash
mongo
mysql
mysqli
OAuth
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
phalcon
Phar
posix
readline
redis
Reflection
sasl
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xhprof
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

```sh
$ lsb_release --all
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

```sh
$ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```sh
$ phpize -v
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212

```

```sh
$ re2c --version
re2c 0.13.5
```

```sh
$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu

```

```sh
$ clang --version
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

```sh
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

```sh
$ automake --version
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

```sh
$ locate libpcre3
/usr/share/doc/libpcre3
/usr/share/doc/libpcre3-dev
/usr/share/doc/libpcre3/AUTHORS
/usr/share/doc/libpcre3/NEWS.gz
/usr/share/doc/libpcre3/README.Debian
/usr/share/doc/libpcre3/README.gz
/usr/share/doc/libpcre3/changelog.Debian.gz
/usr/share/doc/libpcre3/copyright
/usr/share/doc/libpcre3-dev/changelog.Debian.gz
/usr/share/doc/libpcre3-dev/copyright
/usr/share/doc/libpcre3-dev/examples
/usr/share/doc/libpcre3-dev/examples/pcredemo.c.gz
/var/cache/apt/archives/libpcre3-dev_1%3a8.31-2ubuntu2_amd64.deb
/var/cache/apt/archives/libpcre3_1%3a8.31-2ubuntu2_i386.deb
/var/lib/dpkg/info/libpcre3-dev:amd64.list
/var/lib/dpkg/info/libpcre3-dev:amd64.md5sums
/var/lib/dpkg/info/libpcre3:amd64.list
/var/lib/dpkg/info/libpcre3:amd64.md5sums
/var/lib/dpkg/info/libpcre3:amd64.postinst
/var/lib/dpkg/info/libpcre3:amd64.postrm
/var/lib/dpkg/info/libpcre3:amd64.shlibs
/var/lib/dpkg/info/libpcre3:amd64.symbols
/var/lib/dpkg/info/libpcre3:i386.list
/var/lib/dpkg/info/libpcre3:i386.md5sums
/var/lib/dpkg/info/libpcre3:i386.postinst
/var/lib/dpkg/info/libpcre3:i386.postrm
/var/lib/dpkg/info/libpcre3:i386.shlibs
/var/lib/dpkg/info/libpcre3:i386.symbols
```


Thanks!

**Comment by niden** [comment]
@sergeyklay  can you try this ?


```php
$ zephir fullclean
```

and then

```php
$ zephir build
```

**Comment by sergeyklay** [comment]
Excellent!
Dear @niden, you are cooler than Chuck Norris :ghost: 

I think it should be added to the installation guide !

**Comment by ovr** [comment]
@sergeyklay 
OKAY
![](http://i.imgur.com/erKxeSw.jpg)

**Comment by niden** [comment]
lol!

**Comment by joglomedia** [comment]
Hi all,

I can get rid of Warning: Class "APCIterator" by installing APCu extension.
I have do what Mr. @niden suggested 'zephir fullclean',
But Iam still got this 2 error warnings when trying recompile cphalcon, how to solve this?

```php
Warning: Class "Phalcon\Http\ViewInterface" does not exist at compile time in /home/masedi/phalcon/cphalcon/phalcon/http/response.zep on 464 [nonexistent-class]

	   view->disable();
	------------------^


Warning: Function "phalcon_orm_singlequotes" does not exist at compile time in /home/masedi/phalcon/cphalcon/phalcon/mvc/model/query.zep on 513 [nonexistent-function]

	       let escapedValue = phalcon_orm_singlequotes(value);
	---------------------------------------------------------^
```

My box configs

```bash
masedi@localhost:~/phalcon/cphalcon$ php -v
PHP 5.5.20-1+deb.sury.org~trusty+1 (cli) (built: Dec 21 2014 19:56:00) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader v4.7.2, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```

```bash
masedi@localhost:~/phalcon/cphalcon$ php -m
[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
geoip
gettext
hash
iconv
imagick
imap
intl
ionCube Loader
json
libxml
mbstring
mcrypt
memcache
memcached
mhash
ming
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
phalcon
Phar
posix
pspell
readline
recode
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
the ionCube PHP Loader
```
thanks

**Comment by sergeyklay** [comment]
@joglomedia 
Fixed here https://github.com/phalcon/cphalcon/pull/3196

**Comment by joglomedia** [comment]
@sergeyklay  thanks for pointing it out,

**Comment by deb0rian** [comment]
Why you hardcode APC into Zephir?
This package is ignored by php56... Thus, you cannot build Phalcon 2 on php56 without warnings. 
Heck, living without any caching mechanism is not the best way.
