### ISSUE TITLE
[BUG] [Phalcon 1.3.3] [PHP 5.4+] bug in populating (setDefault) for Select element

### ISSUE THREAD

**Issue by tartanpro** [phalcon/cphalcon#2921]
> Phalcon 1.3.3 / PHP 5.5 / Ubuntu 14.04
I've created an element in my form:
```php
$status = new Select("status",
    [0 => 'Disable', 1 => 'Enable', 2 => 'Suspend'] , [
        'class'      => 'form-control',
        "useEmpty"   => true,
        'emptyValue' => '@'
    ]);
```
then I populated the element:

```php
$status->setDefault('@');
```
But the option with **0** value selected as default!!!
$form->render('status') output:

```html
<select id="subscriber_status" name="subscriber_status" class="form-control">
	<option value="@">Choose...</option>
	<option selected="selected" value="0">Disable</option>
	<option value="1">Active</option>
	<option value="2">suspend</option>
</select>
```

I've tried many conditions but it seems that if we have an option with 0 value like my **Disable** option setting default value for __Select__ element didn't works. 

I removed **0 => Disable** option from my values array and everything works correctly. like below:

```html
<select id="subscriber_status" name="subscriber_status" class="form-control">
	<option selected="selected"  value="@">Choose...</option>
	<option value="1">Active</option>
	<option value="2">suspend</option>
</select>
```

**Comment by slarek** [comment]
I have the same problem.   Same behavior. If I remove the element at the 0 index, everything works fine,

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.3

**Comment by hanfeng2000** [comment]
multiple select in 2.0.3，have "PHP Notice:  Array to string conversion"

**Comment by andresgutierrez** [comment]
@hanfeng2000 Could you please provide a script to reproduce the issue?

**Comment by hanfeng2000** [comment]
FirmsForm.php:
$categories = new Select('categories', Constants::$FirmCategories, [
            'id' => 'categories',
            'name' => 'categories[]',
            'multiple' => true,
            'placeholder' => 'Multiple Select'
        ]);
$categories->setLabel('<i class="fa fa-star-o red"></i> Categories);
$this->add($categories);

firms.volt:
<div class="form-group">
	{{ form.label("categories",['class': 'col-sm-3 control-label no-padding-right']) }}
	<div class="col-sm-4">
		{{ form.render("categories",['class': 'form-control select2']) }}
	</div>
</div>

FirmsModel.php:
    public function afterFetch()
    {
        $this->categories = explode(',', $this->categories);

        $this->categories = array_combine($this->categories, $this->categories);

        $this->introduction = htmlspecialchars($this->introduction);
    }

FirmsController.php:
        if (!$this->request->isPost()) {

            $firm = Firms::findFirst(.....);

            if (!$firm) {
                return $this->response->redirect('/firms/index');
            }

            //var_dump($firm->categories);
            $this->view->form = new FirmsForm($firm);
            return;
        }


phalcon/tag/selec.zip （corrected）
        /**
         * Generate the OPTION tags based on an array
         *
         * @param array data
         * @param mixed value
         * @param string closeOption
         */
        private static function _optionsFromArray(data, value, closeOption)
        {
                var strValue, strOptionValue, code, optionValue, optionText, escaped;

                let code = "";

                for optionValue, optionText in data {

                        let escaped = htmlspecialchars(optionValue);

                        if typeof optionText == "array" {
                                let code .= "\t<optgroup label=\"" . escaped . "\">" . PHP_EOL . self::_optionsFromArray(optionText, value, closeOption) . "\t</optgroup>" . PHP_EOL;
                        } else {
                                if typeof value == "array" {
                                        if in_array(optionValue, value) {
                                                let code .= "\t<option selected=\"selected\" value=\"" . escaped . "\">" . optionText . closeOption;
                                        } else {
                                                let code .= "\t<option value=\"" . escaped . "\">" . optionText . closeOption;
                                        }
                                } else {
                                        let strOptionValue = (string) optionValue,
                                                strValue = (string) value;
                                        if strOptionValue === strValue {
                                                let code .= "\t<option selected=\"selected\" value=\"" . escaped . "\">" . optionText . closeOption;
                                        } else {
                                                let code .= "\t<option value=\"" . escaped . "\">" . optionText . closeOption;
                                        }
                                }
                        }
                }

                return code;
        }

**Comment by andresgutierrez** [comment]
@hanfeng2000 Could you please create a new issue? Thanks

**Comment by hanfeng2000** [comment]
@andresgutierrez 

https://github.com/phalcon/cphalcon/issues/10543

Sorry! My English is poor.
