### ISSUE TITLE
Split some Phalcon parts to independent extensions

### ISSUE THREAD

**Issue by nkt** [phalcon/cphalcon#2925]
I suggest to split Phalcon on components, like other frameworks do (Symfony, Zend, Yii).
At least annotations and volt. This components completely independent from Phalcon and could be used without Phalcon.

**Comment by iam-merlin** [comment]
+1, write phalcon extension in separate module can be very useful and interesting to replace juste part of other framework. I'm not a user of phalcon so my point of view can be irrelevant.

If I'm here, it's for this reason. I work on ZF2 and I want to use some  part of phalcon (for test) like the autoloader... and I can't without using the full stack. Composer permit to check if extensions loaded...
