### ISSUE TITLE
[Phalcon2] Segmentation Fault When Using Callable Definitions

### ISSUE THREAD

**Issue by parhamdoustdar** [phalcon/cphalcon#2926]
Steps to reproduce:

Put the following code in a file (eg test.php) and then run it using `php -e test.php`:

```php
<?php
$di = new Phalcon\Di\FactoryDefault();
$application = new Phalcon\Mvc\Application($di);
$di->set('a', function() {
    // This line is never reached
});
$di->get('a');
```

I have looked at `Phalcon\Di\Service::resolve()` and I found no if statement there checking for a  `callable` definition. Since I'm only getting a segmentation fault and I don't know how to trace this, I'm not sure if this is the problem, though.

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.1
