### ISSUE TITLE
Confirmation validator is able to compare strings in case insensitive mode

### ISSUE THREAD

**Issue by Samhayn** [phalcon/cphalcon#2927]
Hello, phalcon team.

It would be great to add an option to Confirmation validator, to switch on/off case-sensitive mode of comparing 2 values.

**Example:**
new Confirmation(array('with' => 'email', 'message' => 'please, confirm your email', 'caseSensitive' => false));

**Reason:**
Such things as a email agents are case insensitive.

**Additional info:**
I know, that it's possible to just extend standard validator (and I'll do it), but, I think it's better to support such simple configs "from the box"

**Comment by andresgutierrez** [comment]
Implemented in 2.0.x
