### ISSUE TITLE
[NFR] [Phalcon 2] Column::BIND_PARAM_ARRAY_*

### ISSUE THREAD

**Issue by quantum13** [phalcon/cphalcon#2934]
Hello.

I want to add Column::BIND_PARAM_ARRAY_INT and Column::BIND_PARAM_ARRAY_STRING for binding arrays in such queries `select * from table where field in (?)` by porting Doctrine DBAL class:
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/SQLParserUtils.php

Expanding parameters can be added to Phalcon\Db\Adapter\PDO::Prepare().

May I?

**Comment by andresgutierrez** [comment]
This is implemented in Phalcon 2.0.4
