### ISSUE TITLE
[NFR] allowEmpty option, all validator classes

### ISSUE THREAD

**Issue by iwai** [phalcon/cphalcon#2938]
I want you to be available in all validator classes, an allowEmpty option.
Implementation to \Phalcon\Validation\Validator class for the guarantee of consistency, 
because I repeatedly implemented allowEmpty option for my custom validator classes.

**Comment by Green-Cat** [comment]
As of phalcon 2.0, all empty values pass the validation as long as they do not have PresenceOf.

**Comment by andresgutierrez** [comment]
Implemented in Phalcon 2 (exception PresenceOf)
