### ISSUE TITLE
[BUG] Phalcon 1.3.3 on WAMP 2.5 (PHP 5.5.12) - Non-free csssminifier not available

### ISSUE THREAD

**Issue by al35mm** [phalcon/cphalcon#2947]
With Phalcon 1.3.3 running on WAMP 2.5 on Win 7 there is an error on minification of assets - "Phalcon\Assets\Exception[0]: Non-free csssminifier not available". I imagine it has something to do with this... https://github.com/phalcon/cphalcon/pull/2774

Tested with Phalcon 1.3.3 - Windows x64 for PHP 5.5.0 (VC11). I have marked this as a bug because that's what it seems to be. Or is there a licensing issue with the minifyer running on Windows?

**Comment by web777** [comment]
+1 get same error on 1.3.4 (win7 + php 5.5)

**Comment by derekang** [comment]
do we need to compile phalcon ourselves with the  --without-non-free build option ? currently using the phalcon dll from the download page..

**Comment by mikkiek** [comment]
+1, same here

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2
