### ISSUE TITLE
VOLT bug php v5.6.1

### ISSUE THREAD

**Issue by erik404** [phalcon/cphalcon#2951]
Using OSX 10.10, PHP 5.6.1 and Phalcon 5.6 the VOLT engine stopped working.

Problem occurs when creating a new view using the VOLT templating engine. Old views are working well, unless edited. Problem does not occur when a view is not using VOLT templating.

On screen message:
Unable to load the webpage because the server sent no data.
Error code: ERR_EMPTY_RESPONSE

Console:
Failed to load resource: net::ERR_EMPTY_RESPONSE 
http://test.localhost/testaction
Failed to load resource: net::ERR_CACHE_MISS http://test.localhost/testaction
GET http://test.localhost/testaction net::ERR_EMPTY_RESPONSE 

Headers:
Request URL:http://test.localhost/testaction
Request Headers
Provisional headers are shown
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer:
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:7289D82C-C510-84A0-C847-C6277DC2AEDF

There are no errors in Apache log nor PHP log.

Workaround is reverting back to PHP 5.5.17 and Phalcon 5.5

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2?
