### ISSUE TITLE
Documentation missing for Simple or Complex Resultset

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#2961]
I have to make some reports from views and using MySQL native functions, that are not supported by PHSQL. For resolve this I've create a dummy model and methods for raw queries.

At api documentation, for Simple or Complex resultset the construct receives a cache object, but it does not have documentation about its use. I'm wondering how to setup the cache for this result? How setup the key for example.

Thanks in advance.
##

**Comment by Jurigag** [comment]
Key for caching should be set in Query object actually. Tbh excepting testing purposes i don't really see need to create Simple or Complex class yourself.

**Comment by sergeyklay** [comment]
Please use for docs-related issues the **phalcon/docs** repository: https://github.com/phalcon/docs
