### ISSUE TITLE
Segfault when using NewRelic PHP-agent

### ISSUE THREAD

**Issue by jodator** [phalcon/cphalcon#2962]
I have trouble using both [php-agent](https://docs.newrelic.com/docs/agents/php-agent) extension for New Relic with PhalconPHP. The problems occurs in segmentation faults from PHP when both extensions are loaded together.

I have posted issue also on [new relic's discussion board](https://discuss.newrelic.com/t/problem-with-monitoring-phalconphp-fw/10527).

**Comment by jhcadlogica** [comment]
https://discuss.newrelic.com/t/problem-with-monitoring-phalconphp-fw/10527

This has been discussed on the NewRelic website.. hopefully they will fix it soon.

**Comment by andresgutierrez** [comment]
Closed as not related to the extension itself
