### ISSUE TITLE
Phalcon 2.0 setting notNullValidations to FALSE has no effect

### ISSUE THREAD

**Issue by rzajac** [phalcon/cphalcon#2979]
During my application bootstrap I do:

`Phalcon\Mvc\Model::setup(['notNullValidations' => false]);`

It works in 1.3.2 but looks like it has no effect in 2.0.0.

**Comment by RickyGit** [comment]
Until the issue is fixed, we can set ini setting "phalcon.orm.not_null_validations" to off

**Comment by andresgutierrez** [comment]
This is fixed
