### ISSUE TITLE
[1.3.4] Orm pb with Model::reset()

### ISSUE THREAD

**Issue by ogarbe** [phalcon/cphalcon#3023]
Hello,

I've ran into a problem with reset while having two objects of the same model working together. The problem is caused by this PR https://github.com/phalcon/cphalcon/pull/2520

I don't have the "correct" plan but the pb is that _uniqueParams is emptied by reset() while _uniqueKey is not, so _exists() method crash : 
here is the backtrace 

```shell
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1

#0 : {"function":"query","class":"PDO","type":"->","args":["SELECT COUNT(*) \"rowcount\" FROM `member` WHERE `id_membre` = ?"]}
#1 : {"function":"query","class":"Phalcon\\Db\\Adapter\\Pdo","type":"->","args":["SELECT COUNT(*) \"rowcount\" FROM `member` WHERE `id_membre` = ?",null,[]]}
#2 : {"function":"fetchOne","class":"Phalcon\\Db\\Adapter","type":"->","args":["SELECT COUNT(*) \"rowcount\" FROM `member` WHERE `id_membre` = ?",null,null,[]]}
#3 : {"function":"_exists","class":"Phalcon\\Mvc\\Model","type":"->","args":[{},{},"member"]}
#4 : {"file":"\/library\/Auth\/Auth.php","line":529,"function":"save","class":"Phalcon\\Mvc\\Model","type":"->","args":[]}
```

as you can see, the _exists method call fetchOne without a binded value, hence the SQL error

the cause seems is due to this kind of request, but i haven't managed to get a "clean case" 

```php
$new = new Model();
$new->save();
$other = Model::findFirst();
$new->save();
```

i've managed to workaround this problem in overloading reset() method in model class : 

```php
    public function reset()
    {
        parent::reset();
        $this->_uniqueKey = null;
    }
```

doing this, _uniqueKey (and _uniqueParams) is recalculated on each _exists() call but it doesn't seems to be the good answer to the problem.

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as 1.3.x is no longer supported

**Comment by mtotheikle** [comment]
I've encountered this using version 2.0.7.

We also noticed that this is only happens for us when we load a relation via magic getters. This loading of the relation causes the dirty state to be changed to DIRTY_STATE_TRANSIENT.

Has anyone else experienced this with newer versions?

**Comment by sergeyklay** [comment]
@mtotheikle Could you please open a new issue with script to reproduce?
