### ISSUE TITLE
[1.3.3] Phalcon phpunit bug $di::reset();

### ISSUE THREAD

**Issue by buildsufai** [phalcon/cphalcon#3031]
i have using Phalcon Test Case,and i receive an error.

Environment:
 phalcon 1.3.3
 phalcon/incubator:dev-master

when test case more then two files,
error logs:

``` php
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /www/html/tests/phpunit.xml

.PHP Fatal error:  Class name must be a valid object or a string in /vendor/phalcon/incubator/Library/Phalcon/Test/UnitTestCase.php on line 156

Fatal error: Class name must be a valid object or a string in /vendor/phalcon/incubator/Library/Phalcon/Test/UnitTestCase.php on line 156

```

when i Comments phalcon/incubator/Library/Phalcon/Test/UnitTestCase.php on line 156, its work

``` php
    protected function tearDown()
    {
        $di = $this->getDI();
       // $di::reset();
        parent::tearDown();
    }
```

my config:

``` xml
phpunit.xml

<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="./TestHelper.php"
         backupGlobals="false"
         backupStaticAttributes="false"
         verbose="true"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="true">
    <testsuite name="Phalcon - Testsuite">
        <directory>./</directory>
    </testsuite>
</phpunit>
```

other config same as http://docs.phalconphp.com/en/latest/reference/unit-testing.html

sorry for my poor english.
##

**Comment by Knallcharge** [comment]
Another cause for this can be too little resources on the database-server: each unit-test will create a new database-connect after di::reset(). Once the limit of connections that the server can handle, is reached, the unittests fail with the above error.
Use "persistent => true" when opening your db-connection in the UnitTestCase to get rid of this annoying error.

**Comment by mahelious** [comment]
Just chiming in that I too have run into this error.  Don't know why reset is doing such a poor job at obscuring errors, but I would be extremely appreciative of a fix that allowed the actual error to pass through, instead of suppressing it and returning a baffling substitute.

**Comment by Zaszczyk** [comment]
I also got this error:
Fatal error: Class name must be a valid object or a string in C:\...\vendor\phalcon\incubator\Library\Phalcon\Test\UnitTestCase.php on line 167

**Comment by sergeyklay** [comment]
The `1.3.x` branch is not longer supported.
