### ISSUE TITLE
Transactions not working when get non shared service from DI

### ISSUE THREAD

**Issue by hugofcampos** [phalcon/cphalcon#3032]
I tried to get the database adapter from DI with this code:

```php
$di = \Phalcon\DI::getDefault();
$db = $di->get('db');
```

Then I tried to begin and commit a transaction with no success, I mean, using Mysql "autocommit = 0" I can't commit a transaction and using "autocommit = 1" I can't rollback it.

```php
//with auto commit = 0;
$db->begin();
$myModel->save();
$db->commit(); //does not commit changes to MySql

//with auto commit = 1;
$db->begin();
$myModel->save();
$db->rollback(); //does not rollback changes
```

Why does it happen? I can't use DB services like this anyway?

**Comment by andresgutierrez** [comment]
OP didn't provide feedback
