### ISSUE TITLE
Private class variables on models appear to be handled improperly.

### ISSUE THREAD

**Issue by tyler-shaw** [phalcon/cphalcon#3033]
When creating a model extending from `\Phalcon\Mvc\Model`, class variables set as private are accessible from outside of the class without error. This applies only when changing the value. Attempting to use the value results in an error, as expected.

For example, let's say we have a plain php class, called MyClass:

	class MyClass {
		private $myVariable;
	}

If we were to create an instance of this class and then attempt to use that variable from outside the class, we would receive the following errors:

	$myClass = new MyClass();

	$myClass->myVariable = 20;
	// Result: Fatal error: Cannot access private property MyClass::myVariable in \File\Path\Here.php on line 3

	echo $myClass->myVariable;
	// Result: Fatal error: Cannot access private property MyClass::myVariable in \File\Path\Here.php on line 6
	
Now let's examine a similar scenario with a class that extends from `\Phalcon\Mvc\Model`.

	class MyModel extends \Phalcon\Mvc\Model {
		private $myDatabaseField;
	}
	
In this scenario, the private variable represents a field in the database that the model interacts with. Performing similar actions to the ones above:

	$myModel = new MyModel();
	
	$myModel->myDatabaseField = 20;
	// Result: Field is updated without notice of any type.
	
	echo $myModel->myDatabaseField;
	// Result: Access to undefined property MyModel::myDatabaseField in \File\Path\Here.php on line 6

Here is my issue with this:

- Allowing a private variable to be updated as if it is public completely defeats the purpose of having a private variable.
- Trying to access a private variable is treated as a notice when PHP itself considers such an action a fatal error, while less important to me, seems rather inconsistent.

Hopefully my example demonstrates the issue I am talking about. I am currently using 1.3.3 I believe, on PHP 5.5

**Comment by daveamol** [comment]
The has not been done on phalcon 2.0 right. So temporarily to prevent using the magic setters and getters can one overwrite the __set function of the model with a dummy function ?

**Comment by bmoore** [comment]
This is possibly being handled in https://github.com/phalcon/cphalcon/pull/11320
