### ISSUE TITLE
[2.0.0] Drop support of PHP 5.3

### ISSUE THREAD

**Issue by m157y** [phalcon/cphalcon#3034]
I was looked on last commits (2.0 branch) and saw some tweaks for support of PHP 5.3 (e.g. https://github.com/phalcon/cphalcon/commit/e8f77329620f05359447ff7df81fa4bb30dd03e7 ).
But PHP 5.3 now EOL ( http://php.net/archive/2014.php#id2014-08-14-1 ), so maybe it's time to ignore it in 2.0 branch?

**Comment by salarmehr** [comment]
Site which use  obsolete PHP versions (5.3, 5.4) generally are hosted on shared server. Phalcon programmers access to system root and can easily upgrade to last stable  PHP version.

Phalcon is not comparable with other PHP frameworks regarding PHP version support.

**Comment by m157y** [comment]
@salarmehr I think you'll be surprised, but at Russia you can install custom modules on shared hosting (not every hoster has this feature, but most of them). So you can use shared hosting and phalcon and it can be compared with any other framework. But, e.g. Symfony has bigger community and more components, so it's more popular. And one of the reasons is Symfony one of mainstream frameworks with usage of latest features of PHP. That's what i want for Phalcon.

**Comment by andresgutierrez** [comment]
As Phalcon 2.0.x is now released and many maintenance releases have been released for this series. Phalcon 2.1.x will deprecate PHP 5.3.x in all platforms. We encourage everyone using PHP 5.3 to update their installations to the latest Phalcon 2.0.x and/or upgrade to >= PHP 5.4.x as soon as possible if you want to continue receiving Phalcon updates.
