### ISSUE TITLE
saving a model with empty (not null) values fails when column is defined "not Null"

### ISSUE THREAD

**Issue by swen100** [phalcon/cphalcon#3035]
i tried to create an entry in a MySQL-Database. My model/table has a column which is defined not null. For MySQL (maybe for other RDMS also) an empty string is not null, so it can be used within insertions. But Phalcon misinterpretes it. Phalcon thinks that it is not valid. That is wrong.

My System is: 
Phalcon Version 1.3.4
PHP 5.5
MySQL 5.6

```sql
CREATE TABLE `dummy` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
   PRIMARY KEY (`id`)
);
```
```php
// create object and set an empty (not null) value
$myModel = new dummy();
$myModel->name = '';

// show that 'name' is empty, but not null
echo "<pre>";
var_dump($myModel->toArray());
echo "</pre>";

// try to create (insert into table)
// and show errors if something was wrong
if( !$myModel->create() ) {
      echo "an error occured:<br>";
      foreach( $myModel->getMessages() as $message ) {
           $this->flash->error((string) $message);
      }
}

```
result:
```php
array(2) {
  ["id"]=>
  NULL
  ["name"]=>
  string(0) ""
}

an error occured:
name is required
```
if i use straight sql like this:
```sql
INSERT INTO `dummy` (`id`, `name`) VALUES (Null, '');
```
all works fine.

The value i have set is empty, but it is not Null. With phalcon the creation of a new object fails. In my opinion it should not fail, but it does...

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.3 https://github.com/phalcon/cphalcon/issues/440#issuecomment-107227724
