### ISSUE TITLE
Validation for max length using Database Introspection Strategy

### ISSUE THREAD

**Issue by mrthebob** [phalcon/cphalcon#3063]
Maybe I need education, but I was assuming that Phalcon would do some kind of validation for max length on a column with a defined length when using its Database Introspection Strategy.  Rather than performing validation, the value happily gets truncated and stuck into the database with a length sufficient for entering it.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
