### ISSUE TITLE
PHP error message is being sent to my log and email to me

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#3070]
I'm using standard Ubuntu 14.04 64-bit.  I don't seem to be having a problem that I can witness but I'm recieving this log message since I configured a sendmail clone for other purposes.

I previously had phalcon on runlevel 20 and I changed it to 50 restarted nginx and then later rebooted.  I'm unsure if this error is new or is just repeating from a log.  Also I can't see to find where that log would be coming from as I'm not such a whiz with the system administrator stuff as I just learn what I need to develop.

Subject:
```
Cron <root@notebook> [ -x /usr/lib/php5/maxlifetime ] && [ -x /usr/lib/php5/sessionclean ] && [ -d /var/lib/php5 ] && /usr/lib/php5/sessionclean /var/lib/php5 $(/usr/lib/php5/maxlifetime)
```

Body:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/phalcon.so' - /usr/lib/php5/20121212/phalcon.so: undefined symbol: php_json_decode_ex in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/phalcon.so' - /usr/lib/php5/20121212/phalcon.so: undefined symbol: php_json_decode_ex in Unknown on line 0
```

**Comment by hasmo** [comment]
I have the same problem at the moment. Priorities are correct so json should be loaded before.

**Comment by ninja4826** [comment]
Priorities are set, and still getting the same error. When manually loading from php.ini and removing the symlinks from conf.d, I get:
```
undefined symbol: php_pdo_get_dbh_ce
```

**Comment by barantaran** [comment]
I had the same issue after adding phalcon extension by php5enmod and "extension=phalcon.so" in php.ini both. Solved with removing "extension=phalcon.so" from php.ini.

**Comment by erickne** [comment]
@barantaran thanks! Worked for me.

**Comment by Hubcore** [comment]
cd /etc/php5/mods-available
sudo nano pdo_mysql.ini

Add after:
extension=pdo_mysql.so

This:
extension=phalcon.so

Remove php.ini phalcon.so line

Works because pdo_mysql.so is obviously loaded before phalcon.so which is where the error is coming from.

**Comment by mrdilanka** [comment]
@Hubcore Thanks a lot . It's working for me. :)

**Comment by elchava** [comment]
PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/phalcon.so'

**Comment by Jurigag** [comment]
And what's a problem ? This just told you that phalcon extension can't be loaded, like it's not installed. Just remove phalcon.so from php.ini or something.
