### ISSUE TITLE
Action Regex Mismatch with Docs

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#3074]
Somewhere along the line, the regex for `:action` was updated from:

```
// http://docs.phalconphp.com/en/latest/reference/routing.html
/([a-zA-Z0-9_]+)
```

to

```
// https://github.com/phalcon/cphalcon/blob/master/ext/mvc/router/route.c#L274
/([a-zA-Z0-9_-]+)
```

I remember this wasn't always the case, but at some point the code was updated but the document didn't reflect the new changes.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/docs#1009
