### ISSUE TITLE
Phalcon 1.3.4 security hash causing webpage connection reset.

### ISSUE THREAD

**Issue by viralj** [phalcon/cphalcon#3081]
Hello friends, I am new at Phalcon and I am using it for my web project. I used phalcon's security hash function to encrypt password in signup controller and also used it in login controller to check password as given information in phalcon documentation. But this was causing connection reset error most of the time. And when it was not causing this error, at new registration it was not inserting only password in mysql. I am using VARCHAR column in mysql for password and to check it, i changed it to text and it inserted sometime. But there was still that connection reset problem. At first, I asked question about this problem at phalcon forum website and my question link is 

http://forum.phalconphp.com/discussion/4079/controller-is-resetting-the-connection-instead-of-getting-variab

Please see the question for more information. I tried to use with my custom encryption class and it worked perfect. No connection reset or no problem with data insert in mysql.

Details of my development environment:-
Windows 8.1, XAMPP server, PHP 5.5.17 and MYSQL 5.6.20

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2
