### ISSUE TITLE
Volt is compiling wrong variable

### ISSUE THREAD

**Issue by fl0pp** [phalcon/cphalcon#3084]
My Phalcon web-app has worked for a long time. I did some changes the last week, and suddenly strange things happends with my templates.

app/config/services.php:

```
$di->set('view', function () use ($config, $di) {
    $view = new View();
    $view->core = new \stdClass;
    $view->core->breadcrumb = array();
});
```

BaseController.php:

```
public function appendBreadcrumb($url = false, $title = false, $fa_class = false) {
    if($url) $url = $this->di->getUrl()->get($url);
        $this->view->core->breadcrumb[] = array('url' => $url, 'title' => $title, 'class' => ($fa_class ? 'fa-'.$fa_class : false));
    }
```

mytemplate.volt:

```
{% if core.breadcrumb %}
```

The volt-file gets compiled to php-file with the variable "$this->core->breadcrumb". This variables is NULL. But when I change the php-file to "$core->breadcrumb" it works.

I created a forum-post that told me it seems like a bug: http://forum.phalconphp.com/discussion/4101/volt-is-compiling-wrong-variable#C13738
##

**Comment by andresgutierrez** [comment]
This happens because you have a service called "core"

**Comment by andrewi-wd** [comment]
Similar to me. And I suppose that this is a real bug.

services.php:
```
$di->set('user', function () {
    return new \MyApp\Collections\User();
}, true);
```

controller.php:
```
    $this->view->users = BackUser::find();
```

view.volt:
```
{% for user in users %}
    <h1>{{ user.backUserName }}</h1>
{% endfor %}
```

error result:
```
Undefined property: MyApp\Collections\User::$backUserName in file ...
```

So, the problem is that services overrides view variables, even in a loop!

**Comment by dschissler** [comment]
Perhaps version 4 could introduce an unambiguous way to reference services.  What about using a prefix for referencing services such as `&`, `\`, `@` or `$`?  @sergeyklay Any chance that this can get put onto a 4.0 milestone?  The current situation creates a complicated edge case when precompiling templates in an environment where the DIs don't match because in one case it is converted to `$this->...` and the other it does't have the `this`.  I think that there needs to be a prefix there.

**Comment by Jurigag** [comment]
The problem i think that variables are done like this:

```
let {key} = value;
```

or something like this.

**Comment by dschissler** [comment]
Is the way that variables are defined an issue?  It seems to me that it is only a matter of how they are referenced.
