### ISSUE TITLE
[2.0.0] Erros Compiling 2.0 on Windows 7

### ISSUE THREAD

**Issue by evandropoa** [phalcon/cphalcon#3086]
Hi All,

I´ve some errors while building 2.0 branch in windows 7 with PHP 5.4 (TS).
 zephir generate it´s ok but compile get some errors:

kernel.zep.c
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(80) : error C2143: syntax error : missing ';' before 'type'
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(81) : error C2143: syntax error : missing ';' before 'type'
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(82) : error C2143: syntax error : missing ';' before 'type'
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(84) : error C2065: 'nKeyLength' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(87) : error C2065: 'nKeyLength' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(87) : error C2065: 'nKeyLength' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(88) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(88) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(88) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(88) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(88) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(89) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(89) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(89) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(89) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(89) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(90) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(90) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(90) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(90) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(90) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(91) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(91) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(91) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(91) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(91) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(92) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(92) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(92) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(92) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(92) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(93) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(93) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(93) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(93) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(93) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(94) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(94) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(94) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(94) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(94) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(95) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(95) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(95) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(95) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(95) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(98) : error C2065: 'nKeyLength' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(99) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(99) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(99) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(99) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(99) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(101) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(101) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(101) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(101) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(101) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(103) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(103) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(103) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(103) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(103) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(105) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(105) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(105) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(105) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(105) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(107) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(107) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(107) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(107) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(107) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(109) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(109) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(109) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(109) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(109) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(111) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(111) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(111) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(111) : error C2065: 'arKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(111) : error C2100: illegal indirection
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(114) : error C2065: 'strKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(114) : warning C4047: '=' : 'int' differs in levels of indirection from 'void *'
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(115) : error C2065: 'strKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(115) : warning C4047: 'function' : 'char *' differs in levels of indirection from 'int'
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(115) : warning C4024: 'ap_php_snprintf' : different types for formal and actual parameter 1
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(115) : error C2065: 'hash' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(117) : error C2065: 'strKey' : undeclared identifier
D:\phpdev\cphalcon\ext\phalcon\kernel.zep.c(117) : warning C4047: 'initializing' : 'const char *' differs in levels of indirection from 'int'

Thanks in advanced

**Comment by olivier-monaco** [comment]
This is a Zephir issue. Can you open a issue on Zephir project?

**Comment by andresgutierrez** [comment]
DLLs are now available: http://phalconphp.com/en/download/windows
