### ISSUE TITLE
Serious bug in variable binding

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#3087]
Consider the following code:

        $query = $this->modelsManager->createBuilder()->from('User');
        $query->andWhere('sex=?0', ['f']);
        $query->andWhere('age=?0', [55]);
        $query->andWhere('name=?0', ['Tom']);

First variable will be assigned to all three place holder: `where sex='f' and age='f' and name='f'` 
This cost me two days. ◕︵◕

**Comment by salarmehr** [comment]
@stanislav-web The link is broken. May you please renew the link.

**Comment by salarmehr** [comment]
@phalcon each condition should be binded to its variables and should be independent from other conditions.

**Comment by andresgutierrez** [comment]
Closed as not a bug
