### ISSUE TITLE
Phalcon\Mvc\Model\Resultset\Complex is causing exceptions when result is empty false. 

### ISSUE THREAD

**Issue by darkgaro** [phalcon/cphalcon#3098]
When running queries which are supposed to return complex result sets but query doesn't return anything and returns false, it causes exception since Phalcon\Mvc\Model\Resultset\Complex consructor  requies ResultInterface for the result parameter.
```php
	public function __construct(var columnTypes, <ResultInterface> result, <BackendInterface> cache = null)
	{
```

Phalcon\Mvc\Model\Resultset\Simple doesn't require the type on the result param. 
```php
public function __construct(var columnMap, var model, result, <BackendInterface> cache=null, keepSnapshots = null)
	{
```

I am not sure how this worked in 1.3  but
It seems like that we should probably remove the requirement on Complex class constructor  or maybe create a new class 'Empty' implementing ResultInterface  which then gets set in case of an empty result set 

In my repo I've removed the requirement and it seems to work now.

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2?
