### ISSUE TITLE
WebTools bug

### ISSUE THREAD

**Issue by karborator** [phalcon/cphalcon#3110]
If I try to click on models from WebTools i get this:

Phalcon\DI\Exception: Invalid service definition. Missing 'className' parameter
#0 [internal function]: Phalcon\DI\Service\Builder->build(Object(Phalcon\DI\FactoryDefault), Array, NULL)
#1 [internal function]: Phalcon\DI\Service->resolve(NULL, Object(Phalcon\DI\FactoryDefault))
#2 /home/bender/vendor/phalcon/devtools/scripts/Phalcon/Web/Tools.php(161): Phalcon\DI->getShared('config')
#3 /home/bender/vendor/phalcon/devtools/scripts/Phalcon/Web/Tools/controllers/ControllerBase.php(60): Phalcon\Web\Tools::getConfig()
#4 /home/bender/vendor/phalcon/devtools/scripts/Phalcon/Web/Tools/controllers/ModelsController.php(30): ControllerBase->listTables(true)
#5 [internal function]: ModelsController->indexAction()
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /home/bender/vendor/phalcon/devtools/scripts/Phalcon/Web/Tools.php(322): Phalcon\Mvc\Application->handle()
#8 /home/bender/projects/minsp/public/webtools.php(26): Phalcon\Web\Tools::main('/home/bender/ve...', '192.168.')
#9 {main}

**Comment by Green-Cat** [comment]
@andresgutierrez Not a phalcon issue.

**Comment by sergeyklay** [comment]
This behaviour fixed in devtools

**Comment by Green-Cat** [comment]
@andresgutierrez please close.
