### ISSUE TITLE
Model serialization with mapping

### ISSUE THREAD

**Issue by evandropoa** [phalcon/cphalcon#3121]
Hi all,

I´m using v. 1.3.4 latest.

I have some issues when serializing a model with mapping, I have a model that maps a property 'id' to table column 'user_id', it works ok, but when I serialize it, it trys to gess the value 'user_id' of the model, so it serializes 'user_id = null'.

Looking at the model's serialize code, it does not account for the reverse mappings of the model, but I think it should do it.

Any point here will be apreciated.

Sry my bad english.
##

**Comment by Jurigag** [comment]
I guess it's fixed in phalcon 3?
