### ISSUE TITLE
Dispatch not firing correctly forward

### ISSUE THREAD

**Issue by andrefigueira** [phalcon/cphalcon#3125]
Hi I seem to have found a bug or at least an undocumented side effect.

I am trying to integrate ACL into my application, which I've setup as a MultiModule app.

And the forward does not seem to be working within a beforeExecuteRoute method.

I am calling before execute route by attaching it to the eventManager in my module:

    <?php
    
    namespace WideZike\Frontend;
    
    class Module
    {
    
        public function registerAutoloaders()
        {
    
            $loader = new \Phalcon\Loader();
    
            $loader->registerNamespaces(array(
                'WideZike\Frontend\Controllers' => '../modules/WideZike/Frontend/Controllers/',
                'Common\WideZike\Models' => '../app/common/WideZike/Models/',
                'PDW' => '../vendor/zazza/phalcon-debug-widget/src/PDW/'
            ));
    
            $loader->register();
    
        }
    
        public function registerServices($di)
        {
    
    
            $di->set('dispatcher', function() use ($di) {
    
    
                $eventsManager = $di->getShared('eventsManager');
    
                $eventsManager->attach('dispatch:beforeExecuteRoute', new \SecurityPlugin);
                $eventsManager->attach('dispatch:beforeException', new \NotFoundPlugin);
    
                $dispatcher = new \Phalcon\Mvc\Dispatcher();
                $dispatcher->setEventsManager($eventsManager);
                $dispatcher->setDefaultNamespace('WideZike\Frontend\Controllers');
    
                return $dispatcher;
    
            });
    
    
            //Setup the view component
            $di->set('view', function(){
    
                $view = new \Phalcon\Mvc\View();
                $view->setViewsDir('../modules/WideZike/Frontend/Views/');
    
                $view->registerEngines(array(
                    '.volt' => 'voltService'
                ));
    
                return $view;
    
            });
    
            if(PHALCONDEBUG)
            {
    
                $debugWidget = new \PDW\DebugWidget($di);
    
            }
    
        }
    
    }

Then in my security plugin I have it defined:

    <?php
    
    use Phalcon\Acl;
    use Phalcon\Acl\Role;
    use Phalcon\Acl\Resource;
    use Phalcon\Events\Event;
    use Phalcon\Mvc\User\Plugin;
    use Phalcon\Mvc\Dispatcher;
    use Phalcon\Acl\Adapter\Memory as AclList;
    
    /**
     * SecurityPlugin
     *
     * This is the security plugin which controls that users only have access to the modules they're assigned to
     */
    class SecurityPlugin extends Plugin
    {
    
        /**
         * Returns an existing or new access control list
         *
         * @returns AclList
         */
        public function getAcl()
        {
    
            if(!isset($this->persistent->acl))
            {
    
                $acl = new AclList();
    
                $acl->setDefaultAction(Acl::ALLOW);
    
                //Register roles
                $roles = array(
                    'users'  => new Role('Users'),
                    'guests' => new Role('Guests')
                );
    
                foreach($roles as $role)
                {
    
                    $acl->addRole($role);
    
                }
    
                //Private area resources
                $privateResources = array(
                    'users' => array('profile'),
                );
    
                foreach($privateResources as $resource => $actions)
                {
    
                    $acl->addResource(new Resource($resource), $actions);
    
                }
    
                //Public area resources
                $publicResources = array(
                    'index'      => array('index'),
                    'videos'     => array('watch', 'category', 'fetch'),
                    'errors'     => array('show404', 'show500', 'show401'),
                );
    
                foreach($publicResources as $resource => $actions)
                {
    
                    $acl->addResource(new Resource($resource), $actions);
    
                }
    
                //Grant access to public areas to both users and guests
                foreach($roles as $role)
                {
    
                    foreach($publicResources as $resource => $actions)
                    {
    
                        $acl->allow($role->getName(), $resource, '*');
    
                    }
    
                }
    
                //Grant access to private area to role Users
                foreach($privateResources as $resource => $actions)
                {
    
                    foreach($actions as $action)
                    {
    
                        $acl->allow('Users', $resource, $action);
    
                    }
    
                }
    
                //The acl is stored in session, APC would be useful here too
                $this->persistent->acl = $acl;
    
            }
    
            return $this->persistent->acl;
    
        }
    
        /**
         * This action is executed before execute any action in the application
         *
         * @param Event $event
         * @param Dispatcher $dispatcher
         * @return bool
         */
        public function beforeExecuteRoute(Event $event, Dispatcher $dispatcher)
        {
    
            $auth = $this->session->get('auth');
    
            if($auth)
            {
    
                $role = 'Users';
    
            }
            else
            {
    
                $role = 'Guests';
    
            }
    
            $controller = $dispatcher->getControllerName();
            $action = $dispatcher->getActionName();
    
            $allowed = false;
    
            if($allowed != Acl::ALLOW)
            {
    
                $dispatcher->forward(array(
                    'namespace' => 'WideZike\Frontend\Controllers',
                    'controller' => 'error',
                    'action' => 'show401'
                ));
    
                return false;
    
            }
    
        }
    
    }

I've set `$allowed` to false to for it to always forward, I have also removed the ACL from this as It was not working either, but that's a separate issue.

Anyway, Ietting this run, the dispatch does not forward to show401, instead renders only the main view, and sets the 404 header, from my 404 handler, so it seems to ignore this forward and instead try to do a 404.

I've tried searching and searching all over the forums, but cannot see what I'm doing wrong so it's let me to beleive perhaps there is a bug when trying to dispatch from beforeExecuteRoute from a module.

Thanks

**Comment by olivier-monaco** [comment]
Your beforeExecuteRoute method returns false or nothing (no return at the end). So, it will be false or null and null is false... So it will always be false...

Add a return true at the end. Maybe it helps...
