### ISSUE TITLE
One black pixel extra added after cropping an image

### ISSUE THREAD

**Issue by lamvuh** [phalcon/cphalcon#3127]
Look at the bottom of the image below

![vn](https://cloud.githubusercontent.com/assets/9286949/5417417/dd8cee06-81ed-11e4-9690-45d099d5d0c0.jpg)

My PHP code:
$image = new GD($pathToMyImage);
$image->crop(400, 400);
$image->save($image->getRealPath(), 100);

OS: Windows 8.1
PHP: 5.6
Phalcon: 1.3.4
GD: 2

Cropping function work perfectly on Code Igniter and Raw PHP
##

**Comment by mikkiek** [comment]
Have same issue =(
Anyone can share with workaround?

**Comment by swen100** [comment]
it's a php bug:
https://bugs.php.net/bug.php?id=67447

**Comment by swen100** [comment]
lamvuh wrote:
"Cropping function work perfectly on Code Igniter and Raw PHP"
so: why don't you write it in raw code :-)

**Comment by lamvuh** [comment]
@swen100: why you use this framework?

People go here to report bugs and look for solutions. So please stop flaming like this.

**Comment by swen100** [comment]
@lamvuh Don't be cross with me. Have you noticed the smiley at the end of my sentence?

**Comment by andresgutierrez** [comment]
Can you try again using Phalcon 2 or close this issue?
