### ISSUE TITLE
Adding getJson and hasJson method to Phalcon\Http\Request

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#3130]
In some js frameworks (e.g Backbone.js and Angular) the request are in json format. Please add `hasJson()` and `getJson()` methods to Phalcon\Http\Request similar to other methods. Also please enhance `has` and `get` method to support json requests. 

Currently the only json related method in Request class is  `getJsonRawBody ()`

**Comment by 7thcubic** [comment]
Json request can be detected by applying isAjax() and json_decode.

It is possible to add it to phalcon, but is it really necessary?

**Comment by yybalam** [comment]
You can extend Phalcon\Http\Request and add those methods wrapping the isAjax() and json_decode().

**Comment by salarmehr** [comment]
0@7thcubic  Yes, they are neccessary as much as other methods in Phalcon\Http\Request. When all of your request/response are in JSON format, you can not use benefit from Phalcon\Http\Request.

**Comment by 7thcubic** [comment]
if u discard all request except ajax request. You would not be able to use the same call for any other fields. 

But if you allow non ajax calls to be processed for has/get json its as good as writing 

Return json_decode(get/post(field)))==null
Or return json_decode(get/post((field))

I guess depends i guess. I believe someone already made a commit for it. Though i wouldnt get my hopes up. 

Meanwhile maybe an extend towards incubator would be in order.

**Comment by salarmehr** [comment]
@7thcubic  @yybalam  `public string getJsonRawBody () `

**Comment by 7thcubic** [comment]
Jsonrawbody returns the engire request as a json object. What he wanted was. If a post/get field has a json object. 

Meaning looping thru the post super array. And checking if any field consist of a valid json object.

**Comment by andresgutierrez** [comment]
Already implemented in getJsonRawBody()

**Comment by salarmehr** [comment]
@andresgutierrez What do you mean by that? The requested method are helper and really useful in developing SPA (in particular Angular and Backbone).

**Comment by andresgutierrez** [comment]
@salarmehr You're requesting something that is already implemented

**Comment by salarmehr** [comment]
@andresgutierrez Sorry, I cann't find them on the documentation.
