### ISSUE TITLE
Events manager attach() by class name

### ISSUE THREAD

**Issue by jacob1237** [phalcon/cphalcon#3133]
Hi all!
This is a feature request.

As documentation said, we can use two types of listeners: an anonymous function and an object.
But it will be great thing, to be able to put just a class name in attach() method as a listener.

So we will have an ability to bootstrap services through config like this:

``` php
return [
    'eventsManager' => [
        'className' => 'Phalcon\Events\Manager',
        'calls' => [
            [
                'method' => 'attach',
                'arguments' => [
                    ['type' => 'parameter', 'value' => 'dispatch'],
                    ['type' => 'parameter', 'value' => 'MyDispatcherListener'],
                ],
            ]
        ],
    ],

    // Some other services
   ...
```

I think such modification will not break the old code compatibility

**Comment by temuri416** [comment]
+1
