### ISSUE TITLE
[NFR] allow Request::getBestLanguage() to return language without dialect

### ISSUE THREAD

**Issue by quasipickle** [phalcon/cphalcon#3135]
When I use `\Phalcon\Mvc\Request->getBestLanguage()` on my browser, it returns "en-US".  I think it would be helpful in some cases to have a way to just return "en", as my language files won't be broken down into "en-UK", "en-US", "en-CA", etc.

Something like `getBestLanguageFamily()`, or a variable passed to `getBestLanguage()` would be helpful.

**Comment by dschissler** [comment]
@sergeyklay Please add this to 4.0 roadmap.  It should be easy to add and I ran into this annoyance some years ago.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14698

Thank you @quasipickle
