### ISSUE TITLE
Segmentation Fault in \Phalcon\Image\Adapter

### ISSUE THREAD

**Issue by wedancedalot** [phalcon/cphalcon#3145]
Hello, was using a cli to resize images in my app, came upon this trouble:

$image = new \Phalcon\Image\Adapter\Imagick($path);
$width = $image->getWidth();
if ($width > self::RESIZE_WIDTH) {
        $image->resize(self::RESIZE_WIDTH)->save();
}

Being using in a loop, this lead to 'Segmentation Fault' and termination
Changed adapter to GD and still got the error.

So i ended up with using php's getimagesize() function instead of getWidth() method, which works fine and doesnt cause the segterm.

**Comment by olivier-monaco** [comment]
Which version of PHP? You may have a "infinite recursive call" which seems to segfault at least on PHP 5.4 and 5.5 provided by Debian (and not 5.3).

**Comment by wedancedalot** [comment]
Same on php 5.4.35, Ubuntu 12.04 and php 5.4.35, CentOS 6.5

**Comment by olivier-monaco** [comment]
Not related to Phalcon. Can you close this issue please?
