### ISSUE TITLE
 Can we have a more efficient multi module system?

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/cphalcon#3146]
I come from the world of Zend and really Phalcon in the development of modular MVC system is very precarious
Reallocation module by module views, routes, etc is very tedious
I do not understand C to contribute to the project, but if I want to use this framework in my next projects

**Comment by dschissler** [comment]
Phalcon provides very low level components that are capable of being arranged in countless ways.  They is a growing number of opinionated implementations that you can find at [Awesome Phalcon](https://github.com/sergeyklay/awesome-phalcon).
