### ISSUE TITLE
Routing is not catching named parameters correctly

### ISSUE THREAD

**Issue by geoidesic** [phalcon/cphalcon#3157]
I'm using the following route on Phalcon 1.3.0 and PHP 5.4.4:
```php
    $router->addGet('/api/:controller/search/{name}',array(
        'module'=>'api',
        'controller'=>1,
        'action'=>'search',
        'namespace'=>'MyPhalconModules\Api\Controllers'
    ));
```
The URL I'm using is: 
```
http://localhost/phalcon-test/api/task/search/test
```
In the 'search' action of the 'task' controller I do:
```php
var_dump ($this->dispatcher->getParams());
```
And the output is mysteriously:
```
Array
(
    [name] => task
)
```
The expected output would be:
```
Array
(
    [name] => test
)
```

**Comment by dugwood** [comment]
You should dump ```$di->getRouter()->getRoutes()```. That will help you understand the «default» routes (IIRC there is just one).

**Comment by sergeyklay** [comment]
@geoidesic

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by geoidesic** [comment]
Hi guys.. sorry but I gave up on Phalcon. Just seems impossible to work with since I can't figure out how to debug when the framework is not available as code for inserting debug prods into. It may run fast but seems impossibly slow to develop with as a result.

**Comment by dugwood** [comment]
At the very least you could have done what I've suggested... Almost everything is available to dump, which helps to detect issues. I've fixed some on the bugs myself for minor ones, with pull requests. Since then (was a while back ago on version 2 beta), I didn't have any issue. And as everyone, I do it for free, because I care. So don't say it's impossible without even trying.

**Comment by sergeyklay** [comment]
@dugwood Quoted you in my bio on Github

**Comment by geoidesic** [comment]
Apologies.. it wasn't intended to offend. I was just trying to inform you that I've stopped spending time on Phalcon and why. I'm sure it is possible – however I wasn't able to achieve it in the time window I had and with the information available to me at that time... thus "it *seems* impossibly slow to develop with...".

**Comment by dugwood** [comment]
I do understand. Every CMS needs some time to learn, and if you don't have that time, sometimes it's easier to avoid using one. The thing is that you opened a bug, asked for help, but didn't answer back. I've answered a little bit late (holidays...), spent time on your issue (yeah, just 2 minutes I agree), as @sergeyklay did, and it just ends without feedback.
Anyway, if you want to give it a try for a new project, the code is really great now, and I don't even imagine use another framework/CMS from now on :-)
