### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by geoidesic** [phalcon/cphalcon#3158]
```
handler class cannot be loaded
```
Is not a particularly useful message when you're trying to figure out why a route doesn't work. It would be helpful to know what specific name the route was trying to load, in terms of Controller and Action.

**Comment by sergeyklay** [comment]
Many Phalcon components (for example `Phalcon\Mvc\Dispatcher`) is able to send events to an `EventsManager` if it is present: https://docs.phalconphp.com/en/latest/reference/dispatching.html

For debugging and logging purposes you have to create your own event handler.
