### ISSUE TITLE
Fatal error: Call to undefined method Phalcon\Flash\Session::has() 

### ISSUE THREAD

**Issue by divined** [phalcon/cphalcon#3159]
<?php

use Phalcon\Mvc\User\Component;

class Elements extends Component
{
    public  function  ifMessages(){
        if ($this->flashSession->has('error') ) return true; 
        return false;
    }
}

**Comment by olivier-monaco** [comment]
Unable to reproduce. Still an issue? Which version of Phalcon?

**Comment by divined** [comment]
Yes. Still have an error. Ph 1.3.4

**Comment by divined** [comment]
New project from console and this component in plugins folder.

**Comment by sergeyklay** [comment]
It seems you forgot to enable session flash:

```php
$di->set('flash', function() {
    return new \Phalcon\Flash\Session;
});
```

By default Phalcon uses `\Phalcon\Flash\Direct`. But `Direct` don't have `has` method.

**Comment by divined** [comment]
i use:
<pre>
        $di->set('flash', function(){
            return new Phalcon\Flash\Session(array(
                'error' => 'alert alert-danger',
                'success' => 'alert alert-success',
                'info' => 'alert alert-info'
            ));
        });
</pre>

**Comment by divined** [comment]
any problem?
<pre>return new Phalcon\Flash\Session</pre>
and
<pre>return new \Phalcon\Flash\Session</pre>

**Comment by sergeyklay** [comment]
`flash` or `flashSession` ?

**Comment by sergeyklay** [comment]
Can you please provide output of this sample debug:

```php
// controller
class DevController extends \Phalcon\Mvc\Controller
{
    public function indexAction()
    {
        $this->view->setVar('flash', $this->flash);
    }
}

// view (eg /apps/views/dev/index.phtml)
<?php
function classDump($class) {
    $class = new ReflectionClass($class);
    echo '<code>';
    printf('<h1>%s <span style="color:#a71d5d">class</span> <span style="color:#0086b3">%s</span></h1>'
        , implode(' ', Reflection::getModifierNames($class->getModifiers()))
        , $class->getName()
    );
    echo '<br>';
    foreach ($class->getProperties() as $property) {
        printf('%s',$property->getDocComment());
        printf('<em>%s</em> $%s;<br>'
            , implode(' ', Reflection::getModifierNames($property->getModifiers()))
            , $property->name
        );
    }
    echo '<br>';
    foreach ($class->getMethods() as $method) {
        $params = function() use($method) {
            $ret = [];
            $class = function(ReflectionParameter $param) {
                preg_match('/\[\s\<\w+?>\s([\w]+)/s', $param->__toString(), $matches);
                return isset($matches[1]) ? $matches[1] : null;
            };
            foreach ($method->getParameters() as $i => $param) {
                $type = $param->isArray() ? 'array ' : $class($param);
                $ret[$param->getPosition()] = sprintf('%s$%s', $type, $param->getName());
            }
            return implode(', ', $ret);
        };
        printf('<span style="color:#969896">// Implemented in %s %s</span><br>'
            , implode(' ', Reflection::getModifierNames((new ReflectionClass($method->class))->getModifiers()))
            , $method->class
        );
        printf('<em style="color:#a71d5d">%s</em> <span style="color:#0086b3">%s</span>::%s(%s)<br><br>'
            , implode(' ', Reflection::getModifierNames($method->getModifiers()))
            , $class->getShortName()
            , $method->name
            , $params()
        );
    }
    echo '</code>';
}

// inspect methods
classDump($flash);
```

**Comment by divined** [comment]
<pre>
$config = include __DIR__ . '/config.php';
$di->set('db', function () use ($config) {
            return new \Phalcon\Db\Adapter\Pdo\Mysql(array(
                'host' => $config->database->host,
                'username' => $config->database->username,
                'password' => $config->database->password,
                'dbname' => $config->database->dbname
            ));
        });
</pre>

**Comment by sergeyklay** [comment]
So, ` $this->flash` isn't instance of `Session`, it is instance of `Direct` as you can see

**Comment by sergeyklay** [comment]
Okay, can you try with `true` as a additional param:

```php
$di->set('flash', function(){
            return new Phalcon\Flash\Session(array(
                'error' => 'alert alert-danger',
                'success' => 'alert alert-success',
                'info' => 'alert alert-info'
            ));
}, true);
```

**Comment by divined** [comment]
"has" function still missing

**Comment by divined** [comment]
no changes

**Comment by olivier-monaco** [comment]
Can you run the following command?

<pre>
php -r 'var_dump(method_exists("Phalcon\\Flash\\Session", "has"));'
</pre>

**Comment by divined** [comment]
puck378:/# php -r 'var_dump(method_exists("Phalcon\\Flash\\Session", "has"));'
bool(false)

**Comment by sergeyklay** [comment]
`
php -r 'var_dump(method_exists("Phalcon\Flash\Session", "has"));'
bool(true)
`

**Comment by divined** [comment]
debian reposytary problem?

**Comment by olivier-monaco** [comment]
Method Phalcon\Flash\Session::has exists since Phalcon 1.3.0. So you have an older version.

How did you install Phalcon? Can you give us the ouput of:
<pre>
 php -r 'echo Phalcon\Version::get().PHP_EOL;'
</pre>
This is your version of Phalcon.

**Comment by divined** [comment]
yep

puck378:/# php -r 'echo Phalcon\Version::get().PHP_EOL;'
1.2.3

**Comment by olivier-monaco** [comment]
So you need to update your version of Phalcon.

**Comment by sergeyklay** [comment]
:anguished:
