### ISSUE TITLE
[2.0.0]Sanitize filter is not supported

### ISSUE THREAD

**Issue by Kuzry** [phalcon/cphalcon#3161]
I have the same error like this: https://github.com/phalcon/cphalcon/issues/1018 in Phalcon 2

**Comment by malczak** [comment]
Problem seems to related with Filter not expecting to receive an array of filters in 'sanitize' call and form is always passing an array of filters for each form element.

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.x branch
