### ISSUE TITLE
Function of emulation methods and data

### ISSUE THREAD

**Issue by stanislav-web** [phalcon/cphalcon#3163]
How can I simulate the behavior of the function header and their data on Phalcon?
Zend still have this
```php
$this->request->setMethod('POST')
         ->setPost(array(
             'username'         => 'user123',
             'zip_code'         => '43215',
             'email'            => 'me1@something.com',
             'password'         => 'secret',
             'confirm_pswd'     => 'secret',
           ));
```

**Comment by 7thcubic** [comment]
you could extend the current request. or make a workaround using

$_SERVER["REQUEST_METHOD"]  = "post";
$_POST = array(
             'username'         => 'user123',
             'zip_code'         => '43215',
             'email'            => 'me1@something.com',
             'password'         => 'secret',
             'confirm_pswd'     => 'secret',
           );

**Comment by stanislav-web** [comment]
Yes, thank you! I did so
