### ISSUE TITLE
PDO documentation examples are wrong

### ISSUE THREAD

**Issue by geoidesic** [phalcon/cphalcon#3164]
```
http://docs.phalconphp.com/en/latest/api/Phalcon_Db_Adapter_Pdo.html
```
All of the examples are missing the required third parameter for the 'executePrepared' method. Having examples of the third parameter would be useful so that we can figure out what format is expected in receipt.

**Comment by maxgalbu** [comment]
Please report this to https://github.com/phalcon/docs :)
