### ISSUE TITLE
Phalcon\Forms\Element hasMessages() always returns false

### ISSUE THREAD

**Issue by ckip** [phalcon/cphalcon#3167]
Should these 2 lines of code return the same value ?

1) $form->hasMessagesFor('name');
2) $form->get('name')->hasMessages();

Before validation both these lines return false. But when the form validation fails, the first line returns true (which is good) while the second line still return false.
##

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch. Thanks you
