### ISSUE TITLE
[Phalcon 2] setViewsDir does not add trailing slash

### ISSUE THREAD

**Issue by olivier-monaco** [phalcon/cphalcon#3170]
While porting Phalcon\Mvc\View::setViewsDir to Zephir, the following line was removed:
<pre>
	phalcon_add_trailing_slash(views_dir);
</pre>

So, the following code does not work as before:
<pre>
$view->setViewsDir('views');
</pre>

It must become:
<pre>
$view->setViewsDir('views/');
</pre>

**Comment by andresgutierrez** [comment]
Could you please try again using latest Phalcon 2?
