### ISSUE TITLE
cache/background/xcache decrement has a bug

### ISSUE THREAD

**Issue by luohow** [phalcon/cphalcon#3171]
cache/backend/xcache.c line:493 need change to "xcache_dec",not "xcache_inc"
if (phalcon_function_exists_ex(SS("xcache_inc") TSRMLS_CC) == SUCCESS) {
		PHALCON_RETURN_CALL_FUNCTION("xcache_inc", last_key, *value);
	} else {
		PHALCON_CALL_FUNCTION(&origVal, "xcache_get", last_key);
		sub_function(return_value, origVal, *value TSRMLS_CC);
		PHALCON_CALL_METHOD(NULL, this_ptr, "save", *key_name, return_value);
	}

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2?
