### ISSUE TITLE
Branch 1.3.5

### ISSUE THREAD

**Issue by chinalu** [phalcon/cphalcon#3172]
php_phalcon.h version number is 1.3.4, like this `#define PHP_PHALCON_VERSION "1.3.4"`.
Is it on purpose?

**Comment by dugwood** [comment]
No 1.3.5 release is planned, ever, if I'm not mistaken.

You should try 2.0.0 :-)

**Comment by chinalu** [comment]
Thank you for your reply.

**Comment by sergeyklay** [comment]
Thanks to @dugwood  answer I am today successfully moved my project to 2.x version :)

**Comment by dugwood** [comment]
@sergeyklay note that there are still issues in 2.0.0, but I'm using it for 1 month now, and most of my issues were fixed (either by the phalcon team or by me, thanks to Zephir simplicity!). My project is due in one month, and I am really happy with the stability of Phalcon 2.0.0 so far.

**Comment by sergeyklay** [comment]
@dugwood In any case, everything is fine. Let's see what will happen next :) Thanks!
