### ISSUE TITLE
call Model::findFirst() in php cli sapi, has memory leak 

### ISSUE THREAD

**Issue by ewenlaz** [phalcon/cphalcon#3175]
Test Code:
$i = 0;
while (true) {
    $i ++;
    DemoModel::findFirst($i);
    echo 'Mem:' . memory_get_usage() .PHP_EOL;
    sleep(5);
}

may be Model has cache in DI node, can not Gc it

**Comment by dugwood** [comment]
Already discussed here:
https://github.com/phalcon/cphalcon/issues/2705

What's your phalcon version?

It's not a memory leak: you _want_ all objects to be loaded in memory, so you'll end up eating all your memory.

Try:
```php
$obj = DemoModel::findFirst($i);
unset($obj);
```
