### ISSUE TITLE
Volt defaults don't work

### ISSUE THREAD

**Issue by erickskrauch** [phalcon/cphalcon#3178]
http://forum.phalconphp.com/discussion/4357/volt-macros-default-values
##

**Comment by ErickSkrauch** [comment]
Reproduced on 1.3.4

**Comment by maxgalbu** [comment]
The "optional parameters" feature is not in the code from what i see: 

(1.3.x) https://github.com/phalcon/cphalcon/blob/33e85f551c253ddff58e594e2bace5c2e55f12ef/ext/mvc/view/engine/volt/compiler.c#L2888-L2897
(2.0.0) https://github.com/phalcon/cphalcon/blob/2dea6b4b3a9f5f7bbea14478ed119b9e9dc3c45a/phalcon/mvc/view/engine/volt/compiler.zep#L1972-L1979

you can use the `default` filter as in twig (http://twig.sensiolabs.org/doc/tags/macro.html)

> Default argument values are defined by using the default filter in the macro body;
