### ISSUE TITLE
Volt "is empty"

### ISSUE THREAD

**Issue by ErickSkrauch** [phalcon/cphalcon#3179]
I have this code:

```
{% if options[3] is empty %}
    {% set options[3] = false %}
{% endif %}
```

That must check is there setted [3] key of array (see [this discussion](http://forum.phalconphp.com/discussion/4357/volt-macros-default-values) for information), but it's give me exception:

```
Syntax error, unexpected token [
```

It's mean, that **options[3] is empty** is not valid construction for Volt.

_Phalcon 1.3.2, Windows 8.1, PHP 5.5.0_

**Comment by maxgalbu** [comment]
Does the error refer to the line `{% if options[3] is empty %}` or `{% set options[3] = false %}`?
I know for sure that the second line is not correct (and it's not a bug).

**Comment by andresgutierrez** [comment]
Can you try again using Phalcon 2?

**Comment by dedalozzo** [comment]
I just confirm that this bug doesn't affect Phalcon 2.

**Comment by sergeyklay** [comment]
@dedalozzo Open new issue. Provide script too reproduce and environment vars - OS, PHP version, Server, Phalcon version, etc

**Comment by Jurigag** [comment]
**doesn't**

**Comment by sergeyklay** [comment]
Oh

**Comment by erickskrauch** [comment]
Issue was created 2 years ago... Since it was rewritten on React.js and is no longer required :)

**Comment by dedalozzo** [comment]
It doesn't matter when you have created the issue, I have just reported the bug has been fixed in Phalcon 2. :-)
