### ISSUE TITLE
NFR adding caller / call support to volt template  macros

### ISSUE THREAD

**Issue by jstacoder** [phalcon/cphalcon#3180]
the concept of the macro caller, is very useful in other similar template engines, (jinja2,nunjucks,twig) 

allows for open spaces in macros to add content for example, with bootstraps form-group divs it helps to write the macro like this

``` jinja2
{% macro form_group(label=false) %}
    <div class=form-group>
        {% if label %}<label>{{ label }}</label>{% endif %}
        {{ caller() }}
    </div>
{% endmacro %}
```

then you can call it in the template and fill in the fields 

```
{% for field in form %}
    {% if field.label %}
        {% set label = field.label.text %}
    {% else %}
        {% set label = false %}
     {% endif %}
    {% call form_group(label) %}
        {{ field() }}
    {% endcall %}
{% endfor %}
```
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. Closing, this is implemented. If there are bugs, we can follow up in separate issues .I'll open it again if the need arises
