### ISSUE TITLE
[NFR] Phalcon\Http\Cookie add getName() method

### ISSUE THREAD

**Issue by tmihalik** [phalcon/cphalcon#3189]
It would be nice to be able to get the name of the cookie from the Phalcon\Http\Cookie class (from protected $_name variable)

**Comment by tmihalik** [comment]
Also could you please implement it into 1.3? 
Currently I'm using 1.3.4 but can't code C :(

**Comment by Green-Cat** [comment]
@sergeyklay Implemented in #3194
