### ISSUE TITLE
Developer Tools IDE stubs

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#3190]
Hi!

Please add to `/phalcon-devtools/ide/2.0.0/Phalcon/Http/Request.php`:

```php
		/**
		 * Gets HTTP URI which request has been made
		 *
		 * @return string
		 */
		final public function getURI() {}
```

**Comment by ovr** [comment]
Stubs generated automatically!

**Comment by ovr** [comment]
Lol in `devtools` it was copied from `1.3`
Use `zephir stubs`

**Comment by sergeyklay** [comment]
Tnx. But why with Developer Tools? 2.x stub need fix

**Comment by sergeyklay** [comment]
@ovr 

After generating stubs for 2.0:

`cphalcon/ide/2.0.0b/Phalcon/Exception.zep.php`

```php
<?php

namespace Phalcon;

class Exception extends \\Exception
{

}
```

`\\` -?

**Comment by ovr** [comment]
Yeap I know that `zephir stubs`
have bugs but at all this will be fixed soon

**Comment by sergeyklay** [comment]
Another error after generating stubs for 2.0.0b `cphalcon/ide/2.0.0b/Phalcon/logger/Adapter.zep.php`:

```php
    /**
     * Logs messages to the internal logger. Appends logs to the logger
     *
     * @param var $type 
     * @param var $message 
     * @param var $context 
     * @return \Phalcon\Logger\AdapterInterface 
     */
    public function log($type, $message = null, $context = null) {}
```

var ?

**Comment by sergeyklay** [comment]
Yet another todo.

After generating stubs for 2.0.0b:

`cphalcon/ide/2.0.0b/Phalcon/http/request/File.zep.php`:

```php
	public function getError() {}

	public function getKey() {}

	public function getExtension() {}
```

without any description, `@return`, etc.
