### ISSUE TITLE
Volt Filenames can get too big for Windows

### ISSUE THREAD

**Issue by Rewt0r** [phalcon/cphalcon#3197]
Resulting in no cached files being written

**Comment by 7thcubic** [comment]
I guess md5 what ever phalcon uses right now as name would help

**Comment by niden** [comment]
We can introduce a hash approach to the volt cache names which will solve this issue. However the down side will be that the developer won't be able to see  which cached file is for which template and that will be inconvenient during development.

I am going to mark this as a NFR and we can definitely address it in 2.0

**Comment by niden** [comment]
Closing - Reference #3226
