### ISSUE TITLE
Filter::sanitize with 'int' accepts dashes everywhere in string

### ISSUE THREAD

**Issue by cyrylas** [phalcon/cphalcon#3198]
Sanitize with filter 'int' acepts dashes everywhere in string and produces incorrect integers. Dash should be accepted only at first character.

Examples:
```php
$filter = new Phalcon\Filter();
$filter->sanitize("123-456-789", "int"); // returns "123-456-789" instead of "123456789"
$filter->sanitize("-abc", "int"); // returns "-" instead of empty string
$filter->sanitize("---123--abc", "int"); // returns "---123--" instead of "-123"
```

**Comment by sergeyklay** [comment]
For numeric validation you can use something like this:

```php
public function isNumeric($str)
{
    list($decimal) = array_values(localeconv());

    return (bool) preg_match('/^-?+(?=.*[0-9])[0-9]*+'.preg_quote($decimal).'?+[0-9]*+$/D', (string) $str);
}
```

For filter you can adopt this regexp:

```php
$myFilter = function($string) {
    return preg_replace(your_regexp_here, "", $string);
};
```

**Comment by 7thcubic** [comment]
Perhaps a santize int strict could be made.

Flags like allow_decimal,allow_negative

And just run a filter remove all other instances of +-.

So by default all + gets removed. - is only allowed in the first pos (with flag), all numbers behind any . Is dropped unless with flag keep till the next .

Is what i describe close to what you have in mind?

**Comment by cyrylas** [comment]
I understand now, that Phalcon filters just wrappers PHP's `filter_var()`. It is logical. I'm just not sure now what PHP developers had in mind developing this feature :confused: .
Having strict int/float validation out of box of course would be nice, but I don't think it is top priority now.

Thanks for clarification :)
