### ISSUE TITLE
[Bug] Gettext

### ISSUE THREAD

**Issue by gunesahmet** [phalcon/cphalcon#3199]
When i change locale with tr_TR it given error like this

Warning: Invalid callback Phalcon\DI::getdefault, class 'Phalcon\DI' not found in xxx.php on line xx

Fatal error: Call to undefined function Phalcon\DI::getdefault() in xxx.php on line xx

i remove gettext function from c code error still continue

**Comment by olivier-monaco** [comment]
Which version of Phalcon? Do you have a use case?

**Comment by gunesahmet** [comment]
1.3.4 only Linux versions. Windows working fine.

**Comment by olivier-monaco** [comment]
Can you copy/paste PHP code one lines arround "xxx.php on line xx"?
