### ISSUE TITLE
Missing and/or bad entries in .gitignore

### ISSUE THREAD

**Issue by olivier-monaco** [phalcon/cphalcon#3201]
I've started debugging and modifying Phalcon some weeks ago and I've found a really annoying behavior: compiling Phalcon changes files that are in git repository.

I also see many "bad" lines in .gitignore. For example, the line "build/Makefile" match any file Makefile in a build directory at any depth. If you want to ignore only the Makefile in the build directory at the root of the repository, you need to write "/build/Makefile" (http://git-scm.com/docs/gitignore#_pattern_format).

Reviewing the .gitignore file means also cleanup the repository by removing any temporary file previously commited. I can help but I need info about with file is generated and which one is not.

Can we ignore any file ending with ".zep.c" and ".zep.h"? 
Can we ignore everything in the build directory?

This is the beginning of a new .gitignore file:
<pre>
# IDE specific files
/.settings/
/.idea
/.cproject
/.project

# Generated files
*.zep.c
*.zep.h

# Compilation files
*.o
*.lo
*.la
.libs/
/build/32bits/build/
/build/64bits/build/
/build/safe/build/
/build/build/
/ext/build/

# Logs
*.log
/unit-tests/logs/*

# Temporary files
.DS_Store
*~
</pre>

**Comment by sergeyklay** [comment]
@olivier-monaco  :+1: 
After I have compiled Phalcon, I noticed that `git status` returns a lot of changes.
And before new `git fetch origin && / git rebase` I had to run `git checkout -- /path`.

**Comment by phalcon** [comment]
".zep.c" and ".zep.h" cannot be ignored, because it we don't add them, developers without zephir won't be able to install Phalcon

**Comment by olivier-monaco** [comment]
@phalcon I forgot that point...

Maybe providing archive with C source for download for release (aka 2.0.0) and add zephir as a requirement for development version?

**Comment by olivier-monaco** [comment]
Updated .gitignore:
<pre>
# IDE specific files
/.settings/
/.idea
/.cproject
/.project

# Generated files
/ext/Makefile*
/ext/config*
/ext/acinclude.m4
/ext/aclocal.m4
/ext/autom4te*
/ext/install-sh
/ext/ltmain.sh
/ext/missing
/ext/mkinstalldirs
/ext/run-tests.php
/ext/.deps
/ext/libtool

# Compilation files
*.o
*.lo
*.la
.libs
/build/32bits/build/
/build/64bits/build/
/build/safe/build/
/build/build/
/ext/build/
/ext/modules/

# Logs
*.log
/unit-tests/logs/*

# Temporary files
.DS_Store
*~
/.temp/
</pre>

**Comment by andresgutierrez** [comment]
@olivier-monaco Could you please submit a PR with the new conf?

**Comment by olivier-monaco** [comment]
Are "zep.c" and "zep.h" still required? I've just compiled Phalcon and some (all?) "zep.c" file were modified.

**Comment by andresgutierrez** [comment]
@olivier-monaco yes, they're required

**Comment by KorsaR-ZN** [comment]
:+1: 
I would also like delete files (*.zep.c, *.zep.h) from the main repository and move them to a separate branch readOnly

**Comment by Green-Cat** [comment]
@sergeyklay fixed in #10030 & #10037
