### ISSUE TITLE
Ubuntu x64 14.04 - PHP 5.6

### ISSUE THREAD

**Issue by phillipsnick** [phalcon/cphalcon#3203]
Investigating the possibility of running Phalcon with PHP 5.6 on Ubuntu x64 14.04 using the simple instructions on the download page, unfortunately hasn't turned out to be as simple as I had hoped.

Just to clarify building the extension manually works perfectly well :)

Anyway trying to using the `apt-get install php5-phalcon` method is giving me a slightly odd error, to replicate my issue on Ubuntu I run the following commands

```bash
sudo add-apt-repository ppa:ondrej/php5-5.6
sudo apt-get update
sudo apt-get install php5
```

This leaves me with:

```bash
$ php -v
PHP 5.6.4-1+deb.sury.org~trusty+1 (cli) (built: Dec 21 2014 19:28:16)
```

If I then run the instructions from the download page:

```bash
sudo apt-add-repository ppa:phalcon/stable
sudo apt-get update
sudo apt-get install php5-phalcon
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-phalcon : Depends: phpapi-20121212
                Recommends: php-apc or
                            php5-xcache but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Found one post on the internet regarding `phpapi-20121212` and some users suggested installing php5-common. This didn't resolve the issue.

Is this something which is likely to be supported in the near future?

**Comment by sergeyklay** [comment]
http://forum.phalconphp.com/discussion/4388/phalcon-ppa-install-on-ubuntu-server-14041-lts-fails ?

**Comment by phillipsnick** [comment]
Ah explains it :)

Didn't know there was a forum, cheers :)

**Comment by sergeyklay** [comment]
@andresgutierrez 
1. I think need update PPA. It is important
2. Need add to README.md instructions (or link) — how to install from PPA for Ubuntu without any compilations and building. 

I think this installation way for Ubuntu/Debian will be very popular, hehe
