### ISSUE TITLE
Phalcon\Forms\Element\Select in Mongodb

### ISSUE THREAD

**Issue by duythien** [phalcon/cphalcon#3207]
HI

Maybe this is bug link here

http://forum.phalconphp.com/discussion/4444/render-element-when-database-is-mongodb
http://forum.phalconphp.com/discussion/3068/phalcon-forms-element-select-mongodb

**Comment by andresgutierrez** [comment]
This is fixed in Phalcon 2.0.4 (branch 2.0.x)
