### ISSUE TITLE
Maybe a misuse with Imagick::setCompressionQuality in Phalcon\Image\Adapter\Imagick

### ISSUE THREAD

**Issue by williamgateszhao** [phalcon/cphalcon#3208]
PHP Version 5.6.2
Phalcon Version 1.3.3
imagick module version  3.2.0b2
ImageMagick version 6.8.6-9

When I use Phalcon\Image\Adapter\Imagick, the '$quality' in methods 'save ([unknown $file], [unknown $quality]) ' does not work. What ever I set the $quality, the same file size I get.
But when I do this:

``` php
$srcImage = new Phalcon\Image\Adapter\Imagick ( $fileRealPath );
$testImage = $srcImage->getInternalImInstance ();
$testImage->setImageCompression ( Imagick::COMPRESSION_JPEG );
$testImage->setImageCompressionQuality ( 85 );
$testImage->writeImage( $imagesDir . '/' . $imageId) ;
```

the image file size only half, which is right.

As the php manual says:

```
A note for people who just couldn't get this working..

With PHP 5.1.6, the below works:

<?php
$img->setCompression(Imagick::COMPRESSION_JPEG);
$img->setCompressionQuality(80);
?>

However, with higher versions of PHP (I tried on PHP 5.2.10), the code has no effect (and there are no exceptions or warnings thrown by Imagick as well).

The code that works instead is:

<?php
$img->setImageCompression(Imagick::COMPRESSION_JPEG);
$img->setImageCompressionQuality(80);
?>

and this is backwards compatible (Works on PHP 5.1.6 as well as 5.2.10)
```

I think maybe that's a bug in phalcon ( maybe you can use the setImageCompression instead of setCompressionQuality ) . if I'm wrong, I'm sorry for the misunderstanding.
##

**Comment by olivier-monaco** [comment]
Does $imageId end with jpg or jpeg?

**Comment by williamgateszhao** [comment]
Yes the $imageId ends with 'jpg'.
I found the problem: the method 'save' can only accept  int as $quality, but the doc says ' unknown $quality '(meanwhile the protected method _save only accept int).
When you do this:
```
$image->save ( 'test.jpg', $imageQuality );
```
The $imageQuality may not be a int. As we are using php, it can be anything.
When you do this:
```
$ImageQuality+=0;
$image->save ( 'test.jpg', $imageQuality );
```
The result is right.

I'm not sure it's a php "feature" or a phalcon "bug"?

**Comment by olivier-monaco** [comment]
No processing is done on the provided quality... Can you try the following code (it's your code with a string as quality):
<pre>
$srcImage = new Phalcon\Image\Adapter\Imagick ( $fileRealPath );
$testImage = $srcImage->getInternalImInstance ();
$testImage->setImageCompression ( Imagick::COMPRESSION_JPEG );
$testImage->setImageCompressionQuality ( '85' );
$testImage->writeImage( $imagesDir . '/' . $imageId) ;
</pre>

**Comment by olivier-monaco** [comment]
http://php.net/manual/fr/imagick.setimagecompressionquality.php

<pre>
bool Imagick::setImageCompressionQuality ( int $quality )
</pre>

**Comment by williamgateszhao** [comment]
http://docs.phalconphp.com/en/latest/api/Phalcon_Image_Adapter_Imagick.html
```
protected boolean _save (string $file, int $quality)

public boolean save ([unknown $file], [unknown $quality]) inherited from Phalcon\Image\Adapter
```
My test code:
```
		$testImage = new Phalcon\Image\Adapter\Imagick ( 'imagelib/test.jpg' );
		
		$testImageIM = $testImage->getImage ();
		$testImageIM->setImageFormat ( 'jpeg' );
		$testImageIM->setImageCompression ( Imagick::COMPRESSION_JPEG );
		$testImageIM->setImageCompressionQuality ( '85' );
		$testImageIM->writeImage ( 'imagelib/result1.jpg' );
		
		$testImage->save ( 'imagelib/result2.jpg','85' );
		
		$limit='85';
		$testImage->save ( 'imagelib/result3.jpg',$limit );
		$testImageIM->clear();
		$testImage->__destruct ();
```
result:
```
test.jpg 375.3K
result1.jpg 371.0K
result2.jpg 864.2K
result3.jpg 864.2K
```

At least the doc is wrong, the method 'save' does not accept 'unknown' but only int.
Meanwhile,  Imagick::setImageCompressionQuality does accept string and convert it into an int.

**Comment by maxgalbu** [comment]
You're right, phalcon 2.0 in fact gets the int from the zval with zephir_get_intval():

https://github.com/phalcon/cphalcon/blob/4f81c42c7b94188eaa1edf0e3e296f70ff8af3e8/ext/phalcon/image/adapter/imagick.zep.c#L1369

phalcon 1.3 instead passes a zval directly:

https://github.com/phalcon/cphalcon/blob/33e85f551c253ddff58e594e2bace5c2e55f12ef/ext/image/adapter/imagick.c#L1338

This should be an easy fix
