### ISSUE TITLE
ODM - Setting multiple databases - Not found service

### ISSUE THREAD

**Issue by tmquang6805** [phalcon/cphalcon#3215]
I base on this introduction: http://docs.phalconphp.com/en/latest/reference/odm.html#setting-multiple-databases

And my code
```php
$di = new \Phalcon\DI();

$di->set('collectionManager', function () {
    return new CollectionManager();
});
$di->set('mongo_test', function () {
    $mongo = new MongoClient('mongodb://localhost:27017');
    return $mongo->selectDB('doc_test');
});

$di->set('collection.user', function () use ($di) {
    $coll = new CollectionUser(); // extends from \Phalcon\Mvc\Collection
    $coll->setDI($di);
    $coll->setConnectionService('mongo_test');
    // Ensure DI has service name "mongo_test"
    xdebug_var_dump((string) $coll->getDI()->get('mongo_test'));
    xdebug_var_dump((string) $di->get('mongo_test'));
    return $coll;
});

$a = $di->get('collection.user');
xdebug_var_dump($a->findFirst()->toArray());
exit;
```

But when I run this snippet, I get this error

```
Phalcon\DI\Exception: Service 'mongo_test' was not found in the dependency injection container
```

I used Phalcon version **1.3.4**. Please help me how to fix this issue. Thanks

**Comment by duythien** [comment]
Hi

I have use mutiple database, my service.php

```php
$di->set(
    'mysql',
    function () use ($di) {
        return new Mysql([
            'host'     => $di->get('config')->database->mysql->host,
            'username' => $di->get('config')->database->mysql->username,
            'password' => $di->get('config')->database->mysql->password,
            'dbname'   => $di->get('config')->database->mysql->dbname,
            'schema'   => $di->get('config')->database->mysql->schema,
            'options'  => array(
                \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES ' . $di->get('config')->database->mysql->charset
            )
        ]);
    },
    true // shared
);
$di->set(
    'mongo',
    function () use ($di) {
        $mongo = new \MongoClient();
        return $mongo->selectDb($di->get('config')->database->mongo->dbname);
    },
    true // shared
);

```

Then in Model 

```php
namespace Zphalcon\Models;

class Test extends \Phalcon\Mvc\Collection
{



    public static function returnArrayForSelect($obj)
    {

        return (array)$obj;
    }

    public function initialize()
    {
         $this->setSource('data');
          $this->setConnectionService('mongo');
    }

```

in Controller 

```php
    public function indexAction()
    {
        d(Test::find());
    }
```

Here result 

```php
Array
(
    [0] => Zphalcon\Models\Test Object
        (
            [_id] => MongoId Object
                (
                    [$id] => 54b39909bc0f0aaf7e8b4567
                )

            [_dependencyInjector:protected] => Phalcon\DI\FactoryDefault Object
                (
                    [_services] => Array
                        (
                            [router] => Phalcon\DI\Service Object
                                (
                                    [_name] => router
                                    [_definition] => Closure Object
```

**Comment by duythien** [comment]
Are you sure insatll MongoDb ?

**Comment by tmquang6805** [comment]
1 - I make sure install MongoDB
2 - You should read my question first. In my case, I init multi MongoDB instance not MySQL and MongoDB (you can read the link above)

**Comment by olivier-monaco** [comment]
Can you provide a back trace of this exception?

**Comment by 7thcubic** [comment]
can you name it mongotest instead of mongo_test

Or mongoTest

If i am not wrong it has issues with _

I think i encountered it before too.

**Comment by tmquang6805** [comment]
@7thcubic I try replace **mongo_test** with **mongoTest** but the same error
@olivier-monaco Give you back trace (I run it in PHPUnit)

```
phpunit --group testmultidb
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /path/to/project/module/Core/phpunit.xml

E

Time: 60 ms, Memory: 5.75Mb

There was 1 error:

1) CoreTest\Service\Collection\UserTest::testMultiDBs
Phalcon\DI\Exception: Service 'mongoTest' was not found in the dependency injection container

/path/to/project/module/Core/tests/CoreTest/Service/Collection/UserTest.php:67
/home/quangtm/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:186
/home/quangtm/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:138
                                   
FAILURES!                          
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by olivier-monaco** [comment]
Thanks but it does not seem to be the same code executed as the one you wrote in your first post. Can you run it and give my the back trace, outside phpunit?

**Comment by tmquang6805** [comment]
@olivier-monaco 
That is the same as the first post. I just only replace "mongo_test" by "mongoTest" as @7thcubic said.
And I run this in PHPUnit with separated group (**testmultidb**), so it run independently

**Comment by 7thcubic** [comment]
Service not found means it did not register at all somehow. Question is why. 

Could you try to create the db objects. Two of them. After that do a dump for both. And see if both gets created and if there is any issues. If there isnt and connection is correct. That means the di is not reciving it correctly. 

Also select db command does not return anything right? Does it return bool? Or smth? Cause based on the function and my understanding. That would cause the function to return a bool instead of a db context? 
Would that cause injection issues? Also does injector require the set/get di in order to register it as a service. If so bool isnt really a service object and thus naturally it fails. 

I lack a detail understanding of the 1.3.4 codes. Seeing as it is in zend. But i will look into it in 2.0.0. Again the failing point is either of the above.
