### ISSUE TITLE
[NFR] [Phalcon 2] Add tags management in Redis

### ISSUE THREAD

**Issue by moisemorard** [phalcon/cphalcon#3218]
Hello,

I'm implementing tags management in Redis Backend for Phalcon.
Is this feature has chance to be merged if I make a pull request with this feature and unit tests?
I've already implemented some features for Redis but not merged for now #3214.
However, to implement this feature in Redis Backend, I have to add one arg in save method 

``` php
$frontCache = new \Phalcon\Cache\Frontend\Data(array(
    "lifetime" => 172800
));
//Create the Cache setting redis connection options
$cache = new Phalcon\Cache\Backend\Redis($frontCache, array(
    'host' => '127.0.0.1',
    'port' => 6379,
    'persistent' => true,
    'statsKey' => 'nonli'
));
$cache->save(['key'[, 'value'[,int lifetime[,bool stopBuffer[,array|int|string tags]]]]]));
//I would prefer to change order of args like that :
$cache->save(['key'[, 'value'[,int lifetime[,array|int|string tags[,bool stopBuffer]]]]]));
```

But in this case we have to not implement BackendInterface in Redis class or change save() method of this interface.

What do you think about that ?

Thanx for your return.

Moïse
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

**Comment by fiskolini** [comment]
Why didn't anyone answers to this PR?
What a shame...
