### ISSUE TITLE
Don't exists way to pass parameters from middleware to handler

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#3221]
Hi, 

   I have a micro application for API, I want to authenticate my clients using headers like the public/secret keys pattern. I use a middleware class on before method of application for this process, but does not exists some way to pass dynamically generated parameters over the handler. I tried by setting params defaults on router, but on the method of Collection class do not have any of them.

**Comment by 7thcubic** [comment]
can u store them in session?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by sunchuo** [comment]
>     public function beforeHandleRoute(Event $event, Micro $application)
>     {
>         return true;
>     }
> 
>     public function beforeExecuteRoute(Event $event, Micro $application)
>     {
>         list($loader, $method) = $application->getActiveHandler();
>         $class = $loader->getDefinition();
>         $handler = strtolower($class.':'.$method);
>         $public_handlers = ['account::sendsms', 'account::login'];
>         if (!in_array($handler, $public_handlers)) {
>             $token = $application->request->getPost('token');
>             $user_id = $this->token->getUserId($token);
>             if ($user_id) {
>                 
>                 // here we want pass $user_id to controller or application
>                 
>                 return true;
>             }
>         }
>         return false;
>     }
>     
>     public function call(Micro $application)
>     {
>         return true;
>     }
