### ISSUE TITLE
[Phalcon 2] Issue with debug component and dispatcher

### ISSUE THREAD

**Issue by brainformatik** [phalcon/cphalcon#3223]
There is an issue with active debug component and the dispatcher in phalcon 2. I checked it with a small example app on 1.3.4 and it works.

If I throw an exception in any of my controller actions, the debug view shows me the call stack which ends up in the file phalcon/dispatcher.zep:585.

If everything works fine, it should end up in my own controller/action and show me the line where I throw the exception.

**Comment by ovr** [comment]
:+1:

https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/dispatcher.zep#L585

**Comment by brainformatik** [comment]
I've found a workaround for my issue, but general problem still exists.

```php
$di->set('dispatcher', function () use($di) {

    $eventManager = $di->getShared('eventsManager');

    $eventManager->attach(
        'dispatch:beforeException',
        function($event, $dispatcher, $exception)
        {
            throw $exception;
        }
    );

    $dispatcher = new Dispatcher();
    $dispatcher->setEventsManager($eventManager);
    return $dispatcher;
});
```

In this case exception is rethrown before dispatcher throws it. After this change, debug message ends up in my controller/action and highlights the line where I throw the exception.

**Comment by olivier-monaco** [comment]
@brainformatik Can you try with latest Zephir please?

**Comment by brainformatik** [comment]
Just tried with latest zephir and phalcon version. Still same result.

**Comment by olivier-monaco** [comment]
Please, close this issue.
