### ISSUE TITLE
[NFR] - Add ability to store volt compiled templates with a hash as a name

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#3226]
Ref: #3197 

Volt compiled files can become very long depending on the depth of the folder structure that the web server or developer has. In Windows environments this can exceed the 255 limit and as a result the files are not being saved.

This NFR will introduce a new method to the developer through the volt init options which will allow the hash of the file/folder name will be used to store the file.

``` php
                $volt = new \Phalcon\Mvc\View\Engines\Volt($view, $depInjector);
                $volt->setOptions(
                    [
                        'compiledPath'      => $mypath,
                        'compiledExtension' => '.php',
                        'compiledSeparator' => '%%',
                        'stat'              => true,
                        'compileAlways'     => true,
                        'hashFilenames'     => true,
                    ]
                );
```

The result will be:

_without hash_

```
%%htdocs%%portal%%app%%views%%partials%%browser_check.volt.php
%%htdocs%%fuseos-dev.git%%portal%%app%%views%%partials%%index%%first.volt.php
%%htdocs%%fuseos-dev.git%%portal%%app%%views%%partials%%index%%success.volt.php
%%htdocs%%fuseos-dev.git%%portal%%app%%views%%partials%%orders%%order.volt.php
```

_with hash_

```
56304b4eee74e027cf98fb179e31402e0f7e5454.php
5915972031abb04f8c8dd9c74c54aa9f9206d487.php
6434c145e18657df394536a049911aedbdcee1e9.php
6b786e4bec011971eaf43a7d3c8245c56b406445.php
```

**Comment by phalcon** [comment]
You can currently use a closure to generate this kind of file: 

```php
<?php

$volt->setOptions(array(
    'compiledPath' => function($templatePath) {
        return md5($templatePath) . '.php';
    }
));
```

**Comment by sergeyklay** [comment]
@phalcon :+1:

**Comment by 7thcubic** [comment]
Since we are already on this, can we add another feature? Like niden said hashing it means no one can read the file. Isnt it also possible to just store the cache in relative filenames from the view folder?

Right now i noticed that the filename is generated from realpath.

Or perhaps if there are multiple folders within the view folder, either enable a option to mkdir that folder in the cache folder, providing it is 0777, and store those files exactly the way the view is stored.

So there alternatives beside just a hash, i think on a production standpoint hashing is the good way to go, since no one will debug that.

On the development side of things, as niden said hashing does break the things.

**Comment by Rewt0r** [comment]
Would it not be as simple as doing this *just* for Windows?

http://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath

> To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path".
Note  The maximum path of 32,767 characters is approximate, because the "\\?\" prefix may be expanded to a longer string by the system at run time, and this expansion applies to the total length.

I've never actually tested the repercussions of this though.

**Comment by 7thcubic** [comment]
so far i have no issues with filenames on windows 8, i could make them really long and full of gibberish. and it will still work.

**Comment by Rewt0r** [comment]
I'm using Windows 8.1 and my volt cache path is: C:\Users\Admin\Desktop\Development\Projects\GingerMarkets\InsuranceSystem\App\backend\cache\volt and I have hit the limit.

**Comment by 7thcubic** [comment]
255 charc eh. Yeah which was why i was saying. Isnt just saving view/controller/action.php or view/partial/name.php

Or dir tree makes sense too. So i guess a few new options for volt cache can be added, hash,dir tree,relative path.

**Comment by dschissler** [comment]
The code produces output like this:

```
common%%views%%layouts%%public.volt.php
common%%views%%partials%%head_init.volt.php
common%%views%%simple%%debug_panel%%index.volt.php
common%%views%%simple%%debug_panel%%panels%%config.volt.php
common%%views%%simple%%debug_panel%%panels%%db.volt.php
common%%views%%simple%%debug_panel%%panels%%request.volt.php
common%%views%%simple%%debug_panel%%panels%%server.volt.php
common%%views%%simple%%debug_panel%%panels%%views.volt.php
modules%%web%%views%%index%%index.volt.php
```

Its relative to the phalcon directory.  I like this because I can check out the Volt code if I need to.

```php
$voltService = function($view, $di) {
    $config = $di->get('config');
    $voltCacheDir = $config->path->voltCacheDir;

    switch (ENV) {
        case DIST_ENV:
            $compileAlways = false;
            $stat = false;
            break;
        case DEV_ENV:
            $compileAlways = true;
            $stat = true;
            break;
    }

    $volt = new Volt($view, $di);
    $volt->setOptions([
        'compileAlways' => $compileAlways,
        'stat' => $stat,
        'compiledPath' => function($templatePath) use ($view, $voltCacheDir) {
            $config = $view->getDI()->get('config');
            $phalconDir = $config->path->phalconDir;

            // This makes the phalcon view path into a portable fragment
            $templateFrag = str_replace($phalconDir, '', $templatePath);
            // Allows modules to share the compiled layouts and partials paths
            $templateFrag = preg_replace('/^modules\/[a-z]+\/views\/..\/..\/..\//', '', $templateFrag);

            // Replace '/' with a safe '%%'
            $templateFrag = str_replace('/', '%%', $templateFrag);

            if (strpos($templateFrag, '..') !== false) {
                throw new \Exception('Error: template fragment has ".." in path.');
            }

            $voltCompiledPath = "{$voltCacheDir}{$templateFrag}.php";
            return $voltCompiledPath;
        }
    ]);

    $compiler = $volt->getCompiler();
    require($config->path->phalconDir . '/config/volt_compiler.php');

    return $volt;
};


```
