### ISSUE TITLE
Phalcon\Http\Request::hasFiles() should return a boolean

### ISSUE THREAD

**Issue by blckshrk** [phalcon/cphalcon#3245]
Hi,

In the doc `Phalcon\Http\Request::hasFiles()` returns a `boolean` but in fact the method return an `integer`.

See ya,

**Comment by blckshrk** [comment]
I dont understand why `hasFiles()` should return a long here https://github.com/7thcubic/cphalcon/commit/035e8ba7c7ea6a12047475568ed1396a8f4d490c#diff-ad2ba656fab28448baa767c4b2e59ae9R186.

**Comment by sergeyklay** [comment]
Oops
