### ISSUE TITLE
Phalcon\Mvc\Router does not implement Phalcon\Mvc\RouterInterface

### ISSUE THREAD

**Issue by olivier-monaco** [phalcon/cphalcon#3250]
Phalcon\Mvc\Router does not implement Phalcon\Mvc\RouterInterface. We can't correct it because Router:getDefaults takes an array but RouterInterface::getDefaults don't.

@phalcon Is changing the type of parameter of RouterInterface::getDefaults a problem?

**Comment by ovr** [comment]
I fixed this in https://github.com/phalcon/cphalcon/pull/3262
Can you check and close it?

**Comment by olivier-monaco** [comment]
Great, thanks.
