### ISSUE TITLE
PHALCON_INIT_VAR in 2.0.0

### ISSUE THREAD

**Issue by olivier-monaco** [phalcon/cphalcon#3271]
See:
https://github.com/phalcon/cphalcon/blob/2.0.0/ext/phalcon/annotations/base.c#L82
https://github.com/phalcon/cphalcon/blob/2.0.0/ext/phalcon/annotations/base.c#L374
https://github.com/phalcon/cphalcon/blob/2.0.0/ext/phalcon/annotations/base.c#L410

**Comment by maxgalbu** [comment]
What about it? Should MAKE_STD_ZVAL be used instead?

**Comment by olivier-monaco** [comment]
I think so but not sure. I've planed to dig into but did not find time...

**Comment by olivier-monaco** [comment]
Hum... ext/phalcon/annotations/base.c seems to not be compiled. Introducing some compilation error don't stop compilation.
