### ISSUE TITLE
Phalcon v1.3.x deletes url parameters in some situations (namespace/controller/action/0 results in params==NULL)

### ISSUE THREAD

**Issue by fsando** [phalcon/cphalcon#3274]
$ php -version
PHP 5.5.20-1+deb.sury.org~trusty+1 (cli) (built: Dec 21 2014 19:56:00) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

Tested in Phalcon 1.3.4 and 1.3.5

**Description:**
Consider an action with two optional parameters
```php

public function editAction($var1=null,$var2=null){
   //... 
}

```
**Steps to reproduce:**

1) When passing an url paramter like this:

    /namespace/controller/edit/0

**Expected behavior:**
The expected behavior is that $var1 == 0

**Actual behavior:**
$var1 == null

2) **HOWEVER** when passing two parameters the expected result equals the actual result:

    /namespace/controller/edit/0/0

Expected (and actual) result:
$var1 == 0, $var2 == 0

I also have a thread on the phalcon forum about the issue: http://forum.phalconphp.com/discussion/4554/phalcon-converts-zero-to-null-when-passed-as-last-parameter-in-u

**Comment by 7thcubic** [comment]
actually if u do
/0/ 
it will work too. cause strsplit it will give 1 params

**Comment by fsando** [comment]
@7thcubic
re strsplit, unfortunately I don't know c. I searched all the code of cphalcon (v1.3.5) for "strsplit" but didn't find anything.

**Comment by 7thcubic** [comment]
https://github.com/phalcon/cphalcon/blob/1.3.5/ext/mvc/router.c#L944

**Comment by fsando** [comment]
Thanks for taking so much time.
I don't know c so I don't really know what I'm looking for or what I'm looking at but looking here

https://github.com/phalcon/cphalcon/blob/1.3.5/ext/kernel/string.c#L313

doesn't seem to be an issue assuming that php_explode() behaves like php's explode(). 

Remember that these two urls produce the same result
ns/crtl/act
ns/crtl/act/0

While these two produce different results:
ns/crtl/act
ns/crtl/act/1

Further, if you look at the output of 
router->getMatches()
You'll see that ns/cctrl/act/0 results in the last entry having the string "/0"

exploding either the string "/0" or the string "0" will both produce an array (ther first with two entries the second with one). Php's explode does not behave differently whether the string is "1" or "0".

This strongly suggests to me that it's not about string functions but but much more likely about a boolean operator evaluating the string "0" to false.

The problem culd be related to zend_is_true() above
https://github.com/phalcon/cphalcon/blob/1.3.5/ext/mvc/router.c#L939

Or even this one
https://github.com/phalcon/cphalcon/blob/1.3.5/ext/mvc/router.c#L936
Which leads here
https://github.com/phalcon/cphalcon/blob/1.3.5/ext/kernel/array.c#L71
Which leads to here
https://github.com/phalcon/cphalcon/blob/1.3.5/ext/kernel/hash.c#L89

And here I'm completely lost, I hope that you or someone else can see what issue might be.

**Comment by 7thcubic** [comment]
it is either zend is true or the exploding,

pretty sure if you did 
ns/crtl/act/0/
it would really give you 0

but yeah string operations of int 0, does crap string comparions, but not always. not sure how php handles it but yes, that being said, its really rare for someone to use 0 for a valid id as i said in the discussion =d

**Comment by fsando** [comment]
Thanks for all your effort.

Unfortunately development has apparently stopped on the 1.3.x branch. So I'll make do with my current workaround, swich to v2.0.0 and help ensuring the bug gets fixed there.

**Comment by 7thcubic** [comment]
I wouldnt say 1.3.x has stopped. but more people are focusing on 2.0, phalcon is still maintaining the 1.3.x, 1.3.5 is already created with the fixes. Personally i moved to 2.0 as .c zend was too much messed up for me. I have no experience in zend so the learning curve was higher than zephir.

Good luck on 2.0

**Comment by olivier-monaco** [comment]
Same issue with 2.0.0. This comes from https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/mvc/router.zep#L577

strParams is "0" so using it as a condition mens false...

**Comment by olivier-monaco** [comment]
Fix for 2.0.0 done as a pull request.

For 1.3.5, you can try to change https://github.com/phalcon/cphalcon/blob/1.3.5/ext/mvc/router.c#L939
with something like:

<pre>
if (Z_STRLEN_P(str_params) > 0) {
</pre>

**Comment by emrullahayin** [comment]
help me! #9917

**Comment by andresgutierrez** [comment]
Fixed in Phalcon 2
