### ISSUE TITLE
[2.0] slashes and router with annotations

### ISSUE THREAD

**Issue by quantum13** [phalcon/cphalcon#3275]
(issue for me)
if 
```php
/**
 * @RoutePrefix("/")
 */
```
added in controller and
```php
    /**
     * @Get("/servers")
     */
```
in action this action catches by site.com//servers url (two slashes)

**Comment by 7thcubic** [comment]
$router->removeExtraSlashes(true);?

**Comment by olivier-monaco** [comment]
@quantum13 Still an issue? Can you provide a minimal use case?

**Comment by DanielAdolfsson** [comment]
I think this might be related to the issue I have.  I can't register the index-action (/) using the Route annotation. https://gist.github.com/DanielAdolfsson/689ee2169da564322af6
