### ISSUE TITLE
Phalcon\Http\Request\File IDE stubs

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#3283]
I just divided the previous issue (#3190) in 2, so they can be closed in parts

After generating stubs for 2.0.0b:

`cphalcon/ide/2.0.0b/Phalcon/http/request/File.zep.php`:

```php
	public function getError() {}

	public function getKey() {}

	public function getExtension() {}
```

without any description, `@return`, etc.

**Comment by andresgutierrez** [comment]
Still an issue?

**Comment by sergeyklay** [comment]
yes
