### ISSUE TITLE
PSR-4 in 2.0?

### ISSUE THREAD

**Issue by nathanielks** [phalcon/cphalcon#3290]
Hey all!

Now that PSR-0 [has been deprecated](http://www.php-fig.org/psr/psr-0/), are there any plans to comply with PSR-4? I read [on the forums](http://forum.phalconphp.com/discussion/1405/php-fig-representative) talk about it, but I haven't seen any official documentation.

**Comment by golovanov** [comment]
In Phalcon classloader always used and continue using PSR-4 (even before his appearance) - http://docs.phalconphp.com/en/latest/reference/loader.html#registering-namespaces

If you need PSR-0 you can use classloader from incubator https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Loader/PSR.php

**Comment by iotch** [comment]
Sorry if I missed something, but it's not.

According to [this example] readme (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md), we should be able to register multiple locations:

>       // register the base directories for the namespace prefix
>       $loader->addNamespace('Foo\Bar', '/path/to/packages/foo-bar/src');
>       $loader->addNamespace('Foo\Bar', '/path/to/packages/foo-bar/tests');

However, `Phalcon\Loader` overwrites previous namespace path, if new path uses same key:

```php
$loader = new Phalcon\Loader;
$loader->registerNamespaces(array(
	'Acme' => '/common/path/src/',
	'Acme' => '/local/path/src/'
));
$loader->register();
```
so only `'/local/path/src/'` will be registered.

IMO this behavior should be redesigned in favor of PSR-4's recommendation.

**Comment by naNuke** [comment]
@iotch overwriting key of an array within array itself is something that Phalcon cant change?

**Comment by iotch** [comment]
@naNuke, IMO `Phalcon\Loader` should track both key and value and build two namespaces list entries if keys are same but values are different. Now it uses simple [array_merge] (https://github.com/phalcon/cphalcon/blob/master/phalcon/loader.zep#L113).
