### ISSUE TITLE
[BUG][1.3.4] Pagination + alias on column + having clause ERROR

### ISSUE THREAD

**Issue by Elenthar** [phalcon/cphalcon#3291]
When I use Pagination with Query Builder and use alias on column like in code below, and then try to refer to this alias in HAVING clause i get an error...

Code:
```php
$myModel = new Model();
$query = $myModel->getModelsManager()->createBuilder();
$query->columns( (some_table_alias.int1 * some_table_alias.int2) result);
...
$query->having('result <= 5');
...
$paginator = new Paginator(array(
            "builder" => $query,
	        "limit" => 2,
            "page" => 1
        ));
```

Produces error:
<code>SQLSTATE[42S22]: Column not found: 1054 Unknown column 'result' in 'having clause'</code>

When I execute query manually:
```php
$query->getQuery()->execute();
```
everything is fine and I am getting expected results.

Please help, I need this to work...  Thanks.

**Comment by maxgalbu** [comment]
which version of phalcon?

**Comment by Elenthar** [comment]
1.3.4, windows.

**Comment by olivier-monaco** [comment]
Can you upgrade to 2.0.0 and check if bug exists anymore?

**Comment by Elenthar** [comment]
is there stable dll's available?

**Comment by olivier-monaco** [comment]
Phalcon 2.0 is not stable at the moment. Can you provide a minimal working use case please?

**Comment by Elenthar** [comment]
```php
use Phalcon\DI\FactoryDefault;
use Phalcon\Db\Adapter\Pdo\Mysql as DbAdapter;
use Phalcon\Paginator\Adapter\QueryBuilder as Paginator;
use Phalcon\Mvc\Model;

$di = new FactoryDefault();

$di->set('db', function () {
    return new DbAdapter(array(
        'host' => '127.0.0.1',
        'username' => 'root',
        'password' => '',
        'dbname' => '',
		'dbname' => 'test_db',
		'charset' => 'utf8'
    ));
});

class Test extends Model
{
	public $id;
}

$test = new Test();
$query = $test->getModelsManager()->createBuilder();

$query->addFrom('Test');
$query->columns('(1 * 2) testAlias');
$query->having('testAlias = 2'); //NOT WORKING, returns "Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'testAlias' in 'having clause'"
$query->having('(1 * 2) = 2'); //working

$paginator = new Paginator(array(
	"builder" => $query,
	"page" => 1,
	"limit" => 1
));

$paginator->getPaginate();

```

MySQL table:
<code>
CREATE TABLE Test (
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
</code>

**Comment by olivier-monaco** [comment]
A pagninator needs to first count how many row match your query. To do some, it changes the select clause to do a "count(*)". This statement will returns how many row match your where clause. You can't have aggregation (group by) or post filtering (having) statement in the query you want to paginate.

Why? In 2.0.0, adding a group by to avoid #3318, we have a "better" error:
<pre>
Fatal error: Uncaught exception 'Phalcon\Mvc\Model\Exception' with message 'Column 'testAlias' doesn't belong to any of the selected models (1), when preparing: SELECT COUNT(*) [rowcount] FROM [Test3291] GROUP BY 1 HAVING testAlias = 2' in phalcon/mvc/model/query.zep:279
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#1 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
...
</pre>

The "count" query is:
<pre>
SELECT COUNT(*) [rowcount] FROM [Test3291] GROUP BY 1 HAVING testAlias = 2
</pre>

No more testAlias in select statement...

So this is not a bug.

**Comment by Elenthar** [comment]
ok I get it now, thanks...
