### ISSUE TITLE
Allow instances of \Phalcon\Config in \Phalcon\Mvc\Application::registerModules() and \Phalcon\Mvc\Router::addRoute()

### ISSUE THREAD

**Issue by nurtext** [phalcon/cphalcon#3305]
By allowing instances of _\Phalcon\Config_ we could use Config classes instead of plain php arrays. This would make handling config files much easier. Currently we have multiple config files: One for the main config, one for modules and one for routes. Routes and modules config are actually plain php arrays while main is a Config class.

This happens if you try to use a Config class instead of a plain php array and behaves the same when passing an Config array of routes to the Router class:
```php
// modules.php
return new \Phalcon\Config(array(
    'frontend' => array(
        'className' => '\Frontend\Module',
        'path'      => __DIR__ . '/../apps/frontend/Module.php'
    ),
    'backend' => array(
        'className' => '\Backend\Module',
        'path'      => __DIR__ . '/../apps/backend/Module.php'
    )
));
```

```php
// index.php
$modules = require "modules.php";
$application = new Application($di);
$application->registerModules($modules);
```

__Result__
Exception: Modules must be an Array

**Comment by andresgutierrez** [comment]
You can use:

```php
$application->registerModules($modules->toArray());
```

**Comment by nurtext** [comment]
@andresgutierrez My bad, I completely forgot about this. Thanks very much! :grin:
