### ISSUE TITLE
Add cursor support for aggregation in Phalcon\Mvc\Collection

### ISSUE THREAD

**Issue by tbjers** [phalcon/cphalcon#3307]
Version 1.5.0 and above of the Mongo PECL extension adds support for returning cursors that can then be sorted. See http://php.net/manual/en/mongocollection.aggregatecursor.php for more information.

Would be wonderful if support for `aggregateCursor` could be added to Collection. Mongo recommends using `aggregateCursor` as opposed to passing the `cursor` option to `aggregate` as requested in #2803.

An excellent use case for this would be using `$geoNear` to return a set of locations that can then be sorted based on their distance from the point coordinates by using the distance field in the returned results.

I am not sufficiently well-versed with C these days or I'd attempt a pull request for this. If there's anything I can do to help facilitate this, I'd love to assist!
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
