### ISSUE TITLE
php built-in server routing doesn't work for routes with a dot in them

### ISSUE THREAD

**Issue by Green-Cat** [phalcon/cphalcon#3308]
The php built-in webserver returns a 404 for any route which contains a dot in it, for example http://phalcon.local/version/1.2
I am using the latest version of phalcon and the routing script provided in the documentation (http://docs.phalconphp.com/en/latest/reference/built-in.html).
Also note the script provided in the documentation does not support $_GET variables.
##

**Comment by Green-Cat** [comment]
Does anyone have any ideas of how this could be fixed?

**Comment by pasindud** [comment]
What happens http://phalcon.local/version/1.2 and .2 is taken as a some extension ( check it with only running built  )

**Comment by marcioAlmada** [comment]
I can confirm this behavior is very unexpected for a router.

:+1:
