### ISSUE TITLE
[2.0.0] File::getRealType() returns an empty string

### ISSUE THREAD

**Issue by DanielAdolfsson** [phalcon/cphalcon#3312]
getRealType (of class Phalcon\Http\Request\File) always seem to return an empty string
If I call finfo_* manually (with exactly the same parameters and checks as in the zep file), it works

**Comment by DanielAdolfsson** [comment]
Test case (you just have to download a test.png into current folder): https://gist.github.com/DanielAdolfsson/1ac09cbe5e3541d6fe5c

**Comment by olivier-monaco** [comment]
With latest 2.0.0:
<pre>
$ php test.php
test.png:inode/x-empty
test.png:inode/x-empty
</pre>

So, no problem...

**Comment by DanielAdolfsson** [comment]
Strange, I'm only running a couple of commits behind. I'll check out the latest as well and try again.

**Comment by DanielAdolfsson** [comment]
A recompile with the latest sources seem to have fixed it.
