### ISSUE TITLE
[BUG][2.0.0] Missing lemon rules for many PHQL statements

### ISSUE THREAD

**Issue by olivier-monaco** [phalcon/cphalcon#3318]
Rules in 1.3.4 and 2.0.0 are not the same. As an example, "select ... from ... having ..." is not a valid statement in 2.0.0. The only matching rule is:
<pre>
select_statement(R) ::= select_clause(S) having_clause(H) order_clause(O) select_limit_clause(L) . {
	R = phql_ret_select_statement(S, NULL, O, NULL, H, L);
}
</pre>

But order_clause and select_limit_clause can't be empty.

In 1.3.4 there is only one select_statement but in 2.0.0 there are more than 20!

Why not using rules from 1.3.4?

**Comment by andresgutierrez** [comment]
Route in Phalcon 2 uses a smart and better way to reduce the number of rules in the parser
