### ISSUE TITLE
1.3.4 \Phalcon\Image\Adapter\GD resize() & crop() bug

### ISSUE THREAD

**Issue by DestinyMKas** [phalcon/cphalcon#3322]
$image = new \Phalcon\Image\Adapter\GD('file.jpg');
$image->resize(200, 200)->crop(100, 100);
$image->save('new_file.jpg');

works bad. Picture colors are darkened.

$image = new \Phalcon\Image\Adapter\GD('file.jpg');
$image->resize(200, 200);
$image->save('new_file.jpg');
$image = new \Phalcon\Image\Adapter\GD('new_file.jpg');
$image->crop(100, 100);
$image->save('new_file.jpg');

works good.
Problem is that we cannot do resize and crop on the same object. If we need to do that, we need to resize, save, create new object, crop, save.

**Comment by dreamsxin** [comment]
Imagescale and imagecrop is bug.
```php
$image = imagecreatefromjpeg(__DIR__.'/assets/phalconphp.jpg');

$image1 = imagescale($image, 200, 200);
$image2 = imagecrop($image1, array('x' => 1, 'y' => 1, 'width' => 100, 'height' => 100));

imagejpeg($image2, __DIR__.'/new_file.jpg');
imagedestroy($image);
imagedestroy($image1);
imagedestroy($image2);
```
