### ISSUE TITLE
[2.0.0] php-fpm and \Phalcon\Mvc\Collection::save()

### ISSUE THREAD

**Issue by DanielAdolfsson** [phalcon/cphalcon#3323]
I ran into an issue with __php-fpm__ and __\Phalcon\Mvc\Collection::save()__.
Sometimes it would simply die with a __SIGSEGV__, and I managed to track it down to a static variable __zephir_fcall_cache_entry__ (called "_3" in zim_Phalcon_Mvc_Collection_save). 
The memory location becomes invalid, I guess, after the request. 

There is a macro zephir_nts_static, so this should be simple to reproduce if you have PHP_VERSION_ID < 50600 (< PHP 5.6.0) and ZTS undefined.

After forcing zephir_nts_static to become empty, I have no more problems.

I suspect this issue could affect other things as well.

**Comment by olivier-monaco** [comment]
Can you provide a minimal use case please?

**Comment by andresgutierrez** [comment]
This is fixed in 2.0.1
