### ISSUE TITLE
Is it possible to use MySQL/MariadB Fulltext with PHQL?

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#3325]
I want to use Phalcon PHQL and Fulltext together.  I know about Lucene and I use it as well.  I've read that MySQL 5.6 changed some things and that Fulltext works with PDO now whereas before there were some kinds of issues.  Is it possible that Phalcon can support this?  It really makes my life a lot easier and I'd prefer to use PHQL all of the way through instead of doing raw SQL.

**Comment by phalcon** [comment]
Check this: https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Db#dialectmysqlextended

**Comment by dschissler** [comment]
Yes.  It appears that Phalcon Models and PHQL can use Fulltext searches with Mysql or MariaDB.

I'll reopen this later if there is an issue.  It seems pretty straight forward.

**Comment by dschissler** [comment]
@phalcon I'll probably end up adding a MariaDB dialect to the Incubator for this [feature](https://mariadb.com/kb/en/mariadb/dynamic-columns/).
