### ISSUE TITLE
phalcon.so breaks argument unpacking in internal class constructors

### ISSUE THREAD

**Issue by TomBZombie** [phalcon/cphalcon#3332]
With Phalcon.so enabled in php.ini, this code fails to execute:

```php
$f = ['Foo'];
$reflect = new ReflectionClass(...$f);
$dir = new DirectoryIterator(...$f);
```

Without Phalcon.so enabled, it works as expected.

Strangely, it doesn't break this behaviour:

```php
class Foo {
	public function __construct($x) {
		echo $x;
	}
}

$f = ['Foo'];

$foo = new Foo(...$f);

```

**Comment by maxgalbu** [comment]
Linking the original bug report could help, here's a quote:

> As you already found out, this is caused by a slightly incorrect execute_internal override in https://github.com/phalcon/cphalcon/blob/master/ext/phalcon.c#L50. See http://lxr.php.net/xref/PHP_5_6/Zend/zend_execute.c#1518 for how this should look like, in particular the first argument to the handler in the second branch.

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 (2.0.3)?
