### ISSUE TITLE
Form getData() method

### ISSUE THREAD

**Issue by phillipsnick** [phalcon/cphalcon#3335]
I have added a bunch of elements with filters on to a form and would like to get this data out of the form with the filters applied. 

Have come across https://github.com/phalcon/cphalcon/issues/602 which appears to be exactly the same issue I'm having, mentions this was implemented in 1.2.0 but I can't find any method getData in the source either in version 1.2.0 or the latest version.

Is there any plan to implement such a feature?
##

**Comment by dreamsxin** [comment]
See http://docs.phalconphp.com/en/latest/reference/forms.html#validation

**Comment by phillipsnick** [comment]
Still won't solve my problem, so I have extended the form and added the following method which works with the below example.

```php
abstract Form extends PhalconForm
{
    public function getData()
    {
        $filter = new Filter();
        $data = new \stdClass();

        foreach ($this->getElements() as $element) {
            $elementName = $element->getName();
            $value = $this->getValue($elementName);
            $filters = $element->getFilters();

            if ($filters) {
                foreach ($element->getFilters() as $filterName) {
                    $value = $filter->sanitize($value, $filterName);
                }
            }

            $data->$elementName = $value;
        }

        return $data;
    }
}
```

In use:

```php
public function someAction()
{
    $form = new UserForm();

    if ($this->request->isPost() && $form->isValid($this->request->getPost(), $form)) {
        $data = $form->getData() // stdClass object
    }
}
```

Might be a bit hacky but works perfectly.

**Comment by dreamsxin** [comment]
Like this
```php
$name = new  Phalcon\Forms\Element\Text("name");
$name->setFilters(array('trim', 'int')); // $name->setFilter('trim');
$form->add($name);
```

**Comment by phillipsnick** [comment]
I have something along those lines inside the form. The problem is getting the data from the form filtered without using an entity.

**Comment by dreamsxin** [comment]
Sorry, Now I see what you mean, it's loss `getData` method, May be it's will implementation in 2.0.
