### ISSUE TITLE
Double key entry in array with models in Phalcon 1.3.4

### ISSUE THREAD

**Issue by DasRed** [phalcon/cphalcon#3336]
Try the example code

``` php
<?
class Model extends \Phalcon\Mvc\Model
{

    /**
     * @Column(type="string", length=32, nullable=false)
     *
     * @var string
     */
    protected $name;

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    public function toJsonStruct()
    {
        $data = $this->toArray();
        $result = [
            'name' => 'THIS SHOULD NOT BE IN ARRAY'
        ];

        foreach ($data as $columnName => $value)
        {
            // THIS SHOULD OVERWRITE THE KEY "name" WITH THE VALUE "nuff" BUT IT ADDS A SECOND KEY "name"
            $result[$columnName] = $value;
        }

        return $result;
    }
}
$app = new \Phalcon\Mvc\Micro();

$app->get('/', function () use($app)
{
    $app->getDI()->set('modelsMetadata', function () use($app)
    {
        // create meta data cache
        $modelMetaDataCache = new \Phalcon\Mvc\Model\MetaData\Memory();
        $modelMetaDataCache->setDI($app->getDI());

        // create model meta data strategy
        $modelMetaDataCache->setStrategy(new \Phalcon\Mvc\Model\MetaData\Strategy\Annotations());

        return $modelMetaDataCache;
    }, true);

    $a = new Model();
    $a->setName('nuff');

    echo '<pre>' . var_export($a->toJsonStruct(), true) . '</pre>';
});

$app->handle();
```

The result is

``` php
array (
  'name' => 'THIS SHOULD NOT BE IN ARRAY',
  'name' => 'nuff',
)
```

but it should be

``` php
array (
  'name' => 'nuff',
)
```

System: Win7
PHP 5.6.x nts win32 vc11 x86
Apache 2.4
##

**Comment by maxgalbu** [comment]
In PHP you can't have the same key twice in the array, they must be different in some way. The two keys are probably different, a space or accent will suffice, eg:

```php
array (
  'nàme' => 'THIS SHOULD NOT BE IN ARRAY',
  'name' => 'nuff',
)
```

**Comment by DasRed** [comment]
I know, that the same key can not be twice in the array. But this happends. There is no space or other special (maybe utf8) sign.

Go an try the code example! Then compare both key with strcmp or some mb functions. Both keys are totaly equal

**Comment by maxgalbu** [comment]
Try with array_merge and post the results again

**Comment by DasRed** [comment]
with array_merge the result is the expected result of
```php
array (
  'name' => 'nuff',
)
```

but this is only a workaround not a solution.

**Comment by maxgalbu** [comment]
It's not a workaround, it's actually quicker since it calls a C function to do the merge.

Anyway, the output is correct:

```php
array (
  'name' => 'nuff',
)
```

PHP 5.3, phalcon 1.3.4, centos 6.5

**Comment by DasRed** [comment]
Of course array_merge is faster then using a for-loop. But the code example is just only to reproduce it bug. In the real world happends many more thing in the for-loop, which could not be done by a array_merge.

Okay, if it works for you, what can i do to give you more input to find the bug?

You can see, it happend:
![image](https://cloud.githubusercontent.com/assets/2239808/6347029/e979aa86-bc14-11e4-982d-0be4ab7577fa.png)

**Comment by DasRed** [comment]
hello? Some response?

**Comment by emrullahayin** [comment]
help me! https://github.com/phalcon/cphalcon/issues/9917

**Comment by olivier-monaco** [comment]
I have no access to a box with PHP 5.6 installed so I can't reproduce. What about this code:
<pre>
$result = [
    'name' => 'THIS SHOULD NOT BE IN ARRAY'
];

$data = [ 'name' => 'nuff' ];
foreach ($data as $columnName => $value) {
    $result[$columnName] = $value;
}

var_dump($result);
</pre>

**Comment by DasRed** [comment]
I switched to phalcon 2.0.1. I can try it again with 2.0.1.

**Comment by andresgutierrez** [comment]
@DasRed Could you please try again using Phalcon 2.0.3?

**Comment by dschissler** [comment]
I just ran this with Phalcon 3.2.*, Ubuntu 16.04, PHP 7 and there is not a double key.  Nobody else reported this in 2.5 years.  Close.
