### ISSUE TITLE
cannot upload large pdf file

### ISSUE THREAD

**Issue by jeanthierry** [phalcon/cphalcon#3349]
Hello,
I am working on a small project and trying to master phalcon.
I am trying to upload pdf files.
When the file is not large, the file upload works fine.
but when the file is very large like a pdf book, it doesn't get uploaded to the server.
any suggestions please???????
here is my phalcon codes in the controller

if ($this->request->hasFiles() == true) {
                foreach ($this->request->getUploadedFiles() as $file) {
                    $name = $file->getName();
                    $size = $file->getSize();
                    $type = $file->getType();
                    $path = 'files/' . md5(uniqid(rand(), true)) . '-' . strtolower($file->getName());
                    $file->moveTo($path) ? $isUploaded = true : $isUploaded = false;
                }

**Comment by ErickSkrauch** [comment]
Apache/PHP file size limit?

**Comment by jeanthierry** [comment]
i think so..
Thank you
how can i solve it?
can you help??

**Comment by ErickSkrauch** [comment]
http://stackoverflow.com/questions/2184513/php-change-the-maximum-upload-file-size

It's not Phalcon issue.

**Comment by jeanthierry** [comment]
Thank you ErickSkrauch
