### ISSUE TITLE
[NFR] DBRef support for \Phalcon\Mvc\Collection

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#425]
<a href="http://docs.mongodb.org/manual/applications/database-references/">DBRef</a> is very efficient and direct way to resolve relationships among records of collections instead of querying with foreign key values.

<a href="http://www.php.net/manual/en/book.mongo.php">PHP's mongo driver</a> already has got support for this feature it's name <a href="http://www.php.net/manual/en/class.mongodbref.php/">MongoDBRef class</a>

I think <a href="http://docs.mongodb.org/manual/applications/database-references/">DBRef</a> support can be implemented like following use case:

``` php
class Page extends \Phalcon\Mvc\Collection
{
    public $title;
    public $parent;
    public $childs;
}

$home = new Page();
$home->title = 'Home Page';
$home->save();

$products = new Page();
$products->title = 'Products';
$products->parent = $home;
$products->save();

$branches = new Page();
$branches->title = 'Branches';
$branches->parent = $home;
$branches->save();

$home->childs[] = $products;
$home->childs[] = $branches;
$home->save();
```

Also <a href="http://docs.mongodb.org/manual/applications/database-references/">DBRef</a> can be very helpful traversing records like following use cases:

breadcrumb use case:

``` php
<ul class="breadcrumb">
<?php while ($page = $page->parent): ?>
    <li><?php echo $page->title; ?></li>
<?php endwhile; ?>
</ul>
```

menu use case:

``` php
function build_menu($page) {
    $html = $page->title;

    if (count($page->childs) > 0) {
        $html .= '<ul>';
        foreach ($page->childs as $child) {
            $html .= '<li>' . build_menu($child) . '</li>';
        }
        $html .= '</ul>';
    }

    return $html;
}
```
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
