### ISSUE TITLE
[NFR][FORMS] Everyday usage abilities

### ISSUE THREAD

**Issue by lantian** [phalcon/cphalcon#433]
1) It would be great to order elements in runtime or in creation (entity elements or manually added).

``` php
$form->add($element, $name, $order)
...
$form->setOrder($elementName, $value)
```

2) Functions that can specify form or element attributes, ex.: form|element styles or class html attributes, or radio|checkField values|options

``` php
$form->set[Param|Attrib|Order]($elementName, $[paramName|attribName], $value)
```

Thanks.

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
