### ISSUE TITLE
Array Oriented Programming

### ISSUE THREAD

**Issue by e-oz** [phalcon/cphalcon#460]
In examples I see a lot of Array Oriented Programming anti-pattern cases:

`array(
        "prefix" => 'cache',
        "host" => "localhost",
        "port" => "11211"
    )`

Why not `$obj->setPrefix('cache')->setHost('localhost')->setPort('11211')` ?
In array-style arguments we always should keep in memory whole set of available keys (even trees of keys), which keys are optional and which are required - all in memory, without tips from IDE. It's a bad practice.
##

**Comment by abraaoz** [comment]
@jamm, You can simply create your own objects with setter/getters and implements an interface "ConfigObject" with one method "toArray". So, 
```php
    $config = new DbConfig(); // implements ConfigObject (method "toArray")
    $config->setHost('localhost')->setPort('11211');

    $di['db'] = function() use ($config) {
        return new Db\Adapter\Pdo\Mysql($config->toArray());
    }}
```

**Comment by Jurigag** [comment]
Well i know it's old but i think phalcon is all about speed. And method/function call is heavy operation in php. Each method call will slow down application, not sure if we need this.
