### ISSUE TITLE
[NFR] Implement ViewModels

### ISSUE THREAD

**Issue by nikolasha** [phalcon/cphalcon#476]
In my opinion, Phalcon\Mvc\View is not made very well. This is especially noticeable when there are complex templates with a lot of partials that are nested into each other. In particular, the problem is that all variables are set to View are common to all used templates. Another problem is the inability to create a complex sequence of rendering templates. Here are lacking in something like the Zend\View\Model\ViewModel.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by emansom** [comment]
I think the original poster meant Phalcon to implement something along the likes of [spatie/laravel-view-models](https://github.com/spatie/laravel-view-models).

The rundown of it is that it makes your controller-specific logic for views lighter, think a unique dynamic form that only applies to the form coupled with custom ACL logic; that would make your controller "fat". ViewModels migitate this.
