### ISSUE TITLE
[NFR] Subqueries in PHQL

### ISSUE THREAD

**Issue by hugoduraes** [phalcon/cphalcon#496]
Subqueries aren't still supported in PHQL. It would be nice to be able to do it instead of using raw sql.

**Comment by loopsframework** [comment]
+1 can't use subqueries with Phalcon\Paginator\Adapter\QueryBuilder

**Comment by Wexsel** [comment]
+1

**Comment by tmihalik** [comment]
+1

**Comment by dataclub** [comment]
+1

**Comment by sukobuto** [comment]
+1

**Comment by andrewi-wd** [comment]
+1

**Comment by sergeyklay** [comment]
+1

**Comment by marcosluizss** [comment]
+1

**Comment by sergeyklay** [comment]
@andresgutierrez It seems solved :)

**Comment by andresgutierrez** [comment]
Implemented in 2.0.2

**Comment by coollider** [comment]
Ty

**Comment by someson** [comment]
Subqueries in JOINs too?

**Comment by Jurigag** [comment]
How to solve it in Active Record exactly? I think it's hard or close to not possible to implement this in Active Record pattern, if we will switch to Data Mapper we could think about it.
