### ISSUE TITLE
[NFR] Datetime column type

### ISSUE THREAD

**Issue by SliceOfLife** [phalcon/cphalcon#524]
What about adding "datetime" column type for Model? By default the "@var \Datetime" converted to string.

**Comment by tmihalik** [comment]
+1

**Comment by AndreBaumeier** [comment]
+1

**Comment by loopsframework** [comment]
+1
I would welcome it if Phalcon translates the DateTime object to the format expected by the database backend. With this layer of abstraction, code should become more portable.

**Comment by f3l1x** [comment]
:+1:

**Comment by sergeyklay** [comment]
@niden 
> Closing this as we will not be implementing automatic Datetime fields in Phalcon in the very near future. Perhaps in 2.0+

Now is 2.0+ :)

**Comment by MLukman** [comment]
I vote for this feature implemented about now.

**Comment by reloaded** [comment]
+1

**Comment by efimBistrov** [comment]
+1

**Comment by kornerita** [comment]
Hi,

I've found this thread and I would like to add the following:

- Regarding the performance impact, there is already a ["castOnHydrate"](https://docs.phalconphp.com/en/3.2/db-models#disabling-enabling-features) option to disable if you don't need it or if you want performance (by default it comes disabled).
- For this implementation there should be methods on the [Phalcon\Db\Dialect](https://github.com/phalcon/cphalcon/blob/master/phalcon/db/dialect.zep) to establish the default date format returned by the engine for each date type (i.e. date or timestamp) and methods to transform the result from those to a \DateTime object. Note: I think [here](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L554) is the actual casting.

My personal opinion about this, is that an ORM should abstract you on the date format the database engine is using and should use native language date manipulations. This adds transparency when you want or need to change a database engine.

Regards,
Federico.

**Comment by StudioMaX** [comment]
This is still relevant.

**Comment by niden** [comment]
https://github.com/phalcon/cphalcon/pull/13562
