### ISSUE TITLE
CLI - Better error message

### ISSUE THREAD

**Issue by odiel** [phalcon/cphalcon#534]
Using the CLI application when you call a Task that does not exist i.e.:

php console.php bla

The application return an error, indicating the task can't be loaded.

BlaTask handler class cannot be loaded

this can be self explanatory for now. 

Here is another example:

php console.php --config=/etc/app/conf/main.php

application message: 

-config=/etc/app/conf/main.phpTask handler class cannot be loaded

this sometimes can be hard to understand specially for newbies.
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
