### ISSUE TITLE
[NFR] Phalcon\Db\Adapter\Pdo\Mysql::fetchColumn($name = null) method

### ISSUE THREAD

**Issue by alvassin** [phalcon/cphalcon#566]
Sometimes it is very necessary to get one column result. Could you please add this method to allow to get one column result?

If method is called w/o parameter, first column could be returned, otherwise - specified one.

**Comment by olivier-monaco** [comment]
This is done in Phalcon 2.0.

**Comment by Green-Cat** [comment]
@andresgutierrez This is implemented in 2.0
https://github.com/phalcon/cphalcon/blob/3070344454ba943b5ccc5c91567f71f91da950ae/phalcon/db/adapter.zep#L263

**Comment by andresgutierrez** [comment]
@Green-Cat @olivier-monaco Thanks for pointing it out

**Comment by salarmehr** [comment]
@andresgutierrez  Fetch column is also very useful in PHQL and models. Did it implemented for theme as well?

     $query->where('price>1000')->fetchColumn('type');
