### ISSUE TITLE
[NFR] Modules to ACL

### ISSUE THREAD

**Issue by Swader** [phalcon/cphalcon#582]
Please consider adding `getModuleName()` to Dispatcher. It already has `getControllerName` and `getActionName`, and would be very helpful in custom ACL issues on multi-module applications.

Also consider adding Modules to ACL resources somehow. Right now resources are registered in the form of `$controller => $actionArray`, but there is no way to register a module such that a specific user role (`admin`) has access to a specific module in its entirety (`admin` module, for example).

**Comment by 7thcubic** [comment]
https://github.com/7thcubic/cphalcon/tree/2.0.0_database_module_acl
https://github.com/7thcubic/cphalcon/tree/2.0.0_module_acl

Help me test it and let me know if i missed anything. It seems to be working correctly.

Need some rewrite to make it nicer though imo, open for suggestions.

**Comment by wgalarcon** [comment]
Resources as modules create acl? Help

**Comment by Slyvampy** [comment]
I ended up implementing a Zend Framework approach with the resource array 'module:controller'=> array('method') to get around it.

**Comment by kornerita** [comment]
Hi,

The [\Phalcon\Mvc\ModuleDefinitionInterface](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/moduledefinitioninterface.zep#L40) requires a `registerServices` method to register it's services. 

On my implementation of this I get the acl from the DI and add the Resources, Roles and permissions for the module there. 

i.e.:
Module.php
```php
class Module implements ModuleDefinitionInterface { 

    public function registerServices($dependencyInjector) {
        $acl = $dependencyInjector->get('acl'); /* @var $acl \Phalcon\Acl\AdapterInterface */
        $acl->addRole('module_role');
        $acl->addResource('Module/IndexController', ['index']);
        $acl->allow('module_role', 'Module/IndexController', 'index');
    }

    // ...
```

- This only applies when the module is loaded.
- Each module can register it's own acls and not interfere with other acls (if you use the 'ModuleName/ControllerName' resource approach).

**Comment by niden** [comment]
https://github.com/phalcon/cphalcon/pull/14078
