### ISSUE TITLE
[NFR] Implement method \Phalcon\Forms\Form::__toString()

### ISSUE THREAD

**Issue by lukaszkujawa** [phalcon/cphalcon#618]
It doesn't look like there is an easy way to render an instance of \Phalcon\Forms\Form. From this what I can see in the documentation (http://docs.phalconphp.com/en/latest/reference/forms.html) one has to iterate though all elements. Additionally it's required to add the form tag and handle errors. 

Forms and highly reusable elements on a website so perhaps it would be worth to wrap all that functionality into one method.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
