### ISSUE TITLE
[NFR] Implement Phalcon\Flash\Direct::output() method

### ISSUE THREAD

**Issue by Agent-J** [phalcon/cphalcon#629]
Issue is based on the forum [discussion](http://forum.phalconphp.com/discussion/199/why-doesn-t-phalcon-flash-direct-have-an-output-method-)
Also it shouls be implemented in \Phalcon\FlashInterface

I will close this issue if you don't want implement it because there are some similar closed issues #565 #278 ,
but I think this feature will be useful for output flash messages in the main layout or absolutely any place

**Comment by pisklov** [comment]
+1

**Comment by andresgutierrez** [comment]
This is implemented in 2.0.x (2.0.4).

It requires initialize the flasher with $flash->useImplicitFlush(false);
