### ISSUE TITLE
[NFR] Implement versioning in Assets Manager

### ISSUE THREAD

**Issue by phalcon** [phalcon/cphalcon#639]
Allow collections to set a version to force CDNs to update the collections in the clients

**Comment by akatasonov** [comment]
+1

**Comment by akatasonov** [comment]
+1

**Comment by Jurigag** [comment]
I think not only on collection - just some method like setVersion in `Phalcon\Assets\Manager` class. I will try to implement this for 3.1.0 because this is nice thing to have.

**Comment by wolftankk** [comment]
+1

**Comment by akatasonov** [comment]
+1

**Comment by Jurigag** [comment]
Well would be fine if `setVersion` would accept bool and when it will be true then version will be automitcally got using `filemtime`? Or better just add seperated method like `setAutoVersion` ?

**Comment by ruudboon** [comment]
+1
