### ISSUE TITLE
[NFR] Build package for Linux

### ISSUE THREAD

**Issue by roman-kulish** [phalcon/cphalcon#669]
Guys, are you going to distribute Phalcon as package for Linux? It can simplify set up, grow popularity and cover some enterprise market, cause medium-to-big companies prefer installing software via packages rather then building it themselves.

**Comment by niden** [comment]
Closing this issue since it is no longer relevant.

The Linux packages are located in PackageCloud for various distributions

https://packagecloud.io/phalcon/
