### ISSUE TITLE
[2.0.0] Segfault with annotation parse method with CLI

### ISSUE THREAD

**Issue by SachaMorard** [phalcon/cphalcon#6784]
Hello

I'm using php56 fpm on debian distribution. I found a Segfault problem when annotation reader parse a class, only with CLI (the bug appear with osx with http too)
Parse method crashes when a simple comment (without any docblock syntax) is in the class.

Try to execute this script with PHP CLI and you'll see:
```php
/**
 * Class testclass
 * @Source('db', 'testclass')
 */
class testclass
{
    /**
     * @return string
     */
    public function hello()
    {
        return 'hello';
    }

    /**
     * Method2
     */
    public function hello2()
    {
        return 'hello';
    }
}

$annotations = new \Phalcon\Annotations\Adapter\Memory();
$reader = $annotations->getReader();
$result = $reader->parse('testclass');
var_dump($result);
```
It seems the problem comes from phannot_internal_parse_annotations method in phalcon.c script

Is anyone is abble to fix this issue ?

**Comment by SachaMorard** [comment]
up

**Comment by kjdev** [comment]
I think to be able to run in this patch.
It is is php5.6.6 was confirmed.

```patch
--- a/cphalcon/ext/phalcon/annotations/parser.c
+++ b/cphalcon/ext/phalcon/annotations/parser.c
@@ -1440,7 +1440,7 @@
 
 	if (Z_STRLEN(processed_comment) < 2) {
 		ZVAL_BOOL(*result, 0);
-		efree(Z_STRVAL(processed_comment));
+		str_efree(Z_STRVAL(processed_comment));
 		return SUCCESS;
 	}
 
```

**Comment by SachaMorard** [comment]
Hi
Thank you very much, it's working perfectly ! Could you submit a PR ?

Sacha

**Comment by kjdev** [comment]
I'm going to submit a PR is from sure that no other version (5.5etc).
