### ISSUE TITLE
Yum / RPM repository?

### ISSUE THREAD

**Issue by jasonsocha** [phalcon/cphalcon#6785]
We build a variety of custom apps for Discovery Communications and I would very much like to use Phalcon for a new public project, relatively high-profile.  The sysadmins don't have a problem with using Phalcon, but they very much want to do it through a package manager, so they can easily update, get notified when security releases come out, etc. etc.  These are pretty reasonable desires, IMO.  This particular unit deploys CentOS, so a yum repo would be needed.

Phalcon provides a PPA for Ubuntu / apt-get, but does not provide a yum repo for Red Hat flavors.  Why not?  What would it take to get one?  I'd even be willing to sponsor a reasonable amount if the Phalcon team could provide repos for Red Hat flavors as well as Ubuntu.

**Comment by skonealone** [comment]
hi,

I have created a RPM package for CentOS 6.5, you can download it from my github.
https://github.com/skonealone

Thanks,
-SK

**Comment by dschissler** [comment]
Rejoice.  Starting with Phalcon 3.0 packages are being created by Packageloud.io for many Linux distros: https://forum.phalconphp.com/discussion/13265/phalcon-on-packagecloudio

**Comment by dschissler** [comment]
@sergeyklay Can we close this issue now?  If someone requests a new distro it can be made as a fresh issue.
