### ISSUE TITLE
[2.0.0] Mvc/Model: Decimal and null fileds cause '0' values in unrelated columns

### ISSUE THREAD

**Issue by meteoblue** [phalcon/cphalcon#6788]
Hello,

I recently upgraded my development system from 1.3.4 to newest 2.0.0. One mvc/model (mysql) now overwrites certain columns to '0' while creating.
I reduced the table structure and code to a minimum. If I change the order of columns the issue does not appear. It requires a null-able, a decimal and a varchar/text/char column.
If decimal is set, the char column will store '0' in the database instead of 'test'.

Could someone try to reproduce this issue? Thanks!

Regards,
Patrick

```SQL
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `null_field` int(1) DEFAULT NULL, 
  `decimal` decimal(2,1) NOT NULL,
  `char` char(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
```

```PHP
class Test extends \Phalcon\Mvc\Model { }

$t = new Test();
$t->decimal = 3; // has to be set
$t->char = 'test';
$t->save(); // 'char' is stored as '0' in DB, but local scope is still 'test'
$t->refresh(); // after reload, 'char' is now '0'

if($t->char != 'test') { 
    echo 'BUG';
} else {
    echo 'OK';
}
```

**Comment by olivier-monaco** [comment]
See #3247. I think it's related. Can you use the latest 2.0.0?

**Comment by olivier-monaco** [comment]
Oups... wrong issue... I'll take a look...

**Comment by olivier-monaco** [comment]
Problem comes from Phalcon\Db\Adapter::insert method. Use this code:
<pre>
$values = [null, 3, 'test'];
$fields = ['null_field', 'decimal', 'char'];
$types = [1024, 32, 2];
$cnx->insert('test2', $values, $fields, $types);
</pre>

And the bindDataTypes passed to the execute method will be: [1024, 32, 2, 32, 2]...

**Comment by olivier-monaco** [comment]
Please try with latest 2.0.0.

**Comment by meteoblue** [comment]
Works! Thanks!
