### ISSUE TITLE
[NFR] Namespace-related views paths

### ISSUE THREAD

**Issue by hesalx** [phalcon/cphalcon#692]
What about to implement namespace-related views paths?
I mean the implementation in the core level, because it could be done by dynamic call of view->pick() but it would be really slower and not pretty at all =)

It would be great to have such structure:
/views/name/space/my_controller/my_action.phtml
/views/layouts/name/space/my_controller.phtml
/views/partials/part.phtml
/views/index.phtml
1. Single general index.phtml (main layer)
2. Shared partials.
3. Separated controllers/actions views.
4. Separated layouts.
##

**Comment by nsossonko** [comment]
This functionality would definitely be appreciated in our environment. We namespace our controllers for organization and proper hierarchical structure but the view module doesn't recognize namespaces, so our views folder has to be "un-namespaced".

**Comment by tugrul** [comment]
I have done using @arantir 's way.

Plugin:
```php
namespace App\Website\Plugins;

class CustomRenderer extends \Phalcon\Mvc\User\Plugin
{
    public function beforeExecuteRoute($event, $dispatcher)
    {
        $defaultNamespace = $dispatcher->getDefaultNamespace();
        $namespace = $dispatcher->getNamespaceName();
        
        if (strpos($namespace, $defaultNamespace) === 0) {
            $namespace = substr($namespace, strlen($defaultNamespace));
        }

        $parts   = array_filter(explode('\\', $namespace));
        $parts[] = $dispatcher->getControllerName();
        $parts[] = $dispatcher->getActionName();

        $this->view->pick(implode(DIRECTORY_SEPARATOR, $parts));
    }
}
```

Binding:
```php
$di->set('dispatcher', function() use ($di) {
            $eventsManager = $di->getShared('eventsManager');
            $eventsManager->attach('dispatch', new CustomRenderer()); 

            $dispatcher = new Dispatcher();
            $dispatcher->setEventsManager($eventsManager);
            $dispatcher->setDefaultNamespace('App\Website\Controllers'); 
            return $dispatcher;
        }); 
```

**Comment by challet** [comment]
@trugrul There is an (it seems undocumented) [application:viewRender](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L336) event that might be closer to what you want. In case many dispatches happend before one render, as when  _$dispatcher->forward_ is called.
The plugin is great, with one tiny downside : the "default namespace" is also becoming the "root namespace".
