### ISSUE TITLE
storing and updating mysql "now()"  in same object 

### ISSUE THREAD

**Issue by cullsin** [phalcon/cphalcon#7710]
Hi, 

I am doing the following, but the field return "now()" instead of datetime after saving the record. 

$obj = new Model();
$obj->created_on = new Phalcon\Db\RawValue('now()');

$obj->save(); // which returns id .

Againg I am doing update in the same object . I hope it will be an update since 
id exists ( Primary key ) 

$obj->update_on = new Phalcon\Db\RawValue('now()');
$obj->save();

What it does, it updates both $obj->created_on,$obj->updated_on with "now()". 

Is this is the expected behaviour ?

Raja K

**Comment by kowach** [comment]
That is expected behavior of object. 
You create object, add variable1. Save() - insert/update row in a table.
You add new variable2, but old variable1 is still there. 
Try remove first variable unset($obj->created_on);

**Comment by andresgutierrez** [comment]
This is the expected behavior, you have to obtain the value again from the database or call $obj->refresh() to refresh the object.
