### ISSUE TITLE
[NFR] Implement afterInitialize event in dispatching loop

### ISSUE THREAD

**Issue by Agent-J** [phalcon/cphalcon#782]
This issue is a continuation of this https://github.com/phalcon/cphalcon/issues/703

For now events priority looks like this:
- SomeListener::beforeExecuteRoute
- Controller::beforeExecuteRoute
- Controller::initialize
- Controller::afterExecuteRoute

With ACL check now it's perfect: beforeExecuteRoute performs ACL check, so controller will not be initialized if user not authenticated.

In some cases we need to perform some operations after controller was initialized but before executing action.

My current case is parse CLI options to set controller params.

Of course I can call like this
```php
	public function initialize()
	{
		// register all I need
		// ...

		$eventsManager->fire("dispatch:afterInitialize", $this, $extraData);
	}
```
but core implementation would be more usable

**Comment by Green-Cat** [comment]
@andresgutierrez Implemented in #984. Also present in 2.0 https://github.com/phalcon/cphalcon/blob/3070344454ba943b5ccc5c91567f71f91da950ae/phalcon/dispatcher.zep#L496
