### ISSUE TITLE
[NFR] WebServices support

### ISSUE THREAD

**Issue by arturgspb** [phalcon/cphalcon#815]
The new feature can be used to improve the design of the application as a whole to properly separate the core of the application from the customers. The interface in this case is client of core api.
## Example implementaion

Implementaion in Controllers as annotations like this:

``` php
<?php
/**
 * @WebService(‘UserService’)
 * @RoutePrefix("/api/UserService")
 */
class UserController extends \Phalcon\Mvc\Controller {

    /**
     * @return User a concrete user
     */
    public function getOne() {
        return User::findOne();
    }

    /**
     * @param UserFilter $userFiler filter for querying
     * @return User[]
     */
    public function getMany(UserFilter $userFiler) {
        return User::find( /* convert $userFilter to parameter */ );
    }

    /**
     * @param int $x same number
     * @return int
     */
    public function calcSomething($x) {
        return ($x + 1);
    }

    /**
     * @param string $text any documentation
     * @return string
     */
    public function quote($text) {
        return '"'.$text.'"';
    }
}
```

And as service in DI like as modelsMetadata for chaching methods list and thier in and out params:

``` php
$di->set('webservicesMetadata', function () {
    $metaData = new Phalcon\Mvc\Model\MetaData\Memory();
    return $metaData;
});
```

And in config if have in api no primitive types:

``` php
$conf =  new \Phalcon\Config(array(
    'webServicesTypesColumnMap' => array(
        '\User' => function($user) {
            $user[‘fullname’] = $user[‘name’].’ ’.$user[‘surname’]; 
            return $user;
        }
    )
));
```
## Generation WSDL

When user call UserService from example http://example.com/api/UserService?wsdl, Phalcon generated wsdl schema for webservice (http://www.w3.org/TR/wsdl20/)
### Primitive Types

When declaring class methods and properties to be remotely accessible, we need to specify the data types of the input and output parameters. The following primitive data types can be used:
- str/string: maps to xsd:string;
- int/integer: maps to xsd:int;
- float/double: maps to xsd:float;
- bool/boolean: maps to xsd:boolean;
- date: maps to xsd:date;
- time: maps to xsd:time;
- datetime: maps to xsd:dateTime;
- array: maps to xsd:string;
- object: maps to xsd:struct;
- mixed: maps to xsd:anyType.
### User types

User type convert rules will be get from webServicesTypesColumnMap from config and do not parse realtime. In xml user type should be represented as:

``` xml
<xsd:complexType name="User">
        <xsd:element name="id" type="xsd:long" />
        <xsd:element name="name" type="xsd:string" />
                        ...
</xsd:complexType>
```
## Using in clients

``` php
$client = new SoapClient('http://example.com/api/UserService?wsdl');
$user = $client->getOne();
```

For example yii implementation: http://www.yiiframework.com/doc/guide/1.1/en/topics.webservice
##

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
