### ISSUE TITLE
[BUG] Missing a method onUncaughtLowSeverity in Phalcon\Debug

### ISSUE THREAD

**Issue by tema87** [phalcon/cphalcon#835]
```php
$debug = new \Phalcon\Debug();
$debug->listen(true, true);
```
an error:
> Warning: set_exception_handler() expects the argument (Phalcon\Debug::onUncaughtLowSeverity) to be a valid callback in ...

And why "set_exception_handler"? Maybe "set_error_handler"?

1.2.1

**Comment by Green-Cat** [comment]
The method still doesn't exist in 2.0.
https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/debug.zep#L110

**Comment by andresgutierrez** [comment]
Fixed in 2.0.x
