### ISSUE TITLE
[NFR] [DISCUSS] Faster way to call native functions/methods

### ISSUE THREAD

**Issue by ghost** [phalcon/cphalcon#856]
This idea has been overseen in the PHP5 MongoDB extension.

Call a known PHP internal function (it must be exported by the extension):

```c
zend_vm_stack_push(arg1 TSRMLS_CC);
zend_vm_stack_push(arg2 TSRMLS_CC);
zend_vm_stack_push((void*)number_of_arguments TSRMLS_CC);
ZEND_FN(function)(number_of_arguments, return_value, NULL /* return_value_ptr_ptr */, NULL /* this_ptr */, 1 /* return_value_used */ TSRMLS_CC);
zend_vm_stack_pop(TSRMLS_C);
zend_vm_stack_pop(TSRMLS_C);
zend_vm_stack_pop(TSRMLS_C);
```

It gets more complicated if the function is not exported:
```c
zend_function *function_handler;
if (zend_hash_find(EG(function_table), "lowercased_name", strlen("lowercased_name")+1, (void**)&function_handler) == SUCCESS) {
    if (function_handler->type == ZEND_INTERNAL_FUNCTION) {
        zend_vm_stack_push(arg1 TSRMLS_CC);
        zend_vm_stack_push(arg2 TSRMLS_CC);
        zend_vm_stack_push((void*)number_of_arguments TSRMLS_CC);
        function_handler->internal_function.handler(number_of_arguments, return_value, NULL /* return_value_ptr_ptr */, NULL /* this_ptr */, 1 /* return_value_used */ TSRMLS_CC);
        zend_vm_stack_pop(TSRMLS_C);
        zend_vm_stack_pop(TSRMLS_C);
        zend_vm_stack_pop(TSRMLS_C);
    }
    else {
        /* fall back to the slow path */
    }
}
else {
    /* the function does not exist */
}
```

Same can be used to call static methods (this_ptr will be null) or parent methods (s/ZEND_FN/ZEND_MN/, pass this_ptr and if the arguments are the same, they can probably be reused — need to check).

With methods, inheritance and access scope it gets even more complicated and therefore it probably makes sense to call this way only own methods that are known to exist, ie:

This:
```c
object_init_ex(exception, phalcon_cli_dispatcher_exception_ce);
phalcon_call_method_p2_noret(exception, "__construct", message, exception_code);
```

can be turned into this:
```c
zval dummy_return_value;
object_init_ex(exception, phalcon_cli_dispatcher_exception_ce);

zend_vm_stack_push(message TSRMLS_CC);
zend_vm_stack_push(exception_code TSRMLS_CC);
zend_vm_stack_push((void*)2 TSRMLS_CC);
ZEND_MN("Phalcon_Cli_Dispatcher_Exception", "__construct")(2, &dummy_return_value, NULL, exception, 0 TSRMLS_CC);
zend_vm_stack_pop(TSRMLS_C);
zend_vm_stack_pop(TSRMLS_C);
zend_vm_stack_pop(TSRMLS_C);
```

or this:
```c
phalcon_call_method(return_value, this_ptr, "gethandlername");
```

can be turned into this:
```c
if (Z_OBJCE_P(this_ptr) == phalcon_cli_dispatcher_ce) {
    /* Same class, go the faster way */
    zend_vm_stack_push((void*)0 TSRMLS_CC);
    ZEND_MN("Phalcon_Cli_Dispatcher", "getHandlerName")(0, return_value, NULL, this_ptr, 1 TSRMLS_CC);
    zend_vm_stack_pop(TSRMLS_C);
}
else {
    /* Inheritance, go the traditional way */
    phalcon_call_method(return_value, this_ptr, "gethandlername");
}
```

Of course, all these details should be hidden under the hood (macros, helpers etc).

Advantages:
  * very very fast: the only overhead is to push the arguments onto/pop them from the stack (in case of a function — look it up in the function table). Basically this is the native C call

Disadvantages:
  * the called function should not use implicitly or explicitly debug_backtrace() or throw exceptions. Well, nothing wrong happens if it does, but this way of calling functions does not create a stack frame in ZE and the backtrace will won't show that function.

Where this in my opinion can be useful:
  * Phalcon\Crypt: the less overhead, the better;
  * methods which are used very frequently and call other internal methods (Model, Volt Compiler are the first ones that come to mind);

How can many classes benefit from this: there are 16 classes that use Phalcon\Events\Manager and at least 30 classes that use Phalcon\DI.

With DI they typically use getShared() or get() methods, with EM — fire().

These classes typically implement Phalcon\Events\EventsAwareInterface and Pahlcon\Di\InjectionAwareInterface; moreover, they share the same implementation of getDI() and getEventsManager() method.

Step 1 is to create helper functions:

```c
void phalcon_helper_getdi(zval* return_value, zval* this_ptr, zend_class_entry* my_class TSRMLS_DC)
{
    zval* return_value;

    if (Z_OBJCE_P(this_ptr) == my_class) {
        RETURN_MEMBER(this_ptr, "_dependencyInjector");
    }
    else {
        phalcon_call_method(this_ptr, "getdi");
    }
}

/* likewise for phalcon_helper_getem */
```

BTW, none of the classes implementing InjectionAwareInterface call getDI; they read _dependencyInjector property instead; if someone wants to inherit from those classes and override getDI method. we will see interesting errors if the derived class won't use _dependencyInjector property; I think this is a bug.

Step 2 is to create helper for DI::getShared() and EM::fire():

```c
void phalcon_helper_di_getshared(zval* return_value, zval* di, zval* service TSRMLS_DC)
{
    if (Z_OBJCE_P(di) == phalcon_di_ce) {
        zend_vm_stack_push(service TSRMLS_CC);
        zend_vm_stack_push((void*)1 TSRMLS_CC);
        ZEND_MN("Phalcon_DI", "getShared")(1, return_value, NULL, di, 1 TSRMLS_CC);
        zend_vm_stack_pop(TSRMLS_C);
        zend_vm_stack_pop(TSRMLS_C);
    }
    else {
        phalcon_call_method_p1(return_value, di, "getshared", name);
    }
}

/* likewise for EM::fire() */
```

What do you think?

**Comment by andresgutierrez** [comment]
This has been implemented in Zephir
