### ISSUE TITLE
[NFR] Phalcon\Db\Profiler\Item::getSqlStatement()

### ISSUE THREAD

**Issue by Makedo** [phalcon/cphalcon#867]
I used an object of Phalcon\Mvc\Model\Criteria in some Action to get data from database like this: 

``` PHP
        $criteria = Criteria::fromInput(
            $this->di, 
            'Translates', 
            ['id' => 1, 'key' => 'key']
        );
        $criteria->setModelName('Translates');
        $data = $criteria->execute();
```

Than, to see queries to database I used Phalcon\Db\Profiler::getLastProfile() which returns an object of Phalcon\Db\Profiler\Item. Then I used method getSQLStatement() of  Phalcon\Db\Profiler\Item, which returns me a string with executed query. But in this string there are no values of binding parameters in WHERE condition, like this:

``` SQL
SELECT `translates`.`id`, `translates`.`key`, `translates`.`value` FROM `translates` WHERE `translates`.`id` = :id AND `translates`.`key` = :key.
```

I think, it will be better, if method getSQLStatement() of  Phalcon\Db\Profiler\Item returns a query string with values of binding parameters, for example, like this:

``` SQL
SELECT `translates`.`id`, `translates`.`key`, `translates`.`value` FROM `translates` WHERE `translates`.`id` = 1 AND `translates`.`key` = 'key'.
```
##

**Comment by sergeyklay** [comment]
Close in favor of #12196
