### ISSUE TITLE
[NFR] Make assets manager recompile files only if needed

### ISSUE THREAD

**Issue by Swader** [phalcon/cphalcon#925]
Currently, the assets manager recompiles all the added assets on every request. This might get inefficient with a lot of resources.

I suggest the following approach which I've personally been using for a while now in my own asset manager:

Request 1:
Read filemtime of all files.
Generate hash from all these times.
Append hash to output file name.
Check if file already exists. It doesn't.
Compress and minify, serve file.

Request 2 (if no files have changed):
Read filemtime of all files.
Generate hash from times, append to output file name.
Check if file exists. It does - no recompile needed.
Output existing file.

Request 2 (some changes were done - either new file added, or file changed):
Read filemtime of all files.
Append times hash to output file.
Check if file exists - it doesn't because hash is different.
Recompile and serve file.

Aside from eliminating overhead from recompiling on every request, this also has the side benefit of making sure your clients ALWAYS have the most up to date JS and CSS loaded, because when changes occur the file name is different and cannot be stuck in the browser's cache.
##

**Comment by system4nl** [comment]
+1

**Comment by lubberscorrado** [comment]
+1

**Comment by Graphmatic** [comment]
+1

**Comment by mzf** [comment]
good idea +1

**Comment by Swader** [comment]
For the interested, I've additionally implemented outside of Phalcon waters at [nofw](https://github.com/swader/nofw) - just a combo of the Robo task runner, Mini-asset for compiling, and that's about it.

**Comment by fenixphp** [comment]
+1

**Comment by FaimMedia** [comment]
I agree (partially) with this setup, however I think a better solution would be to get the highest filemtime from all sources, append this to 'cache' file and check from there. Hashing would be less efficient and (personally) I find a url with a timestamp cleaner then a hash.

**Comment by sergeyklay** [comment]
Closing in favor of https://github.com/phalcon/cphalcon/issues/1756
