### ISSUE TITLE
[1.3.5] Alias fails for referenced table of same name

### ISSUE THREAD

**Issue by skintagain** [phalcon/cphalcon#9903]
When using namespacing for models, you are forced to use an alias for relationships e.g.

```
class Letter {
 public function initialize()  {
    $this->belongsTo('userId', \Foo\Bar\User, 'id',  ['alias' => 'User'] );
    }
}
```
If that alias (User) matches the name of the referenced class (User), the magic setter for userId never gets called.  e.g.:

```
Letter = new Letter();
Letter ->User = User::findFirst() ;
Letter->Save(); //results in a userId is required failure
```

However if you change the alias name (so it differs from the referenced class name) the setter gets called correctly.

**Comment by andresgutierrez** [comment]
Try removing the leading \ in:

```php
$this->belongsTo('userId', 'Foo\Bar\User', 'id',  ['alias' => 'User'] );
```

**Comment by skintagain** [comment]
Sorry that was a mistake i'm using 
```
$this->belongsTo('userId', Foo\Bar\User, 'id',  ['alias' => 'User'] );
```

**Comment by dreamsxin** [comment]
The second param type must be string.

**Comment by olivier-monaco** [comment]
Still an issue?
