### ISSUE TITLE
How to get Parameters in view in phtml template

### ISSUE THREAD

**Issue by vinaysikarwar** [phalcon/cphalcon#9905]
Hi,

I have one query, but i did not find a way to solve that in google.

Can you help me in getting clear with my doubts.

*I am using phtml engine, I am adding a functionality of reset pasword, with swift mailer. Every thing works fine, but i am not getting a way how to get parameter value in my reset.phtml file.*

Mail.php I am setting the template like

```php
$parameters = array_merge(array(
			'publicUrl' => $this->config->application->publicUrl,
		), $params);
		
		return $this->view->getRender('emailTemplates', $name, $parameters, function($view){
			$view->setRenderLevel(View::LEVEL_LAYOUT);
		});
		return $view->getContent();
```

Now I want to get the parameters in my reset.phtml file.
I have used this echo $this->view->publicUrl.

Thanks
Waiting for the reply

**Comment by dreamsxin** [comment]
```php
    return $this->view->getRender('emailTemplates', $name, array('parameters' => $parameters), function($view){
        $view->setRenderLevel(View::LEVEL_LAYOUT);
    });
```

**Comment by andresgutierrez** [comment]
Just access the variable down there in any view:

```php
<?php echo $publicUrl; ?>
```
