### ISSUE TITLE
config.ini - Parameter value got broken with the character "!"

### ISSUE THREAD

**Issue by cullsin** [phalcon/cphalcon#9910]
Hi, 

I have set the db password in the config.ini like ( starting with '!' ) which interpret 
to "1"  and throws the access denied error from the database.

password = !23edas

Is the character is the syntax ? If so, How do I give exclamations ??

Raja K

**Comment by kowach** [comment]
Add quotes:
password = "!23edas"

**Comment by lgomezma** [comment]
I had the same problem and the quotes solved it!

Thanks a lot :)
