### ISSUE TITLE
Multi Insert With ModelCache 

### ISSUE THREAD

**Issue by love4php** [phalcon/cphalcon#9931]
When i Use "modelsCache"; Save Method insert multi row in Table;
```php

$di->set('modelsCache', function() {
				$frontCache = new \Phalcon\Cache\Frontend\Data(array(
						"lifetime" => 86400
				));			
				$cache = new \Phalcon\Cache\Backend\File($frontCache, array(
						"cacheDir" => APPLICATION_PATH."/Cache/"
				));

				return $cache;
			});

```
Insert Data :
```php
$payment = new \Model\Payment();
$payment->save(array(
              var1=> val1,
              var2 => rand(),

));
```
Resutl : 
```
----------------------
     var1   |   var2  
----------------------
      val1  |   15624
      val1  |    5635
      val1  |    6532
```
but When, disable "modelsCache",   is working

Result

```
----------------------
     var1   |   var2  
----------------------
      val1  |   865
```

How do I make this code work correctly?

sorry for my bad english

**Comment by dreamsxin** [comment]
上面的两个结果没看出什么问题。Phalcon 什么版本？

**Comment by love4php** [comment]
With ModelCache : With each call (save method) three times saved in database ,
but without modelcache :  With each call , one row insert in to database,

version : 1.3.4

**Comment by olivier-monaco** [comment]
Can you provide a full usecase? (Model class, create table statement...)

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
