### ISSUE TITLE
About changes in phalcon 1.3.x sources

### ISSUE THREAD

**Issue by Sweet-Bob** [phalcon/cphalcon#9935]
Hi, i try add new function, but don't understand, why it working on macos, but on ubuntu it calls segmentation fault?

router.c (and added declaration in header):
``` c
PHP_METHOD(Phalcon_Mvc_Router, getPrefix) {
	zval *route, *router_prefix = NULL;
	PHALCON_MM_GROW();
	PHALCON_CALL_METHOD(&route, this_ptr, "getmatchedroute");
	PHALCON_CALL_METHOD(&router_prefix, route, "getprefix");
	RETURN_CTOR(router_prefix);
}
```

Thanx for any help.

**Comment by phalcon** [comment]
Try initialising route to null:

```c
zval *route = NULL, *router_prefix = NULL;
```

**Comment by Sweet-Bob** [comment]
Thank you. Now i rebuild, and run it, but segm still remain.

Whether ubuntu has special properties what can call problem (what need consider in development)?

**Comment by dreamsxin** [comment]
Try generating a backtrace:
```shell
ulimit -c unlimited
./configure CFLAGS="-O0 -g3 -Wall"
make && make install
```
Run you code
```shell
gdb $(which php) core
bt
```

**Comment by Sweet-Bob** [comment]
Thank you, all work fine.
