### ISSUE TITLE
Process fails with incorrect mysql login

### ISSUE THREAD

**Issue by luksol** [phalcon/cphalcon#9936]
I have put the wrong mysql credentials in, the user was not authorized to connect to the database from this host and process failed without any error message the moment it tried to run the query or when I tried to do $di->get('db')

I couldn't find any errors in nginx or php logs, and dmesg also wasn't helpful (some segfault there but not related to this issue)

code snippet:

$di->set('db', function(){
	return new \Phalcon\Db\Adapter\Pdo\Mysql(array(
		"host" => "localhost",
		"username" => "user",
		"password" => "pass",
		"dbname" => "database"
	));
 });

echo "Step 1"; // this is being displayed
$di->get('db');
echo "Step 2"; // this is not being displayed

I am not sure what more information would you need? Let me know if you need anything else.

Phalcon: 1.3.4
PHP: 5.6.6
Nginx: 1.6.2

EDIT: software version

**Comment by dreamsxin** [comment]
You can test in CLI:
```shell
php you.php
```
if has coredump,
```shell
ulimit -c unlimited
php you.php
gdb $(which php) core
```

**Comment by andresgutierrez** [comment]
Could you try again using Phalcon 2?
