### ISSUE TITLE
 Call to undefined function Phalcon\CLI\Dispatcher::gethandlername()

### ISSUE THREAD

**Issue by joao-pinheiro** [phalcon/cphalcon#9937]
It seems there is a missing internal method (gethandlername) in https://github.com/phalcon/cphalcon/blob/1.3.4/ext/cli/dispatcher.c#L248 when accessing \Phalcon\CLI\Dispatcher::getTaskClass()

**Comment by andresgutierrez** [comment]
This is fixed in 1.3.5
