### ISSUE TITLE
Phalcon micro router silently ignores named params 

### ISSUE THREAD

**Issue by ethankaminski** [phalcon/cphalcon#9942]
While trying to use named parameters with `\Phalcon\Mvc\Micro` for, I discovered that certain parameter names are *silently* ignored. What seems to be going on is that Router keywords (such as "namespace" or "controller") are ignored, without any warning.

The expected behaviour for me is that either all route params are used and available, or some sort of error or warning is raised.

Interestingly, the route still matches, but the parameters are unavailable.

If `$micro` is an instance of \Phalcon\Mvc\Micro, and that the DI has been initialized with `FactoryDefault`, the following route and callback demonstrate the issue:

```
// send a GET request to "{$host}/app/item"
$micro->get("/{namespace:(app|public)}/item", function($namespace) use ($micro) {
    // both of these var_dumps will be empty.
    // I'd expect them to both include "app" or "public", OR for a PHP error/exception to be raised.
    var_dump($micro->router->getParams());
    var_dump($namespace); // the issue still occurs with func_get_args(), of course
});
```

Tested with Phalcon 1.3.4 and PHP 5.4.

**Comment by andresgutierrez** [comment]
namespace, controller, action and module are reserved variable names, can you try using a different name?
