### ISSUE TITLE
Transactions and Virtual Foreign Key is conflict

### ISSUE THREAD

**Issue by piavgh** [phalcon/cphalcon#9944]
Hi everyone,

I have 2 models: DeliveryRequest and RequestLocation

In DeliveryRequest, I have this relation:

```php
$this->hasMany("id", "\Models\RequestLocation", "requestId", array(
            "foreignKey" => array(
                'action' => Relation::ACTION_CASCADE,
                "message" => "The requestId cannot be deleted because other request location are using it"
            )
        ));
```

In RequestLocation, I have this relation:

```php
$this->belongsTo("requestId", "\Models\DeliveryRequest", "id", array(
            "foreignKey" => array(
                "message" => "The requestId does not exist on the DeliveryRequest model"
            )
        ));
```

In my logic, I need to create a DeliveryRequest object first, to get the requestId, and then create a RequestLocation object, to use that requestId as a foreign key.

What actually happened is if I use transactions, I will get the TxFailed exception "The requestId does not exist on the DeliveryRequest model", because I know at that time, the DeliveryRequest object is not created yet.

What I expected to get is the DeliveryRequest object is saved, then I can get requestId for the RequestLocation, but if any thing wrong happen, the transaction must still work.

I use Ubuntu 14.04 LTS, PHP 5.5.9 and Phalcon 1.3.4, Nginx web server and MariaDB database

How to solve this conflict? Thank you very much

**Comment by dreamsxin** [comment]
Please put test code, Is your problem again.
