### ISSUE TITLE
Phalcon 1.3.4, iis7.5 php5.6 issue.

### ISSUE THREAD

**Issue by BonnieDoug** [phalcon/cphalcon#9945]
Have recently upgraded my vps to php5.6 have downloaded the nts x86 5.6 dll and what not. Yet I can't get my site to load. I keep getting an IndexController cannot be found error. I still have PHP 5.5.11 installed and switching back to that fixes everything. Have tried just about every combination of base url etc but to no avail.

Seems strange that it works fine under 5.5 but breaks under 5.6. Any suggestions would be greatly appreciated. 

Also worth noting, it works perfectly fine on my local machine running IIS8.5, PHP5.6, x86 and Phalcon 1.3.4

___
EDIT

After a bit of fiddling around I've now got a different error message of "A dependency injection object is required to access internal services".

**Comment by andresgutierrez** [comment]
Could you please provide the relevant code to reproduce the issue?

**Comment by BonnieDoug** [comment]
No need now, updated to 2.0 and it's working flawlessly. Was my entire project that produced the error though.
