### ISSUE TITLE
Validation doc typo

### ISSUE THREAD

**Issue by andreroggeri** [phalcon/cphalcon#9950]
The session where explains how to create your own validator has a typo:

`class UrlValidator extends \Phalcon\Mvc\Collection\Validator`

Should be

`class UrlValidator extends \Phalcon\Mvc\Model\Validator`

**Edit:**
URL: http://docs.phalconphp.com/en/latest/reference/odm.html

**Comment by andresgutierrez** [comment]
I can't see the error you're referencing in that page, could you please elaborate?

**Comment by andreroggeri** [comment]
```
class UrlValidator extends \Phalcon\Mvc\Collection\Validator {
	public function validate($model) {
		$field = $this->getOption ( 'field' );
		
		$value = $model->$field;
		$filtered = filter_var ( $value, FILTER_VALIDATE_URL );
		if (! $filtered) {
			$this->appendMessage ( "The URL is invalid", $field, "UrlValidator" );
			return false;
		}
		return true;
	}
}

$validator = new \Piv\Backend\Plugins\UrlValidator(['field'=> 'test']);
```

Throws me **Fatal error: Class 'Phalcon\Mvc\Collection\Validator' not found.**

Whereas extending `\Phalcon\Mvc\Model\Validator` works as expected.

**Comment by andresgutierrez** [comment]
Could you please submit this fix to this repo? https://github.com/phalcon/docs
