### ISSUE TITLE
Resultset Filter by value

### ISSUE THREAD

**Issue by cullsin** [phalcon/cphalcon#9954]
Hi, 

I am trying to get the value through Phalcon resultset filter. 

  $result = $params['resultset']->filter(function($object)  {
                         if ($object->$params['key'] == $params['value'] ) { print $params['key']; return $object; }
   });

  Can you suggest me how do I pass the $params inside the filter function. Am I doing correct ? 

  Raja K

**Comment by andresgutierrez** [comment]
Github is only intented to report bugs or discuss new features, you can get better help in the forum: http://forum.phalconphp.com/

**Comment by cullsin** [comment]
sure, Thanks. Sorry about that
