### ISSUE TITLE
PostgreSQL Uniqueness validator show out of memory error

### ISSUE THREAD

**Issue by yrssoft** [phalcon/cphalcon#9955]
Fatal error: Allowed memory size of 536870912 bytes exhausted at /home/yrssoft/tmp/php-5.6.5/Zend/zend_execute.h:187 (tried to allocate 130968 bytes) in /common/models/User.php on line 77

the code near line 77 :

        $this->validation(new Uniqueness([
            'filed' => 'username',
            'message' => '此用户名已被使用'
        ]));

        $this->validation(new Uniqueness([
            'filed' => 'email',
            'message' => '此邮箱已被使用'
        ]));

How to fix this?

**Comment by dreamsxin** [comment]
What version phalcon and php?

**Comment by yrssoft** [comment]
i was
