### ISSUE TITLE
Phalcon and PHP 7 (perfomance).

### ISSUE THREAD

**Issue by billionaire** [phalcon/cphalcon#9956]
Hello.
With release of PHP 7 (now php-ng) all the classic PHP frameworks will work faster by optimizing of PHP.
Tell me please whether this same acceleration of projects written in Phalcon, after switching to PHP 7?
Thank you.
Kind regards.

**Comment by andresgutierrez** [comment]
Phalcon is not an accelerator for PHP or projects written in PHP. Phalcon is a framework that implements its functionality using a low-level language that is C, exporting this functionality as classes and methods that can be used from PHP, the opportunities we are pursuing are:

* Take advantage of native compilation: which means produce a binary executable representation of the code that a processor can directly understand without the overhead of running bytecode in a VM
* Reduced memory footprint by using optimised specific-purpose C structures and static types
* C compilers like GCC/CLANG/VCC can perform several optimisations over the C code
* Opportunities to place variables and data in the stack. These data have typically higher locality of access
* Branch prediction  is easier as it operates directly over the user code and not over the VM implementation
* Have direct access to internal structures and functions reducing the computation overhead

Phalcon relies on several internal design aspects of PHP such as memory management, garbage collection and its internal structures. The improvement of any of these aspects have a positive impact on Phalcon's performance as well in PHP.

**Comment by ovr** [comment]
@andresgutierrez 
I think we need to create FAQ document...
