### ISSUE TITLE
[2.0.0] Phalcon\Di\Exception: Service 'eventsManager' cannot be resolved for existing service

### ISSUE THREAD

**Issue by arius86** [phalcon/cphalcon#9963]
Part of dump from my DI:
````
[
//...
 'eventsManager' =>
    class Phalcon\Di\Service#5924 (5) {
      protected $_name =>
      string(13) "eventsManager"
      protected $_definition =>
      string(21) "Phalcon\Events\Manage"
      protected $_shared =>
      bool(true)
      protected $_resolved =>
      bool(false)
      protected $_sharedInstance =>
      NULL
    }
//...
]
````

Error when calling:

````
$eventsManager = $this->di->getShared('eventsManager');
````

**Comment by andresgutierrez** [comment]
Can you please try again?

**Comment by arius86** [comment]
Still the same.

**Comment by andresgutierrez** [comment]
I think we need more information to reproduce the issue, DI tests are passing in Travis and the forum and the website is running with Phalcon 2. Could you please share a repository with the code to reproduce the problem?

**Comment by arius86** [comment]
Code: https://github.com/arius86/core/tree/v2.0
Travis CI log for current build: http://archive.travis-ci.org/jobs/57795446/log.txt (search for string
"Phalcon\Di\Exception: Service 'eventsManager' cannot be resolved")

**Comment by olivier-monaco** [comment]
Can you create a small use case?

**Comment by olivier-monaco** [comment]
I think I've found your problem. There's a missing r in constructor of Phalcon\DI\DefaultFactory\Cli for the event manager class name.

**Comment by arius86** [comment]
Hah that was unexcpected :)

**Comment by olivier-monaco** [comment]
Please check with latest 2.0.0.
