### ISSUE TITLE
"Segfault" when using "call_user_func()" in Volt-teplate

### ISSUE THREAD

**Issue by Ra1almaty** [phalcon/cphalcon#9964]
Hello.

I get a "segfault" error and "502 Bad Gateway", when I use call_user_func or call_user_func_array methods in a template, although it works correctly somewhere else, for instance in the method of a controller.

How can I handle it?

I tried to make all stuff in the ->addFunction() and then pass a result to the view, but in my case I need to pass an array to a function from the template: {{ include_component('controller', 'method', ['param1' : value, 'param2': value2]) }}

It doesn't pass the values (value1,2) it passes only the variable names to handle them in the resulting template. So, that is not a case.

here is a simplest example to get a 'segfault'

```php
$compiler->addFunction('include_component', function ($resolvedArgs, $exprArgs) {
    $result = 'call_user_func("ucfirst","sss")';

    return $result;
});
```
try to pass $result = 'ucfirst("sss")' - it will work nice

PHP  version 5.4.33

**Comment by andresgutierrez** [comment]
Are you using xdebug?
