### ISSUE TITLE
[2.0] 'Phalcon\Image\Exception' with message 'width and height must be specified'

### ISSUE THREAD

**Issue by kniaz-tolya** [phalcon/cphalcon#9965]
the problem arises when I do:
$image->resize($this->width);
82 when viewed from the line. there clearly is a check if one of the fields is not set then throw an exception in 1.3.5 of this was not:
It turns out now by default const TENSILE = 7;

I understand now always need to ask
$image->resize($this->width,null,2); Where 2 is - Image::WIDTH

**Comment by andresgutierrez** [comment]
Can you please try again using Phalcon 2.0.5?
