### ISSUE TITLE
how stop php code execute in volt engine?

### ISSUE THREAD

**Issue by lixiphp** [phalcon/cphalcon#9966]
Hi, how to protect the volt engine doesn't compile <?php or <? and end with ?>.

some hacker can inject php code in the volt engine, such as exec(), system(), phpinfo() and other php code.

I want to know how to stop volt engine to compile php template engine in it?

Thanks your time.

**Comment by dschissler** [comment]
This issue is related to #2292.  Volt needs better escaping.
