### ISSUE TITLE
[2.0] Phalcon\Config\Adapter\Php::_merge, cannot access private method Phalcon\Config\Adapter\Php::_merge()

### ISSUE THREAD

**Issue by Kachit** [phalcon/cphalcon#9967]
Invalid callback Phalcon\Config\Adapter\Php::_merge, cannot access private method Phalcon\Config\Adapter\Php::_merge()

**Comment by andresgutierrez** [comment]
Can you try again using latest commit?

**Comment by Kachit** [comment]
I am using php_phalcon.dll from your website ((

**Comment by andresgutierrez** [comment]
ok, then please install Phalcon 1.3.4 until new DLLs will be available
