### ISSUE TITLE
Phalcon Http Response, decoupling and PSR-7

### ISSUE THREAD

**Issue by vicaba** [phalcon/cphalcon#9969]
Phalcon HTTP Response is coupled to the running server. When you call the send() method, Phalcon sends it internally to the client and if you call the getContent() method, it only returns the rendered view, not the HTTP headers, there is no way to get the raw string with the HTTP headers + the rendered content. I propose decoupling responses from the server, so a call to some method should return the entire response HTTP headers + rendered content as a string. I propose to use PSR-7 as a standard too.

I'm solving this problem using Symphony responses :S

``` php
    /**
     * @var Symfony\Component\HttpFoundation\Response
     */
    protected $response;

    protected function response() {

        $phalconResponse = new Phalcon\Http\Response;

        $phalconResponse->setContent($this->response->send());

        return $phalconResponse;

    }
```

**Comment by Atriedes** [comment]
:+1:

**Comment by sergeyklay** [comment]
+1 for PSR-7

**Comment by mbrzuchalski** [comment]
:+1:
