### ISSUE TITLE
Phalcon Http Request, decoupling

### ISSUE THREAD

**Issue by vicaba** [phalcon/cphalcon#9970]
Phalcon Http Request doesn't work when it is used with a PHP server (like React or Ratchet), calling methods on a Phalcon Request return empty values. Symphony request provides a createFromGlobalsMethod(), filling the request with PHP superglobals. I propose to create a similar method in Phalcon Response.
Edit (2015/05/23): Possible related problem: Calling Phalcon\Mvc\Router()::setHttpMethods(), as no HTTP methods are retrieved from the request, specifying HTTP methods in a route object invalidates this route.

**Comment by Atriedes** [comment]
:+1: that is good idea

**Comment by Jurigag** [comment]
Related - https://github.com/phalcon/cphalcon/issues/11789 i would close this and leave psr-7 i think.
