### ISSUE TITLE
[2.0.0] Phalcon\Config\Ini error The argument is not initialized or iterable()

### ISSUE THREAD

**Issue by Kachit** [phalcon/cphalcon#9973]
Config example: https://github.com/Kachit/phalcon-lib/blob/master/tests/stubs/configs/config.ini
If I change file content to:
[data]
name = Foo

Config adapter works correct

**Comment by andresgutierrez** [comment]
This is fixed in the 2.0.x branch (Phalcon 2.0.4(

**Comment by mikkiek** [comment]
Pretty similar issue with \Phalcon\Config and it's not fixed in the 2.0.4

example:

class Base extends \Phalcon\Config{
        public function __construct($arrayConfig = null, array $options = []){
            parent::__construct($arrayConfig);
        }
}

result:
The argument is not initialized or iterable() (0)
phalcon/config.zep:62

**Comment by andresgutierrez** [comment]
@mikkiek Could you please try again using 2.0.7?

**Comment by mikkiek** [comment]
@andresgutierrez 
Hello, 2.0.7 have the same problem:

error:
The argument is not initialized or iterable() (0)
phalcon/config.zep:62
