### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#9975]
Hi !

Can you please update composer version for 2.x.x version?

> For every tag that looks like a version, a package version of that tag will be created. It should match 'X.Y.Z' or 'vX.Y.Z', with an optional suffix of -patch (-p), -alpha (-a), -beta (-b) or -RC. The suffixes can also be followed by a number.

Current version `2.0.0r` broke  installation for incubator dev-master. See phalcon/incubator#293

**Comment by andresgutierrez** [comment]
I've changed the version to fix the problem, thanks
