### ISSUE TITLE
[2.0] \Phalcon\Mvc\ModuleDefinitionInterface implements problem

### ISSUE THREAD

**Issue by Riu** [phalcon/cphalcon#9981]
I want create multi-modules app. I have:

```php
class Module implements \Phalcon\Mvc\ModuleDefinitionInterface 
```
in 1.3.4 for properly operation my methods are:

```php
public function registerAutoloaders($di) {} // where $di can be 'NULL'
public function registerServices($di) {}
```

In 2.0.0 for properly operation I need do some changes:

```php
public function registerAutoloaders(\Phalcon\DiInterface $di = NULL) {}
public function registerServices(\Phalcon\DiInterface $di) {}
```

It is expected and correct?

**Comment by andresgutierrez** [comment]
Yes, it's the expected, now parameters expect interfaces compliance

**Comment by ovr** [comment]
Suggest to patch it on Phalcon `1.3.5`

**Comment by Riu** [comment]
Thank you for your help:)

**Comment by ovr** [comment]
@andresgutierrez 
> Suggest to patch it on Phalcon 1.4.0 for BC
